### ISSUE TITLE
Flow: I want customers to be able to add products from a specific category to their cart in a post/page

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce-gutenberg-products-block#10]
Current prototype: https://automattic.invisionapp.com/share/P4FL7W6VDT8#/screens/276308942_01e
Select `Product category` in scope selector.

Sketch: https://www.dropbox.com/s/dvp2x1poq1yukes/Add%20Products%20Block.sketch?dl=0

**Comment by claudiulodro** [comment]
Category select doesn't seem to be linked in the invision prototype link above, so here it is: https://automattic.invisionapp.com/share/P4FL7W6VDT8#/screens/276308929
