### ISSUE TITLE
Automatically assign a reviewer for PRs from external contributors

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#10000]
## Is your feature request related to a problem? Please describe.

Currently, when an external contributor creates an issue or a PR, we assign the label `type: community contribution`. The corresponding GitHub Actions are defined in https://github.com/woocommerce/woocommerce-blocks/blob/e9a9bda9d2b7622a8cd3af3d5b631d5ffd12cbca/.github/workflows/community-contributor.yml#L32-L36 and https://github.com/woocommerce/woocommerce-blocks/blob/e9a9bda9d2b7622a8cd3af3d5b631d5ffd12cbca/.github/workflows/scripts/is-community-contributor.js#L47-L67

However, we do not assign a reviewer to PRs that have been created by an external contributor. If the porter or another team member does not manually assign a reviewer, that PR might fall through the cracks and will not be reviewed. This can create a negative impression for external contributors.

## Describe the solution you'd like

When an external contributor creates a PR, we should not only assign the label `type: community contribution`, but also assign a reviewer to the PR. It might be tricky to find out which team (Rubik, Kirigami, or Origami) is responsible for reviewing the corresponding PR. Therefore, we should assign both @woocommerce/rubik and @woocommerce/woo-fse as reviewers to the PR. That way, we ensure that external contributions get reviewed in time.

## Describe alternatives you've considered

In https://github.com/woocommerce/woocommerce-blocks/issues/10000#issuecomment-1609439830, @roykho referred to https://github.com/woocommerce/woocommerce/blob/trunk/.github/workflows/community-label.yml#L43, a GitHub Action within the WooCommerce core which is using [shufo/auto-assign-reviewer-by-files](https://github.com/shufo/auto-assign-reviewer-by-files).

**Comment by roykho** [comment]
An alternative is to assign the team based on files. Woo core does this as well seen here https://github.com/woocommerce/woocommerce/blob/trunk/.github/workflows/community-label.yml#L43

**Comment by nielslange** [comment]
> An alternative is to assign the team based on files. Woo core does this as well seen here https://github.com/woocommerce/woocommerce/blob/trunk/.github/workflows/community-label.yml#L43

Thanks for pointing this out, @roykho. I've updated the initial issue description based on your comment.

**Comment by mikejolley** [comment]
Closing due to pca54o-6Dz-p2
