### ISSUE TITLE
Top Rated Products: Columns setting not working on Safari

### ISSUE THREAD

**Issue by carinapilar** [woocommerce/woocommerce-gutenberg-products-block#1001]
#### Steps to reproduce
1. Create a new page on a site with a Woo store
2. Add the Top Rated Products block on it
3. Set the block with 3 columns and 1 row
4. Publish the page

#### What I expected
The block to show 3 products in one row, as it does in Chrome:

![Chrome](https://user-images.githubusercontent.com/16104522/65824020-4cbc5380-e237-11e9-8b5f-4fc3c97b2fc7.png)

#### What happened instead
Safari breaks the row in 2:

![Safari](https://user-images.githubusercontent.com/16104522/65824031-6c537c00-e237-11e9-8f60-3d59a6d35b94.png)

#### Browser / OS version
OS X 10.13.6
Safari/605.1.15
Chrome/77.0.3865.90

#### Context / Source
#user-report

**Comment by Aljullu** [comment]
Thanks for opening this issue @carinapilar. I just tested it and it's working fine for me. Could you tell us which version of WooCommerce Blocks are you using (if it's lower than 2.4.2, I recommend you to update) and which theme is your site using?

That will help us diagnose what's going on. Thank you in advance!

**Comment by carinapilar** [comment]
> Could you tell us which version of WooCommerce Blocks are you using (if it's lower than 2.4.2, I recommend you to update) and which theme is your site using?

Sure! Thanks for looking @Aljullu! Both my test site and the user's site are:

- Using the Storefront theme
- Atomic sites on WordPress.com
- Using WooCommerce Version 3.7.0
- Using Gutenberg Version 6.2.0
- WooCommerce Blocks isn't installed on any of them

My test site is here: https://woo.mytestsite.blog/

**Comment by Aljullu** [comment]
Thanks for the details @carinapilar!

It looks like this is a bug in Storefront. I created and issue there and will prepare a fix soon:

https://github.com/woocommerce/storefront/issues/1212
