### ISSUE TITLE
Prselewy24 (p24)

### ISSUE THREAD

**Issue by DraBard** [woocommerce/woocommerce-gutenberg-products-block#10011]
## Describe the bug

Please fix the block-based checkout incompatibility for Przelewy24 (P24)

## To reproduce

Trying to hook the Przelewy24 (P24) payment method. The method does not display in the checkout.

## Expected behavior

Should display on checkout

## Screenshots

![image](https://github.com/woocommerce/woocommerce-blocks/assets/43968173/ecf1895e-d7c4-47b4-b1e0-e0d4cac95df8)

**Comment by wavvves** [comment]
Hi @Bard2803, thank you for creating the issue but sadly we cannot do this on our side, payment integration with block-based checkout must be done by the extension maintainers.
You can reach out to them, link this issue and point them towards our [guide for payment integration](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/checkout-payment-methods/payment-method-integration.md).

If they have any doubts about the implementation, we are happy to help 👍🏼 

I'm closing this issue on our repo.
