### ISSUE TITLE
get_taxable_address in cart doesn't return complete address

### ISSUE THREAD

**Issue by rahulv-dev** [woocommerce/woocommerce-gutenberg-products-block#10015]
## Is your feature request related to a problem? Please describe.
Currently the "get_taxable_address" method only returns "country", "state", "postcode" and "city". It would be great if this could return "Address_line1" and "Address_line2" as well so that the caller has complete address for further usage.

## Describe the solution you'd like
The return object should also contain "Address_line1" and "Address_line2" as well

**Comment by wavvves** [comment]
Hi @rahulv-dev, thank you for reaching out.

I am assuming you're referring to `$customer->get_taxable_address()`, which is a method that belongs to WooCommerce, not WooCommerce Blocks.

Although outside our scope, I can point you to the `woocommerce_customer_taxable_address` filter, which you can use to modify the output of that method and add the missing data you need.

I am going to close this issue, please reach out if there is anything else we can assist you with WooCommerce Blocks.
