### ISSUE TITLE
Mini-Cart: Make custom colors compatible with theme presets and Global Styles

### ISSUE THREAD

**Issue by danieldudzic** [woocommerce/woocommerce-gutenberg-products-block#10030]
https://github.com/woocommerce/woocommerce-blocks/pull/9647 added support for **Price**, **Icon** and **Product count** custom color options in the **Mini-Cart** block.

@nerrad [pointed out](https://github.com/woocommerce/woocommerce-blocks/pull/9647/files#r1245691175) that in the current implementation, the colors can never be set via presets from a theme (or utilize Global Styles). It also means that stylesheets can't override the colors, as this is set as an inline style color attribute.

He pointed toward Justin Tadlock's **x3p0-progress** block which implements the custom color in a way that addresses that: https://github.com/x3p0-dev/x3p0-progress/blob/1.0/resources/js/color/panel-color.js

@nerrad is also currently working on the custom color panel for the **Price** block and it would make sense to re-use that code across all blocks in Woo Blocks (that utilize custom color settings).

**Comment by nerrad** [comment]
It's looking like I may be have a `CustomColorPanel` component we can use across all our blocks that absorbs the complexity around color management for our blocks. So I've assigned this issue to me for now because I'll probably use the mini-cart implementation in the PR for it.
