### ISSUE TITLE
Order Confirmation: Extension compatibility testing (with hooks)

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#10050]
When the new order confirmation blocks are built, we need to test existing extensions that make use of extensibility points to ensure there is no breakage.

See pdFofs-17q-p2#comment-1399 for an outline of hooks that should be supported.

Find some example extensions and test them with the new page, including guest and account views/

**Comment by mikejolley** [comment]
I looked at a few extensions that use the `woocommerce_thankyou` hooks to render custom content. This worked, however the positioning is different to the old experience.

![Screenshot 2023-09-01 at 14 40 10](https://github.com/woocommerce/woocommerce-blocks/assets/90977/9ff1dbdc-099f-4883-b42c-b9c57db083d2)

Previously this would be at the bottom. 

With the new structure, we won't be able to render these hooks below all of the other blocks without adding a new block to facilitate this. We also will not allow developers to hook in-between the inner blocks (going forward these types of extensions could and should use inner blocks so the merchant can control positioning).

What I'd like to determine is which of these locations would be the best:

![Screenshot 2023-09-01 at 14 43 15](https://github.com/woocommerce/woocommerce-blocks/assets/90977/c6d252ac-934b-4c07-9078-95dc687d73c4)

Position 1 is current-we render the hooks below the summary block. Position 2 is also viable using existing blocks.

For position 3 (my preferred) we'd need to insert a new block which fires the hooks. I'm thinking we just create a placeholder block that is only visible when hooks are in use. Also with this solution, the merchant could move the block into any other position they wish which gives them some control over 3rd party extensions which they lacked previously.

This is all technically possible, and there are placeholder components we can use already in the editor, but I'll need help with naming of the block e.g. 

>**Additional Information**
> This block will render additional order information provided by third party extensions.

Open to suggestions. @annchichi @ralucaStan @pmcpinto

**Comment by pmcpinto** [comment]
Thanks for the ping. 

> For position 3 (my preferred) we'd need to insert a new block which fires the hooks. I'm thinking we just create a placeholder block that is only visible when hooks are in use. Also with this solution, the merchant could move the block into any other position they wish which gives them some control over 3rd party extensions which they lacked previously.

I agree that this is the best solution. "Additional Information" or "Third-party Information" works well as the block name. Just to confirm: you plan to render one block that renders all the 3PD information rather than one per 3PD, right?

**Comment by mikejolley** [comment]
> Just to confirm: you plan to render one block that renders all the 3PD information rather than one per 3PD, right?

@pmcpinto That is correct. In the current system there is a single hook that all extensions share. This is what we're maintaining.

When this is the default experience, the documentation would be updated to recommend using inner blocks instead. This would allow each extension to have it's own block at at position within the thanks page.

**Comment by pmcpinto** [comment]
👍 thanks for the clarification.

**Comment by ralucaStan** [comment]
I prefer the 3rd solution as well. In this way, we can ensure that the most important information is displayed in an optimal way and also allow extensions to add custom content; Adding the custom content in the 2 other positions seems to me like it's interfering with the parsing of the order information. 

The 3rd solution also allows the merchant to move that block which seems like a good thing for the merchant experience;

we should also specify when this custom content is visible on the frontend; for example, it won't be visible if we can't show information about the order (like in the login screens)

I'll add the `needs documentation` label to this ticket so we don't forget about the documentation update.

**Comment by pmcpinto** [comment]
> The 3rd solution also allows the merchant to move that block which seems like a good thing for the merchant experience;

This flexibility is important, as we don't know if what will be rendered is more important than the order information.
