### ISSUE TITLE
How to disable (remove) some field in checkout page of Woocommer Block

### ISSUE THREAD

**Issue by DuynNguyen** [woocommerce/woocommerce-gutenberg-products-block#10060]
## What do you think is missing from the Cart & Checkout blocks?

Hi. I want to remove/disable some filed on the checkout page (for example: country, city, zipcode,.... field). How to do it? Besides that, I want to modify some field is optional, no need to fill in. How can do it?
Thanks so much

**Comment by tarunvijwani** [comment]
@DuynNguyen Thank you for reaching out. Do you wish to disable fields for some specific countries? 

Address fields are determined from the country locale. You can see how they are defined here:

https://github.com/woocommerce/woocommerce/blob/124aeb746710a258f4d66dec4d333dd6cc9818dc/includes/class-wc-countries.php#L795

If you [log an issue](https://github.com/woocommerce/woocommerce/issues) or submit a Pull Request to WooCommerce core with the details of the locale you're targeting and fields that are not required, this can be changed.

**Comment by mikejolley** [comment]
As its been 3 weeks without feedback I will close this issue. Thank you.
