### ISSUE TITLE
Selecting any payment options on the checkout block causes jump to top of page

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-gutenberg-products-block#10061]
## Describe the bug

Testing a new BNPL feature on the checkout block and see that upon selecting different payment methods, the checkout jumps to the top of the screen. This is jarring for the shopper and could cause drop off in the checkout flow.

## To reproduce

1. Go to any WooCommerce store and check out with a product on the checkout block.
2. Scroll down to payment options
3. Select a new payment option

## Expected behavior

The page should maintain scroll position with every selection of payment methods.

## Screenshots
[Video recording](https://www.loom.com/share/54be6367fe0041c585d4fc2649460ca3?sid=e0843012-a3ab-4048-8201-726d863467bf)

Testing on https://favourable-rainbow.jurassic.ninja/block-checkout/

cc @ralucaStan @pmcpinto

**Comment by tarunvijwani** [comment]
Thank you for reporting the issue @elizaan36! Unfortunately, I'm unable to reproduce the issue. I tested it on the following versions:

1. Latest trunk
2. WC Blocks  10.5.0
3. WooCommerce Core 7.8.1.

Site: https://forward-rainbow.jurassic.ninja/checkout/

Could you please help me with which version of WC Blocks you're running?

**Comment by elizaan36** [comment]
hi @tarunvijwani , thanks for looking into this! I just checked on my own test site, and I'm only seeing the jump upon clicking the "Credit card" option from other options in the list. [Video](https://www.loom.com/share/037ad534ad274d34b6898239f1bb6e64)

This is on version 10.6.0 of WooCommerce Blocks with payments options via WooPayments.

**Comment by elizaan36** [comment]
hey @tarunvijwani I'm not seeing this issue anymore! 🎉 I'll close the issue and will reach out again if I notice it again.
