### ISSUE TITLE
My Account block (former used as [woocommerce_my_account])

### ISSUE THREAD

**Issue by masteradhoc** [woocommerce/woocommerce-gutenberg-products-block#10070]
## User Story
As a merchant
I want a block that allows me to add the account area for loggedin clients
So clients can see their latest orders, change their shipping and billing address and change their profile data

### Description
WooCommerce Blocks already offers a huge variety of blocks. To further complete this it would be nice to allow users of the wordpress editor / gutenberg / woocommerce blocks the possibility to change the embedding of My Account from the shortcode `[woocommerce_my_account]` to a block.

![image](https://github.com/woocommerce/woocommerce-blocks/assets/6242098/250b9e65-7f88-41ff-ab94-8dd34de78830)

Its important to note this is not the Customer Account Block - that only handels the login and logout of accounts and servers as menu item f.e. This is about the loginarea that looks like this:
![image](https://github.com/woocommerce/woocommerce-blocks/assets/6242098/4ff2fba6-5370-43d6-a7da-d4881faf0e74)

**Comment by tarhi-saad** [comment]
Hello, @masteradhoc! 👋 Thank you for taking the time to leave your feature request. 🙌  While we have this on our radar, it’s not a priority at the moment. This doesn’t mean what you are suggesting isn’t a good idea or doesn’t make sense – it’s just that we have limited time to work on various projects. At some point, we may revisit our priorities and review the suggestions like this one to see if it warrants a second look. Meanwhile, don’t be alarmed if you don’t see any activity on this issue for a while.
