### ISSUE TITLE
Product Collection block: "No results" msg not displayed

### ISSUE THREAD

**Issue by Marc-pi** [woocommerce/woocommerce-gutenberg-products-block#10082]
## Describe the bug

The "No result found" is not displayed on front side, only on backoffice
Ping @albarin 

## To reproduce

Add the Production Collection block within a Page.

## Expected behavior

* The default message "No results found." (when no products are set yet in Woo) is displayed on editor side (admin)
    * but not on front side (end user side).
* Should we replace the Product Beta blocks by the new Product Collection Block ???

## Screenshots

* front Editor side
![image](https://github.com/woocommerce/woocommerce-blocks/assets/919332/e11b1374-33b9-4067-8a5d-0097226e682c)

* On front
![image](https://github.com/woocommerce/woocommerce-blocks/assets/919332/8f8b1b93-fdc9-4d5b-948c-2a6359eeca6d)

## Environment

WooCommerce 7.8.1
Woo Blocks 10.5.0
WP 6.2.2.
Gutenberg 16.1.0

**Comment by thealexandrelara** [comment]
Hi there @Marc-pi, thank you for reporting this issue! I confirm that I can reproduce this issue on my end as well!

The Product Collection block is currently experimental and its development is still in progress. If you'd like to check the progress, you can visit [the Epic for this block](https://github.com/woocommerce/woocommerce/issues/42389))

At the moment, I would not recommend replacing the Products (Beta) block with the Product Collection block. I'm not sure if @kmanijak or @imanish003 have a different opinion on this matter.

**Comment by imanish003** [comment]
Hi @thealexandrelara, 👋 

From the provided screenshot, it seems @Marc-pi is discussing an issue with the `Products beta` block. If I understand correctly, @Marc-pi is encountering this problem with the `Products beta` block and is considering whether we should substitute this block with the newer `Product Collection` block. @Marc-pi, please feel free to correct me if my interpretation isn't accurate.

~However, it's important to note that I've also been able to reproduce this problem with both the `Products beta` and `Product Collection` blocks, implying we will need to fix this in both.~

Regarding the `Product Collection` block, as @thealexandrelara has noted, it is currently experimental and not yet suitable for general usage. It's only visible in our development build. However, rest assured that we're making progress and planning to launch its beta version shortly.  CC: @kmanijak

**Comment by kmanijak** [comment]
Hi, my colleagues provided great responses and addressed my observations.

I'd like to only add that both Products (Beta) and Product Collection work correctly in terms of the lack of products. These blocks have an inner block placeholder called "No Results":

<img width="352" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/20098064/2327d264-cd21-4131-99ab-37afecb95156">

where you can put any content you'd like to be displayed on the frontend in case there are no products available. If that placeholder is empty no content will be displayed, which is exactly what you experienced. In the example below I added a paragraph displaying there's no content:

Editor | Frontend
-- | --
<img width="1349" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/20098064/58c090a0-19af-4223-bb24-cb6c8c6c70f5"> | <img width="896" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/20098064/c3961484-de43-4784-9ceb-5c448d8bf6bd">

@Marc-pi, please let me know if that answers your concern.

However, I agree that block structure may be confusing and it may not be the best UX. If you have an idea how to improve this journey, please let us know! 🙌

**Comment by Marc-pi** [comment]
yep, i suggest to add systematicaly in the pattern this fallout block, within the pattern group, to enhance pattern adoption.
what do you think about this ?

**Comment by imanish003** [comment]
Hi @Marc-pi,

In PR woocommerce/woocommerce-blocks#11783, we've introduced a default UI for the 'No results' block in the Product Collection block, as illustrated in the screenshot below:

![image](https://github.com/woocommerce/woocommerce-blocks/assets/16707866/2270251d-fec2-43d6-a271-8742b1f5554d)


You're now able to swap out the “Products (Beta)” block for the “Product Collection (Beta)” to leverage this new default UI. I'll be closing this issue for now, but we're open to revisiting it if necessary.
