### ISSUE TITLE
Store Customization MVP > Identify preexisting wireframed patterns

### ISSUE THREAD

**Issue by nefeline** [woocommerce/woocommerce-gutenberg-products-block#10086]
As part of the Personalize Your Store (PYS) project, we need to identify which of our pre-existing patterns are wireframed.

Wireframe: patterns that can adapt colors and fonts.
Opinionated: patterns that stick to a specific default style.

As @verofasulo highlighted: 

> In the assembler, we'd like to introduce wireframe patterns only. Opinionated ones are perceived as a bug in flows like Change your colors or Change your fonts and don't allow users further customization.

ref. p1687417788974599/1686911054.511929-slack-C053716F2H2

At a minimum, we need:

| Page Section                | Number of expected Wireframe Patterns                       |
| --------------------------- | ---------------------------------------- |
| **Header**                 | 3                   |
| **Hero**                   | 2                |
| **Featured products/categories** | 3-4          |
| **About**                  | 1                  |
| **Testimonials/review**    | 2                 |
| **Footer**                 | 3                  |

**Comment by nefeline** [comment]
Listed below are pre-existing patterns, grouped based on the page sections provided in the description of this issue. Each pattern was evaluated and classified as "wireframed" or "opinionated." 

# Important Notes

- Fonts were considered "opinionated" in any patterns with hardcoded references of `font-size` (e.g. `style="font-size:13px"`) or `color` (e.g. `style="color:#ffffff;"`). 
- If the criteria used for determining if a pattern is opinionated or not should change, please flag it in this issue so it can be updated accordingly.
- Not _all_ patterns are listed below: for example, patterns that are just a list of blocks, such as the "Product Filters", and all "Product Query" patterns, are not part of the list.
- By the end, there's a list with the remaining patterns that, IMO, didn't fit the criteria for any of the Page Sections in this project; we can move them to the different sections if folks have different opinions and we want them to be included.

cc: @Aljullu @jarekmorawski @verofasulo 

# Overview

| Title                       | Wireframed Patterns Needed | Wireframed Patterns Available | Opinionated Patterns Available | Total Patterns Available |
| --------------------------- | ------------------------- | ----------------------------- | -------------------- | ------------------------ |
| Header                      | 3                         | 1                             | 5                    | 6                        |
| Hero                        | 2                         | 0                             | 6                    | 6                        |
| Featured products/categories | 3-4                      | 2                             | 6                    | 8                        |
| About                       | 1                         | 0                             | 1                    | 1                        |
| Testimonials                | 2                         | 0                             | 2                    | 2                        |
| Footer                      | 3                         | 0                             | 8                    | 8                        |

# Page Sections
## Header

**Header wireframed patterns needed:** 3
**Header patterns available:** 6 (2 of those are in dark mode)
**Wireframed patterns:** 1
**Opinionated patterns:** 5

| Title                           | Slug                                          | Screenshot (as implemented) | Type |
| ------------------------------- | --------------------------------------------- | ---------- | ---- |
| [Centered Header Menu with Search](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/header-centered-search-pattern.php)| woocommerce-blocks/header-centered-menu-with-search| <img width="953" alt="Screenshot 2023-07-04 at 14 12 18" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/53d07008-e1ed-4fd2-ac4d-e713d34f2e25"> | Opinionated: custom font size and background color  |
| [Essential Header](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/header-essential.php)                | woocommerce-blocks/header-essential          | <img width="952" alt="Screenshot 2023-07-04 at 14 13 10" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/f07f435e-3619-4fe9-827f-2e174bc4f470"> | Opinionated: custom font size  |
| [Essential Header Dark](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/header-essential-dark.php)           | woocommerce-blocks/header-essential-dark     | <img width="950" alt="Screenshot 2023-07-04 at 14 13 54" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/3ca65179-ec80-4fd3-9ebb-2dcd305fdaf9"> | Opinionated: custom font size and background color     |
| [Large Header](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/header-large.php)                    | woocommerce-blocks/header-large              | <img width="950" alt="Screenshot 2023-07-04 at 14 14 44" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/7c25a62f-28bd-44ad-9599-f5a2c0cfe367"> | Wireframed    |
| [Large Header Dark](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/header-large-dark.php)               | woocommerce-blocks/header-large-dark         | <img width="919" alt="Screenshot 2023-07-04 at 14 15 26" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/56de1451-402f-45d6-81d9-1728fa1d6bf2"> | Opinionated: custom background color    |
| [Minimal Header](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/header-minimal.php)                  | woocommerce-blocks/header-minimal            | <img width="929" alt="Screenshot 2023-07-04 at 14 16 11" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/392b95f2-7f39-495a-bf62-d876bab303cb"> | Opinionated: custom font size     |

## Hero

**Hero wireframed patterns needed:** 2
**Hero patterns available:** 6
**Wireframed patterns:** 0
**Opinionated patterns:** 6

| Title                                                                 | Slug                                           | Screenshot (as implemented) | Type |
| --------------------------------------------------------------------- | ---------------------------------------------- | --------------------------- | ---- |
| [Hero Product 3 Split](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/hero-product-3-split.php) | woocommerce-blocks/hero-product-3-split |  ![Screenshot 2023-07-04 at 16 08 47](https://github.com/woocommerce/woocommerce-blocks/assets/15730971/e5e04365-ebc4-42f0-a484-dbabd449d9f1) |  Opinionated: custom font size button color and background color |
| [Hero Product Chessboard](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/hero-product-chessboard.php) | woocommerce-blocks/hero-product-chessboard |  ![Screenshot 2023-07-04 at 16 09 27](https://github.com/woocommerce/woocommerce-blocks/assets/15730971/13bb4d48-59e0-4a7c-b087-e2f2ef436685) |  Opinionated: custom font size |
| [Hero Product Split](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/hero-product-split.php) | woocommerce-blocks/hero-product-split | ![Screenshot 2023-07-04 at 16 10 27](https://github.com/woocommerce/woocommerce-blocks/assets/15730971/4322ae5b-264a-4b71-b39d-80cd074cad19) |  Opinionated: custom font color, background and button color |
| [Just Arrived Full Hero](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/just-arrived-full-hero.php) | woocommerce-blocks/just-arrived-full-hero | ![Screenshot 2023-07-04 at 16 11 57](https://github.com/woocommerce/woocommerce-blocks/assets/15730971/262bd3e2-8d39-4aee-bdea-6e25692f7ebf)  | Opinionated: button color |
| [Product Hero](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/product-hero.php) | woocommerce-blocks/product-hero |  <img width="1209" alt="Screenshot 2023-07-05 at 13 57 44" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/d373f58b-c133-408c-aecf-86561e3341b3">  |  Opinionated: custom font color, background and button color    |
| [Product Hero 2 Column 2 Row](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/product-hero-2-col-2-row.php) | woocommerce-blocks/product-hero-2-col-2-row |  <img width="1031" alt="Screenshot 2023-07-05 at 10 29 05" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/825e7ad4-e661-401c-8ed2-2a960ba426fa"> |   Opinionated: custom font size    |


## Featured products/categories

**Featured products/categories wireframed patterns needed:** 3-4
**Featured products/categories patterns available:** 8
**Wireframed patterns:** 2
**Opinionated patterns:** 6

| Title                                   | Slug                                                      | Screenshot (as implemented) | Type |
| --------------------------------------- | --------------------------------------------------------- | ---------- | ---- |
| [Featured Category Cover Image](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/featured-category-cover-image.php)           | woocommerce-blocks/featured-category-cover-image          |  <img width="1110" alt="Screenshot 2023-07-04 at 17 11 42" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/42f5c781-2cfa-4475-984b-c05d4e4c15de"> |  Opinionated: custom font size and font color, custom button color |
| [Featured Category Focus](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/featured-category-focus.php)                 | woocommerce-blocks/featured-category-focus                |   <img width="1172" alt="Screenshot 2023-07-04 at 17 13 17" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/34382c7b-e172-4d55-b755-f4f535ba7427">         |   Opinionated: custom font color and background, and button color   |
| [Featured Category Triple](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/featured-category-triple.php)                | woocommerce-blocks/featured-category-triple               |   <img width="1110" alt="Screenshot 2023-07-04 at 17 14 32" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/96a64226-01f8-4021-b0fa-15eb72fccf51"> |  Opinionated: font color    |
| [Featured Products 5-Item Grid](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/featured-products-5-cols.php)           | woocommerce-blocks/featured-products-5-item-grid          |  <img width="1240" alt="Screenshot 2023-07-04 at 17 16 40" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/77273cd4-f4c3-4300-a6e1-57e64a5fc279">    |  Wireframed    |
| [Product Collections Featured Collection](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/product-collections-featured-collection.php) | woocommerce-blocks/product-collections-featured-collection |  <img width="1208" alt="Screenshot 2023-07-05 at 13 58 32" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/9c8508ed-e685-4b3f-9e01-a67681bf5802"> |  Opinionated: font, border and background color    |
| [Product Collections Featured Collections](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/product-collections-featured-collections.php)| woocommerce-blocks/product-collections-featured-collections|  <img width="1109" alt="Screenshot 2023-07-04 at 17 19 53" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/481b84e8-89d6-4130-ba3e-1ab192f3c8fe"> |   Opinionated: font size and color, background color and button color    |
| [Product Collections Newest Arrivals](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/product-collections-newest-arrivals.php)     | woocommerce-blocks/product-collections-newest-arrivals    | <img width="1134" alt="Screenshot 2023-07-04 at 17 21 19" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/5896d478-1f02-40c9-a69a-0fa673e4fb0f"> | Opinionated: font size  and border colors   |
| [Featured Products 2 Columns](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/product-featured-2-columns.php)             | woocommerce-blocks/featured-products-2-cols               |  <img width="1121" alt="Screenshot 2023-07-04 at 17 22 32" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/a24ed197-7dc3-483c-b530-39a4f7ea4c1e"> |  Wireframed    |

## About

**'About' wireframed patterns needed:** 1
**'About' patterns available:** 1
**Wireframed patterns:** 0
**Opinionated patterns:** 1

Based on the initial investigation, the only pattern that has an "About us" section is:

| Title                       | Slug                              | Screenshot (as implemented) | Type |
| --------------------------- | --------------------------------- | ---------- | ---- |
| [Alternating Image and Text](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/store-info-alt-image-and-text.php)  | woocommerce-blocks/alt-image-and-text  |  <img width="981" alt="Screenshot 2023-07-04 at 16 37 29" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/6287b13d-b3c8-4530-b1ab-265ff4b73c78"> | Opinionated: custom font size     |

## Testimonials

**Testimonials wireframe patterns needed:** 2
**Testimonials patterns available:** 2
**Wireframed patterns:** 0
**Opinionated patterns:** 2

| Title                   | Slug                                     | Screenshot (as implemented) | Type |
| ----------------------- | ---------------------------------------- | ---------- | ---- |
| [Testimonials 3 Columns](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/testimonials-3-columns.php)  | woocommerce-blocks/testimonials-3-columns  |  <img width="1027" alt="Screenshot 2023-07-04 at 16 44 53" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/9e5fd4f2-6cde-416d-8b72-6fee509d09e0"> |  Custom font color and size    |
| [Testimonials Single](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/testimonials-single.php)     | woocommerce-blocks/testimonials-single     |  <img width="1026" alt="Screenshot 2023-07-04 at 16 45 06" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/19e97eed-ae4f-4739-84e6-6d9da630c4fa"> |  Custom font color and size    |

## Footer

**Footer wireframed patterns needed:** 3
**Footer patterns available:** 8 (3 of those are in dark mode).
**Wireframed patterns:** 0
**Opinionated patterns:** 8

| Title                               | Slug                                          | Screenshot (as implemented) | Type                         |
| ----------------------------------- | --------------------------------------------- | ---------- | ---------------------------- |
| [Large Footer](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/footer-large.php)                        | woocommerce-blocks/footer-large               |  <img width="999" alt="Screenshot 2023-07-04 at 15 35 19" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/170bbdba-f0a9-47c1-93ee-fc01e0122d02"> |  Opinionated: custom font size                            |
| [Large Footer Dark](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/footer-large-dark.php)                   | woocommerce-blocks/footer-large-dark          |  <img width="999" alt="Screenshot 2023-07-04 at 15 35 31" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/6ac3c5c8-eeaa-4dd4-9302-93a12f0bc00b"> |   Opinionated: custom font size and background color                           |
| [Simple Footer](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/footer-simple.php)                       | woocommerce-blocks/footer-simple              |  <img width="1004" alt="Screenshot 2023-07-04 at 15 35 46" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/1b0f7b01-f901-4c07-a938-d38c5ad69298"> |   Opinionated: custom font size                           |
| [Simple Footer Dark](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/footer-simple-dark.php)                  | woocommerce-blocks/footer-simple-dark         |   <img width="907" alt="Screenshot 2023-07-04 at 15 36 27" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/5230deeb-6c22-4aa8-a319-419368e98d35">  |   Opinionated: custom font size and background color                           |
| [Footer with Simple Menu and Cart](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/footer-simple-menu-and-cart.php)    | woocommerce-blocks/footer-simple-menu-and-cart|   <img width="1001" alt="Screenshot 2023-07-04 at 15 37 26" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/0d6a4c2b-721a-4f77-b7e8-489c14958af7"> |   Opinionated: custom font size                           |
| [Footer with 2 Menus](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/footer-with-2-menus.php)                 | woocommerce-blocks/footer-with-2-menus        | <img width="999" alt="Screenshot 2023-07-04 at 15 39 29" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/1647ed96-f3f7-4989-bace-bf1185bbcde8">           |  Opinionated: custom font size                            |
| [Footer with 2 Menus Dark](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/footer-with-2-menus-dark.php)            | woocommerce-blocks/footer-with-2-menus-dark   | <img width="907" alt="Screenshot 2023-07-04 at 15 40 27" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/e75f7a25-341f-4dfc-a080-61014db20fa2"> |  Opinionated: custom font size and background color                            |
| [Footer with 3 Menus](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/footer-with-3-menus.php)                 | woocommerce-blocks/footer-with-3-menus        |  <img width="997" alt="Screenshot 2023-07-04 at 15 41 28" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/69d609b7-6ffd-4c5f-8eea-c78d1b97edd4"> |  Opinionated: custom font size                            |

# Other Patterns

In this section, all remaining patterns are listed (except for patterns that are just a list of blocks, such as the Product Filters, and all Product Query patterns). The blocks listed below were not classified by type just yet ("wireframed" versus "opinionated."), but they can be if we decide we wanna have them as part of the Store Customization project.

## Single Product

| Title                                          | Slug                                                       | Screenshot (as implemented) | Type |
| ---------------------------------------------- | ---------------------------------------------------------- | --------------------------- | ---- |
| [Product Details Product Listing](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/product-details-listing.php)                | woocommerce-blocks/product-details-listing                 |  <img width="1199" alt="Screenshot 2023-07-05 at 14 06 14" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/20ce402e-d1a0-49b8-ab3c-2b9ec43c4797"> |      |
| [Product Details Pattern](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/product-details-pattern.php)                        | woocommerce-blocks/product-details-pattern                 |  <img width="1216" alt="Screenshot 2023-07-05 at 14 06 32" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/49ea3cda-51d3-4386-8967-1f5b99fa2f4a">  |      |
| [Product Listing with Gallery and Description](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/product-listing-with-gallery-and-description.php)   | woocommerce-blocks/product-listing-with-gallery-and-description | <img width="1206" alt="Screenshot 2023-07-05 at 14 06 48" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/ea128d18-23f2-4b8d-9b7a-d87829383d33"> |      |

## Others

| Title                              | Slug                                               | Screenshot (as implemented) | Type |
| ---------------------------------- | -------------------------------------------------- | --------------------------- | ---- |
| [Banner](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/banner.php)                             | woocommerce-blocks/banner                          |   <img width="1197" alt="Screenshot 2023-07-05 at 14 17 55" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/071c20db-0fcc-4a62-9919-3edc8a385fd4">  |      |
| [Discount Banner](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/discount-banner.php)                    | woocommerce-blocks/discount-banner                 |       <img width="486" alt="Screenshot 2023-07-05 at 14 18 08" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/a405d7e2-f3f5-48d8-9336-bf1d74418b37">  |      |
| [Discount Banner with Image](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/discount-banner-with-image.php)         | woocommerce-blocks/discount-banner-with-image      |              <img width="1205" alt="Screenshot 2023-07-05 at 14 18 20" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/73b3461d-48c1-462d-99d7-606028de441f">  |      |
| [Shop by Price](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/shop-by-price.php)                      | woocommerce-blocks/shop-by-price                   |          <img width="1209" alt="Screenshot 2023-07-05 at 14 18 42" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/07a9c77c-dc23-4f47-a100-fa4e68c074ca">   |      |
| [Small Discount Banner with Image](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/small-discount-banner-with-image.php)   | woocommerce-blocks/small-discount-banner-with-image|   <img width="659" alt="Screenshot 2023-07-05 at 14 18 56" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/d1c86105-060d-4dbb-98f0-051bb7c1db16">  |      |
| [Product Collection Banner](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/product-collection-banner.php)   | woocommerce-blocks/product-collection-banner|  <img width="1008" alt="Screenshot 2023-07-05 at 14 43 00" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/820309c7-55c3-45b7-a41b-1cb1cf11ac15"> |      |

**Comment by chrisdesrochers** [comment]
This is awesome! Should we consider "converting" all of the opinionated wireframes to wireframe patterns.

**Comment by nefeline** [comment]
Hi there @chrisdesrochers !

> This is awesome! Should we consider "converting" all of the opinionated wireframes to wireframe patterns.

We have discussed this topic a couple of times already, but, AFAIK, no final decision has been made yet: we know that for the Store Customization MVP project, wireframed patterns are required, but at the same time, for WooCommerce Blocks, the design decision was to stick with opinionated styles. It would be great to get a confirmation from @jarekmorawski and @shaunandrews on this.

**Comment by jarekmorawski** [comment]
I think we've decided to strip the patterns we plan to use in the assembler of all embedded styles (context and confirmation from the core team: `pdnLyh-3Xp#comment-2756`.

Here's the list of patterns we plan to use. It's okay to start working on them, and while the list may change a bit in the coming days, it won't be anything drastic. All patterns not included in this list will remain opinionated for now.

**Headers**
- Essential Header
- Centered Header Menu with Search
- Minimal Header

**Hero**
- Cover Image with CTA (Dotcom)
- Hero Product Split
- Heading And Video (Dotcom)

**Featured category**
- Featured Category Triple
- Featured Category Cover Image

**Featured products•
- Featured Products 5-Item Grid
- New pattern: `F5AAbRJOGbTeEweXPFtHgf-fi-2283-33335&mode=design&t=ad8pj45oCZOaRji4-4`
- Product Collections Newest Arrivals

**Single product**
- Product Hero
- Hero Product 3 Split
- Product Feature with Buy Button (Dotcom)

**Testimonials**
- Testimonials 3 Columns
- Quotes (Dotcom)
- Testimonials Single

**About**
- 3 Column Testimonials (Dotcom)
- Alternating Image and Text
- Three Columns with Images and Text (Dotcom)
- About me (Dotcom)
- Call to Action (Dotcom)
- Simple Two Column Layout (Dotcom)

**Social**
- New pattern: `F5AAbRJOGbTeEweXPFtHgf-fi-2245-36108&mode=design&t=GJPFLlTD5wu1RbC2-4`

**Contact**
- Contact (Dotcom)
- Contact with map on the left (Dotcom)

**Footer**
- Footer with 3 Menus
- Large Footer
- Footer with Simple Menu and Cart
- Footer with Newsletter Subscription Form (Dotcom)

Let me know if you have any questions!

**Comment by nefeline** [comment]
Alright, thanks for clarifying and providing the list @jarekmorawski! cc: @Aljullu @danielwrobert @tjcafferkey

**Comment by nefeline** [comment]
@jarekmorawski do you mind updating the links shared in your previous comment [over here](https://github.com/woocommerce/woocommerce-blocks/issues/10086#issuecomment-1632262165)? Both @Aljullu and I are unable to access them. Thanks!

**Comment by jarekmorawski** [comment]
I just did, and the links are correct. Figma has recently changed the link structure to include the viewing mode (design/dev), so the shorthand may not work properly. Here's a simpler link to the page with all designs. New patterns are marked in green.

`F5AAbRJOGbTeEweXPFtHgf-fi-2229-32566`

**Comment by nefeline** [comment]
> I just did, and the links are correct. Figma has recently changed the link structure to include the viewing mode (design/dev), so the shorthand may not work properly. Here's a simpler link to the page with all designs. New patterns are marked in green.

🤔 Tampermonkey is still not picking up any of these links for some reason: both for Figma and the link to the conversation with the core team. I'll ping you on Slack to get them :)

**Comment by nefeline** [comment]
Sharing here for our reference:

* Design - whole page: F5AAbRJOGbTeEweXPFtHgf-fi-2229_32566
* Design - new pattern (products): F5AAbRJOGbTeEweXPFtHgf-fi-2283_33335
* Design - new pattern (social): F5AAbRJOGbTeEweXPFtHgf-fi-2245_36108
* link to the core team discussion: pdnLyh-3Xp-p2#comment-2756

**Comment by nefeline** [comment]
@chrisdesrochers @jarekmorawski FYI: We have finished wireframing all patterns and implementing the new ones according to the request made here: https://github.com/woocommerce/woocommerce-blocks/issues/10086#issuecomment-1632262165: the only exception is the **Featured Products 5-Item Grid** pattern that is still in code review, but should be merged by EOD today or early next week.

All set for a round of design review :)

**Comment by chrisdesrochers** [comment]
Great work @nefeline & @jarekmorawski. Super fast turnaround. Thanks for the update.

**Comment by chrisdesrochers** [comment]
@shaunandrews When you were out I brought up the following comment:

> This is awesome! Should we consider "converting" all of the opinionated wireframes to wireframe patterns.

Thoughts? Seems like the direction we'd want to head right?

**Comment by nefeline** [comment]
Hi folks! I'm marking this issue as complete since the goal here was to identify preexisting wireframed patterns and this task is complete. For any additional design feedback, feel free to add them on: https://github.com/woocommerce/woocommerce-blocks/issues/10458
