### ISSUE TITLE
Wrapper Block to hide Heading if there is no content

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#10094]
## Current behavior

Downloads, Shipping address, and billing address are made up of a heading block and a shipping address block:

![image](https://github.com/woocommerce/woocommerce-blocks/assets/14235870/64e64ddc-eafc-484b-9f21-aa241a37e73a)

## Expected behavior

However, there is a problem because these blocks may be displayed conditionally e.g. if an order has no shipping address, this section should be hidden. This would result in the heading being displayed, but no address below it.

To fix this we need to create a wrapper (e.g., "Order Confirmation Shipping"). This should contain inner blocks (e.g., the heading, and the shipping address block). The wrapper can then be used to hide all of the contents of the block if it is not needed.

## Screenshots

<img width="960" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/14235870/2698c3f3-b1fd-4e29-a401-3054844ef0cb">

## Additionnal context

We could look to the filter wrapper for inspiration: https://github.com/woocommerce/woocommerce-blocks/tree/trunk/assets/js/blocks/filter-wrapper

**Comment by ralucaStan** [comment]
> Downloads, shipping address, and billing address, all need a new parent block that only displays a heading if they have content

@mikejolley to double check, the wrappers only need to check for address presence and have in place the logic to conditionally show the addresses, for example depending on the URL shape.

**Comment by mikejolley** [comment]
@ralucaStan We can either have logic like that at the top level, or the wrapper could somehow check if the main component rendered null. If its null, hide the heading.
