### ISSUE TITLE
Single Product Template - WordPress 6.3: Strikethrough on regular price is misaligned for "Variable product"

### ISSUE THREAD

**Issue by gigitux** [woocommerce/woocommerce-gutenberg-products-block#10100]
## Describe the bug

The strikethrough on regular price is misaligned for "Variable product".

## To reproduce

1. Ensure you have WordPress 6.3 installed.
2. Blockified the Single Product Template.
3. Visit a variable product (e.g: Hoodie).
4. See the strikethrough misaligned.

## Expected behavior

The strikethrough has to be aligned.

## Screenshots

![image](https://github.com/woocommerce/woocommerce-blocks/assets/4463174/38189ddf-4c39-4ec2-9329-e5f8e1f7706c)

Thread: p1688556635562559-slack-C011ENB20Q1

**Comment by danieldudzic** [comment]
I can't replicate.

I have tested this with two separate websites and:
- WP: 6.2 and 6.3
- WooCommerce Blocks 10.6.0 and 10.7.0-dev
- WooCommerce 7.8.2 and 7.9.0-rc.3 
- Firefox i Chrome


<img width="1151" alt="Hoodie_–_Recent_Magpie" src="https://github.com/woocommerce/woocommerce-blocks/assets/905781/1fbca99f-011f-4e76-b575-35c9d94c24b2">

I believe you were able to replicate it, @gigitux - would you mind giving it a second look?

**Comment by gigitux** [comment]
Mmm, currently, I'm able to replicate with WordPress 6.2.2 and the last beta of WC 7.9:

![image](https://github.com/woocommerce/woocommerce-blocks/assets/4463174/a993cbd3-69e4-487f-8775-673bd3fdf161)

**Comment by danieldudzic** [comment]
Thank you. I was now able to replicate.

The lack of the `summary entry-summary` wrapper causes the theme style (`font-size`) not to apply:

<img width="1272" alt="Hoodie_–_Forthcoming_Howler_i_Pobrane_rzeczy" src="https://github.com/woocommerce/woocommerce-blocks/assets/905781/e0941837-795b-4fd7-bdcd-4eecbf294392">

&nbsp;<br />
Adding it (somewhere) makes the theme styles apply correctly.

<img width="1246" alt="Hoodie_–_Forthcoming_Howler_i_S4E269_-_BLACK_HOLE_PILL" src="https://github.com/woocommerce/woocommerce-blocks/assets/905781/c4342683-44c3-4f0c-a9e9-08507ecc2463">

I'm not 100% sure how we want to address it though:
- Add a wrapper somewhere?
- Add the `font-size` styling via css in WooCommerce blocks?

What do you suggest @gigitux?

**Comment by gigitux** [comment]
> Thank you. I was now able to replicate.
> 
> The lack of the `summary entry-summary` wrapper causes the theme style (`font-size`) not to apply:
> 
> <img alt="Hoodie_–_Forthcoming_Howler_i_Pobrane_rzeczy" width="1272" src="https://user-images.githubusercontent.com/905781/253406516-e0941837-795b-4fd7-bdcd-4eecbf294392.png">
>   Adding it (somewhere) makes the theme styles apply correctly.
> 
> <img alt="Hoodie_–_Forthcoming_Howler_i_S4E269_-_BLACK_HOLE_PILL" width="1246" src="https://user-images.githubusercontent.com/905781/253406575-c4342683-44c3-4f0c-a9e9-08507ecc2463.png">
> I'm not 100% sure how we want to address it though:
> 
> * Add a wrapper somewhere?
> * Add the `font-size` styling via css in WooCommerce blocks?
> 
> What do you suggest @gigitux?

Why have we had this regression? We should check on WooCommerce core and see if something is changed and see if it is possible to improve/revert it.

**Comment by tjcafferkey** [comment]
Doesn't appear to be an issue any longer.
