### ISSUE TITLE
Single Product Template - Related Products Block - WordPress 6.3: the layout of the block is wrong

### ISSUE THREAD

**Issue by gigitux** [woocommerce/woocommerce-gutenberg-products-block#10101]
## Describe the bug

"Related products" block grid layout as a column grid instead of a row grid.

## To reproduce

1. Ensure you have WordPress 6.3 installed.
2. Blockified the Single Product Template. 
3."Related products" block grid layout as a column grid instead of a row grid (wrong behavior).
4. Save the template.
5. Visit a product.
6. "Related products" block grid layout as a column grid instead of a row grid (wrong behavior).
## Expected behavior

Related Products block grid layout should be a row grid.

## Screenshots

![image](https://github.com/woocommerce/woocommerce-blocks/assets/4463174/3777be7f-a4a6-4eaa-83c8-3d318b2dec05)

Thread: p1688556883683899-slack-C011ENB20Q1

**Comment by gigitux** [comment]
Pretty sure that it is something related to https://github.com/woocommerce/woocommerce-blocks/pull/9886

**Comment by danieldudzic** [comment]
This actually seems to be fixed when testing with WordPress 6.3-beta4

<img width="680" alt="V-Neck_T-Shirt_–_Recent_Magpie" src="https://github.com/woocommerce/woocommerce-blocks/assets/905781/8b2e8408-ec3d-466f-b529-a24a3499d22b">
