### ISSUE TITLE
Notice doesn't appear on the cart block page if the product is added via a direct link in a block-based theme

### ISSUE THREAD

**Issue by tarunvijwani** [woocommerce/woocommerce-gutenberg-products-block#10113]
## Describe the bug

Notice doesn't appear on the cart block page if the product is added via a direct link in a block-based theme. 

## To reproduce

1. Activate block based theme like Twenty-Twenty-three
2. Add product via add to cart link. (Eg: http://localhost:10013/cart/?add-to-cart=34)

## Expected behavior

The product has been added to the cart successfully notice should appear. 

## Screenshots

https://github.com/woocommerce/woocommerce-blocks/assets/11503784/de992ce9-5d84-4df2-9f1b-0e3714422d91

## Additional context

Slack: p1688630512127629-slack-C02UBB1EPEF

**Comment by wavvves** [comment]
This is on template-based Cart. Notices still work, it is just this one that misses outputting. I'll pick this issue 👍🏼
