### ISSUE TITLE
Single Product Template > Extensions can trigger fatal errors on templates without any post content blocks

### ISSUE THREAD

**Issue by nefeline** [woocommerce/woocommerce-gutenberg-products-block#10126]
## Describe the bug

When plugin developers add a callback function to an action or filter hook within the Single Product template, it is not uncommon for them to assume the `global $product` variable is always available and an instance of `WC_Product`. 

While this assumption is not ideal (plugin developers should be guarding against fatal errors), this has been a relatively "safe" practice for the classic Product Template, as the core of WooCommerce ensures this variable is properly set via the [`woocommerce_content`](https://github.com/Automattic/woocommerce/blob/security/plugins/woocommerce/includes/wc-template-functions.php#L975-L978), which calls the `the_post()` function. When `the_post` is called, WooCommerce then puts product data into a global via [`wc_setup_product_data`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/wc-template-functions.php#L139).  

With the blockified version of the Single Product template, though, the presence of the global `$product` as an instance of `WC_Product` is not reliable, as it currently depends on the presence of at least one block that invokes the `the_post()` to work as expected. 

In other words, **by simply removing both the Product Details and the Related Products blocks from the blockified template**, the global `$product` variable is not available as an object anymore, resulting in a fatal error for any extensions with callback functions that assume the global `$product` is a `WC_Product`. 

## To reproduce

1. Make sure you have a block theme enabled, such as Twenty-twenty three.
2. Head over to Edit Site > Templates > Single Product
3. Make sure you have the blockyified version of this template up and running: if you don't, click on the "Transform into blocks" button and save.
4. Within any active plugin (e.g. within the `woocommerce-gutenberg-products-block.php` file), add the following:

```php
add_action( 'woocommerce_single_product_summary', function () {
	global $product;

	$product->get_title();
} );
```
5. Access any Single Product on the front-end and ensure everything works as expected.
6. Now head over to `Edit Site > Templates > Single Product` again.
7. Delete/remove both the `Product Details` and the `Related Products` blocks and save.
8. Access any Single Product on the frontend and notice how a Fatal Error is now triggered:

```
Fatal error: Uncaught Error: Call to a member function get_title() on string
```

## Expected behavior

The global `$product` variable should be always an instance of the `WC_Product`, independent of which blocks are being used within the Single Product template.

## Additional context

We have a number of folks reporting they are getting fatal errors as a result of this limitation, including conflicts with plugins such as `WC Payments` and `WooCommerce Google Analytics Integration`.

ref. p1688573619036959-slack-C02UBB1EPEF

**Comment by dinhtungdu** [comment]
FYI, WP 6.4 will also fix this one https://github.com/WordPress/WordPress/commit/5b6555a3845818624a8dab93d57325e11e1c04e1
