### ISSUE TITLE
Product collection - Product category filter isn't working on frontend

### ISSUE THREAD

**Issue by imanish003** [woocommerce/woocommerce-gutenberg-products-block#10131]
### Description
When filtering products by category in the product collection block within the Editor, the products are filtered correctly. However, after publishing the post and viewing it on the frontend, the products are not filtered by category.

### Steps to Reproduce
1. Add a product collection block in the Editor.
2. Add a category to filter the products. At this point, the products are filtered correctly in the Editor based on the chosen category.
3. Publish the post and go to the frontend. 

## Expected Behavior
Products should be filtered by the selected category on the frontend, matching the behavior in the Editor.

## Actual Behavior
On the frontend, the products are not filtered by the chosen category.

Here is a quick demo:

https://github.com/woocommerce/woocommerce-blocks/assets/16707866/492e2c65-d47d-4f70-b429-d5541d8f4a92

**Comment by kmanijak** [comment]
Fixed in https://github.com/woocommerce/woocommerce-blocks/pull/10132
