### ISSUE TITLE
Nonce are invalid 

### ISSUE THREAD

**Issue by afnanz7634** [woocommerce/woocommerce-gutenberg-products-block#10147]
## Describe the bug

Hello I'm adding item into cart from cart api and i'm generating the nonce using this code 

`
        function get_response() {
     $nonce = wp_create_nonce('wc_store_api');
	if(wp_verify_nonce($nonce)){
		return $nonce;
	} else {
		$newNonce = wp_create_nonce('wc_store_api');
		return $newNonce;
	}
}                
`

now the issue is it was working fine yesterday. today the nonce is expired and i saw the newNonce also sending the same nonce id which is already expired. when i try to change the wc_store_api into something else the nonce is changed but the addItem api still shows same error 
![image](https://github.com/woocommerce/woocommerce-blocks/assets/49157938/1c397a9c-323d-4be8-94f9-b2f186674c3a)

as you can see in the above screenshot . Also tried all the solutions from the internet but nothing works 

## Expected behavior

if the nonce is expired new nonce should be generated and the cart api should read it 

### WordPress (please complete the following information):

-   WordPress version: latest
-   WooCommerce version: 7.8.2
-   WooCommerce Blocks version: [e.g. 7.0.0]
-   Site language:
-   Any other plugins installed:

### Desktop (please complete the following information):

-   OS:windows
-   Browser firefox
-   Version [e.g. 22]

**Comment by tarhi-saad** [comment]
Hey, @afnanz7634! 👋 Thank you for reporting this bug! 🙌 Maybe we have another open ticket with the same issue.

@mikejolley, @wavvves, is this issue related to this one: woocommerce/woocommerce#42341?

**Comment by mikejolley** [comment]
Your code is returning the same nonce in the if/else statement. Can you get the current nonce via the headers in the API response?

**Comment by EssDevUi** [comment]
> Your code is returning the same nonce in the if/else statement. Can you get the current nonce via the headers in the API response?

Hello I'm afnan 
nonce from api response are not allowed when ever i try to get them from header by using response.headers.get("Nonce") it always says undefined only 2 headers are allowed to be accessed in response header rest headers are hidden I already tried this but in vain 
@mikejolley

**Comment by mikejolley** [comment]
@EssDevUi This is the response of a GET request to `wp-json/wc/store/v1/cart`:

![Screenshot 2023-07-14 at 15 31 59](https://github.com/woocommerce/woocommerce-blocks/assets/90977/579e0064-ea4f-49a4-b0f4-5ab4ad9e1817)

Can you not see this your end?

**Comment by afnanz7634** [comment]
> @EssDevUi This is the response of a GET request to `wp-json/wc/store/v1/cart`:
> 
> ![Screenshot 2023-07-14 at 15 31 59](https://user-images.githubusercontent.com/90977/253599107-579e0064-ea4f-49a4-b0f4-5ab4ad9e1817.png)
> 
> Can you not see this your end?

I see this on my end and i already tried the response headers are not accessable in the response try it with axios and you will see the error if you console log the response headers you will get only 2 headers in it

**Comment by opr** [comment]
Hi @afnanz7634 and @EssDevUi please would you try this again with WooCommerce Blocks 10.7.0? We recently made some updates to our CORS handling in Store API so it might help. 

Please let me know if this fixes it for you!

**Comment by mikejolley** [comment]
This was the code we found that was missing resulting in missing headers: https://github.com/woocommerce/woocommerce-blocks/blob/6e39893177e2f2b83a34b82dab449a433975c6e6/src/StoreApi/Authentication.php#L33-L38

Should resolve this—please comment back/reopen if the issues persist so we can investigate further.

Thanks
