### ISSUE TITLE
Mention `nvm` and `n` in documentation

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#10167]
## Problem

In #10166, @ockham reported a problem regarding building the WooCommerce Blocks development version. It turned out that he was using Node 16.19.1 (npm 8.19.3) instead of Node 16.15.0 (npm 8.5.5). Apart from that, he's using `n` instead of `nvm`. Therefore, the supported Node version hasn't been loaded automatically. In addition to that, our documentation says https://github.com/woocommerce/woocommerce-blocks/blob/0dc19abc481653154fb3fe6105eaaa6e9d163735/README.md?plain=1#L53

Even though @ockham was using Node.js v16, the problem appeared as the version that he was using is not supported (yet) by WooCommerce Blocks. 

## Proposed change

Apply the following changes to Update [README.md](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/README.md):
- Mention that it's recommended to use `nvm`.
- Mention that developers need to run `nvm use` (before running `npm i` and `npm run build`).
- Mention that if a developer uses `n` instead of `nvm` that they will have to ensure using the supported Node version and potentially point them to https://medium.com/@rodush/adopting-the-zsh-nodejs-developers-story-9af28047460a.

**Comment by ockham** [comment]
Thank you for filing this! It seems like the crucial bit is to use the right Node version (16.15), so maybe the most important change would be

```diff
diff --git a/README.md b/README.md
index b0f317dd0..0a81e7821 100644
--- a/README.md
+++ b/README.md
@@ -50,7 +50,7 @@ We release a new version of WooCommerce Blocks onto WordPress.org every few week
 
 1. Make sure you have the latest versions of WordPress and WooCommerce on your site.
 2. Get a copy of this plugin using the green "Clone or download" button on the right.
-3. Make sure you're using Node.js v16.
+3. Make sure you're using Node.js v16.15.
 4. `npm install` to install the dependencies.
 5. `composer install` to install core dependencies.
 6. To compile the code, run any of the following commands
```

?

(Arguably, Node version management tools might be convenient, but not crucial for things to work; making sure that they pick up the right version kind of follows from the strong requirement for 16.15.)

**Comment by ockham** [comment]
> - Mention that developers need to run `nvm use` (before running `npm i` and `npm run build`).
> - Mention that if a developer uses `n` instead of `nvm` [...]

Suggested change: "they need to run `n auto` (before running `npm i` and `npm run build`)" (which will pick up the version from `.nvmrc`, much like `nvm use` does.)

**Comment by ockham** [comment]
I've filed a PR: #10175.
