### ISSUE TITLE
Optimise Check Markdown links GitHub Action

### ISSUE THREAD

**Issue by tarunvijwani** [woocommerce/woocommerce-gutenberg-products-block#10161]
In #9625, @nielslange  mentioned the following:

> While creating https://github.com/woocommerce/woocommerce-blocks/pull/9622, I noticed that the GitHub Action to check links within Markdown files only goes 3 levels deep. As some of our Markdown files are located deeper than three levels, we would not detect broken links in these files. In addition, I noticed that the GitHub Action, to check for broken links in Markdown files, runs independent if the PR touches Markdown files or not.

In PR #9633 we fixed the following:

- Remove `max-depth: 3` to detect broken links in all Markdown files
- Remove `use-verbose-mode: ‘no’`, as no is the default value, see [configuration](https://github.com/gaurav-nelson/github-action-markdown-link-check/#configuration)

This issue aims to apply the following change to the `Check Markdown links` GitHub Action:

- Exclude Markdown files in `./docs/internal-developers/testing/releases/`

**Comment by nielslange** [comment]
Closing this issue due to #10161. See also https://github.com/woocommerce/woocommerce-blocks/issues/9625#issuecomment-1707627302.
