### ISSUE TITLE
Missing page title in the Cart & Checkout templates

### ISSUE THREAD

**Issue by tarhi-saad** [woocommerce/woocommerce-gutenberg-products-block#10171]
## Describe the bug

In the latest version of WooCommerce Blocks (i.e., v10.6.0) we introduced the Cart & Checkout templates. But, we missed adding the page titles.

You'll notice that the header menu and the footer are also missing in the Checkout Block. This is intentional to offer a distraction-free experience of the Checkout template. See related discussion: p1683289625358199-slack-C8X6Q7XQU

## To reproduce

1. Go to `Appearance -> Editor -> Templates -> Manage all templates`

<img width="360" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/14235870/4941b12d-b9c2-4f8e-8e10-bffb3b8ac2f3">

2. Clear customizations of the Cart & Checkout templates if necessary (see the image below):

<img width="1421" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/14235870/c3e38618-624f-4ebd-8990-f77d68b83179">

3. Go back to the `Templates` view, and select the Cart (then the Checkout) template. Ensure there is no page title. 
4. Go to the frontend of your website, and check the Cart and Checkout pages (add a product if necessary). Ensure there is no page title displayed.

## Expected behavior

We expect the Cart and Checkout templates to have a page title on the editor and frontend pages

### Cart

| Current | Expected |
| -------- | --------- |
| <img width="1401" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/14235870/4347c3b6-4f96-4e7c-bafd-5ddf852a695c"> | <img width="1328" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/14235870/ddbe447b-8461-4140-b3ae-26bf98eea75b"> |

### Checkout

| Current | Expected |
| -------- | --------- |
| <img width="1405" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/14235870/0ac8fb65-009d-4199-921c-560b4be2ee5d"> | <img width="1353" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/14235870/a7c6d5a2-101d-4fe4-a261-2a3684e0d4e5"> |

### WordPress (please complete the following information):

-   WordPress version: 6.2
-   WooCommerce version: 7.8
-   WooCommerce Blocks version: 10.6
-   Site language: English (US)

### Desktop (please complete the following information):

-   OS: macOS
-   Browser chrome
-   Version 114

## Additional context

Initial bug report: p1689059999280559-slack-C02UBB1EPEF

**Comment by ralucaStan** [comment]
maybe similar to #10151
