### ISSUE TITLE
Order Confirmation template: Some styles are missing when using WordPress 6.3 or when Gutenberg is active

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#10170]
## Describe the bug

While testing the Order Confirmation template against WordPress 6.3, I noticed that some styles are missing in the site editor. This is in contradiction to what we presented in p6q7sZ-e1p-p2.

### Before you start

1. Install the Gutenberg plugin.
2. Install and activate the Twenty Twenty-Three theme.

### WordPress 6.2.2, Gutenberg Active

1. Install and activate WordPress 6.2.2.
2. Activate the Gutenberg plugin.
3. Look up the Order Confirmation template both in the site editor and on the frontend.
4. See the problems as highlighted in the following screenshot:

<img width="2559" alt="Screenshot 2023-07-11 at 18 31 40" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/360b280a-16e5-49c4-af85-1c2cc03ee470">

### WordPress 6.2.2, Gutenberg Inactive

1. Install and activate WordPress 6.2.2.
2. Deactivate the Gutenberg plugin.
3. Look up the Order Confirmation template both in the site editor and on the frontend.
4. See that the styles appear as seen in the following screenshot:

<img width="2560" alt="Screenshot 2023-07-11 at 18 34 04" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/8f5898c9-01d5-4f54-acc4-718d1c46e6f8">

### WordPress 6.3, Gutenberg Inactive

1. Install and activate WordPress 6.3.
2. Activate the Gutenberg plugin.
3. Look up the Order Confirmation template both in the site editor and on the frontend.
4. See the problems as highlighted in the following screenshot:

<img width="2560" alt="Screenshot 2023-07-11 at 18 35 43" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/bf780335-c7b8-47ae-a7f5-41ca8559cee0">

### WordPress 6.3, Gutenberg Inactive

1. Install and activate WordPress 6.3.
2. Deactivate the Gutenberg plugin.
3. Look up the Order Confirmation template both in the site editor and on the frontend.
4. See the problems as highlighted in the following screenshot:

<img width="2560" alt="Screenshot 2023-07-11 at 18 35 43" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/bf780335-c7b8-47ae-a7f5-41ca8559cee0">

## Expected behavior

I expect the table borders to be visible, independent if Gutenberg is active or inactive and independent of the WordPress version.

## Environment

I tested this issue against the following variations:

| WordPress | Gutenberg (16.1.2) | Theme               |
| --------- | --------- | ------------------- |
| 6.2.2     | Active    | Twenty Twenty-Three |
| 6.2.2     | Inactive  | Twenty Twenty-Three |
| 6.3       | Active    | Twenty Twenty-Three |
| 6.3       | Inactive  | Twenty Twenty-Three |

> **Note**
> The same problem also appears when using the Twenty Twenty-Two theme.

cc: @mikejolley, @wavvves

**Comment by tarhi-saad** [comment]
I can reproduce the bug! I also noticed that the missing styles are from the `twenty-twenty-three.css` file. For some reason, when the Gutenberg plugin is active, the styles from that file aren't applied anymore!

**Comment by nielslange** [comment]
> I can reproduce the bug! I also noticed that the missing styles are from the twenty-twenty-three.css file. For some reason, when the Gutenberg plugin is active, the styles from that file aren't applied anymore!

That's correct, @tarhi-saad. And as mentioned in the initial description, the same problem also appears when using the Twenty Twenty-Two theme:

<img width="1512" alt="Screenshot 2023-07-12 at 09 00 06" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/ba0fb91d-f56c-45b3-bcd9-6a1920f6cf2b">
