### ISSUE TITLE
Cart and Checkout templates cause previous edits made by the user to be lost

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#10181]
## Describe the bug

Cart and Checkout templates don't inherit the changes made in the Page template. That's problematic as Cart and Checkout were using the Page template before 10.6.0, so updating WC might cause layout breakages.

## To reproduce

1. Create a fresh site and install WooCommerce (I used 7.8.2) but don't install WC Blocks yet.
1. Go to Appearance > Editor > Template Parts > Add New and create a new Header (we can name it My Header).
1. Add some content to it that it's easily identificable: ie "This is My Header".
1. Now go to Templates > Page, remove the default header and add the new one you created: My Header.
1. Feel free to make some more edits, like centering the Post Title.
1. Save the edits.
1. Now, in the frontend, visit the Cart and Checkout pages. You will notice they show the modifications you did in steps 4 and 5.
1. Now, install WC Blocks 10.6.0.
1. Reload the tabs from step 7 and notice all customizations you did are lost in the Cart and Checkout pages: they show the default header and the Post Title block is not centered.

## Expected behavior

Updating WC Blocks to 10.6.0 shouldn't cause any visible change on the frontend of the Cart and Checkout pages on existing stores.

## Screenshots

Cart page modified by the user | Same page after installing WC Blocks 10.6.0
--- | ---
![imatge](https://github.com/woocommerce/woocommerce-blocks/assets/3616980/edd55620-7b9d-4bbb-acc5-4a3e5c3f3e10) | ![imatge](https://github.com/woocommerce/woocommerce-blocks/assets/3616980/f5b49221-b6eb-4978-81da-f4e97fc7d622)

## Additional context

I think that Cart and Checkout templates should default to whatever the existing Page template is at the time of updating. Ie, if the user made some edits to the Page template, Cart and Checkout templates should have those edits as well. Otherwise this seems like a breaking change that might affect existing stores.

Note: I only tested Cart and Checkout templates, but I guess the Order Confirmation template is affected as well.

Note 2: In the testing steps I mentioned creating a custom Header and modifying the Post Title alignment, but the issue affects all page customizations: ie custom Footers, page width, colors, etc.

cc @wavvves @mikejolley as I think you two worked on that? But feel free to ping somebody else.

**Comment by tarhi-saad** [comment]
I can replicate the bug! But I don't know if this behavior is intentional! What are your thoughts on this, @wavvves, @mikejolley?

**Comment by wavvves** [comment]
Nice find @Aljullu! We didn't identify this case when working on migrating existing Cart & Checkout contents, wrapping things with the default Header and Footer (inheriting changes directly from those). Migrating custom template parts included in the Page template wasn't something we were aware of.

On the bright side, this would be easily fixed by the merchant. @ralucaStan we should include this task to improve the merchant's experience when updating from a version prior to 10.6.0

**Comment by ralucaStan** [comment]
Sure thing, we can work on a fix in the next cycle.
