### ISSUE TITLE
Store Customization > Hero Product Split pattern - Update the pattern to become wireframed

### ISSUE THREAD

**Issue by nefeline** [woocommerce/woocommerce-gutenberg-products-block#10211]
As decided on https://github.com/woocommerce/woocommerce-blocks/issues/10086#issuecomment-1632262165, we need to remove all opinionated styles from the [Hero Product Split](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/hero-product-split.php) Pattern, including custom font colors, background, button colors, and any other additional styles (if found).

### Screenshot

<img width="971" alt="Screenshot 2023-07-19 at 11 55 35" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/ebf72e2f-4b00-4d37-9231-a00eca38d2e8">

### Designs

Figma: F5AAbRJOGbTeEweXPFtHgf-fi-2242_36072

**Comment by nefeline** [comment]
Hey @jarekmorawski ! I just noticed that the pattern that is tagged as Hero Product Split pattern on figma is matching a wireframed version of the Banner Pattern:

Figma:

<img width="1338" alt="Screenshot 2023-07-17 at 10 55 29" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/00a861ae-502a-441d-bd00-4c070bf5c1aa">


Banner Pattern:

<img width="1338" alt="Screenshot 2023-07-17 at 10 55 29" src="https://user-images.githubusercontent.com/15730971/251148173-071c20db-0fcc-4a62-9919-3edc8a385fd4.png">

Hero Product Split pattern:

<img width="1338" alt="Screenshot 2023-07-17 at 10 55 29" src="https://user-images.githubusercontent.com/15730971/250926702-4322ae5b-264a-4b71-b39d-80cd074cad19.png">

Could you please confirm if the pattern that needs to be wireframed is the Banner Pattern or the Hero Product Split?

**Comment by jarekmorawski** [comment]
Hi @nefeline 👋 These are different patterns. I referenced Hero Product Split because the image extends to the edge of the screen. In Banner, there's a fixed margin-left that is not suitable for a hero pattern. I assume the similarity comes from the 64 px top and bottom margins I added in Figma (the equivalent of block spacing in Global Styles).

**Comment by nefeline** [comment]
@jarekmorawski thanks:

> I assume the similarity comes from the 64 px top and bottom margins I added in Figma (the equivalent of block spacing in Global Styles).

The reason I flagged it is that on the Figma design, the text doesn't match what we currently have for the Hero Product Split pattern; it matches what is displayed for the Banner Pattern instead (with the only exception being the button text - see screenshots shared in previous comment [over here](https://github.com/woocommerce/woocommerce-blocks/issues/10211#issuecomment-1637646995)). 

> I referenced Hero Product Split because the image extends to the edge of the screen.

Considering **Hero Product Split** pattern is the one we aim to wireframe, should the text of this pattern be updated as well so it matches the design on Figma?

**Comment by jarekmorawski** [comment]
> Considering Hero Product Split pattern is the one we aim to wireframe, should the text of this pattern be updated as well so it matches the design on Figma?

No, I'll update the Figma. Thanks for bringing this up! Let's use the copy we already have.

**Comment by nefeline** [comment]
> No, I'll update the Figma. Thanks for bringing this up! Let's use the copy we already have.

Excellent, thanks for confirming! 🙌
