### ISSUE TITLE
Store Customization > Featured Category Cover Image pattern - Update the pattern to become wireframed

### ISSUE THREAD

**Issue by nefeline** [woocommerce/woocommerce-gutenberg-products-block#10214]
As decided on https://github.com/woocommerce/woocommerce-blocks/issues/10086#issuecomment-1632262165, we need to remove all opinionated styles from the [Featured Category Cover Image](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/patterns/featured-category-cover-image.php) Pattern, including custom font size, color, custom button color and any other additional styles (if found).

### Screenshot

<img width="1057" alt="Screenshot 2023-07-14 at 15 10 12" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/dabf75cd-4472-408c-a02a-8c9c65612837">

### Designs

Figma: F5AAbRJOGbTeEweXPFtHgf-fi-2242_36099

**Comment by Aljullu** [comment]
Closing as we removed this pattern in https://github.com/woocommerce/woocommerce-blocks/pull/10252.
