### ISSUE TITLE
Can not select Featured Category/Product if the ID does not exist

### ISSUE THREAD

**Issue by webmandesign** [woocommerce/woocommerce-gutenberg-products-block#10257]
## Describe the bug

Copying a group of **Featured Category** blocks into a different website (different WordPress + WooCommerce installation), the block throws an error of `Invalid category ID`. It seems there is no way for me to select a category when this error is displayed.

So, if I'm not mistaken, currently I have only 2 options to fix this:
1. edit the block in code editor view and replace the ID with the existing one,
2. or to delete the broken block and reinsert a new one, which is not ideal as I would have to set the block design/layout anew.

**Proposed solution**:
It would be great if there was an option to select a product category also if the `Invalid category ID` error is displayed. This would be much better user experience and would speed up editing.

(Note that this issue also affects **Featured Product** block. It may also affect others I'm not aware of.)

## To reproduce

Steps to reproduce the behavior (my usecase):

1. Take 2 separate WP+WC installations.
2. Create a page and insert a Featured Category block into the page content on the first WP+WC website.
3. Copy this block, switch to second WP+WC website, create a page and paste in the copied block.
4. If there is no product category with ID set in the block, the block throws an `Invalid category ID` error and does not allow you to select a different category.

Or there is actually a **simpler way** to get this error:
1. Create a page and insert a Featured Category block into the page content, set it up properly.
2. In code editor view edit the `"categoryId":##` attribute to `"categoryId":999999` to trigger the block error.
3. Switch back to visual editor view and try to fix the erroneous block, try to select a correct featured category.

## Expected behavior

I expect the block to allow selecting a different featured category/product easy way.

## Screenshots

![wc-featured-category](https://github.com/woocommerce/woocommerce-blocks/assets/2456735/339a774a-530e-4e32-b903-918373b7b93e)

### WordPress:

-   WordPress version: 5.2.2
-   WooCommerce version: 7.9.0
-   WooCommerce Blocks version: 10.6.1

**Comment by roykho** [comment]
Hi @webmandesign - thanks for reporting the issue. If we were to add a button/link to each of the blocks (when a category can't be found) that when clicked, would allow you to choose the category, would that work for you?

**Comment by webmandesign** [comment]
Hi @roykho,

Yes, that would be an ideal solution.

Actually, I think such functionality is already available in the block, it is just not accessible when `categoryId` is already set:

![wc-featured-category-select](https://github.com/woocommerce/woocommerce-blocks/assets/2456735/2868044d-3d98-40e8-a6aa-58a67730caeb)
