### ISSUE TITLE
Ensure the position of the sale badge is consistent across all blocks

### ISSUE THREAD

**Issue by nefeline** [woocommerce/woocommerce-gutenberg-products-block#10253]
## Describe the bug

Currently, the position of the Sale badge is different depending on the block used.

For the **Products (Beta)** and the **All Products** blocks, for example, the badge is displayed within the product image:

<img width="212" alt="Screenshot 2023-07-18 at 12 29 31" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/7b16bb51-9894-4a05-90ff-fec84d81d7f7">

On the other hand for the **Hand-picked Products**, **Newest Products**, **On Sale Products** and **Products by Attribute** blocks, the sale badge is displayed below the product title instead:

<img width="213" alt="Screenshot 2023-07-18 at 12 32 02" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/dc8e5fa0-ded4-488d-b15a-fcb3e885196c">

## Expected behavior & Discussion

What do we think about consolidating and having only one default position for the sale badge across all blocks within WooCommerce? Tagging @jarekmorawski for your thoughts on this.

**Comment by jarekmorawski** [comment]
Thanks for the ping! If possible, all blocks presenting a single product should have the layout we've built for the new Product Collection block. 👍
