### ISSUE TITLE
WooCommerce causing malfunction of the navigation block on WordPress 6.3

### ISSUE THREAD

**Issue by nefeline** [woocommerce/woocommerce-gutenberg-products-block#10259]
## Describe the bug

The core's Navigation Block doesn't work as expected while having the latest version of WooCommerce enabled on WordPress 6.3.

## To reproduce

1. Make sure you have a fresh WordPress install running on version 6.3. You can update the version via WP-CLI by running: `wp core download --version=nightly --force`
2. Update the DB via user interface or via WP-CLI as well by running: `wp core update-db`
3. Access your Dashboard and make sure you are indeed running the nightly version of WordPress, which currently is version `6.3-beta4-56253`.
4. Create a new post and insert the Navigation block. Make sure everything works as expected.
5. Now install and activate the latest version of WooCommerce (7.9.0)
6. Access the post you just created and notice the navigation block is not working anymore and there are errors in the console:

<img width="1997" alt="Screenshot 2023-07-18 at 16 47 47" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/ced53903-6109-4041-9684-3c3494236997">

## Expected behavior

The navigation block should work as expected while having WooCommerce enabled.

## Environment

-   WordPress version: [6.3-beta4-56253]
-   WooCommerce version: [7.9.0]

**Comment by nerrad** [comment]
To better understand the scope of impact, what happens if just WooCommerce core is active?

**Comment by nefeline** [comment]
> To better understand the scope of impact, what happens if just WooCommerce core is active?

The conflict persists with only WooCommerce enabled. I'm updating the testing instructions to reflect this :) If this turns out to be a conflict caused by a core feature rather than blocks, we can then move this issue to the core's repo
