### ISSUE TITLE
Filtering Blocks

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-gutenberg-products-block#1026]
**User Story**
As a merchant
I want blocks that allow filtering my products by one or more criteria
So I can allow users to narrow down products based on specific needs

Filter products by price
Filter products by attribute
Filter products by rating
Active products filtering

**Comment by nerrad** [comment]
We now have a label for each of the filter blocks (and a block-type label for all filter blocks) so the Epic is redundant.
