### ISSUE TITLE
Cart Block: Does not showing you may be interested product in frontend side.

### ISSUE THREAD

**Issue by vipulupadala-multidots** [woocommerce/woocommerce-gutenberg-products-block#10295]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I tested the cart block and found that does not show you may be interested product in frontend side. Please check the below-provided video recording for a better understanding of the issue.

Video URL: https://share.cleanshot.com/XcJhZ0qPwY4JFyhgdjMP

### Expected behavior

Need to show you may be interested product in frontend side

### Actual behavior

does not show you may be interested product in frontend side

### Steps to reproduce

1. Create a new page and take the cart block.
2. Next, added some products to cart 
3. Then compare the backend and front sides.
4. Front side does not show you may be interested product.

### WordPress Environment

WC Version: 7.9.0
WP Version: 6.2.2
Active Theme: Twenty Twenty-Three (twenty twenty-three)
Active theme version:1.1

Server Environment

Web server: nginx/1.16.0
PHP Version: 7.3.5 (Supports 64bit values)
PHP memory limit: 256M
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.54.0 LibreSSL/2.6.5
OpenSSL/3.0.2

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
@vipulupadala-multidots The blocks functionality is maintained in another repository. I'll transfer this issue to that repository.

**Comment by opr** [comment]
Hi there @vipulupadala-multidots thanks for opening this issue! To get the "You may also be interested in" block (also called the "Cart Cross-Sells Products block") you need to add "Cross-sells" to your products.

The Cart Cross-Sells Products block will be populated with cross-sells based on what the shopper has in their cart.

To add a cross-sell to a particular product, you'll need to edit that product in the WooCommerce admin area. Go to the "Product Data" section then "Linked products"

<img width="847" alt="Screenshot 2023-07-21 at 11 16 17" src="https://github.com/woocommerce/woocommerce-blocks/assets/5656702/c13ced02-7994-4114-b1ef-111610775894">

I'll close this ticket as I believe there's nothing actionable on our end, but please feel free to reopen it if you need further help!
