### ISSUE TITLE
Payment Gateways by coinbase doesn't work with the Cart and Checkout Blocks

### ISSUE THREAD

**Issue by VDiamond78** [woocommerce/woocommerce-gutenberg-products-block#10317]
## Is your feature request related to a problem? Please describe.
Nowdays, the cryptocurrencies gains more and more importance and they become a way of payment more and more common.
In this path, I would like to add this payement option to my website but she's doesn't compatible with the blocks.

So, I hope you will made that compatible between them as quickly as possible.

Thanks for your listening and hoping you can take care of it ! 

```[tasklist]
### Tasks
```

**Comment by mikejolley** [comment]
Thanks for the report, I've created a tracking issue here:

https://github.com/woocommerce/woocommerce/issues/42281
