### ISSUE TITLE
RC OMBF Paiement doesn't work with Cart and Checkout Blocks

### ISSUE THREAD

**Issue by VDiamond78** [woocommerce/woocommerce-gutenberg-products-block#10319]
All is in the title.

This way of payment is very important for african people, who are a consequently part of my and other society clients .

I hope you will be able to fix this problem quickly 

Thanks for the listening !

**Comment by mikejolley** [comment]
Hi @VDiamond78 

Are you referring to the [RCOMGateway by RConsolidate](https://pap-aw.wordpress.org/plugins/woo-orange-money-payment-gateway-by-rc/#description) here? That one doesn't appear to have been updated for a while.

Currently it’s up to extension developers to add support for the new checkout flow offered via the Cart and Checkout Blocks. We have some [documentation for Third-party developers](https://href.li/?https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs#third-party-developers) and some [Developer Resources](https://href.li/?https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs#developer-resources) available to help with their integration efforts.

Your best course of action now if you are using a payment method that isn’t working with the blocks is to notify the developer of the extension and ask if they can add support.

Until then, you can keep on top of the [status of the Cart & Checkout Blocks in this documentation](https://href.li/?https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/).

Thanks
