### ISSUE TITLE
style-rtl.css overrides and doesn't respect global styling

### ISSUE THREAD

**Issue by asafm7** [woocommerce/woocommerce-gutenberg-products-block#10321]
`style-rtl.css` overrides and doesn't respect global styling.

See screenshot:
![image](https://github.com/woocommerce/woocommerce-blocks/assets/14274769/a1324b0d-23a5-4a2f-aa29-a0e833c5b843)

**Comment by roykho** [comment]
Hi @asafm7 - thanks for reporting. If you don't mind, could you please give us detailed steps to reproduce the issue? Thank you!

**Comment by asafm7** [comment]
Thanks @roykho. I'm using a blank theme created using the Create Block Theme plugin, and Hebrew as the language. Specific element example can be seen in the screenshot above. I think that's about it. Let me know if you need anything else.

**Comment by gigitux** [comment]
There are several things to check before to confirm that this behavior is an issue:
- What is this expected outcome?
- Did you try removing WooCommerce Core and WooCommerce Blocks plugins? Looking at the screenshot, the css isn't overridden by WooCommerce styles.

**Comment by asafm7** [comment]
Thanks @gigitux .

You are right, I'm sorry. This is a WP core issue, not WooCommerce.

**Comment by gigitux** [comment]
No worries! I will close this issue!
