### ISSUE TITLE
PHP 8.2 Deprecation Messages

### ISSUE THREAD

**Issue by masteradhoc** [woocommerce/woocommerce-gutenberg-products-block#10358]
## Describe the bug
We get the following Deprecation Messages on PHP 8.2 from WooCommerce Blocks.

<html>
<body>

Level| Message | Location | 1 | Plugin
-- | -- | -- | -- | --
Deprecated | Creation of dynamic property Automattic\WooCommerce\Blocks\Shipping\PickupLocation::$cost is deprecated | +wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Shipping/PickupLocation.php:28 | 1 | Plugin: woocommerce
Deprecated | Creation of dynamic property Automattic\WooCommerce\Blocks\Shipping\PickupLocation::$pickup_locations is deprecated | +wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Shipping/PickupLocation.php:30 | 1 | Plugin: woocommerce

</body>
</html>

## To reproduce
We get this on every page.

## Expected behavior
No Deprecation messages :)

### WordPress (please complete the following information):

-   WordPress version: 6.2.2
-   WooCommerce version: 7.9.0
-   Site language: German

**Comment by mikejolley** [comment]
This was fixed in 10.6.0, so the next version of Woo core will contain it.

I did spot some other notices when testing so I will raise a separate PR to address those.
