### ISSUE TITLE
The global $product object is not set in 'woocommerce_before_single_product'

### ISSUE THREAD

**Issue by jimjasson** [woocommerce/woocommerce-gutenberg-products-block#10379]
## Describe the bug

When the block-based single product template is used, the `global $product` object is not set in the `woocommerce_before_single_product`.

To test, you may use the following snippet:

```
add_action( 'woocommerce_before_single_product', 'does_this_run' );

function does_this_run() {
	var_dump( "it runs" );
	
	global $product;
	
	var_dump( $product );
}
```

This snippet prints a string as the `$product` instead of a `WC_Product`.

This object is correctly set when the legacy template is used. 

This issue currently causes two issues with plugins, one with Product Bundles and another with Gift Cards. Given that this is a popular hook, I expect that more plugins will be affected. 

## To reproduce

1. Use the above snippet and note the value of the `global $product` object.

## Expected behavior

I expect that the `global $product` object would be set in the `woocommerce_before_single_product` action.

## Environment

Fresh WordPress install with the latest Blocks version active.

**Comment by nefeline** [comment]
Hi there @jimjasson 👋 ! We have already solved this problem on https://github.com/woocommerce/woocommerce-blocks/pull/10128, which is part of WooCommerce Blocks 10.7.0, but it is not part of the core of WooCommerce just yet: we already have it on deck for the next patch release (10.6.2) which is scheduled for the next few days.

**Comment by jimjasson** [comment]
False alarm, the object is there as expected. The cause of this issue is different and I will open a new issue about this shortly.

**Comment by nefeline** [comment]
For anyone still facing this problem ATM (basically all users with only WooCommerce enabled, not WooCommerce Blocks) the fix is scheduled for release on WooCommerce 8.0.

**Comment by danielwrobert** [comment]
@jimjasson, @nefeline - from what I'm seeing this can be closed now, is that correct?

**Comment by jimjasson** [comment]
@danielwrobert It's a yes from me!

**Comment by danielwrobert** [comment]
Thanks, @jimjasson!
