### ISSUE TITLE
Review the execution sequence of the single product page hooks

### ISSUE THREAD

**Issue by jimjasson** [woocommerce/woocommerce-gutenberg-products-block#10381]
## Describe the bug

When the block-based single product template is used, and I install the following snippet that prints the single product page hooks: 

```
add_action( 'woocommerce_before_single_product', 'before_single_product' );

function before_single_product() {
	error_log( "before_single_product" );
}

add_action( 'woocommerce_before_add_to_cart_button', 'before_add_to_cart_button' );

function before_add_to_cart_button() {
	error_log( "before_add_to_cart_button" );
}

add_action( 'woocommerce_single_product_summary', 'single_product_summary' );

function single_product_summary() {
	error_log( "single_product_summary" );
}

add_action( 'woocommerce_product_meta_start', 'meta_start' );

function meta_start() {
	error_log( "meta_start" );
}

add_action( 'woocommerce_after_single_product_summary', 'after_single_product_summary' );

function after_single_product_summary() {
	error_log( "after_single_product_summary" );
}

add_action( 'woocommerce_after_single_product', 'after_single_product' );

function after_single_product() {
	error_log( "after_single_product" );
}
```

I get this result:

![MXgEgZ.png](https://github.com/woocommerce/woocommerce-blocks/assets/25955483/1d43d3b6-c57c-43f4-9e99-ab70bccf0b59)

As you can see, this sequence is not correct. The `woocommerce_single_product_summary` hook runs after the `woocommerce_after_single_product_summary` hook.

This is the execution sequence when the legacy template is active:

![Jf2qsg.png](https://github.com/woocommerce/woocommerce-blocks/assets/25955483/a4091630-7424-4ecd-be3f-64e9d86dffb0)

## To reproduce

1. Use the above snippet and take note of the execution sequence of the single product page hooks.

## Expected behavior

The `woocommerce_single_product_summary` hook should run after the `woocommerce_after_single_product_summary` hook.

**Comment by gigitux** [comment]
Upon further consideration of this issue, I have decided to close it. 
The sequence of hooks is contingent upon the order of blocks and how WordPress renders them. WordPress follows a rendering logic from the bottom to the top, rendering inner blocks before outer ones. Consequently, relying on a specific execution sequence of the hook is not feasible in this context.
