### ISSUE TITLE
[Enhancement]: Block for showing the current star rating on a single product page (block editor)

### ISSUE THREAD

**Issue by asafm7** [woocommerce/woocommerce-gutenberg-products-block#10391]
### Describe the solution you'd like

Adding a block for showing the current star rating on a single product page (block editor)

### Describe alternatives you've considered

I can't think of one.

### Additional context

It is currently shown in the "Reviews" tab.

I think it should be possible to display the rating separately from the reviews and to make it more prominent.

**Comment by rrennick** [comment]
@asafm7 Thanks for creating the issue. The blocks functionality is maintained in a separate repository. I'll transfer this issue to that repo.

**Comment by gigitux** [comment]
Hi @asafm7,
Thanks for opening this issue!

Currently, it is possible show the current star rating with the `Product Rating` block:

| Editor | Frontend |
|--------|--------|
|![image](https://github.com/woocommerce/woocommerce-blocks/assets/4463174/accca141-747f-4c2d-bfdc-0dfa5ada015a)|![image](https://github.com/woocommerce/woocommerce-blocks/assets/4463174/cc62deeb-9e41-47c7-90b4-e4b400b0f4e7)| 

I will close this comment, but feel free to re-open it if my reply didn't help you!

**Comment by asafm7** [comment]
@gigitux you are right. I somehow missed it.
