### ISSUE TITLE
Not working with more than 1 column - storefront theme.

### ISSUE THREAD

**Issue by GregorR1** [woocommerce/woocommerce-gutenberg-products-block#104]
I can't get the products to display in multiple columns.  I have tried setting it to 3, 4 & 5 columns wide and it displays correctly in the backend - but only displays as one column on the front end.  

I'm using Storefront theme with beaver builder/themer installed.

**Comment by tiagonoronha** [comment]
Hi @GregorR1 I couldn't replicate this issue. Can you please share the url to your site / page in question? 

Thanks!

**Comment by GregorR1** [comment]
Hi Tiago,

I got it on the page https://designtofit.co.uk/2537-2/.

Thanks,
Gregor

**Comment by tiagonoronha** [comment]
The columns styling in Storefront is only added inside the `.site-main` wrapping container. 

In beaver builder settings, find where you can add the `.site-main` class to the container, and it should fix the issue for you.

https://kb.wpbeaverbuilder.com/article/85-add-a-css-id-or-class-name-to-a-module
