### ISSUE TITLE
Opinion

### ISSUE THREAD

**Issue by agnieszkajuroszek** [woocommerce/woocommerce-gutenberg-products-block#10405]
## What do you think is missing from the Cart & Checkout blocks?

What I like about the Cart & Checkout blocks is the simple aesthetics, taking into account the colors of the website template. The ability to sort products is also beneficial.

In my opinion, there is no possibility to edit the fields for entering the address - when ordering electronic products sent by e-mail, the physical address is not needed for shipping.

**Comment by nielslange** [comment]
Hello @agnieszkajuroszek  👋

Thanks for your feature request. We appreciate you sharing your idea with us. We’re glad to inform you that this feature is one of our goals for this year. Although we can’t give you a specific timeline for its implementation, we consider it an important feature and will be working on it. As there's no immediate action item, I'll close this issue. Please bear with us and keep an eye out for updates on this issue, though.

<small>(Similar issues: #4758, #8214, #9918)</small>
