### ISSUE TITLE
Jurassic Ninja > Add WooCommerce Blocks to the list of plugins to allow us selecting a specific branch

### ISSUE THREAD

**Issue by nefeline** [woocommerce/woocommerce-gutenberg-products-block#10400]
On Jurassic Ninja, there's a special section for Woo with a few plugins listed, but this list doesn't include WooCommerce Blocks. When you click on the **WooCommerce Beta Tester** option, you are also allowed to select the branch to be used as a base for the plugin on JN:

<img width="1018" alt="Screenshot 2023-07-28 at 11 26 57" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/26462d4e-16ff-4ab2-90d4-f4ff86c1560c">

Creating this issue as a proposal for us to add WooCommerce Blocks to this list as well and have the same functionality of selecting the branches as available for the **WooCommerce Beta Tester** option.

**Comment by samueljseay** [comment]
I would suggest holding off on this because there are quite a few hoops to jump through, it would be best to wait for blocks to be merged in core and then you'll get this for free.

**Comment by nefeline** [comment]
> I would suggest holding off on this because there are quite a few hoops to jump through, it would be best to wait for blocks to be merged in core and then you'll get this for free.

Good call! We were not aware of this transition when the issue was opened, I'm going ahead and closing it 🙌
