### ISSUE TITLE
Add admin views/actions to the woocommerce-analytics module

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-gutenberg-products-block#10427]
**Description:** the woocommerce-analytics module implementation excludes store admin actions in the store front end. This approach makes sense to avoid having noisy data coming from test actions. However, it can be quite useful to understand when and how merchants are interacting with the store front end. The best solution to this problem is to start tracking admin views/action and add a property to identify them, allowing us to segment the data.
This will need to be implemented in the Jetpack repo. More info about prior art here: pb0Spc-ou-p2#comment-701

**Acceptance criteria:**

- [ ] Change the logic to ensure admin views/actions are tracked when the store admin interacts with all the pages included in the woocommerce-analytics module (product, cart, checkout, order confirmation)
- [ ] Add a `store_admin` [true|false] property to identify when the event is fired by a store admin

Ideally, we should include this change in the next Jetpack release.

**Comment by ralucaStan** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Rubik-Engineering-5a84601e79f97c2acc45cc58/issues/woocommerce/woocommerce-blocks/10427?planning-poker) with Zenhub @mikejolley

**Comment by opr** [comment]
@pmcpinto should we update every event fired by the module in Tracks so it includes the `store_admin` property? Is this necessary? 

The `store_admin` property is recorded even without doing this, just want to know what the correct procedure is, and who should take care of that?

**Comment by pmcpinto** [comment]
> @pmcpinto should we update every event fired by the module in Tracks so it includes the store_admin property? Is this necessary?

Yes

> The store_admin property is recorded even without doing this, just want to know what the correct procedure is, and who should take care of that?

Can you clarify this? Do we already this event property in place?

**Comment by opr** [comment]
> > @pmcpinto should we update every event fired by the module in Tracks so it includes the store_admin property? Is this necessary?
> 
> Yes
> 
> > The store_admin property is recorded even without doing this, just want to know what the correct procedure is, and who should take care of that?
> 
> Can you clarify this? Do we already this event property in place?

Well, what I mean is the `store_admin` property is recorded when sending the event, even though I didn't set it up in the event properties on Tracks, however I'm wondering whether it actually gets added to the event registration automatically when we send it for the first time. 🤔  I'll let you know if we need any changes on this as we progress with these changes.

**Comment by pmcpinto** [comment]
Gotcha. Please keep me posted. Thanks!
