### ISSUE TITLE
Cart block - Third party plugin compatibility - the price shows as "discounted" while it is not

### ISSUE THREAD

**Issue by marcusig** [woocommerce/woocommerce-gutenberg-products-block#10433]
## Describe the bug

When the cart item price is modified by a third party plugin and the price is different from the original, it shows as discounted, even though it is not. (see screenshot)

## To reproduce

1. Go to [https://demos.mklacroix.com/custom-laptop/](https://demos.mklacroix.com/custom-laptop/)
2. Select some options with an extra price
3. Add to cart
4. Visit the cart comparison page (https://demos.mklacroix.com/cart-block-vs-cart-shortcode/)

## Expected behavior

Either the original price should only be displayed if there is an actual discount applied, or there should be an option to not display it.

## Screenshots

![image](https://github.com/woocommerce/woocommerce-blocks/assets/11990914/58f4e9c6-3dae-430c-935e-e054d05dc198)

### WordPress (please complete the following information):

-   WordPress version: 6.3
-   WooCommerce version: 7.9
-   WooCommerce Blocks version: 10.7.1 
-   Site language: EN
-   Any other plugins installed: [Product configurator for WooCommerce](https://wordpress.org/plugins/product-configurator-for-woocommerce/) and add-ons. The Extra price add-on changes the item price.

## Additional context

As the developper of the plugins mentioned above, this issue will be part of a series of issues brought forward in an effort to make them compatible with the cart and checkout blocks.

**Comment by nielslange** [comment]
Hello @marcusig,

Thanks for reaching out. I was able to reproduce this issue by adding the following snippet to my site using the [Code Snippets](https://wordpress.org/plugins/code-snippets/) plugin:

```php
function calc_price( $cart_object ) {
    foreach ( $cart_object->get_cart() as $hash => $value ) {
        $value['data']->set_price( 50 );
    }
}
add_action( 'woocommerce_before_calculate_totals', 'calc_price' );
```

I see that this issue affects both the Cart and the Checkout block.

<table>
<tr>
<td valign="top">Cart block:
<br><br>

<img width="1512" alt="Screenshot 2023-08-09 at 15 51 41" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/de8eb230-53ad-4087-b3e3-ed31f8b361db">
</td>
<td valign="top">Checkout block:
<br><br>

<img width="1512" alt="Screenshot 2023-08-09 at 15 53 05" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/374052a7-9c4f-4d77-928b-5ce6f842b064">
</td>
</tr>
</table>

I'll move this issue to our backlog now.
