### ISSUE TITLE
Cart block - Third party plugin compatibility - Possibility to hide the Quantity field and Remove item link

### ISSUE THREAD

**Issue by marcusig** [woocommerce/woocommerce-gutenberg-products-block#10436]
## Is your feature request related to a problem? Please describe.
In my plugins, I need the possibility to hide the Quantity field as well as the Remove item link.
This is in the context where a cart item is linked to an other one, so it can only be removed when the parent item is removed, and the quantity can only be changed from the parent item.

## Describe the solution you'd like
I would like a way to decide whether those items are displayed or not. 
Obviously not CSS, as that can be overridden easily by other plugins/themes or even the end user.

In the Cart Shortcode, this is achieved with hooks (`woocommerce_cart_item_remove_link` and `woocommerce_cart_item_quantity`) so I would tend to look for something similar, but I'm opened to a solution more adapted to the blocks context.

## Additional context

Cart shortcode example:

![image](https://github.com/woocommerce/woocommerce-blocks/assets/11990914/47fcbb9e-f43d-4578-85a2-b3867da367cb)

Cart block:

![image](https://github.com/woocommerce/woocommerce-blocks/assets/11990914/200d8c61-9281-490f-8e8e-f66ee1cc1bf1)

**Comment by nielslange** [comment]
Thanks for reaching out, @marcusig. To to hide the quantity field and the remove item link, you can use the following two filters:
- `woocommerce_store_api_product_quantity_editable`
- `showRemoveItemLink`

Assuming that you want to hide the quantity field and the remove item link for the product with the ID 46, you can accomplish this using the following code snippets.

**PHP snippet:**
```php
add_filter( 'woocommerce_store_api_product_quantity_editable', function( $quantity, $product, $cart_item )  {
	if ( $product->id == 46 ) {
		return false;		
	}
	return true;
}, 10, 3 );
```

**JS snippet:**
```js
const { registerCheckoutFilters } = window.wc.blocksCheckout;
registerCheckoutFilters( 'example-extension', {
	showRemoveItemLink: ( value, extensions, { cartItem } ) => {
		// Prevent items with ID 46 being removed from the cart.
		return cartItem.id !== 46;
	},
} );
```

Applying these snippets to my site, lead to the following result:

<img width="549" alt="Screenshot 2023-08-09 at 17 18 27" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/438b1f59-83df-4cfa-9ac8-6d33d5af0a78">

I hope this helps. I'll mark this issue as closed, but please don't hesitate to contact us again, in case there's anything else we can assist you with.

**Comment by marcusig** [comment]
That should do it, thank you!

**Comment by nielslange** [comment]
> That should do it, thank you!

I'm glad to hear that, @marcusig. 🙌
