### ISSUE TITLE
Compatibility Layer - hooks are not fired if Products is not wrapped with Group block

### ISSUE THREAD

**Issue by kmanijak** [woocommerce/woocommerce-gutenberg-products-block#10451]
### Steps to reproduce
1. In your theme's `functions.php` add:

```
add_action( 'woocommerce_before_main_content', function () {
	echo '<p class="woocommerce_before_main_content">Hook: woocommerce_before_main_content</p>';
});

add_action( 'woocommerce_after_main_content', function () {
	echo 'Hook: woocommerce_after_main_content';
});

add_action( 'woocommerce_before_shop_loop_item_title' , function () {
	echo 'Hook: woocommerce_before_shop_loop_item_title';
});

add_action( 'woocommerce_shop_loop_item_title' , function () {
	echo 'Hook: woocommerce_shop_loop_item_title';
});

add_action( 'woocommerce_after_shop_loop_item_title' , function () {
	echo 'Hook: woocommerce_after_shop_loop_item_title';
});

add_action( 'woocommerce_before_shop_loop_item' , function () {
	echo 'Hook: woocommerce_before_shop_loop_item';
});

add_action( 'woocommerce_after_shop_loop_item' , function () {
	echo 'Hook: woocommerce_after_shop_loop_item';
});

add_action( 'woocommerce_before_shop_loop' , function () {
	echo 'Hook: woocommerce_before_shop_loop';
});

add_action( 'woocommerce_after_shop_loop' , function () {
	echo 'Hook: woocommerce_after_shop_loop';
});

add_action( 'woocommerce_no_products_found' , function () {
	echo 'Hook: woocommerce_no_products_found';
});
```
2. Go to Product Catalog
3. Add Group block
4. In the Group block add Products (Beta) block
5. Make sure it Inherits Query from Template
6. Save and go to frontend

You should see hooks' content applied

<img width="1326" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/20098064/9d8f5ffb-8cea-43b4-956e-720558984870">

7. Go back to Editor
8. Move Products (Beta) block from Group block so it's not nested anymore
9. Save and go to Frontend

**Expected:** Hooks content is there like on the previous screenshot
**Actual:** Hooks content is not there:

<img width="1450" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/20098064/83fc126f-9690-4a49-a62c-1739134804b8">

**Comment by dinhtungdu** [comment]
We missed the case that the `Products (Beta)` is the top level block. I have an idea to fix this issue, let me handle this.
