### ISSUE TITLE
Customer account block design not compatible for Twenty Twenty-One theme

### ISSUE THREAD

**Issue by VipulUpadala** [woocommerce/woocommerce-gutenberg-products-block#10466]
## Describe the bug

I tested the Customer account block with WordPress twenty twenty-one theme and found blocks icon design are not working.

## To reproduce

1. First Active Twenty Twenty-One theme
2. Create a new page and take the Customer account block .
3. And, see icon size not increase in the frontend side.

## Expected behavior

Need to increase icon size same as display in Twenty Twenty-Three and Twenty Twenty-Two themes.

## Screenshots

Please check the below provided video recording for a better understanding of the issue.
Video URL: https://share.cleanshot.com/xhBqNd1Y8VhXzZk7rCm2

### WordPress (please complete the following information):

-  WordPress version: [ 6.2.2 running ]
-  WooCommerce version: [ 7.9.0 ]
-  WooCommerce Blocks version: [ by default installed ]
-  Site language: English
-  Any other plugins installed: No

### Desktop (please complete the following information):

-   OS: [ macOS ]
-  Browser [ chrome ]

**Comment by albarin** [comment]
Thanks for reporting this @VipulUpadala! 👍 
It does look like a bug, we'll add it to the backlog.
