### ISSUE TITLE
All Products block does not update the cart

### ISSUE THREAD

**Issue by jorgemd24** [woocommerce/woocommerce-gutenberg-products-block#10470]
## Describe the bug

When you try to add a product to the cart using the All Products block, the cart doesn't get updated, and this can lead to a confusing situation for the customer.

https://github.com/woocommerce/woocommerce-blocks/assets/2488994/cd22990c-c072-411c-9439-f26fde6f803f

## To reproduce

1. Create a page using the All Products blocks.
2. Add a product to the cart.
3. Check if the product has been added to the cart.

## Expected behavior

The cart should be updated.

### WordPress (please complete the following information):

-   WordPress version: 6.2.2
-   Gutenberg version (if installed): [e.g. 12.0.0]
-   WooCommerce version: 7.9.0
-   WooCommerce Blocks version: 10.9.0-dev 
-   Site language:
-   Any other plugins installed: AutomateWoo and Google Listings & Ads.

### Desktop (please complete the following information):

-   OS: macOS
-   Browser Chrome
-   Version [e.g. 22]

### Smartphone (please complete the following information):

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Comment by gigitux** [comment]
Thanks for opening this issue!
In the near future, the `All Products` block will de deprecated. The merchant should use the `Products` block. 

Given the upcoming changes, I will close this issue. However, if you have any further questions or need to continue the discussion, please don't hesitate to reach out.
