### ISSUE TITLE
Patterns with content powered by AI in WooCommerce Blocks

### ISSUE THREAD

**Issue by nefeline** [woocommerce/woocommerce-gutenberg-products-block#10503]
This issue describes the planned technical implementation for updating WooCommerce Blocks patterns to have AI-powered content and AI-managed images.

# The Scope

The goal for the MVP of this project is to have the images for patterns populated with Verticals (which is an API built to help designers and developers choose vertical-specific images for use in templates and automatically generated content). The displayed images should dynamically change depending on what the user decides to add as a description for their business in the following field:

<img width="1490" alt="Screenshot 2023-08-07 at 19 01 37" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/93bfd7fe-f985-4c68-a001-c8d6118b1674">

Originally implemented on https://github.com/woocommerce/woocommerce/pull/38920 , this AI settings screen is still not available to all users in the core of WooCommerce, but soon it will be. In the meantime, we can work with the knowledge that this setting is saved in the DB and will be used to feed the prompt to generate the AI content in patterns.

In addition to the images, we should also ensure the content of each one of our patterns is dynamically changed depending on this setting.

# The Implementation Details

Based on my initial discovery work, the following implementation path is proposed to ensure we achieve the goals of this project with optimal performance.

| AI managed Images flow | AI generated Content flow |
| ------ | ----- |
|  <img width="570" alt="Screenshot 2023-08-08 at 12 21 08" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/ce36cf2e-a438-4bec-be08-503eb0494d0f"> | <img width="570" alt="Screenshot 2023-08-08 at 12 27 24" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/07a980b1-cdaa-4b7e-90ad-9be274321647"> |

## Step 1: Introduce a new Patterns Dictionary

Based on initial exploration, it was possible to identify that, at a minimum, the following information is required from each one of our patterns:

* Total number of Images
* Format of the Images required: `'square'`, `'landscape'` or `'portrait'`
* Total number of titles
* Short description of the content expected in the titles
* Total number of descriptions
* Short description of the content expected in the descriptions

These are handy for either creating the prompt for the AI to generate content or to manipulate the data received from external services (e.g. fetch all relevant images from the Verticals API for a given store category in a single request and later on just assign them to be used on specific patterns depending on the format the pattern is expecting).

This dictionary containing info regarding all existing patterns will be stored in our codebase.

## Step 2: Fetch the list of all available verticals via API and ask the AI which one is the best fit considering the provided business description. Store this info.

The Verticals API has an endpoint `v2/site-verticals` that allows us to fetch the complete list of all available verticals, informing whether the given image category has any vertical images in it or not and their ID:

```json
{
  "id": "3",
  "parent_id": "0",
  "root_id": "3",
  "name": "Arts & Entertainment",
  "title": "Arts & Entertainment",
  "has_vertical_images": true
}
```

After narrowing down the results to only categories that contain vertical images, we can combine this info with what the user added as a description of their business in the AI settings screen and compose a prompt to AI, such as:

_**Filter the objects provided below and return the ones that have a title that better matches this description of an online store: "An online store that sells arts and paintings".**_ 

This prompt should narrow the list of available verticals to at least one option. If no object is returned, we should assign a default (cc: @verofasulo since we have discussed/agreed on this yesterday during our call, tagging you for awareness in case you wanna share any thoughts).

## Step 3: Fetch all images for a given vertical based on the provided ID (obtained on step 2).

Having the vertical IDs in hand, a second API request is now required to fetch the images via `v2/site-verticals/{vertical_ID}/images`. The expected result for each one of the images is as follows:

```json
{
  "ID": 4102,
  "guid": "http://wpcomverticals.files.wordpress.com/2023/03/pexels-photo-6899776.jpeg",
  "post_title": "Woman Standing Behind Red Curtain",
  "post_excerpt": "",
  "post_content": "",
  "alt": "",
  "width": 1880,
  "height": 1253,
  "size": "119.41 KB",
  "filename": "pexels-photo-6899776.jpeg",
  "extension": "jpeg",
  "meta": {
  "vertical_id": "3",
  "pexels_object": {
  "id": 6899776,
  "width": 6000,
  "height": 4000,
  "url": "https://www.pexels.com/photo/woman-standing-behind-red-curtain-6899776/",
  "photographer": "cottonbro studio",
  "photographer_url": "https://www.pexels.com/@cottonbro",
  "photographer_id": 1437723,
  "avg_color": "#481214",
  "src": {
  "original": "https://images.pexels.com/photos/6899776/pexels-photo-6899776.jpeg",
  "large2x": "https://images.pexels.com/photos/6899776/pexels-photo-6899776.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  "large": "https://images.pexels.com/photos/6899776/pexels-photo-6899776.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "medium": "https://images.pexels.com/photos/6899776/pexels-photo-6899776.jpeg?auto=compress&cs=tinysrgb&h=350",
  "small": "https://images.pexels.com/photos/6899776/pexels-photo-6899776.jpeg?auto=compress&cs=tinysrgb&h=130",
  "portrait": "https://images.pexels.com/photos/6899776/pexels-photo-6899776.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "landscape": "https://images.pexels.com/photos/6899776/pexels-photo-6899776.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "tiny": "https://images.pexels.com/photos/6899776/pexels-photo-6899776.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280"
  },
  "liked": false,
  "alt": "Woman Standing Behind Red Curtain"
  },
  "tag_names": [],
  "source_url": "",
  "photographer": ""
  }
}
```

## Step 4: Assign the fetched images to patterns according to their requirements when it comes to formats.

Now it is time to assign the returned images to each one of our patterns: based on the dictionary created in step 1, we know that, for example, the `Social: Follow us in social media` pattern requires four images with a `square` format. By relying on a conditional as simple as:

```php
$image_urls  = array();
foreach ( $decoded_verticals as $decoded_vertical ) {
  if ( count( $image_urls ) >= $required_images ) {
	  break;
  }
  
  if ( ! isset( $decoded_vertical->guid ) || ! isset( $decoded_vertical->width ) || ! isset( $decoded_vertical->height ) ) {
	  continue;
  }
  
  if ( 'square' === $required_format && $decoded_vertical->width !== $decoded_vertical->height ) {
	  continue;
  } elseif ( 'landscape' === $required_format && $decoded_vertical->width <= $decoded_vertical->height ) {
	  continue;
  } elseif ( 'portrait' === $required_format && $decoded_vertical->width >= $decoded_vertical->height ) {
	  continue;
  }
  
  $image_urls[] = str_replace( 'http://', 'https://', $decoded_vertical->guid );
}
```
We can then store this information as an option in the database to be fetched by the pattern whenever previewed or inserted (see the "Other considerations" section below to better understand the reason why we should be fetching from a DB option instead of making the API requests on the fly for each one of the patterns). An example of how images could be populated in patterns is as follows:

```php
<img src="<?php echo isset( $image_urls[0] ) ? esc_url( $image_urls[0] ) : esc_url( plugins_url( 'images/pattern-placeholders/office.png', dirname( __FILE__ ) ) ); ?>" alt="<?php esc_attr_e( 'Placeholder image used to represent products being showcased as furniture in an office.', 'woo-gutenberg-products-block' ); ?>" />
```
Notice how there's still a fallback to the pre-existing images in our codebase, those will be used only as a last resort, if the user doesn't have an internet connection available. For all other cases, the images displayed will correspond to either the ones defined as suitable by the AI or, if none is provided, a predefined default category will be used instead.

## Step 5: Ask AI to generate all pattern content (titles and descriptions) based on the provided business description and the patterns dictionary.

A very similar path to the one above described for images can be followed for generating content: knowing the number of titles and descriptions required for a given pattern and having a brief description of their expected content, we can prompt AI with this information and also store the returned results for each one of the patterns in the same option the images were saved (in a dictionary format) and use that to populate the content of patterns later on.

# Other considerations

- At which point in the execution are we planning to make these API requests to both the AI and the Verticals APIs? Those should happen whenever the user adds or changes their business description on the AI settings page. My proposal is to do those async via Action Scheduler for optimal performance. For users who already have this setting filled out prior to the release of the feature described here, we can also schedule an action to run just once to take care of these requests.

- Why not make the API requests for each one of the patterns on the fly right before they are inserted in the editor? Because patterns are loaded every time the editor is accessed, independent of their usage. To avoid sacrificing the editor's performance, fetching from an option in the DB is way less expensive and reliable.

- I can anticipate we will spend some time experimenting with prompts for the AI until we reach optimal and consistent results.

# Conclusion

With the proposed implementation path described above, we have a solid architecture to support patterns with AI-powered content. There are still some details to narrow down, especially regarding the usage of the AI API endpoints: those should be cleared out within the next few days.

Tagging @adrianduffell @verofasulo @chihsuan @jarekmorawski @shaunandrews @chrisdesrochers @nerrad @danielwrobert and @tjcafferkey for awareness and your input in case of any questions or concerns.

**Comment by adrianduffell** [comment]
@nefeline Nice work, this is a great explanation of the scope for this. Thank you!

All looks really good but just adding a few clarifications. cc @chihsuan for thoughts too

> A very similar path to the one above described for images can be followed for generating content: knowing the number of titles and descriptions required for a given pattern and having a brief description of their expected content, we can prompt AI with this information and also store the returned results for each one of the patterns in the same option the images were saved (in a dictionary format) and use that to populate the content of patterns later on.

The other content generation (titles and descriptions) is planned by Ghidorah, however I think we need to co-ordinate on how to how to populate the patterns. I think Ghidorah could save this content into the option (with the dictionary format). Would you then have a final process that retrieves all the content from the option and populates it into the patterns on the site? 

One consideration here is that it will be safe to overwrite existing editor content. For MVP, we will only be dealing with "fresh" sites without existing content. Post-MVP, the plan is to detect established sites and warn about the previous design being overwritten.

> At which point in the execution are we planning to make these API requests to both the AI and the Verticals APIs? Those should happen whenever the user adds or changes their business description on the AI settings page. My proposal is to do those async via Action Scheduler for optimal performance

It would need to be executed during the loading screen, so that when the loading screen finishes the user moves to the design hub and sees the preview of the site with the content populated. This would probably need to be done via REST API request from the JS client side but open to ideas. cc @chihsuan do you have thoughts on this?

Also, we won't need to execute it when the AI settings screen changes. These settings are more envisioned to apply to future AI-generated content. The goal of the setting is to support similar prompts being used in Woo's various AI features. For example, the Woo onboarding will save data about the tone, and then a products feature can read it back later and specify the same tone in prompts.

**Comment by nefeline** [comment]
> I think Ghidorah could save this content into the option (with the dictionary format). 

Sounds like a plan!

> Would you then have a final process that retrieves all the content from the option and populates it into the patterns on the site?

Absolutely, updating all existing patterns is already part of my proposed implementation here. It corresponds to step 4: **Assign the fetched images to patterns according to their requirements when it comes to formats.**

> One consideration here is that it will be safe to overwrite existing editor content. For MVP, we will only be dealing with "fresh" sites without existing content. Post-MVP, the plan is to detect established sites and warn about the previous design being overwritten.

Sounds good; I'll make sure to add this restriction to new stores at this first moment (with a follow-up task for implementing a warning for established sites later on).

> It would need to be executed during the loading screen, so that when the loading screen finishes the user moves to the design hub and sees the preview of the site with the content populated. This would probably need to be done via REST API request from the JS client side but open to ideas.

Is this part of the new/upcoming Pattern Assembler flow? I based this implementation on what we currently have within Woo Blocks for the MVP, where we don't have a loading screen, as patterns are independent of the initial onboarding. Maybe we could implement this part in phase two, as soon as the Assembler is part of the core? WDYT?

> Also, we won't need to execute it when the AI settings screen changes. These settings are more envisioned to apply to future AI-generated content. The goal of the setting is to support similar prompts being used in Woo's various AI features. For example, the Woo onboarding will save data about the tone, and then a products feature can read it back later and specify the same tone in prompts.

Do you mind clarifying this part, please? If the user said they were selling flowers on the initial flow and later on they updated the description to say they are now selling candies, don't we want the content in patterns to reflect that change? I can imagine it is not uncommon for users to just fill out this field with some info that is not an accurate description of their store at the beginning and update that later. One important note here is: this change would not affect patterns that were already inserted in the editor by the user, just the new ones inserted after the description was changed.

**Comment by chihsuan** [comment]
Thanks for the comprehensive explanation! 👍  @nefeline 

> It would need to be executed during the loading screen, so that when the loading screen finishes the user moves to the design hub and sees the preview of the site with the content populated. 

I agreed.

> This would probably need to be done via REST API request from the JS client side but open to ideas. cc @chihsuan do you have thoughts on this?

I think we can create an API like `/populate-patterns` for the client side that calls it with a business description during the loading screen. Then, the backend can send requests to verticals and AI APIs.

> Is this part of the new/upcoming Pattern Assembler flow? 

Yes 🙂, Adrian was referring to this loading screen (Mrk6SERPZ4KrFHSjM0a8TK-fi-2752_261089).

> Maybe we could implement this part in phase two, as soon as the Assembler is part of the core? WDYT?

I think it's okay to use the settings screen as an entry point for now and testing since AI onboarding hasn't been implemented yet.

>  My proposal is to do those async via Action Scheduler for optimal performance. For users who already have this setting filled out prior to the release of the feature described here, we can also schedule an action to run just once to take care of these requests

In the Pattern Assembler flow, we should make it synchronous or have a way to confirm its completion so that the loading page can work properly. I think a simple way is to have a flag to run with Action Scheduler or not.

**Comment by nefeline** [comment]
> Yes 🙂, Adrian was referring to this loading screen ([Mrk6SERPZ4KrFHSjM0a8TK-fi-2752_261089](https://href.li/?https://www.figma.com/file/Mrk6SERPZ4KrFHSjM0a8TK/?node-id=2752-261089)).

> In the Pattern Assembler flow, we should make it synchronous or have a way to confirm its completion so that the loading page can work properly.

Thanks for confirming! I wasn't aware of this new design for the upcoming onboarding flow.

With that said, regarding:

> I think we can create an API like /populate-patterns for the client side that calls it with a business description during the loading screen. Then, the backend can send requests to verticals and AI APIs.

I agree creating a dedicated endpoint makes sense.

> I think it's okay to use the settings screen as an entry point for now and testing since AI onboarding hasn't been implemented yet.

👍 Sounds like a plan! Regarding the implementation after we introduce the AI onboarding: as noted in my last comment on https://github.com/woocommerce/woocommerce-blocks/issues/10503#issuecomment-1677001965 , I believe it would make sense to have both in place so that the patterns will be populated during onboarding, but also have their content updated if the store owner completely changes their business description later on in the settings (knowing that this change would not affect patterns that were already inserted in the editor by the user, just the new ones inserted after the description was changed). Tagging @verofasulo @adrianduffell for your input.

**Comment by adrianduffell** [comment]
> I believe it would make sense to have both in place so that the patterns will be populated during onboarding, but also have their content updated if the store owner completely changes their business description later on in the settings (knowing that this change would not affect patterns that were already inserted in the editor by the user, just the new ones inserted after the description was changed)

Agree, sorry I think I misunderstood before! We can treat the settings as the source of truth. So if the user makes a business description change in the settings, future patterns would use this answer instead of the one originally provided in the onboarding.

**Comment by nefeline** [comment]
> Agree, sorry I think I misunderstood before! We can treat the settings as the source of truth. So if the user makes a business description change in the settings, future patterns would use this answer instead of the one originally provided in the onboarding.

Np at all! Thanks for the confirmation, I'm starting to create the individual issues for the implementation now 🎉 .

**Comment by nefeline** [comment]
This work is now complete. For future reference, we have replaced the requests to the Verticals API with requests to Pexels instead: https://github.com/woocommerce/woocommerce-blocks/pull/11280. This feature will be available on WooExpress in this first moment.
