### ISSUE TITLE
Add something to customize the customer-account menu labels...

### ISSUE THREAD

**Issue by webaxones** [woocommerce/woocommerce-gutenberg-products-block#10506]
I want to customize My Account menu labels.
to be able to display:

"Hello, Dizzy Gillespie" when Dizzy is connected, or "Sign in" when no one is connected.

Currently there is no hook to do this. And there is no field under the settings to do this.

![image](https://github.com/woocommerce/woocommerce-blocks/assets/17084006/1d3db87a-1917-4032-8ea4-05eb01b0d2dd)

![image](https://github.com/woocommerce/woocommerce-blocks/assets/17084006/93b489cb-f678-4c3d-aa82-6688068eeed2)

**Comment by albarin** [comment]
Hey @webaxones thanks for your feedback on the `My Account` block. It's a great suggestion, we are planning on making improvements to the block and we'll definitely take this into account when working on it.
Thanks again!
