### ISSUE TITLE
Duplicated Product Title with Product Collection enabled

### ISSUE THREAD

**Issue by kmanijak** [woocommerce/woocommerce-gutenberg-products-block#10525]
### Background
Product Collection provides its own variation of blocks:
- Product Title (`core/post-title`)
- Product Summary (`core/post-excerpt`)

This is the same approach as Products (Beta) block does.
Unfortunately, that results in the block being duplicated in the inserter.

### Steps to reproduce
1. In the dev build go to Editor
2. In the inserter type "Product Title"

Expected: there's a single block available
Actual: there are two blocks available
<img width="351" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/20098064/5fcebed4-852e-43aa-b9c4-e33241d9cdbb">

### Additional notes
The same shall happen for Product Summary, however, most likely it's not active due to [this check](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/blocks/product-collection/variations/elements/utils.tsx#L22C17-L22C61).

**Comment by imanish003** [comment]
Marking this issue as resolved since it was addressed in #10548. CC: @kmanijak
