### ISSUE TITLE
Use the <header> element for the checkout header

### ISSUE THREAD

**Issue by carolinan** [woocommerce/woocommerce-gutenberg-products-block#10558]
## Describe the bug

The checkout template uses the checkout header template part, but it is set to use `<div>`, please consider using `<header>`.
Compare this with the cart and order information templates that use `<header>` for the standard header template part.

https://github.com/woocommerce/woocommerce-blocks/blob/trunk/templates/templates/checkout.html#L1
https://github.com/woocommerce/woocommerce-blocks/blob/trunk/templates/templates/cart.html#L1

## To reproduce

1. Open the checkout template in the Site Editor and select the checkout header template part, open the Advanced panel, and confirm that it uses a div not header.

## Expected behavior
I expect the header to use the header element.

## Screenshots
The header template part in the checkout template, with div pre-selected in the HTML element option:
<img width="1508" alt="" src="https://github.com/woocommerce/woocommerce-blocks/assets/7422055/838473d0-f7a7-460c-876f-00fda604c7c3">

### WordPress (please complete the following information):

-   WordPress version: 6.3.0
-   WooCommerce version: 8.x

## Additional context

Kindly go through the remaining templates and confirm that they too, are as accessible as possible.

Related: 
https://github.com/woocommerce/woocommerce-blocks/issues/10557

**Comment by ralucaStan** [comment]
Thank you @carolinan, we will soon work on this change.
We'd also appreciate help from contributors who want to give a helping hand by working on a quick win task.

**Comment by wavvves** [comment]
temporarily blocked by #10773

**Comment by mikejolley** [comment]
The fix in https://github.com/woocommerce/woocommerce-blocks/pull/11222 did not work with the default templates despite being set to `<header>` in the editor. Moving to the current sprint to be worked on again.

**Comment by danieldudzic** [comment]
https://github.com/woocommerce/woocommerce-blocks/pull/11222 has been removed from the 11.4.0 release.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce-blocks/pull/11222#issuecomment-1788824563
