### ISSUE TITLE
Use the main element in all block templates

### ISSUE THREAD

**Issue by carolinan** [woocommerce/woocommerce-gutenberg-products-block#10557]
## Describe the bug

The cart and checkout templates should use the `<main>` HTML element as the outer wrapper instead of a `<div>.`
- The order confirmation template already uses the main element.

## To reproduce

1. Open each template in the Site Editor
2. Select the outer group block and all the inner blocks and confirm neither uses the `<main>` HTML element.

## Expected behavior

Each template must have one `<main>` element.
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/main_role

### WordPress (please complete the following information):

-   WordPress version: 6.3.0
-   WooCommerce version: 8.

### Desktop (please complete the following information):

-   OS: macOS
-   Browser Chrome

**Comment by ralucaStan** [comment]
Thank you @carolinan, we will soon work on this change.
We'd also appreciate help from contributors who want to give a helping hand by working on a quick win task.

**Comment by wavvves** [comment]
temporarily blocked by #10773
