### ISSUE TITLE
WooCommerce "woocommerce_product_get_price" hook

### ISSUE THREAD

**Issue by humandev9999** [woocommerce/woocommerce-gutenberg-products-block#10560]
## Describe the bug

Hi there! I'm using the "woocommerce_product_get_price" hook to alter the price of products and everything is working perfectly, from display on all shop pages, to cart/checkout/thankyoupage/email process.
In the minicart block instead it seems that the hook is not fired in any way. In fact, as soon as I add the product to the cart, the minicart displays the price I changed ("/?wc-ajax=get_refreshed_fragments" is called), but if I click on the minicart button, or even just in hover, "/wp -json/wc/store/v1/cart?_locale=user" and the price goes back to the default one.

## To reproduce

1. Use TwentyTwentyTwo as theme
2. Add minicart block in header, in "Appearance -> Editor -> Templates parts -> Header"
3. Alter price with "woocommerce_product_get_price" hook, for example purpose:
<code>
add_filter( 'woocommerce_product_get_price', function($price, $object) {
if (is_user_logged_in()) { return 9999; } // Fake price
return $price;
}, 10, 2 );
</code>
5. In frontend, try to add a product to cart

## Expected behavior

In minicart I expect 9999 as product price but when I click on minicart, price change to product default price

### WordPress (please complete the following information):

-   WordPress version: 6.3
-   WooCommerce version: 7.9.0
-   Site language: EN
-   Any other plugins installed: Copy & Delete Posts,Elementor,iThemelandCo WooCommerce Product Table,Limit Login Attempts Reloaded,LoginPress - Customizing the WordPress Login Screen.,Members,SiteOrigin CSS,User Login History,WooCommerce,WooCommerce B2B

**Comment by senadir** [comment]
I'm unable to reproduce this given the filter you provided


https://github.com/woocommerce/woocommerce-blocks/assets/6165348/c4e4285e-e921-4b98-9c77-56a78b61a81d

**Comment by mikejolley** [comment]
Since we haven't heard back I will close this issue. FWIW I was also unable to replicate this with the mini cart inserted into my homepage template.

![Screenshot 2023-09-05 at 12 18 33](https://github.com/woocommerce/woocommerce-blocks/assets/90977/c7a7f943-6173-4740-b070-709fe9f580a8)
