### ISSUE TITLE
Rating Filter: Optimize to prevent re-rendering

### ISSUE THREAD

**Issue by roykho** [woocommerce/woocommerce-gutenberg-products-block#10579]
This issue is to explore any areas of the filter that is causing unnecessary re-rendering. We want to remove it to gain performance.

**Update**

Based on the two discussions seen [here](https://github.com/woocommerce/woocommerce-blocks/discussions/10678) and [here](https://github.com/woocommerce/woocommerce-blocks/discussions/10691) we've decided to have filters available only in the context of a product collection block. This makes it much easier for us to tackle this issue because now we have direct context access to the product collection block.

In addition, each filter will also live inside a wrapper container called Collection Filters which the initial draft is created https://github.com/woocommerce/woocommerce-blocks/pull/10726

So for now we're creating new experimental filter that lives in `assets/js/blocks/collection-filters/inner-blocks`

**Comment by dinhtungdu** [comment]
Closing this one as we're working on new filter blocks powered by Interactivity API.
