### ISSUE TITLE
Add documentation outlining how to add a field to the checkout block, and how to process that in the checkout POST request.

### ISSUE THREAD

**Issue by opr** [woocommerce/woocommerce-gutenberg-products-block#10571]
There is no specific documentation to show how a developer can extend the checkout endpoint to receive additional data from a new inner block.

While there is https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/rest-api/extend-rest-api-add-data.md#things-to-consider, this seems focused on _outputting_ data.

We should create a new document, or edit to the existing one linked above to include information on how this can be done.

**Comment by tarhi-saad** [comment]
Hi, @opr! Do we have an example where this is used (e.g., an extension that adds a field to the Checkout block)?

**Comment by opr** [comment]
@tarhi-saad you may check the https://developer.woocommerce.com/2023/08/07/extending-the-woocommerce-checkout-block-to-add-custom-shipping-options/ tutorial for an example!
