### ISSUE TITLE
Add a real-life use case to the 'Adding an endpoint to ExtendSchema' documentation

### ISSUE THREAD

**Issue by opr** [woocommerce/woocommerce-gutenberg-products-block#10581]
We should move https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/rest-api/extend-rest-api-new-endpoint.md out of the `third-party-developers` folder because this document is aimed at internal developers.

As part of this issue, we can add a use-case to the document to show an example of when adding a new endpoint might be necessary.

**Comment by nielslange** [comment]
Just noting that https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/rest-api/extend-rest-api-new-endpoint.md had been moved to https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/rest-api/extend-rest-api-new-endpoint.md with #10926.
