### ISSUE TITLE
Filter blocks: Interactivity API

### ISSUE THREAD

**Issue by roykho** [woocommerce/woocommerce-gutenberg-products-block#10582]
For the filter blocks `Attributes`, `Stock`, `Price` and `Rating`, we want to explore if we can utilize the interactivity API to power the interactions on the frontend for performance gain and better UX.

Based on this exploration, we will create separate issues for each filter to implement.

**Update**

Based on the two discussions seen [here](https://github.com/woocommerce/woocommerce-blocks/discussions/10678) and [here](https://github.com/woocommerce/woocommerce-blocks/discussions/10691) we've decided to have filters available only in the context of a product collection block. This makes it much easier for us to tackle this issue because now we have direct context access to the product collection block.

In addition, each filter will also live inside a wrapper container called Collection Filters which the initial draft is created https://github.com/woocommerce/woocommerce-blocks/pull/10726

So for now we're creating new experimental filter that lives in `assets/js/blocks/collection-filters/inner-blocks`

**Comment by dinhtungdu** [comment]
Relates #8456.

**Comment by roykho** [comment]
Closing this to break down separate issues for each of the filters so they can be worked in parallel.
