### ISSUE TITLE
Delayed Visual Feedback and Race Condition in Cart Block Quantity Update

### ISSUE THREAD

**Issue by nate-allen** [woocommerce/woocommerce-gutenberg-products-block#10593]
## Describe the bug

There are two interrelated issues when updating the quantity of a product in the Cart block:

Delayed Visual Feedback: Upon adjusting the quantity (using the <kbd>+</kbd> or <kbd>-</kbd> buttons), there's a noticeable delay before the cart updates the total price. During this gap, the user receives no visual indication that their action is being processed.

Race Condition on Multiple Clicks: When the quantity buttons (<kbd>+</kbd> or <kbd>-</kbd> buttons) are clicked multiple times in succession, it sends multiple asynchronous requests. These requests can potentially complete out of order, leading to the cart displaying an incorrect final quantity. For instance, clicking <kbd>+</kbd> three times might send requests with quantities of 2, 3, and 4. If they're processed out of order, the cart may first display 4 but then revert to 3 as the final quantity.

Disabling the quantity field until the response is received could solve both of these issues.

## To reproduce

For Delayed Visual Feedback:

1. Add a product to the cart and go to a page with the Cart block displayed.
2. In the Cart block, click the <kbd>+</kbd> button to increase the quantity.
3. Observe the delay before the total price updates.

For Race Condition:

1. Add a product to the cart and go to a page with the Cart block displayed.
2. In the Cart block, click the <kbd>+</kbd> button multiple times.
3. Observe the cart quantity fluctuating unpredictably, not always reflecting the number of clicks.

## Expected behavior

After adjusting the quantity, there should be immediate visual feedback (e.g., a loading spinner or a change in opacity) to indicate the change is being processed. This feedback should persist until the updated price or quantity is displayed.

The cart should always reflect the final state corresponding to the user's last action.

## Screenshots

![Screen Capture on 2023-08-14 at 14-09-48](https://github.com/woocommerce/woocommerce-blocks/assets/8797898/f7ce9eda-9923-43e2-abec-05860d70e027)

### WordPress:

-   WordPress version: 6.3
-   WooCommerce version: 8.0.1
-   Site language: English
-   Any other plugins installed: No

### Desktop:

-   OS: macOS
-   Browser Chrome
-   Version 115.0.5790.170

**Comment by senadir** [comment]
Thank you for reporting this! this is a known issue and we have some solutions to fix it, but I think mainly:
- Removing the debounce delay (the delay you see between clicking the quantity update and the request being sent to the server). Once the request is in transit, the proceed to Checkout button is actually blocked.
- Cancel existing requests in favor of the last request, this is something [I prototyped](https://github.com/woocommerce/woocommerce-blocks/compare/trunk...try/cancel-request-middleware) and we will probably polish and publish.

**Comment by ralucaStan** [comment]
This was fixed for the Cart Block in #10472. Thank you for your report @nate-allen
