### ISSUE TITLE
The checkout template is not displayed in the site editor navigation if no items were added to cart.

### ISSUE THREAD

**Issue by nefeline** [woocommerce/woocommerce-gutenberg-products-block#10597]
## Describe the bug

The display of the Checkout template in the editor is conditioned by the presence of products in the cart: If the logged-in user has products in their cart, the template is displayed as expected; if they don't, a blank page is returned instead.

## To reproduce

1. Make sure your cart is empty
2. Head over to `Edit Site > Design - Navigation > Navigation`
3. Click on the Checkout. When the following message appears, click on **Edit**:

<img width="497" alt="Screenshot 2023-08-15 at 11 08 48" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/1b73ab64-1de1-44b2-b460-96d3c9bb132c">

4. On the sidebar menu, click on **Go to Checkout**.
5. Notice how the screen is empty, and the checkout template is not displayed at all.
6. Now access your store and add a product to your cart.
7. Repeat steps 2, 3 and 4
8. Notice how the Checkout template is now correctly displayed.

## Expected behavior

The display of the checkout template in the editor should be independent of the number of products the currently logged-in user has in their cart.

## Screenshots

https://github.com/woocommerce/woocommerce-blocks/assets/15730971/c05d2de4-cdac-4ca9-a07d-d4618f1e6db8

### WordPress (please complete the following information):

-   WordPress version: [6.3]
-   WooCommerce version: [8.1.0-dev]
-   WooCommerce Blocks version: [10.9.0-dev]

**Comment by nefeline** [comment]
FYI: in addition to the issue flagged above, if you proceed to edit the checkout template (with items in your cart), you will notice that it is also impossible to edit it (the block is not even listed in the available options). This is reproducible with the Cart and Checkout page: if you take another page, such as the Shop (with the product catalog template), everything works as expected:

https://github.com/woocommerce/woocommerce-blocks/assets/15730971/1a28307e-634f-414e-9a6b-35e4d8870c95

cc: @ralucaStan

**Comment by ralucaStan** [comment]
@nefeline would you mind creating a separate issue for this last bug you found? Thank you so much.

**Comment by nefeline** [comment]
@ralucaStan done! https://github.com/woocommerce/woocommerce-blocks/issues/10635

**Comment by ralucaStan** [comment]
Thank you @nefeline

**Comment by ralucaStan** [comment]
This issue is no longer replicable
