### ISSUE TITLE
Gutenberg Product Block

### ISSUE THREAD

**Issue by darrenbowen** [woocommerce/woocommerce-gutenberg-products-block#106]
Gutenberg Product Block is not available to utilize despite being installed along with the Gutenberg editor. 
<img width="434" alt="screen shot 2018-08-31 at 1 51 11 pm" src="https://user-images.githubusercontent.com/12937575/44928157-f5db0680-ad24-11e8-827e-866689e1b71e.png">

**Comment by sinegrain** [comment]
Same here after the last gutenberg update 3.7, 
below the console error:

```
Uncaught TypeError: withAPIData is not a function
    at Object.defineProperty.value (products-block.js?ver=1.1.1:1500)
    at __webpack_require__ (products-block.js?ver=1.1.1:20)
    at Object.defineProperty.value (products-block.js?ver=1.1.1:79)
    at __webpack_require__ (products-block.js?ver=1.1.1:20)
    at products-block.js?ver=1.1.1:63
    at products-block.js?ver=1.1.1:66
```

it is related to withAPIData which has been removed from 3.7

as mentioned [here](https://github.com/WordPress/gutenberg/blob/master/docs/reference/deprecated.md#370) @wordpress/data has to be used instead

**Comment by pablogiralt** [comment]
Same here

**Comment by HeatherKW** [comment]
same here

**Comment by warrendholmes** [comment]
Confirmed this is an issue. Good news is that existing blocks still work on the front end (because they're shortcodes I assume?).

Frontend on my store :
https://cloudup.com/cm70RTbB5vy

The existing block reverts to a classic block with the shortcode:

https://cloudup.com/c9BKJm9mpvi
