### ISSUE TITLE
Product Blocks not Responsive

### ISSUE THREAD

**Issue by SiR-DanieL** [woocommerce/woocommerce-gutenberg-products-block#1060]
**Describe the bug**

On mobile, the  products block does not show  one product  per row, but multiple columns.

**To Reproduce**
1. Go to a new pae
2. Add a Hand-Picked product block
3. See error on mobile

**Screenshots**

![](http://d.wedj.at/6KvJq0+)
**Image Link**: http://d.wedj.at/6KvJq0+

**Expected behavior**

I'd expect to see a single column, maybe 2.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by pmcpinto** [comment]
@daveloodts this issue was already moved to the WC blocks repo. We're going to see if we can include this fix in the upcoming WooCommerce Blocks plugin release.

**Comment by afgitxx** [comment]
Hi guys, when can we expect this bugfix? Its been a few weeks since this issue was closed and still doesnt work for me. Thanks
