### ISSUE TITLE
Possible performance degrade due to `read_zone_locations()` when `_woocommerce_shipping_zone_locations` table is large

### ISSUE THREAD

**Issue by kaushikasomaiya** [woocommerce/woocommerce-gutenberg-products-block#10601]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

6596398-zen

Merchant has about 98766 rows in _woocommerce_shipping_zone_locations table.

The `read_zone_locations()` function particularly is slowing down the loading of Shipping Zones page in WP Admin.

Upon investigation, it is found that:

1. The read_zone_locations() function is called repeatedly for some reason  (Could be due to multiple zones perhaps)
2. This particular block is consuming time: https://github.com/woocommerce/woocommerce/blob/05dfaacd37700e89a2903fc85f01e89919a90e9c/plugins/woocommerce/includes/data-stores/class-wc-shipping-zone-data-store.php#L336C1-L340C4
3. The SQL read consumes lesser time though: https://github.com/woocommerce/woocommerce/blob/05dfaacd37700e89a2903fc85f01e89919a90e9c/plugins/woocommerce/includes/data-stores/class-wc-shipping-zone-data-store.php#L329C1-L334C5

Further, it is found that all other WP Admin pages are slowed down due to `read_zone_locations()` called by WC Blocks here: 

https://github.com/woocommerce/woocommerce-blocks/blob/eb7af5204f3f561addc62cec0e944ff956debf26/src/Shipping/ShippingController.php#L68

```
add_action( 'admin_enqueue_scripts', [ $this, 'hydrate_client_settings' ] );
```

Custom logging of time consumed by the SQL read and PHP block above along with stack trace is provided here when a single request is performed for loading Shipping Zones page in WP Admin:

- https://d.pr/n/wu0BWA
- Notice that in one of the calls, the PHP block takes around 33+ seconds. (Search: `INFO Execution time of php = 33.897933006287 sec`)

**Questions:**

1. Is there a chance read performance in read_zone_locations() can be improved for large tables?
2. Should an issue be opened on WC Blocks repo to look into `hydrate_client_settings` affecting performance on other WP Admin pages due to large shipping zone location table?

### For reference, the tests were conducted on the following environment 

WC Version: 8.0.1
REST API Version: ✔ 8.0.1
WC Blocks Version: ✔ 10.6.5
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: ❌ 6.2.2 - There is a newer version of WordPress available (6.3)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.24.0
PHP Version: 7.4.33
PHP Post Max Size: 64 MB
PHP Time Limit: 180
PHP Max Input Vars: 10000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.38-MariaDB-0ubuntu0.20.04.1
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.0.1
WC Database Prefix: wpdv8i_
Total Database Size: 241.25MB
Database Data Size: 177.95MB
Database Index Size: 63.30MB

**Comment by kaushikasomaiya** [comment]
@ralucaStan There's already a separate issue for the WC Blocks part: https://github.com/woocommerce/woocommerce/issues/42257

Just curious if this needs to still stay on Core repo.

**Comment by ralucaStan** [comment]
Thank you @kaushikasomaiya for reporting this performance impact. Let's keep the issue in the Blocks repo, as this is where it would be fixed.

**Comment by kaushikasomaiya** [comment]
@ralucaStan Thank you. I see both issues are closed currently - did we intend to keep one active?
