### ISSUE TITLE
Not compatible with Authorize.Net, Large Ecommerce Store Broken

### ISSUE THREAD

**Issue by fuchris** [woocommerce/woocommerce-gutenberg-products-block#10610]
## What do you think is missing from the Cart & Checkout blocks?
Not compatible with Skyverge Authorize.Net payment method.

**Comment by ralucaStan** [comment]
Thanks for reaching out! According to https://github.com/woocommerce/woocommerce/issues/42577 and https://woocommerce.com/document/cart-checkout-blocks-support-status/#section-4, the Authorize.Net payment gateway does not provide support for WooCommerce Blocks yet.

As it's up to the payment service provider to make the extension compatible with WooCommerce Blocks, I recommend reaching out to them for support. We have some [documentation for Third-party developers](https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs#third-party-developers) and some [Developer Resources](https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs#developer-resources) available to help with their integration efforts.

I'll close this issue for now, but I suggest keeping an eye on https://woocommerce.com/document/cart-checkout-blocks-support-status/#section-4 where we list payment extensions that are compatible with WooCommerce Blocks.
