### ISSUE TITLE
Store Customization > Implement Client for requests to the GPT API within WooCommerce

### ISSUE THREAD

**Issue by nefeline** [woocommerce/woocommerce-gutenberg-products-block#10617]
As part of the scope described on https://github.com/woocommerce/woocommerce-blocks/issues/10503 , we need to create a new client for handling the POST requests to the GPT API so it can return us the IDs of the verticals that are a match for a given store:

<img width="542" alt="Screenshot 2023-08-16 at 11 56 25" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/7f0493bf-c8a3-47d3-a0c9-a386d86a4794">

There's a direct dependency between this API and Jetpack, so we will have to be careful with the assumptions we make and be defensive (e.g. always check for the existence of a given function/class before calling it).

### The Scope

- We need to create a new directory under `src/AI` & a new class called `Connection` (or any other preferred/suitable name).
- Within this class, we need to make a POST request to the GPT endpoint. It currently lives within WP.com.
- The "code is the documentation" for this API, so extra investigation is required to identify the shape and form of the body for this POST request.
- To authenticate, we will need to provide a JWT token. We can fetch this from another endpoint on the local site (with Jetpack installed). This will give us a token that lasts for 2 minutes.
- In this first moment, to expedite work, this util will live within WooCommerce Blocks. A separate issue will be created to move it to the core of WooCommerce so other teams/projects working with AI can use the same client for their requests.
- This issue can be considered complete as soon as we can successfully make a POST request to the GPT API. Adapting the prompt and the returned results to our needs and other fine-tuning will be made in separate issues.

Important and details are available on: pdnLyh-44f-p2#comment-2908

**Comment by chihsuan** [comment]
About how to get the token, we could refer to this [`get_openai_jwt`](https://github.com/Automattic/jetpack/blob/0962ee5610ce7753b9448dc2504d547ae8c009ca/projects/plugins/jetpack/_inc/lib/class.core-rest-api-endpoints.php#L776-L794) method or call it directly when Jetpack is installed. 🙂 

Also, note that we can also pass `_fields` parameter to receive only the `completion` field in the response when sending a request to /text-completion endpoint.

**Comment by nefeline** [comment]
> About how to get the token, we could refer to this [get_openai_jwt](https://github.com/Automattic/jetpack/blob/0962ee5610ce7753b9448dc2504d547ae8c009ca/projects/plugins/jetpack/_inc/lib/class.core-rest-api-endpoints.php#L776-L794) method or call it directly when Jetpack is installed. 🙂

> Also, note that we can also pass _fields parameter to receive only the completion field in the response when sending a request to /text-completion endpoint.

Thanks @chihsuan 🙏 ! We will actually have to ensure this feature works without requiring the Jetpack plugin to be installed. We have already made an exploration for relying on the standalone Jetpack package to generate a new `jetpack_id`, all gory details are available on https://github.com/woocommerce/woocommerce-blocks/issues/10699
