### ISSUE TITLE
[Support question] Change markup?

### ISSUE THREAD

**Issue by strarsis** [woocommerce/woocommerce-gutenberg-products-block#1062]
I want to re-use the New Products block but change its HTML markup drastically, it should also support inner blocks. The ,markup is rendered by PHP on the backend, so I thought about re-using (install using composer, require) most of the code from this plugin and then re-use the frontend JS for the block to use a different endpoint for the new markup.

How can I define a new WooCommerce block for customizing the markup with as few extra code (by re-using as much as possible from already used packages) as possible in a new plugin?

**Comment by Aljullu** [comment]
Thanks for the interest @strarsis, currently we are still experimenting with the best way to add extensibility to WooCommerce Blocks, you can read more about it here: https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/891.

Nevertheless, yesterday we released a new version of WooCommerce Blocks, 2.5, which adds a new block named _All Products_  which allows you to list products sorted by _Newest first_ as the _Newest Products_ block, but it also allows you to add inner blocks inside it. You can read more about it in the _Developer customization_ section of the release article:

https://woocommerce.wordpress.com/2019/11/19/wc-blocks-2-5-release-notes/

Feel free to give us any feedback and report bugs if you build a plugin on top of WooCommerce Blocks using this new API.
