### ISSUE TITLE
Impossible to edit the cart and checkout templates in the editor when accessing them via Navigation menu

### ISSUE THREAD

**Issue by nefeline** [woocommerce/woocommerce-gutenberg-products-block#10635]
## Describe the bug

Initially reported on https://github.com/woocommerce/woocommerce-blocks/issues/10597#issuecomment-1678858519 :

When attempting to edit the checkout template, you will notice it is impossible (the block is not even listed in the available options). This is reproducible with the Cart and Checkout pages: if you take another page, such as the Shop (with the product catalog template), everything works as expected:

https://github.com/woocommerce/woocommerce-blocks/assets/15730971/1a28307e-634f-414e-9a6b-35e4d8870c95

## To reproduce

1. If https://github.com/woocommerce/woocommerce-blocks/issues/10597 wasn't solved yet, access your store and add a product to your cart (otherwise you'll just see a blank page in the checkout template).
2. Head over to `Edit Site > Design - Navigation > Navigation`
3. Click on the Checkout. When the following message appears, click on **Edit**:

<img width="497" alt="Screenshot 2023-08-15 at 11 08 48" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/1b73ab64-1de1-44b2-b460-96d3c9bb132c">

4. On the sidebar menu, click on **Go to Checkout**.
5. Start editing the checkout template.
6. Notice how the block is not even listed in the available options.

## Expected behavior

It should be possible to edit the cart and checkout templates on this flow, the same way it is possible to edit the product catalog.

## Environment

-   WordPress version: [6.3]
-   WooCommerce version: [8.1.0-dev]
-   WooCommerce Blocks version: [10.9.0-dev]

**Comment by senadir** [comment]
This seems to have been fixed? as I can edit it just fine. I won't close this yet until someone else confirm @wavvves
