### ISSUE TITLE
Not rendering `[woocommerce_cart]` when inserted to Cart blocks template as Pattern → Template part → Cart template

### ISSUE THREAD

**Issue by webmandesign** [woocommerce/woocommerce-gutenberg-products-block#10643]
## Describe the bug

In my theme I am including new ([WC8](https://developer.woocommerce.com/2023/08/08/woocommerce-8-0-0-released/)) blocks templates (WC8) Cart and Checkout templates.

I like to use the previous design/layout, not blocks, so I'm trying to use old `[woocommerce_cart]` shortcode in the Cart template.

In the template I provide a site header and a site footer and as a content I am using a template part for easier edits by user.

When I put the `[woocommerce_cart]` shortcode directly into my "Cart page content" template part and insert this template part into Cart template, the shortcode is rendered correctly on the front-end of the website when visiting Cart page.

However, as _I need to keep texts in my theme translatable/localizable_, I create a pattern "Cart page content pattern", which I insert into "Cart page content" template part, which is then inserted into Cart template.

Now the `[woocommerce_cart]` shortcode is not rendered on the front-end of the website.

## To reproduce

See above.

## Expected behavior

`[woocommerce_cart]` shortcode (and other shortcodes) should be rendered when inserted via pattern.

### WordPress (please complete the following information):

-   WordPress version: 6.3
-   WooCommerce version: 8.0.2

**Comment by webmandesign** [comment]
Additional info:

You actually don't have to create a template part. Just create a block pattern containing the shortcode and insert the pattern into the Cart template using `<!-- wp:pattern {"slug":"my-theme/cart-page-content-pattern"} /-->`. The result is the same: shortcode is not rendered.

**Comment by ralucaStan** [comment]
@tarhi-saad could you try to replicate this issue?

**Comment by tarunvijwani** [comment]
@webmandesign We tested multiple patterns with different templates and shortcodes. It appears that WordPress does not support shortcodes within patterns in templates. I hope that clears things up, and if you have any further questions – feel free to ask. We’re here to help!

Internal discussion: p1697462135669469-slack-C8X6Q7XQU
