### ISSUE TITLE
Filter by Price Controls block design not compatible for Twenty Twenty-One theme

### ISSUE THREAD

**Issue by VipulUpadala** [woocommerce/woocommerce-gutenberg-products-block#10648]
## Describe the bug

I tested the filter by price controls block with WordPress twenty twenty-one theme and found blocks design are breaking front side.

## To reproduce

1. First Active Twenty Twenty-One theme
2. Create a new page and take the all product block and filter by price controls block.
3. And, Check front side range input design is breaking.

## Expected behavior

Backend side range input design display same design need to be display front side. 

## Screenshots

Video URL: https://share.cleanshot.com/m9NxsyDhZb1lLmdgr0wG

### WordPress (please complete the following information):

-   WordPress version: [6.3]
-   WooCommerce version: [8.0.2]
-   WooCommerce Blocks version: [ by default installed]
-   Site language: English
-   Any other plugins installed: No

### Desktop (please complete the following information):

-   OS: [macOS]
-   Browser [chrome]

**Comment by kmanijak** [comment]
Hi! Thanks for raising it!

I could reproduce and the fix is included in https://github.com/woocommerce/woocommerce-blocks/pull/10732. You can most likely expect that fix in WC Blocks 11.0.0, but please follow the PR for further updates.
