### ISSUE TITLE
"Edit page" link on Cart and Checkout page opens incorrect Site Editor template

### ISSUE THREAD

**Issue by webmandesign** [woocommerce/woocommerce-gutenberg-products-block#10642]
## Describe the bug

In my theme I am including new ([WC8](https://developer.woocommerce.com/2023/08/08/woocommerce-8-0-0-released/)) blocks templates (WC8) Cart and Checkout templates.

However, whenever I click the "Edit page" link in admin bar (or anywhere else), the Site Editor opens WooCommerce native template file for editing, not the one from my theme.

The issue is in the [URL in the code](https://github.com/woocommerce/woocommerce-blocks/blob/v10.9.0/src/Templates/AbstractPageTemplate.php#L64).

## To reproduce

1. In your block theme, create a template `cart.html` with this content:
```html
<!-- wp:paragraph -->
<p>Hi, I am Cart from the theme.</p>
<!-- /wp:paragraph -->
```
2. Go to your Cart page on the front end of your website.
3. In admin bar click the "Edit page" link.
4. Watch how Site Editor opens the `cart.html` template from WooCommerce, not the one we've just created in the theme.

## Expected behavior

When a template is present in the theme, the link should open the theme template for editing, not the WooCommerce one.

### WordPress (please complete the following information):

-   WordPress version: 6.3
-   WooCommerce version: 8.0.2

**Comment by webmandesign** [comment]
BTW, this applies on Checkout template too.

**Comment by ralucaStan** [comment]
@webmandesign thank you so much for your feedback. That behavior is intentional, but we are now taking a closer look at the implementation of cart and checkout templates.

**Comment by webmandesign** [comment]
I don't understand why this is intentional? If a theme provides a template override, user should be able to edit that particular theme template, not the WooCommerce one.

It works with other WooCommerce templates (such as single product template or shop archive template) perfectly fine. (Although it's true they don't open for editing the same way as these new Cart and Checkout templates do.)

**Comment by webmandesign** [comment]
As a theme developer, when my customer opens Cart/Checkout page for editing and sees a different layout than expected (the theme provided Cart/Checkout template), this creates confusion. Naturally, user reports a strange behavior/bug in my theme. And it is very difficult to explain the issue is coming from WooCommerce and how it happens and why.

Please fix this ASAP as this new approach to Cart/Checkout templates is very confusing/buggy. Thank you.

I've created a discussion thread as requested (#10703) and I don't know where else should I rise this issue.

**Comment by webmandesign** [comment]
One more thought:
If this is intentional behavior of modifying theme template hierarchy, at least allow filtering the URL so themes can opt out using PHP code.

**Comment by wavvves** [comment]
Hi @webmandesign, thanks for reaching out. This type of feedback is very important to us, as we use it to correct bugs and re-evaluate our approaches to specific features.

While changes to support theme-level templates are underway, you can actually force using a theme-level template. 

We use priority 1 on the page hierarchy:

```
/**
* When the page should be displaying the template, add it to the hierarchy.
*
* This places the template name, e.g. `cart`, at the beginning of the template hierarchy array. The hook priority
* is 1 to ensure it runs first; other consumers e.g. extensions, could therefore inject their own template instead
* of this one when using the default priority of 10.
*
* @param array $templates Templates that match the pages_template_hierarchy.
*/
```

So, adding a filter with priority 10 for example, will run after our hierarchy manipulation, allowing a theme/extension to inject its own handler for pages. eg:

```
add_filter( 'page_template_hierarchy', 'override_page_template_hierarchy' , 10 );

function override_page_template_hierarchy( $templates ) {
    array_unshift($templates, <your-template> );
	
    return $templates;
}
```
Note: You must wrap or add logic to run this only on your cart/checkout endpoint.

**Comment by webmandesign** [comment]
Hi @wavvves 

Thanks for your feedback. Though, I think there is a misunderstanding here.

The solution with filtering WordPress page template hierarchy does not resolve the issue. Indeed, it applies custom templates that I want, but everything else that WooCommerce modifies stays the same, so it is not usable solution. It is a partial solution.

This specific issue report I've logged is about "Edit page" link opening Site Editor, not the actual page for editing.

![wc-issue-10642](https://github.com/woocommerce/woocommerce-blocks/assets/2456735/abcd5362-0b47-4694-8aef-7aa034948835)

I'm specifically talking about [this method](https://github.com/woocommerce/woocommerce-blocks/blob/v10.9.0/src/Templates/AbstractPageTemplate.php#L58C2-L65C3) (as linked in the issue description above):
```php
/**
 * Returns the URL to edit the template.
 *
 * @return string
 */
protected function get_edit_template_url() {
	return admin_url( 'site-editor.php?postType=wp_template&postId=woocommerce%2Fwoocommerce%2F%2F' . $this->get_slug() );
}
```

Please, allow theme developers to opt out of this new Cart and Checkout page template hierarchy overrides!

**Comment by webmandesign** [comment]
This still doesn't work with WooCommerce 8.1.0

**Comment by ralucaStan** [comment]
@webmandesign that is correct. As this ticket is still open, a fix for it has not been shipped yet. But don't worry, we have been spending some time on the implementation of the templates and we landed on a solution that we are currently testing in https://github.com/woocommerce/woocommerce-blocks/pull/10773; it should land in the next version of WooCommerce.
