### ISSUE TITLE
Store Customization > Schedule an action to update the patterns content whenever the business description is changed

### ISSUE THREAD

**Issue by nefeline** [woocommerce/woocommerce-gutenberg-products-block#10659]
⚠️ This issue can be worked on as soon as https://github.com/woocommerce/woocommerce-blocks/issues/10623 is complete.

Whenever the user changes their business description on the AI settings page, updating the [`'woo_ai_describe_store_description'`](https://github.com/woocommerce/woocommerce/blob/9418072a472b53bd4519086bc1958145600c42ae/plugins/woo-ai/includes/class-woo-ai-settings.php#L39) option, we should schedule an action (via [Action Scheduler](https://actionscheduler.org/)) for triggering the AI content generation in patterns. 

For users who already have this setting filled out prior to the release of the feature developed as part of this project, we should also schedule an action to run just once to take care of these requests and populate the patterns.

**Comment by albarin** [comment]
Completed by https://github.com/woocommerce/woocommerce-blocks/pull/10956
