### ISSUE TITLE
Single Product FSE Template > Product Short Description > line break not kept on front

### ISSUE THREAD

**Issue by Marc-pi** [woocommerce/woocommerce-gutenberg-products-block#10653]
## Describe the bug

Text formating (line break) is not kept // see the below screenshots

## To reproduce

Make sure you use the Single Product FSE template (not the classic one)
Add text with line breaks into the Short Description field of your product

## Expected behavior

Text formating (line break) is not kept

## Screenshots

On backoffice
![image](https://github.com/woocommerce/woocommerce-blocks/assets/919332/dd2da8c4-c041-457b-bdb8-5c6ca99f9f0d)

On front
![image](https://github.com/woocommerce/woocommerce-blocks/assets/919332/560cb8ff-b0c6-4374-a1bf-ee420d425e39)

## Environment

- TT3 theme
- WP 6.3
- WooCommerce 8.0.2
- Woo Block 10.9.1
- Gutenberg 16.4.0

**Comment by Marc-pi** [comment]
same as https://github.com/woocommerce/woocommerce/issues/42329

**Comment by kmanijak** [comment]
I could reproduce this issue. Product Summary is a variation of `core/post-excerpt` block from Guternberg and seems the issue has been already reported there:

https://github.com/WordPress/gutenberg/issues/15117

Please use the following issue to track the progress on fixing it. In the meantime, I'll go ahead and close this issue for clarity. Keep in mind that closed issues can still be commented on. 🙌 Thanks!
