### ISSUE TITLE
How to edit Cart/Checkout page featured image and excerpt?

### ISSUE THREAD

**Issue by webmandesign** [woocommerce/woocommerce-gutenberg-products-block#10654]
## Describe the bug

In my theme I am including new ([WC8](https://developer.woocommerce.com/2023/08/08/woocommerce-8-0-0-released/)) blocks templates (WC8) Cart and Checkout templates.

In the content of these templates I am using Cover block displaying featured image, Post Title block and Post Excerpt.

However, I am unable to edit the Cart/Checkout page featured image and excerpt since WC8 as clicking "Edit page" opens the Site Editor template, not the actual page for editing.

## Expected behavior

I should still be able to edit Cart/Checkout page content.

### WordPress (please complete the following information):

-   WordPress version: 6.3
-   WooCommerce version: 8.0.2

**Comment by webmandesign** [comment]
Could Cart and Checkout template be registered as [**custom templates**](https://developer.wordpress.org/themes/advanced-topics/theme-json/#defining-custom-templates) instead of **templates** that replace the actual pages?

That way we could gain from both solutions: user can use a page content or set a Cart/Checkout custom template for the page and edit it in Site Editor.

![cart-custom-template](https://github.com/woocommerce/woocommerce-blocks/assets/2456735/f77e6900-b213-4340-9e8c-8087546f7150)

**Comment by ralucaStan** [comment]
@webmandesign thank you so much for your feedback. We are now taking a closer look at the implementation of cart and checkout templates to accommodate the custom theme templates as well. 

I am going to close this in the favor of #10595

**Comment by ralucaStan** [comment]
Hey
