### ISSUE TITLE
Cart and Checkout Blocks not compatible with BTCPayserver v2 plugin

### ISSUE THREAD

**Issue by satscoffee** [woocommerce/woocommerce-gutenberg-products-block#10670]
## Describe the bug

The blocks cart and checkout don't work with the BTCPayserver plugin. 

## To reproduce

The site is corrected by disabling/deleting the blocks and using shortcodes, however you could replicate in the past like this:
1. Go to my cart (sats.coffee/cart)
2. Click on check out
3. Scroll down to try and pay
4. See error no payment gateway.

## Expected behavior

They should be able to check out using btcpayserver v2 plugin.

### WordPress (please complete the following information):

-   WordPress version: 6.3
-   Gutenberg version (if installed): Unknown
-   WooCommerce version: 8.0.2
-   WooCommerce Blocks version: Unknown
-   Site language: English
-   Any other plugins installed: many...none were updated since it stopped working, however.

### Desktop (please complete the following information):

-   OS: [e.g. macOS, Windows] Any
-   Browser [e.g. chrome, safari] Any
-   Version [e.g. 22] Any

### Smartphone (please complete the following information):

-   Device: [e.g. iPhone6] Any
-   OS: [e.g. iOS8.1] Any
-   Browser [e.g. stock browser, safari] Any
-   Version [e.g. 22] Any

**Comment by senadir** [comment]
Hey @satscoffee Thank you for reporting this.

The BTCPayserver needs to provide integration with Checkout block for it to work, please redirect this request to them, we would be happy to help figure it out, and we have plenty of tutorials/docs about integrating payment methods.

**Comment by pavlenex** [comment]
cc @ndeet can you check this one out please?

**Comment by ndeet** [comment]
Hi, yes aware of it and it is on the todo https://github.com/btcpayserver/woocommerce-greenfield-plugin/issues/19 Working on it soonish.
