### ISSUE TITLE
Add notifications style guide to Storybook 

### ISSUE THREAD

**Issue by ralucaStan** [woocommerce/woocommerce-gutenberg-products-block#10681]
We have _Shopper notifications usage guidelines_ (link in resource below) defined  and we need to publish them for the community.

We need to add them to the corresponding Storybook pages: [Notice Banner component](https://href.li/?https://woocommerce.github.io/woocommerce-blocks/?path=/docs/woocommerce-blocks-base-components-noticebanner--default) and [SnackbarList component](https://href.li/?https://woocommerce.github.io/woocommerce-blocks/?path=/docs/woocommerce-blocks-base-components-snackbarlist--default).

See pdFofs-11n-p2 P2 for more details.

**Comment by mikejolley** [comment]
@ralucaStan I didn't get a chance to build this, but perhaps this is a good cooldown activity:

https://storybook.js.org/addons/storybook-readme

This would allow readme content to be pulled into storybook.
