### ISSUE TITLE
Payment documentation shouldn't suggest deprecated `onPaymentProcessing` and `shippingData` `billingData` 

### ISSUE THREAD

**Issue by Sidsector9** [woocommerce/woocommerce-gutenberg-products-block#10690]
## Describe the bug

I am implementing an express payment method (digital wallet) where the shipping address needs to be set from the info returned by the wallet.

Setting `billingData` works but `shippingAddress` does not work. This causes the `woocommerce_rest_invalid_address` error and the only way to resolve this is to set the shipping address fields in the Block Checkout form.

May be related to issue woocommerce/woocommerce-blocks#8785

## To reproduce

Return shipping address  in the observer for`onPaymentProcessing()` in the following format:

```js
onPaymentProcessing( () => {
	//
	// some logic...
	//
	const response = {
		meta: {
			paymentMethodData: {
				key1: 'value1',
				key2: 'value2',
			}
		},
		billingData: {
			email: 'user@example.com',
			first_name: 'John',
			last_name: 'Doe',
			company: 'Billing, INC.',
			address_1: 'Billing Apt.',
			address_2: '',
			city: 'LA',
			state: 'CA',
			postcode: '90001',
			country: 'US',
			phone: '8888899999',
		},
		shippingAddress: {
			first_name: 'Emily',
			last_name: 'Dawson',
			company: 'Shipping, INC.',
			address_1: 'Shipping Apt.',
			address_2: '',
			city: 'LA',
			state: 'NY',
			postcode: '10001',
			country: 'US',
		},
	};
	return response;
} );
```

So far, I have also tried the older response shapes for shipping data:

```js
const response = {
	meta: {
		paymentMethodData: {}
	},
	billingData: {},
	shippingData: {},
};
```

**and**

```js
const response = {
	meta: {
		paymentMethodData: {}
	},
	billingData: {},
	shippingData: {
		address: {}
	},
};
```

### WordPress (please complete the following information):

-   WordPress version: 6.3
-   WooCommerce version: 8.0.2
-   WooCommerce Blocks version: 11.0.0-dev
-   Site language:
-   WooCommerce Square

**Comment by senadir** [comment]
First of all `onPaymentProcessing` is deprecated, you should use `onPaymentSetup` instead.

Using billingData and shippingData is also depricated, and you should use `billingAddress` and `shippingAddress`.

As for your problem, validation seems to fail silently for you, but your shipping address is failing at `isShippingAddress` because it's missing the phone attribute.

You should pass it even if it's empty
```
'first_name',
'last_name',
'company',
'address_1',
'address_2',
'city',
'state',
'postcode',
'country',
'phone',
```

We can probably make this check more vocal.

**Comment by Sidsector9** [comment]
Thanks @senadir that worked.

I referred to these documentation pages:

- https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/README.md
- https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/block-client-apis/checkout/checkout-flow-and-events.md
- https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/checkout-payment-methods/payment-method-integration.md

Please correct me if I am referring to an outdated documentation. If not, I wish to contribute to the Wiki pages.

**Comment by senadir** [comment]
Those tutorials are outdated indeed, sorry for that! I will rename this issue to address that.

**Comment by ralucaStan** [comment]
Added this to https://github.com/woocommerce/woocommerce/issues/42264; cc @opr
