### ISSUE TITLE
Store Customization > Investigate if the standalone Jetpack package can be used to generate a new jetpack_id

### ISSUE THREAD

**Issue by nefeline** [woocommerce/woocommerce-gutenberg-products-block#10699]
WP.com has an endpoint that allows us to create a new JWT token, this token is a requirement for connecting with the GPT API:

`/sites/$jetpack_id/jetpack-openai-query/jwt`

Within JetPack, this connection is handled via [`get_openai_jwt`](https://github.com/Automattic/jetpack/blob/0962ee5610ce7753b9448dc2504d547ae8c009ca/projects/plugins/jetpack/_inc/lib/class.core-rest-api-endpoints.php#L780). To avoid creating this direct dependency between Jetpack and WooCommerce Blocks, we should explore if we can rely on the [Jetpack Connection Package](https://github.com/Automattic/jetpack-connection) for this purpose instead.

If we can have the `jetpack_id` generated for a given site when registering it with WP.com via **[this utility](https://github.com/Automattic/jetpack-connection/blob/trunk/docs/register-site.md#register-the-site--create-blog-token)**, then we should be able to make the request to generate the JWT token without any problems.

## The Scope

- Add the [Jetpack Package](https://github.com/Automattic/jetpack-connection/blob/trunk/docs/register-site.md#register-the-site--create-blog-token) as a Composer dependency for WooCommerce Blocks.
- Check if by [registering the site with WP.com](https://github.com/Automattic/jetpack-connection/blob/trunk/docs/register-site.md#register-the-site--create-blog-token), the `jetpack_id` (which is saved within the wp_options table) is generated, if it is, we can rely on this package to power our implementation and unblock the JWT request.

**Comment by albarin** [comment]
After exploring this option, we see it's actually possible to trigger the Jetpack connection flow, get the `jetpack_id` and get the JWT to make requests to the GPT AI endpoints.
In this PR there's an example on how to do it: https://github.com/woocommerce/woocommerce-blocks/pull/10729
