### ISSUE TITLE
Product Summary not available in Inserter

### ISSUE THREAD

**Issue by imanish003** [woocommerce/woocommerce-gutenberg-products-block#10718]
As reported by @nefeline, `Product Summary` block isn't visible in the insertor on production build.

Here is a quick demo:

https://github.com/woocommerce/woocommerce-blocks/assets/16707866/8d9c52c7-dacf-45af-a74b-97139cc99214

**Comment by imanish003** [comment]
Fixed in https://github.com/woocommerce/woocommerce-blocks/pull/10701.

**Comment by nefeline** [comment]
Thanks for addressing the feedback @imanish003 ! For future reference to anyone coming across this issue, the problem was originally flagged during code review on https://github.com/woocommerce/woocommerce-blocks/pull/10524#pullrequestreview-1584078748
