### ISSUE TITLE
sepet şablonu

### ISSUE THREAD

**Issue by hacerkls42** [woocommerce/woocommerce-gutenberg-products-block#10717]
sepet kısmında indirim ücreti 15 kaydet 25 kaydet gibi cıkıyor ve hos durmuyor kaldırılabilir birde ödeme sayfası icin teelfon numarasıda zorunlu olmalı

**Comment by kmanijak** [comment]
Thanks for the suggestions! Could you provide more details about what you expect and what use case you have that requires such changes?

**Comment by tarunvijwani** [comment]
@hacerkls42 We provide support primarily in English. I'm using Google Translate to understand your messages and reply in English. 

>In the cart section, the discount fee looks like 15 save 25 and it doesn't look nice. It can be removed. Also, the phone number must be mandatory for the payment page.


Will you please provide a few more details? I want to make sure we fully understand your question so we can be as helpful as possible.

To make phone number a mandatory field, please follow the below steps:
1. Open the Checkout page/template editor.
2. Select the billing/shipping block where you wish to make the phone number mandatory.
3. From the Inspector panel on the right side, enable `Require phone number?` and save the changes. 

![image](https://github.com/woocommerce/woocommerce-blocks/assets/11503784/9bd549e1-d0d8-4684-aead-6bd2e28a0bb9)

**Comment by mikejolley** [comment]
As this hasn't had any responses in a while I am going to close the issue. 

Thanks
