### ISSUE TITLE
Create Collection Filters Block

### ISSUE THREAD

**Issue by roykho** [woocommerce/woocommerce-gutenberg-products-block#10711]
Ref design discussion https://github.com/woocommerce/woocommerce-blocks/discussions/10691

This issue is to create a new Collection Filters block that will eventually house the filter blocks we currently have (price,rating,attributes and stock).

**Comment by dinhtungdu** [comment]
Moving https://github.com/woocommerce/woocommerce-blocks/pull/10726#discussion_r1325315125 here for visibility.

We're using `nav` as the wrapper element of the collection filter blocks, but merchants may have different preferences. Should we add an option to let them control which tag to use?

cc @sunyatasattva

**Comment by sunyatasattva** [comment]
@dinhtungdu  I don't think most merchants will care, to be honest. I vote for just making a sensible decision, and `nav` seems correct to me. The other option would be `section`. It's more about accessibility than merchants opinions in my view.

What other tags do you think merchants would want to use?

**Comment by dinhtungdu** [comment]
I really meant merchant and developers. Some may think `nav` is good choice but some may prefer `section`, even `div`, I thought it'd be nice if we can let them choose which tag to use. But I agree that most merchants/dev won't care. Let's do nothing and look at this again when we see real requests.
