### ISSUE TITLE
Products by Category block: Parent category checkbox size issue

### ISSUE THREAD

**Issue by VipulUpadala** [woocommerce/woocommerce-gutenberg-products-block#10724]
## Describe the bug

I have tested the Products by Category block and found the products by category block checkbox size issue. if the parent category has a child category then the checkbox size is big compared to other checkboxies. please check the provided video below for a better understanding.

## To reproduce

1. Create a new page and take the Products by Category block .
3. And, see parent category checkbox size(**need to have a child category**) .

## Expected behavior

Need to same size of all checkbox like featured category block radio button.

## Screenshots

Video URL: https://share.cleanshot.com/CF011w7v2MLsRS0g5qYw

### WordPress (please complete the following information):

-   WordPress version: [ 6.3 running ]
-   WooCommerce version: [ 8.0.2 ]
-   WooCommerce Blocks version: [ by default installed ]
-   Site language: English
-   Any other plugins installed: No

### Desktop (please complete the following information):

-   OS: [ macOS ]
-   Browser [ chrome ]

**Comment by kmanijak** [comment]
Thanks for raising it!

This issue is fixed in https://github.com/woocommerce/woocommerce-blocks/pull/10192 and will be available in WooCommerce 8.1. Also, the fix is available since WooCommerce Blocks 10.7.0.

I'm closing this issue for now, but closed issues can still be commented on if needed! 🙌
