### ISSUE TITLE
Add to Cart Form for variable products not showing in default single product template (current trunk)

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#10739]
## Describe the bug

The add to cart form is not showing for a variable product when testing against the latest trunk ([6f58d5a](https://github.com/woocommerce/woocommerce-blocks/commit/6f58d5a164abad30881607b904f92d833c51b441)). I realize there have been some issues with this but I thought it was fixed - so thought I'd report just in case.

Note:

- I ensured the Single Product template was set to default (and verified the Add to Cart form block is there).
- I also tested with the 10.9.3 (on a separate site) and I'm getting expected results there.

Environment:

- WooCommerce 8.0.2
- WooCommerce Blocks ( 6f58d5a )

## To reproduce

1. View a variable product on the frontend
2. Observe the Add to Cart form button is not displayed.

## Expected behavior

Expect the Add to Cart form button to be displayed.

## Screenshots

<img width="1264" alt="CleanShot 2023-08-27 at 07 51 06@2x" src="https://github.com/woocommerce/woocommerce-blocks/assets/1429108/de3bf3ae-376c-48c2-98b7-8f6dc1e1464b">

### WordPress (please complete the following information):

-   WordPress version: 6.3
-   Gutenberg version (if installed): Not Active
-   WooCommerce version: 8.0.2
-   WooCommerce Blocks version: 6f58d5a
-   Site language: English
-   Any other plugins installed: No.

**Comment by dinhtungdu** [comment]
@nerrad I can't reproduce this on my end as well as playground.

<img width="1285" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/5423135/4a259744-764e-45c3-b325-e1497c731313">

I also tested on JN with nightly and couldn't reproduce as well.
<img width="1789" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/5423135/a00746a5-1c20-48af-8862-2a86f69bd6d3">

**Comment by nerrad** [comment]
Checked the product I was testing with and it didn't have prices set for the variations which is why it wasn't showing up.
