### ISSUE TITLE
Block attribute compatibility with data-*

### ISSUE THREAD

**Issue by Triloworld** [woocommerce/woocommerce-gutenberg-products-block#10731]
## Describe the bug
We like to add some AOS animation into theme.
There is library like this: https://github.com/michalsnik/aos
Require this to be implemented:
[https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*)

On any Core Blocks we can check what is available: https://developer.wordpress.org/block-editor/reference-guides/core-blocks/
As we see there isn't option to add it.

## To reproduce

Add group block from core.
Ty to add `data-test` to any of them in template
You see something like this:
![image (4)](https://github.com/woocommerce/woocommerce-blocks/assets/2671726/75614067-0bd9-401c-85a2-aa9ec2616a95)
You aren't allowed to use it freely.

## Expected behavior

Option to add `data-x` to any place
Information of documentation
Example that is compatible with: https://github.com/alpinejs/alpine or any other method
Compatibility with MVC approach where `data-x` tag used to be manipulate by JS only

## Screenshots

![image (4)](https://github.com/woocommerce/woocommerce-blocks/assets/2671726/75614067-0bd9-401c-85a2-aa9ec2616a95)

## Environment
Newest env and from documentation perspective is any version

**Comment by kmanijak** [comment]
Hi @Triloworld!

Blocks API is defined by Gutenberg (https://github.com/WordPress/gutenberg) and we don't have much control over it. However, I checked and such requests have already been raised there: https://github.com/WordPress/gutenberg/issues/10395 with examples of how to achieve what you need: [example answer](https://github.com/WordPress/gutenberg/issues/10395#issuecomment-428120565).

If you have further questions I'd recommend using the issue I mentioned (or similar) or opening new issue in Gutenberg repo, as they will be better suited to respond to this feature request.

In the meantime I'm going to close this issue, but please be aware closed issue can still be commented on in case there's anything else we can help with! 🙌

**Comment by Triloworld** [comment]
You have right. Sorry
