### ISSUE TITLE
Improve "Check Markdown links" action

### ISSUE THREAD

**Issue by opr** [woocommerce/woocommerce-gutenberg-products-block#10735]
Currently this action fails due to rate limiting while checking links on the markdown docs.

See this workflow where it failed due to rate limiting: https://github.com/woocommerce/woocommerce-blocks/actions/runs/5977210467/job/16216681320?pr=10669#step:5:1473

It seems wasteful that we check links every time a change is made, could we investigate if it's possible to run this on trunk only and also if a PR changes any `.md` files?

**Comment by nielslange** [comment]
> It seems wasteful that we check links every time a change is made, could we investigate if it's possible to run this on trunk only and also if a PR changes any .md files?

@opr A few weeks ago, @saad and I talked about this potential improvement during a pairing session. Back then, we decided against it to ensure that we're detecting broken links, even if an *.md file hasn't been changed, e.g. when a folder was renamed to which a link from an *.md file points to.

**Comment by opr** [comment]
> @opr A few weeks ago, @saad and I talked about this potential improvement during a pairing session. Back then, we decided against it to ensure that we're detecting broken links, even if an *.md file hasn't been changed, e.g. when a folder was renamed to which a link from an *.md file points to.

Good point, maybe we could improve the current `markdown-link-check` package so we can skip checking the link if the URL is one for our own GitHub repository, then we can just check the file exists on the filesystem.

**Comment by nielslange** [comment]
> Good point, maybe we could improve the current markdown-link-check package so we can skip checking the link if the URL is one for our own GitHub repository, then we can just check the file exists on the filesystem.

That sounds like a great approach, @opr.

**Comment by samueljseay** [comment]
I think there is a simpler approach we can take than modifying markdown-link-check which is just to utilise the `retryOn429` [option](https://github.com/tcort/markdown-link-check#markdownlinkcheckmarkdown-opts-callback). This means we don't have to distinguish between links for things like issues in the repo which is what the original run errored on. 

This option respects the `retry-after` header before checking again.

Also I suggest we fix the npm install that's part of this workflow to a specific version just to avoid supply chain hacks.
