### ISSUE TITLE
Incompatible with block based checkout 

### ISSUE THREAD

**Issue by syarahz** [woocommerce/woocommerce-gutenberg-products-block#10740]

**Comment by tarhi-saad** [comment]
Hello @syarahz! 👋 Thanks for getting in touch! 🙌 Could you provide more information about the reported issue? The title alone doesn't give me a clear understanding.

**Comment by mikejolley** [comment]
Since this issue is incomplete and has not had a response I am closing it. Please open a new issue if you have something to report.

**Comment by syarahz** [comment]
This is incompatible with block based please help thx


Sent from Yahoo Mail on Android 
 
  On Tue, 5 Sept 2023 at 18:42, Mike ***@***.***> wrote:   


Closed #10740 as completed.
