### ISSUE TITLE
Product Gallery Next Previous buttons: Buttons hidden with display none

### ISSUE THREAD

**Issue by danieldudzic** [woocommerce/woocommerce-gutenberg-products-block#10760]
## Describe the bug

When **Next/Previous buttons** are hidden with the `Off` block setting, they remain in the markup and are just hidden with `display: none;`.

In `ProductGalleryLargeImageNextPrevious.php` we can check the setting value and not output the markup.

## To reproduce

1. With a block theme, open `Appearance > Editor`.
2. Open `Templates > Single Product`.
3. Select `Convert to Blocks` if you are using the Classic Templates.
4. Add the `Product Gallery` block.
5. Set the `Next/Prev Buttons` setting to `Off`.
6. Open a product page on the frontend with multiple product images.
7. Inspect the code of the page and verify that the `Next/Previous buttons` markup is present.

## Expected behavior

When the buttons are switched off, the markup should not be outputted.

## Screenshots

<img width="1419" alt="V-Neck_T-Shirt_–_newproductgallery" src="https://github.com/woocommerce/woocommerce-blocks/assets/905781/fe4215c3-ea90-49a8-b0bb-1a221d65a274">

**Comment by thealexandrelara** [comment]
This was closed by #10235
