### ISSUE TITLE
No products block appears in gutenberg

### ISSUE THREAD

**Issue by ArineBlaze** [woocommerce/woocommerce-gutenberg-products-block#108]
Got PHP version: 5.6.33-0+deb8u1 
MySQL version: 5.6.39
Gutenberg 3.7.0
WooCommerce 3.4.5

But WooCommerce Gutenberg Products Block doesn't work! Any ideas?

A week ago, I installed this feature plugin, and the block was available, now it's not.

**Comment by aaemnnosttv** [comment]
See #106
