### ISSUE TITLE
[Urgent] Payment Method not Compatible with Extension, RY tools

### ISSUE THREAD

**Issue by sam7933715** [woocommerce/woocommerce-gutenberg-products-block#10801]
## To reproduce

1. go to the checkout page at https://acthl.com/%e7%b5%90%e5%b8%b3%e7%9f%ad%e4%bb%a3%e7%a2%bc/
2. Select the delivery method
3. The website will be redirected to https://acthl.com/%e7%b5%90%e5%b8%b3%e7%9f%ad%e4%bb%a3%e7%a2%bc-2/
4. Payment method is not showing properly (Maybe not compatible with RY tools)

## Expected behavior

Payment method is not showing properly

Videos to reproduce the issue: https://watch.screencastify.com/v/pbXfyflNYoxuIc2bubHY)

### WordPress (please complete the following information):

-   WordPress version: 6.3.1
-   Gutenberg version (if installed): [e.g. 12.0.0]
-   WooCommerce version: [e.g. 6.1]
-   WooCommerce Blocks version: [e.g. 7.0.0]
-   Site language:
-   Any other plugins installed:

### Desktop (please complete the following information):

-   OS: Windows
-   Browser Chrome
-   Version [e.g. 22]

### Smartphone (please complete the following information):

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

## Additional context

Please connect with me via sam7933715@gmail.com

**Comment by mikejolley** [comment]
Hi @sam7933715 

Currently it’s up to extension developers to add support for the new checkout flow offered via the Cart and Checkout Blocks. We have some [documentation for Third-party developers](https://href.li/?https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs#third-party-developers) and some [Developer Resources](https://href.li/?https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs#developer-resources) available to help with their integration efforts.

Your best course of action now if you are using a payment method that isn’t working with the blocks is to notify the developer of the extension and ask if they can add support.

Until then, you can keep on top of the [status of the Cart & Checkout Blocks in this documentation](https://href.li/?https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/).

Thanks
