### ISSUE TITLE
Store Customization MVP (PYS) > Summary of work and technical details

### ISSUE THREAD

**Issue by nefeline** [woocommerce/woocommerce-gutenberg-products-block#10810]
This is a summary of the work we've been doing as part of the Store Customization MVP (PYS - Personalize your Store) project with all technical details.

## Patterns

* #### Part of the WooCommerce Blocks Plugin (this repo)

During Phase 1 https://github.com/woocommerce/woocommerce-blocks/issues/10087, we focused on removing all opinionated styles and fine-tuning our patterns based on the feedback received from the design team. The goal was to ensure our patterns are prepared to support the upcoming features within the Assembler.

## AI Managed Images and Content

* #### Part of the WooCommerce Blocks plugin (this repo)
* #### Has a dependency with the `woo-ai` plugin (which is expected to make its way to the core of Woo at some point)

During Phase 2 https://github.com/woocommerce/woocommerce-blocks/issues/10568, we have been focusing on powering one of the upcoming features expected to be part of the Assembler, ensuring the images for patterns are populated with Verticals (which is an API built to help designers and developers choose vertical-specific images for use in templates and automatically generated content). The displayed images should dynamically change depending on what the user decides to add as a description for their business on their AI settings screen.

#### Part of the WooCommerce Admin plugin (within the WooCommerce monorepo)

The Assembler is the macro feature we are helping to develop with the two aforementioned initiatives: in a nutshell, the Assembler comprehends the creation of a new onboarding flow and settings screen based on the Site Editor. The designs for this new feature are available on: pbIJXs-3l9-p2

### Technical Details

I'll write down here a summary based on my understanding of this work, but @adrianduffell and @chihsuan are the absolute source of truth here, if I'm missing something, please let me know!

- This feature is hidden behind a feature flag.
- While we still don't have any documentation, the local setup for development can be done by following the testing instructions on https://github.com/woocommerce/woocommerce/pull/39843
- In practice, there are two Assemblers: the dotcom Assembler and the Woo’s store customization. The former is wholly built on Calypso, while the latter is built based on the Site Editor.

### Thoughts and Questions

These are a few thoughts/questions I have, since we might be the ones responsible for continuing to develop this feature after the MVP phase:

- Considering the Assembler is a customization for the Site Editor, would it make sense to port over this feature to WooCommerce Blocks? In practice, both plugins (Woo Admin and Woo Blocks) are expected to live under the same umbrella in the monorepo very soon. However, Woo Blocks still feels like a better fit (e.g. we could allow users to have early access to certain features via the feature plugin). WDYT?
- Would it make sense to do an exploration of what features could be ported over from the dotcom assembler to ours? Maybe you already did this @adrianduffell @chihsuan? I'd be curious to hear your thoughts.
- This is more of a suggestion than a question: I think it would be great if @verofasulo could give us a walkthrough of the planned features after the MVP: I remember we discussed some of those a couple of times during our weekly calls; it would be neat to glimpse the expected next steps since we (store editing teams) are expected to focus more on this project moving forward. 

cc: @nerrad @danielwrobert @tjcafferkey @albarin

**Comment by nerrad** [comment]
> Considering the Assembler is a customization for the Site Editor, would it make sense to port over this feature to WooCommerce Blocks? In practice, both plugins (Woo Admin and Woo Blocks) are expected to live under the same umbrella in the monorepo very soon. However, Woo Blocks still feels like a better fit (e.g. we could allow users to have early access to certain features via the feature plugin). WDYT?

I actually think the opposite, we should be doing this in WC Core. It's an opportunity for Woo blocks team to get more familiar with Woo Core. There is already a feature flag system in WC Core that is/can be used.

With that said, I realize there are potential challenges for development given parts of the launch/customization experience require patterns and blocks from Woo blocks. On the surface, I think it'd be more challenging to move the assembler work over the Blocks repo than the other way around. What specific challenges do you forsee with either approach?

**Comment by chihsuan** [comment]
Thanks for creating this! @nefeline 

> - This feature is hidden behind a feature flag.
> - While we still don't have any documentation, the local setup for development can be done by following the testing instructions on https://github.com/woocommerce/woocommerce/pull/39843
> - In practice, there are two Assemblers: the dotcom Assembler and the Woo’s store customization. The former is wholly built on Calypso, while the latter is built based on the Site Editor.

Correct 👍 

> Would it make sense to do an exploration of what features could be ported over from the dotcom assembler to ours? Maybe you already did this @adrianduffell @chihsuan? I'd be curious to hear your thoughts.

I've looked into that. I think we could fork some UI components such as [color palettes UI component](https://github.com/Automattic/wp-calypso/blob/d3c9b16fb99ce242f61baa21119b7c20f8823be6/packages/global-styles/src/components/color-palette-variations/index.tsx#L84). However, it's very different in terms of feature implementation between dotcom and Core site editor. We can just refer to the site editor IMO.

**Comment by nerrad** [comment]
> I think we could fork some UI components such as [color palettes UI component](https://github.com/Automattic/wp-calypso/blob/d3c9b16fb99ce242f61baa21119b7c20f8823be6/packages/global-styles/src/components/color-palette-variations/index.tsx#L84). However, it's very different in terms of feature implementation between dotcom and Core site editor. We can just refer to the site editor IMO.

I agree, let's prefer WordPress packages/components for this where we can - only jumping to use other libraries when necessary.

**Comment by nefeline** [comment]
> I actually think the opposite, we should be doing this in WC Core. It's an opportunity for Woo blocks team to get more familiar with Woo Core. There is already a feature flag system in WC Core that is/can be used.

👍

> With that said, I realize there are potential challenges for development given parts of the launch/customization experience require patterns and blocks from Woo blocks. On the surface, I think it'd be more challenging to move the assembler work over the Blocks repo than the other way around. What specific challenges do you forsee with either approach?

For migrating all Patterns from Woo Blocks to the core of Woo (more specifically Woo Admin, where the Assembler lives), we could ensure they are available in the Core before removing them altogether from our plugin/repo here: We could even keep the code on both repos for a brief period, but with a condition to only load patterns from within Woo Blocks if the installed version of the core of WooCommerce doesn't have them yet. We have an L0 policy for Woo Blocks, so maybe having them running in parallel is not a hard requirement, but we could do that for a smoother transition.

For the other way around, moving the Assembler to Woo Blocks, we would have first to make this change within the Woo Blocks repo, and then when it comes to the moment of updating the version of Woo Blocks within the core of Woo, remove the Assembler from Woo Admin. We would also have some code duplication for a brief period of time, in this case, for all folks running the latest version of Woo Blocks feature plugin in parallel with a version of WooCommerce that still doesn't have it (so we would have to ensure only the Assembler within Woo Blocks is loaded in such cases). If we follow this path we would also have to ensure that we have all JS dependencies for this feature in place within Woo Blocks (I suspect we already have them, as the Assembler is based on the editor, but something to keep an eye on. With the upcoming migration of the Woo Blocks plugin to the monorepo, maybe we wouldn't have to worry about this, depending on how soon that happens).

**Comment by nerrad** [comment]
@nefeline, I haven't reviewed all the content of this issue and I'm wondering - is it still needed? If yes, would it be better suited as a discussion instead of issue?

**Comment by nefeline** [comment]
> @nefeline, I haven't reviewed all the content of this issue and I'm wondering - is it still needed? If yes, would it be better suited as a discussion instead of issue?

Hey! No, it isn't, I'm going ahead and closing this one out 👍
