### ISSUE TITLE
Incorrect postal code validation for Nicaragua

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#10854]
## Describe the bug

Nicaraguan postal code validation fails in the Checkout block due to an incorrect regular expression being used. Nicaraguan postal codes are 5-digit numbers; however, the current regex does not accommodate this format. For instance, a postal code like `13024` should be valid according to [codigo-postal.org](https://codigo-postal.org/en-us/nicaragua/zip/13024/) and [en.youbianku.com](https://en.youbianku.com/Nicaragua), but fails in WooCommerce Blocks.

The validation logic is located in the file [is-postcode.ts](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/packages/checkout/utils/validation/is-postcode.ts). The current regex for Nicaraguan postal codes is:

```js
/^((\d{4}-)?\d{3}-\d{3}(-\d{1})?)?$/
```

This regex does not account for the 5-digit postal codes used in Nicaragua.

## To reproduce

1. Add the Cart block to a test page.
2. Enable the `Shipping calculator` in the Shipping inner block.
3. Add the Checkout block to another test page.
4. Add a test product to the cart via the frontend.
5. Navigate to the test page with the Cart block and click `Change address` in the Shipping section.
6. Select `Nicaragua` as the country and enter a 5-digit postal code (e.g., `13024`).
7. Observe that validation fails.
8. Navigate to the test page with the Checkout block.
9. Repeat steps 6-7.

## Expected behavior

The 5-digit postal codes for Nicaragua should be validated successfully.

## Screenshots

| Postal Code Validation in Cart Block | Postal Code Validation in Checkout Block |
| ------------------------------------ | --------------------------------------- |
| ![Cart Block Validation](https://github.com/woocommerce/woocommerce-blocks/assets/3323310/fb519bb9-a8a2-4af1-b665-4323fbbe75f2) | ![Checkout Block Validation](https://github.com/woocommerce/woocommerce-blocks/assets/3323310/662ccc48-2158-40ba-aef2-8b77d175ecf9) |

**Comment by Siddh744542** [comment]
hi, I am working on this and will open a PR soon.
