### ISSUE TITLE
[WC Admin] Add option to the Home screen for merchant to review incompatibilities

### ISSUE THREAD

**Issue by ralucaStan** [woocommerce/woocommerce-gutenberg-products-block#10853]
When we detect at least one plugin that isn’t compatible with the Cart and Checkout blocks, we’d show a task in the Things to do next list on the Home screen. The task persists until all conflicts are resolved or the user dismisses it from the three-dot menu. It can re-appear when the user installs a new incompatible plugin.

**Figma** KnlCgfrJqYpeQTHLbkIADF-fi-848_89195
**More context** peCask-mo-p2

![task (1)](https://github.com/woocommerce/woocommerce-blocks/assets/1628454/288d7205-e732-4f60-ae08-e99aa8ae0133)

**Things not covered by this ticket**
- the task is not shown for other types of incompatibilities outside of the ones for Cart and Checkout blocks

**Open questions design/product:**
- what does it mean until the conflicts are resolved?
 

cc @pmcpinto  @jarekmorawski

**Comment by ralucaStan** [comment]
Here is a tutorial on how to extend the home section https://developer.woocommerce.com/2021/02/26/use-setup-tasks-to-provide-a-first-class-on-boarding-experience-for-merchants/

**Comment by pmcpinto** [comment]
> what does it mean until the conflicts are resolved?

Good question. As I see it, we don't have a precise way to check this. We can use some proxies: the user disables the cart/checkout blocks, or the user visits the needs review/conflicts tab. @jarekmorawski what do you think?

**Comment by ralucaStan** [comment]
closing this in favor of a new ticket when the new ticket with the updated behavior and design
