### ISSUE TITLE
Media library displays shop page when editing media

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce-gutenberg-products-block#10861]
## Describe the bug

I'm using WC `trunk` pulled earlier today and do not have the blocks plugin active. When editing an image in the media library on a FSE enabled theme the shop page is displayed instead of the the media item.

## To reproduce

1. Pull latest WC trunk branch
2. Switch to TT3 theme
3. Go to media librry and edit image
4. See screenshot

## Expected behavior

Media image

## Screenshots

<img width="1408" alt="Screenshot 2023-09-06 at 4 14 27 PM" src="https://github.com/woocommerce/woocommerce-blocks/assets/343847/bf58aabc-9005-47eb-a768-8d81fac2a184">

### WordPress (please complete the following information):

-   WordPress version: 6.3.1
-   Gutenberg version (if installed): N/A
-   WooCommerce version: trunk
-   WooCommerce Blocks version: N/A
-   Site language: US
-   Any other plugins installed:

### Desktop (please complete the following information):

-   OS: macOS
-   Browser chrome 
-   Version 116.0.5845.140

### Smartphone (please complete the following information):

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

## Additional context

Switching to tag 8.0.3 fixes the issue.

**Comment by dinhtungdu** [comment]
I tried with Woo trunk on a fresh WP 6.3.1 installation but can't reproduce this issue.
<img width="2123" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/5423135/11e6ef98-4b40-4127-a196-d66f16c04a6a">

**Comment by tjcafferkey** [comment]
@rrennick I am also unable to reproduce this on my end. Any chance you can paste the System Report here and also a screen recording of the bug if possible so we can investigate further?

Thanks.

**Comment by rrennick** [comment]
Thanks for investigating. I'm no longer able to reproduce this either. In switching the repo between versions I had to run pnpm install and build so I suspect this may have been an issue with something had not been updated and/or rebuilt in the latest git pull.
