### ISSUE TITLE
PHP error of undefined `$attributes['theme']`

### ISSUE THREAD

**Issue by webmandesign** [woocommerce/woocommerce-gutenberg-products-block#10872]
I get this PHP error:

> **Warning**: Undefined array key "theme" in `./wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/BlockTemplatesController.php` on line `143`

It points to this PHP code within the file:
```php
if ( 'woocommerce/woocommerce' === $attributes['theme'] ) {
```

Please, possibly fix this to:
```php
if ( isset( $attributes['theme'] ) && 'woocommerce/woocommerce' === $attributes['theme'] ) {
```

**Comment by nielslange** [comment]
Thanks for reaching out and reporting this warning, @webmandesign. I've added this issue to our backlog.

**Comment by nielslange** [comment]
For whoever is working on this issue, within WooCommerce Blocks, the corresponding section can be found on https://github.com/woocommerce/woocommerce-blocks/blob/fb0dfb5b7a34874df719ff6f49d631e1c55f4d0b/src/BlockTemplatesController.php#L161-L167

Apart from adding `isset( $attributes['theme'] )`, as mentioned in https://github.com/woocommerce/woocommerce-blocks/issues/10872#issue-1886337781, we should also add `isset( $attributtes['slug'] )` to be on the safe side. (more context on p1694165511553669-slack-C8X6Q7XQU)
