### ISSUE TITLE
Spacing needs to be reduced in/between form fields on Cart and Checkout

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-gutenberg-products-block#10889]
## Describe the bug

There's currently expanded padding between form fields in the Cart and Checkout blocks. There's also too much padding between the helper text and input within the form fields. All this extra space adds up and makes it harder to quickly scan the page. This could add to the perception that the checkout process is long and tedious.

## To reproduce

On any theme go to the Cart block and choose to "Add address" or "Change address" and see form.
Also, on any theme go to the Checkout block to see the issue.

## Expected behavior

In the designs we have 4px between helper text and input, and 16px between form fields. Discussed in wp.me/pdFofs-1dB

## Screenshots

Current/Checkout
<img width="236" alt="Screen Shot 2023-09-11 at 9 48 57 PM" src="https://github.com/woocommerce/woocommerce-blocks/assets/5121465/264e9f8f-787d-460a-b96a-cc042379ddcb">

Current/Cart
<img width="155" alt="Screen Shot 2023-09-11 at 10 16 16 PM" src="https://github.com/woocommerce/woocommerce-blocks/assets/5121465/3c06bfc6-a38d-4067-823c-89c7ff0b221d">

Expected
<img width="219" alt="Screen Shot 2023-09-11 at 9 54 02 PM" src="https://github.com/woocommerce/woocommerce-blocks/assets/5121465/fb372547-d754-4012-8766-f798d1cce119"> |

@mikejolley I think the 4/16 vertical rhythm will be a nice subtle improvement. I know you mentioned there are spacing presets so let me know what you think about these values.

cc @pmcpinto

**Comment by mikejolley** [comment]
@elizaan36 Refer to this: https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/css/abstracts/_variables.scss

Better yet, refer to this version which I've commented on: https://github.com/woocommerce/woocommerce-blocks/pull/10056/files#diff-005d4b16ec4bfd13fd541de5677ad2da7191e3ebbc21e3f96ceadeb829728196

So yes 4/6 fits within those pre-defs and can be used here.

**Comment by elizaan36** [comment]
Thanks, glad to hear those values will work!

**Comment by tarunvijwani** [comment]
I'd love to work on this task. 🙂

**Comment by mikejolley** [comment]
Just wanted to note @elizaan36, the designs work with pixel values, but in practice we're using relative units (ems) for font sizes for input fields for compatibility with themes.

We can base everything on these 4/16 values if font size is 16px, but if the base font size increases these values will also scale up with it. Just wanted to note this because some themes (2023 for example) use a base font size of 18px rather than 16px as defined in our styles.

(we do something like em(16px) and have a mixin that converts to em units).

**Comment by elizaan36** [comment]
Sounds good, thanks.
