### ISSUE TITLE
`Cart Line Items » itemName`: Add code snippet and screenshot

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#10897]
Recently, we've updated the "Available Extensibility Interfaces for the Cart and Checkout blocks" post. In this post, we introduced new code snippets and screenshots. This issue aims to add the following code snippet and screenshot to the [`Cart Line Items » itemName`](https://github.com/woocommerce/woocommerce-blocks/blob/6083484477410fd99d1efd5ca909288eb4d19963/docs/third-party-developers/extensibility/checkout-block/available-filters.md?plain=1#L26) section:

```js
const { registerCheckoutFilters } = window.wc.blocksCheckout;
 
// Adjust item name of the cart line items.
registerCheckoutFilters( 'example-extension', {
  itemName: ( value, extensions, args ) => {
    // Return early since this filter is not being applied in the Cart context.
    // We must return the original value we received here.
    if ( args?.context !== 'cart' ) {
      return value;
    }
    return '🪴 ' + value + ' 🪴';
  }
} );
```

<img width="1512" alt="screenshot-2023-08-24-at-13 11 22" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/08bc3af0-6290-4ec4-b7f5-5ee21d66ed7f">

---

> **Note**
> The code snippet and screenshot should be placed below the table with the filter names and the sentence _"Each of these filters has the following arguments [...]"_, and should have the following subheading
```md
### itemName
```

**Comment by masteradhoc** [comment]
Thanks @nielslange for the issue! I'll go ahead and create a PR for this soon.

**Comment by nielslange** [comment]
Thanks for showing interest in working on this issue, @masteradhoc. I just assigned this issue to you. See also https://github.com/woocommerce/woocommerce-blocks/issues/10896#issuecomment-1719434916. 😉

**Comment by nielslange** [comment]
> Thanks @nielslange for the issue! I'll go ahead and create a PR for this soon.

Thanks for showing interest in working on this issue, @masteradhoc. I just assigned this issue to you. See also https://github.com/woocommerce/woocommerce-blocks/issues/10896#issuecomment-1719434916. 😉

**Comment by masteradhoc** [comment]
screenshot before
![image](https://github.com/woocommerce/woocommerce-blocks/assets/6242098/6cd0aad9-4a7e-45e1-915b-3294db101246)
