### ISSUE TITLE
`Cart Line Items » cartItemPrice`: Add code snippet and screenshot

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#10898]
Recently, we've updated the "Available Extensibility Interfaces for the Cart and Checkout blocks" post. In this post, we introduced new code snippets and screenshots. This issue aims to add the following code snippet and screenshot to the [`Cart Line Items » cartItemPrice`](https://github.com/woocommerce/woocommerce-blocks/blob/6083484477410fd99d1efd5ca909288eb4d19963/docs/third-party-developers/extensibility/checkout-block/available-filters.md?plain=1#L26) section:

```js
const { registerCheckoutFilters } = window.wc.blocksCheckout;
 
// Adjust cart item price of the cart line items.
registerCheckoutFilters( 'example-extension', {
  cartItemPrice: ( value, extensions, args ) => {
    // Return early since this filter is not being applied in the Cart context.
    // We must return the original value we received here.
    if ( args?.context !== 'cart' ) {
      return value;
    }
    return '<price/> for all items';
  }
} );
```

<img width="1512" alt="screenshot-2023-08-24-at-13 06 25" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/6f427b42-f985-4724-a537-8f83d9eff84a">

---

> **Note**
> The code snippet and screenshot should be placed below the table with the filter names and the sentence _"Each of these filters has the following arguments [...]"_, and should have the following subheading
```md
### cartItemPrice
```

**Comment by corners2wall** [comment]
@nielslange  Assign to me pls

**Comment by nielslange** [comment]
> @nielslange Assign to me pls

Thanks for volunteering to work on this task, @corners2wall. I just assigned it to you.

I also saw that you volunteered to work on the following tasks:
- #10900
- #10901

I suggest working on these issues one by one. Once you finished this one, I can immediately assign you the next one. 😀

**Comment by masteradhoc** [comment]
@nielslange in case you need i could take this over also

**Comment by nielslange** [comment]
> @nielslange in case you need i could take this over also

Based on @corners2wall's comment in https://github.com/woocommerce/woocommerce-blocks/pull/10935#issuecomment-1721533316, it appears that this issue is available. Therefore, I just assigned it to you, @masteradhoc.
