### ISSUE TITLE
`Cart Line Items » cartItemClass`: Add code snippet and screenshot

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#10899]
Recently, we've updated the "Available Extensibility Interfaces for the Cart and Checkout blocks" post. In this post, we introduced new code snippets and screenshots. This issue aims to add the following code snippet and screenshot to the [`Cart Line Items » cartItemClass`](https://github.com/woocommerce/woocommerce-blocks/blob/6083484477410fd99d1efd5ca909288eb4d19963/docs/third-party-developers/extensibility/checkout-block/available-filters.md?plain=1#L26) section:

```js
const { registerCheckoutFilters } = window.wc.blocksCheckout;
 
// Adjust cart item class of the cart line items.
registerCheckoutFilters( 'example-extension', {
  cartItemClass: ( value, extensions, args ) => {
    // Return early since this filter is not being applied in the Cart context.
    // We must return the original value we received here.
    if ( args?.context !== 'cart' ) {
      return value;
    }
    return 'my-custom-class';
  }
} );
```

<img width="1512" alt="screenshot-2023-08-24-at-13 07 26" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/58ed0551-998b-4309-bc22-3f7be84565d6">

---

> **Note**
> The code snippet and screenshot should be placed below the table with the filter names and the sentence _"Each of these filters has the following arguments [...]"_, and should have the following subheading
```md
### cartItemClass
```

**Comment by masteradhoc** [comment]
@nielslange you can assign me this one, will work on this asap.

**Comment by nielslange** [comment]
> @nielslange you can assign me this one, will work on this asap.

Go for it, @masteradhoc! 🙌

**Comment by masteradhoc** [comment]
add matching before image
![image](https://github.com/woocommerce/woocommerce-blocks/assets/6242098/6059c77a-6375-4087-a3e5-485d7077ac54)
