### ISSUE TITLE
`Allowing blocks in specific areas in the Cart and Checkout blocks`: Add screenshot

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#10896]
Recently, we've updated the "Available Extensibility Interfaces for the Cart and Checkout blocks" post. In this post, we introduced new code snippets and screenshots. This issue aims to add the following screenshot to the [`Allowing blocks in specific areas in the Cart and Checkout blocks`](https://github.com/woocommerce/woocommerce-blocks/blob/6083484477410fd99d1efd5ca909288eb4d19963/docs/third-party-developers/extensibility/checkout-block/available-filters.md?plain=1#L176) section:

<img width="1512" alt="screenshot-2023-08-23-at-13 43 21" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/816eb52a-b052-4d98-a69e-e96b01dffd6a">

**Comment by masteradhoc** [comment]
Thanks @nielslange for the issue! I'll go ahead and create a PR for this soon.

**Comment by nielslange** [comment]
> Thanks @nielslange for the issue! I'll go ahead and create a PR for this soon.

Thanks for showing interest in working on this issue, @masteradhoc. I just assigned this issue to you.

I also see that you mentioned working on the following issues:
- https://github.com/woocommerce/woocommerce-blocks/issues/10897
- https://github.com/woocommerce/woocommerce-blocks/issues/10906
- https://github.com/woocommerce/woocommerce-blocks/issues/10908
- https://github.com/woocommerce/woocommerce-blocks/issues/10909
- https://github.com/woocommerce/woocommerce-blocks/issues/10910
- https://github.com/woocommerce/woocommerce-blocks/issues/10911
- https://github.com/woocommerce/woocommerce-blocks/issues/10912
- https://github.com/woocommerce/woocommerce-blocks/issues/10914
- https://github.com/woocommerce/woocommerce-blocks/issues/10916
- https://github.com/woocommerce/woocommerce-blocks/issues/10917

Usually, we'd assign one issue at a time to an external contributor to avoid that the contributor is drowning in work. That said, given that you've created three PRs yesterday (#10931, #10932 and #10930), which are all in a great shape and of which two have already been merged, I'll make an exception and assign all the desired tasks to you. 

If you feel that you added too much on your plate, please reach out so that I can unassign a few tasks. After all, contributing should be fun, right? 😁
