### ISSUE TITLE
`Cart Line Items » subtotalPriceFormat`: Add code snippet and screenshot

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#10900]
Recently, we've updated the "Available Extensibility Interfaces for the Cart and Checkout blocks" post. In this post, we introduced new code snippets and screenshots. This issue aims to add the following code snippet and screenshot to the [`Cart Line Items » subtotalPriceFormat`](https://github.com/woocommerce/woocommerce-blocks/blob/6083484477410fd99d1efd5ca909288eb4d19963/docs/third-party-developers/extensibility/checkout-block/available-filters.md?plain=1#L26) section:

```js
const { registerCheckoutFilters } = window.wc.blocksCheckout;
 
// Adjust subtotal price format of the cart line items.
registerCheckoutFilters( 'example-extension', {
  subtotalPriceFormat: ( value, extensions, args ) => {
    // Return early since this filter is not being applied in the Cart context.
    // We must return the original value we received here.
    if ( args?.context !== 'cart' ) {
      return value;
    }
    return '<price/> per item';
  }
} );
```

<img width="1512" alt="screenshot-2023-09-12-at-13 00 41" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/67f089bd-95d0-49f8-81f4-df2fec1a3d69">

---

> **Note**
> The code snippet and screenshot should be placed below the table with the filter names and the sentence _"Each of these filters has the following arguments [...]"_, and should have the following subheading
```md
### subtotalPriceFormat
```

**Comment by corners2wall** [comment]
@nielslange  Assign to me pls

**Comment by masteradhoc** [comment]
@nielslange you can assign this to me. will solve it as part of #10969 

before screenshot
![image](https://github.com/woocommerce/woocommerce-blocks/assets/6242098/a014c8d7-4c26-4a0a-8f4c-f74a8240bbb4)
