### ISSUE TITLE
`Cart Line Items » saleBadgePriceFormat`: Add code snippet and screenshot

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#10902]
Recently, we've updated the "Available Extensibility Interfaces for the Cart and Checkout blocks" post. In this post, we introduced new code snippets and screenshots. This issue aims to add the following code snippet and screenshot to the [`Cart Line Items » saleBadgePriceFormat`](https://github.com/woocommerce/woocommerce-blocks/blob/6083484477410fd99d1efd5ca909288eb4d19963/docs/third-party-developers/extensibility/checkout-block/available-filters.md?plain=1#L26) section:

```js
const { registerCheckoutFilters } = window.wc.blocksCheckout;
 
// Adjust sale badge price format of the cart line items.
registerCheckoutFilters( 'example-extension', {
  saleBadgePriceFormat: ( value, extensions, args ) => {
    // Return early since this filter is not being applied in the Cart context.
    // We must return the original value we received here.
    if ( args?.context !== 'cart' ) {
      return value;
    }
    return '<price/> per item';
  }
} );
```

<img width="1512" alt="screenshot-2023-08-24-at-13 13 35" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/d5e9d791-2429-4cac-b4fb-106a3dbe07ce">

---

> **Note**
> The code snippet and screenshot should be placed below the table with the filter names and the sentence _"Each of these filters has the following arguments [...]"_, and should have the following subheading
```md
### saleBadgePriceFormat
```

**Comment by corners2wall** [comment]
@nielslange  Assign to me pls

**Comment by nielslange** [comment]
> @nielslange Assign to me pls

Thanks for volunteering to work on this task. As I've just assigned #10898 to you, let's focus on that one first, before working on this issue. See also https://github.com/woocommerce/woocommerce-blocks/issues/10898#issuecomment-1716889695.

**Comment by masteradhoc** [comment]
@nielslange you can assign me this one, will work on this asap.

**Comment by nielslange** [comment]
> @nielslange you can assign me this one, will work on this asap.

Go for it, @masteradhoc! 🙌
