### ISSUE TITLE
`Order Summary Items » cartItemPrice`: Add code snippet and screenshot

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#10908]
Recently, we've updated the "Available Extensibility Interfaces for the Cart and Checkout blocks" post. In this post, we introduced new code snippets and screenshots. This issue aims to add the following code snippet and screenshot to the [`Order Summary Items » cartItemPrice`](https://github.com/woocommerce/woocommerce-blocks/blob/6083484477410fd99d1efd5ca909288eb4d19963/docs/third-party-developers/extensibility/checkout-block/available-filters.md?plain=1#L45C4-L45C23) section:

```js
const { registerCheckoutFilters } = window.wc.blocksCheckout;
 
// Adjust cart item price of the order summary items.
registerCheckoutFilters( 'example-extension', {
  cartItemPrice: ( value, extensions, args ) => {
    // Return early since this filter is not being applied in the Summary context.
    // We must return the original value we received here.
    if ( args?.context !== 'summary' ) {
      return value;
    }
    return '<price/> for all items';
  }
} );
```

<img width="1512" alt="screenshot-2023-08-24-at-13 30 39" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/a0d9e26c-51c0-4101-ae80-b626f8dd1f00">

---

> **Note**
> The code snippet and screenshot should be placed below the table with the filter names and the sentence _"Each of these filters has the following additional arguments [...]"_, and should have the following subheading
```md
### cartItemPrice
```

**Comment by masteradhoc** [comment]
Thanks @nielslange for the issue! I'll go ahead and create a PR for this soon.

**Comment by nielslange** [comment]
> Thanks @nielslange for the issue! I'll go ahead and create a PR for this soon.

Thanks for showing interest in working on this issue, @masteradhoc. I just assigned this issue to you. See also https://github.com/woocommerce/woocommerce-blocks/issues/10896#issuecomment-1719434916. 😉
