### ISSUE TITLE
`Proceed to Checkout Button Link`: Add code snippet and screenshot

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#10914]
Recently, we've updated the "Available Extensibility Interfaces for the Cart and Checkout blocks" post. In this post, we introduced new code snippets and screenshots. This issue aims to add the following code snippet and screenshot to the [`Proceed to Checkout Button Link`](https://github.com/woocommerce/woocommerce-blocks/blob/6083484477410fd99d1efd5ca909288eb4d19963/docs/third-party-developers/extensibility/checkout-block/available-filters.md?plain=1#L107) section:

```js
const { registerCheckoutFilters } = window.wc.blocksCheckout;
 
// Adjust the proceed to checkout button link.
registerCheckoutFilters( 'example-extension', {
  proceedToCheckoutButtonLink: ( value, extensions, args ) => {
    if ( ! args?.cart.items ) {
      return value;
    }
 
    const isSunglassesInCart = args?.cart.items.some(
      ( item ) => item.name === 'Sunglasses'
    );
 
    // Return the default value if sunglasses is not in the cart.
    if ( ! isSunglassesInCart ) {
      return value;
    }
 
    return '/sunglasses-checkout';
  }
} );
```

<img width="1512" alt="screenshot-2023-08-24-at-13 39 35" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/2964d529-771d-4d00-9fff-646b15d59cbf">

**Comment by masteradhoc** [comment]
Thanks @nielslange  for the issue! I'll go ahead and create a PR for this soon.

**Comment by nielslange** [comment]
> Thanks @nielslange for the issue! I'll go ahead and create a PR for this soon.

Thanks for showing interest in working on this issue, @masteradhoc. I just assigned this issue to you. See also https://github.com/woocommerce/woocommerce-blocks/issues/10896#issuecomment-1719434916. 😉
