### ISSUE TITLE
`Place Order Button Label`: Add code snippet and screenshot

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#10915]
Recently, we've updated the "Available Extensibility Interfaces for the Cart and Checkout blocks" post. In this post, we introduced new code snippets and screenshots. This issue aims to add the following code snippet and screenshot to the [`Place Order Button Label`](https://github.com/woocommerce/woocommerce-blocks/blob/6083484477410fd99d1efd5ca909288eb4d19963/docs/third-party-developers/extensibility/checkout-block/available-filters.md?plain=1#L115C4-L116C1) section:

```js
const { registerCheckoutFilters } = window.wc.blocksCheckout;
 
// Adjust the place order button label.
registerCheckoutFilters( 'example-extension', {
  placeOrderButtonLabel: ( value, extensions, args ) => {
    return '💰 Pay now 💰';
  }
} );
```

<img width="1512" alt="screenshot-2023-08-24-at-13 42 33" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/3a8babc4-2848-424b-bc4a-8137eb2b2746">

**Comment by masteradhoc** [comment]
@nielslange you can assign me this task also. PR is done and merged already :)
