### ISSUE TITLE
`Show Remove Coupon Notice`: Add code snippet and screenshot

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#10917]
Recently, we've updated the "Available Extensibility Interfaces for the Cart and Checkout blocks" post. In this post, we introduced new code snippets and screenshots. This issue aims to add the following code snippet and screenshot to the [`Show Remove Coupon Notice`](https://github.com/woocommerce/woocommerce-blocks/blob/6083484477410fd99d1efd5ca909288eb4d19963/docs/third-party-developers/extensibility/checkout-block/available-filters.md?plain=1#L290) section:

```js
const { registerCheckoutFilters } = window.wc.blocksCheckout;
 
// Prevent a couponCode called '10off' from creating a notice when it gets removed.
registerCheckoutFilters( 'example-extension', {
  showRemoveCouponNotice: ( value, extensions, args ) => {
    return args?.couponCode === '10off' ? false : value;
  }
} );
```

<img width="1512" alt="screenshot-2023-08-24-at-13 59 41" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/e5256b30-d241-4716-9a28-b531daadfee9">

**Comment by masteradhoc** [comment]
Thanks Niels for the issue! I'll go ahead and create a PR for this.

**Comment by nielslange** [comment]
> Thanks Niels for the issue! I'll go ahead and create a PR for this.

Thanks for showing interest in working on this issue, @masteradhoc. I just assigned this issue to you. See also https://github.com/woocommerce/woocommerce-blocks/issues/10896#issuecomment-1719434916. 😉
