### ISSUE TITLE
`Totals Footer Item`: Add code snippet and screenshot

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#10918]
Recently, we've updated the "Available Extensibility Interfaces for the Cart and Checkout blocks" post. In this post, we introduced new code snippets and screenshots. This issue aims to add the following code snippet and screenshot to the [`Totals Footer Item`](https://github.com/woocommerce/woocommerce-blocks/blob/6083484477410fd99d1efd5ca909288eb4d19963/docs/third-party-developers/extensibility/checkout-block/available-filters.md?plain=1#L60C4-L60C22) section:

```js
const { registerCheckoutFilters } = window.wc.blocksCheckout;
 
// Adjust the total label.
registerCheckoutFilters( 'example-extension', {
  totalLabel: ( value, extensions, args ) => {
    return 'Deposit due today';
  }
} );
```

<table>
<tr>
<td>Before:
<br><br>

![117032889-cc56b200-acf9-11eb-9bf7-ae5f6a0b1538](https://github.com/woocommerce/woocommerce-blocks/assets/3323310/91bd6aeb-4824-4f8c-80ec-79bc63185bc6)
</td>
<td>After:
<br><br>

![117033039-ec867100-acf9-11eb-95d5-50c06bf2923c](https://github.com/woocommerce/woocommerce-blocks/assets/3323310/721e0be5-31a6-4190-947c-326462d6fd98)
</td>
</tr>
</table>

**Comment by masteradhoc** [comment]
@nielslange you can assign me this task also. PR is done and merged already :)
