### ISSUE TITLE
`Show Apply Coupon Notice`: Add code snippet and screenshot

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#10916]
Recently, we've updated the "Available Extensibility Interfaces for the Cart and Checkout blocks" post. In this post, we introduced new code snippets and screenshots. This issue aims to add the following code snippet and screenshot to the [`Show Apply Coupon Notice`](https://github.com/woocommerce/woocommerce-blocks/blob/6083484477410fd99d1efd5ca909288eb4d19963/docs/third-party-developers/extensibility/checkout-block/available-filters.md?plain=1#L290) section:

```js
const { registerCheckoutFilters } = window.wc.blocksCheckout;
 
// Prevent a couponCode called '10off' from creating a notice when it gets applied.
registerCheckoutFilters( 'example-extension', {
  showApplyCouponNotice: ( value, extensions, args ) => {
    return args?.couponCode === '10off' ? false : value;
  }
} );
```

<img width="1512" alt="screenshot-2023-08-24-at-14 02 56" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/2641041d-f5e7-4895-85f8-15663c5e5ecc">

**Comment by masteradhoc** [comment]
Thanks Niels for the issue! I'll go ahead and create a PR for this.

**Comment by nielslange** [comment]
> Thanks Niels for the issue! I'll go ahead and create a PR for this.

Thanks for showing interest in working on this issue, @masteradhoc. I just assigned this issue to you. See also https://github.com/woocommerce/woocommerce-blocks/issues/10896#issuecomment-1719434916. 😉
