### ISSUE TITLE
`Coupons`: Add code snippet and screenshot

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#10911]
Recently, we've updated the "Available Extensibility Interfaces for the Cart and Checkout blocks" post. In this post, we introduced new code snippets and screenshots. This issue aims to add the following code snippet and screenshot to the [`Coupons`](https://github.com/woocommerce/woocommerce-blocks/blob/6083484477410fd99d1efd5ca909288eb4d19963/docs/third-party-developers/extensibility/checkout-block/available-filters.md?plain=1#L70) section:

```js

const { registerCheckoutFilters } = window.wc.blocksCheckout;
 
// Replace coupon label for matching coupon(s).
registerCheckoutFilters( 'example-extension', {
    coupons: ( coupons ) => {
        return coupons.map( ( coupon ) => {
            // Regex to match autocoupon then unlimited undersores and numbers
            if ( ! coupon.label.match( /autocoupon(?:_\d+)+/ ) ) {
                return coupon;
            }
            return {
                ...coupon,
                label: 'Automatic coupon',
            };
        } );
    }
} );
```

<table>
<tr>
<td>Before:
<br><br>

![123768988-bc55eb80-d8c0-11eb-9262-5d629837706d](https://github.com/woocommerce/woocommerce-blocks/assets/3323310/bb6ff77e-7c40-46f7-8d66-a7825ea78fff)
</td>
<td>After:
<br><br>

![124126048-2c57a380-da72-11eb-9b45-b2cae0cffc37](https://github.com/woocommerce/woocommerce-blocks/assets/3323310/029f993a-cf32-4f9b-abb5-af05df2477cd)
</td>
</tr>
</table>

**Comment by masteradhoc** [comment]
Thanks @nielslange for the issue! I'll go ahead and create a PR for this soon.

**Comment by nielslange** [comment]
> Thanks @nielslange for the issue! I'll go ahead and create a PR for this soon.

Thanks for showing interest in working on this issue, @masteradhoc. I just assigned this issue to you. See also https://github.com/woocommerce/woocommerce-blocks/issues/10896#issuecomment-1719434916. 😉
