### ISSUE TITLE
Open Pay Cards

### ISSUE THREAD

**Issue by KevinLima23** [woocommerce/woocommerce-gutenberg-products-block#10925]
## What do you think is missing from the Cart & Checkout blocks?

I have a problem with open pay cards bbva.

It is not compatible with payment blocks.

How could I solve it?

**Comment by opr** [comment]
Hi there @KevinLima23  👋

Thanks for taking the time to make us aware that open pay cards bbva isn’t working with the Checkout and Cart blocks. These Blocks are designed to optimize for faster checkout and it’s expected that some existing Woo Extensions that integrate with the current checkout flow in WooCommerce core will not work with the blocks.

Currently it’s up to extension developers to add support for the new checkout flow offered via the Cart and Checkout Blocks. We have some [documentation for Third-party developers](https://href.li/?https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs#third-party-developers) and some [Developer Resources](https://href.li/?https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs#developer-resources) available to help with their integration efforts.

Your best course of action now if you are using a payment method that isn’t working with the blocks is to notify the developer of the extension and ask if they can add support.

Until then, you can keep on top of the [status of the Cart & Checkout Blocks in this documentation](https://href.li/?https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/).
