### ISSUE TITLE
Incorrect postal code validation for Taiwan 

### ISSUE THREAD

**Issue by devinmaeztri** [woocommerce/woocommerce-gutenberg-products-block#10921]
## Describe the bug

I tried to create an order for someone in Taiwan with six-digit postal code. However, the postal code validation failed and I could not complete the transaction. 

@nielslange mentioned that the validation logic is located in the file [is-postcode.ts](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/packages/checkout/utils/validation/is-postcode.ts). The current regex for Taiwan postal codes is: 

```js
/^\d{3}(\d{2})?$/
```

https://en.wikipedia.org/wiki/Postal_codes_in_Taiwan#Change_from_3+2_to_3+3_postal_codes states
> The official launch of three + three digit postal codes occurred on March 3, 2020,[[2]](https://en.wikipedia.org/wiki/Postal_codes_in_Taiwan#cite_note-2) in order to support more fine grained delivery section codes. The initial three digit division codes remain unchanged, only the supplemental two digits were updated to three digits. The previous three + two digit system had been in service for 29 years, since February 1, 1991.

>  As of November 2020, three + two digit postal codes are still in common use and accepted by the post office. A significant proportion of forms and systems provide space for only three + two digit postal codes.

## To reproduce

1. Add the Cart block to a test page.
2. Enable the `Shipping calculator` in the Shipping inner block.
3. Add the Checkout block to another test page.
4. Add a test product to the cart via the frontend.
5. Navigate to the test page with the Cart block and click `Change address` in the Shipping section.
6. Select `Taiwan` as the country and enter a 6-digit postal code (e.g., `231603`).
7. Observe that validation fails.
8. Navigate to the test page with the Checkout block.
9. Repeat steps 6-7.

## Expected behavior

As stated in https://en.wikipedia.org/wiki/Postal_codes_in_Taiwan#Change_from_3+2_to_3+3_postal_codes both 5 and 6-digit postal codes for Taiwan should be validated successfully.

## Similar issue 

#10854

Thanks, @nielslange, for assisting me with this GitHub Issue.

**Comment by opr** [comment]
Hi @devinmaeztri thanks for opening this issue, it seems like something we should fix! I can reproduce the issue, and it seems Niels already added the correct labels.

~Wondering why the regex is so complex for this, why don't we just do `/^\d{5,6}$/`? Given the wiki mentions both 3+2 and 3+3 codes are common, we can just check if the code is a 5-digit or 6-digit string. What do you think?~

I see that the first three digits are required, and the last two/three are optional.

**Comment by nielslange** [comment]
> I see that the first three digits are required, and the last two/three are optional.

That's what I had in mind, @opr. I'd say, whoever works on this issue, should add the following custom rule for Taiwan (TW) 
```
[ 'TW', /^\d{3}(\d{2,3})?$/ ], 
```
to
https://github.com/woocommerce/woocommerce-blocks/blob/5b2a32ddc40e0189e7c17b0f49fb2cc94394fbae/packages/checkout/utils/validation/is-postcode.ts#L6-L18

Apart from that, it might also be handy to sort the current custom rules alphabetically to increase maintainability.
