### ISSUE TITLE
Attributes Displayed as Strings on Frontend (not respecting the type) on Custom Checkout Block

### ISSUE THREAD

**Issue by wpslashcom** [woocommerce/woocommerce-gutenberg-products-block#10923]
I have created a testing block for Checkout and while the attributes on Edit saved normally respecting the type (boolean, array on this case) , on frontend everything displayed as string

## To reproduce

Steps to reproduce the behaviour:
The new Test Blocks consists of 5 different files (edit.js, block.js, index.js, frontend.js block.json)
**edit.js** 
```
const {__} = wp.i18n;
const { registerBlockType } = wp.blocks;
const {useBlockProps} = wp.blockEditor;
const { BlockControls, InspectorControls, ServerSideRender, PlainText, MediaUpload, PanelColorSettings, ColorPalette } =  wp.editor;
const { TextControl, Panel, PanelBody, PanelRow, Button, FormToggle } = wp.components;
const { useState }  =  wp.element;
const { withDispatch } = wp.data;
const { compose } = wp.compose;


export const Edit = ( { attributes, setAttributes, className } ) => {
	const blockProps = useBlockProps();

	

	const onChangeAddNewToArray = ( value ) => {
		setAttributes( { current_value: value } );
	};

		const onChangeTestBoolean = ( value ) => {
		setAttributes( { test_boolean: value.target.checked } );
	};






	const onClickRemoveValueButton = ( element ) => {

		setAttributes({
			test_array: attributes.test_array.filter((_, i) => i!=element.target.attributes.value_id.value)
		});
	};


	const onClickAddValueButton = ( element ) => {


		if(attributes.current_value.length > 0)
		{
			setAttributes({
				test_array: [...attributes.test_array, parseInt(attributes.current_value)],
				current_value: ''
			});

		}




	};


	return (


		<div { ...blockProps }>
		
		<InspectorControls key="settings">
		<div id="gutenpride-controls">

		<Panel>
		<PanelBody title="Testing" initialOpen={ true }>
		<PanelRow>
		<TextControl
		label="Values..." onChange={onChangeAddNewToArray} value={attributes.current_value}

		/>
		<Button variant="secondary" onClick={onClickAddValueButton}>Add</Button>



		</PanelRow>

		{attributes.test_array.map(function(value, i){
			return (
				<PanelRow key={i}>{value} <Button  variant="secondary" value_id={i} onClick={ onClickRemoveValueButton } >Remove</Button></PanelRow>



				);

		})}

		<FormToggle
		checked={ attributes.test_boolean }
		onChange= {onChangeTestBoolean}
		/>

		</PanelBody>
		</Panel>


		



		</div>
		</InspectorControls>

		




		{attributes.test_array.map(function(value, i){
			return (
				<a>{value}</a>


				);

		})}


	
		</div>
		);

}

export const Save = (props ) => {
	return (
		<div { ...useBlockProps.save() }  >
		
		</div>);

}

```

**block.js**
```
const { useState, useEffect }  =  wp.element;
const { extensionCartUpdate } = wc.blocksCheckout;

const WPSlashFrontTest = ( Props ) => {
			console.log(Props);
		return (
			<div className={Props.className} >
		
			</div>
			);
		
		

		}
export default WPSlashFrontTest;
```

**index.js**
```
const { registerBlockType } = wp.blocks;

import { Edit, Save } from './edit';
import metadata from './block.json';

registerBlockType( metadata, {

	edit: Edit,
	save: Save,
} );

```

**frontend.js**

```
const { registerCheckoutBlock } = wc.blocksCheckout;

import WPSlashFrontTest from './block';
import metadata from './block.json';

registerCheckoutBlock( {
	metadata,
	component: WPSlashFrontTest,
} );
```

**block.json** 

```
{
	"name": "woocommerce/wpslash-test-block",
	"title": "Test Block",
	"apiVersion": 2,
	"description": "Test Array Block.",
	"category": "woocommerce",
    "textdomain": "wpslash-test-block",

	"parent": [ "woocommerce/checkout-totals-block", "woocommerce/checkout-order-summary-block" ],
	"attributes": {
		"className": {
			"type": "string",
			"default": ""
		},

		"current_value": {
			"type": "string",
			"default": ""
		},

		
		"test_array": {
			"type": "array",
			"default": [5,10,20,30]
		},
		"test_boolean": {
			"type": "boolean",
			"default": false
		}
	}
}
```

I am using `console.log` to see all the `Props` I have in frontend and I can see these attributes in the frontend but without respecting the attribute type (boolean and array displayed as strings) as you see also in the screenshot below.
Additionally noticed that if setAttributes is not used (if not change the value of attributes and keep the defaults I have set in block.json) attributes are not displayed inside Props in frontend.

![Screenshot 2023-09-12 at 5 38 58 PM](https://github.com/woocommerce/woocommerce-blocks/assets/129197029/9c9a8fed-9fc4-4e5b-a84d-e3e68ef626b9)

### WordPress

-   WordPress version: 6.3.1
-   WooCommerce version: 8.0.3
-   WooCommerce Blocks version: 11.1.0
-   Site language:English

**Comment by opr** [comment]
Hi, thanks for commenting. These attributes should be saved to the database in the correct format, however the way you're accessing them (through the front-end) means that they will always be represented as strings, this is because they are printed as attributes on a DOM node, so their true type won't be saved.

To allow us to help you further here, could you give us a description of the use case you're working toward? We may be able to suggest some alternatives.

Thanks!

**Comment by wpslashcom** [comment]
Hi @opr ,
Thanks for your feedback. I am creating a block for the new Block Based Checkout  and I want to have the ability to access some attributes In the frontend . In my specific case I want to to display some buttons on the frontend based on the array values  (Display some Add A Tip Buttons like 10%, 20% , 30% ) where the user will have specified these values from Block Settings (Will add the percentage values to the array type attribute from Block Edit )

**Comment by opr** [comment]
> Thanks for your feedback. I am creating a block for the new Block Based Checkout and I want to have the ability to access some attributes In the frontend . In my specific case I want to to display some buttons on the frontend based on the array values (Display some Add A Tip Buttons like 10%, 20% , 30% ) where the user will have specified these values from Block Settings (Will add the percentage values to the array type attribute from Block Edit )

Makes sense, how about having the user add a single "tip button" for each tip level, then the amount can be saved on that button and parsed into an integer. Alternatively you could `JSON.parse` the array you're saving and then parse each "number" into an integer.

I don't think there's anything we can change on our end to help here as they are just attributes on DOM nodes, so I'll close this issue, but feel free to comment and add more information if you need more help!

**Comment by wpslashcom** [comment]
Hi @opr ,
I didn't thought to use `JSON.parse` . This will work on my case. (I will try it to make this way).
Also what about the default attributes not exposed in frontend (if not changed  from Block Edit) ?
Is this normal or I must trigger a setAttributes with the default values first ?

**Comment by opr** [comment]
Hi @wpslashcom glad it will work for you! 

> Also what about the default attributes not exposed in frontend (if not changed from Block Edit) ?
Is this normal or I must trigger a setAttributes with the default values first ?

Sorry but I don't know for _certain_, but I think you're right, if you want to explicitly set that attribute it's best to use `setAttributes` to do that.
