### ISSUE TITLE
Single Product Block > Impossible to change the width

### ISSUE THREAD

**Issue by nefeline** [woocommerce/woocommerce-gutenberg-products-block#10960]
## Describe the bug

When attempting to change the width of the Single Product block, the changes are never visible on the front end.

## To reproduce

1. Create a new post
2. Insert the Single Product block
3. Change the default width to any of the available options:

<img width="253" alt="Screenshot 2023-09-15 at 00 39 58" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/afed42c2-a35d-4a10-b191-9d0d68cc1873">

4. Notice how the width is changed in the editor
5. Save the post and go to the frontend
6. Notice how the width doesn't match what is in the editor.

## Expected behavior

Changes in width for the Single Product block should be visible on the front end.

**Comment by danieldudzic** [comment]
I was also able to replicate!
