### ISSUE TITLE
Make filter blocks contextual

### ISSUE THREAD

**Issue by dinhtungdu** [woocommerce/woocommerce-gutenberg-products-block#10985]
With #10873 merged, we can make all filter blocks contextual in one place, Collection Filter wrapper block. So having one issue for each filter block is no longer needed.

Replaces #10570 #10573 #10572 #10569 

> Based on the two discussions seen https://github.com/woocommerce/woocommerce-blocks/discussions/10678 and https://github.com/woocommerce/woocommerce-blocks/discussions/10691 we've decided to have filters available only in the context of a product collection block. This makes it much easier for us to tackle this issue because now we have direct context access to the product collection block.

> In addition, each filter will also live inside a wrapper container called Collection Filters which the initial draft is created https://github.com/woocommerce/woocommerce-blocks/pull/10726

**Comment by Marc-pi** [comment]
good to have added a Collection Filters block, i was yesterday playing with filter blocks and Product Collection, and stuck to this.
about making them contextual, seems you're only discussing about the context of the collection query passed to the new collection filters block.
What about the context of one filter passed to the other ones within the new block ? (e.g nested filters / dynamic filters) ?
(if you choose one value for the first filter, it impacts the options for the other ones)
should i open a new issue on this or you'll cover the need through this same issue/PR ?

**Comment by dinhtungdu** [comment]
> What about the context of one filter passed to the other ones within the new block ? (e.g nested filters / dynamic filters) ?

@Marc-pi This is something we want to re-evaluate. The current filter blocks will affect others. For example, when we choose an attribute, the price filter will update to show the price range of matched products. This is good but somewhat unpredictable. It's also a confusing because the reverse isn't true: when we choose a price range, attribute options remain the same, then if we choose an attribute, we get no result.

What do you think? Should applied filter affects other filter blocks?

**Comment by sunyatasattva** [comment]
> What do you think? Should applied filter affects other filter blocks?

I know the question wasn't directed to me, but personally I think it is helpful for filters to be influencing each other. It is also helpful too see things at a glance, without necessarily browsing the products (e.g. I select products with the blue attribute, and I see via the price filter that they are outside my budget/price range). This is a technique I often use in my own shopping.

**Comment by Marc-pi** [comment]
> Should applied filter affects other filter blocks?

@dinhtungdu for me it is a big YES
When we use the Product Collection Block (loop), we need filters to ease the product discovering.
That's the purpose of the new Collection Filter Block
Nested / dynamic filters is a must have to bring Woo at the state of art (it has a great impact on conversion)
I do understand it can be tricky in some cases (see your above example), but let's do it

I did not test the new Collection Filter block yet, but we should be able 
- to display it horizontaly (above the block), and vertically (sidewise). 
- to have attribute filters, price ranges in conjonction with category filters, maybe tags

**Comment by sunyatasattva** [comment]
> to display it horizontaly (above the block), and vertically (sidewise).
> to have attribute filters, price ranges in conjonction with category filters, maybe tags

All of this will be possible 🙏

**Comment by Marc-pi** [comment]
> All of this will be possible 

soon we will dream live ;-)
keep it up !

**Comment by gfarma** [comment]
It would be nice to add 2 more features at attributes/tax/tag filters:
1) Instead of plain text at attributes-filter, could you add images or attribute swatches? It is much cleaner for the end-user to see an image at many scenarios (or an image & a text below)
2) Any workaround to add ranges or input values for attributes with numbers? (without sacrificing speed of course)

**Comment by dinhtungdu** [comment]
> Instead of plain text at attributes-filter, could you add images or attribute swatches? It is much cleaner for the end-user to see an image at many scenarios (or an image & a text below)

@gfarma we're considering creating filter blocks as the parent blocks to provide context/data. Each filter block can have multiple views/styles which are inner blocks. Developers can register custom inner blocks and free to structure/style them as they want. With the custom view, you can control 100% how attribute display. The tricky part might be how to set image/color or other data to attribute to display it to customers. It's not practical to do that in WC Core as a single or two options can't cover every use-case. It maybe better to to do it from site plugin, and we can do something to passing those custom data down to inner blocks so developers can use it inside their custom view (both in Editor and on the front end).

> Any workaround to add ranges or input values for attributes with numbers? (without sacrificing speed of course)

This is definitely a tricker issue. Attribute is taxonomy term under the hood. We use taxonomy query to filter products by attribute. The problem here is that taxonomy query doesn't have compare operator like meta query has. So for now, I don't have any workaround and solution for your case, sadly.
My only thought is, if possible, you can structure your attribute differently. In stead of using single number as the attribute value, you can use value representing a range, then your attribute filter becomes a normal one.

**Comment by dinhtungdu** [comment]
Reopening this one as we need to implement the contextual logic in the editor.
