### ISSUE TITLE
Handpicked product block: search by sku

### ISSUE THREAD

**Issue by nbatteur** [woocommerce/woocommerce-gutenberg-products-block#1098]
**Is your feature request related to a problem? Please describe.**
We have many products with same name but with different SKUs. When we search in the Handpicked product block, we could'nt distinguished a product from another.

**Describe the solution you'd like**
Integrate a search by SKU.

Thank you so much.

**Comment by kaelhoel** [comment]
Searching by SKU is a must for larger webshops. It saves a lot of time and should be a standard feature.

**Comment by gabrielbaillie** [comment]
Searching by SKU (or WooCoomerce product ID at least) is a must for larger webshops. 
Should be a standard feature.
