### ISSUE TITLE
Add to Cart Button in Single Product Block Does Not Respect the 'Add to Basket Behaviour' Setting in WooCommerce 

### ISSUE THREAD

**Issue by Babylon1999** [woocommerce/woocommerce-gutenberg-products-block#10992]
## Describe the bug

Reported in zd-6849837

The add to cart button in the Single Product block doesn't respect the **Add to basket behaviour** in WooCommerce settings.

<img src="https://d.pr/i/H1IKNc+" alt="">
Link to image: https://d.pr/i/H1IKNc

## To reproduce

1. Add the Single Product block to a new page.
2. Head to ` WooCommerce > Settings > Products > General `and enable the **Redirect to the basket page after successful addition**  option.
3. Head back to the page where you added the Single Product block and try to add the product to cart.
4. Instead of being redirected to the cart page, the product page will just refresh.

## Expected behavior

To be redirected to the cart page

## Screenshots

As you can see, when I try with another block, I'm redirected to the cart page:

<img src="https://d.pr/i/rrhdZX+" alt="">
Link to image: https://d.pr/i/rrhdZX

### Desktop (please complete the following information):

-   OS: MacOS
-   Browser Firefox

---

**Comment by maxlaf** [comment]
Hi @Babylon1999, thanks for reporting this. This looks like the same issue as #10775 so I'm going to close this one. If I'm missing anything here, please don't hesitate to reopen this. Thanks!
