### ISSUE TITLE
Product Search block results returns 404 with WC 3.8.0-rc.2

### ISSUE THREAD

**Issue by treibalen** [woocommerce/woocommerce-gutenberg-products-block#1100]
**Describe the bug**
Product Search block doesn't return any results. 

**To Reproduce**

1. Create a page with Product Search block:

![https://cld.wthms.co/fAISdx](https://cld.wthms.co/fAISdx+) 
Full Size: https://cld.wthms.co/fAISdx

2. Search for any product:

![https://cld.wthms.co/MzaYcK](https://cld.wthms.co/MzaYcK+) 
Full Size: https://cld.wthms.co/MzaYcK

The URL of this page is the following - https://wc38.mystagingwebsite.com/product-search/?s=hoodie&post_type=product

3. If I search from 404 page once again, it does return results:

![https://cld.wthms.co/1c4fuc](https://cld.wthms.co/1c4fuc+) 
Full Size: https://cld.wthms.co/1c4fuc

The URL becomes - https://wc38.mystagingwebsite.com/?s=hoodie&post_type=product

**Expected behavior**

**Screenshots**

**WordPress (please complete the following information):**

* Core version: 5.2.4
* WooCommerce version: 3.8.0-rc.2
* Site language: English
* Any other plugins installed: clean install

**Comment by nerrad** [comment]
This is fixed as of #1054.  WC core is aware and the fix should land in WC 3.8.  Thanks for reporting!

**Comment by nerrad** [comment]
If you want, you can try version 2.4.4 of the Woo Blocks plugin (now available on WordPress.org) which contains the fix.  That should help verify that it's been resolved.
