### ISSUE TITLE
Product Collection: Consider Removing "Authors" Filter

### ISSUE THREAD

**Issue by imanish003** [woocommerce/woocommerce-gutenberg-products-block#11002]
During a recent discussion (p1695020614699169-slack-C02FL3X7KR6) among our team, we revisited the relevance and utility of the "Authors" filter currently implemented in the Product Collection block. Our analysis brought us to a few crucial observations that warrant further consideration:

- **Limited Usage Scenarios**: In general use, WooCommerce doesn't prominently feature or utilize 'authors' for products. The 'author' field doesn't prominently appear in product creation and editing workflows, and it is noted that it does not have much utility in the block.
- **Alternative Solutions**: For merchants wanting to categorize or differentiate products based on the individual who added them, existing functionalities like tags and categories offer an alternative solution.
- **User Experience (UX)**: There exists a concern that retaining the "Authors" filter might potentially clutter the user interface, thereby possibly detracting from the overall user experience. Considering the filter doesn't cater to a prevalent use-case, its existence might be more of a hindrance than a benefit.

**Comment by Marc-pi** [comment]
i agree, not as usefull as for Page/Posts in eCommerce context :-)
