### ISSUE TITLE
Missing “VAT Number” and “SDI” fields

### ISSUE THREAD

**Issue by Pimialsa** [woocommerce/woocommerce-gutenberg-products-block#11004]
Salve, 
Vi contatto in merito a voci mancanti per modificare l'area pagamenti nel sito Woocommerce. Per le fatturazioni ai clienti, manca l'inserimento dell'input form "Partita iva" e "SDI": campi essenziali per poter fatturare un acquisto, ma che ora non è possibile aggiungere perché è assente nel template. Spero riusciate a farci avere un nuovo aggiornamento il prima possibile per poterci permettere di iniziare ad usare il sito.

porgo cordiali saluti,
Alessandro Adamo.

---

## Translation and added context (by @sunyatasattva)

> Hello,

> I contact you regarding some missing fields in the payment areas of WooCommerce websites. To invoice customers, we are missing the “VAT Number” and ”SDI” inputs: these are essential fields to invoice a purchase, but that are currently missing from the template. […]

In Italy, in order to get tax invoices you need to be able to input your company VAT Number, and, for electronic invoices, the “SDI” which is another form of tax code that basically adds verifiability to the transactions.

**Comment by nielslange** [comment]
Dear @Pimialsa,

Thank you very much for reaching out, and I appreciate your patience. Based on @sunyatasattva's translation and comment, I understand that you are looking to incorporate two additional fields in the checkout:

1. VAT Number
2. SDI Code

## VAT Number

Should you require a feature that validates the VAT number, please consider using the [EU VAT Number](https://woocommerce.com/document/eu-vat-number/) extension.

<img src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/29583b5c-faea-4149-8411-8195ed4e713c" alt="EU VAT Number Extension Screenshot" width="2559">

<br><br>

Alternatively, if VAT validation is not mandatory, you may simply include a paragraph before the order notes field, requesting your customers to provide their VAT number.

<img src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/d2621ba1-e5b3-4833-939e-a3bd85b4878c" alt="Order Note Field Screenshot" width="2558">

## SDI Code

For the verification of SDI codes, I regret to inform you that I cannot recommend a direct solution at this time. Given the specificity of this requirement, a functionality for SDI code validation is not included in the default features of WooCommerce Blocks; it would ideally be developed as an extension. You can refer to [this tutorial](https://developer.woocommerce.com/2023/08/07/extending-the-woocommerce-checkout-block-to-add-custom-shipping-options/) to learn more about extending the WooCommerce Checkout block.

If SDI code validation is not required, the same approach used for the VAT number can be applied.

## Related issues

We acknowledge the existing limitations regarding the VAT field and have noted similar requests in the following tickets:

- https://github.com/woocommerce/woocommerce-blocks/issues/3096
- https://github.com/woocommerce/woocommerce-blocks/issues/3499
- https://github.com/woocommerce/woocommerce-blocks/issues/4213
- https://github.com/woocommerce/woocommerce-blocks/issues/10742

I understand the importance of this feature, and I wish I could offer a firm commitment or timeline for its implementation in WooCommerce Blocks. Unfortunately, I am unable to do so at present. Thus, I will have to close this issue for the time being.

**Comment by Pimialsa** [comment]
Dear @nielslange,

thank you so much for answering me. I tried to install the plugin to insert the two fields in the checkout as you showed me in the first example, but unfortunately it didn't work because the theme I use ("kedai") has blocked templates.
So as you indicated in the second example, I inserted a text string above the order notes.
thanks again and have a nice day.

Alessandro Adamo.

**Comment by nielslange** [comment]
Hello @Pimialsa, 

I'm glad to hear that my suggestions were helpful to you. I also wish you a nice day and a pleasant weekend! 🙌
