### ISSUE TITLE
Filter by xx blocks > dropdown style > UX > don't repeat "select"

### ISSUE THREAD

**Issue by Marc-pi** [woocommerce/woocommerce-gutenberg-products-block#11021]
## Describe the bug

When adding filter blocks with the Dropdown display set, the default placeholder repeats "select xxxx"

## To reproduce

* Define your attributes and populate some products with attribute values
* Add filter by attributes, for instance, on top of the shop page within the Product Catalog template
* Observe the repetition

## Expected behavior

People know that they have to select when they see a selector : it's the natural way
* repeating the action on the default dropdown value adds too much noise (UX) : the attribute name is suffiscient
* it increases the size selector width with no added value
* The arrow explains already we have to select and that the dropdwn is clickable

Apply the same UX adjustement on the other filtering blocks
and on the new Collection Filters block

## Screenshots

![image](https://github.com/woocommerce/woocommerce-blocks/assets/919332/f30f5ab6-7a4f-437a-a74f-32d3ab4b63a0)

## Environment

- WP 6.3.1
- Woo 8.1.1
- Woo Blocks 11.1.0
- Gutenberg 16.6.0
- TT3 theme

**Comment by sunyatasattva** [comment]
Hello @Marc-pi , thanks for the feedback and the suggestion. We are currently reworking all the filters blocks for the new Product Collection block. As such, we are not going to spend time changing the UX of what will soon be legacy blocks.

You'll be happy to know that most likely the UX would be closer to what you are envisioning in the future. Here is a sneak peek (work in progress and subject to change!):

<img width="447" alt="Screenshot 2023-09-23 at 18 58 29" src="https://github.com/woocommerce/woocommerce-blocks/assets/1847066/bf8ce47c-50a5-46d9-ab3a-eee2ba8e95f8">

In the meantime, if you just want to change the strings, perhaps you can achieve that by using a custom translation plugin and replace those strings!

**Comment by Marc-pi** [comment]
yep, i saw, hope it will come soon :-)
