### ISSUE TITLE
Hydration: Warning of undefined array key

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#11059]
## Describe the bug

When proceeding to the checkout while the cart holds a product that is out of stock, the following warning is visible on the checkout page:

```
Warning: Undefined array key "/wc/store/v1/checkout" in /Users/***/Plugins/woocommerce-blocks/src/Domain/Services/Hydration.php on line 51
```

## To reproduce

1. Install and activate a block theme, e.g. [Twenty Twenty-Three](https://wordpress.org/themes/twentytwentythree/).
2. Create a test page and add the Cart block to it.
3. Create a test page and add the Checkout block to it.
4. Create a test product with the Stock status: In stock.
5. Go to the frontend and add the test product to the cart.
6. Go to the cart page.
7. Change the Stock status to  Out of stock.
8. See that the cart page shows the following error:
```
“PRODUCT” is out of stock and cannot be purchased. Please remove it from your cart.**
```
9. Click the `Proceed to Ckecout button`.
10. See that the checkout page shows the following warning:
```
Warning: Undefined array key "/wc/store/v1/checkout" in /Users/***/Plugins/woocommerce-blocks/src/Domain/Services/Hydration.php on line 51
```

## Expected behavior

I do not expect to see the undefined array key warning.

## Screenshots

<table>
<tr>
<td valign="top">Cart page:
<br><br>
<img width="1512" alt="Screenshot 2023-09-27 at 12 39 38" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/3dd5d88e-a2c1-4074-a263-21183ed2b484">
</td>
<td valign="top">Checkout page:
<br><br>
<img width="1512" alt="Screenshot 2023-09-27 at 12 45 48" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/d8fc3f1b-b14d-42a1-8ed1-c0576118c5ea">
</td>
</tr>
</table>

**Comment by senadir** [comment]
Yes I'm seeing that as well but I don't think it was limited to out of stock items, but if you can reproduce like that and all good.

**Comment by nielslange** [comment]
> Yes I'm seeing that as well but I don't think it was limited to out of stock items, but if you can reproduce like that and all good.

It might also be triggered in other scenarios. I just noticed it when changing the stock status of a product after it had been added to the cart, that's why I mentioned this example in this issue.

**Comment by mikejolley** [comment]
This was fixed in https://github.com/woocommerce/woocommerce-blocks/pull/11128
