### ISSUE TITLE
Checkout block: In the Block Editor, display the merchant defined pickup locations instead of the mocked ones

### ISSUE THREAD

**Issue by ralucaStan** [woocommerce/woocommerce-gutenberg-products-block#11072]
In the Editor we show for the Local Pickup option mocked data for pickup locations.
This is a confusing experience and we could improve it by displaying the locations defined in the WC Admin.

<img width="666" alt="Screenshot 2023-09-29 at 16 40 17" src="https://github.com/woocommerce/woocommerce-blocks/assets/1628454/26a2f601-24ad-469e-9fa3-b595122d115a">

**Comment by pmcpinto** [comment]
I'm closing this issue, as I created a new one that includes more areas: https://github.com/woocommerce/woocommerce/issues/42092
