### ISSUE TITLE
Product Category Selection: Searching does not trigger API request, only searches subset already loaded

### ISSUE THREAD

**Issue by hexagongirl** [woocommerce/woocommerce-gutenberg-products-block#111]
Steps to reproduce:
- Create 7+ WooCommerce product categories
- Add Products block to a page
- Select 'Product Category' for your display option
- Only first 6 categories are visible/available for selection?

I've temporarily got around this by re-ordering my product categories, so the one I need is visible/selectable in the products block. Haven't tested on a clean install/default theme, so there's a possibility this could be linked to my setup.

Other minor points:
- Draft products are shown in the block (in admin), but not in live.
- Would be nice to be able to order by menu order?

Thanks!
Sarah

**Comment by GlennMartin1** [comment]
I have identical issue since the beginning.

Waiting for a resolution before I can transition to WC Gutenberg.

**Comment by MAJA1970** [comment]
I have the same problem, and the search doesn't work for categories that are not showing up.

**Comment by ryelle** [comment]
This isn't an issue in the new "Products by category" block which will be released in v1.2, so I'm going to close this issue & suggest you switch to the new block when it comes out.

**Comment by GlennMartin1** [comment]
What's the ETA for release?

**Comment by ryelle** [comment]
We're aiming for next week, to tie into the WP 5.0 release.

**Comment by GlennMartin1** [comment]
Will this become a part of WC Core, or remain a separate plugin?

**Comment by ryelle** [comment]
Yes, the new blocks will be merged into WC Core, but we're planning to create a few more blocks in this plugin before we look at doing that merge.
