### ISSUE TITLE
Product hero and Product details listing block patterns run a query on every page load

### ISSUE THREAD

**Issue by Ritchbox** [woocommerce/woocommerce-gutenberg-products-block#11103]
## Describe the bug

Product hero and Product details listing block patterns run a query on every page load. This occurs on every single page, if the block is in use or not.

## To reproduce

1. Load WooCommerce / Blocks
2. Load main site (not admin)
3. Load any page
4. Check queries loading on page
With debug bar: Open debug bar -> queries -> component: WooCommerce, caller: WP_Query->get_posts()

## Expected behavior

The product query for these blocks should only run on pages they are included in (not every page load).

## Screenshots

N/A

### WordPress (please complete the following information):

-   WordPress version: 6.3.1
-   Gutenberg version (if installed): 16.1
-   WooCommerce version: 8.1.1
-   WooCommerce Blocks version: 10.9.3
-   Site language: English
-   Any other plugins installed: N/A

### Desktop (please complete the following information):

-   OS: macOS 13.5.1
-   Browser: FireFox, Chrome
-   Version: 118.0.1, Chrome: 117.0.5938.132 

## Additional context

Happy to submit a PR with a little guidance on how we should solve the issue

**Comment by tjcafferkey** [comment]
Thanks for submitting this issue. We're able to replicate the problem and are currently looking into a fix. We'll update here once we've made any progress.
