### ISSUE TITLE
[WC 3.8] Backward compatibility issue for Product grid blocks

### ISSUE THREAD

**Issue by Chouby** [woocommerce/woocommerce-gutenberg-products-block#1110]
**Describe the bug**
WC 3.8 introduces a new way to render products grid blocks instead of using shortcodes.

In shortcodes (and thus in previous versions of WooCommerce blocks), it is possible to filter the query args with the filter `woocommerce_shortcode_products_query`. In Polylang for WooCommerce we use this filter to render only products in the current language.

Since WC 3.8, the blocks don't use shortcodes anymore. The filter `woocommerce_shortcode_products_query` isn't honored any more. But worse, there is no equivalent filter in the equivalent method `parse_query_args`. See the code in version 2.4.3 included in WC 3.8 RC2: https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/v2.4.3/src/BlockTypes/AbstractProductGrid.php#L137-L157

As a consequence for Polylang users, the blocks will now render products in all languages, instead of products in the current language in WC < 3.8.

Would it be possible to honor the filter `woocommerce_shortcode_products_query` or, maybe better as the name wouldn't be relevant, create a new filter for product blocks query args?

**WordPress (please complete the following information):**

* Core version: 5.2
* WooCommerce version: 3.8 RC2
* Any other plugins installed: Polylang and Polylang for WooCommerce

**Comment by nerrad** [comment]
@mikejolley it sounds like #1086 should help with this right?

**Comment by Chouby** [comment]
I had seen that the master branch was different but did not interpret correctly the code at first view. I focused on the filter `woocommerce_blocks_product_grid_is_cacheable` which would have allowed us to bypass the cache, but I missed that `BlocksWpQuery` which allows to include query args added by the action `parse_query` in the cache key and thus allows to use `parse_query` for blocks as we do with the filter `woocommerce_shortcode_products_query` for shortcodes. 

Thank you @nerrad for opening my eyes! 

In which version of WooCommerce do you plan to merge this PR?

**Comment by nerrad** [comment]
@Chouby probably WC 3.9 at the earliest.

**Comment by Chouby** [comment]
@nerrad I understand that it may be too late now for WC 3.8, but would it be possible to consider to introduce this in a point release? I am not comfortable with the fact that multilingual shops using products grid blocks would have to completely skip the 3.8.x versions or renounce to use this kind of blocks.

**Comment by nerrad** [comment]
Generally, we don't specifically put out point releases for enhancements or features in WooCommerce core.  However, it's really exciting that your users are wanting to use the new blocks on their multilingual sites!  One option they may have if they don't want to wait for the next version of WooCommerce core is to install the WooCommerce blocks feature plugin which will give them the latest.  We're currently scheduled to release version 2.5 of the feature plugin sometime in the latter half of November (if all goes well), so that might be an option for them.

**Comment by Chouby** [comment]
Thank you for your answer. For me it's not an enhancement, but a backward compatibility issue. Our common users can, for example, use the Top rated products block since WooCommerce 3.6 without any issue. Updating to WooCommerce 3.8 will break this feature. That's why I asked if it was possible to push that in a minor release.

Thank you for the suggestion to use the version 2.5 of the WooCommerce blocks feature plugin. I will suggest this to our users when it will be available.

**Comment by fero8** [comment]
I see that this was targetted for 2.5 release but still has not been implemented. This new blocks behavior breaks plugins like WPML. I am waiting for this to be implemented for our site to behave properly.

As of now, any blocks that do get cached are not able to be cached based on, for example, a language parameter - thus making usage of blocks with plugins like WPML unusable -> this was a breaking change from WC 3.8.

Could this be implemented please?
