### ISSUE TITLE
Product Gallery: Row justification setting isn't being saved

### ISSUE THREAD

**Issue by danieldudzic** [woocommerce/woocommerce-gutenberg-products-block#11104]
## Describe the bug

When setting the Justification of the `Product Gallery > Row` block, saving and reloading the setting doesn't persist.

## To reproduce

1. With a block theme, open `Appearance > Editor`.
2. Open `Templates > Single Product`.
3. Select `Convert to Blocks` if you are using the Classic Templates.
4. Add the `Product Gallery` block.
5. Select the `Row` block and set the justification to `Justify items center`.
6. Save and re-load. Notice the setting is back to default.

## Screenshots
<img width="1320" alt="Single_Product_‹_Template_‹_Editor_‹_newproductgallery_—_WordPress" src="https://github.com/woocommerce/woocommerce-blocks/assets/905781/db844bf8-9888-47c0-a8e4-ca34f44d46ba">

**Comment by roykho** [comment]
Hi @danieldudzic - is the issue the setting won't save only or also the setting has no effect? Because in my test, not only does the setting not save, in editor, changing the setting also doesn't update the justification visually.

**Comment by danieldudzic** [comment]
The setting saves correctly and has an effect in the editor and on the frontend.

It's best to test by setting `Product Gallery` to `Full width`.
