### ISSUE TITLE
Order Confirmation template doesn't recognise the header and footer template parts

### ISSUE THREAD

**Issue by alexflorisca** [woocommerce/woocommerce-gutenberg-products-block#11106]
## Describe the bug

The Order Confirmation template doesn't recognise the header and footer template parts.

## To reproduce

1. ~Switch to WP 6.4-beta1~
2. Activate the Twenty Twenty-Four theme
3. Go to Appearance > Editor > Templates > Order Confirmation. If it isn't blockified yet, click inside the template twice and press "transform to blocks".  
4. Verify that the header and footer template parts are recognised
5. Switch to the Twenty Twenty-Three theme
6. Go to Appearance > Editor > Templates > Order Confirmation
7. Notice that the header and footer are missing with an error as in the screenshot below
8. On the front end, place an order and see that the header and footer are missing with an error as in the screenshot below. Leave this tab open
9. Switch back to the Twenty Twenty-Four theme
10. Refresh the order confirmation page. Notice the header and footer appear

> **Note**
> Initially, we assumed that this issue was related to WordPress 6.4. It turned out that this issue already existed in earlier versions and also affect different themes.

## Expected behavior

I would expect to see the header and footer to be there.

## Screenshots

![external-scarab jurassic ninja_checkout_order-received_92__key=wc_order_GKZ123OiXgTRN](https://github.com/woocommerce/woocommerce-blocks/assets/3966773/c06deae8-379b-4067-8b84-9a7447210d52)

### WordPress (please complete the following information):

-   WordPress version: 6.4-beta1
-   WooCommerce version: 8.1.1
-   WooCommerce Blocks version: 11.2.0
-   Site language:
-   Any other plugins installed:

**Comment by nielslange** [comment]
Closing this issue as it's caused due to a bug in the `BlockTemplatesController` and will be addressed as part of refactoring that controller.
