### ISSUE TITLE
Shipping and billing address

### ISSUE THREAD

**Issue by gfarma** [woocommerce/woocommerce-gutenberg-products-block#11119]
## What do you like about the Cart & Checkout blocks?
The speed is good, for both blocks.

## What do you think is missing from the Cart & Checkout blocks?
I think that the default option at the shipping should be ticked (use the same as billing) or when you hit the tick (something like "add a different shipping address" to open then the shipping address block. 
Because now with the shipping address opened the block is too large and most of the times billing and shipping is same.

**Comment by senadir** [comment]
The option is checked by default unless you unchecked in the editor.

You can get the behavior you're looking for by checking it in the editor and saving again.

**Comment by gfarma** [comment]
Thanks
