### ISSUE TITLE
[3.8 rc2] Reviews by Category block: add category of the product

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-gutenberg-products-block#1112]
**Is your feature request related to a problem? Please describe.**

I am testing WC 3.8 rc2 and see that I can only see the category of the product for which I want to add a review on the page when I am selecting it. In the example below, the 2 categories of products are `Electronica` and `Jazz`:

![reviews2](https://user-images.githubusercontent.com/19143190/67946412-45db8480-fbd9-11e9-842a-9296da447338.jpg)

However, when categories are selected, there is no way of knowing the categories of the products as the review displays the name of the product only: 

![reviews2 1](https://user-images.githubusercontent.com/19143190/67946475-5ee43580-fbd9-11e9-8811-2b4d32f3ea73.jpg)

When the page is published, it is also not clear what categories of products the reviews are for:

![reviews2 2](https://user-images.githubusercontent.com/19143190/67946513-70c5d880-fbd9-11e9-9dba-05a9c5319935.jpg)

**Describe the solution you'd like**

It will be great to know what categories of products the reviews are for. Perhaps add it under the username and date. The option to display the category can be added to the sidebar along with other options:

![reviews2 3](https://user-images.githubusercontent.com/19143190/67946905-4cb6c700-fbda-11e9-9e36-30e7d960d483.jpg)

**Describe alternatives you've considered**

Another way to approach this could be by adding the category name as a title to group all the reviews in that category:

![reviews2 4](https://user-images.githubusercontent.com/19143190/67947041-9acbca80-fbda-11e9-9578-f09fdad9c6ca.jpg)

**Additional context**

No additional context. 
<hr>
Credit for this issue goes to @LCmry.

**Comment by nerrad** [comment]
I agree this would be a good enhancement to the block.  Just not clear on the priority for this.  Is it a must have for WC 3.8?

**Comment by juliaamosova** [comment]
>Is it a must have for WC 3.8?

I don't think it is a must-have for WC 3.8 but will be a good enhancement to include in the next release IMO.
