### ISSUE TITLE
[3.8 rc2] Hyphen doesn't render correctly in the product title in blocks

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-gutenberg-products-block#1113]
**Describe the bug**

The hyphen doesn't render correctly in the product title. I noticed it in the `Review by Category` block. 

Here is how the product page looks like (where hyphen renders correctly):

![hyphen1](https://user-images.githubusercontent.com/19143190/67948349-702f4100-fbdd-11e9-8beb-f382b0c239b4.jpg)

Here when adding `Review by Category` block, hyphen doesn't render correctly:

![hyphen2](https://user-images.githubusercontent.com/19143190/67948391-82a97a80-fbdd-11e9-9bcc-41fe38839ccc.jpg)

And here is how `Review by Category` block titles look at the front end:

![hyphen3](https://user-images.githubusercontent.com/19143190/67948417-9228c380-fbdd-11e9-9a2c-67ceadd570b0.jpg)

Note that only the stand-alone hyphen doesn't display correctly. It renders correctly when a part of the word such as `T-Shirt`, for example. 

**To Reproduce**

1. Create a new product with a stand-alone hyphen (meaning something like `Cosmos - Sun`, not `Cosmos-Sun` where a hyphen is a part of the word);
2. Publish the product and make sure it looks good at the front end;
3. Leave a review for that product on the product page. Note the category this product belongs to; 
4. Create a new page to add blocks to;
5. Add `Review by Category` block to that page;
6. Select a category of the product that you created so the product's review could be displayed;
7. Note how the hyphen doesn't render correctly in the title of the product you created. 

**Expected behavior**

I expected the hyphen to be rendered correctly in the product title of the `Review by Category` block. 

**Screenshots**

See screenshots in the description of the bug section. 

**WordPress (please complete the following information):**

* Core version: [5.2.4]
* Gutenberg version: not installed
* WooCommerce version: [3.8 rc2]
* WooCommerce Blocks version: not installed as they are a part of 3.8 rc2
* Site language: English
* Any other plugins installed: Jetpack by WordPress.com, WooCommerce Beta Tester, WooCommerce Stripe Gateway.

**Desktop (please complete the following information):**

* OS: MacOS Mojave
* Browser: Chrome
* Version: Chrome 77.0.3865.120

**Smartphone (please complete the following information):**

Same error on the smartphone:

![hyphen4](https://user-images.githubusercontent.com/19143190/67949694-15e3af80-fbe0-11e9-8138-b3e4366f0b00.jpg)

* Device: Pixel 2
* OS: Android v 10
* Browser: Chrome
* Version: Chrome 78.0.3904.62

**Additional context**

No additional context. 
<hr>
Credit for this issue goes to @LCmry.

**Comment by juliaamosova** [comment]
I also confirmed that this bug is present in WooCommerce Blocks 2.4.4.

**Comment by nerrad** [comment]
Just noting for reference that this is an em dash that isn't rendering correctly.

**Comment by nerrad** [comment]
I was able to reproduce this, but it does not affect all blocks with product titles. In my case it did not affect the product title in the Featured Product block but it did affect the title in the Product Reviews by Category block.

My test environment:

- a build of 2.4.4 branch of the Gutenberg Blocks plugin
- WP 5.3-RC1-46561
- WC beta1
- WC Storefront theme.

To note, if I insert an actual em dash in the title there's no issue, but when I use an actual hyphen (like what is described in the original issue description) - it happens.  Since the value being shown is the html entity for an emdash, I suspect there's something happening with WP filters somewhere converting a single dash to the more semantically correct emdash.  Just giving an update in case someone else picks this up.

**Comment by nerrad** [comment]
The product_name is actually returned in the REST json response with the html entities: "product_name":"WordPress Star Wars &#8211; Pennant"

**Comment by nerrad** [comment]
So I'm thinking we could use the first option along with something like `domPurify` https://github.com/cure53/DOMPurify
