### ISSUE TITLE
Product Gallery - Thumbnails block: Implement min/max number of columns

### ISSUE THREAD

**Issue by gigitux** [woocommerce/woocommerce-gutenberg-products-block#11148]
![image](https://github.com/woocommerce/woocommerce-blocks/assets/4463174/f91a8aa3-5b91-402d-9296-828f2aa9b408)

Currently, there is an option to set the column number for the thumbnail block. After an internal discussion, we have concluded that adding an option for merchants to set both the minimum and maximum number of columns would enhance the block's adaptability for mobile viewing.

**Comment by thealexandrelara** [comment]
I'm closing this issue because we will not be working on this functionality in the first iteration of the block (ref: pdnLyh-4uj-p2). I just want to make it clear that the 'Number of Thumbnails' setting will still be available.
