### ISSUE TITLE
Release Process: Generate the release build with GitHub Actions

### ISSUE THREAD

**Issue by gigitux** [woocommerce/woocommerce-gutenberg-products-block#11149]
At present, the release build is created on the developer's local machine during the release process. This approach carries the risk that the developer might overlook crucial steps, such as using the correct version of Node.js or installing dependencies with `npm ci`. To mitigate this potential issue, we should transition to a more robust approach by generating the release build through GitHub Actions.

**Comment by mikejolley** [comment]
Just going through cooldown issues and saw this one—since feature plugin releases will no longer be a thing soon, we can close this (due to pca54o-6Dz-p2).
