### ISSUE TITLE
Mini-Cart block shows wrong total if theres multiple installs on the same domain

### ISSUE THREAD

**Issue by passatgt** [woocommerce/woocommerce-gutenberg-products-block#11168]
## Describe the bug

If you have multiple WooCommerce sites on the same domain, the mini-cart block will often show the wrong cart total in case you started a cart on another site. 

## To reproduce

1. Setup _Site A_ on domain.com, lets use EUR as the currency
2. Setup _Site B_ on domain.com/test and use USD as the currency
3. Add something to the cart on _Site A_
4. Go to _Site B_ and the mini-cart will show the cart total coming from _Site A_, even the currency will be EUR. 

## Expected behavior

Obviously it should display the correct cart total in this case. 

## Additional context

I'm guessing this happens because some of the mini-cart data is stored in local storage and that is tied to the domain only, not the path. To give you a real-world use case, some multilingual stores might be setup on /en and /de paths as separate WP/WC installs.

**Comment by dinhtungdu** [comment]
Hi @passatgt, thanks for reporting this issue. I can reproduce it and and submitted #11257 to fix this issue. If you have time, please go to the PR and test it. You can find a zip build created for that PR in the comment section.
