### ISSUE TITLE
I'd like to disable the billing address fields for downloadable free products

### ISSUE THREAD

**Issue by evamusby** [woocommerce/woocommerce-gutenberg-products-block#11172]
## Is your feature request related to a problem? Please describe.
Some of my store has free downloadable products. It's surely a big turnoff for users to have to enter a billing address for a free product. The credit card details section is, correctly, disabled, but it seems impossible at present to disable the billing address.

## Describe the solution you'd like
Enable the billing address block to disappear whenever there is no payment required.

**Comment by tarhi-saad** [comment]
Hi, @evamusby! 👋 Thank you for bringing this to our attention! 🙌

This is not currently possible in the block-based checkout—the fields are standardized. We know about this request, which is on our roadmap for future enhancements. However, I must inform you that we have yet to set a specific timeline for its implementation.

To consolidate the related discussions and track progress more effectively, I will close this issue in favor of https://github.com/woocommerce/woocommerce/issues/42496, which addresses this feature request.

Thank you for your understanding and for bringing this to our attention. If you have any further questions or concerns, please don't hesitate to let us know.
