### ISSUE TITLE
PayFast Payment Gateway compatibility issues on AT Sites

### ISSUE THREAD

**Issue by raifd** [woocommerce/woocommerce-gutenberg-products-block#11195]
## Describe the bug

[PayFast Payment Gateway](https://woocommerce.com/products/payfast-payment-gateway/?aff=10486&cid=1131038) does not render at all on AT sites when using the Checkout Block

## To reproduce

1. Create a new Woo Express or AT Site with a block-based theme
2. Install the latest version of PayFast Payment Gateway
3. Enable test mode (or live)
4. Try to checkout

## Expected behavior

The payment gateway option should be displayed in the checkout as with self-hosted sites. 

## Screenshots

N/A

### WordPress (please complete the following information):

-   WordPress version: 6.3.1
-   Gutenberg version (if installed): 16.7.1
-   WooCommerce version: 8.2.0.30
-   WooCommerce Blocks version: 11.2.0 (Blocks package)
-   Site language: EN
-   Any other plugins installed: Default plugins that come with AT Sites

### Desktop (please complete the following information):

-   OS: macOS
-   Browser: Chrome
-   Version: 117

### Smartphone (please complete the following information):

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

Not tested! N/A

## Additional context

Everything works correctly on self-hosted sites.

**Comment by raifd** [comment]
Originally reported on 7137561-zen

**Comment by a-danae** [comment]
Thanks for creating this issue, @raifd ! 

We have https://github.com/woocommerce/woocommerce-gateway-payfast/issues/161 open in the PayFast repository reporting this behavior. This has to be handled on the extension's end, so I'm referencing this issue and the ticket over there, and closing this issue.
