### ISSUE TITLE
Product Block is showing error message on a product section 

### ISSUE THREAD

**Issue by jonathanoladeji** [woocommerce/woocommerce-gutenberg-products-block#112]
On my homepage at cfwriterz.com, this error message displays once I activate the product block plugin. Warning: Missing argument 3 for wgpb_extra_shortcode_features() in /home/jonazxob/public_html/cfwriterz/wp-content/plugins/woo-gutenberg-products-block/woocommerce-gutenberg-products-block.php on line 105

It displays in an area for displaying my products.

**Comment by GlennMartin1** [comment]
@claudiulodro I think you mean for this to be in milestone 1.1.3.

**Comment by ryelle** [comment]
@jonathanoladeji Thanks for the report– can you tell me what version of WordPress and WooCommerce you're using when you're seeing this issue?

**Comment by warrendholmes** [comment]
@ryelle Should we remove this from the 1.2 release?

**Comment by jonathanoladeji** [comment]
I didn't respond cause I had found a solution to the problem but do some
reason that error message now shows again. Your team must have accessed the
site without my permission to make changes.

**Comment by claudiulodro** [comment]
@jonathanoladeji we could not access your site even if we wanted to, and we did no such thing. Your site is self-hosted. Please read [this short explanation](https://en.wikipedia.org/wiki/Self-hosting#Website_management) about self-hosted WordPress sites.
