### ISSUE TITLE
Hide Cart Price

### ISSUE THREAD

**Issue by naveed-alam** [woocommerce/woocommerce-gutenberg-products-block#11209]
Is it possible to hide cart item price?
registerCheckoutFilters require to return <price/> is must
Some plugins hide the product prices for some reasons but WooCommerce blocks do not allow to hide the cart prices without CSS.

Thank you.

**Comment by tarhi-saad** [comment]
@opr, I am sharing with you this extensibility request. For context: https://woocommercecommunity.slack.com/archives/C03MCL9RTAR/p1696963223937329
<details><summary>In case the Slack discussion is deleted</summary>
<p>

- **Naveedafridi** inquired about the possibility of hiding the cart item price, noting that `registerCheckoutFilters` necessitates the return of a `<price/>` object.
  
- **Niels** responded, emphasizing the potential legal implications of such a move. He highlighted that in some jurisdictions, like Germany, regulations mandate the clear display of full prices, inclusive of VAT. Breaching these regulations could result in fines. As a workaround, Niels provided a CSS snippet to hide the price but advised caution and legal consideration before implementing it. 

- **Naveedafridi** elaborated that some plugins intentionally hide product prices, prompting customers to request quotes. He pointed out that using CSS to hide prices might come off as unprofessional.

- **Niels** acknowledged the context and recommended submitting a feature request for a more integrated solution to the WooCommerce Blocks GitHub repository. He reiterated that the CSS suggestion was a temporary solution to the immediate concern.

</p>
</details>

**Comment by senadir** [comment]
Could you also share with us what the are reasons you want to hide the item price? prices will also show up in other places like the totals and such, and I'm trying to understand if you want to hide them holistically or just for visual reasons.

**Comment by mikejolley** [comment]
@naveed-alam 

> Could you also share with us what the are reasons you want to hide the item price? prices will also show up in other places like the totals and such, and I'm trying to understand if you want to hide them holistically or just for visual reasons.

Could you provide some context please? Otherwise this issue may be closed due to inactivity. Thank you!

**Comment by opr** [comment]
Hi @naveed-alam - since we haven't heard back from you, I'll go ahead and close this issue. Feel free to reopen or add any further comments any time! Thanks.
