### ISSUE TITLE
Handpicked product block: Can see, search, add only from first 100 products

### ISSUE THREAD

**Issue by mariskalejs** [woocommerce/woocommerce-gutenberg-products-block#1120]
I have 123 products, but it is possible see, search and add to page only from first100 Handpicked products (A - S). Not possible to slide down to last 23 products (T-Z).
Only way now is - add 4-digit product code in HTML.
Week ago all was ok.
---
WooCommerce Blocks 2.4.4
WooCommerce 3.7.1, WordPress 5.2.4
MacOS Catalina, Safari 13.0.2

**Comment by artifex-media** [comment]
Seems like this issue is still present and failed to fix. Any update @mikejolley ?
