### ISSUE TITLE
Store API: Support `menu_order` for `product/attribute/terms`

### ISSUE THREAD

**Issue by dinhtungdu** [woocommerce/woocommerce-gutenberg-products-block#11219]
## Is your feature request related to a problem? Please describe.
The [product/attribute/terms](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/StoreApi/docs/product-attribute-terms.md?rgh-link-date=2023-03-15T08%3A29%3A50Z) route doesn't accepts `menu_order` as a valid value for `orderby`. However, in WooCommerce it's the default sorting option when querying product attributes.

## Describe the solution you'd like

[product/attribute/terms](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/StoreApi/docs/product-attribute-terms.md?rgh-link-date=2023-03-15T08%3A29%3A50Z) should support `menu_order` and probably make it as the default value to match with Woo core behavior.

## Additional context
This affect merchant using product Attribute Filter as the filter options are now sorted alphabetical and there isn't any way to change that behavior or control the order of filter options. See https://github.com/woocommerce/woocommerce-blocks/issues/8608.

**Comment by mikejolley** [comment]
I believe `menu_order` is a custom term meta implemented by WooCommerce core for manual sorting—is this correct? It looks as though product categories and attributes have this UI added, but product tags do not.

I would say its fine to add for the terms that support it but with these caveats:

1. Its only applied to taxonomies that support it. Tags do not.
2. It's not the default. It doesn't apply to all terms.

Non-default will make this easier to introduce, and it will avoid issues in the future should menu_order be deprecated in future admin redesigns. As I said, it is custom and its unknown how much usage that feature receives.

**Comment by dinhtungdu** [comment]
@mikejolley you're right, Woo adds custom clauses to change the default sorting order. The actual custom term meta is `order`.

```php
	// For sorting, force left join in case order meta is missing.
	if ( ! empty( $args['force_menu_order_sort'] ) ) {
		$clauses['join']    = str_replace( "INNER JOIN {$wpdb->termmeta} ON ( t.term_id = {$wpdb->termmeta}.term_id )", "LEFT JOIN {$wpdb->termmeta} ON ( t.term_id = {$wpdb->termmeta}.term_id AND {$wpdb->termmeta}.meta_key='order')", $clauses['join'] );
		$clauses['where']   = str_replace( "{$wpdb->termmeta}.meta_key = 'order'", "( {$wpdb->termmeta}.meta_key = 'order' OR {$wpdb->termmeta}.meta_key IS NULL )", $clauses['where'] );
		$clauses['orderby'] = 'DESC' === $args['order'] ? str_replace( 'meta_value+0', 'meta_value+0 DESC, t.name', $clauses['orderby'] ) : str_replace( 'meta_value+0', 'meta_value+0 ASC, t.name', $clauses['orderby'] );
	}
```

> Non-default will make this easier to introduce, and it will avoid issues in the future should menu_order be deprecated in future admin redesigns.

Great point. I will only add `menu_order` to attribute term as a non default option.
