### ISSUE TITLE
All Products: With attributes filter block syntax error in console

### ISSUE THREAD

**Issue by roykho** [woocommerce/woocommerce-gutenberg-products-block#11215]
## Describe the bug

Seeing a console error: `Uncaught SyntaxError: "undefined" is not valid JSON`

## To reproduce

1. Add `Attributes Filter` block and `All Products` block on the same page.
2. Go to the frontend and have your developer tools/console open in your browser.
3. Witness the console error.

## Expected behavior

No console error should show.

### WordPress (please complete the following information):

-   WordPress version: 6.4-beta-3
-   Gutenberg version (if installed): N/A
-   WooCommerce version: 8.3.0-dev
-   WooCommerce Blocks version: 11.4.0-dev/trunk
-   Site language: English
-   Any other plugins installed: No

**Comment by gigitux** [comment]
Fixed by #11263.
