### ISSUE TITLE
Can't customize/translate strings from mini-cart 

### ISSUE THREAD

**Issue by GrupoDO** [woocommerce/woocommerce-gutenberg-products-block#11212]
## Describe the bug

I can't translate or customize the strings used by the mini-cart block. I'm trying to use a filter with the gettext hook to change the strings but not success. My site is in Spanish and some strings of mini cart are in English. Plus some Spanish strings does not fit with my style and I want to change for my own text.

I found some javascript lines containing the original strings but I don't know how to translate because those strings are not changed by the gettext hook.

For example: 
In mini-cart-contents.js:

`
t.a=({lowStockRemaining:e})=>e?Object(r.createElement)(o.a,{className:"wc-block-components-product-low-stock-badge"},Object(n.sprintf)(/* translators: %d stock amount (number of items in stock for product) */
Object(n.__)("%d left in stock","woocommerce"),e)):null}
`

The "%d left in stock" string is in php files and it can be changed by the hook but the change is not applied to the mini cart drawer.

Can you help me? Thank you!

## To reproduce

Try to change the amount in stock with the gettext hook in php:

`add_filter( 'gettext', 'grupodo_woocommerce_change_text', 99, 3);
function grupodo_woocommerce_change_text($translated, $text, $domain) {
	if('woocommerce' == $domain){
		if('quedan 1 disponibles' == strtolower($translated)){
			$translated = '¡Última unidad!';
		}else{
			$translated = str_replace('Quedan', 'Solo', $translated);
		}
	}

	return $translated;
}`

## Expected behavior

Change the original string by the new custom string as usual in wordpress and other woocommerce areas

### WordPress (please complete the following information):

-   WordPress version: 6.3.1
-   Gutenberg version (if installed): [e.g. 12.0.0]
-   WooCommerce version: 8.1.1
-   WooCommerce Blocks version: 10.9.3
-   Site language: es_ES
-   Any other plugins installed:

### Desktop (please complete the following information):

-   OS: Windows 10
-   Browser Mozilla Firefox 
-   Version 118.0.1

**Comment by dinhtungdu** [comment]
@GrupoDO Hi there, have you tried using a plugin like Loco Translate to add/modify translation? I successfully modified translations using that plugin for WooCommerce and WooCommerce Blocks.

We can explorer the hooks approach later if needs, but I suggest using a plugin as quick and easy approach.

**Comment by danieldudzic** [comment]
I will close this issue for now. Feel free to reopen it or create a new one if the problem persists.
