### ISSUE TITLE
Fix height issues with the "Product Collections Featured Collection" on the editor

### ISSUE THREAD

**Issue by albarin** [woocommerce/woocommerce-gutenberg-products-block#11237]
There is some bug happening with the `Product Collections Featured Collection` in the editor. When clicking on the Stack containing the title and price, the height changes depending on the one selected.
<img src="https://user-images.githubusercontent.com/8639742/274628669-cba7a0ef-d424-438d-83a6-908661a80d8d.png" />

**Comment by gigitux** [comment]
I'm closing this issue because it is not reproducible on WordPress 6.4.
