### ISSUE TITLE
Local pickup settings tab - "learn more" links to the incorrect page

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-gutenberg-products-block#11231]
## Describe the bug

The "Learn more" option in the Local Pickup tab links to the wrong document.

## To reproduce

1. Go to Settings > Shipping > Local Pickup
2. Click on "Learn more" under Pickup locations
3. Confirm that you're redirected to this page: https://woocommerce.com/document/local-pickup/

## Expected behavior

It should link to https://woocommerce.com/document/woocommerce-blocks-local-pickup/

## Screenshots

<img width="1757" alt="Captura de ecrã 2023-10-12, às 18 10 19" src="https://github.com/woocommerce/woocommerce-blocks/assets/3380168/8e1349b6-acab-4d7a-bd34-9f0a3df9e346">

**Comment by pmcpinto** [comment]
@ralucaStan ideally, we should fix this before the code freeze. Thanks

**Comment by masteradhoc** [comment]
@pmcpinto please check the linked PR :)

**Comment by pmcpinto** [comment]
> @pmcpinto please check the linked PR :)

👍 thanks for the heads up!
