### ISSUE TITLE
Product collction block, columns per page (desktop,tablet,mobile)

### ISSUE THREAD

**Issue by gfarma** [woocommerce/woocommerce-gutenberg-products-block#11249]
## Describe the bug

The columns per page are not working properly at product collection (beta) block. 
![image](https://github.com/woocommerce/woocommerce-blocks/assets/112942896/7e07bc0b-6bdc-42e0-9909-2b337a03a8fe)
For example if you choose 4 columns, 
![image](https://github.com/woocommerce/woocommerce-blocks/assets/112942896/3255137c-7bc2-4208-9ab7-b28cd8ea0cd6)

when the page is shrinking then it becomes like this:
![image](https://github.com/woocommerce/woocommerce-blocks/assets/112942896/6da96e23-0121-44d0-9403-47e0da41f75b)

Also, from the choosen number of columns (for example 4 here) it goes at 1 at mobiles.

## Expected behavior

I think it should be better to choose how many columnsper resolution (desktop, tablet, mobile), or something to make it responsive

Also we should be able to select 2 columns at mobiles, not only 1

**Comment by dinhtungdu** [comment]
Hi @gfarma, thanks for the report! We acknowledge this issue and we're working on it.

As we already have a tracking issue at https://github.com/woocommerce/woocommerce-blocks/issues/10827, I'm closing this one. Please follow the #10827 for future updates.
