### ISSUE TITLE
Customize your Store > Add margin right to the Hero Product 3 Split pattern

### ISSUE THREAD

**Issue by nefeline** [woocommerce/woocommerce-gutenberg-products-block#11254]
Based on the feedback received from @verofasulo on Mrk6SERPZ4KrFHSjM0a8TK-fi-6359_47036 , update the Hero Product 3 Split pattern to include a margin to the right:

<img width="895" alt="Screenshot 2023-10-16 at 01 39 52" src="https://github.com/woocommerce/woocommerce/assets/15730971/6ba1565b-0a57-4bac-b57f-14700ce06dff">

@verofasulo would you please inform us of the desired margin in this particular case?

PS: it's worth mentioning that this difference in margin is not easily detectable when using the pattern within a regular post or template as those already have a default spacing that doesn't exist in the Assembler.

**Comment by albarin** [comment]
Hey @verofasulo, this fix was included in this PR https://github.com/woocommerce/woocommerce-blocks/pull/11206.
This is how it looks:
<img width="1343" alt="Screenshot 2023-10-16 at 13 46 33" src="https://github.com/woocommerce/woocommerce-blocks/assets/186112/e076db03-242b-49c8-aa46-c6969da38e2e">
Is that ok? Should we close this issue?

**Comment by verofasulo** [comment]
Thanks, @albarin! It looks good.

That's the way it looked like when I went through the assembler on Friday last week:

![image](https://github.com/woocommerce/woocommerce-blocks/assets/98944206/9a2af046-fdaf-4ea4-9f48-2f823b91a14f)


If we've already fixed it, we can close the issue :)
