### ISSUE TITLE
Store Customization > Update spacing in between patterns

### ISSUE THREAD

**Issue by nefeline** [woocommerce/woocommerce-gutenberg-products-block#11252]
As part of this task, we need to review all patterns that compose the three templates and ensure the spacing between them is updated per design feedback received on Mrk6SERPZ4KrFHSjM0a8TK-fi-6359_47173 

@verofasulo, would you please confirm the desired value for the spacing between these patterns is 60px to ensure we meet your expectations? This value was picked up based on the value for the gap in between patterns on Figma ( Mrk6SERPZ4KrFHSjM0a8TK-fi-1408_129331 ):

<img width="577" alt="Screenshot 2023-10-15 at 23 18 13" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/394a853d-6a78-4395-b880-a97f9a1ac99c">

## The scope:

Based on Veronica's feedback, the following patterns need to be reviewed and the padding between them updated with adequate spacing. 

## Template 1

- `'woocommerce-blocks/just-arrived-full-hero'`
- `'woocommerce-blocks/product-collection-5-columns'`
- `'woocommerce-blocks/hero-product-3-split'`
- `'woocommerce-blocks/product-collection-3-columns'`
- `'woocommerce-blocks/testimonials-3-columns'`
- `'woocommerce-blocks/featured-category-triple'`
- `'woocommerce-blocks/social-follow-us-in-social-media'`

## Template 2

- `'woocommerce-blocks/featured-category-cover-image'`
- `'woocommerce-blocks/product-collection-4-columns'`
- `'woocommerce-blocks/hero-product-chessboard'`
- `'woocommerce-blocks/product-collection-5-columns'`
- `'woocommerce-blocks/testimonials-3-columns'`

## Template 3

- `'woocommerce-blocks/featured-category-cover-image'`
- `'woocommerce-blocks/product-collection-featured-products-5-columns'`
- `'woocommerce-blocks/featured-category-triple'`
- `'woocommerce-blocks/product-query-product-gallery'`

**Comment by verofasulo** [comment]
Hey @nefeline 👋

> would you please confirm the desired value for the spacing between these patterns is 60px to ensure we meet your expectations?

The spacing between patterns is 80px — you can double-check in [this Figma File](https://www.figma.com/file/Mrk6SERPZ4KrFHSjM0a8TK/Customize-your-store-with-pattern-assembler?type=design&node-id=5716-46688&mode=design&t=8C1ULyDLliB2SAbo-4).

However, I'm unsure if there is a match between the spacing within the patterns in Figma and what is live. And this affects the overall layout, of course. 😊
