### ISSUE TITLE
Store Customization > Update the Centered Header Menu with Search Pattern

### ISSUE THREAD

**Issue by nefeline** [woocommerce/woocommerce-gutenberg-products-block#11253]
We have received the following feedback from @verofasulo regarding the **Centered Header Menu with Search** Pattern ( reference: Mrk6SERPZ4KrFHSjM0a8TK-fi-6347_54034 ):

> This header needs to be polished—some minor tweaks:
>
> - “Search your store” is not centered. And it would be lovely to increase the spacing on the left, it’s very compressed against the edge.
> - The cart icon and the price are not centered.
>
> Menu:
>
> - we need to increase spacing between menu items—they are too close to each other. 

Screenshot of the menu:

<img width="630" alt="Screenshot 2023-10-16 at 01 07 47" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/ce4a8f23-aadc-4063-8626-02012b94f702">

@verofasulo would you please provide the updated design for this header to ensure we can match your expectations? Apart from the cart icon and the price not being centered, all other requested changes involve spacing and it would be great to have precise values to work with.

Also, regarding your question:

> Why do we have a blog page? Let’s not add any blog page as default.

The following area of this pattern:

<img width="639" alt="Screenshot 2023-10-16 at 01 17 24" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/8af8f24f-7a57-40ce-ab38-5839be4eed63">

Corresponds to the Navigation Block, so the content is dynamically changed depending on the user's default menu: this means this menu was created with this structure on WooExpress out-of-the-box. 

I suggest that if we make any changes, do them on the initial site setup for Woo Express and do not create a blog page at all.

According to this feedback we need to add a width to the site logo as well Mrk6SERPZ4KrFHSjM0a8TK-fi-6660_69538

## Scope

- Ensure the cart icon and the price are centered
- TBD (additional changes pending design to ensure we follow the expected spacings)

**Comment by verofasulo** [comment]
> would you please provide the updated design for this header to ensure we can match your expectations?

@nefeline sure! I guess this header was designed by @jarekmorawski and you can find the proper design [here](https://www.figma.com/file/F5AAbRJOGbTeEweXPFtHgf/%5Btemplates-%26-patterns%5D-Woo-Starting-Layouts?type=design&node-id=1505-32597&mode=design&t=XDSkOzXLHbW5dLTV-4).

![image](https://github.com/woocommerce/woocommerce-blocks/assets/98944206/51800b1a-0ad1-4e0c-8950-643e9999bd98)

I can see that the spacing between menu items is 30px. 

> Corresponds to the Navigation Block, so the content is dynamically changed depending on the user's default menu: this means this menu was created with this structure on WooExpress out-of-the-box.

@manospsyx @PanosSynetos could we please remove Blog from the pages generated by default on Woo Express, please? 🙏

**Comment by PanosSynetos** [comment]
> could we please remove Blog from the pages

@verofasulo I'll move this specific issue to the calypso bridge repo, to further discuss it there, in order not to pollute this thread :) I'll ping you

Closing the loop - I created this https://github.com/Automattic/wc-calypso-bridge/issues/1321 in the bridge

**Comment by verofasulo** [comment]
> I'll move this specific issue to the calypso bridge repo, to further discuss it there, in order not to pollute this thread :) I'll ping you

Thanks, @PanosSynetos!

**Comment by albarin** [comment]
@verofasulo  
> - “Search your store” is not centered. And it would be lovely to increase the spacing on the left, it’s very compressed against the edge.
> - The cart icon and the price are not centered.

Sorry, I'm not getting this, could you clarify? Do you mean "Search our store" is not centered inside the search input? What about the cart and price? Centered vertically in respect of the whole menu? Thanks 🙏

**Comment by albarin** [comment]
> @verofasulo
> 
> > * “Search your store” is not centered. And it would be lovely to increase the spacing on the left, it’s very compressed against the edge.
> > * The cart icon and the price are not centered.
> 
> Sorry, I'm not getting this, could you clarify? Do you mean "Search our store" is not centered inside the search input? What about the cart and price? Centered vertically in respect of the whole menu? Thanks 🙏

@verofasulo I have made some updates to the Header https://github.com/woocommerce/woocommerce-blocks/pull/11304, I think some of the changes you were commenting are still missing. But I have updated margins and mobile behavior.
I don't think we can achieve the exact design we have in Figma, sadly, GB does not help a lot in defining different behaviors for a group of blocks in mobile. The demo site is updated with the latest changes, could you have another look? 🙏

**Comment by verofasulo** [comment]
Hey @albarin! 

I just checked but I see the same behavior: 

<img width="425" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/98944206/edea3c59-f85a-4dc2-bbd5-7f1389ba0015">

Maybe [I'm using the wrong test site](https://woo-exactly-colorful-arbiter.wpcomstaging.com/wp-admin/admin.php?page=wc-admin)? 🤔

**Comment by albarin** [comment]
@verofasulo You are using the correct one, probably someone else updated the plugin with a different version and removed the changes in the pattern. I just updated it again.
<img width="471" alt="Screenshot 2023-10-19 at 09 26 19" src="https://github.com/woocommerce/woocommerce-blocks/assets/186112/5fd333d8-837c-4725-b0be-a19e34b35f28">

**Comment by verofasulo** [comment]
Thanks, @albarin! 🙏

@jarekmorawski, do you know where I can find the mobile design of this header? 

<img width="405" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/98944206/f8926898-d5b1-4bc2-bbde-6f94f8b35d70">
 
It doesn't look right 😅 The account and cart icons there are very odd. Thank you! 🙏

**Comment by verofasulo** [comment]
@nefeline we have the same issue [here](https://github.com/woocommerce/woocommerce-blocks/pull/11304) 😊
