### ISSUE TITLE
Local Pickup should NOT be the default option at checkout

### ISSUE THREAD

**Issue by tomxygen** [woocommerce/woocommerce-gutenberg-products-block#11271]
If both shipping and local pickup options are enabled, the default option at checkout is local pickup.
It doesn't really make sense, because the vast majority of orders in most businesses is to be delivered to the customers.

I think the default option should be Shipping, or maybe give the merchant the ability to choose which one to have as default. 
<img width="822" alt="Screenshot 2023-10-16 at 4 57 07 PM" src="https://github.com/woocommerce/woocommerce-blocks/assets/47855768/1d9bc42c-fdc6-435b-8d7e-2c980ce42acf">

**Comment by tarunvijwani** [comment]
@tomxygen If the shipping method is not available for the given address or default shipping method is not present, it will select the available shipping method automatically. 
As a workaround, either add the default shipping method or default shipping address for the guest users. 

I hope that clears things up, and if you have any further questions – feel free to ask. We’re here to help!

**Comment by tomxygen** [comment]
hi @tarunvijwani thanks for your feedback.
Setting a default shipping address for guest users is not an option. I sell in italy, I'm based near Milan but I have customers from all around Italy, and showing them the default location of the store doesn't really make sense.

Setting a default shipping method is actually what I tried but it doesn't seem to work.
This is my situation:
Orders <70€ -> paid shipping
Orders >70€ -> free shipping
_(This is actually another issue on its own, described here: https://github.com/woocommerce/woocommerce/issues/36667)_

The paid shipping is set by default, meaning that it is the first one in the Shipping Methods list.
However, if I go to checkout as a guest, the in-store pickup is selected by default.

**Comment by tarunvijwani** [comment]
@tomxygen, can you share the screenshot of the shipping method, Cart page, and Checkout page?

I'll try to reproduce the issue on my end to understand this use case better.

**Comment by mikejolley** [comment]
This doesn't appear to be a bug in blocks. I tried the following to confirm.

1. Created 1 shipping zone with a flat rate of $10
2. Setup local pickup. Free.
3. New browser. New session. Add to cart. Visit cart page. Flat rate $10 was selected.
4. New browser. New session. Add to cart. Visit checkout page. Flat rate $10 was selected.

Local pickup was not default in either case.

If you're using code to select a default based on other rules, this may be responsible. Perhaps it needs to be updated to exclude local pickup from default selection. 

Closing for now. If you can reproduce this with steps differing from the above please let us know.
