### ISSUE TITLE
Choosing image size

### ISSUE THREAD

**Issue by wpchannel** [woocommerce/woocommerce-gutenberg-products-block#11288]
## What do you think is missing from the Cart & Checkout blocks?

I can't select image size so right now if a picture is 4000x4000 pixels it will be loaded on front. It's slowing down the website and basic PHP hooks doesn't seem to work anymore.

**Comment by tarunvijwani** [comment]
@wpchannel I'm not sure if I understand your question. Could you please elaborate more? Where exactly you're adding the image?  Can you share a screenshot of what you are trying to explain? It would be a great help to understand your issue better.

Looking forward to hearing back from you.

**Comment by wpchannel** [comment]
@tarunvijwani sure!

For years, I've been following this documentation about images in WooCommerce : https://woocommerce.com/document/image-sizes-theme-developers/

Now with FSE and blocks like cross sells products shown in cart, I can't find a way to adjust image sizes. It seems that those hooks are no more applying. Maybe I'm wrong but as a senior WooCommerce developper I pretty sure that it's not the case.

Btw, we need more tooling options in these blocks like choosing image size.

Let me know if I'm not clear.

**Comment by tarunvijwani** [comment]
@wpchannel Thank you for sharing the details. The particular documentation you linked is fairly old. This is a known issue and we plan to review how images are delivered on the front-end in general to improve the performance. However, there is no definite timeline for it's fix so closing the issue. 

internal discussion: p1697631637271849-slack-C02UBB1EPEF
