### ISSUE TITLE
About the Last Checkout + Cart Features

### ISSUE THREAD

**Issue by X752** [woocommerce/woocommerce-gutenberg-products-block#11292]
Hello and thank you for your works ! : ) 
Here a feedback from a newbie, not dev x)

## What do you like about the Cart & Checkout blocks?

- The new easy way to manage some sections
- The new product list in the shopping cart
- The new Adress Card on checkout page
- The numbered steps on the payment page
-  Easy editing the layout vs shortcode
-  And few more but my english is bad ^^ so i will focus on what i think can be improved or brainstormed

## What do you think is missing from the Cart & Checkout blocks?

- One thing i can't setup because of my low skill is : the Cart page WITHOUT Shipping calculator, because in my mind, the shipping is set on checkout page only, 
cart is for products, and checkout is for promo code, shipping, note, paiement etc... and unfortunately this option is Locked on woocommerce block and can't be remove : / 

- The new Adress card:  when i click edit, can you add a button to submit the form? i think it's better for users to see its entries submited and updated with the display of the Adress card again (also for users like me who using a adress book with multiple adress registered ^^)

- For an Adress Book plugin, would be great to add a way to manage settings for display the dropdown menu with selection adress ? 

- On cart page, on products list, i don't like the price total  display on right, it's looks like alone x) 

Thank's again
Keep Going Keep Growing : )

**Comment by tarunvijwani** [comment]
Thank you for the feedback, @X752!

>One thing i can't setup because of my low skill is : the Cart page WITHOUT Shipping calculator, because in my mind, the shipping is set on checkout page only,

You can hide the shipping calculator from Cart pages from WooCommerce > Settings > Shipping > Shipping Options.

>when i click edit, can you add a button to submit the form? i think it's better for users to see its entries submited and updated with the display of the Adress card again (also for users like me who using a adress book with multiple adress registered ^^)

That's a nice suggestion to save an address for the next order. We might have something similar in future releases. We don't have a specific timeline for it at the moment. 


>On cart page, on products list, i don't like the price total display on right, it's looks like alone x)

Could you please share the screenshot of it to understand this better? It might vary from theme to theme.

Looking forward to hearing back from you.

**Comment by opr** [comment]
Hi @X752 since we haven't heard back from you, I'll go ahead and close this issue. Feel free to reopen or add any further comments any time! Thanks.

**Comment by X752** [comment]
I tried to reply, but can’t find the topic ^^´

EDIT: edited to mask personnal information

**Comment by opr** [comment]
@X752 I see you've replied by email - you can find the topic at this URL - https://github.com/woocommerce/woocommerce-blocks/issues/11292

Please let us know if we can help you further! Thanks.

**Comment by X752** [comment]
Hi o/

Thanks for reply, i do screenshot and i come back in few minutes


EDIT:

- So the Shipping Calculator is here even if it's unchecked,
- 3 Total on this page :/  If shipping calculator is disable, i would like to remove both Total (on left in cart layout, and on right in total cart) Amazon style ^^ maybe add option to hide some labels, sections ?

Thank you
(i stop my report here, i don't speak english and can't explain with my words ^^)


![OPTIONS SHIPPING](https://github.com/woocommerce/woocommerce-blocks/assets/56833674/e27d00e1-5b62-4bc3-a7ee-26db3265f831)
![info-cart-page](https://github.com/woocommerce/woocommerce-blocks/assets/56833674/94ff6f43-37a5-4cde-992a-6f2283a238e5)

**Comment by opr** [comment]
Hi @X752 thanks for showing the screenshots and sharing your feedback, it's very valuable.

I see you have disabled the shipping calculator, and in your screenshot it looks like it is disabled correctly. The line you're seeing refers to the shipping _cost_, and doesn't show the _calculator_.

I don't think there's any way to hide this row, unless all of the items in your cart are virtual (i.e. do not require shipping).

Thanks also for sharing the feedback about labels, we don't have any options to hide them now but they could be hidden using CSS.

> (i stop my report here, i don't speak english and can't explain with my words ^^)

No problem, we really appreciate you making the effort to bring this up with us, and as I mentioned your feedback is valuable to us. Thanks again and feel free to open any more issues if you have anything else to bring up.
