### ISSUE TITLE
TT4: Hand-picked Products Block - Visible Bullet Points and Excessive Padding

### ISSUE THREAD

**Issue by imanish003** [woocommerce/woocommerce-gutenberg-products-block#11299]
## Describe the bug

In the Hand-picked Products block, there are two main issues within the editor:
1. Bullet points that should be hidden are visible.
2. There is excessive left and right padding around the block content.

## To reproduce

1. Add a 'Hand-picked Products' block to a page or post.
2. Observe that bullet points appear visible within the block when they should be hidden.
![image](https://github.com/woocommerce/woocommerce-blocks/assets/16707866/92cb16b8-2565-4378-9061-d264b9b76891)

3. Also observe that there is excessive padding on the left and right sides of the block.
![image](https://github.com/woocommerce/woocommerce-blocks/assets/16707866/0ff27d6a-917d-4be1-a0e6-ac776f0ea21f)

## Expected behavior

- Bullet points should be hidden.
- Padding on the left and right shouldn't be too much. 

## Additional context

The issues are observed in the editor view.

**Comment by danieldudzic** [comment]
Thanks for testing and reporting.

1. @sunyatasattva reported the same issue here: https://github.com/woocommerce/woocommerce-blocks/issues/11327

> There is excessive left and right padding around the block content.

2. I was not able to replicate this. The padding seems to be correct for me:

<img width="1497" alt="Cursor_i_Edit_Page_“Hand_Picked_Products”_‹_Dominant_Penguin_—_WordPress" src="https://github.com/woocommerce/woocommerce-blocks/assets/905781/1cd01e32-d10a-4206-a40a-267e9444b591">

<img width="1506" alt="Hand_Picked_Products_–_Dominant_Penguin" src="https://github.com/woocommerce/woocommerce-blocks/assets/905781/5eaeb33a-a303-4680-a865-8194e8112234">

**Comment by danieldudzic** [comment]
This has been fixed now by https://github.com/woocommerce/woocommerce-blocks/pull/11444
