### ISSUE TITLE
TT4: Minor issues in pattern "Essential Header Dark"

### ISSUE THREAD

**Issue by imanish003** [woocommerce/woocommerce-gutenberg-products-block#11297]
## Describe the bug

In Pattern "Essential Header Dark," there are design inconsistencies both on the Editor side and the Frontend side, particularly in terms of contrast and spacing.

## To reproduce

**Editor Side:**

1. Insert the "Essential Header Dark" Pattern.
2. Notice the contrast issues with the search button when using the TT4 theme.
3. Observe that there is no space between the "Shop" text and the user icon.

**Before**
![image](https://github.com/woocommerce/woocommerce-blocks/assets/16707866/5e8e10b2-27bc-4541-9772-a68601ef79ee)

**Current**
![image](https://github.com/woocommerce/woocommerce-blocks/assets/16707866/8016f726-6ac9-477d-80c3-8e18566f4e45)

**Frontend Side:**

1. Preview or publish the page containing the "Essential Header Dark" Pattern.
2. Notice the contrast issues with the search icon.

**Before**
![image](https://github.com/woocommerce/woocommerce-blocks/assets/16707866/213f6ccf-5733-41d7-90bd-70f32a7af29f)

**Current**
![image](https://github.com/woocommerce/woocommerce-blocks/assets/16707866/e1e983e3-342a-406c-bb43-e2f9e31bf685)

## Expected behavior

**Editor Side:**

- The search button should have proper contrast to be easily accessible.
- There should be adequate spacing between the "Shop" text and the user icon. All items after the "Shop" text should be aligned to the right corner for better design consistency.

**Frontend Side:**

- The search icon should have good contrast against its background for better visibility.

**Comment by danieldudzic** [comment]
I personally don't see a big issue with the search button color, but I understand your concern.

I have discovered a significant issue with lack of contrast on the dropdown menus in this pattern:

<img width="1175" alt="Essential_Header_Dark_–_Dominant_Penguin" src="https://github.com/woocommerce/woocommerce-blocks/assets/905781/e698d7cf-f4fa-463c-a6a0-f397534b3a62">
