### ISSUE TITLE
TT4: Unclickable Appearance of Site Title in "Footer with 2 Menus" pattern

### ISSUE THREAD

**Issue by imanish003** [woocommerce/woocommerce-gutenberg-products-block#11294]
## Describe the bug

The Site Title in pattern **Footer with 2 Menus** does not appear to be a clickable link when using the TT4 theme. The text color for the link is also black by default, making it less obvious that it's a clickable element.

## To reproduce

1. Apply the TT4 theme to your WordPress instance.
2. Add the **Footer with 2 Menus** pattern to a page or post.
3. Observe the Site Title.

## Expected behavior

The Site Title should be visually distinct and indicate that it is a clickable link, possibly through color or underlining.

## Screenshots

**Before**
![image](https://github.com/woocommerce/woocommerce-blocks/assets/16707866/07e31696-20ac-446d-8660-1b5d81f928c1)

**Current**
![image](https://github.com/woocommerce/woocommerce-blocks/assets/16707866/02436c42-0bdf-4506-a195-3bf2bfd19b6f)

**Comment by danieldudzic** [comment]
This also seems like a design choice in the theme. Not sure if we should be addressing this in the pattern.

**Comment by nerrad** [comment]
> This also seems like a design choice in the theme. Not sure if we should be addressing this in the pattern.

Agree. Closing the issue.
