### ISSUE TITLE
TT4: Content alignment issue in pattern "Essential Header"

### ISSUE THREAD

**Issue by imanish003** [woocommerce/woocommerce-gutenberg-products-block#11298]
## Describe the bug

In "Essential Header" pattern, there's an alignment issue on the Editor side where the content in the last row is not aligned to the right as expected.

## To reproduce

1. Insert the "Essential Header" pattern in a post
2. Observe the alignment of content in the last row.

**Before**
![image](https://github.com/woocommerce/woocommerce-blocks/assets/16707866/c23e9794-7ad3-43dc-93cb-26a5e2c6d78f)

**Current**
![image](https://github.com/woocommerce/woocommerce-blocks/assets/16707866/e3216ac0-0587-407f-ab47-10ed715f84d4)

## Expected behavior

The content in the last row of the "Essential Header" should be aligned to the right.

**Comment by danieldudzic** [comment]
I am unable to replicate this issue.

The alignment seems to be correct on my test site with WP 6.4 & TT4:

Editor:
<img width="1296" alt="editor" src="https://github.com/woocommerce/woocommerce-blocks/assets/905781/1d8e795e-6cb7-4cf9-af5f-334abc838dfa">

Frontend:
<img width="1300" alt="Essential_Header_–_Dominant_Penguin" src="https://github.com/woocommerce/woocommerce-blocks/assets/905781/0e101e80-431a-4400-8199-b5d25658e3bf">

**Comment by danieldudzic** [comment]
Can you still replicate this, @imanish003?

**Comment by imanish003** [comment]
Hey @danieldudzic, I've attempted to replicate the issue but have been unable to do so. I think we can close this issue 🙂
