### ISSUE TITLE
All Products block - Cursor not changing on hover over page number

### ISSUE THREAD

**Issue by imanish003** [woocommerce/woocommerce-gutenberg-products-block#11301]
## Describe the bug

When hovering over the page number in the All Products block, the cursor does not change its appearance, leading to user confusion.
![image](https://github.com/woocommerce/woocommerce-blocks/assets/16707866/927eb801-b428-4ac7-8491-8be2dd29a0f6)

## To reproduce

1. Go to a page that contains the All Products block.
2. Hover your mouse over the page number at the bottom of the All Products block.
3. Notice that the cursor does not change, even though it's an interactive element.

## Expected behavior

The cursor should change to a pointer (or another appropriate type) when hovering over the page number to indicate that it's an interactive element.

**Comment by danieldudzic** [comment]
I was able to replicate with WP 6.3 and Twenty Twenty-Three so this is not specifically related to WP 6.4 and Twenty Twenty-Four.
