### ISSUE TITLE
Single Product Block - UI Inconsistency Between Editor and Frontend

### ISSUE THREAD

**Issue by imanish003** [woocommerce/woocommerce-gutenberg-products-block#11303]
## Describe the bug

There is a UI inconsistency between the editor view and the frontend view for the Single Product Block

## To reproduce

1. Insert a Single Product block into a post or page.
2. Customize the block in the editor view.
3. Preview or publish the post or page.
4. Observe the UI inconsistency between the editor and frontend views.

**Editor View:**
![image](https://github.com/woocommerce/woocommerce-blocks/assets/16707866/127609e0-4922-4158-9147-ae5ab2a17c92)

**Frontend View:**
![image](https://github.com/woocommerce/woocommerce-blocks/assets/16707866/c87864db-1780-4cc6-8b25-7b2058c69fe0)

## Expected behavior

The UI should be consistent between the editor and frontend views.

**Comment by samueljseay** [comment]
Some detail on this:

1. it's not respecting the editor selected color for buttons in the editor
2. it's not got the same border radius on it in the editor

**Comment by danieldudzic** [comment]
A similar issue occurs with WP 6.3 and Twenty Twenty-Three so this is not specifically related to WP 6.4 and Twenty Twenty-Four.
