### ISSUE TITLE
Investigate: Mini Cart sometimes not reacting to products being added to cart.

### ISSUE THREAD

**Issue by tjcafferkey** [woocommerce/woocommerce-gutenberg-products-block#11316]
## Describe the bug

@senadir reported a potential issue on the website https://crayon-dz.com/ whereby a user adding a product to cart from the product page is not reflected in the mini cart in the header. 

Context:
* The linked site uses a classic theme and the Mini Cart block
* I have been able to replicate this on the link site above, but not consistently. I also cannot replicate it at all on the free classic WooCommerce themes shown [here](https://woocommerce.com/product-category/themes/free-themes/?categoryIds=1600&collections=theme&page=1)

**We should investigate this to understand if this is a bug unique to the theme or from WooCommerce.**

## To reproduce

1. Go to https://crayon-dz.com/
2. Open a number of products in new tabs
3. On one of these tabs click "Add to cart", from the product page
4. The Mini Cart will not update.

I’ve found that if I am visiting the site for the first time, it happens reliably. If I add the item to the cart again it will get added successfully and I am unable to reproduce the bug. Opening a different browser to visit the site again for the first time, again reproduces the problem.

## Expected behavior

The Mini Cart should update to reflect newly added products.

**Comment by dinhtungdu** [comment]
I can't reproduce the bug when Mini Cart is used as a widget 

<div>
    <a href="https://www.loom.com/share/921458c147f745cdb10600ee824b7cf5">
      <p>Arc - Blouse – wp - 19 October 2023 - Watch Video</p>
    </a>
    <a href="https://www.loom.com/share/921458c147f745cdb10600ee824b7cf5">
      <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/921458c147f745cdb10600ee824b7cf5-with-play.gif">
    </a>
  </div>

**Comment by tjcafferkey** [comment]
Closing this issue as it seems to be isolated to that one site and not a wider WooCommerce bug.
