### ISSUE TITLE
Status incorrectly reporting that no shortcode is present in the cart and checkout pages

### ISSUE THREAD

**Issue by Chouby** [woocommerce/woocommerce-gutenberg-products-block#11321]
## Describe the bug

The system status page reports that no shortcode is present in the cart and checkout pages.

## To reproduce

1. Install WooCommerce 8.2.1, without running the wizard
2. Install WooCommerce Blocks 11.3.1
3. Go to WooCommerce > Status > Tools
4. Click on "Create pages"
5. Go to WooCommerce > Status > System status
6. Go down to the WooCommerce pages section
7. Check that both pages have the shortcode :)

## Expected behavior

No error in the System status

## Screenshots

![image](https://github.com/woocommerce/woocommerce-blocks/assets/3238583/6c0b508b-fab0-48f3-afaa-a0ce09aa8e80)

### WordPress (please complete the following information):

-   WordPress version: 6.3.2
-   Gutenberg version (if installed): N/A
-   WooCommerce version: 8.2.1
-   WooCommerce Blocks version: 11.3.1
-   Site language:
-   Any other plugins installed:

### Desktop (please complete the following information):

N/A

### Smartphone (please complete the following information):

N/A

## Additional context

In my opinion, the bug was introduced by #10773, more specifically by the filter used to modify the shortcode in https://github.com/woocommerce/woocommerce-blocks/pull/10773/files#diff-67306479da293f095927542c4cff1a45875138eb52372caaba982b07c053285bR16.
Using the filter `create_pages` bypasses the [other filters](https://github.com/woocommerce/woocommerce/blob/8.2.1/plugins/woocommerce/includes/class-wc-install.php#L762-L774) [which are used for the status report](https://github.com/woocommerce/woocommerce/blob/51c9b9051e3f81530835e09911886616e33d845d/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-system-status-v2-controller.php#L1336).

**Comment by mikejolley** [comment]
@wavvves This should be taken care of when you make the default change in core IMO since you'll be touching that logic. I'll move to backlog.

**Comment by wavvves** [comment]
I marked this as a `won't fix` for Blocks, a new issue will be created in Core, and I will close this one after I create it and mention it here.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/40948
