### ISSUE TITLE
Special characters on siteTitle are not being decoded

### ISSUE THREAD

**Issue by gpressutto5** [woocommerce/woocommerce-gutenberg-products-block#11323]
## Describe the bug

Related to Automattic/woocommerce-payments#7216

Quotes are allowed in the blog title, but they are encoded before saving to the database, so we need to use `wp_specialchars_decode` to get the correct value ([example in core WP](https://github.com/WordPress/wordpress-develop/blob/781953641607c4d5b0743a6924af0e820fd54871/src/wp-admin/includes/user.php#L611)).

## To reproduce

1. Go to Setting >> General
1. Add a `'` to your Site Title and save
1. Go to WooCommerce >> Home on wp-admin
1. Open the console and send `wcSettings.siteTitle`
1. Notice the `'` is encoded as `&#039;`

## Expected behavior

It should be `'` instead of `&#039;`

## Screenshots

![image](https://github.com/woocommerce/woocommerce-blocks/assets/12385501/62b2da73-e96a-408e-af55-d12697e1bdae)

### WordPress (please complete the following information):

-   WordPress version: 6.3.2
-   WooCommerce version: 8.2.1
-   Site language: English
-   Any other plugins installed: WooPayments 6.6.0

**Comment by tarunvijwani** [comment]
@gpressutto5 Thank you for reporting it. I have created a PR #11334 to fix the issue.
