### ISSUE TITLE
TT4: Featured Product picker list style

### ISSUE THREAD

**Issue by sunyatasattva** [woocommerce/woocommerce-gutenberg-products-block#11327]
## Describe the bug

When adding a Featured Product block, the `SearchListControl` component allows the user to select a product via a list of radio buttons. In TT4, unnecessary bullet points appear to the left of each item.

## To reproduce

1. Insert a Featured Product block.
2. Wait for the list to load.
3. Notice the bullet points.

## Expected behavior

No bullet points should appear next to the items.

## Screenshots

<img width="639" alt="Screenshot 2023-10-19 at 14 13 29" src="https://github.com/woocommerce/woocommerce-blocks/assets/1847066/a13ba8e6-9e62-42b7-b567-d5b480fd2298">

## Additional context

Relates to woocommerce/woocommerce#42275 and woocommerce/woocommerce-blocks#11299

**Comment by samueljseay** [comment]
This bullet point style issue is in any block using a select control list or a radio button list.

**Comment by danieldudzic** [comment]
I was able to confirm that this issue is present in Twenty Twenty-Four and not in Twenty Twenty-Three.
