### ISSUE TITLE
Store Customization > Update spacing between icons for the Social: Follow us on social media pattern

### ISSUE THREAD

**Issue by nefeline** [woocommerce/woocommerce-gutenberg-products-block#11335]
Based on the feedback we received from @verofasulo on Mrk6SERPZ4KrFHSjM0a8TK-fi-6359_47173, we need to reduce the spacing between icons for the **Social: Follow us on social media** pattern.

<img width="1170" alt="Screenshot 2023-10-19 at 09 40 15" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/3339af6b-5f2e-4af6-ab8e-3468d82421f3">

**Comment by nefeline** [comment]
Hey @verofasulo ! This spacing between the icons was updated on purpose as part of this work: https://github.com/woocommerce/woocommerce-blocks/pull/10709 

Should we preserve the icons as-is to comply with the initial decision or you would prefer to revert back to the original spacing? Thanks!

**Comment by verofasulo** [comment]
Thanks for providing more context, @nefeline! 🙏

The video is helpful to understand the behavior, and to me, it's very odd. I would prefer to revert the spacing to the original one and align the icons on the left side on mobile [as per Jarek's design](https://www.figma.com/file/F5AAbRJOGbTeEweXPFtHgf/%5Btemplates-%26-patterns%5D-Woo-Starting-Layouts?type=design&node-id=2245-36124&mode=design&t=M4b5JslxSqOh1DDU-4), please—would it be possible? 

![image](https://github.com/woocommerce/woocommerce-blocks/assets/98944206/3ae0c7e8-7d4a-4a9c-bbc4-2fff98e5834d)

**Comment by nefeline** [comment]
> I would prefer to revert the spacing to the original one and align the icons on the left side on mobile F5AAbRJOGbTeEweXPFtHgf-fi-2245_36124, please—would it be possible?

I think the only problem is aligning the icons to the left on mobile due to limitations on Gutenberg: if I recall correctly, the limitation here is that we can't align a text to the right on desktop view and left on mobile: do you recall @albarin?

In case it's not possible, @verofasulo, would you be ok with continuing to align the icons to the right on mobile?

**Comment by albarin** [comment]
> I think the only problem is aligning the icons to the left on mobile due to limitations on Gutenberg: if I recall correctly, the limitation here is that we can't align a text to the right on desktop view and left on mobile: do you recall @albarin?
> 
> In case it's not possible, @verofasulo, would you be ok with continuing to align the icons to the right on mobile?

@verofasulo @nefeline you are right, because we were using `columns`, but I gave it another thought and managed to find a way to align the to the left on mobile using `rows`, here's the PR: https://github.com/woocommerce/woocommerce-blocks/pull/11355

**Comment by verofasulo** [comment]
Thanks, @albarin! ❤️
