### ISSUE TITLE
Document missing `Actions`

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#11337]
While working on #10583, I noticed that the `Actions` of various data stores are not documented. This issue aims to document them.

### Cart Store
Location: `docs/third-party-developers/extensibility/data-store/cart.md`
- [ ] `setCartData`
- [ ] `setErrorData`
- [ ] `receiveCartContents`
- [ ] `receiveApplyingCoupon`
- [ ] `receiveRemovingCoupon`
- [ ] `receiveCartItem`
- [ ] `itemIsPendingQuantity`
- [ ] `itemIsPendingDelete`
- [ ] `setIsCartDataStale`
- [ ] `updatingCustomerData`
- [ ] `shippingRatesBeingSelected`
- [ ] `applyExtensionCartUpdate`
- [ ] `applyCoupon`
- [ ] `removeCoupon`
- [ ] `addItemToCart`
- [ ] `removeItemFromCart`
- [ ] `changeCartItemQuantity`
- [ ] `selectShippingRate`
- [ ] `setBillingAddress`
- [ ] `setShippingAddress`
- [ ] `updateCustomerData`

### Checkout
Location: `docs/third-party-developers/extensibility/data-store/checkout.md`
- [ ] `setPrefersCollection`

### Collections
Location: `docs/third-party-developers/extensibility/data-store/collections.md`
- [ ] `receiveCollectionError`
- [ ] `receiveLastModified`

### Validation
Location: `docs/third-party-developers/extensibility/data-store/validation.md`
- [ ] `clearAllValidationErrors`

**Comment by ralucaStan** [comment]
A reminder that if a PR has an issue attached, that already has metadata, you don’t need to add metadata to the PR. Only PRs without issues need metadata.

My recommendation is to move the metadata to the attached issue.
