### ISSUE TITLE
Document missing `Selectors`

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#11340]
While working on #10583, I noticed that the `Selectors` of various data stores are not documented. This issue aims to document them.

### Checkout
Location: `docs/third-party-developers/extensibility/data-store/checkout.md`
- [ ] `prefersCollection`

Location: `docs/internal-developers/block-client-apis/checkout/checkout-api.md`
- [ ] In https://github.com/woocommerce/woocommerce-blocks/issues/11340#issuecomment-1821157671, @mikejolley mentioned that this document also shows the selectors. We should remove the selectors there and link to the ones in `docs/third-party-developers/extensibility/data-store/checkout.md`.

### Collections
Location: `docs/third-party-developers/extensibility/data-store/collections.md`
- [ ] `getFromState` 
- [ ] `getCollectionHeaders` 
- [ ] `getCollectionError`
- [ ] `getCollectionLastModified`

### Payment
Location: `docs/third-party-developers/extensibility/data-store/payment.md`
- [ ] `getIncompatiblePaymentMethods` 
- [ ] `getState`

### Query-State
Location: `docs/third-party-developers/extensibility/data-store/schema.md`
- [ ] `getRouteFromResourceEntries`
- [ ] `assembleRouteWithPlaceholders`

**Comment by mikejolley** [comment]
Note that docs/internal-developers/block-client-apis/checkout/checkout-api.md has an incomplete list of selectors which should link to the main selectors doc.

**Comment by nielslange** [comment]
> Note that docs/internal-developers/block-client-apis/checkout/checkout-api.md has an incomplete list of selectors which should list to the main selectors doc.

Thanks for pointing this out, @mikejolley. I understand that some selectors haven't been documented. What do you mean by _"[...] which should list to the main selectors doc."_, though? Do you mean all selectors should be listed in the TOC of the doc, similar to what we're doing in https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/data-store/cart.md?

**Comment by mikejolley** [comment]
I meant link—we shouldn't list them in two places.

**Comment by nielslange** [comment]
Thanks, @mikejolley.
