### ISSUE TITLE
Multiselect checkbox/tag input component

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#1134]
Blocks such as the Attribute filter could benefit from a reusable multiselect component that supports both single and multiple (tag-like) selections. For examples, WooCommerce core uses Select2/SelectWoo for this, but we'll want a react based solution.

![TKcbPc](https://user-images.githubusercontent.com/90977/68304120-07443f00-009d-11ea-9816-14d4007de28a.png)

@nerrad suggested using https://github.com/downshift-js/downshift which is being adapted for use in Gutenberg. 

Key requirements:
- Allow single and multiple selections
- Multiple selections show a tag like interface where options can be removed with an "X" link
- Type ahead/search
- A11y and screen-reader support baked in
- Lightweight as possible - this may be used on the frontend of a store

**Comment by nerrad** [comment]
For reference, this is the pull in GB which is implementing downshift: https://github.com/WordPress/gutenberg/pull/17926

**Comment by silviuavram** [comment]
Downshift has the main component `<Downshift>` that can be used to create autocomplete widgets as a render prop. Currently I am working on a React hook similar to `useSelect` (used in the PR referenced above) to have the same logic but as a hook. Let me know via Issues or mentions if you think you need additional support. :)

**Comment by Aljullu** [comment]
@silviuavram I created a PR implementing a multiselect checkbox using `<Downshift>`, in case you would like to take a look at it (#1255). It was really handy to use. :ok_hand:

**Comment by silviuavram** [comment]
Cool !
