### ISSUE TITLE
Update the colors in the Cart and Checkout blocks

### ISSUE THREAD

**Issue by ralucaStan** [woocommerce/woocommerce-gutenberg-products-block#11354]
We need to update the colors used for borders in the Cart and Checkout blocks to create a cohesive experience with the order confirmation block template defaults.

- Gutenberg Gray-100 For all borders except form fields
- Gutenberg Gray-900 For form fields

Before merging the work we need a confirmation from @elizaan36 on the final result. 

![screenshot-2023-10-18-at-9 31 20-pm-1](https://github.com/woocommerce/woocommerce-blocks/assets/1628454/99d23fdd-88fd-4511-9887-27b2f4a0abde)
![screenshot-2023-10-18-at-9 57 02-pm](https://github.com/woocommerce/woocommerce-blocks/assets/1628454/c1aeda98-a327-45ce-a73a-9e374ae7d9b4)
![screenshot-2023-10-18-at-10 04 33-pm](https://github.com/woocommerce/woocommerce-blocks/assets/1628454/2c2e4c01-3ea4-4ed9-b172-0bcdfabfaf88)

**Comment by tarunvijwani** [comment]
The ticket is on hold. There were concerns about user experience with light border colors. 
Waiting for @elizaan36 to confirm the colors for borders. 

Internal discussion: p1698400336133709/1698387117.246639-slack-C8X6Q7XQU
