### ISSUE TITLE
Store Customization > Testimonials 3 columns: remove repeated names

### ISSUE THREAD

**Issue by albarin** [woocommerce/woocommerce-gutenberg-products-block#11363]
- The customer name is repeated, we need to remove the one at the end of the review text.
<img width="984" alt="Screenshot 2023-10-19 at 17 10 33" src="https://github.com/woocommerce/woocommerce-blocks/assets/186112/894a65d4-0b53-40d3-aab4-34a3a0e80a87">
- Change the content to make to 5 lines max.

**Comment by nefeline** [comment]
Closing this one out in favor of https://github.com/woocommerce/woocommerce-blocks/issues/11400 as that one has some additional feedback
