### ISSUE TITLE
Store Customization > Check AI is working

### ISSUE THREAD

**Issue by albarin** [woocommerce/woocommerce-gutenberg-products-block#11365]
We need to double-check that AI is working fine on the `Featured Category Triple` and the `Social: Follow us on social media` pattern
Mrk6SERPZ4KrFHSjM0a8TK-fi-6660_69480
It could be that it was a temporary error, but we need to make sure.

**Comment by nefeline** [comment]
@verofasulo I'm crossposting from my comment on Figma: this might have been a hiccup as we were constantly updating the Woo Blocks plugin throughout the week on the test site, often not including the latest changes with the Pexels images as this work wasn't merged to trunk just yet.

I'm keeping this issue open for now, closing it later on if we confirm no new occurrences are visible as soon as we stop updating the test site.

**Comment by gigitux** [comment]
During this week, we did multiple tests, and nobody reported this issue. I think that it is fine to close this issue.

**Comment by verofasulo** [comment]
> I'm keeping this issue open for now, closing it later on if we confirm no new occurrences are visible as soon as we stop updating the test site.

Thanks, @nefeline 🙏 Yes, please — let's keep it open. I'm still experiencing problems both with images and text. Again, not sure if it's because the test site is a bit messed up 😆

Let me test it again on a fresh new site once we merge all the changes.
