### ISSUE TITLE
Store Customization > Update the "Hero Product 3 Split" pattern

### ISSUE THREAD

**Issue by albarin** [woocommerce/woocommerce-gutenberg-products-block#11375]
- Increase the spacing between the separators and the text in the third columns (check designs: F5AAbRJOGbTeEweXPFtHgf-fi-1540_33321)
- Change the texts on the third column to make them take only 2 lines each.

**Comment by nefeline** [comment]
Thanks @albarin ! It looks like we have two issues for the same task now, so I'm going ahead and closing this one out in favor of https://github.com/woocommerce/woocommerce-blocks/issues/11398 since we have received additional feedback over there.
