### ISSUE TITLE
TT4: Single Product Template, visual inconsistency between "no reviews" in editor and front-end

### ISSUE THREAD

**Issue by samueljseay** [woocommerce/woocommerce-gutenberg-products-block#11388]
## Describe the bug

The visual inconsistency between the template in the editor and front-end is confusing.

When there are no reviews for a product they editor displays a "No reviews" state, but the front-end displays nothing.

## To reproduce

1. You'll need a WP site with Woo and with products that have no reviews
2. Create a page and insert the "Single Product" template
3. Save it and note that the editor view shows text like "No reviews"
4. Preview the page and see that this no reviews state is not displayed on the front-end

## Expected behavior

The editor and front-end should match closer in what is rendered.

## Screenshots

Editor: 
![Uploading Screenshot 2023-10-23 at 1.08.22 PM.png…]()

Frontend:
<img width="720" alt="Screenshot 2023-10-23 at 1 08 48 PM" src="https://github.com/woocommerce/woocommerce-blocks/assets/1281828/80c1b3cb-8411-4660-84ed-b02cece79d98">

**Comment by danieldudzic** [comment]
I believe this is an intentional decision: https://github.com/woocommerce/woocommerce-blocks/issues/9666

**Comment by samueljseay** [comment]
Ah fair enough! I think we can close this. Thank you for pointing it out!
