### ISSUE TITLE
[CYS Woo Express] 3-column product row

### ISSUE THREAD

**Issue by verofasulo** [woocommerce/woocommerce-gutenberg-products-block#11399]
Please review `3-column product row`.

- Let’s double-check that we have a character limit in place for the product title, and that it takes only one line.
- Please let’s center align “No reviews” with the star. 

<img width="1723" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/98944206/fe944cf5-aead-4428-918a-cb8387fa32f5">

**Comment by nefeline** [comment]
Whoever picks this issue up for working, feel free to ignore this change:

> Let’s double-check that we have a character limit in place for the product title, and that it takes only one line.

This will be tackled on https://github.com/woocommerce/woocommerce-blocks/issues/11405

**Comment by albarin** [comment]
@verofasulo The `No reviews` text will only show up in the editor view (and the assembler in this case), but not in the frontend. Check the screenshots below 👇 

| Editor | Frontend |
|--------|--------|
| <img width="1252" alt="Screenshot 2023-10-24 at 15 04 27" src="https://github.com/woocommerce/woocommerce-blocks/assets/186112/86b0eed8-5753-4c40-9d4a-86b13e5a5c2b"> | <img width="1205" alt="Screenshot 2023-10-24 at 15 04 32" src="https://github.com/woocommerce/woocommerce-blocks/assets/186112/4fe695ea-68d6-4acc-b7fa-babd4721f974"> | 

I think it could be confusing for the users to see that `No review` in the assemble but not in the actual site after applying the design. Should we remove the reviews block from this pattern? (and the one with 4 and 5 cols) Thanks!

**Comment by verofasulo** [comment]
> The No reviews text will only show up in the editor view (and the assembler in this case), but not in the frontend.

I always find it very confusing — the Frame in the assembler is supposed to be the FE, not the editor. 

> Should we remove the reviews block from this pattern? (and the one with 4 and 5 cols) Thanks!

Hmm, no — let's not change patterns only because they don't look good in the assembler. I think that the problem here is the way we intend the Frame. It should be a store preview; that's how users perceive it.

**Comment by albarin** [comment]
This was fixed by https://github.com/woocommerce/woocommerce-blocks/pull/11468
