### ISSUE TITLE
[CYS Woo Express] Large header

### ISSUE THREAD

**Issue by verofasulo** [woocommerce/woocommerce-gutenberg-products-block#11390]
Please review `Large header`.

How it currently looks like:

<img width="1728" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/98944206/1cab1d3d-a4a6-4fb7-8a95-d23054c9e901">

<img width="1723" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/98944206/7d97b8aa-3654-437e-afdc-861cad5589b2">

---

How it's supposed to look like:

[Figma - Large screens](https://www.figma.com/file/F5AAbRJOGbTeEweXPFtHgf/%5Btemplates-%26-patterns%5D-Woo-Starting-Layouts?type=design&node-id=2313-135938&mode=design&t=qkpAGsXW7rY6XBmF-4)

![image](https://github.com/woocommerce/woocommerce-blocks/assets/98944206/5b6507f0-99d7-457d-a306-757b5b71efcd)

[Figma - Small screens](https://www.figma.com/file/F5AAbRJOGbTeEweXPFtHgf/%5Btemplates-%26-patterns%5D-Woo-Starting-Layouts?type=design&node-id=2313-135837&mode=design&t=qkpAGsXW7rY6XBmF-4)

![image](https://github.com/woocommerce/woocommerce-blocks/assets/98944206/e73edded-cde7-433b-88b4-bc579922eef1)

**Comment by nefeline** [comment]
Quick note regarding the icon size: that will be worked on by Guidorah as part of https://github.com/woocommerce/woocommerce/issues/40947 : we should not be hardcoding the width of the icon in patterns.

**Comment by gigitux** [comment]
Unfortunately, we can't achieve the mobile view. As discussed earlier, we can only "hide" the navigation block in the mobile view.

We can't:

- change the position of the Navigation block (desktop view is at the center, on mobile view is on the right)
- hide specific blocks (Customer Account block and Search Block)

It is worth mentioning that it is possible to hide the Search Block only if it is an inner block of the Navigation block.

cc @verofasulo @nefeline

**Comment by verofasulo** [comment]
After discussing it on [Slack](https://a8c.slack.com/archives/C053716F2H2/p1698132360788219), it looks like this is the only viable—and temporary—solution for mobile:

![image](https://github.com/woocommerce/woocommerce-blocks/assets/98944206/f05d583e-7877-48b3-9d09-92103dcec824)

![image](https://github.com/woocommerce/woocommerce-blocks/assets/98944206/96cd6666-8992-4c50-a523-d7cfce1094ee)

Let me know if you have any further questions 🙏

**Comment by gigitux** [comment]
I tried to implement this pattern, but the current approach doesn't work on mobile.

The first row is too large.

![image](https://github.com/woocommerce/woocommerce-blocks/assets/4463174/bcf30f24-130e-4f9b-ae27-7c8d285bd8a1)

cc @verofasulo

**Comment by verofasulo** [comment]
Thanks for trying it out, @gigitux! 🙏 

> The first row is too large.

I'm not sure I got the issue 😅

<img width="431" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/98944206/525a9be4-ed5f-499a-96c3-e5d3fb0ffd3d">

Can't we: 

- Align the search bar on the left side;
- Apply the correct spacing between the account and cart icons and align them to the right;
- Apply the correct spacing between the site title and the menu and center-align them?

**Comment by gigitux** [comment]
As I already mentioned above, on very small screens, the Mini Cart icon falls outside of the screen. For example, this is what happens on the iPhone SE:


![image](https://github.com/woocommerce/woocommerce-blocks/assets/4463174/3bbe40b9-d0fb-4c0a-a9e5-3f8d3caf6e1d)


There are two fixes:

- Allowing to wrap to multiple lines when there isn't enough space to show the icons on the same row:

![image](https://github.com/woocommerce/woocommerce-blocks/assets/4463174/91da1533-bbe3-4180-b5c6-4175a9299e96)

- get rid of the Product Search Block.

Any feedback, @verofasulo?


cc @albarin

**Comment by verofasulo** [comment]
> As I already mentioned above, on very small screens, the Mini Cart icon falls outside of the screen. 

What I was suggesting was to fix the spacing between the cart and the account icons, which is currently wrong, and see if it improves the mobile screen too. The correct spacing is 16px:

![image](https://github.com/woocommerce/woocommerce-blocks/assets/98944206/db7d6e87-2de5-4564-adf4-adae6de1b13c)

I'm also not getting why the site title and the hamburger menu are misaligned:

<img width="142" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/98944206/a3b9c49a-94be-40fb-a74f-b2500e649c52">

**Comment by gigitux** [comment]
@verofasulo thanks for the feedback, but it is the same issue:

![image](https://github.com/woocommerce/woocommerce-blocks/assets/4463174/feb3a65a-fb87-4666-8fdb-660a33332109)

Even if I put 0px, on some devices, there is the issue:

![image](https://github.com/woocommerce/woocommerce-blocks/assets/4463174/152e6433-055b-4eba-b71e-16c850f49e7f)

**Comment by verofasulo** [comment]
Adding a comment here for visibility: we decided to change the header design, both on large and narrow screens. 

@gigitux proposed to replicate Zalando header, and it looks really good — [here](https://d.pr/v/0iRGGM)'s an initial video and [here](https://a8c.slack.com/archives/C053716F2H2/p1698675303753959)'s the convo on Slack. 

@gigitux, could you please share a link to the header here once you're done so that I can have a last look? Thank you!

cc @albarin
