### ISSUE TITLE
[CYS Woo Express] Footer with simple menu and cart

### ISSUE THREAD

**Issue by verofasulo** [woocommerce/woocommerce-gutenberg-products-block#11393]
Please review `Footer with simple menu and cart`. 

How it currently looks like:

<img width="1727" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/98944206/775c71ed-ebe0-4629-a951-59def300ba3c">

<img width="1723" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/98944206/3718ea74-5af4-4d81-9324-661a78eb143e">

---

How it's supposed to look like:

[Figma - Large screens](https://www.figma.com/file/F5AAbRJOGbTeEweXPFtHgf/%5Btemplates-%26-patterns%5D-Woo-Starting-Layouts?type=design&node-id=2283-33974&mode=design&t=qkpAGsXW7rY6XBmF-4)

![image](https://github.com/woocommerce/woocommerce-blocks/assets/98944206/6d6c398d-5a78-4cd9-a61f-0ca6600f9840)

[Figma - Small screens](https://www.figma.com/file/F5AAbRJOGbTeEweXPFtHgf/%5Btemplates-%26-patterns%5D-Woo-Starting-Layouts?type=design&node-id=2242-36049&mode=design&t=qkpAGsXW7rY6XBmF-4)

![image](https://github.com/woocommerce/woocommerce-blocks/assets/98944206/39de4d55-ad25-4bb1-b1bd-f8f3e09b5719)

**Comment by tjcafferkey** [comment]
There was some minor limitations found with implementing this by @albarin, you can read them here https://github.com/woocommerce/woocommerce-blocks/pull/11409#issuecomment-1774945840
