### ISSUE TITLE
VAT / noVAT in product block

### ISSUE THREAD

**Issue by overcatbe** [woocommerce/woocommerce-gutenberg-products-block#1139]
Hi, i've read the documentation, but i am afraid i can't solve this on my own. Thanks for any help.

I need prices without VAT and with VAT on my website. I have accomplished this with messing with the 
woocommerce template single-product/price.php as follows:
`<class="<?php echo esc_attr( apply_filters( 'woocommerce_product_price_class', 'price' ) );?>">

<?php if ( $price_html = $product->get_price_html() ) : ?>
<?php 
    $price_excl_tax = wc_get_price_excluding_tax( $product ); 
    $price_incl_tax = wc_get_price_including_tax( $product ); 

    if ( $price_excl_tax !== $price_incl_tax ) : ?>
		<span class="price-cvat"><?php echo wc_price( wc_get_price_excluding_tax( $product ) ); ?> excl. VAT, taxes and charges</span><br />
		<span class="price-incvat"><?php echo wc_price( wc_get_price_including_tax( $product ) ); ?> incl. VAT</span>
    <?php else : ?>
    <span class="price-zerovat"><?php echo wc_price( wc_get_price_including_tax( $product ) ); ?></span>
    <?php endif; ?>
<?php endif; ?>`

All nice, but i would need the same output also on the product block. I have been messing around with the block function call in functions.php of my theme:
`function my_product_block( $html, $data, $product ) {
    $html = '<li class="wc-block-grid__product">
        <div class="image-wrap">
            <a href="' . $data->permalink . '" class="wc-block-grid__product-link">' . $data->image . '</a>
        </div>
        <h3><a href="' . $data->permalink . '">' . $data->title . '</a></h3>
        ' . $data->badge . '
        ' . $data->price . 'excl. VAT, taxes and charges' . '
        ' . $data->rating . '
		' . $data->button . '
		' . $price_incl_tax .'
    </li>';
    return $html;
}
add_filter( 'woocommerce_blocks_product_grid_item_html', 'my_product_block', 10, 3);`

but i can't find the call for these PHP variables:
    $price_excl_tax = wc_get_price_excluding_tax( $product ); 
    $price_incl_tax = wc_get_price_including_tax( $product ); 

So how do i call the woocommerce price excluding/including tax in the block function? Thanks a lot.

**Comment by overcatbe** [comment]
SOLVED:function my_product_block( $html, $data, $product ) {
	$price_excl_tax = wc_get_price_excluding_tax( $product ); 
	$price_excl_tax_round = wc_format_decimal($price_excl_tax, wc_get_price_decimals());
    $price_incl_tax = wc_get_price_including_tax( $product ); 
	
    $html = '<li class="wc-block-grid__product">
        <div class="image-wrap">
            <a href="' . $data->permalink . '" class="wc-block-grid__product-link">' . $data->image . '</a>
        </div>
        <h3><a href="' . $data->permalink . '">' . $data->title . '</a></h3>
        ' . $data->badge . '
		<p>
		' . $price_excl_tax_round . " € excl. VAT, taxes and charges <br/>" . '</p>
		<p>' . $price_incl_tax . " € incl. VAT (EU)" . '</p>
		' . $data->price . '
        ' . $data->rating . '
		' . $data->button . '
    </li>';
    return $html;
}
add_filter( 'woocommerce_blocks_product_grid_item_html', 'my_product_block', 10, 3);

**Comment by Aljullu** [comment]
Thanks for the interest @overcatbe, currently we are still experimenting with the best way to add extensibility to WooCommerce Blocks, you can read more about it here: #891.

Nevertheless, yesterday we released a new version of WooCommerce Blocks, 2.5, which adds a new block named _All Products_  which allows you to list products and add inner blocks inside them. You can read more about it in the _Developer customization_ section of the release article:

https://woocommerce.wordpress.com/2019/11/19/wc-blocks-2-5-release-notes/

I will proceed closing this issue, but feel free to give us any feedback and report bugs if you build a plugin on top of WooCommerce Blocks using this new API.
