### ISSUE TITLE
[CYS Woo Express] Minimal header

### ISSUE THREAD

**Issue by verofasulo** [woocommerce/woocommerce-gutenberg-products-block#11391]
Please review `Minimal header`.

How it currently looks like:

<img width="1728" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/98944206/ef563818-0b3d-4051-abe9-650a3db4939d">

<img width="1728" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/98944206/ebe2fe26-5c75-43a7-9cf6-20fd3b952f5a">

---

How it's supposed to look like:

[Figma - Large screens](https://www.figma.com/file/F5AAbRJOGbTeEweXPFtHgf/%5Btemplates-%26-patterns%5D-Woo-Starting-Layouts?type=design&node-id=2283-35766&mode=design&t=qkpAGsXW7rY6XBmF-4)

![image](https://github.com/woocommerce/woocommerce-blocks/assets/98944206/47dd178d-c8a3-4273-9b00-963a008d8c28)

[Figma - Small screens](https://www.figma.com/file/F5AAbRJOGbTeEweXPFtHgf/%5Btemplates-%26-patterns%5D-Woo-Starting-Layouts?type=design&node-id=2242-34431&mode=design&t=qkpAGsXW7rY6XBmF-4)

![image](https://github.com/woocommerce/woocommerce-blocks/assets/98944206/819d38b1-093e-4b86-8dc8-f63dc5fedf91)

**Comment by nefeline** [comment]
This regression may be related to the size of the icon used: let's use an icon with a regular size as a reference to confirm if that's the case & make adjustments if needed. Otherwise, we can close this one out.
