### ISSUE TITLE
[CYS Woo Express] Hero product 3-split

### ISSUE THREAD

**Issue by verofasulo** [woocommerce/woocommerce-gutenberg-products-block#11398]
The Inspector doesn't work within the Frame, but the proportions (image - text) seem wrong.
Pattern: `Hero product 3-split`.

How it currently looks like:

<img width="1306" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/98944206/ff403663-dfa9-4c07-a992-a27257dead93">

<img width="1725" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/98944206/cb4f7240-d3a2-4ab4-8a49-244cc9f3b3ec">

<img width="1724" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/98944206/05766c6a-7c1d-4315-a150-08a16cb24126">

- Check spacing.
- Check image-text proportions.
- In the mobile screen, the image is between the two text sections.
- Please set a character limit for the product descriptions on the right side to take only two lines.

---

How it's supposed to look like:

[Figma - Large screens](https://www.figma.com/file/Mrk6SERPZ4KrFHSjM0a8TK/Customize-your-store-with-pattern-assembler?type=design&node-id=1406-127560&mode=design&t=ZBW0Ds0G26mxIowu-4)

![image](https://github.com/woocommerce/woocommerce-blocks/assets/98944206/07c4934b-6149-478a-bf66-a020b89ebcad)

[Figma - Small screens](https://www.figma.com/file/Mrk6SERPZ4KrFHSjM0a8TK/Customize-your-store-with-pattern-assembler?type=design&node-id=1406-127585&mode=design&t=ZBW0Ds0G26mxIowu-4)

![image](https://github.com/woocommerce/woocommerce-blocks/assets/98944206/b82c3f75-8ae3-4454-ab1e-734138a70644)

**Comment by albarin** [comment]
Fixed by https://github.com/woocommerce/woocommerce-blocks/pull/11495
