### ISSUE TITLE
[CYS Woo Express] Essential header

### ISSUE THREAD

**Issue by verofasulo** [woocommerce/woocommerce-gutenberg-products-block#11392]
Please review `Essential header`.

How it currently looks like:

<img width="1728" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/98944206/3fd6b7bd-6767-4f3e-bda5-9ebb9bba2cb2">

<img width="1728" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/98944206/1cec4635-e16d-48f6-a4ff-08343007efd9">

---

How it's supposed to look like:

[Figma - Large screens](https://www.figma.com/file/F5AAbRJOGbTeEweXPFtHgf/%5Btemplates-%26-patterns%5D-Woo-Starting-Layouts?type=design&node-id=2283-35624&mode=design&t=qkpAGsXW7rY6XBmF-4)

![image](https://github.com/woocommerce/woocommerce-blocks/assets/98944206/7258df24-8c14-4318-bc2c-246f0329584c)

[Figma - Small screens](https://www.figma.com/file/F5AAbRJOGbTeEweXPFtHgf/%5Btemplates-%26-patterns%5D-Woo-Starting-Layouts?type=design&node-id=2237-32837&mode=design&t=qkpAGsXW7rY6XBmF-4)

![image](https://github.com/woocommerce/woocommerce-blocks/assets/98944206/9e4343eb-fd1f-432e-b3da-d63e3b116c65)

**Comment by gigitux** [comment]
Unfortunately, we can't achieve the mobile view. As discussed earlier, we can only "hide" the navigation block in the mobile view. 

We can't:
- change the position of the Navigation block (desktop view is at the center, on mobile view is on the right)
- hide specific blocks (Customer Account block)

cc @verofasulo @nefeline
