### ISSUE TITLE
[CYS Woo Express] Just arrived full hero

### ISSUE THREAD

**Issue by verofasulo** [woocommerce/woocommerce-gutenberg-products-block#11396]
Please review `Just arrived full hero`.

How it currently looks like:

<img width="1309" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/98944206/b1002302-cb3a-45b3-b1fd-d04d56535b38">

---

How it's supposed to look like:

[Figma](https://www.figma.com/file/Mrk6SERPZ4KrFHSjM0a8TK/Customize-your-store-with-pattern-assembler?type=design&node-id=1406-127992&mode=design&t=ZBW0Ds0G26mxIowu-4) 

![image](https://github.com/woocommerce/woocommerce-blocks/assets/98944206/b573b6be-9232-4544-9653-c4ca77b7e9f3)

**Comment by gigitux** [comment]
Fixed by #11406
