### ISSUE TITLE
[CYS Woo Express] Testimonials 3 columns

### ISSUE THREAD

**Issue by verofasulo** [woocommerce/woocommerce-gutenberg-products-block#11400]
Please review `Testimonials 3 columns`.

- The customer's name is repeated twice. Please remove the one on the same line of the review.
- Please set a character limit for each review to take a maximum of 5 lines.
- Change the title to "What our customers say". 

<img width="1304" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/98944206/4f3d1b4a-2eff-4b16-bafb-40c473e7c05d">

[Figma](https://www.figma.com/file/Mrk6SERPZ4KrFHSjM0a8TK/Customize-your-store-with-pattern-assembler?type=design&node-id=1408-129636&mode=design&t=ZBW0Ds0G26mxIowu-4)

![image](https://github.com/woocommerce/woocommerce-blocks/assets/98944206/2631c8a1-cfd4-46ab-9149-3aa0ccf91f76)

**Comment by nefeline** [comment]
@verofasulo regarding:

> Change the title to "What our customers say".

This is AI-generated content. Can you please confirm that you want to downgrade the feature and hardcode this string instead? "What our customers say" is already the default text if for some reason AI fails generating content.

**Comment by verofasulo** [comment]
> This is AI-generated content. Can you please confirm that you want to downgrade the feature and hardcode this string instead?

Haaaa! Apologies, for some reason I thought it was the default content. Forget my comment—let's not downgrade the feature at all 😄
