### ISSUE TITLE
[CYS Woo Express] Product gallery

### ISSUE THREAD

**Issue by verofasulo** [woocommerce/woocommerce-gutenberg-products-block#11407]
Pattern: `Product gallery`.

- The star icon doesn’t follow the color palette.
- Please center-align the star icon with the text "No reviews".
- From "No Reviews" to "No reviews".
- Remove buttons.

<img width="1294" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/98944206/77f1b7c7-0b17-4f7d-9550-f111d0b46a14">

---

[Figma](https://www.figma.com/file/Mrk6SERPZ4KrFHSjM0a8TK/Customize-your-store-with-pattern-assembler?type=design&node-id=5730-46754&mode=design&t=ZBW0Ds0G26mxIowu-4)

![image](https://github.com/woocommerce/woocommerce-blocks/assets/98944206/2bd32b78-dda3-445d-8398-c02c07890010)

**Comment by nefeline** [comment]
@verofasulo we have already documented the expected changes for this pattern on https://github.com/woocommerce/woocommerce-blocks/issues/11344, so I'm going ahead and closing this one out.

Regarding the changes requested to the Reviews block:

> The star icon doesn’t follow the color palette.
> Please center-align the star icon with the text "No reviews".
> From "No Reviews" to "No reviews".

Based on the designs, the reviews block should actually be completely removed from this pattern, so as a consequence, these three changes would not be required. If there's a wish to change the initial design for this and preserve the Ratings instead, please let us know.

**Comment by verofasulo** [comment]
> Based on the designs, the reviews block should actually be completely removed from this pattern, so as a consequence, these three changes would not be required.

Sounds great! Thanks, @nefeline 🙏
