### ISSUE TITLE
[CYS Woo Express] Search bar 

### ISSUE THREAD

**Issue by verofasulo** [woocommerce/woocommerce-gutenberg-products-block#11408]
There are issues with the search bar when the background is not white.

<img width="1728" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/98944206/0fcd843f-1193-4fce-8875-fb1a5ff7b416">

<img width="1724" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/98944206/617c49eb-95d5-4d51-8a0d-c6be5f145b33">

Also, please align the style of the search bar in the header and in the footer—we currently have 2 different styles.

**Comment by nefeline** [comment]
@verofasulo can you please clarify a few things here?

> There are issues with the search bar when the background is not white.

Can you please confirm the expected outcome here? Should the background color within the search bar match the one selected in the pattern assembler?

> Also, please align the style of the search bar in the header and in the footer—we currently have 2 different styles.

Which one of the styles do you want to preserve: the one we have for the header or the footer? It would be great if you could provide us with an updated design so we can have a reference.

**Comment by verofasulo** [comment]
Hey @nefeline! 

> Which one of the styles do you want to preserve: the one we have for the header or the footer?

In the designs, there's no inconsistency—this is the search bar's style adopted everywhere: 

![image](https://github.com/woocommerce/woocommerce-blocks/assets/98944206/48b10b0a-93f1-46b4-9dc7-9fa379222458)


The following are all the headers and footers implemented in the assembler and they all share the same search bar:

- [Essential header](https://www.figma.com/file/F5AAbRJOGbTeEweXPFtHgf/%5Btemplates-%26-patterns%5D-Woo-Starting-Layouts?type=design&node-id=2283-35624&mode=design&t=M4b5JslxSqOh1DDU-4)
- [Minimal header](https://www.figma.com/file/F5AAbRJOGbTeEweXPFtHgf/%5Btemplates-%26-patterns%5D-Woo-Starting-Layouts?type=design&node-id=2283-35766&mode=design&t=M4b5JslxSqOh1DDU-4)
- [Large header](https://www.figma.com/file/F5AAbRJOGbTeEweXPFtHgf/%5Btemplates-%26-patterns%5D-Woo-Starting-Layouts?type=design&node-id=2313-135835&mode=design&t=9w0tIfNRlDwhiSnz-4)
- [Centered header menu with search](https://www.figma.com/file/F5AAbRJOGbTeEweXPFtHgf/%5Btemplates-%26-patterns%5D-Woo-Starting-Layouts?type=design&node-id=2242-34306&mode=design&t=9w0tIfNRlDwhiSnz-4)
- [Footer with simple menu and cart](https://www.figma.com/file/F5AAbRJOGbTeEweXPFtHgf/%5Btemplates-%26-patterns%5D-Woo-Starting-Layouts?type=design&node-id=2242-35967&mode=design&t=9w0tIfNRlDwhiSnz-4)
- [Footer with 3 menus](https://www.figma.com/file/F5AAbRJOGbTeEweXPFtHgf/%5Btemplates-%26-patterns%5D-Woo-Starting-Layouts?type=design&node-id=2242-35777&mode=design&t=9w0tIfNRlDwhiSnz-4)
- [Large footer](https://www.figma.com/file/F5AAbRJOGbTeEweXPFtHgf/%5Btemplates-%26-patterns%5D-Woo-Starting-Layouts?type=design&node-id=2313-131473&mode=design&t=9w0tIfNRlDwhiSnz-4)

> Can you please confirm the expected outcome here? Should the background color within the search bar match the one selected in the pattern assembler?

In Jarek's design, I can see there's no fill—So I would expect not to have the white background 😊

**Comment by gigitux** [comment]
Hey, @verofasulo

> In Jarek's design, I can see there's no fill—So I would expect not to have the white background 😊

It is not possible to change the background of the input field: https://github.com/WordPress/gutenberg/issues/44671

> Also, please align the style of the search bar in the header and in the footer—we currently have 2 different styles.

Could you expand this? The only difference that I see is the label:

![image](https://github.com/woocommerce/woocommerce-blocks/assets/4463174/87004a41-8c1d-4f90-9f38-69ef4c6a4af0)

**Comment by verofasulo** [comment]
> It is not possible to change the background of the input field: https://github.com/WordPress/gutenberg/issues/44671

Thanks, Luigi. Let's go with the white background, then.

> Could you expand this? The only difference that I see is the label:

<img width="205" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/98944206/d76f667a-0fdd-4a8e-a445-68c8eeba9da3">

- Some headers have this style, with no space between the input field and the search button. 
- The border-radius is different. Sometimes it's 0px, sometimes 2px (it looks like this). It's not something inherited by the theme.
- And yes, the label—could we use `Search` everywhere, please?

**Comment by verofasulo** [comment]
Addressing this comment here that came out from the last QA —  The current search bar presents border-radius inconsistencies between the input field and the search button:

<img width="428" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/98944206/0622f624-7589-4812-b503-2122cf3537d8">

Please use 0px for both of the elements.

**Comment by albarin** [comment]
@verofasulo fixed here: https://github.com/woocommerce/woocommerce-blocks/issues/11514
