### ISSUE TITLE
[CYS Woo Express] 1:1 image 4-column products row

### ISSUE THREAD

**Issue by verofasulo** [woocommerce/woocommerce-gutenberg-products-block#11403]
Pattern: `1:1 image 4-column products row`.

- Please set a character limit for the product title to take only one line.
- Please double-check the button size. It looks pretty small and compressed.

<img width="1298" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/98944206/97d3a5f7-1896-4ea5-bf86-67351faa3667">

---

[Figma](https://www.figma.com/file/Mrk6SERPZ4KrFHSjM0a8TK/Customize-your-store-with-pattern-assembler?type=design&node-id=1412-130754&mode=design&t=ZBW0Ds0G26mxIowu-4)

![image](https://github.com/woocommerce/woocommerce-blocks/assets/98944206/1d858ba6-7092-4de8-ad6f-2e3c5114d241)

**Comment by nefeline** [comment]
The name for this pattern was updated to **Product Collection 4 Columns** when the Products (beta) block was replaced with the new Product Collection.

The character limit will be tackled via https://github.com/woocommerce/woocommerce-blocks/issues/11405.

Whoever picks this issue up, please focus on:

> Please double-check the button size. It looks pretty small and compressed.
