### ISSUE TITLE
[CYS Woo Express] Smart color for buttons

### ISSUE THREAD

**Issue by verofasulo** [woocommerce/woocommerce-gutenberg-products-block#11402]
Is there any way for us to detect the light/dark background and default to a proper color for the button? 

`Featured category cover image`

<img width="1307" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/98944206/3edff134-8e09-49d1-bf15-e23801e8fb01">

 `Just arrived full hero`

<img width="1297" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/98944206/d7d19731-e584-49a9-a92e-d949ca523cee">

**Comment by nefeline** [comment]
> Is there any way for us to detect the light/dark background and default to a proper color for the button?

@verofasulo the color of the button will default to whatever was selected for usage within the pattern assembler: 

<img width="1232" alt="Screenshot 2023-10-24 at 09 09 43" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/1597bbdf-9cbb-46bf-a396-8c6bb06936c1">

if you think this needs improvement, I would suggest reaching out to Guidorah instead.

**Comment by verofasulo** [comment]
> if you think this needs improvement, I would suggest reaching out to Guidorah instead.

@adrianduffell @chihsuan, do you have any idea of how we can solve this issue? It's really not looking good with a dark background. 🤔 Would it be possible to default to a white button if the contrast between the background and the button is too low?

**Comment by chihsuan** [comment]
> > if you think this needs improvement, I would suggest reaching out to Guidorah instead.
> 
> @adrianduffell @chihsuan, do you have any idea of how we can solve this issue? It's really not looking good with a dark background. 🤔 Would it be possible to default to a white button if the contrast between the background and the button is too low?

Hey @verofasulo, @ilyasfoo has also raised that.
> I believe there’s some opportunity to better label the data that we present the AI with. For example, I found some of the images chosen by AI was dark, where the text heading color chosen by AI is also dark, making the text illegible - p1698109927277869/1698073238.377839-slack-C01SFMVEYAK

We will explore more in our upcoming hack week.  🙌

**Comment by verofasulo** [comment]
> I believe there’s some opportunity to better label the data that we present the AI with. For example, I found some of the images chosen by AI was dark, where the text heading color chosen by AI is also dark, making the text illegible - p1698109927277869/1698073238.377839-slack-C01SFMVEYAK

@ilyasfoo I agree!

> We will explore more in our upcoming hack week.

Yes, please! Did we move it to next week?
