### ISSUE TITLE
[CYS Woo Express] Featured category triple

### ISSUE THREAD

**Issue by verofasulo** [woocommerce/woocommerce-gutenberg-products-block#11401]
Please review `Featured category triple`.

- Please set a character limit for the product title to take only one line.
- Add overlay—Text is barely readable.
- Double-check spacing

<img width="1310" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/98944206/71fe4a7a-86ae-4262-82a6-1ba1e11a24fa">

---

[Figma](https://www.figma.com/file/Mrk6SERPZ4KrFHSjM0a8TK/Customize-your-store-with-pattern-assembler?type=design&node-id=1406-127487&mode=design&t=ZBW0Ds0G26mxIowu-4)

![image](https://github.com/woocommerce/woocommerce-blocks/assets/98944206/5cde0938-c628-4951-9432-be5672765da0)

**Comment by nefeline** [comment]
> Please set a character limit for the product title to take only one line.

This will we worked on https://github.com/woocommerce/woocommerce-blocks/issues/11405

> Double-check spacing

@verofasulo, @albarin have already updated the spacing for this pattern last week on https://github.com/woocommerce/woocommerce-blocks/issues/11276

**Comment by nefeline** [comment]
> Add overlay—Text is barely readable.

@verofasulo  could you please provide us with the design for the expected overlay color and percentage for these images?

**Comment by verofasulo** [comment]
Hey @nefeline

> could you please provide us with the design for the expected overlay color and percentage for these images?

The design is linked above. 🙂 Here's the details for the overlay:

<img width="160" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/98944206/7a91eb42-eb72-405b-a0b3-f3e1308a7199">
