### ISSUE TITLE
TT4: Patterns with buttons

### ISSUE THREAD

**Issue by tjcafferkey** [woocommerce/woocommerce-gutenberg-products-block#11412]
## Describe the bug

All of the patterns that don't have a black button in TT4 theme (e.g. Banner & Discount Banner With Image) have a black border around the buttons used in these. 

However these are opinionated patterns and we are moving to wireframed patterns so I'm marking this as a low priority issue.

## To reproduce

1. Go to create a new post
2. Insert "Discount Banner With Image" pattern
3. See button has border outline

## Expected behavior

These buttons shouldn't have a border.

## Screenshots

![Screenshot 2023-10-23 at 13 25 17](https://github.com/woocommerce/woocommerce-blocks/assets/8639742/1a31eebc-5ceb-42ce-9cf9-a95f5a6b683a)

## Additional context

These are opinionated patterns and we are moving to wireframed patterns so I'm marking this as a low priority issue.

**Comment by nerrad** [comment]
I'm not sure I agree that _all_ the bundled Woo patterns should be unopinionated. Should probably have a conversation about this with design (cc @jarekmorawski).

In general, for opinionated patterns, this is the sort of thing that the pattern should override.

**Comment by danieldudzic** [comment]
@tjcafferkey A bit unrelated, but speaking of buttons and patterns. I found that we have [hardcoded width](https://github.com/woocommerce/woocommerce-blocks/blob/c3e3cd851f30cab5a1a6ba924136d03bb00fe060/assets/js/atomic/blocks/product-elements/button/style.scss#L73) and paddings via CSS in some of our blocks.

I'm thinking of doing a PR stripping all of those, letting the theme control the appearance of buttons, this will solve issues like: https://github.com/woocommerce/woocommerce-blocks/issues/11436 - do you think that's the correct approach?

**Comment by tjcafferkey** [comment]
In the case you've linked where there is a fixed width, I think these should be addressed and let these control them via `theme.json` but I wonder whether a min-width is necessary or not? 🤔

**Comment by danieldudzic** [comment]
I think button `width` and `padding` should be controlled by however the theme decides to style it. `min-width` could be interesting, but I don't think I see a use case for it.

**Comment by jarekmorawski** [comment]
To be honest, I can hardly imagine how opinionated patterns can be useful to merchants. If I spend 10 hours customizing colors, buttons, and fonts on my store, would I want to use a pattern that completely disregards that? It's not a good experience for the merchant, but may also spook shoppers who instinctively recognize broken patterns and visual inconsistencies (website quality is one of the top factors that influences the conversion rate).

Opinionated patterns can be helpful when they come from a theme or an external library. In my opinion, if a pattern is bundled with the core, it should be unopinionated, so the merchant can use it out of the box. As long as the editor doesn't currently offer tools to easily replace custom styles with global ones, we should default to wireframes.

Let me know what you think!

**Comment by danieldudzic** [comment]
@tjcafferkey I believe the hardcoded width `150px` was added to prevent the width from changing (expanding) when the spinner is displayed:

![nevw9YWI2A](https://github.com/woocommerce/woocommerce-blocks/assets/905781/8c05f08c-6101-44f8-b715-7cbe171b7910)

**Comment by Aljullu** [comment]
I agree with what @jarekmorawski mentioned above. But in the meanwhile, as we have some opinionated patterns, I opened a PR to make sure button borders from the theme don't leak into those patterns: https://github.com/woocommerce/woocommerce-blocks/pull/11564.
