### ISSUE TITLE
[Enhancement]: Store API accessibility for external request for flutter mobile app development

### ISSUE THREAD

**Issue by sanskritkm** [woocommerce/woocommerce-gutenberg-products-block#11432]
### Describe the solution you'd like

Currently I have Woocommerce for web e-commerce and want to extent to Flutter mobile commerce that want WC as my main by just use Rest API to fetch all data from WC.

I have WC store API but it require Nonce-Token which is PHP lang, it really hard to call cURL Rest API from mobile app to WC.

Could WC improve not required Nonce-Token when request curl rest api? This way we can use WC as our backend e-commerce solution and develop flutter mobile app by just fetch cURL Rest API to make mobile e-commerce.

**Comment by mikejolley** [comment]
The nonce can be disabled programmatically, but in your use case are you not able to look up the nonce by first performing a GET request? it's returned as a header—you'd just need to store it and send it with POST requests.

**Comment by senadir** [comment]
We haven't heard from you in a while, so I will close this issue for now. Feel free to open it if you still have questions.

**Comment by sanskritkm** [comment]
Hi @senadir Oop! I just saw my mail.

Hi @mikejolley I'm not developer coding. You know today we also can use Low-Code builder to build website or app too without touching code. We can integrate data or sycn by API and low-code platform can only access API curl than if WC require Nonce it real hard for this case. Low-code concept fetch API does not support return such header like programming the concept can only receive response from API as json data. I can make it work everything with WC API except can't add product to card while WC require Nonce Token. 

Could WC has a way to make API request as other system? They need only API key. If it is possible we can make Woocommerce as e-commerce backend for website and we can fetch data to mobile app flutter easily.

Is it secure to disable Nonce Token in Woocommerce for production?

**Comment by senadir** [comment]
It should be fine to disable nonce if you're only going to use the website as a backend for an app.
