### ISSUE TITLE
Update WP test environment to use 6.4 and TT4

### ISSUE THREAD

**Issue by sunyatasattva** [woocommerce/woocommerce-gutenberg-products-block#11443]
Currently our E2E test environment uses TT3 as default theme. We should switch to testing in TT4 and 6.4 to catch bugs with further development.

**Comment by danieldudzic** [comment]
PR updating WP 6.3 to WP 6.4: https://github.com/woocommerce/woocommerce-blocks/pull/11451

PR updating TT3 to TT4: https://github.com/woocommerce/woocommerce-blocks/pull/11466

**Comment by danieldudzic** [comment]
Tests are now running on WP 6.4 and TT4
