### ISSUE TITLE
WP 6.4: Classic Template block for Single Product does not work on the front-end

### ISSUE THREAD

**Issue by sunyatasattva** [woocommerce/woocommerce-gutenberg-products-block#11454]
## Describe the bug

Classic Template block doesn't render on the front-end of WordPress 6.4-based block themes.

## To reproduce

1. Enable WordPress 6.4.
2. Enable a block theme.
3. Go to Site Editor → Single Product template.
4. Remove the blockified template and add the “Classic Template” block.
5. Save and check the front-end.
6. Notice that the template is not rendered.

## Expected behavior

The template should render correctly using the “Classic Template” block.

## Additional context

p1698230999338099-slack-C02FL3X7KR6
p1698246828170079-slack-C029LRAU2

**Comment by sunyatasattva** [comment]
Can confirm this is solved in [6.4-rc.3](https://wordpress.org/news/2023/11/wordpress-6-4-release-candidate-3/) as expected. Also closing the associated draft PR (#11455). However, this created a new issue: https://github.com/woocommerce/woocommerce-blocks/issues/11542

cc @danieldudzic

**Comment by gigitux** [comment]
We noticed that 6.4-rc.2 didn't fix the issue. #11455 fixed the issue.
