### ISSUE TITLE
Investigate: Building a filters block with auto-inserted block hierarchy

### ISSUE THREAD

**Issue by samueljseay** [woocommerce/woocommerce-gutenberg-products-block#11460]
We have been investigating ideas about how we can implement improved frontend filters while trying to achieve some specific goals:

1. They should be as easy to extend as possible. While we currently only support a handful of filters due to Store API limitations, this still would let you build many kinds of filtering API, but it needs to be easy to create a new filter block. This is a Dev UX concern

2. It should be easy for users to use in the editor. If the blocks you can insert are too restricted because you must have a specific parent block or some similar constraint then users will get confused or frustrated when trying to add filters and it should be a simple task. This is a user UX concern.

We are contemplating for the dev UX having a concept of inner blocks to support the different filters. See this PR: https://github.com/woocommerce/woocommerce-blocks/pull/11139 this would be really good for dev UX because the inner block will inherit data that is filtered and processed, all the dev has to do is render their own custom UI. Very flexible.

The **downside however**, is that it is not great for **user UX**. Because now you have a fiddly job of knowing which blocks you need to insert to get price filtering, its quite complicated and there is not good discovery to help a user add a filter. We just made their job very difficult.

Since we like the dev UX, one idea proposed is to have a higher level block. For the sake of discussion lets call it FilterSelectorBlock

FilterSelector block could be inserted anywhere in a product collection and when inserted would allow you to choose from available filter types (e.g. price). 

Hypothetically if you choose the price filter we would insert the block hierarchy for you, adding the CollectionFilter block and the PriceFilter block and it would not be something the user has to deal with.

**Comment by dinhtungdu** [comment]
Closed by https://github.com/woocommerce/woocommerce-blocks/pull/11805
