### ISSUE TITLE
Two documented hooks aren't dispatched when expected

### ISSUE THREAD

**Issue by martynmjones** [woocommerce/woocommerce-gutenberg-products-block#11472]
## Describe the bug

We recently moved the Google Analytics integration from WooCommerce Blocks to WooCommerce Google Analytics Integration. While working to update the tracking for GA4 I noticed that two of the hooks [listed in the documentation](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md#usages-of-experimental-prefix) don't actually exist in WooCommerce Blocks as far as I can tell:

- `experimental__woocommerce_blocks-checkout-render-checkout-form`
- `experimental__woocommerce_blocks-product-search `

## To reproduce

1. With [GA Debugger enabled](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna) and Google Analytics configured, go to a page with the `Product Search` block
2. Search and see that no `search` event is triggered
3. Visit a checkout page powered by the `Checkout` block
4. See no `begin_checkout` event is triggered

## Expected behavior

The documented actions should be dispatched at the expected points of checkout and search.

## Additional context

I appreciate these hooks are still behind an `experimental_` prefix and so aren't production-ready but as the integration exists in WooCommerce Blocks and is currently outdated with Google having retired Universal Analytics I felt it worth reporting.

**Comment by opr** [comment]
Hi @martynmjones thanks for raising this - looks like the `experimental__woocommerce_blocks-checkout-render-checkout-form` action was no longer dispatched following https://github.com/woocommerce/woocommerce-blocks/pull/4745/files - @mikejolley let's re-add it to https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/blocks/checkout/inner-blocks/checkout-fields-block/frontend.tsx#L7 ?

Looks like the product search block is using the standard WordPress search block with a post type specific, so no longer using the one from our repo. Cc @danieldudzic as the FSE porter can you look into this and triage how long it will take to get the event firing again?

**Comment by mikejolley** [comment]
I've raised https://github.com/woocommerce/woocommerce-blocks/pull/11554 to take care of the checkout hook. 

Logged a separate issue for the search one https://github.com/woocommerce/woocommerce/issues/42145
