### ISSUE TITLE
[CYS] Minimal header - Mobile

### ISSUE THREAD

**Issue by verofasulo** [woocommerce/woocommerce-gutenberg-products-block#11509]
Not sure if it’s possible to hide the logo or the store name in the mobile version only. I think it doesn't work well this way:

![image](https://github.com/woocommerce/woocommerce-blocks/assets/98944206/218b2041-9d83-4ef7-a696-3cf73ca5a11d)

**Comment by albarin** [comment]
> Not sure if it’s possible to hide the logo or the store name in the mobile version only. I think it doesn't work well this way:

@verofasulo Sorry, we cannot hide blocks only in one of the versions :(
