### ISSUE TITLE
[CYS] Product Collection 4 Columns

### ISSUE THREAD

**Issue by verofasulo** [woocommerce/woocommerce-gutenberg-products-block#11513]
![image](https://github.com/woocommerce/woocommerce-blocks/assets/98944206/c1c1dcbe-dfc2-4020-b812-fce2891d005a)

The button looks really small (or the label is too big). Could we please double-check if everything is ok? I attached below another button where the balance is different:

![image](https://github.com/woocommerce/woocommerce-blocks/assets/98944206/5fa1f3b0-618c-4961-a0b5-b3ce5e8b56b9)

Also, the label is optically misaligned. Can we center-align the label in each button, please?

@albarin

**Comment by albarin** [comment]
@verofasulo can you share the link to that site so I can check it? I don't see this happening on my site on TT3.

<img width="470" alt="Screenshot 2023-10-31 at 11 14 37" src="https://github.com/woocommerce/woocommerce-blocks/assets/186112/6d6b224e-42c9-427a-a5a6-adad455c46d8">

**Comment by verofasulo** [comment]
Hey @albarin! :)

Just sent you an invite to join my test site 😊
