### ISSUE TITLE
[CYS] Footer with 3 menus

### ISSUE THREAD

**Issue by verofasulo** [woocommerce/woocommerce-gutenberg-products-block#11511]
![image](https://github.com/woocommerce/woocommerce-blocks/assets/98944206/f65e7b88-2016-4c2f-9b0f-aa01c332a0c1)

During our weekly demo, we noticed that resizing the screen caused some menu items to wrap in a weird way. To avoid this behavior, we proposed to decrease the gap between the three menu columns. 

I can’t inspect the component in the frame. @albarin, could you please just try to reduce the spacing a bit and see if some weird behavior happens again? Thank you 🙏

**Comment by albarin** [comment]
@verofasulo Can you check this example 👉 https://annoying-moose.jurassic.ninja/2023/10/31/25/

The first footer is with a reduced space between menus.
The second one is the current one.

**Comment by verofasulo** [comment]
Thanks, @albarin 🙏

I tested both and I have to say I can't see the issue we saw yesterday replicated even in the current one 🤔 That's weird.

**Comment by albarin** [comment]
@verofasulo what about in this site? https://woo-mortally-rad-kitten.wpcomstaging.com/2023/10/31/115/ 🤔

**Comment by verofasulo** [comment]
> what about in this site? https://woo-mortally-rad-kitten.wpcomstaging.com/2023/10/31/115/ 

Oh yes I can see it now! Would it be possible to increase the text container width? I think it would help, also with longer text (we're currently using pretty short menu items, what happens if the user writes "Return and refund policy" for example?)

**Comment by danieldudzic** [comment]
Leaving the link here, just in case any of the spacing issues in the above thread are related to this issue: https://github.com/woocommerce/woocommerce/issues/42150

**Comment by albarin** [comment]
Fixed by https://github.com/woocommerce/woocommerce-blocks/pull/11544
