### ISSUE TITLE
[CYS] Large footer

### ISSUE THREAD

**Issue by verofasulo** [woocommerce/woocommerce-gutenberg-products-block#11512]
![image](https://github.com/woocommerce/woocommerce-blocks/assets/98944206/c15df28f-7bfd-4496-b88d-146107d36a4e)

![image](https://github.com/woocommerce/woocommerce-blocks/assets/98944206/67ac8aa3-d4e2-4a6a-8dc3-e44bf14b4b21)

- There’s a misalignment here: the Join the community block is not aligned wit the logo and the rest of the items.
- Not sure why we wrap the Join the community block this way, there’s still lots of space. 🤔

cc @albarin

**Comment by albarin** [comment]
> There’s a misalignment here: the Join the community block is not aligned wit the logo and the rest of the items.

@verofasulo Can you share the link to this site, please? I don't see the left space you are having.
<img width="566" alt="Screenshot 2023-10-31 at 11 16 59" src="https://github.com/woocommerce/woocommerce-blocks/assets/186112/df069615-ae40-4600-b669-7842d1838001">

> Not sure why we wrap the Join the community block this way, there’s still lots of space. 🤔
<img width="400" alt="Screenshot 2023-10-31 at 11 18 03" src="https://github.com/woocommerce/woocommerce-blocks/assets/186112/7bed868f-b0dd-4dab-b75d-70e2d724ae61">

There's a 40px vertical space in the `Join the community` block, as in the design ☝️

**Comment by verofasulo** [comment]
@albarin, just sent you an invite :) Let me know if you got it.

**Comment by albarin** [comment]
Okay, it's going to be fixed here https://github.com/woocommerce/woocommerce-blocks/pull/11520

**Comment by albarin** [comment]
Fixed by https://github.com/woocommerce/woocommerce-blocks/pull/11520
