### ISSUE TITLE
Example from Divi + WooCommerce = Divi block backend product page.

### ISSUE THREAD

**Issue by paaljoachim** [woocommerce/woocommerce-gutenberg-products-block#1153]
**Is your feature request related to a problem? Please describe.**
It would be nice with a better integration of a product page and Gutenberg. Consisting of a parent product block and child/nested blocks.

Here is an example from Divi + WooCommerce = Divi block product page.

![Screen Shot 2019-11-11 at 11 37 26](https://user-images.githubusercontent.com/5323259/68604089-ad19f400-0477-11ea-8e2e-b5c9d7fe9746.png)

**Comment by nerrad** [comment]
I'm closing this because it is something on the Woo roadmap but no ETA on when it will show up :).

**Comment by paaljoachim** [comment]
Alrighty! 
Have a great continued day, Darren!
