### ISSUE TITLE
Unlock blocks on custom page Checkout impossible

### ISSUE THREAD

**Issue by audi63** [woocommerce/woocommerce-gutenberg-products-block#11541]
Hi,
I want to move down one of the blocks but unlocking the block checkout seems impossible... children's blocks are locked too..
Can you help me ?

Thanks for your work

**Comment by audi63** [comment]
I want to move the Express checkout under Terms of Service.. I can't find a solution to move it properly... and that's not to mention that I would like to keep Express checkout so that it displays under certain conditions, when certain additional fields are not required or depending on the type of sale.

Does anyone have a solution to offer me?

**Comment by opr** [comment]
Hi there, it's not currently possible to do this from within the editor, however I'm wondering if registering a custom block and making it a child of the terms and conditions block would work for you? You could hide the original block with CSS.

> that's not to mention that I would like to keep Express checkout so that it displays under certain conditions, when certain additional fields are not required or depending on the type of sale.

I understand you want to show/hide the block based on certain conditions? I think that if you take the approach above, you can render your custom block based on any condition you like.

Hope this helps answer your question, but please feel free to reach out again if you need more help!

**Comment by audi63** [comment]
Thank you for your response but I've already tested it, and this solution didn't work.

**Comment by opr** [comment]
Hi @audi63 what exactly did you try and what errors did you experience? If you can share some more context with us about this we can try to debug what the issue is and if we need to make any changes to make it easier for developers to extend the blocks. Thanks!

Reopening until we get more feedback.

**Comment by audi63** [comment]
Thank @opr , All children's blocks are blocked. I can understand that we can't delete some of them but we should be able to organize them as we need, and certain child blocks, like ExpressCheckout and certainly others, we should have the right to move or delete them if we don't want the functionality. I have the same problem if I create a personalized block: the child blocks are always clocked, and no modification is possible.

![block-checkout-custom](https://github.com/woocommerce/woocommerce-blocks/assets/52264873/7c83c183-e0bc-4b29-80a3-f2922f4040ed)
![block-checkout-original](https://github.com/woocommerce/woocommerce-blocks/assets/52264873/89fea327-e5af-4b79-acc8-b62a46c4b367)

**Comment by opr** [comment]
Hi thanks for the additional feedback!

> I have the same problem if I create a personalized block: the child blocks are always clocked, and no modification is possible.

I actually mean if you create a custom block as a child of `woocommerce/checkout` you should be able to move this freely. It is intended and expected that merchants cannot move/remove certain blocks as we want to ensure a consistent user experience for shoppers and merchants when it comes to using the Cart and Checkout blocks.

I'll move this to a discussion as I don't think it's an issue that requires action from us, and I'll also cc @pmcpinto - just to make you aware of this discussion. Thanks!
