### ISSUE TITLE
Missing CTT Drop Off Point Box

### ISSUE THREAD

**Issue by mjproenca** [woocommerce/woocommerce-gutenberg-products-block#11540]
## What do you like about the Cart & Checkout blocks?
I like the range of customizing.

## What do you think is missing from the Cart & Checkout blocks?
We have a drop-off point shipping option available. However, when using the blocks Checkout the drop-off point button/box does not appear.

**Comment by opr** [comment]
Hi there @mjproenca 👋🏼 

Thanks for taking the time to make us aware that CTT Drop Off Point Box isn’t working with the Checkout and Cart blocks. These Blocks are built in a different way to the traditional Cart and Checkout shortcodes, and they are designed to optimize for faster checkout. It’s expected that some existing Woo Extensions that integrate with the current checkout flow in WooCommerce core will not work with the blocks.

Currently it’s up to extension developers to add support for the new checkout flow offered via the Cart and Checkout Blocks. We have some [documentation for Third-party developers](https://href.li/?https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs#third-party-developers) and some [Developer Resources](https://href.li/?https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs#developer-resources) available to help with their integration efforts.

Your best course of action now if you are using an extension isn’t working with the blocks is to notify the developer of the extension and ask if they can add support.

Until then, you can keep on top of the [status of the Cart & Checkout Blocks in this documentation](https://href.li/?https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/).

I'll close this issue as there's nothing we can do right now, but please do get in touch with the developer of that extension.

Many thanks again for reporting this.
