### ISSUE TITLE
Notice with action button in My account/ Orders page is not styled properly

### ISSUE THREAD

**Issue by PanosSynetos** [woocommerce/woocommerce-gutenberg-products-block#11563]
## Describe the bug

The notice on `my-account` page when there is an action button, is not styled properly

## To reproduce

Visit `my-account/orders` without having any orders placed

## Screenshots

![image](https://github.com/woocommerce/woocommerce-blocks/assets/2484390/79a9c4f7-44dc-4b2a-8f39-0f9676f51210)

### WordPress (please complete the following information):

-   WordPress version: 6.3.2
-   Gutenberg version (if installed): 16.9.0
-   WooCommerce version: 8.3.0 built from trunk
-   WooCommerce Blocks version: 11.4.1
-   Site language:
-   Any other plugins installed:

**Comment by PanosSynetos** [comment]
@elizaan36 mentioned that 

>  I’m seeing examples of the icon being misaligned from the text on some themes as well.

![image](https://github.com/woocommerce/woocommerce-blocks/assets/2484390/16078288-e22a-49af-85e7-1c1ae2815f31)

![image](https://github.com/woocommerce/woocommerce-blocks/assets/2484390/175bb609-0655-4d7b-a93a-0000ac55f475)

**Comment by tarunvijwani** [comment]
@PanosSynetos @elizaan36, thank you for creating the issue. I wanted to confirm that, as per the recent design changes, the button should appear as a link. Could you please confirm this?

Figma: hqyJB5F38BOXTrOyxehUZH-fi-2134_7160

### Example
| Before | After |
|---|---|
|![image](https://github.com/woocommerce/woocommerce-blocks/assets/11503784/dcac166d-c382-4b8a-ba1b-d98c4c091f0b)|![image](https://github.com/woocommerce/woocommerce-blocks/assets/11503784/fc719278-9b31-499d-b06e-6e81de7188bf)|



##
@PanosSynetos Could you please share the theme name you were using for the below?

| | |
|---|---|
|![image](https://github.com/woocommerce/woocommerce-blocks/assets/11503784/97dd6ef8-890e-4572-a2dd-511603480d0d)|![image](https://github.com/woocommerce/woocommerce-blocks/assets/11503784/c3ab09ea-1133-448b-a19c-06d973737cfb)|

**Comment by PanosSynetos** [comment]
> @PanosSynetos Could you please share the theme name you were using for the below?

These are not my screenshots, these were @elizaan36 , I just pasted them here

**Comment by elizaan36** [comment]
> @elizaan36, thank you for creating the issue. I wanted to confirm that, as per the recent design changes, the button should appear as a link. Could you please confirm this?

Correct!

The block theme was either Sonoran or Lineup.

**Comment by PanosSynetos** [comment]
@tarunvijwani the notices have been addressed by @xristos3490 under this PR

- https://github.com/woocommerce/woocommerce/pull/41325#issuecomment-1842732144

I'd recommend opening a new issue for the rest of the styling issues that @elizaan36 has posted.

**Comment by tarunvijwani** [comment]
Created the new issue: https://github.com/woocommerce/woocommerce/issues/42027
