### ISSUE TITLE
checkout page > checkout block > shipping / billing addresses > company toggle > crash

### ISSUE THREAD

**Issue by Marc-pi** [woocommerce/woocommerce-gutenberg-products-block#11583]
## Describe the bug

activating the Company field leads to a shipping/billing block crash

## To reproduce

1. Go to your checkout page
2. Click the billing or shipping adresse areas, to display the block options on the right panel
3. Toggle on the Company option

## Expected behavior

should not crash

## Screenshots

![image](https://github.com/woocommerce/woocommerce-blocks/assets/919332/eb14bb92-bd47-489e-a89b-f0504d2a1b38)

![image](https://github.com/woocommerce/woocommerce-blocks/assets/919332/c1699c1d-3a7b-440a-add5-a6dc5e84183c)

## Environment

WP6.3.2
WooCommerce 8.2.1
Woo blocks 11.4.1
TT3 theme
PHP v8.1.23

**Comment by senadir** [comment]
This seems to fall in line with other reports we have about those issues, happening only in the editor and started surfacing recently when we introduced Condensed Address.

Thank you for the report @Marc-pi !

**Comment by senadir** [comment]
This also affects things like unchecking and checking the "use shipping as billing" checkbox in the editor.

**Comment by tarunvijwani** [comment]
Related issue, when changing the shipping method in checkout from shipping to local pickup and back, the shipping address form block displays an error message `This block has encountered an error and cannot be previewed.`



https://github.com/woocommerce/woocommerce-blocks/assets/11503784/808defcd-3e4c-4880-85fd-5a177d439568

**Comment by ralucaStan** [comment]
@mikejolley I've assigned this to you because it's a high priority and it can be related to the condensed address
