### ISSUE TITLE
StoreApi CartAddItem /  woocommerce_store_api_add_to_cart_data

### ISSUE THREAD

**Issue by goat-io** [woocommerce/woocommerce-gutenberg-products-block#11609]
## Describe the bug

I'm encountering a situation that might be either a bug or an area where the documentation could be improved, specifically regarding the addition of custom data to the cart items.

**Details**
When attempting to add a new item to the cart using CartAddItem, I noticed that the cart_item_data attribute gets filtered out. It has been suggested in discussions that we should use [woocommerce_store_api_add_to_cart_data](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/hooks/filters.md#woocommerce_store_api_add_to_cart_data) as an alternative.

However, rather than just appending data to the item, add_to_cart_data seems to pass all the "extra" data to the [cart body](https://github.com/woocommerce/woocommerce-blocks/blob/c5afddb1abb0b6024a38aecc4ac5f86b9899e369/src/StoreApi/Utilities/CartController.php#L122). While this approach could be beneficial for further extending the cart, it seems somewhat counterintuitive when we consider that add_to_cart is meant to support only 4 attributes (id, quantity, variation, cart_item_data).

It appears to be a hybrid between WooCommerce's woocommerce_add_cart_item and woocommerce_add_cart_item_data. Is this the intended behavior?

Furthermore, when we try to use the data, item_data goes through a [schema filter](https://github.com/woocommerce/woocommerce-blocks/blob/c5afddb1abb0b6024a38aecc4ac5f86b9899e369/src/StoreApi/Schemas/V1/ItemSchema.php#L162-L190) which only allows arrays in the form of {name:string, value:string, display:string}. This seems less intuitive, especially considering that the initial purpose of omitting cart_item_data was to provide users the flexibility to send "any" type of data.

Even if we send everything in the right format, we would still end up with an empty array, because the [CartItemSchema](https://github.com/woocommerce/woocommerce-blocks/blob/c5afddb1abb0b6024a38aecc4ac5f86b9899e369/src/StoreApi/Schemas/V1/CartItemSchema.php#L102) uses woocommerce_get_item_data, and if we don't have anything defined, we end up with an empty array.

**Finally, to make it work.**
So the only way that I found for this to work as expected was to define **woocommerce_store_api_add_to_cart_data** to get the data that I want to send in the request, and also **woocommerce_get_item_data** to extract the right data from the cart.
And given that the values just get appended to the cart, I had to wrap them in another attribute

![image](https://github.com/woocommerce/woocommerce-blocks/assets/48744933/5bcc0cce-54bb-4982-9313-f79aa650e83a)

```php

add_filter(
  'woocommerce_store_api_add_to_cart_data',
  'custom_add_to_cart_data',
  10,
  2
);

function custom_add_to_cart_data($add_to_cart_data, $request)
{
  // Check if cart_item_data is set in the request
  if (isset($request['cart_item_data'])) {
    // Add cart_item_data to the add to cart data array
    $add_to_cart_data['cart_item_data'] = $request['cart_item_data'];
  }

  // Return the modified data
  return $add_to_cart_data;
}

add_filter(
  'woocommerce_get_item_data',
  'custom_woocommerce_get_item_data',
  10,
  2
);
function custom_woocommerce_get_item_data($some, $cart_data)
{
  if (isset($cart_data['custom_data'])) {
    return $cart_data['custom_data'];
  }
  return [];
}
```

I'm I missing something or is this the intended behaviour? 

## To reproduce

1. Create a simple custom filter woocommerce_add_cart_item_data to accept the "cart_item_data"
```php
function custom_add_to_cart_data($add_to_cart_data, $request)
{

  if (isset($request['cart_item_data'])) {
    // Add cart_item_data to the add to cart data array
    $add_to_cart_data['cart_item_data'] = $request['cart_item_data'];
  }

  // Return the modified data
  return $add_to_cart_data;
}

```
2. Send a POST request to /wp-json/wc/store/v1/cart/add-item containing the body and the cart_item_data

```
{
 "id": 294,
 "quantity": 3,
 "cart_item_data": [{
   "name": "Color",
   "value": "red"
 }, {
   "name": "Size",
   "value": "2"
 }]
}
```

## Expected behavior

I would expect to see the cart_item_data values in the cart response in item_data
```
{
...
items: [
{
...
item_data:  [{
   "name": "Color",
   "value": "red"
 }, {
   "name": "Size",
   "value": "2"
 }]
}
]
}
```
But I get an empty array
```
[]
```

## Screenshots

![image](https://github.com/woocommerce/woocommerce-blocks/assets/48744933/de200a94-ad0e-4ca9-b2ce-8fd5966e9197)

### WordPress (please complete the following information):

-   WordPress version: 6.3
-   Gutenberg version (if installed):
-   WooCommerce version:7.9
-   WooCommerce Blocks version: 10.4.6
-   Site language: EN
-   Any other plugins installed: -

### Desktop (please complete the following information):

-   OS: macOs Docker

**Comment by wavvves** [comment]
Hi @goat-io, thank you for reaching out. While trying to wrap my head around this Issue, I noticed this on the testing steps:

> Create a simple custom filter woocommerce_add_cart_item_data to accept the "cart_item_data"

Where you mention `woocommerce_add_cart_item_data`, yet we do have a similarly named filter called `woocommerce_store_api_add_to_cart_data` as you mentioned earlier.

Is there any chance this is not working because you intended to use that one instead?

From the source, it seems you are getting the empty array from there:

```
/**
		 * Filters cart item data sent via the API before it is passed to the cart controller.
		 *
		 * This hook filters cart items. It allows the request data to be changed, for example, quantity, or
		 * supplemental cart item data, before it is passed into CartController::add_to_cart and stored to session.
		 *
		 * CartController::add_to_cart only expects the keys id, quantity, variation, and cart_item_data, so other values
		 * may be ignored. CartController::add_to_cart (and core) do already have a filter hook called
		 * woocommerce_add_cart_item, but this does not have access to the original Store API request like this hook does.
		 *
		 * @since 8.8.0
		 *
		 * @param array $customer_data An array of customer (user) data.
		 * @return array
		 */
		$add_to_cart_data = apply_filters(
			'woocommerce_store_api_add_to_cart_data',
			array(
				'id'             => $request['id'],
				'quantity'       => $request['quantity'],
				'variation'      => $request['variation'],
				'cart_item_data' => [],
			),
			$request
		);

		$this->cart_controller->add_to_cart( $add_to_cart_data );

		$response = rest_ensure_response( $this->schema->get_item_response( $cart ) );
		$response->set_status( 201 );
		return $response;
	}
```

**Comment by mikejolley** [comment]
Since this hasn't had any updates in a while I'm going to mark it closed, but feel free to respond or post a new issue if issues persist.

Thanks
