### ISSUE TITLE
PHP Warning: foreach() argument must be of type array|object, null given in `...PatternsHelper.php`

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#11696]
## Describe the bug

The `PatternsHelper.php` is outputting some PHP warnings on my site.

## To reproduce

1. Go to Appearance > Editor.
2. Now, open the PHP log of your site.
3. Notice there is this PHP warning:

```
foreach() argument must be of type array|object, null given in .../wp-content/plugins/woocommerce-blocks/src/Patterns/PatternsHelper.php on line 153
```

I tested it with WP 6.4 and PHP 8.1.9.

## Expected behavior

There should be no warnings in the log.

**Comment by Aljullu** [comment]
@albarin tagging you in this one as well for awareness as it's related to patterns and https://github.com/woocommerce/woocommerce-blocks/issues/11695. :pray:

**Comment by albarin** [comment]
This is going to be fixed in https://github.com/woocommerce/woocommerce-blocks/pull/11681
