### ISSUE TITLE
PHP Warning: Trying to access array offset on value of type null in `.../featured-products-fresh-and-tasty.php`

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#11695]
## Describe the bug

It looks like we have some PHP warnings related to the _Featured Products: Fresh & Tasty_ pattern.

## To reproduce

1. Go to Appearance > Editor.
2. Now, open the PHP log of your site.
3. Notice there is this PHP warning:

```
PHP Warning:  Trying to access array offset on value of type null in .../wp-content/plugins/woocommerce-blocks/patterns/featured-products-fresh-and-tasty.php on line 132
```

I tested it with WP 6.4 and PHP 8.1.9.

## Expected behavior

There should be no warnings in the log.

**Comment by Aljullu** [comment]
@albarin can you reproduce? Maybe I have something not properly set up in my dev environment.

**Comment by albarin** [comment]
Hey this is going to be fixed in https://github.com/woocommerce/woocommerce-blocks/pull/11681
