### ISSUE TITLE
Incompatible plugin declaration message not displaying correctly in Safari

### ISSUE THREAD

**Issue by grenadeco** [woocommerce/woocommerce-gutenberg-products-block#11734]
## Describe the bug

While testing the Checkout Block incompatible plugin declaration message, I noticed the message displayed as blank in Safari.

## To reproduce

1. Install WooCommerce
2. Instal a WooCommerce plugin that is not yet compatible with the new Checkout Blocks and has declared incompatibility (e.g. Checkout Field Editor).
3. Navigate to the Checkout page
4. Select a block and view the Block option panel on the right of the screen
5. The plugin declaration message area displays, however, the actual message is blank.

## Expected behavior

The plugin declaration message should display as expected.

## Screenshots

Safari:
![Screenshot 2023-11-10 at 14 19 48](https://github.com/woocommerce/woocommerce-blocks/assets/23656235/b3b387a0-5a11-490c-b37c-2eafad4347e3)

Expected behavior (Chrome):
![Screenshot 2023-11-10 at 14 26 38](https://github.com/woocommerce/woocommerce-blocks/assets/23656235/1113ea67-f142-47e4-8cfc-1724eb892a5a)

### WordPress (please complete the following information):

-   WordPress version: 6.4.1
-   Gutenberg version (if installed): NA
-   WooCommerce version: 8.3.0-rc.2
-   WooCommerce Blocks version: NA
-   Site language: English (United States)
-   Any other plugins installed: WooCommerce Checkout Field Editor 1.7.12

### Desktop (please complete the following information):

-   OS: macOS
-   Browser: Safari 
-   Version: 16.3

### Smartphone (please complete the following information):

NA

## Additional context

None

**Comment by ralucaStan** [comment]
Thank you @grenadeco for this report. I was able to replicate

**Comment by nielslange** [comment]
Hello @grenadeco 👋 

Thanks for reaching out and congratulations for your very first bug report! 👏 Similar to @ralucaStan, I was able to reproduce this issue and I went ahead and fixed it in https://github.com/woocommerce/woocommerce-blocks/pull/11736. Usually, reports did not get addressed that fast, but you discovered a critical bug. Thanks again for reporting it! 🙌
