### ISSUE TITLE
Woo+Wooblocks latests + Gutenberg 17.0.0 > manage page or post or product > editor crash

### ISSUE THREAD

**Issue by Marc-pi** [woocommerce/woocommerce-gutenberg-products-block#11730]
After upgrading to the latest 17.0.0, i observed that i cannot add or edit content, like Woo Products
I have the issue on multiples websites, all with the same technical / plugin environment
but not on those that do not run wooCommerce / Woo Blocks, or only Gutenberg with no Woo/Wooblocks plugins
I you rollback to 16.9.0, it works again

I you run a website with the same very latest woocommerce/wooblocks releases but without the Gutenberg plugin installed, you do not have the issue, that's why i post the issue here in the project, instead of in the gutenberg repository.

i fear it deals with the latest WooBlocks release in conjonction with latest Gutenberg 17.0.0 version and WP6.4 changes
especially could be a follow up to the recent fixes around template loading.

![image](https://github.com/woocommerce/woocommerce-blocks/assets/919332/3f87ca38-add0-4792-be74-b9abe9c6ff4e)

![image](https://github.com/woocommerce/woocommerce-blocks/assets/919332/849ccc3f-c45b-4179-bdc9-33b7690263ea)

> please tell me what extra infos you need so we tackle down this issue

**Step-by-step reproduction instructions**
1. Upgrade to 17.0.0
2. Go to add a new page, or edit a new one, or a ... woocommerce product
3. You will get the message "The editor as encountered an unespected error"
4. From Webmaster tools (FF), in console tab, you'll see that there is a syntax issue with css/unclosed block, but i did not investigate further on
5. If you roll back to 16.6.9, ther error is going away, you can manage your contents

**Environment infos**
- WP 6.4.1
- Gutenberg 17.7
- TT3 theme
- Woocommerce 8.2.2
- Woocommerce Blocks 15.5.1
- PHP 8.1.23
- Chrome or Firefox

**Comment by danieldudzic** [comment]
👋 Thank you for reporting the problem.

I'm struggling to replicate the issue with the following setup:
- WordPress 6.4.1
- Gutenberg: 17.0.0
- Twenty Twenty-Three
- WooCommerce: 8.2.2
- WooCommerce Blocks: 11.5.1

<img width="1118" alt="Add_New_Page_‹_Deafening_Hare_—_WordPress" src="https://github.com/woocommerce/woocommerce-blocks/assets/905781/75d0001f-6b8d-4dc8-b14b-3c1169dc6d2e">

Did you test with all other plugins disabled?

**Comment by Marc-pi** [comment]
i'll try to determine by inactivating other plugins
i do have the issue with several websites with different plugin installed
possibly related to https://github.com/WordPress/gutenberg/pull/56051

**Comment by Marc-pi** [comment]
1/ The error trace
i've copied the error from the crash toolbar above
seems the error lies in Gutenberg (unclosed block error)

```
i@https://www.mysite.com/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=7a6a1df140c4fe7830e1:1:90318
error@https://www.mysite.com/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=7a6a1df140c4fe7830e1:1:94112
unclosedBlock@https://www.mysite.com/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=7a6a1df140c4fe7830e1:1:120433
endFile@https://www.mysite.com/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=7a6a1df140c4fe7830e1:1:117751
parse@https://www.mysite.com/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=7a6a1df140c4fe7830e1:1:119444
l@https://www.mysite.com/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=7a6a1df140c4fe7830e1:1:113525
y@https://www.mysite.com/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=7a6a1df140c4fe7830e1:1:97078
process@https://www.mysite.com/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=7a6a1df140c4fe7830e1:1:124965
Pm/<@https://www.mysite.com/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=7a6a1df140c4fe7830e1:18:19596
Pm@https://www.mysite.com/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=7a6a1df140c4fe7830e1:18:19466
@https://www.mysite.com/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=7a6a1df140c4fe7830e1:18:20391
useMemo@https://www.mysite.com/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:115217
t/e.useMemo@https://www.mysite.com/wp-content/plugins/gutenberg/build/vendors/react.min.js?ver=18:1:9875
Nm@https://www.mysite.com/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=7a6a1df140c4fe7830e1:18:20244
St@https://www.mysite.com/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:47627
$s@https://www.mysite.com/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:120574
Sl@https://www.mysite.com/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:88651
kl@https://www.mysite.com/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:88579
bl@https://www.mysite.com/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:88440
sl@https://www.mysite.com/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:85264
dl@https://www.mysite.com/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:85651
Nn@https://www.mysite.com/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:32464
n/ol/<@https://www.mysite.com/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:83216
```

that's the same as the issue revealed by the Firefox Dev tool 
CssSyntaxError: <css input>:36:1: Unclosed block
![image](https://github.com/woocommerce/woocommerce-blocks/assets/919332/ca1c3aa9-dcd9-4d41-a6c4-4fcc5c5ae33b)

With Query monitor, i can read

PHP errors were triggered during an Ajax request. See your browser developer console for details.


2/ I've tested with playground : no issue
https://playground.wordpress.net/?plugin=woocommerce&plugin=woo-gutenberg-products-block&plugin=gutenberg&theme=twentytwentythree

3/ I've compared the installed plugins installed accross all websites (some that work, some that does not work)
* i was not able to detect any faulty plugin
* i've swiped to EN (i was on FR) : the issues are still there
* i've double checked the impacted features 
    * the issue lies on Edit Page and Edit Posts
    * Woo Products can be edited
    * so checkout / shop Page cannot be edited


Can anyone give me another way to check what's wrong ? 
seems to be a gutenberg issue so far, no ?

**Comment by Marc-pi** [comment]
ok, i've found it, was a missing closing bracket in my custom css (through the Editor) / see https://github.com/WordPress/gutenberg/issues/56082, linked to a regression in 6.4 (syntax error warning is missing)
we can close this, sorry for the noise ;-)
