### ISSUE TITLE
Hardcoding colors for validation messages causes problems with certain color palettes

### ISSUE THREAD

**Issue by xristos3490** [woocommerce/woocommerce-gutenberg-products-block#11738]
## Describe the bug

Hardcoding colors for validation messages causes problems with certain color palettes, resulting in styling issues.

![zujBUD.png](https://github.com/woocommerce/woocommerce-blocks/assets/1105590/996d27b4-2b30-423f-92ae-e8099e0b52b0)

## To reproduce

1. Visit a store using the TT4 theme
2. Switch to a dark background style like _Maelstorm_
3. Add some products to the cart.
4. Navigate to the checkout.
5. Submit the checkout with empty fields.
6. Notice the styling issue.

## Expected behavior

Not sure tbh.

Perhaps validation messages should not have a specific color and instead inherit the one defined in the body from the color palette.

Removing the red color looks like this:
![DYqXoI.png](https://github.com/woocommerce/woocommerce-blocks/assets/1105590/454e52a9-9fc5-4eda-b07b-096fcb78c498)

Another idea could be to provide a color setting in the inspector _(if that's feasible)_:
![xZ0SIh.png](https://github.com/woocommerce/woocommerce-blocks/assets/1105590/795b6927-0ac6-4109-b0f2-1059422b4d8a) 

### WordPress (please complete the following information):

-   WordPress version: [e.g. 5.9]
-   Gutenberg version (if installed): [e.g. 12.0.0]
-   WooCommerce version: [e.g. 6.1]
-   WooCommerce Blocks version: [e.g. 7.0.0]
-   Site language:
-   Any other plugins installed:

### Desktop (please complete the following information):

-   OS: [e.g. macOS, Windows]
-   Browser [e.g. chrome, safari]
-   Version [e.g. 22]

### Smartphone (please complete the following information):

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Comment by ralucaStan** [comment]
@elizaan36 we'll need your input on this one. What I'm also thinking is that we could provide some predefined colors that people might be able to choose from. 

For now, I think this can be fixed with some custom CSS, but we should target to make this as flexible as possible for merchants with no code required.

**Comment by elizaan36** [comment]
Error messages and validation should be something that just works without the merchant needing to think too much about it. For dark mode form fields, we could we use another predefined red color that works on dark themes, such as #FFAAAA.

**Comment by ralucaStan** [comment]
I don't think it's possible to detect dark more form fields.

**Comment by senadir** [comment]
Checkout supports a dark mode option @ralucaStan 

<img width="281" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/6165348/7a207b53-c412-4cfb-a566-36502cbf0277">

<img width="653" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/6165348/b8dbf964-2712-481e-8e60-1089bcae759f">


Yet, it stands that the red has not been adapted to it, so we can adapt it I think.

**Comment by ralucaStan** [comment]
I appreciate the reminder @senadir. 

@elizaan36, should we keep the `#FFAAAA` as the desired color for errors when using dark inputs? Is that the same color as the borders?

**Comment by elizaan36** [comment]
Looks like the border and input text is #f18c8c on dark mode form fields, so the error string color should match that.
