### ISSUE TITLE
woocommerce_cart_item_name  filter not working with wocommerce cart block page.

### ISSUE THREAD

**Issue by nidhitatosaniya** [woocommerce/woocommerce-gutenberg-products-block#11747]
## Describe the bug

woocommerce_cart_item_name  filter not workingon wocommerce cart block page.
## To reproduce

`add_filter( 'woocommerce_cart_item_name', array( $this, 'add_product_input_fields_to_cart_item_name' ), PHP_INT_MAX, 3 );`

## Expected behavior

should be display look like : https://prnt.sc/PLUS_D3_bsOt
which hook or filter we need to use instead it?

**Comment by wavvves** [comment]
Hi @nidhitatosaniya, thank you for reaching out.
Can you provide more details on what you are trying to achieve and how you currently do it?

If you want to change the itemName there's [documentation](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/checkout-block/available-filters/cart-line-items.md#itemname) providing examples on how to do it.

If you need to add and display custom metadata for items, it is also possible, and probably the right way to achieve that. [This](https://stackoverflow.com/questions/54505642/display-and-save-added-custom-cart-item-data-on-woocommerce-cart-checkout-and-o)
outlines how it could be achieved.

If you need any extra help regarding Blocks, we'll be happy to help 🙂

**Comment by mikejolley** [comment]
Since this hasn't had any further feedback I am going to mark it closed. Thanks!
