### ISSUE TITLE
Custom add_to_cart text - error when checking product type 

### ISSUE THREAD

**Issue by Amelandbor** [woocommerce/woocommerce-gutenberg-products-block#1176]
`Fatal error: Uncaught Error: Call to a member function is_type()`

Getting this error when I'm checking if a product is a variable product, which I use to have a custom add to cart text. Seems I can't access any methods in WC_Product.

Simplified code:

``` php
function custom_woocommerce_product_add_to_cart_text() {
	
	global $product;

	if ( $product->is_type( 'variable' ) ) {
		return __( 'Select options', 'woocommerce' );
	}
	else {
		return __( 'Add to cart', 'woocommerce' );
	}
}
```

**Comment by nerrad** [comment]
See thread prompting this in the [WooCommerce community slack](https://woocommercecommunity.slack.com/archives/C1K9K3UD9/p1573736197483100) (requires account there)

Thanks for taking the time to post this issue @Amelandbor , however there's still a bit more detail we need here in order to troubleshoot this issue:

- How is this related to WooCommerce Blocks?
- What version of WooCommerce core?
- What version of WooCommerce Product Blocks plugin?
- What are you hooking that example code into? Or how are you implementing it?

**Comment by Amelandbor** [comment]
WC Core - 3.8.0
WC Blocks - 2.4.4

```php 

function custom_woocommerce_product_add_to_cart_text() {
    
    global $product;
  
    print $product->get_type();
}
add_filter( 'woocommerce_product_add_to_cart_text' , custom_woocommerce_product_add_to_cart_text' );'''

**Comment by mikejolley** [comment]
It's a problem with your function. In this case, how do you know the global is set? Without first checking if `$product` is set and is indeed a product object, you are inviting errors.

`woocommerce_product_add_to_cart_text` actually passes you a product object. So if you did this:

```
function custom_woocommerce_product_add_to_cart_text( $product ) {
...
```

You don't need to use globals at all.

I am closing this, it's not related to woo blocks.

Thanks

**Comment by Amelandbor** [comment]
Thanks for looking into it. 

Like I said, this is the simplified version. In the original I have a check for a product object. Did you try the solution yourself, because I'm getting the same error. 

> I am closing this, it's not related to woo blocks. 

So how come this only happens when I'm trying to add a product through Woo blocks. Shortcodes work fine.

**Comment by mikejolley** [comment]
I updated my snippet, you have to understand how filters work and what data can be passed, referring to the filter itself: https://github.com/woocommerce/woocommerce/blob/badb135bd62ca5d11cf6a55220cee61180f8c00c/includes/class-wc-product-simple.php#L62

**Comment by Amelandbor** [comment]
Thanks a lot for taking the time. I guess I have some reading up to do.
