### ISSUE TITLE
Update notice for default cart and checkout

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#11777]
## Is your feature request related to a problem? Please describe.

When a merchant adds the Cart or Checkout block to a page, but does not define the corresponding pages as the cart or checkout page via `/wp-admin/admin.php?page=wc-settings&tab=advanced`, the following notices are visible in the sidebar:

<table>
<tr>
<td valign="top">Current notice for Cart block:
<br><br>
<img width="289" alt="Screenshot 2023-11-15 at 10 42 25" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/5f032022-3e2a-4d84-8f1e-f5c043ba1444">
</td>
<td valign="top">Current notice for Checkout block:
<br><br>
<img width="289" alt="Screenshot 2023-11-15 at 10 41 46" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/0bc10943-7d9e-4270-b5d8-b83a316a7064">
</td>
</tr>
</table>

## Describe the solution you'd like

In p1699988291133359/1699592175.220079-slack-C02UBB1EPEF, @elizaan36 asked to replace the button in the `<DefaultNotice>` component with an inline link and to display an info notice instead of a warning notice.

<table>
<tr>
<td valign="top">Expected notice for Cart block:
<br><br>
<img width="290" alt="Screenshot 2023-11-15 at 10 54 06" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/244f334e-042d-4948-9ba8-9abbe854eb11">
</td>
<td valign="top">Expected notice for Checkout block:
<br><br>
<img width="290" alt="Screenshot 2023-11-15 at 10 55 22" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/77c390df-4ec0-4160-aa0a-12648b490dbd">
</td>
</tr>
</table>

## Describe alternatives you've considered

n/a

## Additional context

n/a

**Comment by Sahad-09** [comment]
I'm working on it
