### ISSUE TITLE
Notices not showing on the empty cart block view

### ISSUE THREAD

**Issue by wavvves** [woocommerce/woocommerce-gutenberg-products-block#11786]
## Describe the bug

Notices are not displaying on the block empty cart view

## To reproduce

1. Make sure the Cart page has the Cart Block
2. With no items on Cart navigate to the checkout page
3. Verify it redirects to cart page and displays the "Your cart is currently empty!" view and no notices are shown
4. Navigate directly to the My Account page
5. It shows a notice stating "Checkout is not available whilst your cart is empty."

## Expected behavior

The notice should display on the empty Cart view, not the following request.

## Screenshots

https://github.com/woocommerce/woocommerce-blocks/assets/17236129/6fada88f-6519-467a-b9f5-2f380988d988

**Comment by pierorocca** [comment]
@wavvves if you use a failing test card on checkout do you also not see the notice? My test site is not get notices and am hoping others can replicate that issue.

**Comment by mikejolley** [comment]
The notice container is not missing, its just not capturing the notice created by core.

**Comment by mikejolley** [comment]
Decided to remove the notice in core since we cannot capture it our side.

https://github.com/woocommerce/woocommerce/pull/41504

**Comment by wavvves** [comment]
Closing this as it has been solved by https://github.com/woocommerce/woocommerce/pull/41504
