### ISSUE TITLE
Internalize "private" Code APIs

### ISSUE THREAD

**Issue by ObliviousHarmony** [woocommerce/woocommerce-gutenberg-products-block#11798]
One potential concern about the merge is the strictness with which WooCommerce Core adheres to backward compatibility in code APIs. Any code within `includes/` or the `Automattic\WooCommerce` namespace is fair game for external developers and should be expected to work long-term. The approach we've taken in woocommerce/woocommerce with respect to code APIs we don't intend to support forever is to use the `Automattic\WooCommerce\Internal` namespace. This namespace does not have any backward compatibility guarantees and is considered internal to WooCommerce Core.

While there's definitely a line to walk here, we should review all of the code in `src` and decide what kind of guarantees we want to make about these code APIs. In cases where the likelihood that someone is using it is low we can move them into the internal namespace. As part of this work, we should set up the `Automattic\WooCommerce\Internal` namespace in `woocommerce/woocommerce-blocks.

I can't recall off the top of my head, but we can probably create a `src/Internal` directory and add a mapping to `composer.json` for autoloading. If that doesn't work we can create a `src-internal` directory and do the mapping that way. As long as we distribute that directory in the feature plugin and composer package it'll work just fine.

**Make sure to not accidentally use `Automattic\WooCommerce\Blocks\Internal`!**

**Comment by nerrad** [comment]
Generally, any code that is not prefixed `_experimental` or `_internal` is "public" and already _is potentially used by third parties_. Keep in mind, Woo Blocks has already been released with Woo Core (and from the consumer pov _is core_) so I think the ship has sailed for what you are proposing here.

At a minimum, the team should have a conversation about the future use of `_experimental` or `_internal` prefixes going forward.

**Comment by ObliviousHarmony** [comment]
> Keep in mind, Woo Blocks has already been released with Woo Core

While true, it's worth pointing out that `packages/woocommerce-blocks/src` is buried pretty deeply in the plugin and isn't clearly documented anywhere in Core. It's entirely possible that people have used it, of course, but this is more of a note from the WooCommerce Admin merge than something specifically required here.

In that case, there was a bunch of code that engineers wrote without ever intending to explicitly declare backward compatibility for. They reviewed the code and decided what could and couldn't be safely moved, and in cases where they needed to maintain compatibility but wanted to internalize that work moving forward, [they implemented the class as a facade and marked it as deprecated](https://github.com/woocommerce/woocommerce-admin/blob/main/src/Loader.php).

Ideally, all of the code currently within the Blocks plugin is written with the expectation that it be used by external developers. That would certainly make things easier, but this is just food for thought.

**Comment by nerrad** [comment]
Comparing WC Admin in this case isn't a fair comparison (and I'm aware of the distinction there) - Woo Blocks explicitly learned from what was done in WC Admin and from the get-go the teams were careful about indicating internal/experimental code. I'm giving you the context. I think it's useful to make sure the teams working on Woo Blocks are aware of the availability of the `Internal` namespacing, but we don't have code that can be moved into that namespace as a part of the merge.

**Comment by ObliviousHarmony** [comment]
That's good to hear, I can close this issue then, thanks!
