### ISSUE TITLE
Feedback on new cart

### ISSUE THREAD

**Issue by Juanmafortes** [woocommerce/woocommerce-gutenberg-products-block#11809]
## What do you like about the Cart & Checkout blocks?

I like the new layouts much more than the old one. They are cleaner, more straight forward and modern, which may increase conversion rates.

## What do you think is missing from the Cart & Checkout blocks?

Customization options on the blocks. I dont know why, but my "proceed to payment" button is transparent. I can tweak that easily with CSS, but another issue I am finding is that the cross-selling products in the cart show the product's average rating **in text** instead of stars. So it reads "Valorado 5 sobre 5 basado en 1 puntuación" in spanish, which is almost 3 lines long in desktop lol.

Also, this blocks not being customizable with the old filters and snippets makes it more challenging, as most of the info out there is for the old system. One example of this is that I do not want to show the price range of my variations, but a "from X" instead. I sell fruit boxes in different sizes, so price ranges going from 40-240 is discouraging for customers. I feel like this might be a good and fairly easy adition to Woo core.

Another thing from the cross-selling products in the cart is that you cannot select not showing the button. This means that when they are out of stock you can not filter them out, and they show a "read more" button, and that variable products show a "select options" text, which is very suboptimal.

Thanks a lot for improving the cart and checkout process.

**Comment by wavvves** [comment]
Hi @Juanmafortes 
Thank you for the feedback, can you please send the report from WooCommerce > Status so we can have a look at what might be causing those visual glitches?

**Comment by Juanmafortes** [comment]
Hi @wavvves 

`
### WordPress Environment ###

WordPress address (URL): https://www.staging2.example.com
Site address (URL): https://www.staging2.example.com
WC Version: 8.3.0
REST API Version: ✔ 8.3.0
WC Blocks Version: ✔ 11.4.8
Action Scheduler Version: ✔ 3.6.4
Log Directory Writable: ✔
WP Version: 6.4.1
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: –
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.85.0
OpenSSL/3.0.9

SUHOSIN Installed: –
MySQL Version: 5.7.39-42-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.3.0
WC Database Prefix: dxp_
Tamaño total de la base de datos: 212.63MB
Tamaño de los datos de la base de datos: 169.17MB
Tamaño del índice de la base de datos: 43.46MB
dxp_woocommerce_sessions: Datos: 0.11MB + Índice: 0.02MB + Motor InnoDB
dxp_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
dxp_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
dxp_woocommerce_order_items: Datos: 0.41MB + Índice: 0.16MB + Motor InnoDB
dxp_woocommerce_order_itemmeta: Datos: 3.52MB + Índice: 4.03MB + Motor InnoDB
dxp_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
dxp_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
dxp_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
dxp_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
dxp_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_actionscheduler_actions: Datos: 0.09MB + Índice: 0.13MB + Motor InnoDB
dxp_actionscheduler_claims: Datos: 1.52MB + Índice: 0.50MB + Motor InnoDB
dxp_actionscheduler_groups: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_actionscheduler_logs: Datos: 0.11MB + Índice: 0.09MB + Motor InnoDB
dxp_campos_cntrlz: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_commentmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
dxp_comments: Datos: 1.52MB + Índice: 1.14MB + Motor InnoDB
dxp_duplicator_pro_entities: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_duplicator_pro_packages: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_enviados_prcss_cntrlz: Datos: 0.11MB + Índice: 0.00MB + Motor InnoDB
dxp_gla_attribute_mapping_rules: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_gla_budget_recommendations: Datos: 0.22MB + Índice: 0.14MB + Motor InnoDB
dxp_gla_merchant_issues: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_gla_shipping_rates: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
dxp_gla_shipping_times: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_icl_background_task: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_icl_content_status: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_icl_core_status: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_icl_flags: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_icl_languages: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
dxp_icl_languages_translations: Datos: 0.20MB + Índice: 0.17MB + Motor InnoDB
dxp_icl_locale_map: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_icl_message_status: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
dxp_icl_mo_files_domains: Datos: 0.14MB + Índice: 0.05MB + Motor InnoDB
dxp_icl_node: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_icl_reminders: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_icl_strings: Datos: 5.52MB + Índice: 6.73MB + Motor InnoDB
dxp_icl_string_batches: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_icl_string_packages: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_icl_string_pages: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
dxp_icl_string_positions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_icl_string_status: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_icl_string_translations: Datos: 5.52MB + Índice: 4.03MB + Motor InnoDB
dxp_icl_string_urls: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_icl_translate: Datos: 18.52MB + Índice: 0.17MB + Motor InnoDB
dxp_icl_translate_job: Datos: 0.05MB + Índice: 0.02MB + Motor InnoDB
dxp_icl_translations: Datos: 0.19MB + Índice: 0.52MB + Motor InnoDB
dxp_icl_translation_batches: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_icl_translation_downloads: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_icl_translation_status: Datos: 9.52MB + Índice: 0.08MB + Motor InnoDB
dxp_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_mailchimp_carts: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_mailchimp_jobs: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_mailpoet_automations: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_mailpoet_automation_runs: Datos: 0.02MB + Índice: 0.08MB + Motor InnoDB
dxp_mailpoet_automation_run_logs: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
dxp_mailpoet_automation_run_subjects: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
dxp_mailpoet_automation_triggers: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_mailpoet_automation_versions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_mailpoet_custom_fields: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_mailpoet_dynamic_segment_filters: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_mailpoet_feature_flags: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_mailpoet_forms: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_mailpoet_log: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_mailpoet_mapping_to_external_entities: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_mailpoet_migrations: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_mailpoet_newsletters: Datos: 3.52MB + Índice: 0.05MB + Motor InnoDB
dxp_mailpoet_newsletter_links: Datos: 0.52MB + Índice: 1.73MB + Motor InnoDB
dxp_mailpoet_newsletter_option: Datos: 0.05MB + Índice: 0.02MB + Motor InnoDB
dxp_mailpoet_newsletter_option_fields: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_mailpoet_newsletter_posts: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_mailpoet_newsletter_segment: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_mailpoet_newsletter_templates: Datos: 11.52MB + Índice: 0.00MB + Motor InnoDB
dxp_mailpoet_scheduled_tasks: Datos: 0.41MB + Índice: 0.39MB + Motor InnoDB
dxp_mailpoet_scheduled_task_subscribers: Datos: 0.33MB + Índice: 0.17MB + Motor InnoDB
dxp_mailpoet_segments: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
dxp_mailpoet_sending_queues: Datos: 15.52MB + Índice: 0.03MB + Motor InnoDB
dxp_mailpoet_settings: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_mailpoet_statistics_bounces: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_mailpoet_statistics_clicks: Datos: 0.09MB + Índice: 0.08MB + Motor InnoDB
dxp_mailpoet_statistics_forms: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_mailpoet_statistics_newsletters: Datos: 0.34MB + Índice: 0.34MB + Motor InnoDB
dxp_mailpoet_statistics_opens: Datos: 0.22MB + Índice: 0.58MB + Motor InnoDB
dxp_mailpoet_statistics_unsubscribes: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
dxp_mailpoet_statistics_woocommerce_purchases: Datos: 0.05MB + Índice: 0.08MB + Motor InnoDB
dxp_mailpoet_stats_notifications: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
dxp_mailpoet_subscribers: Datos: 0.20MB + Índice: 0.39MB + Motor InnoDB
dxp_mailpoet_subscriber_custom_field: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_mailpoet_subscriber_ips: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_mailpoet_subscriber_segment: Datos: 0.14MB + Índice: 0.13MB + Motor InnoDB
dxp_mailpoet_subscriber_tag: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
dxp_mailpoet_tags: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_mailpoet_user_agents: Datos: 0.22MB + Índice: 0.05MB + Motor InnoDB
dxp_mailpoet_user_flags: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_options: Datos: 5.39MB + Índice: 0.19MB + Motor InnoDB
dxp_postmeta: Datos: 15.55MB + Índice: 12.03MB + Motor InnoDB
dxp_posts: Datos: 42.52MB + Índice: 1.02MB + Motor InnoDB
dxp_rank_math_404_logs: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_rank_math_analytics_objects: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_rank_math_internal_links: Datos: 0.09MB + Índice: 0.05MB + Motor InnoDB
dxp_rank_math_internal_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_rank_math_redirections: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_rank_math_redirections_cache: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_ref_plus_cntrlz: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_separar_cntrlz: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_smush_dir_images: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
dxp_termmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
dxp_terms: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
dxp_term_relationships: Datos: 0.11MB + Índice: 0.09MB + Motor InnoDB
dxp_term_taxonomy: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
dxp_union_prov_cntrlz: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_union_tra_cntrlz: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_usermeta: Datos: 2.52MB + Índice: 4.03MB + Motor InnoDB
dxp_users: Datos: 0.16MB + Índice: 0.14MB + Motor InnoDB
dxp_wc_admin_notes: Datos: 0.11MB + Índice: 0.00MB + Motor InnoDB
dxp_wc_admin_note_actions: Datos: 0.11MB + Índice: 0.02MB + Motor InnoDB
dxp_wc_category_lookup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_wc_customer_lookup: Datos: 0.13MB + Índice: 0.09MB + Motor InnoDB
dxp_wc_download_log: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
dxp_wc_orders: Datos: 0.02MB + Índice: 0.11MB + Motor InnoDB
dxp_wc_orders_meta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
dxp_wc_order_addresses: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
dxp_wc_order_coupon_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
dxp_wc_order_operational_data: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
dxp_wc_order_product_lookup: Datos: 0.31MB + Índice: 0.33MB + Motor InnoDB
dxp_wc_order_stats: Datos: 0.27MB + Índice: 0.25MB + Motor InnoDB
dxp_wc_order_tax_lookup: Datos: 0.08MB + Índice: 0.06MB + Motor InnoDB
dxp_wc_product_attributes_lookup: Datos: 0.05MB + Índice: 0.02MB + Motor InnoDB
dxp_wc_product_download_directories: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_wc_product_meta_lookup: Datos: 0.06MB + Índice: 0.09MB + Motor InnoDB
dxp_wc_rate_limits: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_wc_reserved_stock: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_wc_tax_rate_classes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_wfblockediplog: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_wfblocks7: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
dxp_wfconfig: Datos: 0.48MB + Índice: 0.00MB + Motor InnoDB
dxp_wfcrawlers: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_wffilechanges: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_wffilemods: Datos: 9.52MB + Índice: 0.00MB + Motor InnoDB
dxp_wfhits: Datos: 1.52MB + Índice: 0.23MB + Motor InnoDB
dxp_wfhoover: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_wfissues: Datos: 0.05MB + Índice: 0.06MB + Motor InnoDB
dxp_wfknownfilelist: Datos: 6.52MB + Índice: 0.00MB + Motor InnoDB
dxp_wflivetraffichuman: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_wflocs: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_wflogins: Datos: 0.20MB + Índice: 0.06MB + Motor InnoDB
dxp_wfls_2fa_secrets: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_wfls_settings: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_wfnotifications: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_wfpendingissues: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
dxp_wfreversecache: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_wfsnipcache: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
dxp_wfstatus: Datos: 0.14MB + Índice: 0.09MB + Motor InnoDB
dxp_wftrafficrates: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_wpforms_tasks_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_wpmailsmtp_debug_events: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_wpmailsmtp_tasks_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_wt_iew_action_history: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_wt_iew_cron: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_wt_iew_ftp: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_wt_iew_mapping_template: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
dxp_yoast_indexable: Datos: 0.33MB + Índice: 0.25MB + Motor InnoDB
dxp_yoast_indexable_hierarchy: Datos: 0.06MB + Índice: 0.05MB + Motor InnoDB
dxp_yoast_migrations: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
dxp_yoast_primary_term: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
dxp_yoast_seo_links: Datos: 0.17MB + Índice: 0.16MB + Motor InnoDB
dxp_yoast_seo_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB

### Post Type Counts ###

attachment: 1530
custom_css: 3
customize_changeset: 2
elementor_library: 1
gp_elements: 62
mailpoet_page: 1
nav_menu_item: 93
oembed_cache: 10
page: 80
post: 40
product: 54
product_variation: 199
product-feed: 1
revision: 955
seedprod: 1
shop_coupon: 36
shop_order: 1963
shop_order_refund: 8
wp_global_styles: 1
wp_navigation: 12
wp_show_posts: 1
wpcf7_contact_form: 9
wpmm_theme: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (19) ###

WPML Multilingual CMS: por OnTheGoSystems – 4.6.7
WPML SEO: por OnTheGoSystems – 2.1.0
AddFunc Head & Footer Code: por AddFunc – 2.3
Honeypot for Contact Form 7: por Nocean – 2.1.1
Contact Form 7 Multilingual: por OnTheGoSystems – 1.2.1
Contact Form 7: por Takayuki Miyoshi – 5.8.3
GTM4WP: por Thomas Geiger – 1.18.1
GenerateBlocks Pro: por Tom Usborne – 1.6.0
GenerateBlocks: por Tom Usborne – 1.8.2
GP Premium: por Tom Usborne – 2.3.2
MailPoet: por MailPoet – 4.36.0
Procesos cntrlz: por Centraliza – 0.1.1
Rank Math SEO: por Rank Math – 1.0.206
WooCommerce Redsys Gateway Light: por José Conti – 5.3.0
WooCommerce Multilingual & Multicurrency: por OnTheGoSystems – 5.2.1
Pay for Payment for WooCommerce: por Karolína Vyskočilová – 2.1.8
WooCommerce: por Automattic – 8.3.0
WP Mail SMTP: por WP Mail SMTP – 3.10.0
WPML String Translation: por OnTheGoSystems – 3.2.8

### Inactive Plugins (1) ###

Speed Optimizer: por SiteGround – 7.4.3

### Dropin Plugins (1) ###

maintenance.php: maintenance.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Base de la tienda: ❌ Página sin definir
Carrito: woocommerce/woocommerce-blocks#29 - /carrito/
Finalizar compra: ❌ La página no contiene el shortcode [woocommerce_checkout] o el bloque woocommerce/checkout.
Mi cuenta: woocommerce/woocommerce-blocks#30 - /mi-cuenta/
Términos y condiciones: woocommerce/woocommerce-blocks#2641 - /condiciones-de-compra/

### Theme ###

Name: GeneratePress Child
Version: 0.1
Author URL: 
Child Theme: ✔
Parent Theme Name: GeneratePress
Parent Theme Version: 3.3.1
Parent Theme Author URL: 
WooCommerce Support: ✔

### Templates ###

Overrides: /home/customer/www/staging2.example.com/public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/error.php
/home/customer/www/staging2.example.com/public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/notice.php
/home/customer/www/staging2.example.com/public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-virtual-downloadable
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-08-18 08:35:07 +02:00
Options: ✔
Notes: 179
Onboarding: completed

### MailPoet ###

Sending Method: PHPMail
Send all site's emails with: El método de envío por defecto de WordPress (por defecto)
Task Scheduler method: WordPress
Cron ping URL: https://www.staging2.example.com?mailpoet_router&endpoint=cron_daemon&action=ping

### Action Scheduler ###

Complete: 64
Oldest: 2023-10-10 14:10:13 +0200
Newest: 2023-11-16 21:26:43 +0100

Failed: 11
Oldest: 2023-06-06 13:41:23 +0200
Newest: 2023-11-17 12:06:34 +0100

Pending: 2
Oldest: 2023-11-17 21:07:55 +0100
Newest: 2023-11-17 21:07:55 +0100


### Status report information ###

Generated at: 2023-11-17 12:06:43 +01:00
`

**Comment by tarunvijwani** [comment]
@Juanmafortes I tried but couldn't replicate the behavior. I'd really appreciate it if you could share the screenshot or screen -recording of it. Thank you!

**Comment by mikejolley** [comment]
Hello,

First off, thanks for the feedback. Since we haven't heard back about this issue I will mark this closed but feel free to raise a new issue if it persists.

Regarding the stock in cross sells, this is a valid issue and is being tracked here:

https://github.com/woocommerce/woocommerce/issues/42326

Thanks
