### ISSUE TITLE
Adopt WooCommerce Monorepo Labels

### ISSUE THREAD

**Issue by ObliviousHarmony** [woocommerce/woocommerce-gutenberg-products-block#11800]
In order to simplify the transfer of issues we should change the labels in `woocommerce/woocommerce-blocks` to mirror the labels and structure present in the `woocommerce/woocommerce` monorepo. This should be done after https://github.com/woocommerce/woocommerce/issues/41490 that way it can take the full set of available labels into consideration.

**Comment by nerrad** [comment]
In most cases they already do. Woo blocks utilized the Woo Core labels tool to sync up on the standard label sets.

However, there are also a large number of block-specific labels that I'd like to see kept post-merge because they have helped with quickly scanning impacted blocks.

**Comment by ObliviousHarmony** [comment]
> In most cases they already do. Woo blocks utilized the Woo Core labels tool to sync up on the standard label sets.

Looking through the labels in [Blocks](https://github.com/woocommerce/woocommerce-blocks/labels) and the [Monorepo](https://github.com/woocommerce/woocommerce/labels) highlights a number of differences. I'd bet that the label synchronization happened before the labels changed for the monorepo?

Some specific things:

* `category:` labels aren't used in the monorepo and `focus:` labels are used instead.
* The monorepo has `needs:` prefixed labels but the blocks repo has `needs X` labels. There also seems to be differences in the granularity of, for instance, `needs feedback` vs `needs: author feedback`, `needs: design feedback`, `needs: developer feedback`, and `needs: triage feedback`.
* There's a `status: cherry-picked` label that doesn't have an analogue in our release process since that's all automated.
* I also see a number of naked labels that should be adjusted to fit on of the standard label prefixes or removed from the monorepo post-transfer.

It's worth noting that the GitHub API transfers all labels when it transfers an issue. Any labels that don't exist in the new repo are automatically created. It's much easier to rename the labels in the Blocks repo (or add new ones where appropriate!) before the transfer since it means we don't have to do anything more complicated like removing and adding labels to swap them.

> However, there are also a large number of block-specific labels that I'd like to see kept post-merge because they have helped with quickly scanning impacted blocks.

Would you be okay with a `focus:` label replacement? In the monorepo these labels are used to identify the area of focus for a PR and replaced `category` labels (and another type I think, there's a post somewhere). The other label sets that might be strange in the context of the monorepo are the `theme:` ones. There don't seem to be many things with these labels, do you have any thoughts on that?

One element of the monorepo was trying to create a label structure that can serve all of the projects in it without having hundreds of project-specific process labels.

---

I'd say that next steps for this task is the creation of a spreadsheet containing all of the current labels and a proposed re-mapping. We don't need to worry about labels that have no open issues or PRs associated with them since they won't be created in the monorepo through issue transfer.

Would this be something you'd be interested in @rrennick since you're knee-deep in the Monorepo triage process?

**Comment by nerrad** [comment]
There was a significant effort in 2020 to synchronize labels across _all Woo Repositories_ (p6q8Tx-1Sy-p2) and it looks like somewhere along the way the monorepo diverged from what was agreed there. There were significant reasons for doing this synchronization and have a label sync tool that teams could use but for whatever reason this hasn't been kept up.

**Comment by nerrad** [comment]
> Would you be okay with a focus: label replacement?

Not for the `block: *` or `block-type:*` labels. There are probably some `category` labels that could be transferred, but there are also some that fit better as a "category" or "type" rather than a "focus".

> I'd say that next steps for this task is the creation of a spreadsheet containing all of the current labels and a proposed re-mapping.

Agreed.

I also think it will be important to review any automations tied to specific label/labels and make sure those are considered.

**Comment by ObliviousHarmony** [comment]
> Not for the block: * or block-type:* labels. There are probably some category labels that could be transferred, but there are also some that fit better as a "category" or "type" rather than a "focus".

Just in case there's a misunderstanding about the purpose of the `focus:` prefix, it's meant to identify the specific area of a given project that an issue or PR relates to. For example, there are some labels like `focus: FSE`, `focus: refund`, and `focus: react marketplace`. This feels aligned with the purpose of the `block:` and similar prefixes. `block: add to cart form` would become `focus: add to cart form block` or something like that.

The same is often true of `category:` labels. For instance, `category: wc-settings` and `category: data-store` have analogues in the monorepo such as `focus: data-store`. All of the `category:` labels were spread between `type:` and `focus:` labels and still exist in some form in the monorepo for us to switch to.

> I also think it will be important to review any automations tied to specific label/labels and make sure those are considered.

Agreed.

**Comment by rrennick** [comment]
> Would this be something you'd be interested in @rrennick since you're knee-deep in the Monorepo triage process?

@nerrad I'd be okay with doing this. Would you prefer someone from the blocks repo doing this instead?

**Comment by rrennick** [comment]
> I also think it will be important to review any automations tied to specific label/labels and make sure those are considered.

The monorepo automations around labels are documented in pdV5qK-dY-p2.

**Comment by nerrad** [comment]
> Just in case there's a misunderstanding about the purpose of the focus: prefix, its meant to identify the specific area of a given project that an issue or PR relates to. For example, there are some labels like focus: FSE, focus: refund, and focus: react marketplace. This feels aligned with the purpose of the block: and similar prefixes. block: add to cart form would become focus: add to cart form block or something like that.

I disagree, I think there could be a `focus: blocks` label which describes the general focus of the work, but the `blocks*` labels are an explicit categorization for what block the work relates to that is more easily scannable. It's similar to the categorization separation in the Gutenberg repo as well. We've also colorized the labels distinctly within that group which contributes to the scannability of what an issue/PR involves. I think `focus:` labels should less specific. I'm going to direct that you _not_ make this change for the merge. We can take a more holistic look at labels post-merge (especially considering there may be changes that will help with overall PM changes). I'm okay with reviewing `category: *` labels before merging and at least aligning with how the mono-repo is doing those.

> @nerrad I'd be okay with doing this. Would you prefer someone from the blocks repo doing this instead?

If you're willing to do that @rrennick , that'd be great! Ping me when it's done and I'll have a couple folks from Woo Blocks and myself take a look and then we can go ahead and make the changes in the Woo Blocks repo ahead of the merge.

**Comment by rrennick** [comment]
> I think there could be a focus: blocks label which describes the general focus of the work, but the blocks* labels are an explicit categorization for what block the work relates to that is more easily scannable.

I agree. The team and focus labels usage should be common across all teams but after that teams should have the flexibility to use labels that work for them. In the case of the blocks:* labels, they will also help community contributors find relevant issues.

**Comment by ObliviousHarmony** [comment]
> We can take a more holistic look at labels post-merge (especially considering there may be changes that will help with overall PM changes).

Totally fine with this; it's certainly appropriate given the labels were created two years ago and we've certainly grown the number of folks working in the monorepo since then. Realistically speaking, my only pre-merge concern is removing labels with duplicate purposes.

> I'm okay with reviewing category: * labels before merging and at least aligning with how the mono-repo is doing those.

This seems the least contentious since there's more often than not a 1:1 mapping that exists in the monorepo already.

**Comment by rrennick** [comment]
I'm passing this on to @nerrad . I've created a list of existing label matches and potential changes for comparable labels.

**Comment by nerrad** [comment]
This has been completed.
