### ISSUE TITLE
Blocked checkout page

### ISSUE THREAD

**Issue by winstonsieck** [woocommerce/woocommerce-gutenberg-products-block#11840]
#### In main settings, I turned on the option for user to make an account with checkout. however, username and password fields still don't appear anywhere (they do show up in the classic version, so i'm probably just going forward with that).

**Comment by tarunvijwani** [comment]
@winstonsieck Thank you for reaching out. 

>Customization, edits for the checkout page seem pretty limited. I can select the "express checkout" section, but can't seem to remove it. It just sits there, blankly. Some billing fields can be removed, but not all(?) - I'd like to ditch more of them, really just leave name and email.

You can disable the express payment option under payment settings of any plugin. Here is the example for Stripe:

<img width="1413" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/11503784/0fbe5577-09f7-4062-9333-40fa611453b6">

For stripe, these settings are available at `/wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe&panel=methods&area=payment_requests`

>In main settings, I turned on the option for user to make an account with checkout. however, username and password fields still don't appear anywhere (they do show up in the classic version, so i'm probably just going forward with that).

Could you please share the screenshot of what you see in the classic version? 

You will need to logout from your browser to see the option to create an account on Checkout: 

<img width="718" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/11503784/700928e3-124b-4e19-886d-23cddf089cac">

**Comment by winstonsieck** [comment]
@tarunvijwani Thanks for your reply. I've now unselected the express checkouts for stripe, but the section still shows on the block checkout page. I also made sure  was logged out, but still didn't see the "create an account button." I tried clearing cache and different browser, as well to check those. Screenshots are attached to show how it looks with the block based checkout ("Checkout") and with the classic shortcode-based checkout (titled "myCheckout). I used checkout field editor plugin to remove some fields from the myCheckout form. I've also attached screenshots to confirm the settings.

![accounts-privacy-settings](https://github.com/woocommerce/woocommerce-blocks/assets/41486655/98bcd51d-e8e0-4785-bcab-ffd9d0fbfb60)
![block-checkout](https://github.com/woocommerce/woocommerce-blocks/assets/41486655/27520fc5-19d1-4259-b49a-9ee13fa1310b)
![mycheckout-create-account](https://github.com/woocommerce/woocommerce-blocks/assets/41486655/472f0527-0eb7-4c10-bf36-035f2a260f85)
![stripe-express-checkout-settings](https://github.com/woocommerce/woocommerce-blocks/assets/41486655/e752cc73-b058-41ed-ab6f-0c596ddfc152)

**Comment by tarunvijwani** [comment]
@winstonsieck Thank you for the screenshots. Can you also please send a copy of your WooCommerce system status report?

You can get it from your dashboard by going to WooCommerce—> Status.

**Comment by senadir** [comment]
If you have a live website to share, so we can debug from there directly.

**Comment by mikejolley** [comment]
Since this hasn't had any update for some time I'm going to mark it closed, but please reopen or post a new issue with the details requested if the issue persists.

Thanks!
