### ISSUE TITLE
Please change these ASAP

### ISSUE THREAD

**Issue by chi-chanuk** [woocommerce/woocommerce-gutenberg-products-block#11843]
## What do you think is missing from the Cart & Checkout blocks?
I'm using Astra and Elementor Pro. I face very annoying issues.
[Checkout page]
-> Coupon Code does not work. I cannot place coupon codes in the field and I cannot edit the field.
-> It messes up with my Astra button design. I had a border in my Astra but your plugin erases it.

I appreciate you guys developing and making it better.
Ayaka

**Comment by tarunvijwani** [comment]
@chi-chanuk Thank you for reaching out. I used the Astra theme, and the coupon code works fine. Here is the screen recording:

https://github.com/woocommerce/woocommerce-blocks/assets/11503784/84303d95-514e-484e-95c2-77437dd2332c

Could you please help us with the screenshot or screen recording to understand your issue better?

**Comment by mikejolley** [comment]
Since this hasn't had any updates in a while and we could not reproduce it, I will mark it closed. If the issue persists please open a new issue with more details.

Thanks
