### ISSUE TITLE
Replace deprecated button props `isPrimary`, `isSecondary`, `isTertiary` and `isLink`

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#11855]
With Gutenberg 14.2.0, the button props`isPrimary`, `isSecondary`, `isTertiary` and `isLink` have been deprecated in favour of `variant`. See https://github.com/WordPress/gutenberg/blob/trunk/packages/components/CHANGELOG.md#1420-2021-07-21 and  https://github.com/WordPress/gutenberg/pull/31713. 

Currently, we're still using all four deprecated button props:
- [`isPrimary`](https://github.com/search?q=repo%3Awoocommerce%2Fwoocommerce-blocks%20isPrimary&type=code) → should be replaced with `variant="primary"`
- [`isSecondary`](https://github.com/search?q=repo%3Awoocommerce%2Fwoocommerce-blocks+isSecondary&type=code) → should be replaced with `variant="secondary"`
- [`isTertiary`](https://github.com/search?q=repo%3Awoocommerce%2Fwoocommerce-blocks+isTertiary&type=code) → should be replaced with `variant="tertiary"`
- [`isLink`](https://github.com/search?q=repo%3Awoocommerce%2Fwoocommerce-blocks+isLink+language%3ATSX&type=code) → should be replaced with `variant="link"`

Reference:
- https://developer.wordpress.org/block-editor/reference-guides/components/button/#variant-primary-secondary-tertiary-link

**Comment by arsanyjoseph** [comment]
@nielslange I would like to work on this.
if you don't mind, please assign me.
Thanks

**Comment by nielslange** [comment]
Hello @arsanyjoseph 👋

Thanks for volunteering to work on this issue. I just assigned it to you. For any clarifications, please feel free to reach out.
