### ISSUE TITLE
Featured product block is not centered

### ISSUE THREAD

**Issue by Rebbun** [woocommerce/woocommerce-gutenberg-products-block#11868]
## Describe the bug

I have added a featured product block and it is not centered it moves to the left position.

## To reproduce

1. Go to 'Add block'
2. Click on 'Featured product'
3. Scroll down to 'View page'

## Expected behavior

Featured product block is centered

## Screenshots

[](https://i.ibb.co/r6XMf9n/featured-Product.png)

### WordPress (please complete the following information):

-   WordPress version: 6.4.1
-   Gutenberg version (if installed): [e.g. 12.0.0]
-   WooCommerce version: 8.3.0
-   WooCommerce Blocks version: 11.5.4
-   Site language: Spanish
-   Any other plugins installed:

### Desktop (please complete the following information):

-   OS: Windows 10
-   Browser: Firefox
-   Version: 119.0.1

### Smartphone (please complete the following information):

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. ]

**Comment by Rebbun** [comment]
`<a href="https://ibb.co/Lts6hK4">`

**Comment by Rebbun** [comment]
https://i.ibb.co/r6XMf9n/featured-Product.png

**Comment by roykho** [comment]
Hi @Rebbun - thanks for reporting however I am unable to replicate your issue. I am not certain where you've added the featured product block but in my example I created a new post with the products (beta) block on top and the featured product block on the bottom to try and mimic what I saw in your screenshot. This is what I am seeing on my end:

![file.png](https://github.com/woocommerce/woocommerce-blocks/assets/2132595/eda63ca3-8325-433c-bc32-0ac2e6d9ad19)

Could this perhaps be theme related styling? Can you try a default block theme like the Twenty Twenty Four?

**Comment by Rebbun** [comment]
I was just going to comment on which theme I was using. Twenty twenty

**Comment by Rebbun** [comment]
I have tried with envo storefront and storefront and with both it centers, but with twenty twenty it does not.

**Comment by Rebbun** [comment]
I'm new using wordpress, woocommerce... and it's probably because of some version thing, I'd love to know.

**Comment by roykho** [comment]
I would suggest you to use custom CSS to center align that block if you're using Twenty Twenty theme. For example:

`.wc-block-featured-product { margin: 0 auto; }`

**Comment by Rebbun** [comment]
It does not work or I did it wrong

**Comment by Rebbun** [comment]
![css](https://github.com/woocommerce/woocommerce-blocks/assets/144560933/aa44044f-e482-47d3-9ea9-c79dbb3e7bd4)

**Comment by kmanijak** [comment]
Hi @Rebbun,

Good news, I was able to reproduce the issue you described! Here's the PR with the fix: https://github.com/woocommerce/woocommerce-blocks/pull/12063, please follow it for further updates. 🙌 

Thanks!

**Comment by Rebbun** [comment]
Hi @kmanijak,

I am not able to find the exact path of the style.css inside the woocommerce files to make the change. I would appreciate it if you could help me.

**Comment by Rebbun** [comment]
![ruta](https://github.com/woocommerce/woocommerce-blocks/assets/144560933/f6c0a9db-a8dd-4d7d-ae57-f90c224a69ad)

**Comment by kmanijak** [comment]
@Rebbun, do I understand correctly you're looking for the file in your WordPress instance?

If so, you should look for:
`wp-content/plugins/woocommerce/packages/woocommerce-blocks/assets/js/blocks/featured-items/style.scss`

But to let you know, the fix I've made was just merged and will be available in upcoming WooCommerce Blocks and WooCommerce versions 🙌

**Comment by Rebbun** [comment]
@kmanijak Okay. Then I'll wait for the update to come out. I'll keep an eye out for it.
