### ISSUE TITLE
Basket Block

### ISSUE THREAD

**Issue by antonyjsmith** [woocommerce/woocommerce-gutenberg-products-block#11864]
## What do you like about the Cart & Checkout blocks?

Not much, it creates the illusions of customisation without actually allowing me to actually really customise anything. Most blocks are locked and don't have any styling options.

## What do you think is missing from the Cart & Checkout blocks?

Pretty much everything, I'm struggling to see the point of it in the current form.

**Comment by pmcpinto** [comment]
Hi Antony,

We appreciate your feedback. Can you provide more details about the customization options you'd like to have?
The team will thoroughly evaluate proposals for missing functionality based on key factors like feasibility, impact on the shopper experience, and priority compared to other roadmap initiatives. The clearer the use case, the better equipped we’ll be to address the requests. Thanks!

**Comment by mikejolley** [comment]
Since this hasn't had any updates in a while I'm going to mark it closed, but feel free to post back with more details or create a new issue with further details. 

Thanks
