### ISSUE TITLE
Store Customization > Enable DELETE request for the ai/patterns endpoint

### ISSUE THREAD

**Issue by nefeline** [woocommerce/woocommerce-gutenberg-products-block#11873]
Enable the DELETE request for the `ai/patterns` route within Store API to ensure all patterns have content reset to default. This goal can be achieved by simply deleting the post with the type `'patterns_ai_data'` from the database (when this post doesn't exist, patterns are rendered based on the info provided by the patterns dictionary instead - the `Patterns/dictionary.json` file).

The DELETE request is required to ensure that if, for some reason, AI is not available, the user can still be guided to the Assembler with the patterns rendering their native/default content.

**Comment by nefeline** [comment]
I am temporarily marking this issue as on hold until the proposed implementation is discussed with the engineering teams.

**Comment by gigitux** [comment]
We agreed on the current implementation! I removed the `on hold` label! I'm going to work on it!

**Comment by nefeline** [comment]
Updated the title and description to change the scope here based on @gigitux 's great suggestion: instead of creating a new `ai/patterns/reset` route, let's add a DELETE request to the existing `ai/patterns` route instead.
