### ISSUE TITLE
Add transition animation to view states on the All Products Block

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#1187]
I think it'd be worthwhile exploring some subtle transition on the view states of the All Products block.  I'm thinking specifically the transition between loading query results and the results displayed.  It's not _too_ bad right now, but there is a bit of a "jerky" feeling.

![Screen Recording 2019-11-15 at 03 48 PM](https://user-images.githubusercontent.com/1429108/68974784-8fbe9000-07bf-11ea-9999-57f5b1c486a7.gif)

**Comment by jwold** [comment]
Maybe I've been watching it too long, but it doesn't bother me as much now as I thought it would. 

A few suggestions:

1. We could add a fade in and out of the placeholder graphics, to force a slight delay and allow more time to load things. 
2. Try removing the placeholder graphics and see if the straight transition from showing one group of products to another would be clean enough. Here's an example that does this well: https://d.pr/i/JhhLBV (was too large to paste in here). 
3. Adding a transition animation (like you suggested) could be done well, here's how Apple does it: https://d.pr/i/fF9hSv

---

I'd be curious if options #1 or #2 above are feasible, if not I'm happy to go with option #3. Would just need to hunt down a decent transition animation (I have an idea where I could get one).

**Comment by nerrad** [comment]
I think it'd be worthwhile trying option 2.  I still like the idea of option 3 but maybe instead we could just have existing results have a mask applied that fades them slightly (similar pulsing effect as the current transition) and then swap out with the new results as they come in?
