### ISSUE TITLE
Add a control for the Product Categories block that allows showing the category image for each category

### ISSUE THREAD

**Issue by strarsis** [woocommerce/woocommerce-gutenberg-products-block#1188]
**Is your feature request related to a problem? Please describe.**
It would be nice to optionally show the category image for each product category.

**Describe the solution you'd like**
An option for categories block that allows showing the category image for each category.

**Describe alternatives you've considered**
Complicated filtering of frontend HTML + editor (if possible at all) or trying to find a different categories block, both being very suboptimal alternatives.

**Additional context**
Old, closed issue for adding product categories block: https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/212

**Comment by nerrad** [comment]
Hmm... it looks like this is already possible. Maybe it was added at some point to address this issue and the issue didn't get closed.

<img width="1295" alt="Image 2020-04-15 at 1 01 09 PM" src="https://user-images.githubusercontent.com/1429108/79365913-4d89ae00-7f19-11ea-9382-f53173707045.png">

If I'm wrong and this was created for some other reason than what is illustrated above, leave a comment and it can be reopened.
