### ISSUE TITLE
Product Gallery: block validation error when editing the Product Gallery template part

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#11882]
## Describe the bug

In `trunk`, I get an error when loading the Product Gallery template part.¡

## To reproduce

1. From your WordPress dashboard, go to Appearance > Themes. Select a block-based theme like "Twenty-twenty Three," "Twenty-twenty Four," etc.
2. On the left-hand side menu, click on Appearance > Editor.
3. Go to Patterns > General > Product Gallery.
4. Notice the block isn't loaded as there is invalid content: `This block contains unexpected or invalid content.` and there is this error in the console:

```
Block validation: Block validation failed for `woocommerce/product-gallery`.
Content generated by `save` function:

<div class="wp-block-woocommerce-product-gallery alignwide wc-block-product-gallery wc-block-product-gallery--has-next-previous-buttons-inside-image"></div>

Content retrieved from post body:

<div
		class="wp-block-woocommerce-product-gallery wc-block-product-gallery wc-block-product-gallery--has-next-previous-buttons-inside-image">
		

		
	</div>
```

## Expected behavior

The block should load correctly.

## Screenshots

![imatge](https://github.com/woocommerce/woocommerce-blocks/assets/3616980/7264888a-9e95-4928-9379-471b06c6822f)

### WordPress (please complete the following information):

-   WordPress version: 6.4.1
-   Gutenberg version (if installed): none
-   WooCommerce version: 8.3.1
-   WooCommerce Blocks version: 11.6.0-dev (`trunk` at the time of writing this)
-   Site language: English
-   Any other plugins installed: none

**Comment by wavvves** [comment]
Thanks for creating this @Aljullu 
~Is this a blocker for releasing 11.6.0?~

It's under experimental, so it's not a blocker.
Does not show in a production build:
<img width="1536" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/17236129/60de387f-6dd9-445a-a89d-d2d41fc62e08">
