### ISSUE TITLE
Single Product page. Wanting to use Gutenberg to create a product.

### ISSUE THREAD

**Issue by paaljoachim** [woocommerce/woocommerce-gutenberg-products-block#11886]
## Is your feature request related to a problem? Please describe.
Not able to use Gutenberg when creating a product.

## Describe the solution you'd like
I would like to use Gutenberg to create a product. As it would be a lot easier creating the layout one wants.
This means I would adjust the Single Product Template with various blocks. To create the template all the Single Product pages would use. Then when I create a new product I would see the template as a product page automatically added as a pattern with the various sections that are needed.

## Describe alternatives you've considered
Finding plugins that makes a single product page look more modern and nicer.

## Additional context
-

**Comment by Marc-pi** [comment]
yep, it's on the way
you can see the real status here https://github.com/woocommerce/woocommerce-blocks/discussions/10991 for classic needs
here i'm building a side dedicated plugin to manage my grouped product pages templates with blocks (currently, the single product contains nested templates, not everything is blockified), as listed in my issues. 
You can also hook some during that time
To manage template per product or category page, we have to wait for the new product editor

**Comment by paaljoachim** [comment]
This is interesting. I came across a blog post etc to where it is possible to turn on the Gutenberg editor for the Products page. In the backend going to WooCommerce -> Settings -> Advanced -> Features ->  and clicking to turn on "New product editor". 

Here I would like to see a predefined pattern/Single Product Template locked in place to where one fills in the sections. As it would then look closer to what the frontend view would be. That means similar to the Template but not editable. If a user tried to edit the locked template a notice could show up asking if the user wants to edit the template. Making the process more similar to how Full Site Editing works today in relation to editing pages <-> templates.

**Comment by gigitux** [comment]
@paaljoachim Thanks for opening this issue!

>  In the backend going to WooCommerce -> Settings -> Advanced -> Features -> and clicking to turn on "New product editor".

You can read more about the new product editor experience [here](https://developer.woo.com/2023/06/28/introducing-a-brand-new-product-creation-experience-powered-by-blocks/).


> Here I would like to see a predefined pattern/Single Product Template locked in place to where one fills in the sections. As it would then look closer to what the frontend view would be.


Currently, the new product editor has a "preview" button to check how the product will look on the frontend:

https://github.com/woocommerce/woocommerce-blocks/assets/4463174/875ea9b8-c19f-44fe-97c7-d575659b848b


> That means similar to the Template but not editable. If a user tried to edit the locked template a notice could show up asking if the user wants to edit the template.

Can you clarify this?

**Comment by paaljoachim** [comment]
Hi @gigitux Luigi

I made this discussion:
Creating a product using the Block Editor - thinking content pattern -
https://github.com/woocommerce/woocommerce-blocks/discussions/11929

A short summary.
In Gutenberg one can go between Template <-> Page. An improvement is being worked on.
Here is a comment in regards to locking template parts. Which could also be very helpful for locking the Single Product template. https://github.com/WordPress/gutenberg/issues/55025#issuecomment-1827191187

It would be helpful to automatically insert the Single Product pattern/template into a product page. Showing the template editable areas. Title, description, image etc etc. User fills in the needed areas and saves the product. User can not edit the inserted template only fill out the needed areas to add the product information.

**Comment by gigitux** [comment]
Thanks, @paaljoachim! I'm going to close this issue!
