### ISSUE TITLE
can't access the global window.wc.blocksCheckout from the third party theme

### ISSUE THREAD

**Issue by mohammaddanish-cedcoss** [woocommerce/woocommerce-gutenberg-products-block#11881]
I was using the woocommerce- block to do some modifications to the existing functionality. but it seems like the window global is not access through the third-party theme.
Somebody please help !!!!!

**Comment by tarunvijwani** [comment]
@mohammaddanish-cedcoss Thank you for reaching out! Could you please provide more details like what are you trying to achieve and which theme you're using?

I have tested it on `Blocksy By creativethemeshq` theme and it worked fine for me:
![image](https://github.com/woocommerce/woocommerce-blocks/assets/11503784/50d6325b-fa13-4d6e-b492-a41cf8bbc072)

**Comment by senadir** [comment]
Make sure whatever script you're loading has a dependeny on the right scripts, in this case, `wc-blocks-checkout` for it to load an excute after the original script has loaded.

**Comment by mohammaddanish-cedcoss** [comment]
ok, I found out the issue. I was accessing the element before loading files on the site, I have added some js code in the script for the document ready

**Comment by senadir** [comment]
Just noting that if you're using a build system that leverages `@wordpress/scripts` or one of WooCommerce build process templates, this should work out of the box. otherwise, anything you use from `wp.` or `wc.` need to be defined as a dependncy.
