### ISSUE TITLE
Reverting to classic cart block prevent removing last item in cart table

### ISSUE THREAD

**Issue by wpchannel** [woocommerce/woocommerce-gutenberg-products-block#11889]
## Describe the bug

Issue with reverting to classic cart feature.

## To reproduce

Use cart block in page editor, switch block to classic cart block using the new CTA to do. This CTA appears in a notice if a plugin is not compatible with blocks. The cart page on front is working fine except that removing last item is not working. Ajax requests are correctly done but the table is not updating.

Removing HTML comments in page and adding back the shortcode [woocommerce_cart] solve this issue.

<img width="323" alt="Capture d’écran 2023-11-22 à 15 16 17" src="https://github.com/woocommerce/woocommerce-blocks/assets/7568562/cadace6b-8fd4-4850-b3d5-f93385e648b5">
<img width="1200" alt="Capture d’écran 2023-11-22 à 15 16 25" src="https://github.com/woocommerce/woocommerce-blocks/assets/7568562/7f840564-e058-475d-8299-5e4d6c935713">

## Expected behavior

The classic cart should work like shortcode.

### WordPress (please complete the following information):

-   WordPress version: 6.4.1
-   Gutenberg version (if installed): [e.g. 12.0.0]
-   WooCommerce version: 8.3.1
-   WooCommerce Blocks version: [e.g. 7.0.0]
-   Site language: english, french
-   Any other plugins installed: none

## Additional context

Test locally and on a stagging environment. No plugins installed, Storefront default theme.

**Comment by mikejolley** [comment]
Thanks for the report. There is a missing `woocommerce` classname that the scripts use to update the cart page. This is fixed here: https://github.com/woocommerce/woocommerce-blocks/pull/11919

This will be part of the 11.6.1 fix release as well.
