### ISSUE TITLE
Single Product Template. Switch Product Image Gallery to image or video block.

### ISSUE THREAD

**Issue by paaljoachim** [woocommerce/woocommerce-gutenberg-products-block#11885]
## Is your feature request related to a problem? Please describe.
Additional options for the Product Image Gallery.

## Describe the solution you'd like
Product Image Gallery. Be able to switch it to an image or video. Adjusting the size. Think Gutenberg Gallery block but with some added features.

## Describe alternatives you've considered
None yet.

## Additional context
-

**Comment by gigitux** [comment]
Hey @paaljoachim! Thanks for opening this issue! We are working on a new block to improve the gallery. You can read more about this by checking https://github.com/woocommerce/woocommerce/issues/42095.

I will close this issue, but feel free to comment and re-open it!

**Comment by paaljoachim** [comment]
Thank you @gigitux Luigi!
