### ISSUE TITLE
Reorganise storybook to ensure all exported components are available in the "External components" section.

### ISSUE THREAD

**Issue by opr** [woocommerce/woocommerce-gutenberg-products-block#11908]
Following on from our effort to [Move components into the components package](https://github.com/woocommerce/woocommerce-blocks/issues/11661) and to add Storybook entries for them, we now need to do some housekeeping on Storybook.

All components we export via `@woocommerce/blocks-components` should be in their own folder on Storybook.

To solve this issue, find the stories for each component in `packages/components/**/stories/*.tsx` and ensure the story title is:

`External Components/{Component}` like so: https://github.com/woocommerce/woocommerce-blocks/blob/bf046d24b9870e1bcb8af2726c6d606ce26e5688/packages/components/panel/stories/index.stories.tsx#L13

**Comment by arsanyjoseph** [comment]
I would like to contribute to this 
Would you please assign me ?

**Comment by opr** [comment]
@arsanyjoseph sure! I've assigned you to this task. Please let me know if you need any help.

To get storybook running you need to run `npm run storybook` on the command line then go to `localhost:6006`

By the way if you're not already in the [WooCommerce Community Slack](https://woo.com/community-slack/) then feel free to join and ping me there too.

Thanks for offering to help!

**Comment by arsanyjoseph** [comment]
@opr I created a [PR ](https://github.com/woocommerce/woocommerce-blocks/pull/11910)
kindly review it and let me know if any further changes required.
