### ISSUE TITLE
Code represent block for latest Checkout and Cart

### ISSUE THREAD

**Issue by msyahrizan** [woocommerce/woocommerce-gutenberg-products-block#11915]
Hi, I'm curious to know what code represents the equivalent block for displaying the latest Checkout and Cart? 
Example the `<!-- wp:latest-posts /-->` block represents a block for displaying a list of the latest posts.

**Comment by mikejolley** [comment]
Hi @msyahrizan 

You can look this up by inserting the cart/checkout block into a page and then using the code view:

![Screenshot 2023-11-23 at 11 57 39](https://github.com/woocommerce/woocommerce-blocks/assets/90977/1db885ef-2371-4829-a317-837875ba0d50)

Cart and checkout use Inner Blocks so the markup is longer than a single tag, but here is cart for reference:

<details>
<pre><code>
&#x3C;!-- wp:woocommerce/cart {&#x22;className&#x22;:&#x22;wc-block-cart&#x22;} --&#x3E;
&#x3C;div class=&#x22;wp-block-woocommerce-cart alignwide is-loading wc-block-cart&#x22;&#x3E;&#x3C;!-- wp:woocommerce/filled-cart-block --&#x3E;
&#x3C;div class=&#x22;wp-block-woocommerce-filled-cart-block&#x22;&#x3E;&#x3C;!-- wp:woocommerce/cart-items-block --&#x3E;
&#x3C;div class=&#x22;wp-block-woocommerce-cart-items-block&#x22;&#x3E;&#x3C;!-- wp:woocommerce/cart-line-items-block --&#x3E;
&#x3C;div class=&#x22;wp-block-woocommerce-cart-line-items-block&#x22;&#x3E;&#x3C;/div&#x3E;
&#x3C;!-- /wp:woocommerce/cart-line-items-block --&#x3E;

&#x3C;!-- wp:woocommerce/cart-cross-sells-block --&#x3E;
&#x3C;div class=&#x22;wp-block-woocommerce-cart-cross-sells-block&#x22;&#x3E;&#x3C;!-- wp:heading {&#x22;fontSize&#x22;:&#x22;large&#x22;} --&#x3E;
&#x3C;h2 class=&#x22;wp-block-heading has-large-font-size&#x22;&#x3E;You may be interested in&#x2026;&#x3C;/h2&#x3E;
&#x3C;!-- /wp:heading --&#x3E;

&#x3C;!-- wp:woocommerce/cart-cross-sells-products-block --&#x3E;
&#x3C;div class=&#x22;wp-block-woocommerce-cart-cross-sells-products-block&#x22;&#x3E;&#x3C;/div&#x3E;
&#x3C;!-- /wp:woocommerce/cart-cross-sells-products-block --&#x3E;&#x3C;/div&#x3E;
&#x3C;!-- /wp:woocommerce/cart-cross-sells-block --&#x3E;&#x3C;/div&#x3E;
&#x3C;!-- /wp:woocommerce/cart-items-block --&#x3E;

&#x3C;!-- wp:woocommerce/cart-totals-block --&#x3E;
&#x3C;div class=&#x22;wp-block-woocommerce-cart-totals-block&#x22;&#x3E;&#x3C;!-- wp:woocommerce/cart-order-summary-block --&#x3E;
&#x3C;div class=&#x22;wp-block-woocommerce-cart-order-summary-block&#x22;&#x3E;&#x3C;!-- wp:woocommerce/cart-order-summary-heading-block --&#x3E;
&#x3C;div class=&#x22;wp-block-woocommerce-cart-order-summary-heading-block&#x22;&#x3E;&#x3C;/div&#x3E;
&#x3C;!-- /wp:woocommerce/cart-order-summary-heading-block --&#x3E;

&#x3C;!-- wp:woocommerce/cart-order-summary-coupon-form-block --&#x3E;
&#x3C;div class=&#x22;wp-block-woocommerce-cart-order-summary-coupon-form-block&#x22;&#x3E;&#x3C;/div&#x3E;
&#x3C;!-- /wp:woocommerce/cart-order-summary-coupon-form-block --&#x3E;

&#x3C;!-- wp:woocommerce/cart-order-summary-subtotal-block --&#x3E;
&#x3C;div class=&#x22;wp-block-woocommerce-cart-order-summary-subtotal-block&#x22;&#x3E;&#x3C;/div&#x3E;
&#x3C;!-- /wp:woocommerce/cart-order-summary-subtotal-block --&#x3E;

&#x3C;!-- wp:woocommerce/cart-order-summary-fee-block --&#x3E;
&#x3C;div class=&#x22;wp-block-woocommerce-cart-order-summary-fee-block&#x22;&#x3E;&#x3C;/div&#x3E;
&#x3C;!-- /wp:woocommerce/cart-order-summary-fee-block --&#x3E;

&#x3C;!-- wp:woocommerce/cart-order-summary-discount-block --&#x3E;
&#x3C;div class=&#x22;wp-block-woocommerce-cart-order-summary-discount-block&#x22;&#x3E;&#x3C;/div&#x3E;
&#x3C;!-- /wp:woocommerce/cart-order-summary-discount-block --&#x3E;

&#x3C;!-- wp:woocommerce/cart-order-summary-shipping-block --&#x3E;
&#x3C;div class=&#x22;wp-block-woocommerce-cart-order-summary-shipping-block&#x22;&#x3E;&#x3C;/div&#x3E;
&#x3C;!-- /wp:woocommerce/cart-order-summary-shipping-block --&#x3E;

&#x3C;!-- wp:woocommerce/cart-order-summary-taxes-block --&#x3E;
&#x3C;div class=&#x22;wp-block-woocommerce-cart-order-summary-taxes-block&#x22;&#x3E;&#x3C;/div&#x3E;
&#x3C;!-- /wp:woocommerce/cart-order-summary-taxes-block --&#x3E;&#x3C;/div&#x3E;
&#x3C;!-- /wp:woocommerce/cart-order-summary-block --&#x3E;

&#x3C;!-- wp:woocommerce/cart-express-payment-block --&#x3E;
&#x3C;div class=&#x22;wp-block-woocommerce-cart-express-payment-block&#x22;&#x3E;&#x3C;/div&#x3E;
&#x3C;!-- /wp:woocommerce/cart-express-payment-block --&#x3E;

&#x3C;!-- wp:woocommerce/proceed-to-checkout-block --&#x3E;
&#x3C;div class=&#x22;wp-block-woocommerce-proceed-to-checkout-block&#x22;&#x3E;&#x3C;/div&#x3E;
&#x3C;!-- /wp:woocommerce/proceed-to-checkout-block --&#x3E;

&#x3C;!-- wp:woocommerce/cart-accepted-payment-methods-block --&#x3E;
&#x3C;div class=&#x22;wp-block-woocommerce-cart-accepted-payment-methods-block&#x22;&#x3E;&#x3C;/div&#x3E;
&#x3C;!-- /wp:woocommerce/cart-accepted-payment-methods-block --&#x3E;&#x3C;/div&#x3E;
&#x3C;!-- /wp:woocommerce/cart-totals-block --&#x3E;&#x3C;/div&#x3E;
&#x3C;!-- /wp:woocommerce/filled-cart-block --&#x3E;

&#x3C;!-- wp:woocommerce/empty-cart-block --&#x3E;
&#x3C;div class=&#x22;wp-block-woocommerce-empty-cart-block&#x22;&#x3E;&#x3C;!-- wp:heading {&#x22;textAlign&#x22;:&#x22;center&#x22;,&#x22;className&#x22;:&#x22;with-empty-cart-icon wc-block-cart__empty-cart__title&#x22;} --&#x3E;
&#x3C;h2 class=&#x22;wp-block-heading has-text-align-center with-empty-cart-icon wc-block-cart__empty-cart__title&#x22;&#x3E;Your cart is currently empty!&#x3C;/h2&#x3E;
&#x3C;!-- /wp:heading --&#x3E;

&#x3C;!-- wp:paragraph {&#x22;align&#x22;:&#x22;center&#x22;} --&#x3E;
&#x3C;p class=&#x22;has-text-align-center&#x22;&#x3E;&#x3C;a href=&#x22;https://store.local/shop/&#x22;&#x3E;Browse store&#x3C;/a&#x3E;&#x3C;/p&#x3E;
&#x3C;!-- /wp:paragraph --&#x3E;

&#x3C;!-- wp:separator {&#x22;className&#x22;:&#x22;is-style-dots&#x22;} --&#x3E;
&#x3C;hr class=&#x22;wp-block-separator has-alpha-channel-opacity is-style-dots&#x22;/&#x3E;
&#x3C;!-- /wp:separator --&#x3E;

&#x3C;!-- wp:heading {&#x22;textAlign&#x22;:&#x22;center&#x22;} --&#x3E;
&#x3C;h2 class=&#x22;wp-block-heading has-text-align-center&#x22;&#x3E;New in store&#x3C;/h2&#x3E;
&#x3C;!-- /wp:heading --&#x3E;

&#x3C;!-- wp:woocommerce/product-new {&#x22;columns&#x22;:4,&#x22;rows&#x22;:1} /--&#x3E;&#x3C;/div&#x3E;
&#x3C;!-- /wp:woocommerce/empty-cart-block --&#x3E;&#x3C;/div&#x3E;
&#x3C;!-- /wp:woocommerce/cart --&#x3E;
</code></pre>
</details>

Hope that helps.

**Comment by msyahrizan** [comment]
Thank you for your help mikejolley
