### ISSUE TITLE
No sale products shown when products are "variable"

### ISSUE THREAD

**Issue by smallstar67** [woocommerce/woocommerce-gutenberg-products-block#11934]
The woocommerce product blocks do not list variable products that are on sale.  They also do not shown the "on sale" badge when these sale products are manually placed in a normal product listing block.

**Comment by gigitux** [comment]
Hi @smallstar67,
Thanks for opening this issue! I'm not able to replicate it!

`Hoodie` is a variable product and:
- the sale badge is rendered.
- the product is visible in the Products block.

Can you give us more details to reproduce the issue?

![image](https://github.com/woocommerce/woocommerce-blocks/assets/4463174/d0e7088d-405d-428c-84cc-fd08d1a5fd58)

**Comment by smallstar67** [comment]
Hi Luigi,
Well, here is a page of items live on sale now using the "on sale"
woocommerce block, all items are on sale, and no sale page is displayed in
the block.
Black Friday, Small Business Saturday, Cyber Monday Sale (usanunchaku.com)
<https://usanunchaku.com/black-friday/>


*--HK Bowman *



*"What is the difference between genius and stupidity? Genius has limits."
- Albert Einstein. *

**Comment by gigitux** [comment]
I'm not able to access this website:

![image](https://github.com/woocommerce/woocommerce-blocks/assets/4463174/e39f5c86-b681-4cc3-b720-67fdacd3bf01)


On my local WordPress instance, I tested the `On Sale Products` block and I'm able to see variation products:

![image](https://github.com/woocommerce/woocommerce-blocks/assets/4463174/a1f5e98b-63ee-4633-85c2-858c9bbc05c8)

Can you share some reproduction steps? Thanks!

**Comment by smallstar67** [comment]
what country are you in, i can release the firewall block.

Basically the woocommerce blocks for items on sale will "say" there are no
items for sale, even though there are.  The alternative is to populate a
normal products block with the items on sale, but while they are listed in
this product block, none have the sale badge displayed in the block.
It has functioned like this for years.

*--HK Bowman *



*"What is the difference between genius and stupidity? Genius has limits."
- Albert Einstein. *

**Comment by gigitux** [comment]
Can you try to disable all the plugins except for WooCommerce Blocks and WooCommerce?

**Comment by smallstar67** [comment]
Unfortunately no, we can't do that.  It's the busiest day of the year for
sales in America, we can't turn stuff off.

*--HK Bowman *



*"What is the difference between genius and stupidity? Genius has limits."
- Albert Einstein. *

**Comment by smallstar67** [comment]
I might also add that we have tested the same scenario with "simple"
products and those have the badge shown and they also are listed in the "%
on Sale Products" block.

*--HK Bowman *



*"What is the difference between genius and stupidity? Genius has limits."
- Albert Einstein. *

**Comment by gigitux** [comment]
I'm unable to successfully reproduce the bug. This doesn't mean there isn't something happening, but it appears to be specific to your environment. Until we can reproduce this, there isn't anything we can do to fix. For that reason, I'm going to close this issue, but please do leave a comment if you have additional information that you think will help us reproduce the issue. We will re-open if we're able to replicate.

You can start the investigation by reading the[ Self Service guide](https://woo.com/document/woocommerce-self-service-guide/).

Thanks again for your report!
