### ISSUE TITLE
Product Gallery: Address the edge case when Product Image is not set but Product gallery images are

### ISSUE THREAD

**Issue by danieldudzic** [woocommerce/woocommerce-gutenberg-products-block#11940]
## Describe the bug

Currently in the following situation:
<img width="302" alt="Edit_product_“Beanie_with_Logo”_‹_newproductgallery_—_WordPress" src="https://github.com/woocommerce/woocommerce-blocks/assets/905781/5a565461-67be-4126-a867-4475a726077e">

The Product Gallery block will:
- Hide the Thumbnails
- Still output the Next/Previous Buttons and the Pager
- The first Large Image image will be blank

![RMMeTuyymN](https://github.com/woocommerce/woocommerce-blocks/assets/905781/412c69b6-b6f6-4415-8888-fc027bbb5edb)

## To reproduce

1. With a block theme, open `Appearance > Editor`.
2. Open `Templates > Single Product`.
3. Select `Convert to Blocks` if you are using the Classic Templates.
4. Add the `Product Gallery` block.
5. Edit a product and make sure the Product Image is not set but some Product gallery images are.
6. Notice the broken behavior on the front end.

**Comment by danieldudzic** [comment]
@jarekmorawski @roykho In the event that the Product Image is not set but some Product Gallery images are present, which of the following behaviors should be preferred?:
- Display an empty Large Image.
- Display an image Placeholder as the Large Image.
- Hide the Thumbnails (and Pager and Next/Prev buttons) altogether.
- Set the Large Image to the first of the Product gallery images and display Thumbnails, Pager and Next/Prev buttons normally.

FYI: The legacy WooCommerce Single Product Gallery hides the thumbnails and pagination and just displays the placeholder:

<img width="1055" alt="Moto_Guzzi_v7_–_newproductgallery" src="https://github.com/woocommerce/woocommerce-blocks/assets/905781/f37b5b14-7a15-4b3a-99c5-92f1faa1f855">

**Comment by jarekmorawski** [comment]
Great question. Thanks for keeping an eye out for such details. I'd display the image placeholder as well as the Thumbnails and the Prev/Next buttons. It's a temporary solution because, in the new product editing UX, the large image is set automatically.
