### ISSUE TITLE
Checkout > Company field not visible on front (visible from Editor) + phone mandatory flag issue (on front)

### ISSUE THREAD

**Issue by Marc-pi** [woocommerce/woocommerce-gutenberg-products-block#11955]
## Describe the bug

The company field was activated through the Delivery Block options
But it is not visible within the checkout page (on front), even if set as a mandatory field
The field is only visible on Editor Side.

I guess it is related to recent changes see https://github.com/woocommerce/woocommerce-blocks/issues/11583
I can see @senadir is working on https://github.com/woocommerce/woocommerce/issues/42773
I ping @mikejolley who worked on this recently also

![image](https://github.com/woocommerce/woocommerce-blocks/assets/919332/7a21ad5c-12da-498c-be9f-1e03875406bf)

![image](https://github.com/woocommerce/woocommerce-blocks/assets/919332/dc118735-382e-4e20-91af-202ff27db1ce)

## To reproduce

1. Set Company field as activated within the Delivery Block
2. Add a product in your cart
3. Go to the checkout page
4. See the missing Company field

## Expected behavior

The activated field must be visible on both sides (front / editor)

## Screenshots

see above

## Environment

- WP 6.4.1
- Woo 8.3.1
- WooBlocks 11.6.1
- Gutenberg 17.1.2
- TT3 theme
- Tested with Firefox
- PHP 8.1.23

**Comment by Marc-pi** [comment]
Another related bug : 
You can also see from the screenshots that the `mandory` phone field is `optional` on front !!!

**Comment by senadir** [comment]
Hey @Marc-pi! I'm not able to reproduce this. 

<img width="1218" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/6165348/7f6cf716-3e5c-45a2-b3ea-00ac04677b60">

<img width="695" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/6165348/fe51c706-1cf0-4213-a7a7-4d73f5cfcee1">

Can you share your checkout page content?

<img width="315" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/6165348/c0fe03bf-fba7-4030-bd63-88c995e04e39">

It should give you something like this:

```html
<!-- wp:woocommerce/checkout {"showCompanyField":true,"requirePhoneField":true} -->
<div class="wp-block-woocommerce-checkout alignwide wc-block-checkout is-loading"><!-- wp:woocommerce/checkout-fields-block -->
<div class="wp-block-woocommerce-checkout-fields-block"><!-- wp:woocommerce/checkout-express-payment-block -->
<div class="wp-block-woocommerce-checkout-express-payment-block"></div>
<!-- /wp:woocommerce/checkout-express-payment-block -->

<!-- wp:woocommerce/checkout-contact-information-block -->
<div class="wp-block-woocommerce-checkout-contact-information-block"></div>
<!-- /wp:woocommerce/checkout-contact-information-block -->

<!-- wp:woocommerce/checkout-shipping-method-block -->
<div class="wp-block-woocommerce-checkout-shipping-method-block"></div>
<!-- /wp:woocommerce/checkout-shipping-method-block -->

<!-- wp:woocommerce/checkout-pickup-options-block -->
<div class="wp-block-woocommerce-checkout-pickup-options-block"></div>
<!-- /wp:woocommerce/checkout-pickup-options-block -->

<!-- wp:woocommerce/checkout-shipping-address-block -->
<div class="wp-block-woocommerce-checkout-shipping-address-block"></div>
<!-- /wp:woocommerce/checkout-shipping-address-block -->

<!-- wp:woocommerce/checkout-billing-address-block -->
<div class="wp-block-woocommerce-checkout-billing-address-block"></div>
<!-- /wp:woocommerce/checkout-billing-address-block -->

<!-- wp:woocommerce/checkout-shipping-methods-block -->
<div class="wp-block-woocommerce-checkout-shipping-methods-block"></div>
<!-- /wp:woocommerce/checkout-shipping-methods-block -->

<!-- wp:woocommerce/checkout-payment-block -->
<div class="wp-block-woocommerce-checkout-payment-block"></div>
<!-- /wp:woocommerce/checkout-payment-block -->

<!-- wp:woocommerce/checkout-order-note-block -->
<div class="wp-block-woocommerce-checkout-order-note-block"></div>
<!-- /wp:woocommerce/checkout-order-note-block -->

<!-- wp:woocommerce/checkout-terms-block -->
<div class="wp-block-woocommerce-checkout-terms-block"></div>
<!-- /wp:woocommerce/checkout-terms-block -->

<!-- wp:woocommerce/checkout-actions-block -->
<div class="wp-block-woocommerce-checkout-actions-block"></div>
<!-- /wp:woocommerce/checkout-actions-block --></div>
<!-- /wp:woocommerce/checkout-fields-block -->

<!-- wp:woocommerce/checkout-totals-block -->
<div class="wp-block-woocommerce-checkout-totals-block"><!-- wp:woocommerce/checkout-order-summary-block -->
<div class="wp-block-woocommerce-checkout-order-summary-block"><!-- wp:woocommerce/checkout-order-summary-cart-items-block -->
<div class="wp-block-woocommerce-checkout-order-summary-cart-items-block"></div>
<!-- /wp:woocommerce/checkout-order-summary-cart-items-block -->

<!-- wp:woocommerce/checkout-order-summary-coupon-form-block -->
<div class="wp-block-woocommerce-checkout-order-summary-coupon-form-block"></div>
<!-- /wp:woocommerce/checkout-order-summary-coupon-form-block -->

<!-- wp:woocommerce/checkout-order-summary-subtotal-block -->
<div class="wp-block-woocommerce-checkout-order-summary-subtotal-block"></div>
<!-- /wp:woocommerce/checkout-order-summary-subtotal-block -->

<!-- wp:woocommerce/checkout-order-summary-fee-block -->
<div class="wp-block-woocommerce-checkout-order-summary-fee-block"></div>
<!-- /wp:woocommerce/checkout-order-summary-fee-block -->

<!-- wp:woocommerce/checkout-order-summary-discount-block -->
<div class="wp-block-woocommerce-checkout-order-summary-discount-block"></div>
<!-- /wp:woocommerce/checkout-order-summary-discount-block -->

<!-- wp:woocommerce/checkout-order-summary-shipping-block -->
<div class="wp-block-woocommerce-checkout-order-summary-shipping-block"></div>
<!-- /wp:woocommerce/checkout-order-summary-shipping-block -->

<!-- wp:woocommerce/checkout-order-summary-taxes-block -->
<div class="wp-block-woocommerce-checkout-order-summary-taxes-block"></div>
<!-- /wp:woocommerce/checkout-order-summary-taxes-block --></div>
<!-- /wp:woocommerce/checkout-order-summary-block --></div>
<!-- /wp:woocommerce/checkout-totals-block --></div>
<!-- /wp:woocommerce/checkout -->
```

**Comment by senadir** [comment]
It's likely that whatever country you have might be hiding the field via its locale settings?

**Comment by senadir** [comment]
Another likely thing is that you're probably editing in the wrong place, Checkout might still be in the template but you're editing the Checkout page, you will need to reset your Checkout template.

**Comment by Marc-pi** [comment]
> you're probably editing in the wrong place, Checkout might still be in the template but you're editing the Checkout page, you will need to reset your Checkout template.

wow ! i'm sure that's it. I'm editing the page set as checkout, that makes use of the checkout block.
I'll check the checkout template (maybe it is a partial template / i'll have a look)
there's something to fine IMHO tune to warn the final (novice) user, to prevent such a feedback
i'll test this afternoon and give my findings
thanks for your help

**Comment by senadir** [comment]
Yes, I raised this issue internally.

Initially, the template would contain its own Checkout block, and we would hide the Checkout page.

This caused some confusing in our testing, so we switched to templates just using the page content, this might not have migrated well for existing merchants, but should work fine for any new merchant. 

So if you're a new merchant, editing in the template and page is the same.

**Comment by Marc-pi** [comment]
@senadir just to better understand, i've to delete my checkout page and recreate a new one ?
or ? My pre-prod website is up since july, so it's not a fresh new merchant website

**Comment by senadir** [comment]
If you're using a block theme, you need to go to Editor -> Templates -> Page: Checkout and reset customizations.

**Comment by Marc-pi** [comment]
well, it fixed !
@senadir maybe there's a need to write down something on this in release notes, or force reset the template in next release, no ?

**Comment by Marc-pi** [comment]
and thx for your help on this

**Comment by senadir** [comment]
I've looped in the team members who worked on this and they can decide the best next steps.
