### ISSUE TITLE
Checkout > Phone label > localization > translated value is not used

### ISSUE THREAD

**Issue by Marc-pi** [woocommerce/woocommerce-gutenberg-products-block#11970]
## Describe the bug

At checkout, the missing phone number text is not valid
The FR translation was done, but the translated term "phone" is used

![image](https://github.com/woocommerce/woocommerce-blocks/assets/919332/4306996b-1bd2-4471-9ea9-635444999dd0)
![image](https://github.com/woocommerce/woocommerce-blocks/assets/919332/66477992-9a25-4683-ac0a-0a6be359eb3d)
![image](https://github.com/woocommerce/woocommerce-blocks/assets/919332/0677affa-3dfd-450a-970f-2b1340cbaa33)

See https://translate.wordpress.org/projects/wp-plugins/woo-gutenberg-products-block/stable/fr/default/ (FYI, i'm waiting for my translation to be merged, i maintain those, but the term used in the template for this issue are already all translated). So it is an error at code level.

## To reproduce

1. Go to checkout 
2. Go to checkout
3. Let empty the mandatory field 
4. Observe the message display : "phone" is not translated

## Expected behavior

The Phone term must be translatable (seems that's the case), but the translation effectively used

![image](https://github.com/woocommerce/woocommerce-blocks/assets/919332/94dbb40a-d8e7-4998-943c-05fa5a9808da)

## Environment

- WP 6.4.1
- Woo 8.3.1
- WooBlocks 11.6.1
- Gutenberg 17.1.2
- TT3 theme
- Tested with Firefox
- PHP 8.1.23

**Comment by senadir** [comment]
Hey @Marc-pi ! Thank you for raising this. As you said, the error is a generic one that combines the label.

Recently (https://github.com/woocommerce/woocommerce-blocks/pull/11651 ), the field moved locations in JS, so this might affect its translation. The recent update should have fixed that, at least in french

<img width="631" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/6165348/f5e3bc25-4ec2-49be-b568-693cf5af269b">

For me, it seems to be working fine, with WooCommerce Blocks installed or not.

I will close this issue for now, do let me know if you're still seeing this.

**Comment by Marc-pi** [comment]
@senadir do i need to clear something to see the change in FR ? (like the one we made on another subject about the company field at checkout ?). I do not have any cache running.

**Comment by senadir** [comment]
Just make sure your translation is up to date.
