### ISSUE TITLE
All Products: changing filters should reset pagination

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#1198]
**To Reproduce**

1. In a page with an _All Products_ block and a _Filter Products by Attribute_ block go to the last page in _All Products_.
2. Activate one of the attributes that you know will display less pages.
3. Notice the pagination buttons disappear and you only see placeholders.

**Expected behavior**
You should see the first page of results with that attribute filter.

**Screenshots**
![Peek 2019-11-18 17-36](https://user-images.githubusercontent.com/3616980/69071439-3017ed00-0a2a-11ea-9078-f66706f7e985.gif)

**Comment by nerrad** [comment]
This is a tricky one because it's related to the query string for page being persisted to and used from, the url.
