### ISSUE TITLE
Incompatibility flow - decrease modal width

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-gutenberg-products-block#11994]
**Description:** can we decrease the width in the confirmation modal displayed in the Cart flow? It seems to be too wide.

<img width="1920" alt="Captura de ecrã 2023-11-29, às 18 36 33" src="https://github.com/woocommerce/woocommerce-blocks/assets/3380168/629ce56e-7d8f-4176-833f-fec48412bde1">

**Comment by pmcpinto** [comment]
cc @jarekmorawski

**Comment by jarekmorawski** [comment]
Agreed. The modal should be 480 px wide or less.
