### ISSUE TITLE
[Checkout blocks] Change the link in the Feedback box

### ISSUE THREAD

**Issue by ralucaStan** [woocommerce/woocommerce-gutenberg-products-block#11990]
## Is your feature request related to a problem? Please describe.
<img width="285" alt="Captura de ecrã 2023-11-16, às 16 53 08" src="https://github.com/woocommerce/woocommerce-blocks/assets/3380168/0733d7a4-29c8-4e42-970a-61b95cb58622">

The `Give us your feedback` link points to the WooCommerce Blocks repo. We need to change the link to point to the WooCommerce repo discussions: to a new discussion in the Checkout flow category, with the label `type: product feedback`.

woocommerce/woocommerce#42091 will introduce the CES prompt, but before that gets implemented we need to replace the link. 

Timeline:
- WooCommerce 8.4 will have the current feedback box with the link pointing to the WooCommerce repo
- With WooCommerce 8.5 will replace the link with a button for CES (#11808 )

## Describe the solution you'd like
- change the link to `https://github.com/woocommerce/woocommerce/discussions/new?category=checkout-flow&labels=type%3A+product%20feedback`

## Describe alternatives you've considered
Another option would be to remove the feedback box altogether until we implement CES

**Comment by nerrad** [comment]
Let's change the link to create a topic in the discussion board (within the appropriate category if possible).

**Comment by wavvves** [comment]
> Let's change the link to create a topic in the discussion board (within the appropriate category if possible).

@nerrad It is 🙂, `https://github.com/woocommerce/woocommerce/discussions/new?category=<category-here>`

We probably need to create the category first (btw, am I the only one to think that GH discussions are so simplified, that they actually turn complex?)

**Comment by ralucaStan** [comment]
These are the [current categories ](https://github.com/woocommerce/woocommerce/discussions)

<img width="360" alt="Screenshot 2023-11-30 at 14 51 40" src="https://github.com/woocommerce/woocommerce-blocks/assets/1628454/d6b04378-cfde-4799-a68c-66f1f0ae8e1a">

I propose we create a new category.
We can be specific `The Checkout blocks` or general, `The Checkout flow`. @nerrad, what do you think? I'd go with the second one.

**Comment by nerrad** [comment]
> @nerrad It is 🙂, https://github.com/woocommerce/woocommerce/discussions/new?category=<category-here>

Oh, great! I was going by the link Raluca pasted in the description of the issue.

> We probably need to create the category first

Yes, something like `Checkout Flow` would be good. If possible, it'd be good to also automatically assign a `type: product feedback` label to the discussion to help differentiate those types of discussion threads. 

Also, there is an [airtable automation](https://airtable.com/appra4zMRgiGscWB7/wflHjh1F8iFT92Z7v) that will need updated post-merge.

**Comment by ralucaStan** [comment]
> Also, there is an [airtable automation](https://airtable.com/appra4zMRgiGscWB7/wflHjh1F8iFT92Z7v) that will need updated post-merge.

@pmcpinto mentioned we'll be collecting the feedback once we have CES in place. Pedro, did you mean this automation?

**Comment by nerrad** [comment]
To be clear, that automation is already collecting feedback coming into the designated GH discussions category.

**Comment by ralucaStan** [comment]
This is the link `https://github.com/woocommerce/woocommerce/discussions/new?category=checkout-flow&labels=type%3A+product%20feedback`. I'll update the ticket description

**Comment by wavvves** [comment]
> To be clear, that automation is already collecting feedback coming into the designated GH discussions category.

@nerrad I'm seeing some pretty interesting things around this, it seems that automation runs from feedback left on the default FeedbackPrompt URL (correct me if I'm wrong here, assuming from the logic on the airtable automation)

```ts
const FeedbackPrompt = ( {
	text,
	title = __( 'Feedback?', 'woo-gutenberg-products-block' ),
	url = 'https://ideas.woocommerce.com/forums/133476-woocommerce?category_id=384565',
}: FeedbackPromptProps ) => {
(...)
```

It gets overwritten for Cart&Checkout, Product Query, Product Collection and LegacyFeedbackPrompt (which seems not to be used at all)

Cart&Checkout and Legacy use the link we want to replace. The other two use airtable links.
I'd say:

1. Change the URL on `CartCheckoutFeedbackPrompt` as planned
2. Keep the airtable automation and the default URL (although I don't see `FeedbackPrompt` being used directly anywhere)
3. Delete the unused `LegacyFeedbackPrompt`

```ts
export const CartCheckoutFeedbackPrompt = () => (
	<FeedbackPrompt
		text={ __(
			'We are currently working on improving our cart and checkout blocks to provide merchants with the tools and customization options they need.',
			'woo-gutenberg-products-block'
		) }
		url="https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/new?template=--cart-checkout-feedback.md"
	/>
);

export const LegacyFeedbackPrompt = () => (
	<FeedbackPrompt
		text={ __(
			'We are working on a better editing experience that will replace classic blocks. Keep an eye out for updates!',
			'woo-gutenberg-products-block'
		) }
		url="https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/new?template=--classic-block-feedback.md"
	/>
);

export const ProductQueryFeedbackPrompt = () => (
	<FeedbackPrompt
		text={ __(
			'Thanks for trying out the Products block! Help us make it better by sharing your feedback.',
			'woo-gutenberg-products-block'
		) }
		title={ __( 'Share your feedback!', 'woo-gutenberg-products-block' ) }
		url={ 'https://airtable.com/shrFX5FAqmCY6hVYI' }
	/>
);

export const ProductCollectionFeedbackPrompt = () => (
	<FeedbackPrompt
		text={ __(
			'Thanks for trying out the Product Collection block! Help us make it better by sharing your feedback.',
			'woo-gutenberg-products-block'
		) }
		title={ __( 'Share your feedback!', 'woo-gutenberg-products-block' ) }
		url={ 'https://airtable.com/shrqsMSDPvAKoY99u' }
	/>
);
```

I'll link the PR shortly.

**Comment by ralucaStan** [comment]
@wavvves 
Indeed the `FeedbackPrompt` component has a default value for the `url` prop: `https://ideas.woocommerce.com/forums/133476-woocommerce?category_id=384565` <- this link is invalid, it's redirecting me to the homepage/my dashboard when logged in. It's not problem because we don't use the component without specifying a value for the URL. But we should remove the default value for the component and mark the `url` prop as required

**Comment by wavvves** [comment]
I closed this by mistake, I followed up with another PR 👍🏼
