### ISSUE TITLE
Cart & Checkout blocks tech spike

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-gutenberg-products-block#1199]
**Questions:** *
- What are the largest modules of work and potential pain points? 
- What do we need to take into consideration on v1 that doesn't block extensibility in the future?
- Can we reduce technical complexity or the mvp scope to improve development time?
- Does it make more sense to break the work or try to tackle both blocks at the same time?
- How long it will take to implement the two blocks?

*- it would be great to have feedback on each question at the end of the cycle, even if it's not 100% accurate or complete.

**Links:**
- Master Thread - p6q8Tx-137-p2
- Project Kick-off - p6q8Tx-154-p2
- Cart & Checkout MVP - p6q8Tx-1gJ-p2
- Usability Research - p6q8Tx-1ks-p2
- Followup Design - p6q8Tx-1lH-p2

**Comment by nerrad** [comment]
I've created some issues that I think identify some specific exploration points that will help us answer the questions in this epic.  Each of the issues can be used as a launching pad for filling out information we need (whether that involves writing some example code, or reviewing existing code and documenting what's available, or gathering responses from other sources).  View these issues as a starting point, not all-encompassing.

**Comment by pmcpinto** [comment]
Thanks! I imagine that the cart and checkout are going to be some of the most difficult blocks to tackle and probably they're going to be two of the biggest blocks that exist in the market.
