### ISSUE TITLE
Our Plugin does not work with WooCommerce Blocks anymore

### ISSUE THREAD

**Issue by ivanlouis** [woocommerce/woocommerce-gutenberg-products-block#12001]
## Describe the bug
We provide a payment plugin for WooCommerce for zahls.ch (see https://wordpress.org/plugins/zahls-ch-payment-gateway/). Since a few weeks, customers report that the blocks checkout does not work anymore with our plugin. I cannot find the bug.

Please excuse me, if this is not the correct report type.

## To reproduce

1. Install our zahls.ch plugin (https://wordpress.org/plugins/zahls-ch-payment-gateway/)
2. Go to the checkout section. If blocks is activated, the checkout is not shown anymore

### WordPress (please complete the following information):
-   WordPress version: 6.4
-   WooCommerce version: 8.3.1
-   WooCommerce Blocks version: 11.6.1

**Comment by ralucaStan** [comment]
Hi @ivanlouis. Did your plugin work with the Checkout blocks before and it stopped working? If so, after which version did your plugin stop working?

Currently, it's up to extension developers to add support for the new checkout flow offered via the Cart and Checkout Blocks. We have some [documentation for Third-party developers](https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs#third-party-developers) and some [Developer Resources](https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs#developer-resources) available to help with their integration efforts.

**Comment by senadir** [comment]
Hey @ivanlouis 

I Checked the plugin code just to confirm @ralucaStan's report. While it seems you have the integration in place, it seems to reference nonexisting files, your plugin does not include the `build` folder, something must have messed this up in your build/deployment process so please check that.

<img width="313" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/6165348/4dae2f74-2c50-4049-a967-a77918ff89d7">

The plugin also seems to comment out the script loading part

<img width="851" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/6165348/8a98549b-c34c-4be8-ae85-a69c35211130">


As such, I'd advise you to figure out what's wrong, get a working full copy, and reach out again if it's a problem from our side.
