### ISSUE TITLE
Homepage templates tech spike

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-gutenberg-products-block#1200]
Questions: *

How long it will take to create 1-3 templates with the existing blocks?
Can we introduce any intuitive way to select a template within the block editor?
How long it would take to release some atomic blocks (like the add to cart button and the price) as individual blocks?

*- it would be great to have feedback on each question at the end of the cycle, even if it's not 100% accurate or complete.

**Links:**
- Master Thread - p6q8Tx-1gb-p2
- Homepage templates: Initial design research - p6riRB-4Xa-p2
- Homepage template discovery: Initial research - p6q8Tx-1iE-p2

**Comment by nerrad** [comment]
I've created a couple issues that I think will help guide the exploration that will enable us to somewhat answer these questions (or at least give us a better picture for what we can tackle in the next cycle - or plan for future cycles).
