### ISSUE TITLE
Add some features to customize buttons

### ISSUE THREAD

**Issue by devygram** [woocommerce/woocommerce-gutenberg-products-block#12023]
## What do you like about the Cart & Checkout blocks?
Cart & Checkout button are not suitable to my theme (Flatsome) they are not optimized.
![Screenshot 2023-12-04 122813](https://github.com/woocommerce/woocommerce-blocks/assets/84488784/e89692ef-c6c1-428b-85ef-6c9704b63e2c)
When i hover / click on button it changing color to black as button color so please help.

**Comment by tarhi-saad** [comment]
Hi, @shopeclub! 👋 Thank you for reaching out! WordPress global styles define the button's colors. Your theme or a plugin you have installed may be applying these styles. To verify this, you can do a conflict check:

1. Briefly switch to the [Storefront](https://www.woocommerce.com/storefront/) or [Twenty Twenty-Four](https://wordpress.org/themes/twentytwentyfour/) theme.
2. Deactivate all plugins, keeping only WooCommerce active.
3. Check the hover style of the Cart and Checkout buttons

If the problem disappears after these steps, it indicates a conflict with one of the deactivated plugins or themes. To pin down the culprit, reactivate your plugins one by one and test after each. This process will help identify the conflicting plugin. For a step-by-step guide on performing a conflict test, [click here](https://docs.woocommerce.com/document/how-to-test-for-conflicts/).

You can also apply your custom CSS to fix this issue using the following CSS selectors:

```css
.wp-element-button:hover, .wp-block-button__link:hover { /* Your styles here */ }

.wp-element-button:visited, .wp-block-button__link:visited { /* Your styles here */ }
```
