### ISSUE TITLE
Inconsistent background color for pagination in 2020 theme

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#1203]
**Describe the bug**
Pagination seems to have a background in the frontend but doesn’t have any background in the editor.

**To Reproduce**

1. install 2020 theme
2. see a page with All Products
3. Pagination has a background
4. See the color

**Expected behavior**
Pagination buttons shouldn’t have a background color

**Screenshots**
<img width="696" alt="Screen Shot 2019-11-19 at 9 22 59 AM" src="https://user-images.githubusercontent.com/6165348/69130696-3f8e4900-0ab1-11ea-8ea4-6f681f480bb5.png">

**How to fix**
this code in 2020 is overriding the block styling, even though this selector seems more generic than `.wc-block-pagination-page` because of the `:not` coupled with a class, we can enter a specificity war with the theme or we can submit a patch to 2020.

```css
button:not(.toggle) {
    background-color: #cd2653;
}
```

**Comment by Aljullu** [comment]
I'm reopening this issue because I think it wasn't fixed (at least I can still reproduce it in `master`).

**Comment by senadir** [comment]
Yeah I guess @nerrad mistook it for #1204, I don’t think it makes sense to wait for TwentyTwenty to fix it, I will push a fix and report to TwentyTwenty

**Comment by nerrad** [comment]
oops, sorry about that.  I saw the merge notification for #1241 in this issue and didn't realize that was a merge into another branch.
