### ISSUE TITLE
Add field EIN/SSN like in US ora NIP like in Poland

### ISSUE THREAD

**Issue by WEBTEC-PK** [woocommerce/woocommerce-gutenberg-products-block#12044]
## What do you like about the Cart & Checkout blocks?
It is realy clear view. Intuitive.

## What do you think is missing from the Cart & Checkout blocks?
I think it is neccesery to ad extra field to chec if custome would like to get Invoice oraz not. If yes should be displayed for him extra fields to insert TAX number like EIN/SSN or NIP like in poland.

**Comment by senadir** [comment]
Adding custom fields is something we're actively working on. We will share it publicly once it's ready.

Follow this issue and discussion to be updated on that.

https://github.com/woocommerce/woocommerce-blocks/discussions/11173
https://github.com/woocommerce/woocommerce/issues/42769
