### ISSUE TITLE
How to disable billing address?

### ISSUE THREAD

**Issue by ikamboon** [woocommerce/woocommerce-gutenberg-products-block#12062]
Hi, how to disable billing address in woocommerce checkout block?

**Comment by tarhi-saad** [comment]
Hi, @ikamboon! 👋 Thank you for reaching out! 🙌 Can you explain why you need to disable the billing address?

**Comment by ikamboon** [comment]
> Hi, @ikamboon! 👋 Thank you for reaching out! 🙌 Can you explain why you need to disable the billing address?

Because I am used for online ticket booking, I want to make it convenient for users so that they don't need to fill in too much information.

**Comment by senadir** [comment]
A billing address is used for taxes and payment methods, so it's not advisable to fully remove it.

Your ticketing/booking platform can fill the customer session, which in turn will show the address from as a title card.

<img width="616" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/6165348/fb64f72d-5dac-44a7-91e4-90557ebf6b24">

**Comment by mikejolley** [comment]
Agreed with the above; billing is required at the very least for taxes and payment gateways. With auto-complete and the collapsed view for returning customers this shouldn't be too much of a burden.

Since this has been answered I will mark it closed. Thanks.
