### ISSUE TITLE
Exploration - Checkout Block: What components are needed?

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#1208]
### What will be the components needed for the MVP?

Keeping in mind the MVP will not have inner blocks initially, we still need to identify the logical units in the main block.  So this exploration should map out the various components and what we already have vs what needs created.

**Comment by nerrad** [comment]
As a part of this exploration, would be good to see what is being done in this package: https://github.com/Automattic/wp-calypso/tree/master/packages/composite-checkout

**Comment by Aljullu** [comment]
In a similar way as I listed the components I think will be needed for the Cart block (#1207), here it goes the list for the Checkout block. They are also listed with their name and the proposed path.

This exploration doesn't consider if some of these components should rely on other packages as a base (the discussion is ongoing in the Cart block exploration issue).

## Express checkout
![image](https://user-images.githubusercontent.com/3616980/69612910-ec784100-1030-11ea-9c7d-0068a7d4d8c6.png)
* ExpressCheckout (`/base/components/checkout/express-checkout`)
* ExpressCheckoutButton (`/base/components/checkout/express-checkout-button`)

## Form
![image](https://user-images.githubusercontent.com/3616980/69613108-41b45280-1031-11ea-8248-fbe43067b172.png)
* CheckoutForm (`/base/components/checkout/form`)
* CheckoutFormStep (`/base/components/checkout/form-step`)
	* CheckoutContactInformation (`/base/components/checkout/contact-information`)
![image](https://user-images.githubusercontent.com/3616980/69613175-69a3b600-1031-11ea-8431-3dce302befc1.png)
	* CheckoutShippingAddress (`/base/components/checkout/shipping-address`)
![image](https://user-images.githubusercontent.com/3616980/69613199-732d1e00-1031-11ea-81fd-124aef038fe9.png)
		* ShippingAddressPlaceholder (`/base/components/checkout/shipping-address-placeholder`)
![image](https://user-images.githubusercontent.com/3616980/69613279-9ce64500-1031-11ea-8004-3417925e47b0.png)
	* CheckoutBillingAddress (`/base/components/checkout/billing-address`)
![image](https://user-images.githubusercontent.com/3616980/69614145-ebe0aa00-1032-11ea-9dd4-691ffb1dd389.png)
	* CheckoutShippingOptions (`/base/components/checkout/shipping-options`)
![image](https://user-images.githubusercontent.com/3616980/69613217-7de7b300-1031-11ea-8452-9833911f75ed.png)
		* CheckoutOrderNotesCheckbox (`/base/components/checkout/order-notes-checkbox`)
	* CheckoutPaymentMethod (`/base/components/checkout/payment-method`)
![image](https://user-images.githubusercontent.com/3616980/69613245-88a24800-1031-11ea-8fde-03978b368a53.png)
		* PaymentMethodTabs (`/base/components/checkout/payment-method-tabs`)
		* PaymentMethodTab (`/base/components/checkout/payment-method-tab`)
		* PaymentMethodPlaceholder (`/base/components/checkout/payment-method-placeholder`)
![image](https://user-images.githubusercontent.com/3616980/69613303-a4a5e980-1031-11ea-9061-8814e85c85da.png)
* BackLink (defined in #1207)
![image](https://user-images.githubusercontent.com/3616980/69614419-614c7a80-1033-11ea-8160-af3811c6d6b7.png)
* PlaceOrderButton (`/base/components/checkout/place-order-button`)
![image](https://user-images.githubusercontent.com/3616980/69614399-598cd600-1033-11ea-8137-d854fecfa1c3.png)

## Form components
* Checkbox (`/base/components/checkbox`)
* Select (`/base/components/select`)
* TextInput (`/base/components/text-input`)
* TextInputTooltip (`/base/components/text-input-tooltip`)
* PhoneInput (`/base/components/phone-input`)
* CountryInput (`/base/components/country-input`)
* CountyInput (`/base/components/county-input`)
* CreditCardInput (`/base/components/credit-card-input`)

## Other
* Separator (`/base/components/separator`)
![image](https://user-images.githubusercontent.com/3616980/69612935-f7cb6c80-1030-11ea-8e6d-4bc6108b181b.png)

## Sidebar
![image](https://user-images.githubusercontent.com/3616980/69613576-0fefbb80-1032-11ea-92a8-54ef00045c90.png)
* CheckoutSidebar (`/base/components/checkout/sidebar`)
	* All contents are already defined as Cart Block components.

**Comment by nerrad** [comment]
Thanks @Aljullu for the excellent work in mapping out this block, I was able to use it to break things down into workable issues 🎉 I'm going to close this issue now that we have things mapped out for working on.
