### ISSUE TITLE
Add a sale badge block for single product page

### ISSUE THREAD

**Issue by derridHeidegger** [woocommerce/woocommerce-gutenberg-products-block#12093]
## Is your feature request related to a problem? Please describe.
as of now the sale badge is included with the product image. it is not flexibile. 

## Describe the solution you'd like
it should be a seperate block so one can use it and put it everywhere one need it

**Comment by kmanijak** [comment]
Hi @derridHeidegger! Thanks for creating this issue.

> it should be a seperate block so one can use it and put it everywhere one need it

I'd like to let you know that this topic has been raised already and was in some early explorations. Here's the issue that touches on this subject: https://github.com/woocommerce/woocommerce/issues/42478. To keep our backlog clean I'll go ahead and close your issue in favor of https://github.com/woocommerce/woocommerce/issues/42478 which has more details and context. Please follow it for further updates 🙏 .

Please be aware that it doesn’t fit in with our current priorities for the project. This doesn’t mean what you are suggesting isn’t a good idea or doesn’t make sense (we agree and explore that idea ourselves!) – it’s just that we have limited time to work on various projects. Meanwhile, don’t be alarmed if you don’t see any activity on this issue for a while.
