### ISSUE TITLE
Cart Block REST API: What routes/endpoints are needed?

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#1213]
In this exploration, a review should be taken of our existing endpoints and routes and clarify what we have vs what we think we'll need.

**Comment by haszari** [comment]
See #1312 for some initial exploration from @mikejolley

**Comment by haszari** [comment]
> review our existing endpoints and routes and clarify what we have

We have two APIs (that I'm aware of):

1. [WooCommerce Core rest API](https://woocommerce.github.io/woocommerce-rest-api-docs) - in core plugin 
1. WooCommerce Blocks plugin [Store API](https://github.com/woocommerce/woocommerce-gutenberg-products-block/tree/master/src/RestApi/StoreApi#cart-api) – in this repo/plugin

The core API doesn't have any `/cart` endpoint (based on a quick search/review of the docs).

The blocks store API has a `/cart` endpoint. This is a good starting point for us – it has things like order total, line items etc.

> what we think we'll need

To explore what we need, I looked at the designs for the new checkout and the existing checkout, and what we could add to the existing blocks store API `/cart` endpoint. In other words, I'm assuming that extending the store API is a good solution; we may need to explore alternatives.

I also assumed a particular kind of API – we call one API endpoint, and it returns all the data we need to render a cart. This is in contrast to the ideals of REST (there are lots of entities within a shopping cart - products, coupons, shipping methods), and some of the explorations in #1312.

I went with this approach partly for simplicity, but also to try to focus on the needs of the proposed UI (to avoid scope creep). Having all the data in one response will also hopefully avoid the risk of different parts of the UI showing different "versions" of cart data.

Here's an overview of the structure that would be returned from all `/cart` endpoints - e.g. `GET /cart`.

```
currency
item_count
items_subtotal
order_total
shipping_method
items[]
items[].quantity
items[].item_price
items[].subtotal
items[].stock_count
items[].show_low_stock_label
items[].discount_amount
coupons[]
coupons[].coupon_code
coupons[].type
coupons[].discount_percent
coupons[].discount_fixed
coupons[].product_id
shipping_methods[]
shipping_methods[].name
shipping_methods[].shipping_cost
payment_methods[]
payment_methods[].name
payment_methods[].icon_image
```

As part of this proposal I've added some endpoints to update particular areas of the cart - e.g. apply a coupon, update quantity for a line item. This is not particularly RESTful – but I think it's a pragmatic compromise to keep us focused on shipping an improved cart experience. 

Some examples – all these would return the full cart object (as above) in the response:

```http
// apply a coupon
PUT /cart/order/coupons?coupon_code=blackfriday2019
// remove a coupon
DELETE /cart/order/coupons?coupon_code=blackfriday2019
// update quantity for an order item
PUT /cart/order/items/:key?quantity=4
// remove an order item entirely
DELETE /cart/order/items/:key
// select a different shipping method
PUT /cart/order/shipping_method?method=slow_free_shipping
```

**Comment by mikejolley** [comment]
@haszari Some intial comments without doing my own deep dive:

- Shipping and payment methods are not unique to the cart - the checkout block also needs this, and there may be use cases for other reuse in the future?
- Does `/cart/order/` make sense if no order exists yet?
- `// select a different shipping method` Why can't selected things be stored local? We only need to transfer this when creating the order right?
- If we do need to store selections, maybe a dedicated endpoint isn't needed, we can PUT to the main endpoint and validate when the order is created to prevent tampering of values.
- I think storing coupons on the cart makes more sense than on an order to begin. We currently have `/cart/items`, so we could have `/cart/coupons` too, and expose that on the main `/cart/` endpoint too if needed.

> The blocks store API has a /cart endpoint. This is a good starting point for us – it has things like order total, line items etc.

This is the API we're adding too. It's the one which doesn't require auth and is aimed at customers.

**Comment by mikejolley** [comment]
@nerrad When I created https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/1312 I didn't see this issue. Should we close in favour?

**Comment by nerrad** [comment]
yup 👍
