### ISSUE TITLE
Query string ignored for all products block

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#1246]
I'm not sure where this was introduced, but I noticed while testing the All Products block on master today that the query string is ignored and reset.   So if you have `?product_page=3`, when you load the page, there will be a network request for that page, but immediately after initial render it gets reset to `?product_page=1`.  So we have a variation of the paging problem happening still.

Ultimately, I think this will involve refactoring how the query_string functionality works and lifting the pagination state up (see #1126 )

**Comment by senadir** [comment]
This was introduced on #1202, removing this code fixes it
https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/237ea7d2b8cfb5df6a193ecb789620b8e6e53766/assets/js/base/components/product-list/index.js#L113-L119

But it will render that fix invalid so we should see a way around it cc @nerrad

**Comment by nerrad** [comment]
Right, ultimately the fix is going to involve finishing #1126 (I added the link to the pull description).

**Comment by nerrad** [comment]
I'm going to close this in light of #1287 removing the `withQueryStringValues` implementation (so this bug won't surface) and #1275 being put on hold.
