### ISSUE TITLE
Add to Cart in new All Products Block does not update the page shopping cart on the same page

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#1247]
Reported  in a comment here: p90Yrv-1mS-p2

When adding a product to a cart using the add to cart button in the product grid, it's not updating the page shopping cart elsewhere on the page.  The item _is_ added to the cart, it's just not updating the view (Example using Storefront theme).

![Screen Recording 2019-11-22 at 06 11 PM](https://user-images.githubusercontent.com/1429108/69466808-8dc27700-0d53-11ea-98f7-365761225c46.gif)

**Comment by mikejolley** [comment]
@nerrad We'd have to fire ajax requests for (shudder) the jquery based widget to update. There is an issue logged to build a cart block which could use wp.data directly. Just not sure when that is prioritised for, or how useful it can be as a block rather than a widget at this point.

**Comment by nerrad** [comment]
Yup I figured that would be the case.  We may need to do some tweaks to the jquery based widget too so the blocks can trigger it to do an update (if that's not already present).  I don't think we can convert it to a full block yet until navigation is a content area for blocks.
