### ISSUE TITLE
Hand-picked Products: first row has one less column than requested in Safari

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#1249]
**Describe the bug**
When I set the columns property of the `Hand-picked Products` block, in Safari, the front end displays one less item than expected (in the first row). 

**To Reproduce**
WordPress 5.3, WooCommerce 3.8, Storefront 2.5.3, WooCommerce Blocks `master`, using woo sample product data.

1. New page, add a new `Hand-picked Products` block.
2. Select 3 products.
3. Accept default block settings, in particular 3 columns.
4. Publish page.

Should see first column with one less product than expected.

Note that this appears to just affect first row, possibly due to `:before` style using extra space in the container.

**Expected behavior**
Correct number of columns as specified in block.

**Screenshots**
<img width="1547" alt="Screen Shot 2019-11-25 at 1 17 00 PM" src="https://user-images.githubusercontent.com/4167300/69504293-6c959c80-0f86-11ea-8a79-a1f67379171a.png">

**WordPress:**

* Core version: 5.3
* Gutenberg version (if installed): plugin not installed
* WooCommerce version: 3.8.0
* WooCommerce Blocks version: 2.6.0-dev `master` branch 355daa0295571886414ebe87249db19bfbe75b46
* Site language: English US
* Any other plugins installed: WooCommerce Admin 0.22, WordPress Importer

**Desktop:**

* OS: macOS
* Browser: Safari
* Version: 13.0.3 (15608.3.10.1.4)

**Comment by nerrad** [comment]
I wonder if this is related to the work done in #1066 (is your screen size on one of the breakpoints @haszari ?

**Comment by haszari** [comment]
> I wonder if this is related to the work done in #1066. Is your screen size on one of the breakpoints @haszari ?

Feels unrelated, I resized the window huge to be sure, and you can see almost enough whitespace for the missing product in the column:

<img width="2485" alt="Screen Shot 2019-11-25 at 1 39 14 PM" src="https://user-images.githubusercontent.com/4167300/69504581-fa728700-0f88-11ea-950e-34bb871d9849.png">

**Comment by haszari** [comment]
Looks like this is Safari specific, it's ok in Chrome and Firefox:

<img width="1528" alt="Screen Shot 2019-11-25 at 1 43 19 PM" src="https://user-images.githubusercontent.com/4167300/69504630-8c7a8f80-0f89-11ea-9d81-10e89703bca4.png">

<img width="1395" alt="Screen Shot 2019-11-25 at 1 43 34 PM" src="https://user-images.githubusercontent.com/4167300/69504642-9a301500-0f89-11ea-9a47-bda4b054f3c0.png">

**Comment by nerrad** [comment]
Ahh good to know :) nice find!

**Comment by Aljullu** [comment]
I think that's a Storefront issue: :slightly_smiling_face: 

https://github.com/woocommerce/storefront/pull/1217
