### ISSUE TITLE
Update changelog script to work with new ZenHub workflow

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#1252]
When we migrated releases to ZenHub our [changelog script](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/bin/changelog.js) stopped working. This issue is about updating it to work with [ZenHub's API](https://github.com/ZenHubIO/API#get-all-the-issues-for-a-release-report).

**Comment by nerrad** [comment]
This will assist with end of cycle release related things so I'm including it in the 2.6 release however, let's leave this to the second sprint in the cycle.
