### ISSUE TITLE
Update repo docs with more details on releases.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#1260]
One suggestion coming out of process planning was to update the releases section in our `CONTRIBUTORS.md` (or maybe it should live in `README.md` ) with additional details on:

- versioning scheme (SEMVER)
- how we track versions.
- criteria used for where an issue/pull is assigned for the different versions

Also as a part of this issue the `README.md` doc should be updated to reflect our current processes (we no longer _automatically_ release every two weeks for instance).

**Comment by mikejolley** [comment]
Upon reviewing our documentation as part of #1285 it appears that this is already taken care of. The recent docs updates from team cover processes, whereas sprints are an internal policy that do not need to be documented here in public IMO, and finally, versioning is covered in the Appendix in the contributors file.
