### ISSUE TITLE
Block Idea:  Shop Directory Block

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#1261]
Now that we have the All Products block and a number of Filter blocks available.  I think there'd be value in creating a container block that has the All Products block setup with filter blocks in a curated layout so merchants can just drop this in a page and have it ready to go.  Some thoughts:

- ability to adjust the layout of the inner blocks (all products, filters etc) selecting a patterns.
- everything contained in the container would be in it's own context so that search results/filter selections  etc will be specific to that container.  This will feasibly allow for merchants to setup containers on the same page for various targeted types of products.

Primary purpose behind this work would be to enable merchants to get started with a Shop Directory out of the box with little to no configuration.  It could also be used in various contexts (and potentially replace the current shop page view).

**Comment by haszari** [comment]
Seems like a great idea - at the moment the user needs to know how these blocks work together.

Another area where this is a little confusing – these blocks are "different" from the other self-contained woo blocks. Perhaps they could be grouped in the block chooser or identified in some way – i.e. new user choosing between `Filter Products by Attribute` vs. `Products by Attribute` blocks. cc @jwold 

<img width="705" alt="Screen Shot 2019-11-27 at 8 54 52 AM" src="https://user-images.githubusercontent.com/4167300/69667819-95877000-10f3-11ea-8877-63b28b215801.png">

**Comment by nerrad** [comment]
> Another area where this is a little confusing – these blocks are "different" from the other self-contained woo blocks.

Yes, I very much agree with you here.  It'd be good to differentiate between "atomic" blocks that generally work best in context with other blocks, and "curated" blocks which are either stand-alone or container type blocks which are drop and go.  Also I think we need to do some explorations around what terminologies we use (which would fit into your idea how how we group things).

As a starting point, we probably should tighten up the description for these blocks so the description can give some insight into where they are used.

**Comment by jwold** [comment]
Great points @haszari and @nerrad. I'm definitely open to ways we could change up how atomic blocks vs larger blocks are shown. There's been some discussion by folks where we've looked at ways to improve the organization of blocks overall when you go to look for them. This is one such example:

![image](https://user-images.githubusercontent.com/3411173/69669216-45060900-1046-11ea-81fc-1ad00a066736.png)

Wondering cc @pmcpinto and @garymurray if prioritizing this sooner than later may make sense.

**Comment by pmcpinto** [comment]
Gave my feedback here: p1574848938295000-slack-wootenberg

**Comment by garymurray** [comment]
We could work on this as part of the block patterns work later this year imo.

**Comment by nerrad** [comment]
This is still a good candidate for block patterns, however I realized that we still need a container block for defining the context of all the elements within it.  So patterns would be simply different arrangements for the inner blocks in the Block Directory container block. Or it's possible we may just use the block variation api (slightly different than patterns) within the container block.

**Comment by nerrad** [comment]
I don't think we should do any engineering work on this until there's some direction given on the design part of this.

cc @LevinMedia aside from the original description, what other details do you need to help with understanding the need for something like this block?
