### ISSUE TITLE
Cart & Checkout Block: Add Data Tracking

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-gutenberg-products-block#1273]
In order to quickly and properly measure the cart & checkout blocks impact it would be important to have an event triggered when the cart and checkout pages are published with the blocks.

If it's not possible to add the tracking we'll need to rethink the release strategy of v1.

- There's a good guide about Tracks in the Fieldguide: /tracks
- A couple of months ago it was implemented an event tracking library for the block editor, but it seems to be exclusive to .com. More info here: p7H4VZ-2hb-p2

**Comment by pmcpinto** [comment]
@nerrad I imagine that it won't be possible to check this during the cooldown, but it's important to evaluate if it's possible to have the event tracking as it's going to influence how we release v1.

Justin and Joshua have been implementing the tracking in the new obw, so maybe they have some good tips. I'm not sure if anyone in the merch squad has experience with Tracks. Maybe @haszari has done some implementation in the wc.com side.

**Comment by nerrad** [comment]
> but it's important to evaluate if it's possible to have the event tracking as it's going to influence how we release v1.

If it's similar to tracking I saw when doing [this pull](https://github.com/woocommerce/woocommerce-admin/pull/3313) then I don't think we'll have issues with implementing it.  cc @joshuatf is that a fair assumption?

**Comment by haszari** [comment]
Agree, the sooner we have tracks capabilities & events the more we can understand how our blocks are being used. Happy to help figure this out, perhaps I can do a research spike on what we have and what we need?

@nerrad / team are there any tracks events for blocks yet, or is this completely new?

**Comment by nerrad** [comment]
woocommerce/woocommerce-admin implementation is [here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/1273).

**Comment by nerrad** [comment]
See [this comment](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/1659#issuecomment-580201344) from Pedro:

> In terms of our blocks usage, it's being tracked through Jetpack and dotcom sites. More context about the dashboard here: pa1C6h-u4-p2
>
> As for the user behavior within the block editor, this p2 contains more info about it: p7H4VZ-2hb-p2

**Comment by haszari** [comment]
PRs related to this:

- https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/1975
- https://github.com/woocommerce/woocommerce/pull/25977
- https://github.com/Automattic/jetpack/pull/15028

**Comment by haszari** [comment]
Related issues: #2030 #2031 #2032

**Comment by haszari** [comment]
Closing - we have what we need in place now. (See [comment](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/1273#issuecomment-601488485) above.)

If there are specific issues or gaps we can open issues to fix :)
