### ISSUE TITLE
Several HOCs are missing propTypes definitions

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#1280]
We are inconsistently defining propTypes in HOCs: some of them have definitions and some don't.

This issue lists all current HOCs in WooCommerce Blocks based on whether they have propTypes definitions or not. The ones under _Missing propTypes definitions_ are the ones that need to be fixed.

### `assets/js/base/hocs`
* Have propTypes definitions:
	* [x] `with-reviews.js` [#](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/assets/js/base/hocs/with-reviews.js#L16)
* Don't need propTypes definitions:
	* [x] `with-component-id.js`
	* [x] `with-query-string-values.js`
* Missing propTypes definitions:
	* [ ] `with-products.js`

### `assets/js/hocs`
* Have propTypes definitions:
	* [x] `with-attributes.js`
	* [x] `with-searched-products.js`
	* [x] `with-transform-single-select-to-multiple-select.js`
* Don't need propTypes definitions:
	* [x] `with-rest-api-hydration.js`
* Missing propTypes definitions:
	* [ ] `with-categories.js`
	* [ ] `with-category.js`
	* [ ] `with-product-variations.js`
	* [ ] `with-product.js`

That was initially discussed in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/1177#discussion_r347869371.

**Comment by nerrad** [comment]
Since we're moving to TypeScript which will replace propTypes I think we can close this.
