### ISSUE TITLE
Allow for toggling product description field in Product blocks.

### ISSUE THREAD

**Issue by strarsis** [woocommerce/woocommerce-gutenberg-products-block#1286]
**Is your feature request related to a problem? Please describe.**
It would be nice if the products of the product blocks can also show their product description.

**Describe the solution you'd like**
An option for enabling/disabling product descriptions.

**Describe alternatives you've considered**
There aren't really alternatives.

**Comment by nerrad** [comment]
Hi @strarsis 👋

Thanks for taking the time to share this idea, we really appreciate your help.  While this is clearly a great idea, we won't be able to tackle it in the upcoming weeks as we're currently focused on finishing all the work that was identified as a priority for version 2.6 of this feature plugin.  I'm going to add this to our backlog where it will be considered for feature releases.

**Comment by haszari** [comment]
Just to clarify, the goal of this issue is to add the description to these blocks and allow merchant to toggle it on/off. When I first read the issue I thought this was just about adding a toggle - i.e. allowing product description at all is the enhancement.

**Comment by strarsis** [comment]
@haszari: Well, adding a product description to final block markup (with being able to hide it using filter or CSS) would have been an improvement, too.

**Comment by haszari** [comment]
Moved out of `in progress` and unassigned based on discussions in PR #2753

**Comment by helgatheviking** [comment]
For what it's worth, I also needed descriptions in the hand-picked products block over the weekend and was just about to submit a PR for this (I think I changed the same two files) but I found this one first.

**Comment by helgatheviking** [comment]
FYI, the short description can be added to the block output via the following snippet:

```

/**
 * Add short description to blocks
 *
 * @param string $html
 * @param object $data
 * @param WC_Product $product
 * @return string
 */
function kia_blocks_product_grid_item_html( $html, $data, $product ) {
	$short_description = $product->get_short_description() ? '<div class="wp-block-grid__short-description">' . wc_format_content( $product->get_short_description() ) . ' </div>' : '';

	return 
		"<li class=\"wc-block-grid__product\">
			<a href=\"{$data->permalink}\" class=\"wc-block-grid__product-link\">
				{$data->image}
				{$data->title}
			</a>
			{$data->badge}
			{$data->price}
			{$data->rating}" .

			$short_description

			. "{$data->button}
		</li>";
}
add_filter( 'woocommerce_blocks_product_grid_item_html', 'kia_blocks_product_grid_item_html', 10, 3 );

```

However, there's no UI for toggling it on/off and that cannot be added since the product schema cannot be modified and no additional toggles can be added to the "Content" panel.

**Comment by helgatheviking** [comment]
FYI, the short description can be added to the block output via the following snippet:


/**
 * Add short description to blocks
 *
 * @param string $html
 * @param object $data
 * @param WC_Product $product
 * @return string
 */
function kia_blocks_product_grid_item_html( $html, $data, $product ) {
	$short_description = $product->get_short_description() ? '<div class="wp-block-grid__short-description">' . wc_format_content( $product->get_short_description() ) . ' </div>' : '';

	return 
		"<li class=\"wc-block-grid__product\">
			<a href=\"{$data->permalink}\" class=\"wc-block-grid__product-link\">
				{$data->image}
				{$data->title}
			</a>
			{$data->badge}
			{$data->price}
			{$data->rating}" .

			$short_description

			. "{$data->button}
		</li>";
}
add_filter( 'woocommerce_blocks_product_grid_item_html', 'kia_blocks_product_grid_item_html', 10, 3 );

However, there's no UI for toggling it on/off and that cannot be added since the product schema cannot be modified and no additional toggles can be added to the "Content" panel.

**Comment by nerrad** [comment]
Currently on our roadmap (but no ETA) we are planning on migrating the existing blocks to use product element and inner blocks which allow for finer control over how content is rendered (which will resolve this and other issues). With this in mind, to limit the surface area involved with that kind of migration we are not adding additional controls to the existing blocks. We've definitely heard the request for this feature and it will be functionally possible after this migration but it won't be implemented as described in this issue so I'm closing it.

Thanks for leaving your request!
