### ISSUE TITLE
Cart Block: Block skeleton registered (php/js)

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#1295]
For this issue:

* [ ] Cart block registered that is just the basic skeleton for the block registered php side and js side. Just use placeholder for content right now - components will come in future iterations.
* [ ] Should have "Full Cart" and "Empty Cart" modes (again with just placeholder content).
* [ ] ~The block should only be available via the cart page.~ This has been split out to #1305

**Comment by haszari** [comment]
I spun off a separate issue for limiting blocks to specific page(s): #1305
