### ISSUE TITLE
Checkout Block: Block skeleton registered (php/js).

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#1301]
For this issue:

* [ ] Checkout block registered that is just the basic skeleton for the block registered php side and js side. Just use placeholder for content right now - components will come in future iterations.
* [ ] ~The block should only be available via the Checkout page of a user's site~ This has been split out to #1305

**Comment by haszari** [comment]
I spun off a separate issue for limiting blocks to specific page(s): #1305
