### ISSUE TITLE
Needs Decision: Should we allow cart/checkout blocks on specific pages only (and next steps).

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#1305]
> Note (added by @nerrad): There's some discussion happening in this issue on whether we _should_ add any restriction. 

We are starting work on a new improved cart and checkout layout, implemented as blocks.

As part of this, we'd like the option to limit where the cart and checkout blocks can be used – they should only be available for particular pages. Specifically, the cart page, and checkout page.

The goal of this issue is to investigate how we could achieve this, and if there's any prior art for something like this in Gutenberg or elsewhere. Ideal outcome would be a list of options for how this could be implemented, and proposal for what we should do.

**Comment by senadir** [comment]
with some research and asking around, we can use [`allowd_block_types`](https://developer.wordpress.org/reference/hooks/allowed_block_types/).

**Comment by mikejolley** [comment]
The page association in woo core, to my knowledge, is there so links can point to the correct place. I don't know if we should limit to that page in our first release because:

1. The customer may want to test the new block on a different page, or run both checkouts side by side for comparison.
2. If we build the block well and self-contained, it could work on any page. Unlike the core checkout page which has script dependencies that get enqueued on checkout only.
3. Global settings can add confusion right? Why can't I add the block here! And it impacts discoverability.

**Comment by garymurray** [comment]
This does highlight something that has not really been thought about - until these are part of WooCommerce core - what will be the experience of someone wanting to use these blocks?

I can see two scenarios (currently):

1. They add them to their existing cart/checkout pages and remove the existing shortcodes
2. They create new pages and insert the new blocks themselves

If they go with option 1, the urls stay the same, if they go with option 2 - they will end up with a `/cart-2/` or `/checkout-2/` type situation - which means their store will still default to the old cart and checkout - is that correct?

So, ultimately, we can't just replace their cart/checkout pages shortcodes with these new blocks. People are going to have to add them to a page of some sorts and adding them to the existing pages sounds like the better UX than having them have to then go remove the old page, change the url etc.

I can see the case as Mike points out here though:

> The customer may want to test the new block on a different page, or run both checkouts side by side for comparison.

which would allow people to:

- Just preview the differences (they would not be able to actually preview the UX though as it would default to the old cart/checkout
- Possibly try A/B test this by sending 50% of traffic to each checkout based on URL - but that sounds more advanced than most of our typical customers would be comfortable doing (I think)

I'm going to have to think about this a bit - is this a blocker to moving forward in anyway?

**Comment by nerrad** [comment]
> I'm going to have to think about this a bit - is this a blocker to moving forward in anyway?

Not a blocker.  I've intentionally put this in the "Next" pipeline because we can continue discussing and make a decision later in the cycle.  I have some thoughts but want to ruminate on it a bit before commenting :)

**Comment by senadir** [comment]
forget to update PR, thanks Mike

**Comment by pmcpinto** [comment]
If we decide to move forward to allow eCom plan users to experiment with the new cart and checkout, can we easily automatically create cart & checkout pages (or update the existing ones) if a user agrees to test them?

**Comment by nerrad** [comment]
I think we could yes.

**Comment by nerrad** [comment]
We're getting close to the end of the cycle so I think we should pick up discussing this and come to a decision. My thoughts:

- For initial release, I don't think we should restrict where the blocks can be used.  This aligns with the current way shortcodes work as well.
- We can evaluate post release (likely do some user-testing and tracking?) to see whether this is a ux stumbling block for users.
- I think _eventually_ we can introduce a more canonical place to edit cart and checkout views (i.e. we lock down a specific view/route for where the blocks are used and managed and handle all the rewrite/redirect stuff internally).  This can be done once the new wc-admin navigation is in place and we have a designated home for editing cart and checkout.

cc @pmcpinto, @garymurray, @jwold (and any other @woocommerce/blocks crew who want to comment.  Thoughts?

**Comment by pmcpinto** [comment]
👍 backlogging this restriction seems to be the best option at this stage. I'm going to move this issue to the backlog

**Comment by nerrad** [comment]
The decision was to not add any restriction. So I'm closing this.
