### ISSUE TITLE
REST API: Payment Methods API

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#1321]
_This issue needs more in-depth exploration and planning._

Lists available/registered payment methods. Used by the cart to show a payment methods list (icons only), and used by the checkout to show available express and regular payment methods.

```
GET /payment-methods
```

It may be possible to use or borrow the /payment_gateways controller from the core REST API. However, we do need to factor in some unique use-cases such as the 'express' payment methods box.

Unanswered Questions/Notes:

- Do payment method FIELDS come from the API or are they inserted by the payment gateway plugin/class?
- Do we provide some common fields, for example, a basic credit card component for those gateways which need it?
- What is the context for this endpoint? Is it the current customer/location, or perhaps the order being processed? How is this data passed to the endpoint?
- How do we allow payment methods (gateways) to handle collected data?

**Comment by nerrad** [comment]
I'm going to explore a bit how the payment methods themselves might be able to register a component for the checkout (and what might be needed for that).  That can help inform whether we need additional apis for this issue.

**Comment by nerrad** [comment]
With the work done in #1349 it's becoming clearer that we won't need this endpoint because payment methods will be responsible for registering themselves with the new checkout and taking care of any communication with the server etc.  So for now I think we can probably close this (feel free to re-open Mike if you disagree)
