### ISSUE TITLE
"Full Cart" and "Empty Cart" modes for cart block

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#1326]
The cart block will allow merchants to preview and edit the cart in empty and full states in the block editor. This issue is focused on implementing these modes and editor UI for selecting mode. 

Placeholder content can be used for both modes for now. Real content / settings in each mode are covered by follow up issues: #1296 #1297 #1299 #1300 etc

![Screen Shot 2019-12-05 at 2.53.50 PM.png](https://images.zenhubusercontent.com/5ddb3cb39529f10001e618e5/2a4d4c82-7699-40de-b7be-3ede0711bc74)

![Screen Shot 2019-12-05 at 2.54.07 PM.png](https://images.zenhubusercontent.com/5ddb3cb39529f10001e618e5/e586535d-6d4b-46ea-ae70-24c6dad69771)

**Comment by haszari** [comment]
cc @Aljullu  - this probably blocks implementing cart empty state #1296

**Comment by Aljullu** [comment]
> cc @Aljullu - this probably blocks implementing cart empty state #1296

Yes, thank you @haszari! I was still investigating how to use core blocks as inner blocks, but it's helpful that you're working on this issue now so when I finally implement it empty/full cart will already be different. :+1:
