### ISSUE TITLE
Checkout Block: Step One - Contact Information

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#1345]
As per the exploration done by @Aljullu in #1208 this issue is concerned with the Contact Step in the form area of the checkout template:

![contact information step](https://user-images.githubusercontent.com/3616980/69613175-69a3b600-1031-11ea-8431-3dce302befc1.png)

`/base/components/checkout/contact-information`

**Comment by senadir** [comment]
I'm just noticing this & #1346, I guess #1348 should solve them all?

**Comment by nerrad** [comment]
Ya you can this issue with #1348.  However I think #1346 still has work to do for when there are no shipping options available.

**Comment by senadir** [comment]
Yeah, for now I just supplied a `shippingMethods` props and worked around it and I'm building the placeholder until we have datastores in place

**Comment by nerrad** [comment]
@senadir is this issue considered closed from the work done in #1351?

**Comment by senadir** [comment]
yes, some itiration should still be done to those components but we can close this
