### ISSUE TITLE
Checkout Block: Payment Method Form Steps.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#1347]
As per the exploration done by @Aljullu in #1208 this issue is concerned with the Payment Method Steps in the form area of the checkout template.

These steps will be provided by registered payment methods so there will need to be some thought into how that process will work.

### CheckoutPaymentMethod ( `/base/components/checkout/payment-method`)

![Payment method step](https://user-images.githubusercontent.com/3616980/69613245-88a24800-1031-11ea-8fde-03978b368a53.png)

- PaymentMethodTabs ( `base/components/checkout/payment-method-tabs` )
- PaymentMethodTab ( `base/components/checkout/payment-method-tab`)
- PaymentMethodPlaceholder ( `base/components/payment-method-placeholder`)
-  CreditCardInput (`/base/components/credit-card-input`) (and expiry and ccv inputs).

![Payment method placeholder](https://user-images.githubusercontent.com/3616980/69613303-a4a5e980-1031-11ea-9061-8814e85c85da.png)

**Comment by haszari** [comment]
> These steps will be provided by registered payment methods so there will need to be some thought into how that process will work.

Indeed! I believe payment methods are currently implemented in woo extensions (other plugins), so we'll need to consider those plugins and how they feed into the checkout block UX. 

- https://docs.woocommerce.com/wc-apidocs/class-WC_Payment_Gateway.html
- https://woocommerce.com/product-category/woocommerce-extensions/payment-gateways/
- https://woocommerce.com/products/woocommerce-gateway-paypal-checkout/
- https://woocommerce.com/products/stripe/

**Comment by nerrad** [comment]
The registration process and initial skeleton for steps has been merged in with #1349. There are other issues for remaining work so this can be closed.
