### ISSUE TITLE
Checkout Block: Form Inputs

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#1348]
As per the exploration done by @Aljullu in #1208 this issue is concerned with the Form Input components used in the form area of the checkout block.  For context, here's the entire block:

![entire-block](https://user-images.githubusercontent.com/1429108/69998705-e8628c80-1524-11ea-9e6c-e8b6297b446c.jpg)

## Needed components
* Checkbox (`/base/components/checkbox`)
* Select (`/base/components/select`): #1573.
* TextInput (`/base/components/text-input`)
* TextInputTooltip (`/base/components/text-input-tooltip`)
* PhoneInput (`/base/components/phone-input`)
* CountryInput (`/base/components/country-input`): #1574.
* CountyInput (`/base/components/county-input`): #1575.

**Note:**  A number of other components are dependent on this work, so this should be done fairly quickly.  Probably a good idea to do this in concert with #1346 so the inputs can be implemented for review.

A number of these inputs will likely have already been done in the `@woocommerce/components` package (or elsewhere in the `woocommerce/wc-admin` project).  We should try to address how we can use them (even if it means making `@woocommerce/components` more usable, or temporarily copying them in to our project in the meantime).

**Comment by nerrad** [comment]
@senadir is this issue considered closed from #1351?

**Comment by senadir** [comment]
@nerrad I wouldn’t consider this done yet, some components are still missing like country select and phone input and they need to be solved, however, this is not blocking anything else so far so we can remove the blocker

**Comment by Aljullu** [comment]
`<CountryInput>` and `<CountyInput>` are needed for the Cart Shipping Calculator (#1530). Should we create child issues for them and move them to the current sprint?

**Comment by nerrad** [comment]
> Should we create child issues for them and move them to the current sprint?

Yes let's do that.

**Comment by nerrad** [comment]
Since Company Name input option has its own issue now (#1481) that takes care of all the inputs for this issue. I'm going to close this and if there's still missing inputs we can open up separate issue(s) for them.
