### ISSUE TITLE
[WC 3.9 beta1]: All Products Block - can't go back to default width after changing to Wide or Full

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-gutenberg-products-block#1372]
**Describe the bug**

Found this issue during WooCommerce 3.9 beta1 testing. In `All Products` Block - can't go back to default width after changing to `Wide` or `Full`. 

**To Reproduce**

1. Go to page or post where you can add blocks;
2. Add `All Products` block;
3. Note that when you add the block, the default width is set on the block:

![all_products1](https://user-images.githubusercontent.com/19143190/70794889-99bfb880-1d96-11ea-9117-ece9922c8500.jpg)

4. Change the width to either `Wide` or `Full`:

![all2](https://user-images.githubusercontent.com/19143190/70795036-ddb2bd80-1d96-11ea-9862-b925ec219bf9.jpg)

5. Try to switch the width back to default and you'll see that there is no default width option:

![all3](https://user-images.githubusercontent.com/19143190/70795205-308c7500-1d97-11ea-9950-e2d279c809db.jpg)

**Expected behavior**

I expected to be able to go back to the default width after switching to either `Wide` or `Full`. 

**Screenshots**

See the screenshots above. 

**WordPress (please complete the following information):**

* Core version: 5.3.1
* Gutenberg version (if installed): not installed
* WooCommerce version: 3.9 beta1
* WooCommerce Blocks version: not installed
* Site language: English
* Any other plugins installed: No

**Desktop (please complete the following information):**

* OS: macOS Catalina
* Browser: Chrome
* Version: 78.0.3904.108 (Official Build) (64-bit)

**Additional context**

Thanks to @rantoncuadrado for spotting this issue during his testing.

**Comment by nerrad** [comment]
@juliaamosova , this isn't an issue specific to All Products block.  It's the same behaviour for _any_ Gutenberg block.  If you want to go back to the default width, you need to click the currently selected width to unselect it.  Not very intuitive, but sounds like an issue for Gutenberg core, not here.

Thoughts?

**Comment by nerrad** [comment]
I'm going to close, but if there's reason to re-open, please do!

**Comment by juliaamosova** [comment]
@nerrad thanks for taking a look. I can see that clicking on the currently selected width allows going back to the default width. Not intuitive indeed. But yes, I agree with you that this is a Gutenberg issue. Going to open it there.

**Comment by juliaamosova** [comment]
Opened a feature request issue in Gutenberg repo: https://github.com/WordPress/gutenberg/issues/19160
