### ISSUE TITLE
All reviews block carrousel

### ISSUE THREAD

**Issue by leandroprz** [woocommerce/woocommerce-gutenberg-products-block#1388]
**Is your feature request related to a problem? Please describe.**
Right now the All reviews block allows you to show X number of reviews. When the user loads more than the initial amount the page gets bigger and bigger.

**Describe the solution you'd like**
I think it would be great to have an option to see all the reviews in one single block that doesn't get bigger. This could be done by loading all the reviews and showing them one after the other using a slider effect, after a few seconds, with a fade animation. Maybe also add an arrow to let the user go back or forward between the reviews.

**Describe alternatives you've considered**
I found [this plugin](https://wordpress.org/plugins/twb-woocommerce-reviews/) that does what I described above, but since WooCommerce has the All reviews block, I think it would be a great addition instead of just installing another plugin.

**Comment by nerrad** [comment]
Hi there 👋 @leandroprz 

While we appreciate you sharing your idea with us (thanks!), it doesn’t fit in with our current priorities for the project. At some point we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. In the meantime, don't be alarmed if you don’t see any activity on this issue for a while.

**Comment by liviujs** [comment]
@nerrad i subscribe as well to this feature.
It's pointless to have the ability to show all reviews on a Landing Page, without a Carousel option, or at least a styling option to load more/less.
Thank you.

**Comment by nerrad** [comment]
Once again thanks for the feature request! This issue has come up in our regular review of open issues and while we do understand the use case for adding something like this it's not something that we will be working on.. 

There's opportunity here for enterprising WooCommerce developers to create a block that has this specific feature set but we have a current slate of higher priority items that realistically means we won't be addressing this.
