### ISSUE TITLE
Vertical display option for price filter block.

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-gutenberg-products-block#1393]
**Is your feature request related to a problem? Please describe.**

With the arrival of the `All Products` block along with all price filter blicks, one of the popular (assumed) used cases could be using `All Products` block with `Filter by Price` block within 2 columns block as shown below:

![filter12](https://user-images.githubusercontent.com/19143190/70910450-a5fe7c80-2007-11ea-96be-f62b75761305.jpg)

Here is how it looks at the front end (lots of empty space below the filter by price block):

![filter1](https://user-images.githubusercontent.com/19143190/70910541-d219fd80-2007-11ea-8c83-1a60982bf052.jpg)

**Describe the solution you'd like**

It could be nice to utilize the space below the `Filter by Price` block in case the user won't be adding more blocks under it. The solution could be to introduce the vertical block instead of horizontal. Not sure if this will be the only block that can be used vertically but it is a thought. In this case, the widths of both columns will need to be adjusted to allow for even distribution of content:

![filter122](https://user-images.githubusercontent.com/19143190/70911327-9849f680-2009-11ea-9bb5-362802fab0a0.jpg)

**Describe alternatives you've considered**

None. 

**Additional context**

Thanks to @rantoncuadrado for spotting this issue during his testing.

**Comment by nerrad** [comment]
I just did a quick experiment and something like a `transform: rotate( 90deg 0` css property can get us most of the way there for this feature request.

**Comment by nerrad** [comment]
This issue came up as a part of our weekly issue review and we've decided this isn't something we will be implementing. Thanks for taking the time to document the suggestion made Julia.
