### ISSUE TITLE
Issue with build on WordPress.org

### ISSUE THREAD

**Issue by danielbitzer** [woocommerce/woocommerce-gutenberg-products-block#1398]
**Describe the bug**
When I try to edit the inner blocks of the **all products block** I get a JS error and the block breaks. 

**To Reproduce**
1. Install the 2.5.4 build from https://wordpress.org/plugins/woo-gutenberg-products-block/
2. Add the All Product Block
3. Click the edit button in the BlockToolbar

**WordPress:**
* Core version: 5.3.1
* WooCommerce version: 3.8.1
* WooCommerce Blocks version: 2.5.4
* Site language: US EN

**Desktop:**

* OS: Mac
* Browser firefox
* Version 71

**Comment by nerrad** [comment]
Thanks for reporting this @danielbitzer , we can reproduce and I'm getting a fix ready.
