### ISSUE TITLE
[WC3.9-beta1] Fix issue with Filter By Price block not working as expected with certain combination of attribute filters.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#1414]
Original report: pb22l9-5F-p2

To reproduce:

- Create two attribute terms: Values `test` and `test2` under the attribute `attr1`.  
- Create a product priced at $9.99. Assign the `attr1` attribute to this product (with `test` term).
- Create a product priced at $13.99, on sale for $10.99.  Assign the `attr1` attribute to this product (with `test2` term).
- Set up the view so there is the all products block, price filter block, active filters, and filter by attr1.
- Setup the filter by attribute block to "or" conditions.

### Issue 1: Filter Price Block showing wrong price range:

<img width="663" alt="issue1" src="https://user-images.githubusercontent.com/1429108/71093233-d0227c80-2176-11ea-8b76-5b6d2e1c2123.png">

When ticking both attributes, the right products show up, but the "filter by price" block shows the price range as begin from $0-$10, when the highest priced product is $10,00 (and $13.99 if it wasn't on sale).

### Issue 2: Disappearing Filter By Price Block

<img width="663" alt="issue2" src="https://user-images.githubusercontent.com/1429108/71093401-1aa3f900-2177-11ea-8853-69a2662551b3.png">

Unchecking the `test` attribute shows the correct product but the price filter disappears.  However if you leave the `test` attribute term checked and uncheck the `test2` attribute the price filter stays.

<img width="663" alt="issue2b" src="https://user-images.githubusercontent.com/1429108/71093549-6b1b5680-2177-11ea-8b78-bc3b92fdaa9e.png">

**Comment by senadir** [comment]
While fixing issue 1, issue 2 seems to be magically fixed, in what I assume the filter is no longer returning NaN for it to not show up

**Comment by nerrad** [comment]
> While fixing issue 1, issue 2 seems to be magically fixed, in what I assume the filter is no longer returning NaN for it to not show up

Awesome!
