### ISSUE TITLE
[WC3.9-beta1] It's not obvious filters only work with All Products block

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#1416]
We should make it clearer that the filter blocks only work in combination with the _All Products_ block. Some ideas:

We could update their descriptions to make it clear they only work in combination with the <i>All Products</i> block:

![Screenshot from 2019-12-18 11-54-35](https://user-images.githubusercontent.com/3616980/71099674-f6b2d880-21b3-11ea-8ccc-6f03cdab7a91.png)

Or even update the block names:

![Screenshot from 2019-12-18 11-53-21](https://user-images.githubusercontent.com/3616980/71099657-f1ee2480-21b3-11ea-9318-8f5e25fb479d.png)

The second option is more obvious because the user doesn't need to hover them or add them to the page to discover they only work with the <i>All Products</i> block, but block names become more verbose.

**Comment by nerrad** [comment]
I like the first idea about updating the block descriptions. However, I'm wary about updating the actual block names because technically there's nothing preventing us from making this available to work with more blocks in the future.
