### ISSUE TITLE
Change WooCommerce block icons

### ISSUE THREAD

**Issue by jwold** [woocommerce/woocommerce-gutenberg-products-block#1418]
The current icons for our WooCommerce blocks were custom designed. They've helped convey ideas for blocks, but have also varied in consistency. This issue proposes updating our blocks to use outlined material design icons. 

Download: [Icon-svgs.zip](https://github.com/woocommerce/woocommerce-gutenberg-products-block/files/3980632/Icon-svgs.zip)

Old icons with proposed new icons:

<img width="912" alt="Screen Shot 2019-12-18 at 1 32 11 PM" src="https://user-images.githubusercontent.com/3411173/71124963-d9254500-219a-11ea-9998-3b9efa33a8d9.png">

**Comment by senadir** [comment]
Some icons are missing like Cart and Checkout, any possibility to amend them?

**Comment by jwold** [comment]
Ah @senadir great point. I was only doing the icons that had shipped so far. @garymurray what would you like to do for Cart and Checkout?

**Comment by senadir** [comment]
Since this will ship with the next major release at least, Cart & Checkout will still be included

**Comment by garymurray** [comment]
I see you using the outline version - so we can use these for cart and checkout from the Material library:

<img width="784" alt="Screenshot 2019-12-20 at 11 33 51" src="https://user-images.githubusercontent.com/10805911/71252339-9db28400-231c-11ea-9ca7-77f089457a08.png">

**Comment by senadir** [comment]
@garymurray in the process of replacing all of our icons, I have a legacy one from gridicons that needs to be replaced as well if we want to match the style of all the icons (all of them using Material icons)

Aside
![image](https://user-images.githubusercontent.com/6165348/73065657-63507f80-3ea4-11ea-86ab-9323329a2f5d.png)
currently used for Product Summary atomic block
![image](https://user-images.githubusercontent.com/6165348/73065808-c17d6280-3ea4-11ea-815a-f40079e72782.png)

I was thinking this
![image](https://user-images.githubusercontent.com/6165348/73067005-d4ddfd00-3ea7-11ea-9ce6-366b84cf46a9.png)

or this
![image](https://user-images.githubusercontent.com/6165348/73067056-f4752580-3ea7-11ea-804e-49181c0ffaac.png)

**Comment by garymurray** [comment]
@senadir I would go with the `Notes` one you suggest.
