### ISSUE TITLE
Mobile columns don't have options available or styles

### ISSUE THREAD

**Issue by yratof** [woocommerce/woocommerce-gutenberg-products-block#1422]
There seems to be no styles for mobile / smaller screens, or any setting to allow different columns for smaller devices:

In the scss, there is an area that shows how columns are made:
`woocommerce-blocks/assets/css/style.scss:169`

But there are no mediaqueries around this... I'm seeing that after updating, my mobile view on my site shows 4 columns of products, which is no where near fitting on the page.

Am i missing something here? Perhaps there is an option available to collapse these columns down at a breakpoint?

**Comment by Aljullu** [comment]
Hi @yratof, media queries for responsive product grids were introduced in WooCommerce Blocks 2.5, so this issue should be solved if you update. :slightly_smiling_face: 

I have opened another issue about adding a UI option to manually set the number of columns on smaller devices: #1626.

I will proceed closing this one, but feel free to follow #1626 if you are interested in that feature.
