### ISSUE TITLE
Active Filters block: always display the active filters section, even prior to selecting a filter option

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-gutenberg-products-block#1435]
The Active Filters section should also be displayed, even prior to selecting a filter option, so the shopper has a sense that he will be able to easily remove any filter.

Current experience:
![YjPKDsHwVW.gif](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/6c3e428f-e1a2-4f7a-99b7-59f5562961ad)

Suggested during the WC 3.9 Testing (pb22l9-5F-p2)

**Comment by garymurray** [comment]
Is the suggestion here that we always have the section `Active Filters` displayed - even where there are not filters active - i.e. it would then have some sort of message to say something like `No filters are currently active` ?

If you look at something like Allbirds as an example, you don't see the active filters, until you actually filter - i.e.:

No filters active:

<img width="1174" alt="Screenshot 2020-01-13 at 11 45 10" src="https://user-images.githubusercontent.com/10805911/72253772-307fcf00-35fa-11ea-9798-38d76dcfc388.png">

Filters active:

<img width="1168" alt="Screenshot 2020-01-13 at 11 45 59" src="https://user-images.githubusercontent.com/10805911/72253819-4ee5ca80-35fa-11ea-97ac-c0cbd6323bc7.png">

**Comment by haszari** [comment]
I've grabbed this (hopefully quick fix), though we may want to design-review this before merge. From the description it's not clear that this is essential.
