### ISSUE TITLE
All Products block: crop product images accordingly to the thumbnail crop settings in the Customizer

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-gutenberg-products-block#1443]
Currently the block ignores the thumbnail crop settings in the Customizer and when the merchant doesn't use images with the same aspect ratio it completely breaks the page layout.

A good workaround it's cropping the product images accordingly to the thumbnail crop settings in the Customizer. In the future, we can evaluate if it makes sense to move this setting to the block.

Customizing ▸ WooCommerce ▸ Product Images

![screenshot-2019-12-23-at-15.10.42.png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/4bbfd64d-67eb-4f97-ae0d-6c641d9a66f9)

**Comment by nerrad** [comment]
Personally, I think we should avoid trying to preserve what is set in the customizer and leave customizer for core functionality/old templates. Instead, where we identify the need for setting parity with what is available in the customizer we should implement that at the block level (for blocks that are affected).
