### ISSUE TITLE
Majority of products are not found

### ISSUE THREAD

**Issue by Pottypotsworth** [woocommerce/woocommerce-gutenberg-products-block#145]
I have been using the plugin for a couple of weeks and I am having an issue with finding the majority of products on a site which has well over 100.

The plugin seems to only search for the last 75-100 recently added products at best.

I also found that typing anything into product search box causes Guttenberg to do an autosave, this also seems to cripple the plugin from being able to find any products whilst the autosave is in progress.

It almost seems like luck if you can find the product you wish to add.

I'd be happy to troubleshoot further, but it really is quite as simple as the above.

Thanks

**Comment by ryelle** [comment]
Thanks for the report. Can you tell me which versions of WordPress, WooCommerce, and Gutenberg you're using?

**Comment by ryelle** [comment]
I just want to check that I'm testing the right thing. You've got a site with 100+ products, and are trying to add a product block with "individual products", like this:
<img width="630" alt="screen shot 2018-11-20 at 12 51 32 pm" src="https://user-images.githubusercontent.com/541093/48792741-0adf8a00-ecc3-11e8-911f-961f4603eae8.png">

When you search, you're seeing two things

- Gutenberg triggers an autosave (I can't replicate this issue, but I'll keep an eye out for it)
- It appears to be only returning results from the latest 100 or so products

Are all of your products named very similarly? The way we handle searching, it will return the latest 10 matching products, so if your search term returns 15 products, you won't see those last 5 (without a more specific search term). If you search on the Products page with the same terms you're using in the block, do you get more than 10 results?

![searchbox](https://user-images.githubusercontent.com/541093/48793273-6eb68280-ecc4-11e8-98bb-21c201e64bc9.png)

**Comment by Pottypotsworth** [comment]
Hey @ryelle 

Yes i am trying to add in individual products into the blog posts.

Some products have similar names, some are very unique. Another user of the site almost cannot get any product to show, even the same products that I have managed to get to show.

The more I test this, the more I am convinced that it is a speed issue with the autosave and not actually an issue with the plugin being unable to find the product.

It is like the autosave causes the plugin to stop searching. Then when the autosave is finished i basically need to restart the search to kick the plugin back into life. If the autosave fires again whilst I am searching then I will not get any results. I basically have to attempt to do my searches in between autosaves.

If there was a way for me to disable autosave entirely I bet the issue wouldn't show at all and all products would show.

Slightly unrelated, I did notice the search logic seems a bit weird. Products seem to show up for a terms which don't even have the term in the title.

![image](https://user-images.githubusercontent.com/20905543/48794106-f12a5b00-ed33-11e8-8730-f3076c8c91e1.png)

**Comment by ryelle** [comment]
> It is like the autosave causes the plugin to stop searching.

Unfortunately, I can't replicate this. The search stays active for me while autosaving. Have you tried disabling other plugins, to see if there's a conflict?


> Slightly unrelated, I did notice the search logic seems a bit weird. Products seem to show up for a terms which don't even have the term in the title.

It also searches the product content, so it's likely matching something in there.

**Comment by Pottypotsworth** [comment]
Hey @ryelle 

I'll have to play around with the plugins and see if one is influencing the autosave or causing the backend to freeze up.

I managed to solve the mystery of one of the other users not being able to see ANY products. He user level was set as an editor, it seems that "Shop Manager" or "Admin" are the only ones that can insert a product using this plugin despite "Editor" being able to ass/edit WooCommerce products.

Understood on the search logic, perhaps products with the search term in the title could be given more weight and show up first/higher? It would seem to me that most users who are trying to insert a product will largely be doing so based on the title they have given it.

Thanks for your help. I think the issue can be closed since there isn't a bug, it is other things influencing the plugin :)

**Comment by ryelle** [comment]
> it seems that "Shop Manager" or "Admin" are the only ones that can insert a product using this plugin

Thanks for pointing that out, I've created a separate issue for that in #153 

> Understood on the search logic, perhaps products with the search term in the title could be given more weight and show up first/higher?

We're just relying on core WordPress searching at the moment, but that does sound like a good idea for a future improvement.

Thanks for taking the time to report your feedback 🙂
