### ISSUE TITLE
Atomic Product title size is not being visually respected by styles

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#1451]
**Describe the bug**
Reported in pb22l9-5T-p2#comment-311
Atomic product title size can be changed from H2 to H6, this option is there for styles and accessibility reasons, but themes like storefront and other themes seem to hardcode a value for the title regardless of what Heading level it is

**To Reproduce**

1. Create a new All Product block
2. Go to block edit
3. Change the title size and notice that it stays the same

**Expected behavior**
Size should change

**Screenshots**

![image](https://user-images.githubusercontent.com/6165348/71580341-7a4bbe00-2b00-11ea-990f-c60de08561ef.png)

![image](https://user-images.githubusercontent.com/6165348/71580350-833c8f80-2b00-11ea-8b0a-dd89cdc2a690.png)

**WordPress (please complete the following information):**

* Core version: 5.3.2
* WooCommerce version: 3.9 RC-2
* WooCommerce Blocks version: 2.5.7 (included with Woo)

**Comment by haszari** [comment]
See related closed PR for more info: https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/1452

**Comment by haszari** [comment]
This issue should be fixed in themes directly. The blocks plugin provides a class allowing themes to target these titles directly if they wish.
