### ISSUE TITLE
Improve or replace Tabs Component.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#1474]
I introduced a tabs component in #1349 to get the ball rolling but I'm not sure if we should roll with it because there's some accessibility issues and I also think we should look at using existing solutions out there. Possibilities are:

### `@wordpress/components` [tab-panel](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/tab-panel) component. 

This is what I loosely based the existing implementation off of.  Implementing this will require something like #1371 (along with tree-shaking) to be implemented to reduce weight on the frontend.

### [reakit](https://reakit.io/docs/tab/)

I'm leaning towards trying to implement this one because it was built accessibility first in mind and likely will result in less weight overall.  If it works well, we could consider contributing it back to the WordPress component package.

**Comment by nerrad** [comment]
This is a candidate for followup iteration.

**Comment by senadir** [comment]
I think we should go for `reakit`

**Comment by senadir** [comment]
I'm returning this to the current sprint (feel free to move), I did some initial playing around in this branch, sadly it didn't work, something about how tabs content render.

https://github.com/woocommerce/woocommerce-gutenberg-products-block/compare/add/reakit
I will revisit back in the future if anyone wants to take this go-ahead.

**Comment by diegohaz** [comment]
@senadir Took a quick look at the code and noticed that you're not passing `selectedId` to the components, only the rest of the state:
https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/1666671f274c0ff8b088f10fee1b1a4d20ed9acb/assets/js/base/components/tabs/index.js#L23

Not sure if that's the only problem, but that will definitely make it not work.

**Comment by senadir** [comment]
Thanks @diegohaz that actually did help me solve the initial problem and discover a second issue in our code, must have took it off and never returned the `selectedId`
