### ISSUE TITLE
Add Unit Tests for New Hooks

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#1475]
In #1349 a number of new hooks were introduced.  This issue is to ensure we get unit tests added for these new hooks.  Also should add unit tests for the payment method registration api.

Add tests for:

* [ ] payment method registration api and it's utilities.
* [x] useStoreCart (#2013)
* [ ] useStoreCartCoupons
* [x] useStoreCartItemQuantity (#2013)
* [x] useCheckoutRedirectUrl (#2013)
* [x] useCheckoutSubmit (#2013)
* [ ] useBillingData
* [ ] useStoreOrder
* [ ] usePaymentMethodInterface
* [ ] usePaymentMethods
* [ ] useSelectShippingRate
* [ ] useShippingAddress
* [ ] useShippingRates
* [ ] useCollectionData
* [ ] useCollectionHeader
* [ ] useStoreNotices (#3162)
* [ ] useThrowError

**Comment by Aljullu** [comment]
I updated the list above with all the hooks that are currently missing tests.

In #2013 I added tests to some of them. I will unassign this issue from me since I will be working on something else for now.

**Comment by nerrad** [comment]
Thanks for getting the ball rolling Albert!

**Comment by nerrad** [comment]
I'm going to close this. Expanding our test coverage is an ongoing thing that we need to be watching for as we work on code.
