### ISSUE TITLE
Add placeholder for when no payment methods are installed and available.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#1478]
This is a followup to #1349.  There is no design yet for this.

cc @garymurray, @jwold

**Comment by jwold** [comment]
I'm guessing @garymurray will want to tackle this, but if not I'm happy to take a look! If there's a need for an illustration in the placeholder, that's also something I could support on.

**Comment by nerrad** [comment]
Here's what is currently implemented as the placeholder for the shipping step. We could do something similar for the payment methods?

<img width="683" alt="Image 2020-01-03 at 11 48 11 AM" src="https://user-images.githubusercontent.com/1429108/71736442-06225a80-2e1f-11ea-9dbf-b1f8d5c79ccf.png">

**Comment by jwold** [comment]
That makes a lot of sense to just replicate the feel of the shipping options placeholder.

**Comment by garymurray** [comment]
Yes - the idea is to replicate that - pretty sure I had it in the designs somewhere at some point:

<img width="677" alt="Screenshot 2020-01-13 at 11 19 33" src="https://user-images.githubusercontent.com/10805911/72252048-99654800-35f6-11ea-9e21-80446103670d.png">
