### ISSUE TITLE
Wire up checkout to display with an existing or sample product

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#1479]
This has some pre-requisites as noted in the dependencies.

The goal here is that if the store has an existing product, then use that for the checkout preview in the editor. Otherwise use a sample product to power the preview.

There may be some extra considerations here:

- Should we only display preview for certain product types?
- Should we narrow the scope for the initial release and just use a sample product for now (cc @pmcpinto , @garymurray )?

**Comment by pmcpinto** [comment]
If using a sample product makes it easier/quicker to implement this, I think we should move forward with it and consider displaying an existing product in a future iteration

**Comment by nerrad** [comment]
We're currently using sample product. I think we can wire up existing product in future iteration, removing from scope for cycle 3.
