### ISSUE TITLE
Address 2 Form Input Options

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#1480]
The following options should be available for the merchant to customize for this form input:

* Show/hide the Address2 input field.
* Should be on (or showing) by default.
* Can choose to make this a required field or not.  It should be optional by default.

**Comment by mikejolley** [comment]
> Can choose to make this a required field or not. It should be optional by default.

I think this would be bad. If an address doesn't have an address field 2 you're essentially blocking checkout or inviting spoof data.

**Comment by nerrad** [comment]
> I think this would be bad. If an address doesn't have an address field 2 you're essentially blocking checkout or inviting spoof data.

I kinda agree with this. It'd be nice to know the rationale behind requesting this feature.  If I were to guess, it might be because there are some shops where they never need an address 2 (don't ship things or it's a country with differing address requirements).  If this is the case, we could still always provide an empty `address2` field value in the checkout, it's just not a field visible to the shopper (so maybe the toggle just makes this a hidden field?

cc @garymurray can you add some context behind this feature request please (I extracted this issue from the requirements).  This also seems like something we can remove from iteration 1?

**Comment by mikejolley** [comment]
@nerrad Showing/hiding isn't a problem, because it can either be ignored, or (my assumption would be) the shopper would just use address 1.

But forcing a requirement could be problematic because it may not be part of an address. For example, I have no line 2 of my address, just address 1 (street).

**Comment by nerrad** [comment]
> But forcing a requirement could be problematic because it may not be part of an address. For example, I have no line 2 of my address, just address 1 (street).

Ah yes I see what you're getting at here. This comes into the territory of whether we provide an option that allows merchants to shoot themselves in the foot :).  I agree, we probably should not include the option for making this required or not as a part of this work.

**Comment by garymurray** [comment]
@mikejolley @nerrad 

I think this was an oversight on my part - I can't see (or recall) a reason for the address 2 field to have the option to be set to required. Maybe some businesses may need it, but my making it a "default option" we would be opening up a risk merchants "shoot themselves in the foot" so-to-speak.

We can remove that requirement.
