### ISSUE TITLE
Order Notes Field and options in the Checkout

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#1483]
The merchant should have the ability to add a order notes field to the checkout block.  The following work will need completed.

* An order notes field input component (which consists of both the order notes input and the checkbox for toggling showing/hiding that input).
* The merchant can enable/disable whether the order notes field shows. It is enabled by default.
* Order notes are always _optional_ for shoppers.  So when the merchant has enabled this feature, the shopper sees a checkbox that they can check to add order notes (selecting shows the order notes input).

**Comment by nerrad** [comment]
Reducing scope by removing from current cycle. Can be added in a later iteration.

**Comment by haszari** [comment]
Is this included in v1 @garymurray @mikejolley ? 

Currently the checkbox is visible and does nothing, so perhaps we can hide it for now. (Spotted when testing #2283)

**Comment by mikejolley** [comment]
We can move this in soon I think. Does not appear to need much effort.

**Comment by Aljullu** [comment]
@LevinMedia according to the designs, the _Add order notes?_ checkbox is displayed inside the _Shipping options_ section:

![imatge](https://user-images.githubusercontent.com/3616980/87442691-e3a2a280-c5f4-11ea-90e1-742dadcc1be4.png)

However, according to the way the shortcode works, the checkbox should be visible even when the order doesn't require shipping. Where should it be shown in those cases?

- Inside the _Billing address_ section?
- Inside the _Payment methods_ section? (Notice this section will not exist if the order price is 0)
- In its own section with another title?
- Or it shouldn't be shown at all and that's a difference with the current shortcode?

![imatge](https://user-images.githubusercontent.com/3616980/87443406-bd313700-c5f5-11ea-9d9c-f4f7b1cb5ced.png)

**Comment by LevinMedia** [comment]
@Aljullu let's add it as a new section below the payment method, I don't think we need a new title. 

<img width="744" alt="Screen Shot 2020-07-15 at 7 59 14 PM" src="https://user-images.githubusercontent.com/4500952/87621497-c2fe4980-c6d5-11ea-8af0-f10a3a18dd66.png">

<img width="704" alt="Screen Shot 2020-07-15 at 7 59 20 PM" src="https://user-images.githubusercontent.com/4500952/87621516-ce517500-c6d5-11ea-9614-1427b12b9eca.png">
