### ISSUE TITLE
Checkout Block: Legal links

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#1484]
The following component needs added:

![Image 2020-01-03 at 10.50.10 AM.png](https://images.zenhubusercontent.com/55c8bfc24f7a08fbb7f431bd/8fb86bc5-9078-4881-88bc-e787f3f8e782)

For this component:

- Terms & Conditions link should only show if it has been configured in the customizer or wc settings.
- Privacy Policy link should only show if it has been configured in the customizer or wc settings.
- There is a Refund Link in the mockup but I'm not sure whether that's currently a setting for WooCommerce (a quick search doesn't show anything).  If it's not a setting, then this will need to be configurable by the merchant (link to a page in the block settings?).  cc @pmcpinto and @garymurray to comment on this last bullet point.

**Comment by garymurray** [comment]
> There is a Refund Link in the mockup but I'm not sure whether that's currently a setting for WooCommerce (a quick search doesn't show anything). If it's not a setting, then this will need to be configurable by the merchant (link to a page in the block settings?). cc @pmcpinto and @garymurray to comment on this last bullet point.

There is not option/setting currently within WooCommerce that allows you to 'automatically' setup a refund policy and have it linked in the way we are proposing here - this would be a new setting/option we would have to introduce if we include it.

**Comment by mikejolley** [comment]
@garymurray @nerrad If we're adding a new option to control "refund policy", don't we need something similar for the other links? It would be weird for users to have one option locally in block, and then have to go elsewhere for the others.

Additionally, are we sure we want to hardcode policies to these 3? What if I have a custom store policy to add? How is this best managed?

Whilst this block is relatively simple to create (I'm almost done based on spec, aside from refund policy), I'm not sure it meshes well with the block, and these simple links could very easily be added as a block below checkout.

**Comment by nerrad** [comment]
Forgive my lack of understanding of how these links function currently in Woo. For the MVP could we just link to _existing_ policy pages if they exist (otherwise don't include links). We could just implement this as a component for the MVP and potentially convert to a block (with variations) in the future?

**Comment by mikejolley** [comment]
@nerrad Yes thats completely fine, but why would you want this over a full customizable text block on the page?

**Comment by mikejolley** [comment]
I'm going to add a toggle for legal links if thats ok. At least then you can opt to disable these and insert your own custom block.

**Comment by nerrad** [comment]
I'm mostly concerned about unexpected behaviour that might pop up with a custom block. We haven't accounted for dynamic block areas via inner blocks within the checkout yet and what kind of lock-in/restrictions that might expose for future iterations. So I'd still prefer a very basic initial iteration where folks can toggle the links on or off but it's very opinionated for i1. I _definitely_ do not think we'll want to stay with that but it leaves us some wiggle room for how we implement further customization with inner block areas and layout controls etc in future iterations of the checkout block.
