### ISSUE TITLE
Show sample cart content in editor and block inserter preview

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#1487]
The goal of this issue is that the cart block shows a realistic representation of a full cart:

- In the block picker preview pane
- In the block "full cart" mode when editing

This is somewhat underway, the full cart currently shows sample data from `previews/cart-items.js`. Before launch we'll need to ensure the preview looks good and may want to tweak the sample data.

This has some prerequisites as noticed in the dependencies.

~~The goal here is that if the store has an existing product, then use that for the cart preview in the editor. Otherwise use a sample product to power the preview.~~ **Update: we're using sample data, see discussion in comments**

There may be some extra considerations here:

- Should we only display preview for certain product types?
- Should we narrow the scope for the initial release and just use a sample product for now (cc @pmcpinto , @garymurray )? Based on feedback for the corresponding [checkout block issue](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/1479) I'm guessing we'll want to just do sample content for this initial iteration too? **See below - yes, limiting scope to sample data for now**

**Comment by pmcpinto** [comment]
> Should we narrow the scope for the initial release and just use a sample product for now (cc @pmcpinto , @garymurray )? Based on feedback for the corresponding checkout block issue I'm guessing we'll want to just do sample content for this initial iteration too?

Yes, I think it's better to have the same approach here

**Comment by nerrad** [comment]
See #1411 and #1333 for the work getting this done.

**Comment by Aljullu** [comment]
> The goal here is that if the store has an existing product, then use that for the checkout preview in the editor. Otherwise use a sample product to power the preview.

In the _All Products_ block preview we are always displaying placeholder products, even when the store has products. That was done so we were sure the preview would show up correctly (we are confident the placeholder products have an image, price, title, etc.). Shouldn't we do the same for the _Cart_ and _Checkout_ blocks and use placeholder content instead of real content for the preview?

**Comment by nerrad** [comment]
> Shouldn't we do the same for the Cart and Checkout blocks and use placeholder content instead of real content for the preview?

Good catch. Yes.

**Comment by garymurray** [comment]
Happy to use the placeholder products.

**Comment by haszari** [comment]
@nerrad should we bump this issue out of Current Sprint? From the discussion above it seems like this is not work we're taking on right now.

**Comment by nerrad** [comment]
No, the current sprint is for the cart block. This is for the cart block - unless I'm misunderstanding something we still need a preview to show in the block picker for the cart block?

I'll move this to the bottom of the pipeline, but I don't think it needs bumped just yet, especially when it should be relatively trivial (if not no extra work needed) with the cart block using example data for the edit view anyways.

**Comment by haszari** [comment]
> No, the current sprint is for the cart block. This is for the cart block - unless I'm misunderstanding something we still need a preview to show in the block picker for the cart block?

Ah I see, I didn't realise it was that 'preview', I was thinking of the full cart view in the editor. I'll tweak the issue title so it's clearer.

**Comment by haszari** [comment]
FYI here's shots of the current state:

#### Block inserter preview
<img width="743" alt="Screen Shot 2020-01-15 at 9 02 19 AM" src="https://user-images.githubusercontent.com/4167300/72378763-e96b1880-3776-11ea-9a1d-52ac4a666093.png">

#### Full cart block
<img width="1234" alt="Screen Shot 2020-01-15 at 9 02 03 AM" src="https://user-images.githubusercontent.com/4167300/72378724-d6584880-3776-11ea-81bc-4e9fd0ffe09f.png">

**Comment by garymurray** [comment]
Two comments here:

1. What are our options for the 'preview' in the **Block inserter preview** pane - can we use a static image there instead?
2. We have an icon for the checkout block which we can use:

<img width="216" alt="Screenshot 2020-01-15 at 09 45 36" src="https://user-images.githubusercontent.com/10805911/72423224-ce4ed780-377b-11ea-8601-1533d99c3ffc.png">

**Comment by nerrad** [comment]
> can we use a static image there instead?

Yes we can, and I think this is a good candidate for one. Is that something you can look at prepping for us @garymurray ?  In the past we've tried to use an svg if the size is kept relatively low (easier to include directly with the block and thus loads faster). Otherwise we can load it from external image.

**Comment by garymurray** [comment]
@nerrad sure, will take a look to see what I can create for there. Are there standard dimensions to work with?

**Comment by nerrad** [comment]
It looks like most of our grid block previews use 

- an [externally loaded svg](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/assets/img/grid.svg)
- with a width of `230` and a height of `250` (see [here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/assets/js/previews/grid-block.js))

**Comment by haszari** [comment]
Image sounds like a good idea! We'll need to review it when we finish implementing the cart in case anything changes (styling/storefront theme).

I split off the icon to a separate issue: #1577

**Comment by garymurray** [comment]
Perhaps we should just wait till we have it working then, and screenshot the design from an actual installation vs a mockup?

**Comment by pmcpinto** [comment]
I think that the cart & checkout previews probably will always look a bit crammed with the desktop view, so maybe it will be better to display the mobile view of each block? @garymurray what do you think? 

The downside is that users might find it confusing seeing the mobile layout in the preview and then the desktop layout when they add the block

**Comment by garymurray** [comment]
@pmcpinto I think desktop previews can still work - this just takes the current cart design and scales it to fit that preview area:

![Cart preview](https://user-images.githubusercontent.com/10805911/72610413-2f62e080-391f-11ea-9f8c-afe436b0367a.png)
