### ISSUE TITLE
Cart Block: Block settings for shipping options.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#1488]
The following options should be configurable for the cart block by the merchant:

* The merchant can show/hide the shipping calculator (setting currently available on WooCommerce > Settings > Shipping > Shipping options). The shipping calculator should be on by default.
* The merchant can choose to hide shipping costs until an address is entered (setting currently available on WooCommerce > Settings > Shipping > Shipping options). This option should be off by default.  
* Any change to those settings in the block editor should be reflected on the same setting on WooCommerce > Settings > Shipping > Shipping options
* Both shipping settings should be off by default if the user doesn't have any physical products in the store.

**Comment by nerrad** [comment]
> The merchant can choose to hide shipping costs until an address is entered (setting currently available on WooCommerce > Settings > Shipping > Shipping options). This option should be off by default.

It sounds like this option is dependent on whether the shipping calculator is toggled on or off as well?

> Both shipping settings should be off by default if the user doesn't have any physical products in the store.

Should either option be available for the merchant to toggle if there are physical products in the store (maybe just disabled)? If no, should there be additional messaging to the merchant about why these settings are not available?

cc @garymurray and @pmcpinto on the above questions.

**Comment by pmcpinto** [comment]
> It sounds like this option is dependent on whether the shipping calculator is toggled on or off as well?

Yes, ideally we should change the core setting so it matches our preference (having this option off by default), but I'm not sure if it's easy to do that.

> Should either option be available for the merchant to toggle if there are physical products in the store (maybe just disabled)?

I think that in order to simplify we should always display those settings and just toggle them to default if the user doesn't have a physical product.

> Also, if the calculator is turned off, should there be messaging with the total that shipping costs are not included?

If the shipping calculator is turned off it will be ok if we just hide the "Estimated shipping cost" section in the front-end and display the following message: Shipping options will be updated during checkout.

**Comment by senadir** [comment]
> Both shipping settings should be off by default if the user doesn't have any physical products in the store.

Since this will be reflected on the WooCommerce settings page, does it make sense to disable it? those values will persist right? they are not default values if the users didn’t set anything

**Comment by nerrad** [comment]
Nadir I may not be understanding your feedback correctly, so bear that in mind with my answer.  Taking a step back for a minute, let's start with the settings being referenced that are currently found in the WooCommerce Settings:

<img width="645" alt="Image 2020-01-13 at 1 39 55 PM" src="https://user-images.githubusercontent.com/1429108/72282271-48f7e580-360a-11ea-9d15-a1e87c5d6084.png">

Assuming we want to keep and respect these global settings. Here's how I think things should work (and this varies from my original post in here):

### 1. The current settings should be the global _default_ for the settings in the new cart block.

In other words, whatever the merchant has selected in the WooCommerce settings should be what the block defaults to when it is first loaded.  However, once the block is saved, the settings are specific to the block.  Why? The default cart shortcode/page will still be available to users and the only way for them to modify these settings for the _default_ cart shortcode/page will be through the existing settings. So until the new block is a complete replacement for the old cart, we have to keep existing settings.

### 2. "Hide shipping costs until address is entered" operates independently of the other setting so should be available no matter what.

I hadn't tested things with the original cart when I made my initial comment.  I see that the ship calculator provides a way to add an address, but if a shipping zone has a flat shipping fee (regardless of address) then that might still display with the calculator disabled _unless_ the "requires address" option is checked. 

So, based on that I've revised my original suggestion and I think we should keep these options independent.

### 3. We can't really hide these settings if there are no physical products in the store because the merchant might add physical products after they've set-up their cart. 

But should we hide these options if they don't have any shipping zones configured?  Should they just be disabled with some sort of messaging for why they are disabled?

cc @garymurray and @Aljullu  what are your thoughts on this?

**Comment by Aljullu** [comment]
> But should we hide these options if they don't have any shipping zones configured? Should they just be disabled with some sort of messaging for why they are disabled?

@nerrad I don't think they need to be hidden or disabled. Merchants might be customizing their Cart block before setting the shipping zones.

However, I agree adding a noticed might be useful, something similar to what we have in the Reviews blocks:
![imatge](https://user-images.githubusercontent.com/3616980/72339421-7ace8200-36c6-11ea-911b-56f284595111.png)

**Comment by garymurray** [comment]
> But should we hide these options if they don't have any shipping zones configured? Should they just be disabled with some sort of messaging for why they are disabled?

If a customer has not setup shipping options - we currently show this:

<img width="592" alt="Screenshot 2020-01-14 at 13 03 42" src="https://user-images.githubusercontent.com/10805911/72346707-642c2900-36ce-11ea-948e-4597b09c055c.png">

Which I think is fine - I think unless we have some global setting where someone says they are only ever selling digital goods we can't remove that section entirely as the majority of stores sell physical goods which require shipping.

@Aljullu are you suggesting we also add a notice above the actual block settings to indicate they are disabled?

**Comment by Aljullu** [comment]
> If a customer has not setup shipping options - we currently show this:

@garymurray but that screenshot is from the _Checkout_ block, right? In the _Cart_ block we don't have any indication if there are no shipping options.

My idea was to add the notice in the _Cart_ block editor sidebar before or after the settings related to the shipping options.

**Comment by garymurray** [comment]
> @garymurray but that screenshot is from the Checkout block, right? 

🤦my bad....

If the cart/checkout process is actually reliant on the store owner having to actually setup a Shipping option - we should perhaps pull that same notice in the cart - so like this:

<img width="403" alt="Screenshot 2020-01-14 at 13 39 05" src="https://user-images.githubusercontent.com/10805911/72348876-41504380-36d3-11ea-8c88-a8a2a3ae825a.png">

Which would then mean that no settings are shown in the sidebar - if they can actually still have a functioning cart and checkout, then we could go with the notice like you shared - so something like this:

<img width="363" alt="Screenshot 2020-01-14 at 13 48 55" src="https://user-images.githubusercontent.com/10805911/72349577-a9ebf000-36d4-11ea-838b-53bbb3b6d963.png">

**Comment by nerrad** [comment]
I think it's important to remember what I wrote [here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/1488#issuecomment-573814057):

> We can't really hide these settings if there are no physical products in the store because the merchant might add physical products after they've set-up their cart.

Unless it's considered acceptable that merchants are expected to remember to go back to their cart and update it with these options if they add physical products...I think we always need to have these options visible and usable.  The need for the notice is mostly around information ("Hey! these options are set, but there won't actually be any shipping information in the cart until you configure shipping zones").

Also, I think we need to be a bit more specific about the language, it's shipping _zones_ that need configured right? I'm assuming shipping doesn't come into play until _at least one zone_ is configured? It sounds kind of odd to say something like "Options are disabled here until you configure options" 🤔

**Comment by garymurray** [comment]
@nerrad great feedback

>  Unless it's considered acceptable that merchants are expected to remember to go back to their cart and update it with these options if they add physical products...I think we always need to have these options visible and usable.

Agree.

I think we could possibly go with something along these lines then based on your feedback and revised copy:

![no shipping options enabled](https://user-images.githubusercontent.com/10805911/72364071-c9dbdd80-36ed-11ea-81e3-1fcba20a4763.jpg)
