### ISSUE TITLE
Cart Block (frontend context): Wire up cart block to use new endpoints

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#1489]
The following user stories should be fulfilled with this issue:

- [x] The cart will be automatically updated when a shopper removes an item from the cart
 - [x] The cart will be automatically updated when a shopper updates an item quantity
 - [x] The shopper can see how many products are in stock when there are 3 products or less in stock (scarcity label)
 - [x] The cart will be automatically updated when a shopper changes the shipping option
 - [x] The shopper can change the shipping address in the cart (if shipping calculator is turned on)
 - [x] The cart will be updated when the shopper changes the shipping address (if the shipping calculator is turned on)
 - [x] The shopper can add a coupon code in the cart (if coupon codes are turned on)
 - [x] The cart will be updated when the shopper adds a valid coupon code (if coupon codes are turned on)
 - [ ] The cart layout is responsive and it should be adapted to the screen width/height
 - [x] Cart line item description should be truncated if necessary (see #1552)

The above can be done in smaller pulls where possible.

**Comment by haszari** [comment]
I've started work on this in #1741. Added a bunch of issues for related follow up work (some of these relate to user stories in description).

- Correctly handle empty cart - there is an issue with empty cart component on front end #1743
- Show progress/loading spinner while cart API data is loading #1744
- Show discount on sale line items #1745
- Tax (this may be working, need to test more)
- Truncate long cart item descriptions #1590 (?) 
- Manage cart items - remove, change quantity #1746
- Handle coupons - add/remove coupon #1747
- Handle shipping #1561 
- Show correct cart total (`$36717` for my `$717` worth of products!) #1748
- Mobile layout may still need work #1539

**Comment by haszari** [comment]
I'm thinking we can close this issue – we've implemented all the key work. There are some follow ups (e.g. theme/styling polish) which we're tracking in separate issues. 

@Aljullu can you review the shipping related checklist items and tick them off if you're happy?

@nerrad Assuming the shipping stuff is all implemented are you happy that we close this issue?

**Comment by nerrad** [comment]
Yup!

**Comment by Aljullu** [comment]
> @Aljullu can you review the shipping related checklist items and tick them off if you're happy?

Done! I checked three checkboxes from the list above.

**Comment by nerrad** [comment]
Since remaining todos in this list have issues, I'm going to go ahead and close this. Thanks!
