### ISSUE TITLE
Filter by Price Block: Product list not updated on product price update

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce-gutenberg-products-block#1494]
**Describe the bug**
Maybe this is a caching issue, but when a product price gets updates, moving sliders back and forth does not reflect the latest price changes.

**To Reproduce**

1. Open a page with a product listing and price filter.
1. Filter by price using the range $0 – $20 and note the products that are present.
1. In a separate tab, open the admin, find a product X that is outside the $0-20 range, and change its price to be under $20.
1. Go back to the product listing, change the price filter range to else, and let the product list update.
1. Then change the price filter back to $0-20 and note that product X, which is now priced under $20, is not included in the list.

**Expected behavior**
List of products includes products within the given price range and no other ones.

**Screenshots**

**WordPress (please complete the following information):**

* Core version: [e.g. 5.2.2]
* WooCommerce version: [e.g. 3.9 rc.2]
* Site language: En
* Any other plugins installed:
```

Active plugins (7)
--
Query Monitor |   | by John Blackbourn – 3.4.0
WooCommerce PayPal Checkout Gateway |   | by WooCommerce – 1.6.17 – 1.6.18 is available – Not tested with the active version of WooCommerce
WooCommerce PayPal Powered by Braintree Gateway |   | by WooCommerce – 2.3.3 – 2.3.6 is available – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway |   | by WooCommerce – 4.3.1 – Not tested with the active version of WooCommerce
WooCommerce - ShipStation Integration |   | by WooCommerce – 4.1.30 – Not tested with the active version of WooCommerce
WooCommerce |   | by Automattic – 3.9.0-rc.2
WP Crontrol |   | by John Blackbourn & crontributors – 1.7.1


Inactive plugins (4)
--
Akismet Anti-Spam |   | by Automattic – 4.1.2
GHActivity |   | by Jeremy Herve – 2.0.0-alpha
Hello Dolly |   | by Matt Mullenweg – 1.7.2
W3 Total Cache |   | by BoldGrid – 0.11.0


```

**Desktop (please complete the following information):**

* OS: MacOS
* Browser: Chrome
* Version: 78

**Additional context**

**Comment by nerrad** [comment]
Ya it's a caching issue but client side not server side. The All Products block caches products locally for each set of query parameters (including paging etc). So if the price changes while someone is viewing the product via the block, they will not get the updated price until they refresh the entire view or view the single product view for the product.

Some options:

- don't cache client side the list of products and always make a request on parameter changes (could be a hit to server).
- add a freshness feature to the client side data store that will automatically refresh queries after a set time (won't completely eliminate staleness but does help reduce it).
- implement a polling feature (via special endpoint) that can be used to check if there's been updates to any products while the block is being viewed and if there has, invalidate the client cache.

I'm wondering how much of a real world problem this will be.  Is it typical for most stores to be changing prices often?  Should there be an option for stores to toggle client caching on or off for the All Product block (for the few stores that do/are changing prices frequently)?

Also how critical is this for wc3.9 release?  What option we choose can be affected by priority.  I don't think it's critical myself but don't want to presume.

cc @mikejolley and @Aljullu can you add some feedback here?

**Comment by senadir** [comment]
This bug doesn’t seem to be that high in priority but fixing it may introduce serious side effects or bugs, I would say we keep this to a future release for now

**Comment by Aljullu** [comment]
If I understand it correctly, when refreshing the page all client caches are invalidated, right? So the user would only see old prices as long as they don't reload. Even if not ideal, I think most users will understand that not refreshing the page keeps old prices.

> Some options:
> 
> - don't cache client side the list of products and always make a request on parameter changes (could be a hit to server).
> - add a freshness feature to the client side data store that will automatically refresh queries after a set time (won't completely eliminate staleness but does help reduce it).
> - implement a polling feature (via special endpoint) that can be used to check if there's been updates to any products while the block is being viewed and if there has, invalidate the client cache.

From these options, I think the best one would be the third but I think it might be over-engineering while the first one is simpler but has performance drawbacks, so I would go for the second one, which is a middle point between the other two and I'm pretty sure good enough in most cases. Otherwise, the idea from @senadir also sounds like a good approach.

But in the case we go for an option to update product prices without reloading the page, we must make sure prices are only updated on user interaction (change filters, order or pages). I wouldn't like to see a store page and suddenly one of the products disappear from the page because its price changed and now it's in another page.

In any case, I don't think it should block WC 3.9.

**Comment by mikejolley** [comment]
Yes this is a bug, however, the client side caching is super important, and it does feel like an edge case--it only affects visitors with a session who fail to refresh a page. I don't think that would be a concern for busy stores and it only affects discoverability temporarily.

IMO not a blocker.

Of the solutions, I prefer these 2:

> add a freshness feature to the client side data store that will automatically refresh queries after a set time (won't completely eliminate staleness but does help reduce it).

> implement a polling feature (via special endpoint) that can be used to check if there's been updates to any products while the block is being viewed and if there has, invalidate the client cache.

However, polling has the same limitation as the freshness one; you're relying on the client to poll at certain intervals, so there are still periods of time where data will be stale. Therefore given both options, the freshness idea is probably easiest to implement with say a timeout of 5/10 mins.

To prevent large API requests for stale data that isn't actually stable, I wonder if we could implement last-modified or eTag headers on the server side (similar to the hash idea from @senadir ) so full requests are not made unnecessarily. I've not done this before but it sounds promising:

- https://www.kennethlange.com/avoid-data-corruption-in-your-rest-api-with-etags/
- https://jakearchibald.com/2016/caching-best-practices/

**Comment by senadir** [comment]
We can also relay on the browser to do the invalidation for us since cache policies are natively supported

* https://web.dev/stale-while-revalidate/
* https://tools.ietf.org/html/rfc5861#section-3

**Comment by nerrad** [comment]
> when refreshing the page all client caches are invalidated, right?

Correct. It just surfaces more readily because the user is kept on the page longer while browsing results using all products block.

I like some of the ides being discussed here, but imo cache busting (and the related etag idea) are more important when there's risk of data corruption because of data manipulating happening on concurrent requests (which is not the case here). 

Thanks for all the feedback folks, I'm going to put this in the backlog as it looks like we're all in agreement it's not a blocker for WC 3.9.

**Comment by peterfabian** [comment]
Thanks for the discussion and looking into the report, agreed this should not hold a WC core release now. It's an interesting balance between fresh data and performance implications.
