### ISSUE TITLE
All Products block: sync ordering block option vs dropdown

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce-gutenberg-products-block#1496]
**Is your feature request related to a problem? Please describe.**
The Order Products By block option should be reflected in the dropdown on the block itself.
![screenshot-2019-12-23-at-15 17 23](https://user-images.githubusercontent.com/2207451/71814247-15521400-307c-11ea-92da-8f4073492397.png)

ref: pb22l9-5F-p2, #comment-283

**Additional context**
Discovered while testing 3.9 by @josemarques

**Comment by garymurray** [comment]
This makes sense to me.
