### ISSUE TITLE
All Products block: Button line break enhancement

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce-gutenberg-products-block#1497]
**Is your feature request related to a problem? Please describe.**
Button breaks in a weird form in 2019 when the copy is long.
![screenshot-2019-12-23-at-11 42 43](https://user-images.githubusercontent.com/2207451/71814352-6a8e2580-307c-11ea-9108-a6318b924e18.png)

ref: pb22l9-5F-p2 #comment-283

**Additional context**
Discovered by @josemarques during 3.9 testing.

**Comment by mikejolley** [comment]
This is no longer an issue it appears (the theme was 2020, not 2019), but there may be some styling conflicts between core and blocks. Raising discussion separately.
