### ISSUE TITLE
Filter by Price Block: No filter displayed

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce-gutenberg-products-block#1499]
**Describe the bug**
On a new ephemeral site with WC 3.9-rc.2, products created during Storefront activation, the Filter by price block does not seem to show up at all. Similar behaviour encountered by me and another tester.

Block editor:
![Screenshot 2020-01-06 at 14 05 36](https://user-images.githubusercontent.com/2207451/71819885-a1b90280-308d-11ea-9581-e15ef073dbcb.png)

Frontend:
![Screenshot 2020-01-06 at 14 06 02](https://user-images.githubusercontent.com/2207451/71820500-8e0e9b80-308f-11ea-844e-e00afd81fc35.png)

During rendering, the outline of the block is shown, though:
https://youtu.be/k9TeDpoH4iU

**To Reproduce**

1. Create a new ephemeral site
2. Install WC 3.9-rc.2 via beta tester plugin, install Storefront and let it create products (or import sample products)
3. Create a page with 2 columns, All Products block and Price filter block
4. See the problem (hopefully, I only tried it twice, still have the sites available if needed)

**Expected behavior**
Price filter working.

**WordPress (please complete the following information):**

* Core version: 5.3.2
* WooCommerce version: 3.9-rc.2
* Site language: En
* Any other plugins installed:

```

Active plugins (4)
--
Akismet Anti-Spam |   | by Automattic – 4.1.3
Jetpack by WordPress.com |   | by Automattic – 8.0
WooCommerce Beta Tester |   | by WooCommerce – 2.0.1 – Not tested with the active version of WooCommerce
WooCommerce |   | by Automattic – 3.9.0-rc.2



Inactive plugins (4)
--
AMP |   | by AMP Project Contributors – 1.4.2
Classic Editor |   | by WordPress Contributors – 1.5
Full Site Editing |   | by Automattic – 0.18.2
Gutenberg |   | by Gutenberg Team – 7.1.0


```

**Desktop (please complete the following information):**

* OS: macOS
* Browser Chrome 78

**Additional context**
ref pb22l9-5F-p2, #comment-307

**Comment by peterfabian** [comment]
Not sure if related to https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/1450?

**Comment by nerrad** [comment]
> Not sure if related to #1450?

That or another one of the price filter block fixes released in [2.5.8](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues?q=is%3Aclosed+milestone%3A2.5.8)

WC3.9-rc.2 is bundled with Blocks 2.5.7 so it's missing a number of fixes related to the price filter block.

**Comment by nerrad** [comment]
cc @senadir can you verify that 2.5.8 fixes this please?

**Comment by senadir** [comment]
Yes, #1450 fixes that

**Comment by nerrad** [comment]
Thanks for confirming @senadir !  I'll go ahead and close this issue then.
