### ISSUE TITLE
Implement Feature Gating

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#1500]
As we start building more features in the block plugin, we'll eventually reach the point where we have some in progress (or even experimental work) that will be merged to master, but that we don't want to include in general releases yet.  So it will be beneficial to add to the Blocks plugin something similar to Gutenberg's feature gating (or wc-admin's feature gating).

This is something we could tackle during our cooldown period.

**Comment by senadir** [comment]
Gutenberg current build process excludes whole blocks, this is less problematic than trying to gate certain features within a block, does this feel suitable to us?

**Comment by nerrad** [comment]
> Gutenberg current build process excludes whole blocks, this is less problematic than trying to gate certain features within a block, does this feel suitable to us?

Ya since we're mostly  concerned with exposing blocks prematurely I agree we should focus this feature gating on whether blocks are registered or not.
