### ISSUE TITLE
Quantity selector component for cart line items

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#1521]
The full cart view has a custom control for increasing/decreasing the quantity of a product / line item.

<img width="1263" alt="Screen Shot 2020-01-08 at 8 33 28 AM" src="https://user-images.githubusercontent.com/4167300/71923308-a4346d00-31f1-11ea-8d49-ba94d19c791a.png">

This is similar to a standard number edit / updown control but with custom look & bigger increase/decrease buttons on each side of the value. 

Currently in #1333 there's a temporary component wrapping a `<input type="number>`, used in cart line items. This should be replaced with the new component.

**Comment by senadir** [comment]
Couldn’t find anything in Calpyso for this so I guess it’s worth building from scratch
