### ISSUE TITLE
Create ShippingCalculator component

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#1530]
This component must:
* Allow entering a different address.
* Update the parent component with the introduced address.

_Closed_
![imatge](https://user-images.githubusercontent.com/3616980/72100991-01304000-3324-11ea-8764-809295f83a77.png)

_Opened_
![imatge](https://user-images.githubusercontent.com/3616980/72147999-0df27980-33a0-11ea-98b2-d7eac30f2c96.png)

**Comment by Aljullu** [comment]
@garymurray do we have a design for this? I was looking in Figma and P2s but couldn't find it.

This is how it currently looks in the _Cart_ page:
![imatge](https://user-images.githubusercontent.com/3616980/72101069-2c1a9400-3324-11ea-8c57-310c64d2b952.png)

**Comment by garymurray** [comment]
Shared the design via slack - looks like the initial issue has been updated with the design correct @Aljullu ?

**Comment by Aljullu** [comment]
> Shared the design via slack - looks like the initial issue has been updated with the design correct @Aljullu ?

Yes, I added a screenshot of the design in the description of this issue. Thanks @garymurray!

**Comment by Aljullu** [comment]
@garymurray reviewing this again, should we include the _State_ field or it was removed in purpose? I see the old _Cart_ has it (second selector) but your design doesn't.

**Comment by garymurray** [comment]
@Aljullu we should include it - just an omission my side when mocking it up quickly.
