### ISSUE TITLE
"Checkout Draft" Order Cleanup

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#1542]
Introduced in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/1425, the API creates draft orders during the checkout flow which also help reserve stock during checkout for a customer.

These order ideally should be periodically cleaned up; either using the queue, or cron. An appropriate time needs to be chosen. Implementing the endpoints on checkout should make clearer what time is appropriate.

**Comment by senadir** [comment]
Should we use the same duration of `hold stock` option?

**Comment by mikejolley** [comment]
Good idea @senadir. We just need to ensure if it's set too low, checkout can either renew the hold, or ignore it. Might need some work on client side too?

**Comment by senadir** [comment]
what confuses me till now is Hold stock, does it hold finished orders that are waiting for payment? like check or bank payment or just the orders that are created the instance, you enter your details, like ours. and so, what should we honor.
Default Hold Stock only handles `pending` orders.
