### ISSUE TITLE
Find the best way to load the aliased version of `@wordpress/components` without increasing `cart-frontend.js` size

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#1545]
In parallel, we also need to revert the temporary increase in `cart-frontend.js` bundlewatch size limit introduced in #1544.

**Comment by haszari** [comment]
@Aljullu  is this a dup of #1537 ? 

I see we bumped cart-frontend.js limit for two different reasons, but we probably only need one follow up task to tidy up.

**Comment by Aljullu** [comment]
Yes and no... As I understand it, #1537 is about removing the temporary test data and then lowering the limit. While this issue is about finding a way to load our aliased version of `@wordpress/components` without increasing `cart-frontend.js`'s size (and lowering the bundlewatch limit afterwards).

So I think the two issues are about different things even though both of them will end up in lowering the size limit. So from my point of view, we should re-name the issues to make it easier to differentiate them, but keep both of them open.

**Comment by Aljullu** [comment]
It turns out that all our JS-rendered blocks are depending on external dependencies, up until #1423, they were bundled into each block frontend script. #1544 moved those dependencies into the vendors file, so not loading it made those blocks to fail.

As an example, _All Products_ was not loading because it couldn't find `react-number-format` dependency.

There are several possible solutions to fix it:

1. Make all JS-rendered blocks rely on the `vendors-frontend.js` script for external dependencies.

2. Make all JS-rendered blocks bundle external dependencies into its built file. This is how it is currently in `master`, it has the drawback that for some blocks, like _Cart_ and probably _Checkout_ in the near future, files will become very large (see table below).

3. Keep old blocks like they were (bundling external dependencies into their own file) and only split dependencies for the _Cart_ and _Checkout_ block.

4. Keep everything like it was and instead of splitting all external dependencies, only extract our aliased version of `@wordpress/components` into another file. That means only _Cart_ and _Checkout_ blocks depend on this new file.

I checked the size difference of these solutions to have a better understanding on how they would work in real life:

| File | Solution 1 | Solution 2 | Solution 3 | Solution 4 |
| --- | ---: | ---: | ---: | ---: |
| `active-filters-frontend.js` | 15,7kB | 19,0kB | 18,8kB | 19,0kB |
| `attribute-filter-frontend.js` | 25,9kB | 55,4kB | 54,8kB | 55,4kB |
| `all-products-frontend.js` | 34,0kB | 53,6kB | 53,4kB | 53,6kB |
| `cart-frontend.js` | 107,6kB | 260,3kB | 106,9kB | 168,0kB |
| `checkout-frontend.js` | 26,7kB | 31,5kB | 26,5kB | 31,5kB |
| `price-filter-frontend.js` | 21,4kB | 42,9kB | 42,7kB | 42,9kB |
| `reviews-frontend.js` | 22,0kB | 26,2kB | 26,0kB | 26,2kB |
| `vendors-frontend.js ` | 182,6kB | - | 155,3kB | 94,3kB |

In order to get the table above, I just run `npm run build` with the different proposed solutions. I couldn't find why old blocks files are slightly smaller in solution 3 than 2 --I expected them to be the same. But those inconsistencies are pretty small so they don't affect the big picture.

I'm leaning towards solution 3 or 4, but would like to hear more opinions before taking a decision on this.

**Comment by haszari** [comment]
I made a [chart](https://docs.google.com/spreadsheets/d/1wWDtE325ETO8Lgjj26Li8e2rK0wpDMnQaeC90d4UkG0/edit#gid=0) to visualise those values, and had a stab at naming the different strategies.

<img width="600" alt="Screen Shot 2020-01-14 at 2 38 50 PM" src="https://user-images.githubusercontent.com/4167300/72306441-ef5feb80-36db-11ea-810b-44d5602f0bbc.png">

I'd lean towards (3) cart-checkout lib for now, as it keeps those block scripts relatively under control with a slightly chunkier frontend lib file. However I don't think there's a lot in it, we probably need to consider when these assets are going to be needed and how we can group the library content to keep cart/checkout page load snappy & make best use of caching.

**Comment by nerrad** [comment]
Thanks for taking a closer look at this @Aljullu  (and for the follow up graph @haszari 👍 ).  So if I understand things correctly, with option 2 (bundling with the script), the cart block will be a total of 260+ without additional split out vendors-frontend bundle. But with option 3 the total loaded (including vendors-frontend will be (106+155 = 250) and with option 4 it would be (168+94=262).

The advantage of code splitting is most seen when there's multiple scripts loaded _on the same route_ that share the same assets (to avoid duplication in bundles).  Since it's highly unlikely the cart and checkout block will be output on the same frontend route, I don't think we should do any code-splitting right now.  It feels like premature optimization, and could potentially add _more_ over the wire bytes rather than less.

So my preference would actually be for option 2 right now.  With tree-shaking we should only really be seeing specific components from wp-components get bundled in with bundles, not everything.

**Comment by Aljullu** [comment]
Today @senadir also found out we could reduce `cart-frontend.js` size significantly replacing `<PanelBody>` with something else (p1579082300118300-slack-C8X6Q7XQU). So staying with option 2 for now sounds good to me as well.

We can always revisit it before release if needed.
