### ISSUE TITLE
Shipping rates selector: display products name and quantity before package options

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#1554]
When there are several packages, we need to display the list of products that will be sent with each package.

In the old Cart, this is how it looks:
![imatge](https://user-images.githubusercontent.com/3616980/71722468-29ea9e00-2e29-11ea-801c-616d271da89e.png)

And this is how it looks in the blocks after #1468:
![imatge](https://user-images.githubusercontent.com/3616980/72280524-ccc8c680-3638-11ea-9db1-7845a0005139.png)

**Comment by garymurray** [comment]
@mikejolley @peterfabian is this feature - being able to assign a set of products to a different shipping method something supported by core or does it require an extension?

Just figuring out if we need this for our v1 or if it can be part of a future release. Thanks

**Comment by garymurray** [comment]
Pending feedback on the comment above - this is what I would recommend we go with for these - the design is working on the assumption that the same address is used for both packages and that you cannot enter a custom address for each package:

**Cart page:**

<img width="397" alt="Screenshot 2020-01-14 at 13 30 29" src="https://user-images.githubusercontent.com/10805911/72348365-2df0a880-36d2-11ea-9e72-db5eb3d74415.png">

**Checkout page:**

<img width="600" alt="Screenshot 2020-01-14 at 13 32 59" src="https://user-images.githubusercontent.com/10805911/72348465-66908200-36d2-11ea-8490-9ff63b295948.png">

<img width="362" alt="Screenshot 2020-01-14 at 13 33 15" src="https://user-images.githubusercontent.com/10805911/72348481-714b1700-36d2-11ea-9eae-b92f0d9a70f9.png">

**Comment by senadir** [comment]
> is this feature - being able to assign a set of products to a different shipping method something supported by core or does it require an extension?

So according to Mike, it is something that core supports inside but does not use directly, however, some extensions use.
p1582283498065300-slack-C8X6Q7XQU

**Comment by haszari** [comment]
Here's a sweet blog post that explains the APIs in a bit more detail (thanks @mikejolley !): https://mikejolley.com/2013/12/12/manipulating-shipping-packages-woocommerce-2-1/

There are a few filters that allow extensions to customise packages:

- `woocommerce_cart_shipping_packages`
- `woocommerce_shipping_package_name`
- `woocommerce_package_rates`
