### ISSUE TITLE
Shipping rates selector: add loading state

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#1555]
Shipping rates update dynamically on address change, so we need to have a loading state for it.

![Peek 2020-01-13 19-19](https://user-images.githubusercontent.com/3616980/72280867-a48d9780-3639-11ea-9197-8e2c0cfe9bd3.gif)

Notice this issue is only about adding the loading state (spinner in the GIF above).

**Comment by garymurray** [comment]
I think we can use 1 of 2 options here:

- Keep using the same animation we have in core currently
- Use whatever animation we have implemented with any other existing blocks we have made that have loading animations (if there are any)
