### ISSUE TITLE
Radio Control: radio inputs are not correctly aligned when options are shown in one line

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#1556]
In some occasions we don't have a description for each option, in those cases the `<RadioControl>` options look misaligned (tested with Firefox and Chrome in Linux):
![imatge](https://user-images.githubusercontent.com/3616980/72281195-5200ab00-363a-11ea-97a8-7938269e8920.png)

We might want to load styles from Gutenberg's radio control:

https://github.com/WordPress/gutenberg/tree/master/packages/components/src/radio-control

**Comment by senadir** [comment]
The problem with Radio and Checkbox is that they’re not styled yet at all, and some styles have not been deleted yet, so we should either decide to style them according to design spec, or keep the default browser ones and fix them
