### ISSUE TITLE
shared "badge" UI component

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#1566]
We use a badge style in a couple of places in the cart design, e.g. to alert users to low stock or how much they are saving.

![Screen Shot 2020-01-15 at 1.09.16 PM.png](https://images.zenhubusercontent.com/5ddb3cb39529f10001e618e5/0114cc77-88f7-4097-80c0-7ee4a42f933b)

Currently this is implemented as css styles on each of these elements directly (#1557 #1548), though some of the styles could be shared.

If we use this component in more places in the UI, it might be worth wrapping it up as a component. To do this we'd need to decide on an appropriate interface to standardise look/feel while also provide appropriate flexibility to themes.

FYI @garymurray - is this a "component" in your view (or in figma)? Where else might we use this component in the woo front end UX?

**Comment by haszari** [comment]
As noted by @nerrad in #1557 ..

> We should also review various existing component libraries (calypso, wp-components, wc-components etc) as a part of the new issue to make sure we don't duplicate work unnecessarily.

As we build out our components inside the blocks plugin, we could consider adding storybook support. The goal would be to easily browse components in this repo, and compare with other sources, many of which implement storybook (e.g. https://wordpress.github.io/gutenberg).

**Comment by garymurray** [comment]
> FYI @garymurray - is this a "component" in your view (or in figma)? Where else might we use this component in the woo front end UX?

I would say yes its a component, and it could be used on any page/area that showed a product i.e.

- Full product archive
- Individual product page
- Any of the blocks that pull in products i.e. On sale, best sellers etc

**Comment by nerrad** [comment]
> We should also review various existing component libraries (calypso, wp-components, wc-components etc) as a part of the new issue to make sure we don't duplicate work unnecessarily.

This could also apply to #1600 if we don't find a good option in the other libraries.

**Comment by Aljullu** [comment]
This issue was fixed in #2833 (but the PR was not linked to this issue), the component is named `ProductBadge`:

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/assets/js/base/components/cart-checkout/product-badge/index.js
