### ISSUE TITLE
Create Select component

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#1573]
Part of #1348.

We need an `<select>` field component that can be used in different forms included in the _Checkout_ and _Cart_ block.

**Comment by senadir** [comment]
Depending on the design requirements, does it make sense to build a custom select box or use the native select experience, the best option, if we want to go custom, is the [custom select](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/custom-select-control) in Gutenberg, but I believe our case doesn’t require a custom select box, so the native [select component](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/select-control) should be fine

**Comment by Aljullu** [comment]
That was fixed in #1727.
