### ISSUE TITLE
Followup: Evaluate `short_description` field in `/cart/` route has parity with current cart behaviour.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#1590]
This issue is born out of a follow-up to [some discussion](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/1552#discussion_r366426812) on #1552.

Currently (as of #1552) the `/carts/` endpoint does the following for the `short_description` argument:

```php
$short_description = apply_filters( 'woocommerce_short_description', $product->get_short_description() ? $product->get_short_description() : $product->get_description(), 400 );
$short_description = wp_filter_nohtml_kses( $short_description );
$short_description = strip_shortcodes( $short_description );
$short_description = normalize_whitespace( $short_description );
```

It should be noted that along with applying `woocommerce_short_description` filter to the initial content, this will also have [this filter](https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-data.php#L750-L752) applied (due to the code execution path for `$product->get_short_description()`.

I created this follow-up for us to evaluate:

- Does what we output for the cart short description have parity with what the current cart uses for short description?
- If not, does this matter? Do we need to communicate the difference?
- If not and it matters, then we'll need to modify to align with the current cart.
- Also, the current `store/products` route also returns a `description` field which in turn uses `$product->short_description`.  Since there is obvious similarity here, do we want to align how short_description is prepared for the response for the two routes (will filtering be the same etc)?

**Comment by haszari** [comment]
@nerrad Does this issue include truncating long descriptions? Came up when testing #1741.

**Comment by mikejolley** [comment]
I thought this looked familiar. This was taken care of in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/1639/files

We've gone with `short_description` and `description` for full untruncated data from woo core matching naming, and a separate `summary` field for a truncated version.

`summary` is what you'll need in #1741 @haszari 

Closing this issue.
