### ISSUE TITLE
Implement e2e testing framework.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#1599]
We need to start getting some end to end tests going for our blocks. This issue is to be focused on getting an e2e testing framework in place that we can start building e2e tests against.

- We should be able to use what has been developed for WooCommerce core as a base.
- Will need to prepare at least one set of tests to validate the tests work.
- Will need to document how to run tests locally.
- Will need to wire up to travis for automatically running e2e tests as a part of a job.

**Comment by senadir** [comment]
Does it make sense to break this into smaller issues? the last three points could be done concurrently
