### ISSUE TITLE
Audit and clarify labels

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#1602]
Our list of labels is due for review and clarification. @pmcpinto and I have been working on this and we'll use this issue to track the progress of unrolling it.

* [x] Audit existing labels and plan what gets removed, updated or added.
* [x] Present suggested changes to squad for feedback (via p2)
* [x] Implement changes.

**Comment by nerrad** [comment]
See p90Yrv-1v1-p2 for proposal to team.  I'll give this until Friday and then go ahead and make changes in the repo.

**Comment by pmcpinto** [comment]
Ok thanks for the heads up 👍

**Comment by nerrad** [comment]
Changes are implemented!
