### ISSUE TITLE
All Products: Changing back to "sort by Latest" shows no results

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#1609]
**Describe the bug**
In the front end, the All Products block can show no results when you change the sorting from `Latest` to something else and back again. (See gif below.)

Discovered when testing #1598

**To Reproduce**
1. Ensure you have some products. Publish a post with All Products block and default settings (sort by newness/latest).
2. View the post on front end. Note there are products displayed.
3. Select a different sort from the sort by dropdown, e.g. `Average rating`.
4. Re-select sort by `Latest`. 

- All products shows `No products` and placeholder image for first page of results.
- Other results pages show products as normal.

**Expected behavior**
Show products on first results page, consistent with before switching sort order.

**Screenshots**

![sort-latest-disappear](https://user-images.githubusercontent.com/4167300/72695950-4fa0d280-3b9f-11ea-81a6-3209653c2549.gif)

**WordPress (please complete the following information):**

* Core version: 5.3.2
* Gutenberg version (if installed): Plugin not installed
* WooCommerce version: 3.8.1
* WooCommerce Blocks version: 2.5.10
* Site language: English
* Any other plugins installed: Jetpack 8.1
* Theme: Storefront 2.5.3

**Desktop (please complete the following information):**

* OS: macOS
* Browser: Safari
* Version: 13.0.4 (15608.4.9.1.3)

**Comment by Aljullu** [comment]
> Browser: Safari

To add some more info here: I could reproduce it in `master` with GNOME Web (which uses WebKit, same as Safari), while I was unable to reproduce it with Firefox nor Chrome.
