### ISSUE TITLE
[WC 3.9 rc4]: Sale price display issues - overlaps with "Add to Cart" button if price is below button 

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-gutenberg-products-block#1616]
**Describe the bug**

Sale price display issues - overlaps with the "Add to Cart" button if the price is below the button in the Inner Block. 

**To Reproduce**

1. Create a post or page where you can add blocks;
2. Create a product on sale;
3. Add `All Products` block;
4. Click on the `pencil` icon of the `All Products` block to get to the `Inner Block`;
5. Once in the `Inner Block` - rearrange the blocks as follows:

- Product Image
- Product Button
- Product Rating
- Product Price
- Product Title

![Screen Shot 2020-01-21 at 12 02 18 PM](https://user-images.githubusercontent.com/19143190/72804207-cdb8b400-3c47-11ea-9c31-60650d05caad.png)

6. Save changes of the Inner Block;
7. Update / Publish the page. 
8. Note how the sale price overlaps with the `Add to Cart` button both on the back-end and front-end:

![back](https://user-images.githubusercontent.com/19143190/72804420-399b1c80-3c48-11ea-97d4-dbbc6d87920a.jpg)

![front](https://user-images.githubusercontent.com/19143190/72804434-3ef86700-3c48-11ea-8455-0ebec810ced8.jpg)

**Expected behavior**

I expected for the sale price to have a padding / space above to allow for a proper display of the `Add to Cart` button without overlapping. 

**Screenshots**

See the screenshots above. 

**WordPress (please complete the following information):**

* Core version: 5.3.2
* Gutenberg version (if installed): not installed
* WooCommerce version: 3.9 rc4
* WooCommerce Blocks version: not installed
* Site language: English
* Any other plugins installed: Jetpack by WordPress.com, WooCommerce Beta Tester, WooCommerce Stripe Gateway

**Desktop (please complete the following information):**

* OS: macOS Catalina v 10.15.1
* Browser: Chrome
* Version:  79.0.3945.117 (Official Build) (64-bit)

**Additional context**

N/A.

**Comment by mikejolley** [comment]
This was fixed with https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/1659 where some margin was added to the buttons when not last.

@nerrad I've put #1659 under the fix release milestone. If that's not appropriate let me know or remove.

**Comment by nerrad** [comment]
I think the assigned milestone is great! Thanks 👍
