### ISSUE TITLE
Media queries: Block columns

### ISSUE THREAD

**Issue by jobthomas** [woocommerce/woocommerce-gutenberg-products-block#1619]
**Describe the bug**
When one looks at the responsiveness of Blocks, it looks nice _if_ the store builder has selected 4 columns. However, if the builder has selected 3 columns, this leaves an orphan product hanging:

![](https://d.pr/i/GM6ZXn+)
Link to image here: https://d.pr/i/GM6ZXn.

![](https://d.pr/i/r2mxvf+)
Link to image here: https://d.pr/i/r2mxvf.

Reported here: https://wordpress.org/support/topic/woocommerce-blocks-not-formatting-on-mobile/

**Comment by Aljullu** [comment]
Thanks @jobthomas for creating this issue. However I'm not sure the issue you reported and the one the user was reporting are the same. What makes me think that is that in your screenshot, the first two products (`Beanie with Logo` and `Single`) occupy the entire row width, while in the user screenshot the first two products do not occupy the entire space:
![imatge](https://user-images.githubusercontent.com/3616980/72899783-0085a980-3d27-11ea-8652-4ab0312737bd.png)

So my guess is that the user issue is this one: https://github.com/woocommerce/storefront/issues/1197. We could ask them if they are using Safari, just to confirm it.

In the other hand, the issue you reported seems to be a drawback of responsive product grids introduced in #1066. In the past there were discussions about improving the UI to allow manually setting the number of columns on small devices, I created an issue for it: #1626.

I will proceed closing this issue so we can focus the discussion in #1626 and https://github.com/woocommerce/storefront/issues/1197, but feel free to reopen if I'm missing something.

**Comment by epiclolzhere** [comment]
Hello,

Thank you for your reply.

That is indeed the issue I originalyl reported - and I think Job also highlights an issue - but it is the white space that is the problem.

On ALL dekstop browsers (even chrome dev mode) it works fine.

On ALL mobile browsers (inc. Safari) it does the problem as highlighted - the white space.

Is there a fix for it?

Best,

Oli

**Comment by jobthomas** [comment]
@Aljullu not entirely. I do think that the forum thread is slightly different, but I think the bug/enhancement I reported is still a challenge.

Did you look at the gif here? https://d.pr/i/GM6ZXn

More specifically, this one I think is the culprit: 

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/d6f18e7a86ed37da22445e7052d4cb53acd46afd/assets/js/base/components/product-list/style.scss#L321-L346

I think it's a matter of discussing whether you want to make this transition to 2 columns in this media query. Any product that has an odd number of columns (3, 5, 7, 9) will always have an orphaned product with whitespace next to it in this media query. This doesn't look ideal. 

A few suggestions: 

* Center this orphaned product so the gap doesn't stand out as much
* Skip this media query for odd number of columns

**Comment by Aljullu** [comment]
Thanks for dropping by @epiclolzhere!

> On ALL dekstop browsers (even chrome dev mode) it works fine.

Did you try with Safari or another [WebKit-based browser](https://en.wikipedia.org/wiki/List_of_web_browsers#WebKit-based)? If it's https://github.com/woocommerce/storefront/issues/1197, it only affects WebKit browsers. My guess is that the issue you are experiencing doesn't depend on being on a mobile or desktop but between using one browser or another.

> On ALL mobile browsers (inc. Safari) it does the problem as highlighted - the white space.

Are you using iOS or Android? On iOS all browsers are WebKit-based so if it's https://github.com/woocommerce/storefront/issues/1197, I would expect it to affect you.

**Comment by jobthomas** [comment]
My test was indeed on iOS. So this should fix it, right? (in the next release of SF)? 

https://github.com/woocommerce/storefront/pull/1217

That still leaves my other comment. :D

**Comment by Aljullu** [comment]
> My test was indeed on iOS. So this should fix it, right? (in the next release of SF)?

Correct.

> That still leaves my other comment. :D

You think #1626 is a good summary of it? Feel free to add anything there or create a new issue if you meant something else. :slightly_smiling_face:

**Comment by epiclolzhere** [comment]
Hi  @Aljullu ,

Thanks for getting back to me.

All my devices are iOS, and my desktop is Windows - but used Chrome and Safari on both iOS/MacOS and Windows 10.

At the moment I have just given up using the blocks but desperately need a way to fix it.

Are you and Job saying there is a fix for it? As I cant seem to find one.

Please put the fix here if you know of one - I would be VERY grateful!

Best,

**Comment by jobthomas** [comment]
Yes, it will be fixed in the next version of Storefront. In this pull request: woocommerce/storefront#1217
