### ISSUE TITLE
Change jetpack-autoloader version dependency to range from specific version.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#1625]
## The problem

Jetpack Autoloader is used by @woocommerce/woocommerce-rest-api, @woocommerce/woocommerce, @wocommerce/woocommerce-admin and this project for handling autoloading.  Woo core, and woo-rest-api both pin jetpack-autoloader to a version range (minors) but wc-admin and wc-blocks pin to specific versions.  This introduces the potential for conflicts and inability to pull in either woo blocks or wc-admin into woo core when either blocks or wc-admin don't satisfy the version requirements for either's jetpack-autoloader specific version.  

This complicates the release process because it means when this mismatch happens, the release tag for a project needs to be rebuilt to get in sync with any other dependencies being pulled in.

This will become an increasingly annoying problem as the number of packages pulled into WC core increases.

## The solution

I'm not sure exactly why we are pinning to specific version for a build tool type package but the above problem could be resolved if we set the dependency to a minor range instead of pinning to a specific version. So I suggest that we use `^1.3.0` for our jetpack version range (meaning the latest minor version is used (greater than 1.3.0 and less than 2.0.0)). This will allow for more flexibility when pulled in to woo core.

cc @woocommerce/wc-admin as well for your thoughts on doing something similar for the wc-admin package.

**Comment by psealock** [comment]
Great idea to have cohesion on this by all the repos. wc-admin issue here https://github.com/woocommerce/woocommerce-admin/issues/3617
