### ISSUE TITLE
Product grid blocks: add setting for mobile number of columns

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#1626]
That was discussed in the past but I couldn't find an issue for it (even though there are several related ones: #1060, #1422, #1619).

Product grid blocks allow merchants to set the number of columns, but those are reset by media queries in small viewports without a UI option to change it.

In https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/1060#issuecomment-525895701 there were some suggestions about possible UIs to improve this.

In case we start working on this. It might be worth taking a look at the discussion about responsive controls in Gutenberg: https://github.com/WordPress/gutenberg/issues/13363.

**Comment by jobthomas** [comment]
As mentioned in #1619, it does seem like there's something created for this:

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/d6f18e7a86ed37da22445e7052d4cb53acd46afd/assets/js/base/components/product-list/style.scss#L321-L346

However, in this case the media query for `480px-600px` defaults to a 2 column approach as an intermediate step towards a 1 column approach in 480px or lower. That is a great approach for even-numbered columns I think, but not ideal for odd-numbered columns (3, 5, 7, 9 in this case). 

As you mentioned above, the comment suggesting this approach might provide a good solution:

![](https://user-images.githubusercontent.com/3411173/63887646-19657b00-c992-11e9-834c-3e5f30cf8f07.JPG)
Link to image here: https://user-images.githubusercontent.com/3411173/63887646-19657b00-c992-11e9-834c-3e5f30cf8f07.JPG.

However, it seems that the current approach is to work with 3 media queries (0-480, 480-660 and 660+) so I'm wondering if that would be addressed properly in this approach as well.

**Comment by squill** [comment]
I'd like to add my thoughts as a non-developer who builds his own Woo sites.

I am using WooCommerce Blocks on the homepage, with two rows of five across.

In the WooCommerce category pages I have got the images on the grid to display five across on desktop and two across on mobile.

Customers tell me they like that. They prefer two images across the screen on mobile. They think one image across on mobile is less attractive because it means more scrolling.

I would like to implement two across on mobile with WooCommerce Blocks but I don't know how to do it. If there is some CSS I can add, then I am OK with that. I looked at the CSS above but I cannot pick out what I should do.

Thank you,
David

**Comment by Aljullu** [comment]
@squill you could try adding a CSS snippet like this:

```CSS
.wc-block-grid.has-5-columns .wc-block-grid__product {
	float: left;
	margin: 0;
	max-width: 50%;
	padding: 0;
}
```

Notice you might need to change `.has-5-columns` for a different class depending on the number of columns it has on desktop (`.has-3-columns`, `.has-4-columns`, etc.).

Hope that helps! Notice this CSS snippet might break in the future when we update the base CSS, but it might be useful as a work-around for now.

For future support questions asking in the [WordPress.org forums](https://wordpress.org/support/plugin/woo-gutenberg-products-block/) is usually better so you get faster/better answer. Sometimes in GitHub questions might get lost since it's mostly used for development.  :slightly_smiling_face:

**Comment by squill** [comment]
@Aljullu Thank you. That works perfectly. I hope you don't. mind that I didn't ask on the forums because I saw that the thread had been closed after someone asked about two images view on mobile [here](https://wordpress.org/support/topic/products-by-category-or-tag-in-mobile-view/).

**Comment by nerrad** [comment]
I'm going to close this issue for a few reasons:

- The responsive control features should be provided by Gutenberg. Along with the explorations in https://github.com/WordPress/gutenberg/issues/13363, there's also some in https://github.com/WordPress/gutenberg/issues/19909. Once GB exposes these controls for use/extending then we can consider implementing them in our blocks.
- Workarounds for themes/sites that want them right now are possible by using existing CSS.
- There's some unknowns still about work we may be doing on our roadmap that will change how `ProductGrid` blocks are rendered and this will impact what controls we expose and how they are applied.
- There's nothing actionable on this in the short-term.

**Comment by erikdemarco** [comment]
> @squill you could try adding a CSS snippet like this:
> 
> ```css
> .wc-block-grid.has-5-columns .wc-block-grid__product {
> 	float: left;
> 	margin: 0;
> 	max-width: 50%;
> 	padding: 0;
> }
> ```
> 
> Notice you might need to change `.has-5-columns` for a different class depending on the number of columns it has on desktop (`.has-3-columns`, `.has-4-columns`, etc.).
> 
> Hope that helps! Notice this CSS snippet might break in the future when we update the base CSS, but it might be useful as a work-around for now.
> 
> For future support questions asking in the [WordPress.org forums](https://wordpress.org/support/plugin/woo-gutenberg-products-block/) is usually better so you get faster/better answer. Sometimes in GitHub questions might get lost since it's mostly used for development. slightly_smiling_face

Using this ome part looks weird if the product count is odd numbered. the left side will be empty
