### ISSUE TITLE
Grid blocks that were already published grew from 1 to 3 rows

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#1637]
**To Reproduce**
1. `git co f4d9f7de648821b87019f021394a31c7b141f66f`.
2. Create a post with a _Top Rated Products_ block.
3. Publish it.
4. Notice there is only one row.
5. `git co master`.
6. Reload the post.
7. Notice there are three rows.

I imagine that's related to #1613 cc @mikejolley.

**Comment by mikejolley** [comment]
We agreed that these blocks would change and only handled deprecation in all products block. @nerrad correct? It should be documented in readme.

**Comment by nerrad** [comment]
> It should be documented in readme.

I also think it's a significant enough change that it should be documented in release notes and for Woo Support (close to release) as it could come up when released.

**Comment by Aljullu** [comment]
Oh ok, I missed that. Will close this issue then. :+1:
