### ISSUE TITLE
Disable issue-label-bot

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#1643]
From p90Yrv-1v1-p2#comment-3308:

> It has been very imprecise for my experience and if we get the habit to tag all issues, it shouldn’t be necessary. For issues created by contributors, they still need triaging so I don’t think the bot adds anything.

So if nobody of the team has anything against it, we should disable `issue-label-bot`,

**Comment by nerrad** [comment]
@mikejolley can you take care of this please?  It doesn't look like I have the ability to disable/remove integrations: 

<img width="955" alt="Image 2020-01-24 at 2 06 55 PM" src="https://user-images.githubusercontent.com/1429108/73096567-19bb6100-3eb3-11ea-8aa7-4fff26a0a2de.png">

_As an aside_ Would it be possible for me to get more permissions in the Woo org so I can approve/remove/update integrations (we can take this question to internal team channels if necessary).
