### ISSUE TITLE
Consider enabling some eslint-plugin-wpcalypso rules

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#1678]
In #1672 we fixed an issue where we were using three dots (`...`) instead of an ellipsis (`…`) in a user-facing string. It turns out, Calypso has a ESLint rule to catch this kind of mistakes: `wpcalypso/i18n-ellipsis`.

This issue is about enabling that rule and consider enabling some more from [`eslint-plugin-wpcalypso`](https://github.com/Automattic/wp-calypso/tree/master/packages/eslint-plugin-wpcalypso).

**Comment by nerrad** [comment]
Keep in mind we have a bunch of i18n related rules now running in our repo as a result of the latest `@wordpress/eslint-plugin` ruleset. So it's possible this issue might not even be needed.

**Comment by Aljullu** [comment]
Ah... I missed that, thanks @nerrad! `@wordpress/eslint-plugin` has `@wordpress/i18n-ellipsis` which does exactly the same as `wpcalypso/i18n-ellipsis`.

`eslint-plugin-wpcalypso` has some rules which are not in `@wordpress/eslint-plugin`, but some of them are not relevant to us. I think we can close this issue and open new ones if we ever feel we need a new ESLint rule.
