### ISSUE TITLE
404 on `post-new.php`

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-gutenberg-products-block#168]
**Describe the bug**
When opening up the editor on an existing post, or a brand new post, the following 404 is being shown in the console:

![image](https://user-images.githubusercontent.com/22080/49236323-bb7b1700-f3b0-11e8-9aec-953d17394fa5.png)

**To Reproduce**

1. Open the editor on `master`
2. See the error

**Comment by ryelle** [comment]
I can't replicate this, and I don't see any reference to `woocommerce-product-search` in this project– are you sure this plugin is causing it?

**Comment by timmyc** [comment]
🤦‍♂️ indeed it was another extension on my site. Nothing to see here folks, move along :)
