### ISSUE TITLE
Filter blocks (editor): <textarea> has role="button", but it's not allowed

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#1681]
![imatge](https://user-images.githubusercontent.com/3616980/73441278-04cb4b80-4353-11ea-8e93-26d1c8e11877.png)

The `<textarea>` used for the title has a `role="button"`, but that's not a valid role value for a `<textarea>` element.

**Comment by mikejolley** [comment]
This appears to have been fixed upstream.
