### ISSUE TITLE
All Products (editor): 'Cancel' button doesn't pass WCAG AAA: color contrast

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#1688]
![imatge](https://user-images.githubusercontent.com/3616980/73461387-5935f180-437a-11ea-9e36-ccb1a940d498.png)

Text color is `#005D8C` and background `#F3F3F4`. That combination doesn't pass the WCAG AAA color contrast test for normal text:

https://webaim.org/resources/contrastchecker/

**Comment by nerrad** [comment]
We should make sure we're using the same colors as elements elsewhere in the GB ui/ux. So that would mean changing our background if needed.

**Comment by frontdevde** [comment]
Closing as this issue as the link is now displaying on a white background instead of a grey one, thus negating the original issue.
