### ISSUE TITLE
All Products Block: Order Products by Low to High not working

### ISSUE THREAD

**Issue by ldr2273** [woocommerce/woocommerce-gutenberg-products-block#1693]
**Describe the bug**
When using the All Products Block, ordering products from low to high does not render the correct results.

**To Reproduce**

1. Add the All Products Block to your page. 
2. Edit Block and Order Products By `Price - low to high`
3. Results are not in the correct order:

![low to high](https://d.pr/i/g5Zzky+)
Link: https://d.pr/i/g5Zzky

![front end](https://d.pr/i/gqlTOZ+)
Link: https://d.pr/i/gqlTOZ

Tested with latest Storefront & WC active.

**Comment by nerrad** [comment]
Hi @ldr2273 👋 Thanks for reporting this!  Would you be able to fill in a bit more details about the site that you have this setup on? I'm unable to reproduce this so it might be something with how things are configured for product setup.

- Are there other plugins or woo extensions active that hook into WooCommerce queries?
- Are any of the products in your screenshot complex products (variable, grouped etc) with various prices?
- How are taxes setup on the site? Is it configured to save prices with taxes applied or not applied? Is it configured to display prices with taxes or without taxes? Are all the products displayed configured to be taxable?

cc @mikejolley can you think of any other things that could help narrow down what's happening here?

**Comment by mikejolley** [comment]
Sorting is done exclusively using the lookup table; since this is working for me also, it's the most likely culprit. This can happen after an import if the data is not regenerated I think.

You should go to WC > Status > Tools > Product lookup tables "Regenerate"

This will queue up a regeneration of product data and should help.

**Comment by ldr2273** [comment]
Thanks @mikejolley. That did the trick, and definitely good to know!

I'm closing this now, as this isn't a bug.
