### ISSUE TITLE
Category Selection: Need designs for empty & loading states

### ISSUE THREAD

**Issue by ryelle** [woocommerce/woocommerce-gutenberg-products-block#170]
The possible "empty" states are:

- Waiting for categories to load (we could use `<Spinner />`)
- There are no categories on the site
- The user has searched for categories, but none match

Currently we just have a simple "no results found" message for the last, otherwise we don't do anything.

![49188490-f477a500-f338-11e8-8537-e24ef7b5ca25](https://user-images.githubusercontent.com/541093/49238539-9d241400-f3ce-11e8-969c-8255da0622f0.png)

**Comment by LevinMedia** [comment]
One other possible senario is the user hasn't added any products to their store, either.

**Comment by ryelle** [comment]
Huh, true– I was only thinking for the category selection, but we'll need that as well.
