### ISSUE TITLE
Category Block: Clicking "Done" should open the layout panel

### ISSUE THREAD

**Issue by ryelle** [woocommerce/woocommerce-gutenberg-products-block#171]
From #166 

> Once the user clicks "done" on the setup screen, can you open the layout setting container by default?

We could have Layout open by default always, which would make more sense during "edit mode" too (then there aren't two category selections on screen). Or have Layout open during edit mode and the categories settings open on preview?

Tracking where the user came from (ie, "they just clicked done, and are seeing the preview" vs "they were on another block and clicked into this block") probably won't work.

Thinking about the flow:

- User adds block, attribute initializes as "in edit"
- User clicks Done, attribute sets to "left edit", and layout opens
- at some point the attribute needs to set to "in preview", but if we do that when the preview loads, it'll trigger a re-render and the layout section will close & categories will open.

**Comment by LevinMedia** [comment]
> We could have Layout open by default always

Like that! Lets do it.
