### ISSUE TITLE
Category Block: Don't automatically save category changes in edit mode, add cancel button

### ISSUE THREAD

**Issue by ryelle** [woocommerce/woocommerce-gutenberg-products-block#172]
From #166 

> We're now aligning the Done button right and including a cancel link so that folks aren't forced to save changes.

Currently all category selections are automatically applied & saved to the block, which works for both the sidebar UI and edit mode UI. If I understand correctly, we want to add a "cancel" button to just the edit mode, and cancelling should reset to the previous selected categories. ie, I select "Shirts", then go to edit mode, change my selection to "Shoes", but hit cancel – the block should still be showing products in "Shirts".

I'm assuming the same is _not_ true for the sidebar, there is no concept of cancelling changes in the sidebar because they live-update. The only possible issue here is that the sidebar UI and edit mode UI can both be on the screen at the same time, and having it save real-time means your changes to edit mode are reflected in the sidebar and vice-versa. Looking at #171 we could show Layout open while in edit mode, but it's possible a user would open the Product Category setting anyway.

The other issue (code-wise) is that we now have two different functionalities when clicking a category, but both UIs use the same base component, which will add complexity to the components.

Does this sound right, @jameskoster ?

**Comment by jameskoster** [comment]
Yup, all sounds correct. 

This functionality is coming to core. We just need to keep an eye on [this](https://github.com/WordPress/gutenberg/issues/12401) issue and adopt the feature when it's ready.
