### ISSUE TITLE
All Products & Filters: hidden products are still displayed

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#1720]
**To Reproduce**
1. If you use the placeholder products, you can directly modify _Sunglasses_ and set their _Catalog visibility_ to _Hidden_ (in the _Publish_ box).
![imatge](https://user-images.githubusercontent.com/3616980/74233524-23becb80-4ccb-11ea-94e9-3e82a7e8d553.png)
2. Create a page with the _All Products_ & filter blocks.
3. Preview it in the frontend and notice the price slider goes up to `90` and sunglasses are still displayed.
![imatge](https://user-images.githubusercontent.com/3616980/74233665-6680a380-4ccb-11ea-863d-2d87759bac45.png)
4. Go to your _Shop_ page and notice the price slider goes up to `60` and sunglasses are not displayed.
![imatge](https://user-images.githubusercontent.com/3616980/74233706-7a2c0a00-4ccb-11ea-842f-89f4bb313ceb.png)

That's because `Sunglasses` cost 90: they are shown in the _All Products_ block but hidden in the _Ship_ page.

**Expected behavior**
Behavior should be consistent between the _All Products_ block and the _Shop_ page.

**Comment by nerrad** [comment]
@Aljullu, in your opinion do you think this is something we should line up for a patch release to WooCore 4.0?

**Comment by Aljullu** [comment]
@nerrad I think it would be a good idea. We didn't get any user reports regarding this, so I don't think it's a very used feature, but still I think it would be worth fixing it in a 2.5.x release so it can be merged into 4.0.
