### ISSUE TITLE
Top Rated Products block shows ratings as text in editor

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#1733]
**Describe the bug**
In the block editor, the Top Rated Products is showing reviews as text, e.g. `Rated 5.00 out of 5 based on 1 customer rating`. This is inconsistent with the front end for this block, and other rating blocks - all usually display ratings as filled stars.

Discovered during testing of Storefront 2.5.4.

Editor:

<img width="914" alt="Screen Shot 2020-02-14 at 12 27 16 PM" src="https://user-images.githubusercontent.com/4167300/74487886-8a3f2600-4f25-11ea-8829-806ee3724653.png">

Compare with same block on front end:

<img width="583" alt="Screen Shot 2020-02-14 at 12 30 03 PM" src="https://user-images.githubusercontent.com/4167300/74487964-bd81b500-4f25-11ea-8d79-6700c17f2911.png">

**To Reproduce**
1. Ensure you have some products and some reviews.
2. Add a `Top Rated Products` block to a page or post.
3. Compare editor and front end view.

**Expected behavior**
Reviews consistently display as filled stars in editor and elsewhere.

#### Environment
**WordPress:**

* Core version: 5.3.2
* Gutenberg version (if installed): n/a
* WooCommerce version: 3.9.2
* WooCommerce Blocks version: n/a

Reproduced with Storefront 2.5.4 and 2.5.3 and Twenty Twenty.

**Desktop:**

* OS: macOS
* Browser: Safari 13.0.5 (15608.5.11)

**Comment by nerrad** [comment]
@haszari I'm unable to reproduce this using the latest master with either Storefront 2.5.4 or Twenty-Twenty active:

<img width="1857" alt="Image 2020-02-26 at 10 17 44 AM" src="https://user-images.githubusercontent.com/1429108/75358864-8d210b80-5881-11ea-9d1d-ef44d7e5704f.png">

<img width="1782" alt="Image 2020-02-26 at 10 19 40 AM" src="https://user-images.githubusercontent.com/1429108/75358890-93af8300-5881-11ea-9e06-d92e7ae0c532.png">

Is it possible there is some other WooCommerce setting or plugin affecting this or maybe some custom styles?

**Comment by haszari** [comment]
Thanks for checking @nerrad. This is a bug in the version of blocks in WooCommerce core.

I retested this with WordPress 5.3.2 and WooCommerce 4.0.0-rc.1, and I see the fix is included in upcoming core release - so closing :). (Bug is still present in WooCommerce 3.9.2, with no Blocks plugin active.)

**Comment by nerrad** [comment]
> This is a bug in the version of blocks in WooCommerce core.

Ahh!  I missed that, thanks for confirming it's fixed in WC 4.0-rc.1 👍
