### ISSUE TITLE
show spinner / loading state while cart data is loading

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#1744]
Follow up issue to #1741. The cart block pulls the cart data (line items, totals etc) from the Store API. While the cart data is loading, we may need to show a spinner or some kind of loading state.

**Comment by Aljullu** [comment]
In #1764 I'm planning to introduce a wrapper for loading components (`<LoadingComponent>`). Might be helpful for this task as well.

**Comment by mikejolley** [comment]
Ran into this today; it's only needed on initial load (currently returns null).
