### ISSUE TITLE
PHP error when editing a post which contains both blocks: Cart and Checkout

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#1751]
**To Reproduce**
1. Create a post with a _Cart_ block.
2. Add a _Checkout_ block and try to save the post.
3. An error bar will appear saying update failed (`Updating failed.`).
4. Reload the page.
5. A PHP error appears (see screenshot).

**Expected behavior**
There should be no error.

**Screenshots**
![imatge](https://user-images.githubusercontent.com/3616980/74649112-3e87b900-517f-11ea-84ef-6f9a74d6f436.png)

**Additional context**
This happens because both blocks are trying to register the same settings (`shippingCountries` and `shippingCounties`):
* https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/src/BlockTypes/Checkout.php#L54
* https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/src/BlockTypes/Cart.php#L52

Currently, the asset data registry doesn't allow registering data with the same key:
* https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/src/Assets/AssetDataRegistry.php#L250

Some possible fixes:

* Prefix data registered as `cartShippingCountries` and `checkoutShippingCountries`. This way we would prevent conflicts between the data registered by both blocks. To me, that sounds more like a workaround than a real fix. But would avoid having to make any change to the Data Registry.
* Expose a method to retrieve data from the Data Registry. So we could do something like:
```PHP
$shipping_countries = $data_registry->get( 'shippingCountries' );
if ( ! $shipping_countries ) {
	$data_registry->add( 'shippingCountries', ... );
}
```
* Allow overriding data when registered with the same key. So calling `$data_registry->add( 'shippingCountries', ... );` the second time would overwrite whatever was in `shippingCountries`.
* Ignore new data when registered with the same key. So calling `$data_registry->add( 'shippingCountries', ... );` the second time would do nothing but would not throw an error.

cc @nerrad for feedback.

**Comment by nerrad** [comment]
I think we should look at if there's a way we can prevent both checkout and cart block from being added to the same page/post. It's likely there will be additional problems so fixing this one would just be a bandaid. Thoughts?

**Comment by nerrad** [comment]
I get this error when trying to edit a page that just has a cart block in it. So it appears that there's other contexts that can trigger this error thus pushing it up in priority.

**Comment by Aljullu** [comment]
> I get this error when trying to edit a page that just has a cart block in it. So it appears that there's other contexts that can trigger this error thus pushing it up in priority.

I'm unable to reproduce this. I tried creating a post/page with a _Cart_ block and reloading it but there is no way to reproduce the error. I tried saving it in a draft, publishing, making modifications to the empty cart, saving it in combination with other blocks, etc. and it kept working fine. :confused:  Do you have some other steps to reproduce?

> I think we should look at if there's a way we can prevent both checkout and cart block from being added to the same page/post. It's likely there will be additional problems so fixing this one would just be a bandaid. Thoughts?

That would fix the specific problem with the _Cart_ & _Checkout_ blocks, but I wonder if at some point we might want to create new blocks that share the same settings. In that case we would face the same issue.

**Comment by nerrad** [comment]
> I'm unable to reproduce this.

Hmm odd, I can't reproduce now either.  I _think_ what might have happened is I had a page that had both cart and checkout blocks. I trashed it and created a new post with the same title and it received the _same slug_ as the original post (might be a gb bug?). When I viewed the editor, it was loading the old trashed post id (even though I went to edit the new page). Anyways, when I trashed and deleted both and then created another new page I was unable to reproduce.

> but I wonder if at some point we might want to create new blocks that share the same settings.

Hmm, good point. So maybe instead of throwing an error php side, we should just silently discard the overwrite and keep what is existing in the settings?  The other option is to always overwrite?

**Comment by Aljullu** [comment]
> So maybe instead of throwing an error php side, we should just silently discard the overwrite and keep what is existing in the settings?

@nerrad That would work, yes.

Just curious, is the option to expose a method to retrieve data from the data registry not possible? I think a solution like:
```PHP
$shipping_countries = $data_registry->get( 'shippingCountries' );
if ( ! $shipping_countries ) {
	$data_registry->add( 'shippingCountries', ... );
}
```
or:
```PHP
$shipping_countries_exist = $data_registry->is_defined( 'shippingCountries' );
if ( ! $shipping_countries_exist ) {
	$data_registry->add( 'shippingCountries', ... );
}
```
might be more reliable because the consumer will always know if the values were added or not, instead of 'silently discarding', which might be confusing. But I wonder if adding this kind of methods was avoided to prevent bad practices?

**Comment by nerrad** [comment]
> Just curious, is the option to expose a method to retrieve data from the data registry not possible? I think a solution like:

Good idea!
