### ISSUE TITLE
Migrate CountryInput and StateInput to ComboboxControl

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#1752]
Follow-up of #1574 and #1575.

In the legacy country and state controls, you could write the country name in an input field inside the select so it filtered the available options:

![imatge](https://user-images.githubusercontent.com/3616980/72445014-57343600-37b1-11ea-9195-ed852dc6951a.png)

We would like the same for the CountryInput and StateInput components. In order to do that, we should migrate from the `CustomSelectControl` to the `ComboboxControl` that might be introduced in Gutenberg: https://github.com/WordPress/gutenberg/pull/19657.

**Comment by haszari** [comment]
[`ComboBoxControl` has shipped / merged](https://developer.wordpress.org/block-editor/components/combobox-control/), but may not be available in the package yet: https://github.com/WordPress/gutenberg/issues/24443

**Comment by nerrad** [comment]
@Aljullu should the description or the title of this issue be changed to reflect the work you submitted to Gutenberg around related needs we have (I think it was a different component you ended up working on)?

**Comment by Aljullu** [comment]
> I think it was a different component you ended up working on

@nerrad Correct, I worked on `FormTokenField`, the PR can be found here: https://github.com/WordPress/gutenberg/pull/29110. The idea was to mimic the behavior of our `DropdownSelector` component (used in the Attribute Filter block) in Gutenberg's `FormTokenField`. That would allow us to eventually replace `DropdownSelector` with `FormTokenField` (https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3762).

Having said that, I'm not sure `FormTokenField` is the best fit for `CountryInput` and `StateInput`. `FormTokenField` works best when multiple values are allowed, while `ComboboxControl` seems to be better suited when only a single option can be selected like in this case.
