### ISSUE TITLE
Shipping rates are double formated.

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#1756]
**Describe the bug**
When you go to see shipping rates in the cart blocks, prices are double formatted (a 100$ shipping option shows up as $1.00 and a £40 is £0.4.

**Expected behavior**
Price should be £40 or $100.

**Screenshots**
![image](https://user-images.githubusercontent.com/6165348/74672147-f4b5c780-51ac-11ea-804f-32e32b9ad886.png)

![image](https://user-images.githubusercontent.com/6165348/74672137-ee275000-51ac-11ea-966b-aaa6de7844c7.png)

**Comment by haszari** [comment]
Spotted this when testing #1741 :)

<img width="267" alt="Screen Shot 2020-02-18 at 1 52 14 PM" src="https://user-images.githubusercontent.com/4167300/74695159-d2c54f00-5257-11ea-94b0-5419d5b323c3.png">
