### ISSUE TITLE
Switch to Fragment short syntax (from <Fragment> to <>)

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#1761]
There has been some discussion in a couple of PRs in parallel whether we should use `<Fragment>` or `<>`:
* https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/1561#discussion_r369029350
* https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/1736#discussion_r380131662

This issue is to centralize the discussion and, in case we agree to switch from `<Fragment>` to `<>`, enable the appropriate [ESLint rule](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-fragments.md).

Some things to notice:
* We have been consistently using `<Fragment>` until now.
* Gutenberg is inconsistent about this and uses both, `<Fragment>` and `<>`.
* Using `<Fragment>` means we need to import it. Considering we currently have three different packages where it can be imported from (`@wordpress/element`, `wordpress-element` and `react`), that might be a source of unexpected bugs that could be prevented if we used the short syntax.
* [Fragments in React docs](https://reactjs.org/docs/fragments.html)

**Comment by nerrad** [comment]
cc @woocommerce/wc-admin - this is a code style/standard change that we should decide on together so we keep the projects align. For the next cooldown period it'd be good to create an eslint package (extending WP linting package) that standardizes around code styles/standards for the project and then we can just submit pulls to that package.

**Comment by mikejolley** [comment]
Been using `<>` in new PRs since learning about it. The convenience of that is a massive ➕ .
