### ISSUE TITLE
All Products: Ignores Setting - Redirect to the Cart Page on Successful Addition

### ISSUE THREAD

**Issue by jacoswan** [woocommerce/woocommerce-gutenberg-products-block#1766]
**Describe the bug**
When you click on "Add to Cart" from a product in the All Products block, it ignores Add to cart behavior when set to Redirect to the cart page after successful addition, and stays on the page. 

**To Reproduce**

1. WooCommerce » Settings » Products » General
2. Make sure "Redirect to the cart page after successful addition" is checked
3. On the page set as the Shop Page, add an All Products bloc and update.
4. Now, on the Shop page add a product from the All Products block. 
5. Notice it adds the product, but stays on the same page. 
6. Do the same form a product rendered natively to the Shop page. 
7. Notice it adds the product and redirects to the cart page as expected. 

**Expected behavior**
Expected to be redirected to the cart page, given the settings was checked.

**Screenshots**
n/a

**WordPress (please complete the following information):**

* Core version: 5.3.2
* Gutenberg version (if installed): n/a
* WooCommerce version: 3.9.2
* WooCommerce Blocks version: 2.5.11 (but not required for this to work)
* Site language: English
* Any other plugins installed: No

**Desktop (please complete the following information):**

* OS: MacOS 10.15.2 (19C57)
* Browser Firefox 72.0.2

**Comment by nerrad** [comment]
Thanks for the report!
