### ISSUE TITLE
Category Selection: Add hierarchy indication to each term

### ISSUE THREAD

**Issue by ryelle** [woocommerce/woocommerce-gutenberg-products-block#178]
From @LevinMedia 

> Child categories appear indented in the list. 

<img width="670" alt="screen-shot-2018-11-29-at-8-35-31-pm" src="https://user-images.githubusercontent.com/541093/49298237-d91caf00-f48a-11e8-835b-6e2ffb8bf67c.png">

> When searching, the parent category is deemphasized, and separated from the child category with a caret.

<img width="691" alt="screen-shot-2018-11-29-at-8-38-04-pm1" src="https://user-images.githubusercontent.com/541093/49298239-d9b54580-f48a-11e8-8d2b-b7156208f2e8.png">

> When selected the child category is added to the field tokens. The alt text uses the full “parent > child” for accessibility and disambiguation in the rare case that a user selects multiple child categories with the same name.

**Comment by LevinMedia** [comment]
Per a slack convo with @ryelle 

Things are going to get "interesting" when stores have deeply nested categories. To keep things from getting out of hand visually, we're going to truncate the hierarchy when displaying a search result that is more than one child category deep. 

**Deeply Nested Categories:**
<img width="665" alt="screen shot 2018-11-30 at 9 19 03 am" src="https://user-images.githubusercontent.com/4500952/49304571-9bffef00-f481-11e8-80ed-ea03fa8df7c2.png">

**Searching for "Sil"**
<img width="665" alt="screen shot 2018-11-30 at 9 15 48 am" src="https://user-images.githubusercontent.com/4500952/49304878-732c2980-f482-11e8-8993-6430a3d1ce69.png">

The alt text for each item would read the entire hierarchy.
