### ISSUE TITLE
Implement new @woocommerce/e2e-utils package.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#1781]
There is a new `@woocommerce/e2e-utils` package that is published from the WooCommerce core repository. We should implement this to avoid pulling in the entire WooCommerce core repo for e2e-utils.

This will be used for our own e2e tests.

**Comment by senadir** [comment]
This was done as part of updating to npm 7, so it should be an easy couple of lines.
