### ISSUE TITLE
Create notices Context Provider and implement with hook

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#1795]
For the Cart and Checkout blocks (and for anything we build for client side js in the frontend), we will  need to have some sort of notice system for providing informational messages to shoppers as they perform various actions. Some examples of types of notices needed will be:

- Errors (eg. "The coupon you entered is invalid")
- Information (eg. "The coupon you entered has already been applied")
- Success (eg. The coupon you entered was entered successfully)

## Design

I don't know if there's been any design work for notices with the new blocks but I imagine at least initially we'd want to follow the same criteria as the existing notices across Woo? cc @garymurray .  Mike has done a rough implementation in #1790 that looks like it's just using existing styles provided by Woo core. As a first iteration we could probably do the same by just having the notice system implement the same classes.

## Suggested Structure/Logic

Since this might be used in places where we don't need to load `wp.data` I think we should try to implement this using `React.Context`.  So with that in mind here's some ideas on an api that could be built.

### Notices Context Provider.

Something like `<NoticesProvider />` could be exposed that wraps the app. It would have a rough structure like this (note, not all the included pieces here - this is just the main provider example):

```jsx
export const NoticesProvider = ( { className='', createNoticeContainer = true, children } ) => {
  const { notices, dispatch } = useReducer( {
    error: [],
    success: [],
    info: [],
  }, reducer );
  const setNotice = useMemo( () => ( {
    error: ( message ) => void dispatch( addErrorNotice( message ) ),
    success: ( message ) => void dispatch( addSuccess( message ) ),
    info: ( message ) => void dispatch( addInfo( message ) ),
    warning: ( message ) => void dispatch( warning( message ) ),
    clear: ( noticeType = null ) => void noticeType ? dispatch( clear( noticeType )) : dispatch( clearAll() ),
  } ), [] );
  const noticesApi = [ notices, setNotice ];
  <NoticesContext.Provider value={ noticesApi }>
    // Note: NoticeContainer should probably be wrapped in `withComponentId` so that each instance of
    // NoticeContainer in the page will have a unique id on it (in cases where we might have multiple 
    // instances in a tree for more contextual notices.
    ( createNoticeContainer && <NoticeContainer className={ className } notices={ notices } /> )
    { children }
  </NoticesContext.Provider>
}
```

Then this would simply wrap any portion of an app like so:

```jsx
const MyApp = () => {
  return <NoticesProvider>
     <MyApp />
  </NoticesProvider>
};
```

The props coming into NoticesProvider:

| prop | purpose |
| ---- | ----- |
| `className` | Allows consumers to add a custom class to the container if they want to override certain notice styles.
| `createNoticeContainer` | A boolean (defaults true) that allows consuming code to skip the auto-generated notice container and instead generate it's own (using the exposed `notices` data).

Each notice dispatcher (available on the exposed `setNotice` object) would receive a `message` object. This object could have the following shape:

```jsx
const message = {
  content: <Element />,
  dismissible: false,
  autoHide: false,
};
```

| property | value |
| ------ | ------ |
| content | This could be either a string or a react element (the NoticeContainer will need to handle detecting if it's a react element and outputting using `cloneElement( notice.content )` or just output the string in a paragraph container. |
| dismissible | A boolean used to indicate if the notice is dismissible or not |
| autoHide | A boolean used to indicate if the notices autohides or not |

**Note:** I'm not sure about the content property yet. I think it'll be useful for handling scenarios where notices might contain links (and creating an element will be easier for that). For accessibility, we may also want a `speak` property so a we can use the `@wordpress/a11y` `speak` api to announce the notice...

## `useNotices`

This would be a hook that simply exposes the values from the `NoticesContext` anywhere in the tree.  

**Note:** there is a `useCheckoutNotices` hook currently in `assets/js/hooks/checkout/use-checkout-notices` that could be removed in favor of this new hook.

**Comment by nerrad** [comment]
I did do some looking through existing libraries:

### Calypso
[Calypso notices](https://github.com/Automattic/wp-calypso/tree/master/client/notices) js  seems too specific to calypso's use to use here.

### WordPress (Gutenberg)

The `@wordpress/notices` package just registers a data store for notices and as noted in the description, using a data store creates a dependency on `wp.data` that for something like notices might not be needed in all frontend contexts.

The `<Notice />` [component](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/notice) is specific to the wp-admin (which we should totally hook into in that context) but is not really usable for consistent Woo styled notices on the frontend. 

Also the WordPress notice implementation is very ad-hoc and doesn't have a streamlined api for interacting with (you need to pull in a package/global, plus a couple components to use).

### Jetpack

Jetpack has the a [notices](https://github.com/Automattic/jetpack/tree/f7110d2499aacf660e0dd2330bde4ab7f49ee5e8/_inc/client/components/jetpack-notices) library - but it doesn't look like it's available on a package. It also appears to be very specific to jetpack styling/branding. So not suitable for our use.

**Comment by garymurray** [comment]
> I don't know if there's been any design work for notices with the new blocks but I imagine at least initially we'd want to follow the same criteria as the existing notices across Woo? cc @garymurray .

I did design notices as part of the cart/checkout for Storefront:

<img width="1121" alt="Screenshot 2020-02-24 at 11 02 05" src="https://user-images.githubusercontent.com/10805911/75147400-1b1bbb80-56f5-11ea-9bc4-452da0eefd37.png">

Which would have worked like Snackbar component here: https://material.io/components/snackbars/

**Comment by nerrad** [comment]
@garymurray so are you suggesting that we're going to want to use this opportunity to move away from the notice designs currently used on the frontend for WooCommerce and start using snackbar type notifications? If so, 

* can you provide some mockups of handling the various notification types (success, info, warning, error).
* Do we want the same behaviour for all notice types (i.e. should errors be more prominent)? Snackbar or Toast notices are generally good for low impact notifications, will these be sufficient for things needing more attention?
* Adding actions to the snackbars do add scope as we'd have to include handling for that, something to keep in mind. However, I do think it affects some planning that goes into this.

**Comment by garymurray** [comment]
@nerrad I am happy for us to keep using the existing notices as is for now, and new notices can be worked on in a future update.

**Comment by nerrad** [comment]
>  I am happy for us to keep using the existing notices as is for now, and new notices can be worked on in a future update.

Great! So what that means is for the purpose of this scoped issue we'll essentially keep using the same _styles_ for existing frontend WooCommerce notices (but they can be served through the suggested api in this issue).
