### ISSUE TITLE
Reviews blocks: The content section outputs extra DIVs

### ISSUE THREAD

**Issue by dashkevych** [woocommerce/woocommerce-gutenberg-products-block#1797]
**Describe the bug**
The content section in the All Reviews block outputs extra two DIVs.

**Screenshots**
![GitHub Logo](https://snipboard.io/OaSMl2.jpg)

**WordPress (please complete the following information):**

* Core version: [5.3.2]
* WooCommerce version: [3.9.2]

**Comment by nerrad** [comment]
Confirmed and thanks for your report!
