### ISSUE TITLE
Shipping rates: add package title before each one of the options

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#1802]
Coming from https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/1783#pullrequestreview-363811062.

In the current _Cart_ page, each one of the packages has a title next to it (see _Fragile products shipping_ and _Shipping_):
![imatge](https://user-images.githubusercontent.com/3616980/75233667-8038e500-57b9-11ea-87dc-39cbfb7169e9.png)

In the current implementation of the _Cart_ block, however, we are not displaying any indication of which products are in which package, which makes it confusing:
![imatge](https://user-images.githubusercontent.com/3616980/75233724-98106900-57b9-11ea-89cf-a19e20683d89.png)

We would also like to wrap each package in a wrapping `div` or something similar, so they can be easily navigated and styled.

**Comment by Aljullu** [comment]
@garymurray may I get your feedback here? We need to add the package name when there are several packages in an order. I think there is no design for this, so maybe you can help with some advice? It will look something like:

_Cart_:
![imatge](https://user-images.githubusercontent.com/3616980/75237739-2a1b7000-57c0-11ea-850b-4e4ea953aa50.png)

_Checkout_:
![imatge](https://user-images.githubusercontent.com/3616980/75237763-37d0f580-57c0-11ea-893e-57ca303667d7.png)

The package names are _Fragile Products Shipping_ and _Shipping_. I wonder if we should make the name bold or keep it regular? Make it smaller or keep its size as-is? Add a colon (`:`) at the end?

In the first comment of the issue you can see how it is in the current _Cart_ page. :point_up_2:

**Comment by garymurray** [comment]
@Aljullu I had these in the Figma file:

<img width="400" alt="Screenshot 2020-02-25 at 10 43 06" src="https://user-images.githubusercontent.com/10805911/75240038-9cd61c80-57bb-11ea-9cd3-f1cec898ebb2.png">

<img width="650" alt="Screenshot 2020-02-25 at 10 43 16" src="https://user-images.githubusercontent.com/10805911/75240060-a3649400-57bb-11ea-91f3-b940a1c662a5.png">

Which in the context of what you have - would look like this:

<img width="406" alt="Screenshot 2020-02-25 at 10 48 49" src="https://user-images.githubusercontent.com/10805911/75240553-6b118580-57bc-11ea-8f2c-9dc6345241a6.png">

<img width="605" alt="Screenshot 2020-02-25 at 10 52 23" src="https://user-images.githubusercontent.com/10805911/75240837-ea06be00-57bc-11ea-8f59-23a1c1e9ed57.png">

Does that give you what you need?

**Comment by Aljullu** [comment]
@garymurray my bad, didn't find them. :man_facepalming: 

> Does that give you what you need?

Yes, absolutely. Thank you!
