### ISSUE TITLE
Cart block should enforce `Sold individually` product option

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#1822]
Woo products have a `Sold individually: ☑︎ Enable this to only allow one of this item to be bought in a single order` setting. When this is checked, the existing checkout and product page ensure that customers can only order one instance at a time.

<img width="898" alt="Screen Shot 2020-02-27 at 1 56 01 PM" src="https://user-images.githubusercontent.com/4167300/75402108-e4e67200-5968-11ea-839c-bbbdd508bae9.png">

<img width="823" alt="Screen Shot 2020-02-27 at 1 56 18 PM" src="https://user-images.githubusercontent.com/4167300/75402121-ef087080-5968-11ea-9be2-01dcd06adc27.png">

The new cart doesn't yet support this:

<img width="561" alt="Screen Shot 2020-02-27 at 1 56 46 PM" src="https://user-images.githubusercontent.com/4167300/75402152-00517d00-5969-11ea-978d-224b31531c1d.png">

**Describe the solution you'd like**
If this option is set, ~~remove the quantity selector and show static `1`~~ set the max for the quantity selector to 1.

**Describe alternatives you've considered**
If this feature is rarely used (?), perhaps we could consider not supporting it in new cart, and/or start thinking about deprecating. cc @garymurray

**Comment by mikejolley** [comment]
I think we should leave qty picker but set a max of 1.

**Comment by garymurray** [comment]
I agree with @mikejolley's comment - any further UI improvements there for that setting can be done in future iterations.

**Comment by haszari** [comment]
I've implemented this in #1824 alongside support for updating quantity. There was crossover between the two fixes, particularly in `QuantitySelector` - adding a max/min limit, making it a controlled component.
