### ISSUE TITLE
Product search block broken with the last Gutenberg release

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#1825]
**To Reproduce**
1. Install Gutenberg 7.6.0 and activate it.
2. Create a post and add the `Product Search` block.
3. Reload the editor and notice it shows a white screen and there is an error in the console:

> Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
> 1. You might have mismatching versions of React and the renderer (such as React DOM)
> 2. You might be breaking the Rules of Hooks
> 3. You might have more than one copy of React in the same app
> See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

**Screenshots**
![Peek 2020-02-27 10-52](https://user-images.githubusercontent.com/3616980/75432763-34b83f80-594f-11ea-8167-6fb2d44824bc.gif)

**Comment by nerrad** [comment]
@Aljullu can you see if this is reproducible with WordPress 5.4 release candidates. If so, then we'll need to prioritize fixing this before WP 5.4 lands (and also will need to ensure the fix lands in WC 4.0)

**Comment by haszari** [comment]
I tested this with the latest [beta 3](https://wordpress.org/wordpress-5.4-beta3.zip) (no RCs yet) and reproduced the issue.

<img width="646" alt="Screen Shot 2020-03-02 at 3 42 21 PM" src="https://user-images.githubusercontent.com/4167300/75641228-69ecc680-5c9c-11ea-96a5-006c7e693a50.png">

**Comment by Aljullu** [comment]
Confirming what @haszari says. It affects both 2.5.13 and `master`.
