### ISSUE TITLE
All Products block not usable on iPad 2?

### ISSUE THREAD

**Issue by ajgw** [woocommerce/woocommerce-gutenberg-products-block#1827]
I had setup on new page the new blocks All Products and Filter by Attribute as I saw in example. After I called this page with an older iPad 2 which has an older Safari Browser installed, I got no content in blocks. I saw blocks in frontend, but instead of content like products and attributes there was only a badge shown (I don't remember the exact text on it).

Does it mean, that the requirements for using blocks require up-to-date browsers?

**Comment by nerrad** [comment]
Currently we use the [same requirements as WooCommerce core](https://docs.woocommerce.com/document/frequently-asked-questions/#browseros) which in turn follows the [WordPress core requirements](https://make.wordpress.org/core/handbook/best-practices/browser-support/).

I don't know specifically what version of Safari is supported on the latest iOS version the iPad2 supports but it's highly unlikely it's a version we support.

Does that answer your question?

**Comment by nerrad** [comment]
Since this hasn't received a reply to my question in over two weeks, I'm going to close this issue. It can still receive comments though if there's any updates to offer.
