### ISSUE TITLE
Ensure cart totals correctly update when items are removed/quantity change

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#1830]
Follow up issue to #1813. The cart totals aren't updating when items are removed – need to refresh the page (!) to see the correct total $$.

Might look at this as part of #1824.

**Comment by nerrad** [comment]
Just noting that the cart quantity endpoints will likely need to be changed to return the entire cart object which can then be used to update `cartData` in the store (thus totals will be up to date for display elsewhere automatically).

**Comment by haszari** [comment]
> Just noting that the cart quantity endpoints will likely need to be changed to return the entire cart object which can then be used to update cartData in the store (thus totals will be up to date for display elsewhere automatically).

This makes sense @nerrad - we'll need to change a few endpoints, but overall this should simplify the API (there are some `GET` requests for slices of cart that might not be needed).  I've started prototyping this in a new PR #1840, just `DELETE /cart/items/:key` to begin with.  If this works out (keen for feedback) then we can update other endpoints.
