### ISSUE TITLE
Shipping calculation: improve messaging when no location by default is set

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#1835]
**To Reproduce**
1. Go to _WooCommerce_ > _Settings_ and set the _Default customer location_ to _No location by default_.
2. Open a page with the _Cart Block_. Make sure you don't have any address already introduced (you can use a private window).
3. Notice it says shipping options could not be found.
<img src="https://user-images.githubusercontent.com/3616980/75569692-e6419880-5a55-11ea-8b17-068e3e8aac8f.png" alt="Screenshot" width="224" />

**Expected behavior**
Instead, it should ask the user to enter an address, like in the _Cart_ page:
<img src="https://user-images.githubusercontent.com/3616980/75569677-dd50c700-5a55-11ea-88ad-1679b91ca78b.png" alt="Screenshot" width="448" />

**Comment by mikejolley** [comment]
This is blocked by https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/1836 since it needs to check if address has been entered.
