### ISSUE TITLE
Remove `setSetting` and usage from `@woocommerce/settings` alias.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#1838]
`setSetting`  was originally exposed as an interface to mutating the `wcSettings` global which exposed data from the server. However, this is a bad pattern to expose because in the context of react apps, mutated global state can never be reacted to and it's a "hidden state change" that makes it far to easy for client code using this to create bugs in apps reliant on these values.

As such, the `@woocommerce/settings` interface should be provided as a way to explicitly expose _immutable_ settings from the server.  While we can't _enforce_ immutability, we can at least remove any hints that there is an explicit way to override these values globally (and use module scoping to limit the impact of changes).  If settings from the server need to be changed, then it is preferable to use them to hydrate some other state in the app (preferably a custom wp.data store or something like it). 

Thus, this issue is to remove the `setSetting` interface that is currently exposed on the `wc.wcSettings` global (and `@woocommerce/settings` alias).

There is effort already underway in wc-admin to remove this dependency so co-ordination will have to be made there with how/when this lands.

Some suggested steps:

- soft-deprecate (add a warning if it's used) (potentially use `@wordpress/deprecated` package)
- eventually (when wc-admin is ready) remove the logic from `setSetting` so it does nothing and warning is updated to console.error (so calls to `setSetting` won't error, but also won't update any values in the global).
- At some point (determined by wc-admin usage) remove the function all-together.

**Comment by senadir** [comment]
This is a bit confusing to me, currently, our code doesn't use `setSetting` at all, the deprecation process seems to be lengthy, are we exposing `setSetting` to third party developers, or is it exposed as a package? if not, then we can simply delete it.

**Comment by nerrad** [comment]
`wc-admin` _was_ (and may still be) using it in some places.  It's likely WC-Admin already moved away from it. It's also a publicly available API that, while we haven't publicized at all, is still available for use. So I'm erring on the side of caution here.
