### ISSUE TITLE
CountryInput and StateInput use CustomControlSelect, which doesn't support a required prop

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#1848]
Currently, there is no way to mark _Country_ and _State_ input fields as required, but we would like to do so in the _Checkout_ form. That's because internally they use Gutenberg's `<CustomControlSelect>`, which can't handle `required` cases.

**Comment by mikejolley** [comment]
I'm not sure this issue actually affects us @Aljullu @nerrad Whilst it's true we cannot add a HTML required prop to this field, won't we have validation in place using the Store Notices? 

HTML required attributes don't provide a consistent experience across browsers and can easily be bypassed with a little inspector knowledge. I think we need JS based validation on the address fields.

**Comment by mikejolley** [comment]
There is no issue I can find for validating fields?

**Comment by nerrad** [comment]
> HTML required attributes don't provide a consistent experience across browsers and can easily be bypassed with a little inspector knowledge. I think we need JS based validation on the address fields.

Agreed, and it's notable that [MDN has no browser compatibility data for this attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/required)

> There is no issue I can find for validating fields?

No, but it is something that will come up as a part of splitting out work from #1780 (*see the notes in the flowchart).  Still, it'd be good to create an issue so it's not missed.

**Comment by mikejolley** [comment]
@garymurray Flagging this up with you - I don't think I've seen any designs for field validation, and whilst we have notices, it might not be the best solution. e.g. we could add inline validation.

**Comment by nerrad** [comment]
I think Gary already did some designs and shared them (but it might have only been in slack) - I'll see if I can find.

**Comment by nerrad** [comment]
Okay so this is what was shared by Gary in slack: https://www.figma.com/file/Pfw5Qa1UOw03RiJere3Wlo/Automattic-Components?node-id=4117%3A16532

Related slack convo: p1582022324322700-slack-C8X6Q7XQU

**Comment by garymurray** [comment]
@mikejolley yes - the idea was to use inline validation as per those components @nerrad shared above.
