### ISSUE TITLE
Legacy block default font size

### ISSUE THREAD

**Issue by tiagonoronha** [woocommerce/woocommerce-gutenberg-products-block#186]
The legacy block appears to be in inheriting the default font size from the editor which is set at 22px, which for this specific case is quite big:

<img width="611" alt="screenshot 2018-12-03 at 15 40 35" src="https://user-images.githubusercontent.com/1177726/49384369-c0262f00-f712-11e8-9f9a-42c7347ddaec.png">

**Comment by ryelle** [comment]
I saw this come up in slack, and I think we decided to leave it as-is since we're deprecating this block, is that correct @tiagonoronha ?

**Comment by willgorham** [comment]
Other block styles also seem to be overridden with Storefront editor styles (see #250). If this block is deprecated then these minor adjustments don't seem like too-big of a deal though.

**Comment by tiagonoronha** [comment]
@ryelle even though the old block will be deprecated in the near future, it is something that we are still making available to our users right now.

So, I think we should address these styling issues.

**Comment by ryelle** [comment]
Since we've officially removed the legacy block & won't be merging it into WC core, I'm going to close this issue.
