### ISSUE TITLE
cart block submit/proceed to checkout button should be sticky on mobile

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#1873]
(Adding an issue for this – I suspect it's in the designs, couldn't find a screenshot. @garymurray can you clarify and add a screenshot/mockup?)

The primary action for the cart block is to proceed to checkout. If the submit button is fixed at the bottom of the screen (on mobile) then this is much easier for shopper.

Currently the checkout button is below totals, coupons etc (by default), and mobile shoppers will need to scroll to find it.

**Comment by garymurray** [comment]
@haszari this is what we would be looking for here:

<img width="375" alt="X - 1" src="https://user-images.githubusercontent.com/10805911/75965600-f081ed80-5ec0-11ea-9b73-3c9738f4946e.png">
