### ISSUE TITLE
Investigate potential options for optimistic updates in the data stores.

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#1876]
as per the discussion in p1583357982405700-slack-C8X6Q7XQU we want to implement some form of optimistic behavior in our data store, it should help us build better interfaces, and handle error logic in a much better manner, @nerrad suggested [ForbesLindesay/redux-optimist](https://github.com/ForbesLindesay/redux-optimist) since its used within GB, other solutions include [kasperpihl/react-optimist](https://github.com/kasperpihl/react-optimist), [mattkrick/redux-optimistic-ui](https://github.com/mattkrick/redux-optimistic-ui) and [ecomfe/redux-optimistic-thunk](https://github.com/ecomfe/redux-optimistic-thunk)

**Comment by nerrad** [comment]
Thanks for creating the issue @senadir! 

Just to clarify, while I know I might have sounded a bit more assertive about implementing this, I want to _investigate_ if this will be worthwhile implementing.

**Comment by senadir** [comment]
optimistic behavior is definitely something we will want to have a UI that is perceived to be faster, but yeah we should test more solutions before sticking to something.

**Comment by nerrad** [comment]
I changed the title because it was a bit aggressive in prescribing a specific solution. I do think at some point we'll want to spend some time looking into optimistic updates but I think it's premature to explicitly call out how that might be implemented in the issue title.
