### ISSUE TITLE
Disable "Continue to checkout" button if any resource is currently resolving.

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#1882]
Part of optimistic UI is to directly load results to the user even if the server didn’t respond yet, this is meant to allow him to continue using the cart while things load in the background and to make an experience seem fast, however, every action will update parts of the cart like totals and shipping and prices, "continue to checkout" is the final step of this formula and we want to make sure servers responded before producing, so this button should be disabled until everything has resolved.

I'm not yet aware of a catch-all `isResolving` selector so we might need to construct it from various actions `isResolving`s

**Comment by haszari** [comment]
Is is this necessary? Just thinking about this from the user point of view...

- Does this mean proceed button will be disabled if user makes a change (e.g. add coupon)? 
- Is it possible the button would be disabled while some content loads initially, or is this covered by server-side hydrate?
- What if users click some other link to checkout – e.g. checkout page link in header/menu - what would be broken? 
- If there is an issue, should we prevent navigating away from cart page? Is it that serious?

I just want to better understand how this could cause an issue/problem for users. 

Here's an example flow: 

1. User adds something to cart.
2. User clicks through to view cart. Something is loading .. shipping rates?
3. User doesn't care about the information presented in the cart – e.g. prices, shipping etc – they just want to complete purchase (NOW!), so they click through to checkout immediately.

Put another way, do we need to enforce that users see cart info and engage with the cart in a certain way, or do we let them proceed to checkout whenever they want?

cc @nerrad  @garymurray

**Comment by nerrad** [comment]
Button will only be disabled if shipping rates or quantity changes result in total updates after the cart is loaded. So if the user decides to just click through this will not be blocking.  

@haszari did you take a look at the conversation in any of the linked pulls before leading your comment? I just want to ensure you have full awareness of the discussions that have happened there.

**Comment by haszari** [comment]
> Button will only be disabled if shipping rates or quantity changes result in total updates after the cart is loaded. So if the user decides to just click through this will not be blocking.

Right - similarly, if user updates quantity or adds a coupon, do we care if they click through to checkout via menu? Or navigate away? I'm trying to understand how the UI will break. 

I agree that usually it's best to indicate to the user in some way that their changes are persisting, and they need to wait / not navigate away - just exploring the implications of this for a store.

> did you take a look at the conversation in any of the linked pulls before leading your comment? I just want to ensure you have full awareness of the discussions that have happened there.

Yes – my question is somewhat independent of the discussion in #1978 - most of that is focused on the code/architecture, I want to understand the UX implications better.

**Comment by nerrad** [comment]
> Right - similarly, if user updates quantity or adds a coupon, do we care if they click through to checkout via menu? Or navigate away? I'm trying to understand how the UI will break.

By disabling the continue to checkout button we're signalling to the user that the coupon is being validated. In reality this is a short window. There's different ways we could signal things, we could have a spinner, we could fade out the cart render. We've chosen here to go with a disabled button state. This can change as we iterate or as we get feedback from testing.

As for whether we care if they click through other navigation. I don't know, likely not. Maybe this is something to discuss but I don't think we can resolve that absent of any actual testing feedback. Definitely open to other suggestions on how we signal resolution state but for now, to me, this is a reasonable _starting point_.

**Comment by nerrad** [comment]
BTW, recently #2082 was recently merged to master that adds the behaviour being discussed in #1978 to the _checkout_ block. If you want you can see the behaviour by testing a master build.

**Comment by nerrad** [comment]
I got the pull number wrong in my previous comment, edited to update with correct id.

**Comment by haszari** [comment]
Works for me – just exploring the rationale for the code.

> BTW, recently #2082 was recently merged to master that adds the behaviour being discussed in #1978 to the checkout block. If you want, you can see the behaviour by testing a master build.

Will take a look. There's a key difference with the checkout submit – it creates an order, user can't go back, so more important to block submit when requests are pending. The cart block is not the final step.

Anyway, thanks for explaining.

**Comment by nerrad** [comment]
> There's a key difference with the checkout submit – it creates an order, user can't go back

Just to clarify, we actually create a draft order on loading the checkout block (assuming conditions exist for creating the draft order). So the flow is a _bit_ different than the current shortcode based checkout. Also, user's _can_ go back to cart from the checkout block.

However, you are correct that blocking the button on checkout is a bit more important than the cart block because it triggers payment processing (or anything else hooked into the checkout processing event), so it's important the totals we feed the payment methods are correct.

**Comment by senadir** [comment]
blocking the Cart only happens after a use action, disabled might be the best option here but it's a step in the right direction (other options include a spinner inside the button to indicate loading), what happens here is that a user can associate his action (changing rates, selecting a rate, changing quantity) with the loading, meaning his action didn't resolve yet, moving away before resolving an action might not commit that action, meaning the users needs to do things again and this might cause frustrations.
