### ISSUE TITLE
[Design] buttons container block?

### ISSUE THREAD

**Issue by strarsis** [woocommerce/woocommerce-gutenberg-products-block#1886]
**Is your feature request related to a problem? Please describe.**
The [`core/buttons` block was added as default container block for inserted `core/button` blocks](https://github.com/WordPress/gutenberg/pull/17352).
Some WooCommerce related blocks also use `button` blocks, however, those are not inside `core/buttons` container blocks.

Does it make sense to wrap these often singular `core/button` blocks into a `core/buttons` container block? Does this `core/buttons` container block only make sense when an user actually inserts buttons and need some kind of container for the `button` blocks?

**Comment by nerrad** [comment]
Hi there,

I'm not sure exactly what problem you're raising here? From your questions it appears if you are asking about a decision made in Gutenberg core to wrap `core/button` block into `core/buttons` containers and whether we think it makes sense?  Are you asking if the `FeaturedCategory` and `FeaturedProduct` block in this plugin should be using `core/buttons` instead of `core/button`?

**Comment by strarsis** [comment]
@nerrad: Yes, some of these WooCommerce blocks contain `core/button` blocks.
Does it make sense to wrap them into `core/buttons` block, too?

**Comment by nerrad** [comment]
Whether or not it makes sense depends on what the use case is to have this converted to allow for multiple buttons over a single call to action. I'll leave this issue open for discussion for now, but it's not something I could see us prioritizing at the moment.

**Comment by nerrad** [comment]
Eventually there will be a refactor of existing Blocks to a new system implementing inner blocks (in the long term roadmap) and when that happens the points raised in this issue likely will be addressed. As is, this is not something explicitly going to be worked on for the existing blocks so I'm going to close this issue.
