### ISSUE TITLE
Can't add Checkout block anymore

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#1888]
**To Reproduce**
1. Create a post and add a _Checkout_ block.
2. Notice an error appears in the console:
`TypeError: can't access property "includes", fieldLabel is undefined`

The line causing the error is:
https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/assets/js/base/components/address-form/index.js#L84

That's because we expect to have a label in all fields but `DEFAULT_ADDRESS_FIELDS` might be undefined when creating the block.

We should either:

1. Always define `DEFAULT_ADDRESS_FIELDS` in the editor even when no _Checkout_ block is present. So when one is added it has the necessary values.

2. Fix #1879, which might automatically fix this issue as well.

**Comment by Aljullu** [comment]
The issue was introduced in #1847. After that one, when inserting a _Checkout_ block, fields appear without labels. After #1868 it started to crash because we were doing some manipulations on those labels.

@mikejolley any opinion on the solutions proposed above? The first one would work, but if we are going to move the labels to the frontend anyway, we might want to wait for #1879 being fixed.

**Comment by mikejolley** [comment]
@Aljullu Let's work on #1879 so we have correct labelling under our control. We can tailor that more to our needs also.
