### ISSUE TITLE
wp.components is fully loading on Cart frontend

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#1899]
**Describe the bug**
as per @nerrad latest research in pb0Spc-nM-p2 it seems wp.components is loading in the frontend but we're supposed to be tree shaking it.

**To Reproduce**
in a page with Cart block, open network tab and watch the resources, you will see wp.components (I didn’t confirm this yet but I'm opening this trusting Darren analytics, I will fully check later.

**Comment by nerrad** [comment]
Thanks for creating this Nadir, I had meant to and then forgot :)

**Comment by mikejolley** [comment]
I think these are being included due to dependencies in imports. e.g. cart and checkout import icons (which use SVG from components) and I found usage of Placeholder under `/base` in the NoShipping component.
