### ISSUE TITLE
States are not correctly sorted in Cart and Checkout blocks

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#1902]
Core sorts countries alphabetically, but doesn't do the same for country states, so in some locales the _State_ dropdown might be unordered.

![imatge](https://user-images.githubusercontent.com/3616980/76101861-61173000-5fcf-11ea-852b-37f7fde3b749.png)

See #1903 for an in-progress PR trying to fix this.

**Comment by mikejolley** [comment]
@Aljullu Would it make more sense to push a core patch to order the states correctly on definition? This would avoid the need to sort dynamically or deal with special characters.

**Comment by Aljullu** [comment]
> Would it make more sense to push a core patch to order the states correctly on definition?

@mikejolley I'm not sure, alphabetical order depends on the locale, so states might be correctly sorted in one language while not correctly sorted in another. That's why I think dynamic sorting is required.
