### ISSUE TITLE
The Rating section HTML inconsistency in the products grid

### ISSUE THREAD

**Issue by dashkevych** [woocommerce/woocommerce-gutenberg-products-block#1916]
Here is how the rating html looks in the Best Selling Products, On Sale Products, Hand-picked Products, Top Rated Products and Newest Products blocks:

![HTML markup](https://i.snipboard.io/60vm45.jpg)

Here is how the rating html looks in the All Products block:

![HTML markup](https://i.snipboard.io/JE67od.jpg)

--

WordPress: 5.4-RC1-47424
WooCommerce: 3.9.3

**Comment by nerrad** [comment]
@Aljullu or @mikejolley what are your thoughts on this one?  

It appears the `ProductRating` component isn't following the same structure as what is exposed by the server side rendered product grid blocks.  Should we align the two?

**Comment by Aljullu** [comment]
> Should we align the two?

Absolutely, we should also align it with the _Reviews_ blocks:

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/assets/js/base/components/review-list-item/index.js#L126-L149

**Comment by gigitux** [comment]
After the investigation, the HTML of the first screenshot is generated by [WC Core](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/f935e4190c3313b0ec25ba01dd1980af6fdb8932/src/BlockTypes/AbstractProductGrid.php#L510), and the other one is generated by [WC Blocks ](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/f935e4190c3313b0ec25ba01dd1980af6fdb8932/assets/js/atomic/blocks/product-elements/rating/block.js#L44)
