### ISSUE TITLE
Remove todo code introduced in #1919 when woocommerce/woocommerce#25854 is fixed.

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#1920]
**Describe the bug**
A new todo was added to #1919, that could should be removed once woocommerce/woocommerce#25854 is fixed

**Comment by Aljullu** [comment]
I'm going to set the epic of this issue to _Cart_ and _Checkout_ blocks, this way we can close _Shipping Methods Integration_ epic.

**Comment by mikejolley** [comment]
Done in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2374
