### ISSUE TITLE
Storefront sticky footer overlaps sticky cart submit button on mobile

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#1930]
Follow up issue to #1917

The cart block has a sticky checkout button. Storefront has a sticky footer on all pages, which obscures the checkout button. 

<img width="459" alt="Screen Shot 2020-03-11 at 9 45 33 AM" src="https://user-images.githubusercontent.com/4167300/76357776-2b7e9800-637d-11ea-88b0-442cdbd1d7db.png">

We'll need to either override storefront styling (to hide the footer), or get this addressed in Storefront directly. 

This may also affect checkout (assuming it has fixed footer for submit button on mobile).

**Comment by nerrad** [comment]
Do the existing checkout/cart blocks in WooCommerce core have any special treatment for storefront in WooCommerce core, or is storefront implementing CSS for styling the cart and checkout in the theme? I'm guessing the latter because existing cart and checkout flows use templates.

With that in mind, the current mobile styles in storefront seem fairly specific to the Storefront theme and thus I think it should be the theme that accommodates any necessary tweaks for the blocks rather than this plugin (or core).

Alternatively, are there any different approaches that could be taken for the button in CSS that makes this unnecessary?

**Comment by haszari** [comment]
> Do the existing checkout/cart blocks in WooCommerce core have any special treatment for storefront in WooCommerce core, or is storefront implementing CSS for styling the cart and checkout in the theme?

There are two parts to this: the cart/checkout shortcodes, and the designated cart/checkout pages. I'm not an expert but this is what I found:

- Core [applies classes to cart/checkout pages](https://github.com/woocommerce/woocommerce/blob/e1aaa6c63c02bd6197d4b40fce317cf8d424d36b/includes/wc-template-functions.php#L287-L297), e.g. `.woocommerce-page.woocommerce-checkout`.
- Core [styles cart & checkout pages using these classes](https://github.com/woocommerce/woocommerce/blob/f25967d57bc50c2906c94c111966d1bdbac04d1f/assets/css/woocommerce.scss#L1886), and even includes override styles for specific default themes (e.g. [Twenty Twenty](https://github.com/woocommerce/woocommerce/blob/8a0a5805e4795fb3984b1446c6b5fc59f327d053/assets/css/twenty-twenty.scss#L1640)).
- Storefront also styles [cart](https://github.com/woocommerce/storefront/blob/12c737a5a173f97f0ab9bac4ebd642945debef7e/assets/css/woocommerce/woocommerce.scss#L2380) & [checkout](https://github.com/woocommerce/storefront/blob/12c737a5a173f97f0ab9bac4ebd642945debef7e/assets/css/woocommerce/woocommerce.scss#L1158) pages using these classes, and overrides some details of the content rendered by the shortcodes.

So in summary - yes: I think the existing cart/checkout has storefront-specific styling (special treatment) in woo core, and yes: storefront is contributing to the styling of cart & checkout.

> With that in mind, the current mobile styles in storefront seem fairly specific to the Storefront theme and thus I think it should be the theme that accommodates any necessary tweaks for the blocks rather than this plugin (or core).

Agree in principle - though this may mean that we need to ship a Storefront update alongside blocks. Doable, just a release dependency we need to plan for.

Looking at the overrides in core, perhaps in the past we've shipped overrides/fixes for specific themes in core as a (temporary) workaround?

> Alternatively, are there any different approaches that could be taken for the button in CSS that makes theme specific accommodations unnecessary?

Good question – we should explore this. Perhaps we could raise it above storefront footer in z-index (ugh). The core of this is the interface between blocks plugin (and woo core if/when these blocks merge) and storefront/themers. 

We could log this as an issue on Storefront too – I've just logged here for now, since the cart/checkout blocks are still in development, so it's our problem to figure out :)
