### ISSUE TITLE
Inconsistent item count on cart widget vs cart block

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#1954]
- In woo core / Storefront, the cart widget in top right (and also in mobile sidebar) the number of items is displayed, including any multiples (`7 items` in screenshot below). 
- In cart block, the number of products/lines is displayed (`3 items` in screenshot below).

We should make this consistent or tweak the wording of the block (e.g. `3 products`). Probably best to stick with "items" meaning number of total things, as in the widget.

![Screen Shot 2020-03-12 at 10.38.06 AM.png](https://images.zenhubusercontent.com/5ddb3cb39529f10001e618e5/b55af000-34a3-4ba1-b31c-b44195573b4f)

cc @garymurray

**Comment by garymurray** [comment]
Best to do a bit of research on this across other sites to see how it is handled. Something to check in future iterations.

**Comment by mikejolley** [comment]
Pretty sure the total items is returned in the cart API, and that includes multiples :)
