### ISSUE TITLE
Totals don't add up when prices are displayed without taxes

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#1963]
**To Reproduce**
1. Go to _WooCommerce_ > _Settings_ > _Taxes_ and set _Display prices during cart and checkout_ to _Excluding Tax_.
2. Add some products to your cart and visit a page with the _Cart_ block.
3. Depending on the items you have in the cart, totals might not add up correctly:
![imatge](https://user-images.githubusercontent.com/3616980/76617220-2446be00-6526-11ea-8b70-4267ee68cac9.png)
_(line items are 170,93€, while subtotal is 170,91€)_

This is how it looks in the _Cart_ page, which doesn't have this issue:
![imatge](https://user-images.githubusercontent.com/3616980/76617294-49d3c780-6526-11ea-854d-8ac85cf5fa4e.png)
_(notice the subtotal of _Cap_ is different than before)_

**Comment by senadir** [comment]
seems like a rounding issue that could be related to how JS does float calculations? not fully sure how to approach this honestly
