### ISSUE TITLE
Update cart totals immediately with known informations

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#1982]
**Is your feature request related to a problem? Please describe.**
Currently, in a lot of places in the cart, we can have immediate updates to the cart totals while the server response, this can be done with known information like selecting a rate (that you know the price of) or changing or remove an item quantity (that you know the price of), this can help us update taxes, totals, shipping and cart total all immediately in JS without waiting for the server to respond, we do acknowledge that many factors can influence the total price (like discounts on quantities, plugins, and third-party developers), however, we can setup proper filtering places for third-party developers to also influence and add those changes, we can also add ways for third-party developers to disable certain updates if it’s impossible to have an immediate result (results depend on some logic that can’t be exposed or third party calculations), in that case, simply a loading indicator will be shown.

The goal of this is to use less loading indicators around the block, this should help make the interface seem faster and more responsive.

**Comment by nerrad** [comment]
This looks like a duplicate of #1876 (or at least something that would be solved as a side-effect of that work). So I'm going to close this. @senadir if you still think this should be a distinct issue, please do re-open with some explanation around how they differ (or maybe if needed, you could update 1876 to highlight any use-cases such as this that should be considered?)
