### ISSUE TITLE
Ensure woocommerceanalytics_product_checkout fires for stores that use blocks

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#2031]
We'll use the `woocommerceanalytics` events (from [Jetpack](https://github.com/Automattic/jetpack/tree/master/modules/woocommerce-analytics)) for measuring conversion rate of the new block-based cart & checkout, and comparing with existing (shortcode) flow.

We need the `checkout` event to fire correctly for stores using blocks, in particular when the checkout block is viewed.

See also #2032 #2030

**Comment by haszari** [comment]
Reopening – https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2038#issuecomment-606555548

We'll need to use a new hook – the one I used in #2038 is not appropriate.

**Comment by haszari** [comment]
I've opened a PR in Jetpack to fix this, using one of the new checkout hooks: https://github.com/Automattic/jetpack/pull/15223

Jetpack woo analytics now hooks `woocommerce_blocks_enqueue_checkout_block_scripts_after` as well as `woocommerce_after_checkout_form` to send the checkout event. Note that the events are sent as JS - this is rendered using WooCommerce utility `wc_enqueue_js()`. For full details check `wp-woocommerce-analytics-universal.php` in Jetpack (on the PR). 

@nerrad Can you give this a review when you're back on - I want to make sure that this is use of the new hook is safe and as intended. The difference between this fix and #2038 is the expectations on the hook, it's being fired in basically the same place (checkout block PHP `render()`).

**Comment by nerrad** [comment]
I reviewed the pr, but I also left a comment on it with a question.
