### ISSUE TITLE
Ensure woocommerceanalytics_product_purchase fires for stores that use blocks 

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#2032]
We'll use the `woocommerceanalytics` events (from [Jetpack](https://github.com/Automattic/jetpack/tree/master/modules/woocommerce-analytics)) for measuring conversion rate of the new block-based cart & checkout, and comparing with existing (shortcode) flow.

We need the `purchase` event to fire correctly for stores using blocks.

See also #2031 #2030

**Comment by haszari** [comment]
This event is [sent from a callback on `woocommerce_thankyou` hook](https://github.com/Automattic/jetpack/blob/master/modules/woocommerce-analytics/classes/wp-woocommerce-analytics-universal.php#L49).

This hook is fired from the [Woo core checkout thankyou template](https://github.com/woocommerce/woocommerce/blob/master/templates/checkout/thankyou.php#L26). I think this should all work the same for orders submitted from checkout block (vs traditional shortcode).

@mikejolley Can you confirm my suspicions - normal Woo core order handling will take place after order is submitted via checkout block?

We'll need to test this to be sure (alongside more comprehensive testing of all the events), but for now I'm assuming this event will work correctly. Leaving this issue open until we can test this, when checkout block is hooked up to submitting real order.

**Comment by mikejolley** [comment]
I mean, it will work initially, but I'm not sure if we'll use that thanks page forever.

**Comment by haszari** [comment]
> I mean, it will work initially, but I'm not sure if we'll use that thanks page forever.

@mikejolley Agreed, this doesn't feel super robust. Will leave this issue open until we confirm this is firing for block-based checkouts. 

Long term this is essentially a WooCommerce Analytics maintenance issue – the events code needs to be maintained as woo & blocks develop over time.

**Comment by haszari** [comment]
Tested this on ephemeral and confirmed the event is firing for cart + checkout block purchase flow.

I don't think we need to keep this issue open, and there's no action we need to take now.

If we need to do more work in this area we can open new issues as needed. For example:

- If we move away from the `thankyou` template (no current plans to do so), we'll need to add new code for firing purchase event. 
- Similar for anything that affects the purchase funnel, e.g. if we add a new add-to-cart mechanism in single product block.
- When we are preparing for launch on eCommerce plan, we may need to retest this to confirm everything's still firing, or adapt or add new events as needed to measure impact of blocks.

With that in mind, I'm closing this :)

cc @nerrad @Aljullu  - feel free to open a new issue for any specific follow up for this sprint/cycle.
