### ISSUE TITLE
Wire up "Keep me up to date" checkbox in checkout.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#2035]
The following checkbox is present in the checkout block and has state but the value isn't persisted anywhere:

<img width="698" alt="keep-up-to-date-checkbox" src="https://user-images.githubusercontent.com/1429108/77646909-d70e1780-6f3b-11ea-9e15-53ab2f0ffa3e.png">

Things needing done:

- Decide how/where this gets persisted. Is this part of order? Is there equivalent functionality in Woo Core right now? If so, that probably informs where this gets persisted.
- Based on the above, the value for this should be kept in the relevant context state.
- Make sure the value is persisted via whatever endpoint needs to handle it.

**Comment by senadir** [comment]
The first time I saw this it didn’t make sense, what is the point of collecting emails if woo doesn’t have support for managing them, sending emails or such, so I searched and this doesn’t exist anywhere in Woo core, I suspected it is added by Mailchimp, so I downloaded it and set it up, and sure enough, it was added, so I don’t think we should be adding this (we should remove it for now) and let MailChimp integrate it once we publish.
![image](https://user-images.githubusercontent.com/6165348/77913912-f9ca6400-728c-11ea-824d-06c5f3e434b9.png)

@garymurray

**Comment by garymurray** [comment]
Ideally this _would_ be an option in WooCommerce itself i think, where customers can opt-in and this 'decision' is stored against their account data. Then in turn, when you started using an email marketing platform you could sync those who had opted in to your email marketing platform.

Because something like this does not currently exist in WooCommerce - we can remove it/or look to try work with Proton to get something like this added as a feature in upcoming work perhaps?

**Comment by senadir** [comment]
so I think for now I simply feature flag the checkbox and leave it until we can ship it

**Comment by nerrad** [comment]
> so I think for now I simply feature flag the checkbox

I wouldn't feature flag it. Just remove it. We don't know if/when this will be added - I think feature flags should only be for things that have a timeline for getting released and we don't have that yet.

**Comment by senadir** [comment]
> I wouldn't feature flag it. Just remove it. We don't know if/when this will be added - I think feature flags should only be for things that have a timeline for getting released and we don't have that yet.

yeah, after some thinking, this is what I've done.
