### ISSUE TITLE
Featured Category: markup inconsistency between back-end and front-end

### ISSUE THREAD

**Issue by dashkevych** [woocommerce/woocommerce-gutenberg-products-block#2046]
**Describe the bug**
There is a minor markup inconsistency between back-end and front-end in the Featured Category block.

**Expected behavior**
The same HTML markup in both, back-end and front-end. 

Currently, the back-end markup uses a `div` with `wc-block-featured-category__wrapper` class. It is used a wrapper for the title, description and button. The front-end markup does not use this wrapper.

**Screenshot: Front-end**
![the Featured Category block](https://snipboard.io/ZvBphz.jpg)

**Screenshot: Back-end**
![the Featured Category block](https://snipboard.io/Yshguq.jpg)

**WordPress (please complete the following information):**

* Core version: [5.5-alpha-47507]
* WooCommerce version: [4.0.1]

**Comment by nerrad** [comment]
Hi there 👋,

Thanks for taking the time to report this. We'll investigate why this inconsistency exists at some point. For now, I'm just acknowledging that we've seen this.

**Comment by ralucaStan** [comment]
The inner wrapper is also missing on the Featured Product block. A `<div class="wc-block-featured-product__wrapper">` should be added there as well as a parent for the inner elements.
