### ISSUE TITLE
Product Search: block outputs multiple wrappers

### ISSUE THREAD

**Issue by dashkevych** [woocommerce/woocommerce-gutenberg-products-block#2047]
**Describe the bug**
The Product Search block outputs two wrappers for the form:

(1) `wp-block-woocommerce-product-search`
(2) `wc-block-product-search`

**Expected behavior**
Are there any particular reasons to use both? Can we eliminate one of them? For example:

```html
<div class="wc-block-product-search">
  <form>...</form>
</div>
```

instead of this:

```html
<div class="wp-block-woocommerce-product-search">
  <div class="wc-block-product-search">
    <form>...</form>
  </div>
</div>
```

**Screenshots**

![the Product Search block](https://snipboard.io/MYX4Hk.jpg)

**WordPress (please complete the following information):**

* Core version: [5.5-alpha-47507]
* WooCommerce version: [4.0.1]

**Comment by nerrad** [comment]
Worth investigating. I'm adding to our backlog.

**Comment by nerrad** [comment]
Should note however, I _think_ the `wp-block-woocommerce-product-search` wrapper is something added via Gutenberg. We might be able to eliminate the inner wrapper but not that one.
