### ISSUE TITLE
Add support for importing shipping zones in E2E

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#2053]
**Is your feature request related to a problem? Please describe.**
Tow write better e2e tests, we need to setup some shipping zones to test the shipping functionality, to do that, we need to either write a prep test that builds shipping zones, or import shipping zones (faster), however woocommerce doesn’t support importing rates, so this plugin can help [WC Shipping Rates Importer](https://wordpress.org/plugins/wc-shipping-rates-importer/), we just need to install it on the e2e test and write a prep test that imports those zones, ideally, you want to install this on your machine first, make some extensive rates (different zones with different rates and type of shipping methods and prices), export it, add it so somewhere in the plugin, and import it in the test.

**Comment by haszari** [comment]
We could use [WooCommerce CLI](https://github.com/woocommerce/woocommerce/wiki/WC-CLI-Commands) to set up shipping zones as part of container build or container launch (entrypoint).

**Comment by senadir** [comment]
creating shipping zones is possible but feels like a lot of work for little value, having it as a part of the DB imported can reduce, see this in proton channel p1585824649359500-slack-C0E1AV8T0

**Comment by haszari** [comment]
Good point @senadir  - I haven't looked at how complex this would be with CLI. It's looking doable, but maybe a little cumbersome to set up initially.

One advantage with injecting the data using CLI (or other script/import approaches) over a raw DB dump is that the database schema will change from version to version. The SQL dump might need to be regenerated when schema changes.

**Comment by senadir** [comment]
I'm once again revisiting this, importing DB turned out to be a very fragile idea, the CLI was not possible but the REST API does cover everything we need pb0Spc-A7-p2
