### ISSUE TITLE
Create editor preview for stripe and check payment methods.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#2056]
Currently third party stripe library is not loaded in the editor view for the checkout block to save potentially unnecessary loading. So there is need to finish the edit component preview for the stripe CC payment method.

Unfortunately, in order to do this, because we use stripe elements in the frontend, we can't do a 1:1 rendered view in the editor _unless_ we load the stripe.js library and generate the elements.

Options:

## Option A: Load stripe.js and re-use same components as frontend

| Advantages | Disadvantages|
|------------| --------------|
| easier to get 1:1 match with frontend | additional weight of loading `stripe.js` (~48kb)
| little to no extra code for editor preview | Might not respond to disabling inputs in the editor. Could lead to confusing behaviour if merchants try to use. |

## Option B: Create an edit component for stripe that renders preview inputs.

In this option, we wouldn't load `stripe.js` but we'd have to create components to render that have a similar structure to the stripe components without using stripe.elements. If we went this route, I would suggest the components be built in core and exposed for the gateway to use in their previews.

| Advantages | Disadvantages|
|------------| --------------|
| no additional weight from loading `stripe.js` | harder to get 1:1 match with frontend and likely more styles are needed |
| will respond better to any `<Disabled>` wrapper in editor context | more extra code for editor preview - and we'd need to work out how this would be split out extensions don't have to load this extra code in frontend views

Currently I'm leaning towards trying Option A mostly because while it does increase weight by loading stripe in the editor context, it prevents any additional weight being added to the frontend script. The downside is stripe.js is being loaded in every editor context. Will that be problematic?

### Check Payment method

This is much more simpler and we probably can just show the same as the frontend.

**Comment by nerrad** [comment]
If we go the path of loading stripe.js to use elements, then stripe data will need to be loaded differently because it only loads when the block is rendered in the current view (new posts/pages without the block inserted will not have the data loaded).

**Comment by haszari** [comment]
Could we just render an image / svg of what the payment method UI will roughly look like? Seems like a lot of complexity to simulate the exact same look as the front end. 

If the user can't configure aspects of how payment method looks/behaves (in block editor), and isn't going to be interacting with it, perhaps it's not we can avoid the complexity involved in showing a high-fidelity preview.

**Comment by nerrad** [comment]
> Could we just render an image / svg of what the payment method UI will roughly look like? Seems like a lot of complexity to simulate the exact same look as the front end.

That's an option, but there's some downsides to that too:

- Font colors and some styling will be inherited from the theme. The image won't match that.
- Are we going to establish the precedent that all gateways do the same?
- Stripe can be configured to show either one single input (inline credit card, expiry and ccv all in the same input) or split inputs for Credit Card details. Which will we show for the image? Or would we have two images and show the correct one depending on how the gateway is configured?

I had considered the image as an option but didn't include it with this issue because I think the downsides are worse than the other options currently. Still, it's a last resort if either of the other two options aren't feasible.

**Comment by mikejolley** [comment]
This won't be within scope right now, but there is potential for this area to be the place where you can configure payment gateway settings too. Just throwing it out there.

**Comment by nerrad** [comment]
> This won't be within scope right now, but there is potential for this area to be the place where you can configure payment gateway settings too. Just throwing it out there.

Yup, that was definitely on my mind when devising the api system for registering payment methods :) The payment method's registered edit component could implement inspector controls etc.
