### ISSUE TITLE
Add treatment for SavedPaymentMethodOptions in the editor context

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#2061]
Right now in the editor context:

- ~SavedPaymentMethodOptions is using what's available on the logged in user (fixed in #1983)~ Let's just show preview saved payment options.
- If there are saved options on the logged in user, the active payment method is hidden (because it defaults to a saved option). Let's always default to show the payment method selector **when in the editor**.

**Comment by haszari** [comment]
@nerrad I started looking at this but can't get my payment method (card) saved in current master - when I complete a purchase the card isn't saved, or at least it's not showing up as an option in subsequent purchase. Possibly there's a regression with saving card? 

I was testing with:

- Admin user
- Chrome
- Stripe CC set up in test mode, using 4242 test card number
- Current master (0f4ab25adb3a522aad8d17120b7587eba272e922), after rebuilding

I'll switch to another issue for now.

**Comment by haszari** [comment]
Actually, looking at the current behaviour I think see the next step here.

In editor, the payment area shows this:

<img width="469" alt="Screen Shot 2020-04-07 at 3 32 20 PM" src="https://user-images.githubusercontent.com/4167300/78627207-fc5c3780-78e4-11ea-9c03-d5fa62e2d0a6.png">

What we want is something to indicate to the merchant/editor that the card form will go here (or whatever the UI is for the payment method(s) user has set up.

We could show a hi-fidelity preview - so for Stripe CC, something like this:

<img width="632" alt="Screen Shot 2020-04-07 at 3 33 56 PM" src="https://user-images.githubusercontent.com/4167300/78627327-49d8a480-78e5-11ea-8fc6-a24cd09a113f.png">

I think this would mean that payment method extensions would have to implement this preview.

For now, I'll put in a basic placeholder component. We can improve the fidelity of this later.

**Comment by haszari** [comment]
Or .. can we just use `<StripeCreditCard />` as is? This works in my current setup, but maybe it would show my saved card (if I had one saved). E.g. it shows this - is this what you had in mind @nerrad ?

<img width="917" alt="Screen Shot 2020-04-07 at 3 44 08 PM" src="https://user-images.githubusercontent.com/4167300/78627865-a1c3db00-78e6-11ea-9dc8-2a36bfec3a92.png">

**Comment by haszari** [comment]
I was wondering if we could implement a fallback so payment methods aren't required to provide an edit preview component. If a payment method doesn't provide `edit`, then we could display a generic `Placeholder` component. Something like this...

<img width="571" alt="Screen Shot 2020-04-07 at 3 56 25 PM" src="https://user-images.githubusercontent.com/4167300/78628484-5a3e4e80-78e8-11ea-9c0a-68e01da92356.png">

On second thought, I can't see how to make that placeholder UI clear and helpful; perhaps it's best just to require that payment methods provide a hi-fidelity preview.

**Comment by nerrad** [comment]
> What we want is something to indicate to the merchant/editor that the card form will go here (or whatever the UI is for the payment method(s) user has set up.

That's to be done in a separate issue (#2056). Any discussion can go on that issue.

To be clear, this issue is specifically about doing the preview for saved payment method ui in the **editor** so you shouldn't be worried about actually _saving a card_ (and don't need to) in this issue. The components for saved payments should be able to just be fed preview data that can get used in the editor.

You also should not need payment method previews working either for this issue, the current placeholder behaviour is sufficient.

**Comment by haszari** [comment]
Sorry for the confusion here @nerrad - I understand this is focused on the editor :) 

Can you show a pic/explanation of what the checkout block should show in the editor? I'm guessing this is the radio buttons, something like:

```
[ ] Use my saved card
[ ] Add a new card
[  card number ] [ card expiry ] [ card cvc ]
```

I'm having trouble visualising what success looks like for this issue because I can't get that `Use my saved card` UI to appear on front end right now (well, this was the case yesterday).

**Comment by nerrad** [comment]
Ahh, ok, so what I did was just completed a purchase using the shortcode checkout and saved the payment method using that flow. At that point you will see saved payment method options in the checkout block in the frontend.

Alternatively, the component in use is found in `base/components/payment-methods/saved-payment-method-options.js`. You can search through the code and find where the component is implemented. That should give you an idea of what _preview data_ you'd need to feed to the component. You could then feed it preview data in the editor (plus whatever other code changes need to happen) which should show it like it does on the frontend only with preview data being used.
