### ISSUE TITLE
nonce error when add-to-cart from All Products block with anon/logged out user

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#2092]
![Screen Shot 2020-04-02 at 9.27.01 AM.png](https://images.zenhubusercontent.com/5ddb3cb39529f10001e618e5/a202a75f-1861-47cc-86ad-5530515cdb9b)

To reproduce:

- Clone master branch (this is a regression on master, not reproducible in current release)
- Add all products block to a page
- View page in incognito window
- Add two different products to cart

Should get a nonce error when adding the second product.

**Comment by nerrad** [comment]
I have a feeling the issue here is the nonce is just not being updated in the store from the response of adding/removing from cart. The store nonce was something added as a part of cart/checkout block work.
