### ISSUE TITLE
All Products: add to cart can fail when adding multiple products to cart in quick succession

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#2094]
### To reproduce

- Set up a page with all products block, showing lots of products which can be added to cart directly (no variations/options).
- Click add to cart for multiple products in quick succession. 

Notice only the first product correctly shows the updated `1 in cart ` feedback text. On the other product(s), the button switches back initial `Add to cart` text.

![add-to-cart-bad-feedback.gif](https://images.zenhubusercontent.com/5ddb3cb39529f10001e618e5/6a3adaa5-cbfb-484a-b54c-014877109d43)

**Comment by haszari** [comment]
The button text is correct - due to a race condition, only one gets added to cart. I've updated the title :)

**Comment by nerrad** [comment]
Still reproducible.
