### ISSUE TITLE
Cancel inflight api requests if CheckoutProcessor component is unmounted.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#2100]
In the new `CheckoutProcessor` component, we have a an effect that executes an api fetch request and then dispatches state updates when the promise is resolved or rejected. A potential problem with this is that if the component is unmounted before the promise is resolved, the state setters will fail, and React will log a warning to the console.

The solution is to implement a cancellable apiFetch promise so that we can return the cleanup action on the `useEffect` and cancel inflight requests.

Jetpack implemented a [fix here](https://github.com/Automattic/jetpack/pull/15228) that we can use as a guide.

**Comment by haszari** [comment]
I'm about to review this PR (#2130). Is there a specific flow / scenario where this bug could happen? I.e. how to unmount/delete a `CheckoutProcessor` component. Is that component part of the checkout block? Or is there logic that could mount/unmount `CheckoutProcessor` during a regular checkout flow?

I'll dig into the code to see if I can figure out how a user could trigger this. In the [Jetpack PR](https://github.com/Automattic/jetpack/pull/15228) the test steps are in the editor, and you delete the block; maybe there's a way to trigger the error by e.g. deleting a checkout block.

**Comment by haszari** [comment]
Ah I see this is not in `Review/QA`  column, will ignore for now.

**Comment by nerrad** [comment]
> maybe there's a way to trigger the error by e.g. deleting a checkout block.

Ya this is why this is an edgecase and we decided to move into backlog, currently checkout processing wouldn't be happening in the editor so there would never be risk that deleting the block would need the fetch cancelled.

Mike's initial work here is useful though because we'll have to be aware of potential places this might happen in blocks we develop where it _wouldn't_ be edgecase (i.e. populating settings or data via api in the editor).

**Comment by nerrad** [comment]
I think an more straightforward approach here might be to use [AbortController](https://developer.mozilla.org/en-US/docs/Web/API/AbortController). The caveat is it isn't available in IE, but imo that's okay here because we just don't abort in IE.

**Comment by tjcafferkey** [comment]
If the user hits "Place Order" regardless of whether the component is unmounted or not we don't want to cancel that request to prevent the user from successfully placing an order. For this reason I'm closing this issue.
