### ISSUE TITLE
Product "On sale":  HTML structure inconsistency in the products grid

### ISSUE THREAD

**Issue by dashkevych** [woocommerce/woocommerce-gutenberg-products-block#2107]
**Describe the bug**
There is HTML inconsistency of displaying the "On sale" container in the products grid

**To Reproduce**

1. Add the "Hand-picked Products" block or the "Newest Products" block or the "Best Selling Products" block to the content area. Make sure it contains the product on sale.
2. Add the "All Products" block to the content area. Make sure it contains the product on sale.
3. Compare the HTML structure of these blocks.

**Expected behavior**

The products grid has the same structure. One block displays this section in the `wc-block-grid__product-image` container while others display it outside of it. Also, one block is missing accessibility improvements in the "On sale" section.

**Screenshots**

The "Hand-picked Products" block or the "Newest Products" block or the "Best Selling Products" block.

![Best Selling Products HTML](https://snipboard.io/S1FX30.jpg)

The "All Products" block.

![All Products HTML](https://snipboard.io/QLrnb3.jpg)

**WordPress:**

* Core version: [5.5-alpha-47534]
* WooCommerce version: [4.0.1]

**Comment by Aljullu** [comment]
Thanks for opening this issue @dashkevych!

> One block displays this section in the `wc-block-grid__product-image` container while others display it outside of it.

That depends on the place the sale badge is shown. In the editor, you can edit the _All Products_ block to reorder some of the inner blocks. You could, for example, hide the _Sale_ badge from inside the image and add it outside.
![imatge](https://user-images.githubusercontent.com/3616980/78346902-02c67880-75a0-11ea-9fab-4b2a2d8de5fd.png)

> Also, one block is missing accessibility improvements in the "On sale" section.

Correct! The accessibility differences you reported are solved in #1656 and will be included in the next release.

Besides that, I still noticed some markup differences that might be worth solving:
* Product grid blocks (like _Handpicked products_) use a span for `.wc-block-grid__product-onsale`, while _All Products_ use a div.
* Product grid blocks copy is  `Sale!` (notice the exclamation mark), while _All Products_' is `Sale` (without exclamation mark).

**Comment by Aljullu** [comment]
@garymurray tl;dr: in some blocks like _Handpicked products_ the sale badge text is `Sale!` while in some others, like the _All Products_ block it is `Sale` (without exclamation mark). Should we try to unify both? Do we have a preference for one of them?

**Comment by garymurray** [comment]
I would prefer rather not using the exclamation mark as the standard setting - so just `Sale`.
