### ISSUE TITLE
Don't include `@woocommerce/previews` in frontend builds.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#2114]
In #2103 it was noticed that the frontend build for the all products block increased in size significantly. After some sleuthing by the squad, we noticed that `useStoreCart` imports `@woocommerce/previews` which include some weighty preview images.

A quick solution here would be to simply ensure that frontend builds alias `@woocommerce/previews` to a basic skeleton object instead of the data utilized in the editor. This should result in significant size improvements.

Alternatively (**and preferably**), we should pass preview data via the EditorContextProvider. The provider could receive preview data as a prop so that only editor builds will import the preview data. Then we'd just need to do a search for `@woocommerce/previews` imports and make sure any code importing that switches to implement `useEditorContext` hook for grabbing preview data instead.

Long term, we should probably also look to decreasing the size of the previews in the backend as well.

**Comment by senadir** [comment]
the huge size comes from the image preview, if we can possibly fix the previews in the future or alias them to a linked image, it will help reduce that size.
