### ISSUE TITLE
Product Categories block

### ISSUE THREAD

**Issue by strarsis** [woocommerce/woocommerce-gutenberg-products-block#212]
**Is your feature request related to a problem? Please describe.**
It should be possible to add a list of WooCommerce categories (including the category images), 
as it is possible using a shortcode as a Gutenblock to a Gutenberg page.
In contrast to the shortcode the user should be able to select and order the categories to be listed,
e.g. the user wants to list particular categories on the start page or different lists of categories throughout a page.

**Describe the solution you'd like**
A WooCommerce Category block should become available.

**Describe alternatives you've considered**
Currently a `product_categories` shortcode has to be used, a Gutenblock would offer much more, like immediate feedback, comfortable options and consistent experience (everything being Gutenblocks).

**Additional context**
This proposed WooCommerce Category block is not to be confused with the already existing `Products by Category` block which lists products by category, not a selected category or categories.

WooCommerce categories shortcode doc:
https://docs.woocommerce.com/document/woocommerce-shortcodes/3-1-earlier/#section-19

**Comment by ryelle** [comment]
Design for this block has been finished.

Settings include toggles for list/dropdown, show/hide product counts, show/hide empty categories, show/hide hierarchy (and max depth), dropdown for order (not sure offhand what the options are).

![Product Categories - Dropdown](https://user-images.githubusercontent.com/541093/57560959-2fa1e980-7357-11e9-8af5-670ae4726d81.png)
![Product Categories - List](https://user-images.githubusercontent.com/541093/57560960-2fa1e980-7357-11e9-90a9-a7de3afe3093.png)

**Comment by strarsis** [comment]
@ryelle: Will this be published with next WooCommerce plugin release?

**Comment by ryelle** [comment]
@strarsis Yes, that's the plan :) If you want to test it out early we'll also be releasing a new version of [WooCommerce Blocks](https://wordpress.org/plugins/woo-gutenberg-products-block/) with it this week.
