### ISSUE TITLE
Make sure we build in a way for gateway extensions to unregister the integration bundled with blocks.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#2122]
The goal will be to eventually move block compatibility for gateway extensions to the extensions themselves. This means we'll need a clean way for gateways to override what the blocks register internally for compatibility to provide an easier transition between the blocks and gateways.  This will have to be done before launching the blocks or we could make this harder to implement later in a painless way for merchants (version comparisons etc).

So I've created this issue just to make sure we don't forget this (will flesh out exactly how to do this - or what needs tweaked later).

**Comment by senadir** [comment]
if you have time later can you flesh out the details because this still feels fuzzy to me.

**Comment by nerrad** [comment]
Server side, could likely just remove the actions/hooks that the `Automattic\WooCommerce\Blocks\Payments\Integrations\Stripe.php` class is hooked into. Client side we may need an `unregisterPaymentMethod` and `unregisterExpressPaymentMethod` function as companions to the `registerPaymentMethod` and `registerExpressPaymentMethod` apis.  The tricky part is unregistration would have to be called after registration.

**Comment by nerrad** [comment]
In #3165 an experimental implementation of this was created. So this issue can now be used to determine whether we remove it from experimental or not.

**Comment by senadir** [comment]
Is this what we did for the recent Stripe integration? or would `__experimentalDeRegisterPaymentMethod` be enough here?

**Comment by nerrad** [comment]
We can close this 👍
