### ISSUE TITLE
Checkout Block cannot replace checkout shortcode without handling various order related endpoints.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#2145]
I discovered today that the [checkout shortcode](https://github.com/woocommerce/woocommerce/blob/master/includes/shortcodes/class-wc-shortcode-checkout.php) has handling for various order related endpoints (including `order-received` etc). This means that we can't completely replace the existing checkout page with the checkout block until we resolve where those endpoints will redirect to (or we automatically inject that on whatever page the block is added to).

I'm just adding this issue as a placeholder for now, but it is a blocker for suggesting the checkout block can replace the existing shortcode usage.

**Comment by nerrad** [comment]
We may need to bump this outside of the current sprint pipeline, but I've added it for visibility initially. This will impact releasing the plugin - do we fix before release or do we just document the caveat for using the block?

**Comment by senadir** [comment]
Copied from slack 
we can try to repurpose them
they use simple template parts, we might have to create our own router inside the block logic and just show those instead of the block content.

The optimal and preferred solution is that we have to design them and build, but that’s just another whole cycle.

**Comment by mikejolley** [comment]
@nerrad I know they are grouped under checkout in the settings, but it seems like the payment method endpoints are part of the **My Account page.** You can see these are handled in the my account shortcode.

For checkout, we only have to deal with order-received and order-pay.

**Comment by mikejolley** [comment]
![Screenshot 2020-04-08 at 14 59 25](https://user-images.githubusercontent.com/90977/78792840-8c63b500-79a9-11ea-8f37-b7a4a103d09b.png)

**Comment by nerrad** [comment]
> @nerrad I know they are grouped under checkout in the settings, but it seems like the payment method endpoints are part of the My Account page.

Hmm ya confirmed via the [account shortcode](https://github.com/woocommerce/woocommerce/blob/master/includes/shortcodes/class-wc-shortcode-my-account.php) code.

Although I'm guessing the payment method system hooks into checkout to add those routes for handling adding payment methods. We don't have to worry about that because we build that in via our REST endpoints.
