### ISSUE TITLE
Checkout inputs are broken in TwentyTwenty 

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#2154]
**Describe the bug**
It seems our input fields are broken on TwentyTwenty theme, I'm not sure if supporting that theme is within this scope or not, I'm filling this as part of https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/1539 but might not take on this issue until a later time.
![image](https://user-images.githubusercontent.com/6165348/78764874-12b6d180-797f-11ea-9bb7-a3d67c1f7688.png)
As you see,the label is positioned below the input, the text is also not aligned, without mentioning the font.

* Browser: Chrome
* Version: 80

**Comment by nerrad** [comment]
I think we'll have to bite the bullet and fix this, we can't release with things looking this bad in a WP default theme (even if that theme isn't typically e-commerce friendly).
