### ISSUE TITLE
Checkout Block: Re-order registered payment methods initially by the order they are configured in WooCommerce Payment settings

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#2157]
WooCommerce payment settings allows for setting the display order in the frontend for payment methods. We don't account for any of that currently in the new checkout block but we could account for that by doing some sorting based on those settings in [this code](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/assets/js/base/context/cart-checkout/payment-methods/use-payment-method-registration.js).

Likely, in iterations of the block, the ux of the block could allow for the merchant to change the order via block settings.

**Comment by haszari** [comment]
This probably crosses over with #2628 - updating how multiple methods are rendered.

**Comment by mikejolley** [comment]
@nerrad If we support the current admin UX for reordering then:

> Likely, in iterations of the block, the ux of the block could allow for the merchant to change the order via block settings.

This ^ will be problematic because it will conflict with global settings. I think re-ordering is better suited at block level. If we're happy to break this later, then ok :)

**Comment by nerrad** [comment]
> This ^ will be problematic because it will conflict with global settings. I think re-ordering is better suited at block level. If we're happy to break this later, then ok :)

I think you mean that if we don't put this in block settings now, adding later could create problems? If so, I think we can work around that when we eventually implement by defaulting to the global setting when block setting isn't present in attributes. 

While I definitely think we'll want this as a block setting eventually, the ui/ux around that is going to need some thought as there are a number of considerations affecting that including: How do we control the order in the block context? Inspector control area? Drag and drop tabs?
