### ISSUE TITLE
Create a testing plan for Cart and Checkout Blocks

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#2183]
We'll need a list of things to test for when we pass the blocks off for internal and external testing.  This list should include:

- Expected behaviour (i.e. how ui/ux should behave)
- Any setup steps for a set of tests (i.e. payment method, shipping etc).
- Cross browser coverage should be included
- Mobile, device usage should be covered.
- Outline different scenarios that might need special setup to trigger (eg certain error conditions etc).

If anyone things of other things the testing plan should include please feel free to edit this description.  

As far as where we write this plan, I'm thinking we should create a `docs/testing/cart-checkout` folder in our repository and then each area of testing could be it's own doc?

**Comment by senadir** [comment]
most of our errors are hard to generate from regular UX/UI, some need changes in code to trigger (because those errors happen on a rare moon when things don't work), should we also include them? I think regular UX/UI should be enough for now, as in, everything that can be done by a e2e test.

**Comment by nerrad** [comment]
> most of our errors are hard to generate from regular UX/UI, some need changes in code to trigger (because those errors happen on a rare moon when things don't work), should we also include them?

I think it may be premature to say "most" of our errors are hard to generate. Regardless I think we should also include all these errors in the testing steps (including how to trigger these types of errors with code changes if necessary).  If we're aware of the potential for these errors and we're accounting for them, then we should be testing the assumptions.

An example is shipping rate calculation errors because an invalid country is submitted to the endpoint. While via the current checkout shipping address fields this is virtually impossible to do. The Stripe ApplePay interface can and will collect arbitrary values for some shipping address fields from users. So I think it's possible for the payment method to provide a shipping address to checkout that will trigger a rest api error.

**Comment by senadir** [comment]
> Stripe ApplePay interface

I definitely forget about this interface and the possibility of having things outside of our validation.

> including how to trigger these types of errors with code changes if necessary

This is the type of errors I meant, are we expecting the people testing to have skills to build and modify the code (will they be other developers, HE, contractors, closed beta? ), granted with PHP this is straightforward but with JS there is a build step, so we might also do a check on our build documentation.

**Comment by nerrad** [comment]
> This is the type of errors I meant, are we expecting the people testing to have skills to build and modify the code (will they be other developers, HE, contractors, closed beta? )

This is why these checklist items will be in the repo docs. What we expose to others for testing will depend on what they are capable of testing but we have the docs to source the _authoritative_ testing checklists from.  I'm still not sure on how we'd organize this, but maybe we can make sure the checklists are separated by level of difficulty to test (i.e. tests requiring code change to simulate would be "high effort").

Initially, let's definitely focus on documenting checklists for testing things that don't require code changes, but if while building these lists you come across an edgecase that does, at least document the scenario that we can flesh out later.

**Comment by haszari** [comment]
Adding some things I saw today just as raw bullet points for now. Some of these are very detailed, I'm hoping we can generalise these to the most important high level flows.

- Checkout block editor preview should show tabs for configured and supported (in block) payment methods 
- Checkout block editor preview should show an example saved payment option which is appropriate for configured payment methods
