### ISSUE TITLE
Missing "cat_operator" in block settings....

### ISSUE THREAD

**Issue by GlennMartin1** [woocommerce/woocommerce-gutenberg-products-block#219]
**Describe the bug**
I need to have a category selected which includes only products that match two categories. 

With the shortcode, I would use `[products category="t-shirt, blue" cat_operator="and"]`

As described in https://docs.woocommerce.com/document/woocommerce-shortcodes/, this returns only products that match **both** categories.

The `cat_operator="and"` is a necessary component to make the block usable, but I cannot locate this in the block settings.

**Comment by ryelle** [comment]
Thanks for the suggestion @GlennMartin1, you're correct that we don't have a control for that here.

@LevinMedia @jameskoster – should we look at adding a setting to the category selection for this? Currently, selecting categories "A" and "B" catches all products in either "A" or "B", but we could add a control to say "only products in all selected categories".

The `cat_operator` also supports "not in", so products not in the selected category – that's probably less useful (and can probably be left to the shortcode) , but I wanted to bring it up.

**Comment by jameskoster** [comment]
Chatted about this with @LevinMedia. We figured that the feature will have a bigger impact on the attribute block we'll be working on soon. We'll work on the design there and we can retrofit our solution to the category block as well.

**Comment by ryelle** [comment]
This has been designed as part of the attribute selector, and we can use the same UI for Categories.

![placeholder-operator](https://user-images.githubusercontent.com/541093/49969874-a5fd0580-fef7-11e8-9c63-cc9cb0d1fb49.png)
