### ISSUE TITLE
Extending Store API response for Product Schema

### ISSUE THREAD

**Issue by doozy** [woocommerce/woocommerce-gutenberg-products-block#2195]
It could be useful for developers if a filter will be added to the Product Schema Store API response to extend it via 3rd party code.

I'm trying to add a custom inner block for the "All products" block and the product object lack of required data in my case (such as a product type, etc.).

**Comment by nerrad** [comment]
@senadir will the pending `ExtendStoreAPI` interface solve this requirement?

**Comment by senadir** [comment]
Yes, but we would need to implement it for that endpoint `store/products`, currently it's only available on `store/cart/items`

**Comment by senadir** [comment]
@doozy I'm not sure if you're still facing this issue, feel free to implement `ExtendRestAPI` on that route following this detailed doc:
https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/extensibility/extend-rest-api-new-endpoint.md
We don't have any immediate plans to extend this endpoint for our own use so I'm going to close this issue given there's nothing left for us to do.
