### ISSUE TITLE
postcss-loader is stripping SCSS sourcemap url

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#2200]
**Describe the bug**
It seems that even though `sass-loader` is generating a source map, it is getting stripped out in the final build, a suspect for that could be `postcss-loader` from what I [read here](https://stackoverflow.com/a/53122155).

**To Reproduce**

1. run `npm start` to generate files
2. notice that sourcemap files for styles are being created `build/styls.css.map`.
3. open a style file like `build/style.css` and scroll to the end of it, there is no sourceMapURL comment to include the source map.

**Comment by haszari** [comment]
To clarify the impact of this … I'm assuming the missing sourcemap means it's more painful debugging styles. Does this affect both release and builds @senadir ? Let's tweak the title so it highlights the problem/impact (rather than the technical details).

**Comment by senadir** [comment]
Sourcemaps are not included in production builds, they're a development tool so they're only available in `npm start`.

>  Let's tweak the title so it highlights the problem/impact (rather than the technical details).

I'm not sure I understand, this is a purely technical problem that affects the development team on a technical level, so I think the title is fine, how would you change it?

**Comment by haszari** [comment]
> I'm not sure I understand, this is a purely technical problem that affects the development team on a technical level, so I think the title is fine, how would you change it?

I'm thinking something like `Debugging SCSS is broken - minified css, source maps broken`. Focusing on the outcome that we want - debugging SCSS should be easy, the SCSS should show in the dev tools. 

Anyway I might take a look at this in cooldown :)

**Comment by haszari** [comment]
Confirmed the issue - when debugging using `npm start` the css files have no source maps in dev tools, you can only see minified CSS. I was looking at our 3 css files - `editor.css` `style.css` `vendors-style.css`.

I noticed two issues:

1. The css files don't reference a source map at all (the issue mentioned in description). I think there should be a comment something like this: `/*# sourceMappingURL=style.css.map */`.
2. The actual source map files look empty to me. For example, this is what my `style.css.map` contains: `{"version":3,"sources":[],"names":[],"mappings":"","file":"style.css","sourceRoot":""}`.

So looks like there's a problem generating the maps.

**Comment by haszari** [comment]
Saw this warning that might be relevant: 

```
Building Styles [=================== ] 93% after chunk asset optimization (37.1 seconds)
Without `from` option PostCSS could generate wrong source map and will not find Browserslist config. 
Set it to CSS file path or to `undefined` to prevent this warning.
```

**Comment by haszari** [comment]
Maybe just missing `sourceMap: devtool` option in a few places?? https://stackoverflow.com/questions/52422220/sourcemap-with-sass-loader-and-postcss-loader-in-webpack

Update - added this (https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3573) and now the sourceMaps are getting correctly generated: 

<img width="1174" alt="Screen Shot 2020-12-21 at 11 10 57 AM" src="https://user-images.githubusercontent.com/4167300/102725768-17d97680-437e-11eb-86e7-6b73eeeaa3ca.png">

It's still not working in dev tools though, there's still no comment linking the built css file with the source map.
