### ISSUE TITLE
snackbars are too high in desktop

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#2204]
try applying a coupon, you will get a snackbar, however, it is too high

![image](https://user-images.githubusercontent.com/6165348/79141232-447dcd00-7db1-11ea-8204-cbc58c5b463a.png)

tested in Chrome, storefront 2.5.5 on master.

**Comment by nerrad** [comment]
Definitely seems like a regression somehow. I don't remember it being that high.

**Comment by mikejolley** [comment]
Related, it seems to create a "block" element the full width of the page. That means you cannot click anywhere to the right of the snackbar. I came across this when trying to click a button that was to the right of a displayed snackbar. I had to wait for it to go, or scroll.

**Comment by senadir** [comment]
> Related, it seems to create a "block" element the full width of the page.

Yes, I experienced that as well.
