### ISSUE TITLE
error notice has bad contrast 

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#2206]
**Describe the bug**
Error notices have a light background with white text, making them unreadable, also I don't remember when did they start being so light?

![image](https://user-images.githubusercontent.com/6165348/79141109-0bddf380-7db1-11ea-9997-d221a32fd357.png)

Running chrome, on master and storefront 2.5.5.

**To Reproduce**

1. In checkout submit an empty fielded order
2. it should trigger the validation error.

**Comment by senadir** [comment]
The light color is coming from `@wordpress/components/notice` but it's only setting the background, not the font, the white font is coming from storefront (and generic WooCommerce styles).

I can confirm this in Production and Dev in safari, chrome and firefox on storefront master and our repo master.

**Comment by nerrad** [comment]
I'm closing this because I think you reported in slack this was a problem with your WooCommerce build right @senadir ?
