### ISSUE TITLE
Taxes are not updating in Cart and Checkout blocks if you change their settings or values.

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#2210]
**Describe the bug**
So if you have a cart with some products and taxes in it, and you update your taxes settings (change the value, disable, enable) it will not be reflected in Cart and Checkout no matter how much you refresh, it will only update if:
1- You change the cart (causing a recalc) so changing an item quantity, applying a coupon, selecting a rate...
2- You view the normal cart, somehow this also causes a recalc.

**To Reproduce**

1. set up some taxes.
2. add products and open your cart.
3. change the tax value (double it maybe).
4. refresh your cart or visit checkout, the value will still be the old one.
**Expected behavior**
It should update.

** Personal Note **
I understand that cart is not updating since nothing changed in it, using the cached cart, for anyone fixing this, if it affects performance, we can possibly skip fixing it, since it will affect a very small use case (someone updating taxes on a live website, affecting people who have an active cart at that moment and won't be updating it) so the surface area is very low.

**Comment by nerrad** [comment]
Is the behaviour in Cart and Checkout blocks for this _different_ than the behaviour in the current shortcode based cart and checkout blocks? It doesn't mean that we don't address it but it does make me wonder if this needs addressed in core as well.

**Comment by senadir** [comment]
Well I wouldn’t say different, it’s just Classic shortcodes will always update on refresh, this won’t
