### ISSUE TITLE
Cart and Checkout not respecting Display tax totals: itemized

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#2211]
**Describe the bug**
If you have multiple taxes, and choose the setting Display tax totals: itemized, Cart and Checkout blocks will not show each tax alone, it will still shown them as itemized, as compared to classical Cart and Checkout in which each tax is shown alone.

Blocks:
![image](https://user-images.githubusercontent.com/6165348/79247201-1c09d780-7e72-11ea-9760-10b5a8bd1686.png)

Shortcodes:
![image](https://user-images.githubusercontent.com/6165348/79247226-26c46c80-7e72-11ea-86a6-25f0bea75a68.png)

**To Reproduce**

1. Setup two taxes.
2. In tax settings, set Display tax totals to itemized
3. view Cart and Cart block and compare.

**Comment by haszari** [comment]
Testing tip - set a different priority for your taxes so they both apply (took me a while to find this) 💵 

<img width="1171" alt="Screen Shot 2020-04-23 at 4 43 35 PM" src="https://user-images.githubusercontent.com/4167300/80060046-b6100500-8581-11ea-8a46-ba31eb32878c.png">
