### ISSUE TITLE
Coupons with restrictions are showing raw errors (HTML) when restrictions are not met.

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#2212]
**Describe the bug**
1- have a coupon with a restriction (min or max spend).
2- try to apply it when you don't meet that restriction.
3- the error will have HTML in it

![image](https://user-images.githubusercontent.com/6165348/79248103-4c9e4100-7e73-11ea-93b0-4d681a03ac92.png)

I think a good solution (instead of remapping all old errors to new ones) is to filter out HTML from them.

**Comment by nerrad** [comment]
The html in this case is coming from `wc_price`:

https://github.com/woocommerce/woocommerce/blob/18ff3960b7413205cc2c725a1310cae1abb0c498/includes/class-wc-coupon.php#L977-L980

How were you thinking we'd filter out HTML?  I think what might work better is it _looks_ like responses can include the coupon error code. If that's the case, I think what would be preferable is if:

- WooCommerce core exposed the translated strings with the placeholder for each error code (which could then be exposed via the REST endpoint).
- The REST endpoint could also expose other details (minimum/max spend for instance) for each coupon type.
- Client code can use that information to assemble the notice as needed with the correct formatting applied etc using `__createInterpolateElement`.

For the first item we'd probably have to create our own strings mapped initially but add a pull to WC core to expose what's needed so future iterations can avoid duplicating these strings.

**Comment by senadir** [comment]
> How were you thinking we'd filter out HTML?

using `strip_tags` on errors before returning https://repl.it/repls/DefinitiveFinishedTechnicians

> For the first item we'd probably have to create our own strings mapped initially but add a pull to WC core to expose what's needed so future iterations can avoid duplicating these strings.

my hope was to avoid remapping, also only exposing the translated strings and building our own error on the client will remove some customization that some people would run, and would assume a stable structure that the API is returning, I think this is doable but kind limiting.

we could offer those customizations on the frontend, but we would be solving the same issue in two places.

**Comment by mikejolley** [comment]
We need to strip tags here; Woo only provides the message, not the code, so our code must be generic. We could implement validation on the client side, given some coupon data from the API.
