### ISSUE TITLE
Cart is not respecting Sold individually option

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#2215]
**Describe the bug**
When you have a product that you only sell one in an order via the `Sold individually: Enable this to only allow one of this item to be bought in a single order` inventory option, the normal cart will not allow you add more than one, or change quantity, Cart Block will allow you to change quantity and checkout with more that one.

![image](https://user-images.githubusercontent.com/6165348/79250311-5d9c8180-7e76-11ea-9524-ae4d7dc3374d.png)
![image](https://user-images.githubusercontent.com/6165348/79250289-570e0a00-7e76-11ea-86c0-da42c68569e5.png)
![image](https://user-images.githubusercontent.com/6165348/79250256-4bbade80-7e76-11ea-92e8-45e4dd592fee.png)

it also breaks old cart total, even if that cart won't allow you to change quantity (and will say a hardcoded 1, even if subtotal is not)
![image](https://user-images.githubusercontent.com/6165348/79250393-7c027d00-7e76-11ea-9493-8d9f9d4b9397.png)

**To Reproduce**

1. make a product be sold individually
2. add it to cart
3. change quantity
4. checkout like nothing happened.

**Expected behavior**
You shouldn't be able to change the quantity above 1.

**Comment by nerrad** [comment]
Hmm this seems like a regression, I'm pretty sure at one point the cart block _was_ accounting for this.
