### ISSUE TITLE
Ensure our Add to Cart has parity with Core Add to Cart in term of filters

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#2218]
**Describe the bug**
A recent bug (#2215) raised this point, however that bug is core check, not a filter check, so to make sure other plugins that add restrictions work fine, we need to ensure filter parity between Core "Add to Cart" and our API "Add To Cart", see @mikejolley comment p1586883607249300-slack-C8X6Q7XQU

As a part of the slack discussion, it was noted that merchants can use plugins like [WooCommerce Product Dependencies ](https://en-gb.wordpress.org/plugins/woocommerce-product-dependencies/) to restrict buying some products, however, in our case you can add products via the API directly, so we can verify filter parity by making sure no restrictions set by this plugin can be bypassed by our API.

**Comment by nerrad** [comment]
I gave this a `bug` label because it could be considered a bug if there is _no_ feature parity. However, whether this issue retains the label or not depends on exactly what happens with extensions like what was noted in the description.
