### ISSUE TITLE
Ensure conditions set by WooCommerce Product Dependencies are respected in Store API

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#2219]
Raised by a recent discussion in slack p1586883535248300-slack-C8X6Q7XQU merchants can use plugins like [WooCommerce Product Dependencies ](https://en-gb.wordpress.org/plugins/woocommerce-product-dependencies/) to restrict buying some products, however, in our case you can add products via the API directly, so we should make sure no restrictions set by this plugin can be bypassed by our API.

related issue: https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/2218

**Comment by nerrad** [comment]
I don't think we need this as a separate issue but instead what is noted here can be used to verify the issue raised in #2218 is appropriately handled. So I moved the description from this issue into #2218's description.
