### ISSUE TITLE
Stripe external files failing to load will disable other payment methods

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#2220]
**Describe the bug**
So I first saw this when I had a bit slow internet, I confirmed by blocking stripe.com domain in the devtools network panel, other payments methods won't load.
![image](https://user-images.githubusercontent.com/6165348/79257188-31d2c900-7e81-11ea-8f9c-38b8a935619e.png)

**To Reproduce**

1. Have two payment methods (checks and Stripe)
2. in the devtools, block js.stripe.com 
![image](https://user-images.githubusercontent.com/6165348/79257326-62b2fe00-7e81-11ea-92e7-d6d8d67090a4.png)

3. Relaod the page with devtools open
4. Watch that both payment options are not working
![image](https://user-images.githubusercontent.com/6165348/79257408-7a8a8200-7e81-11ea-90d6-b180769128aa.png)

**Expected behavior**
Only stripe should fail.

**Screenshots**

**WordPress (please complete the following information):**

* Core version: [e.g. 5.0.3]
* Gutenberg version (if installed): [e.g. 4.8.0]
* WooCommerce version: [e.g. 3.5.3]
* WooCommerce Blocks version: [e.g. 1.3.1]
* Site language:
* Any other plugins installed:

**Desktop (please complete the following information):**

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

**Smartphone (please complete the following information):**

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Additional context**

**Comment by nerrad** [comment]
I _think_ this might be covered by #2065 .

**Comment by senadir** [comment]
is this caused by the logic inside stripe, or is it in the logic that registers and adds payment methods?

**Comment by nerrad** [comment]
That's why I didn't close this issue because I don't know for sure, I just linked to the issue as a reference point.

**Comment by Aljullu** [comment]
Yeah, I think I fixed that while working on #2065. I will create a PR today so we can verify. :+1:
