### ISSUE TITLE
Checkout block: validation errors don't appear

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#2227]
**To Reproduce**
1. Go to the _Checkout_ block.
2. Click on _Place Order_ button without interacting with the form.
3. Notice you are not scrolled to the top and validation errors don't appear below input fields.

**Screenshots**
![Peek 2020-04-15 12-15](https://user-images.githubusercontent.com/3616980/79326185-bf122e00-7f12-11ea-8a38-335a68335d83.gif)

**Comment by Aljullu** [comment]
Actually the entire checkout flow seems to be broken for me. Checking out individual commits it looks like it might be introduced in #2189. @nerrad can you reproduce it too?

**Comment by nerrad** [comment]
> Actually the entire checkout flow seems to be broken for me. 

By entire checkout flow you mean payments too? Here's what I can confirm on latest master:

- inline validation is still working when tabbing through fields.
- global validation when clicking "Place Order" button is doing the main notice but not scrolling to the first invalid field (similar to what you report).  So yup, there's a regression there.
- Fixing the empty fields and doing a purchase is working for me, but until #2186 is merged, there's no feedback that things are processing.

So afaik, the regression with global validaiton is what needs fixed.

**Comment by Aljullu** [comment]
Correct, it seems it was a false alarm, sorry! Only validation when click `Place Order` is broken. I re-tried doing a purchase and it works.
