### ISSUE TITLE
remove WooCommerce core enqueued styles and scripts when a block page is the default Cart and Checkout page.

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#2239]
**Describe the bug**
Currently Woo Core loads some styles and scripts in the Cart and Checkout page, if our block is the default page, those styles would still load anyway (since they use `is_checkout()` and `is_cart()`) functions, therefore adding extra weights.
Checkout loads 44kb of gzipped JS and CSS.
Cart loads 38kb of gzipped JS and CSS.

I did a small modification in [this line 363](https://github.com/woocommerce/woocommerce//blob/4ae1e1f5fc6e9da4c4d0348d1590cd09b51fbbce/includes/class-wc-frontend-scripts.php#L363) and 366 and 375 by adding another condition

```php
if ( is_cart() && ! has_block( 'woocommerce/cart' ) )
```

That condition reduced bundle size in Checkout 13kb, and Cart to 9kb (most notably it removed WooSelect), other wins are still possible (some scripts that are loaded on all pages, not just those pages, can also be removed from those pages).

Before:
![image](https://user-images.githubusercontent.com/6165348/79462426-5d73c180-7fef-11ea-88a9-b7eee8d90c74.png)

After:
![image](https://user-images.githubusercontent.com/6165348/79461628-55ffe880-7fee-11ea-9172-2e37cdc119af.png)

**Wins**: 29kb gzipped from Woo alone, and 14kb gzipped from other places.

Before:
![image](https://user-images.githubusercontent.com/6165348/79463281-8b0d3a80-7ff0-11ea-9bc1-fee01da62bfa.png)

After:
![image](https://user-images.githubusercontent.com/6165348/79461762-85aef080-7fee-11ea-86b3-d3aff4afecdd.png)

**Wins**: 33kb gzipped from Woo alone.

**To Reproduce**
0. set the Cart and Checkout pages as the default Cart and Checkout pages.
1. Open devtools in the network tab.
2. Open one of the pages.
3. let the page download, now filter with `plugins/woocommerce/` it should leave the dependencies that woo is loading directly (this exclude other dependencies caused by woo that are loaded from other places, say wp-includes).
4. See the scripts that are not needed.

Not fully sure how to solve this from within our render function, since it's called way late, so we might need to add an action that runs after scripts finished registering to remove them.

**Comment by senadir** [comment]
Another win I could spot for us was the payment icons, down from 41kb
![image](https://user-images.githubusercontent.com/6165348/79463694-14bd0800-7ff1-11ea-943c-f056ba514f49.png)

**Comment by senadir** [comment]
created a PR for the svg issue (and now down to 9, not 18).
https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1172

**Comment by nerrad** [comment]
Nice catch @senadir - I think the improvements you mentioned for Woo scripts would be worth doing as a WooCommerce core change? So maybe move the issue there?

**Comment by mikejolley** [comment]
Don't forget those shortcode fallbacks for thanks and pay pages. Hopefully there is a way to dequeue them though - maybe in block render?

**Comment by senadir** [comment]
yeah that was a concern as well, I was trying to remove things that are only used in the actual checkout, those pages only use styles as far as I know, but will need actual testing.
