### ISSUE TITLE
Expose shippingRates errors to express payment methods.

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#2240]
Taken from #2203

> Expose the error to express payment methods. Likely could be saved to the shipping context state and surfaced back through the related shipping emitters so that anything hooked into the emitters can react to the errors.

We need to catch and surface errors from `useShippingAddress` to `ShippingDataProvider` and emit them from there so that express payment methods that are listening can see the errors and react accordingly.

**Comment by nerrad** [comment]
This probably will need done before release but not necessarily before testing.

**Comment by nerrad** [comment]
Something also I noticed (at least with Apple Pay) in testing today. The selected shipping address is not persisting for the completed purchase. So that will need fixed.  However with ApplePay I _am_ seeing shipping rates update in the apple pay modal for different address selections.

**Comment by nerrad** [comment]
> The selected shipping address is not persisting for the completed purchase. So that will need fixed.

I noticed this in testing with Chrome Pay today and I thought I was seeing the bug again but then realized that the issue was because I have a _local pickup_ shipping rate. When that is selected the shipping address is not shown on the order received view.
