### ISSUE TITLE
Checkout Block does not respect "Guest checkout" option

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#2252]
**Describe the bug**
Currently, our block will always let you checkout as a guest or a user, even if Guest checkout option is set to limit that.

**To Reproduce**

1. disable guest checkout in WooCommerce settings.
2. Try to checkout from an incognito window.
3. You will still be able to checkout.

**Expected behavior**
You should not be able to checkout.

**Comment by haszari** [comment]
There's a related option that we don't yet support - `Allow customers to create an account during checkout`.

<img width="824" alt="Screen Shot 2020-05-01 at 1 43 21 PM" src="https://user-images.githubusercontent.com/4167300/80774740-eecb6200-8bb1-11ea-995a-7d5b45a4c5a8.png">

**Comment by garymurray** [comment]
The blocks should inherit these settings - not sure if we decided against supporting this at any stage for our initial release - do you recall @nerrad ?

**Comment by nerrad** [comment]
Specific to the guest checkout settings that Nadir created this issue for, I don't think there was any explicit plan to support or explicit decision to not support - it was just overlooked in the scoping for the block. At least if I go by the [scoped out user stories here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/1294).

It looks like @haszari has got a fix underway for the guest checkout settings in #2375 

Regarding @haszari's note about creating an account (which is a separate issue imo), the same thing, there was not scoping either for or against.  I'll move his comment to a new issue.
