### ISSUE TITLE
Cart and Checkout blocks are failing with the last Gutenberg master

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#2257]
**To Reproduce**
1. Get the last version of Gutenberg from master.
2. Visit a page with the _Cart_ or _Checkout_ blocks.
3. Notice it shows an error.

**Screenshots**
![imatge](https://user-images.githubusercontent.com/3616980/79747274-abe4d100-830b-11ea-910a-9bf364db4fde.png)

Adding this to `2.6.0` milestone because it's probably blocking release.

**Comment by Aljullu** [comment]
Some more info:
* The issue seems to happen after https://github.com/WordPress/gutenberg/pull/21467 was merged.
* It affects all blocks, not only _Cart_ and _Checkout_.
* The difference seems to be that block attributes are now objects instead of arrays.
* Removing the types from method arguments that read `$attributes` fixes it:
```diff
-public function enqueue_assets( array $attributes = [] ) {
+public function enqueue_assets( $attributes = [] ) {
```
For example, in: https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/src/BlockTypes/AbstractBlock.php#L76

**Comment by mikejolley** [comment]
Yeah I found https://github.com/WordPress/gutenberg/pull/21467 too - that seems to be a breaking change. I'm checking the attributes are still accessible as an array.
