### ISSUE TITLE
Individual product block fails with no image

### ISSUE THREAD

**Issue by rogovski** [woocommerce/woocommerce-gutenberg-products-block#226]
**Describe the bug**
If an 'Individual Product' block is added to a page, it produces an error when associated with a product that doesn't have an image.

**To Reproduce**

1. Goto the admin panel
2. add a new product *without* an image
3. add a new page, while in editor
4. add a product block
5. select 'individual products'
6. Search for product created in (2)

**Expected behavior**
the search will report an error

**Desktop (please complete the following information):**

* OS: mac el-capitan
* Browser: chrome
* Version: 71

**Comment by rogovski** [comment]
@ryelle here is the new PR without the package-lock.json

**Comment by ajgw** [comment]
I have talked to James Koster about this at wordpress.org support. I have same issue but equal products have image or not – I get the error just after typing one letter into searchbox.

I am on Safari, macOS Mojave 10.14.2, Wordpress 5.0.1, WC 3.5.1
All Plugins deactivated except Woocommerce and WooCommerce Blocks 1.2
