### ISSUE TITLE
Cart block: Removing item from cart gives js error

### ISSUE THREAD

**Issue by menakas** [woocommerce/woocommerce-gutenberg-products-block#2279]
**Describe the bug**
When I have a list of items in the cart(built using the Cart block) and I click on "Remove item", the item fades and freezes. There is a JS error in the console. Though this does not happen for all items, I could reproduce it many times. I haven't been able to find the pattern, though it happened definitely for certain products on my local installation.

**To Reproduce**

1. Add a few different products to the cart.
2. View cart
3. Click on the "Remove item" link of some of the products
4. See error in JS Console, though not for all products. The item fades, but freezes.
`Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0`

**Expected behavior**
No error should be seen and the product should be removed from the cart without any issues.
**Screenshots**
https://d.pr/i/sHTZ7b

**WordPress (please complete the following information):**

* Core version: 5.4
* Gutenberg version (if installed): -
* WooCommerce version: 3.7; 4.0.1(tried on both)
* WooCommerce Blocks version: 2.6.0-beta.1 
* Site language: English
* Any other plugins installed: Stripe, WC Subscriptions

**Desktop (please complete the following information):**

* OS: Mac
* Browser Chrome
* Version Version 81.0.4044.11

**Comment by senadir** [comment]
Hey @menakas, thank you for filling this issue, can you possibly expand a bit on this issue?
usually `Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0` means the server didn't return a JSON respond but mostly an HTML one.
In your console, in the network tab, you will see all the request that has been made, search for one that starts with `?key=....` it will be in red if it failed, clicking on it should open a tab, can you tell us what you see in the Preview or Respond tab?
![image](https://user-images.githubusercontent.com/6165348/80092335-8699d200-855a-11ea-9bc5-6b4bc8397825.png)

**Comment by senadir** [comment]
Interesting, stock reserve table didn't install for some reason, I'm going to cc @mikejolley since he might have a better idea of why is this happening.
