### ISSUE TITLE
Cart: Shorten product description in demo data

### ISSUE THREAD

**Issue by garymurray** [woocommerce/woocommerce-gutenberg-products-block#2293]
The product description we are using in the demo data is to long. I think we can shorten it to and make it clearer what it would actually be. I would suggest using: `Product short description` instead.

**Comment by nerrad** [comment]
Can you give an example of what you mean by "demo data" Gary? Do you mean the preview that is shown in the editor? Or are you talking about demo data that can be preloaded on a site for testing.

We are currently using _summary_ from the REST API endpoint as per what was added in [this pull](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/1639) and also [this comment](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/1741#pullrequestreview-359637187).

For context, here's what the different possible text content options are:

- `summary`: A short summary (or excerpt from the full description) for the product in HTML format.
- `short_description`: Product short description in HTML format.
- `description`: Product full description in HTML format.

Summary actually uses `short_description` if it's available, otherwise it falls back to use a truncated string from the `description`. So in this case, I'm wondering if you are seeing product content that does _not_ have a short description set (so you're getting the truncated description)?

**Comment by haszari** [comment]
> Do you mean the preview that is shown in the editor? Or are you talking about demo data that can be preloaded on a site for testing.

Good question - I think we can probably improve our preview data, used in the editor, and possibly look at the Woo sample data set to see if it can set a better example too. I realise these are separate issues :)

**Comment by garymurray** [comment]
> Can you give an example of what you mean by "demo data" Gary? Do you mean the preview that is shown in the editor? Or are you talking about demo data that can be preloaded on a site for testing.

The preview that is shown in the editor - which I see now is actually pulling the content from the product description that was set for the demo products I imported to my storefront install.

So basically, I think the length of content it is pulling from the `description` is too long if the `short_description` has not been set. Ideally it would pull the whole `short_description` if it was set as I would assume people would craft something more applicable there, but if it falls back to using the `description` we should limit it to say 40 characters?

**Comment by nerrad** [comment]
@mikejolley currently `summary` is using `150` characters. It'd be fairly trivial to change this to 40 characters but I think `summary` from the endpoint is used by other blocks too (featured product for instance) where the longer summary might be more appropriate. Some ideas:

1. We could add a parameter that allows the client to indicate what value it what character count it wants for the summary.
2. We could add a client side utility (do we already have one) for intelligently truncating content and use that for the cart & checkout to further truncate the existing summary to the 40 char count?

**Comment by mikejolley** [comment]
@nerrad This is a word count, so 150 words is currently returned.

> The preview that is shown in the editor - which I see now is actually pulling the content from the product description that was set for the demo products I imported to my storefront install.

I'm confused by this statement - we are using sample data. In both the cart and checkout block previews I only see one sentence:

![Screenshot 2020-04-30 at 13 46 55](https://user-images.githubusercontent.com/90977/80711931-1276a580-8ae9-11ea-8b64-a01ab83c6519.png)

If you are talking about the actual frontend display, in conjunction with using sample data from Storefront/Woo, those would be full summaries and yes they are quite long.

We can add an arg to the API to limit summary length on product and cart endpoints - we will only need it on cart. I"m suggest a word count of say say no more than 20?

I'd also suggest not showing summary content when also showing variation content.

![Screenshot 2020-04-30 at 13 50 07](https://user-images.githubusercontent.com/90977/80712209-887b0c80-8ae9-11ea-944c-238645ca17d8.png)

@garymurray @nerrad If you're happy with this Ill get on it.

**Comment by nerrad** [comment]
> We can add an arg to the API to limit summary length on product and cart endpoints - we will only need it on cart. I"m suggest a word count of say say no more than 20?
>
> We could also consider not showing summary content when also showing variation content.

I like both those ideas. I'll defer to @garymurray on what we move forward with.

**Comment by garymurray** [comment]
> If you are talking about the actual frontend display, in conjunction with using sample data from Storefront/Woo, those would be full summaries and yes they are quite long.

That is what I was referring to. :)

> We can add an arg to the API to limit summary length on product and cart endpoints - we will only need it on cart. I"m suggest a word count of say say no more than 20?

Let's implement this. 

> We could also consider not showing summary content when also showing variation content.

Let's leave that for now. I think something we could maybe give as an option is allow merchants to decide if they want to display the summary content in the cart as an option in future iterations.
