### ISSUE TITLE
Cart: Shadow in the qty selector in the cart front end

### ISSUE THREAD

**Issue by garymurray** [woocommerce/woocommerce-gutenberg-products-block#2295]
**Describe the bug**
The qty selector in the cart shows a shadow around the 'container box' of the number - it should not

**To Reproduce**
View the qty selector in the front end of the cart.

<img width="162" alt="Screenshot 2020-04-27 at 12 03 58" src="https://user-images.githubusercontent.com/10805911/80365250-320a9580-887f-11ea-8093-946ca69b9b77.png">

**Comment by mikejolley** [comment]
I've confirmed this one is fixed in master by https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2283
