### ISSUE TITLE
Cart: Empty cart icon/image should be centre aligned by default

### ISSUE THREAD

**Issue by garymurray** [woocommerce/woocommerce-gutenberg-products-block#2297]
**Describe the bug**
The empty cart icon/images is left aligned by default when I view the empty cart state - it should be centre aligned. 

**To Reproduce**
Add the cart block to a page, view the empty state - the image/icon should be centre aligned by default.

**Screenshots**

<img width="1154" alt="Screenshot 2020-04-27 at 12 08 33" src="https://user-images.githubusercontent.com/10805911/80365777-0b992a00-8880-11ea-96e2-a738348bd915.png">

**Comment by haszari** [comment]
Note this was also reported as a Storefront issue, potentially affecting other editor images. https://github.com/woocommerce/storefront/issues/1255

Anyone who picks this up - check behaviour in other themes too (e.g. Twenty Twenty), in case this is actually a Storefront issue, and to ensure we fix in the right place(s).
