### ISSUE TITLE
Cart: low stock notification is not dynamic

### ISSUE THREAD

**Issue by garymurray** [woocommerce/woocommerce-gutenberg-products-block#2298]
**Describe the bug**
When you increase the qty of an item in your cart that shows the low stock notification badge - that badge does not update based on the change you are making to the qty in your cart - i.e. as you add an item, the low stock notification should decrease accordingly.

**To Reproduce**
Add an item to your cart that is set up to manage low stock - see the notification badge appear, increase the qty of that item in your cart - observe that the number in the notification does not change - making it appear as though you could still add for instance 5 items to your cart.

**Expected behavior**
The low stock notification badge should update as you change the qty of items in the cart for that associated product.

**Comment by mikejolley** [comment]
Hmm items in the cart are not considered as taking up stock. Should this badge be representivite of current stock in the store, or stock + whatever is in cart? I think this could be pretty confusing if for example there is 1 in stock, 1 in the cart, and the badge states 0 or none in stock at the same time. 

Fwiw low stock does also already restrict what you can add to cart via the max property on the quantity input.

**Comment by garymurray** [comment]
> Should this badge be representivite of current stock in the store, or stock + whatever is in cart?

I was thinking it would be stock + whatever is in the cart

> I think this could be pretty confusing if for example there is 1 in stock, 1 in the cart, and the badge states 0 or none in stock at the same time.

If you had the last item in stock in your cart, it should probably say something like: `LAST ITEM IN STOCK`
