### ISSUE TITLE
Cart: no error when increasing item above stock level

### ISSUE THREAD

**Issue by garymurray** [woocommerce/woocommerce-gutenberg-products-block#2300]
**Describe the bug**
In the test instructions - one of the things to check is the following:

`If you try to increase an item quantity to above its stock quantity, you get an error.`

However, when trying to increase an item above it's stock quantity I did not get any error message - it just would not let me do it, either via the + button or by trying to enter a number via the input. 

**To Reproduce**

Try increase the item of an item above its stock quantity in the cart. There is no error message.

**Comment by nerrad** [comment]
@mikejolley does this sound like incorrect expectation from test instructions? I think we enforce things so the user cannot increase an item quantity above the stock quantity right? Or maybe test instructions need expanded to include how to simulate where this error might happen, for example:

- set a stock of 4 on an item.
- open tabs in two different browsers (so you have two different sessions in play).
- in both browsers add 1 of that item to the cart.
- in both browsers load the cart (block).
- in one browser, increase the quantity of that item to the maximum you can.
- in the other browser, try increasing the quantity, an error should appear.

I think the above instructions should stimulate a race condition with low stocks that might occur?

**Comment by mikejolley** [comment]
@nerrad yes that's likely an outdated testing instruction. The complex test you suggest is probably best left to unit tests.

**Comment by garymurray** [comment]
Right - tested and works as per those instructions.

**Comment by nerrad** [comment]
I updated the testing instructions directly on master branch in e2003f0
