### ISSUE TITLE
Cart: Free shipping coupon - strange UX

### ISSUE THREAD

**Issue by garymurray** [woocommerce/woocommerce-gutenberg-products-block#2302]
**Describe the bug**
When I enter a coupon that allows free shipping, it does "discount" the order by the shipping amount and selects the free shipping option, but it says that the discout is $0 - whereas it should reflect the discounted amount I would think?

**To Reproduce**
Create a coupon that allows free shipping - and view the UX once you enter the coupon amount - the discount shows as $0.

**Expected behavior**
The discounted amount would reflect the value of the shipping amount discounted.

**Screenshots**

<img width="371" alt="Screenshot 2020-04-27 at 11 52 38" src="https://user-images.githubusercontent.com/10805911/80367226-9da23200-8882-11ea-96c0-aae17c169d58.png">

**Comment by mikejolley** [comment]
All this coupon type does is enable the free shipping method - no shipping rate has been discounted. Look at your example; you could have chosen local pickup which is also $0. 

We should probably hide the discount row unless there is a discount > 0.

**Comment by nerrad** [comment]
> We should probably hide the discount row unless there is a discount > 0.

I agree with that, would that be a satisfactory solution here Gary?

**Comment by garymurray** [comment]
> All this coupon type does is enable the free shipping method - no shipping rate has been discounted.

Is this they way the UX for this works via the shortcode? It seems like a strange UX to me that when I apply a coupon, it is shown as being applied alongside the 'discount' row - but then there is no actual discount shown alongside it.

> We should probably hide the discount row unless there is a discount > 0.

I think this would probably be a better UX - so if someone had this coupon, they could enter it during the checkout and it would enable the free shipping option on the order. The only catch then is that if they wanted to remove the coupon (for any reason) and we are hiding the discount row, then they can't.

Thoughts here @LevinMedia ?

**Comment by mikejolley** [comment]
>  The only catch then is that if they wanted to remove the coupon (for any reason) and we are hiding the discount row, then they can't.

But they can deselect free shipping if no longer wanted so this is probably a non-issue?

> Is this they way the UX for this works via the shortcode? It seems like a strange UX to me that when I apply a coupon, it is shown as being applied alongside the 'discount' row - but then there is no actual discount shown alongside it.

The coupon displays with no discount in the shortcode - there is no total discount row, each coupon has it's own row.

**Comment by LevinMedia** [comment]
Howdy ya'll... per your point @mikejolley 

>We should probably hide the discount row unless there is a discount > 0.

I'm with you there - I'd put the frees hipping code under the shipping section, and re-order the free shipping option to the top of the stack:

<img width="527" alt="Screen Shot 2020-04-29 at 6 45 01 AM" src="https://user-images.githubusercontent.com/4500952/80603222-f8ec3580-89e4-11ea-9373-2481a1f71b07.png">

**Comment by mikejolley** [comment]
I've increased the estimate for this - I'm not sure how feasible it is to selectively pull those coupons or reorder shipping methods. Will start with the discount row removal.
