### ISSUE TITLE
Cart/Checkout: Apply btn on coupon component does not follow corner radius of other buttons

### ISSUE THREAD

**Issue by garymurray** [woocommerce/woocommerce-gutenberg-products-block#2306]
**Describe the bug**
The `Apply` button on the coupon component does not follow the styling of the other buttons - it has a square radius, whereas the proceed to checkout and place order buttons are rounded.

<img width="368" alt="Screenshot 2020-04-27 at 12 40 41" src="https://user-images.githubusercontent.com/10805911/80368363-86644400-8884-11ea-8d92-957f933949e7.png">

**Comment by haszari** [comment]
Note also the cart `Proceed` button is also square on front end:

<img width="356" alt="Screen Shot 2020-04-29 at 3 38 46 PM" src="https://user-images.githubusercontent.com/4167300/80558792-a6843680-8a2f-11ea-9bf2-a6a7ed265c27.png">

**Comment by Aljullu** [comment]
I'm seeing the same as @haszari. What theme were you using @garymurray?

Both of them inherit the border-radius from the theme (`.button` selector). The difference might come from the fact that `Apply` is a `<button>` but `Proceed to Checkout` is a `<a>`, so if a theme only styles `<button>` elements but not element with the class `button`, there might be some discrepancies in the style.

**Comment by garymurray** [comment]
I was using Storefront - note the rounded corners on the place order button vs the square one on the apply button in the checkout page:

<img width="752" alt="Screenshot 2020-05-01 at 10 18 12" src="https://user-images.githubusercontent.com/10805911/80795707-2e378580-8b95-11ea-9802-06d4087c9933.png">

**Comment by haszari** [comment]
In #2390 I've fixed this by _removing_ our lone opinionated style for the place order button radius – the idea is that the theme is responsible for button roundedness, and we defer to theme. 

Keen for feedback - cc @garymurray  @Aljullu.  Another alternative would be that we always round the cart/checkout buttons, essentially overriding the theme styles.
