### ISSUE TITLE
Checkout: Order summary card - no dividers btw products

### ISSUE THREAD

**Issue by garymurray** [woocommerce/woocommerce-gutenberg-products-block#2307]
**Describe the bug**
When there is more than 1 item in the cart - the Order summary card in the checkout should use divider lines to separate the products. Currently it does not.

**To Reproduce**
Add more than 1 item to your cart, proceed through checkout and look for dividers between products in the order summary card.

**Expected behavior**
Products should be seperated by dividers in the order summary card/

**Screenshots**

Currently:
<img width="384" alt="Screenshot 2020-04-27 at 12 42 34" src="https://user-images.githubusercontent.com/10805911/80368566-d511de00-8884-11ea-9786-854154a91ff0.png">

As per design:
<img width="719" alt="Screenshot 2020-04-27 at 12 44 42" src="https://user-images.githubusercontent.com/10805911/80368594-df33dc80-8884-11ea-840e-2b38ba7e08d7.png">

**Comment by nerrad** [comment]
Looks like this was fixed at some point since beta1 was released. The latest master has this:

<img width="420" alt="Image 2020-04-28 at 1 35 57 PM" src="https://user-images.githubusercontent.com/1429108/80518995-4751f380-8955-11ea-9f1c-4f5ec4a6add0.png">
