### ISSUE TITLE
Checkout: Order notes component not usable

### ISSUE THREAD

**Issue by garymurray** [woocommerce/woocommerce-gutenberg-products-block#2308]
**Describe the bug**
The order notes component shows on the checkout page, it is unusable currently and you cannot remove it via the block settings:

<img width="683" alt="Screenshot 2020-04-27 at 12 46 04" src="https://user-images.githubusercontent.com/10805911/80368719-130f0200-8885-11ea-82a5-a93cfe6fc7a5.png">

It should be removed if we are not going to enable it for the initial release.

**Comment by senadir** [comment]
@nerrad I think in our last discussion we decided to leave it to see if we had time to implement it or not, I guess we should remove it for now and follow back on it in a future cycle?
