### ISSUE TITLE
Checkout: Express payment was not really express...

### ISSUE THREAD

**Issue by garymurray** [woocommerce/woocommerce-gutenberg-products-block#2310]
**Describe the bug**
During checkout I was presented with an Express payment option based on my shipping address - when clicking the button it opened a window in Chrome, however there were not stored credit card details - making it not really "Express" as I still needed to fill that out.

**To Reproduce**
Checkout using a US address, click the available express payment option - if you do not have a saved credit card already observe that you still have to enter those details.

**Expected behavior**
Express payment options should only show if they have all the details to actually make the payment "express" having to still enter credit card details make it less express and we should rather take the customer through checkout to start.

**Screenshots**

Express payment option:

<img width="710" alt="Screenshot 2020-04-27 at 11 07 17" src="https://user-images.githubusercontent.com/10805911/80369358-0b9c2880-8886-11ea-8406-d3f02c185fb8.png">

Chrome prompt:

<img width="507" alt="Screenshot 2020-04-27 at 11 10 38" src="https://user-images.githubusercontent.com/10805911/80369375-12c33680-8886-11ea-93d5-fcbc52bf9767.png">

Note - no credit card details are available.

**Comment by senadir** [comment]
> During checkout I was presented with an Express payment option based on my shipping address - when clicking the button it opened a window in Chrome, however there were not stored credit card details - making it not really "Express" as I still needed to fill that out.

Depending on your environments and if you have a credit card already saved in chrome payments, this will either use that card or prompt you to save the new one for future usage.

**Comment by nerrad** [comment]
Nadir's explanation is correct here. Basically there is _no_ connection between credit card details that might be connected with Stripe and those that are saved in the browser (and there's no way for us to sync between the two... that's completely controlled by the stripe integration). That's how the "express payment" (using the payment request api works). The same is true for Apple Pay (which uses the same api). When payments are made using these express payment buttons, stripe does not get any cc details, they are saved with the browser (or in Apple's case with your Apple ID).
