### ISSUE TITLE
Cannot Add order note to checkout

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce-gutenberg-products-block#2312]
**Describe the bug**
Clicking on the Add order note does nothing.

**To Reproduce**

1. Go to checkout
2. Try to add an order note

![Screenshot 2020-04-27 at 14 42 04](https://user-images.githubusercontent.com/2207451/80373707-c08a1180-8895-11ea-87c9-11dc5e92042c.png)

**WordPress (please complete the following information):**

* Core version: 5.4
* WooCommerce version: 4.0.1
* WooCommerce Blocks version: 2.6.0-beta.1
* Site language: en_US
* Any other plugins installed:

```

Active plugins (8)
--
Companion Plugin |   | by Osk – 1.11
Facebook for WooCommerce |   | by Facebook – 1.11.0
Jetpack by WordPress.com |   | by Automattic – 8.4.2
Mailchimp for WooCommerce |   | by Mailchimp – 2.3.6
WooCommerce Stripe Gateway |   | by WooCommerce – 4.3.3
WooCommerce Blocks |   | by Automattic – 2.6.0-beta.1
WooCommerce - ShipStation Integration |   | by WooCommerce – 4.1.35
WooCommerce |   | by Automattic – 4.0.1

```

**Desktop (please complete the following information):**

* OS: MacOS Mojave 10.14.6
* Browser Chrome Version 81.0.4044.122 (Official Build) (64-bit)

**Comment by peterfabian** [comment]
Duplicate of #2308. The filter for "issues already exists" should maybe be different in test instructions...

**Comment by senadir** [comment]
> Duplicate of #2308. The filter for "issues already exists" should maybe be different in test instructions...

@peterfabian that filter exists for already triaged issues, not much we can do for #2308 since it was untriaged when you posted, and the issues tab serves for all types of ideas and bugs outside the cycle and future cycles.

But I agree that a better could be implemented.
