### ISSUE TITLE
Cart and Checkout blocks on the same page

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce-gutenberg-products-block#2313]
**Describe the bug**
Not sure if I can call it a bug, but since it's possible to add Cart and Checkout blocks on one page, maybe there should be some modification in how Cart block behaves (e.g. just hide Proceed to checkout button?). I guess lots of people who want one-page checkout would attempt this, so we might as well be ready?

**To Reproduce**

1. Create a page
2. Add cart block
3. Add checkout block
4. They work nicely together, just the Proceed to checkout navigates away and kind of doesn't make sense in that context.

**Expected behavior**
I'm not sure what the best way to support this would be, but naive ideas are i) move viewport/scroll down on Proceed to Checkout or ii) hide Proceed to Checkout button if checkout block is on the same page.

**Comment by nerrad** [comment]
Good points, and great suggestions. Not sure we'll get this in for i1 but definitely going to put on our list.
