### ISSUE TITLE
No interaction in editor on mobile Chrome 

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce-gutenberg-products-block#2314]
**Describe the bug**
I've opened the editor with the Cart page in a mobile browser and I can't really do anything. The icons/buttons on top (+, Draft, Preview, Update, Gear) don't do anything, I can't scroll down. Only the panel on the top is still responsive. 

But when trying other pages with blocks, it seems those behave the same, so I guess it's not a problem with specifically cart & checkout? 

**Expected behavior**
Being able to interact with the page in editor, at least scroll down.

**Screenshots**
![Screenshot_20200427-145710_Chrome](https://user-images.githubusercontent.com/2207451/80375174-25df0200-8898-11ea-9107-067584436c11.jpg)

**WordPress (please complete the following information):**

* Core version: 5.4
* WooCommerce version: 4.0.1
* WooCommerce Blocks version: 2.6-beta.1
* Site language: en_US
* Any other plugins installed:
```
Active plugins (8)
--
Companion Plugin |   | by Osk – 1.11
Facebook for WooCommerce |   | by Facebook – 1.11.0
Jetpack by WordPress.com |   | by Automattic – 8.4.2
Mailchimp for WooCommerce |   | by Mailchimp – 2.3.6
WooCommerce Stripe Gateway |   | by WooCommerce – 4.3.3
WooCommerce Blocks |   | by Automattic – 2.6.0-beta.1
WooCommerce - ShipStation Integration |   | by WooCommerce – 4.1.35
WooCommerce |   | by Automattic – 4.0.1
```

**Smartphone (please complete the following information):**

* Device: Samsung Galaxy S8+
* OS: Android 9
* Browser Chrome 81.0.4044.117

**Comment by nerrad** [comment]
I can reproduce this with the simulated mobile views in Chrome.

**Comment by haszari** [comment]
Did some testing to clarify the details of this. Even with no blocks on the page, scroll is broken for small screens. Reproduced on Chrome and Safari with small window or responsive devtools view.

However, if I deactivate WooCommerce Blocks plugin, it works correctly - can scroll the page, edit etc. So maybe there's a bug with the styles we're enqueuing for woo blocks.

**Comment by nerrad** [comment]
Thanks for your additional testing @haszari ,  as a result I've pinned this as a high priority issue. It may be something that has existed for a while but I think we need to address it now that we know about it since it effectively breaks editor usage in mobile.
