### ISSUE TITLE
Input on checkout lags on Firefox mobile

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce-gutenberg-products-block#2319]
**Describe the bug**
It's a bit hard to describe because it's also based on a feeling of increased latency between the finger and the output on the screen, but the input fields on the checkout block lag quite a bit and miss some letters when typing/deleting quickly. This might be more pronounced on older devices. 

From what I saw, it doesn't happen on the old checkout screen with the same browser, so it seems like there is some additional processing happening that slows it down? Also, Chrome does not suffer from the same behavior, IIRC. 

Please see the vid below:
https://youtu.be/-c_HOuG_5xs

**To Reproduce**

1. In mobile Firefox, open 100 tabs
2. Navigate to the WC store, add item to cart
3. Go to checkout
4. Try to fill in any field in the Shipping options

**Expected behavior**
More snappy reactions.

Core version: 5.4
WooCommerce version: 4.0.1
WooCommerce Blocks version: 2.6.0-beta.1
Site language: en_US
Any other plugins installed:

```
Active plugins (8)
--
Companion Plugin |   | by Osk – 1.11
Facebook for WooCommerce |   | by Facebook – 1.11.0
Jetpack by WordPress.com |   | by Automattic – 8.4.2
Mailchimp for WooCommerce |   | by Mailchimp – 2.3.6
WooCommerce Stripe Gateway |   | by WooCommerce – 4.3.3
WooCommerce Blocks |   | by Automattic – 2.6.0-beta.1
WooCommerce - ShipStation Integration |   | by WooCommerce – 4.1.35
WooCommerce |   | by Automattic – 4.0.1
Smartphone (please complete the following information):
```

Device: Galaxy S8+
OS: Android 9
Browser Firefox 68.7.0

**Comment by nerrad** [comment]
This does sound like a potential performance issue.
