### ISSUE TITLE
Payment Method Integration: Smart Payment Buttons (PayPal Express)

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#2322]
Broken out from https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/1473

[Smart Payments Buttons](https://developer.paypal.com/docs/checkout/) is a PayPal payment method along the same lines as PayPal Express ([extension here](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout)).

This payment method would be idea for the block checkout, and I did a little investigation to see if we could add this by extending our extension. I got as far as adding buttons, but wasn't able to reuse any of the processing logic or scripts, and it looked like this would require a lot more time and effort to do correctly. 

The extension did have some useful features:

- The process of getting API details into the settings page is good - we should definitely keep that.
- It supports cart/checkout/product pages. Although Blocks only needs an integration on the checkout page currently.

But also quite a few issues:

- It covers lots of legacy PayPal Express methods and doesn't use current best practice. Rather than use the Smart Payment Buttons SDK, [it uses this legacy script](https://developer.paypal.com/docs/archive/checkout/).
- Not clear to be where order details are sent to PayPal - I think it's done all on the server side/using AJAX callbacks. We should use client side code instead.
- Too many options, and some of the settings (style controls) clash with the restrictions set up on Blocks checkout. We would definetely want to limit some of the control here to offer the best customer experience.

Additionally, we'd need these buttons to work in React. There is an example library here we could reuse or work from for reference: https://github.com/Luehang/react-paypal-button-v2 I tested this one and it worked well, but I only tested rendering, not processing. Basic implementation without processing:

```react
import { PayPalButton } from 'react-paypal-button-v2';
import { getSetting } from '@woocommerce/settings';

const settings = getSetting( 'paypal_express_data', {} );

export const ExpressCheckoutButton = ( props ) => {
	const { billing } = props;

	if ( ! billing?.cartTotal?.value ) {
		return null;
	}

	return (
		<PayPalButton
			amount={
				billing.cartTotal.value / 10 ** billing.currency.minorUnit
			}
			style={ {
				color: settings.button_color,
				shape: settings.button_shape,
				size: settings.button_size,
				label: settings.button_label,
				layout: settings.button_layout,
				tagline: false,
				branding: false,
			} }
			options={ {
				clientId: 'sb',
				currency: billing.currency.code.toUpperCase(),
				locale: settings.locale,
			} }
		/>
	);
};
```

![Screenshot 2020-04-27 at 14 50 48](https://user-images.githubusercontent.com/90977/80383218-38a70600-889b-11ea-9b0a-bfa4ddc703b7.png)

It might be a good idea to start over with this one with Block Checkout in mind, focussing solely on Smart Payment Buttons rather than all of the legacy methods, streamlining the codebase, and reducing the number of merchant facing settings. 

It would also allow us to move most of the order creation logic to the client side:

- Including the SDK script can be done dynamically. See how this React Library does it: https://github.com/Luehang/react-paypal-button-v2 I tried that library and it worked well.
- Setting up the amounts can come from the BillingContext (totals), and so can currency
- PayPal exposes some events around shipping which would allow us to get shipping rates via the API and update on PayPal side (https://developer.paypal.com/docs/checkout/integration-features/shipping-callback/)
- If the client side got authorisation, we'd just pass the token via **process_payment** to capture the funds and update the order. There would be less requests to the server overall.

I think we need to decide whether or not this gets added to blocks, a new extension, or the existing extension, but either way needs quite a bit of work. I'm sticking this in the icebox @nerrad since it's unlikely (?) to be looked at by our team any time soon.

**Comment by nerrad** [comment]
This is covered by #3173 so am closing.
