### ISSUE TITLE
Cart block: displays payment gateways logos even if I only have cheque active

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-gutenberg-products-block#2324]
**Describe the bug**
In the cart page see the payment gateways logos even if I only have cheque active

**To Reproduce**

1. Make sure that Cheque is the only payment turned on
2. Add the cart block to a page
3. Visit the cart page and see the payments' logos.

**Expected behavior**
Not seeing the payment gateways logos if the store only accepts cheque.

**Screenshots**
https://d.pr/i/VOh5Ml

**Comment by senadir** [comment]
This should be fixed by https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2267

**Comment by mikejolley** [comment]
Indeed; this was just missing functionality. See #2267
