### ISSUE TITLE
Cart/Checkout Blocks: Cart and Checkout Blocks can be added on the same page

### ISSUE THREAD

**Issue by chickenn00dle** [woocommerce/woocommerce-gutenberg-products-block#2335]
**Describe the bug**
The Cart and Checkout blocks can be added to the same page. This may be expected, but we are unable to assign the same page to both Cart and Checkout pages in **WooCommerce > Settings > Advanced**

**To Reproduce**

1. Create a new page
2. Add the Cart Block to the page
3. Add another block to the page.
4. While searching through the available blocks, Cart will be disabled, but Checkout will not and can be added to the same page
5. Repeat steps 1-4, this time first adding Checkout.

**Expected behavior**

Both Cart and Checkout should be disabled once either is added to a page.

**Screenshots**

![Screenshot_2020-04-29 Checkout Block – woostore localhost](https://user-images.githubusercontent.com/17905991/80556020-24831600-8a0d-11ea-8260-b502f4aab136.png)

**WordPress (please complete the following information):**

* Core version: 5.4
* WooCommerce version: 4.1
* WooCommerce Blocks version: 2.6.0-beta.1
* Site language: English

**Desktop (please complete the following information):**

* OS: iOS
* Browser FireFox
* Version 75.0

**Comment by nerrad** [comment]
This is currently expected. Granted, it does mean there could be some ux issues for links from other places in Woo Core if folks do this, but for now we aren't planning to restrict this.
