### ISSUE TITLE
If user doesn't have a privacy/terms page, checkout links to random page in footer

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#2339]
If the privacy links are enabled in checkout, but the site doesn't have the pages set up, then we render links to other pages (e.g. checkout in my testing!).

![Checkout - privacy:terms link broken when pages not set 2.png](https://images.zenhubusercontent.com/5ddb3cb39529f10001e618e5/c533df13-7ab3-4c1b-950e-cc17e910b74f)

I think this checkout option is enabled by default, so it should work well with any store setup – even if merchant has yet to set up privacy pages.

I'm thinking we only render the links if the page(s) are set, and always leave the option available (even if pages don't exist). (Seems simplest.)

**Comment by mikejolley** [comment]
Or we just fix the bug with the page query :p
