### ISSUE TITLE
Checkout - order summary card box has no bottom padding (in editor)

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#2340]
![Checkout - order summary cart lacks padding in editor.png](https://images.zenhubusercontent.com/5ddb3cb39529f10001e618e5/23283f94-0c91-46bc-bb73-0f64ceca7a0c)

Looks like it needs a bit more whitespace to be consistent with the rest of the box. See also related issues in summary area #2304 #2305

**Comment by nerrad** [comment]
I think this might be fixed in #2355, would you mind verifying and closing if so @haszari ?

**Comment by haszari** [comment]
Looks like this is still an issue with #2355 - note this is editor only. Here's a screenshot on `update/order-summary-styling` branch. Note the tight padding for each item row.

<img width="724" alt="Screen Shot 2020-04-30 at 9 13 33 AM" src="https://user-images.githubusercontent.com/4167300/80647780-25767f00-8ac3-11ea-9949-4245a70ad91d.png">

**Comment by mikejolley** [comment]
This is an issue with the variation data div which also happens on the frontend. On it.
