### ISSUE TITLE
Checkout footer / link options heading & help text could be improved

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#2341]
![Checkout - footer:link content options & help text could be improved.png](https://images.zenhubusercontent.com/5ddb3cb39529f10001e618e5/baf3ba92-4f1b-4e64-a8a8-e816ee6fdcef)

The heading and the help text are a bit abstract – would be great if we could make this clearer or highlight why these options are useful.

Since all this stuff is in the footer/bottom perhaps it's `Footer options`, or since it's all "link" related perhaps could use `Links`. Or maybe this is related to `No distraction checkout`?

Similar with `Form options` - these are all extra address fields, so maybe we could narrow this down as `Address options`.

![Screen Shot 2020-04-29 at 3.44.23 PM.png](https://images.zenhubusercontent.com/5ddb3cb39529f10001e618e5/80fd1817-7f14-4aee-8097-12159a6d5331)

I realise it's tricky getting this text right and a lot of thought has gone into these. If we can make these options even clearer it'd be great IMO :)

FYI @garymurray @LevinMedia  - you're the experts here

**Comment by haszari** [comment]
Also while we're looking at sidebar wording, `Display the checkout experience` seems a bit strange to me.  I think "experience" covers more than just the block (i.e. cart => checkout => order completed) or UI. I'm thinking "Allow customers to submit orders" is more focused on what the checkout block does.

**Comment by garymurray** [comment]
> The heading and the help text are a bit abstract – would be great if we could make this clearer or highlight why these options are useful.

> Since all this stuff is in the footer/bottom perhaps it's Footer options, or since it's all "link" related perhaps could use Links. Or maybe this is related to No distraction checkout?

They not quite in the footer though as per how a 'footer' is defined in the layout of a site. 

If anything we should probably separate them into two things:

`Return to cart` which would contain the toggle for the return to cart option and then something like `T&C and Policy pages`  which would contain the toggle for the T&Cs and Policy pages.

> Similar with Form options - these are all extra address fields, so maybe we could narrow this down as Address options.

Address options sounds much better here.

> Also while we're looking at sidebar wording, Display the checkout experience seems a bit strange to me. I think "experience" covers more than just the block (i.e. cart => checkout => order completed) or UI. I'm thinking "Show a checkout form so customers can submit orders" is more focused on what the checkout block does (how it delivers part of that experience).

Agree - let's change it to this perhaps: `Display a checkout form so your customers can submit orders` which I think aligns with some of the wording of our other blocks. 

It might make sense to review all the wording/descriptions we use across all the blocks to ensure they consistent in approach and set a guide for future descriptions as a separate PR/work.

**Comment by haszari** [comment]
I've started work on this in #2401. Refer to the PR for the exact wording and screenshots in context.

@garymurray I've taken some liberties with your wording above, in particular using `Navigation options` for policy/return to cart panel, rather than splitting out multiple panels each with one option. This is a starting point – it's tricky getting wording right, keen for feedback/ideas.

> It might make sense to review all the wording/descriptions we use across all the blocks to ensure they consistent in approach and set a guide for future descriptions as a separate PR/work.

Definitely a good idea. I think right now for Cart & Checkout things are pretty good, but still a great time to review as a whole. cc @LevinMedia

**Comment by garymurray** [comment]
Commented on the PR.
