### ISSUE TITLE
Cart - low stock badge has no margin

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#2342]
![Cart - low stock badge has no margin.png](https://images.zenhubusercontent.com/5ddb3cb39529f10001e618e5/339e926e-8b11-4fc8-9359-ef5b8ce0a526)

I saw this in editor, not sure if it's on front end also (I'm guessing it affects front end also).

**Comment by Aljullu** [comment]
Ah, I'm pretty sure I introduced this bug here:
https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2283/files#diff-52576519a9267d6cf2035fd6a560b0e2L4
