### ISSUE TITLE
Cart styles different in editor/front end (headings etc)

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#2344]
![Cart - editor heading styles (etc) different from front end.png](https://images.zenhubusercontent.com/5ddb3cb39529f10001e618e5/a9321fc3-7a46-44a1-abed-ad7e64fa2bd9)

The main cart heading is quite different, there may be a few other subtle differences here & there (e.g. quantity picker).

**Comment by nerrad** [comment]
Just noting, this _may_ be a theme issue.

**Comment by nerrad** [comment]
I think this affects checkout as well.
