### ISSUE TITLE
Log in button at checkout block displayed for logged in user.

### ISSUE THREAD

**Issue by vbelolapotkov** [woocommerce/woocommerce-gutenberg-products-block#2349]
**Describe the bug**

Saved Stripe cards are shown at the same time as `Log in` button at checkout block.

**To Reproduce**

1. Log in as admin.
2. Open new tab with the shop.
3. Go to `My account` page and add a payment method with Stripe. E.g. 4242 4242 4242 4242 (any date and cvc).
4. Add some products to the cart and go to checkout page.
5. Saved payment method is shown as well as `Log in` link at the top of the block.

**Expected behavior**
Expect either `Log in` link is not shown or saved cards not displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/3139099/80582824-0f5fb480-8a18-11ea-854d-0ca2c9b36e13.png)
![image](https://user-images.githubusercontent.com/3139099/80582847-171f5900-8a18-11ea-9fa8-c181e20fd3fd.png)

**WordPress (please complete the following information):**

* Core version: 5.3.2 
* Gutenberg version (if installed): n/a
* WooCommerce version: 4.0.1
* WooCommerce Blocks version: 2.6.0-beta.1
* Site language: en_US
* Any other plugins installed: 

WooCommerce PayPal Checkout Gateway |   | by WooCommerce – 1.6.20 – 1.6.21 is available – Not tested with the active version of WooCommerce
-- | -- | --
WooCommerce Stripe Gateway |   | by WooCommerce – 4.3.3
WooCommerce Blocks |   | by Automattic – 2.6.0-beta.1
WooCommerce Subscriptions |   | by WooCommerce – 3.0.3
WooCommerce |   | by Automattic – 4.0.1
WordPress Importer |   | by wordpressdotorg – 0.7

**Desktop (please complete the following information):**

* OS: OS X 10.15.4
* Browser Safari
* Version  13.1 

**Additional context**

**Comment by nerrad** [comment]
Thanks for the report! This is a good companion to #2325

**Comment by haszari** [comment]
This is fixed in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2375 (alongside another issue). Feel free to test @vbelolapotkov  - thanks for reporting :)
