### ISSUE TITLE
Checkout - Payment fails for saved Stripe card (or other saved payment methods)

### ISSUE THREAD

**Issue by vbelolapotkov** [woocommerce/woocommerce-gutenberg-products-block#2350]
**Describe the bug**
Payment fails when trying to pay with saved stripe card.
The same card can be used as new card.

**To Reproduce**

1. Enable Stripe gateway.
2. Log in and go to my account.
3. Add at least one payment method. E.g. 4242 4242 4242 4242 (any date and cvc). 
4. Add product to the card and go to checkout page.
5. Use saved payment method to place the order.
6. Error is shown: `Something went wrong. Please contact us to get assistance.`

**Expected behavior**
Order is placed successfully and used payment method is chardged.

**Screenshots**
![image](https://user-images.githubusercontent.com/3139099/80584380-41721600-8a1a-11ea-9ddc-f0415c0f5c82.png)
![image](https://user-images.githubusercontent.com/3139099/80584410-4cc54180-8a1a-11ea-98e9-67fe992cd952.png)

**WordPress (please complete the following information):**

* Core version: 5.3.2 
* Gutenberg version (if installed): n/a
* WooCommerce version: 4.0.1
* WooCommerce Blocks version: 2.6.0-beta.1
* Site language: en_US
* Any other plugins installed: 

WooCommerce PayPal Checkout Gateway |   | by WooCommerce – 1.6.20 – 1.6.21 is available – Not tested with the active version of WooCommerce
-- | -- | --
WooCommerce Stripe Gateway |   | by WooCommerce – 4.3.3
WooCommerce Blocks |   | by Automattic – 2.6.0-beta.1
WooCommerce Subscriptions |   | by WooCommerce – 3.0.3
WooCommerce |   | by Automattic – 4.0.1
WordPress Importer |   | by wordpressdotorg – 0.7

**Desktop (please complete the following information):**

* OS: OS X 10.15.4
* Browser Safari
* Version  13.1

**Comment by nerrad** [comment]
Hmm, I wonder if we forgot to wire up saved payment method processing...

**Comment by haszari** [comment]
Spotted another potential issue when testing this. When I save the payment method from checkout, it didn't show up as an option on next checkout.

This is what I did:

- Add a saved card via my account (same steps as in issue description above).
- Complete a purchase, with a different card number, and checked `Save payment information to my account for future purchases.` checkbox.
- Add something to new cart, view checkout - I expected to see both my saved cards, or the most recently added one.

I'll work on the original issue for now and we can log this as a separate issue if needed.

**Comment by nerrad** [comment]
Ya I'm pretty sure I forgot to wire up the saved payment method functionality to the server all-together, your latest report @haszari confirms that.

**Comment by haszari** [comment]
Logged a new issue for the `Save my card for next time` feature: https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/2411

**Comment by haszari** [comment]
Can also reproduce this issue by saving your payment method/card from the shortcode checkout (instead of setting it via `My account`), then do a new purchase => checkout with checkout block.

**Comment by haszari** [comment]
I noticed another quirk with saved payment methods that might be a bug. Mentioning here to clarify - I could see why this might be different in the new checkout. cc @garymurray 

It looks like the saved payment methods (saved cards/tokens) are nested under a payment method (tab), i.e. a saved card is a saved Stripe card. In the existing checkout the options are only shown when that method is selected:

![stripe-saved-card-old](https://user-images.githubusercontent.com/4167300/81135899-fd4cbb80-8fad-11ea-904a-d0d32f8cf541.gif)

In the new checkout, the saved option takes precedence. If you select your saved (stripe) card, the other payment options are hidden. 

![global-saved-card-new](https://user-images.githubusercontent.com/4167300/81135930-16556c80-8fae-11ea-86f4-26802f34b25e.gif)

**Comment by haszari** [comment]
Spent a while digging and didn't get far, though I found a problem persisting the saved card token and payment method id (name / slug, e.g. `stripe`).

I'm working in this branch - feel free to run with it or start afresh :) (cc @nerrad)

https://github.com/woocommerce/woocommerce-gutenberg-products-block/tree/fix/2350-use-saved-stripe-card

There was possibly an issue with the token etc not getting set up if user leaves default saved option selected. I was working around this in my testing by selecting stripe then selecting `Use my saved card` to retrigger the `updateToken` callback. (Maybe a blind alley!)

Apart from getting the token `POSTed` and handled on the server, there seemed to be another problem, with the `payment-methods` reducer state getting reset to `PRISTINE` during checkout processing, wiping out `paymentMethodData.savedPaymentMethodToken`.

**Comment by garymurray** [comment]
> I noticed another quirk with saved payment methods that might be a bug. Mentioning here to clarify - I could see why this might be intentionally different in the new checkout. cc @garymurray

> It looks like the saved payment methods (saved cards/tokens) are nested under a payment method (tab), i.e. a saved card is a saved Stripe card. In the existing checkout the options are only shown when that method is selected:

I did this intentionally - if someone has a saved payment method - we should show it to them on checkout without them having to click something/somewhere to find it.
