### ISSUE TITLE
Checkout - add order notes checkbox is not clickable

### ISSUE THREAD

**Issue by vbelolapotkov** [woocommerce/woocommerce-gutenberg-products-block#2351]
**Describe the bug**

Clicking `Add order notes?` checkbox has no effect on checkout block.

**To Reproduce**

1. Add some products and go to custom checkout page.
2. Click `Add order notes?`
3. Nothing happens

**Expected behavior**
Checkbox toggles on click and text area is displayed for the note when option is active.

**Screenshots**
N/A

**WordPress (please complete the following information):**

* Core version: 5.3.2 
* Gutenberg version (if installed): n/a
* WooCommerce version: 4.0.1
* WooCommerce Blocks version: 2.6.0-beta.1
* Site language: en_US
* Any other plugins installed: 

WooCommerce PayPal Checkout Gateway |   | by WooCommerce – 1.6.20 – 1.6.21 is available – Not tested with the active version of WooCommerce
-- | -- | --
WooCommerce Stripe Gateway |   | by WooCommerce – 4.3.3
WooCommerce Blocks |   | by Automattic – 2.6.0-beta.1
WooCommerce Subscriptions |   | by WooCommerce – 3.0.3
WooCommerce |   | by Automattic – 4.0.1
WordPress Importer |   | by wordpressdotorg – 0.7

**Desktop (please complete the following information):**

* OS: OS X 10.15.4
* Browser Safari, Chrome
* Version  13.1,  81.0.4044.122 

**Additional context**

**Comment by nerrad** [comment]
Thanks for the report! This functionality slipped through into beta 1 when it was supposed to be removed for the MVP, it was removed in beta 2.
