### ISSUE TITLE
Responsive layout not responding in Gutenberg previews 

### ISSUE THREAD

**Issue by josemarques** [woocommerce/woocommerce-gutenberg-products-block#2357]
While testing with Gutenberg 7.9.1 and WooCommerce 4.1.0-rc.1 the cart and checkout preview is not adapting well when using the tablet mobile previews: 

<img width="1404" alt="Screenshot 2020-04-29 at 15 27 04" src="https://user-images.githubusercontent.com/57050/80615089-2792fc00-8a37-11ea-8f91-04590eeecb4e.png">

<img width="1334" alt="Screenshot 2020-04-29 at 15 14 09" src="https://user-images.githubusercontent.com/57050/80614840-d8e56200-8a36-11ea-8951-9ecee41ee98c.png">

**Comment by nerrad** [comment]
@Aljullu this sounds like something that should be covered with #2274 right?

**Comment by Aljullu** [comment]
Yes, it is! I marked that PR as fixing this issue.
