### ISSUE TITLE
Checkout block broke after save

### ISSUE THREAD

**Issue by josemarques** [woocommerce/woocommerce-gutenberg-products-block#2360]
After saving my new checkout page with the checkout block and returning to that page I was faced with this error:

<img width="1403" alt="Screenshot 2020-04-29 at 15 20 34" src="https://user-images.githubusercontent.com/57050/80618426-46938d00-8a3b-11ea-8284-fdc6023a639f.png">

Pressing resolve converted the code to HTML: 

<img width="1404" alt="Screenshot 2020-04-29 at 15 21 14" src="https://user-images.githubusercontent.com/57050/80618477-57440300-8a3b-11ea-8e3d-6e7b7e95bee5.png">

<img width="1406" alt="Screenshot 2020-04-29 at 15 21 28" src="https://user-images.githubusercontent.com/57050/80618501-5f03a780-8a3b-11ea-970f-36cb2a48a6e6.png">

**Comment by nerrad** [comment]
Thanks for the report!

No one on the team was able to reproduce this, but the behaviour for how attributes are saved was changed in the recent [beta 2 release](https://github.com/woocommerce/woocommerce-gutenberg-products-block/releases/tag/v2.6.0-beta-2) which should reduce the risk of something like this happening. So if you're able, can you see if you can reproduce in beta 2? If so, you can re-open this issue with additional details about your environment so we can try and narrow down how to reproduce.
