### ISSUE TITLE
"Use same address for billing" does not persist

### ISSUE THREAD

**Issue by josemarques** [woocommerce/woocommerce-gutenberg-products-block#2361]
I submitted an order with different info in the shipping and billing sections. When following up with a new order the shipping info was retrieved but the checkbox for "Use same address for billing" was checked and the billing address use in the previous order was not retrieved:

![Checkout-new – My WordPress Site](https://user-images.githubusercontent.com/57050/80619269-65deea00-8a3c-11ea-9689-aa49944be6e7.jpg)

![Checkout-new – My WordPress Site 2](https://user-images.githubusercontent.com/57050/80619391-9030a780-8a3c-11ea-864b-3c8a6d595a0f.jpg)

<img width="568" alt="Screenshot 2020-04-29 at 17 12 27" src="https://user-images.githubusercontent.com/57050/80619449-9f175a00-8a3c-11ea-90b4-fa717c476eda.png">

**Comment by mikejolley** [comment]
@nerrad Do we want this to persist? Noting that this does not persist in core either, so we'd need a new method of tracking this and persisting it to the user profile.

Alternatively, we could compare stored billing address to stored shipping address and determine the checkbox value from that?

**Comment by nerrad** [comment]
I wasn't sure how it behaved in the current checkout but it sounds to me like this is something we could potentially improve on in this case. 

> Alternatively, we could compare stored billing address to stored shipping address and determine the checkbox value from that?

I like this option, it seems relatively trivial to implement and should work to improve the behaviour. We might just need to make sure we only do this for _existing_ customers though right (new customers - id 0?) will likely have just shipping address data?
