### ISSUE TITLE
All Products: Introduce the ability to set default filtered values for the Block

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#2373]
I've noticed in a few places that folks have been looking for the ability to more finely tune how many products appear in some of our grid blocks ([example here](https://wordpress.org/support/topic/products-by-category-block-does-not-list-all-products/)). While we could add additional options to all the existing blocks, I think there's value in keeping them for more targeted one off cases in templates etc, where more complete/flexible functionality isn't needed. Then for needs requiring flexibility around the content of each product in the grid and/or showing paging etc, the All Products block could be the next iteration.

To support this use case, I think there'd be value in introducing the ability for merchants to configure some default filters applied to the All Products block when it's content is first loaded. Used standalone, this would allow for some creative implementations in pages showcasing specific subsets of products and combined with existing filter blocks also allow for improving the _default_ experience merchants want for those views.

**Comment by kimmenbert** [comment]
This issue is related to improving the all products block with initial state: https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/1705

**Comment by kdgyimah** [comment]
Any progress?

**Comment by kdgyimah** [comment]
@nerrad Resolved?
