### ISSUE TITLE
Long product names upset layout in checkout order summary

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#2376]
![Screen Shot 2020-05-01 at 2.12.19 PM.png](https://images.zenhubusercontent.com/5ddb3cb39529f10001e618e5/aa5cae42-7453-4ba6-a7a6-b373e6c71ad9)

### To reproduce
- Edit the name of a product so it's super long with long words (think part numbers at a store that only sells truck/automotive parts) - e.g. `Long Semicircular Widget Flange, brown LBS_WF_5389u90ri3905i930ti609i509kmklm-b`
- Add that product to your cart, go to checkout (block of course)

The product name takes up more width than it should, doesn't wrap correctly, and the price is nudged out of the box. 

It looks like the `break-word` style is still applied, but the container width is too large and/or it's `flex-grow`ing bigger than we want.

**Comment by Aljullu** [comment]
I'm pretty sure I introduced this regression in #2348, so assigning it to me.
