### ISSUE TITLE
Checkout Block: Add support for - `Allow customers to create an account during checkout` option

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#2377]
There's a related option that we don't yet support - `Allow customers to create an account during checkout`.

<img width="824" alt="Screen Shot 2020-05-01 at 1 43 21 PM" src="https://user-images.githubusercontent.com/4167300/80774740-eecb6200-8bb1-11ea-995a-7d5b45a4c5a8.png">

_Originally posted by @haszari in https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/2252#issuecomment-622208649_

**Comment by mouligreenlaw** [comment]
Adding this ticket 3053275-zen

**Comment by haszari** [comment]
@LevinMedia I don't see this checkbox in the designs. I'm thinking we put it in the email address step, upfront - it could get lost in the address section. So something like this - let me know your thoughts:

<img width="1114" alt="Screen Shot 2020-07-13 at 11 55 13 AM" src="https://user-images.githubusercontent.com/4167300/87259487-c8a23680-c4ff-11ea-9d1c-39759c54af40.png">

In the design there's a `Keep me up to date on news and exclusive offers` checkbox, so I'm thinking this is similar to that (note - that checkbox is not implemented in current checkout).

Figma design:

<img width="1033" alt="Screen Shot 2020-07-13 at 11 51 16 AM" src="https://user-images.githubusercontent.com/4167300/87259426-4ca7ee80-c4ff-11ea-9a70-5a282227d221.png">

**Comment by haszari** [comment]
Update @LevinMedia - depending on store config, we should show username & password field in checkout `Create an account?` form. Here are the relevant settings:

<img width="1117" alt="Screen Shot 2020-07-13 at 1 59 14 PM" src="https://user-images.githubusercontent.com/4167300/87263389-225f2c80-c511-11ea-8722-d1edc22e619b.png">

And here's what it looks like in legacy checkout with both options disabled (as above):

<img width="698" alt="Screen Shot 2020-07-13 at 1 56 50 PM" src="https://user-images.githubusercontent.com/4167300/87263355-f80d6f00-c510-11ea-8e2e-2877c1ec9bc6.png">

FYI @Aljullu @nerrad - I'll continue with this, assuming we need to support all variations of these options for now.

**Comment by LevinMedia** [comment]
@haszari @Aljullu  @nerrad Let's go with the checkbox for creating an account. I'm going to look into providing the best possible copy for that. But don't let it block you. We can open a new issue to update it. I think it should explain (briefly) the benefits of creating an account.

That said, _I strongly want to avoid making the customer create a username and password in the midst of the checkout flow._ Per the [Baymard](https://baymard.com/) research data - that's a pretty big distractor that can lead to more abandoned checkouts. 

If the customer has to manually enter account details like a username or password, it's best if that happens  _after_ the purchase is made, either on the order success confirmation screen, or via an email.

**Comment by nerrad** [comment]
> That said, I strongly want to avoid making the customer create a username and password in the midst of the checkout flow. Per the Baymard research data - that's a pretty big distractor that can lead to more abandoned checkouts.

💯

**Comment by haszari** [comment]
Love the idea of streamlining account creation - nice work team :)

> In the case where an account creation happens after purchase, we might want to have that as a part of the interstitial flow in the checkout AFTER payment has been processed on the server.
> @LevinMedia doing the above, could require some flow mockups?

I think we can just implement the case where both "generate" options are checked (see below), and ignore these user options in the block. We could look at deprecating these options maybe with core, or just indicate in blocks docs that we only support the "autogenerate account username and password" flow in blocks.

@nerrad I'll see how this works out - might not need any extra design/screens, though there will be some error handling (e.g. account already exists).

- `When creating an account, automatically generate an account username for the customer based on their name, surname or email`
- ` When creating an account, automatically generate an account password`

**Comment by LevinMedia** [comment]
@haszari is there anyway we can sidestep the need for a username all together, and just rely on the provided email?

**Comment by haszari** [comment]
> @haszari is there anyway we can sidestep the need for a username all together, and just rely on the provided email?

@LevinMedia Yes ish - by relying on the WooCommerce option:

`automatically generate an account username for the customer based on their name, surname or email`

Though in all cases there will be a username, though the user might never see it (if they log in using email). I assume a username is somewhat required by WordPress for legacy reasons. I don't think we can ignore the username, it's probably unsafe to pretend it doesn't exist, since it's part of the underlying platform. If we could make this change we'd need to address it in at least Woo core. If there were to be a "no username" (email only) feature, the best place to implement it would be WordPress core.

**Comment by LevinMedia** [comment]
>automatically generate an account username for the customer based on their name, surname or email

@haszari do you know if that option is checked by default?

**Comment by haszari** [comment]
> > automatically generate an account username for the customer based on their name, surname or email

> @haszari do you know if that option is checked by default?

@LevinMedia Yes - these both options (autogenerate username and password) are enabled by default. I tested on a new ephemeral site with Woo 4.3.1 and these are the default settings:

<img width="1161" alt="pre-onboarding" src="https://user-images.githubusercontent.com/4167300/88248301-d2444f00-ccf4-11ea-904c-e4fa0dcf257f.png">

**Comment by haszari** [comment]
@LevinMedia Regarding autogenerated username and password, we've hit an issue there - see PR for details:  https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2851

Essentially we might need to tweak this behaviour in core to better support the autogenerate use case as the default. We could fall back to showing the username/password fields if needed but that's extra work for a less-good user experience.
