### ISSUE TITLE
[Single Product Block] Block Creation

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#2392]
Create and register the barebones block with the following title and description:

> **Single Product**
> Display a single product with its details and quantity.

- [x] Check ^ description with @garymurray. Doesn't seem great (quantity has no context).
- [x] Add new icon for block
- [x] Implement product picker using existing components (see featured product)
- [x] Sidebar settings (others from mockup will be part of atomic blocks)
  - [x] Product picker 
- [x] Create placeholder for product details/frontend/inner block view for now. This will be completed in a follow up.

**Comment by mikejolley** [comment]
> Display a single product with its details and quantity.

How about:

> Display details about a single product.

@garymurray? We shouldn't infer what details are shown since we'll support inner blocks.

**Comment by garymurray** [comment]
> We shouldn't infer what details are shown since we'll support inner blocks.

Agree, perhaps we can just shorten it even more to: `Display a single product`?
