### ISSUE TITLE
Expand our WordPress test matrix to cover all versions we support

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#2396]
After getting https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/2395 it would make more sense to test our blocks in different WordPress versions, currently, we test in the latest WordPress version, we should probably pin that version.

Recently we discussed that we need to increase our support from WP 5.0 to 5.2, we also have blocks that only work in 5.3, and we should cover them all in 5.4 (along with if the new blocks will only work in 5.4 or 5.3).

So the matrix is getting complicated and the range of testing is getting complicated.
We should possibly use an ENV variable to decide what tests on run directly inside our e2e, we will see how that goes.

**Comment by nerrad** [comment]
@senadir are you wanting to tackle this in the current sprint or the next?

**Comment by senadir** [comment]
this is a low priority issue, since it will only be some extra lines in travis, if time wans't enough, I will keep it for the next sprint.
