### ISSUE TITLE
[Atomic Block] Variation Picker Component

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#2398]
A new variation picker component is needed to support variable product add to cart forms. These pickers display available variation attributes, and hide/show options based on validity:

![Screenshot 2020-05-04 at 14.25.23.png](https://images.zenhubusercontent.com/546232087c6ccc6277a5e9a7/9c3c4eda-d7ff-4fe0-8fcb-8e44f7f8a2bc)

This component also needs to support default selections so it can be wired up to block settings:
![Screenshot 2020-05-04 at 14.25.34.png](https://images.zenhubusercontent.com/546232087c6ccc6277a5e9a7/41c7d0bd-cba5-40ba-9973-cea34fbd2fe4)

**API Requirements**

Currently the products API does give us child variation IDs, but doesn't provide attribute data (from the parent). Whilst this could be determined by looping over child variation IDs, that won't be efficient enough for this use case.

We'll need to surface from the API at a minimum:

- A list of product attributes (from the parent) which will form the values in the select boxes
- A collection of variations with _their_ attributes, and data such as ID, price, etc.
- (possibly) A way to match against a variations in the collection based on attributes. I think some collections support this already, this just needs checking with variations only.

Woo core has 2 approaches to these forms. 

1. For variations with few attributes and SKUs, the matching is all done client side using child variation attribute data to find a valid match.
2. For variations with many attributes and SKUs, all attributes are chosen, and then a request is made via AJAX to return a matching variation. This is to prevent performance issues from loading too much variation data at once.

What should we do here? I think there would be value of approaching this in a single way, but I am mindful of 'variation abuse' and performance issues if there are hundreds or even thousands of variation SKUs under a single product. cc @nerrad 

**UX**

The select boxes have designs, but nothing interaction wise has had design. Whilst we can mirror core, this probably needs design review before this issue can be resolved. 

- How we handle invalid combinations of attributes. Are the invalid options greyed out of hidden? Is there a way to reset the form once selections have been made? See core variations with multiple attributes for reference.
- After selecting attributes (and a variation ID is matched), what is shown? Core shows variation price and description/sku. 
- Similarly, if a match is not found, what is displayed? Core I believe shows an error stating the combination is not available.

Please also note, the 'greying out' or 'disabling' of invalid combinations in core is also impacted by the number of variations a product has. See the API section above; finding matching variations on the client side allows for this, whearas the ajax requests do not.

cc @garymurray

**Comment by nerrad** [comment]
> What should we do here? I think there would be value of approaching this in a single way, but I am mindful of 'variation abuse' and performance issues if there are hundreds or even thousands of variation SKUs under a single product. cc

It sounds like doing something similar to core here, as you listed, might be the preferable approach (with the difference being instead of ajax we'd use a REST endpoint). Do we know what how often large numbers of variations & attributes are used? 

Some additional complexity points that I'm not sure on here:

- It sounds like it'd be possible to have a relatively low number of variations, but a large number of attributes. So we might be able to load all the variations up front without issue but the number of product attributes could be problematic (or vice versa)?
- If we did on demand loading, how would that be presented to the shopper? How would they know there are additional options (would autocomplete be a potential solution here)?

**Comment by mikejolley** [comment]
> It sounds like it'd be possible to have a relatively low number of variations, but a large number of attributes.

Anything is possible, so yes thats a concern.

> If we did on demand loading, how would that be presented to the shopper? How would they know there are additional options (would autocomplete be a potential solution here)?

I think we'd need to populate attributes as a minimum. The dynamic loading portion is matching against variations and returning a filtered set of options.

We can base on core for now I think to ease design. It might have been what was intended. If there are optimisations along the way Ill update this thread.
