### ISSUE TITLE
Fix invalid X-WC-Store-API-Nonce Error on All Products block while logged out.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#2406]
**Describe the bug**

At first I thought this was just an artifact of how I was testing but it's become consistent enough that I'm writing an issue to both track this and also have someone else confirm if they are getting it. If reproducible, I think it potentially blocks releasing 2.6.0 (hence the labels).

**To Reproduce**

1. Setup All Products block on a page (I have all filter blocks setup too, not sure if that matters, but if you can't reproduce with just the All Product block, maybe try that too).
2. Load the page in an icognito browser instance.
3. Click to add a product to the cart. Should be no error. Click to add a second item to the cart. This is where I'd get the nonce error and am unable to add any product to the cart until...
4. The weird thing here is that if I reload the page hosting the block, I won't get that error anymore so the nonce is clearly being refreshed okay.

So the weird thing is that I can _consistently_ reproduce this on every _initial_ load of an incognito browser instance.

**Expected behavior**
I expect to _never_ see the invalid `X-WC-Store-API-Nonce` error

**WordPress (please complete the following information):**

* Core version: 5.4
* Gutenberg version (if installed): Not active
* WooCommerce version: 4.1
* WooCommerce Blocks version: Master
* Site language: English
* Any other plugins installed: Yes, but don't think they apply here.

**Desktop (please complete the following information):**

* OS: Mac OSX
* Browser Chrome
* Version 81.0.4044.129 (Official Build) (64-bit)

The response object from the failed request:

```json
{"code":"woocommerce_rest_invalid_nonce","message":"X-WC-Store-API-Nonce is invalid.","data":{"status":403}}
```

**Comment by mikejolley** [comment]
@nerrad I'm not able to replicate this. 

Perhaps check the XHR view in console, under preview, see the response headers. Is the nonce there consistent after each request? For me it is.

**Comment by nerrad** [comment]
I can still reproduce. Here's what I've discovered (keep in mind I'm also using a `npm run build` version - which I don't think should matter but I mention regardless:

- when I initially load the page I have the block on, there is no `X-WC-Store-API-Nonce` header in the response from any of the REST requests made.
- The first instance of clicking "Add to Cart" for a product is successful and returns `X-WC-Store-API-Nonce` in the header with this value `db89e109b5` (I know values change across environments, just sharing for the purpose of illustrating what happens in mine).
- I click another product's "Add to Cart" button and this request _fails_. The failing request returned the value of `a04ac475cb` for the `X-WS-Store-API-Nonce` header.

This is all happening while testing in the Chrome browser - however, I just tested in a Firefox Private window and the same thing happens (and it _consistently_ happens for me).

Thinking this may be an artifact of incognito or private modes, I decided to log out and open up a fresh browser instance to see if I could reproduce, and I can - consistently (using the same steps outlined in the pull description).

**Comment by mikejolley** [comment]
> I wonder if this has to do with starting with an empty cart? It seems that as long as there is an item in the cart, I don't have any issues.

Incognito (fresh window) always starts with empty cart, so I should be seeing what you are.

**Comment by nerrad** [comment]
Okay, so it sounds like this is something I'm going to have to debug more locally to find out what's causing, which I will do.

**Comment by mikejolley** [comment]
I found it was PayPal Express giving me an initial session. I can reproduce without that active and I have an idea what the issue is. On it!

**Comment by dasia123** [comment]
My website keeps giving the error x-wc-store-api-nonce is invalid woocommerce to my customers, how can I resolve this matter

**Comment by fylgjur** [comment]
Something similar reported in 27305918-hc and followed up in 3688475-zen - not yet reopening here as I'm unable to replicate currently in test.
