### ISSUE TITLE
Fix padding, alignment, and various UI inconsistencies in the block editor interfaces

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/woocommerce-gutenberg-products-block#2408]
There are various padding and alignment issues in block editor UI - these bugs are in the preview state of the blocks, as well as in the sidebar controls

Preview state:

<img width="1046" alt="Screen Shot 2020-05-05 at 1 52 01 PM" src="https://user-images.githubusercontent.com/4500952/81114939-cad08f00-8ed7-11ea-95c1-922c4de7fb63.png">

Sidebar:

<img width="268" alt="Screen Shot 2020-05-05 at 1 54 01 PM" src="https://user-images.githubusercontent.com/4500952/81115002-e5a30380-8ed7-11ea-8e7e-a95fc611b601.png">

Additionally some preview states have a grey background, while others have a white background:

<img width="783" alt="Screen Shot 2020-05-04 at 9 46 47 PM" src="https://user-images.githubusercontent.com/4500952/81115084-053a2c00-8ed8-11ea-8e1d-062171b90aa8.png">

<img width="791" alt="Screen Shot 2020-05-04 at 9 44 56 PM" src="https://user-images.githubusercontent.com/4500952/81115114-0ec39400-8ed8-11ea-8840-5e6548b37d66.png">

Gutenberg version: 8.0.0
WordPress Version: 5.4.1
WooCommerce Version: 4.1.0-rc.2

**Comment by Aljullu** [comment]
It looks like in the last version of Gutenberg the background of the placeholders was changed to white. We could make all our placeholders white too, but that makes the list of options to have no contrast with the placeholder background:
![imatge](https://user-images.githubusercontent.com/3616980/81188218-5704b400-8fb5-11ea-9581-814c19c38734.png)

For reference, this is how it used to look:
![imatge](https://user-images.githubusercontent.com/3616980/81188304-726fbf00-8fb5-11ea-9c35-2d269d671599.png)

@LevinMedia any thoughts on this? Should we add a border or change its background?

**Comment by Aljullu** [comment]
I also see the position of the _Done_ and _Cancel_ buttons is a bit weird:

![imatge](https://user-images.githubusercontent.com/3616980/81194318-ce8a1180-8fbc-11ea-99a4-c2ac2e8f0a08.png)

@LevinMedia do you know how should they be positioned? One on each side but with the same vertical alignment? One next to each other?

**Comment by LevinMedia** [comment]
>We could make all our placeholders white too, but that makes the list of options to have no contrast with the placeholder background:

@Aljullu Let's start by making all our backgrounds white, then adding a border to the scrollable container that is the same color as the horizontal dividers inside.

>I also see the position of the Done and Cancel buttons is a bit weird:

I'm taking cues from another block:

<img width="710" alt="Screen Shot 2020-05-08 at 2 45 34 PM" src="https://user-images.githubusercontent.com/4500952/81452049-b809c480-913a-11ea-9b24-5371d7f62302.png">

lets change "Done" to the primary button, and move cancel just to the right of it.

**Comment by Aljullu** [comment]
@LevinMedia sounds good, thank you!

Just one more thing I noticed. We might want to update the design of the _All Products_ block when editing the inner blocks:

![imatge](https://user-images.githubusercontent.com/3616980/81495990-97fe1080-92b4-11ea-9e5e-0b420555e8a0.png)

How it was before, for reference:
![imatge](https://user-images.githubusercontent.com/3616980/81496013-bd8b1a00-92b4-11ea-860d-355bbc70fa60.png)

**Comment by LevinMedia** [comment]
thanks @Aljullu I'll be posting design updates for this screen later this week, as part of a larger review of the "all products block" and the upcoming "product block".

**Comment by Aljullu** [comment]
From the discussion in #2456, notice some of the issues reported in this thread have been reported directly to WC Admin repo because they come from the `@woocommerce/components` package: https://github.com/woocommerce/woocommerce-admin/issues/4349.
