### ISSUE TITLE
Load @woocommerce/components from an external

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#2419]
Given that our minimum WC required version is 4.0, we can now load `@woocommerce/components` from the external. This will decrease our bundle size and ensure we use the same version as WooCommerce admin screens.

@senadir assigning it to you per the Slack chat we had yesterday. :slightly_smiling_face:

**Comment by haszari** [comment]
I might grab this as part of tidying up components in cooldown.

**Comment by haszari** [comment]
Closing this based on feedback in PR #3024 :

- We are using 1-2 of these components, i.e. a small subset.
- If we load from the external then the page payload will include all components (and any of their dependencies) - i.e. bloat.
- If we continue to load from package:
  - We can potentially tree-shake the library to load only what we need.
  - We'll be using a known version of the components, and won't need to handle different versions of the lib in different Woo core/wc-admin versions.

So for these reasons, we'll continue to load as an npm dependency as before (no change).

Feel free to reopen or open a new issue if I've missed anything!
