### ISSUE TITLE
Coupon field should be cleared after submit a coupon?

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#2427]
When you add a coupon in the cart, the text stays in the coupon field - I think it should probably clear out?

![Screen Shot 2020-05-07 at 3.41.40 PM.png](https://images.zenhubusercontent.com/5ddb3cb39529f10001e618e5/c26052ce-4a05-4d98-9190-048bb9dee5d7)

**Comment by mikejolley** [comment]
Clears for me after successful application. @Aljullu ?

**Comment by Aljullu** [comment]
Same for me, tested both in the _Cart_ and _Checkout_ blocks.

**Comment by haszari** [comment]
Working fine for me now too .. :) closing.
