### ISSUE TITLE
Cart block layout is broken in editor on mobile

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#2430]
**To Reproduce**
1. With a narrow viewport, create a post or page with the _Cart_ block.
2. Notice the layout is broken and doesn't look like in the frontend.

**Screenshots**
![imatge](https://user-images.githubusercontent.com/3616980/81301830-de1b6000-9079-11ea-940c-c108bf8d43c8.png)

**Comment by nerrad** [comment]
@Aljullu is this theme specific (i.e. does the same thing happen with themes other than Storefront?)

**Comment by Aljullu** [comment]
It's seems to affect all themes. I tested Storefront, TwentyTwenty and TwentyNineteen.
