### ISSUE TITLE
JS error when add both Cart & Checkout blocks to a post

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#2439]
### To reproduce
- Edit a post or page.
- Add the `Cart` block.
- Add the `Checkout` block.
- Publish, view on front end.

Expected: works (?) or prevent adding both to same page. See also related issue for post vs. page: #2440

Actual: JavaScript error in console: `Uncaught SyntaxError: Identifier 'containers' has already been declared`

Maybe related to loading skeleton stuff, error is on this line:

```js
const containers = document.querySelectorAll( 'div.wc-block-skeleton' );
```

**Comment by nerrad** [comment]
Good catch @haszari, this is a regression introduced in #2420 .  Likely can be fixed by just not using `const` in the script added php side.
