### ISSUE TITLE
clarify wording/APIs relating to payment method (used by shoppers) and payment gateway (implemented by extensions, installed by merchants)

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#2442]
Follow up issue from https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2425#issuecomment-625402179

In our code and the new payment-related APIs, we may be using `payment method` to refer to different things. For example:

1. An instance of a payment method, used by a shopper, to pay for an order - e.g. `stripe credit card ending with 1234` or `paypal account with email xyz@123`. These can be saved to user account - i.e. `pay with my saved card` feature.
2. A service, gateway or mechanism that merchant installs/configures so shoppers can pay - e.g. `Stripe Credit Card` `Paypal` `Cheque` `Cash on Delivery`. Aka a payment provider.

Note - payment extensions often bundle multiple gateways/mechanisms.

The goal of this issue is to ensure we are aligned and clear on these terms and any related wording. This helps to ensure the APIs, and potentially the UI too, are consistent and easy for payment providers to implement, and for merchants to configure. 

Note this is not specifically a blocks issue – these terms are in Woo core too. However, since we are implementing new payment related APIs for Cart & Checkout, it's a good time for us to review. Then we can fix any low-hanging fruit, or note any inconsistencies for follow up later.

**Comment by mikejolley** [comment]
Any customer facing wording should definitely avoid the term `gateway` and instead use `method`.

**Comment by haszari** [comment]
Related consideration - some gateways/extensions support multiple different payment methods. For example, `Stripe` extension includes `Stripe - Credit Card` and `Stripe - Payment Request`.

In the API we should aim to use consistent naming so this distinction is clear. In the new JS API it looks like we're using `name` for the extension, e.g. `stripe` and `id` for a payment method within an extension, e.g. `cc` or `payment-request`. I'm not sure what terms are used for these concepts in the Woo core gateway / extensibility API.

**Comment by nerrad** [comment]
The motivation behind this issue is sound. However I think the actionable item here is to watch for inconsistencies in code reviews and fix as we come across them.
