### ISSUE TITLE
Gutenberg page link functionality does not include product categories

### ISSUE THREAD

**Issue by ninetyninew** [woocommerce/woocommerce-gutenberg-products-block#2446]
**Is your feature request related to a problem? Please describe.**
If you use the link tool in the default Gutenberg paragraph block it doesn't list product categories to link to. Unsure if adding this functionality is a WordPress or WooCommerce thing.

**Describe the solution you'd like**
Allow product categories to be linked like individual products are in the WordPress link functionality.

**Comment by senadir** [comment]
This is unrelated to WooCommerce, Gutenberg link doesn't link to taxonomies (including WooCommerce categories and tags, and WordPress categories and tags), it only supports post types (Post, Page, Product...) it's best to fill this issue in https://github.com/wordpress/gutenberg/
