### ISSUE TITLE
Fix regression with payment method validation.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#2447]
In #2444 I fixed an issue with multiple source requests and it looks like that regressed some work done in #2374 which in turn removed the original `useCallback` on setValidations added in #2353 (see [comment](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2444#pullrequestreview-408289235)).

**Comment by haszari** [comment]
I'm just about to review #2450 - details of the the specific regression is a bit tricky to find. Here's my understanding of the issue:

- Add stuff to cart, proceed to checkout.
- Complete checkout fields but leave payment (stripe cc) fields empty.
- Submit order.

Expected: validation errors on payment fields prevent submit.

Actual: generic `Payment processing failed` notice on the page.
