### ISSUE TITLE
Create new block: "Hand-picked Products"

### ISSUE THREAD

**Issue by ryelle** [woocommerce/woocommerce-gutenberg-products-block#245]
See p6riRB-3K4-p2

> The Selected Products block enables the author to insert a grid of hand-picked products. It’s kind of like the traditional Featured Product feature in WooCommerce except it can be easily adjusted on-the-fly without affecting other areas of the store.

Sidebar options are Layout, Order by, Products

![333077573](https://user-images.githubusercontent.com/541093/49970709-3b00fe00-fefa-11e8-8faf-f21e81d6351b.png)

This relies on #244 being created/merged first.

**Comment by strarsis** [comment]
Isn't this the same as using 'Featured products' as source?

**Comment by ryelle** [comment]
Added in #276

**Comment by gsim** [comment]
An issue with it is there is no class added if a product is sold out, so no way of targeting sold out items with css. They just show as normal. Really not sure if this is the right place to bring this up.
