### ISSUE TITLE
Revisit our CSS selectors naming

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#2457]
We have some components whose CSS selector is `.wc-block-components-` while some others is `.wc-block-`, we should unify this and make sure it's in line with the [coding guidelines](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/docs/contributors/coding-guidelines.md#css-class-names).

**Comment by Aljullu** [comment]
Over time, the class names used in our components have become a bit messy and currently it looks like this:

| Location in the tree | Class names used |
| --- | --- |
| assets/js/atomic/blocks | `.wc-block-components-` |
| assets/js/base/components | `.wc-block-`<br>`.wc-block-components-`<br>_(inconsistent usage between both)_ |
| assets/js/blocks | `.wc-block-` |
| assets/js/components |  Most: `.wc-block-`<br>One component uses: `.wc-block-components-` |

In order to make our lives easier and reduce complexity for 3rd-party themes, I think we should solve the inconsistencies and make it clearer which class names are used in the markup of our blocks and which ones are only used in the editor.

I propose the following changes:
* Leave **assets/js/atomic/blocks** as it is now.
* Consolidate all components inside **assets/js/base/components** to use the prefix `.wc-block-components-`.
* Differentiate components in **assets/js/blocks** between the ones used in the editor and the ones used in the frontend. Use prefixes `.wc-block-` and `.wc-block-editor-` accordingly. As a rule of thumb that means:
  * Components in `block.js` will have the `.wc-block- ` prefix.
  * Components in `editor.js` will have the `.wc-block-editor- ` prefix.
* Migrate all components inside **assets/js/components** to use a new prefix `.wc-block-editor-components-`.

So the table above would look like:

| Location in the tree | Class names used | Can be styled by themes?
| --- | --- | :---: |
| assets/js/atomic/blocks | `.wc-block-components-` | ✓ |
| assets/js/base/components | `.wc-block-components-` | ✓ |
| assets/js/blocks | `.wc-block-`<br>`.wc-block-editor-` | ✓<br>✘ |
| assets/js/components |  `.wc-block-editor-components-` | ✘ |

The benefits of this approach?
* We make it clear what components can be styled by themes and which others can't. All classes that have a `-editor-` prefix are used in the editor, so themes shouldn't style them. All other class names, are themable. This makes documentation simpler and makes it easier for us to identify breaking changes in the future: if you change a `-editor-` class, you can do it safely; if you change another class, better write release notes.
* Doing the change above, the only breaking change we will face now would be some `.wc-block-xyz` class names that will change to `.wc-block-components-xyz`.
* If we ever want to publish a `@woocommerce-blocks/components` or `@woocommerce-blocks/editor-components` packages, the class prefixes will match the package names, as [stated in our coding guidelines](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/docs/contributors/coding-guidelines.md#naming).

Thoughts @woocommerce/merch-squad?

**Comment by Aljullu** [comment]
Ok, let's leave `assets/js/atomic/blocks` as it is for now. I created a PR with updated coding guidelines and docs for themes in case you want to take a look: #2691.

**Comment by senadir** [comment]
> 1. For components that have been introduced in 2.6.0 and 2.7.0, just switch to the new class names and add a dev note.
> 2. For components that have been shipped with WC Core, we could keep the old class name while adding the new one. In the docs, we could explain that if both class names are there, the one without -components- is deprecated and will be removed in the future.

this seems like a good deprecation policy.

I don’t have opinions about the rest of the things, I think I'm failing to see any possible issues.

**Comment by senadir** [comment]
I  feel like we can close this right? I believe we solved this in other PRs.
