### ISSUE TITLE
X-WC-Store-API-Nonce header missing in production builds

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#2468]
**Describe the bug**
Checkout and Cart are currently broken on production

**To Reproduce**
1. create a production build `npm run build`
2. in Checkout, trigger a server request (change shipping, update info).
3. Block will break with the error `Error: Missing the X-WC-Store-API-Nonce header. This endpoint requires a valid nonce.`

**Comment by haszari** [comment]
Good find @senadir ! A good reminder that we should try and test using production builds as much as possible. Would be cool to set up a nightly build or an automated build for all PRs using Travis or something, so PR testers can download a zip easily :)

**Comment by haszari** [comment]
e2e might be able to catch issues like this too … 🤔

**Comment by webdeveloperplus2** [comment]
How do I fix my site?  This just started happening to me.

**Comment by senadir** [comment]
Hey, this should have been fixed in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2469, what version are you running
