### ISSUE TITLE
Set image size

### ISSUE THREAD

**Issue by strarsis** [woocommerce/woocommerce-gutenberg-products-block#247]
**Is your feature request related to a problem? Please describe.**
Image size should be changeable, either by block option and/or by a filter for theme.

**Describe the solution you'd like**
A block option and/or filter.

**Describe alternatives you've considered**
Crop/resize using CSS on user side, but this wastes bandwidth.

**Comment by ryelle** [comment]
Hi @strarsis – currently the products blocks use the `products` shortcode, so you can control the output of the block the same way you would customize the shortcode. We're investigating different image handling/responsiveness for a future version, so I'm going to close this issue for now.

**Comment by strarsis** [comment]
@ryelle: Is there also a filter that only applies to the thumbnails inserted by the shortcode (and this Gutenberg block)?

The shortcode uses a product template file which seems to be generally used, not only by the shortcode:
https://github.com/woocommerce/woocommerce/blob/bdf5c02f48989d2d7acb1c0dc8e92565faa4536a/includes/shortcodes/class-wc-shortcode-products.php#L643
