### ISSUE TITLE
billing_address.email field missing when order submitted

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#2474]
**Describe the bug**
When logged out, orders fail with a missing email address. 

This issue was discovered by @nerrad when testing https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2473. 

Note that this issue can not be reproduced on current master. The regression from #2467 (fixed in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2473) masks the issue - if no payment methods are available (when logged out), then you can't submit an order (and see the bug).

To reproduce, check out b0977750ba2d66634756f4588458374640cde762 (prior to merge of #2467) or @nerrad fix branch (https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2473).

<img width="2031" alt="Screen Shot 2020-05-13 at 1 51 51 PM" src="https://user-images.githubusercontent.com/4167300/81762784-a1d87b80-9521-11ea-81b4-2b82e4822555.png">

**To Reproduce**

0. Clone & build b0977750ba2d66634756f4588458374640cde762 or #2473
1. Open incognito browser or log out. Ensure store allows anon orders (Woo Accounts setting).
2. Add stuff to cart, proceed to checkout. Complete all the form fields, especially email.
99. Submit a payment with cheque or stripe (happens with either) with all valid fields filled out.

Expected: `billing_address.email` field is sent to server, purchase success

Actual: fail with error, and `billing_address.email` field is empty in request

**Comment by haszari** [comment]
Update: seems to work ok if you manually enter a billing address - i.e. untick `Use same address for billing`. So something screwy with the field binding.

<img width="684" alt="Screen Shot 2020-05-13 at 2 26 26 PM" src="https://user-images.githubusercontent.com/4167300/81764453-bb7bc200-9525-11ea-9eaa-26d41865ce27.png">

**Comment by haszari** [comment]
Maybe related to recent checkout address work: https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2374

**Comment by haszari** [comment]
FYI @mikejolley for when you come online :)

**Comment by haszari** [comment]
I had a quick dig around and saw a lot of eslint hook dependency warnings, for example in new `useCheckoutAddress`. So perhaps we try fixing them all - not sure how risky that is before RC? cc @nerrad

**Comment by nerrad** [comment]
> So perhaps we try fixing them all

Yup I've been fixing those as I come across them in relation to work being done (so testing for that work also covers the fixes).

RC1 is coming but I'm okay with pushing it a day if we feel we're introducing potential instability that needs more testing.

**Comment by nerrad** [comment]
Also #2473 is merged to master so this can be fixed off master.
