### ISSUE TITLE
Fix default saved payment method selection not working in specific circumstances.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#2483]
Spotted this bug while doing more testing. To reproduce.

- Test while logged in (because it affects saved payment methods).
- Setup saved payment methods so you have multiple saved payment methods from stripe.
- Start a checkout but don't select any other payment methods and just leave the default checked.
- When you submit the checkout, you'll get an error. 

If you look at the request, you'll see that the package has `false` for the saved payment method.

**Comment by haszari** [comment]
Looks like the default payment method is persisted on setup via onChange, but then the payment-methods reducer state gets reset via `PRISTINE` at least once after that during the rest of setup. cc @nerrad

**Comment by haszari** [comment]
This is firing and resetting to pristine, after the onChange, which is supposed to set it to successful:

```js
	// When checkout is returned to idle, set payment status to pristine
	// but only if payment status is already not finished.
	useEffect( () => {
		if ( ! currentStatus.isSuccessful ) {
			dispatch( statusOnly( PRISTINE ) );
		}
	}, [ checkoutIsIdle, currentStatus.isSuccessful ] );
```

**Comment by mikejolley** [comment]
Sounds like it could be related to this running on first mount?

**Comment by mikejolley** [comment]
That was it. Creating a PR.
