### ISSUE TITLE
Explore ways so form elements in blocks don't look disabled in the editor

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#2487]
When adding the _Cart_ or _Checkout_ blocks in the editor, all form elements look disabled, which makes them look different from the frontend. This issue is about exploring a way to keep them disabled but look like if they weren't.

See previous discussion in #2437 

### Screenshots
_Editor:_
![imatge](https://user-images.githubusercontent.com/3616980/81926959-24753f80-95e3-11ea-8cd4-6374ff3870ce.png)

_Frontend:_
![imatge](https://user-images.githubusercontent.com/3616980/81926524-5df97b00-95e2-11ea-88a0-1cefeed1c044.png)

**Comment by senadir** [comment]
we stop using `<Disabled>` and create our own `<Disabled>` component, in it, we can disable remove user events using `user-events: none` this will handle mouse things, focus will still be an issue, we can fix that by using `inert` an HTML property that removes a block from the page flow without removing it, like disabled but without adding disabled, it's not supported, for now, there're some polyfills, this is one https://github.com/WICG/inert/
I suggest we just copy the code and it to our custom `<Disabled>` component.

**Comment by ralucaStan** [comment]
Another issue I found was that in other blocks is that this disabled style is not normalized.
All the inputs in the image below are disabled, but they have different styling -> grey or white background.
<img width="633" alt="Screenshot 2021-02-18 at 13 49 11" src="https://user-images.githubusercontent.com/1628454/108370933-82cbf000-71fd-11eb-9d6d-4b56dfd40264.png">

Another thing I found is that the disabled product buttons aren't consistent as well in the editor
<img width="731" alt="Screenshot 2021-02-18 at 13 59 28" src="https://user-images.githubusercontent.com/1628454/108371009-98411a00-71fd-11eb-903f-6b58cb9ae668.png">
