### ISSUE TITLE
Checkout block: 'Free shipping' preview method has a price of $2.00

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#2490]
**To Reproduce**
1. Add a _Checkout_ block and view it in the editor.
2. Notice one of the shipping options is named _Free Shipping_ but it has a price of $2.00.

**Expected behavior**
If it's named _Free Shipping_, I would expect its price to be $0.00.

**Screenshots**
![imatge](https://user-images.githubusercontent.com/3616980/82036289-04a45100-96a1-11ea-9de8-1b1b02e2ce85.png)

**Comment by nerrad** [comment]
Ha! good catch, nice little polish thing to improve here :)
