### ISSUE TITLE
Resource heavy pages with filters and all products block

### ISSUE THREAD

**Issue by kimmenbert** [woocommerce/woocommerce-gutenberg-products-block#2500]
**Description**
Having multiple attribute filter blocks on a page is really resource heavy.
Reloading a page makes 4 cpu cores (9 attribute filter blocks) go straight up to 100% usage while the Storage API calls is doing the heavy lifting.

The site makes 9 requests to the /wc/store/products/attributes/ID/terms API and one request to the wc/store/products/collection-data API (2 requests if you've got the filter by price block aswell)

This totals to a 4 seconds wait just for the blocks to be fully rendered.

**To Reproduce**
Probably best to test on a site with many products and attributes.
Add multiple filter by attribute blocks to page
Check network tab in devtools

**Setup**
WordPress, WooCommerce and Storefront. Eveything latest version.

**Comment by nerrad** [comment]
Thanks for the report Kim. This is definitely something on our radar!

**Comment by nerrad** [comment]
@mikejolley it'd be interesting to see how the batch request work you did impacts this issue - I think it will right?

@kimmenbert, some recent work was merged in #4075 that batches requests together into one request that should help address this performance issue you highlighted on sites with the required WP version installed (I think the batch feature for REST came in WP 5.6). It will be more widely available with the release of WC Blocks 5.0 next week if you want to check?

**Comment by mikejolley** [comment]
@nerrad Batching currently only impacts POST requests, not GET. If we roll out GET it will help here.

**Comment by nerrad** [comment]
Ahh right 👍
