### ISSUE TITLE
Add categories/product taxonomies to a core/navigation block

### ISSUE THREAD

**Issue by strarsis** [woocommerce/woocommerce-gutenberg-products-block#2505]
Can WooCommerce categories/product taxonomies (like product attribute terms) be added automatically to a `core/navigation` block?
Currently, I have to insert/update each and every WooCommerce category/product taxonomy term for a `core/navigation` block manually, including the URL.

**Comment by nerrad** [comment]
Hi there 👋@strarsis

That's an interesting idea and definitely would be a nice improvement for folks utilizing the `core/navigation` block.

We won't be able to tackle this in the upcoming weeks as we're currently focused on finishing all the work that was identified as a priority for the next release of this plugin.  I'm going to add this to our backlog where it will be considered for future releases (or if there's a way we can improve the behaviour of the `core/navigation` block - this may be something that needs developed in the Gutenberg project itself).

**Comment by strarsis** [comment]
@nerrad: I just noticed that now besides a normal menu link block, also a search block can be added.

**Comment by strarsis** [comment]
@nerrad: So such navigation blocks have been added now? Or was this feature request discarded?

**Comment by nerrad** [comment]
Hi @strarsis, sorry I should have left a comment why this was closed. 

We've been going through our issues and triaging things to try to be honest about what will be worked on and things that just don't have the resources to tackle anytime soon.

While the request here is _valid_, the navigation blocks are not in WordPress core yet and are still being perfected (I'm aware they are in the Gutenberg plugin). We _do_ intend on making sure WooCommerce surfaces it's data appropriately in any new Core blocks and workflows but that's something that will be done on as a part of general WordPress compatibility work (or when we dedicate time to working with upcoming Gutenberg features). 

So closing this issue doesn't mean the request is discarded, the request is on our radar.
