### ISSUE TITLE
"Hidden" products show up in preview, but not front end

### ISSUE THREAD

**Issue by ryelle** [woocommerce/woocommerce-gutenberg-products-block#252]
Like #124, this is another case of a disparity between block preview & front end. In this case, hidden products are returned in the API response, but they aren't shown when the shortcode renders on the front end of the site. 

Hidden products should return via API in general, but we should probably see if we can set something to only return `catalog_visibility=visible` products.

**Comment by ryelle** [comment]
@claudiosanches @claudiulodro Is there a way to get only visible products from the API? I see that `catalog_visibility` should be set to `visible` by default, but I don't think that API parameter does anything.

For example, I can `GET /wc/v3/products?catalog_visibility=hidden`, and I should only get one product in the response, but it seems to ignore the visibility setting and returns everything.

**Comment by claudiulodro** [comment]
There doesn't seem to be a feature in the API yet to control the visibility. Since this plugin is using its own custom version of the products API it should be possible to add it here, though, and have this feature available in the next version of the API.

**Comment by ryelle** [comment]
Ah, I was misreading the schema for the request + product properties on [the API page](https://woocommerce.github.io/woocommerce-rest-api-docs/#products) and thought that `catalog_visibility` was a collection param. I'll add it to the API here.

**Comment by ryelle** [comment]
@jameskoster @LevinMedia Right now, if a product is "hidden", it doesn't show in the shortcode, but it does render in the API preview. This is causing the above issue, where @ercousin expected the hidden products to display on the front end.

What do you think? If a product is set as "hidden", should it appear in the blocks? For reference, this is the "Catalog visibility" setting on a product:

![screen shot 2019-01-31 at 12 09 07 pm](https://user-images.githubusercontent.com/541093/52071451-08b26b00-2551-11e9-8937-92591e35fc12.png)

**Comment by jameskoster** [comment]
If it's hidden it shouldn't appear in the preview. Based on that it probably shouldn't appear in any product lists as selectable either, e.g. in the Featured Product block.
