### ISSUE TITLE
Checkout block: pressing Enter when the card inputs have focus reloads the page (Firefox)

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#2529]
I'm not sure if that's an issue we can fix or it's a bug with Stripe's library. But filling it for awareness.

**To Reproduce**
1. With Firefox, go to the _Checkout_ block.
2. Fill the form including the card number inputs.
3. Still having focused one of the card number inputs, press <kbd>Enter</kbd>.
4. Notice the page reloads.

**Expected behavior**
When pressing <kbd>Enter</kbd> it should either submit the _Checkout_ form or do nothing. In other browsers, it seems to do nothing. But reloading the page is confusing.

**Screenshots**
![Peek 2020-05-21 12-40](https://user-images.githubusercontent.com/3616980/82551321-42512000-9b60-11ea-925b-ee84ab9acab1.gif)

**Comment by nerrad** [comment]
I think this is a blocker to release because it would be jarring for shoppers to have this happen (and is also an a11y issue).
