### ISSUE TITLE
Filter blocks: switch to named font sizes

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#2536]
In #2533 we introduced named font sizes to keep them consistent across blocks. However, the _All Products_ and filter blocks were not migrated yet. This PR is about migrating them once we agree on how to map them to the new named font sizes.

![123](https://user-images.githubusercontent.com/3616980/82656480-231bc680-9c24-11ea-87c7-5cc0c14f7106.png)

**Comment by Aljullu** [comment]
After discussing this with @LevinMedia, we will migrate the Filter font sizes to the named ones, but we will keep the _All Products_ ones for now. We want to explore if we can allow the user to customize them similarly to other textual blocks.

**Comment by Aljullu** [comment]
The dropdown value sizes were 12.8px (or 0.8em), so they felt a bit between our XS size (12px or 0.75em) and the S size (14px or 0.875em). I tried with both sizes and this is how they look:
| XS (`smaller`) | S (`small`) |
| --- | --- |
| ![Screenshot from 2020-05-29 12-26-39](https://user-images.githubusercontent.com/3616980/83250100-de55d980-a1a7-11ea-90f1-2998a93262b0.png) | ![Screenshot from 2020-05-29 12-26-50](https://user-images.githubusercontent.com/3616980/83250140-f168a980-a1a7-11ea-9d3d-9caff82e364d.png) |

@LevinMedia any preference? I kinda like it more with S size.

**Comment by LevinMedia** [comment]
+1 for (S) Small thanks!
