### ISSUE TITLE
All Products in TwentyTwenty: on sale badge is not correctly positioned

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#2537]
**To Reproduce**
1. Add an _All Products_ block.
2. Add a _Sale_ badge below the title.
3. Notice it's right aligned in the editor.
4. Open the page in the frontend and notice the sale badge is rendered on the top-right corner of the image.

**Screenshots**
![imatge](https://user-images.githubusercontent.com/3616980/82657596-e650cf00-9c25-11ea-8b39-bc7c855a77dd.png)

**Comment by haszari** [comment]
I'm thinking the sale badge should always be positioned top-right, overlaying the image. Am I missing something?

**Comment by haszari** [comment]
DOh! I see, there's an option for an extra sale badge? I had no idea! 

Figured it out, it's a nested block, now I understand the issue :)
