### ISSUE TITLE
Identify which blocks have font colors that don't play well with some specific backgrounds

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#2539]
Besides the _Cart_ and _Checkout_ blocks, we found that some other blocks don't play well with dark backgrounds:
![1234](https://user-images.githubusercontent.com/3616980/82659026-4a749280-9c28-11ea-8fbc-4329b7f13043.png)

This PR is about identifying all of them and creating issues to fix each one of the glitches.

**Comment by ralucaStan** [comment]
@Aljullu I can take a look here. 
- Testing different dark colors is a big task, should we focus only on black `#000`?
- About font colors that don't work well: should we just note here the ones that fail the a11y contrast check?

I don't think we can find a color for all cases, but it would help me to understand better what the expected result is here.

**Comment by Aljullu** [comment]
> Testing different dark colors is a big task, should we focus only on black #000?

Sounds good. Testing black or dark gray will expose most contrast issues.

> About font colors that don't work well: should we just note here the ones that fail the a11y contrast check?

Yeah, I guess we first need to identify them and then fix each one of them individually. Ideally we shouldn't specify any text color so strings inherit the color from the theme (only exception is when we control the background, ie: input fields, buttons, etc.).

**Comment by ralucaStan** [comment]
@Aljullu please take a look at my findings and let me know which ones should we handle in separate tickets.

Here are my findings:
1. Product rating is barely visible, in any block that shows it
<img width="450" alt="Hand-picked Products" src="https://user-images.githubusercontent.com/1628454/108357639-fe25a580-71ed-11eb-8318-4be759c38c9c.png">

2. The cursor for _Filter Products by price_ is cut on top-bottom and is more visible on dark backgrounds
<img width="300" alt="Screenshot 2021-02-18 at 13 14 54" src="https://user-images.githubusercontent.com/1628454/108357761-28776300-71ee-11eb-835f-7959fd24ea09.png">

3. The button from _Product search_ is barely visible
<img width="575" alt="Screenshot 2021-02-18 at 12 35 28" src="https://user-images.githubusercontent.com/1628454/108357873-4e9d0300-71ee-11eb-88f4-708fc74efc75.png">

4. Only the icon from the button in _Active Product filters_ is visible, the action area is hard to detect.
<img width="473" alt="Screenshot 2021-02-18 at 13 14 18" src="https://user-images.githubusercontent.com/1628454/108357905-58bf0180-71ee-11eb-813a-083833e340bc.png">

5. The Hover color for the "Add to cart" button 
<img width="650" alt="Screenshot 2021-02-18 at 13 20 51" src="https://user-images.githubusercontent.com/1628454/108358138-a50a4180-71ee-11eb-878d-c58930a8ea9e.png">


It also appears that The inputs from Filter by color and other _Filter by attribute_ blocks have been fixed.
<img width="306" alt="Screenshot 2021-02-18 at 13 45 07" src="https://user-images.githubusercontent.com/1628454/108359016-b99b0980-71ef-11eb-97cf-9beaa187f6ef.png">

**Comment by Aljullu** [comment]
Good findings @ralucaStan, thanks for doing this research!

> @Aljullu please take a look at my findings and let me know which ones should we handle in separate tickets.

I think all of them are worth fixing. I'm fine either way: creating a separate ticket for each one or using this one as a meta-ticket.

> 1. Product rating is barely visible, in any block that shows it

Maybe that was an issue with fonts? In theory, you should see yellow stars instead of text.

> 5. The Hover color for the "Add to cart" button

That button should use the color from Customize > Buttons (if using Storefront or a child theme). If it doesn't, that's probably a bug.

**Comment by ralucaStan** [comment]
> 1. Product rating is barely visible, in any block that shows it

I tried to fix it but was unable to find a solution that works in all blocks. It's related to the markup and I think it's best for it to be fixed in #1916.

> 2. The cursor for Filter Products by price is cut on top-bottom and is more visible on dark backgrounds

Fixed in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3887. I removed the glow effect, as it was inconsistent with the UI, and hard to fix while the icons come from a sprite.

> 3. The button from Product search is barely visible

Fixed in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3887. I removed custom styling for this button and the one in _Product Categories List_. These buttons were the only ones with shadow & rounded corners and with no background. They also had no focus style. Now they have the same style as the buttons in other blocks. 

> 4. Only the icon from the button in Active Product filters is visible, the action area is hard to detect.

Fixed in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3887 I changed the button to accommodate an svg with a `fill ="currentColor"`


> 5. The Hover color for the "Add to cart" button

I haven't fixed this and I would need more details to do so. I also noticed that the fallback color when disabling the current one is not necessarily better. @Aljullu should we skip this one?

**Comment by Aljullu** [comment]
> I haven't fixed this and I would need more details to do so. I also noticed that the fallback color when disabling the current one is not necessarily better. @Aljullu should we skip this one?

Yes... I can't think of any way to fix it other than adding a light border around the button, but I don't think it's worth it because it might affect negatively other themes.

In Storefront and child themes, the button honors the `Alternate button background color` set in Appearance > Customize > Buttons, so it will look fine if colors are set up correctly.

For other themes that might have dark backgrounds, I think the best approach is for them to add styles on top of ours.  We have [docs about styling WC Blocks buttons](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/theming/cart-and-checkout.md#buttons) that we can share with 3rd-party devs if we see a theme that is not working fine with our buttons.

In the future we can revisit this decision with a [global styles](https://github.com/WordPress/gutenberg/issues/20331) based approach.
