### ISSUE TITLE
Address form: fields no longer update when changing the country

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#2541]
In the past, the address form changed based on the selected country (see #1847):
![Peek 2020-03-02 17-46](https://user-images.githubusercontent.com/3616980/75697752-d3290580-5cad-11ea-8166-3964525db38a.gif)

But that doesn't seem to work for me in `master`.

**Comment by nerrad** [comment]
Ugh, ya I can reproduce too. I'd like to have this resolved before releasing 2.6.0 so I'll see if I can work on it over the weekend.
