### ISSUE TITLE
Product by category grid limited to 36 items

### ISSUE THREAD

**Issue by GDB-dev** [woocommerce/woocommerce-gutenberg-products-block#2546]
Pagination doesn't appear to be an option and max grid size is 6 columns by 6 rows? Could there be a load more option to load remaining products in category or pagination

**Comment by kimmenbert** [comment]
Could be solved by this: https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/2373

Where the all product block gets support for setting initial categories/attributes etc.

**Comment by nerrad** [comment]
Thanks @kimmenbert for pointing to the other issue 👍. We're reviewing this and other issues related to affecting the grid size for various product blocks so I'm going to close this issue for now because we are aware.

Thanks!
