### ISSUE TITLE
Filter by Attribute: 'Go' button is not aligned with the input field

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#2560]
**To Reproduce**
1. Add a _Filter by Attribute_ block and select 'Display Style: Dropdown' and check 'Filter button'.
2. In the frontend with a wide viewport, notice the right side of the input field and the `Go` button are not aligned.

**Screenshots**
![imatge](https://user-images.githubusercontent.com/3616980/82886201-7d7b9680-9f46-11ea-8ca9-c3230aaaf7c1.png)

**Comment by nerrad** [comment]
Problem still confirmed to exist.
