### ISSUE TITLE
Expose deleted draft order ids to plugins that might need them.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#2570]
I experienced a bug when I visited the Woo Admin order list table route (`?page=wc-admin&path=%2Fanalytics%2Forders`) to see how our new draft status orders (introduced with the Checkout block) appear there. You can read up on my report of this bug and how to reproduce  in the [issue I created in the WC-Admin repo](https://github.com/woocommerce/woocommerce-admin/issues/4447).  Please _do read the report there_ because it provides not only the bug that was happening (a fatal that borks the view) but also some context around _why_ it was happening that is also background for this issue.

I've also created an issue in our repo because this is a blocker to releasing since even if WC-Admin adds defensive checking, it's just a bandaid over the issue and won't resolve cases where Woo Blocks 2.6.0 is used in earlier versions of WooCommerce core that have WC-Admin active or a site has the WC-Admin feature plugin active.

Also, it exposes a flaw that could surface with _any_ extension that syncs any sort of custom table with the order table (or order meta etc).

The flaw is that those extensions (or WC-Admin) have no awareness when draft status orders are _deleted_ from the database and thus are not able to update their own tables accordingly.

I haven't taken a dive into WooCommerce code yet (because I discovered this way past my work hours and I'm tired...just wanted to get this documented :) ) but I'm assuming there's an action hook that could be fired when an order is deleted that we could surface in our draft status cleanup logic (and we just make sure we grab the deleted ids before deleting to surface via the hook).

So there's a couple things we need to do before we can release 2.6.0:

## Prevent fatals happening in earlier versions of WooCommerce core (or installs with WC-Admin plugin active for Woo Core 4.0 environments).

There's a variety of options here:

- in our code we manually delete from the `wc_order_stats` table as a part of our cleanup (if it exists).
- It looks like woo-admin [hooks into `delete_post` to capture when orders are deleted](https://github.com/woocommerce/woocommerce-admin/blob/714660f67ee03ba94bc0febf30d2acbfe22bca7d/src/API/Reports/Orders/Stats/DataStore.php#L110-L112). So we could just fire off that hook for each order that was deleted (advantage here is that in theory that should work for any other extension hooking into that hook for the same reasons).

## Add in a bulk action for extensions (including wc-admin too hook into) for doing bulk deletes after this cleanup.

I'm not sure how feasible this is or whether we should just fire the `delete_post` hook here?

**Comment by nerrad** [comment]
@mikejolley I assigned this to you because this is in a domain that you are probably most familiar with on the squad and with it being a blocker to releasing 2.6.0 I'd like to see this resolved as soon as reasonably possible. Thanks!

**Comment by mikejolley** [comment]
@nerrad I'm going to wait for some feedback here from others in @woocommerce/merch-squad before raising a PR for this.

I have concerns over the `delete_post` solution mainly around the load this will create on high-traffic stores if it must loop over and clean a high volume of orders. This won't be as efficient as the DB query. [If we do have to go this route we may have to batch it like core does for privacy cleanup](https://github.com/woocommerce/woocommerce/blob/7f45c56417828683294b900ce59c7cb8edbfaa51/includes/class-wc-privacy.php#L164).

Introducing a hook when orders are cleaned up our side to allow wc-admin to re-sync when orders are deleted would be the most efficient way, but until thats used we would need to clean up the order stats with a custom query on our side. Thats not so bad so long as we can detect its existence first.

One other thing we could attempt would be to see if we can make it return no dates for creation for draft orders so this check fails: https://github.com/woocommerce/woocommerce-admin/blob/e2ef363d3368a420c5085e96416136581860d9da/src/Schedulers/OrdersScheduler.php#L156-L158 We'd ensure once the order was no longer a draft, the creation date was updated. That would prevent stats on draft orders which may or may not be desirable..

**Comment by nerrad** [comment]
> I have concerns over the delete_post solution mainly around the load this will create on high-traffic stores if it must loop over and clean a high volume of orders. This won't be as efficient as the DB query. If we do have to go this route we may have to batch it like core does for privacy cleanup.

Ya I hear you on the concerns with `delete_post`. But to be clear I'm not suggesting we delete each order using `wp_delete_post`. I'm suggesting we do a query to get the ids we're going to bulk delete first and then loop over those ids and fire the `wp_delete_post` hook (which still has potential performance concerns for anything hooking into the action).

> Introducing a hook when orders are cleaned up our side to allow wc-admin to re-sync when orders are deleted would be the most efficient way, but until thats used we would need to clean up the order stats with a custom query on our side. Thats not so bad so long as we can detect its existence first.

Agreed.

> One other thing we could attempt would be to see if we can make it return no dates for creation for draft orders so this check fails: https://github.com/woocommerce/woocommerce-admin/blob/e2ef363d3368a420c5085e96416136581860d9da/src/Schedulers/OrdersScheduler.php#L156-L158 We'd ensure once the order was no longer a draft, the creation date was updated. That would prevent stats on draft orders which may or may not be desirable..

Besides potentially being undesirable. I'm not sure this is worth doing because we still have the problem 2.6.0 support on earlier versions of Woo Core/WC-Admin. Certainly wc-admin might want to handle draft orders differently where-ever they potentially show up in queries, but I think that's a conversation for the @woocommerce/wc-admin team to have.

If we go with _not_ using `delete_post` the side-effect there is that `wc-admin` (or any extension hooking into delete actions), will need to be aware of whatever custom action we provide for handling when orders are deleted on their end (which could mean there's orphaned data in databases if that's missed, but especially for users on versions of wc-admin or extensions that _don't_ have the new status).

if we go with just looping through the `ids` we deleted in the batch query and firing the `delete_post` hook, then we avoid the load for _our_ batch delete of these orders, but potentially increase the load for anything plugging into the hook. Still this grants the advantage of handling (at least wc-admin) data table syncs with these orders on earlier versions of Woo Core and a wc-admin. 

The batch processing of orders for deletes could be a solution here except we'd have to keep in mind that the usage of it for the `wc-privacy` logic is typically not happening often but only when manually triggered for privacy deletions. Our case here is a bit different in that _every day_ there will potentially be orders deleted and on busy sites, potentially hundreds of those orders.

Based on this, I'm currently leaning in the following direction:

1. When we go to do the batch delete query, do a query getting the ids that will be deleted before doing the delete query.
2. If the count of ids is under _x_ (where we decide what is an acceptable number for x), we loop through the ids and fire off `delete_post`. 
3. If the count of ids is over _x_, we fire a new action (something like `wc_bulk_delete_orders`) with the array of ids and code can hook into the action to handle their own deletes in those cases.
4. If we fire the bulk action, then we'll need to temporarily also handle deleting these orders from the `wc_order_stats` table if it exists (until `wc-admin` has handling hooking into this new bulk action).
5. I'll need to update the release notes to highlight this new hook.

Thoughts?

**Comment by mikejolley** [comment]
I think a two pronged approach as suggested would lead to more edge case bugs and should be avoided - plugins consuming this would end up needing to handle two cases and testing for this would be more difficult.

R/e delete post, noting core has cleanup logic on these hooks too, although in our case we won't be affected due to not having refunds, but it's still extra logic running on each call: https://github.com/woocommerce/woocommerce/search?q=delete_post&unscoped_q=delete_post

This for example will do a query to get refunds on every order ID https://github.com/woocommerce/woocommerce/blob/86f59dff09529c52beead45e01e4b59f014c6040/includes/class-wc-post-data.php#L309

I think the best 2 options available for us are:

1. fire an action, use the action ourselves for cleanup, and when wc-admin introduces handling of the new action, we can disable ours with [has_action](https://developer.wordpress.org/reference/functions/has_action/) to ensure maximum cross version compatibility.
2. run cleanup more often but limit the number of orders cleaned up per run.

2 could impact stock checks and still cause a performance issue so I am preferring option 1.

**Comment by nerrad** [comment]
My main worry about not _ever_ firing `delete_post` is that it's the known mechanism for catching when anything saved in the post table is deleted. That presents potential complications if there are extensions that rely on that for any sort of cleanup logic. With us providing a custom action, we're doing something outside of the models which makes discoverability and awareness an issue. So it becomes a huge gotcha (and I realize that my two-pronged approached is poor as a result of this comment as well).

I totally grok the performance implications but I really think we're going to have to implement a solution that always fires the `delete_post` action because without doing so we're potentially introducing a whole class of bugs for extensions or custom code in the wild on stores that is dependent on _knowing when orders have been deleted_.

What about doing something like this?

- We do a query to see how many orders there are to delete. If it's under a given number (which we could filter for sites that want to control this), we just loop through the known ids and delete each order so the `delete_post` fires. 
- If it's _over_ that number then we delete up to that number and then immediately schedule a single event to do fire this cleanup method x minutes in the future.

That way, if there's not a lot of orders to delete, we're taking care of them all at once but otherwise we split them up over time. For sites that have a LOT of traffic and abandoned checkouts (resulting in a greater number of orders) they can filter the number of orders in each batch (if they have more resources to handle the cleanup).

Some potential things to watch for:

- While a bit edgecase, is there possibility for overlapping calls to the cleanup action if the number of orders is significant enough to cause a single scheduled event to fire around the same time as the regular scheduled daily event? If so, should we have some mechanism for tracking when a batch delete is in progress (so that any additional incoming batch delete processing can be aborted)?
