### ISSUE TITLE
Products with no price break the product selector

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#2578]
Similarly to #2551, I'm only able to reproduce this issue in a specific server, but not in local.

**To Reproduce**
1. Create a product (or modify an existing one), so it doesn't have a price.
![imatge](https://user-images.githubusercontent.com/3616980/83043658-6b335280-a043-11ea-98cb-1cafef284f19.png)
2. Create a page and add a `Hand-Picked Products` block or a `Featured Product` block. I guess all blocks which have a product selector will have this issue.
3. Notice the block placeholder shows a '`The response is not a valid JSON response.`' error message:
![imatge](https://user-images.githubusercontent.com/3616980/83043605-5c4ca000-a043-11ea-9d97-715983afdba6.png)

The API response is:
```JSON
Warning: A non-numeric value encountered in /usr/home/.../web/wp-content/plugins/woocommerce-gutenberg-products-block-2.6.0/src/StoreApi/Schemas/AbstractSchema.php on line 243

... /* the error message is repeated three times per each product with no price */

[ /* correct JSON data here */ ]
```

My guess is that we need to return early in:
https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/src/StoreApi/Schemas/AbstractSchema.php#L240
if `$amount` is not a number.

**Comment by nerrad** [comment]
Probably related [to this](https://stackoverflow.com/questions/42044127/warning-a-non-numeric-value-encountered).

**Comment by Aljullu** [comment]
I couldn't find yet why this error is only occurring in my server but not in local.

Basically, the `$amount` value is an empty string (it comes from [here](https://docs.woocommerce.com/wc-apidocs/source-function-wc_get_price_excluding_tax.html#1012)). [`wc_format_decimal()`](https://docs.woocommerce.com/wc-apidocs/source-function-wc_format_decimal.html#276-313) doesn't modify it, so we end up with `"" * ( 10 ** 2 )`, the server shows a warning with this calculation while local, doesn't.

Server is PHP 7.4 while local is 7.3.

Doing this change fixes the issue:
```diff
-wc_format_decimal( $amount ) * ( 10 ** $decimals ),
+floatval( wc_format_decimal( $amount ) ) * ( 10 ** $decimals ),
```

**Comment by nerrad** [comment]
`wc_formt_decimal` removes all decimals etc from the string right? So could it just be `absint`?

**Comment by Aljullu** [comment]
@nerrad I don't think we can use `absint` here, `wc_format_decimal` might return strings representing decimal numbers (ie: `"9.99"`).

**Comment by nerrad** [comment]
Hmm, I saw this code doc for `wc_format_decimal` without looking at the code, seems like it's not accurate then:

> Sanitize, remove decimals, and optionally round + trim off zeros.

**Comment by Aljullu** [comment]
Yeah, I'm a bit confused by that `remove decimals` from the method description, but rounding is controlled by the [`$dp` argument](https://github.com/woocommerce/woocommerce/blob/master/includes/wc-formatting-functions.php#L284). Leaving it undefined (so it defaults to false) means no rounding happens.

I tested it locally, but the tests are also quite handy to see how it works: https://github.com/woocommerce/woocommerce/blob/master/tests/legacy/unit-tests/formatting/functions.php#L297.
