### ISSUE TITLE
Add Remove Quantity/Product from checkout order summary

### ISSUE THREAD

**Issue by letmework** [woocommerce/woocommerce-gutenberg-products-block#2583]
Would be nice if we could remove items from the checkout order summary without having to go back to cart.

**Comment by nerrad** [comment]
Hi there 👋

Thanks for taking the time to test the Cart and Checkout blocks and share your idea, we really appreciate your help!

We'll consider this for future iterations of the blocks.

**Comment by nerrad** [comment]
Thanks for the suggestion. This is not something currently on our roadmap as what we will support.
