### ISSUE TITLE
Add pagination to the products block

### ISSUE THREAD

**Issue by awilmsmeier** [woocommerce/woocommerce-gutenberg-products-block#259]
**Is your feature request related to a problem? Please describe.**
Not directly related to a problem, more a missing feature.

**Describe the solution you'd like**
I'd like to show all products with a certain attribute value on specific pages. I'd like to show only one row of, say 5,  products and allow the user to scroll through all (>5) available products for the selection.

**Describe alternatives you've considered**
I could, of course, add more rows - but then there are limits to that as well if you want to keep the page design light and clear.

**Additional context**
N/A

**Comment by LevinMedia** [comment]
Hi @awilmsmeier Thanks for the feature suggestion! This is actually a topic we've discussed quite a bit. As it relates to these bocks, we've have elected to not support it for a couple specific reasons. Most notably: 

1. Adding pagination to the blocks would allow people to duplicate core wordpress/woocommerce functionality. (ie: using it to build a product category archive page) 
2. If that were to happen, sites would end up with duplicate content. People would link to their block version of the archive page from their navigation, but core would still link to the native archive page through things like widgets, and product meta. Ultimately, that would have a very negative affect on SEO. 

I'm going to mark this issue as closed, but your feedback is welcome and noted!  It's something we hope to address in a more sustainable way as Gutenberg evolves to allow for a more all encompassing site editing experience.
