### ISSUE TITLE
Unset shop pages are using `false` as value

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#2600]
Today while testing, I saw that some shop pages are using `false` as a value if that page doesn’t exist, instead, they should either use an empty string or home page link.

@mikejolley suggested we should default to the home page, this is done here
https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/f77c7f387ea413cdfe1c2022b105e9bcf553b386/src/Assets.php#L206

However, we have some conditional rendering using those links, so we should keep them into account

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/f77c7f387ea413cdfe1c2022b105e9bcf553b386/assets/js/base/components/cart-checkout/policies/index.js#L21

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/f77c7f387ea413cdfe1c2022b105e9bcf553b386/assets/js/base/components/cart-checkout/policies/index.js#L37

Also, if we use an empty string, we should remember it will render, as `""` doesn’t evaluate to false in React, we should use `SHOP_URL.length` as this will evaluate to 0 if it's an empty string.

**To Reproduce**

1. Have a store with no shop page.
2. in empty cart, notice that "go to store" will take you to `/false`

**Expected behavior**
Those links should either not render, or render to the home page or the current page.

**Comment by mikejolley** [comment]
The original issue no longer seems to occur. Empty strings are false in react, so the PRIVACY and TERMS pages are correctly handled. The only bug is the SHOP page handling. We don't check the URL before using it, we just assume it exists.
