### ISSUE TITLE
Coinbase payment gateway option not shown on checkout

### ISSUE THREAD

**Issue by ScreenTag-Team** [woocommerce/woocommerce-gutenberg-products-block#2602]
**Describe the bug**
After installing the official Coinbase Commerce plug-in, the option to pay using this gateway is not shown.

**To Reproduce**

1. Install Coibase Commerce (https://wordpress.org/plugins/coinbase-commerce) and activate it (WooCommerce should be already installed with at least one product)
2. Setup Coinbase Commerce Gateway (to open an account, visit https://commerce.coinbase.com)
3. Add API key and Passphrase to complete Coinbase Commerce setup and activate Coinbase Commerce as a payment method
4. Add the test product in a test order, and proceed to checkout
5. Scroll down to select payment method. Coinbase or cryprocurrency logos are not shown, and there is no way to select this gateway.
6. In fact, no other gateway besides PayPal and Stripe is made available, including CoD or Direct bank Transfer 

**Expected behavior**
Normally, a payment option displaying cryptocurrency logos and 'Pay with Bitcoin' should be visible

**WordPress**
* Core version: 5.4.1
* WooCommerce version: 4.1.1
* WooCommerce Blocks version: 2.6.1
* Site language: English U.S.

**Desktop**
* OS: Windows
* Browser Chrome
* Version 81.0.4044.138

**Comment by nerrad** [comment]
Hi there!

Thanks for testing out the _preview_ of the Cart_ and Checkout blocks! 

As noted in [the release post](https://woocommerce.wordpress.com/2020/05/27/available-for-testing-a-block-based-woocommerce-cart-and-checkout/), there is a limited support for payment methods in the blocks currently and they only support Stripe Payment Request (ApplePay, ChromePay), Stripe CC, Paypal Standard, or Cheque.

As we continue with evaluating the blocks and how they perform using the existing feature set, we'll be determining what other features and payment methods to support (along with any required improvements to the extensibility of these blocks for third party developers hooking in their extensions).

Your request is known!

**Comment by nerrad** [comment]
I'm closing this issue because there's nothing actionable in this repository. The request is known and there is opportunity for payment methods/gateways to integrate with the Checkout blocks using the current available API interfaces. Best next step is to ask the individual payment method extension developers to build the integration.
