### ISSUE TITLE
Cart: merge the left and right titles

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#2614]
Currently, the _Cart_ block has two titles, one left aligned and the other one right aligned. We want to merge them into a single one:
![imatge](https://user-images.githubusercontent.com/3616980/83628822-6158a480-a599-11ea-8bea-e2aed5e207e2.png)
↓
![imatge](https://user-images.githubusercontent.com/3616980/83628848-6cabd000-a599-11ea-8029-136315079b64.png)

**Comment by mikejolley** [comment]
I think I've mentioned this before in Slack, but is this heading actually useful in the real world? Unless you have masses of products in the cart it isn't hard to see the number of rows, and this type of data is less useful on stores which sell 1 or few items total. It was semi-justified when it read "shopping cart" but now I'm not so sure. cc @LevinMedia

**Comment by LevinMedia** [comment]
I just did a review of a few large eCommerce sites... all of them only show an item count, so I think the original design was on point in that regard. Many of them labeled it as "Your cart" or "Your bag" along with the item count, so I've updated our designs to match:

Examples:
<img width="1732" alt="Screen Shot 2020-06-04 at 9 48 58 AM" src="https://user-images.githubusercontent.com/4500952/83787564-d59e5100-a648-11ea-8330-b50a79a070b3.png">
<img width="1732" alt="Screen Shot 2020-06-04 at 9 44 14 AM" src="https://user-images.githubusercontent.com/4500952/83787581-da630500-a648-11ea-9f6d-cc387ece628e.png">
<img width="1390" alt="Screen Shot 2020-06-04 at 9 24 07 AM" src="https://user-images.githubusercontent.com/4500952/83787612-e8b12100-a648-11ea-8fd7-ea554f4de6d4.png">

Updates to our design:
<img width="820" alt="Screen Shot 2020-06-04 at 9 52 12 AM" src="https://user-images.githubusercontent.com/4500952/83787745-18f8bf80-a649-11ea-903c-0a8e1eab8e11.png">

cc @Aljullu
