### ISSUE TITLE
No cash on delivery in checkout

### ISSUE THREAD

**Issue by air66design** [woocommerce/woocommerce-gutenberg-products-block#2623]
When selecting Cash On Delivery as the payment method. It doesn’t show as a payment method in the checkout page.

If it is the only payment method selected you get a warning saying no payment methods are available.

To test it wasn’t a plugin conflict all plugins were de activated expect woocommerce and woocommerce blocks

**Comment by nerrad** [comment]
Hi there 👋 

Thanks for taking the time to submit an issue in the repository.

As noted [in the release post for the Cart and Checkout blocks](https://woocommerce.wordpress.com/2020/05/27/woocommerce-blocks-2-6-0-release-notes/), there is a limited set of payment methods available for the initial iteration of the preview. You can read more information about this in the post I linked to.

Your request is noted and we will be reviewing the next batch of payment methods we will integrate with the Cart and Checkout block in future iterations.

**Comment by air66design** [comment]
Thank you and apologies... I did try looking for the included ones. Could find the link.

**Comment by nerrad** [comment]
No problem, it's still great you posted this because it gives us an idea of what people are looking for and helps us prioritize :)

**Comment by air66design** [comment]
Thanks, the reason we would like cash on delivery is because we tend to use it for customers that use woocommerce for trade sites - so we change it to payment on invoice. 

keep up the great work
