### ISSUE TITLE
Override default display of savings in the cart detail table if savings are _negative_

### ISSUE THREAD

**Issue by markwils** [woocommerce/woocommerce-gutenberg-products-block#2627]
I have desktop software (photobook design) that directs customers to their cart for online checkout and order management. The products are defined in WooCommerce with a dummy "base" price, which is subsequently programmatically overridden by the actual price of the item they have designed/ordered, with all their required extras. This results in a higher price than the base price attached to the product in WC. 

With the cart block, the item is shown in the cart with base price shown in strikethrough, and new higher price in plain text, with resulting _negative_ savings shown underneath. This might be considered an edge case, but the option to ignore the original price and only show what the customer is expecting to pay, would be useful to me. (As it currently displays, the customer may well have the impression there is an unjust/opportunistic markup, which is not the case.)

**Comment by nerrad** [comment]
Hi there 👋

Thanks for taking the time to share this idea and feedback, we really appreciate your help!

We'll take your request under consideration as we iterate on the Cart and Checkout Block previews.

**Comment by markwils** [comment]
Actually, since this is probably not an issue for typical sites - a simpler, easier, and more logical option is simply build in the logic to _not_ display savings if they are _negative_. Thus no need for special options, and I would get the cart working as it does now in my current standard cart page.

Please consider!

**Comment by haszari** [comment]
@markwils Can you please provide a bit more detail about how to reproduce the negative discount issue - does this require a specific plugin or custom code?

To simulate the issue, I tried manually setting a higher discount price on a product, but WooCommerce doesn't allow that.

**Comment by senadir** [comment]
I managed to reproduce this using [Product Add-ons](https://woocommerce.com/products/product-add-ons/)

![image](https://user-images.githubusercontent.com/6165348/89298597-6d2a1b00-d65d-11ea-84f5-015a6139ecba.png)

**Comment by markwils** [comment]
@haszari - sorry for late reply, indeed this was triggered by a programmatic price override of a product's base price. Glad there are other scenarios that expose the issue.

**Comment by senadir** [comment]
@markwils this should be fixed once https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2955 is merged, so by the next release (3.2), but if you want to make sure that it actually fixes your issue, you can test that PR if you have some experience using git, you will need `git` `npm` and `composer` to be installed in order to build a version.

- `git clone --single-branch --branch fix/hide-saving-if-is-negative https://github.com/woocommerce/woocommerce-gutenberg-products-block`
- `npm run package-plugin`
you will get a zip file that you can test with.
