### ISSUE TITLE
[GlobalStep] Randomly buttons available under Featured Product and Featured Category block fails to align to center

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-gutenberg-products-block#2631]
**Environment:**
Windows 10: Chrome(v83.0.4103.61)
MAC Book Air: Safari(v13.0.5 (15608.5.11))

**Steps to Reproduce:** 
1. Login to the wp-admin dashboard using valid credentials.
2. Click on Post.
3. Click on Add New Post.
4. Select block type as Featured Product or Featured Category.
5. Change alignment of the button to center.
6. Preview the post.
7. Now repeat step 5 and 6 multiple times.
8. Observe that randomly buttons available under Featured Product and Featured Category block fails to align to center.

**Actual Result:**
Randomly buttons available under Featured Product and Featured Category block fails to align to center

**Expected Result:**
Upon setting center alignment button should be displayed on the Center of the Post.

[#2631.zip](https://github.com/woocommerce/woocommerce-gutenberg-products-block/files/4730916/2631.zip)

**Comment by nerrad** [comment]
To me this looks like an issue specific to the theme in use. Since it's not clear to me from the report what theme is being tested with I'm going to have to just close this.
