### ISSUE TITLE
[GlobalStep] Best Selling Products: In layout upon setting Column value to 6 buttons on Preview and Publish gets misaligned.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-gutenberg-products-block#2633]
**Environment:**
Windows 10: Chrome(v83.0.4103.61)
MAC Book Air: Safari(v13.0.5 (15608.5.11))

**Steps to Reproduce:** 
1. Login to the wp-admin dashboard using valid credentials.
2. Click on Post.
3. Click on Add New Post.
4. Select block type.
5. In Settings panel, change Column value to 6.
6. Tap on Previews or Publish button.
7. Go the site.
8. Observe that button gets aligned vertically.

**Note:** 
1. In Post editor button appears properly aligned.
2. Observed on https://lw.testwc.com/wp-login.php

**Actual Result:**
In layout upon setting Column value to 6 buttons on Preview and Publish gets misaligned.

**Expected Result:**
The button should aligned properly as there are displayed in Post editor.

![#2633](https://user-images.githubusercontent.com/41110392/83774487-5ee27180-a6a3-11ea-945d-a55ea2cd0271.png)

**Comment by nerrad** [comment]
@juliaamasov this looks like it’s a theme issue. We will track this because we’re working on style fixes but there will likely still be themes that have to fix their styles too.

Would you be able to add to this ticket what theme is being used on that test site please? Thanks!

**Comment by juliaamosova** [comment]
@nerrad thanks! This site has a theme [Astra](https://wordpress.org/themes/astra/) installed - version 2.4.5 which is the latest version.

**Comment by nerrad** [comment]
I'm just confirming this still exists with the latest version of the Astra theme (and any product grid type block):

![Image 2020-12-15 at 1 06 31 PM](https://user-images.githubusercontent.com/1429108/102254234-61394a00-3ed6-11eb-9c21-0c3c8c9a9eee.jpg)

Note that there are also other styling issues related to the theme too. I think this is something that likely should be resolved at the theme level but will leave open for now in case we want to do a temporary fix given the large usage of this theme.

**Comment by juliaamosova** [comment]
Thanks for doing a check on this issue @nerrad!
