### ISSUE TITLE
[GlobalStep] On MAC, "+" icon on "Group" block type is misaligned.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-gutenberg-products-block#2635]
**Environment:**
MAC Book Air: Safari(v13.0.5 (15608.5.11))

**Steps to Reproduce:** 
1. Login to the wp-admin dashboard using valid credentials.
2. Click on Post.
3. Click on Add New Post.
4. Select Group block type.
5. Add one block.
6. Scroll the page to the end of the block.
7. Observe that "+" icon on "Group" block type is misaligned

**Actual Result:**
On MAC, "+" icon on "Group" block type is misaligned.

**Expected Result:**
On MAC, "+" icon on "Group" block type should fit to the screen.

![#2635](https://user-images.githubusercontent.com/41110392/83774701-aa951b00-a6a3-11ea-87fc-c1267c0b51cf.png)

**Comment by nerrad** [comment]
This is a Gutenberg issue, not Blocks Plugin issue.
