### ISSUE TITLE
[GlobalStep] On MAC, "403 forbidden…” error message is displayed while uploading comment on Newest Product and On Sale Product block

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-gutenberg-products-block#2636]
**Environment:**
MAC Book Air: Safari(v13.0.5 (15608.5.11))

**Steps to Reproduce:** 
1. Login to the wp-admin dashboard using valid credentials.
2. Go to Post.
3. Add new post.
4. Select block type as Newest Product or On Sale Product.
5. Click on Publish button.
6. Click on View post.
7. Scroll to the Comment section.
8. Add some comment and tap on Comment button.
9. Observe that "403 forbidden…” error message is displayed while uploading comment on Newest Product and On Sale Product block

**Actual Result:**
"403 forbidden…” error message is displayed while uploading comment on Newest Product and On Sale Product block.

**Expected Result:**
"403 forbidden…” error message should not be displayed while uploading comment on Newest Product and On Sale Product block.

[#2636.zip](https://github.com/woocommerce/woocommerce-gutenberg-products-block/files/4730958/2636.zip)

**Comment by nerrad** [comment]
@juliaamosova this sounds like an issue with the test environment and not something related to the Blocks plugin. I’m going to close this but you can move and re-open if you feel it needs investigated?

**Comment by juliaamosova** [comment]
Thanks @nerrad! I am moving it to the WooCommerce Core repository and reopening there to take a look in a bit.
