### ISSUE TITLE
[GlobalStep] On MAC, “Group” is highlighted by default even when user has not select “Group” from block type.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-gutenberg-products-block#2637]
**Environment:**
MAC Book Air: Safari(v13.0.5 (15608.5.11))

**Steps to Reproduce:** 
1. Login to the wp-admin dashboard using valid credentials.
2. Go to Post.
3. Add new post.
4. Select any block type except Group.
5. Click on Change Block Type.
6. Observe that Group block type is highlighted by default.

**Actual Result:**
On MAC, “Group” is highlighted by default even when user has not select “Group” from block type.

**Expected Result:**
Selected block type should be highlighted by default.

![#2637](https://user-images.githubusercontent.com/41110392/83775160-46268b80-a6a4-11ea-9cf9-ab523c056b3f.png)

**Comment by nerrad** [comment]
This is also a Gutenberg issue, not a Blocks plugin issue.
