### ISSUE TITLE
[GlobalStep]Credit/Debit card details i.e., Card Number, Expire date and CVV/CVC fails to refresh.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-gutenberg-products-block#2638]
**Environment:**
Windows 10: Chrome(v83.0.4103.61)
MAC Book Air: Safari(v13.0.5 (15608.5.11))

**Steps to Reproduce:** 
1. Login to the wp-admin dashboard using valid credentials.
2. Create and publish Cart and Checkout page.
3. Go to site.
4. Add a product to cart.
5. Proceed to checkout.
6. Enter Card detail as "4000 0000 0000 0002"
7. Click on place order.
8. Note that "The card was declined" error message is displayed.
9. Also note that credit card details fails to clear.
10. Now enter valid credit card details i.e., "4242 4242 4242 4242".
11. Note that "Sorry, we are unable to process your payment at this time. Please retry later" error message is displayed.
12. Observe that user fails to place order unless and unit user refresh the page.

**Actual Result:**
Credit/Debit card details i.e., Card Number, Expire date and CVV/CVC fails to refresh.

**Expected Result:**
Credit card details should get clear and user should be able to place order with another credit card details.

[#2638.zip](https://github.com/woocommerce/woocommerce-gutenberg-products-block/files/4730978/2638.zip)

**Comment by nerrad** [comment]
I'm able to reproduce this.
