### ISSUE TITLE
[GlobalStep]On Windows 10 for BLUEHOST Site user fails to unchecke “Enable tax” checkbox from WooCommerce -> Settings ->General.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-gutenberg-products-block#2639]
**Environment:**
Windows 10: Chrome(v83.0.4103.61)

**Steps to Reproduce:** 
1. Login with BLUEHOST site.
2. Click on WooCommerce.
3. Click on Settings.
4. Scroll to the "Enable Tax" checkbox.
5. Note that checkbox is checked by default.
6. Now uncheck "Enable Tax" checkbox.
7. Note that it gets unchecked.
8. Now save the settings.
9. Again scroll back to "Enable Tax".
10.  Observe that the checkbox is checked by default.

**Actual Result:**
On Windows 10 for BLUEHOST Site user fails to uncheck “Enable tax” checkbox from WooCommerce -> Settings ->General.

**Expected Result:**
User should be able to uncheck the "Enable tax" checkbox and Tax option should be hide from the frontend.

[#2639.zip](https://github.com/woocommerce/woocommerce-gutenberg-products-block/files/4730998/2639.zip)

**Comment by nerrad** [comment]
@juliaamosova this sounds like a Woo Core issue? I’ll close it here but you can move and reopen if you think it needs investigated further.

**Comment by juliaamosova** [comment]
Thanks @nerrad! Moving this issue to the WooCommerce Core repository and reopening to take a look later.
