### ISSUE TITLE
[GlobalStep]Validation on payment method are misaligned

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-gutenberg-products-block#2641]
**Environment:**
Windows 10: Chrome(v83.0.4103.61)
MAC Book Air: Safari(v13.0.5 (15608.5.11))

**Steps to Reproduce:** 
1. Login to the wp-admin dashboard using valid credentials.
2. Go to site.
3. Go to Checkout page.
4. Keep Credit/Debit card detail i.e., Card Number, Expire date and CVV/CVC empty.
5. Tap on Place order.
6. Observe that validation on payment method are misaligned

**Actual Result:**
Validation on payment method are misaligned.

**Expected Result:**
Validation should not overlap with the images/icons below payment details method.

![#2641](https://user-images.githubusercontent.com/41110392/83776138-70c51400-a6a5-11ea-91b9-40cf8c1e71d9.png)

**Comment by nerrad** [comment]
@juliaamosova this looks like another styling related issue. Would you be able to track down what theme is being used please?

**Comment by juliaamosova** [comment]
@nerrad this site has Storefront installed - version 2.5.7.
