### ISSUE TITLE
[GlobalStep] On MAC, created attributes fails to update on Products ->Add New Attribute page.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-gutenberg-products-block#2642]
**Environment:**
MAC Book Air: Safari(v13.0.5 (15608.5.11))

**Steps to Reproduce:** 
1. Login to the wp-admin dashboard using valid credentials.
2. Click on Products.
3. Click on Attributes.
4. Add valid attribute details i.e., Name, Slug, Default Sort Order.
5. Click on Add Attribute button.
6. Observe that newly created attributes fails to update in the table present on Attributes page.

**Actual Result:**
On MAC, created attributes fails to update on Products ->Add New Attribute page.

**Expected Result:**
User should be able to add attributes for product.

[#2642.zip](https://github.com/woocommerce/woocommerce-gutenberg-products-block/files/4731076/2642.zip)

**Comment by nerrad** [comment]
@juliaamosova this appears to be another WooCommerce core issue. I’m going to close here and you can move and reopen if you think it needs investigated further.

**Comment by juliaamosova** [comment]
Thanks @nerrad! Moving it to the WooCommerce Core repository to reopen and take a look there further.
