### ISSUE TITLE
Investigate misaligned item count badge in Twenty Twenty

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#2651]
@nerrad reported it in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2619#issuecomment-639559750:
> I still see some off center padding for the numbers in the quantity bubbles for Twenty Twenty (both frontend and editor/mobile):

<img width="444" alt="Image 2020-06-05 at 11 10 32 AM" src="https://user-images.githubusercontent.com/1429108/83893231-b1f90a80-a71d-11ea-9d77-c22801f6396b.png">

**Comment by nerrad** [comment]
This must have got fixed somewhere along the way because I'm not seeing the padding anymore.
