### ISSUE TITLE
Establish a consistent naming schema for asset handles.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#2660]
This issue is prompted from a [comment made by @haszari](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2648#issuecomment-640275006) which appropriately draws attention to the potential for regression if we don't namespace the handles we used for built assets registered with WP.

For back-compatibility reasons, I don't think we should change any of the established script handles (except maybe `wc-vendors` and `wc-shared-context` (as that seems like something other WC plugins - or core itself - might use). Since there seem to be two patterns of how namespacing is used, I propose the following convention (to keep things consistent with existing patterns):

- If the asset is for a block, then use `block` as the suffix. Example: `wc-checkout-block`
- If the asset is some other bundled script, then use `wc-blocks-` as the prefix. (Note: we have some uses of `wc-block-` prefix right now...I'm on the fence whether we change them, for back compat reasons).

Should there be agreement, we could document this in our `/docs` folder.

**Comment by nerrad** [comment]
@woocommerce/rubik I think we'll want to consider this for inclusion in our `/docs` folder. Thoughts?

**Comment by senadir** [comment]
I think @mikejolley recent PR touches on this?
