### ISSUE TITLE
Checkout: remove borders around Order summary panel

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#2663]
According to the designs, the _Order summary_ panel shouldn't have top and bottom border:

| `master` | Design |
| --- | --- |
| ![imatge](https://user-images.githubusercontent.com/3616980/84013474-3f846680-a979-11ea-9da8-031e950511cf.png) | ![imatge](https://user-images.githubusercontent.com/3616980/84013518-4f03af80-a979-11ea-8727-f88e3245800d.png) |

**Comment by haszari** [comment]
Related to this – @LevinMedia I'm wondering if we need two levels of separator in this sidebar (and cart sidebar too) - seems like the hierarchy would be clearer if there was only one (top) level of separator. 

Specifically I'm suggesting:

- Checkout sidebar, order summary - remove separators between products, just use whitespace.
- Cart sidebar - remove separators between radio buttons for shipping options.

These are both "narrow", secondary separators on desktop, and I think they make the hierarchy less clear (and add clutter).

Keen for your thoughts on this :)

<img width="436" alt="83982920-7741dd00-a97e-11ea-98dc-7624954d3acc" src="https://user-images.githubusercontent.com/4167300/84080456-5043e380-aa30-11ea-9cd3-676f489a81f5.png">
<img width="465" alt="83982930-8f196100-a97e-11ea-8bf8-39b0f57df746" src="https://user-images.githubusercontent.com/4167300/84080458-51751080-aa30-11ea-9f9b-fd6aee00053b.png">

**Comment by Aljullu** [comment]
#2694 fixes this and some other issues, just in case you want to see how it looks, @LevinMedia.
