### ISSUE TITLE
Fix payment icon layout issue with Twenty Twenty theme (non-mobile layout)

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#2669]
While testing 2.7.0, I noticed that with Twenty Twenty, the payment method icons for payment methods are incorrectly positioned:

![Image 2020-06-08 at 3.33.05 PM.png](https://images.zenhubusercontent.com/55c8bfc24f7a08fbb7f431bd/7948637b-9c77-4a95-b58c-1e6b0313108c)

They should be on the same line as the text content.  Since they are at least left aligned, this isn't a huge issue but I think it would still be good to be consistent across themes for this.

**Comment by haszari** [comment]
Related: based on [this comment](https://github.com/Automattic/woocommerce-payments/pull/723#discussion_r455190773) from @LevinMedia, we are moving away from having a generic icons on payment methods; icons should be used for recognisable payment method brands only (example: PayPal).

With that in mind, we can simply remove the cheque icon and the generic CC icon (from Stripe Credit Card). Should be a nice clean PR :)
