### ISSUE TITLE
Shipping Tax Cost 

### ISSUE THREAD

**Issue by Corderz** [woocommerce/woocommerce-gutenberg-products-block#2673]
When selecting a shipping method, the price shown beside the shipping title (e.g. standard) does not include shipping tax if items in the cart have taxable shipping. The shipping cost below the subtotal in the order summary section reflects the tax cost (e.g. if express is £6.50 without tax, it shows £7.80 (20% tax) in order summary), just not the shipping select section.

![image](https://user-images.githubusercontent.com/48267520/84145140-42528a80-aa51-11ea-8998-50cc2d4b8d6c.png)
![image](https://user-images.githubusercontent.com/48267520/84145153-48486b80-aa51-11ea-8292-2563873a4965.png)

**Comment by Aljullu** [comment]
Hi @Corderz, thanks for filling this issue! It looks like it was filled before, so I will close as a duplicate. Feel free to follow #2626 to get a notification when it gets fixed.
