### ISSUE TITLE
Add Cart and Checkout block descriptions to readme.txt

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#2674]
If you go to the [plugin page in the .org repository](https://wordpress.org/plugins/woo-gutenberg-products-block/), it doesn't say anything about the new Cart and Checkout blocks. It would be good to update the `readme.txt` file so users can see those blocks are included before downloading the plugin.

**Comment by nerrad** [comment]
Definitely! I'll assign this to the 2.8 milestone so we don't forget.

**Comment by nerrad** [comment]
Cart and Checkout blocks are mentioned in the readme.txt now, so it must have got added at some point.
