### ISSUE TITLE
[GlobalStep] Fix Product by Tag block showing content on the frontend when there are no tags on a site.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-gutenberg-products-block#2684]
**Environment:**
Windows 10: Chrome(v83.0.4103.61)(64-bit), Firefox(v77.0.1)(64-bit)

**Steps to Reproduce:**
1. Open test site.
2. Login using valid credentials and go to admin dashboard.
3. Note that no tags are added on the site.
4. Click on Pages.
5. Click on Add New.
6. Add Product By Tag block.
7. Note that placeholder text stating “This block displays products from selected tags. In order to preview this, you'll first need to…” is displayed.
8. Now preview the page/publish the page.
9. Observe that few products are displayed in Product by tag category.

**Actual Result:** 
On editor Product by tag shows placeholder text stating “This block displays products from selected tags. In order to preview this, you'll first need to…” and upon tapping preview, few products are displayed in Product by tag category.

**Expected Result:**
Products by tag field should be empty if tags are not added to the product.

[#2684.zip](https://github.com/woocommerce/woocommerce-gutenberg-products-block/files/4759681/2684.zip)

**Comment by nerrad** [comment]
Thanks for the report! It looks like this issue is one that has been present for a while. While it's legitimate, the impact is low so it won't be addressed immediatley.
