### ISSUE TITLE
[GlobalStep] For the “List” display Category images fails to display next to “Product Category List”. 

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-gutenberg-products-block#2685]
**Environment:**
Windows 10: Chrome(v83.0.4103.61)(64-bit), Firefox(v77.0.1)(64-bit)

**Steps to Reproduce:**
1. Open test site.
2. Login using valid credentials and go to admin dashboard.
3. Click on Pages/Post.
4. Add "Product Category List" block.
5. Toggle on "Show Category Image".
6. Click on Preview.
7. Observe that for the “List” display Category images fails to display next to “Product Category List”. 

**Note:** 
Observed on following links: 
1. DREAMHOST TEST SITE: http://gerpot.dreamhosters.com/
2. BLUEHOST TEST SITE: bluehost-and-a8c.com
3. ATOMIC TEST SITE: https://atomic1.testwc.com
4. WPENGINE TEST SITE: http://wpe.testwc.com

**Actual Result:** 
For the “List” display Category images fails to display next to “Product Category List”. 

**Expected Result:**
Image should load properly.

[#2685.zip](https://github.com/woocommerce/woocommerce-gutenberg-products-block/files/4759701/2685.zip)

Testing: WooCommerce 2.7.0 release

**Comment by nerrad** [comment]
Thanks for the report!

I'm unable to reproduce this.  I logged into the wpEngine test site and I'm seeing the expected results:

<img width="925" alt="Image 2020-06-11 at 10 27 40 AM" src="https://user-images.githubusercontent.com/1429108/84398953-9040cd00-abce-11ea-980a-914cea1284e0.png">

Categories don't have images by default so it's expected that there'd be a _placeholder image_ for those categories.
