### ISSUE TITLE
No Create Account option in Checkout Block if Account is required

### ISSUE THREAD

**Issue by mouligreenlaw** [woocommerce/woocommerce-gutenberg-products-block#2687]
**Describe the bug**
When an account is required for checkout and the option to allow account creation in the checkout is enabled under WooCommerce ➔ Settings ➔ Accounts and Privacy, a logged out user is presented with a login link and nothing else on the checkout page.
There is no option to Create and Account.

**To Reproduce**

1. Go to WooCommerce ➔ Settings ➔ Accounts and Privacy
2. Disable `Allow customers to place orders without an account `
3. Enable `Allow customers to log into an existing account during checkout `
4. Enable `Allow customers to create an account during checkout `
5. Create a Checkout Page using the WooCommerce Checkout Block
6. Visit the Checkout as a logged out user
7. Try to create an account

**Expected behavior**
The user should be given the option of creating an account

**Screenshots**

![https://d.pr/i/DmVfCY](https://d.pr/i/DmVfCY+) 
Full Size: https://d.pr/i/DmVfCY

**WordPress (please complete the following information):**

* Core version: 5.4.2
* Gutenberg version (if installed): 
* WooCommerce version: 4.2
* WooCommerce Blocks version: 2.7
* Site language: English
* Any other plugins installed: Disabled

**Desktop (please complete the following information):**

* OS: MacOS High Sierra
* Browser Firefox
* Version 77.01

3053275-zen

**Comment by Aljullu** [comment]
Hi @mouligreenlaw, thanks for filling this issue! This is currently under our radar, and we already have an issue for it (#2377), so I will close as a duplicate. Feel free to follow #2377 to get a notification when it gets fixed.
