### ISSUE TITLE
⚛️  Form Element Registration API (Allow extensions to add components within the Add to Cart Form)

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#2701]
To allow our own and 3rd party extensions to extend the add to cart form, we need a system to register components and modify add to cart requests.

Use cases:
- Variation swatches
- Product Addons
- Other product types such as Bookings and Subscriptions

We need to implement a registration system so extensions can register components for use in the Add to cart form. Bare in mind the system needs to handle and consider the following:

- Registration of components under certain product types only (e.g. simple, variable, external, something custom)
- Core components (variation picker, qty input, button) which can all be registered internally using the same system
- If a product type has no registered components it's not supported - fallback to something else (https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/2857)

In addition to this formal registration per product type, it might be useful to also offer some slot fill areas so that extensions can output something across all product types.

**Comment by helgatheviking** [comment]
Name Your Price would fall into that category. Mix and Match too.

**Comment by mikejolley** [comment]
Internal discussion here about approach to this system https://teamrubik.wordpress.com/2020/07/28/building-an-%e2%9a%9b%ef%b8%8f-add-to-cart-form-element-registration-api/

**Comment by helgatheviking** [comment]
don't close
