### ISSUE TITLE
Cart and Checkout blocks are broken in IE11

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#2703]
**To Reproduce**
1. With IE11, go to a page with the Cart or Checkout blocks.
2. Notice you get an error in the console:
![imatge](https://user-images.githubusercontent.com/3616980/84502773-3f59d300-acb9-11ea-8859-a9af01ccbad8.png)

The error points to:
https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/assets/js/module_replacements/dashicon.js.

If the issue is that file, this might be a regression in 2.7.0.

**Comment by nerrad** [comment]
Do you know what specific line it points to Albert?

**Comment by nerrad** [comment]
I'm suspecting that babel polyfills aren't getting added on this module replacement which is why we might be encountering this.

**Comment by nerrad** [comment]
It affects any client side rendered block.

**Comment by nerrad** [comment]
Ya as I suspected, it's looks like babel isn't running on this module and transpiling to IE friendly code.
