### ISSUE TITLE
Simplify naming of directories of the Cart & Checkout totals components

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#2712]
We could simplify the naming of the directories under `/assets/js/base/components/cart-checkout/totals`:

* `subtotals-item`→ `subtotal`
* `totals-coupon-code-input` → `coupon`
* `totals-discount-item` → `discount`
* `totals-fees-item` → `fees`
* `totals-footer-item` → `footer-item`
* `totals-item` → `item`
* `totals-shipping-item` → `shipping`
* `totals-taxes-item` → `taxes`

Reasons for that:
* There is no need to repeat `totals`, it's already the name of the parent class.
* Lets reserve the suffix `-item` for `totals-item` and `totals-footer-item`, which apply a specific style depending on their position.
* This will match the class names introduced in #2711.

**Comment by nerrad** [comment]
Generally we follow the naming schema where the folder or the file (if it's a more flat structure) match the _name of the component_. So I'm not sure we should rename things this way unless we also plan on renaming the components.

**Comment by Aljullu** [comment]
> Generally we follow the naming schema where the folder or the file (if it's a more flat structure) match the name of the component.

@nerrad good point, sorry for not specifying. Yes, the idea would be to update component names as well, so `TotalsCouponCodeInput` would become `TotalsCoupon`. In the folder structure, it would be inside `.../totals/coupon/index.js`, so its name would actually be compounded from its own directory and the parent one. This is similar to how other components get their name from the composition of the directory and the file name: `shipping-calculator/address.js`'s component is named `ShippingCalculatorAddress`. If this type of relation between the file name and the folder name is not correct, I think it would be good to document it, so we don't keep introducing components with the wrong folder/filename structure.

Going back to `TotalsCouponCodeInput`, the component is not only rendering the input, but an entire section of the Totals sidebar including a panel, a button, etc., so I think the previous name was not appropriate. I don't have a strong opinion on which should be the end name, but to keep it simple, I thought that `Totals${keyword}`/`.wc-blocks-component-totals-${keyword}` for the component name/class name would be a good approach.

The last change that was proposed was removing the suffix `-item`. It doesn't have a lot of meaning in most cases, that's why I think we could remove it from all components but keep it in `TotalsItem` and `TotalsFooterItem`. These last two are a bit different from the others because they infer a specific position in the totals sidebar, so having the same suffix but different from the others makes easy to see they are kind of related.

Of course, this is very subjective, but wanted to post here some of the reasons for those proposed changes. :slightly_smiling_face:
