### ISSUE TITLE
Notice for `Filter Products by Attribute`

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce-gutenberg-products-block#2715]
**Describe the bug**
```
PHP Notice: Undefined index: query_type in /srv/www/wordpress-one/public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/StoreApi/Routes/ProductCollectionData.php on line 77
```

**To Reproduce**

1. Added All products, Filter by price and Filter by attributes blocks to a page, got the notice in the log.

**Expected behavior**
No notice.

**Screenshots**
![Screenshot 2020-06-15 at 14 56 50](https://user-images.githubusercontent.com/2207451/84659998-87c2fc00-af18-11ea-8cd0-b4e04085d8e2.png)

env the same as issue 2714, blocks 2.7.0, WC master, WP 5.4.1.

**Comment by Aljullu** [comment]
Thanks for filling @peterfabian! I could reproduce this one too. After adding the All Products and Filter by Price blocks in the editor, I added the Filter by Attribute block. Doing so generated the warning.

I could reproduce it in 2.5.x, so it doesn't seem to be a regression.
