### ISSUE TITLE
Coupon label inside the chip instead of coupon code in the checkout block

### ISSUE THREAD

**Issue by codewp** [woocommerce/woocommerce-gutenberg-products-block#2716]
I noticed that WooCommerce Blocks is using coupon code instead of coupon label inside chips in the checkout block and there is not any way to filter it.

In our plugin, we append a suffix to the coupon code to make it detectable that this coupon added by our plugin and using coupon code there has a display issue and there is not any filter to use label instead of coupon code there.

Also, all coupon codes are removable but we would like to make some of the coupons not removable by the user. In the WooCommerce we did it with "woocommerce_cart_totals_coupon_html" but in the WooCommerce Blocks, we don't have such an option.

Please let me know your feedback.

**Comment by nerrad** [comment]
Hi there 👋 

Thanks for taking the time to leave this feature request!

Currently the blocks have parity with the default way coupons are displayed in the shortcode powered Cart and Checkout flow (which is to use the coupon code instead of the Coupon description). When you say coupon "label" you mean the description field for coupons right? I don't think WooCommerce core has a "label" field for coupons.

I think this is something we could consider as an option for merchants with the coupon field but we would have to consider how things would work for merchants that have a lot of text in the description field. 

I've added this for consideration as we think through extensibility or how this might work as an option in future iterations of the blocks.

**Comment by codewp** [comment]
Hi @nerrad :handshake:

Thank you so much for your response.

In the WooCommerce itself, there is the below filter and we used it to show the meaningful name of the coupon.
```php
$label = apply_filters( 'woocommerce_cart_totals_coupon_label', sprintf( esc_html__( 'Coupon: %s', 'woocommerce' ), $coupon->get_code() ), $coupon );
```
The above code is in the `wc_cart_totals_coupon_label` inside `woocommerce\includes\wc-cart-functions.php`

Because WooCommerce Blocks only use `text={ cartCoupon.code }` and has not any filter it only shows the coupon code.

Also, WooCommerce has a below filter to and we used it to make the coupon unremovable.
```php
echo wp_kses( apply_filters( 'woocommerce_cart_totals_coupon_html', $coupon_html, $coupon, $discount_amount_html ), array_replace_recursive( wp_kses_allowed_html( 'post' ), array( 'a' => array( 'data-coupon' => true ) ) ) );
```
This filter is in the `wc_cart_totals_coupon_html` function inside `woocommerce\includes\wc-cart-functions.php` and we used above filter to remove the below code from it to do not allow a coupon to be removed.
```php
' <a href="' . esc_url( add_query_arg( 'remove_coupon', rawurlencode( $coupon->get_code() ), Constants::is_defined( 'WOOCOMMERCE_CHECKOUT' ) ? wc_get_checkout_url() : wc_get_cart_url() ) ) . '" class="woocommerce-remove-coupon" data-coupon="' . esc_attr( $coupon->get_code() ) . '">' . __( '[Remove]', 'woocommerce' ) . '</a>';
```
In the WooCommerce Blocks, all of the coupons are removable and we don't have any filter to make them unremovable.

Also, I should say that you are right and coupons haven't label and they have only code and we used the above filters to show meaningful coupon labels and my meaning was not coupon description because as you said description maybe multiline and it is not possible to show them inside a chip.

Please let me know does it make sense?

Thanks.

**Comment by nerrad** [comment]
This came up in our triage of issues and this is something that we're not going to be addressing in the current plans for the Checkout and Cart blocks. While I understand the technical implementations described above, the use-case from a shopper/merchant perspective still is not clear or apparent. Having more insight into that use-case could help with potentially addressing it in more a more holistic way vs what appears on the surface to be a workaround using these filters.

For now, we have no plans on including parity with these filters in the Cart and Checkout blocks. However, should there be more use-cases surface that indicate broad need for this, we're definitely open to reconsider. In the meantime, if this is critical functionality for your needs, using the shortcode based checkout flows is likely still your best option.
