### ISSUE TITLE
Document how to write E2E tests using the new par

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#2718]
With https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2707 merged, I changed the way we approach E2E tests for blocks, this needs documentation so other team members can approach this easily.

**Comment by nerrad** [comment]
Looks like #2800 got the ball rolling on this issue so I think we can close it. Improving and iterating on docs is an ongoing thing.
