### ISSUE TITLE
Several of our blocks don't honor 'Thumbnail cropping' setting

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#2728]
**To Reproduce**
1. Create a product with a big vertical image.
2. Go to Appearance > Customize > WooCommerce > Product Images
3. Select the option to crop the images as 1:1.
4. Go to a page with some of our blocks and notice most of them don't honor the setting:
  * All Products show the image without cropping:
![imatge](https://user-images.githubusercontent.com/3616980/84765950-4d1c9a80-afd0-11ea-8e17-576d6663e7ce.png)
  * Same for the Cart and Checkout blocks:
![imatge](https://user-images.githubusercontent.com/3616980/84766520-42163a00-afd1-11ea-98e8-fdef932d51ca.png)
![imatge](https://user-images.githubusercontent.com/3616980/84766562-522e1980-afd1-11ea-9bf7-c45ad16bf186.png)
  * Review blocks product images are squared in the frontend but, if you select a custom cropping size in the settings, they don't honor it. So they seem to be affected by this bug as well. Also, even with 1:1 cropping they don't look squared in the editor:
    * _Editor_:
![imatge](https://user-images.githubusercontent.com/3616980/84766408-0a0ef700-afd1-11ea-859a-c029363f66ce.png):
    * _Frontend_:
![imatge](https://user-images.githubusercontent.com/3616980/84766427-14c98c00-afd1-11ea-8b5c-5be8235c1c96.png)

PHP-based product grid blocks correctly show the images cropped.

**Screenshots**
For reference, this is how it looks in the Shop page:
![imatge](https://user-images.githubusercontent.com/3616980/84766935-ec8e5d00-afd1-11ea-97b4-67d5f51433bd.png)

**Expected behavior**
All blocks should honor the settings and display images cropped if that's the selected setting.

**Related issue:** #2719.

**Comment by nerrad** [comment]
Hmm this is an interesting one because it appears this is a setting specific to the StoreFront theme right @Aljullu? While we might have to adjust how client side rendering works to accommodate how themes configure things like this (extensibility wise), I'm not sure we want to cater to specific themes in the blocks.

**Comment by Aljullu** [comment]
> this is an interesting one because it appears this is a setting specific to the StoreFront theme right @Aljullu?

AFAIK this [feature](https://docs.woocommerce.com/document/image-sizes-theme-developers/#section-2) is from WC Core. After switching to Twenty Twenty, for example, I can still access that section of the settings:

![imatge](https://user-images.githubusercontent.com/3616980/84786156-a98db300-afec-11ea-9a78-f333eaefcdf2.png)

**Comment by nerrad** [comment]
Today I learned! That’s good to know and definitely makes it easier for knowing where support lies 👍
