### ISSUE TITLE
Don't show out of stock single/variation products in blocks 

### ISSUE THREAD

**Issue by Jorgu5** [woocommerce/woocommerce-gutenberg-products-block#2739]
We need an option to disable showing out of stock products, otherwise we are promoting something that we don't have in our stores at the moment. 

The best solution would be an option inside Gutenberg editor, where we can tick "don't show out of stock products"

**Comment by nerrad** [comment]
Hi there 👋,

Would you mind sharing a few more details for your request please? This feature plugin includes a number of blocks that could be related to stock and it's not clear what specific blocks your request relates to. Currently, it's hard to assign any action to this issue.

Thanks!

**Comment by Jorgu5** [comment]
Thanks for prompt reply.

Which blocks are currently related to stock? I don't see any block that would give me an option to show products ONLY that are "in stock". We need this option for 

- Best Selling Products
- Newest Products
- On Sale Products

Blocks.

**Comment by Jorgu5** [comment]
Any chance it will be fixed soon?
