### ISSUE TITLE
Inserting the products by category block without selecting a category

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/woocommerce-gutenberg-products-block#274]
**Describe the bug**

The products by category block can be inserted into the editor without selecting a category. 

**To Reproduce**

1. Add the products by category block
2. don't choose any categories
3. click done
4. The block renders all products ordered by most recent added to the store

**Expected behavior**

We should consider re-labeling the "done" button to "Insert Block"

If a user inserts the block without selecting a category, we should render an empty state similar to what appears if a user selects a category with no products. (see screen shot below)

It's also possible to end up in the same state by unchecking all of the categories in the sidebar. In that case we should render the same empty state message. 

**Screenshots**

<img width="952" alt="screen shot 2018-12-19 at 2 52 03 pm" src="https://user-images.githubusercontent.com/4500952/50253531-53ac6080-039f-11e9-858e-e7965a414f74.png">

**Comment by ryelle** [comment]
> We should consider re-labeling the "done" button to "Insert Block" and make it disabled until a selection is made.

I'd like to avoid having it disabled, some screen readers will skip over disabled buttons leaving those users confused about the next step (we could possibly work around this by adding extra text explaining things?) – see [Disabled buttons suck](https://axesslab.com/disabled-buttons-suck/)/[Disabled buttons don’t have to suck!](https://medium.com/@DanielKoster/disabled-buttons-dont-have-to-suck-6dcd22b16b6) for some context.
