### ISSUE TITLE
2x confusing error notices + broken checkout when user cancels 3D secure payment

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#2743]
**Describe the bug**
Stripe supports an extra ["3D Secure" payment verification modal](https://en.wikipedia.org/wiki/3-D_Secure) for some cards. There's a [test card number](https://stripe.com/docs/testing) you can use to trigger this modal.

If the user cancels the modal, the checkout is in a bad state and the error notices are unhelpful; the user cancelled, so the checkout should roll back to previous state.

**To Reproduce**
0. Set up your store with Stripe CC payment method, in test mode.
1. Set up page with checkout block (not shortcode).
2. Add stuff to cart, proceed to checkout.
3. Complete checkout form, and use this [test card number](https://stripe.com/docs/testing): `4000 0027 6000 3184`
4. Click `Place order`.
3. 3D secure / verification modal should pop up - click `CANCEL` in top right.
2. See error notices etc (see below).
1. Subsequent attempts to pay fail, even with different card number - I think the checkout is in a broken state. (Need to refresh page.)

**Expected behavior**
If the user cancels payment at any stage, the checkout should roll back to "ready to submit" state cleanly. Any error message should be consistent and reassuring, e.g. "payment cancelled by user" (Stripe maybe has recommended wording.)

There may be other modal-payment flows that we might need to test - e.g. [SCA](https://en.wikipedia.org/wiki/Strong_customer_authentication).

Also need to test other flows out of the 3DS modal, e.g. verification fail, verification succeed (etc).

**Screenshots**
<img width="653" alt="Screen Shot 2020-06-17 at 4 01 02 PM" src="https://user-images.githubusercontent.com/4167300/84957085-95fa5d80-b14e-11ea-934c-db32e2d0b195.png">

**Comment by haszari** [comment]
Tested this with old checkout for comparison. The same generic ish error notice is shown, and the payment can be completed without needing to reload the page.

<img width="775" alt="Screen Shot 2020-06-19 at 1 27 18 PM" src="https://user-images.githubusercontent.com/4167300/85087163-d9c59380-b230-11ea-8583-f84b1a47a3c7.png">

**Comment by nerrad** [comment]
I'm noting a couple other things the WCPay team noted in testing and I'm just leaving here for investigation as well since it's related to this flow (might be done in separate pulls, but not sure it warrants separate issues yet).

- WCPay noted that "Even though the confirmation failed, the submit button displays a seemingly successful check-mark." It doesn't look like it happened here for Rua, but we should take a closer look to see if it _could_ happen given certain conditions.

**Comment by haszari** [comment]
Just noting that the failure behaviour is the same for canceling from the top-right (modal cancel) or failing auth (`FAIL AUTHENTICATION` button). 

<img width="931" alt="Screen Shot 2020-08-07 at 11 39 21 AM" src="https://user-images.githubusercontent.com/4167300/89593226-b3bc8700-d8a2-11ea-8c19-c468cffe2fed.png">

Initially I'm going to focus on getting the checkout in healthy state after cancel. I.e. if 3DS is cancelled, user can try again without refreshing the page.

**Comment by haszari** [comment]
Initially I'm going to focus on getting the checkout in healthy state after cancel. I.e. if 3DS is cancelled, the shopper should be able to try again without having to refresh the page.

**Comment by haszari** [comment]
Digging into the error/data flow to figure out why we get two notices. Still figuring things out but here's some raw info:

### `usePaymentIntents` hook
- This is involved when a 3DS card number is used, but not used for normal card numbers. I don't understand what code is responsible for this, I suspect some Stripe API or lib code is invoking our payment intent handler when needed.
- `usePaymentIntents` has a few success cases, but one error case - if an exception is thrown or the request returns an object where `response.error` is truthy.
- Exception handler returns an "error, please try again" response to checkout processing, and passes `error.message` up to display in payment notice context (i.e. near payment form on screen).
- I'm a little concerned that I don't know what cases cause `usePaymentIntents` to fire - what are all the cases I need to test? How do we know this code is working 100% - or is it not fully tested?

### Normal (non "intents") error handling
- In `useCheckoutSubscriptions`, there's a handler for `onCheckoutAfterProcessingWithError`. I'm guessing this handles normal error case.
- In 3DS fail case, this fires too - but I suspect the data it's passed is confusing it - `paymentStatus: "success"`. See below for a full json example.

So what I think is happening is that the payment intents logic is not clearly signalling to the normal flow that there was an error. So we just need to figure out how to do that 😁 

@nerrad  - I'm happy to keep digging here - but if you have a moment to guide me that might save some time! 


```
# onCheckoutAfterProcessingWithError called with this after 3DS fail
message: ""
paymentStatus: "success"
paymentDetails: {  
  payment_intent_secret: "pi_1HDMiUJVW71mhMFtT3ud7vQM_secret_7bUhB9hqG53hCI46rFsJlo4iM"
  redirect: "http://localhost:8333/?page_id=7&order-received=82&key=wc_order_gvDd6GfE8gu1M"
  result: "success"
  verification_endpoint: "http://localhost:8333/?wc-ajax=wc_stripe_verify_intent&order=82&nonce=f08cf4ed9f&redirect_to=http%3A%2F%2Flocalhost%3A8333%2F%3Fpage_id%3D7%26order-received%3D82%26key%3Dwc_order_gvDd6GfE8gu1M"
}
```

**Comment by haszari** [comment]
Unassigning myself for now - focusing on other areas for cooldown 5. When we get back into cycle anyone (including me) can pick this up 😄

**Comment by haszari** [comment]
Added some logging in the checkout state reducer to better understand the normal success flow and the 3DS flow (when it fails).

```
// Checkout state - successful Stripe purchase
type=set_before_processing  undefined undefined
type=set_checkout_is_processing  undefined undefined
type=set_redirect_url  http://localhost:8333/?page_id=7&order-received=276&key=wc_order_6suvzcyFr8Dqp undefined
type=set_processing_response  undefined {message: "", paymentStatus: "success", paymentDetails: {…}}
type=set_after_processing  undefined undefined
type=set_checkout_complete  undefined {type: "success"}
Navigated to http://localhost:8333/?page_id=7&order-received=276&key=wc_order_6suvzcyFr8Dqp
```

```
// Checkout state - unsuccessful Stripe purchase with 3DS card cancelledd
type=set_before_processing  undefined undefined
type=set_checkout_is_processing  undefined undefined
type=set_redirect_url  http://localhost:8333/?page_id=7&order-received=277&key=wc_order_LV1HVa18zDVeX undefined
type=set_processing_response  undefined {message: "", paymentStatus: "success", paymentDetails: {…}}
  paymentDetails:
    payment_intent_secret: "pi_1HQ3P1JVW71mhMFtr72qUUBj_secret_LcbmHxLg2AxLpPhJFeD7i5CHc"
    redirect: "http://localhost:8333/?page_id=7&order-received=277&key=wc_order_LV1HVa18zDVeX"
    result: "success"
    verification_endpoint: "http://localhost:8333/?wc-ajax=wc_stripe_verify_intent&order=277&nonce=b54c86ff20&redirect_to=http%3A%2F%2Flocalhost%3A8333%2F%3Fpage_id%3D7%26order-received%3D277%26key%3Dwc_order_LV1HVa18zDVeX"
type=set_after_processing  undefined undefined
// -- Modal shown here --
// -- Shopper cancels modal (or payment fails auth) --
type=set_checkout_has_error  undefined undefined
type=set_idle  undefined undefined
```

So, similar to above findings, I think there's an interim `success` response firing – BEFORE the auth modal is displayed. So we might need to tweak the flow in `usePaymentIntents` so the checkout isn't set as successful before 3DS auth is completed. And of course we may need to tweak the handling of the auth callback - i.e. real success/failure for 3DS.
