### ISSUE TITLE
Display account login form inline with the Checkout Block

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#2751]
Currently the Checkout block has a Login link exposed if the store is configured to offer login for Customers. However, it’s behaviour is different than the shortcode checkout flow. The shortcode checkout flow allows for inline logging in without leaving the checkout.

I think it will be better if we allow for inline logging in as well.

This will require some design input (and prioritization) before tackling.

In the meantime, it is worth noting that while the current login flow does take the user to the native WordPress login form, it is configured to redirect back to the checkout after the shopper logs in.

**Comment by haszari** [comment]
At face value, this feels like an opportunity for a new block. Either a login block, or a login/signup combo block.

I could imagine that this would be a useful block that merchants could use anywhere they want the user to log in, and then we'd use the same code for rendering a login form as a fallback for checkout when needed. Possibly could use a similar approach as empty cart's `InnerBlocks`.

Just mentioning that in case we have a login block or something similar later in the roadmap.
