### ISSUE TITLE
Checkout does not respect the payment method settings for express payment method being active

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#2754]
First reported in [this forum thread](https://wordpress.org/support/topic/remove-express-pay-on-checkout-page/).

## Steps to reproduce:

On a site where express payment method has been configured initially.

1. Uncheck payment request methods in the Stripe settings
![IMG_0012](https://user-images.githubusercontent.com/1429108/85134222-25187b80-b20a-11ea-983e-6ba7faeecd7c.jpeg)
2. View checkout in the editor and in the front end. Notice the express payment area still shows up.

The expectation is that when express payment methods are turned off, that the checkout will respect that and not show them.

**Comment by nerrad** [comment]
Note: this is likely more a bug with the payment method integration itself.

**Comment by haszari** [comment]
Noticed a related issue - we're ignoring the merchant-configured `Title` for Stripe Credit Card #2919 - FYI @nerrad @Aljullu
