### ISSUE TITLE
Cart & Checkout: style button depending on theme colors

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#2761]
According to the last designs, the _Proceed to Checkout_ and _Place Order_ button styles should depend on theme colors:

![imatge](https://user-images.githubusercontent.com/3616980/84915063-a104ad80-b0bc-11ea-8c59-c5a0b89c0afa.png)

In #2494 we removed the `button` class to avoid style conflicts in the editor, so we don't have an easy way to inherit theme styles (at least, until global styles are an option).

My proposal would be to leave it as-is in WC Blocks and instead style it directly in Storefront. Something like:

```SCSS
.wc-block-components-button {
  background-color: $button_alt_background_color;
  color: $button_alt_text_color;
}
```

This way, we ensure old `.button` styles from themes are not applied to the button, so we minimize the possibility of style conflicts.

The biggest con of this approach is that buttons will show 'default' colors for all themes not Storefront-based. I think it's fair enough to expect themes to update to support this new component. We could document it.

Tagging @mikejolley and @haszari for feedback. If this approach makes sense, I would add the new styles to Storefront and write some docs for WC Blocks repo.

**Comment by mikejolley** [comment]
I mean, it does make the most sense. Defaults should use black or neutral tones and themes should be given a list of component classes (documented stylesheet?) to customise them in bulk. I think your proposal makes sense 👍 

How would you feel about moving all color declarations out of the individual component style sheets into a single colors stylesheet, with inline docs explaining what each component is used for, which forms the basis of customisation for themes? That can also hold the default colors for ease of use.

**Comment by Aljullu** [comment]
Thanks for the feedback @mikejolley! Yeah... I think we should evaluate how we can make it easier for themes to style those components. My idea was to document it like here:

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/main/docs/theming/cart-and-checkout.md

If needed, we could also host a CSS file which grouped all code snippets from the docs, so themes could see all selectors we recommend them to use without needing to read the docs, something like [this](https://gist.github.com/Aljullu/592ceb9d1033e8752db634ed8b628b86).

I'm not sure about splitting our styles to separate the color declarations (but I'm happy to change my mind :slightly_smiling_face: ). Currently, our components styles are always inside `style.scss`, and I think it makes working with them quite easy. If we split the rules and some of them are in `style.scss`, but some others in a file in the root directory (`colors.scss`?), my concern is that it might make it harder to know where to go to do style modifications? I don't have a strong opinion on this, so happy to hear your thoughts.

Kinda related, but these last days I have been wondering if we should start using CSS custom properties. I saw Coblocks and some new themes are using them, but I'm just wary about doing an implementation now and having to refactor it when global styles land in Gutenberg.

**Comment by mikejolley** [comment]
It might be harder unless you know where to look yes, but it also:

- encourages you to think about what is getting color based styles, and why
- see other color based styles in the same context so more likely to follow existing convention
- allows color changes to be made in bulk from one place
- gives you that CSS like your example ready for themes

I don't mind either way, just thinking it might makes things easier in the long run for themes and also for us should colors become dynamic and need to be extracted into the page.

**Comment by Aljullu** [comment]
Ok, for now I created a PR documenting how to style the Cart & Checkout button styles (https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2814) and a PR in Storefront applying those styles (https://github.com/woocommerce/storefront/pull/1412). Moving color declarations of other blocks/components into a separate file can be done as a follow-up so we don't block this issue.
