### ISSUE TITLE
Refactor changelog generator to account for block-type labels.

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#2766]
We introduced a new set of labels `block-type: BLOCK` those labels break our release tool as it expects only `type: SOMETHING`, we should account for such things in our regex.

**Comment by Aljullu** [comment]
@senadir I'm not able to reproduce this issue, I tried running `npm run changelog` on a release with a PR tagged with `block-type: xyz` and everything worked as expected, I couldn't see any breakage. Am I doing something wrong?

It's true that the info from the `block-type` label was ignored, but the same happens with `block` labels. The changelog script doesn't show which blocks are affected in each changelog entry. Is this issue about changing that and introducing the info from `block-type` and `block` in the changelog?

**Comment by nerrad** [comment]
I don't think this is an issue we have to worry about given we've done a number of releases since this issue was created.
