### ISSUE TITLE
Evaluate if we can switch to the changelog package used in GB.

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#2767]
Some time ago, we copied our changelog script to the GB repo, it had more interest there and more development work, we should look into the possibility of using that code directly, so we don't end up fixing bugs in two places.

**Comment by nerrad** [comment]
I'm going to close this because changelog is currently built by the release pull request automation (which in turn lifted code from the changelog script in GB - which isn't in a package).
