### ISSUE TITLE
"New" product badge not applying to all new products

### ISSUE THREAD

**Issue by alanabweinstein** [woocommerce/woocommerce-gutenberg-products-block#2791]
**Describe the bug**
The new Marketplace landing page is showing some products, but not all, with their proper badges. The "new" badge seems to be applying to a couple of new products on this page: https://woocommerce.com/product-category/woocommerce-extensions/?orderby=date&#038;paged=1 

But other new products next to One Stock and Product Recommendation Quiz that are also new, are not showing the badge.

**To Reproduce**

1. Go to https://woocommerce.com/product-category/woocommerce-extensions/?orderby=date&#038;paged=1 
2. Look at first couple of thumbnails appearing, which appear as new
3. Next to the first two, you'll see they are not marked as new

**Expected behavior**

I'd like to confirm the parameters we're using to label a product as new. For now, I'd like to label anything that's launched in the past 3 months as new. This will likely change over time as we continue to scale.

**Screenshots**

<img width="1380" alt="Screen Shot 2020-06-30 at 2 32 09 PM" src="https://user-images.githubusercontent.com/43149472/86163627-8b40b080-bade-11ea-909e-97bdbc3a5371.png">

CC @mattyza @bgrgicak

**Comment by bgrgicak** [comment]
@alanabweinstein this issue is related to WooCommerce.com only, we are not using product blocks.

Currently, we are marking products as new if they were published in the last 2 weeks. I will update this to be 3 months on WooCommerce.com.

I'm closing this issue and will open another one in the WooCommerce.com GitHub repo.
