### ISSUE TITLE
Implement GitHub action for modifying labels for approved pull requests.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#2809]
We're moving away from the Zapier automations we have since there's no longer need to use Zapier when we can implement automations via GitHub actions. Currently one Zapier action we have is adding the `status: ready to merge` label when a pull request has been approved.

We can just implement an action for this. One option could be [this one](https://github.com/marketplace/actions/label-approved-pull-requests).

For reference, here is an issue I created in the woo automations repo: https://github.com/woocommerce/automations/issues/8

**Comment by mikejolley** [comment]
Can this be done during next cooldown? I can't cancel billing in zapier without cancelling the plan entirely so this needs doing first :)

**Comment by nerrad** [comment]
This has been added added with https://github.com/woocommerce/woocommerce-gutenberg-products-block/commit/23d65493c2fba470f2210e8d73f15a634f2ae0fe and https://github.com/woocommerce/woocommerce-gutenberg-products-block/commit/961d22a3e00b6e4e59b7488c1afd2f543ead0b80
