### ISSUE TITLE
Configure renovate to update major versions on devDependencies

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#2811]
I've noticed that a number of our devDependencies are _significantly_ behind in updates because currently renovate seems to be configured to only update within the minor release range. Ideally devDependencies would not be pinned either since they are for development, they should be updated more frequently.

**Comment by haszari** [comment]
Looks like you can [configure `automerge` for `devDependencies` using `devTypeList`](https://docs.renovatebot.com/configuration-options/#automerge). Maybe something like this:

```json
{
  "packageRules": [
    {
      "updateTypes": ["minor", "patch", "pin", "digest"],
      "depTypeList": ["devDependencies"],
      "automerge": true
    }
  ]
}
```

Note, the `"updateTypes": ["minor", "patch", "pin", "digest"]` in our current config is intended to only automerge minor updates.

**Comment by haszari** [comment]
Linking in #2806 - automerge is not working for us for some reason. So that needs fixing too :)
