### ISSUE TITLE
Price slider thumbs sometimes don't work in Safari/WebKit browsers

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#2819]
**Describe the bug**
The `Filter by price` block price slider thumbs sometimes don't work in Safari. Tricky to reproduce, but frustrating when it happens!

![Screen Capture on 2020-07-06 at 17-04-52](https://user-images.githubusercontent.com/4167300/86557644-e412bc00-bfaa-11ea-9307-69809d2eda8f.gif)

Discovered when testing 2.9.0 release. #2816

**To Reproduce**
1. Add a page with All Products + Price filter block and publish.
2. View page on front end, in Safari.
3. Mouse over thumbs - no hover effect, and can't "pick up" by clicking.

Two things that help trigger this:

- Reduce the price range to the minimum width - i.e. drag the top down a bit and the bottom thumb up until it can't move anymore.
- Mouse in from the purple slider line, over the "arrow" part of the thumb.

Feels like it might be a mouseenter/mouseleave bug?

**Expected behavior**

**Screenshots**
Should be able to easily change the price filter at all times.

**WordPress (please complete the following information):**

* Core version: 5.4.2
* Gutenberg version (if installed): n/a
* WooCommerce version: 4.2.2
* WooCommerce Blocks version: 2.9.0, 2.8.0

**Desktop (please complete the following information):**

* OS: macOS
* Browser: Safari 
* Version: 13.1.1 (15609.2.9.1.2)

**Additional context**

**Comment by nerrad** [comment]
I spent a few minutes trying my darndest to reproduce this in Safari unsuccessfully (using the steps outlined in the oc and extrapolating to intentionally try to break):

![Screen Recording 2020-12-15 at 01 46 58 PM](https://user-images.githubusercontent.com/1429108/102258620-1ae6e980-3edc-11eb-8f80-d0f69a3f031a.gif)

I'm going to close this for now as it's possible it's been fixed via some other work we did. If it resurfaces we can always create a new issue.
