### ISSUE TITLE
Product block don't respect out-of-stock product visibility setting

### ISSUE THREAD

**Issue by Magganpice** [woocommerce/woocommerce-gutenberg-products-block#2824]
**Describe the bug**
There is a setting (checkbox) in WooCommerce settings to display/not display out-of-stock products in the shop catalog. Regardless of this setting the product block display all products.

**To Reproduce**

1. Set WooCommertce to not show out-of-stock products in the shop (here: /wp-admin/admin.php?page=wc-settings&tab=products&section=inventory)
2. check to see: the product block still display them

**Expected behavior**
Product block should respect this setting and not display out-of-stock product if that option is checked.

* Core version: 5.4.2
* WooCommerce version: 4.2.2
* WooCommerce Blocks version: 2.9.0
* Site language: German

**Comment by nerrad** [comment]
Hi there 👋,

Thanks for taking the time to report this bug, we really appreciate your help. I can reproduce this and it's clearly an issue that needs resolved. We'll start working on it soon.

**Comment by Magganpice** [comment]
any plans to fix this? Isn't it quite an important block and its showing wrong products.

**Comment by Magganpice** [comment]
So it just got wiped away? Is the issue not understood?

**Comment by nerrad** [comment]
Sorry about that, no we missed this issue getting flagged and closed by the stale bot while various members of the team were away during the holiday season. Thanks for leaving a comment to re-surface this to our attention!
