### ISSUE TITLE
Cart block not showing when product is on backorder

### ISSUE THREAD

**Issue by aheckler** [woocommerce/woocommerce-gutenberg-products-block#2825]
If you allow backorders for an out-of-stock product, an alert is shown on the core WooCommerce Cart page, but not in the WC Blocks Cart page.

Core WC cart page:

![Markup on 2020-07-07 at 10:55:41](https://user-images.githubusercontent.com/5512652/86799931-7ca74b80-c040-11ea-9cec-9db404d84979.png)

Cart block:

![Markup on 2020-07-07 at 10:56:00](https://user-images.githubusercontent.com/5512652/86799958-84ff8680-c040-11ea-9c8b-a6c2da0fc27a.png)

**Expected behavior**
I would expect a notice in the cart block similar to the stock WC cart page.

From: https://wordpress.org/support/topic/backorder-message-not-visible-on-cart-page/

**Comment by Aljullu** [comment]
Thanks for filling this issue, @aheckler!

@LevinMedia any advice design-wise on how to display this? This is what I got currently working:

![imatge](https://user-images.githubusercontent.com/3616980/86902182-e5102e80-c10d-11ea-8089-4b391163407a.png)

**Comment by LevinMedia** [comment]
@Aljullu Let's use the same treatment we've got for low stock indication, on both the cart and checkout: 

### **Cart**

**Low stock:**
<img width="992" alt="Screen Shot 2020-07-09 at 11 31 09 AM" src="https://user-images.githubusercontent.com/4500952/87077415-ed34a080-c1d7-11ea-829b-8e12347cd74d.png">

**Backorder:**
<img width="1007" alt="Screen Shot 2020-07-09 at 11 31 01 AM" src="https://user-images.githubusercontent.com/4500952/87077404-ea39b000-c1d7-11ea-8ccd-584cab43c607.png">

### **Checkout**

**Low stock:**
<img width="1012" alt="Screen Shot 2020-07-09 at 11 35 27 AM" src="https://user-images.githubusercontent.com/4500952/87077676-57e5dc00-c1d8-11ea-981b-6761fef9bb61.png">

**Backorder:**
<img width="1011" alt="Screen Shot 2020-07-09 at 11 35 13 AM" src="https://user-images.githubusercontent.com/4500952/87077703-63d19e00-c1d8-11ea-9b47-861dfde1f1c7.png">
