### ISSUE TITLE
Payment gateways in WooCommerce Block

### ISSUE THREAD

**Issue by Titus100** [woocommerce/woocommerce-gutenberg-products-block#2826]
I highly appreciate the effort in developing woocommerce block.

Read up that developers are working on adding more payment gateway to improve user experience.

I would suggest that Rave payment gateway by FlutterWave be included in this process as this is a popular payment gateway African continent and has a large user base.
Thanks

Titus

**Comment by nerrad** [comment]
Hi there!

Thanks for letting us know about your interest in seeing Rave payment gateway supporting the new Checkout block!

Unfortunately, we won't be building actual payment method support in the blocks in this repository, the block merely provides the [api for payment methods to integrate themselves](https://github.com/woocommerce/woocommerce-gutenberg-products-block/tree/main/docs/extensibility).

I suggest getting in touch with the developers of any extensions integrating with Rave and letting them know about your desire to see support for the block!  I notice one extension is [listed here](https://wordpress.org/plugins/woo-rave/).
