### ISSUE TITLE
Support for payment methods that change availability based on user actions/data in checkout - e.g. COD supported for specific shipping methods only

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#2838]
**Is your feature request related to a problem? Please describe.**
`Cash on Delivery` (COD) payment method can be enabled for merchant-selected shipping options only. For example, a store uses one particular shipping service that allows COD, and others that don't support it. 

In the checkout block, this means that the COD payment method needs to be made available only for valid shipping methods. And if the shopper changes shipping method, or address (etc) the COD payment method may need to disable/enable dynamically. See related PR in progress for COD - #2831

Currently, payment methods return boolean from the [`canMakePayment`](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/main/docs/extensibility/payment-method-integration.md#client-side-integration) callback to indicate if the payment method can be used. This callback is currently called once on initialisation (note: some payment methods might call an API from `canMakePayment`).

**Describe the solution you'd like**
Extend the payment methods JS API to allow for dynamically-available payment methods. 

One way to do this would be to pass `canMakePayment` all relevant data (e.g. selected shipping methods, cart items), and retrigger the callback when anything changes. For example, when a different shipping option is selected, `canMakePayment` is called again. If we went this route, we'd need to carefully document this so payment methods that run expensive or async (e.g. third-party API) code know to cache it in some way. Potentially could provide a different API/callback for expensive initialisation.

Another option could allow payment methods to register for events/callbacks when specific data changes (e.g. different shipping method selected).

Note - payment methods might depend on other changing state, so we should consider that when implementing any JS API changes. For example, COD also potentially depends on the cart items (if merchant disables `Accept COD if the order is virtual`). If we implement #2583 then this will affect COD - the new API will have to support this case also. I.e. user removes physical products from order (on checkout page), COD may no longer be available.

**Comment by nerrad** [comment]
I think _ideally_ `canMakePayment` would remain the interface for this as it's fairly clear from the property name what it provides. The _only_ downside I have concerns about is what you identified about potentially expensive initialization routines.

A couple thoughts as you explore a solution using `canMakePayment`:

- Is there anything about the current payment method implementations that is potentially problematic if `canMakePayment` is invoked multiple times? Maybe take a look at the Stripe payment methods and see what they do (I know they invoke the Stripe api), including network requests.
- Could we provide an property in the argument passed into the `canMakePayment` callback that indicates whether it's the _initialization_ run or not, then payment methods could use that as a signal for what logic they run?
