### ISSUE TITLE
Improve resilience of draft order cleanup against rogue filters.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#2844]
We had a report come in about a site that updated to WooCommerce 4.3 and started seeing all their orders get deleted (p1594299378193700-slack-C0E1AV8T0).

On investigating, it became apparent that one way this could be happening is if the [`woocommerce_order_query_args` filter](https://github.com/woocommerce/woocommerce/blob/730df27bc6b92c41e7572f850d80c3afe40f9679/includes/class-wc-order-query.php#L85) is being used to filter the arguments used for the [order query Blocks is running to get orders for deleting](https://github.com/woocommerce/woocommerce/blob/d5ca9a7e14d06a75568a5a747fa97c0cf7e0c2b3/packages/woocommerce-blocks/src/Library.php#L165-L172). It's entirely possible for a rogue plugin or custom code to be incorrectly blanket filtering all queries for retrieving orders.

It's somewhat understandable that a plugin or custom code might be adding a filter here not expecting it would affect deletes (because it's a get request) even though it's still a bad assumption.

This doesn't appear to be a widespread problem, and so far only seems to surface for this single site reporting. I want to document some potential routes we can go to be more defensive here and improve the resiliency of our code against this unexpected filtering:

## Option 1:  Before deleting orders retrieved using the query, we double-check they have the expected status. 

This is probably the simplest, most straightforward approach, but it has it's drawbacks:

- `$order->status` [could still be filtered](https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-data.php#L751) and return an unexpected value (although less likely).
- The scheduled task would most likely end up running over and over if the query always returns orders without the draft status. So site performance would potentially be impacted.

## Option 2: Call `remove_all_filters('woocommerce_order_query_args')` before executing the query.

This has the advantage of ensuring that no manipulation happens via `woocommerce_order_query_args` on our query arguments. However this approach has it's caveats too:

- Assumes that `wc_get_orders` is only invoked once in the cron request executing the cleanup. If there is other code calling `wc_get_orders` in the same request _after_ `remove_all_filters` is invoked, then none of those subsequent calls will have filters applied (which could be problematic for those other cases). This could be mitigated by some clever code grabbing the state of the `$wp_filters` global before removing filters and restoring that state, but it'd likely be fragile code.
- It only catches potential filtering on `woocommerce_order_query_args`. If something is filtering the query at any other stage in the query execution stack (i.e. `wp_query` itself), there's still potential for breakage (although more likely it's happening higher in the stack).

## Option 3: Same as Option 1, but if abort and notify if non valid order returned for delete.

In this case we'd abort the scheduled action and show an admin_notice on the store's dashboard if an order not matching the expected status is returned from the query.  While this has the advantage of preventing the performance problems of Option 1, I'm not sure how we could phrase the notice to be understandable/actionable for the store owner. 

There's also the issue that while the schedules are aborted, draft orders will not be deleted and will start piling up on the site.

## Option 4: WooCommerce core introduces a method to batch delete entities.

With this method in place, it's more clear what's happening for any filters that might exist on this action. We could switch the blocks code to use this method. It's more likely customizations will pay closer attention to filtering things that explicitly delete data.

## Option 5: Do nothing - this is a problem with specific sites having poor customizations.

While this option is attractive to me. I think if we _can_ prevent catastrophic data loss (no matter who is to blame) we _should_.

------

Personally, I think the _ideal_ solution here is Option 4 but that requires some work in WooCommerce Core. Close second for me (as a potential short term solution) would be to implement Option 1. I think the performance downside is much better than potential entity deletes, and having stores surface the performance issues is still resolve-able once the offending code hooking into the filter is found.

Of course all the above is based on the assumption this is what's happening on the customer's site. It's plausible though so even if that ends up not being the case I think there may still be value in visiting this.

**Comment by mikejolley** [comment]
This is a tricky one because:

a) we're using the core function as we should be.
b) fixing this by removing filters prohibits real-valid use cases for the filters e.g. from translation plugins which duplicate order records.

I think we'll need some guidance from Proton here (@peterfabian) to whether or not this function can be trusted going forward or if we need to use something else or remove filters. As an alternative to running filters on the query itself, perhaps it would be more robust to fire an action on the IDs of affected queries once the initial one completes, albeit this could have issues if a large number of orders are affected.

Short term we should do 4 or introduce a custom batch delete (option 5).

**Comment by peterfabian** [comment]
If we're talking about Blocks code in itself, I think I'm most in favor of option 1 with the expansion pack of Option 3. If someone misconfigures their site to return all orders when code asks for drafts, then it's still better to only suffer the performance penalty than to potentially face deleted orders. If a site is not filtering the status, I believe the performance impact is negligible. 
I would assume that straight out changing status from a new one (`wc-checkout-draft`) to something else is quite rare.

For option 2, I think we would have to also remove at least `woocommerce_order_query` and we still can't be sure it's not getting filtered in another layer of code. That being said, I've just noticed that `WP_Query` has an option called `suppress_filters`, so I guess we could use it if we decided to go for this option.

However, I agree that option no 4 sounds like a better and cleaner approach overall. @ObliviousHarmony is working on adding support for batch operations. Christopher, how close you are to have it ready and have you included deletions in your batch operations? 

Based on the timeline for those changes, I think we can decide which option to go for, and if something is needed to be done in Blocks repo.

**Comment by nerrad** [comment]
> Based on the timeline for those changes, I think we can decide which option to go for, and if something is needed to be done in Blocks repo. What do you think?

With no other issues of this surfacing, I'd be okay with implementing Option 1 and then have Option 4 be the long term fix. Thoughts @mikejolley ?

**Comment by nerrad** [comment]
This is fixed by #2874
