### ISSUE TITLE
⚛️ ‎‎‏‏‎ Product Title - Update icon, inspector, and toolbar controls

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#2852]
The Product Title Element Block requires:

- [ ] A new icon
- [ ] Typography controls
- [ ] Color controls
- [ ] Heading level toolbar controls
- [ ] Alignment toolbar controls

Alignment needs specifying in the default template of the single product block so that:

- In the product block, the headline should default to h2, and left aligned.
- In grid based blocks, the headline should default to h2 and center aligned.

See https://woogrowp2.wordpress.com/2020/07/01/product-title-block/

**Comment by senadir** [comment]
Leaving this out `and left-aligned.` as setting this value explicitly would mean it's always on the left even in RTL, the title is left aligned on LTR and right-aligned on RTL unless you explicitly set an absolute value for it.
