### ISSUE TITLE
⚛️ ‎‎‏‏‎ Add to Cart - Cart context provider API

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#2856]
The cart context provider (used in the product add to cart element block) needs to allow form elements to communicate so that a product can be added to the cart with additional data if needed, or to show/update certain product data based on its state. For example, the price may be changed after selecting a variation.

We need to design and create an API to facilitate this so that important functionality is exposed.

This includes, but may not be limited to:

- Providing product data
- Sharing common cart data (qty, other form element values)
- Exposing events (with event subscribers) so form elements can validate or perform actions such as surfacing error notices, or adding supplemental data to requests

See the Checkout Payment Gateway API for inspiration (subscribers).

This is closely linked to #2736 and #2738

**Comment by nerrad** [comment]
We have a Cart context provider already... ideally we could have it so the Add To Cart button and Cart can either be the same context provider or _share_ the same _base_ properties (where things like shipping/coupons wouldn't be needed in the add to cart context). I'll take a look at this sometime this week.

**Comment by mikejolley** [comment]
Internal discussion here about approach to this system https://teamrubik.wordpress.com/2020/07/28/building-an-%e2%9a%9b%ef%b8%8f-add-to-cart-form-element-registration-api/
