### ISSUE TITLE
Slow query on large network

### ISSUE THREAD

**Issue by pkelbert** [woocommerce/woocommerce-gutenberg-products-block#2885]
**Describe the bug**

On a large network, [Query Monitor](https://br.wordpress.org/plugins/query-monitor/) reports slow query on function `Installer::maybe_create_table()` as can be seen here:

![query-monitor-slow-query](https://user-images.githubusercontent.com/3440523/87841262-8881e180-c87a-11ea-9c28-9cee83d4bc6e.png)

Note the number of returned rows and that there isn't any other slow query reported.

The cause is the query `SHOW TABLES` without any kind of filter.

**To Reproduce**

1. Create thousands of tables in a WordPress database (I faced the problem with nearly 28k).
1. Install and activate [Query Monitor](https://br.wordpress.org/plugins/query-monitor/) plugin.
1. Navigate to any admin page.
1. Check Query Monitor report.

Important: this kind of problem may present a variable behavior due to hardware capacity.

**Expected behavior**

WooCommerce shouldn't present any slow query.

**WordPress:**

* Core version: 5.4.2
* Gutenberg: not active
* WooCommerce version: 4.3.0
* WooCommerce Blocks version: not installed
* Site language: pt_BR
* Any other plugins installed: [Query Monitor](https://br.wordpress.org/plugins/query-monitor/)

**Additional context**

Although WooCommerce Blocks plugin isn't installed, I faced the problem when using main WooCommerce plugin. I'm reporting the bug in this project because it's where the problem is.

**Comment by diegpl** [comment]
The issue was related here:
https://wordpress.org/support/topic/2-6-0-update-bug/
https://wordpress.org/support/topic/slow-query-issue-create-table-for-woocommerce-blocks/

Please, adopt Phellipe Kelbert solution, it was implemented in my server and worked really great. I know Phellipe for a long time and he is an excellent programmer :-)
