### ISSUE TITLE
UTF-8 Issue in "woocommerce_blocks_product_grid_item_html" filter

### ISSUE THREAD

**Issue by hamidrezayazdani** [woocommerce/woocommerce-gutenberg-products-block#2889]
When the "woocommerce_blocks_product_grid_item_html" filter is used for Persian, the texts have a problem

**To Reproduce**
Sample code:

```
add_filter( 'woocommerce_blocks_product_grid_item_html', 'yrm_product_block', 10, 3);
function yrm_product_block( $html, $data, $product ) {
	$percentage = yrm_get_sale_percentage( $product );
	if ( $product->is_in_stock() ) {
		$ribbon = '<div class="off-ribbon"><i class="mdi mdi-decagram"></i><span>' . $percentage . ' %<br>تخفيف</span></div>';
	} else {
		$ribbon = '<div class="yrm-out-of-stock"><i class="mdi mdi-cart-off"></i><span>ناموجود</span></div>';
	}

	if( ! is_user_logged_in() ) :
		if ( $price_html = $product->get_price_html() ) :
			$price = '<span class="price mb-3">' . $price_html . '</span>';
		endif;
	else :
		if( bought-products()  ) :
			$price = '<span class="price loop-bought mb-3">قبلاً خريديش!</span>';
		else :
			if ( $price_html = $product->get_price_html() ) :
				$price = '<span class="price mb-3">' . $price_html . '</span>';
			endif;
		endif;
	endif;

    $html = '<li class="wc-block-grid__product product">
       	<a href="' . $data->permalink . '" class="woocommerce-LoopProduct-link woocommerce-loop-product__link">' . $data->image . $ribbon . '
        <h2 class="woocommerce-loop-product__title">' . get_the_title( $product->get_id() ) . '</h2>
        ' . $price . '</a>' . $data->button . '</li>';

    return $html;
}
```
**Screenshots**
You can see the output of this code in Gutenberg and in Front in the following images:

![Screenshot_2020-07-21 آخر هفته های 5 هزار تومانی کتاب‌ صوتی موفقیت رادیو مثبت](https://user-images.githubusercontent.com/40775953/88004572-88a10c00-cb1c-11ea-9e2a-df0db15fd995.png)

![Screenshot_2020-07-21 ویرایش لندینگ پیج ‹ کتاب‌ صوتی موفقیت رادیو مثبت — وردپرس](https://user-images.githubusercontent.com/40775953/88004576-8ccd2980-cb1c-11ea-80df-59b0de8f98ed.png)

**WordPress:**

* Core version:  5.4.2
* Gutenberg version (if installed): 8.5.1
* WooCommerce version: 4.3.0
* WooCommerce Blocks version: 2.9.0

**Additional context**
I tried to fix the problem by adding `content = "utf-8"` to Gutenberg files using [script_loader_tag](https://developer.wordpress.org/reference/hooks/script_loader_tag/) but it did not work.

**Comment by nerrad** [comment]
Hi there, 

Thanks for reporting. Can you clarify a few things please:

- We'd prefer the _specific version_ noted instead of "Latest version". There's a couple reasons for this: 1. It removes any possible error in reporting latest version of something when it actually isn't (for instance _technically_ the latest version of something would be the most up to date commit in a repo). 2. We can't always get to working on an issue when it's first reported, so the latest released version when we do work on it might be different from when the issue was originally created.

Regarding this specific issue, it's unclear to me exactly what isn't rendering correctly from your code example in the screenshot as it appears some persian text _is rendering_ and some isn't. Would you be able to clarify that a bit more please?

**Comment by hamidrezayazdani** [comment]
Hello.

Yes you are right. I updated the description and specified the versions.

But this is exactly the problem with the fact that Persian is not displayed properly,

When I want to use `$data`, everything is fine. But if you look inside my code, this problem occurs when I want to replace the text myself with the default text taken from the database and WooCommerce (product title, currency symbol, etc.).

Thanks.

**Comment by nerrad** [comment]
Are you sure you are saving the content of the file you have your code in with the right encoding?

**Comment by hamidrezayazdani** [comment]
Yes, of course, this code is in the file of my functions.php, I have used Persian in the whole my theme.

**Comment by hamidrezayazdani** [comment]
Oh, 
I just checked again. 
Seems our version control system changed the coding of the file to ANSI. I apologize for taking your time.
