### ISSUE TITLE
Product block breaks again and again + sometimes not all products/categories are displayed

### ISSUE THREAD

**Issue by nmschaller** [woocommerce/woocommerce-gutenberg-products-block#289]
**Describe the bug + Steps to reproduce**

Bug 1: When I reedit a page that contains the product block, it is broken "contains unexpected elements ... Do you want to restore?". When I click on that, I receive a shortcode with a category number, no preview of the products, and no possibility to change the content of this block. If I want to edit the block, I have to completely start fresh. I am frustrated because I don't know how many times I have done that now; sticking with the old product shortcode naming the category would be easier.

Bug 2: The reason why I have gone back to creating product categories is another bug. In the product block, not all products are displayed in the "search by individual product". So working with categories instead of just selecting single products is already a workaround.

**Comment by nmschaller** [comment]
An addition:

Now, with 10+ product categories, not all product categories are displayed when creating a new product block. So I'm back from the workaround with categories to picking single products. Very sad.

**Comment by nmschaller** [comment]
Just trying to add an individual product to a page using the product block: When I type the letters of how the product name starts, I get: 

"This block has encountered an error and cannot be previewed." Then I have to delete the block, and try again, same result.

Then I try if creating and choosing a category works (the category that I tried to add previously on a different page is still not displayed). It works.

**I discover the bug: there is a maximum of 10 product categories displayed, ascending from A-Z.** So, all categories beyond that are simply not offered in the product block.

Please fix this.

**Comment by LevinMedia** [comment]
Hi @nmschaller [the latest version of the plugin](https://wordpress.org/plugins/woo-gutenberg-products-block/) (1.3.1) includes a new "Products By Category" and a new "Hand Picked Products" block. Both blocks include updated product and category search and selection.

**Comment by nmschaller** [comment]
Hi @LevinMedia, Thanks a lot.
