### ISSUE TITLE
Cash on delivery: not available when enabled for a generic shipping category

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#2892]
**To Reproduce**
1. Create a shipping zone for all the world with a shipping method of 'Flat rate'.
![imatge](https://user-images.githubusercontent.com/3616980/88064319-6b475e80-cb6b-11ea-94b2-c85478274790.png)
2. Enable COD payment method and restrict it to 'Any "Flat rate" method'.
![imatge](https://user-images.githubusercontent.com/3616980/88064410-8914c380-cb6b-11ea-969b-84e47158eb4b.png)
3. Go to the Checkout block and notice COD is not available:
![imatge](https://user-images.githubusercontent.com/3616980/88064557-bbbebc00-cb6b-11ea-9897-200fd9b075ad.png)

**Comment by nerrad** [comment]
I can reproduce. I've set this as a blocker for the 3.0.0 release for now but if it turns out being a difficult thing to fix we can consider releasing 3.0.0 without it.
