### ISSUE TITLE
Create db tables and schema option update run on each admin_init

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce-gutenberg-products-block#2893]
**Describe the bug**
Maybe I've missed something, but it seems to me the check 
https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/main/src/Installer.php#L46
could be changed to >= so that maybe create table and option update does not need to run if db schema is up to date? Now it seems to run on each admin_init, even on heartbeat, which seems unnecessary (from my superficial point of view).

**To Reproduce**

1. Put a breakpoint on [line 50](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/main/src/Installer.php#L50)
2. Browse around admin
3. See it being hit repeatedly

**Expected behavior**
Only run the db update if db schema version is lower than current. 

**WordPress (please complete the following information):**

* Core version: 5.5-beta2-48510 
* WooCommerce version: 4.3
* WooCommerce Blocks version: 2.7.2

**Comment by nerrad** [comment]
Slightly related (still separate issue) #2886 (the slow query wouldn't be as noticeable if this wasn't running on every admin_init).
