### ISSUE TITLE
Checkout: add billing address to the canMakePayment property of the payment methods

### ISSUE THREAD

**Issue by webdados** [woocommerce/woocommerce-gutenberg-products-block#2906]
See #2858 

Payment gateways should have access to the billing address alongside with the shipping address (that is already made available) in the `canMakePayment` property to be able to use those details to determine if the payment method is available or not.

Let's see this scenario: a person from Portugal is buying a gift for a friend in the US. The shipping address will be in the US but he will deactivate the "Use same address for billing" option and enter his Portuguese address on the billing address. I should allow him to use a Portuguese payment gateway.

The `usePaymentMethodRegistration` hook on `use-payment-method-registration.js` that makes `cartTotals`, `cartNeedsShipping`, .... available is related to **payment**, so it should also make available the **billing** address, don't you agree?

**Comment by nerrad** [comment]
Thank for creating the issue @webdados 👍  - I've added it to our backlog of things to investigate/address at some point. I can't give an ETA on this at the moment.

**Comment by webdados** [comment]
@nerrad Any developments on this?

**Comment by nerrad** [comment]
Nothing new, it is still something we will consider adding at some point. Don't be alarmed by the `stale` bot - one of the reasons we added it was to surface issues that we haven't looked at in a while.

**Comment by nerrad** [comment]
I think we should do this before promoting the payment method api more broadly.
