### ISSUE TITLE
Add Product Add-ons Extension support for `Full Cart` block

### ISSUE THREAD

**Issue by zwiesman31** [woocommerce/woocommerce-gutenberg-products-block#2907]
**Is your feature request related to a problem? Please describe.**

Currently, when the `Full Cart` block is used alongside our very popular [Product Add-Ons](https://woocommerce.com/products/product-add-ons/?aff=10486&cid=1131038), the add-on pricing gets shown as a discount, although the cart total is still correct.

Here's an example product with two add-on options: 

![https://d.pr/i/oculBQ](https://d.pr/i/oculBQ+)
Image link: https://d.pr/i/oculBQ

This is what it looks like in the cart when the `Full Cart` block is used: 

![https://d.pr/i/oeJ1SH](https://d.pr/i/oeJ1SH+)
Image link: https://d.pr/i/oeJ1SH

It displays the add-on totals as a discount, even though the total for each product is correct.

**Describe the solution you'd like**
Remove the discount display for the add-on options in the cart when the `Full Cart` block is being used.

**Describe alternatives you've considered**
---

**Additional context**

Reported in 3165028-zen

**Comment by Aljullu** [comment]
I'm pretty sure this was fixed in 3.2.0 (see #2955). Feel free to reopen if you can reproduce it in the latest release.

**Comment by zwiesman31** [comment]
The price issue has been fixed, as the total price in the cart is working: 

![https://d.pr/i/E9evvg](https://d.pr/i/E9evvg+)
Image link: https://d.pr/i/E9evvg

However, it does not show the [Product Add-Ons](https://woocommerce.com/products/product-add-ons/) option(s) that were selected in the cart like the regular cart option does: 

![https://d.pr/i/gccdvB](https://d.pr/i/gccdvB+)
Image link: https://d.pr/i/gccdvB

**Comment by Aljullu** [comment]
Thanks for the details @zwiesman31! Yeah, I closed this issue thinking it was only referring to the discount badge. Regarding showing Product Add-Ons data in the C&C blocks, I opened a new issue only focused on that: #3138.
