### ISSUE TITLE
Update screenshots and examples in wp.org releases

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#2911]
What we have currently has been in place for a while now and it'd be nice to update this.

It would involve:

- picking what to highlight.
- make sure the screenshots are done off of the latest release of WordPress
- changing the screenshots bundled with the plugin
- updating the readme.txt file to point to and describe the new screenshots.

**Comment by haszari** [comment]
@nerrad can you clarify what screenshots/examples you're referring to? Are these displayed on WPORG somewhere – I couldn't find them browsing here: https://wordpress.org/plugins/woo-gutenberg-products-block/

If we are updating screenshots / walkthroughs / docs, we should consider [WCCOM](https://woocommerce.com/products/woocommerce-gutenberg-products-block) and [docs](https://docs.woocommerce.com/document/woocommerce-blocks/) and ensure everything's consistent.

.. Looking at the [product page](https://woocommerce.com/products/woocommerce-gutenberg-products-block) - I see that has editor screenshots, so probably good to refresh 😄

**Comment by nerrad** [comment]
Looks like the wordpress.org screenshots have been removed since the time I created this issue. We could update the WCCom page but I think that's also something the Docs Guild team is on top of thus not something we need to track in this repository. Going to close this issue.
