### ISSUE TITLE
Checkout block links to wp-admin login page, not themed like store front end

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#2918]
**Describe the bug**
If guest checkout option is disabled, the Checkout block has a link prompting the shopper to log in. 

This links to a wp-admin login form, which is not themed, and has no store branding.

Originally reported by `Silver Surfer` in a comment on Woo Blocks release post [here](https://woocommerce.wordpress.com/2020/07/22/woocommerce-blocks-3-0-release-notes/#comment-7151).

**To Reproduce**

1. Go to `WooCommerce > Settings > Accounts`.
2. Require login for checkout by disabling these options: 
   - `Allow customers to place orders without an account` => no
   - `Allow customers to create an account during checkout` => no
3. Save settings. Ensure you have checkout block published on a page.
4. On front end, as anon user (incognito or other browser), add stuff to cart and view checkout block.
5. See login prompt and click it.

**Expected behavior**
Store themed login / signup page.

**Screenshots**
![Screen Shot 2020-07-28 at 8.08.39 AM.png](https://images.zenhubusercontent.com/5ddb3cb39529f10001e618e5/f1a4b5ad-422b-468a-a7fe-881e29f4f3ce)
![Screen Shot 2020-07-28 at 8.09.00 AM.png](https://images.zenhubusercontent.com/5ddb3cb39529f10001e618e5/4281ebd4-44c9-4633-bef8-fb0725461faf)

**Comment by nerrad** [comment]
Ideally this would go to the WooCommerce my-account login endpoint.

**Comment by zdenys** [comment]
Another case on the forums https://wordpress.org/support/topic/login-redirect-to-wp-admin-page/

**Comment by zdenys** [comment]
Another report on the forums https://wordpress.org/support/topic/login-url-in-checkout/

**Comment by nerrad** [comment]
Initial task here is to investigate whether redirecting from the my account page login back to the checkout flow is possible. If so, we can do that as an interim change. If not, then we'll likely just wait until we can implement the ideal solution which is to have the login flow happen in context of the checkout block (modal or otherwise).
