### ISSUE TITLE
Support Stripe payment method title store setting

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#2919]
**Describe the bug**
Stripe Credit Card has a `Title` setting. Currently we're using a hard-coded `Credit Card` title for the tab - it would be good to use the setting. This allows stores to optimise the wording as appropriate, or disambiguate multiple payment methods.

<img width="701" alt="Screen Shot 2020-07-28 at 3 28 01 PM" src="https://user-images.githubusercontent.com/4167300/88615911-f33ae480-d0e6-11ea-8218-93baf3f58c63.png">

**To Reproduce**
1. Set up checkout block.
2. Set up Stripe, enable Stripe Credit Card.
3. Edit settings, change title (or leave default title, which is different from the title in blocks).
4. View checkout block and checkout shortcode on front end - note the shortcode uses the store setting, block doesn't.

<img width="730" alt="Screen Shot 2020-07-28 at 3 26 41 PM" src="https://user-images.githubusercontent.com/4167300/88615857-d1416200-d0e6-11ea-8379-be40601d389f.png">

<img width="863" alt="Screen Shot 2020-07-28 at 3 26 58 PM" src="https://user-images.githubusercontent.com/4167300/88615866-d3a3bc00-d0e6-11ea-8424-8dba08b73857.png">

**Comment by nerrad** [comment]
I think this could be a potential issue for users that are accustomed to being able to configure this. However, I also see the pov where we control this to keep merchant's from potentially shooting themselves in the foot.

Personally I think there's a disconnect if some payment methods allow for modifying the title displayed in the tab and others don't.

cc @LevinMedia  Could you provide some feedback here?

This also appears to be something that would be good to expose as a setting for the payment method when it's moved to the stripe extension.

**Comment by haszari** [comment]
> Personally I think there's a disconnect if some payment methods allow for modifying the title displayed in the tab and others don't.

By the way, the custom title is supported in the other core extensions:

<img width="564" alt="Screen Shot 2020-07-29 at 7 35 48 AM" src="https://user-images.githubusercontent.com/4167300/88712648-27a5b380-d16e-11ea-9656-8c3081033931.png">

**Comment by nerrad** [comment]
> By the way, the custom title is supported in the other core payment methods:

Oh great! Since we're already supporting for the other payment methods then I think we need to do it for Stripe too.
