### ISSUE TITLE
Remove `isLarge` from our buttons

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#2922]
In WP 5.5, `isLarge` is [no longer defined as an attribute](https://github.com/WordPress/gutenberg/pull/23239) for `@wordpress/components/button`, it seems it s[erved no purpose from the beginning](https://github.com/WordPress/gutenberg/issues/16541#issuecomment-645336060), so we can remove it safely as it triggers a console error in 5.5
![image](https://user-images.githubusercontent.com/6165348/88664697-5c196100-d0d5-11ea-93a8-04976341bfed.png)

It triggers an error because `isLarge` is not destructured in Button, causing it to go along with `...additionalProps` and eventually being spread into `button` HTML element.

**Comment by nerrad** [comment]
This has been fixed so can be closed.
