### ISSUE TITLE
Create new block: "Call To Action"

### ISSUE THREAD

**Issue by ryelle** [woocommerce/woocommerce-gutenberg-products-block#293]
This is a tracking issue for a new block in gutenberg, a "Call To Action" block. This block has a background image with overlay, like the cover image block, but will include a title, some content, and a button. This will use InnerBlocks + a template + allowed blocks. The whitelisted blocks should be:

- Heading
- Paragraph
- Button
- Spacer
- Separator

![empty-block](https://user-images.githubusercontent.com/541093/50706476-f9accb80-102b-11e9-8cd5-05e1e0164b99.png)

See p6riRB-3Fa-p2

**Comment by spencerfinnell** [comment]
@ryelle What is the advantage of having this alongside the Featured Product block? It seems like if the  Featured Product block was made a bit more robust (editable title, #368) you could easily recreate this Call to Action block with the existing settings.

**Comment by ryelle** [comment]
Looks like an alternate approach - improving the Cover block - has been started already: https://github.com/WordPress/gutenberg/pull/13822

**Comment by ryelle** [comment]
Closing this, we'll use the core "Cover" block now that it's been updated.
