### ISSUE TITLE
Error when running PHP tests: Error: Call to a member function set_props() on bool

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#2936]
**To Reproduce**
1. Run `npm run phpunit` or see the Travis logs from a PR or commit (see [example](https://github.com/woocommerce/woocommerce-gutenberg-products-block/runs/921550007)).
2. Notice CartItemps.php outputs an error (`Error: Call to a member function set_props() on bool`) several times.

**Expected behavior**
Tests should pass.

Looking at the [main branch history](https://github.com/woocommerce/woocommerce-gutenberg-products-block/commits/main) it looks like this was introduced in commit 523e7af535ce88c28402c71747f38544382f0aa8, from Renovate bot.

**Comment by nerrad** [comment]
This is fixed in #2925

**Comment by Aljullu** [comment]
#2925 has been merged, so closing this issue.
