### ISSUE TITLE
Create new block: "Featured Product"

### ISSUE THREAD

**Issue by ryelle** [woocommerce/woocommerce-gutenberg-products-block#294]
This new block will feature a single product in a style similar to the Call To Action block #293. 

First the user will select a product using the ProductSelector component:

![select-product](https://user-images.githubusercontent.com/541093/50706755-b9018200-102c-11e9-8a5b-41184b48496f.png)

This will fill out a preview with background image, header, description, price, & link:

![product-inserted](https://user-images.githubusercontent.com/541093/50706754-b9018200-102c-11e9-81ef-9ed9138b116d.png)

- It supports wide/full alignment
- It also supports left/right/center text alignment
- The button text and background color can be edited.
- The image can be changed, but only for other images on this product.
- It should be possible to upload a new image to use, and this will be attached to the product itself

See p6riRB-3OP-p2

**Comment by jameskoster** [comment]
> The button is not a separate block, so if we want to add a control for the background color, it'll need to go in the whole block's sidebar items (this can happen before 1.3, but it's not exactly what you requested)

I think it's fine to leave as-is for now.

> The image height is not controllable– it would go from this fixed min-height to the height of the full image, but we don't have the image height from the API. I also don't see a mockup for the custom height slider idea.

If the "Custom" radio is selected the range is revealed;

![range](https://cldup.com/vB7C5Yb4rz-2000x2000.png)

> The user should be able to choose from the images attached to the product.

Thought about this some more. Allowing folks to pick any image or upload a new one should be fine.

**Comment by ryelle** [comment]
I've created issues #319 and #320 to track the remaining tasks here. Any other updates to this block should be new issues.

**Comment by GlennMartin1** [comment]
I think this block should be renamed. 

Since WooCommerce already uses the term "Featured Product" to classify a product, this block should use a term other than "Featured Product".

As is, it's confusing - my instinct is to choose this block if I wish to display WooCommerce Featured Products. 

It would be better to call it "Spotlight" or some other synonym. 

👍
