### ISSUE TITLE
Product Search block (WP 5.5): input field doesn't have border in editor

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#2947]
**To Reproduce**
This issue is only reproducible in WordPress 5.5 or WordPress 5.4 + Gutenberg plugin installed.

1. Create a page and add the Product Search block.
2. Notice the search input doesn't have a border around it in the editor.

**Screenshots**
WP 5.5:
![imatge](https://user-images.githubusercontent.com/3616980/89030358-96cb0580-d330-11ea-9b72-53ed7919f39d.png)

WP 5.4:
![imatge](https://user-images.githubusercontent.com/3616980/89030374-9fbbd700-d330-11ea-82d4-961338790ae7.png)

**Comment by nerrad** [comment]
I think this should be included with the 3.2.0 release so I've labelled it accordingly.

**Comment by senadir** [comment]
I felt like we're using the wrong tool here, we're using a text area when we should be using a text input, simply adding border won't do it, I switched to an input and it matched fine with the overall design without needing to change anything.
