### ISSUE TITLE
Enable transform from "Featured Product" to "Call to Action"

### ISSUE THREAD

**Issue by ryelle** [woocommerce/woocommerce-gutenberg-products-block#295]
Once we have both #293 & #294, we want to be able to transform from Featured Product to the Call to Action block. This will let users customize the block content, disconnected from the product itself. The content in the Featured Product block will be converted into the equivalents in Call to Action.

Note: I think converting to something with InnerBlocks is not possible right now, so we might run into trouble there too 😕

**Comment by mikejolley** [comment]
So summarize our conversation in Slack:

- We don't have metrics to know if this is actually desirable from the perspective of users. No requests we know of have come in.
- Concerns over a dynamic (product data) block becoming static and then potentially becoming stale as data changes with no way to sync that data once it's a cover block.

We can revisit if there are definite indicators that this is something wanted.
