### ISSUE TITLE
All Products Block: Out of Stock products are still being displayed even if the `Hide out of stock items from the catalog` setting is enabled.

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-gutenberg-products-block#2950]
**Describe the bug**

Out of Stock products are still being displayed even if the `Hide out of stock items from the catalog` setting is enabled when using All Products Block. 

I tested the regular WooCommerce functionality and confirmed that it works as intended on the Shop page. If the product is out of stock and `Hide out of stock items from the catalog` setting is enabled, the product is not visible on the Shop page. 

The issue happens when using `All Products` block. 

**To Reproduce**

1. Create a product and mark it as `Out of stock`:

![out1](https://user-images.githubusercontent.com/19143190/89082123-0eae2580-d35b-11ea-98bd-c7212e765ec9.jpg)

2. Navigate to `WooCommerce / Settings / Products / Inventory` and enable `Hide out of stock items from the catalog` setting:

![out2](https://user-images.githubusercontent.com/19143190/89082250-6ba9db80-d35b-11ea-80cd-652e15910bf6.jpg)
 
3. Navigate to the Shop page and confirm that the product you created in step 1 is not visible. 
4. Create a new page and add the `All Products` block on it. Publish the page. 
5. Navigate to the page created and note that the product which is out of stock is visible on that page but shouldn't:

![out3](https://user-images.githubusercontent.com/19143190/89082387-dce98e80-d35b-11ea-86d1-5bacb3aca50b.jpg)

**Expected behavior**

I expected the out of stock product not to be visible on the page when using the `All Products` block to create the page when `Hide out of stock items from the catalog` setting is enabled.  

**Screenshots**

See above. 

**WordPress (please complete the following information):**

* Core version: 5.4.2
* Gutenberg version (if installed): not installed
* WooCommerce version: 4.4 beta1
* WooCommerce Blocks version: not installed (3.0.0 is included in WC 4.4 beta1)
* Site language: English
* Any other plugins installed: Jetpack, WooCommerce Beta Tester

**Desktop (please complete the following information):**

* OS: macOS Catalina 10.15.5
* Browser: Chrome
* Version: 84.0.4147.105 (Official Build) (64-bit)

**Additional context**

This bug was originally reported here https://github.com/woocommerce/woocommerce/issues/27178 but it was reported as a part of another bug which is why I am reporting it separately here for more clarity.

**Comment by nerrad** [comment]
@haszari can you see if you can reproduce this in WooCommerce 4.3? If no, then this is a regression and we'll give this a higher priority and likely do a point release of Woo Blocks 3.1 to include in the pending WooCommerce 4.4 release. If yes, then we might just hold off and do a fix in the plugin only for now (and the fix will land in WooCommerce 4.5 for September).

**Comment by nerrad** [comment]
I have a feeling this isn't a regression. If it isn't, we may need to consider whether this becomes a block level setting for the block or not.

**Comment by haszari** [comment]
I've reproduced this on a local dev build of WooCommerce 4.3.1 based on [`release/4.3` branch](https://github.com/woocommerce/woocommerce/tree/release/4.3), with WooCommerce Blocks disabled and WordPress 5.4.2.

Also reproduced on ephemeral site with production version of WooCommerce 4.3.1.

So I think that confirms this is an existing issue, not a regression. 

> I have a feeling this isn't a regression. If it isn't, we may need to consider whether this becomes a block level setting for the block or not.

That makes sense, though maybe we could respect the core setting as an alternative. Could also implement the block setting and have it default to the core setting.

Also, when out of stock products are shown, we could consider adding an `out of stock` badge or similar to the grid view. cc @LevinMedia

**Comment by nerrad** [comment]
This is related to (and probably any work will also address) #2824

**Comment by nerrad** [comment]
Also related is #2823

**Comment by Magganpice** [comment]
Any simple solution would be greatly appreciated. The blocks are now not usable in shops that don't want to display out of stock products.

**Comment by nerrad** [comment]
Closing as a duplicate of #2824
