### ISSUE TITLE
Consider renaming /assets/js/components/ to /assets/js/editor-components/

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#2954]
All components inside `/assets/js/components/` are exclusively used inside the editor, but the folder naming is a bit conflicting, especially with folders like `/assets/js/base/components/`, we should consider renaming it to something more relevant to the editor.

**Comment by haszari** [comment]
Grabbing this for cooldown, as I'm looking at tidies/easy fixes for our components.

**Comment by haszari** [comment]
I'm going to broaden this a little - look at the naming of both components folders, and the readmes. The goal is that it's easy to decide where a component should live, and what kinds of components are available in each folder. 

This will help us decide which components we might want to migrate to WooCommerce or Gutenberg or elsewhere.

**Comment by haszari** [comment]
Update: based on discussion in #3025, I think it's a great idea to rename this folder/collection to `editor-components`. I'll make the change ..

cc @nerrad @Aljullu @senadir for visibility

**Comment by Aljullu** [comment]
> I think it's a great idea to rename this folder/collection to `editor-components`

+1. Another nice thing of renaming the folder is that directory name will be in line with [class names](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/main/docs/contributors/coding-guidelines.md#naming).
