### ISSUE TITLE
Exclude Mike Jolley from random PR review selection.

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#2956]
Mike is out on sabbatical till November, currently, round-robin will automatically choose him for certain PRs, creating extra notifications for him and taking that automatic review value from someone else, we should see how to exclude him until he's back.

cc @nerrad

**Comment by senadir** [comment]
It looks like we can do this from the team settings, but I don't have access to that page, only Darren has

![image](https://user-images.githubusercontent.com/6165348/89314471-9785d380-d671-11ea-995a-6652d6944d7d.png) ([This article](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/managing-code-review-assignment-for-your-team), step 10).

https://github.com/orgs/woocommerce/teams/rubik/ -> Settings.

**Comment by nerrad** [comment]
I already took care of this :)

**Comment by senadir** [comment]
Also, I think that both Gary and David are notified each `@woocommerce/rubik` is tagged for review, this happens when manually select a reviewer when creating a PR (see this [PR](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2953), I approved on behalf of the team), leaving this option like, we create extra noise for them, hiding actual issues and PR that we need their opinion in.

**Comment by nerrad** [comment]
> Also, I think that both Gary and David are notified each @woocommerce/rubik is tagged for review

Currently, yes, but they are also excluded from the round robin. Notifications for `@woocommerce/rubik` do not go out with the round robin tags (even though the group is initially assigned). Notifications for `@woocommerce/rubik` DO go out if the entire group is explicitly tagged _after_ round robin automation has fired. But we do that rarely so I don't anticipate it's a significant problem at the moment.
