### ISSUE TITLE
All Products block: 'No products' placeholder layout is broken

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#2959]
**To Reproduce**
1. Replace [line 283](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/main/assets/js/blocks/products/all-products/edit.js#L283) from `all-products/edit.js` as follows:
```diff
-if ( ! HAS_PRODUCTS ) {
+if ( true ) {
```
2. Create a new page and add the All Products block.
3. Notice the layout looks completely broken (at least, with WP 5.5).

In addition to that, I think the links should open in a new tab. Currently, they open in the current editor tab.

**Screenshots**
![imatge](https://user-images.githubusercontent.com/3616980/89313028-42998b80-d678-11ea-8b1b-3712c308fc02.png)

**Comment by senadir** [comment]
This is also reproducible in 5.4.2 (and possibly 5.4)
![image](https://user-images.githubusercontent.com/6165348/89318028-25fc5400-d676-11ea-8dde-b9ce9c7d80ec.png)

**Comment by senadir** [comment]
This is fixed as of now.
