### ISSUE TITLE
When switching away from saved payment option to new payment method, pre-select first payment method.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#2963]
While reviewing #2934 I noticed that when a shopper has saved payment methods and selects the new payment method option, the active tab defaults to the same payment method as that attached to the saved payment token.

Example:

![example](https://user-images.githubusercontent.com/1429108/89340312-8a66e580-d66d-11ea-8e56-a5d2105187a8.gif)

In discussion with @haszari  about this, we noticed and considered:

- The active tab corresponds with what is attached to the saved token.
- The above might actually be preferable as the behaviour.

Currently I don't think this is urgent to address as we may want the behaviour to stay as is.  However, I'm documented this for awareness for now.

**Comment by senadir** [comment]
I didn't get the idea behind this? is this the default behavior (like you showed in the image), or do you want it to default to Check Payment?

**Comment by nerrad** [comment]
I think the question here is around what should be the default payment method selected when selecting the new payment option.

- Option one: The first payment method tab according (which is ordered by the merchant).
- Option two: Whatever the payment method for the default _saved_ payment method (which is existing behaviour).

There's likely pros and cons to each. A couple that I can think of immediately:

- The merchant may want Option one because they prefer payments using the payment options they've put in order (so the first tab would be the preferred).
- The shopper already has a saved token for a given payment method, so Option Two might be an intelligent assumption that they'd want to use an alternative card number etc for the same payment method when choosing to pay with a new payment method.

This may be an issue that would be good surfacing for wider discussion. You could also check and see what the current shortcode flows does. 

I'm leaning towards leaving things as is for now, and then just addressing it if we get good feedback on why the current approach isn't favorable.
