### ISSUE TITLE
Improve name of orderNotes flag for checkout-state provider.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#2982]
While reviewing #2851, I left some feedback on choice of variable names for the account creation flag and noticed there's a similar problem with the naming around the `orderNotes` flag (added in #2877).

This issue is to address the `orderNotes` flag naming. It should better reflect that the property is a boolean. Maybe something like `canLeaveOrderNotes`. I realize it's more verbose, but it's immediately clear when parsing code it's purpose as opposed to `orderNotes` which on first glance I would assume is a list/collection of orderNotes.

**Comment by haszari** [comment]
> This issue is to address the orderNotes flag naming. It should better reflect that the property is a boolean. Maybe something like canLeaveOrderNotes. I realize it's more verbose, but it's immediately clear when parsing code it's purpose as opposed to orderNotes which on first glance I would assume is a list/collection of orderNotes.

FYI @nerrad  - I think this `orderNotes` state is text; either empty (no order note) or containing user-supplied note text. In the API response it's serialised as `customer_note`. I agree though it maybe could be clearer and more consistent throughout.

<img width="698" alt="Screen Shot 2020-08-10 at 5 24 37 PM" src="https://user-images.githubusercontent.com/4167300/89754093-956abb80-db2e-11ea-8d02-631564a9c49b.png">

There is a boolean `showOrderNotes` block attribute, controlling whether the note UI is available to shopper. This might be clearer as `allowOrderNotes`.

**Comment by nerrad** [comment]
OHHH, I totally misunderstood then, I should have clued in from the type on the default that it was not a boolean flag 🤦 . Some good suggestions in your comment about renaming but it's not as critical as what I originally thought with flags. So I'll close the issue.
