### ISSUE TITLE
Checkout: Order Summary / Coupon panel heading (disclosure triangle) background is white in Twenty Seventeen dark mode

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#2986]
## Describe the bug
Twenty Seventeen has a dark colour scheme. When this is active, there's a white box around `Order Summary` and `Coupon Code?`:

<img width="1124" alt="Screen Shot 2020-08-10 at 3 20 03 PM" src="https://user-images.githubusercontent.com/4167300/89749771-44060080-db1d-11ea-94d1-4deca692b3e1.png">

## To reproduce
1. Set up a page with Checkout block.
2. Install & activate `Twenty Seventeen` theme (observed issue with `Version: 2.3`).
4. `Customizer > Colors > Color Scheme: Dark` and publish changes.
3. On front end, add stuff to cart and view checkout.
4. See white boxes.

## Expected behavior
No white boxes - these should look like regular headings on page background colour.

## Context
- WordPress v5.4.2

This might need to be fixed in core/Twenty Seventeen, reporting here as a first step.

**Comment by senadir** [comment]
This should be fixed in #2981
