### ISSUE TITLE
JS error when selecting an address with no available shipping options

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#2987]
## To reproduce
1. Add products to your cart that need shipping.
2. Go to the Checkout block and select an address without any shipping option available.
3. Look at the console and you will notice there is a JS error:
```
Uncaught (in promise) Error: Problem with payment method initialization: can't access property "includes", selectedMethod is undefined
```

## Expected behavior
There shouldn't be a JS error.

## Screenshots
![imatge](https://user-images.githubusercontent.com/3616980/89792116-6b140080-db24-11ea-8fb9-6289c1ed3d21.png)

**Comment by senadir** [comment]
This issue[ is caused by COD](https://github.com/woocommerce/woocommerce-gutenberg-products-block//blob/6d08ae277971ce9a6f9070de1ba22114642fdeb2/assets/js/payment-method-extensions/payment-methods/cod/index.js#L65) so you need to have that enabled to reproduce this.
