### ISSUE TITLE
Update our min required WP version to WordPress 5.3 and update .travis.yml config for tests.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#2995]
[WordPress 5.5](https://wordpress.org/news/2020/08/eckstine/) has shipped. With our L-2 support policy, that means the next version of WooCommerce Blocks will require a minimum of WordPress 5.3 (instead of 5.2). The following needs updated:

- README.md?
- readme.txt
- woocommerce-gutenberg-products-block.php
- .travis.yml (bump what versions of WP are tested against).
- drop legacy builds (and any explicit WP version checks).

Re legacy builds and WP version checks, it's probably good to leave the logic in place but just don't build the legacy builds, that way we can resume legacy builds if needed for progressive enhancement.

**Comment by haszari** [comment]
Related to this, we also have a versions/requirements section in various docs, including:

- [WCCOM product page](https://woocommerce.com/products/woocommerce-gutenberg-products-block/)
- [WooCommerce blocks main documentation page](https://docs.woocommerce.com/document/woocommerce-blocks/)

These should be updated whenever our min WP version (or other reqs) changes.

As part of this issue, perhaps we should add a step/reminder to the release process to keep these pages fresh ✨
