### ISSUE TITLE
Fix incorrect schema for `ProductReviewSchema` on `date-time` types

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#3005]
WordPress 5.5 introduces a [doing_it_wrong notice for schema types that are non-standard](https://make.wordpress.org/core/2020/07/16/rest-api-parameter-json-schema-changes-in-wordpress-5-5/) (i.e `date-time`) types. Currently this doesn't affect us significantly because the notice only applies to put/post requests. However we do have [one instance of this in our REST endpoints](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/a404e5b24814240f15e50aa4f983b787bb9b36f1/src/StoreApi/Schemas/ProductReviewSchema.php#L52-L69). The correct implementation would be to have `{ type: 'string', format: 'date-time' }`. 

This isn't an urgent fix needed, but still trivial and should be done sooner vs later.

**Comment by haszari** [comment]
Grabbing this so it's out of the way & done :)
