### ISSUE TITLE
Fix various styling issues

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#3006]
This is a collection of styling issues I found recently:

### Checkbox mark is misaligned on TwentyTwenty and TwentySeventeen

<img width="297" alt="Screen Shot 2020-08-13 at 3 50 17 PM" src="https://user-images.githubusercontent.com/6165348/90151654-dce78680-dd7e-11ea-8af6-d7844f963bd8.png">

### Quantity selector controls have an underline in TwentyTwenty

<img width="141" alt="Screen Shot 2020-08-13 at 3 50 47 PM" src="https://user-images.githubusercontent.com/6165348/90151894-21732200-dd7f-11ea-97e9-46283d461778.png">

### Buttons have a gray background on hover and click in TwentySeventeen dark mode
![image](https://user-images.githubusercontent.com/6165348/90152029-436ca480-dd7f-11ea-9038-142638636ae8.png)
![image](https://user-images.githubusercontent.com/6165348/90152208-7b73e780-dd7f-11ea-9a6b-a0e0b37d0e2c.png)

### Regular and Sale price are misaligned 
![image](https://user-images.githubusercontent.com/6165348/90152105-5a12fb80-dd7f-11ea-8084-e1e58e9d4bed.png)

### Select-control is misshaped in Editor view in all themes
![image](https://user-images.githubusercontent.com/6165348/90152422-b4ac5780-dd7f-11ea-9a34-c1c4ad96a9da.png)

**Comment by Aljullu** [comment]
> Regular and Sale price are misaligned

This one was fixed in #3047.

**Comment by nerrad** [comment]
@senadir at some point can you take some time to break out these things, verify if they are still valid, and put into individual issues. The current format makes it difficult to scan titles to work out what needs addressed and the full content of the issue needs to be parsed (along with reading through the comment log to see if any pull requests fixed any of these).

Thanks!
