### ISSUE TITLE
Bump Jetpack autoloader version

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#3008]
Jetpack is currently [working on a new version of the autoloader package](https://github.com/Automattic/jetpack/pull/16755) we use. This is potentially a blocker to the next release of the WooCommerce blocks package and there's some coordination internally around this.

This issue is created so we can track this as a part of the 3.2.0 release.

**Comment by nerrad** [comment]
From internal discussions, this is not a blocker for 3.2.0, so it can be bumped if the JetPack autoloader update is not available yet.

**Comment by Aljullu** [comment]
@nerrad was this closed in #2847?

**Comment by nerrad** [comment]
Yup!
