### ISSUE TITLE
Improve storybook coverage for general-purpose components

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#3031]
Adding some storybook coverage for some of our more general-purpose components. As well as improving our storybook coverage, the goal here is to help decide which components might be good candidates for migrating to `@woocommerce/components` or `@wordpress/components`.

### Component docs/readme, and relationship to other code bases
I also like the idea of using Storybook for more documentation about the components, e.g. when they relate to a Gutenberg component. So might try prototyping that alongside writing stories.

Some examples:

- The added value in our `Button` over gutenberg `Button`. I think our component is a `Button` with an optional spinner mode, so maybe clearer to name `SpinnerButton`. 
- Components that are a simple wrapper (of Gutenberg or Reakit) with classes so we can style for our needs. These are unlikely to be worth sharing for reuse.
- `ToggleButtonControl` - I recall this being needed as a temporary fix until a Gutenberg button got more support for a toggle state. 

### Note - Storybook has changed, we may want to upgrade before writing more stories
Storybook 6 has a different api, we're on 5. 

See related issue: #3028

## PRs / components (feel free to add items, tick box when PR merged)
- [ ] `Chip` #3029 @haszari 
- [ ] `CheckboxControl` #3030 @haszari

**Comment by haszari** [comment]
All welcome! 

- Add checkboxes to list for components that need stories.
- If you start working on one or more stories, add your name to that line.
- Link the PR when it's up (push a draft PR early!)
- Check the box when PR is merged ✅

**Comment by nerrad** [comment]
I'm going to close this issue because we're not really doing a focused sprint/work on adding stories but rather just including it as continued ongoing work across cooldowns and/or new work.
