### ISSUE TITLE
Checkout Block Feature Request: Add option for submitting order without payment details.

### ISSUE THREAD

**Issue by johann75sch** [woocommerce/woocommerce-gutenberg-products-block#3042]
## What do you like about the Cart & Checkout blocks?
The look & feel is much nicer.

## What do you think is missing from the Cart & Checkout blocks?
What is more important about checkout for me, possibility to place an order with contact details before a payment to be able to reach out to the client in case of an uncompleted payment.

**Comment by nerrad** [comment]
Thanks for leaving feedback! Is this something that is available in the shortcode checkout flow that’s a part of WooCommerce core now?

Offhand, one way I could see this being implemented is a new payment method for “Arrange payment later” that could be offered by merchants as an option for shoppers that want to arrange to pay with the merchant vs pay via another payment method.

I don’t see this as something we’d offer natively with the checkout flow.

**Comment by johann75sch** [comment]
Hi Darren,
 
You know like the most Shopify shops this days, the checkout will be arranged in 2 — 3 steps. The main idea behind is, to have a Process to Checkout or Proceed to Payment button after entering the billing or shipping details and before displaying credit card payment form to capture buyer’s data like the email, mobile and the products they are interested in. In case if they did not enter the payment details thereafter, the order would be still saved as uncompleted so that you could target the buyer to encourage to complete the purchase.
 
Regards
Johann   
>Понедельник, 24 августа 2020, 16:51 +03:00 от Darren Ethier <notifications@github.com>:
> 
> 
>Thanks for leaving feedback! Is this something that is available in the shortcode checkout flow that’s a part of WooCommerce core now?
>Offhand, one way I could see this being implemented is a new payment method for “Arrange payment later” that could be offered by merchants as an option for shoppers that want to arrange to pay with the merchant vs pay via another payment method.
>I don’t see this as something we’d offer natively with the checkout flow.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С уважением,
Johann Schiffmacher
johann75@mail.ru
