### ISSUE TITLE
Stripe Payment Gateway not showing up in checkout block

### ISSUE THREAD

**Issue by cdrake118** [woocommerce/woocommerce-gutenberg-products-block#3061]
We are using the Stripe Payment Gateway CC.  However, on checkout, it is still appearing as "There are no payment methods available. This may be an error on our side. Please contact us if you need any help placing your order."

<img width="1061" alt="Screen Shot 2020-08-26 at 9 23 14 PM" src="https://user-images.githubusercontent.com/3526134/91372750-7df42980-e7e2-11ea-9273-134fd724331d.png">

<img width="705" alt="Screen Shot 2020-08-26 at 9 25 26 PM" src="https://user-images.githubusercontent.com/3526134/91372814-b0058b80-e7e2-11ea-81e1-51bfb7656bae.png">

The text is also displaying in white by default.

https://heyhoneybeecompany.com/checkout/

**Comment by cdrake118** [comment]
Paypal does display if enabled.

**Comment by haszari** [comment]
Hi @cdrake118  - thanks for reporting this!

Can you confirm the exact Stripe extension you are using on your store? That looks similar to the [supported extension](https://woocommerce.com/products/stripe/), but slightly different. This is what the official Stripe extension looks like in my store (in `Dashboard > Settings > Payments`):

<img width="1200" alt="Screen Shot 2020-08-27 at 4 41 48 PM" src="https://user-images.githubusercontent.com/4167300/91385119-4b027200-e884-11ea-858b-430b71438a5e.png">

There's a bit more info about which payment extensions are supported on [this page](https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/).

**Comment by nerrad** [comment]
Since we haven't heard a response in over a week, I'm going to close this, but please feel free to update this issue with more information @cdrake118 if you have any.
