### ISSUE TITLE
Cart and Checkout Blocks: More customization options.

### ISSUE THREAD

**Issue by kyaniheessels** [woocommerce/woocommerce-gutenberg-products-block#3063]
## What do you like about the Cart & Checkout blocks?
- Wysiwyg is great (for example if I want the "Add a note" option on or off.

## What do you think is missing from the Cart & Checkout blocks?
- More customization options where you can change every text string in the block to your liking, and having more choice in terms of what fields to switch on and off, like the ability to use a coupon.

**Comment by nerrad** [comment]
Thanks for leaving feedback on the blocks!

**Comment by nerrad** [comment]
Just noting that there's nothing specifically actionable for this issue and we we are currently working on making the blocks more extensible (along with considering requests like yours here). As a result I'm going to close this but it does not mean your requests are being ignored or aren't heard.
