### ISSUE TITLE
Change registerPaymentMethod to accept a config object instead of a PaymentMethodConfig instance

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#3064]
In our payment method registration API, `registerPaymentMethod` takes a callback that passes `PaymentMethodConfig` class and expects you to return a new instance of it with your config.

```js
const cashOnDeliveryPaymentMethod = {
	name: PAYMENT_METHOD_NAME,
	label: <Label />,
	content: <Content />,
	edit: <Content />,
	icons: null,
	canMakePayment,
	ariaLabel: label,
};
// Config is PaymentMethodConfig
registerPaymentMethod(
	( Config ) => new Config( cashOnDeliveryPaymentMethod )
);
```

But upon further digging, @nerrad concluded that we don't need to expose `PaymentMethodConfig` to third party integrations, therefor exposing more implementation detail. We can accept a config object and handle the class initiation inside `registerPaymentMethod`.

```js
const cashOnDeliveryPaymentMethod = {
	name: PAYMENT_METHOD_NAME,
	label: <Label />,
	content: <Content />,
	edit: <Content />,
	icons: null,
	canMakePayment,
	ariaLabel: label,
};

registerPaymentMethod( cashOnDeliveryPaymentMethod );
```

So, to do that, we have several steps:

- [ ] Deprecate the old method with a notice that people should pass an object instead.
- [x] Provide a fallback inside `registerPaymentMethod` to accept either an object or a callback.
- [x] Update our internal payment methods to pass an object instead.
- [x] Update the integration docs for third-party developers.
- [x] Do the same for express payment methods.
- [ ] Include a dev-note for this when we ship those changes.

**Comment by nerrad** [comment]
Thanks for creating this issue Nadir, and for asking such great probing questions that got me thinking about this more in the first place!

**Comment by haszari** [comment]
@Aljullu  are you in progress on this? I might pick it up today, looking for something different to do 🦊

**Comment by Aljullu** [comment]
Feel free to pick it up @haszari. I started investigating it yesterday, but didn't get far because other things appeared. Unassigning it from me.
