### ISSUE TITLE
Rename WooCommerce Product Blocks to WooCommerce Blocks

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#3066]
When the project was first created, the focus was on product blocks, but in the time since this project ecompasses (and will encompass) more than just product blocks. So the purpose of this issue is to rename the project to a more simplified "WooCommerce Blocks".

What does this require:

* [x] Changing the name of the plugin wherever it is referenced in code and documents.
* [x] Updating name of plugin in WooCommerce.com.
* [ ] Changing the slug for the github repo (🚨This could be dangerous and we'll need to make sure it won't break anything before doing).
* [x] Revisit [this paragraph in the README.md for the repo](https://github.com/woocommerce/woocommerce-gutenberg-products-block#vision-for-the-feature) and update it to reflect the current status of the project.
* We **can't** change the slug for the wp.org repo (just including this to head off potential questions).

**Comment by haszari** [comment]
Most of this was already done/started. Tidied up a few things in this PR: https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3567

I've left the slugs (github repo, WCCOM url) for follow up, they should only be changed with care (if safe to do so!).
