### ISSUE TITLE
Ensure `woocommerce` is listed as a contributor for WordPress.org

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#3067]
This just requires adding `woocommerce` to the `contributors` list in the `readme.txt` file. 

Why? This has been requested by project leads.

**Comment by haszari** [comment]
I'll do this as part of 3.3.0 :)

**Comment by haszari** [comment]
Fixed in 8ce79d9ed149f021728151609097cd7cd3d6b5c9 💜
