### ISSUE TITLE
Seedlet: All Products block "Align last block" option not working

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#3079]
## Describe the bug
In `All Products` block there is an `Align last block` option. This allows merchant to set up product grid so all the buy buttons are aligned (for example).

In Seedlet theme, the option doesn't seem to work:

<img width="910" alt="Screen Shot 2020-08-31 at 4 52 52 PM" src="https://user-images.githubusercontent.com/4167300/91684129-a72e0480-ebaa-11ea-8dde-357d9b62238c.png">

Observed while preparing 3.3.0 release (when setting up test store).

## To reproduce
0. Add some products to store.
1. Install & activate Seedlet theme.
2. Set up a page with all products, activate `Align last block`, publish.
3. View page on front end.

## Expected behavior
Nicely aligned buttons. For example, this is what it looks like in Twenty Twenty:

<img width="967" alt="Screen Shot 2020-08-31 at 5 04 08 PM" src="https://user-images.githubusercontent.com/4167300/91684555-fd4f7780-ebab-11ea-9b3f-6a9431459c63.png">

### WordPress (please complete the following information):
* Core version: 5.5
* Gutenberg version (if installed): n/a
* WooCommerce version: 4.4.1
* WooCommerce Blocks version: n/a (included in core)

**Comment by nerrad** [comment]
Just noting this may be out of date (and has since been fixed). Also, it does sound like something that should be fixed at the theme level.
