### ISSUE TITLE
Cart block: original (undiscounted) prices render without strikethrough on Seedlet theme

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#3080]
## Describe the bug
In the Cart block, if products are discounted, the original price is shown with strikethrough formatting. On Seedlet theme, it's rendering as normal. This could be confusing 😕 

<img width="873" alt="Screen Shot 2020-08-31 at 5 15 07 PM" src="https://user-images.githubusercontent.com/4167300/91685306-135e3780-ebae-11ea-8027-0175fec9305d.png">

Note that original prices are displaying correctly in other places, e.g. All Products block.

Observed while testing 3.3.0 release.

## To reproduce
1. Add some products to store. Ensure some products have sale prices.
2. Install & activate Seedlet theme.
1. Set up a page with cart block.
1. On front end, add discounted stuff to cart and view cart. 
3. Notice original prices are not strikethrough.

## Expected behavior
Original prices for discounted products should always be displayed with strikethrough, so it's clear what price shopper will pay.

**Comment by nerrad** [comment]
Rua, can you see if this is fixed by #3089? If it isn't, we can just leave in the pipeline I assigned to for now.

**Comment by haszari** [comment]
> Rua, can you see if this is fixed by #3089? If it isn't, we can just leave in the pipeline I assigned to for now.

Nice one @senadir! It does fix it: 

<img width="736" alt="Screen Shot 2020-09-01 at 4 16 52 PM" src="https://user-images.githubusercontent.com/4167300/91794211-9ba41180-ec6e-11ea-83dc-84b33e418802.png">

**Comment by Aljullu** [comment]
Just tested and it looks like #3065 has fixed this.
