### ISSUE TITLE
Double "Add to cart" notices when add to cart via url parameter (possible regression of #2854)

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#3081]
## Describe the bug
I'm seeing two notices when I use a custom add to cart url, for example `/cart/?add-to-cart=31`. Examples:

<img width="1087" alt="Screen Shot 2020-08-31 at 5 30 46 PM" src="https://user-images.githubusercontent.com/4167300/91686037-50c3c480-ebb0-11ea-8735-71010d691a09.png">
<img width="1220" alt="Screen Shot 2020-08-31 at 5 31 47 PM" src="https://user-images.githubusercontent.com/4167300/91686040-515c5b00-ebb0-11ea-8746-6674e48ca4aa.png">

Noticed this when release testing 3.3.0.

FYI @Aljullu 

## To reproduce
- Configure your store so cart & checkout blocks are used on respective pages.
- Set a `Sold individually` option on a product:
  - Edit a product. Note down the product ID.
  - Scroll down to `Product data` box, select `Inventory` tab.
  - Enable `Sold individually` option, and click `Update` to save changes to the product.
- Add a button block linking to `/cart/?add-to-cart=19`, simulating a "Buy" button on a landing page for the product.
- On front end, click the button.

Even when the cart is empty, I get 2x notices.

Button example, in a `Cover` block: 
<img width="784" alt="Screen Shot 2020-08-31 at 5 44 08 PM" src="https://user-images.githubusercontent.com/4167300/91686535-9af97580-ebb1-11ea-9464-d8117e0fd2f1.png">

## Expected behavior
One notice ..

## Additional context
I suspect this is a cookie/state issue with my browser session, but reporting in case it's a real issue. Either way I don't think this is is a high priority or a release blocker.

**Comment by nerrad** [comment]
I'm not able to reproduce this. When I try, I only get one notice - it's possible this might have been fixed since it was first reported or as noted an issue with cookie/state during testing.
