### ISSUE TITLE
'Already have an account' text overflows 'Contact info' title

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#3082]
## To reproduce
1. Go to the Checkout block with a small viewport.
2. Notice how the 'Already have an account? Log in.' text overflows the 'Contact info' title.

## Expected behavior
Texts shouldn't collide.

## Screenshots
![imatge](https://user-images.githubusercontent.com/3616980/91695569-a7a8aa00-eb6e-11ea-8a9f-7ce3d63176e2.png)

**Comment by opr** [comment]
Hi @LevinMedia do you have any thoughts on where we should position this text when the viewport is too small to display it all on one line? My initial thought was to drop it below the "Contact information" title but would welcome any other thoughts you have.

**Comment by LevinMedia** [comment]
Yep, that's correct - lets drop it below the "Contact information" like so: 

<img width="463" alt="Screen Shot 2020-11-17 at 9 01 33 AM" src="https://user-images.githubusercontent.com/4500952/99421706-89239680-28b3-11eb-9dd4-a7b504e48854.png">
