### ISSUE TITLE
Twenty Twenty: All Products product image "Sale" badge left-align option renders full-width 

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#3097]
## Describe the bug
In Twenty Twenty, the left align option for the Product Image `SALE` badge renders as full-width on front end. The other align options work correctly, as does editor preview.

<img width="880" alt="Screen Shot 2020-09-02 at 11 54 32 AM" src="https://user-images.githubusercontent.com/4167300/91917208-66053400-ed13-11ea-8c8f-76a001e445a5.png">

## To reproduce
- Add an all products block (or edit existing)
- Click the Edit (pencil icon) button to edit the layout of products within the grid.
- Select the Product Image block, or add it if needed.
- In the settings inspector, select `Sale Badge Alignment == Left`.
- Click Done to exit layout edit.
- Publish the page or save changes.
- View page on front end.

## Expected behavior
Badge should be small and left-aligned, mirror of right-align option, and consistent with editor preview.

### WordPress (please complete the following information):
* Core version: 5.5.
* Gutenberg version (if installed): n/a
* Twenty Twenty version: 1.5
* WooCommerce version: 4.4.1
* WooCommerce Blocks version: 3.3.0-dev (test release build from #3077)
* Any other plugins installed: Jetpack, Akismet, WooCommerce Stripe Gateway

### Desktop (please complete the following information):
* OS: [e.g. macOS, Windows]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):
* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Comment by nerrad** [comment]
Can still reproduce.
