### ISSUE TITLE
much better than before, but there is a problem.

### ISSUE THREAD

**Issue by Anglie-crea** [woocommerce/woocommerce-gutenberg-products-block#3102]
# What do you like about the Cart & Checkout blocks?
looks much better than traditional.

## What do you think is missing from the Cart & Checkout blocks?
They could add the option of being able to move the order of the blocks, add typography to customize.

However, I have been testing it and at the end of the purchase it does not redirect me to the thank you or purchase page, I do not know why it takes me to a blank page.

If they know of something I would appreciate it very much.

**Comment by aheckler** [comment]
This may have been posted by the same person as this thread:

https://wordpress.org/support/topic/me-gusta-mucho-pero-2/?view=all

If I can confirm, I'll close this in favor of using the forums.

**Comment by aheckler** [comment]
Solved in forum thread.

**Comment by nerrad** [comment]
Thanks for the follow-up, I'll go ahead and close.
