### ISSUE TITLE
Css Modifications: Delete from cart button on mobile, Apply Coupon Button, Product Add-ons

### ISSUE THREAD

**Issue by couselm** [woocommerce/woocommerce-gutenberg-products-block#3105]
## Delete from cart button on mobile blocks cart text.  Floated to right of screen to fix.
svg {float:right;}

## Apply Coupon Button Blocks input field. Flex-shink value changed from 0 to 10

.wc-block-components-totals-coupon__form .wc-block-components-totals-coupon__button {
    flex-shrink: 10;
}

## What do you like about the Cart & Checkout blocks?
Overall cleaner look. 

## What do you think is missing from the Cart & Checkout blocks?

Bug Fix request.  Product Variations and Add-ons do not display on Cart and Check-Out blocks.  Please add product add-on info after product meta.

**Comment by nerrad** [comment]
Hi there @couselm 👋 

Thanks for taking time to leave some feedback here. I want to make sure I'm understanding your requests correctly. It sounds like you have three requests here:

- A request related to the delete from cart button styling on mobile. Will you expand on this more please? On the surface this looks more like a theme customization issue as opposed to something we need to distribute to all users of the blocks.
- A request related to the apply coupon button blocks input. Again this looks more like a theme customization issue as opposed to something we need to distribute to all users of the blocks.

For the above two requests, before we consider adding your suggestions to the css code we do need more details around what problem you are wanting to solve and why.

The third request looks like it's related to the Product Add-ons extension. Just to be clear, is it [this extension in the WooCommerce marketplace](https://woocommerce.com/products/product-add-ons)? 

It is **expected** that a number of extensions won't appear to work yet with the new Cart and Checkout blocks as we still have to build extensibility points for extension authors to hook into (or extension authors need to integrate). We do take all these reports though as a signal of what we may need to prioritize on for extensibility so thanks for your submission.

**Comment by nerrad** [comment]
Without a response to the clarification questions, this issue isn't actionable.
