### ISSUE TITLE
Storefront child themes issues with Cart and Checkout blocks

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#3110]
I tested all themes listed in the [Storefront Themes category in WooCommerce.com](https://woocommerce.com/product-category/themes/storefront-child-theme-themes/) with the Cart and Checkout blocks. Below is a list of issues I detected. Notice some of this issues might be in WC Blocks, some others in Storefront and some others in the child theme. However, I'm listing all of them here so we can investigate it further and open issues in the relevant repos.

I think, some of the themes listed in that page are not child themes of Storefront. So in the list below I split them between the ones that are Storefront child themes (they have some minor issues) and other themes (the experience is mostly broken).

### Arcade
_(I couldn't find any issue)_

### Bistro
_(I couldn't find any issue)_

### Bookshop
* Panel titles and selects have a green background.
![imatge](https://user-images.githubusercontent.com/3616980/92102380-d2993500-edde-11ea-9978-8d2e671b22ca.png)

### Boutique
_(I couldn't find any issue)_

### Deli
* Order summary quantity badge is not readable.
![imatge](https://user-images.githubusercontent.com/3616980/92101305-39b5ea00-eddd-11ea-9fa4-00bf895c6f32.png)
* Text input and button don't have the same height. (Similar issue is affecting Block Shop)
![imatge](https://user-images.githubusercontent.com/3616980/92101373-50f4d780-eddd-11ea-951a-16ac1837ff3f.png)
* Proceed to Checkout button in Cart has a weird brown background. (Similar issue is affecting Arcade, Block Shop and ToyShop)
![imatge](https://user-images.githubusercontent.com/3616980/92101446-6bc74c00-eddd-11ea-8599-6112327e3bc9.png)

### Galleria
* Panel titles have a border on hover that causes the content to jump.
![Peek 2020-09-03 12-04](https://user-images.githubusercontent.com/3616980/92101590-a204cb80-eddd-11ea-88bf-2709f07434d3.gif)

### Homestore
* Quantity input overflows in mobile.
![imatge](https://user-images.githubusercontent.com/3616980/92101769-e1331c80-eddd-11ea-818a-1176b9d879bb.png)

### Hotel
* Proceed to Checkout button has no background/border.
![imatge](https://user-images.githubusercontent.com/3616980/92124300-e738f580-edfd-11ea-9fd1-b4f1fdc4003f.png)
* Cart: there is no padding between table contents and border.
![imatge](https://user-images.githubusercontent.com/3616980/92124407-0899e180-edfe-11ea-9c8b-5898a3b4fc53.png)

### Outlet
* Buttons are not legible.
![imatge](https://user-images.githubusercontent.com/3616980/92102023-4981fe00-edde-11ea-9aab-bc3f6130b095.png)

### Petshop
_(I couldn't find any issue)_

### Pharmacy
* Notices overflow page title.
![imatge](https://user-images.githubusercontent.com/3616980/92102546-0b390e80-eddf-11ea-9e0a-8323f933afb8.png)

### ProShop
* Checkout: Card icons overflow checkbox label. (This issue is happening in several other themes)
![imatge](https://user-images.githubusercontent.com/3616980/92102221-9c5bb580-edde-11ea-9982-3233f6f6b9b8.png)

### Stationery
_(I couldn't find any issue)_

### ToyShop
* Cart summary and Checkout order summary overflow the available space in narrow viewports.
![imatge](https://user-images.githubusercontent.com/3616980/92123378-db006880-edfc-11ea-88d0-69f2e12bf0e6.png)

### Artisan and Threads
(Both themes have very similar issues, so listing them together):
* Cart and Checkout: content breaks in two rows. (#3111)
![imatge](https://user-images.githubusercontent.com/3616980/92125478-5fec8180-edff-11ea-8ce8-122deec957b6.png)
* Select label is not inline.
![imatge](https://user-images.githubusercontent.com/3616980/92125612-814d6d80-edff-11ea-9d16-2a2cd005b3cd.png)
* Coupon chips are too big.
![imatge](https://user-images.githubusercontent.com/3616980/92125653-8ca09900-edff-11ea-8022-b72d5dfd5688.png)
* Inputs and checkboxes are too big.
![imatge](https://user-images.githubusercontent.com/3616980/92125711-99bd8800-edff-11ea-9c92-4167311e36d0.png)
* Coupon code input and button are not aligned.
![imatge](https://user-images.githubusercontent.com/3616980/92125774-ad68ee80-edff-11ea-8692-dc88837c1ff3.png)
* Threads: cart table has a background.
![imatge](https://user-images.githubusercontent.com/3616980/92125996-f0c35d00-edff-11ea-97e0-672d3e1b457b.png)
* Threads: step number breaks in a separate line from number.
![imatge](https://user-images.githubusercontent.com/3616980/92126048-0173d300-ee00-11ea-991d-c9e67f09c9fc.png)

* There are some bugs in the checkout page when hovering over different elements.
![Artisan](https://user-images.githubusercontent.com/69914963/107657696-277d8900-6c64-11eb-8f2d-4265f2df60bb.gif)

* Wrong alignment on the "Proceed to checkout" button
![Frame 157](https://user-images.githubusercontent.com/69914963/107676544-04f56b00-6c78-11eb-9d04-32aff3bb9b71.png)

* Wrong alignment between the radio buttons and the payment titles.
![Frame 162](https://user-images.githubusercontent.com/69914963/107676590-13438700-6c78-11eb-859a-f9d1f40ed640.png)

* Wrong alignment in the checkout form.
![Frame 163](https://user-images.githubusercontent.com/69914963/107676769-471eac80-6c78-11eb-957b-6ca09b83efca.png)

### Block Shop
* Payment methods section layout is broken.
![imatge](https://user-images.githubusercontent.com/3616980/92124735-7219f000-edfe-11ea-8875-4649f34d4de8.png)
* Proceed to Checkout button is not visible.
![imatge](https://user-images.githubusercontent.com/3616980/92124792-8362fc80-edfe-11ea-93aa-d3d66ab31add.png)
* Product image has underground.
![imatge](https://user-images.githubusercontent.com/3616980/92124846-91b11880-edfe-11ea-9f0d-6c9c29640b7c.png)
* No margin between product name and badges.
![imatge](https://user-images.githubusercontent.com/3616980/92124902-a55c7f00-edfe-11ea-8791-2572b11d5031.png)
* Form fields are broken in several lines.
![imatge](https://user-images.githubusercontent.com/3616980/92124973-bb6a3f80-edfe-11ea-92fb-8897e9cd7fc0.png)
* Wrong alignment on the  "Apply coupon" button.
![Frame 171](https://user-images.githubusercontent.com/69914963/107676836-5867b900-6c78-11eb-83b6-34bab7b732d1.png)

### Fifth Avenue
* Accessibility texts are visible in prices.
![imatge](https://user-images.githubusercontent.com/3616980/92126427-7515e000-ee00-11ea-8a3b-536fb8770ee4.png)
* 'Add a note to your order' is not vertically aligned.
![imatge](https://user-images.githubusercontent.com/3616980/92126532-95459f00-ee00-11ea-9ec5-513d8d058309.png)

### Matthew
* CSS is not loading at all.
![imatge](https://user-images.githubusercontent.com/3616980/92127055-37fe1d80-ee01-11ea-814c-61eb8b7373c0.png)

* Check icon is not legible.
![Frame 212](https://user-images.githubusercontent.com/69914963/107656397-e042c880-6c62-11eb-9daf-0319e59a826d.png)

We should change it to white.

* Wrong alignment on the  product picture and the price.
![Frame 179](https://user-images.githubusercontent.com/69914963/107676977-7fbe8600-6c78-11eb-9491-2518c7c846e4.png)

**Comment by ghost** [comment]
Update: I've added some new issues to the "other themes" category.

**Comment by nerrad** [comment]
I'm going to close this because there are issues in the related repos for Storefront child themes compatibility and is being tracked separately.
