### ISSUE TITLE
Like and missing - addressing, creating an account and login

### ISSUE THREAD

**Issue by Eresipaq** [woocommerce/woocommerce-gutenberg-products-block#3112]
Hello
I recently used your add-on and I admit that I liked it very much. Clean, clear and legible interface, well-designed elements make the Cart page or the order page look nice and professional. Encouraged by your request in the block configuration options, I decided to share some critical comments that I hope will allow you to improve the product even more.

- the shipping address is displayed as the main address. The billing address is treated as an additional address and can only be changed after selecting the appropriate check box. Meanwhile, in my opinion, it should be the other way around. From the point of view of the store operator, the billing address is more important for legal and tax reasons. It is the shipping information that is additional. I think so.
- there is a missing field on the checkout page that, when entering the shipping / payment address, would allow to automatically set up an account for a user who does not have such an account in the store yet. An option specifying the default status would also be useful - the field checked or unchecked. Since woocommerce allows such configuration, it is a pity that you cannot use this option. The standard "naked" version of Storeforont allows this setting. Well, unless there is such a possibility, but I didn't notice it. :)
- there is one more thing related to the user account. On the checkout page, in the contact information section, there is a link: "if you have an account, click and log in". Unfortunately, after clicking, the login page does not open, but only displays the error message related to the missing URL: "The requested URL /wp-login.php was not found on this server." This is at least the case in my test local environment. I haven't had time to look for a solution yet, so I don't know if it is a known problem and I describe it as well. :)

Best regards
Robert

**Comment by nerrad** [comment]
Thanks for taking the time to leave your feedback on the Cart and Checkout Blocks @Eresipaq!

### Regarding Shipping and Billing address

The current implementation is based on our (fairly exhaustive) research into best practices where it's recommended:

- If an order requires shipping, include that as the first fields to fill out. This address potentially informs shipping rates, so it aids with calculating the correct order total before submitting the order.
- Provide the option to copy the same details for the billing address (default is to use the same details) or to enter different details if necessary.

It's worth noting that if an order does not require shipping, the billing address fields are the only fields that are shown.

If you have some data or research to point us to which demonstrates it's better to show the billing address first we'd be happy to review/consider it!

### Regarding, create Account Checkbox

This is a known issue. It's something we haven't implemented yet but are in the process of reviewing and discussing the approach we will take here (including potentially making some minor changes to how it's currently done in WooCommerce core).

### Regarding "The requested URL /wp-login.php was not found on this server."

Hmm, that sounds like it could be a bug related to your local install. This is working as expected in my testing. One thing that might improve this for you however is [this issue we have open](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/2918) for pointing this link to the Store's My Account page for logging in.

**Comment by nerrad** [comment]
I'm going to close this issue because there's nothing actionable from it currently. However rest assured you can still continue the conversation if you wish by leaving comments on it and we _have_ taken note of your comments. Thanks again!

**Comment by Eresipaq** [comment]
Thanks for the answer. It was not my intention to report any problems, I just shared my comments based on the request in the plugin settings :).
As for the research related to addresses, I do not have such. That's just what I felt. Most likely because of a habit. I think so. Of course, this is not a mistake, but a way to solve the given task.
I will verify the login link after transferring the test installation to the production environment and then I will do something about it, if necessary.
However, the issue of the missing option seems to be the most important from my point of view. It would be really worth considering adding it. Obtaining an e-mail address (account registration) while completing data is very often the only way to obtain data that can later be used for marketing purposes. I am not in favor of forcing buyers to register so that they can make a transaction. I myself often prefer shopping without registering. Especially if registration requires an additional, special action elsewhere in the website. On the other hand, information when filling in the address during shopping, for example: "check this box, and in the future I will inform you about new products, availability of certain goods or promotions" often works. This also encourages the buyer to return to the store.

Best regards and good luck in product development. I will definitely use it. :)
Robert
