### ISSUE TITLE
"Select options" should take you to the product page instead of trying to add it in a product with add-ons

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#3113]
## Describe the bug
All Products offers an in-place "add to cart" button, but if the product is a variable product, it will show "select options" that will take you to that product page.
The issue stems from combining a simple product with required add-ons, All Products will show you "Select Options" but won't take you to that page (and instead tries to directly add it, since the product is a simple product).

The issue could exist with other extensions, but I discovered it will playing with that extension. 
## To reproduce

1. You need to have [WooCommerce Products Add-ons](https://woocommerce.com/products/product-add-ons/) extension enabled.
2. Create a simple product, add a required add-on to it
![image](https://user-images.githubusercontent.com/6165348/92303365-ef16a800-ef6b-11ea-97c2-2f8c42ce0323.png)
3. On All Product page, click "Select Options"
4. the block will attempt to directly add it, and it will give you an error.

## Expected behavior
The link should take you to the product page.

## Screenshots
![ezgif com-video-to-gif (10)](https://user-images.githubusercontent.com/6165348/92303380-238a6400-ef6c-11ea-8a22-5487a692e3ef.gif)

**Comment by senadir** [comment]
I added `extensibility` label but I believe we can fix this because it's a bug, we handle Variable Product fine, we also handle Variable Subscription fine, something we don't explicitly support, we're also showing the "Select Options" text instead of "Add to Cart", it means we know somehow that this isn't a simple product, so we might try to find that logic and fix it.

**Comment by mikejolley** [comment]
This is closed by 657-gh-woocommerce/woocommerce-product-addons
