### ISSUE TITLE
Support manual ordering for Handpicked Products block

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce-gutenberg-products-block#3119]
## Is your feature request related to a problem? Please describe.
If you need to display products 43, 33, 99 in exactly that order that's currently not supported by the orderby options in the sidebar. This would be equivalent to `orderby => 'post__in'` in `WP_Query`

## Describe the solution you'd like
1. Manual order as an option in the "Order by" panel of the block settings
2. Ability to re-order the selected products via drag and drop

## Describe alternatives you've considered
Still working on a way to get around this... I'm guessing menu order will be the only workaround

**Comment by nerrad** [comment]
Thanks Kathy for the enhancement request.

Currently we don't have the bandwidth to implement this feature request as there are a number of other projects that have been prioritized for our team. We also will potentially refreshing the existing blocks in the future to share a common base so we're hesitant about implement new enhancements until we've finalized a decision around that.

Know that requests like this do get noticed and considered as we deliberate direction so it's much appreciated!
