### ISSUE TITLE
Checkout Page not Showing Stripe or COD Payment Methods & Styling Problems

### ISSUE THREAD

**Issue by yadavplusshubham** [woocommerce/woocommerce-gutenberg-products-block#3121]
## Describe the bug
I am using Kadance Theme (tried with Astra too) I am up to date on WordPress, Woocommerce & Blocks when I try to use the blocks checkout option I am First shown a Big Tick Mark near 'Same as Shipping' & Order Notes: https://ibb.co/tcvx5Kc
Also, I am not being shown any Payment method Stripe or COD: https://ibb.co/Mp7rtbG

## To reproduce

1. Go to 'Checkout Page' after setting up Plugin Checkout block on the page.
2. Scroll down to 'Same as Shipping & Payment Methods'

## Expected behavior
The Checkout page should display Payment Methods
It should not show the Big Tick Marks

## Screenshots
https://ibb.co/tcvx5Kc
https://ibb.co/Mp7rtbG

### WordPress (please complete the following information):
* Core version: 5.5.1
* WooCommerce version: 4.4.1
* WooCommerce Blocks version: 3.3.0
* Site language: English
* Any other plugins installed:

### Desktop (please complete the following information):
* OS: [e.g. macOS, Windows]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):
* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Comment by nerrad** [comment]
I think this is addressed by #3125 (and the related pull that is being done there) so I'm going to close this issue.

**Comment by yadavplusshubham** [comment]
> 
> 
> I think this is addressed by #3125 (and the related pull that is being done there) so I'm going to close this issue.

Yes Thank You, The Styling Problems were faced because of the SG Optimizer Plugin.
