### ISSUE TITLE
Ability to add quantity inputs next to the add to cart button in product blocks

### ISSUE THREAD

**Issue by emiliedebra** [woocommerce/woocommerce-gutenberg-products-block#3123]
## Is your feature request related to a problem? Please describe.
Currently, I am unable to change the quantity before adding to my basket when using a Product Block

## Describe the solution you'd like
It would be great if we could optionally add a quantity input/adjuster next to the Add to Basket button in order to achieve this.

## Describe alternatives you've considered
I have attempted to add code snippets myself to do this but it has proven too complicated.

## Additional context
Something like this is what is meant.
<img width="268" alt="Screenshot 2020-09-08 at 17 33 41" src="https://user-images.githubusercontent.com/11694694/92503621-7298f900-f1f9-11ea-9060-903c1bf301f7.png">

**Comment by nerrad** [comment]
Hi there 👋 

While we appreciate you sharing your idea with us (thanks!) and this is a good idea, it doesn’t fit in with our current priorities for the project. At some point we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. In the meantime, don't be alarmed if you don’t see any activity on this issue for a while.

**Comment by nerrad** [comment]
This request will be possible as a part of future work migrating our existing blocks to use inner blocks so there's more control over what is shown. No ETA on when that work will be done but since it's accommodated by that planning I'm going to close this issue.

Thanks again for the suggestion!
