### ISSUE TITLE
Remove unnecessary files from release tag.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#3140]
Currently in our release tags, things like `storybook` and various configuration files in the root directory are included in the tag when it's unnecessary (and means that composer pulls in these files to the package bundled with WooCommerce core releases).

We still need to include the `assets` folder because of WordPress.org releases, but I'd like to investigate doing the following:

- review what files/folders are _not_ needing included in any _release_ tags.
- make any necessary changes to the build scripts so that release tags are built without the extraneous files/folder
- retain those files in the `-dev` tag created for each release (so we can checkout the full development builds if we need to for some reason in the future).

This is assigned to the 3.4.0 milestone because 3.4.0 will be going into the next release of WooCommerce core and removing these extraneous files make it much cleaner for WC Core (especially given the various context WooCommerce core is used in).

Since I'm doing the next release of Woo Blocks, if needed, I can take care of this as a part of the release process.

**Comment by senadir** [comment]
Noting that storybook is [already removed as of 3.3.0](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3036)

**Comment by nerrad** [comment]
> Noting that storybook is already removed as of 3.3.0

Unfortunately the changes in the linked pull just affect the built zip for the plugin but not what actually is pushed to the release tag. It does not affect what is deployed to WordPress.org via the workflow we have setup because that uses what is in the `.gitattributes` file to control excluded files for that deploy.

**Comment by nerrad** [comment]
So it looks like if we get our `.gitattributes` file up to date with what should be excluded, when the package is included via `composer` in WooCommerce core, the file should be followed regarding what gets pulled in from the tag.

**Comment by nerrad** [comment]
I tested running `wp i18n make-pot` locally and while strings are extracted, our build files don't have an translation comments in them. No comment blocks make it to the built files. So for now, we have to leave source files in our release tag (and deploys - even to WooCommerce core).

**Comment by nerrad** [comment]
Related to translation comments in built code. Gutenberg encountered this issue too:

- https://github.com/WordPress/gutenberg/issues/19006 is the overall issue and
- https://github.com/WordPress/gutenberg/pull/22990 is the pull that implemented a custom terser plugin config for leaving the translator comments in place.

There will still be an issue with translators not being able to easily find source files for translations but this could remove the need to bundle source files in the plugin.
