### ISSUE TITLE
Investigate why e2e tests fail in renovate PRs

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#3141]
Travis e2e tests are failing in all Renovate PRs:

https://github.com/woocommerce/woocommerce-gutenberg-products-block/pulls/app%2Frenovate

The issue seems to be that renovate modifies the file `package-lock.json` and removes puppeteer from the top level dependencies, so Travis doesn't find it when trying to run the tests. See #3139 for more details.

What's weird is that running `rm -rf node_modules/ && rm package-lock.json && npm i` locally in those branches sets puppeteer as a top-level dependency, so for some reason the `package-lock.json` generated by renovate is not the same as the one generated locally.

Edited: as specified in the comments below, :point_down: rebasing the branches doesn't fix the issue.

**Comment by haszari** [comment]
Note that Renovate has some options for rebasing PRs. 

- Can tick a box on specific PR to request an automated rebase.

<img width="713" alt="Screen Shot 2020-09-14 at 8 36 02 AM" src="https://user-images.githubusercontent.com/4167300/93031633-912b4400-f680-11ea-98db-41fa8b69fb26.png">

- Can [configure renovate to rebase PRs whenever target branch (e.g. `main`) changes](https://docs.renovatebot.com/presets-default/#rebasestaleprs).

Note - I don't think either will completely fix the "different package-lock.json on renovate" issue, just mentioning as it might be part of a solution.

As an experiment I kicked off a rebase for #3022 👀

**Comment by haszari** [comment]
Linking in other issues related to improving our Renovate setup: #2811 #2806

**Comment by Aljullu** [comment]
> Note - I don't think either will completely fix the "different package-lock.json on renovate" issue, just mentioning as it might be part of a solution.

Right! I did try rebasing them with no luck so, while I agree that rebasing them is good, there must be something else. :confused:

**Comment by haszari** [comment]
I see there's a separate renovate PR for bumping the lock file: #3078 🤷

**Comment by Aljullu** [comment]
> I see there's a separate renovate PR for bumping the lock file: #3078 shrug

Currently, it doesn't seem to make any changes to `puppeteer`, but it might be interesting to see how that PR is updated when rebasing it with a failing `main` branch.

**Comment by nerrad** [comment]
We need to figure this out in order to unblock renovate updates, so I'm pushing it to a higher priority in the Current sprint pipeline. If no one else grabs it this week, I'll try to jump on it.

**Comment by nerrad** [comment]
I'm discovering that if I run `npm install` locally now the package-lock.json is getting regenerated and this moves puppeteer outside of the root dependency. I think what we're going to have to do is just list puppeteer-core as a top level dependency.

I'll take this issue for now so we can get the backlog of renovate pulls fixed.

**Comment by nerrad** [comment]
> I'm discovering that if I run `npm install` locally now the package-lock.json is getting regenerated

I just remembered that I have been bouncing between a number of Woo Blocks releases while fixing the recent express payment method issue, so it's quite possible the structure of files in the node_modules path is contributing to this. In turn, this may be what's causing the issue with renovate.
