### ISSUE TITLE
Fix shipping options showing when "Hide shipping costs until address is entered" setting is checked and there is no address entered yet.

### ISSUE THREAD

**Issue by Shazgu** [woocommerce/woocommerce-gutenberg-products-block#3148]
## Describe the bug
When logged out and before entering address in checkout (page is set to show default shipping cost), the default shipping cost is shown correctly under Shipping Options, but is shown as zero in the basket summary on the right hand side. See screenshot.

## To reproduce
1. Ensure you're logged out and there's a default shipping cost for the default zone
1. Add products to basket and proceed to checkout 
2. You will see the issue captured in the attached screenshot

## Expected behavior
The summary section should also show the default shipping cost. Not 0.

## Screenshots
Attached. 

### WordPress (please complete the following information):
* Core version: 5.5.1
* Gutenberg version (if installed):-
* WooCommerce version: 4.4.1
* WooCommerce Blocks version: 3.3.0
* Site language: English
* Any other plugins installed: many many others. If you ask about specific plugins I can let you know if they're installed.

### Desktop (please complete the following information):
* OS: macOS
* Browser: multiple
<img width="1670" alt="Screenshot 2020-09-15 at 11 04 35" src="https://user-images.githubusercontent.com/71322363/93199770-b5e9ef00-f746-11ea-8310-4c05bc5ab867.png">

**Comment by nerrad** [comment]
Hi @Shazgu 👋 

Thanks for reporting this bug. I think I know what's happening here. I was able to reproduce but I noticed that if _this_ setting is set:

<img width="644" alt="Image 2020-09-17 at 1 48 35 PM" src="https://user-images.githubusercontent.com/1429108/93508656-a9070000-f8ec-11ea-9270-feeeaccd88c0.png">

...then the _shortcode_ checkout flow doesn't show the shipping options. It _looks_ like the issue that might be happening in our case here is that the checkout block flow isn't respecting that option correctly.

**Comment by Shazgu** [comment]
Hey Darren,

Yep! That did the trick!

I’m happy to have it shown by default.

Thank!
Shaz

**Comment by nerrad** [comment]
Great! I'm glad this workaround works for you @Shazgu, I think I'm going to reword the title of the issue because there's still a bug with the checkout block not respecting this option for whether the shipping section shows or not.

**Comment by Shazgu** [comment]
Makes sense.
