### ISSUE TITLE
Capture details of checkout in draft order

### ISSUE THREAD

**Issue by jrick1229** [woocommerce/woocommerce-gutenberg-products-block#3150]
## Is your feature request related to a problem? Please describe.

No problem. When using the checkout block as a non-logged in user, no details are initially filled in.
If a required field is left empty and the customer clicks the 'Place Order' button, a draft order is created.

The draft order does not include any information that was actually filled in during checkout.

## Describe the solution you'd like

Capturing _any_ of the information that was filled in on the checkout block in the draft order could prove helpful for stores following up on those draft orders.

I believe GDPR should be taken into consideration, but a similar solution can be found in AutomateWoo's settings. **Enable pre-submit data capture**: https://automatewoo.com/docs/abandoned-cart/#capturing-guest-data

If nothing else, offering a hook (if possible) to enable this would be helpful as well.

## Describe alternatives you've considered

No alternatives that I can think of at this moment.

## Additional context

https://wordpress.org/support/topic/draft-order-created-automatically-on-failed-checkout-checkout-block/

**Comment by nerrad** [comment]
Thanks Joey for creating the issue. As a point of clarification, a draft order is actually created when the checkout block is first loaded. However, I do see the value in capturing any input info in the checkout form when an incomplete order is submitted. What's happening currently is validation is only happening client side for invalid fields and there is no actual submission to the server until that initial client side validation passes.

**Comment by mikejolley** [comment]
@nerrad What is the value in offering client-side validation if we're posting updates to the server anyway? This would introduce a performance issue in that we would be making unnecessary requests to the server and saving potentially invalid data (which could also be rejected by the API validation causing more error notices to display).

**Comment by nerrad** [comment]
@mikejolley I think we'd need to be calculated about _when_ the extra details are captured. Are there any points in the checkout flow where the client has validated a certain set of data that can be used to update the draft order on the server with that data? The primary benefit here from the merchant perspective would be having potential additional data to work with if they wanted to followup with an abandoned cart?

**Comment by mikejolley** [comment]
@nerrad I think this may need some design input, and some revisions to the steps. For example, one thing we could do is instead of trying to send data to the server on blur (or validate) would be to wait for an event such as a button to progress after inputting shipping address. This would validate, post to server, and get shipping rates. A mechanism like that would also solve this issue indirectly.

**Comment by nerrad** [comment]
Okay, thanks Mike, I'll put this back in the backlog for now.

**Comment by mikejolley** [comment]
@nerrad I'd be happy to investigate the button approach—it would definitely reduce unnecessary requests to the server (requests before address info is complete).

**Comment by nerrad** [comment]
Fantastic, thanks Mike. As discussed I'll add this as a cooldown task.
