### ISSUE TITLE
hi how do you change the login link to go my login  page already created

### ISSUE THREAD

**Issue by coriassnabil** [woocommerce/woocommerce-gutenberg-products-block#3159]

**Comment by nerrad** [comment]
Hi there @coriassnabil,

You've created an issue that is more of a support request and unfortunately we don't provide support for the Blocks plugin in this repository.

There are a couple avenues for support that you can take:

- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket here](https://woocommerce.com/contact-us/).
- Make a post on the [WooCommerce Gutenberg Blocks community forum](https://wordpress.org/support/plugin/woo-gutenberg-products-block/).
