### ISSUE TITLE
Fix starting express payment method and then switching to pay by saved payment method.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#3166]
This bug surfaces when a shopper that is logged in and has a saved payment method does the following steps when checking out using the checkout block:

1. Click Express Payment method (chrome pay or apple pay).
2. Abandon paying by the express payment method (cancelling or closing the modal).
3. Leaving the saved payment method option selected without choosing any other payment method.
4. Submitting the order.

The order processing fails with the notice: "Something went wrong. Please contact us to get assistance."

Network request for the checkout processing has the following as the payload:

```json
{
  "billing_address": {
    "first_name": "Darren",
    "last_name": "Ethier",
    "company": "",
    "address_1": "123 Anytown St.",
    "address_2": "",
    "city": "Anytown",
    "state": "ON",
    "postcode": "N465T2",
    "country": "CA",
    "email": "dudedandy@gmail.com",
    "phone": "1231231234"
  },
  "shipping_address": {
    "first_name": "Darren",
    "last_name": "Ethier",
    "company": "",
    "address_1": "123 Anytown St.",
    "address_2": "",
    "city": "Anytown",
    "state": "ON",
    "postcode": "N465T2",
    "country": "CA"
  },
  "customer_note": "",
  "payment_method": "stripe",
  "payment_data": [{ "key": "wc-stripe-new-payment-method", "value": false }]
}
```

Saved payment methods are expected to have something like this as the network request:

```json
{
  "billing_address": {
    "first_name": "Darren",
    "last_name": "Ethier",
    "company": "",
    "address_1": "123 Anytown St.",
    "address_2": "",
    "city": "Anytown",
    "state": "ON",
    "postcode": "N465T2",
    "country": "CA",
    "email": "dudedandy@gmail.com",
    "phone": "1231231234"
  },
  "shipping_address": {
    "first_name": "Darren",
    "last_name": "Ethier",
    "company": "",
    "address_1": "123 Anytown St.",
    "address_2": "",
    "city": "Anytown",
    "state": "ON",
    "postcode": "N465T2",
    "country": "CA"
  },
  "customer_note": "",
  "payment_method": "stripe",
  "payment_data": [
    {
      "key": "payment_method",
      "value": "stripe"
    },
    {
      "key": "wc-stripe-payment-token",
      "value": 1
    },
    {
      "key": "isSavedToken",
      "value": true
    },
    {
      "key": "wc-stripe-new-payment-method",
      "value": false
    }
  ]
}
```

The issue here is that when the express payment is cancelled, the payment method for the saved payment token is restored but the previous data for the token is not so the submission happens without that data.

**Comment by haszari** [comment]
Linking in a similar but maybe unrelated issue – #2743

These are probably completely different issues, but there are some similarities in the symptom/behaviour (cancelled modal, generic error notice, checkout in bad state).
