### ISSUE TITLE
Operator has disappeared from product category selection component

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/woocommerce-gutenberg-products-block#317]
**Describe the bug**
Operator has disappeared from product category selection component.

**To Reproduce**

- Add a product category block
- note the operator selection does not appear in the placeholder, or in the sidebar settings.

add a best selling product block
note the category operator does not appear under the category select in the sidebar settings

**Expected behavior**
The category operator should appear in the product category placeholder screen, and below the product category selection setting in the sidebar in all blocks that include the ability to filter by product category.

**Screenshots**

<img width="2012" alt="screen shot 2019-01-14 at 9 59 27 am" src="https://user-images.githubusercontent.com/4500952/51130926-1c38a480-17e3-11e9-8a85-5f432b85a92d.png">

<img width="2012" alt="screen shot 2019-01-14 at 9 59 58 am" src="https://user-images.githubusercontent.com/4500952/51131115-9bc67380-17e3-11e9-8ed3-5d1cb53beb82.png">

**Comment by ryelle** [comment]
@LevinMedia  In https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/279 we hid the operator until multiple categories are selected– does it appear once you select 2+ items?

**Comment by LevinMedia** [comment]
Sorry about that - that was the problem! Marking this closed 😬
