### ISSUE TITLE
Migrate Stripe Integration to WooCommerce Stripe repository

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#3172]
The Stripe team will be taking ownership of the Stripe extension so we will be moving the integration code from Blocks plugin to the [Stripe extension](https://github.com/woocommerce/woocommerce-gateway-stripe) itself.

**Comment by cvandend** [comment]
Looking forward to this. I would like to use the additional different Stripe payment methods, mainly iDeal.

**Comment by nerrad** [comment]
Since the PR for the migration is now in the Stripe repository, I'm closing this Epic as being done. The handoff has happened to the team owning the Stripe extension.
