### ISSUE TITLE
Klarna Checkout and Klarna Payments Integration with Cart and Checkout Blocks

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#3176]
Klarna [is owned by third parties](https://github.com/woocommerce/woocommerce-gateway-klarna) so it's still unknown what direct contributions we will/can make for this work, however it's being included as a part of our integration work for the blocks. Where possible we will attempt to support ensuring any integrations are in place for these extensions. It's still undetermined while we will contribute work to the extension itself or do an initial integration in the blocks plugin.

Currently the repository for the extension will need to have a build process implemented for the integration (webpack & react) which adds to the work needed.

**Comment by nerrad** [comment]
I'm going to close this because it's something handled outside of our repository.

**Comment by thisissandip** [comment]
We have now integrated Klarna Payments: https://woocommerce.com/products/klarna-payments/ with WooCommerce Blocks.

You can find the compatible payment gateway and WooCommerce Blocks version on our documentation here: https://woocommerce.com/document/cart-checkout-blocks-support-status/#payment-gateways

I hope this helps everyone who drops into this GitHub report.

Please feel free to contact us here: https://wordpress.org/support/plugin/woo-gutenberg-products-block/ if you have any further questions.

We will be happy to assist you!
