### ISSUE TITLE
Integrate TaxJar with Checkout block

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#3180]
This issue is a tracking issue for integrating the TaxJar extension with the Checkout Block.

Some knowns:

- Likely will require same APIs as WooCommerce Services (#3170)
- This extension syncs orders so potential issue with our reserve-stock orders (looks like it syncs completed/refunded status only so maybe okay).

Unknowns:

- I don't see the repo available in the WooCommerce org, so unclear how we'd contribute to the integration (some discovery work around this needed). This is a 3PD extension.
- Unclear the difficulty involved in testing any integration.

**Note: this issue is mostly about auditing the Cart and Checkout Blocks the ensure they have the extensibility interfaces TaxJar needs.**

**Comment by mikejolley** [comment]
I believe we have all the integration points necessary. TaxJar does have a bug because it only calculates taxes on certain routes. I created this patch upstream:

https://github.com/taxjar/taxjar-woocommerce-plugin/pull/188
