### ISSUE TITLE
Integrate StoreFront PowerPack with Cart and Checkout Blocks

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#3181]
This issue is a tracking issue for integrating Storefront Powerpack with Cart and Checkout blocks. I anticipate any work needed will be done in the [PowerPack repository](https://github.com/woocommerce/storefront-powerpack) but we can use this issue to track that work.

See review of feature set and current behaviour with the blocks: pca54o-gc-p2

Given the review above, there are a number of things that work okay with Powerpack and a few things that we intentionally will _not_ integrate:

### Checkout Layout

This feature allows changing the alignment of the checkout page sections. For the blocks, the layout and manipulation will be something potentially iterated on in future releases and may be accomplished by sections of the checkout being blocks themselves. So we will not be adding the ability for PowerPack to change the block layout.

**Actions:** 

- When checkout block is active in the checkout page content, remove the visibility of this feature in powerpack.
- Ensure any documentation referencing this feature adds the caveat that it does not work with the Checkout Block.

### Two-Step Checkout

This feature separates the customer details collection form and the order summary/payment details form into two separate views (or steps in the checkout flow).

For the checkout block, the flow is already optimized for more clearly representing the different steps in the checkout and in the future we may introduce the option for more flexibility with this (how steps display, ordering steps etc) but for now this is _not_ something that will be enhanced by the Storefront PowerPack extension.

**Actions:**

- When checkout block is active in the checkout page content, remove the visibility of this feature in powerpack.
- Ensure any documentation referencing this feature adds the caveat that it does not work with the Checkout Block.

**Comment by nerrad** [comment]
@opr can you link any in progress prs related to the work for this epic to the issue. Thanks!

**Comment by opr** [comment]
There is a single PR which will complete all necessary actions for this epic: 233-gh-woocommerce/storefront-powerpack

**Comment by opr** [comment]
Other literature:

Open request with docs guild: p1615987381004400-slack-CSP74N77C
P2 warning for Woo Support: p6q7sZ-8rb-p2
