### ISSUE TITLE
The all-products block, used in a reusable block not rendered by ajax (rest-api)

### ISSUE THREAD

**Issue by fotovat** [woocommerce/woocommerce-gutenberg-products-block#3186]
## Describe the bug

When ajax loads a reusable block which has The all-products block, everything loaded except all-products. 
There is no problem with the heading, gravity forms, Etc.

When it loads without ajax by single-cpt.php, it is rendered correctly.
we use REST-API instead of admin-ajax.php

## To reproduce

1. Create reusable block and include all-products block and a sample heading

2. Register REST API endpoint
```

add_action('rest_api_init', static function () {
    register_rest_route('/sitename/render/v1/list', '/products', array(
        'methods' => 'GET',
        'callback' => 'page_render_fn'
    ));
});

function page_render_fn()
{
    $post_id = 512; //the id of reusable block
    $reuse_block = get_post($post_id);
    $reuse_block_content = apply_filters('the_content', $reuse_block->post_content);
    echo $reuse_block_content;

}
```

3.use jQuery to do ajax

```

jQuery(document).ready(function ($) {
    listesh_Gifts_fn();

    function listesh_Gifts_fn() {
        $.ajax({
            type: 'GET',
            url: page_render_val.restURL + 'sitename/render/v1/list/products',
            beforeSend: function (xhr) {
                xhr.setRequestHeader('X-WP-Nonce', page_render_val.restNonce);
            },
            dataType: 'html',
            success: function (response) {
                if (response) {
                    jQuery("#main").html(response);
                }
            },
        })
    }
});

```

## Expected behavior
Show page with All products and Heading
(currently it shows just Heading)

## Current Behavior
the out put is:
```

<h2>Sample</h2>


<div class="wp-block-woocommerce-all-products wc-block-all-products" data-attributes='{"alignButtons":false,"columns":4,"contentVisibility":{"orderBy":true},"isPreview":false,"layoutConfig":[["woocommerce/product-image"],["woocommerce/product-title"],["woocommerce/product-price"],["woocommerce/product-rating"],["woocommerce/product-button"]],"orderby":"date","rows":3}'></div>
```

### WordPress (please complete the following information):
* Core version: 5.5.1
* Gutenberg version : 9.0.0
* WooCommerce version: 4.5.2
* WooCommerce Blocks version: 3.4.0
* Site language: English

**Comment by fotovat** [comment]
I guess I have to enqueue all-products block assets manually, but how?

**Comment by senadir** [comment]
I've yet to look at the issue, but all-products files are registered under the handle `wc-woocommerce/all-products` so you can manually enqueue that into your code.
If that didn't work, you can try to register and enqueue the files manually:
all-products files are `build/all-products-frontend.js` and the dependencies are `build/all-products-frontend.asset.php`
You can see an example here of how to enqueue the file with its dependencies 
https://github.com/WordPress/gutenberg/tree/master/packages/dependency-extraction-webpack-plugin#wordpress

One important note is that the path depends if you're loading the blocks from WooCommerce Blocks plugin or WooCommerce plugin.

**Comment by fotovat** [comment]
Thank you
