### ISSUE TITLE
Fix checkout error message showing encoded code.

### ISSUE THREAD

**Issue by Shazgu** [woocommerce/woocommerce-gutenberg-products-block#3188]
## If total payment isn't meeting a minimum (not sure why this error has suddenly started appearing, but that's a different question), the woo-commerce blocks checkout page is showing code rather than the parsed message.

This is what the error looks like on the standard woo-commerce checkout
<img width="1431" alt="Screenshot 2020-09-23 at 18 54 33" src="https://user-images.githubusercontent.com/71322363/94058525-09a8a800-fdd9-11ea-9255-759a8861bff8.png">

This is what it looks like on the plugin checkout:
<img width="1669" alt="Screenshot 2020-09-23 at 18 43 06" src="https://user-images.githubusercontent.com/71322363/94058468-f695d800-fdd8-11ea-8bc1-bc732e6b08ca.png">

## To reproduce
Make sure the total is under the minimum required (not sure where that's set. This error message has started appearing for us today. There was no minimum requirement before now), and submit the patment

## Expected behaviour
See first screenshot

### WordPress (please complete the following information):
* Core version: 5.5.1
* Gutenberg version (if installed):-
* WooCommerce version: 4.5.2
* WooCommerce Blocks version: 3.4.0
* Site language: English
* Any other plugins installed: Loads.

### Desktop (please complete the following information):
* OS: macOSX 10.14.6
* Browser: Safari (don't think it's relevant)
* Version: 14

### Smartphone (please complete the following information):
* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Comment by nerrad** [comment]
Thanks @Shazgu for reporting this bug. It looks like this notice is added by the WooCommerce Stripe extension. 

@woocommerce/rubik this appears to be an encoding issue with the response sent back for order processing errors from the `wc/store/checkout` route. At a minimum the currency symbol should be decoded but I'm not sure how we should handle html in notices because of potential escaping issues. We may need to strip html from notice content before sending back on the request.

**Comment by Shazgu** [comment]
Glad to help.

**Comment by Shazgu** [comment]
Hi Darren, 

I know this isn’t the right channel, but I’m hoping you can help anyway - we’re stuck and we urgently need help with a woocommerce checkout bug. It’s standing in the way of us going live, and we’re stumped for a solution. 

I saw you tried to assist someone with it about 3 months ago (https://wordpress.org/support/topic/after-purchasing-it-shows-empty-checkout-page/ <https://wordpress.org/support/topic/after-purchasing-it-shows-empty-checkout-page/>) but couldn’t reproduce the issue. 
It’s the bug where the order-complete page is coming up blank even though the order is processed ok (see screenshot). It happens both when we use WooCommerce blocks checkout or the standard checkout page.
There are no issues found in console (See screenshot) - it’s just not showing.
It’s not a custom page. We have it set up to the default order-complete page.

I’ve spent the day turning things on and off to find out what’s causing it. I’ve finally found out that disabling Elementor fixes it, but turning it on again brings the problem back. I can’t remove the plugin because it messes up the site. Large chunks of it are built with Elementor.

It’s been working fine with elementor up to yesterday. We’ve had it happen before for about a day but the problem disappeared as randomly as it had appeared.
Any suggestions would be very very welcome. 

Hope you can help.
Kind regards,
Shaz

**Comment by nerrad** [comment]
Really sorry but this isn't a support channel. I can appreciate the urgency in your case, but we do have to draw the line. Since you've narrowed this down to something with elementor, you may have to seek support from them instead of WooCommerce.

Let's avoid adding separate issues to this thread otherwise it creates additional noise diverting from what was originally posted.

**Comment by Shazgu** [comment]
I’m not sure it is an Elementor issue because people are reporting the same issue with different themes and plugins sounds like a woocommerce thing. 
Please feel free to delete my last two messages, I’ll post it in the proper channel.

**Comment by opr** [comment]
After investigating and testing, it looks like this was fixed in #3410. I tested the checkout using Stripe for an order less than 0.30 and the error displayed nicely for me.

**Comment by nerrad** [comment]
Awesome! Thanks for confirming 👍 @Shazgu that means the fix should show up in the pending 3.9.0 release of WooCommerce blocks.
