### ISSUE TITLE
Featured Product: Allow custom block height related to set image

### ISSUE THREAD

**Issue by ryelle** [woocommerce/woocommerce-gutenberg-products-block#319]
The user should be able to set a "custom" height somewhere between the block minimum and the max height of the image. This is controlled with a slider.

<img width="290" alt="68747470733a2f2f636c6475702e636f6d2f7642374335596234727a2d3230303078323030302e706e67" src="https://user-images.githubusercontent.com/541093/51134337-456a2c80-1805-11e9-984d-b15967494a9b.png">

**Comment by jameskoster** [comment]
Hmm, with a fixed max value what would happen if the product description was really long and more than 1000px was required? I suppose that problem existed with the original plan as well, something to consider though.

Would it be possible to use a range+text input with a default max of 1000, but if you manually type something >1000 into the text input the range would inherit that value as the new max? I think something like that with the `cover` / `contain` toggle might work. We'd just need to think of some more human friendly labels for that toggle.

**Comment by ryelle** [comment]
> what would happen if the product description was really long

Well, even now the height isn't a fixed height - it will stretch to fit the content, so really all we'd need to do would be fix some padding:

<img width="573" alt="screen shot 2019-02-01 at 10 34 44 am" src="https://user-images.githubusercontent.com/541093/52132510-4b397d80-260d-11e9-8d0e-72c020de45e2.png">

> Would it be possible to use a range+text input with a default max of 1000, but if you manually type something >1000 into the text input the range would inherit that value as the new max?

Given that the block height is a min-height, and not a fixed height, do you think we still need to try this?
