### ISSUE TITLE
When tax calculations is disabled in settings, total in cart and checkout shows 'includes £0 in taxes' 

### ISSUE THREAD

**Issue by Shazgu** [woocommerce/woocommerce-gutenberg-products-block#3195]
## Describe the bug
When the tax calculation setting is disabled, tax is still showing under the total as 'includes £0 in taxes', which is both incorrect and shouldn't be shown. (See screenshots)

## To reproduce
Make sure 'Enable taxes' is disabled in Woocommerce settings (under General Options), add items to basket, navigate to basket and then checkout and observe the total sum.

## Expected behaviour
Totals should not include any reference to taxes.

## Screenshots
<img width="821" alt="Woocommerce Settings" src="https://user-images.githubusercontent.com/71322363/94260543-4931da00-ff28-11ea-8edf-f23accbd69e4.png">
<img width="431" alt="Total in basket" src="https://user-images.githubusercontent.com/71322363/94260554-4df68e00-ff28-11ea-8b00-9cfdcdaf0161.png">
<img width="461" alt="Total in checkout" src="https://user-images.githubusercontent.com/71322363/94260572-52bb4200-ff28-11ea-8e1e-8fca16cd6e7f.png">

### WordPress (please complete the following information):
* Core version: 4.5.2
* Gutenberg version (if installed): -
* WooCommerce version: 4.5.2
* WooCommerce Blocks version: 3.4.0
* Site language:
* Any other plugins installed:

### Desktop (please complete the following information):
* OS: [e.g. macOS, Windows]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):
* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Comment by nerrad** [comment]
I can reproduce, however in order for this to happen, the tax settings must also be configured to include tax for the "Display prices during cart and checkout" setting:

<img width="712" alt="Image 2020-09-28 at 11 47 32 AM" src="https://user-images.githubusercontent.com/1429108/94454894-77115b80-0180-11eb-8230-0e77fde5e2c9.png">

So as a temporary workaround until we fix this, you can just change that setting to Excluding tax (you'll have to re-enable the tax settings option mentioned in the issue description first) and then turn off taxes generally.

**Comment by Shazgu** [comment]
Thanks. I think this’ll work for us for the time being.

**Comment by senadir** [comment]
Adding to Darren's comment, you wouldn't be able to find that option unless you enable taxes first, so

- Enable taxes.
- set checkout prices to include taxes.
- Disable taxes.
