### ISSUE TITLE
Add Mailchimp for WooCommerce Newsletter Checkbox to work like it did on the traditional checkout

### ISSUE THREAD

**Issue by nathanteaton** [woocommerce/woocommerce-gutenberg-products-block#3207]

**Comment by nerrad** [comment]
Hi 
HI there @nathanteaton  👋🏻

Thanks so much for taking the time to leave some feedback - much appreciated! We make note of all feedback we receive and we also close issues with the feedback as active issues are used for bugs or feature/enhancements. It does not mean that we don't note or review the feedback. Closed issues can also still be commented on.

The Cart and Checkout blocks are still in preview via the Blocks feature plugin and we're still working out extensibility points for extensions to integrate with the blocks. The blocks are not implemented the same as the shortcode checkout flows so there are extensions will have to explicitly integrate with them once we have the extensibility available. Once it's available we'll be announcing and encouraging extension developers to integrate.

In the meantime you can keep up with the [status of the Cart & Checkout blocks here](https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/).

**Comment by thisissandip** [comment]
Hey @nathanteaton,

The MailChimp for WooCommerce is now compatible with the Cart and Checkout Blocks.

The minimum requirements are:

> WooCommerce Blocks 8.0.0+
Mailchimp for WooCommerce 2.7+

You can read and find other compatible extensions with Cart & Checkout blocks here: https://woocommerce.com/document/cart-checkout-blocks-support-status/#section-5

Should you have any questions, feel free to reach out to us and we will be happy to assist you! 🙂
