### ISSUE TITLE
Conditional Shipping and Payments

### ISSUE THREAD

**Issue by completegraphics** [woocommerce/woocommerce-gutenberg-products-block#3218]
Cant exclude specific payment gateways for specific products. all payment gateways show.

**Comment by nerrad** [comment]
Hi @completegraphics 

Can you share a bit more about your use-case or ideally point to an extension that does what you want to do? Right now your request is a bit too concise.

I gather that you want the ability to hide specific payment methods from being an option for products that may be in the cart. We do have a [payment method integration api](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/extensibility/payment-method-integration.md) that could potentially help with this but we'd need some clarity on:

- your use case.
- how does your use case handle multiple products in the cart?
- does your use case hide custom payment methods specific to this type of purchase or does it hide/show payment methods provided by other WooCommerce extensions?

**Comment by nerrad** [comment]
Due to lack of response there's nothing actionable on this issue.
