### ISSUE TITLE
Add ability to turn on Cart and Checkout blocks programmatically externally.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#3222]
At some point in the future we may be looking towards inviting specific qualified stores to use the Cart and Checkout blocks in A/B tests to validate how the blocks convert compared to shortcode flows. This data will be a more targeted measurement of conversion rates that will provide better insight into the performance of the new flows over the shortcodes.

An important prerequisite to doing this will be having an external programmatic way to enable the Cart and Checkout blocks in core which are currently restricted via the feature phase flag.

One question that comes to mind is around the fact that currently our feature gating is "phase" specific vs feature specific. This means enabling Cart and Checkout block functionality also potentially enables all other things gated behind the Feature plugin phase. What complications does that potentially introduce - if any?

I've set #3211 as a dependency because I think it will be easier and less error prone if we have all the logic related to setting the current feature phase in a new feature service class.

**Comment by haszari** [comment]
A CLI command for this could be interesting, at least for testing/dev but maybe also for eCommerce plan.

**Comment by nerrad** [comment]
We are pausing on this for the time being pending review of the reasons for implementing this.
