### ISSUE TITLE
Adjust Woo status page/status report so it includes blocks (vs. cart/checkout shortcode)

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#3224]
## Is your feature request related to a problem? Please describe.
There's a status report in Woo which alerts the merchant to missing config or store setup. If the store uses blocks for cart and checkout, the status page shows this as an error!

<img width="938" alt="Screen Shot 2020-09-30 at 2 44 20 PM" src="https://user-images.githubusercontent.com/4167300/94635120-5edf3f00-032e-11eb-9d16-e16986599b4a.png">

Spun off from [discussion](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3187#issuecomment-701117942) in #3187

## Describe the solution you'd like
Adjust this status item so it's happy if site uses blocks OR shortcodes. Optionally add a warning/danger state if blocks AND shortcodes are present.

If this info is included in the text status report (used in support tickets), we should fix that up too so it's all consistent.

## Additional context
We have some prior art for this in Woo core - in [wc_tracker we dig into the cart/checkout pages (code in Woo core)](https://github.com/woocommerce/woocommerce/blob/60d6510cb049836ae5c92482f0c8853436e42726/includes/class-wc-tracker.php#L738) to see if they contain shortcode or block. We might be able to adapt/reuse this code. The point is we should aim to use the same concept for the tracker prop and status page (even if they don't share code), rather than have two slightly different implementations.

I've logged the issue in blocks, but it may be cleaner to implement this in core.

**Comment by haszari** [comment]
While working on #3187 I realised there's a more robust way to detect shortcodes - `has_shortcode()`.

As part of fixing this issue it's probably a good idea to look at using the same code (from solution to #3187) for the status page and also for the [wc-tracker props in core](https://github.com/woocommerce/woocommerce/blob/60d6510cb049836ae5c92482f0c8853436e42726/includes/class-wc-tracker.php#L750).

**Comment by budzanowski** [comment]
Closing in favor of #3565
