### ISSUE TITLE
User-defined sort order for Hand Picked Products Block

### ISSUE THREAD

**Issue by spwarner** [woocommerce/woocommerce-gutenberg-products-block#3230]
I want to be able to quickly show specific products in a **_specific order_**. The Hand-Picked Products block lets you choose specific products, but you can't define the order manually.

Wordpress supports "post__in" as an orderby option, and passing "post__in" to the [products] shortcode works (though undocumented). So to support this, you'd just need to add a new option for orderby - something like "Manual" to trigger the 'post__in" orderby option, and then add the ability to drag/drop selected products to set the order (as the block currently reorders the selected products (alphabetically?) as you select them).

**Comment by nerrad** [comment]
Hi there 👋

Thanks for taking the time to share this idea, we really appreciate your help.  

While this is clearly a great idea, we won't be able to tackle it in the upcoming weeks as we're currently focused on finishing all the work that was identified as a priority for the next release of this plugin.  I'm going to add this to our backlog where it will be considered for future releases.
