### ISSUE TITLE
Create a generic build process that can be integrated into other plugins 

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#3232]
Part of the integration process is creating a build process for each plugin that will have JS code (the majority of them), the build process should be consolidated and hashed out here and once ready, merged to each repository.
Because the build process is not overly complicated, I prefer that don't build a custom package for it. We're going to use `wp-scripts` with a custom webpack config file.

### Things the build process should support:
- [x] Compile ES6 code to compatible code (covered by wp-scripts).
- [x] Support sass (covered by wp-scripts).
- [x] Support JSX (covered by wp-scripts).
- [x] Tree-shaking and bundle optimization (covered by wp-scripts).
- [x] Dependency extraction for core packages (covered by wp-scripts).
- [ ] Support eslint and includes `@woocommerce/eslint-plugin`
- [ ] Dependency extraction for Woo specific packages.
- [ ] Enqeueing scripts and registering dependencies (specific to each plugin).
- [ ] Loading the scripts and styles only when Cart or Checkout block is present (specific to each plugin).
- [ ] Adds a package.json file with required metadata and node-module dependencies.
- [ ] Can extend and add data to `wc.settings`.
- [ ] Supports WooRelease (assumed and implied, but not confirmed). 

### Good to have (in the future)
- [ ] Has some sort of automated package update in Github (renovateBot for example).
- [ ] Supports some sort of unit/integration tests.

### Not trivial but very important tasks for the future
- [ ] Implements its own E2E infrastructure or integrates deeply with existing E2E systems.

## Reminders

- Each time you add a build process to a plugin, link the PR and plugin here in a comment.
- It's preferable that we solve all generic issues and points before we start implementing the system so that we don't go back and forth and update all plugins.

**Comment by nerrad** [comment]
Thanks for getting this outlined and made clear @senadir! I think it will greatly help rolling out the build process to the extensions as we build integrations. I think all of the extensions we will work with will need a webpack config, so once we've got an example to roll with, maybe add it to this issue as a comment and that way it's just a copy/paste.

> It's preferable that we solve all generic issues and points before we start implementing the system so that we don't go back and forth and update all plugins.

💯  on this.

> Dependency extraction for Woo specific packages.

@psealock is [working on a `@woocommerce/webpack-dependency-extraction` package](https://github.com/woocommerce/woocommerce-admin/pull/5198) that should help with this. Should maybe work with him to help get that over the line so we can use it.

> Enqeueing scripts and registering dependencies (specific to each plugin).

Just to clarify, this will be php side right?

> Adds a package.json file with required metadata and node-module dependencies.

I think nearly all the extensions I looked at already have a `package.json` file, so it's just a matter of updating it.

For the `Good to Have` and `Not trivial but important tasks for the future`, it's really good you documented this. I think we'll want to surface this to the teams involved and have them own these tasks.

**Comment by senadir** [comment]
A note of why I included unit/integration/e2e tests even thou this issue talks about a build process.

All Unit and Integration runners will usually implement their build process. Jest has its own babel setup. If we're writing JS code and have a custom build process, we need to make sure the same code can run with jest.
Who will do this work depends on availability and progress (probably, the team owning the plugin), but it was important to highlight so that people can reference the build process when doing that.

E2E is a bit different, the build process shouldn't care how E2E works, as long as we're invoking `npm run build`, but I wanted to highlight that wp-scripts has e2e runner capabilities if teams want to use it.

**Comment by nerrad** [comment]
Yup understood Nadir, I'm sure you're aware but just pointing out for others that may not be - it's worth noting that out of the box, `wp-scripts` includes configuration for kicking of e2e and jest unit tests. As you point out, there may still be some additional configuration required in the case where there may be custom aliases etc (or for adding `react-testing-library` as an option) but I still think that should be on the team owning the extension so they are familiar with what they've setup. 

Also something else I forgot to mention, we should probably include adding `@woocommerce/eslint-plugin` as the list of things to include in the build process. It does mean that for extensions we might need to exclude any existing js files extensions have because I'm guessing they likely won't pass the linting.

**Comment by senadir** [comment]
The work that Thomas did in 3906-gh-woocommerce/woocommerce-subscriptions is great example of a generic build process, so we should try and use that as we go.

It can also include this issue #3532 but it's neither a requirement nor a blocker.

**Comment by senadir** [comment]
Closed by 3906-gh-woocommerce/woocommerce-subscriptions

If you're adding a build process to a plugin, consult that PR and this one 3940-gh-woocommerce/woocommerce-subscriptions
