### ISSUE TITLE
Integration Tracking (WC Subscriptions): Create a subscription when checking out a subscription product

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#3233]
Currently, when you checkout an order that contains a subscription product, no subscription is created.

### Steps to reproduce 
- Add a subscription product to your cart.
- Checkout.
- Visit the backend. No subscription is created.

### Expected behavior
- A subscription should be created.

### Where should this issue be solved
This issue should probably be solved on the [WooCommerce Subscription](https://github.com/woocommerce/woocommerce-subscriptions) repository

**Comment by haszari** [comment]
FYI @senadir I assigned you and shifted to in progress - it looks like you're working on this in woocommerce/woocommerce-subscriptions#3825.

**Comment by senadir** [comment]
This is closed by 3825-gh-woocommerce/woocommerce-subscriptions
