### ISSUE TITLE
Does not work with WooCommerce Subscriptions

### ISSUE THREAD

**Issue by JSalamanca95** [woocommerce/woocommerce-gutenberg-products-block#3235]
## What do you like about the Cart & Checkout blocks?

Layout is perfect!

## What do you think is missing from the Cart & Checkout blocks?

I have the Woocommerce Subscriptions add-on but when I use the Cart and Checkout through blocks, it completely negates the subscription for my products. I'm not sure why this would be.

**Comment by nerrad** [comment]
HI there {handle} 👋🏻

Thanks so much for taking the time to leave some feedback - much appreciated! We make note of all feedback we receive and we also close issues with the feedback as active issues are used for bugs or feature/enhancements. It does not mean that we don't note or review the feedback. Closed issues can also still be commented on.

The Cart and Checkout blocks are still in preview and there are a number of extensions and payment methods that are not integrated yet. WooCommerce Subscriptions is one of those extensions. You can follow [this document](https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/) to keep up to date with the latest status of the blocks.
