### ISSUE TITLE
Integration Tracking (WC Subscriptions): Load existing orders into Checkout

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#3239]
When you resume a subscription order, or try to manually pay for a renewal order, you won't see the renewal screen, instead, you will just get the regular order block that ends up creating a new order and ignoring the previous one.

## Steps to reproduce
1- Have a subscription in your store.
2- In the admin area, run `create pending renewal order`
3- Go to my-account/subscriptions
4- View the subscription.
5- Scroll till you see the pending order, click Pay.
6- You will be redirected to the checkout block.
7- Attempt to checkout, it would be successful, but a new order will be created.

## Expected behavior
You should either see the order-pay screen
![image](https://user-images.githubusercontent.com/6165348/95098531-b4e52580-0726-11eb-9238-6eaa021ecd2e.png)

Or the checkout block should process the provided order, not a new one.

## Extra caveat
WooCommerce Subscription doesn't use the normal order-pay screen, and redirects the user to another to the regular checkout. This is the code responsible for that
https://github.com/woocommerce/woocommerce-subscriptions/blob/50522bf2ad29e9d796d21d33da442ae5099988a4/includes/class-wcs-cart-renewal.php#L161-L234

**Comment by senadir** [comment]
Removing `maybe_setup_cart` fixes this by redirecting the flow to the order-pay screen, however, I think we should use the current checkout block to pay for the order.
This is a bit tricky issue that touches a lot of places, what we need to do is:
- Pass the order ID to our checkout REST so that it uses that order instead of creating a new one.
- Resume that order directly.

I don't feel super confident about my ability to do this, so I'm going to keep it aside for now and handle other issues before coming back to it.

**Comment by haszari** [comment]
> Removing maybe_setup_cart fixes this by redirecting the flow to the order-pay screen, however, I think we should use the current checkout block to pay for the order.
> This is a bit tricky issue that touches a lot of places

@senadir Agreed, this seems like a pretty important piece of delivering subscriptions. Might be worth someone doing a quick research/prototype spike and P2ing to decide on an approach.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce-subscriptions/pull/3967

**Comment by senadir** [comment]
@mikejolley why did you close this? 3967-gh-woocommerce/woocommerce-subscriptions is still open with a new bug from Bartek?
Or do you want me to open a separate issue that targets manual renewals?

**Comment by mikejolley** [comment]
I thought it had merged already nvm
