### ISSUE TITLE
Integration Tracking (WC Subscriptions): Add filters to our REST endpoints

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#3244]
To expose certain data types in our interface, we need to have that data in the first place.

The first option is to call another API, but this will cause an extra API request.

The best option is to extend our store API, this can be done with extra filters.

For the initial work, we will need filters in:

- Cart items.
- Coupons.

Under consideration, but not final:
- Shipping methods.
- Product.

Those filters should be private (not publicly documented) until we're certain we want to ship them.

**Comment by senadir** [comment]
After some discussions with @nerrad the approach we're taking here is this:
- instead of filtering the response directly `return apply_filter( "woocommerce_blocks_rest_cart_item", $data );` we would only append data, so our `$data` array would be like this:

```php
$data = [
// original data
"extensions" => apply_filter( "woocommerce_blocks_rest_cart_item", [] ),
];

// plugin code
add_filter( "woocommerce_blocks_rest_cart_item", function( $response ) {
    return $response[ $plugin_namespace ] = $data;
});
```

This ensures that our original data shape is never altered, but limits extensions ability to update its values from this filter. However, they can still hook into earlier places with existing filters in WooCommerce Core.

Plugins need to add data under a namespace to not compete for the same key.

We can go even fancier and introduce a wrapper thing that abstracts the filter.

```php
wc_blocks_extend_item_response( $plugin_namespace, $data );
```

The approach we use should be consistent between all of our extension endpoints.
Instead of trusting that extensions won't mess core data, we should only trust that they won't override each other data.

**Comment by nerrad** [comment]
There's some good initial plans there, however I would like us to avoid adding the filter directly on the data response and introduce a registration mechanism (like you suggested) that allows for a few things:

- adding api requirements.
- validating what is registered.
- protecting extensions from clobbering other extensions (and thus increasing the risk of breaking other integrations).
- ensuring things are namespaced properly.

**Comment by senadir** [comment]
After more digging, I found `add_rest_field`, which should work exactly as we want.

https://developer.wordpress.org/reference/functions/register_rest_field/

It checks all the things we need except the namespace one. We can implement something like this, or abstract this to our needs.
