### ISSUE TITLE
Image override option not appearing in featured product block

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/woocommerce-gutenberg-products-block#325]
**Describe the bug**
Image override option not appearing in featured product block 1.3.0 RC zip

**To Reproduce**
Add featured product block
Select a product
Note, the image override button doesn't appear in the block toolbar

<img width="1683" alt="screen shot 2019-01-14 at 8 25 42 pm" src="https://user-images.githubusercontent.com/4500952/51159243-1079cc00-183d-11e9-9fcf-1f7141f53d03.png">

**Comment by ryelle** [comment]
This should be fixed in the newly updated RC zip: https://github.com/woocommerce/woocommerce-gutenberg-products-block/releases/tag/v1.3.0-RC

**Comment by ryelle** [comment]
When you install it, check that the version says `1.3.0-RC` and not `1.3.0-dev`
