### ISSUE TITLE
My thoughts on this nice plugin

### ISSUE THREAD

**Issue by amogul22** [woocommerce/woocommerce-gutenberg-products-block#3255]
## What do you like about the Cart & Checkout blocks?
It looks really good!
## What do you think is missing from the Cart & Checkout blocks?
To make this perfect:
- The coupon button may be missed, both on Cart and Checkout page. You can make this pop up more, maybe change its position, add maybe a border or a splash of color than can be customized.
- The "Add delivery note" is not translated, both the title and the text field hint;
- It would be nice to customize if the check "Billing address is the same as delivery address" is ON or OFF by default.  
- There should also be a checkbox to "I have read and agree to the terms and conditions and data protection" with the hyperlink to "terms and conditions" and "data protection", like it is on default template. Translatable of course ;) It is not enough, especially for EU, to just put a link, the user has to actively check it, otherwise he should not Finalise the order.

**Comment by nerrad** [comment]
HI there @amogul22  👋🏻

Thanks so much for taking the time to leave some feedback - much appreciated! We make note of all feedback we receive and we also close issues with the feedback as active issues are used for bugs or feature/enhancements. It does not mean that we don't note or review the feedback. Closed issues can also still be commented on.

> The coupon button may be missed, both on Cart and Checkout page.

Noted. There currently aren't any plans to change the design for this which has gone through various user testing and design iterations already.

> The "Add delivery note" is not translated, both the title and the text field hint;

It's possible the translation doesn't exist yet for the language you are viewing it in. However, the code outputting that string [definitely is configured for translation](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/5effb3d5fe0d977bc3f4719922e10d5f74619b3e/assets/js/blocks/cart-checkout/checkout/form/order-notes/index.js#L26-L29).

> It would be nice to customize if the check "Billing address is the same as delivery address" is ON or OFF by default.

Noted. Would you be able to share why you think this would be useful? Our current implementation is based on our research into best practices and data obtained around reducing friction for the purchase process and this is one area that impacts conversion rates. However there may be use-cases for merchants defaulting both billing address and shipping address to always show that we haven't considered.

> There should also be a checkbox to "I have read and agree to the terms and conditions and data protection" with the hyperlink to "terms and conditions" and "data protection", like it is on default template.

Thanks for bringing this up, I've created #3258 for us to consider this in future workk.
