### ISSUE TITLE
Price overflow on smaller viewports

### ISSUE THREAD

**Issue by chrismademe** [woocommerce/woocommerce-gutenberg-products-block#3257]
## Describe the bug
On small (iPhone 5/SE size) devices, if a price is larger than 3 digits, it overflows the container slightly.

## To reproduce

1. Add the WooCommerce Cart block to your Cart page
2. Resize the viewport down to 320ish pixels

## Expected behavior
I think maybe the price should drop to the next line or the quantity component would have the +/- buttons removed for small viewports?

## Screenshots
https://i.imgur.com/tk1bqtn.png

### WordPress (please complete the following information):
* Core version: 5.5.1
* WooCommerce version: 4.5.2
* WooCommerce Blocks version: 3.5.0
* Site language: English
* Any other plugins installed: Advanced Custom Fields PRO, Custom Post Type UI, Regenerate Thumbnails

### Desktop (please complete the following information):
* OS: macOS
* Browser Firefox
* Version 81.0.1

**Comment by nerrad** [comment]
Hi there 👋,

Thanks for taking the time to report this bug, your help is really appreciated!

I can reproduce this on Storefront. I can't give an ETA on when this will be addressed but it is something we'll address at some point.
