### ISSUE TITLE
Consider including checkbox for "I have read and agree to terms [terms]" with customizable text when there is a terms and conditions page.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#3258]
The current shortcode checkout flow includes customizable Privacy Policy and Terms and Conditions text that is configurable via the customizer:

![Image 2020-10-08 at 10.17.30 AM.png](https://images.zenhubusercontent.com/55c8bfc24f7a08fbb7f431bd/0d079c6d-109e-419f-abb2-94e90f5ae6dd)

Which results in the following in the shortcode checkout ui:

![Image 2020-10-08 at 10.19.07 AM.png](https://images.zenhubusercontent.com/55c8bfc24f7a08fbb7f431bd/9f053ad0-ab23-4d78-ba30-aa49ad40daef)

This checkbox must be checked before finalising the order.

While the checkout block _does_ allow for setting the terms and conditions page (and shows a link to it when set), it does not have parity with the current feature in the shortcode checkout flow.

The current implementation was done _intentionally_ as a result of discussion in this thread: p6q8Tx-1gJ-p2 (internal link). However, there are some aspects of the discussion in that thread that still might have been missed in the initial iteration.

**Comment by Luisxdrr76** [comment]
Hi!
Really excited to see where this goes since in EU its necesary by GDRP. 
Can you tell me aproximendly how long will it take or if this project isnt going anywere.
Thanks

**Comment by Aljullu** [comment]
Heads-up that in the last couple of days we received two duplicates of this issue #3482 and #3496.

**Comment by kamitey** [comment]
hello everyone, is there a solution to this problem?

**Comment by nerrad** [comment]
@kamitey no not yet.

**Comment by kamitey** [comment]
is it difficult to implement this function in code? or is it not wanted by the developer!

**Comment by nerrad** [comment]
It's a matter of priority in relation to all the other things we're working on. This issue will be updated when there's more information.

**Comment by kamitey** [comment]
i understand, thank you for your work

**Comment by roastingcoffee** [comment]
unfortunately in the EU it is illegal to not have those checkboxes ticked by the customer before purchase. so it can't be used... very good work though, looking forward to it being further developed.

**Comment by ghost** [comment]
Hey everyone! Is there any news when we can have checkbox for privacy policy/accept the agreements! Thanks for answering

**Comment by ghost** [comment]
Any news about checkbox for privacy policy/accept the agreements! When can we have it? Thanks for answering

**Comment by nerrad** [comment]
@arxalustab I appreciate the anticipation for it, you can be assured you'll see an update in here when there's anything new to post about.  Some form of resolving this is in our roadmap, but there is still no ETA.

**Comment by thuautp** [comment]
this feature is also requested in 3953845-zen

**Comment by mikejolley** [comment]
This is going to be part of the next version of the Checkout Block — see https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4319.
