### ISSUE TITLE
Stock display format setting and checkout block

### ISSUE THREAD

**Issue by rwaynick** [woocommerce/woocommerce-gutenberg-products-block#3259]
## Describe the bug
When setting the `Stock display format` to `Never show quantity remaining in stock` the Checkout block still shows stock.

## To reproduce

1. Go to WP Admin > WooCommerce > Settings > Products > Inventory.
2. Set `Stock display format` to `Never show quantity remaining in stock`.

<img width="681" alt="Screen Shot 2020-10-08 at 11 22 50 AM" src="https://user-images.githubusercontent.com/10882502/95471901-c9106900-0958-11eb-9533-fd1ba3310da6.png">

3. Add the Checkout block to your Checkout page.
4. Add a product with a stock quantity to the cart and go to checkout.

<img width="752" alt="Screen Shot 2020-10-08 at 11 22 35 AM" src="https://user-images.githubusercontent.com/10882502/95471922-d0d00d80-0958-11eb-8d0f-08e9fa6fa972.png">

5. Notice that the quantity is still shown.

![Screen Shot on 2020-10-08 at 11:23:39](https://user-images.githubusercontent.com/10882502/95471943-d62d5800-0958-11eb-8185-7c0e85639df5.jpg)

## Expected behavior
I'd expect no quantity to be shown on the checkout page since the `Stock display format` setting says, "This controls how stock quantities are displayed on the frontend".

### WordPress (please complete the following information):

<details>
### WordPress Environment ###

WordPress address (URL): http://wc.local
Site address (URL): http://wc.local
WC Version: 4.5.2
REST API Version: ✔ 4.5.2
WC Blocks Version: ✔ 3.5.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.5.0
Log Directory Writable: ✔
WP Version: 5.5.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 7.3.5
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.54.0
LibreSSL/2.6.5

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.5.2
WC Database Prefix: wp_
Total Database Size: 4.35MB
Database Data Size: 2.95MB
Database Index Size: 1.40MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.03MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 17
customize_changeset: 2
page: 9
post: 2
product: 14
revision: 8
shop_order: 1
wcpf_item: 4
wcpf_project: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (4) ###

Jetpack by WordPress.com: by Automattic – 9.0.1
Loco Translate: by Tim Whitlock – 2.4.3
WooCommerce Blocks: by Automattic – 3.5.0
WooCommerce: by Automattic – 4.5.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: ❌ Page does not contain the shortcode.
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.7.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 6
Oldest: 2020-09-29 13:35:07 +0000
Newest: 2020-10-08 14:02:59 +0000

Pending: 2
Oldest: 2020-10-08 14:26:53 +0000
Newest: 2020-10-09 14:02:59 +0000

</details>

### Desktop (please complete the following information):
* OS: macOS 10.15.7
* Browser: Chrome
* Version: 85.0.4183.121

**Comment by nerrad** [comment]
We may want to consider moving this to be a block level setting (cc @LevinMedia for thoughts on this).

**Comment by LevinMedia** [comment]
@nerrad I think in this case, it's best to respect the setting at the product level, and have be reflected through the entire experience, cart checkout etc.

**Comment by nerrad** [comment]
To be clear, I'm not suggesting we'd _remove_ the global setting just yet (although I realize my choice of the word "move" can easily be interpreted that way). I think it'd be handy to have it as a block level setting that brings it in context with how that affects the display and have it _linked_ to the global setting for now.

Let's say we _don't_ add a block setting, how would the merchant discover the _option_ to toggle that from the context of the block?

**Comment by nerrad** [comment]
>  it changes the display on other pages too

I'm realizing there's a bit more nuance to this setting. Do you know offhand all the pages this affects? I assumed initially this just applies to Cart and Checkout flows but maybe it impacts other displays too?

**Comment by mikejolley** [comment]
@nerrad @LevinMedia Should we perhaps clarify if this setting is supposed to be used globally, or just on product pages?

"Never show quantity remaining in stock" is misleading because stock is bound to be displayed (or revealed) at some point during the checkout process e.g. not enough stock for the cart. 

I think our current behaviour is to show the stock level if the product is low in stock. To me this makes sense. If that were hidden we'd run into problems with customers trying to purchase too much, or the qty boxes not being able to limit what can be selected for existing cart items. That could be frustrating experience.

**Comment by nerrad** [comment]
I agree with Mike here. There's a few approaches we could take here:

- Leave things as is for now and see if this is a significant enough problem for merchants and/or stores to address.
- Submit a patch to Core to clarify exactly where that option setting is applied. However, getting the messaging correct could be hard given how many places this setting is applied - including add to cart form on single product pages.  Since it's also exposed through the `wc_get_stock_html` template function, it's likely applied in any custom template/theme work as well. 
- Since it appears our implementation of this badge is not considering this global option at all, do we want to provide a local block setting that allows for control over the checkout and cart visibility of stock badges?

I'll surface this in our next backlog triage.

**Comment by garymurray** [comment]
I think the wording `Never show quantity remaining in stock` of the core setting creates confusion and is misleading here - it is not a case of `Never` as even if you select that - it still shows that there is "stock" of the item - it just does not show the quantity - see screenshot below of setting in action:

<img width="817" alt="Screenshot 2020-12-04 at 09 26 44" src="https://user-images.githubusercontent.com/10805911/101146379-d5d8d280-3612-11eb-84c1-a5ad90d7f109.png">

If the item goes out of stock - it still then shows the item as out-of-stock:

<img width="806" alt="Screenshot 2020-12-04 at 09 28 09" src="https://user-images.githubusercontent.com/10805911/101146550-091b6180-3613-11eb-8f96-8f1b9cb505a6.png">

Even when that setting is enabled.

I think the wording of that setting in core could change to something like: `Don't show stock quantity levels - unless an item is out of stock` 

On the cart side - we should then inherit that setting for now - so if someone selects it - we don't show the low stock notice in the cart as it's clear this setting is a global setting affecting more than just the cart. If we make an individual control for it in the cart we run into the same issues of does the setting:

- control just the block?
- control that setting for whole site?
- or does changing it at the core setting level change the block too?

With regards to how the qty controls etc would work in the cart - my understanding is that then if they had 1 item in their cart, and there was 1 item left in stock - they'd only be able to add 1 more item and then they'd not be able to add more.
