### ISSUE TITLE
Add styles for `.screen-reader-text` to cover themes that don't have that style defined

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#3265]
In [this comment](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3169#issuecomment-706653184) a user of the blocks reported an issue which upon investigation revealed that the theme for his site is not styling the `screen-reader-text` class.

It looks like [WooCommerce core](https://github.com/woocommerce/woocommerce/blob/16faf915e0055e48d4f0c2f647696716df957bbb/assets/css/woocommerce.scss#L41-L48) adds these styles, presumably as a fallback for themes that don't add the it (the blame for that code indicates so too).

This issue is for adding something similar for WooCommerce Blocks as well for cases where blocks are loaded on pages not loading the `woocommerce.scss` styles.

**Comment by haszari** [comment]
Reproduced the issue using a new [scaffolded theme based on underscores](https://developer.wordpress.org/cli/commands/scaffold/underscores/). After generating the theme, I deleted the screen-reader styles, then viewed checkout block and I see the bug:

<img width="338" alt="Screen Shot 2020-12-16 at 2 04 35 PM" src="https://user-images.githubusercontent.com/4167300/102291264-a24d5f00-3fa7-11eb-8023-3fce95cc6eec.png">

This is definitely an edge case, but still a good idea for us to include fallback styles.
