### ISSUE TITLE
Visual glitches in the Cart sidebar with IE11

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#3267]
## To reproduce
1. Go to a page with the Cart block with IE11.
2. Notice the panel down arrow overflows the text and the 'Proceed to Checkout' button text is not vertically aligned.

## Screenshots
![imatge](https://user-images.githubusercontent.com/3616980/95752930-1d8d4e80-0ca1-11eb-81fb-e96fe5509bf3.png)

**Comment by nerrad** [comment]
As a polish type issue, I'm going to leave for tackling before releasing Cart and Checkout blocks to wider audiences (when we can do this along with other polish fixes).

**Comment by nerrad** [comment]
I'm going to close this since IE11 support will be dropped within the next 6 months anyways.
