### ISSUE TITLE
(Translated): I cannot use another payment gateway other than paypal and off-line

### ISSUE THREAD

**Issue by PitsApp** [woocommerce/woocommerce-gutenberg-products-block#3270]

**Comment by senadir** [comment]
Hello @PitsApp 

I've translated your message using [Google translation](https://translate.google.com/) 

Currently, The Checkout block supports:

- Offline payment methods (like you mentioned).
- Paypal  Standard (that comes installed with WooCommerce).
- [Stripe](https://woocommerce.com/products/stripe/)

You can see the state of Checkout [on this page.](https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/)

What kind of payment gateway do you want to use? If you use a custom gateway, ask the developer to provide support for the new block.

In the meantime, I'm going to close to this, feel free to open it back if you have other questions.
