### ISSUE TITLE
Integration Tracking (WC Subscriptions): Add Recurring Coupon data to store coupon endpoint 

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#3273]
Similar to https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3262 we need to add coupon specific data to our coupon endpoint.

I'm thinking that this can be done generically without third party intervention, so far, the only use I can think of is:

- Adding Coupon type.

This would allow us to only show subscription specific coupons on the recurring total section of the cart.

Giving that this is the only thing needed, we shouldn't integrate this from Subscriptions sides, it can be done from our API, but I'm keeping this issue if we need other values that can only be derived from Subscriptions.

**Comment by senadir** [comment]
The coupon type value will be used from within WC Subscriptions, but won't be added by WC Subscriptions.

**Comment by haszari** [comment]
Is this issue covered by #3274 / #3399, or is additional work needed?

> This would allow us to only show subscription specific coupons on the recurring total section of the cart.

Based on this, I'm assuming the following:

- Woo core allows extensions to add new coupon `discount_type`s through a hook.
- WooCommerce Subscriptions adds a new coupon type for some subs-related reason.
- When #3399 is merged, custom extension coupon types will be transparently handled by the new API field `discount_type`.

Is that roughly correct @senadir ?

**Comment by senadir** [comment]
Your assessment is correct Rua.

The assumption was that we need to do extra work to expose this newly created data in `useStoreCartCoupons` but that was really covered. Closing this.
