### ISSUE TITLE
Integration Tracking (WC Subscriptions): Add coupon type to coupons endpoint

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#3274]
As mentioned in https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3273, we need the coupon type value in our coupons endpoint, this is needed to display them differently in certain places.

This is a generic issue, but it is needed for WC Subscriptions.

We need to:
- Add the value to our endpoints.
- Update our docs (cart, checkout, coupons).
- Update our hooks to pass along that value.
- Possibly update any test fixtures.

**Comment by haszari** [comment]
In progress on this @senadir - see draft PR above ↖️

**Comment by haszari** [comment]
While we're here, should we add coupon amount for completeness? Or is that dangerous/unnecessary? cc @nerrad @mikejolley for thoughts.

**Comment by haszari** [comment]
@senadir PR ready for review! I implemented this as a simple extension to the API to add the field, though I'm not clear on the specific need/use case for this, so possibly missed something.

I don't understand why Woo Subscriptions needs the coupon type. Can you add a comment here explaining what feature / flow in Subscriptions needs discount type in the API response? Thanks in advance 😄

**Comment by senadir** [comment]
> I don't understand why Woo Subscriptions needs the coupon type. Can you add a comment here explaining what feature / flow in Subscriptions needs discount type in the API response? Thanks in advance 😄

Of course, WCS introduce 4 new types of coupons:
- Fixed Sign-up fee discount
- % Sign-up fee discount
- Fixed recurring product discount.
- % recurring product discount

![image](https://user-images.githubusercontent.com/6165348/99090252-a8c67080-25ce-11eb-8c01-fe1b3c804c79.png)

Those discounts only apply to future subscription or only the current subscription, and based on that can be shown either up in Totals due today or in recurring totals.
It is also a useful field to have in the store API nevertheless.

**Comment by haszari** [comment]
Thanks @senadir - that all makes sense! TLDR it provides coupon types for the different components of subscription pricing 😄
