### ISSUE TITLE
Price slider goes back to 0 after moving the min handle

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#3282]
## Describe the bug
The minimum price handle of the price slider some times goes back to 0 after being moved. I'm not sure exactly why and when it happens. I wrote some testing steps below, but I could only reproduce it intermittently and only with Firefox, but it might affect other browsers.

## To reproduce

1. Go to a page with product filter blocks and All Products block.
2. Move the minimum price handle in the Filter products by price block.
3. Drop it right after it goes to a loading state.
4. Notice some times the handle moves back to 0.

## Screenshots
![Peek 2020-10-14 13-49](https://user-images.githubusercontent.com/3616980/95985216-9ec11e80-0e24-11eb-8b9e-dbc8c1db657c.gif)

**Comment by nerrad** [comment]
I'm unable to reproduce after trying for a few minutes. It's _possible_ this issue got fixed recently.
