### ISSUE TITLE
WooCommerce Blocks Plugin leaves white page for page builder

### ISSUE THREAD

**Issue by timbertactics** [woocommerce/woocommerce-gutenberg-products-block#3287]
Right now the woocommerce blocks plugin is leaving a white page for the WP Page builder plugin. 

While blocks in activated, the WPpage builder will full load on click and end at a white page.

Is there another plugin I can use instead of woocommerce blocks? or a fix that you know of? Thank you.

**Comment by timbertactics** [comment]
WPBakery page builder**

**Comment by nerrad** [comment]
Unfortunately, there's not enough information here for us to take any action and it sounds like it'd be better to have this reported to the WP Bakery plugin author. I suspect there is a JavaScript conflict, if you are able to get any errors in the browser console when you see the white page that'd be great.

It's also possible there are PHP errors happening on the server in which case any PHP errors that occur when the white page is displayed would also be useful information to know.

For now, I'm going to close this issue, but if you any extra information including reported errors (as mentioned above), please do reply here and if needed I can re-open.
