### ISSUE TITLE
Hand-picked Products bypasses tickets' required fields when using Box Office

### ISSUE THREAD

**Issue by robertocyrino** [woocommerce/woocommerce-gutenberg-products-block#3288]
## Describe the bug
When using the Hand-picked Products Block with a Simple Product marked as Ticket using the Box Office extension, the block allows the ticket to be added to cart without the required fields.

## To reproduce

1. Start with a store using [Box Office](https://github.com/woocommerce/woocommerce-box-office/releases);
2. Create a simple product, and mark the checkbox that says `Ticket`;

![https://d.pr/i/ovgPsI](https://d.pr/i/ovgPsI+) 
Full Size: https://d.pr/i/ovgPsI

3. Confirm that in the `Ticket Fields` section of your product's meta, you have at least one required field;

![https://d.pr/i/Wrjcon](https://d.pr/i/Wrjcon+) 
Full Size: https://d.pr/i/Wrjcon

3. Add a new page, add the Hand-picked Products block, and choose the product you created;
4. Publish changes, and visit the page;
5. Verify that it's possible to add the ticket to cart without the required fields.

![https://d.pr/i/4FrHrA](https://d.pr/i/4FrHrA+) 
Full Size: https://d.pr/i/4FrHrA

___

## Expected behavior
The expected behavior should be similar to Bookable products:
The button changes from `Add to Cart` to `Read More`, and directs customers to the product's page where they can choose a block, without adding it to the cart:

The same behavior should be in place for Box Office.

![https://d.pr/i/oMhcPu](https://d.pr/i/oMhcPu+) 
Full Size: https://d.pr/i/oMhcPu

### WordPress:
* Core version: 5.5.1
* WooCommerce version: 4.6.0
* WooCommerce Blocks version: 3.4.0
* Site language: en_US

### Desktop :
* OS: macOS 10.15.6
* Browser Firefox 81.0.2 (64-bit)

**Comment by nerrad** [comment]
Thanks for taking the time to report this @robertocyrino.

It looks like https://github.com/woocommerce/woocommerce/pull/27514 _might_ be the solution here?

**Comment by nerrad** [comment]
Given the [comment I left above](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3288#issuecomment-709264573) and that other extensions work as expected, this looks like something that the Box Office extension needs to resolve.
