### ISSUE TITLE
When tax is re-enabled for a store, orders can show $0.00 tax in cart & checkout (briefly)

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#3296]
## Describe the bug
If I have tax configured and set up, but disabled for my store, and then I re-enable it, the cart and checkout blocks may show `Including $0.00 in taxes` briefly.

<img width="817" alt="Screen Shot 2020-10-19 at 2 35 00 PM" src="https://user-images.githubusercontent.com/4167300/96392741-7b79e300-1219-11eb-8f0d-5045e1aa5652.png">
<img width="845" alt="Screen Shot 2020-10-19 at 2 35 40 PM" src="https://user-images.githubusercontent.com/4167300/96392747-7f0d6a00-1219-11eb-8368-f19225eb4f27.png">

Note - this is temporary. The incorrect tax calc goes away after refreshing the checkout (maybe not immediately). I'm guessing this won't affect new orders after changing the setting. I don't think this is a major issue – as it's uncommon for a store to enable or disable taxes in regular operation. 

Possibly there's some caching of prices/taxes in the cart/checkout/order API that goes stale when the global store setting is changed.

## To reproduce
1. Enable taxes and set up a 10% tax on all items / regions. 
   - select `No, I will enter prices exclusive of tax`
   - `Display prices in the shop == Including tax`
   - `Display prices during cart and checkout == Including tax`
2. Add something to cart. Note the included tax amount in cart / checkout totals.
3. Disable taxes globally across store `WooCommerce > Settings > General > Enable taxes` == off
4. Refresh cart & checkout (block) pages. Should see `Including $0.00 in taxes`.

## Expected behavior
- Cart block:
  - Totals area and line items should be consistent ($60.50 vs $55 in screenshots; line item should be $55).
  - Totals tax summary should not be displayed.
- Checkout block:
  - Order summary item price & subtotal should be consistent.
  - Totals tax summary should not be displayed.

### WordPress (please complete the following information):
* Core version: 5.5.1
* WooCommerce version: 4.7.0-dev
* WooCommerce Blocks version: 3.7.0-dev

**Comment by senadir** [comment]
I think it's a known issue related to cache that we fixed
reported here https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/2210
fixed here https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2275

It could be that the fix didn't cover this use case.

**Comment by haszari** [comment]
> It could be that the fix didn't cover this use case.

Thanks for the extra context @senadir  :)

**Comment by ralucaStan** [comment]
Closing this ticket as I could no longer reproduce it. Tested with WC Blocks Version 4.6.0
