### ISSUE TITLE
Filter out the `checkout-draft` status from all order queries by default except where explicitly needed by Woo Blocks

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#3301]
As a part of the work on the Checkout Block we implemented a new order status for orders: `checkout-draft`.  While this status is feature gated, there are some implications around it's usage in how its surfaced in numerous places in the WooCommerce core ui/ux and potential confusion around its implementation (example totals for draft orders being included in sales total for WooCommerce reports).

While we are internally working on making this an official order status in WooCommerce core (see pca54o-ib-p2) , in the interim let's explore how we can exclude this new status from all order queries by default except where explicitly implemented by WooCommerce blocks.

**Comment by senadir** [comment]
So far it feels it would be much easier to implement this from Core/wc-admin side compared to doing it from our side.
We add our status to wc_get_order_status which is used in a lot of places without being filtered again, backend, rest.
I got nowhere with my testing.

If we're okay with also removing this from the admin area, we might get somewhere.

**Comment by nerrad** [comment]
🤔 Would it be possible to hook into [this filter](https://github.com/woocommerce/woocommerce/blob/69d359c60c131f9cfd1afab36e06ef12cf3fc323/includes/class-wc-order-query.php#L85) to remove `checkout-draft` from any queries that are using it and then _explicitly_ add it back in via a filter on a later priority for queries we _do_ need to include `checkout-draft` for blocks specific queries. As far as I can tell, that would only be needed [for this logic](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/bc109615cb75288b8b73719981b4cf1e24f5a015/src/Domain/Services/DraftOrders.php#L153).

**Comment by Aljullu** [comment]
After some discussion, we decided to go for a "whack-a-mole" approach, so we will filter out draft orders for each individual feature. More context can be found in pca54o-zb-p2.

#3379 has been updated accordingly.
