### ISSUE TITLE
Cart and Checkout blocks WordPress plugin

### ISSUE THREAD

**Issue by jcalcagni2008** [woocommerce/woocommerce-gutenberg-products-block#3308]
## What do you like about the Cart & Checkout blocks?

The improvements to the look and feel and functionality provided by the referenced plug-in are extremely valuable.

## What do you think is missing from the Cart & Checkout blocks?

Unfortunately, the referenced plugin generates conflict or disables the main payment method that was already implemented in the store [https://labodegadebelen.aprendeyvende.net/](url) and also disables the functionality of the plugin that provides electronic invoicing.
I would be very grateful if you could indicate if there is any way to normalize the operation of the disabled plugins since they are fundamental to the operation of the store.

Features that conflict with the Cart and Checkout blocks WordPress plugin are not Woocommerce-default features, they were added through two plugins listed below:

- Main payment method, identified as **Pasarela Flow**. Ref. [https://www.flow.cl/woocommerce.php](url)
- Electronic invoicing, identified as **FACTO – Facturación Electrónica**, Ref. [https://wordpress.org/plugins/facto-facturacioacuten-electroacutenica/](url)

**Comment by senadir** [comment]
Hi @jcalcagni2008  👋🏻

Thanks so much for taking the time to leave some feedback - much appreciated! We make note of all feedback we receive and we also close issues with the feedback as active issues are used for bugs or feature/enhancements. Closing the issue does not mean that we don't note or review the feedback. Closed issues can also still be commented on.

We currently don't support all payment methods, but developers can integrate those payment methods with the new checkout via [this guide](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/extensibility/payment-method-integration.md).

You can also follow along with the [status of the Cart and Checkout Blocks in this doc](https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/).
