### ISSUE TITLE
1.3 doesn't work

### ISSUE THREAD

**Issue by el-presidente** [woocommerce/woocommerce-gutenberg-products-block#331]
Just updated to the new version and I cannot search for the Products block.

Rollback to 1.2 and it works fine.

Tested on two installs and the blocks are nowhere to be found..

**Comment by LevinMedia** [comment]
Hi @el-presidente per the change log, we've intentionally hidden the legacy "Products" in the block inserter for the 1.3 release. 

Most of it's functionality is now available using the new blocks included in this release. The new blocks have better functionality when searching for products and categories. 

The legacy "Products" block is still registered, so if you're using it on your pages, they'll still be available and editable.

**Comment by el-presidente** [comment]
Sorry but I've looked everywhere - I can see that it's a language bug, and changing this to English works. Please test end-to-end..

**Comment by GlennMartin1** [comment]
Likely a duplicate of https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/341

**Comment by LevinMedia** [comment]
Hi @el-presidente my apologies, I miss-understood your original comment. As @GlennMartin1 pointed out - we're tracking the issue you mentioned as a bug, and we'll have a patch out to remedy it today.
