### ISSUE TITLE
Sale badge translation not used by all blocks

### ISSUE THREAD

**Issue by melindahelt** [woocommerce/woocommerce-gutenberg-products-block#3318]
## Describe the bug
The Sale badge translation does not work consistently across all blocks.

## To reproduce

Translate the "SALE" badge
![](https://d.pr/i/ne92Fu+)Image Link: https://d.pr/i/ne92Fu

Check multiple blocks:
![](https://d.pr/i/Rfwqy2+)Image Link: https://d.pr/i/Rfwqy2

![](https://d.pr/i/rJcNDn+)Image Link: https://d.pr/i/rJcNDn

![](https://d.pr/i/onzld9+)Image Link: https://d.pr/i/onzld9

## Expected behavior
I expected the sale badge translation to work the same across all blocks

### WordPress (please complete the following information):
* Core version: 5.5.1
* Gutenberg version (if installed): N/A - core
* WooCommerce version: 4.6.1
* WooCommerce Blocks version: core
* Site language: English (but appears to be happening on other languages
* Any other plugins installed: Loco Translate |   | by Tim Whitlock – 2.4.3

**Comment by senadir** [comment]
👋  Hello @melindahelt 

All Products Block is a JS rendered block that uses another method of loading translation (not the usual gettext one).
It uses the `@wordpress/i18n` method; you can see the introduction here in [make.wordpress.org](https://make.wordpress.org/core/2018/11/09/new-javascript-i18n-support-in-wordpress/).
Translation plugins are yet to support this method. However, it would load fine if you're getting it from https://translate.wordpress.org.

You can also read this thread for more information pb0Spc-IS-p2

**Comment by senadir** [comment]
Since there's no action we can make to fix this, I'm going to label it as feedback and close it, you can always open this back if you think there's something we can do to fix this.
