### ISSUE TITLE
Incompatible with composer 2

### ISSUE THREAD

**Issue by leewillis77** [woocommerce/woocommerce-gutenberg-products-block#3321]
## Describe the bug
Composer 2 was [released recently](https://blog.packagist.com/composer-2-0-is-now-available/). WooCommerce is currently uninstallable with this as `woocommerce/woocommerce-blocks` depends on `composer/installers` locked at v1.7.0 which requires composer 1. 

```
✗ composer update
The "composer/installers" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires composer/installers 1.7.0 -> satisfiable by composer/installers[v1.7.0].
    - composer/installers v1.7.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 2
    - composer/installers v1.7.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - woocommerce/woocommerce-blocks v3.4.0 requires composer/installers 1.7.0 -> satisfiable by composer/installers[v1.7.0].
    - Root composer.json requires woocommerce/woocommerce-blocks 3.4.0 -> satisfiable by woocommerce/woocommerce-blocks[v3.4.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.
```

Updating the dependency on `composer/installers` to the latest release (v1.9.0) would be compatible with composer 1 and 2. 

## To reproduce
Update composer to composer v2 (See https://blog.packagist.com/composer-2-0-is-now-available/), and try and run `composer install` on WooCommerce.

## Expected behavior
Installable with composer 2.

### WordPress (please complete the following information):
* WooCommerce version: [e.g. 4.6.1]

**Comment by nerrad** [comment]
Thanks for the report!

**Comment by nerrad** [comment]
#3323 has been merged in that fixes this, but be aware that until this makes its way to WooCommerce core in a future release, you still won't be able to install **WooCommerce Core** using Composer 2 until WooCommerce core and other packages pulled in are updated. Currently after brief discussion with the team this will be a target for WooCommerce 4.8.

In the meantime, a workaround is to revert back to composer v1 for install of Woo Core.
