### ISSUE TITLE
phone required backend but not showing on the frontend

### ISSUE THREAD

**Issue by linuxandroid-xyz** [woocommerce/woocommerce-gutenberg-products-block#3334]
##

**Comment by senadir** [comment]
Phone field is part of the shipping step, so if you don't have shipping enabled, it won't show up.
Can you confirm that you have shipping enabled?

**Comment by theGreaterBayArea** [comment]
you are correct ! once setup the shiiping zone, phone colum shown up as 2.Shipping address above in the 3.Billing address !!!

**Comment by theGreaterBayArea** [comment]
can i make Shipping address (phone form required)   the default  Billing address , make 2.Shipping address AND 3.Billing address as ONE FORM instead of 2  annoying form ?

**Comment by theGreaterBayArea** [comment]
also , can i DISABLE the Shipping options shown up and make 2.Shipping address AND 3.Billing address as ONE FORM ( phone required ) instead of 2 annoying form

**Comment by theGreaterBayArea** [comment]
also , can i DISABLE the 4.Shipping options shown up and make 2.Shipping address AND 3.Billing address as ONE FORM ( phone required ) instead of separated annoying form

**Comment by nerrad** [comment]
HI there @linuxandroid-xyz  👋🏻

Sorry for the delay in responding. Thanks so much for taking the time to leave some feedback - much appreciated! We make note of all feedback we receive and we also close issues with the feedback as active issues are used for bugs or feature/enhancements. It does not mean that we don't note or review the feedback. Closed issues can also still be commented on.

Your requests regarding how Shipping and Billing options  and the related form will be considered as we iterate on the Cart and Checkout blocks but no promises on whether that's a feature we will support.
