### ISSUE TITLE
Folder names contain the tilde character

### ISSUE THREAD

**Issue by Hexadel** [woocommerce/woocommerce-gutenberg-products-block#3338]
**Prerequisites (mark completed items with an [x]):**
- [ x ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ x ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Good day, I was sent here by one of your Happiness engeneers. We are running Woocommerce latest version and have some issues deploying it to our servers through beanstalk. The problem is there are folder names that contain the ~ (tilde) character. 

The release attempt failed because your server responded with: "550 /public_html/redacted/wp-content/plugins/woocommerce/packages/woocommerce-blocks/build/vendors~atomic-block-components/price-frontend.js: Forbidden filename (Failed action: create file wp-content/plugins/woocommerce/packages/woocommerce-blocks/build/vendors~atomic-block-components/price-frontend.js)"

Your assistance in this regard would be greatly appreciated. 

Thank you

**Comment by Hexadel** [comment]
Thank you, in the meantime, is there anything we can do about this?

**Comment by nerrad** [comment]
Thanks for the report! The `~` character is an artifact of the bundle split/lazy loading feature we are using for our Webpack builds. Looks like we can change this via the `splitChunks.automaticNameDelimiter` option.

**Comment by mikejolley** [comment]
I couldn't find any other examples of tilde causing issues on the interwebs, but this does look like something we can easily modify, perhaps using hyphens instead which are more common as filenames.
