### ISSUE TITLE
Update @woocommerce/* packages, fixing an issue with non-English locales

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/woocommerce-gutenberg-products-block#334]
Update @woocommerce/* packages, fixing an issue with non-English locales

Per forum report: 

https://wordpress.org/support/topic/uncaught-typeerror-cannot-read-property-dow-of-undefined-error/

https://wordpress.org/support/topic/no-blocks-added-after-plugin-activation/#post-11097993

**Comment by ryelle** [comment]
Fixed in #333
