### ISSUE TITLE
Document prerequisites / requirements of release process (or fix script if no longer needed)

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#3340]
## Describe the bug
Possibly we still require GitHub `hub` to be installed, and a valid GitHub token in an environment variable. I think this used to be documented the releases doc.

Spotted this because I'm doing my first release in a little while from a clean-reinstall machine – `npm run deploy` fell over 😭 

```
npm run deploy

...

Error: hub is not installed. Install from https://github.com/github/hub
```

Not sure if this is a spurious check or not, maybe we need to fix the script.

**Comment by haszari** [comment]
We can probably get the relevant info from an [older version of the file](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3124/files) cc @nerrad  😄

**Comment by nerrad** [comment]
Oh shoot yeah it is needed because it's used to create the **GitHub Release** as a part of the deploy script. I missed that when I removed the doc. I was incorrectly thinking it was only used in our changelog script (but that's not the case).

**Comment by nerrad** [comment]
This is no longer relevant, additional notes around hub requirements were added to the [release checklist](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/.github/release-initial-checklist.md) at some point.
