### ISSUE TITLE
Taxes won't react to changes from billing form

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#3341]
Reported here https://wordpress.org/support/topic/taxes-wont-update-when-province-changes

When you have different taxes for different addresses, the rates and values won't update when you change the address.
They would update if:

- You have shipping enabled.
- You have "Use shipping for billing" checked.

This means that any changes in the billing step are not accounted for, the shopper can either checkout with no taxes, or with outdated taxes.

### Steps to reproduce

- Disable shipping.
- Setup some taxes rates, different ones.
- On checkout block, observe your current taxes, it can be zero or an initial sum if you already have an address saved.
- Change your address to one with a different tax.
- Taxes won't change.
- Checkout, taxes are still the same and didn't update with your address.
- See the order, it has the new address you entered.

**Comment by nerrad** [comment]
I've bumped the severity on this because if I'm reading things correctly, this potentially means purchases can be made without the correct taxes applied.
