### ISSUE TITLE
[GlobalStep - WooCommerce 4.7.0-rc.1][Win-IE11] Page Editor view appears half in grey color and Edit Block options appear misaligned  

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-gutenberg-products-block#3342]
## Bug Description:
Page Editor view appears half in grey color and Edit Block options appear misaligned  

## Environment:
Windows 10
Browser: IE11 (Version 11.1139.18362.0)

## Steps To Reproduce:
1. Create any test site using Jurassic Ninja.
1. Install and activate all required plugins.
1. Go to WooCommerce beta Tester.
1. Switch the WooCommerce version to 4.7.0-rc.1.
1. Assuming multiple products with different attributes are added in "All Products" section
1. Go to "Pages" section and click on "Add New" button.
1. Insert multiple blocks by tapping on "+" icon, say "All Products" "Hand-Picked" "Filter by Attributes" etc. 
 1. Observe that Page Editor view appears half in grey color and Edit Block options appear misaligned  

**Note:**
Observed same issue for New and Existing test site for all block options.

## Actual Result:
Page Editor view appears half in grey color and Edit Block options appear misaligned  

## Expected Result:
Page Editor view and Edit Block options should appear properly  

## Artifacts:
[#3342.zip](https://github.com/woocommerce/woocommerce-gutenberg-products-block/files/5458882/3342.zip)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by nerrad** [comment]
@Aljullu would you mind testing this and seeing if you can reproduce. This doesn't look like it's something specific to Blocks and might be GB related?

**Comment by nerrad** [comment]
I went ahead and tested this in BrowserStack and I can confirm this is not a WooCommerce Blocks or Storefront issue (I also swapped out the theme to Twenty Twenty to rule out possible storefront styling issues on IE11. This appears to be an issue with Gutenberg itself. I did a quick check and there are already a number of Gutenberg issues created for IE11 that appear to be related.
