### ISSUE TITLE
Woocommerce checkout condition wrapper is missing!

### ISSUE THREAD

**Issue by MirceaObreja** [woocommerce/woocommerce-gutenberg-products-block#3344]
## What do you like about the Cart & Checkout blocks?
Very nice block!
## What do you think is missing from the Cart & Checkout blocks?
A very important feature is missing! The Woocommerce checkout condition wrapper. So the customer has to tick this box and says that they have read the conditions. Can you add this to the block?

**Comment by nerrad** [comment]
Hi there!

Thanks for your feedback. Your request about a checkbox for indicating terms and conditions has been read is already reported and being tracked via #3258.
