### ISSUE TITLE
Update PR template for to prompt good titles/changelog entries

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#3345]
## Is your feature request related to a problem? Please describe.
We're considering moving to using PR titles directly in the product changelog. The current PR template has a changelog section which may be redundant now.

### Proposed fix
Assuming we stick with PR titles for changelog:

- Remove the changelog template.
- Add a text comment prompt to encourage thoughtful, concise and clear titles.
- Add a text comment prompt to ensure appropriate `type` labels are used (changelog uses these categories for headings).

**Comment by haszari** [comment]
While we're thinking about changelog process, there's an [older script in the repo that is no longer used](https://github.com/woocommerce/woocommerce-gutenberg-products-block/tree/trunk/bin/changelog) (?) - if this is not needed let's delete it. Feel free to spin off a separate issue if appropriate.

**Comment by nerrad** [comment]
Thanks for pro-actively creating this issue Rua, in light of the recent convo in our team about this, I've decided we're going to keep the option for an alternative changelog in the pull request description so I'm going to close this.
