### ISSUE TITLE
Introduce Attributes Context to Cart and Checkout

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#3347]
Seeing the increasing number of editor options in our blocks, we have a large collection of attributes.
And with the increasing complexity of those two blocks, we have a lot of sub-components, several levels down.
For those components to use the attributes, we end up [prop drilling](https://kentcdodds.com/blog/prop-drilling) 4 or 5 levels until an attribute reached the goal.
For this specific reason, we should consider introducing a new Context, `AttributesContext` that takes the block attributes and provide them to all components.

This context is going to be useful when building innerBlocks for those blocks, because we don't need to introduce redundant attributes for parent and child blocks, and can always access them via the parent block.

Gutenberg provides something slightly similar to this, called [Block Context API](https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/block-api/block-context.md), however. Under normal conditions, I'd say we wait until Block Context API reaches L-2, and we use it; However, block context serves different needs from ours and isn't compatible with our frontend React approach.

### Implemntation detail 
The context should be just below the Edit function, wrapping the `Block` component and receiving props in its place.
Because we're not going to change values in the frontend, adding this context should cause very low to no performance degradations at all.

As in initial iteration, I context should be read-only, any attributes changing should happen above it in the settings area.

**Comment by nerrad** [comment]
I'm wary about discarding using the Block Context API usage outright as it also supports php side exposure of the attributes to inner blocks being rendered php side. This _could_ be of value in an potential changes to our frontend rendering where we could do a hybrid react enhancement where some inner blocks retain their static rendering from PHP (from the inner blocks `save` value) and others are dynamically hydrated for React.

Putting aside that potential use-case (which may not even be possible), what about the Block Context API would not be compatible with our frontend React approach?

**Comment by senadir** [comment]
There're several hypotheses that I need to confirm before I get back to you on this, I have them based on the docs and spec.

The general idea I had is to implement Block Context Wrapper that uses regular context in the frontend and Block Context in the editor, up to prototyping to see how much effort might go into this.
Because Block Context is only provided by the editor, we need some kind of polyfill in the frontend.

### Hypothesis 1: Block Context API only works child-parent blocks.
I'm yet to confirm this, but looking at the docs, it seems to be the case. In that case, we can't use in our Cart and Checkout because they're a single block.

### Hypothesis 2: It's only provided as prop in the edit and render function.
This ties back to the first point, if it's only a prop on the edit function, we still need to do prop drilling, to a small scale at least, this is not a huge issue if we switch to innerBlocks for Cart and Checkout.

### Hypothesis 3: It solves a different problem.
Context API is there to solve a different problem, in which you have a dynamic value, think of it like ProductID in Single Product Block and all atomic blocks, for Cart and Checkout, our values are static and we're trying to reduce redundant attributes in child blocks, in which we might end up causing again if we use Context.

**Comment by nerrad** [comment]
Let me know what you find after you've investigated this at some point (probably can wait until next sprint).

**Comment by mikejolley** [comment]
Upon reading the docs for the Block Context API in Gutenberg I believe @senadir to be correct; it does solve a different problem (seems to be like how we expose props as attributes on the PHP side). Our use-case (dynamic blocks on the frontend) is unique.

However, I don't agree that we should introduce a new context specifically for attributes.

> Seeing the increasing number of editor options in our blocks, we have a large collection of attributes.
> And with the increasing complexity of those two blocks, we have a lot of sub-components, several levels down.

Whilst this is true, the larger blocks (cart and checkout as the obvious examples) have their own contexts already which are the ideal place to pass down attributes to subcomponents. What is the benefit of a new `AttributesContext` when we can already use the contexts we have in place?

Additionally, if we set a precedent for needing `AttributesContext`, that might complicate simpler blocks (e.g. filter blocks) that can cope quite easily with prop-drilling.

Are there use-cases I am missing?

**Comment by nerrad** [comment]
I'm going to close this for now. I think we need a concrete example to implement this idea in to help weigh the benefits of the abstraction. Closing the issue is not intended as a signal it's a bad idea. Once there's a great example where this can be demonstrated in we can re-open (or simply include it as a part of the proposed change).
