### ISSUE TITLE
Product image should have a 1px border if it's the placeholder

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#3354]
WooCommerce [sets a default 1px border](https://github.com/woocommerce/woocommerce/blob/master/assets/css/woocommerce.scss#L196-L198) to placeholder images in the Product grid:

![imatge](https://user-images.githubusercontent.com/3616980/97883263-ee5c8100-1d24-11eb-9a19-a9c9ea4c1c4c.png)

WC Blocks don't honor those styles and placeholders are shown without border:

_All Products:_
![imatge](https://user-images.githubusercontent.com/3616980/97883322-00d6ba80-1d25-11eb-9c1f-64cee1008ee0.png)

_Product grid:_
![imatge](https://user-images.githubusercontent.com/3616980/97883537-42fffc00-1d25-11eb-9bda-3d00f85e7d73.png)

## Expected result
I would expect the placeholder image to always show a border no matter if it's a WC Core product grid or WC Blocks.

The screenshots above are taken from the Varia theme. The issue is not reproducible in Storefront because it [prevents WC Core default styles from being registered](https://github.com/woocommerce/storefront/blob/trunk/inc/woocommerce/class-storefront-woocommerce.php#L29).

Ideally, when fixing this, we will review other blocks that render product/category images (Cart, Checkout, categories list, reviews, etc.) to ensure all of them are consistent.

**Comment by Aljullu** [comment]
@LevinMedia tagging you to get your feedback/confirmation on this issue. Do we want to be consistent with WC Core and display a border around the placeholder image or should we leave it without border?

**Comment by ghost** [comment]
@Aljullu 

I agree with the expected result and your comment. We should be consistent with WC Core and display a border around the place holder image.
