### ISSUE TITLE
Cart and Checkout blocks do not respect a product's catalog visibility status

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce-gutenberg-products-block#3370]
## Is your feature request related to a problem? Please describe.

If a product's catalog visibility is set as "hidden" then the product in the default cart does not link back to that product's page.

To reproduce..

1. Set a product's catalog visibility to "hidden"
![image](https://user-images.githubusercontent.com/507025/98128299-fd524900-1e74-11eb-9bd4-85473b36d2df.png)

2. Add that product to the cart... and view the cart block
The core cart will show the product title, but not link to the product's page. The cart block still shows a link:
![image](https://user-images.githubusercontent.com/507025/98130554-9c784000-1e77-11eb-9815-ef02b8f5fcdf.png)

## Describe the solution you'd like
When the product is not visible then there should be no link

**Comment by Aljullu** [comment]
Thanks for opening this issue @helgatheviking, I was able to reproduce it.

This is how a hidden product looks in the Cart block (notice the product name is a link):

![imatge](https://user-images.githubusercontent.com/3616980/98213946-1e369f00-1f46-11eb-970f-07564ec2ed22.png)

And this is in the Cart shortcode (notice the product name is not a link):

![imatge](https://user-images.githubusercontent.com/3616980/98213992-2f7fab80-1f46-11eb-829a-2bf167dce46e.png)

This issue also affects the Checkout block.
