### ISSUE TITLE
"Already have an account? Log in." URL goes to wp-admin Login, not Customer Login

### ISSUE THREAD

**Issue by hanislm** [woocommerce/woocommerce-gutenberg-products-block#3375]
## Describe the bug
In the Check Out page for Woocommerce Blocks, the "Already have an account? Log in." link does not take you to a customer login page but to the wp-admin login page. 

## To reproduce

1. Go to 'Checkout'
2. Click on 'Log in'
4. See error: goes to wp-admin login page rather than customer login

## Expected behavior
I expect a customer to be able to sign in, not to be sent to the wp-admin page

### WordPress (please complete the following information):
* Core version: [5.5.3]
* WooCommerce version: [ 4.6.1]
* WooCommerce Blocks version: [3.7.1]
* Site language: English
* Any other plugins installed:

### Desktop (please complete the following information):
* OS: [Windows 10]
* Browser [Firefox]
* Version [82.0.2]

### Smartphone (please complete the following information):
* Device: [e.g. iPhone X]
* OS: [e.g. iOS14.1]
* Browser [stock browser, safari]

**Comment by nerrad** [comment]
Hi @hanislm!

Thanks for taking the time to make this report! We are already aware of this issue and it's being tracked in #2918 so I'm going to close this one.
