### ISSUE TITLE
Delete method giving 500 error, for this endpoint /wc/store/cart/items

### ISSUE THREAD

**Issue by swapnilkuwar** [woocommerce/woocommerce-gutenberg-products-block#3378]
## woocommerce_rest_cart_error Unable to retrieve cart.
Delete method giving 500 error, for this endpoint /wc/store/cart/items.

## To reproduce

jQuery.ajax({
  type: 'delete',
  url: '/wp-json/wc/store/cart/items',
  xhrFields: {
     withCredentials: true
  }
});

## Expected behavior
Should Delete all items from the cart.

## Screenshots
![Screenshot-from-2020-11-06-20-11-40-png-1920×1080-](https://user-images.githubusercontent.com/37270346/98378711-664fe180-206c-11eb-881a-80a969d663ae.jpg)

## My Solution
I tried to load the cart in the get_cart_instance function of the CartController.php then this issue gets fixed.
```
public function get_cart_instance() {
   wc_load_cart();
   
   $cart = wc()->cart;
   if ( ! $cart || ! $cart instanceof \WC_Cart ) {
     throw new RouteException( 'woocommerce_rest_cart_error', __( 'Unable to retrieve cart.', 'woocommerce' ), 500 );
    }
   
    return $cart;
}
```

**Comment by nerrad** [comment]
Hi there @swapnilkuwar,

As noted in the [documentation for the StoreAPI](https://github.com/woocommerce/woocommerce-gutenberg-products-block/tree/trunk/src/StoreApi):

> This API is used internally by Blocks--it is still in flux and may be subject to revisions. There is currently no versioning system, and this API should therefore be used at your own risk. Eventually, it will be moved to the main WooCommerce REST API at which point it will be versioned and safe to use in other projects.

As a result, we're not providing support for any usage of this API outside of potential bugs with the current internal implementations of it.
