### ISSUE TITLE
Stripe Payment request button type not respected 

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#3387]
## Describe the bug
Payment request button type, an option that allows you to change the text or style of the payment request, is not being honoured on Cart and Checkout (even thou we pass the option to value from stripe settings).

## To reproduce

1. In Stripe settings, change the option value to branded or custom.
![image](https://user-images.githubusercontent.com/6165348/98669539-caff8a80-2351-11eb-806a-bff62d23a1cf.png)

2. See the button in the classic Cart block
![image](https://user-images.githubusercontent.com/6165348/98669595-dfdc1e00-2351-11eb-93d3-7b4bf28abcaa.png)

3. In our block, it's not being respected
![image](https://user-images.githubusercontent.com/6165348/98669644-ec607680-2351-11eb-993d-96016c30b35c.png)

**Comment by mikejolley** [comment]
I started to look at this and noticed these don't appear to be "official" types, certainly not mentioned in the docs here: 
https://stripe.com/docs/stripe-js/elements/payment-request-button

I think the Stripe extension may be handling these custom types:
https://github.com/woocommerce/woocommerce-gateway-stripe/blob/27381ccf22b35afe3a81eb9c111a71b5fcbe3a6d/assets/js/stripe-payment-request.js

Not sure if we can mirror that or not.

**Comment by nerrad** [comment]
Issue moved to [woocommerce/woocommerce-gateway-stripe #1503](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1503) via [**ZenHub**](https://www.zenhub.com/)
