### ISSUE TITLE
fail to track users through payment options (GTM)

### ISSUE THREAD

**Issue by method7** [woocommerce/woocommerce-gutenberg-products-block#3394]
We are using GTM to track users through the entire journey but we are not getting very good data form the payment options they choose - paypal / stripe so we have no idea what users are doing before they abandon. all we need to know is user interaction with fields - change events on card number, exp-date and ccv. These fields are in iframes and i am not able to find a reliable way to bind user events to these interactions - any insights to how we might achieve this tracking would be much apreciated.

**Comment by nerrad** [comment]
Thanks @method7 for documenting this as a separate issue (see [original feedback here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3386#issuecomment-724575760)). I'm just going to copy and paste part of my answer from the other issue here for context:

>  It is on our roadmap to ensure there is clear integration paths for analytics/commerce tracking software (or documentation on how to implement existing solutions).

While on our radar, _currently_ this is a customization/support type question that we won't be able to action on in this repository. So for now I'm going to close this issue but it does not mean we aren't aware of the need for this functionality for merchants. It's likely this will be addressed when we get to working on #3175.
