### ISSUE TITLE
No support for Stripe for WooCommerce by Payment Plugins

### ISSUE THREAD

**Issue by afizan75** [woocommerce/woocommerce-gutenberg-products-block#3395]
## What do you think is missing from the Cart & Checkout blocks?

Hello There, the design is a vast improvement from standard woocommerce checkout. However, my payment method is not loading. I used Stripe For WooCommerce by Payment Plugins. How can I solve this issue. Thanks

**Comment by nerrad** [comment]
HI there @afizan75  👋🏻

Thanks so much for taking the time to leave some feedback - much appreciated! We make note of all feedback we receive and we also close issues with the feedback as active issues are used for bugs or feature/enhancements. It does not mean that we don't note or review the feedback. Closed issues can also still be commented on.

The Cart and Checkout blocks are still in preview and there are a number of extensions and payment methods that are not integrated yet. WooCommerce Subscriptions is one of those extensions. You can follow [this document](https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/) to keep up to date with the latest status of the blocks.

There are also some [payment method integration](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/extensibility/payment-method-integration.md) docs that payment method extensions can use to integrate with the new blocks.
