### ISSUE TITLE
X-WC-Store-API-Nonce is invalid - Coupon Error Message?

### ISSUE THREAD

**Issue by method7** [woocommerce/woocommerce-gutenberg-products-block#3396]
for invalid coupon code input,

![Screenshot from 2020-11-10 11-46-35](https://user-images.githubusercontent.com/1433204/98849102-98858880-244a-11eb-912c-a5ebc5d09f7d.png)
we seem to be getting this error message with some users?  - for invalid coupon code input

**Comment by nerrad** [comment]
Thanks for the report @method7!

Do you happen to have any details on what browser this happens for users who get this notice? Also any other details around users this is happening for vs users that don't have issues would be useful (eg have multiple tabs open for the same site or coming back to the same open page with the cart after a day to resume things).

You can read more about the [`X-WC-Store-API-Nonce` header and tokens here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/src/StoreApi/docs/nonce-tokens.md). 

It is odd that this error is appearing intermittently for some shoppers but generally refreshing the page completely should fix it. It's definitely not a great experience for shoppers experiencing this though so we do want to try and figure out why this is happening. Any additional information you can contribute to help us reproduce this will be much appreciated!

**Comment by method7** [comment]
Hi @nerrad I appreciate your reply, 
It does seem to be a general issue, It appeared on my Linux / Firefox / Chrome / Chromium setup but has also been reported on Apple / Safari desktops - In my case refreshing the page did fix the error message and I have not seem it since - in the same browser.

We asked a couple of users to test the issue so they had never visited the site before (www.purenaturals.co.uk) both reported the issue and sent screen shots. Both used Safari v14 and MacOS v 10.15.7 and both witnessed this in the cart page - I have tried to reproduce this on the checkout page but I have run out of browsers now - clearing cache and cookies doesn't seem to help reproduce the issue.

For the record the code entered is incorrect so this should be a error message, correct codes don't seem to be causing the issue but i am not sure we have tested this.

**Comment by nerrad** [comment]
Thanks for the additional details - much appreciated!

**Comment by nerrad** [comment]
I realize it's been a while @method7 but we introduced some fixes related to how nonces were generated and applied in releases since this issue was created. Have you tested the latest releases of Blocks and do you still see this issue happening?

**Comment by brucelee90** [comment]
Any updates on this problem?

I have also encountered it on my site. If I do not accept cookies on my page This error occurs while there are no problems if I accept all cookies. Is there any workaround? I Haven't seen any solutions yet

**Comment by method7** [comment]
We updated last week and we are still seeing this error. - something to note though - it seems to occur on the first occasion, subsequent attempts to reproduce fail. Clearing cache or a new build seem to help reproduce it.

**Comment by budzanowski** [comment]
@method7 The latest version of the plugin was shipped with additional fixes regarding nonce handling. Could you please try again with the latest version.
