### ISSUE TITLE
Express Payment Request API (Stripe) Errors not surfaced

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#3402]
## Describe the bug
If an Express Payment method encounters an error (from the server side) nothing is exposed to the user in the cart/checkout.

## To reproduce

1. Create a product costing 0.01 and add to the cart. Ensure the total does not exceed 0.30. You may also need to reduce shipping costs.
2. Go to checkout and attempt to pay with Chrome Pay via Stripe.
3. Notice after attempting payment a generic processing error is shown. Network requests in the console will reveal an API error stating that the min order amount is 0.3.

## Expected behavior
There are 2 expectations here;

1. The error from the API needs to be exposed and output at the top of the checkout page.
2. Stripe Express Payment Methods should be disabled if the order total is less than 0.30.

**Comment by nerrad** [comment]
Another case of an error not showing up can be reproduced by:

Configure your WooCommerce -> Settings -> Accounts & Privacy settings like so:

<img width="1157" alt="Image 2020-11-13 at 4 37 07 PM" src="https://user-images.githubusercontent.com/1429108/99123643-92b8b000-25ce-11eb-9f7a-6c7933081831.png">

- Checkout using express payment (eg chrome pay) with an email address matching a user account already on the site.
- The express modal will display an error after 30s and not close and you'll see the following error in the network response (using browser network tab): `registration-error-email-exists` (status code 400).
