### ISSUE TITLE
Checkout allows order submit when there are no payment methods configured

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#3411]
## Describe the bug
If there are no payment methods for the store, the checkout block shows a warning message to shopper, but still allows the order to be submitted.

By comparison, the checkout shortcode doesn't allow order submit if there are no payment methods available. Attempting to place an order fails with `Invalid payment method` error:

<img width="1221" alt="Screen Shot 2020-11-17 at 9 14 45 AM" src="https://user-images.githubusercontent.com/4167300/99303649-24b60680-28b6-11eb-9503-e4e08516d2ed.png">

Spun off when investigating #3363

## To reproduce
1. Add a checkout block to a published page.
2. In `WooCommerce > Settings > Payments` disable all payment methods.
3. On front end, logged out (or incognito) add something to cart and proceed to checkout.
3. Complete checkout form and click `Place order`.

## Expected behavior
I'd expect behaviour consistent with existing checkout - can't submit an order with no payment methods.

Although I can imagine scenarios (edge cases) where submitting an order with no payment method might be desirable.

**Comment by senadir** [comment]
How are you submitting this order? I can't get past the error.
What defines `Checkout allows order submit` is it having the button enabled?

**Comment by haszari** [comment]
> How are you submitting this order? I can't get past the error.
> What defines Checkout allows order submit is it having the button enabled?

@senadir Hmm, not sure what happened, I can't reproduce now – I must have been confused, or maybe I had a stale checkout page render. Closing, sorry for the noise!
