### ISSUE TITLE
Compatibility Audit  for Twenty Twenty One Theme

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#3433]
This is the main issue for an audit of all compatibility for WooCommerce Blocks and the Twenty Twenty One theme.

> Before addressing the issues from this audit, make sure you are using the latest version of the [twenty twenty one theme](https://github.com/wordpress/twentytwentyone) in case any of these issues have been addressed.

**Note:** All my testing for the below was done in the Chrome browser. It's possible behaviour is different in different browsers so when completing the issues, please doublecheck how it looks in other browsers that we support and ensure any fixes don't impact other browser renderings either.

I've added this to the 3.8.1 milestone because we'll have to include this as a patch for WooCommerce Core 4.8 release so it's ready for WP 5.6.

So as we apply fixes we'll need to cherrypick for a 3.8.1 release (cc @budzanowski , as the release lead for the 3.8 branch you'll be called upon to do the 3.8.1 patch release when it's ready - I'll assist).

## Editor

These are the issues that show up in the editor:

### Text flow in Add to Cart buttons for Product Grid type blocks (affects frontend as well)

For all the product grid type blocks (including All Products) the text flow in the buttons is fairly wonky for the container restricting the size of the buttons in the block columns. Example screenshot for HandPicked Products:

<img width="773" alt="Image 2020-11-19 at 4 33 29 PM" src="https://user-images.githubusercontent.com/1429108/99726900-30a3f300-2a85-11eb-8660-97a7c48c8015.png">

### Jarring visual difference between "Add to Cart" button and "Read More" or "View Products" buttons in All Products Block.

Example:

<img width="871" alt="Image 2020-11-19 at 4 43 58 PM" src="https://user-images.githubusercontent.com/1429108/99727847-85943900-2a86-11eb-8d17-5c00c7358e8b.png">

### Cart and Checkout Blocks only display mobile view

I just wanted to note this as a part of the audit results but I'm not sure it's something we actually need to address as a part of this work.

### Price slider UI for Price Filter Block on frontend is wonky.

<img width="286" alt="Image 2020-11-19 at 4 56 37 PM" src="https://user-images.githubusercontent.com/1429108/99728987-423aca00-2a88-11eb-8fd5-9a601b40b91c.png">

### Wonky radio inputs for Cart and Checkout Blocks

<img width="699" alt="Image 2020-11-19 at 5 04 19 PM" src="https://user-images.githubusercontent.com/1429108/99729730-56cb9200-2a89-11eb-981f-d101e6f1b237.png">

**Comment by Aljullu** [comment]
One more issue:

* Active filters have too much padding:
![imatge](https://user-images.githubusercontent.com/3616980/99787152-abb9e780-2b1f-11eb-8e34-aaf11497181a.png)

**Comment by Aljullu** [comment]
@LevinMedia In Twenty Twenty One, range inputs have the same style for the 'active' and 'inactive' sides:

![imatge](https://user-images.githubusercontent.com/3616980/99796990-b5971700-2b2e-11eb-89b5-cd3696195398.png)

If we applied the same styles, this is how the Filter Products by Price block would look:

![imatge](https://user-images.githubusercontent.com/3616980/99797041-cf385e80-2b2e-11eb-98ae-a3c443035929.png)

Do you think that's ok? I feel it might be a bit confusing when the range has two thumbs so the 'active part' of the range is between them. I played a bit with it and I tried to make the 'inactive part' to be empty but bordered:

![imatge](https://user-images.githubusercontent.com/3616980/99797112-f5f69500-2b2e-11eb-963d-669e88760ac9.png)

Do you think that would work or is there something else we can do?

**Comment by Aljullu** [comment]
> ### Cart and Checkout Blocks only display mobile view
> 
> I just wanted to note this as a part of the audit results but I'm not sure it's something we actually need to address as a part of this work.

If the user toggles the alignment to 'wide' or 'full width', the large layout is displayed, so I would leave it as-is.

**Comment by nerrad** [comment]
Awesome! I missed that.

**Comment by mikejolley** [comment]
> Jarring visual difference between "Add to Cart" button and "Read More" or "View Products" buttons in All Products Block.

This is caused by styling on disabled buttons. We can work around it with targeted 2021 styles, or consider removing `<Disabled>`. Ill go with CSS for now.

**Comment by LevinMedia** [comment]
@Aljullu the updated price slider looks great, thanks!
<img width="236" alt="Screen Shot 2020-11-23 at 6 16 29 AM" src="https://user-images.githubusercontent.com/4500952/99972498-6ed63680-2d53-11eb-9841-8bc5eb8a4f84.png">
