### ISSUE TITLE
WP 5.6 – deprecation warnings in various blocks

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#3438]
Note: This is a megabug - adding all the deprecation warnings I see when testing against 5.6 here. If needed we can split these off to separate issues later.

## Describe the bug
Editing the `Featured Category` or `Featured Product` block shows some deprecation warnings in browser dev console:

- `[Warning] Using Toolbar without label prop is deprecated. Please use ToolbarGroup component instead. See: https://developer.wordpress.org/block-editor/components/toolbar/ (deprecated.min.js, line 2)`
- `[Warning] wp.components.IconButton is deprecated. Please use wp.components.Button instead. (deprecated.min.js, line 2)`
- `[Warning] Using custom components as toolbar controls is deprecated. Please use ToolbarItem or ToolbarButton components instead. See: https://developer.wordpress.org/block-editor/components/toolbar-button/#inside-blockcontrols (deprecated.min.js, line 2)`

Also similar issues with `Hand-picked Products` and `Products by Tag`:

- `[Warning] Using Toolbar without label prop is deprecated. Please use ToolbarGroup component instead. See: https://developer.wordpress.org/block-editor/components/toolbar/ (deprecated.min.js, line 2)`
- `[Warning] wp.components.IconButton is deprecated. Please use wp.components.Button instead. (deprecated.min.js, line 2)`

<img width="794" alt="Screen Shot 2020-11-23 at 1 16 22 PM" src="https://user-images.githubusercontent.com/4167300/99921266-1bcda500-2d8e-11eb-9b78-5250ef2fa8f9.png">

<img width="753" alt="Screen Shot 2020-11-23 at 1 16 11 PM" src="https://user-images.githubusercontent.com/4167300/99921258-11131000-2d8e-11eb-8cd0-30e7a979232b.png">

`Product Categories List` and `All Reviews` are both using `Button .isDefault`:

- `Button isDefault prop is deprecated. Please use isSecondary instead.`

## To reproduce
1. Go to block editor, open dev tools console.
2. Add a `Featured Category` block.
3. Click out of editing the inner button block to edit the  `Featured Category` block.
4. See console deprecated warnings.

### WordPress (please complete the following information):
* Core version: 5.6-RC.1
* Gutenberg version (if installed): n/a
* WooCommerce version: 4.8.0-beta.1
* WooCommerce Blocks version: 3.8.0

**Comment by Aljullu** [comment]
I updated the issue description to include that Products by Tag has the same issues as Hand-picked Products.

**Comment by opr** [comment]
Added #3479  for Products by Attribute and #3481 for Reviews by Product

**Comment by budzanowski** [comment]
Adding https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3485 for Reviews by Category.

**Comment by senadir** [comment]
Added Filter by Price https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3487

**Comment by Aljullu** [comment]
`wp.components.IconButton is deprecated. Please use wp.components.Button instead.` is fixed in #3547.

**Comment by haszari** [comment]
Took a dive into `Warning] Using custom components as toolbar controls is deprecated. Please use ToolbarItem or ToolbarButton components instead.` for `Featured Category`. 

The [custom component we're using is `MediaUpload` (etc)](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/assets/js/blocks/featured-category/block.js#L98-L116); this must be a deprecated pattern now. 

Digging into Gutenberg I see that the [core `Image` block now uses `MediaReplaceFlow`](https://github.com/WordPress/gutenberg/blob/f3c538578aa818e76dbe09445d0fb1678166086d/packages/block-library/src/image/image.js#L297-L305), maybe we can switch to that.

**Comment by senadir** [comment]
> Warning] Using custom components as toolbar controls is deprecated. Please use ToolbarItem or ToolbarButton components instead. for Featured Category.

Same problem affects Featured Product.

**Comment by haszari** [comment]
@senadir does your PR fix all these warnings or should we reopen this issue?

**Comment by senadir** [comment]
All that was reported yeah, did I miss anything?

**Comment by haszari** [comment]
> All that was reported yeah, did I miss anything?

Looks like you got 'em all! If there are any more we can fix them as they come up 👍
