### ISSUE TITLE
If coupons become invalid between applying to a cart and checking out, the order continues without notifying the customer

### ISSUE THREAD

**Issue by opr** [woocommerce/woocommerce-gutenberg-products-block#3447]
## Describe the bug

In some cases, when using coupons that become invalid between applying them to the basket and completing the checkout, the order complete, the customer is not notified, and the discount is not applied.

##### 🐛 Limited-use coupons
Tested with a single-use coupon being applied to cart A, but without completing checkout. Create a new incognito session and apply the coupon to cart B. Complete check out on cart B. Return to cart A and complete checkout. Checkout fails, but an account is created.

##### 🐛 Expiring coupons
When a coupon expires after applying to the cart but before completing the checkout, the order completes without the discount being applied and the user is still created. Core behaviour is: Returns user to the checkout page with an error message, no order or account is created.

##### 🐛 Coupons with minimum spend
When a coupon is modified to have a minimum spend value after it has been applied to a cart, the checkout continues without applying the discount. The order is created and the discount is not applied. Core behaviour is: Returns user to the checkout page with an error message, no order or account is created.

##### 🐛 Coupons with product restriction
If a coupon is modified to have a product restriction after it has been applied to a cart, then the checkout continues without applying the discount. The order is created and the discount is not applied. Core behaviour is: Returns user to the checkout page with an error message, no order or account is created.

## To reproduce
Steps to reproduce the behaviour:

1. Create a coupon with no expiry date, minimum spend restriction, product restrictions, or usage limit.
2. Add a product to the cart, go to the checkout block, then apply the coupon.
3. Repeat these steps several times, with different coupons and new baskets each time.
- Modify the coupon's expiry date to be in the past.
- Modify the allowed products for the coupon, to ensure it is not applicable to the cart you're testing against.
- Create a coupon with a single use. Apply it to this test cart. Then use it on another, unrelated cart and complete the checkout.
- Add a minimum order value to the coupon, that is above the cart's value.
4. Complete checkout

## Expected behaviour
The checkout should fail, and inform the shopper that their coupon was invalid. Additionally, no account should be created if the "Create account?" checkbox is on.

**Comment by mikejolley** [comment]
Looks like they are removed silently when checkout syncs with the cart. You can see them removing themselves if you refresh the checkout instead of placing order.
