### ISSUE TITLE
Columns disappear from pages/posts

### ISSUE THREAD

**Issue by desnum** [woocommerce/woocommerce-gutenberg-products-block#345]
**Bug description**
When [WooCommerce Blocks plugin](https://wordpress.org/plugins/woo-gutenberg-products-block/) is activated, columns created on pages/posts don't work anymore 

**To Reproduce**

1. Create a new page
2. Add a column block using the Gutenberg editor. Set to four columns (to see more clearly what happens)
3. Publish page to see that the columns are on the front-end
4. Install and activate WooCommerce Blocks plugin
5. Refresh published page with columns to see that the 4 columns are now stacked on top of each other.

**Expected behavior**
Columns previously created on pages/posts should still appear beside each other, as opposed to stacked on top of each other

**Screenshots**
Before:
<img width="1228" alt="screen shot 2019-01-17 at 1 03 45 pm" src="https://user-images.githubusercontent.com/43796228/51338667-6f675d00-1a58-11e9-89ab-3e2133d7a995.png">

After:
<img width="1320" alt="screen shot 2019-01-17 at 1 04 06 pm" src="https://user-images.githubusercontent.com/43796228/51338675-755d3e00-1a58-11e9-874c-63852b9d72f2.png">

**Desktop:**

* OS: MacOS High Sierra
* Browser: Chrome
* Version: 71.0.3578.98

**Additional context**
Reported by a user in hc-9586184, and I was able to replicate issue.

**Comment by GlennMartin1** [comment]
This is resolved in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/342
