### ISSUE TITLE
All Products block not loading in the editor

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#3456]
The All Products block is not rendering in the editor on WP 5.6b4 and Gutenberg disabled.

## To reproduce
1. Create a post with the All Products block.
2. Notice the block doesn't load in the editor (but it works fine in the frontend).
![imatge](https://user-images.githubusercontent.com/3616980/100079824-6b22dc80-2e45-11eb-9bb1-37c98c7790a4.png)
3. Notice there are several errors in the console:
![imatge](https://user-images.githubusercontent.com/3616980/100080101-b5a45900-2e45-11eb-9697-d1788d7e37e2.png)

@nerrad I added this as a blocker of 3.9 because I could reproduce it in `release/3.9` in addition to `trunk`.

`release/3.8.1` seems to be unaffected.

**Comment by Aljullu** [comment]
False alarm, I think it was an issue with dependencies.

**Comment by nerrad** [comment]
I noticed I got this error when switching branches and rebuilding. If I didn't do a hard refresh of the browser the error would show up. Were you testing in Chrome? I wonder if chrome is getting more aggressive with asset caches, I'm also wondering if the webpack chunks are being cached and that's a potential problem for users updating and then seeing the error?

**Comment by Aljullu** [comment]
I was testing with Firefox. I couldn't get clear testing steps because when building from scratch in a clean environment and refreshing the browser, I wasn't able to reproduce agree. Agree that it seems to be related to switching branches/rebuilding (maybe when dependencies are different between branches?).

I will keep an eye on this, but it might be something only reproducible in a dev environment.
