### ISSUE TITLE
Top Rated block and Featured Products block do not show products from all categories if filtered by categories

### ISSUE THREAD

**Issue by ahmadbaig1** [woocommerce/woocommerce-gutenberg-products-block#3458]
## Describe the bug
When these blocks are used "Top Rated" and "Featured products" and you enable the option "Filter by Product Category" (select 2 or more categories), then to show a product from each category you enable the option "Show products from All Selected Categories", the blocks stop rendering products, they just show "Block Rendered as Empty".

Here are some screenshots-
<img width="319" alt="Screenshot at Nov 25 01-40-19" src="https://user-images.githubusercontent.com/40609190/100146037-479c7800-2ebf-11eb-8907-8b7e1a4fdcf9.png">
<img width="1524" alt="Screenshot at Nov 25 01-40-48" src="https://user-images.githubusercontent.com/40609190/100146052-4e2aef80-2ebf-11eb-9e1c-7d344d7de2f8.png">

## To reproduce
Steps to reproduce the behaviour:

1. Go to a page on your site.
2. Make sure you have multiple products under different categories.
3. Add the "Top Rated" or "Featured Products" block, filter by category and select option to show products from all categories.
4. The block will show "Block rendered empty", and even the front-end won't show any products.

## Expected behavior
The expected behaviour is that the blocks should show the top-rated or featured products from all categories.
But, instead, they stop showing any products at all.

## Screenshots
Added above.

### WordPress:
* Core version: 5.5.3
* Gutenberg version (if installed): 9.3.0
* WooCommerce version: 4.7.0
* WooCommerce Blocks version:-
* Site language: English

### Desktop (please complete the following information):
* OS: macOS
* Browser: Chrome
* Version 86.0.4240.111

**Comment by mikejolley** [comment]
@ahmadbaig1 To confirm, did you have products in the store which were in BOTH "Art" and "Ceramics" categories? This type of query is "AND" based, so only products assigned to both categories would be displayed.

If that's the case, the only issue here is we are missing a more clear placeholder when no products match.

**Comment by ahmadbaig1** [comment]
@mikejolley No, I think I had products in different categories, where they did not overlap.
However, this is a bit misleading in that case. If I want to show top-rated products from several categories, there's no way to do it. Selecting "Any category" shows all products from a single category, not giving a chance to products from the other selected categories, and selecting "All categories" will only show it if the categories overlap, which I believe is a less likely scenario.

**Comment by mikejolley** [comment]
> Selecting "Any category" shows all products from a single category, not giving a chance to products from the other selected categories

Surely this depends on how they are sorted? Products from all selected categories would display, but the order would not be randomised.

**Comment by ahmadbaig1** [comment]
Oh, alright, thanks for clearing it up!

**Comment by nerrad** [comment]
Since it seems like this issue is resolved, I'm going to go ahead and close it.
