### ISSUE TITLE
Dedicated block for featured products grid

### ISSUE THREAD

**Issue by danielcharrua** [woocommerce/woocommerce-gutenberg-products-block#3466]
### Is your feature request related to a problem? Please describe.
I'm always frustrated when trying to add a grid of featured products block using Gutenberg (there is no such block).

### Describe the solution you'd like
I think that would be great for you to add a **dedicated featured product(S) block grid** to list **ONLY** featured products .

### Describe alternatives you've considered
I usually ended up using the old shortcode, but it will not render on the backend.
`[products limit="4" columns="2" visibility="featured" ]`

**Comment by mikejolley** [comment]
As a workaround, you could create a featured category and use the "Products by Category" block instead. This renders a grid.

I'm not sure if the concept of "featured products" is something that will be supported forever @nerrad? I've not seen much mention of that attribute in designs and such. Seems like it could quite easily be replaced by taxonomies.

**Comment by nerrad** [comment]
To make sure I'm on the same page about what's being talked about here, when we refer to "featured products" we're talking about products that have this checkbox checked right?

![Image 2020-11-26 at 1 31 57 PM](https://user-images.githubusercontent.com/1429108/100383576-e4f4ca80-2feb-11eb-8bd4-641190f415f6.jpg)

While I agree it could be replaced by taxonomies, it's also likely something that would have value in remaining a standard flag  for products that is a known meta value across all products. Of course, this could also be accomplished by simply having a protected term for a taxonomy as well.

I don't feel that this is something I can weigh in on it's potential future application. cc @gary or @LevinMedia do you have additional thoughts on whether this product option is something we plan to support long term and develop for or not?

**Comment by danielcharrua** [comment]
Thank you both for your thoughts, I agree that I can manage this trough categories, but as a standard WooCommerce feature I think that would be great to have a product grid block just for showing featured products.

@nerrad I’m talking exactly of the screenshot you’ve posted. This also can be selected when listing all products and select the star icon.

As I see it from now, the featured product capability would be useless on building an e-commerce website using blocks, so why have this feature if is not supported by blocks? Just for backward compatibility?

**Comment by garymurray** [comment]
@peterfabian can you provide any insights into what the purpose of [this option is](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3466#issuecomment-734438167) (other than to mark the product as featured) i.e. is this used in any other way by WooCommerce core itself - or is this something that themes can hook into for showcasing featured products?

To add to that - do we have any way of telling how many products are created that make use of this option?

Ultimately I'd just like to understand if this is something that we'll be keeping in Core and as a result - should we be looking to create a block that makes use of this option and/or add it to our Featured Product Block as an option perhaps.

**Comment by peterfabian** [comment]
Apologies for missing the ping. As far as I know, tagging products as featured is just a way to include them in the featured products shortcode. As far as I know, and judging by a quick search over the codebase, it serves no other purpose. There is also a related styling class, so people can make these products stand out more easily in their theme if they wish so.

As for removing it--it's not really an easy option, as we need to remain backward compatible, but we can potentially deprecate it. However, I'm not aware of any data showing if people are using this feature or not, so maybe we could add it to the tracker if we want to get some insights? Another option would be to just see if people are requesting this block and add it if it's high on the list of requested items.

**Comment by RavanH** [comment]
Yes please. The shortcode `[products visibility="featured"]` works and even `[featured_products]` still does the trick but it's not ideal for the block editor. Why is this not treated the same as the On Sale block for `[sale_products]` and `[products on_sale=true]` shortcodes?

**Comment by nerrad** [comment]
Just highlighting that the new [Products Block](https://github.com/woocommerce/woocommerce/issues/42616) will have [support for restricting the results to featured products.](https://github.com/woocommerce/woocommerce/issues/42539).  I'm going to leave this issue closed because it will be handled by woocommerce/woocommerce#42539.

**Comment by RavanH** [comment]
Excellent news! Thanks @nerrad :)
