### ISSUE TITLE
Hand-picked Products block removes part of already selected products

### ISSUE THREAD

**Issue by turansadri** [woocommerce/woocommerce-gutenberg-products-block#3467]
Hand-picked Products block removes some of the already selected products when using search below. Usually only 10 products are left.

## Steps to reproduce the behavior:
1. Add Hand-picked Products block to page
![Screenshot 2020-11-26 at 14 34 28](https://user-images.githubusercontent.com/6302228/100354852-761e6e00-2ff9-11eb-8a0e-d78bbd53f6a0.png)
2. Select more than 10 products for example 20 by checking the checkboxes. The products will appear as "tag list" above.
![Screenshot 2020-11-26 at 14 34 57](https://user-images.githubusercontent.com/6302228/100354874-7c144f00-2ff9-11eb-9691-e13fcd536b6c.png)
3. Now activate the Search for products to display and search for products. The list of previously selected products will shrink to 10.
![Screenshot 2020-11-26 at 14 35 11](https://user-images.githubusercontent.com/6302228/100354889-820a3000-2ff9-11eb-956a-e008e33eec53.png)
4. Add a checkbox to the product which you had searched and save
![Screenshot 2020-11-26 at 14 35 18](https://user-images.githubusercontent.com/6302228/100354913-89313e00-2ff9-11eb-8e28-a26b04867580.png)
5. You now have 11 products instead of 21 (if you had 20 before searching)
![Screenshot 2020-11-26 at 14 35 47](https://user-images.githubusercontent.com/6302228/100354927-8df5f200-2ff9-11eb-80da-364dc1725f9c.png)

## Expected behavior
It would be expected that selected products won't get deleted when using search in same block.

### WordPress
* Core version: 5.4.2 (tested also with 5.5.3
* WooCommerce version: 4.7.1 (tested also with 4.5.1)
* WooCommerce Blocks version: 3.9.0 (tested also without with the one included in WP)
* Site language: English (United States)
* Any other plugins installed: Advanced Custom Fields Pro 5.9.3 (all other plugins disabled)

### Desktop (please complete the following information):
* OS: macOS Mojave 10.14.6
* Browser Chrome
* Version 87.0.4280.67 (Official Build) (x86_64)

Also tested with latest Safari

**Comment by mikejolley** [comment]
This only happens with catalogs larger than 100. If you end Assets.php and change:

```
'isLargeCatalog'                => $product_counts->publish > 100,
```

To 10, you can reproduce this. Just select 11 products then search. After the search completes, only 10 selections remain.

**Comment by turansadri** [comment]
@mikejolley is there a workaround for this? I'd like to be able to use the search also in larger catalogs.

**Comment by nerrad** [comment]
@mikejolley given the work to move `isLargeCatalog` to the client side as a calculated setting, should we pass along a filterable threshold value for how many products is considered a large catalog (default to 100) in the settings?

**Comment by mikejolley** [comment]
@nerrad I think we should make the call on this one. It would be nice if we only needed one set of logic, but I realise that might seem slower on small catalogs. Unless we prefetch it somehow.

**Comment by dfaligertwood** [comment]
I've also come across this problem. IDK if it helps, but I noticed that the client-side javascript is running, is sending a get request with all the items selected:
```
/wp-json/wc/store/products?catalog_visibility=any&include[0]=2689&include[1]=2693&include[2]=2695&include[3]=8373&include[4]=8292&include[5]=8218&include[6]=7196&include[7]=7130&include[8]=6980&include[9]=6978&include[10]=6976&include[11]=6974&include[12]=6548&include[13]=2705&_locale=user
```

but because it hasn't set a per_page setting, it is only receiving 10 items in response, and it isn't following the next page link. Might this be the source of the issue?

**Comment by dfaligertwood** [comment]
Just following up - I may be completely wrong as I can't work out how to step through the original code/set a breakpoint, but it looks like when the SearchListControl from woocommerce/woocommerce-admin calls onChange, it is only sending 10 items, because of the incorrect API call above. Is it worth raising a bug with them?

**Comment by mikejolley** [comment]
I believe this was fixed in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/4534 :)
