### ISSUE TITLE
Products by tag: JS warning when adding the block

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#3474]
There is a JS warning from react-dom when adding the Products by tag block into a page.

## To reproduce
1. Create a new page and add a Products by tag block.
2. In the browser console, you should see the following error:
`Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.`

This warning doesn't affect the block functionality, it still works as expected.

## Screenshots
![imatge](https://user-images.githubusercontent.com/3616980/100440792-b9361b00-30a5-11eb-9623-108258763dbc.png)

### WordPress (please complete the following information):
* Core version: 5.6-rc1
* Gutenberg version (if installed): it happens when Gutenberg is disabled and with Gutenberg 9.4.1.
* WooCommerce version: 4.9.0-dev
* WooCommerce Blocks version: `trunk`

**Comment by nerrad** [comment]
I suspect this is in progress fetches that are happening when the component is unmounting.

**Comment by Aljullu** [comment]
I can still reproduce, so removing the `stale` label.

**Comment by Aljullu** [comment]
I'm not able to reproduce this anymore, so leaving the issue closed.
