### ISSUE TITLE
Evaluate if we should expose `register_endpoint_data` in a public function.

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#3477]
Currently, extensions can extend our StoreAPI by fetching our `ExtendRestApi` from our DI.

```php
<?php
use Automattic\WooCommerce\Blocks\Package;
use Automattic\WooCommerce\Blocks\Domain\Services\ExtendRestApi;

$extend = Package::container()->get( ExtendRestApi::class );
$extend->register_endpoint_data( ... );
```

We should consider if this is the right approach.
If we want to make this available in a global function or some other solution.

**Comment by mikejolley** [comment]
We should agree on a public API for this before it hits core. The `Blocks` namespace here should probably not be exposed as it doesn't make sense in the context of woo core.
