### ISSUE TITLE
WP 5.6 – Products by attribute block deprecation notices

### ISSUE THREAD

**Issue by opr** [woocommerce/woocommerce-gutenberg-products-block#3479]
This is a meta bug for all deprecation notices of the Products by attribute block with WP 5.6.

## To reproduce

1. Add a Products by attribute block to a new page.
2. Check the browser console and notice the warning:
* `Using Toolbar without label prop is deprecated. Please use ToolbarGroup component instead. See: https://developer.wordpress.org/block-editor/components/toolbar/ `
3. Choose an attribute, then a value
4. Check the browser console and notice the warning:
* `wp.components.IconButton is deprecated. Please use wp.components.Button instead. `

None of these warnings affect the block functionality, it still works as expected.

### WordPress (please complete the following information):
* Core version: 5.6-rc1
* Gutenberg version (if installed): it happens when Gutenberg is disabled and with Gutenberg 9.4.1.
* WooCommerce version: 4.7.1
* WooCommerce Blocks version: `trunk`

**Comment by nerrad** [comment]
The Products by Category block shares similar code so documenting the same deprecated notices here from my testing with the block:

> wp.components.IconButton is deprecated. Please use wp.components.Button instead. 

and 

> Using Toolbar without label prop is deprecated. Please use ToolbarGroup component instead.

**Comment by Aljullu** [comment]
I wasn't able to reproduce `wp.components.IconButton is deprecated. Please use wp.components.Button instead.` anymore. Maybe it was fixed when we updated `@woocommerce/components`?

**Comment by nerrad** [comment]
Not sure about why the deprecation notice wouldn't be appearing but I do notice via a search of the codebase that there are instances of `IconButton` being imported from `@wordpress/components`. We could probably just convert those to use `Button`?

**Comment by Aljullu** [comment]
@nerrad did you search in `trunk` or in the branch of https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3547? We had some components which directly imported `IconButton` from `@wordpress/components` but they are being updated in that pull.

**Comment by nerrad** [comment]
`trunk` not #3547. Sorry I didn't realize #3547 was addressing this :)
