### ISSUE TITLE
Reviews by product - React warning when changing product in the block settings

### ISSUE THREAD

**Issue by opr** [woocommerce/woocommerce-gutenberg-products-block#3480]
## Describe the bug
When changing from a product with no reviews, to a product without reviews the following React warning is output in the console:

`Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in WithProduct(NoReviewsPlaceholder) (created by EditorBlock)`

## To reproduce

1. Go to a page and add the Reviews by product block and select a product with 0 reviews.
2. Save and reload the page.
3. Edit the block settings, go to Product and choose a product that has reviews.
4. See warning in the JS console.

## Expected behavior
No warning.

### WordPress (please complete the following information):
* Core version: 5.6-rc1
* Gutenberg version (if installed): it happens when Gutenberg is disabled and with Gutenberg 9.4.1.
* WooCommerce version: 4.7.1
* WooCommerce Blocks version: `trunk`

**Comment by nerrad** [comment]
I got a similar error when testing the Products by Category Block:

> Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in WithCategories(Component) (created by r)

Since `WithCategories` and `WithProducts` were modeled after each other, I expect the fix will be similar for both so including this in this issue.
