### ISSUE TITLE
casilla aceptar terminos y condiciones

### ISSUE THREAD

**Issue by robertovall** [woocommerce/woocommerce-gutenberg-products-block#3482]
Hola he hecho una pagina con su bloque carrito y checkout y no se la manera de poner la casilla de acepto términos y condiciones (obligatoria para poder hacer la compra) saludos

**Comment by Aljullu** [comment]
¡Hola @robertovall, gracias por tu sugerencia! Tenemos un issue abierto para añadir una casilla de "He leído y acepto los términos" (#3258), que parece ser tu petición, así que voy a cerrar este issue como duplicado. Puedes seguir #3258 para estar al día del progreso.

---

Hi @robertovall, thanks for your suggestion! We have an open issue to track adding a checkbox for "I have read and agree to terms" (#3258), which seems to be your request, so I will close this issue as a duplicate. You can follow #3258 to be aware of the progress.
