### ISSUE TITLE
WP 5.6 - Reviews By Category

### ISSUE THREAD

**Issue by budzanowski** [woocommerce/woocommerce-gutenberg-products-block#3485]
This is a meta bug for all deprecation notices of the Reviews by Category block with WP 5.6.

None of these warnings affect the block functionality, it still works as expected.

## To reproduce

1. Add the Reviews by Category block to a new page.
2. Go to the block settings UI, you should see the following console messages.
 - `Button isDefault prop is deprecated. Please use isSecondary instead.`
 - `Using Toolbar without label prop is deprecated. Please use ToolbarGroup component instead. See: https://developer.wordpress.org/block-editor/components/toolbar/ `
3. Open Category panel and select a category. The following message will appear.
 - `wp.components.IconButton is deprecated. Please use wp.components.Button instead.`

## Environment:
* WP Core version: 5.6-RC1-49707
* WooCommerce version: 4.9.0-dev
* WooCommerce Blocks version: 3.9.0
* Storefront: 2.9.0

**Comment by Aljullu** [comment]
I wasn't able to reproduce `wp.components.IconButton is deprecated. Please use wp.components.Button instead.` anymore. Maybe it was fixed when we updated `@woocommerce/components`?

**Comment by budzanowski** [comment]
That makes sense. Closing. If it still the issue then we will stumble on it anyhow.

**Comment by Aljullu** [comment]
@budzanowski I'm still able to reproduce these two errors:

![imatge](https://user-images.githubusercontent.com/3616980/102068352-a12bfe80-3dfc-11eb-9bd8-1fe6ebc603a7.png)

I think only the `IconButton` warning was fixed. Reopening the issue for now, but feel free to close it if you feel that was a mistake.
