### ISSUE TITLE
checkout page

### ISSUE THREAD

**Issue by kamitey** [woocommerce/woocommerce-gutenberg-products-block#3496]
## What do you like about the Cart & Checkout blocks?
compact and clean

## What do you think is missing from the Cart & Checkout blocks?

In europe you have to confirm the terms and conditions before you sending the order.
A chekbox over the butten 'order now' with the text: 'I agree and confirm the terms and conditions.'

THX.

**Comment by Aljullu** [comment]
Hi @kamitey, thanks for your suggestion! We have an open issue to track adding a checkbox for "I have read and agree to terms" (#3258), which seems to be your request, so I will close this issue as a duplicate. You can follow #3258 to be aware of the progress.
