### ISSUE TITLE
products do not display in 6-column format on backend....

### ISSUE THREAD

**Issue by GlennMartin1** [woocommerce/woocommerce-gutenberg-products-block#35]
Products do not display in 6-column format.

1-column, 2-column, 3-column, 4-column, and 5-column all work well.

- 6-column setting works on the front end.
- 6-column setting does NOT work on the back end - instead it works just like 1-column.

**Comment by jameskoster** [comment]
We should tie this setting to the `product_grid` settings that themes can now specify in core.

**Comment by warrendholmes** [comment]
At 5 columns the Add To Cart breaks here https://cloudup.com/cNtDsXJP-qc
