### ISSUE TITLE
Featured Product/Category blocks: button is not centered with recent Gutenberg releases

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#3507]
The button in the Featured Product and Featured Category blocks is not centered in recent versions of Gutenberg:

_Gutenberg 9.5:_
![imatge](https://user-images.githubusercontent.com/3616980/101339212-67984800-387e-11eb-944f-ad4904f5bf2f.png)

_WP 5.6 RC4 with Gutenberg disabled:_
![imatge](https://user-images.githubusercontent.com/3616980/101339972-66b3e600-387f-11eb-930b-fbbf25dd1ea2.png)

**Comment by nerrad** [comment]
This sounds like it _might_ be a bug in Gutenberg (if the button is relying on alignment related things). We should verify that and report upstream if needed.

**Comment by Aljullu** [comment]
I'm unable to reproduce this anymore, so it might have been fixed already. Closing for now.
