### ISSUE TITLE
Gutenberg Products Blocks not translated in FR_fr back-end

### ISSUE THREAD

**Issue by djdmsr** [woocommerce/woocommerce-gutenberg-products-block#351]
**Describe the bug**
Gutenberg not translated in back-end

**To Reproduce**

1. Go to 'editor
2. Click on + add block
3. All strings appear in english in a FR_fr admin site
4. Published articles are translated correctly

**Expected behavior**
See the french translation in back-end

* Core version: 5.0.3
* Gutenberg version : 4.8.0
* WooCommerce : 3.5.3
* WooCommerce Blocks version:  1.3.1
* Site language: FR_fr
* Any other plugins installed:

    *Autoptimize
    Gutenberg
   * Mailchimp for WooCommerce
    Members
    *OnePress Plus (with Theme OnePress)
    Regenerate Thumbnails
    Registrations for WooCommerce
    *Simple Calendar
    *UpdraftPlus - Backup/Restore
    User Role Editor
    *WooCommerce
    *WooCommerce Blocks
    *WooCommerce PayPal Checkout Gateway
    WooCommerce Services
    WooCommerce Stripe Gateway
    WP-Optimize
    WPForms Lite
    WP Maintenance Mode
    *WP Super Cache
(*=activated)

* OS: [e.g. iOS] El Capitan
* Browser [e.g. chrome, safari] FF
* Version [e.g. 22] 64

**Additional context**
The page I need help with: http://regard-image.fr

**Comment by ryelle** [comment]
@djdmsr Are all gutenberg blocks in English, or just the WooCommerce blocks? For example, if I change my site to French, I see this when I click the +

![screen shot 2019-01-18 at 3 22 08 pm](https://user-images.githubusercontent.com/541093/51411254-318c3680-1b35-11e9-87c3-57486abb2ff3.png)

**Comment by djdmsr** [comment]
Hello,
just the woocommerce blocks
[image: Capture d’écran 2019-01-19 à 05.41.46.jpg]

https://regard-image.fr/blog/cest-noel/

thanks.

Hubert

Le ven. 18 janv. 2019 à 21:36, Kelly Dwan <notifications@github.com> a
écrit :

**Comment by ryelle** [comment]
@djdmsr Can you try deactivating your plugins, to see if one of them is the conflict?
- If not, re-enable the plugins one by one until the issue comes back, and we can debug that specific conflict.
- If you still have the issue with other plugins deactivated, do you see any messages if you open the developer console? Here’s how to do that on a few different browsers: https://support.airtable.com/hc/en-us/articles/232313848-How-to-open-the-developer-console

**Comment by djdmsr** [comment]
It's a production site, fortunately it's a multi-sites install., then I cloned it, to run your tests:
I disabled all my extensions and then I activated Woocommerce and Woocommerce Blocks first, then  after all the others, one by one. At no stage, Woocommerce Blocks was translated into French in dashboard. No change. No alert in my Firefox console. 
Sorry @ryelle but sadly I think I will not help you.
Fortunately, front-end is translated.
Thanks for your attention.

**Comment by mikejolley** [comment]
This does not seem to be affecting the latest builds (in WC 3.6) with WordPress 5.2. It could have been a previously patched WP issue, or simply missing translations on translate.wordpress.org.

If you're now using the blocks in WooCommerce 3.6, the translations will be part of woocommerce core.

If using the feature plugin, some will come from https://translate.wordpress.org/projects/wp-plugins/woo-gutenberg-products-block/

After updating/installing this plugin or switch locales, you need to go to Dashboard > Updates and run the 'update translations' tool. This will pull in the newest po/mo files.

I did this and tested the `de_CH_informal` translation. It worked with the exception of a few missing strings which are not yet translated on translate.wordpress.org, so all seems to be working here.

Thanks
