### ISSUE TITLE
Investigate usage of @wordpress/icons in place of our current @woocommerce/icons aliased package.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#3512]
We implemented our own icons aliased package because at the time `@wordpress/icons` was not available. I think we should consider:

- Can we use `@wordpress/icons` directly and just enhance with our own icons? What impact does this make to bundle size?
- Should we submit our icons upstream in a pr on the `@wordpress/icons` package as additional icons for that package?
- Are there icons we can use from the `@wordpress/icons` package instead of custom ones we're using to make things more consistent with the WordPress ui/ux?

cc @senadir  and @LevinMedia  - I don't think we need to do this immediately, but it'd be a good cooldown task to audit. Also David, it's good to be aware that the icons in this package are available for future designs (if you weren't already aware).

**Comment by mikejolley** [comment]
@nerrad Might be a good time to raise this again with the design team because the checkout i2 will be introducing new blocks which need new icons.

**Comment by nerrad** [comment]
cc @vivialice - See MIke's comment above and the original comment with this issue. You can see the [current library of WordPress icons here](https://wordpress.github.io/gutenberg/?path=/story/icons-icon--library). 

The current library of icons we use on the Woo Blocks side can be [viewed here](https://woocommerce.github.io/woocommerce-gutenberg-products-block/?path=/story/woocommerce-blocks-woocommerce-icons--library). 

Even with switching to use the `@wordpress/icons` package, we can still use custom icons if needed, but ideally we'd use as much as possible from the `@wordpress/icons` package to get the benefits of a common design style and any future performance optimizations WP adds.

**Comment by ralucaStan** [comment]
> Should we submit our icons upstream in a pr on the @wordpress/icons package as additional icons for that package?

I find this to be a good idea considering we have some _common_ icons that we introduce: cart, etc

But before we do this we need to update our icons to match the style of the library upstream, our icons are thicker, as we can see in [this comment](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5599#issuecomment-1026775689) where the stroke for cart for example is thicker than for other icons.

I propose we create a different ticket for this effort, and identify what icons need to be updated (with the help of design) after the merge of @mikejolley 's [PR](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5599)
