### ISSUE TITLE
WooCommerce Checkout Block Validation

### ISSUE THREAD

**Issue by theritesite** [woocommerce/woocommerce-gutenberg-products-block#3525]
I noticed while using the WooCommerce Checkout Block that if a user fills in billing & shipping information, chooses a shipping method, then changes the zip code to something invalid (space, completely invalid text) shipping options often no longer appear, and the order can be submit and payment captured with invalid shipment details (literally, a space as the zip code).

Seems that due to the order-draft storing data, there may be need for additional validation on the front end.

## To reproduce
1. Build a cart
2. Go to checkout & enter Shipping Address (check use same address for billing) details
3. Select shipping option (if not pre-selected)
4. Change Shipping Address to Invalid (change anything, but change the zip code to a space ' ')
5. Click Checkout
6. Watch as form submitted and accepted, payment captured, order in processing, possibly to a wrong address, depending on the intention of a user.

## Additional Notes
Can also be reproduced by building a cart, changing contents & address.
Real life situation: customer builds a cart with an existing address stored, needing to ship to a new address, the order may have already been accepted in the cart when the shipping options might be displayed

## Expected behavior
1. Build a cart
2. Go to checkout & enter Shipping Address (check use same address for billing) details
3. Select shipping option (if not pre-selected)
4. Change Shipping Address to Invalid (change anything, but change the zip code to a space ' ')
5. Click Checkout
6. Invalid shipping address & shipping option selected, checkout not submit, payment not captured

### WordPress (please complete the following information):
* Core version: 5.5.3
* WooCommerce version: 4.7.0 & 4.8.0
* WooCommerce Blocks version: 3.9 & 4.0

### Desktop (please complete the following information):
* OS: macOS
* Browser: Safari, Chrome, Firefox

## EDIT:
On inspection of the code, and further front end testing, there is quite a bit of validation, but on some test cases that I myself cannot reproduce, we are able to get orders through using US addresses with no postal code or state even when they are required.

**Comment by theritesite** [comment]
Additional circumstances:
New users with no saved addresses were never presented with shipping options, and order valid with missing city and zip code. On inspection of the database, there are no rows in the database associated to the order with '_shipping_postcode'.
The person who ran into this scenario didn't give me any more information on fields presented to them or anything, but rather reported that the checkout process worked with said fields missing.

On my own experience, sometimes the shipping options request never fires, and no shipping options presented, and I am able to check out, even though items are simple or variable (meaning products are marked as "shipping required")

**Comment by theritesite** [comment]
Another update, it seems that sometimes customers are no longer getting the end point 'update-customer' ran, which may be causing most of the issues present.
It seems primarily present in new customers who have not yet saved a shipping address. The problems described above are either far less prevalent, or not an issue if there was previously a saved shipping address.

**Comment by theritesite** [comment]
This morning I found what seems to be part of the above described issue(s) (default customer location), but may be indicative of another bug. Feedback and guidance would be appreciated!

I found that on the test website I had setup, I had entered the WC Setting "Default Customer Location" as "**no default address**" rather than the default, Geolocation. This caused the address in the checkout screen to never be updated IF the address was never set to begin with. This makes no shipping option ever appear for new customers with no address saved.

This issue was also similarly present if the setting was using "Shop Base Address" or using "Geolocate (with page caching support)", if a user attempts to change the state, the shipping options no longer update accordingly with new state and zip code.

We found that if new customers went into the WooCommerce > My Account > Addresses and set an address from there, the shipping options would appear and would be dynamic based on user input, as expected.

- This led us to find something else: Interacting with the **Shipping State** field caused the shipping options to no longer be queried.
- This then led us to find a further discovery of unchecking the "use same address" box, allowed the shipping state field to work as expected and the shipping options queried and displayed correctly. Once again, checking the box, then interacting with the state made the shipping options non-queriable yet again.

## To reproduce
1. Sign in to an existing customer account
2. Create a cart by adding product(s)
3. Go to checkout screen
4. Ensure "Use same address for billing" is checked
5. Edit the Shipping State
6. Edit zip code
7. Unexpected behavior: no shipping options queried no matter what else you change from here

## To Reproduce (with a twist)
1. Sign in to an existing customer account
2. Create a cart by adding product(s)
3. Go to checkout screen
4. Ensure "Use same address for billing" is **NOT** checked
5. Edit the Shipping State
6. Edit zip code
7. Decide to use your original credit card instead, which has a your current address!
8. Now **tick** the "Use same address for billing" box
9. Edit the zip code (notice expected behavior)
10. Edit the shipping State
11. Edit the zip code
12. Unexpected behavior: no shipping options queried no matter what else you change from here

**Comment by nerrad** [comment]
Thanks for reporting this!

@haszari can you please investigate this and see if it's something you can reproduce. Offhand this seems like a high priority issue if it's reproducible and is something we should address soon.

**Comment by haszari** [comment]
@nerrad I can reproduce the first issue – changing zip code/postcode to a space submits an order with an empty postcode field.

Looks like our validation is not catching whitespace as empty. So this is worth following up IMO 👍

**Comment by nerrad** [comment]
Can we confirm this is an issue specific to Blocks, is this also something that occurs in the shortcode checkout flow?

**Comment by haszari** [comment]
> Can we confirm this is an issue specific to Blocks, is this also something that occurs in the shortcode checkout flow?

Just retested with checkout shortcode. Shortcode complains if the postcode is a space, so looks like this is gap in our validation.

<img width="877" alt="Screen Shot on 2020-12-11 at 15-16-41" src="https://user-images.githubusercontent.com/4167300/101853095-f0d3b580-3bc3-11eb-84e5-4f3990b52398.png">

**Comment by mikejolley** [comment]
If fixed the whitespace issue, but the other is different. It seems when the shipping country changes which in turn changes the state input (from select to text for example), this is when rates stop updating. Investigating.

**Comment by mikejolley** [comment]
Ok, that one might be my PR :) It loses some values if the API fails to update a field due to validation. Ill tackle this in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3552
