### ISSUE TITLE
Move tests from Travis to GitHub actions

### ISSUE THREAD

**Issue by opr** [woocommerce/woocommerce-gutenberg-products-block#3542]
Travis recently announced that it will no longer be free for open source projects (https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing).

At the moment Travis runs our tests and builds and deploys Storybook. Since we are already running a few actions on GitHub it makes sense to migrate our tests (and Storybook build) to GitHub actions.

We may be able to use the workflow configs they're using on Gutenberg to inform the way we set ours up.

- [Gutenberg E2E Tests action](https://github.com/WordPress/gutenberg/actions/runs/413103677/workflow)
- [Gutenberg Unit Tests action](https://github.com/WordPress/gutenberg/actions/runs/413103667/workflow)
- [Gutenberg Storybook deploy](https://github.com/WordPress/gutenberg/actions/runs/412882115/workflow)

CC @haszari since @nerrad mentioned you were interested in working on this too.

**Comment by opr** [comment]
FYI: [This PR](https://github.com/docker-library/wordpress/pull/551) on `docker-library/wordpress` will let us test against PHP8 when is it merged.

**Comment by nerrad** [comment]
@opr is this issue done or is there still ongoing work related to it needing done?

**Comment by opr** [comment]
@nerrad it is pretty much done, #3544 just needs a review, then @senadir needs to disable the Travis integration for this repo (or anyone else who has the correct access level to do this)

**Comment by nerrad** [comment]
Alrighty, I moved #3544 to the Code Review pipeline and applied the appropriate label.
