### ISSUE TITLE
Hide categories with no visible products

### ISSUE THREAD

**Issue by alantygel** [woocommerce/woocommerce-gutenberg-products-block#3564]
## Describe the bug
Currently, the Product Categories block has an option to hide empty categories. However, this option doesn't work as expected.

To consider a category empty, it only checks whether there are products associated to this category. However, these products might not be visible (hidden or outofstock, if the don't show out of stock products is on). Thus, the category shows on the list (or dropdown), customer clicks on it and then there are products in the archive page, which is very frustrating.

## To reproduce

1. Add the "Product categories list" block to a page. Ensure the "Show empty categories" option is off. (Empty categories should be hidden).
2. Add a new category.
3. Create a new product, add it to the category.
4. Change the product's catalogue visibility to hidden.
5. Visit the page and see that the category is still listed.
6. Try this with out of stock products too when the hide out of stock products option is enabled.

## Expected behavior
The category list should not show any categories that do not contain at least one visible product.

_edited by @opr_

**Comment by opr** [comment]
Thanks a lot for reporting this, I was able to replicate this and I've added it to our backlog of issues.

I've edited your original comment to give more information to the developer who picks this up.

For reference, these areas of the codebase seem to be where the items are added to the list/select:

- https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/7a6accdabaad6b51b6e446adf73b6e88e1928b6d/src/BlockTypes/ProductCategories.php#L243-L258
- https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/7a6accdabaad6b51b6e446adf73b6e88e1928b6d/src/BlockTypes/ProductCategories.php#L291-L307

**Comment by alantygel** [comment]
Well, I would rather act over 

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/7a6accdabaad6b51b6e446adf73b6e88e1928b6d/src/BlockTypes/ProductCategories.php#L121-L137

If `$attributes['hasEmpty']` is True, I would make a query checking if there are products which are not outofstock neither hidden from catalog. However, this approach seems to add a significant burden (one additional query per category), especially if there are many categories.

@opr, do you think this is the correct approach?

**Comment by mikejolley** [comment]
WooCommerce has an `wc_change_term_counts` function which should be handling this for us. We should check if it's running. We should not add additional queries here which would degrade performance further.
