### ISSUE TITLE
Delete All Cart Items Endpoint returns woocommerce_rest_cart_error

### ISSUE THREAD

**Issue by albertkp** [woocommerce/woocommerce-gutenberg-products-block#3571]
## Delete All Cart Items not working
Hi,
I'am calling the delete all cart items endpoint  with the X-WC-Store-API-Nonce. But I'am getting back woocommerce_rest_cart_error error. I have tried the add-item and remove-items endpoints. Both are working fine when triggered with nonce. But the delete endpoint is failing. I have checked in code and found the get_cart_instance() function is returning null for wc-cart() for this delete request.
**DELETE /cart/items/**

## To reproduce

1. Trigger curl --request DELETE https://example-store.com/wp-json/wc/store/cart/items with X-WC-Store-API-Nonce
2. API response is {"code":"woocommerce_rest_cart_error","message":"Unable to retrieve cart.","data":{"status":500}}

## Expected behavior
API should successfully clear the cart and return [].

**Comment by senadir** [comment]
I'm not seeing this error, can you update to the latest version and try again?

**Comment by albertkp** [comment]
> I'm not seeing this error, can you update to the latest version and try again?

Sure. Will try and let you know

**Comment by mikejolley** [comment]
This was fixed here: https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3488

I'm not sure if this version is live in Woo Core yet, so you may need to wait for WC 4.9 to be released, or use the Blocks Feature plugin which does contain the fix.

Thanks
