### ISSUE TITLE
X-WC-Store-API-Nonce is invalid errors because of inconsistent nonce

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#3595]
## Describe the bug
When you try to add a product after a checkout, you get a nonce error.

## To reproduce

1. In a private window, add and checkout, without creating an account.
2. Go back to all products, try adding a product
3. you get a nonce error, this seems to happen with all products only, works fine in cart requests.

You can also reproduce it by:
1. In a private window, visit a page with All Products.
2. Try adding to cart, it would work.
3. Try filtering or switching the page, and then adding the cart, it wouldn't work.

this issue is mostly because of inconsistent nonce between products and cart due to session.
Sometimes it works, sometimes it doesn't.

## Expected behavior
You can add a product with no problem.

**Comment by senadir** [comment]
I give this a run but didn't get anywhere with this
deleting this line `$response->header( 'X-WC-Store-API-Nonce', wp_create_nonce( 'wc_store_api' ) );` fixes it but would create a regression when people log in.
I'm not sure at all why removing this line fixes the issue.

**Comment by senadir** [comment]
After some digging, I found that `/store/products` returns a different nonce from cart and checkout endpoints, not sure why.

**Comment by mikeicode** [comment]
This happened in 26070536-hc

**Comment by nerdysandy** [comment]
Still happened on # 27796336-hc

**Comment by marcuswisecaesar** [comment]
This happened in 28227363-hc
