### ISSUE TITLE
Products grid: Alignment issues of the sale badge in smaller screens

### ISSUE THREAD

**Issue by dashkevych** [woocommerce/woocommerce-gutenberg-products-block#3601]
## Describe the bug
It looks like the [following styles](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/assets/js/base/components/product-list/style.scss#L133) cause an alignment issue of the sale badge in smaller screens when the badge is aligned to the center. Also, these styles cause an alignment issue of the sale badge when the badge is aligned to the right. See screenshots below.

## Expected behavior
The alignment of the sale badge should remain unchanged in smaller screens.

## Screenshots

![Grid in regular views](https://snipboard.io/S64bDh.jpg)

![Grid in smaller views](https://snipboard.io/7hsY6L.jpg)

![Grid in regular views](https://snipboard.io/LjtzYl.jpg)

![Grid in regular views](https://snipboard.io/g3HD4m.jpg)

## Environment
* Core version: [5.7-alpha-49904]
* WooCommerce version: [4.8.0]
* WooCommerce Blocks version: [4.1.0]

**Comment by dashkevych** [comment]
Also, it would be great if all products blocks had the same functionality for the sale badge. Currently, only the _All Products_ block allows to set a position of the sale badge while other block do not have this functionality. It may raise questions from users who set alignment of this section in the _All Products_ block and want to mimic the same layout for other product blocks.

Additionally, we can simplify styles of the badge in the products grid by having the same structure for all blocks. Currently, only the _All Products_ block comes with the following classes for the badge: `wc-block-components-product-sale-badge--align-center`, `wc-block-components-product-sale-badge--align-left`, `wc-block-components-product-sale-badge--align-right`. Other blocks do not have these classes. They have `wc-block-grid__product-onsale`. The _All Products_ block also has this class. So, we need to use different CSS rule-sets in order to avoid alignment issues.

I believe that by having the same structure for this section we would be able to reduce a complexity of styles in this section and make it easier to maintain styles for the section.

**Comment by nerrad** [comment]
Thanks for leaving the feedback and suggestions @dashkevych. Related to aligning styles across all grid type blocks, we likely won't be doing much with the current blocks because there are plans in our longer term roadmap to align how these blocks are constructed (using block elements) which will result in this alignment since all blocks will be sharing the same base components. The inconsistency you pointed out between mobile and desktop views is something we'll need to address sooner however.
