### ISSUE TITLE
New Cart & Checkout Blocks don't load content for users

### ISSUE THREAD

**Issue by cds1991** [woocommerce/woocommerce-gutenberg-products-block#3606]
## Describe the bug
- Aim is to replace default cart & checkout with new block based Woocommerce cart & checkout
- Cart and Checkout load and work as expected for user logged in as WP-Admin
- Cart and Checkout load and work as expected for all other visitors if accessed by URL and **not** set as WC Cart and Checkout Page in WC -> Settings -> Advanced
- If Cart and Checkout are set as WC Cart and Checkout Page (in WC -> Settings -> Advanced) no content is displayed. All content is replaced with grey boxes. This happens whether new pages have been created or the default pages have been updated with the new blocks shortcodes. 

## To reproduce

**option 1**
1. Create and publish new pages for Cart & Checkout using the new Cart / Checkout Block. Do not set as cart/checkout page in settings.
2. Access site while not logged in as wp-admin, add product to cart and use URLs of the new pages to access them. They should display as intended. 
3. Go to wp-admin -> WooCommerce -> Settings -> Advanced
4. Set Cart & Checkout page as the new pages you have created. 
5. Access site while not logged in as wp-admin, add product to cart and click "go to cart". The new page will display grey boxes where the content should be. 
6. Access site while not logged in as wp-admin, use URLs for the new pages to access them. The new pages will display grey boxes where the content should be. 

**option 2**
1. Update existing Cart & Checkout pages by replacing the default shortcode with the new cart & checkout blocks.
2. Access site while logged in as wp-admin, cart & checkout pages should perform as expected.
3. Access site while not logged in as wp-admin, add product to cart and click "go to cart". The new page will display grey boxes where the content should be. 

## Expected behavior
Expected new block cart & checkout to display the correct content for all users. 

## Screenshots
**1. Behaviour when logged in as WP-Admin**
<img width="1317" alt="Screenshot 2020-12-29 at 11 22 24" src="https://user-images.githubusercontent.com/76048838/103280537-8f378780-49c8-11eb-8396-f725fdc3b4cb.png">

**2. Behaviour when not logged in as WP-Admin, but page is not set as default cart (accessed using URL)**
<img width="1338" alt="Screenshot 2020-12-29 at 11 23 28" src="https://user-images.githubusercontent.com/76048838/103280558-9eb6d080-49c8-11eb-998e-e02b2bf5a9f5.png">

**3. Behaviour when not logged in as WP-Admin, and page is set as default cart (same result whether accessed by "view cart" or by entering direct URL**
<img width="1430" alt="Screenshot 2020-12-29 at 11 24 39" src="https://user-images.githubusercontent.com/76048838/103280579-abd3bf80-49c8-11eb-9dbd-b9d6223d2cc2.png">

**Behaviour for Checkout is identical**

### WordPress (please complete the following information):
* Core version: 5.6
* Gutenberg version (if installed): 
* WooCommerce version: 4.8.0
* WooCommerce Blocks version: 4.1.0
* Site language: English
* Any other plugins installed (all latest versions): Astra Widgets, Coming Soon Page (Seedprod), Cookie Notice, Elementor, Elementor - Header, footer & blocks, Elementor pro, Facebook for WooCommerce, Google Ads & Marketing by Kliken, Google Analytics for Wordpress by Monster Insights, Gutenberg Post Blocks, Jetpack by WordPress.com, Mailchimp for Woocommerce, Password Protected, Return refund and exchange for WooCommerce, SG Optimiser, UpdraftPlus - Backup/restore, WooCommerce Cart Abandonment Recovery, WooCommerce Shipping & Tax, Woocommerce Stripe Gateway, Wordfence Security, WP Forms Lite, Yoast SEO.

### Desktop (please complete the following information):
* OS: macOS
* Browser: chrome
* Version: 87

Behaviour replicated on MacOS-Safari, Windows 10 Chrome, iOS 13.5 Safari

### Smartphone (please complete the following information):
* Device: iPhone 7
* OS: iOS 13.5
* Browser: safari
* Version ?

**Comment by senadir** [comment]
Hey there, this happens when JS fails to load/run, are you seeing any console errors?

**Comment by cds1991** [comment]
Hi Seghir, 

- When logged into WP-admin (page displays as expected): "DevTools failed to load SourceMap: Could not load content for chrome-extension://eakacpaijcpapndcfffdgphdiccmpknp/scripts/content_page.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME"

- When not logged into wp-admin with cart page set in WC - settings - advanced (page doesn't display): LOADS! 

<img width="962" alt="Screenshot 2020-12-29 at 15 35 11" src="https://user-images.githubusercontent.com/76048838/103295386-b94e7100-49eb-11eb-8e0e-cdf81cb36fc3.png">
<img width="965" alt="Screenshot 2020-12-29 at 15 35 16" src="https://user-images.githubusercontent.com/76048838/103295387-bb183480-49eb-11eb-9de7-19da9c51f2b0.png">

- When not logged into wp-admin and cart page isn't set in wc-settings-advanced (page displays as expected): no errors at all. 

Thanks, I'm new to all of this, do you have any idea how to go about fixing this or what might be causing JS to fail?

Thanks, Charlie

**Comment by cds1991** [comment]
bump

**Comment by budzanowski** [comment]
Hi, Charlie ( @cds1991 )
I have tried to reproduce your issue but I was not able to. I see that you have a lot of plugins installed. This suggests that there may be an issue with one of them. If you don't mind, could you please try [Test for Plugins and Themes Conflicts](https://docs.woocommerce.com/document/how-to-test-for-conflicts/) . Since you are seeing the grey boxes instead of the content I think that the API data is not loading which would suggest issues with caching, but that is just a guess. Please try the procedure and tell us if something has changed.

**Comment by cds1991** [comment]
Thank you so much for your help. I've fixed it now. 

The conflict was with SG Optimizer. I disabled Minify JS and Combine JS Files and it seems to work now.

**Comment by Juha83** [comment]
> Thank you so much for your help. I've fixed it now.
> 
> The conflict was with SG Optimizer. I disabled Minify JS and Combine JS Files and it seems to work now.

I had the same problem and reconfiguring the SG Optimizer helped.
