### ISSUE TITLE
Display "Products by Attribute" on front end of site

### ISSUE THREAD

**Issue by ryelle** [woocommerce/woocommerce-gutenberg-products-block#361]
A sub-issue for #243 – We need a way to render the Products by Attribute block on the front end. We might have a combination of multiple attribute terms across attributes.  For example, we might have attributes Color and Material, and we need to be able to show combinations like: "red and cotton", "blue or linen", "red or blue", etc.

Currently we render all blocks using [the `[products ]` shortcode,](https://docs.woocommerce.com/document/woocommerce-shortcodes/#content-product-attributes) but we can only pass one `attribute` slug. We could update the shortcode.

Or perhaps this is [the first dynamic block,](https://wordpress.org/gutenberg/handbook/designers-developers/developers/tutorials/block-tutorial/creating-dynamic-blocks/) where we use a `render_callback` to display the products? We could query the DB for a set of product IDs, then render the shortcode with those IDs (to keep the themeable output the same).

Or some other idea?

**Comment by ryelle** [comment]
I've started this in the branch here, but the query doesn't appear to be returning the product IDs in the correct order: https://github.com/woocommerce/woocommerce-gutenberg-products-block/compare/update/products-by-attribute-frontend

**Comment by ryelle** [comment]
Last week I updated the branch to use `WC_Product_Query`, but we're running into the same taxonomy relationship issues we had with mixing Attributes and Categories, because "product visibility" is also a taxonomy, so when we set "match any attribute" we're requesting "blue or large or visible", which then returns every visible product.

**Comment by jameskoster** [comment]
@ryelle here's the updated design for this block:

![design](https://cldup.com/meWRETd5kh.gif)

The radio buttons coupled with the fact that only a single attribute "drawer" can be opened at once should make it clear that only terms from a single attribute can be selected.
