### ISSUE TITLE
Filter Products by Attribute: Add a CSS class to the heading element 

### ISSUE THREAD

**Issue by dashkevych** [woocommerce/woocommerce-gutenberg-products-block#3612]
Currently, the Filter Products by Attribute block comes with a title ("Filter by size") which is shown above the product attribute section. Also, this block allows to change a heading level in the Editor. It would be great it the block had a special CSS class for the heading element in order to avoid using complex selectors. For example, we can add the following class to the heading element in this block: `wc-block-attribute-filter-title`.

For example, at the moment, we can use the following selectors to change styles of this section:

### Front-end

`.wp-block-woocommerce-attribute-filter > *:not(.wc-block-attribute-filter)`

### Editor

`.editor-styles-wrapper .wp-block[data-type="woocommerce/attribute-filter"] > div > :first-child`

By having a special class for the heading element, we can simplify the process of styling this element. Instead of using two different versions of CSS rule-sets, we can use just one for both, front end and the editor: `.wc-block-attribute-filter-title { ... }`

The same thing we can apply to the _Filter Products by Price_ and the _Active Product Filters_ blocks.

**Comment by tjcafferkey** [comment]
This has been completed in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/4749/files
