### ISSUE TITLE
Integration Tracking (WC Subscriptions): Indicate whether a Switch Subscription product is downgrade/upgrade/crossgrade in REST API

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#3614]
WC Subscriptions offers the ability to upgrade/downgrade or crossgrade a Subscription, it achieves this by creating a pseudo Subscription Product with new data.
In classic Checkout, the original Subscription is updated with new information.

For this issue, we want to indicate whether an item is a downgrade, upgrade, or crossgrade pseudo subscription product, we can inspire from this function.
The code should live in WCSubs repo.
https://github.com/woocommerce/woocommerce-subscriptions/blob/294a664182e5759d65edf189b551425599998ddd/includes/class-wc-subscriptions-switcher.php#L1839-L1866

the new data should be:

```
switch_type: 'crossgrade|upgrade|downgrade|null'
```
the schema type should be `['string', 'null']`.

**Comment by budzanowski** [comment]
Closed by 3982-gh-woocommerce/woocommerce-subscriptions
