### ISSUE TITLE
Checkout Block doesn't support PayPal Express

### ISSUE THREAD

**Issue by itielsefer14** [woocommerce/woocommerce-gutenberg-products-block#3615]
## hola! el error es que no acepta otras formas de pago, como por ejemplo PayPal express etc

**Comment by senadir** [comment]
Hi @itielsefer14 ,

The Cart and Checkout blocks are still in preview and there are a number of extensions and payment methods that are not integrated yet. Paypal Express is one of those extensions. You can follow [this document](https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/) to keep up to date with the latest status of the blocks.

I'm going to close this issue as there's nothing actionable for it at the moment. We are aware of there being limited payment method support and it's on our roadmap to integrate WooCommerce owned extensions as well as encourage third party developers to integrate their own extensions.

Thanks for taking the time to create the issue and make sure we were aware!
