### ISSUE TITLE
Integration Tracking (WC Subscriptions): Indicate if the cart/summary item is a downgrade/upgrade/crossgrade

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#3619]
When a customer switches his subscription, some sort of indication should be shown on Cart and Order Summary that the current item is a switch, Checkout shortcode appends (downgrade/upgrade/crossgrade) to the item subtotal, in our case we have "Due today" prepended to the subtotal, so I'm not sure what's the best place to add the switch keyword.

pinging @LevinMedia

**Comment by budzanowski** [comment]
@Spacepol Any suggestions on how to proceed?

**Comment by budzanowski** [comment]
For shortcode pages we have:
In cart:
![image](https://user-images.githubusercontent.com/17271089/106591966-3622bc80-654f-11eb-8739-7a4e1686c265.png)

In checkout:
![image](https://user-images.githubusercontent.com/17271089/106592042-4d61aa00-654f-11eb-9a76-b7249cbcfe4d.png)

**Comment by senadir** [comment]
I discussed this with Pablo and have a possible solution of showing a badge (just without the extra colors).
pca54o-Pg-p2
![image](https://user-images.githubusercontent.com/6165348/106592291-9f0a3480-654f-11eb-88dc-4295a03c3d85.png)

We're still not sure if allowing extensions to add a badge is going to be scalable or not, or if we're only going to have one badge that everyone controls.

**Comment by ghost** [comment]
@budzanowski 

As Nadir said, we discussed about using the badge, however, I have the same comment on the scalability of the component.

**Comment by senadir** [comment]
Closed by  3991-gh-woocommerce/woocommerce-subscriptions
