### ISSUE TITLE
Integration Tracking (WC Subscriptions): Indicate whether a Subscription Product is a resubscribe in REST API

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#3624]
WC Subscriptions offers the ability to resubscribe a Subscription, it achieves this by creating a pseudo Subscription Product based on the previous product but without sign-up fees or trial periods.
If your previous subscription contains several products, all of them are going to be added to your cart.

For this issue, we want to indicate whether an item is a resubscribe pseudo subscription product
the new data should be:

```
is_resubscribe: 'true|false'
```
the schema type should be `boolean`.

**Comment by opr** [comment]
Closed by 3976-gh-woocommerce/woocommerce-subscriptions
