### ISSUE TITLE
Full site editor renders blank page with WooCommerce activated

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#3626]
Full Site Editor renders blank when WooCommerce is enabled. This issue was reported by a user in GB repo (https://github.com/WordPress/gutenberg/issues/27938) and according to the discussion there, the cause might be the work-around introduced in this PR: https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3219.

### Steps to reproduce

1. Install a FSE compatible theme (ie, [Armando](https://wordpress.org/themes/download/armando.1.0.0.zip?nostats=1)).
2. Enable Gutenberg and WooCommerce.
3. Click on the _Site Editor_ sidebar menu item.
4. Notice the page renders blank.

**Comment by Aljullu** [comment]
I can confirm reverting the changes from #3219 fixes the issue.

FSE is probably a more important feature than the visual glitch https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3219 was fixing, so as a quick solution might be reverting those changes.

**Comment by jeyip** [comment]
Hi @Aljullu 👋 Any updates on this issue?

**Comment by nerrad** [comment]
I think we should definitely at a minimum roll out reverting #3219 to fix this. However it'd be nice to see if we can find an alternate way of addressing the visual glitch in the editor context in the interim until the iframed editor instance lands in WP core for all editor usage.
