### ISSUE TITLE
Product title in Cart should inherit link styles

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#3628]
Based on the new design iteration for Cart, the product title is going to inherit link styles.

figma file: n90hX6hG3wwQbYwsYsrJnj-fi-5119%3A0

screenshot
![image](https://user-images.githubusercontent.com/6165348/103554772-ba7e1300-4eaf-11eb-886c-d8b5c639a8a4.png)
![image](https://user-images.githubusercontent.com/6165348/103554886-e4cfd080-4eaf-11eb-8d25-0c1317d7c298.png)

> The product title inherits the link color and styles from the theme. In the checkout meta, the product title isn’t linked. This is intentional to avoid directing the customer away from completing the checkout process.

**Comment by nerrad** [comment]
We're going to do a review of polish type issues at a later stage in the C&C blocks roadmap so I'm adding to the backlog for now.

**Comment by opr** [comment]
@nerrad this was done in #3734 - I didn't notice this issue existed because I was just looking at ones with the subscription integration in the title.

**Comment by nerrad** [comment]
Awesome! Nice I can close it then :)
