### ISSUE TITLE
Remove quantity column in Cart and move Quantity selector and delete button to below Product Title

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#3631]
Based on the new design iteration for Cart and Checkout, we need to move the quantity selector and the remove link to below the price.

> The Quantity column was removed to provide more space for the product title, description, price etc.
>
> The quantity selector was moved to the bottom of the left column.
>
> Mobile considerations:
> In the cart, the delete icon is removed from the upper right corner, and the “remove” link is added under the quantity selector to match desktop. This provides additional space for the product title and price.
>
> The quality select should be aligned to the right of the image.

screenshot
![image](https://user-images.githubusercontent.com/6165348/103558036-5873dc80-4eb4-11eb-843f-595b376e63b3.png)
![image](https://user-images.githubusercontent.com/6165348/103558124-79d4c880-4eb4-11eb-89e6-e3a709739cd6.png)

**Comment by opr** [comment]
This work is closely tied to #3629 - I feel like doing #3629 without doing this makes the cart block display poorly.
