### ISSUE TITLE
Champs Adresse

### ISSUE THREAD

**Issue by 321-Soleil** [woocommerce/woocommerce-gutenberg-products-block#3639]
Bonjour, j'ai installer woo block, excellent, seul soucis, sur mon champs d adresse il y a écrit "Adresse& nbsp;
" j'aimerais le changer en "Adresse" comment est ce possible?
Merci d avance.
Cordialement

**Comment by Aljullu** [comment]
Closing as duplicate of #3649. I suggested the translation update but it's up to the localization community to accept it or not.
