### ISSUE TITLE
Cart block doesn't use the Fees Label, always says 'Fees'

### ISSUE THREAD

**Issue by pramodjodhani** [woocommerce/woocommerce-gutenberg-products-block#3648]
## Describe the bug
While using [this snippet](https://docs.woocommerce.com/document/add-a-surcharge-to-cart-and-checkout-uses-fees-api/#section-1), the Cart block always refers to the fees as "Fees", rather than "Surcharge".

## To reproduce

1. Install this plugin.
2. Create the cart page using the Cart block
3. Add [this snippet](https://docs.woocommerce.com/document/add-a-surcharge-to-cart-and-checkout-uses-fees-api/#section-1) to a plugin or theme
4. Add any Product to the cart
5. Go to the cart page and notice that it refers to fees as 'Fees' rather than 'Surcharge'
![image](https://user-images.githubusercontent.com/5794565/103742293-955ce200-5020-11eb-8bdc-04788f8518b9.png)

## Expected behavior
Fees should be referred to by their name, just how it is done in the legacy shortcode [woocommerce_cart]
![image](https://user-images.githubusercontent.com/5794565/103742413-c9380780-5020-11eb-9ac4-2da44fc5cb68.png)

### WordPress (please complete the following information):
* Core version: 5.6
* WooCommerce version: [e.g. 3.5.3]
* WooCommerce Blocks version: 4.1.0
* Site language: English
* Any other plugins installed: None

### Desktop:
* OS: MacOS Catalina
* Browser Chrome
* Version Version 87.0.4280.88 (Official Build) (x86_64)

**Comment by Aljullu** [comment]
Thanks for opening this issue and the detailed testing instructions @pramodjodhani! It looks like we already have an open issue to track this problem: #3519, so I will close this one as a duplicate.
