### ISSUE TITLE
Enable @wordpress/no-global-event-listener ESLint rule

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#3650]
Gutenberg enabled a rule to avoid calling `addEventListener` and `removeEventListener` from `document` and `window` globals: https://github.com/WordPress/gutenberg/pull/26810. In order to keep our codebase consistent and prevent introducing more instances of this issue, we would like to enable this rule in our repo as well.

Taking a quick look, there might be a couple of instances where this rule might throw in our codebase. This issue is about fixing those instances as well.

**Comment by mikejolley** [comment]
This was fixed in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/4206
