### ISSUE TITLE
Memory leak error when emptying cart

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#3655]
When you remove all items from your cart, you get a console error about a memory leak

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in PaymentMethodDataProvider (created by CheckoutProvider)
    in ShippingDataProvider (created by CheckoutProvider)
    in CustomerDataProvider (created by CheckoutProvider)
    in CheckoutStateProvider (created by CheckoutProvider)
    in CheckoutProvider (created by CartProvider)
    in CartProvider (created by Block)
    in Block (created by Block)
    in ValidationContextProvider (created by Block)
    in LoadingMask (created by Block)
```

This is the guilty useEffect

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/f0cb5425e6e9e01c80d89318049e8791ea0745ee/assets/js/base/context/cart-checkout/payment-methods/use-payment-method-registration.js#L140-L145

**Comment by nerrad** [comment]
I've reopened, but for what it's worth React [has actually removed this warning](https://github.com/facebook/react/pull/22114) which should show up in a future release. So I think we should just evaluate if we actually need to address this (i.e. a real memory leak - i'm not sure it is given we're mostly just updating internal state, and it's okay if it happens on remounts?) or just leave for now until it gets resolved with a React update.
