### ISSUE TITLE
webpack-helpers.js cleanup

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#3658]
We think we can clean up [`webpack-helpers.js`](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/bin/webpack-helpers.js) a bit:

* `@woocommerce/blocks-registry` is listed in the `wcDepMap` and `wcHandleMap` and it's also returned in the `getAlias()` function. We think it doesn't need to be [returned by `getAlias()`](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/70d5ab022b1229e37f950e1d5ec17ceb659dc2e3/bin/webpack-helpers.js#L76-L79).
* `@woocommerce/block-settings` is in `wcHandleMap` and returned in `getAlias()`. We think it doesn't need to be in [`wcHandleMap`](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/70d5ab022b1229e37f950e1d5ec17ceb659dc2e3/bin/webpack-helpers.js#L28).

This issue is about making the changes above and verify nothing fails.

**Comment by nerrad** [comment]
@ralucaStan just getting this on your radar as it's related to the alias audit work you did.
