### ISSUE TITLE
Option to disable 'continue shopping'

### ISSUE THREAD

**Issue by Major1ty** [woocommerce/woocommerce-gutenberg-products-block#3660]
## What do you like about the Cart & Checkout blocks?
Huge improvement, thanks. 

## What do you think is missing from the Cart & Checkout blocks?
BUT, there needs to be an option to disable 'continue shopping' please. 
This is especially important for a single-product store!!!

**Comment by Aljullu** [comment]
Hi @Major1ty, glad to know you like the Cart and Checkout blocks!

It's not clear to me where the 'Continue shopping' option appears. Could you post a screenshot or some steps to reproduce it? Thanks!

**Comment by nerrad** [comment]
I'm going to close this because we haven't heard back in a week. @Major1ty if you update this issue with additional details that help us reproduce your report we'll reopen as necessary.

**Comment by Major1ty** [comment]
Sorry, didn't see your reply!

When an item is added to the cart, a "continue shopping" message appears. As you can see from the screenshot, it's on the product page.

Worse, on a mobile, it appears at the top of the checkout.

To improve conversions in a 1-product store, the ideal flow would be for the "add to cart" button to take a buyer straight to the cart. There could be an option in the block settings to allow the "continue shopping" option.

Cheers
Mike

P.S. I'm using Kadence theme v 1.0.11 and woocommerce 4.9.0 with woocommerce blocks 4.2.0 on WordPress 5.6

________________________________

**Comment by Aljullu** [comment]
@Major1ty it looks like the screenshot was not uploaded and I'm not able to figure out where the 'Continue shopping' message appears. Is that in a specific WooCommerce block?

**Comment by Major1ty** [comment]
I'll try again with the screenshots.

I'm not sure, but I think the continue shopping message is generated by the cart block, because the add to cart is from the product page, which does not have blocks (unfortunately.)

Cheers

________________________________
