### ISSUE TITLE
Handle double padding when LineItem is inside Panel

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#3669]
It happens that when nest a LineItem inside a panel, you get double padding, because both components

![image](https://user-images.githubusercontent.com/6165348/104306958-ebbd9b00-54ce-11eb-942e-b4cfb545cb85.png)

Preferably, Panel shouldn't have padding in them and that should be left to the insider items to decide, ethier that or LineItem shouldn't have padding that should be left for the container to decide how elements are shown.

The least resisting option to simply detect when LineItem is inside Panel and remove its padding.

cc @Aljullu

**Comment by Aljullu** [comment]
Yes, I agree some of those styles can be simplified. We inherited them from the time we used a `<Card>` to render the sidebar. The reason to have those paddings, is so the border lines will overflow on the sides. But I think this could be accomplished in easier ways: one that comes to my mind would be moving the padding to `.wc-block-components-sidebar` and then adding a negative margin to the lines?

**Comment by opr** [comment]
I believe this issue was _partly_ fixed by #4415, but I am about to create another PR to fully correct this.
