### ISSUE TITLE
Do we need to capture the address when a customer chooses local pickup?

### ISSUE THREAD

**Issue by garymurray** [woocommerce/woocommerce-gutenberg-products-block#3677]
This was logged as part of another feature request here: https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3352#issuecomment-720055800 so I have created a new issue for us to deal with this issue seperately.

Essentially - the question was asked - do we need to capture the customers address if they intend to use local pickup as the delivery option? 

As @nerrad mentioned in his comment [here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3352#issuecomment-720084670):

> I will bring up your point about the shipping address to the team, however we're unlikely to change the behaviour because shipping method options can be tied to geographical area. So the shipping address still needs entered to determine what shipping options to show (which may or may not include Local pickup - depending on how the store is configured).

I think we just want to confirm that there is no 'better' approach we could be using here. 

cc @Spacepol for design input/thought.

**Comment by mikejolley** [comment]
Is it not the case that some payment gateways require billing address in order to process payment?

**Comment by garymurray** [comment]
@mikejolley I've always been led to believe it was needed - perhaps something to check with Transact if they any insights on this. 

Anecdotally I know _someone_ who managed to pay for something using a card, but put in the wrong address (not the one associated with the card) and the payment went through fine - so it's hard to tell how much this is an actual requirement vs a suggested requirement.

**Comment by nerrad** [comment]
> so it's hard to tell how much this is an actual requirement vs a suggested requirement.

It can vary by payment gateway and also by how payment gateways are configured in their account settings.

**Comment by garymurray** [comment]
This is what I was thinking - note this is a rough mockup of the concept:

<img width="653" alt="Screenshot 2021-01-14 at 12 17 48" src="https://user-images.githubusercontent.com/10805911/104590006-9f0ac900-5662-11eb-997f-5be56feed852.png">

If a merchant has local pickup enabled - it is not shown as a shipping option - but rather the second step in the checkout changes to one called something like 'Delivery' and the customer makes a decision on how they'd like their item "delivered" i.e Shipped or will they Pick Up?

If they selected Pick Up - we'd then need to move the capturing of the Billing Address to the checkout step itself alongside the payment method.

**Comment by senadir** [comment]
Stripe doesn't require but highly suggest you pass billing address so there's less chance the payment get rejected for fraud, granted, payment gateway only verify the numbers in an address.

**Comment by Marc-pi** [comment]
This is a very annoying feature lack :
1. User selects Local Pickup at Cart Step (i use Cart/Checkout FSE Blocks)
2. We ask for delivery address, which leads to confusion (he can also choose set delivery address as billing address)
3. Final invoice delivery address is made at his own address, instead of at the local pickup address, the same for the order
4. There is no way to set local pickup address in WC Settings, to ease user understanding and make the process cristal clear. Seems there is no setting for that purpose

**Comment by senadir** [comment]
Thank you @Marc-pi 
Having first class support for local pickups is the next thing we're going to handle, keep an eye on our releases for the next couple of months or so.

**Comment by mikejolley** [comment]
Looks like this issue has been superseded by #7136. Follow along there for updates.
