### ISSUE TITLE
Convert the button in the Featured Product block into a full-featured Button block

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce-gutenberg-products-block#368]
Folks expect the edit-ability of this button to match the core button block.

Ito design it should mimic other nested blocks, e.g. the Media and Text block:

![button](https://cldup.com/4mJGoKdqZd.gif)

Clicking on the button switches focus to that block and reveals the corresponding settings, with two exceptions; 

* In the Featured Product block it should not be possible to edit the button destination url. 
* It should also not be possible to adjust the button alignment (this is governed by the parent block justification setting).

All other settings should be included.

After making this change we can remove the **b** _i_ ~s~ options on the Featured Product block toolbar as these are currently only applied to the button anyway. Folks found this confusing as they weren't sure whether it would be applied to the product title / price / description as well. It should still be possible to apply **b** _i_ ~s~ to the button, but this should be handled through the Button block toolbar.

**Comment by ryelle** [comment]
Done in #398
