### ISSUE TITLE
Twenty Twenty-One: "Add to Cart" button appears dark on editor page for the product grid blocks

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-gutenberg-products-block#3685]
## Bug Description:
"Add to Cart" buttons appears dark on editor page for all the Product grid blocks on Twenty Twenty One theme 

## Environment:
Windows 10, Mac 10.15.7 (19H114).
Browser: Chrome(Version 87.0.4280.88 (64-bit)) 
               Firefox(Version 83.0)(64-bit)
               Safari: v13.1.1 (14609.2.9.1.3)
                
 
## Steps To Reproduce:
1. Create any test site using Jurassic Ninja.
1. Install and activate all required plugins.
1. Complete the Onboarding setup wizard.
1. Select Twenty Twenty one theme.
1. Add Some products.
1. Go to Pages->Add New.
1. Add any Product grid block.
1. Observe that "Add to Cart" buttons appears too dark.

## Actual Result:
"Add to Cart" buttons appears dark on editor page for all the Product grid blocks on Twenty Twenty One theme 
 
## Expected Result:
"Add to Cart" button should be properly displayed.

## Video:

https://user-images.githubusercontent.com/41110392/104609639-4b6f9e00-56a9-11eb-8657-fae6071f836a.mp4

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by Aljullu** [comment]
Thanks for the report!

I can reproduce this issue consistently in PHP-based product grid blocks in the editor. All Products block doesn't seem to be affected

The issue is only visible in the editor. Frontend is not affected:
![imatge](https://user-images.githubusercontent.com/3616980/104631814-10676d80-569d-11eb-9266-4c37dd1e4732.png)

**Comment by nielslange** [comment]
@gglobalstep & @Aljullu: Can you still reproduce this problem on your end? I'm unable to reproduce it using a fresh WP installation and the _On Sale Products_ block, as seen in https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3685#issue-786042981.

<table>
<tr>
<td>Frontend:
<br><br>

![#3685-frontend](https://user-images.githubusercontent.com/3323310/128187828-0c9f416b-4c0d-4419-aabe-397db5c7a5c8.png)
</td>
<td>Editor:
<br><br>

![#3685-editor](https://user-images.githubusercontent.com/3323310/128187835-ea27d45c-31cb-4c77-9fd7-2f96e2ff4c35.png)
</td>
</tr>
</table>

**Comment by Aljullu** [comment]
You're right @nielslange, I'm unable to reproduce now. Thanks for testing it!

**Comment by nielslange** [comment]
> You're right @nielslange, I'm unable to reproduce now. Thanks for testing it!

Anytime, @Aljullu.
