### ISSUE TITLE
finalizar compra

### ISSUE THREAD

**Issue by maelegance2020** [woocommerce/woocommerce-gutenberg-products-block#3689]
## What do you like about the Cart & Checkout blocks?
It's fine because it improves the woocommerce version. Thanks a lot

## What do you think is missing from the Cart & Checkout blocks?
It comes out to me that I don't have the payment option set up, and I do have it set up. How can I fix it? Thanks a lot

**Comment by senadir** [comment]
Hey,
What payment gateway are you using?

**Comment by maelegance2020** [comment]
Hello. I’m using redsys blugin for payment.

**Comment by senadir** [comment]
Hi again,

The Cart and Checkout blocks are still in preview and there are a number of extensions and payment methods that are not integrated yet. Redsys is one of those extensions. You can follow [this document](https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/) to keep up to date with the latest status of the blocks.

I'm going to close this issue as there's nothing actionable for it at the moment. We are aware of there being limited payment method support and it's on our roadmap to integrate WooCommerce owned extensions as well as encourage third party developers to integrate their own extensions.

Thanks for taking the time to create the issue and make sure we were aware!
