### ISSUE TITLE
Investigate size increase in @woocommerce/blocks-checkout

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#3697]
While working on moving components to `@woocommerce/blocks-checkout` package, its size increased to 50kb, and there was a total of 9kb increased between all files, this didn't make sense because if anything, the total size should decrease because we removed duplicated components between cart and checkout.

This PR introduced the size change https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3671

We should investigate if this increase is legit and if there's anything we can do to reduce it.

**Comment by nerrad** [comment]
The increase is a little less with the work I did around circular dependencies and the last fix in there:

- checkout package is now 38.1kb instead of 50kb
- total increase of 7.51kb instead of 9kb.

**Comment by senadir** [comment]
Actually, it's still 50kb, it increased by 38.1 (same result as before) we just lost some weight due to better tree shaking.

**Comment by nerrad** [comment]
ahh, I misunderstood your original comment, I thought you were saying the package increased 50kb over what was in trunk with the pr and my changes dropped it down to 38.1 increase :). So ya we saved a bit more  on the overall bundle size. I think this issue will still be good to investigate in a cooldown.

**Comment by senadir** [comment]
This is now fixed by #3778 

> You can actually get a peek into the effects of the original bug by looking at the bundle size differences. build/blocks-checkout decreased by 33.2kb whereas the build/cart-frontend, build/cart, build/checkout-frontend, and build/checkout files only increased a total of 20.02kb. So the extra ~13kb that was in build/blocks-checkout was all the duplicate context and dependencies pulled in from base/context and elsewhere.
