### ISSUE TITLE
Product Grid Blocks: Add transformation

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce-gutenberg-products-block#370]
For example; it should be possible to transform the Best-Sellers block in to the Top-Rated block and preserve settings like layout and filtering.

**Comment by ryelle** [comment]
Basically we want a set of transforms that let the user cycle between Best Selling Products, Newest Products, On Sale Products, Top Rated Products.

Hand-picked Products, Products by Category, and Products by Attribute all have setting that wouldn't transfer between blocks (the exception maybe being Products by Category, which could possibly transform into one of the other simple blocks with a category restriction).

The Featured Product will also eventually have a transform into a Cover block (see #293 ), tracked in #295
