### ISSUE TITLE
Cart block: missing margin below the shipping rate when there is only one option

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#3700]
Found when testing WC Blocks 4.3.0 (#3698).

There is a small visual glitch in the Cart block: there is no margin below the shipping rates if there is only one option available

## To reproduce

1. Set up your store so there is only one shipping method available.
2. Add some products to the cart and go to the Cart page.
3. Notice there is no margin below the shipping rate:
![missing-margin-cart](https://user-images.githubusercontent.com/3616980/105017132-bd4a3d80-5a43-11eb-97d1-2a4a16306e3a.png)

**Comment by ralucaStan** [comment]
Looks like this has been fixed in the meantime so I am gonna close this issue. 
Tested with Version 4.7.0-dev.

<img width="249" alt="Screenshot 2021-03-11 at 11 01 34" src="https://user-images.githubusercontent.com/1628454/110777621-3c483f00-8259-11eb-84d5-6fd6130b2d9f.png">
