### ISSUE TITLE
WooCommerce Product Blocks rendering stars as 'SSSSS'

### ISSUE THREAD

**Issue by Luminus** [woocommerce/woocommerce-gutenberg-products-block#3713]
## Describe the bug

1. WooCommerce Product Blocks are rendering rating stars as 'SSSSS' instead of actual stars
2. The are forcing a black colour output and overriding the colour set by the theme

1026776-hc

## To reproduce

1. Go to a product on your site and make to leave a rating e.g. 5 stars
2. Create a new page
3. Insert the **Hand-picked Products** block and select the product that has a rating
4. Publish the page
5. View the page

## Expected behavior
The star ratings should display as stars and carry the colour that is set by the theme even when being displayed via a product block

## Screenshots
Here's what the stars look like by default in Storefront
![Default Ratings](https://user-images.githubusercontent.com/248077/105196584-b00c7c00-5b33-11eb-9429-c2c0aa871a5e.png)

Here's what it looks like in the Hand-picked Products block
![Block Ratings](https://user-images.githubusercontent.com/248077/105196676-c7e40000-5b33-11eb-8b20-8707c637146b.png)

Notice that the Stars are displaying as 'S' characters and the colour is black instead of the purple prescribed by the theme.

The character and colour seem to be set here - https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/f1e423b0ac4b1a68aed8a057a9df22678282adfa/assets/css/style.scss#L135-L143

`content: "\53\53\53\53\53";` is what is outputting 'SSSSS' whereas WooCommerce by default outputs `content: "\f005\f005\f005\f005\f005";` where `f005` is the code for ⭐ in Font Awesome.

The colour is also forced to be black

This line also seems to be setting the wrong font-family - https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/f1e423b0ac4b1a68aed8a057a9df22678282adfa/assets/css/style.scss#L112

WooCommerce has it set as `font-family: Font Awesome\ 5 Free;` which allows the stars to show up.

### WordPress (please complete the following information):
* Core version: 5.6
* WooCommerce version: 4.9.1
* WooCommerce Blocks version: 4.0.0
* Site language: en_US
* Any other plugins installed:

### Desktop (please complete the following information):
* OS: MacOS
* Browser: Brave
* Version: Version 1.18.77 Chromium: 87.0.4280.101 (Official Build) (x86_64)

**Comment by mikejolley** [comment]
Hi @Luminus 

This is a Storefront bug being worked on here: https://github.com/woocommerce/storefront/pull/1588 There will likely be an update on Tuesday.

Thanks 

(closing this as a duplicate).

**Comment by Luminus** [comment]
Thanks for the heads up @mikejolley
