### ISSUE TITLE
Product Grid Blocks: Allow product title, price and add-to-cart button to be toggled off

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce-gutenberg-products-block#372]
Essentially this should function in the same way as the Price and Description visibility toggles on the Featured Product block.

So for each of the product grid blocks add a new setting section with the title "Content" and place toggles for the product title, price and add-to-cart button in there.

**Comment by LevinMedia** [comment]
@jameskoster What do you think about putting the toggles for these controls in the "Layout" settings, under the columns and row controls? My thinking... that is ultimately affecting the "Layout" and it's one less thing for people to discover, as layout should be exposed by default.

**Comment by jameskoster** [comment]
I suggested a "Content" section because that would match the featured product block content controls:

![content](https://cldup.com/zBpjWAbehe-3000x3000.png)

Personally, these feel more like "content" settings than "layout" settings to me, so I'd prefer to stick with what we have. But I don't feel super strongly about it. If you do, I wouldn't object to that change.

**Comment by spencerfinnell** [comment]
Is there a corresponding core ticket to add the ability to toggle these items via the shortcode? Or any other information on implementing this on the frontend?

**Comment by jameskoster** [comment]
@spencerfinnell we don't seem have an issue for it yet but our plan for 2.0 is to move away from relying on the core shortcode for the output of these blocks.

**Comment by LevinMedia** [comment]
@jameskoster yeah no, I don't feel terribly strong about that. Just a thought. Let's leave it in content for now.
