### ISSUE TITLE
Nothing is showing on my cart page

### ISSUE THREAD

**Issue by neonnightsnz** [woocommerce/woocommerce-gutenberg-products-block#3725]
Hi there I have added the cart and checkout blocks to both pages on my website and I'm seeing nothing when navigating to the page except the rath math page score.

What have I done wrong any tips to overcome the issue?

https://neonnights.co.nz/shop/cart/

Thanks
Isaac

**Comment by senadir** [comment]
Hey there, it seems you have a cache plugin that is minfying and concating JS files, can you disable all cache plugins and try again?

**Comment by budzanowski** [comment]
Closing for now as we know that this problem is caused by caching issues. If after disabling cashing the problem persist please reopen the issue.
