### ISSUE TITLE
Update all tested up to headers for extensions to WooCommerce 5.0

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#3729]
With the pending release of WooCommerce 5.0, please make sure all WooCommerce tested up to headers in our extensions and Storefront are updated to WooCommerce 5.0.

**Comment by budzanowski** [comment]
- [x] WooCoommerce Blocks
- [x] Storefront
- [x] Product Add-Ons 
- [x] Checkout Field Editor
- [x] Additional Variation Images 
- [x] Email Customizer
- [x] Force Sells 
- [x] Cart Add-Ons
- [x] Ajax-Enabled Layered Navigation
- [x] One Page Checkout
- [x] Quick View
- [x] Sale Flash Pro
- [x] Splash Popup 
- [x] 360º Image
- [x] Products Compare 
- [x] WooSlider Products Slideshow 
- [x] WooSlider

**Comment by ralucaStan** [comment]
I found an issue testing Cart Add-Ons with WooCommerce 5.0. The following controls on the Plugin's dashboard don't work:
Default Add-Ons, Add Category, and Add Products
![Screenshot 2021-02-09 at 13.05.53.png](https://images.zenhubusercontent.com/6006f97ad883b38577590742/94c8b9f4-3ad2-48c7-abeb-9091f8eed854)

There are some errors in the console 

```
GET admin.php?page=sfn-cart-addons:35 GET https://innovative-jambu.jurassic.ninja/wp-content/plugins/woocommerce-cart-add-ons-1.15.34/assets/css/settings.css?ver=1.15.34 net::ERR_ABORTED 404
GET admin.php?page=sfn-cart-addons:1933 GET https://innovative-jambu.jurassic.ninja/wp-content/plugins/woocommerce-cart-add-ons-1.15.34/assets/js/product-search.min.js?ver=1.15.34 net::ERR_ABORTED 404
GET admin.php?page=sfn-cart-addons:1937 GET https://innovative-jambu.jurassic.ninja/wp-content/plugins/woocommerce-cart-add-ons-1.15.34/assets/js/settings.min.js?ver=1.15.34
```

**Comment by ralucaStan** [comment]
All extensions tested and shipped.
