### ISSUE TITLE
Provide an easier (standardised) way to override the Rest API routes

### ISSUE THREAD

**Issue by pryley** [woocommerce/woocommerce-gutenberg-products-block#3733]
## Some background information of this feature request

This issue is related to #3503 

I am the author of the [Site Review](https://github.com/pryley/site-reviews) plugin and I provide a free extension ([Woocommerce Reviews](https://niftyplugins.com/plugins/woocommerce-reviews/)) which allows Site Reviews to integrate with Woocommerce and fully replace the built-in Woocommerce Reviews (comments) with the Site Reviews reviews.

Overriding the Woocommerce review REST API routes is not as straight-forward as it could be. It involves four different things:

1. Using the [woocommerce_rest_api_get_rest_namespaces](https://github.com/woocommerce/woocommerce/blob/ab4a46e32e338cbf33094ab26144744a021a21a9/includes/rest-api/Server.php#L53) hook to override the `product-reviews` and `reports-reviews-totals` Route Controllers.
2. Using the [woocommerce_rest_check_permissions](https://github.com/woocommerce/woocommerce/blob/ab4a46e32e338cbf33094ab26144744a021a21a9/includes/wc-rest-functions.php#L355) hook to override the route permissions.
3. Using the [rest_endpoints](http://developer.wordpress.org/reference/hooks/rest_endpoints/) hook to override the `/wc-analytics/products/reviews/*` analytics route endpoint callbacks.
4. Using the [rest_endpoints](http://developer.wordpress.org/reference/hooks/rest_endpoints/) hook to override the `/wc/store/products/reviews` blocks route endpoint callbacks (used by this Block package).

The reason why this issue is related to #3503 is because it introduced a breaking change with the addition of the [Domain\Services\ExtendRestApi](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/src/Domain/Services/ExtendRestApi.php) class in a minor version update of Woocommerce (v4.8.0 &rarr; v4.9.0)

This is how I am now implementing the override of the `/wc/store/products/reviews` REST API route for the Woocommerce review blocks:

```php
use Automattic\WooCommerce\Blocks\Domain\Services\ExtendRestApi;
use Automattic\WooCommerce\Blocks\Package;
use Automattic\WooCommerce\Blocks\StoreApi\Schemas\ImageAttachmentSchema;

// ...

/**
 * @param array $endpoints
 * @filter rest_endpoints
 */
public function filterRestEndpoints($endpoints)
{
    foreach ($endpoints as $route => &$endpoint) {
        if ('/wc/store/products/reviews' === $route) {
            $this->modifyStoreEndpoint($endpoint);
        }
    }
    return $endpoints;
}

/**
 * @param array $endpoint
 * @return void
 */
protected function modifyStoreEndpoint(&$endpoint)
{
    $extend = Package::container()->get(ExtendRestApi::class);
    $schema = new CustomProductReviewSchema($extend, new ImageAttachmentSchema($extend));
    $routes = new CustomProductReviewsRoute($schema);
    foreach ($endpoint as $key => $value) {
        if ('schema' === $key) {
            $endpoint[$key] = [$schema, 'get_public_item_schema'];
            continue;
        }
        if (isset($value['callback'])) {
            $endpoint[$key]['callback'] = [$routes, 'get_response'];
        }
    }
}
```

Using this method, I can easily extend [StoreApi\Routes\ProductReviews](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/src/StoreApi/Routes/ProductReviews.php) with my own Route class:

```php
use Automattic\WooCommerce\Blocks\StoreApi\Routes\ProductReviews;

class CustomProductReviewsRoute extends ProductReviews
{
    /**
     * @param \WP_REST_Request $request
     * @return \WP_REST_Response
     * @throws \Automattic\WooCommerce\Blocks\StoreApi\Routes\RouteException
     */
    protected function get_route_response(\WP_REST_Request $request)
    {
        // query the reviews from Site Reviews here...
    }
}
```

However, extending the [StoreApi\Schemas\ProductReviewSchema](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/src/StoreApi/Schemas/ProductReviewSchema.php) class is not as straight forward since the [get_item_response](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/ff366f7161cc37ae91e78f7508912266ad4858d7/src/StoreApi/Schemas/ProductReviewSchema.php#L163) method specifically requires a [WP_Comment](http://developer.wordpress.org/reference/classes/wp_comment/) instance. To get around this, we have to extend [StoreApi\Schemas\AbstractSchema](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/src/StoreApi/Schemas/AbstractSchema.php) instead which is being done like this:

```php
use Automattic\WooCommerce\Blocks\Domain\Services\ExtendRestApi;
use Automattic\WooCommerce\Blocks\Package;
use Automattic\WooCommerce\Blocks\StoreApi\Schemas\ProductReviewSchema;
use Automattic\WooCommerce\Blocks\StoreApi\Schemas\AbstractSchema;
use Automattic\WooCommerce\Blocks\StoreApi\Schemas\ImageAttachmentSchema;

class CustomProductReviewSchema extends AbstractSchema
{
    /**
     * @return array
     */
    public function get_item_response(\GeminiLabs\SiteReviews\Review $review)
    {
        // return the custom review response here...
    }

    /**
     * @return array
     */
    public function get_properties()
    {
        // Use the original review schema properties
        $extend = Package::container()->get(ExtendRestApi::class);
        return (new ProductReviewSchema($extend, new ImageAttachmentSchema($extend)))->get_properties();
    }
}
```

As you can see, overriding the API routes is quite possible but my concern is that the implementation is extremely fragile. Any changes introduced similar to #3503 have the potential to break it. 

## Suggested solution

I would like to see a standard way implemented that would allow third-party extensions to override REST API routes without worrying about the implementation breaking in a minor version release of Woocommerce.

**Comment by budzanowski** [comment]
Hi @pryley,

I am sorry to hear that you had problems related to the latest update. We try to be conscious of the changes we introduce. The API you are referring to is still internal and in the experimental phase.  We try not to break backward compatibility but some changes can happen, especially adding new features that may require significant adjustments. Hopefully not too often. When the APIs will be open ( we don't know yet, when exactly this will happen ) then they will be versioned, and no breaking changes will be allowed without bumping the version.

We try to add this information for developers like you in places we know that can change:
https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/src/StoreApi/Schemas/ProductReviewSchema.php#L10
