### ISSUE TITLE
Variable product missing product short description on cart

### ISSUE THREAD

**Issue by taylorchance** [woocommerce/woocommerce-gutenberg-products-block#3754]
I have a cart that is working fine for simple products, on the cart it is showing the description, but for variable products it is only showing the product size and leaving the description

**Comment by opr** [comment]
Hi @taylorchance - I experienced the same thing this morning.

I needed to add a short description to each variant of my product to get it to display in the cart. Can you verify that you've done this?

@nerrad what do you think about defaulting to the "main" product short description if all variants don't have a description?

**Comment by taylorchance** [comment]
@opr that worked, thanks!

**Comment by nerrad** [comment]
> @nerrad what do you think about defaulting to the "main" product short description if all variants don't have a description?

Would that create potential for other problems if the main product short description isn't accurate for the variant?  This feels like more of a configuration/product setup issue?
