### ISSUE TITLE
Nonce validation issue: "X-WC-Store-API-Nonce is invalid" in All Products Block.

### ISSUE THREAD

**Issue by budzanowski** [woocommerce/woocommerce-gutenberg-products-block#3757]
## Describe the bug
When using All Products Block it is possible to hit:
![image](https://user-images.githubusercontent.com/17271089/106144662-cc806800-6174-11eb-94d3-1559cb62bb26.png)

Related ticket: 3688475-zd-woothemes
## To reproduce

1. Open incognito window
2. Go to a page with All Products block
3. Add an item to the cart 
4. Go to cart
5. Go back using the browser back button
6. Try to add another item to the cart: not possible + nonce notice

## Expected behavior
The item should be added to the cart and the error notice should not be shown.

### WordPress (please complete the following information):
* Core version: [e.g. 5.6]
* Gutenberg version (if installed): none
* WooCommerce version: 4.9.0 - 5.0.0-rc1
* WooCommerce Blocks version: none
* Site language: English.
* Any other plugins installed: nope

### Desktop (please complete the following information):
* OS: macOS
* Browser Chrome
* Version 87.0.4280.141 (Official Build) (x86_64)

## Additional context
This was also tested with WooCommerce 4.8 and the problem was not present there.

**Comment by budzanowski** [comment]
This is a duplicate of https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3598 
Closing.

**Comment by budzanowski** [comment]
Actually reopening as this is a different scenario - just results in the same error.

**Comment by nerdysandy** [comment]
@mikejolley Is it possible to open this issue? I replicated it for another user today on #27796336-hc

**Comment by mikejolley** [comment]
@nerdysandy Would it be possible to post the updated steps to reproduce here please, as well as the version of blocks being used (or if this is the version currently in WooCommerce core). It may be that the version being used does not contain the above fixes. This was released in Blocks 4.4.0 which is part of WooCommerce 5.1.
