### ISSUE TITLE
npm install issue: WARN Tried to download(404): https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.27.0-node-v79-linux-x64.tar.gz

### ISSUE THREAD

**Issue by method7** [woocommerce/woocommerce-gutenberg-products-block#3771]
I wonder is anyone can help with this issue while trying to npm install

node -v = v13.10.0
npm -v = 6.14.11

error:
`
> nodegit@0.27.0 install /home/method7/Local Sites/pure-naturals-dev/app/public/wp-content/plugins/woocommerce-gutenberg-products-block/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Running install script
node-pre-gyp
WARN Using request for node-pre-gyp https download
node-pre-gyp
WARN Tried to download(404): https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.27.0-node-v79-linux-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for nodegit@0.27.0 and node@13.10.0 (node-v79 ABI, glibc) (falling back to source compile with node-gyp)

/bin/sh: 1: krb5-config: not found
gyp: Call to 'krb5-config gssapi --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp
ERR! configure error
gyp ERR!
stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/method7/.nvm/versions/node/v13.10.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp
ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.0-64-generic
gyp ERR! command "/home/method7/.nvm/versions/node/v13.10.0/bin/node" "/home/method7/.nvm/versions/node/v13.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/method7/Local Sites/pure-naturals-dev/app/public/wp-content/plugins/woocommerce-gutenberg-products-block/node_modules/nodegit/build/Release/nodegit.node" "--module_name=nodegit" "--module_path=/home/method7/Local Sites/pure-naturals-dev/app/public/wp-content/plugins/woocommerce-gutenberg-products-block/node_modules/nodegit/build/Release" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v79"
gyp ERR! cwd /home/method7/Local Sites/pure-naturals-dev/app/public/wp-content/plugins/woocommerce-gutenberg-products-block/node_modules/nodegit
gyp
ERR! node -v v13.10.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp
ERR! build error
node-pre-gyp ERR!
stack Error: Failed to execute '/home/method7/.nvm/versions/node/v13.10.0/bin/node /home/method7/.nvm/versions/node/v13.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/method7/Local Sites/pure-naturals-dev/app/public/wp-content/plugins/woocommerce-gutenberg-products-block/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/home/method7/Local Sites/pure-naturals-dev/app/public/wp-content/plugins/woocommerce-gutenberg-products-block/node_modules/nodegit/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/method7/Local Sites/pure-naturals-dev/app/public/wp-content/plugins/woocommerce-gutenberg-products-block/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1026:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System
Linux 5.4.0-64-generic
node-pre-gyp ERR! command "/home/method7/.nvm/versions/node/v13.10.0/bin/node" "/home/method7/Local Sites/pure-naturals-dev/app/public/wp-content/plugins/woocommerce-gutenberg-products-block/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp
ERR! cwd /home/method7/Local Sites/pure-naturals-dev/app/public/wp-content/plugins/woocommerce-gutenberg-products-block/node_modules/nodegit
node-pre-gyp ERR! node -v v13.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp
ERR! not ok
Failed to execute '/home/method7/.nvm/versions/node/v13.10.0/bin/node /home/method7/.nvm/versions/node/v13.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/method7/Local Sites/pure-naturals-dev/app/public/wp-content/plugins/woocommerce-gutenberg-products-block/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/home/method7/Local Sites/pure-naturals-dev/app/public/wp-content/plugins/woocommerce-gutenberg-products-block/node_modules/nodegit/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)
[nodegit] ERROR - Could not finish install
[nodegit] ERROR - finished with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.1 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodegit@0.27.0 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodegit@0.27.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

**Comment by opr** [comment]
Hi @method7 - The answers here may be useful: https://stackoverflow.com/questions/30088355/kerberos-installation-error-error-setup-script-exited-with-error-command-i68 

I ran into a similar issue a couple of months ago while trying to run this project on Linux, which it looks like you're trying to do too.

**Comment by method7** [comment]
Hi @opr many thanks for your reply and you are correct I am using Linux  - I have, in fact resolved the issue by reverting node to v12.x.x the project is building fine now.
