### ISSUE TITLE
“Cart is Empty” Issue

### ISSUE THREAD

**Issue by Andrewkow** [woocommerce/woocommerce-gutenberg-products-block#3783]
Found an issue when added a product to checkout page will show “Cart is Empty” on the mobile device only. On desktop is fine.

![added to checkout on mobile](https://user-images.githubusercontent.com/78463506/106701960-874fb080-6622-11eb-8b00-2167e96837af.jpg)

## What do you like about the Cart & Checkout blocks?
I like the layout and design compare to the default WooCommerce checkout page

## What do you think is missing from the Cart & Checkout blocks?
Allow customizing the input field and layout.

**Comment by opr** [comment]
Hi @Andrewkow - it looks like your "Order now" button has a different product ID on the mobile view than it does on the desktop view. The button links to `/checkout/?add-to-cart=1065` on desktop but `/checkout/?add-to-cart=495` on mobile. It looks like you're using Elementor to add this button to the page, so I would recommend you check your settings there and update the link.

Hope this helps. I will close this issue now as there's nothing actionable from us, but feel free to reopen it if you have further information regarding this.

Also, thanks for your feedback:

> Allow customizing the input field and layout.

Do you have any specific customisations in mind that you want to make that you're not able to? If you let us know what you're trying to customise we can keep a record of this and discuss adding it to the project in future.
