### ISSUE TITLE
Express Payments Break if Missing Billing Data

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#3784]
## Describe the bug
Something I noticed with 4.4 and 4.3. 4.0 seems to work.

If you enter a payment method in Chrome but only provide one name like this:

![Screenshot 2021-02-03 at 11 33 20](https://user-images.githubusercontent.com/90977/106741912-418beb80-6614-11eb-8951-3d9ce7bfcb7e.png)

When you place order you will see no error notices from our checkout, just the generic failed payment message in the payment modal. In the network tools you will see the failed API response:

![Screenshot 2021-02-03 at 11 35 53](https://user-images.githubusercontent.com/90977/106742040-641e0480-6614-11eb-941d-924309994b79.png)

## To reproduce
Steps to reproduce the behaviour:

1. Enable Stripe Payment method
2. Enter test payment details and address in chrome. Provide only 1 name.
3. Go to the cart page and try to pay for a cart using Chrome Pay
4. See error on screen and in network tab

## Expected behavior
We should either reject with a clear error message, or be more lax with validation in the API.

**Comment by opr** [comment]
I'll pick this issue up. I'm using Brave and have set up a saved payment method. When using this, even if I do have my full name added to the payment method my surname is not sent in the request. I'll investigate this, and the original issue using Chrome.

**Comment by opr** [comment]
While working on this, we noticed a significant UX problem. Further discussion around this can be found here: pca54o-19H-p2

**Comment by nerrad** [comment]
For reference, it looks like currently validation of whether last_name/first_name should appear is attached to country schema data:

https://github.com/woocommerce/woocommerce/blob/b19500728b4b292562afb65eb3a0c0f50d5859de/includes/class-wc-checkout.php#L225-L246

However, even then, I'm not sure why. Unless there's some specific reason this is attached to the country it seems that it shouldn't be assumed that someone living in a specific country has a name matching what's defined in this country validation schema?

**Comment by senadir** [comment]
This issue also highlights the fact that we should try and surface up errors coming back from the server.

**Comment by opr** [comment]
Issue opened in https://github.com/woocommerce/woocommerce/issues/34105

The error _is_ displayed in the Checkout Block, see loom below showing how it appears.

https://www.loom.com/share/4462888266d54b88b1c187feb17af0fe

These express payments are not actually processed by WooCommerce Blocks, the payment request UI interacts directly with a WC Core API.

Therefore there is nothing actionable from us here.
