### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined method WP_Error::get_data()

### ISSUE THREAD

**Issue by gazuots** [woocommerce/woocommerce-gutenberg-products-block#3791]
`Fatal error: Uncaught Error: Call to undefined method WP_Error::get_data() in …./plugins/woo-gutenberg-products-block/src/RestApi.php:52
Stack trace: #0 …./plugins/woo-gutenberg-products-block/src/Assets.php(184): Automattic\WooCommerce\Blocks\RestApi::get_routes_from_namespace(‘wc/store’)
woocommerce/woocommerce#1 …./wp-includes/class-wp-hook.php(287): Automattic\WooCommerce\Blocks\Assets::get_wc_block_data(Array)
woocommerce/woocommerce#2 …./wp-includes/plugin.php(212): WP_Hook->apply_filters(Array, Array)
woocommerce/woocommerce#3 …./plugins/woo-gutenberg-products-block/src/Assets/AssetDataRegistry.php(132): apply_filters(‘woocommerce_sha…’, Array)
woocommerce/woocommerce#4 …./plugins/woo-gutenberg-products-block/src/Assets/AssetDataRegistry.php(223): Automattic\WooCommerce\Blocks\Assets\AssetDataRegistry->initialize_core_data()
woocommerce/woocommerce#5 /home/te in …./plugins/woo-gutenberg-products-block/src/RestApi.php on line 52`

Hey woo lovers!
I see this in Admin > Products and almost 3 days i cant fix this..
Any ideas whats wrong?

**Comment by gazuots** [comment]
https://imgur.com/PNWoghe

**Comment by nerrad** [comment]
It looks like this was also reported in the [WordPress.org support forums](https://wordpress.org/support/topic/fatal-error-uncaught-error-call-to-undefined-method-wp_errorget_data-2/) and found to be a conflict with another theme/plugin.
