### ISSUE TITLE
Exclude files touched by renovate bot from being automatically assigned for reviews

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#3793]
Right now, via the [`CODEOWNERS`](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/.github/CODEOWNERS) file, `@woocommerce/rubik` is set as the owner of every file which is what triggers the automatic assignment of reviewers for changes. I think it should be possible to exclude certain files from being owned by `@woocommerce/rubik` which would prevent the automatic review assignment. Likely we'd only need to exclude:

- package-lock.json
- package.json
- composer.json
- composer-lock.json

**Comment by budzanowski** [comment]
Reopening as #3794 has not worked.

**Comment by nerrad** [comment]
I think we can close this now that we've moved to using something other than the `CODEOWNERS` file for automatic review assignment. The [GitHub action we're currently using](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/.github/automate-team-review-assignment-config.yml) automatically assigns based on the team the PR author belongs to. Since Renovate doesn't belong to a team no reviewer will get assigned.
