### ISSUE TITLE
Running some npm commands in a working directory that contains spaces fails

### ISSUE THREAD

**Issue by opr** [woocommerce/woocommerce-gutenberg-products-block#3799]
## Describe the bug
If you are working in a path that has spaces, for example 
> /Users/opr/**My Code Directory**/woocommerce-gutenberg-products-block

then running some npm commands, such as `npm run package-plugin:zip-only` will fail.

## To reproduce

1. Clone the repository into a directory whose path contains spaces.
2. run `npm install` and then `npm run package-plugin:zip-only` you should get an error.

## Expected behavior
The command should run without erroring.

## Additional context
There may be other scripts that fail. As part of the resolution of this issue we should check the other `npm` scripts to ensure they all work when in a directory path containing spaces.

Many thanks to @method7 for finding and reporting this issue in #3789 - this new issue has been created as it provides a more concise explanation of the problem.

**Comment by budzanowski** [comment]
A similar issue was found and fixed for another command: https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3290
