### ISSUE TITLE
litlle problems on woo block

### ISSUE THREAD

**Issue by 321-Soleil** [woocommerce/woocommerce-gutenberg-products-block#3804]
Hello i found small problems on the woo block here are they :
Im on the French woo block and here is the first little problem :
when i insert a promo code in the shopping cart page, in the promo code field, after that there is a quote that says "remise"which is great but just after ther is the litlle "nbsp" 
here is the photo
![image](https://user-images.githubusercontent.com/76965021/107116855-6b444d00-6876-11eb-8419-7bd25b09fb13.png)

the second litlle problem is that on the same page there is two times the shipping rate, one is in french so it say "livraison" which is perfect and the other is in english "shipping which is not so good.
here is the image
![image](https://user-images.githubusercontent.com/76965021/107116896-ad6d8e80-6876-11eb-8c49-e04669ce51ba.png)

Finally and the last thing is just my opinion but on the checkout page i just feel that the 4 steps of checkout are a litlle bit too much to the right of my laptop and not enough on the left i just show you, im on samsung galaxy :

![image](https://user-images.githubusercontent.com/76965021/107116966-3e446a00-6877-11eb-8899-7789ad43e343.png)
![image](https://user-images.githubusercontent.com/76965021/107116969-456b7800-6877-11eb-8300-072a92c6b86b.png)

The woo block is a really nice plug in, Keep Up the good work my friends.

**Comment by ralucaStan** [comment]
Hi @321-Soleil - it would be helpful to see your system status report - You will find information on how to do this here: https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/#section-1

If you can paste the status report into this thread that would be great.

Thanks!

**Comment by 321-Soleil** [comment]
Hello ! this is my Status report :

Name: Astra
Version: 3.0.1 (une mise à jour de la version 3.0.2 est disponible)
Author URL: https://wpastra.com/about/
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n’avez pas construit personnellement
nous vous recommandons d’utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 556
Oldest: 2021-01-08 17:40:48 +0100
Newest: 2021-02-08 14:23:11 +0100

Pending: 5
Oldest: 2021-02-09 04:22:38 +0100
Newest: 2021-02-12 11:19:31 +0100

`

**Comment by 321-Soleil** [comment]
Im Sorry this is the real status report !
`
### WordPress Environment ###

WordPress address (URL): https://321soleil.fr
Site address (URL): https://321soleil.fr
WC Version: 4.9.2
REST API Version: ✔ 4.9.2
WC Blocks Version: ✔ 4.4.2
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.8.3
Log Directory Writable: ✔
WP Version: 5.6.1
WP Multisite: –
WP Memory Limit: 640 Mo
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.26
PHP Post Max Size: 300 Mo
PHP Time Limit: 60
PHP Max Input Vars: 10000
cURL Version: 7.52.1
OpenSSL/1.0.2l

SUHOSIN Installed: –
MySQL Version: 5.7.32-log
Max Upload Size: 300 Mo
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.9.2
WC Database Prefix: wp_562781_
Taille totale de la base de données: 143.36MB
Taille de la base de données: 136.49MB
Taille de l’index: 6.87MB
wp_562781_woocommerce_sessions: Données : 0.06MB + Index : 0.02MB + Moteur InnoDB
wp_562781_woocommerce_api_keys: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_562781_woocommerce_attribute_taxonomies: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_562781_woocommerce_downloadable_product_permissions: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_562781_woocommerce_order_items: Données : 0.05MB + Index : 0.02MB + Moteur InnoDB
wp_562781_woocommerce_order_itemmeta: Données : 0.20MB + Index : 0.20MB + Moteur InnoDB
wp_562781_woocommerce_tax_rates: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_562781_woocommerce_tax_rate_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_562781_woocommerce_shipping_zones: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_562781_woocommerce_shipping_zone_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_562781_woocommerce_shipping_zone_methods: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_562781_woocommerce_payment_tokens: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_562781_woocommerce_payment_tokenmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_562781_woocommerce_log: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_562781_actionscheduler_actions: Données : 0.20MB + Index : 0.19MB + Moteur InnoDB
wp_562781_actionscheduler_claims: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_562781_actionscheduler_groups: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_562781_actionscheduler_logs: Données : 0.16MB + Index : 0.13MB + Moteur InnoDB
wp_562781_cartflows_ca_cart_abandonment: Données : 0.11MB + Index : 0.02MB + Moteur InnoDB
wp_562781_cartflows_ca_email_history: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_562781_cartflows_ca_email_templates: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_562781_cartflows_ca_email_templates_meta: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_562781_commentmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_562781_comments: Données : 0.08MB + Index : 0.09MB + Moteur InnoDB
wp_562781_fbv: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_562781_fbv_attachment_folder: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_562781_links: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_562781_options: Données : 6.50MB + Index : 0.14MB + Moteur InnoDB
wp_562781_postmeta: Données : 70.45MB + Index : 2.81MB + Moteur InnoDB
wp_562781_posts: Données : 46.36MB + Index : 0.58MB + Moteur InnoDB
wp_562781_rank_math_404_logs: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_562781_rank_math_internal_links: Données : 0.05MB + Index : 0.02MB + Moteur InnoDB
wp_562781_rank_math_internal_meta: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_562781_rank_math_redirections: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_562781_rank_math_redirections_cache: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_562781_shortpixel_folders: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_562781_shortpixel_meta: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_562781_swift_performance_warmup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_562781_termmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_562781_terms: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_562781_term_relationships: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_562781_term_taxonomy: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_562781_usermeta: Données : 0.05MB + Index : 0.03MB + Moteur InnoDB
wp_562781_users: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_562781_vtprd_purchase_log: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_562781_vtprd_purchase_log_product: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_562781_vtprd_purchase_log_product_rule: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_562781_vtprd_transient_cart_data: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_562781_wc_admin_notes: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_562781_wc_admin_note_actions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_562781_wc_category_lookup: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_562781_wc_customer_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_562781_wc_download_log: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_562781_wc_order_coupon_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_562781_wc_order_product_lookup: Données : 0.05MB + Index : 0.06MB + Moteur InnoDB
wp_562781_wc_order_stats: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_562781_wc_order_tax_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_562781_wc_product_meta_lookup: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
wp_562781_wc_reserved_stock: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_562781_wc_tax_rate_classes: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_562781_wc_webhooks: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_562781_wdp_orders: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_562781_wdp_order_items: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_562781_wdp_rules: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_562781_wdr_order_discounts: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_562781_wdr_order_item_discounts: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_562781_wdr_rules: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_562781_wfblockediplog: Données : 0.06MB + Index : 0.00MB + Moteur InnoDB
wp_562781_wfblocks7: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_562781_wfconfig: Données : 0.47MB + Index : 0.00MB + Moteur InnoDB
wp_562781_wfcrawlers: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_562781_wffilechanges: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_562781_wffilemods: Données : 5.52MB + Index : 0.00MB + Moteur InnoDB
wp_562781_wfhits: Données : 1.02MB + Index : 0.23MB + Moteur InnoDB
wp_562781_wfhoover: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_562781_wfissues: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_562781_wfknownfilelist: Données : 2.52MB + Index : 0.00MB + Moteur InnoDB
wp_562781_wflivetraffichuman: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_562781_wflocs: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_562781_wflogins: Données : 0.39MB + Index : 0.17MB + Moteur InnoDB
wp_562781_wfls_2fa_secrets: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_562781_wfls_settings: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_562781_wfnotifications: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_562781_wfpendingissues: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_562781_wfreversecache: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_562781_wfsnipcache: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_562781_wfstatus: Données : 0.14MB + Index : 0.09MB + Moteur InnoDB
wp_562781_wftrafficrates: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_562781_wpfm_backup: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_562781_wpforms_tasks_meta: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_562781_yoast_indexable: Données : 0.23MB + Index : 0.20MB + Moteur InnoDB
wp_562781_yoast_indexable_hierarchy: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_562781_yoast_migrations: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_562781_yoast_primary_term: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_562781_yoast_seo_links: Données : 0.36MB + Index : 0.19MB + Moteur InnoDB

### Post Type Counts ###

attachment: 243
custom_css: 10
customize_changeset: 36
elementor_library: 10
elementor-hf: 2
ig_campaign: 1
ig_message: 4
nav_menu_item: 12
oembed_cache: 10
page: 19
popup: 2
popup_theme: 8
post: 19
product: 13
product_variation: 38
revision: 2764
shop_coupon: 15
shop_order: 115
vtprd-rule: 1
wcct_countdown: 4
wp_block: 1
wpforms: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (18) ###

Easy Google Fonts: par Titanium Themes – 1.4.4
Elementor: par Elementor.com – 3.1.1
Finale Lite - Sales Countdown Timer & Discount for WooCommerce: par XLPlugins – 2.13.0
Elementor - Header, Footer & Blocks: par Brainstorm Force
Nikhil Chavan – 1.5.6

Heartbeat Control by WP Rocket: par WP Rocket – 2.0
Facebook for WordPress: par Facebook – 3.0.1
Really Simple SSL: par Really Simple Plugins – 4.0.7
Rank Math SEO: par Rank Math – 1.0.57.1
UpdraftPlus - Sauvegarde/Restauration: par UpdraftPlus.Com
DavidAnderson – 1.16.47

WooCommerce Cart Abandonment Recovery: par CartFlows Inc – 1.2.9
WooCommerce Blocks: par Automattic – 4.4.2
Variation Swatches for WooCommerce: par Emran Ahmed – 1.1.7
WooCommerce Stripe Gateway: par WooCommerce – 4.8.0
WooCommerce: par Automattic – 4.9.2
Wordfence Security: par Wordfence – 7.4.14
Asset CleanUp : Page Speed Booster: par Gabe Livan – 1.3.7.4
WP Fastest Cache: par Emre Vona – 0.9.1.4
WPForms Lite: par WPForms – 1.6.4.1

### Inactive Plugins (4) ###

Advanced Dynamic Pricing for WooCommerce: par AlgolPlus – 3.1.5
Astra Widgets: par Brainstorm Force – 1.2.7
Blackhole for Bad Bots: par Jeff Starr – 3.0
WordPress Importer: par wordpressdotorg – 0.7

### Must Use Plugins (1) ###

Elementor Safe Mode: par Elementor.com – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base de la boutique: #401 - /shop-2/
Panier: ❌ La page ne contient pas le code court.
Commander: ❌ La page ne contient pas le code court.
Mon compte: #29652 - /my-account/
Conditions générales de vente et d’utilisation: ❌ Page non définie

### Theme ###

Name: Astra
Version: 3.0.1 (une mise à jour de la version 3.0.2 est disponible)
Author URL: https://wpastra.com/about/
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n’avez pas construit personnellement
nous vous recommandons d’utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 556
Oldest: 2021-01-08 17:40:48 +0100
Newest: 2021-02-08 14:23:11 +0100

Pending: 5
Oldest: 2021-02-09 04:22:38 +0100
Newest: 2021-02-12 11:19:31 +0100

`

**Comment by 321-Soleil** [comment]
Hello 🙂
Do you think it is possible to change this litlle details ?
Tim

________________________________
De : Raluca Stan <notifications@github.com>
Envoyé : lundi 8 février 2021 16:04
À : woocommerce/woocommerce-gutenberg-products-block <woocommerce-gutenberg-products-block@noreply.github.com>
Cc : 321-Soleil <t1delage@hotmail.fr>; Mention <mention@noreply.github.com>
Objet : Re: [woocommerce/woocommerce-gutenberg-products-block] litlle problems on woo block (#3804)


Hi @321-Soleil<https://github.com/321-Soleil> - it would be helpful to see your system status report - You will find information on how to do this here: https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/#section-1

If you can paste the status report into this thread that would be great.

Thanks!

**Comment by ralucaStan** [comment]
Hello @321-Soleil,

thank you again for reaching out.

Regarding your first problem, it seems to be an issue with the French translation, which is something we don't control.
We suggested they remove the `&nbsp` part from [the translation](https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/fr/default/?filters%5Btranslated%5D=yes&filters%5Bstatus%5D=waiting), but the change is still in waiting state.

We are however investigating your second issue and we will get back to you.

**Comment by 321-Soleil** [comment]
Thank you so much 🙂.

**Comment by ralucaStan** [comment]
Closing this issue, as the duplicated Shipping title in the cart block will be fixed as part of https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3837
