### ISSUE TITLE
Ability to change text on "Cart" and "Checkout" blocks

### ISSUE THREAD

**Issue by arunsathiya** [woocommerce/woocommerce-gutenberg-products-block#3805]
## Is your feature request related to a problem? Please describe.

Certain stores prefer to change the text `Shipping` in cart and checkout blocks, to `Delivery` as they seem to be physically delivering the goods, and are not shipping with a carrier. In the example below, would like to change `Shipping` to `Delivery`:

<img width="718" alt="Screenshot 2021-02-07 at 2 29 45 PM" src="https://user-images.githubusercontent.com/18581859/107141748-eed26c80-6950-11eb-9487-c90ccede2b5b.png">

## Describe the solution you'd like

Overall, the idea is to have editable text within these blocks so that customers may modify that to their preferences.

## Describe alternatives you've considered

None applicable besides hiring a WooCommerce developer to customize the block.

## Additional context

Came up on this user request: 3718926-zen

**Comment by nerrad** [comment]
Thanks for the feedback @arunsathiya!

This is not something that we will be addressing immediately but at some point in the future we will review to see how we can make this possible.

**Comment by nerrad** [comment]
@senadir - I think this issue will be resolved by the I2 work for Cart and Checkout blocks right?

**Comment by senadir** [comment]
> @senadir - I think this issue will be resolved by the I2 work for Cart and Checkout blocks right?

No, not really. The merchant is trying to change strings inside a component.
