### ISSUE TITLE
Shipping heading duplicated in the Cart block

### ISSUE THREAD

**Issue by ralucaStan** [woocommerce/woocommerce-gutenberg-products-block#3837]
## Describe the bug
In the Cart block, the Shipping title appears twice. 

## To reproduce

1. Make sure you have shipping methods added for your region
2. Add a product to the cart
3. Go to the cart block
4. See the duplicated Shipping title like in the image below
<img width="294" alt="Screenshot 2021-02-12 at 15 07 00" src="https://user-images.githubusercontent.com/1628454/107778282-2f145f00-6d44-11eb-8077-82e8817ca533.png">

## Expected behavior
The cart should follow the structure below

<img width="282" alt="Screenshot 2021-02-12 at 15 10 11" src="https://user-images.githubusercontent.com/1628454/107778562-81ee1680-6d44-11eb-9088-8855861a76c4.png">

**Comment by nerrad** [comment]
Good spot. This will need to be reviewed design wise as well though since currently the Shipping heading for the rate options is a collapsible container. I'll add this for weekly triage review.

**Comment by nerrad** [comment]
@Spacepol is going to take a look at how this could be improved. Currently it's not a bug but intentional. However there is definitely room for improvement here.

**Comment by ghost** [comment]
Update: Posted design improvements on [P2 post.](https://teamrubik.wordpress.com/2021/02/23/incremental-improvement-to-the-cart-block-shipping/)

**Comment by nerrad** [comment]
This will be addressed by the work in #4180

**Comment by nerrad** [comment]
This was fixed at some point, there is now a distinction between "Shipping" and "Shipping method".

**Comment by nerrad** [comment]
I took another look at the designs and it looks like this still isn't following the design though so re-opening.
