### ISSUE TITLE
Adding a Cart or Checkout Block causes block editor "plugins" to duplicate

### ISSUE THREAD

**Issue by theritesite** [woocommerce/woocommerce-gutenberg-products-block#3839]
## Describe the bug
When editing a page in the block editor that has a "plugin" for the block editor (like Yoast or classic editor), assets seem to get duplicated when adding a cart or checkout block.
Seems that this is limited to only the cart and checkout, but I have not exhausted all blocks in the plugin.
This shows on the "pinned" bar and within the Kebab menu, under the "plugins" section

## To reproduce
1) Add a plugin to a WC Blocks environment that has a block editor "plugin"
      Yoast SEO or Classic Editor are good primary examples. 

2) Edit any page (can be random or assigned cart/checkout pages)
3) Add a cart or checkout block
4) See as the pinned plugin has duplicated, or the plugin menu items have doubled.

## Expected behavior
"Plugins" are not duplicated.

## Screenshots
![image](https://user-images.githubusercontent.com/26701248/107828019-2f612a00-6d45-11eb-873a-33529038c08b.png)

### WordPress (please complete the following information):
* Core version: 5.5.3 & 5.6
* WooCommerce version: 4.7.0 & 5.0.0
* WooCommerce Blocks version: 4.2.0 & 4.4.2
* Any other plugins installed: Yoast SEO & Classic Editor, issue persists when other is off in both cases.

### Desktop (please complete the following information):
* OS: macOS
* Browser Safari & Chrome

**Comment by mikejolley** [comment]
Confirmed. Increases Yoast branding by 300%.

**Comment by mikejolley** [comment]
Related: https://teamisotope.wordpress.com/2020/11/16/exporting-slotfill-components-gotcha/

Comes from https://github.com/woocommerce/woocommerce-gutenberg-products-block/commit/914eb93452ebba292bde64d7848eab6c94df7beb

Specifically:

```js
export { SlotFillProvider } from 'wordpress-components';
```

Using `@wordpress/components` fixes admin, but breaks the subscriptions integration. So unsure how to proceed at this point. cc @senadir
