### ISSUE TITLE
Sobre botones del carrito

### ISSUE THREAD

**Issue by luismichelmx** [woocommerce/woocommerce-gutenberg-products-block#3840]
## What do you think is missing from the Cart & Checkout blocks?

Creo que deberia poder personalizar los botones del carrito, personalmente creo inecesario tener todos los botones de los diferentes metodos de pago  en el carrito, con mostrar el boton de finalizar compra creo es suficiente y en la pantalla de finalizar compra mostrar los metodos de pago.

**Comment by mikejolley** [comment]
Hi,

The payment method icons shown at the bottom of the cart page near the button can be hidden with CSS if they are not needed. It's easier to remove them than expect users who want them to add them manually. 

```css
.wc-block-components-payment-method-icons { display: none; }
```

Thanks!
