### ISSUE TITLE
store/cart/update-shipping "rest_no_route" after upgrade to WC 5.0.0

### ISSUE THREAD

**Issue by cgtv** [woocommerce/woocommerce-gutenberg-products-block#3841]
Hello there,

After update to Woocommerce 5.0 I got the `"rest_no_route" `error when sending a request:

****POST** mystore.com/store/cart/update-shipping**

It seems the endpoint address was change.

I just report the issue for your future consideration.

**Comment by mikejolley** [comment]
Hi,

You're probably after `/wc/store/cart/select-shipping-rate` You can see the full list of endpoints here: 

https://github.com/woocommerce/woocommerce-gutenberg-products-block/tree/trunk/src/StoreApi

Please note this API is not versioned nor considered stable/public yet, it is for internal use and may change further.

Thanks

**Comment by cgtv** [comment]
Thanks for your reply,

It seems the route `/wc/store/cart/select-shipping-rate` also not working anymore.

Thanks

![Screen Shot 2021-02-26 at 19 23 49](https://user-images.githubusercontent.com/1297306/109375181-f346d100-78cf-11eb-9bfd-5c12a99d3050.png)

**Comment by mikejolley** [comment]
It's a POST route.

**Comment by cgtv** [comment]
Sorry, I tried with `POST` also several time:
But I faced the same error.
(WC ver 5.0)

![Screen Shot 2021-03-01 at 16 15 32](https://user-images.githubusercontent.com/1297306/109498912-6ce5e700-7aa9-11eb-960a-938feb371a25.png)

**Comment by mikejolley** [comment]
Latest blocks version has it. We use it on the cart page. 
![Screenshot 2021-03-01 at 12 56 36](https://user-images.githubusercontent.com/90977/109500081-a9a3e500-7a8d-11eb-9db6-9b8c1c327116.png)
