### ISSUE TITLE
Country and State address inputs grow/shrink incorrectly

### ISSUE THREAD

**Issue by theritesite** [woocommerce/woocommerce-gutenberg-products-block#3847]
Minor.
On multiple themes and multiple versions of WP & WC, the Checkout Block Country and State inputs are in a "shrunken" state until hover, or active. This makes the text illegible if there is already a pre-populated address until hover or active state.

## To reproduce
1. Have customer address saved (for checkout use). Store country was set to United States.
2. Visit checkout page with checkout block.
3. Notice in billing & shipping the shrunken state of Country and State

## Expected behavior
If data is present in field, the field should grow to match other fields sizes. Otherwise, the label should go away to view the country or state without overlap.

## Screenshots
![image](https://user-images.githubusercontent.com/26701248/107976532-f4ded380-6f76-11eb-8066-83d605045a69.png)

### WordPress (please complete the following information):
* Core version: 5.5.3 & 5.6
* WooCommerce version: 4.7.0 & 5.0.0
* WooCommerce Blocks version: 4.2.0 & 4.4.2

### Desktop (please complete the following information):
* OS: MACOS
* Browser: chrome, safari
* Repeatable on mobile

**Comment by Aljullu** [comment]
HI @theritesite, thanks for opening this issue, could you tell us some of the themes that are affected by this issue? This would help us diagnose whether that's an issue in the theme or something we can fix in WC Blocks.

Thanks in advance!

**Comment by theritesite** [comment]
Hi!
I am using twenty twenty-one, Hello Elementor, and further tested on storefront, twenty nineteen, and twenty twenty.

**Comment by theritesite** [comment]
Also, I have now tested those themes using the 4.5.2 version, and with other plugins turned off. Additional CSS is empty and none of the themes have been modified nor have child themes.

**Comment by Aljullu** [comment]
Hi @theritesite, thanks for the details. Unfortunately, I'm still unable to reproduce, this is how it looks for me with Storefront:

![imatge](https://user-images.githubusercontent.com/3616980/108977163-8e4d6a00-7688-11eb-88dc-18fda2d0e51b.png)

and Twenty Twenty One:

![imatge](https://user-images.githubusercontent.com/3616980/108977074-7a096d00-7688-11eb-8862-901dbf32ddb5.png)

If you have a URL to share, we could take a look to investigate if it's an issue in WC Blocks. You can also try in a fresh install before installing any other plugin and see if it's reproducible there.

**Comment by theritesite** [comment]
Hi!

Looks like it was actually a plugin that added other blocks. Styles were getting extracted from a wordpress component that applied extra select-control components.

Sorry for the confusion, I will mark it closed as the issue was definitely our side!

Thank you for the responses!
