### ISSUE TITLE
Implement memoization for wp.data

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#3855]
While implementing memoization for https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3835 to avoid rerunning the same 3PD code several times, we ended up discovering that our wp.data store is not memorizing its selector and therefore creating new instance several times, up to 13 times in each render cycle.

After asking around, this is the conclusion we had:
- Our selector should never return a raw `[]` or `{}` but should always use `EMPTY_OBJECT` and `EMPTY_ARRAY` (https://github.com/WordPress/gutenberg/blob/4872d1983db04d685de1816a81177caba5a36903/packages/editor/src/store/selectors.js#L48-L64).
Example: instead of
```js
export const getCartErrors = ( state ) => {
	return state.errors || [];
};
```
Do
```js
export const getCartErrors = ( state ) => {
	return state.errors || EMPTY_ARRAY;
};
```
Instead of
```js
export const useStoreCart = ( options = { shouldSelect: true } ) => {
	const { shouldSelect } = options;

	const results = useSelect(
		( select ) => {
			const store = select( storeKey );
			const cartData = store.getCartData();

			return {
				cartItems: cartData.items || [],
				cartItemErrors: cartData.errors || [],
				extensions: cartData.extensions || {},
				shippingRates: cartData.shippingRates || [],
				paymentRequirements: cartData.paymentRequirements || [],
			};
		},
		[ shouldSelect ]
	);
	return results;
};
```
Do
```js
export const useStoreCart = ( options = { shouldSelect: true } ) => {
	const { shouldSelect } = options;

	const results = useSelect(
		( select ) => {
			const store = select( storeKey );
			const cartData = store.getCartData();

			return {
				cartItems: cartData.items || EMPTY_ARRAY,
				cartItemErrors: cartData.errors || EMPTY_ARRAY,
				extensions: cartData.extensions || EMPTY_OBJECT,
				shippingRates: cartData.shippingRates || EMPTY_ARRAY,
				paymentRequirements:
					cartData.paymentRequirements || EMPTY_ARRAY,
			};
		},
		[ shouldSelect ]
	);
	return results;
};
```
- All of our selectors should be memoized to avoid returning new values several times in a row, we do this by making sure our objects don't change at the reducer level, or if the object is constructed on the selector, it is memoized.
- instead of using raw default values inside our selectors, we define those values in a const and use that.
Example: instead of 
```js
/**
 * Retrieves cart meta from state.
 *
 * @param {Object} state The current state.
 * @return {Object} The data to return.
 */
export const getCartMeta = ( state ) => {
	return (
		state.metaData || {
			applyingCoupon: '',
			removingCoupon: '',
		}
	);
};
```
Do
```js
const defaultCartMeta = {
	applyingCoupon: '',
	removingCoupon: '',
};

export const getCartMeta = ( state ) => {
	return state.metaData || defaultCartMeta;
};
```

More reading:
https://riad.blog/2020/02/14/a-journey-towards-a-performant-web-editor/

**Comment by nerrad** [comment]
I generally agree with this and it will be a good change. The one thing to watch for is that the defaults aren't mutated anywhere (but that applies equally to any technically mutable state).
