### ISSUE TITLE
Cart subtotals not updating, or summary order on checkout page

### ISSUE THREAD

**Issue by caitnig** [woocommerce/woocommerce-gutenberg-products-block#3873]
After the latest update, the subtotals no longer updated correctly.

![image](https://user-images.githubusercontent.com/79385825/108612068-c892df00-73dc-11eb-906e-7266a8424baa.png)

![image](https://user-images.githubusercontent.com/79385825/108612076-dc3e4580-73dc-11eb-9f74-a0c31d6ac079.png)

**Comment by Aljullu** [comment]
Hi @caitnig, thanks for opening this issue. I was able to reproduce this issue with this currency options:

![imatge](https://user-images.githubusercontent.com/3616980/108694932-fae92d00-74ff-11eb-8ab5-d2038527ea98.png)

I'm currently investigating a fix for this.

**Comment by Aljullu** [comment]
PR with a potential fix created: https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3876.

**Comment by caitnig** [comment]
Great. As a temporary measure, I've set number of decimals to 2 so that's it's displaying correctly until a fix is rolled out.
