### ISSUE TITLE
cart block needs css editor so that customize the cart appearance. 

### ISSUE THREAD

**Issue by alsrmurad** [woocommerce/woocommerce-gutenberg-products-block#3880]

**Comment by Aljullu** [comment]
Hi @alsrmurad, you can access the WordPress CSS editor from Appearance > Customize, there you can add as many CSS rules as you want. We have specific [docs about theming WC Blocks](https://github.com/woocommerce/woocommerce-gutenberg-products-block/tree/trunk/docs/theming) and specifically the [Cart and Checkout blocks](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/theming/cart-and-checkout.md) which might be useful to you.
