### ISSUE TITLE
Possible React conflict with other block plugins

### ISSUE THREAD

**Issue by HardeepAsrani** [woocommerce/woocommerce-gutenberg-products-block#389]
**Describe the bug**
`classnames` is defined in devDependency instead of dependencies: https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/5f4466f77783a3033e853a6d30d3d529fd3cf0de/package.json#L40

This is causing an issue with our plugin [Otter](https://wordpress.org/plugins/otter-blocks/) and WooCommerce blocks.

The issue is... WooCommerce block won't load any more (or Otter won't load but Woo will for some), and throws this error in console:

<img width="561" alt="screen shot 2019-02-01 at 5 15 34 am" src="https://user-images.githubusercontent.com/2649903/52093258-99845780-25e0-11e9-9dea-f65e1cca50de.png">

In all honesty, I'm not sure what might be causing this error. There's surely nothing wrong in PHP or JS side, apart from both using `classnames` 😄 

This error isn't consistent in all instances, but always happens on poopy.life (as well as some other places where we tested).

**Comment by HardeepAsrani** [comment]
Or, it might be due to react and react-dom being used from outside instead of using the one available in the core using aliases.

**Comment by ryelle** [comment]
@HardeepAsrani I've tried downloading [the Otter Blocks plugin](https://wordpress.org/plugins/otter-blocks/), but I'm not seeing the same errors when I try to edit posts with both product blocks and otter-provided blocks. Do you see this when using any combination of blocks in particular? Which version of WP & the woo blocks plugin are you using?

- Core version: [e.g. 5.0.3]
- Gutenberg version (if installed): [e.g. 4.8.0]
- WooCommerce version: [e.g. 3.5.3]
- WooCommerce Blocks version: [e.g. 1.3.1]
- Site language:
- Any other plugins installed:

**Comment by HardeepAsrani** [comment]
Core, Woo, and Woo Blocks are latest from WordPress.org, and Gutenberg isn't installed.

Site language is US English (default), and no other plugins are installed. I pushed a new update last night where I list dependencies properly in our Otter, and since then it's working properly in Otter and Woo isn't loaded.

As I said, this is pretty inconsistent as I'm not able to reproduce this locally, while it's happening in many test environments, such as poopy.life or https://jurassic.ninja/ (which is Automattic owned, so you will be able to reproduce it here).

You can just install these three plugins (no need to config or add products to Woo), and just open the editor to see errors pop-up in the console).

Also, I faced a similar issue with one other plugin which seemed to be caused by their use of React/ReactDOM externally instead of using from Core (using externals in webpack).

There's nothing wrong with the code in both plugins, so I guess it has something to do with dependencies.

Thank you for looking into this issue for me. 😄

**Comment by HardeepAsrani** [comment]
Let me make an instance of jurassic.ninja for you with the configurations. 😄

**Comment by HardeepAsrani** [comment]
Link: https://chinese-sturgeon.jurassic.ninja/wp-admin/post-new.php
User: `demo`
Pass: `cJcxdFxqPyje`

Able to reproduce here. @ryelle

**Comment by HardeepAsrani** [comment]
Can you just remove react and react-dom and use the one from code to see if it works? That's my best guess at this moment. 😄

**Comment by HardeepAsrani** [comment]
@ryelle Few users are complaining about it, any updates?

I noticed a few things:

1. If I install your plugin and run the `npm start` then the development build works just fine. The issue only happens once I build the code.

2. `classnames` is listed in your `devDependencies,` while it's a production dependency. There could be other similar scripts that you have added in devDep which are supposed to be for production?

**Comment by HardeepAsrani** [comment]
Do see similar small mistakes here: https://github.com/woocommerce/woocommerce-admin/blob/master/package.json - which I believe is being used in this plugin, so could be an issue with that, maybe?

**Comment by HardeepAsrani** [comment]
I suspect this could be the issue: https://medium.com/@cliffers/how-to-run-multiple-webpack-instances-on-the-same-page-and-avoid-any-conflicts-4e2fe0f016d1

**Comment by HardeepAsrani** [comment]
Figured the issue out: https://github.com/webpack/webpack/issues/8872

I'll send a PR with a fix. This should ideally be fixed *inside* Gutenberg as well as any plugin that uses it.

I literally spent hours trying to debug but Webpack doesn't show any warning so it's quite hard to debug it. Luckily, I was sitting with someone who experienced the same issue just few days ago so that's just getting extremely lucky. I'll send a pr soon. 😄

**Comment by HardeepAsrani** [comment]
@ryelle This should fix it: https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/518

This won't affect anything in development but in the production. Development version never had any conflict because webpack uses jsonFunction only during production.

Let me know if you see any issues with it.

**Comment by HardeepAsrani** [comment]
To add more context here, both of our plugins make a `vendor` chunk which is the reason for this conflict, in my limited knowledge of webpack.

So this will cause an issue with every single project that does this, not just our plugin. It's recommended by webpack to use a custom jsonpFunction to avoid it.
