### ISSUE TITLE
Order summary: with a screen reader it's not clear what's the difference between the cart item subtotal and the product price

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#3906]
In the Checkout Order Summary, we display all products with its unitary price and the cart item price. While the alignment helps explain their meaning (unitary price on the left, under the title / cart item price aligned to the right in bold), nothing of this is obvious to screen reader users, which will get two prices read without any clue of which one is which.

<img src="https://user-images.githubusercontent.com/3616980/109668318-586d2180-7b71-11eb-9782-32343efb9b3b.png" alt="Order summary screenshot" width="363" />

**Comment by ovidiul** [comment]
Opened up a PR here https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/4810 to address this accessibility issue.
