### ISSUE TITLE
add ability to modify category of Featured Category block

### ISSUE THREAD

**Issue by EdithAllison** [woocommerce/woocommerce-gutenberg-products-block#3912]
## Is your feature request related to a problem? Please describe.
We've just done an update to the category structure of the site. After the update it became clear that there is no way to update an existing "Featured Category" block. Instead we had to delete / add, thereby losing all settings for the block.

## Describe the solution you'd like
I'd love to have a way to change the category for an existing "Featured Category" block.
## Describe alternatives you've considered
The only alternative curently is to delete the old block and add a new one.

**Comment by senadir** [comment]
Hey @EdithAllison
Thank you for your feedback, I'm going to break your issue into two issues, but I can't promise when this is going to be fixed.

**Comment by senadir** [comment]
Width issue moved to https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3915
