### ISSUE TITLE
Provide option to make City field required

### ISSUE THREAD

**Issue by Andrewkow** [woocommerce/woocommerce-gutenberg-products-block#3926]
## What do you like about the Cart & Checkout blocks?
Nice layout design and checkout flow!

## What do you think is missing from the Cart & Checkout blocks?
If we could set the "City" field to be required field that would be great because some user they miss out the field.

Thank you!

**Comment by senadir** [comment]
Hey there @Andrewkow
Thank you for your feedback, I'm going to rename this issue so it's more descriptive and triage it accordingly.
Later on, we might fix this directly, close, or provide some sort of solution.

**Comment by Andrewkow** [comment]
Hi Seghir,

Thank you so much for taking this attention. Please update me again on this
issue.

Cheers
Andrew

**Comment by mikejolley** [comment]
@Andrewkow what locale/country requires the city field? This might need to be updated in Woo core rather than an option in blocks.

**Comment by Andrewkow** [comment]
Hi Mike,

We're selling in Singapore, which is a city-state country. Normally, we
fill in the city field with "Singapore" also. But some users/customers will
leave it blank and it will cause issues while we create shipments with a
third-party delivery company. We just want the "City" field to have the
option as a compulsory field.

**Comment by mikejolley** [comment]
@woocommerce/proton Should we move this over to core so the address locale can be changed for Singapore?

**Comment by Andrewkow** [comment]
I think that's the better option, especially those who doesn't us Gutenberg
block for check-out page.

Thanks!

**Comment by vedanshujain** [comment]
@mikejolley please move this one to the core. Thanks!

**Comment by nerrad** [comment]
Issue moved to [woocommerce/woocommerce #29455](https://github.com/woocommerce/woocommerce/issues/29455) via [**ZenHub**](https://www.zenhub.com/)
