### ISSUE TITLE
Improve layout for Order Summary section in the checkout block

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#3927]
This layout change helps improve the legibility of the order summary section. In the current structure we find this (including subscriptions in the example):

<img width="759" alt="CleanShot 2021-03-06 at 16 34 06@2x" src="https://user-images.githubusercontent.com/1429108/110221346-d2671880-7e99-11eb-83ef-8534591f6109.png">

Some observations from the current implementation:

- There are line breaks between the price and "due" label depending on the length of the price.
- Description, subscription attributes such as color, sign up fee, and trial details live under the subscription details, and might be hard to read at a glance.
- Having all the information on the left can create visual clutter.

## Changes

The adjustments apply distinct labels and prices along with typographic variables to fix the line breaks. Here's a structure map:

<img width="746" alt="CleanShot 2021-03-06 at 16 37 05@2x" src="https://user-images.githubusercontent.com/1429108/110221436-3558af80-7e9a-11eb-9760-7e9d2e7d9c79.png">

Translated to design:

<img width="781" alt="CleanShot 2021-03-06 at 16 37 31@2x" src="https://user-images.githubusercontent.com/1429108/110221443-430e3500-7e9a-11eb-8c44-db00a3c9d861.png">

Along with some observations on the design:

<img width="778" alt="CleanShot 2021-03-06 at 16 37 56@2x" src="https://user-images.githubusercontent.com/1429108/110221451-53261480-7e9a-11eb-8349-d542fc159dc4.png">

## Resources

- Figma File: (eaQcoMs7E8Ys0YgxfkOKxR-fi-491%3A1)
- P2 Post: (pca54o-15I-p2)

**Comment by senadir** [comment]
Thank you for filling out the issue Darren.

**Comment by senadir** [comment]
While I have a local PR already lined up for this, there are still unanswered questions in the P2 post preventing me from fully finishing. I went along and had this in the icebox until I know for certain how we're going to handle the remaining cases.

**Comment by Aljullu** [comment]
What was the plan with this? Should we reopen @nerrad @senadir?

**Comment by nerrad** [comment]
I think we should reopen.
