### ISSUE TITLE
PaymentMethodCard does not display checkbox 

### ISSUE THREAD

**Issue by paymentplugins** [woocommerce/woocommerce-gutenberg-products-block#3928]
## Describe the bug
The `CheckboxControl` used for saving a payment method does not render in the `PaymentMethodCard` component. The `PaymentMethodCard` component located in `assets/js/blocks/cart-checkout/payment-methods/payment-method-card.js` accepts an argument `showSaveOption` which determines if the save payment method checkbox is rendered. The parent component `PaymentMethodOptions` passes an unused property `allowsSaving` and  `showSaveOption` is never defined.

The boolean value `supports.savePaymentInfo` that is passed to `allowsSaving` is a deprecated property in the `PaymentMethodConfig` class and has been replaced by `supports.showSaveOption`. 

## To reproduce
Navigate to the checkout page and select a payment method that supports the `showSaveOption`. Despite the payment method supporting this feature the checkbox will not render.

## Expected behavior
If a payment method supports the `showSaveOption` the checkbox associated with saving a payment method should render.

### WordPress (please complete the following information):
* Core version: 5.6.2
* Gutenberg version (if installed): N/A
* WooCommerce version: 5.0
* WooCommerce Blocks version: 4.6.0
* Site language: EN
* Any other plugins installed:

### Desktop (please complete the following information):
* OS: Windos
* Browser: Chrome
* Version 88.0.4324.190

**Comment by senadir** [comment]
Hey there @paymentplugins 
I will look into this issue to see if we can reproduce it, we had a somehow recent refactor in that area that could have caused this.

**Comment by paymentplugins** [comment]
Hi @senadir,

Thank you for taking a look at this issue.

Kind Regards,
