### ISSUE TITLE
All Products Block and Product Attributes Filter

### ISSUE THREAD

**Issue by ajgw** [woocommerce/woocommerce-gutenberg-products-block#3929]
![Bildschirmfoto 2021-03-07 um 14 02 35](https://user-images.githubusercontent.com/3390880/110240787-d48aaf00-7f4d-11eb-9172-58618c727e85.png)
I have setup a page with columns, in left column is a block Filter by Attribute and set to "or", in right column is the All Products Block. If I am on page and try to use the Filters and select more than one filter, only products from alphabetical top products are shown. Products from second attribute do not show. But I am able to select more than one attribute to filter by.

I am on Mac, use Safari and Blocks from WC 5.0 but not this extra plugin.

**Comment by opr** [comment]
Hi there, thanks for your report - I have tried to replicate this using only WooCommerce 5.0 but I was unable to. Could you confirm you're not using any other plugins and that this is reproducible using only WooCommerce 5.0? 

Please also double check that the "or" option is selected. The way this option is displayed is sometimes confusing, this is how it should appear when "or" is selected. 
![image](https://user-images.githubusercontent.com/5656702/110622041-da250680-8192-11eb-9f6e-97e9a1946c67.png)
(Please note the selected option has a blue background with white text)


It would also be helpful to see your System Status report - instructions on how to provide that can be found at this URL: https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/#section-1 and a link to the page where this issue is happening on your website would also be a great help.

**Comment by ajgw** [comment]
@opr Hi, I checked this on a staging site with few products and you are right, there it works fine. But after upgrading to WC 5.1 the All Products Block does not render anymore. Live Site was updated this morning so I couldn't check there if any other Plugin is involved in this. And yes I tried both settings "and" and "or".

I attached system status from live site were bug was first seen.

Thanks.
[systemstatus.txt](https://github.com/woocommerce/woocommerce-gutenberg-products-block/files/6115517/systemstatus.txt)

**Comment by opr** [comment]
Thanks @ajgw - could you confirm that this is the page where you're seeing the error? https://atelier-an-der-muehle.de/fotowelten/

You mentioned that
> after upgrading to WC 5.1 the All Products Block does not render anymore

but for me the All Products Block and Filter by Attribute block on this page seem to be working correctly.

**Comment by ajgw** [comment]
Thanks @opr too. Yeah, that is correct page.
Hmm … I checked this on iPad and yes, all works fine. But if I call page on Safari on Mac (Version 14.0.3 (15610.4.3.1.6, 15610)) I get error and many javascript errors in javascript console.
Same in backend were Block does not render but instead I get a error that Block has error and no preview can be shown.

Same bug on staging site were only WC is activated, no other plugin. I use Storefront theme most times.

![Bildschirmfoto 2021-03-10 um 13 17 08](https://user-images.githubusercontent.com/3390880/110628123-09437400-81a3-11eb-90bc-053f6a5ed4b5.png)
![Bildschirmfoto 2021-03-10 um 13 17 39](https://user-images.githubusercontent.com/3390880/110628141-0ea0be80-81a3-11eb-9706-3b2dc8b2866f.png)

**Comment by opr** [comment]
Thanks for the update, could you share the link to the staging site if possible? I can't reproduce this in Safari either so I'm keen to find a place where I can. Can you verify if this happens in other browsers on your system? (Chrome, Firefox for example).

**Comment by ajgw** [comment]
OK, checked in Chrome on Mac and there are no issues. Seems that only Safari on Mac has this.

Page on Stagingsite is this: https://bremerhaven-shopping.de/stage1/all-products/

**Comment by ajgw** [comment]
Wondering: after installing WooCommerce Blocks 4.6 Plugin, now I can use the All Products Block again – in admin and frontend too.

**Comment by ajgw** [comment]
Checked on Livesite with WooCommerce Blocks Plugin too and yes, now I see Block with contents in admin and frontend. And selecting more than one attribute works now as expected. With extra plugin installed all works fine and you may set this to resolved and close comment? :)

**Comment by opr** [comment]
Hey there @ajgw, thanks for looking into this again and working with us to get this resolved. Glad it's working on your end now. Thanks for using WooCommerce Blocks! Have a great day.
