### ISSUE TITLE
Evaluate using #start-resizable-editor-section to get responsive styles in the editor preview

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#3931]
From @nerrad:

> Responsive styles for blocks in the editor can use the `#start-resizable-editor-section` and `#end-resizable-editor-section` (see [make post](https://make.wordpress.org/core/2020/08/04/new-editor-preview-options/)). We might want to look into implementing this for various previews of our blocks in responsive views.

Cart and Checkout block currently use the [`useContainerQueries()` hook](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/assets/js/base/hooks/use-container-queries.js), so they are not affected. But all other blocks with responsive styles might benefit from those markers.

**Comment by nerrad** [comment]
Just noting this has a dependency on Woo Blocks having a minimum requirement of at least WordPress 5.5 before implementing this.
