### ISSUE TITLE
Best seller by time range

### ISSUE THREAD

**Issue by erikdemarco** [woocommerce/woocommerce-gutenberg-products-block#3943]
Hi, please add best seller block option to show based on certain timerange (for example by: last week, last month, last year, all time).
Currently woocommerce block only support showing all time best seller. Which a bit doesnt make any sense. New product hit the market all the time. there is no point showing very old best seller product. If you look all the big boys in marketplace. They never show all time best seller instead their best seler data based on daily or weekly. Look Amazon, look aliexpress. etc.

Please consider this feature.

**Comment by nerrad** [comment]
Hi there @erikdemarco  👋 

Thanks for taking the time to leave your feature request. While we appreciate you sharing your idea with us, it doesn’t fit in with our current priorities for the project. This doesn't mean what you are suggesting isn't a good idea or doesn't make sense - it's just that we have limited time to work on various projects. At some point we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. In the meantime, don't be alarmed if you don’t see any activity on this issue for a while.
