### ISSUE TITLE
[GlobalStep] "Product Catalog" fails to display limit of 6 for "Products per row and Rows per page" field as displayed on Page Editor

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-gutenberg-products-block#3948]
## Bug Description:
"Product Catalog" fails to display limit of 6 for "Products per row and Rows per page" field as displayed on Page Editor

## Environment:
Woocommerce Version: WooCommerce 5.1 and 5.0
WordPress version: (v5.7)

PC:
Windows 10, Mac 10.14.6
Chrome(Version 88.0.4324.104) 
Firefox(Version 86.0)
Safari: v13.1.2(13609.3.5.1.5)

# Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins
1. Complete the onboarding setup wizard.
1. Add products/ import products from "Add my products" option on Woocommerce->Home Page
1. Go to Appearance->Customize.
1. Select "WooCommerce->Product Catalog" option.
1. Set the Products per rows to 7 or above and Rows per page to 7 or above.
1. Observe that "Product Catalog" fails to display limit of 6 for "Products per row" field as displayed on Page Editor

**Note**:
Observed for "Twenty-Twenty theme" for both the field mentioned above and for Storefront this issue is observed only for "Rows per page" field

## Actual Result:
"Product Catalog" fails to display limit of 6 for "Products per row and Rows per page" field as displayed on Page Editor

## Expected Result:
"Product Catalog" should display limit of 6 for "Products per row and Rows per page" field as displayed on Page Editor

## Video:

https://user-images.githubusercontent.com/41110392/110654251-fc934000-81e3-11eb-8be5-2b030356bdf8.mp4

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by opr** [comment]
Thanks for reporting this, I was able to reproduce, but I believe this to be an issue in WooCommerce Core, so I will move this issue there.

**Comment by opr** [comment]
Issue moved to [woocommerce/woocommerce #29347](https://github.com/woocommerce/woocommerce/issues/29347) via [**ZenHub**](https://www.zenhub.com/)
