### ISSUE TITLE
[GlobalStep] For Twenty Twenty One theme, "Sale" badge appears misaligned if "Products per row" is set to "1".

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-gutenberg-products-block#3949]
## Bug Description:
For Twenty Twenty One theme, "Sale" badge appears misaligned if  "Products per row" is set to "1".

## Environment:
Woocommerce Version : WooCommerce 5.1 and 5.0
WordPress version: (v5.7)

PC:
Windows 10, Mac 10.14.6
Chrome(Version 88.0.4324.104) 
Firefox(Version 86.0)
Safari: v13.1.2(13609.3.5.1.5)

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins
1. Complete the onboarding setup wizard.
1. Select Twenty Twenty One theme.
1. Add some products.
1. Go to Appearances->Customize.
1. Select WooCommerce->Product catalog option.
1. Set the Products per row value to "1".
1. Observe that "Sale" badge appears misaligned.

## Actual Result:
For Twenty Twenty One theme, "Sale" badge appears misaligned if "Products per row" is set to "1".

## Expected Result:
For Twenty Twenty One theme, "Sale" badge should be aligned if "Products per row" is set to "1".

## ScreenShot:

![#3949](https://user-images.githubusercontent.com/41110392/110654742-6ad80280-81e4-11eb-9c67-61273f38f92a.png)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by opr** [comment]
Hi, thank you for reporting this. This is not controlled by WooCommerce Blocks, it is actually WooCommerce core that is responsible for this.

I will move the issue to the WooCommerce repository.

**Comment by opr** [comment]
Issue moved to [woocommerce/woocommerce #29343](https://github.com/woocommerce/woocommerce/issues/29343) via [**ZenHub**](https://www.zenhub.com/)
