### ISSUE TITLE
Products by Category turns into Products by Taxonomy

### ISSUE THREAD

**Issue by alantygel** [woocommerce/woocommerce-gutenberg-products-block#3963]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when I try to show my products using a custom taxonomy.

## Describe the solution you'd like
I propose that the Products by Category block could turn into a Products by Taxonomy block, adding one option (select taxonomy).

## Describe alternatives you've considered
Going further, this could even merge Products by Category and Products by Tag in only one block, making this block a generic option for every taxonomy associated to Products.

**Comment by nerrad** [comment]
Hi there @alantygel   👋 

Thanks for taking the time to leave idea here for improving options by having a Products by Taxonomy. While we appreciate you sharing your idea with us, it doesn’t fit in with our current priorities for the project. This doesn't mean what you are suggesting isn't a good idea or doesn't make sense - it's just that we have limited time to work on various projects. At some point we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. In the meantime, don't be alarmed if you don’t see any activity on this issue for a while.

**Comment by alantygel** [comment]
So simple, and so useful ;)
