### ISSUE TITLE
Address data not sent to API on checkout block after using shortcode cart's address shipping calculator

### ISSUE THREAD

**Issue by opr** [woocommerce/woocommerce-gutenberg-products-block#3975]
## Describe the bug
When using a combination of the shortcode cart, and the checkout block, if you use the shipping calculator on the shortcode block, but update the address without making any changes, then your pre-filled address data will not be sent to the API when checking out.

Thanks to @waclawjacek for originally finding this.

## To reproduce
This can be a little tricky to reproduce, you may have to complete an order first to get the address to save. See this loom for a reproduction.
https://www.loom.com/share/5e97fe53b2e74c76a47ea96fe6274294

1. Go to the shortcode cart, ensure the shipping calculator has a saved address in.
2. If it does not, then you may need to complete an order.
2. Open the shipping calculator and save the address without making any changes.
2. Proceed to checkout (you should be using the checkout _block_) and try to complete the order without changing any address fields. (You may need to fill some required fields)
3. Observe the error: `Sorry, we do not ship orders to the provided country ()`

## Expected behavior
Given the address is valid when arriving on the checkout block, the order should complete when the "Place order" button is pressed.

### WordPress (please complete the following information):
* Core version: 5.7
* Gutenberg version (if installed): n/a
* WooCommerce version: 5.1.0
* WooCommerce Blocks version: trunk

**Comment by ralucaStan** [comment]
I did a lot of testing on this one. One situation I came across repeatedly:
- I follow the testing steps
- I see the error, BUT the country field is sent (see image below)
- I click the submit again without changing anything
- The form is submitted

<img width="1270" alt="Screenshot 2021-03-25 at 17 36 54" src="https://user-images.githubusercontent.com/1628454/112517940-d0092780-8d90-11eb-8a4a-02aab9d0c93f.png">


So I think this is not front-end related and it might be a back-end bug. @mikejolley do you have any idea of what might be causing this? Could you point me towards what you think could cause this?

Also noticed while testing:
- The data is not added consistently to the shipping address after the 3rd step. Sometimes names are missing, zip code as well. 
- I actually modified the country in the cart Change address form. When I went to check out I got a similar error for other fields that were also sent from the FE. Don't know if it's related.
<img width="1158" alt="Screenshot 2021-03-25 at 17 55 00" src="https://user-images.githubusercontent.com/1628454/112521138-13b16080-8d94-11eb-9f56-d47feb718d35.png">

**Comment by mikejolley** [comment]
@Raluca I actually have no idea where to begin with this one. You could probably start by seeing what is actually set in the order object when this point is hit: https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/952d38a204dd4f4956c1af2846bb9f7d71ab820f/src/StoreApi/Utilities/OrderController.php#L215

**Comment by mikejolley** [comment]
@ralucaStan just to let you know I'm looking at this in more depth today.

**Comment by mikejolley** [comment]
I think it's caused by this which I just created a PR for ^ 

I will attempt a workaround our side to avoid these getters.
