### ISSUE TITLE
Cart and checkout country selects do not prevent keypresses being captured elsewhere

### ISSUE THREAD

**Issue by opr** [woocommerce/woocommerce-gutenberg-products-block#3976]
## Describe the bug
On a Jetpack connected site where the notification panel is present (You may need to use a JN site, I could not get the notification panel to show on my local installation) when typing in the select box for country on either the cart (Shipping calculator) or checkout address fields the keypresses can bubble up and be caught by other elements of the UI.

For example typing `u n i` to get to "United Kingdom" will cause the notification panel to be opened when `n` is pressed.

Thanks to @waclawjacek for initially finding this.

## To reproduce

1. Go to a Jetpack connected site and ensure you're logged in - ensure the notification panel is available in the admin bar.
2. Go to the cart block and use the shipping calculator, start typing `u n i`, and see the notification panel opens when you press `n`.
3. Do the same on the checkout block.

## Expected behavior
This input should capture all keystrokes and not let them bubble up.

## Screenshots
Loom: https://www.loom.com/share/2dbe6a589c4541599438782d066151a7

### WordPress (please complete the following information):
* Core version: 5.7
* WooCommerce version: 5.1.0
* WooCommerce Blocks version: 4.7.0

### Desktop (please complete the following information):
* OS: Mac OS
* Browser Reproducible in Brave/Chrome, Firefox, and Safari

**Comment by opr** [comment]
I have opened an upstream issue https://github.com/WordPress/gutenberg/issues/30204 which should resolve this.

**Comment by opr** [comment]
A fix for this has been merged upstream (https://github.com/WordPress/gutenberg/pull/30557), when the next version of `@wordpress/components` is released this can be closed.

**Comment by mikejolley** [comment]
https://github.com/WordPress/gutenberg/blob/trunk/packages/components/CHANGELOG.md looks like we just need to bump the version.
