### ISSUE TITLE
Raw HTML sometimes appears in checkout error message when shortcode cart shipping calculator is used

### ISSUE THREAD

**Issue by opr** [woocommerce/woocommerce-gutenberg-products-block#3977]
## Describe the bug
When you are using the shortcode cart's shipping calculator, and don't enter a ZIP code, when you try to check out in the checkout block the API will return this error:
![image](https://user-images.githubusercontent.com/5656702/111631580-75e5f080-87eb-11eb-8c6e-a77452f240fe.png)

Thanks to @waclawjacek for finding this!

## To reproduce
Steps to reproduce the behaviour:

1. Enable WooCommerce Shipping and Tax
1. Go to the shortcode cart.
2. Use the shipping calculator, select United States as your country, but leave ZIP code empty.
2. Proceed to checkout.
3. Fill in all fields, including ZIP code.
4. See error.

## Expected behaviour
The checkout should work when the ZIP code is entered on the checkout block.

## Screen capture
View reproduction here: https://d.pr/i/RrLNVa

### WordPress (please complete the following information):
* Core version: 5.7
* WooCommerce version: 5.1.0
* WooCommerce Blocks version: trunk

**Comment by waclawjacek** [comment]
I didn't confirm this but it is possible that the problematic HTML is created here: https://github.com/Automattic/woocommerce-services/blob/develop/classes/class-wc-connect-shipping-method.php#L249

If so, this would make this an issue with how Blocks and WooCommerce Shipping & Tax communicate.

**Comment by opr** [comment]
I can confirm that this _exact_ bug is not happening without WooCommerce Shipping and Tax enabled, however something similar happens, but the replacement message is: `There was a problem with the provided shipping address: Address is required, ZIP is required` without any HTML.
