### ISSUE TITLE
[GlobalStep] No spacing between "Search" and "All Products" block on front end

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-gutenberg-products-block#3985]
## Bug Description:
No spacing between "Search" and "All Products" block on front end for "Twenty Twenty-One" and "Twenty Twenty" theme

## Environment:
Woocommerce Version : WooCommerce 5.1 and 5.0
WordPress version: (v5.7)
WooCommerce Admin version: v2.0.2

PC:
Windows 10, Mac 10.14.6
Chrome(Version 88.0.4324.104) 
Firefox(Version 86.0)
Safari: v13.1.1

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins
1. Complete the onboarding setup wizard.
1. Select any one of the theme among these two: "Twenty Twenty-One" and "Twenty Twenty" 
1. Go to Pages->Add New 
1. Add "Search" Product and "All Products" block
1. Click on "Publish" button and "Preview" button
1. Observe that their is no spacing between "Search" and "All Products" block on front end

**Note:**
Didn't observe this issue on "StoreFront" and "Twenty-Nineteen" theme

## Actual Result:
No spacing between "Search" and "All Products" block on front end

## Expected Result:
Spacing should be present between "Search" and "All Products" block on front end

## ScreenShot:
![ #29410_1](https://user-images.githubusercontent.com/41110392/111489025-cadc2500-875f-11eb-8994-4679daadddca.png)
![#29410_2](https://user-images.githubusercontent.com/41110392/111489071-d3ccf680-875f-11eb-9912-48f911dffa89.png)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by mikejolley** [comment]
I wasn't able to replicate this one on either. The Form element in the Search Block has correct margins. Screenshot:

<img width="781" alt="Screenshot 2021-03-25 at 16 58 24" src="https://user-images.githubusercontent.com/90977/112512750-8f5adf80-8d8b-11eb-8611-a3e20413d700.png">

**Comment by Aljullu** [comment]
Same results as @mikejolley, I can see margin in both TwentyTwenty and TwentyTwentyOne. Closing for now, we can reopen if we can reproduce it at some point.
