### ISSUE TITLE
No option to return to regular width display

### ISSUE THREAD

**Issue by roykho** [woocommerce/woocommerce-gutenberg-products-block#400]
**Describe the bug**
After adding a block, the width displayed in the editor is "regular/default" width. If you then select either wide or full width, the display will adjust accordingly however there is no button/icon to show regular/default width.

**To Reproduce**

1. Go to a post
2. Click on add a block - handpicked product block.
3. Note the current default width and click on wide width for example.
4. There is no option to return to the default width.

**Expected behavior**
I am expecting a way to return to the default/regular width.

**Screenshots**
![](http://cld.wthms.co/F7Z4na+)

**Comment by roykho** [comment]
@ryelle so what prompted this question was I've seen this design ![](http://cld.wthms.co/FacTRi+)

**Comment by ryelle** [comment]
Yeah, it's not _totally_ clear but those work the same way - that first one is a toggle for `center`, not default width.
