### ISSUE TITLE
Clarify status of __experimental_woocommerce_blocks_checkout_order_processed hooks

### ISSUE THREAD

**Issue by leewillis77** [woocommerce/woocommerce-gutenberg-products-block#4009]
Following the recent [call-to-action to add support for the new checkout block](https://developer.woocommerce.com/2021/03/15/integrating-your-payment-method-with-cart-and-checkout-blocks/), I'm looking at integration in a couple of plugins I maintain. 

One of the aspects I'm looking at is the fact that the `woocommerce_checkout_order_processed` hook isn't fired, and in its place there is `__experimental_woocommerce_blocks_checkout_order_processed` which was added in #3238. There was also #3359 which was opened to stabilise and document the hook, but it appears that this was closed without the hook being stabilised. 

From an outside party's point of view It's difficult to justify integration while there are such a large set of "experimental" / in-flux APIs (https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/blocks/feature-flags-and-experimental-interfaces.md).

Now that you're asking people to integrate with the checkout block, what's the process to stabilise and formerly support these items, and `__experimental_woocommerce_blocks_checkout_order_processed` specifically.

## Describe the solution you'd like
Clarification on status of `__experimental_woocommerce_blocks_checkout_order_processed` and [other experimental features](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/blocks/feature-flags-and-experimental-interfaces.md).

**Comment by Aljullu** [comment]
Hi @leewillis77, great to hear you are looking into integrating your extensions with the Cart and Checkout blocks.

The call-to-action post from developer.woocommerce.com was mostly intended to payment methods. While we consider the payment method integration API to be pretty stable, the extensibility points for other extensions are still experimental and might suffer changes in the future as we make progress on making Cart and Checkout blocks more extensible.

Hopefully that clarifies the status: integrating payment methods with Cart and Checkout is fairly stable and we suggest 3rd parties to start right now. For other extensions, we are still in a experimental phase so most APIs are not available yet and the ones which are available are experimental so they might change in the future. 3rd parties might play around with these APIs and share their feedback with us, but we don't recommend integrating with them yet until they have been stabilized.

My recommendation would be to stay tuned to [developer.woocommerce.com blog](https://developer.woocommerce.com/blog/). You can also check our [extensibility docs](https://github.com/woocommerce/woocommerce-gutenberg-products-block/tree/trunk/docs/extensibility), where we will add docs for extensibility options as they become stable.
