### ISSUE TITLE
Shipping packages name not shown in the Checkout block

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#4026]
## To reproduce

1. Install [WooCommerce Advanced Shipping Packages](https://woocommerce.com/products/woocommerce-advanced-shipping-packages/).
1. Go to WooCommerce > Settings > Shipping > Shipping classes and create a shipping class. This is an example one I created:
![imatge](https://user-images.githubusercontent.com/3616980/113316832-0dc8fb80-930f-11eb-81fb-8573209ac60a.png)
1. Go to WooCommerce > Settings > Shipping > Packages and create a package. For example:
![imatge](https://user-images.githubusercontent.com/3616980/113317904-2be32b80-9310-11eb-87c9-fccab46c89a4.png)
1. Edit a product (ie: Sunglasses) and set its shipping class to the one you created.
1. In the frontend, add two products to the Cart (ie: Beanie and Sunglasses).
1. Go to the Cart and notice package names are correctly shown in the sidebar:
![imatge](https://user-images.githubusercontent.com/3616980/113318735-0e629180-9311-11eb-9aca-691423f5e63d.png)
1. Now go to the Checkout and notice package names are not shown:
![imatge](https://user-images.githubusercontent.com/3616980/113318822-220df800-9311-11eb-9307-db9b1e15bae7.png)

**Comment by mikejolley** [comment]
Looks like this has since been resolved. This is the checkout now after following instructions:

![Screenshot 2021-05-18 at 11 51 40](https://user-images.githubusercontent.com/90977/118639084-6aa14800-b7cf-11eb-82e6-2e088d6174d5.png)
