### ISSUE TITLE
WP 5.7: Featured category block button alignment

### ISSUE THREAD

**Issue by dreamwhisper** [woocommerce/woocommerce-gutenberg-products-block#4027]
## Describe the bug
Buttons in the featured category block are aligned left instead of center after updating to WordPress 5.7.

## To reproduce

1. Install or update to WP 5.7
2. Create a category and assign it to a product.
3. Create a post or page and insert a featured category block into the page.
4. Select your category, save and view on the front end.
5. Note the button is aligned left instead of center.

## Expected behavior
Button will be aligned center.

### Before

![Screen Shot 2021-04-01 at 11 57 53 AM](https://user-images.githubusercontent.com/1271053/113321386-8913b880-92e1-11eb-8818-ebd0826ad1ee.png)

### After

![Screen Shot 2021-04-01 at 11 32 22 AM](https://user-images.githubusercontent.com/1271053/113321424-9466e400-92e1-11eb-9a80-288b302a0c39.png)

### WordPress (please complete the following information):
* Core version: 5.7
* Gutenberg version (if installed): n/a
* WooCommerce version: 5.1
* WooCommerce Blocks version: 4.8

### Desktop (please complete the following information):
* OS: Mac
* Browser: Chrome
* Version: 89

## Additional context

Button markup has incrementally changed over a few WP releases.

**Comment by Aljullu** [comment]
Thanks for opening this issue @dreamwhisper! It looks like this is the same as #3788, so I will close this one as duplicate. Feel free to follow that bug if you want to know when it gets fixed.
