### ISSUE TITLE
Option to show/hide Product Metadata

### ISSUE THREAD

**Issue by EMBARKwebdesign** [woocommerce/woocommerce-gutenberg-products-block#4045]
Hey there,

I am sure the feature of including product metadata would be useful in some cases. But an option to toggle this on/off would be perfect for all set-ups.

Currently, it's included product descriptions that are overly-long (by design). It's even including media I have inserted into the description.

See here:

![Screenshot 2021-04-07 at 20 07 42](https://user-images.githubusercontent.com/49721730/113920627-eb3a5500-97dc-11eb-91ae-cc1c3bb215f2.png)

Preferred solution:

![Screenshot 2021-04-07 at 20 08 06](https://user-images.githubusercontent.com/49721730/113920655-f9887100-97dc-11eb-97ba-4dde1a5f3d51.png)

Hope that helps explain the reasoing.

Thanks a lot!

**Comment by senadir** [comment]
Hey, there is no option to hide it for now. If you know the option key, you can set its `__experimental_woocommerce_blocks_hidden` value to `true`. This would only hide it in Cart and Checkout.
Setting `hidden` to `true` would do it in both places.

Let me know if this works for you.

**Comment by mikejolley** [comment]
CSS can also be used as a temp solution. Moving to backlog.
