### ISSUE TITLE
Order Shipping Packages Fill Memory Leak

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#4047]
Reported here: https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/4025#pullrequestreview-630507843

https://user-images.githubusercontent.com/1429108/113930901-dac7b180-97bf-11eb-9338-882f6eb2af98.png

Reproducible on trunk. For me, I just needed to change the country select box during checkout to see the error logged to console.

**Comment by mikejolley** [comment]
@nerrad I've raised a fix upstream: https://github.com/WordPress/gutenberg/pull/30667

What should we do with this issue in the meantime?

**Comment by nerrad** [comment]
Let's leave it open but add back to the tier one backlog? This will keep it surfacing for review when the fix in GB eventually gets into a release?

**Comment by mikejolley** [comment]
This fix has been merged upsteam 🎆
