### ISSUE TITLE
Checkout Checkbox for Terms

### ISSUE THREAD

**Issue by rasmus-damgaard** [woocommerce/woocommerce-gutenberg-products-block#4065]
Thank you for some awesome work on both the checkout and cart blocks!

I am missing a Checkbox for the Terms on the final checkout page however. In the EU this is mandatory and as such, we unfortunately can't use the blocks for our webshop. Is there a way to add the checkbox to the checkout page? I have very little coding experience by the way.

Thanks in advance!

**Comment by mikejolley** [comment]
This option doesn't exist yet but is being tracked here:

https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3258

Thanks
