### ISSUE TITLE
Product price atomic block (All Products & Single Product) doesn't honor the "Redirect to the cart page after successful addition" setting

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#4074]
## To reproduce
1. Go to WooCommerce > Settings > Products and check the "Redirect to the cart page after successful addition" option.
2. In the frontend, go to a page with the All Products block.
3. Add a product to your cart using the All Products block.
4. Notice you are not redirected to the cart page.

The same can be reproduced with the Single Product block and the Product price block available in dev builds.

## Expected behavior
You should be redirected to the cart page when adding a product to your cart. This behavior works in the Shop page but it doesn't in the All Products block.

**Comment by mikejolley** [comment]
I guess the main question here is, do we want to support this option, and if not, how can we communicate this? This is one of those options where I think we should revisit how things work. View cart links are shown after adding to cart so it's not a massive inconvenience to use those, and by redirecting we prevent other items being added at the same time.

**Comment by Aljullu** [comment]
I think there are valid use-cases for this option. I'm thinking of stores that only sell one product or the products they sell exclude the others (imagine a site that sells three types of subscriptions, but a user can't have more than one subscription active).

Worth pointing out the same issue happens with the Single product block and the Product price atomic block. I updated the issue description and labels accordingly.

**Comment by Aljullu** [comment]
This seems to be a duplicate of #1766.
