### ISSUE TITLE
Buttons in Featured Product Block align to the left instead of center on all devices

### ISSUE THREAD

**Issue by wpniall** [woocommerce/woocommerce-gutenberg-products-block#4076]
## Describe the bug
The Featured Product Block aligns to the left when it should be aligned to the center on desktop, tablet, and mobile. I see the same issue using the latest version of Storefront, as well as with other themes.

## To reproduce

1. Go to 'Pages > Add New'
2. Add a `Featured Product` block with a Simple Product or Product Variation and leave the default options. The button should be center aligned.
3. Save the page
4. View the page on the front-end and see that the button is aligned to the left

## Expected behavior
I expected the button to be center aligned like it is when editing the page and like the rest of the text in the block.

## Screenshots
Preview when editing the page inside the WP-Admin shows the button is center-aligned with the rest of the text-related content:

![https://d.pr/i/b2gDo0](https://d.pr/i/b2gDo0+) 
Full Size: https://d.pr/i/b2gDo0

On the front-end, the button is no longer aligned to the left but aligned to the left, while the rest of the text is centered like it should be:

![https://d.pr/i/Br7yGc](https://d.pr/i/Br7yGc+) 
Full Size: https://d.pr/i/Br7yGc

### WordPress (please complete the following information):
* Core version: 5.7.1
* WooCommerce version: 5.2.2
* WooCommerce Blocks version: 4.7.2 (WooCommerce core bundled version)
* Site language: en_US
* Any other plugins installed: None
* Theme: Storefront 3.5.1
 
### Desktop (please complete the following information):
* OS: macOS and Windows
* Browser Chrome (also Firefox)
* Version 90 (Firefox 87.0)

## Additional context
Reported in 3913300-zen

**Comment by mikejolley** [comment]
Thanks for the detailed report. This was fixed in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/4028 and is part of the Blocks 4.9 feature plugin.

Original issue was here: https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3788

Thanks

**Comment by wpniall** [comment]
Thanks @mikejolley. I have no idea how I missed #4028 when searching.
