### ISSUE TITLE
Changes to the Cart + Checkout block sidebar 

### ISSUE THREAD

**Issue by vivialice** [woocommerce/woocommerce-gutenberg-products-block#4093]
Hi folks, this request is to improve some of the UX in our Cart + Checkout block experience for buyers.
 
Sections that will be changed: 

- Shipping title
- Taxes
- Coupon input

**Shipping**
Group shipping information into its own section and remove title style. 

**Taxes**
Isolate taxes into its own section and position underneath the shipping options section. 

**Coupon input** 
Shift position of this Coupon input upwards to appear under the subtotals section.

These changes should be reflected in _both_ the Cart and Checkout views. I have attached visual comparisons below. 

<img width="710" alt="cart-comparison" src="https://user-images.githubusercontent.com/9888201/115737665-3d09e000-a384-11eb-9138-87f434c7d377.png">

<img width="710" alt="checkout-comparison" src="https://user-images.githubusercontent.com/9888201/115737666-3da27680-a384-11eb-9463-bba21a933ff5.png">

Thank you and ping me if you have any questions :) 

Figma design files: eaQcoMs7E8Ys0YgxfkOKxR-fi-727%3A1243

**Comment by mikejolley** [comment]
@vivialice I'm working through these changes. Related to this, on the cart block you'll notice the left area has no padding, but the totals area does:

![Screenshot 2021-05-06 at 12 57 00](https://user-images.githubusercontent.com/90977/117296900-7c006100-ae6d-11eb-861e-274f7a860062.png)

Should we make these consistent? It's more obvious now both sections have a heading (Total + Cart Totals).

**Comment by mikejolley** [comment]
Another issue/question regarding the order summary on checkout. Currently, this is toggled open on desktop but closed on mobile since it appears above the checkout form. Since the new design removes the toggle, how should we handle the handheld view here?

**Comment by mikejolley** [comment]
WIP branch for anyone picking this up https://github.com/woocommerce/woocommerce-gutenberg-products-block/compare/update/cart-sidebar-update-4093?expand=1

**Comment by opr** [comment]
👋🏼 @vivialice, quick question about the Taxes section. If the merchant has the `Display tax totals` option set to `As a single total` then I guess we won't be displaying the individual rates below the main Taxes heading, but if they _do_ set it to `Itemized` shouldn't we be displaying the actual amount next to it?

| As a single item | Itemized |
|---|---|
|![image](https://user-images.githubusercontent.com/5656702/117439298-98ae9e80-af2a-11eb-8f5e-ae3e6ee3a751.png) | ![image](https://user-images.githubusercontent.com/5656702/117439504-d27fa500-af2a-11eb-8818-1d27ed197123.png)|

I am also wondering in your example, is `CA Sales tax 7.5%` the _name_ of the tax rate, or is `CA Sales Tax` the name, and you propose that we display the rate `7.5%` directly after it?

**Comment by vivialice** [comment]
Hi @opr! Ah yes if there is the option to have itemized tax rates, then that second option is the way to go. I believe that `CA Sales tax` from the original concept is the name of the tax rate and I would want to include the percentage after it. I think in the case of the second example, we could also show the rate of VAT as a percentage next to it. ie. `VAT 20%`

**Comment by mikejolley** [comment]
I think this has come up before, @opr note that woo core does not do this so some merchants will have (if they want it that way) the percent entered as the tax rate name. By forcing the percent to display in code, we remove this control. Cc @nerrad

**Comment by nerrad** [comment]
Based on what you wrote here Mike, that suggests the following options:

Option 1 -  Don't display the percentage rate separately. If merchant's want to add it, then they will need to manually add it to the name of the tax rate.
Option 2 - Display the tax rate separately as a percentage (which merchants won't be able to control the display of)
Option 3 - Same as Option 2, but add a block control setting for deciding whether it displays or not.

I can't recall if the tax rate is something exposed on the API or not - if it isn't, then that means that Option 1 is the good short term option to go with here. If it is, then we could do Option 2 and then see whether there is need for adding a toggle for merchants with option 3?

Does that sound about right @mikejolley?

**Comment by opr** [comment]
@mikejolley Thanks for thinking of this! 

> I can't recall if the tax rate is something exposed on the API or not

@nerrad - I've added this in 1eedd32be12e9026564e63762f3cfdbbcc490aa7 - I actually like option 3 here.

**Comment by mikejolley** [comment]
Option 3 sounds good. Block level controls (or inner block level if we do that work!) would work well here. The itemised option would also be nice here but that's a global setting, unfortunately :)

**Comment by jacoswan** [comment]
Is it possible to make the Order Summary more flexible in terms of placement via CSS? 

Currently, on mobile, it appears at the top of the checkout block by default. Using some CSS it's possible to change its position, but only to the very bottom, where it then appears below the Checkout button. 

In [this forum post](https://wordpress.org/support/topic/swapping-containers-positions-billing-and-shipping/), a user needed the Order Summary be placed at the bottom, but still have the Checkout / Buy button be at the very bottom.

**Comment by mikejolley** [comment]
@nerrad was this reopened for a reason?

@jacoswan Not easy with CSS because the express methods are in a separate column. This might be more feasible with the new Checkout i2. Log a separate enhancement request?

**Comment by nerrad** [comment]
> @nerrad was this reopened for a reason?

Hmm nope, It looks like it may be have happened because of some Zenhub pipeline move maybe 🤔 I'll re-close.
