### ISSUE TITLE
Checkout & Cart styles broken

### ISSUE THREAD

**Issue by piotrmaroszek** [woocommerce/woocommerce-gutenberg-products-block#4095]
Hello,

when I'm putting my Woo Blocks Cart and Checkout on my page there's like some styles missing and everything is broken in this view. How I can fix this?

**Comment by ralucaStan** [comment]
Hi there @piotrmaroszek ,
sorry to hear you are having issues with the styles. 
Could you provide us with more details in order to better understand what issue you are having?
A screenshot, the version of blocks you are using, what styles are missing?

**Comment by piotrmaroszek** [comment]
Thanks for your contact. I fix this. Wooblock checkout was noncompatible with one of my plugins.

By the way, do you know when WooCommerce Blocks Checkout and Cart will be full compatible like the old checkout? :) Its awesome!

Pozdrawiam / Best Regards
Piotr Maroszek

tel: 602 158 046

**Comment by senadir** [comment]
Hey @piotrmaroszek, We don’t have an exact timeline for this. We're integrating some plugins ourselves and encouraging developers to integrate themselves.

Since you fixed the issue, I'm going to close this thread, if you have further questions feel free to post them.

Have a good day!
