### ISSUE TITLE
Stock status filter feature 

### ISSUE THREAD

**Issue by grogou** [woocommerce/woocommerce-gutenberg-products-block#4096]
## Is your feature request related to a problem? Please describe.
No problems!

## Describe the solution you'd like
Created stock status filter in our fork, we just need to understand is it possible to contribute our changes to this repo and what we need to do for that. For example filter, I examine attribute filter.

## Additional context
The editor side is like another filter. For now, it has an attribute filter icon :)
And it gets disabled if used once.

![image](https://user-images.githubusercontent.com/10712881/115829144-a985ed00-a41f-11eb-8884-18bf58d34ba1.png)

The editor side rendered block.
![image](https://user-images.githubusercontent.com/10712881/115829575-34ff7e00-a420-11eb-9131-1d7eb248667b.png)

Block inspector controls.
![image](https://user-images.githubusercontent.com/10712881/115829645-49437b00-a420-11eb-9ab3-bf259f836820.png)

And finally the front side combination with other filters. ( Added to active filter too. )
![image](https://user-images.githubusercontent.com/10712881/115829925-a3444080-a420-11eb-8bd5-75f40422b711.png)

**Comment by senadir** [comment]
Hey @grogou!
I would be happy to review it and get it merged, can you open a PR?

**Comment by grogou** [comment]
Hey @senadir!
PR opened #4145
