### ISSUE TITLE
Prepare WooCommerce for the Navigation Editor

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#4102]
The new navigation screen and navigation component are coming with WP 5.8 and we want to make sure WooCommerce works fine with them. This is an epic to make an audit and add any issues we find.

**Comment by nerrad** [comment]
@Aljullu, I'm assuming this can be repurposed to address the navigation _screen_ when it comes in a future release of WP (so 6.0). I'm assuming navigation block support is already handled? If not, please prioritize as needed.

**Comment by Aljullu** [comment]
There are still some improvements we want to make to the Navigation block independently of the Navigation screen: making it easy to add WooCommerce Endpoints links, allowing to add the Product Search and Mini Cart blocks, etc.

For now, we prioritized other projects which had a bigger impact; that's specially true considering that the Navigation screen hadn't been enabled in classic themes. In any case, we can discuss the priority of these issues in our next meeting if that sounds good, just to make sure we are on the same page.

**Comment by Aljullu** [comment]
Given that https://github.com/woocommerce/woocommerce/issues/42670 is the only issue open in this epic, I think we can close this epic issue and leave the individual issue open.
