### ISSUE TITLE
`woocommerce_shared_settings` deprecation notice

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#4137]
[The shared settings notice was deprecated](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/4092), but it still used by WC Admin.

We need to decide if we can:

- Leave notice in place and add dev note somewhere
- Soft-deprecate the filter (no notice) and inform teams before hard deprecating the filter
- Deprecate with a notice only in feature plugin context
- Leave filter in place, supported, but just don't use it in blocks internally.

**Comment by nerrad** [comment]
I think we can start with soft-deprecate and no notice. We can surface this for more discussion/awareness (I can write)?
