### ISSUE TITLE
Add item type to cartTotalItems

### ISSUE THREAD

**Issue by paymentplugins** [woocommerce/woocommerce-gutenberg-products-block#4148]
## Is your feature request related to a problem? Please describe.
It is common in European countries to display item price including tax. It would be helpful if the `cartTotalItems` that is part of the `usePaymentMethodInterface` included the item type. If the item type is known, it will assist with payment method logic.

## Describe the solution you'd like
In the function `prepareTotalItems`, add a `type` property that describes what the line item is. The function already has access to the line item type via the `factory` function so that could be used to add the type to the line item. 

Example:
```javascript
const factory = ( label, property ) => {
    const value = parseInt( totals[ property ], 10 );
    const tax = parseInt( totals[ property + '_tax' ], 10 );	
    return {
        label,
        value,
        valueWithTax: value + tax,
        type: property
    };
};
```

## Describe alternatives you've considered
- Using the label of the item to determine its type is unreliable because of translations. 
- The tax item could be determined by adding the difference of `item.tax - item.valueWithTax` and comparing that value to all line items. But that doesn't tell you what the other line items are.

**Comment by nerrad** [comment]
Seems like a fair ask, I'll queue this up as something we'll work on improving but no ETA just yet.

**Comment by paymentplugins** [comment]
@nerrad Thank you for your time and for considering this request.
