### ISSUE TITLE
When you click the 'Use same address for billing', the email input field gets emptied

### ISSUE THREAD

**Issue by parvnoor** [woocommerce/woocommerce-gutenberg-products-block#4155]
When you click the 'Use same address for billing', the email input field gets emptied.

**Comment by nerrad** [comment]
Thanks for the report @parvnoor. I'm able to reproduce this - here's some clearer steps.

1. Load the checkout block on the frontend as a shopper.
2. Fill out email address (and optionally other address fields)
3. Uncheck the "Use same address for billing option"
4. Notice the email address field is cleared.

![CleanShot 2021-04-30 at 05 59 43](https://user-images.githubusercontent.com/1429108/116680377-98863000-a979-11eb-8c83-b2895a69be69.gif)

This only happens for me when _unchecking_ the option, checking doesn't seem to clear.

**Comment by parvnoor** [comment]
Thanks @nerrad for the clearer explanation! I will use this format in future issue posts :)

**Comment by senadir** [comment]
This also happens for the phone field.
