### ISSUE TITLE
Can't see Stripe payment methods on Checkout Block

### ISSUE THREAD

**Issue by suze-it** [woocommerce/woocommerce-gutenberg-products-block#4156]
## Describe the bug
The Stripe credit card option is missing from the Checkout Block's payment options.  Only PayPal is visible method of payment.  when I use the WooCommerce Checkout block, the Stripe option is visible.  So I know my Stripe settings are correct.

Please help!!

### WordPress:
* Core version: [5.7.1]
* WooCommerce version: [5.2.2]
* WooCommerce Blocks version: [5.0.0]
* Site language: English
* Any other plugins installed:

### Desktop (please complete the following information):
* OS: [Windows 10 Home]
* Browser [chrome]
* Version [89.0.4389.90]

**Comment by senadir** [comment]
Hi, I'm not able to reproduce this issue

<img width="750" alt="image" src="https://user-images.githubusercontent.com/6165348/116810628-bf409400-ab3c-11eb-9bcf-e07781d5cfae.png">


What do you mean by "when I use the WooCommerce Checkout block, the Stripe option is visible. So I know my Stripe settings are correct."

Can you provide a screen shot of when this is not working?

**Comment by suze-it** [comment]
This is a snapshot without using the new Blocks:
![OldCheckoutPageWithCreditCards](https://user-images.githubusercontent.com/83427163/116837590-ee2c2980-ab7f-11eb-9cf4-6f2f5e36a604.jpg)
See that the other credit card options are available.
Here is the page with the Blocks:
![NewCheckoutPage2](https://user-images.githubusercontent.com/83427163/116837660-33505b80-ab80-11eb-98cd-20faa6a894cc.jpg)
Only the PayPal option is available!  Also, for some reason $0.00 for Local Pickup is crossed out.  I'm at a loss for that too...

Any help would be much appreciated as I'm at a loss as to why I can't get Stripe payments visible.  Other than PayPal, that's all the payment options I have.  Thank you!

**Comment by senadir** [comment]
Hey again, seeing that no one can reproduce this issue, can you disable the plugins that add `Gift Card` and `BLoyal` payment methods?

Can you also check your console to see if there are any errors logged there? [You can open the console by following this guide](https://balsamiq.com/support/faqs/browserconsole/#google-chrome).

**Comment by suze-it** [comment]
I noticed these errors in the console... anything significant?  Those payment methods were disabled already in the snapshot I gave with the Blocks.  I'll see if re-enabling makes a difference...

![errors](https://user-images.githubusercontent.com/83427163/116902595-2bc89b00-abf0-11eb-9549-a3f1f641ba53.jpg)

**Comment by suze-it** [comment]
Re-enabling the other payment options didn't make a difference ... I'll look for more anomalies...

**Comment by suze-it** [comment]
Hi.  I reverted to the version without the new Checkout Blocks and the Stripe credit cards worked.  Here's our temporary in-progress website:  ckb.itb.mybluehost.me.  This has the ugly old checkout element and not the nice new one.  I need to check something else out so if you'd like to take a look at it with the old checkout, it's there.  I will put it back to the new Checkout Block probably later tomorrow, or whenever you think you'd need it so you can compare.  I guess it'd be better to have the defective one, but I thought it would be useful to prove (to myself too) that the problem isn't a Stripe setting.  Thank you.  I am also open to a direct chat too, if that will be helpful, or sending more direct correspondence.  I just need to know how to do that.  ;)

**Comment by senadir** [comment]
Hey, this is not probably not a Stripe settings issue but a conflict issue, can you please:
- Enable Checkout block on https://ckb.itb.mybluehost.me/checkout/
- Disable all other payment methods and only leave Stripe activated and enabled.

and I will look it up myself.

**Comment by mikejolley** [comment]
Can you post your full system status report; it's important we see what version/plugin for Stripe you are using since only this one is supported for Blocks  https://wordpress.org/plugins/woocommerce-gateway-stripe/

**Comment by suze-it** [comment]
@mikejolley I'm not sure how to get the full system status report that you'd like.  But I can tell you that Stripe for WooCommerce is the plugin that's installed... version 3.2.15.  That's not the same as the gateway stripe you mentioned.  I'll install that one and see how it goes.  Thanks!  Stay tuned.  

@senadir I will go back to my website version with your Checkout Blocks to try the gateway stripe version.

**Comment by suze-it** [comment]
@mikejolley I installed the woocommerce gateway stripe and now the Stripe payment method is visible.  That plugin had a lot of bad reviews.  Also, is there a nice way to change the size of the payment method icons since the default seems to make them huge!

@senadir I removed the PayPal payment method and only left the stripe plugin method that Mike suggested.  There were lots of bad reviews on that plugin, so I'm hoping that the website doesn't crash in my using it.

**Comment by mikejolley** [comment]
@suze-it If the icons are not styled by the theme, it can be done with some CSS I believe.

Glad we identified the issue. Perhaps the other Stripe plugin will get Blocks support in the future, but it's not affiliated with us so cannot say.

Thanks, I'm marking this closed.
