### ISSUE TITLE
Confirmation Emails are not sending

### ISSUE THREAD

**Issue by parvnoor** [woocommerce/woocommerce-gutenberg-products-block#4168]
## Describe the bug
When an order is made, no processing / new order or any other confirmation emails are sending. I have tried to deactive all plugins and use just woocommerce and the default woocommerce shortcode checkout, and emails send. I have SMTP set up, and have checked all required solutions such as double checking settings, removing any custom code, etc.

## To reproduce
To reproduce the bug, 
1) Fresh installation of Wordpress.
1) Set up a Woocommerce store with woocommerce blocks. 
2) Ensure all email settings are correct. 
3) Create one test product. 
4) Order the product. 
5) No confirmation email should come through.

TO confirm this is with Woocommerce blocks, now:
1) Make another cart page with the old woocommerce cart shortcode [woocommerce_cart]
2) Make another checkout page with the old woocommerce checkout shortcode [woocommerce_checkout]
3) Ensure Woocommerce advanced settings to locate cart and checkout are pointed to the new pages.
4) Order the test product again.
5) Email confirmation should arrive immediately.

## Expected behavior
After an order is made, there are a number of emails that should be sent out to both admin and customer at different stages of the order process.

### WordPress (please complete the following information):
Divi  4.9.4
Wordpress 5.7.1
Woocoomerce 5.2.2
Woocommerce blocks 5.0.0

**Comment by mikejolley** [comment]
Can you confirm the order status as shown in admin after the order is placed? And post the full status report from WooCommerce > Status for us here.

Testing locally I get both emails through (merchant and user), so I'm not certain what it could be in your case.

**Comment by parvnoor** [comment]
Hey,

The order status is shown in the admin after an order is placed.

Here is the status report:
`
### WordPress Environment ###

WordPress address (URL): http://www.londontypewriters.co.uk
Site address (URL): http://www.londontypewriters.co.uk
WC Version: 5.2.2
REST API Version: ✔ 5.2.2
WC Blocks Version: ✔ 5.0.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.1.5
Log Directory Writable: ✔
WP Version: 5.7.1
WP Multisite: –
WP Memory Limit: 102 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.18
PHP Post Max Size: 256 MB
PHP Time Limit: 300
PHP Max Input Vars: 5000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.28-MariaDB-1:10.3.28+maria~focal
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.2.2
WC Database Prefix: 0_
Total Database Size: 213.90MB
Database Data Size: 164.95MB
Database Index Size: 48.95MB
0_woocommerce_sessions: Data: 23.77MB + Index: 0.75MB + Engine MyISAM
0_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
0_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
0_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
0_woocommerce_order_items: Data: 0.31MB + Index: 0.10MB + Engine MyISAM
0_woocommerce_order_itemmeta: Data: 1.27MB + Index: 0.88MB + Engine MyISAM
0_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
0_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
0_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
0_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
0_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
0_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
0_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
0_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_actionscheduler_actions: Data: 4.02MB + Index: 2.08MB + Engine InnoDB
0_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_actionscheduler_logs: Data: 2.02MB + Index: 1.92MB + Engine InnoDB
0_cartflows_ca_cart_abandonment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_cartflows_ca_email_history: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0_cartflows_ca_email_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_cartflows_ca_email_templates_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_commentmeta: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
0_comments: Data: 1.08MB + Index: 0.45MB + Engine MyISAM
0_et_bloom_stats: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
0_et_social_stats: Data: 0.05MB + Index: 0.01MB + Engine MyISAM
0_ewwwio_images: Data: 24.55MB + Index: 23.31MB + Engine InnoDB
0_ewwwio_queue: Data: 0.28MB + Index: 0.16MB + Engine InnoDB
0_fbv: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_fbv_attachment_folder: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_frm_fields: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0_frm_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_frm_items: Data: 0.20MB + Index: 0.08MB + Engine InnoDB
0_frm_item_metas: Data: 0.42MB + Index: 0.17MB + Engine InnoDB
0_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
0_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_options: Data: 16.38MB + Index: 4.59MB + Engine MyISAM
0_postmeta: Data: 49.03MB + Index: 5.26MB + Engine MyISAM
0_posts: Data: 11.73MB + Index: 1.46MB + Engine MyISAM
0_racart_cartemail: Data: 0.25MB + Index: 0.00MB + Engine InnoDB
0_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0_snippets: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
0_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
0_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
0_term_relationships: Data: 0.07MB + Index: 0.16MB + Engine MyISAM
0_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
0_usermeta: Data: 0.06MB + Index: 0.02MB + Engine MyISAM
0_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
0_wc_admin_notes: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
0_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_wc_customer_lookup: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
0_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0_wc_order_product_lookup: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
0_wc_order_stats: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
0_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0_wc_product_meta_lookup: Data: 0.11MB + Index: 0.20MB + Engine InnoDB
0_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_wfBlockedIPLog: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
0_wfBlocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
0_wfConfig: Data: 0.08MB + Index: 0.01MB + Engine MyISAM
0_wfCrawlers: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
0_wfFileChanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_wfFileMods: Data: 6.65MB + Index: 1.15MB + Engine MyISAM
0_wfHits: Data: 2.80MB + Index: 0.75MB + Engine MyISAM
0_wfHoover: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
0_wfIssues: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
0_wfKnownFileList: Data: 4.03MB + Index: 0.35MB + Engine MyISAM
0_wfLiveTrafficHuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_wfLocs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
0_wfLogins: Data: 0.24MB + Index: 0.06MB + Engine MyISAM
0_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_wfNotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_wfPendingIssues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
0_wfReverseCache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
0_wfSNIPCache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
0_wfStatus: Data: 0.07MB + Index: 0.04MB + Engine MyISAM
0_wfTrafficRates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_wpml_mails: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
0_yith_wcwl: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
0_yith_wcwl_lists: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
0_yoast_indexable: Data: 13.52MB + Index: 3.67MB + Engine InnoDB
0_yoast_indexable_hierarchy: Data: 0.39MB + Index: 0.45MB + Engine InnoDB
0_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0_yoast_seo_links: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
0_yoast_seo_meta: Data: 0.19MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 8719
custom_css: 3
customize_changeset: 9
et_body_layout: 2
et_footer_layout: 2
et_header_layout: 1
et_pb_layout: 3
et_template: 6
et_theme_builder: 3
flamingo_contact: 85
flamingo_inbound: 162
frm_form_actions: 3
frm_styles: 1
nav_menu_item: 10
oembed_cache: 27
page: 28
post: 16
product: 870
revision: 797
shop_coupon: 1
shop_order: 1516
shop_order_refund: 25
wc_whsm: 1
wp_block: 1
wpcf7_contact_form: 1
wpforms: 2
wphb_minify_group: 32

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (32) ###

FiboSearch - AJAX Search for WooCommerce: by Damian Góra – 1.10.0
All-in-One WP Migration: by ServMask – 7.42
Bloom: by Elegant Themes – 1.3.12
Code Snippets: by Code Snippets Pro – 2.14.1
Contact Form 7: by Takayuki Miyoshi – 5.4.1
Custom Functionality For LondonTypeWriters: by WeDoAllTech – 1.0
Elegant Themes Updater: by Elegant Themes – 1.0
EWWW Image Optimizer: by Exactly WWW – 6.1.3
FileBird Lite: by Ninja Team – 4.7.2
Flamingo: by Takayuki Miyoshi – 2.2.1
Site Kit by Google: by Google – 1.31.0
Hide Shipping Method For WooCommerce Pro: by theDotstore – 1.0.8
Mailchimp for WooCommerce: by Mailchimp – 2.5.1
Monarch Plugin: by Elegant Themes – 1.4.14
Facebook for WordPress: by Facebook – 3.0.5
Really Simple CAPTCHA: by Takayuki Miyoshi – 2.1
Really Simple SSL: by Really Simple Plugins – 4.0.14
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.5
WooCommerce Blocks: by Automattic – 5.0.0
Advanced Order Export For WooCommerce: by AlgolPlus – 3.1.8
WOOCS - WooCommerce Currency Switcher: by realmag777 – 2.3.2
WooCommerce Stripe Gateway: by WooCommerce – 5.1.0
WooCommerce Product Image Flipper: by jameskoster – 0.4.2
Woocommerce Side Cart Premium: by XootiX – 3.1
WooCommerce: by Automattic – 5.2.2
Wordfence Security: by Wordfence – 7.5.2
Yoast SEO: by Team Yoast – 16.2
WP Mail Logging: by MailPoet – 1.9.7
WP Mail SMTP: by WPForms – 2.7.0
WPS Hide Login: by WPServeur
NicolasKulka
wpformation – 1.8.5

YITH Custom Thank You Page for WooCommerce: by YITH – 1.3.8
YITH Infinite Scrolling: by YITH – 1.5.1

### Inactive Plugins (0) ###


### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #90 - /
Cart: #72 - /cart/
Checkout: #73 - /checkout/
My account: #74 - /my-account/
Terms and conditions: #118 - /terms-and-conditions/

### Theme ###

Name: Divi
Version: 4.9.4
Author URL: http://www.elegantthemes.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 8,456
Oldest: 2021-04-28 00:19:50 +0000
Newest: 2021-05-06 12:02:29 +0000

Pending: 3
Oldest: 2021-05-06 12:17:29 +0000
Newest: 2021-05-06 17:26:09 +0000


### Status report information ###

Generated at: 2021-05-06 12:06:43 +00:00
`

I'm wondering what else could be the case.

Is it okay to share a vimeo video with you of the issue? In brief again, when everything is disabled except from Woocommerce / SMTP (divi theme), the emails come through. When Woocommerce blocks is enabled (everything else still the same), emails don't come through.

**Comment by parvnoor** [comment]
Hi guys,

To make this process much more simpler I have:

1)  Installed a fresh installation of Wordpress on Siteground.
2) Installed Woocommerce Blocks
3) Activated the storefront theme.
4) Added a product with no cost.
5) Ensured the admin email address has the same domain as the website being used.
6) Ordered a product.
7) No confirmation emails.

8) Deactivated WooCommerce Blocks
9) Removed Woocommerce Blocks from checkout/cart and replaced with Woocommerce shortcodes.
10) Ordered same product again.
11) Confirmation Emails arrive.

12) Changed back to Woocommerce Blocks.
13) Changed Checkout/Cart from shortcodes to Blocks.
14) Ordered products.
15) No confirmation Emails.

Please see the diagnostics below:

`
### WordPress Environment ###

WordPress address (URL): https://beginnertodev.com
Site address (URL): https://beginnertodev.com
WC Version: 5.2.2
REST API Version: ✔ 5.2.2
WC Blocks Version: ✔ 4.7.2
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.1.5
Log Directory Writable: ✔
WP Version: 5.7.1
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.27
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.66.0
OpenSSL/1.1.1k-fips

SUHOSIN Installed: –
MySQL Version: 5.7.32-35-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.2.2
WC Database Prefix: aai_
Total Database Size: 3.77MB
Database Data Size: 2.36MB
Database Index Size: 1.41MB
aai_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
aai_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
aai_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
aai_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
aai_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
aai_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
aai_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
aai_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
aai_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
aai_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
aai_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
aai_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
aai_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
aai_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
aai_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
aai_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
aai_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
aai_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
aai_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
aai_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
aai_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
aai_options: Data: 1.48MB + Index: 0.06MB + Engine InnoDB
aai_postmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
aai_posts: Data: 0.03MB + Index: 0.06MB + Engine InnoDB
aai_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
aai_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
aai_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
aai_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
aai_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
aai_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
aai_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
aai_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
aai_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
aai_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
aai_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
aai_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
aai_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
aai_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
aai_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
aai_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
aai_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
aai_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
aai_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 6
post: 2
product: 1
revision: 7
shop_order: 7

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

Really Simple SSL: by Really Simple Plugins – 4.0.14
SG Optimizer: by SiteGround – 5.7.20
WooCommerce: by Automattic – 5.2.2

### Inactive Plugins (1) ###

WooCommerce Blocks: by Automattic – 5.0.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.5.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 18
Oldest: 2021-05-06 21:16:12 +0000
Newest: 2021-05-06 21:34:20 +0000


### Status report information ###

Generated at: 2021-05-06 21:34:33 +00:00
`

**Comment by nerrad** [comment]
I have a little more detail to add to this ticket.  It's _incorrect_ that **no notifications** are sent (at least in my testing), however I AM able to confirm this for at least the "New Order" notification under the following conditions:

1. Complete a purchase that totals $0.00 using the Woo Blocks checkout flow (by the way, it's just doing purchases using the blocks flow that reproduces this, it has nothing to do with the actual blocks extension being active - in my testing).
2. Notice the shopper will receive an email notification of their order, but the merchant/store "new order" notification will not get sent out (there may be others like Out of stock email notification that don't get sent either but I didn't test with any products would trigger that so can't confirm).

**Comment by senadir** [comment]
I was able to reproduce this under specific circumstances.

Locally, when checking out a $0.00, I get no notification at all (no store owner notification or customer notification).

When checking out a subscription product with a trial (a zero checkout with payment details still being captured), I get both emails.

Meaning this only happens when no payment is captured.

**Comment by nerrad** [comment]
I wonder if the shopper being logged in our out also makes a difference. In my testing I was logged in.

**Comment by senadir** [comment]
I also tested while logging in, I will try again while logged out.

**Comment by mikejolley** [comment]
This is due to status transitions. Core tracks the following events for new order emails:

```
add_action( 'woocommerce_order_status_pending_to_processing_notification', array( $this, 'trigger' ), 10, 2 );
add_action( 'woocommerce_order_status_pending_to_completed_notification', array( $this, 'trigger' ), 10, 2 );
add_action( 'woocommerce_order_status_pending_to_on-hold_notification', array( $this, 'trigger' ), 10, 2 );
add_action( 'woocommerce_order_status_failed_to_processing_notification', array( $this, 'trigger' ), 10, 2 );
add_action( 'woocommerce_order_status_failed_to_completed_notification', array( $this, 'trigger' ), 10, 2 );
add_action( 'woocommerce_order_status_failed_to_on-hold_notification', array( $this, 'trigger' ), 10, 2 );
add_action( 'woocommerce_order_status_cancelled_to_processing_notification', array( $this, 'trigger' ), 10, 2 );
add_action( 'woocommerce_order_status_cancelled_to_completed_notification', array( $this, 'trigger' ), 10, 2 );
add_action( 'woocommerce_order_status_cancelled_to_on-hold_notification', array( $this, 'trigger' ), 10, 2 );
```

Orders that require no payment (in blocks) bypass pending status, so the transition would be draft_to_processing. We could force the status pending but this would be an extra save event.
