### ISSUE TITLE
[GlobalStep][Mac] "Browse All" window starts jittering when user scrolls down and tries to add "Top rated products" after adding "All Products" block on Edit Page

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-gutenberg-products-block#4173]
## Bug Description:
 "Browse All" window starts jittering when user scrolls down and tries to add "Top rated products" after adding "All Products" block on Edit Page

## Test Instructions:
Blocks 4.9.0- Remove deprecated shortcode save handling from SSR Blocks (#4010):
https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/testing/releases/490.md#remove-deprecated-shortcode-save-handling-from-ssr-blocks-4010

## Environment:
Woocommerce Version : WooCommerce 5.2.2 and 5.3 RC 1
WordPress version: (v5.7)

**PC**:
Mac 10.14.6
Safari: v13.1.1

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins 
1. Complete the onboarding setup wizard setup 
1. Go to "Pages->Add new"  
1. Add "All Products" Block by clicking on "+" icon
1. Enter and Search "top" in "Browse All" window after clicking on "+" icon below "All Products" block
1. Scroll down on editor page
1. Observe that  "Browse All" window starts jittering when user scrolls down and tries to add "Top rated products" after adding "All Products" block on Edit Page

## Actual Result:
 "Browse All" window starts jittering when user scrolls down and tries to add "Top rated products" after adding "All Products" block on Edit Page

## Expected Result:
 "Browse All" window should smoothly scroll down and add "Top rated products" after adding "All Products" block on Edit Page

## ScreenShot:

https://user-images.githubusercontent.com/41110392/117165624-4747c780-ade3-11eb-976b-bbee0cab99c2.mov

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by nerrad** [comment]
On the surface I don't think this is an issue WooCommerce Blocks but something specific to Gutenberg. I'm not able to reproduce with the Google Chrome browser and with Safari I'm not getting the same as what's reported here but am seeing some slight jitter in other parts of the ui.

I think it's related to https://github.com/WordPress/gutenberg/issues/30803
