### ISSUE TITLE
GreenInvoice Payment Gateway Checkout Block Integration

### ISSUE THREAD

**Issue by DorZuberi** [woocommerce/woocommerce-gutenberg-products-block#4174]
Hello,
I'm the developer of a a payment gateway for a client of mine, and he wishes me to add support for the Checkout Block.

I've went over the [following tutorial](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/extensibility/payment-method-integration.md) and it won't work.

The error is:
```
wc-blocks-registry.js?ver=a1397959cd5948b3b644f95cf2d9572a:1 Uncaught TypeError: The content property for the payment method must be a React element or null.
    at p (wc-blocks-registry.js?ver=a1397959cd5948b3b644f95cf2d9572a:1)
    at Function.assertValidConfig (wc-blocks-registry.js?ver=a1397959cd5948b3b644f95cf2d9572a:1)
    at new e (wc-blocks-registry.js?ver=a1397959cd5948b3b644f95cf2d9572a:1)
    at cc.min.js?ver=5.7.1:19
    at v (wc-blocks-registry.js?ver=a1397959cd5948b3b644f95cf2d9572a:1)
    at cc.min.js?ver=5.7.1:19
```

The code is:
```
/**
 * External dependencies
 */
const { registerPaymentMethod } = wc.wcBlocksRegistry;

/**
 * Cheque payment method config object.
 */
const giCreditCard = {
	name: 'greeninvoice_cc',
	label: 'Test1',
	content: 'Test2',
	edit: 'Test2',
	icons: null,
	canMakePayment: () => true,
	ariaLabel: 'Test',
};

registerPaymentMethod( ( Config ) => new Config( giCreditCard ) );
```

The plugin allows people to pay via Credit Card in an iFrame.
Would love to get your help please.

**Comment by mikejolley** [comment]
Hi there,

Looking over the tutorial, it does correctly specify that the content property be a React node:

> This should be a React node that will output in the express payment method area when the block is rendered in the frontend. It will be cloned in the rendering process. When cloned, this React node will receive props passed in from the checkout payment method interface that will allow your component to interact with checkout data (more on these props later).

The example you posted is using a `string`.

That tutorial has a full example a bit further down:

```
const options = {
	name: 'my_payment_method',
	content: <div>A React node</div>,
	edit: <div>A React node</div>,
	canMakePayment: () => true,
	paymentMethodId: 'new_payment_method',
	supports: {
		features: [],
	},
};
```

Notice the content property is passed a react node (div element) rather than a string. I think this is your issue :)

Hope that helps. I am marking this question closed.

**Comment by DorZuberi** [comment]
Hi @mikejolley 
Thanks for responding so quickly, i saw that it needs a React node, however i don't have any experience with React and when i copied the code like in the Cheque example it said the the `<` should be there, I understand it needs to go some kind of compilation, yet I don't know how, the tutorial is very basic.

**Comment by mikejolley** [comment]
@DorZuberi The tutorial assumes knowledge of React and doesn't cover the build process for using JSX. There is a top level API in react for creating elements (https://reactjs.org/docs/react-without-jsx.html).

@nerrad Any other resources to share here? Should we link to some from the tutorial?

**Comment by DorZuberi** [comment]
I'm mainly a backend developer and thus i don't deal with React, but I wish to give my client a solution, I think most developers would appreciate if you could create sample repository with bootstrap code.

**Comment by nerrad** [comment]
Hi there @DorZuberi - it's great that you're working on addressing this for your client! As Mike mentioned the existing documentation here assumes some pre-requisite understanding for working with modern JavaScript, and React. One of the great things about React and JavaScript is there are a lot of tutorials around the internet that help teach concepts with working with them.  There's also [this doc](https://developer.woocommerce.com/modern-javascript-and-woocommerce-101/) on developer.woocommerce.com that among other things gives a good primer around working with some of the newer JavaScript and React interfaces being built in Woo.

I like the idea of having a sample repository with bootstrap code - I've created #4175.  Fair warning it's likely not something we'll get to right away.

**Comment by senadir** [comment]
I believe the API should be able to accept strings as well, I don't think the react requirement is needed here, glancing over BACs, cheque, and COD, they all use strings, I anticipate several plugins to be a simple redirect type of plugins where most of the work is done on the backend and the frontend simply redirects to the payment processer website.

This would skip the need for a build process and any knowledge in React unless needed.

For the example above, someone has to figure out how to run a build process, generate built JS, what a react node/element/component is, and possibly any other bugs if they try to include React themselves.

**Comment by nerrad** [comment]
A build process isn't needed. The example above can be done with something like this:

```js
/**
 * External dependencies
 */
const { registerPaymentMethod } = wc.wcBlocksRegistry;
const { creatElement } = wp.element;

/**
 * Cheque payment method config object.
 */
const giCreditCard = {
	name: 'greeninvoice_cc',
	label: createElement( 'div', {}, 'Test1' ),
	content: createElement( 'div', {}, 'Test1' ),
	edit: createElement( 'div', {}, 'Test2' ),
	icons: null,
	canMakePayment: () => true,
	ariaLabel: 'Test',
};

registerPaymentMethod( ( Config ) => new Config( giCreditCard ) );
```

I'm not closed to the idea of exploring whether we could accept strings in the API but I'd like to see how it complicates the internal logic where the property is used before committing to it. 

Even though there are valid examples where only a string is needed, if the API was to accept a string here, there would have to be clear documentation/instructions to implementors that this is _only_ going to be parsed as a string (i.e. using html as a string will not work as they expect). 

I also appreciate the sentiment of removing one more layer of thing folks need to learn (React) here. But given the direction WordPress and WooCommerce is going, I don't think that should be a primary criteria for the interface.

**Comment by senadir** [comment]
I'd argue that `createElement( 'div', {}, 'Test1' ),` is not very intuitive as `Test1` (given that div is not needed here).

> I'm not closed to the idea of exploring whether we could accept strings in the API but I'd like to see how it complicates the internal logic where the property is used before committing to it.

That would be part of the exploration, I still think it would be worthwhile.

> Even though there are valid examples where only a string is needed, if the API was to accept a string here, there would have to be clear documentation/instructions to implementors that this is only going to be parsed as a string (i.e. using html as a string will not work as they expect).

That's a fair observation and something we can do with code examples.

> I also appreciate the sentiment of removing one more layer of thing folks need to learn (React) here. But given the direction WordPress and WooCommerce is going, I don't think that should be a primary criteria for the interface.

I do understand this approach and support having the WordPress and WooCommerce community learn React, but integrating a payment gateway should be an easy win to help adoption, what could be done in less than an hour, would require more time understanding and debugging what's happening.

There're going to be cases where the majority of use cases are going to be React based if not 100% react based (slots for example, or new inner blocks) and for those cases, we shouldn't try to complicate things in order to cater to an edge case (using strings) but there are some cases where React is not needed at all for the majority of cases, and for those cases we can simplify it a bit.

> I'm not closed to the idea of exploring whether we could accept strings in the API

I will glance later at what it might take to get this and open an issue for it, and leave it for you to triage.
