### ISSUE TITLE
Unable to re-select featured category block

### ISSUE THREAD

**Issue by strarsis** [woocommerce/woocommerce-gutenberg-products-block#4177]
## Describe the bug
It is not possible to reset the selected category of a featured category block, at least not in an obvious manner.
It is possible to select a new preview image though, but not the actually linked category - without removing the whole block and re-inserting it or manually editing the source.

## To reproduce
1. Insert a featured category block.
2. Select a category to be featured.
Note that it now isn't possible to re-select the category to be featured.

## Expected behavior
Some button or mechanism (that is similar to what core and other blocks do) for re-selecting the category.

**Comment by Aljullu** [comment]
Thanks for reporting this issue @strarsis, I can confirm that the Featured Product block has an edit button (pencil icon) that allows changing the selected product while the Featured Category doesn't have anything similar.

_Featured Product:_
![imatge](https://user-images.githubusercontent.com/3616980/117662426-d49e6980-b19f-11eb-9eb1-54f138060470.png)

_Featured Category:_
![imatge](https://user-images.githubusercontent.com/3616980/117662384-c94b3e00-b19f-11eb-91d5-7707da2c7d75.png)

I investigated whether that was a regression or not, but I could reproduce the issue with WC Blocks 4.0 and I couldn't find anything in the code that made me think that button existed in the past, so it doesn't seem to be a regression.

**Comment by thisissandip** [comment]
PR added: https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/4559
