### ISSUE TITLE
WooCommerce Stripe Payment Gateway makes payment icons huge in laptop view; fine in mobile and tablet view

### ISSUE THREAD

**Issue by suze-it** [woocommerce/woocommerce-gutenberg-products-block#4178]
WooCommerce Checkout Blocks and Stripe Payment Gateway for some reason displays the payment credit card options "screen-wide", so huge!  The mobile and tablet view is set to 16px, so they are fine.

## To reproduce

1. Go to 'ckb.itb.mybluehost.me/shop'
2. Click on any products with "Select Options"
3. Add to Cart
4. View Cart
5. "Proceed to Checkout"
6. Click on "Credit Card (Stripe)"   and you will see the credit card icons

## Expected behavior

The icons are huge, so I added the following css code... but this inadvertently affects the size of the website logo too so I can't make the credit card icons smaller without the logo going smaller.  The theme writer said they don't do any resizing...

When I had another Stripe plugin the credit card icons weren't huge on the desktop version.

Code:  
_**legacy.woocommerce img, body.ckc-legacy.woocommerce-page img {
    height: 64;
}**_

## Screenshots
this is what it looked like prior to my adding the above 'hack'
![CreditCardIcons](https://user-images.githubusercontent.com/83427163/117358335-e368e180-ae6a-11eb-8802-401d82423e3a.jpg)

### WordPress: 5.7.1
* WooCommerce version: 5.2.2
* WooCommerce Blocks version: 5.0.0
* WooCommerce Stripe Payment Gateway 5.1.0
* Site language: English
* Any other plugins installed: Templatation Framework 3.3

### Desktop (please complete the following information):
* OS: Windows 10 Home
* Browser Chrome
* Version 90.0.4430.93

**Comment by ralucaStan** [comment]
Hi @suze-it,
sorry to hear you are having issues with your icons.

it looks like the code that is changing the image sizes actually comes from `themes/cakecious/assets/css/themestyles.css`. As you can see in the image below I have disabled them and it works as expected:
<img width="1870" alt="Screenshot 2021-05-07 at 11 57 21" src="https://user-images.githubusercontent.com/1628454/117433168-7a956e00-af2b-11eb-8210-615b5846a3f5.png">

If you only want to target the payment images then I recommend you use this selector: `.wc-block-components-payment-method-icons .wc-block-components-payment-method-icon`.

As this is not a blocks related issue, I am gonna go ahead and close it. 

Hope this helps.
