### ISSUE TITLE
Audit Blocks for dependency on `unfiltered_html` capability attached to the user that inserts and saves content with the block (and work on alternatives)

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#4181]
We have some blocks that add html to the `post_content` of a page or post that is stripped out by WordPress unless the user role has `unfiltered_html` capabilities. An example of a block doing this is the Product Search block. 

This issue has the goal of accomplishing the following:

## Audit our blocks for which are affected.

A quick way to do this is to create a user with the "Author" WordPress role and use that user to add all blocks to a page. Go to the frontend and see which blocks don't render/behave as expected.

## Plan how we'll resolve this.

There's a couple approaches that immediately come to mind (there may be more). Also, note that it's possible different approaches might be needed across the blocks that come up in the audit.

### Option A: Only make affected blocks available to users editing content with `unfiltered_html` capability.

This probably would be the most trivial to implement but some significant cons are:

- it removes the availability of these blocks for users on sites/stores with reduced capabilities for security reasons.
- it'd be fairly easy for someone without the `unfiltered_html` capability to edit a post that _was_ saved with the block by a user with the right capabilities and bork the content as a result. This would also be an initially hard thing to troubleshoot what went wrong.

### Option B: Change what we save to the post content to be placeholder and hook in server side or client side to dynamically add any additional html usually stripped out by `wp_kses_post` on post save.

While this would be a bit more effort to implement, it would have the benefit of retaining usage of the blocks to _anyone_ on the site that has publishing capabilities. The downside with this approach (at least in the case of server side rendering only) is that the user experience in the editor will be degraded a bit with using this type of block and/or potentially having multiple places to track/preserve layout changes (vs using the saved `post_content` only).

**Comment by mikejolley** [comment]
Added all blocks to a page as admin, then enabled the `DISALLOW_UNFILTERED_HTML ` constant and resaved. I then compared the diff of the code view. There were 2 discrepencies:

- woocommerce/product-search - Wrong form output]
- woocommerce/cart - `data:` part removed from inline SVG image in default markup

After testing the cart one doesn't make any noticeable difference. We should only need to patch search.
