### ISSUE TITLE
Call to action buttons: formatting issues in preview.

### ISSUE THREAD

**Issue by coderkevin** [woocommerce/woocommerce-gutenberg-products-block#419]
**Describe the bug**
While the English form of "Add to cart" is concise enough to collapse well for multiple columns, other languages are more problematic and suffer from formatting issues.

**To Reproduce**

1. Set language to Spanish or French.
2. Create a block with multiple columns.

**Expected behavior**
Formatting of buttons to appear complete and not overlapping.

**Screenshots**

<img width="820" alt="editar_entrada_ _two_wordpress_test_ _wordpress" src="https://user-images.githubusercontent.com/945228/52688633-da536900-2f1c-11e9-98d7-54f43aa6e46a.png">

**WordPress (please complete the following information):**

* Core version: 5.0.3
* WooCommerce version: current master (as of 2018.02.12)
* WooCommerce Blocks version: current master (as of 2018.02.12)
* Site language: Various

**Desktop (please complete the following information):**

* OS: osx
* Browser: Chrome
* Version:  71.0.3578.98

**Comment by ryelle** [comment]
I would say this is just an issue with using columns that become too small– it would be nice if we could be smart about minimum column widths (there has been a lot of investigations into this), but we're not doing that yet. I don't think we should be breaking words apart, so IMO this isn't really a bug– the user should see this and adjust the columns or switch it to wide or full width.

@jameskoster What do you think?

**Comment by jameskoster** [comment]
> I would say this is just an issue with using columns that become too small

I agree. That, and the Gutenberg editor column being so narrow.

I imagine that on the front-end this isn't a problem which, imo makes this the themes responsibility to address. The theme author has multiple options in that regard:

1. Add editor styles so that the editor column width matches the frontend content width.
2. Filter our column range allowance for appropriate column options based on content width.
3. Adjust button styles for products if required.

**Comment by ryelle** [comment]
We should make sure those approaches are documented somewhere before 3.6 is released, so I've added a separate issue for all documentation notes: https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/437

Closing this, since we don't need to fix anything here.
