### ISSUE TITLE
Prepare WooCommerce for Block Widgets in the Widgets Editor and Customizer

### ISSUE THREAD

**Issue by frontdevde** [woocommerce/woocommerce-gutenberg-products-block#4198]
The goal of this project is to prepare WooCommerce for Block Widgets in the Widgets Editor and Customizer. These Gutenberg features are slated to become part of the WordPress core with the upcoming WordPress 5.8 release.

This is an epic following our audit to address the issues we found.

**Comment by nerrad** [comment]
I'm going to close this because I think it's done? (reopen if it isn't).
