### ISSUE TITLE
Disabling Coupons Doesn’t hide the Coupon Code Option in the Checkout Block

### ISSUE THREAD

**Issue by igotdes** [woocommerce/woocommerce-gutenberg-products-block#4201]
## Describe the bug
Even when coupons are disabled under **WooCommerce > Settings > General**, there is still an option to add a coupon in the Checkout block.

## To reproduce

1. Under **WooCommerce > Settings > General**, make sure that "Enable coupons" is unchecked
2. Create a page, add a Checkout block to it, and save it
3. View the page from the front end

## Expected behavior
The option to add a coupon should be hidden.

## Screenshots
Coupons Are Disabled In General Settings
![Coupon Setting](https://user-images.githubusercontent.com/74066241/117969127-9e0c4e80-b359-11eb-957c-448a9c6bf15c.png)

Coupons Are Still an Option in the Checkout Block
![Page with Checkout Block](https://user-images.githubusercontent.com/74066241/117969257-c5631b80-b359-11eb-9117-3fa219f1da39.png)

### WordPress:
* Core version: 5.7.1
* WooCommerce version: 5.2.2
* WooCommerce Blocks version: 5.1.0
* Site language: en_US
* Any other plugins installed:
  * Companion Plugin: by Osk – 1.18

### Desktop:
* OS: macOS 11.3.1 (20E241)
* Browser: Chrome 90.0.4430.93 (Official Build) (x86_64)

## Additional context
* This was reported in [this WooCommerce Blocks forum thread on WordPress.org](https://wordpress.org/support/topic/can-not-disable-coupon-code-option/)
* A JN site displaying the issue can be seen [here](https://melted-goldfish.jurassic.ninja/product/test-product/). It will be destroyed around May 18, 2021. For ease of checking, there's a link there in the menu to a page with a Checkout block.

**Comment by Aljullu** [comment]
Confirming the issue, thanks for opening it @igotdes!

It seems to be a regression introduced in 5.0 (particularly, in this PR: #4059).
