### ISSUE TITLE
To large font of product price in Cart an Checkout

### ISSUE THREAD

**Issue by alzajac** [woocommerce/woocommerce-gutenberg-products-block#4214]
Hello, how can I make font of product price smaller in Cart an Checkout? I dont know if it is coused by Elementor or Porto Theme compatibility issue.

![To large font of price - Cart](https://user-images.githubusercontent.com/58148038/118468230-d8cd0880-b704-11eb-9df9-b12a1bb25136.png)

![To large font of price - Checkout](https://user-images.githubusercontent.com/58148038/118468243-dc608f80-b704-11eb-81d0-0e1ded4c9fd3.png)

**Comment by senadir** [comment]
This is mostly a theme issue, you can target this class `.wc-block-components-totals-item__value` to change the value back.

**Comment by Neslist** [comment]
how to target this class can u guide me? i have same problem

**Comment by Neslist** [comment]
> This is mostly a theme issue, you can target this class `.wc-block-components-totals-item__value` to change the value back.

how to target this class can u guide me? i have same problem
