### ISSUE TITLE
Block Widgets: revisit (UX) issues that led to decision to exclude the All Products and filter blocks

### ISSUE THREAD

**Issue by frontdevde** [woocommerce/woocommerce-gutenberg-products-block#4218]
_This issue surfaced as part of our audit of the current state of using WooCommerce Blocks as Block Widgets in the new Widgets Editor and Customizer (pca54o-1pT-p2)._

In https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4217 and https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3737 we excluded the `All products` and filter blocks from being used as block widgets.

The exclusion of these blocks should be seen as a temporary measure. Ultimately we'd like users to be able to use these blocks instead of the related widgets.

The goal of this tracking issue is to revisit the UX issues that led to the decision to exclude these blocks and identify what steps would be necessary to resolve these issues.

**Comment by Aljullu** [comment]
Filter blocks have been enabled in #6299, and I think we can hold off on enabling the All Products block in widget areas until we have a blockified solution for product grids/lists. So closing this issue.
