### ISSUE TITLE
£0 Tax included in basket and checkout although taxes not enabled in settings

### ISSUE THREAD

**Issue by Shazgu** [woocommerce/woocommerce-gutenberg-products-block#4243]
## Describe the bug
We have not enabled taxes in settings (see screenshot), but we've started seeing £0 tax under Total in both basket and cart after the a recent updated (see screenshot).
This doesn't appear to be a result of a clash. We saw it on the default theme too and with all third party plugins disabled. When we changed to the default cart and checkout pages, that line didn't appear (with either theme enabled and with plugins disabled or enabled). So we deduced it's a blocks issue.

## Expected behavior
No taxes notice.

## Screenshots
<img width="789" alt="tax settings" src="https://user-images.githubusercontent.com/71322363/118857631-2c3f8200-b8d0-11eb-8321-08aef93c6692.png">
<img width="455" alt="taxes showing in basket" src="https://user-images.githubusercontent.com/71322363/118857634-2d70af00-b8d0-11eb-8157-c89562976572.png">

### WordPress (please complete the following information):
* Core version: 5.7.1
* Gutenberg version (if installed): [e.g. 4.8.0]
* WooCommerce version: 5.3.0
* WooCommerce Blocks version: [e.g. 1.3.1]
* Site language:
* Any other plugins installed:

### Desktop (please complete the following information):
* OS: [e.g. macOS, Windows]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):
* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Comment by opr** [comment]
Thanks for the report @Shazgu - I have verified the bug and even made a PR to fix it this morning since it was quite an easy fix. 🙌🏼  If it gets reviewed in time it will be released this week.

**Comment by Shazgu** [comment]
That's very good news, @opr :) 
Thanks!
