### ISSUE TITLE
Research spike: get a Product element block to work inside the Query block

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#4246]
We need to investigate how the Query block works internally and try to create a Product element block that works inside the Query block.

### Outcome

The outcome of this research spike should be to have a prototype of a Product element block which can be added inside the Query block. An example, would be being able to add the Product price block inside the Query block.

Related to https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4245, the block should not have unnecessary JS dependencies loaded in the frontend.

### Resources

"Product element blocks" were named "Atomic blocks" in the past. They might be a good base to start from. They can be found in this directory:

https://github.com/woocommerce/woocommerce-gutenberg-products-block/tree/trunk/assets/js/atomic/blocks/product-elements

**Comment by nerrad** [comment]
I'm assuming this issue is done based on the published P2 so I'm going ahead and closing it, please do re-open if I'm incorrect. If it's re-opened, it'd be nice to have an update on the issue on where this is at given it's still in the "In Progress" pipeline.

**Comment by frontdevde** [comment]
@nerrad I left the issue open as I'm still looking into ensuring we only request required data once. That said, this is more related to the actual implementation than the research spike. So from that perspective, I'd agree we can close this research spike issue.
