### ISSUE TITLE
Create a function that allows extensions to make an API request, and signal that the cart should also be reloaded

### ISSUE THREAD

**Issue by opr** [woocommerce/woocommerce-gutenberg-products-block#4254]
When extensions update the cart server-side, we need the fresh cart data to be fetched client-side. The following solutions have already been explored:
1. Let extensions set cart data themselves
2. Give extensions a way to tell Blocks that the cart needs to be re-fetched

Neither of these solutions are suitable for the following reasons, respectively:
1. If an extension adds cart data that is the incorrect shape, the entire block will break
2. If this happens, there will be the initial delay where the cart is updated by the extension, then a second delay when Blocks fetches new API data.

To solve this I am proposing a new method in the `blocks-checkout` package, named something like `restRequestWithCartUpdate`. The API would be the same as `@wordpress/api-fetch` but the request made by the extension would be batched with a request to fetch new cart data, so only one request needs to be made to the server.

**Comment by mikejolley** [comment]
@opr can you provide examples of the types of requests being made to the server? Like, do they go via existing Store API routes, or do they use custom endpoints?

**Comment by senadir** [comment]
How can extensions update the cart without interacting with the block? are they hitting an endpoint themselves? can you provide an example?

In my understanding, any interaction with the data store should refresh the cart by our block.

**Comment by opr** [comment]
> @opr can you provide examples of the types of requests being made to the server? Like, do they go via existing Store API routes, or do they use custom endpoints?

It'll be a custom endpoint, the specific one I have in mind is the one I'm adding in Points and Rewards that will (ultimately) apply a discount code to the cart.
 https://github.com/woocommerce/woocommerce-points-and-rewards/blob/90951fa41e427efb6db822f239f6ee198feebb67/assets/js/partial-redemption-panel.js#L55-L70 which executes this function in PHP:  https://github.com/woocommerce/woocommerce-points-and-rewards/blob/90951fa41e427efb6db822f239f6ee198feebb67/includes/class-wc-points-rewards-cart-checkout.php#L184-L203

The discount code isn't known ahead of time as it's calculated server-side based on the amount of points the customer wants to redeem, how many points the user has available, settings in Points and Rewards, and the value of the cart, this is why we can't simply use the `apply-coupon` endpoint.

**Comment by mikejolley** [comment]
This is hacky idea, but we could look at extending one of the update endpoints which return a new cart object to accept points, such as https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/src/StoreApi/Routes/CartUpdateCustomer.php

If this had value, we could look at exposing an update routine on the main cart endpoint instead so other extensions with similar use cases could benefit.

**Comment by opr** [comment]
> This is hacky idea, but we could look at extending one of the update endpoints which return a new cart object to accept points, such as https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/src/StoreApi/Routes/CartUpdateCustomer.php
> 
> If this had value, we could look at exposing an update routine on the main cart endpoint instead so other extensions with similar use cases could benefit.

The problem with this is that it only covers this one use-case, and is not a generic or reusable solution for other extensions that need to do something server-side before updating the cart.

The points redemption is ultimately just a discount code, so while we could use the `apply-coupon` endpoint, to know which coupon to apply we'd still need to make a request to the P&R API. This is what I want to avoid, making two requests, where one depends on the result of the other (so they can't be batched).

**Comment by mikejolley** [comment]
@opr To try to be clearer, I'm not suggesting this is the correct route, but I am trying to say we should have a generic "cart update" route which extensions can extend. e.g. Points are Rewards can add a 'points' property, which in turn returns an updated cart as normal or an error code if it fails.
