### ISSUE TITLE
Integration Tracking (AutomateWoo): Make sure Draft orders don't trigger Order Created

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#4261]
This issue is meant to track the progress on guarding order created trigger in AutomateWoo from draft orders.

## Requirements
- The trigger should not run when a draft order is created.
- It should still run when the order is finally submitted.
- It should not affect other events.

**Comment by nerrad** [comment]
Looks like the related PR was merged in the automate woo repo so I'm going to close this one.
