### ISSUE TITLE
Border on `Coupon code` Panel in Cart/Checkout is too thick when there is no shipping required

### ISSUE THREAD

**Issue by opr** [woocommerce/woocommerce-gutenberg-products-block#4267]
## Describe the bug
When there is no shipping required on the order, the border below `Coupon code` is too thick, it is made up of two borders, one below the coupon panel, and one above the order total.

## To reproduce

1. Add a virtual product to the cart.
2. View the Cart/Checkout block.
3. See the double border.

## Expected behavior
The border should not be doubled up if there is no shipping on the cart.

## Screenshots
![image](https://user-images.githubusercontent.com/5656702/119530119-9cd81a00-bd7a-11eb-9911-0aecb7d3460c.png)

**Comment by vaish567** [comment]
Hey @opr Can I take step up on this issue? 
Could you please navigate me where can I find this issue? As this would be my first pull request.

**Comment by opr** [comment]
Howdy @vaish567 ! Thanks for offering your help here, we're really grateful for your willingness to step up 😊  Sorry for the delay getting back to you!

While discussing internally, we actually decided on a direction that's a little bit more involved, and so this probably won't be suitable for a `good first issue`, so I'll be removing this label. This is on the basis that we're planning on adding a `TotalsWrapper` component which will be responsible for spacing and borders, this component will encapsulate all fields that don't need borders, and quite a lot of style changes will need to be applied, and a fair amount of experimentation will need to be done.

In spite of this issue not being suitable for a first one, we have plenty of others to choose from, you can find them at this URL: https://github.com/woocommerce/woocommerce-gutenberg-products-block/labels/good%20first%20issue - feel free to comment in any of these issues if you're keen on picking one up.

Thanks again 🙇🏼‍♂️
