### ISSUE TITLE
Some strings not translated on cart and checkout blocks

### ISSUE THREAD

**Issue by dani-elo** [woocommerce/woocommerce-gutenberg-products-block#4273]
## Describe the bug
Some strings are not translated/translatable in the checkout and cart blocks.

## To reproduce

1. Create a checkout page with the blocks
2. Change your site language to a fully localized language as es-Es. ([Translation status](https://translate.wordpress.org/locale/es/default/wp-plugins/woo-gutenberg-products-block/))
3. Navigate to the checkout page and see that some strings are not translated 

![https://d.pr/i/hzdQwe](https://d.pr/i/hzdQwe+) 
Full Size: https://d.pr/i/hzdQwe

## Expected behavior
I would expect all the strings translated providing the status of the translation project.

### WordPress (please complete the following information):

* WooCommerce Blocks | &nbsp; | by Automattic – 5.1.0
* WooCommerce | &nbsp; | by Automattic – 5.3.0
* Site language: es-Es
* Any other plugins installed: No.

## Additional context
Strings can be translated with the [Say What](https://wordpress.org/plugins/say-what/) as a workaround

Reference: https://wordpress.org/support/topic/some-translations-do-not-work/

**Comment by nerrad** [comment]
I did some initial investigation on this and I'm able to reproduce. It's not immediately apparent what's going on but I have assigned this for the porter rotation to pick up and investigate.

**Comment by opr** [comment]
Posting my findings for the next porter:

From what I can see, the strings that don't get translated  (the fields in [`defaultAddressFields`](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/cbbd9d7dcc30a2c4224aa83e62486501658a4050/assets/js/settings/shared/default-address-fields.ts#L65)) are loaded and evaluated straight away, and thus the `__` function is evaluated immediately as soon as the script is loaded. This is in contrast to those that are executed later (for example in the [render function of a component](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/ea74395e34de2ca7c569bab69bc6017d753c07a7/assets/js/blocks/cart-checkout/checkout/form/phone-number/index.js#L26)).

How can we ensure the script translations are loaded before the script is? I don't have much experience of wp i18n so I'm not sure exactly how it works.

**Comment by nerrad** [comment]
I think what's happening here is `defaultAddressFields` were moved into the `wc-settings` build and as far as I can tell, we're not using `wp_set_script_translations` on this handle. So the relevant strings aren't getting registered for this file client side as a result.

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/b9bd086e0eda251d5ecb337151f6922e0b521e48/src/Assets/AssetDataRegistry.php#L314-L321

This is the interface that is called:

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/b9bd086e0eda251d5ecb337151f6922e0b521e48/src/Assets/Api.php#L81

So notice the `$has_i18n` flag is set to false.
