### ISSUE TITLE
Terms and Conditions Block

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#4319]
This will be an inner block for Checkout i2. There will be 2 versions or layout options for this block:

- Checkbox: Mandatory checkbox with custom text beside it
- Text: Text that explains that by proceeding you agree to TOS

Notes:
- We need to decide between pre-def text, or completely custom
- Pre-def text can contain links to the TOS and privacy pages, which are selectable in the UI.
- If not pages are selected, a warning is shown to the admin.

See https://teamrubik.wordpress.com/2021/06/04/cart-and-checkout-i2-design-exploration-progress-post-2/

Edit: This has been started in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/4268 and the block has been defined, but two things need to be added:

- [x] Checkbox Validation
- [x] Validation in editor if no links are added within the block text

**Comment by Luisxdrr76** [comment]
Exited to see when it comes out
