### ISSUE TITLE
Products by Tag: no tags message is not correctly aligned in Site Editor

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#4333]
## To reproduce
1. Remove all Product Tags from your store if your store has any.
2. With Gutenberg and TT1 Blocks, go to the Site Editor.
3. Add a Products by Tag block and notice the message `Your store doesn't have any product tags.` is not aligned with the icon:

![imatge](https://user-images.githubusercontent.com/3616980/121341156-acca2f00-c920-11eb-8842-d0352181cd5a.png)

This needs to be fixed in WC Admin. If I'm not wrong, adding `vertical-align: middle;` to [this line](https://github.com/woocommerce/woocommerce-admin/blob/586e770fe0bdfb5cabc91eac8417dc63cd35edfd/packages/components/src/search-list-control/style.scss#L69) would fix it.

**Comment by vaish567** [comment]
Howdy @Aljullu If you don't mind Could I step-up on this issue? I think it looks perfect for my contribution.

**Comment by Aljullu** [comment]
Sure thing @vaish567! You will need to clone WooCommerce Admin repo:

https://github.com/woocommerce/woocommerce-admin

And make the change I indicated to `packages/components/src/search-list-control/style.scss`. Then, you will need to create a PR and link to this issue. Let me know if you need any more guidance on how to get started. :slightly_smiling_face:

**Comment by Aljullu** [comment]
Oh, and one more thing. To test if the fix works and doesn't break anything else, you will need to run `npm run storybook` in WC Admin to run the Storybook. There, you can open the `SearchListControl` component and play with it. If you search for an item that doesn't exist, you will see the 'No results' message:
![imatge](https://user-images.githubusercontent.com/3616980/121382678-22e18c80-c947-11eb-9a79-21a551765157.png)

**Comment by Aljullu** [comment]
Tested and I can still reproduce this.

**Comment by alexflorisca** [comment]
Tested and looks like it has been fixed. @Aljullu mind taking another look just to be sure before I close it?
![Screenshot 2021-11-17 at 17 22 07](https://user-images.githubusercontent.com/3966773/142250259-4a0d84ba-ad83-488a-8d2d-045428c4f1d2.png)

**Comment by Aljullu** [comment]
Yes, it looks like it has been fixed. Thanks for investigating @alexflorisca!
