### ISSUE TITLE
Load block CSS only from blocks used in the page

### ISSUE THREAD

**Issue by Mte90** [woocommerce/woocommerce-gutenberg-products-block#4338]
## Is your feature request related to a problem? Please describe.
We are using only a single block in all the website, but the whole woocommerce block css (5975 lines of rules) is loaded in all the pages of the website. 
For Chrome the coverage is that the css unused is 95% in the page where it is used.

## Describe the solution you'd like
Check what blocks are used in the page and load the specific css file just for that.

**Comment by aristath** [comment]
A few months ago Gutenberg got the ability to load separate block-styles on-render. These tweaks are being backported to WordPress Core and are present in WP5.8-beta.
Basically, if the plugin is registered using `register_block_type_from_metadata` (which is now the recommended method to register a block) and has a `style` defined inside the JSON file, core takes care of the rest.
However, I see that this plugin doesn't use a `block.json` file for its blocks, so an alternative would be to split the CSS files and have a separate file per block. Then, to add the block-styles on-render, the plugin can hook in `render_block` and enqueue its stylesheet then.

**Comment by Mte90** [comment]
The issue is still active just to avoi getting closed the ticket.

**Comment by Mte90** [comment]
Well the ticket is still on, closing in 10 days doesn't help at all.

**Comment by Mte90** [comment]
Stale for the third time...

**Comment by Mte90** [comment]
stale for forth time...

**Comment by Mte90** [comment]
Stale for the fifth time!

**Comment by Mte90** [comment]
It's me again for the sixth time...

**Comment by Mte90** [comment]
For the seventh time it is stale because no one from woocommerce is replying!

**Comment by gigitux** [comment]
Hi @Mte90!
Thanks for opening this issue. This issue is on our radar. Also, since it was created there has been some work on utilizing `block.json` and `register_blocktype_from_metadata`. We will review what remaining related performance improvements can be made in the coming weeks. In the meantime, any contributions are welcome!

**Comment by Aljullu** [comment]
To bring some extra context to this discussion: that's something that was evaluated three years ago (#752). At that time, we decided not to move forward with this, the rationale being that WooCommerce blocks share a lot of styles between them. So, while splitting the styles per block was a performance improvement for pages using one single block, it would cause a performance degradation for pages using several blocks.

We acknowledge things have changed in three years and Gutenberg is splitting styles per block (https://github.com/WordPress/gutenberg/pull/25220). We are onboard on following the best practices to create and register blocks. But at the same time, it needs to be understood that some WooCommerce blocks are quite different from those included in Gutenberg, and their approach might not always be the best for our use case.

Hopefully in the short term we will be able to measure the impact this change would have and we will be able to take a decision on this.

**Comment by danielwrobert** [comment]
See https://github.com/woocommerce/woocommerce-blocks/pull/7006.

**Comment by Aljullu** [comment]
This has been closed in #9831 and will be included in WC Blocks 10.7.
