### ISSUE TITLE
Spacing for the Payment method section is too small

### ISSUE THREAD

**Issue by ralucaStan** [woocommerce/woocommerce-gutenberg-products-block#4341]
## Describe the bug
In the Checkout block, the spacing for the Payment method section is too small.

## To reproduce
1. Add the Checkout block to a page and make sure you have the Stripe extension and Stripe credit cart enabled
2. Buy a product and go to checkout 
3. Scroll and see the crowded content in the Payment method section

## Expected behavior
The spacing should be bigger. @vivialice we might need your help here.

## Screenshots
![Screenshot 2021-06-08 at 11 53 13](https://user-images.githubusercontent.com/1628454/121660505-00b54f00-caac-11eb-886e-14b2ae2b2be9.png)

**Comment by vivialice** [comment]
Hey @ralucaStan! Yep this should be a simple fix. Is this the standard line-height on the copy next to the checkbox? It feels a little high and I'd like to shorten it but don't want to contradict other styles. 

The spacing on the top of the logos should be matched below and we could add more breathing space in between. 

I've attached a mockup for reference! 👇 

![payment-spacing1](https://user-images.githubusercontent.com/9888201/121667353-19206c00-caa2-11eb-8cc7-d9f31a8dde73.png)

**Comment by nerrad** [comment]
I'm not seeing this spacing issue anymore (at least in Chrome). The screenshot below is on a smaller viewport as well:

<img width="467" alt="CleanShot 2021-08-18 at 14 50 57@2x" src="https://user-images.githubusercontent.com/1429108/129955400-6707b8d7-0b01-47d6-89d5-0b949994994c.png">
