### ISSUE TITLE
There is a bug on the shopping cart page when the resolution changes

### ISSUE THREAD

**Issue by msroky** [woocommerce/woocommerce-gutenberg-products-block#4371]
I have seen through hotjar that my customers are facing this problem.

The user came with the tablet to the page to buy the product, the resolution of the tablet is 748x480.

![Capture](https://user-images.githubusercontent.com/12650820/122670417-3ea82680-d1c2-11eb-9645-61eefb19a1ce.PNG)

The thumbnails below the "process to checkout" button were magnified full screen and the user could not do anything. I lost that customer because of it.

I had to manually add my own CSS style to customize the thumbnails.

Please fix this in the next version.

**Comment by mikejolley** [comment]
Hi there,

These icons seem to already have a defined size in CSS - height is 24px, and width is auto.

Can you give more details about the theme you're using and what triggered the large size?

Thanks

**Comment by msroky** [comment]
I added this custom css style

```
.wc-block-components-payment-method-icons {
    display: flex !important;
    width: 50px;
    margin: 10px 0 0 40px !important;
}

.wp-block-woocommerce-cart {
    text-align: left !important;
}

.wc-block-components-express-payment.wc-block-components-express-payment--cart, .wc-block-components-express-payment-continue-rule.wc-block-components-express-payment-continue-rule--cart {
    display: none;
}
```

**Comment by msroky** [comment]
This is what it looks like without a custom css
![Capture3](https://user-images.githubusercontent.com/12650820/123515045-49692c80-d696-11eb-83d3-5d3b5f37f5ef.PNG)

**Comment by msroky** [comment]
I solved the problem by adding "!important" to your existing css
```
.wc-block-components-payment-method-icons .wc-block-components-payment-method-icon {
    height: 24px !important;
}
```

**Comment by senadir** [comment]
Hey there @msroky

Glad you fixed the issue! can you tell us what theme are you using so we can try to fix it on our end?

**Comment by msroky** [comment]
https://themeforest.net/item/salient-responsive-multipurpose-theme/4363266
