### ISSUE TITLE
Payment methods limited

### ISSUE THREAD

**Issue by optimvsjag** [woocommerce/woocommerce-gutenberg-products-block#4375]
Hi Team, I've some payment methods that not shows in checkout block like "[Coinbase commerce](https://es.wordpress.org/plugins/coinbase-commerce/)" or "[Paycomet cards](https://es.wordpress.org/plugins/paytpv-for-woocommerce/)"
This plugin not charge all payments methods activated in woocommerce? Needs some special config or code for apply this?

Thanks a lot.

**Comment by mikejolley** [comment]
Hi there @optimvsjag 

Thanks for taking the time to make us aware that these methods are not working with the Checkout and Cart blocks. These blocks are still in early access (via the feature plugin) and it's _expected_ that some existing payment methods will not work with the blocks.

Currently, it's up to payment method extension developers to add support for the new checkout flow offered via the cart and checkout blocks. We have some [documentation on that here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/extensibility/payment-method-integration.md).

Your best course of action right now is to notify the developer of the extension and ask if they can add support to their extension using our documented APIs.

Until then you can keep on top of the [status of the Cart & Checkout Blocks in this documentation](https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/).

Thanks
