### ISSUE TITLE
Express payment buttons unmounts and mount again on changes causing layout shift

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#4383]
## To reproduce
You need to have an express payment method set up.

1. Go to checkout.
2. Change something in the checkout like email, shipping address, or selecting a different shipping method.
3. Notice that express payment buttons would unmount and mount again.

I confirmed that this only happens for express payment methods. Regular payment methods are fine.

This issue also predates https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/4228 I tested with 5.3.1 and the issue was there as well.
## Expected behaviour
Buttons shouldn't unmount and mount. If they're no longer valid, they should unmount completely.

## Screenshots
https://user-images.githubusercontent.com/6165348/122988799-052a1380-d39a-11eb-8236-d50619156872.mov

**Comment by senadir** [comment]
Content jumping around is called cumulative layout shift and is harmful to the website SEO and just straight out annoying.
https://web.dev/cls/

**Comment by ralucaStan** [comment]
Possibly related to #4321

**Comment by senadir** [comment]
Yes, same issue.
