### ISSUE TITLE
Category filter and All Products block for archive page support

### ISSUE THREAD

**Issue by grogou** [woocommerce/woocommerce-gutenberg-products-block#4395]
Hi there!!!

In our fork I created Category filter block for All Products block.
Created All Products and related filters support for archive pages.

My code isn't fully clean for now, but if it is interesting for you i can create new pull request for this features, same as Stock Status filter #4145 

Some screenshots

Shop filter
![image](https://user-images.githubusercontent.com/10712881/123232468-3f0a2f80-d4ea-11eb-9e93-1d84a8f599f5.png)

Archive filter
![image](https://user-images.githubusercontent.com/10712881/123232592-5b0dd100-d4ea-11eb-9db0-d483765d3a7f.png)

I know it isn't main priority for now, but if you interested tell me!
Thank you guys!

**Comment by opr** [comment]
Hey @grogou, from my point of view this would be a great addition thank you!

Would you be able to open a PR for this new block, and we'll review the changes you're proposing?

**Comment by grogou** [comment]
Sure. Will do it, just need to clearify my code. It is little bit difficult block than stock filter, so need some time to do it. Thank you for responding.

**Comment by grogou** [comment]
Sorry for be late, I am working on this now, so if this request is actual for now I can continue work on this.
