### ISSUE TITLE
Cart and Checkout: Make URL targets customizable or give me filters

### ISSUE THREAD

**Issue by thomasdiesenreiter** [woocommerce/woocommerce-gutenberg-products-block#4396]
Use-Case:
We are building kind of a second shop inside our woocommerce install separate from the other one. One is for classic products, the other one is for courses (Sensei LMS).

Problem:
We managed most things to keep the two shops separately, except for the cool new cart and checkout blocks. The problem is, that they use the standard target url of the checkout page or the cart page, so they direct the user to the "wrong" shop.
I would like to be able to overwrite the form action targets or the redirect targets. I tried to use the woocommerce_get_checkout_url filter, but it seems like that the new blocks don't use the filter. 
The same goes for the cart link and the login link in the checkout block. I didn't try a test purchase with the new blocks yet, so I don't know if the target after a successful purchase is customizable as well or note at the moment.

**Comment by senadir** [comment]
Hey @thomasdiesenreiter 
I'm not really sure I understand what you're talking about. Do you want to change to where the "Proceed to Checkout" and "Return to Cart" buttons point to? If that's so, both blocks have an option to change to what page they point to.

For the login link, it will point to your My account page (to use WooCommerce login form), if you don't have that page setup, it will use `wp_login_url` which you can filter.

If that's not what you're asking for, can you please clarify your goal exactly?

**Comment by thomasdiesenreiter** [comment]
> Hey @thomasdiesenreiter
> I'm not really sure I understand what you're talking about. Do you want to change to where the "Proceed to Checkout" and "Return to Cart" buttons point to? If that's so, both blocks have an option to change to what page they point to.

Hi Senadir, thanks for your feedback.

Yeah, thats what I want to do. But thats weird, I don't see an option to change the page they point to. Here's for example what I see with the cart block:
![image](https://user-images.githubusercontent.com/28954669/123438223-c7630000-d5d0-11eb-93df-f215a8567cb9.png)
and here is the checkout block:
![image](https://user-images.githubusercontent.com/28954669/123438549-14df6d00-d5d1-11eb-8b6f-ba70d06938f7.png)

There is also no way to change the links in the visual editor itself, at least as far as I tried to click everything.

> For the login link, it will point to your My account page (to use WooCommerce login form), if you don't have that page setup, it will use `wp_login_url` which you can filter.
Ah, thanks a lot, I'll try that.

> If that's not what you're asking for, can you please clarify your goal exactly?
If there already should be an option to change the pages they point to, then thats what I need. But as I don't see them I suspect that there could be a bug preventing me from seeing them? Sorry should it be my fault for not

**Comment by thomasdiesenreiter** [comment]
OOOOOOkay, that was a wild ride.

The page selector wasn't visible in my editor because one of my plugins had a add_shortcode function which at one point did an echo instead of writing into the return buffer. 
This shortcode is called via an action on the page where I added the cart and the page. 
I was able to verify this by commenting the shortcode in and out. After fixing it, the error vanished.

Though I still don't know why this error in a shortcode leads to one editor UI element going missing? This still seems like a bug to me. Otherwise we can close this ticket of course, sorry for the hassle should it be a non-issue.

**Comment by thomasdiesenreiter** [comment]
> For the login link, it will point to your My account page (to use WooCommerce login form), if you don't have that page setup, it will use `wp_login_url` which you can filter.

I tried this. As you said, it only uses wp_login_url if the setting isn't used. This is counterintuitive: Why doesn't it get the my account page from the settings and then apply the filter in every case?
In my case this doesn't help me, as unsetting the page isn't an option.

**Comment by thomasdiesenreiter** [comment]
okay, i was able to solve the login url issue with a filter on option_woocommerce_myaccount_page_id, works just fine.

**Comment by senadir** [comment]
> I tried this. As you said, it only uses wp_login_url if the setting isn't used. This is counterintuitive: Why doesn't it get the my account page from the settings and then apply the filter in every case?

We're avoiding adding filters to the new code introduced by Cart and Checkout and prefer more curated extensibility points. I'm glad you were able to use `option_woocommerce_myaccount_page_id`.
