### ISSUE TITLE
"In Cart" Not Being Translated on the All Products Block

### ISSUE THREAD

**Issue by igotdes** [woocommerce/woocommerce-gutenberg-products-block#4420]
## Describe the bug
When using the All Products block, "add to cart" is translated. However, "# in cart" is not.

## To reproduce

1. On WP Admin > Settings, set the Site Language to a language other than English like Español or 日本語
2. Make sure to download any translation updates under My Home > Updates
3. Create a page, add the All Products block to it, and save it
4. View the page and add a product to cart

## Expected behavior
"# in Cart" should be translated.

## Screenshots
![GHSpanish](https://user-images.githubusercontent.com/74066241/124253695-df033100-db5a-11eb-871d-15fd66d327ab.png)
![GHJapanese](https://user-images.githubusercontent.com/74066241/124253715-e591a880-db5a-11eb-8061-8d71a623f4a3.png)

### WordPress:
* Core version: 5.7.2
* WooCommerce version: 5.4.1
* WooCommerce Blocks version: 5.4.0
* Site language: es_ES
* Any other plugins installed:
 * Companion Plugin: by Osk – 1.18

### Desktop (please complete the following information):
* OS: macOS
* Browser: Chrome Version 91.0.4472.114 (Official Build) (x86_64)

## Additional context
* Reported in [this WordPress.org forum thread](https://wordpress.org/support/topic/spanish-translation-error-add-to-cart-button-x-items-in-cart/)
* May be related to this report: ["Sale" Not Being Translated on the All Products Block](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4019)?
* Test site demonstrating the issue: https://solitary-pheasant.jurassic.ninja/test-page/

**Comment by rafamerino** [comment]
Feel free to contact me in case you need EN > ES translations. Happy to help!

**Comment by senadir** [comment]
Hey! this should be fixed by https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/4392
