### ISSUE TITLE
POST /cart/update-customer does not update shipping and billing

### ISSUE THREAD

**Issue by TatjanaDjurdjevic** [woocommerce/woocommerce-gutenberg-products-block#4440]
This API call doesn't work how it is described in the documentation. It does not update shipping and billing addresses properly. When called it only sends back the cart response, without the new information. 

#Steps to reproduce
1. Make API call GET /wc/store/cart in order to get nonce token
2. With nonce token add item in the cart via POST /wc/store/cart/add-item 
3. Try to update shipping or billing address with nonce token and POST /cart/update-customer. 

### WordPress (please complete the following information):
* Core version: 5.7.2
* WooCommerce version: 5.4.1
* WooCommerce Blocks version: 5.1.0

**Comment by mikejolley** [comment]
Hi @TatjanaDjurdjevic 

Can you paste the body of your request for `POST /cart/update-customer`?

If the endpoint was broken then the Block Checkout address updates would also fail—did you confirm this is functional? You can try the shipping calculator on the block cart page.

Thanks

**Comment by mikejolley** [comment]
Since this hasn't had a response I'm closing this issue after confirming it's functional. If you do still have issues, feel free to post back so we can do our best to help.

Thanks
