### ISSUE TITLE
Checkout i2: Shipping Rates Missing on the frontend

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#4441]
Since the last rebase there is an issue with missing shipping rates on the frontend, potentially related to Slot Fill issues we've been seeing (https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/4437).

CC @senadir 

To see the issue, just go to checkout. You'll see white space where the fills should be rendered: 

![Screenshot 2021-07-08 at 16.24.54.png](https://images.zenhubusercontent.com/546232087c6ccc6277a5e9a7/8d8adf77-9bce-4a15-8201-52ef7ac61889)

**Comment by senadir** [comment]
I'm pretty sure I fixed this, will look into it.
