### ISSUE TITLE
Checkout i2: Template Locking

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#4445]
This work has been started by @senadir, but adding a proper issue to track progress.

> Lock down the main blocks (individual steps, order totals) so that at that level blocks can’t be inserted and existing blocks can’t be moved. The idea being that in the future we retain the ability to unlock that.

As part of customizability and extensibility, we are planning on having a system where merchants can insert blocks into the Checkout Form Steps. But at the same time, some _core_ blocks need to be kept in the layout and non-removable. For this purpose, a [proposal for Locking has been made in Gutenberg](https://github.com/WordPress/gutenberg/pull/32457). However, due to time, we also want an interim solution so Checkout i2 can still ship with this functionality before this change makes it's way into WP.

**Tasks:**
- [ ] Work with Gutenberg Team to get [#32457](https://github.com/WordPress/gutenberg/pull/32457) merged.
- [ ] Integrate with template locking system from [#32457](https://github.com/WordPress/gutenberg/pull/32457)
- [x] #4453

**Comment by senadir** [comment]
Should this be ~locked~ closed or kept open until GB one merge?

**Comment by mikejolley** [comment]
@senadir if our system detects native support, this can be closed.

**Comment by mikejolley** [comment]
There is a separate issue here to track native support detection: https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4459
