### ISSUE TITLE
Create a Checkout Field Validation API for 3rd parties to hook callbacks into, which also shares values from other fields

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#4467]
There is a need for certain fields on the Checkout to have custom client-side validation callbacks—something to register a validation function, and then render an error message if validation fails, blocking checkout.

Validation would run either on change (for text fields) or on submit (to block checkout). **Fields would have access to all posted values so more complex validation could take place based on other fields.**

@opr proposed a solution along these lines:

> something similar to __experimentalRegisterCheckoutFilter you could pass this function an object (or two, one for billing one for shipping) keyed by the name of the field you want to validate, and the value of it would be an array containing: the function, an error message to display if invalid, and possibly some other fields to "listen" to (to revalidate if they change)

This API could be used for the postcode field (https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3326).

**Comment by mikejolley** [comment]
@opr This issue is still valid but isn't blocking Checkout i2 right now, FYI, because inner blocks with fields can validate themselves.

**Comment by mikejolley** [comment]
@nerrad is this more of a cooldown task? It's not needed for ci2 right now.

**Comment by nerrad** [comment]
> because inner blocks with fields can validate themselves.

Oh sweet! That does reduce the urgency for this issue. Is there still need for addressing the issue with the postcode field (#3326).

While this could be done as a cooldown task, I also think it's worthwhile considering issues like this for cycle work if we think it's need is significant? If you agree I'll add it for Cycle 6 consideration?

**Comment by mikejolley** [comment]
@nerrad I think a few of us have discussed the need for a refactor of the validation system. @senadir was interested in this. So yes this is nice to have and will make integrations easier. It's not blocking checkout though.

**Comment by mikejolley** [comment]
Clarification around what is needed:

- [This post has some context around why some of these changes are needed](https://teamrubik.wordpress.com/2021/04/06/adding-custom-validation-rules-to-address-fields/)
- We want the validation system to allow a component to:
     - Validate its own fields, prevent Checkout from submitting if its field is invalid
     - Access values of other fields, preventing checkout from submitting if values of other fields do not meet certain condition 
- Currently, validation works bottom-up, meaning only an input can say its value is invalid, but there's no way for a parent component to validate an input e.g. to retrigger validation without modifying a field
- An idea to to have data stored in a wp.data store so components and 3pd can query address data - this replaces storing data in context
