### ISSUE TITLE
Add links to all methods in "API Resources and Endpoints" section of the StoreApi documentation

### ISSUE THREAD

**Issue by opr** [woocommerce/woocommerce-gutenberg-products-block#4473]
In this page https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/src/StoreApi/README.md#api-resources-and-endpoints in the API Resources and Endpoints section the `Cart` row contains links to all sections (i.e. all endpoints) on the Cart page, but the other sections do not.

For example, under `Cart Items` there is only one link to `/wc/store/cart/items`, but there are 5 other methods in [the linked document](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/src/StoreApi/docs/cart-items.md#list-cart-items).

We should be consistent in linking to all endpoints.

**Comment by mikejolley** [comment]
Just to note, in the linked document that are not separate routes, just all variations of the `/cart/items` route. The cart endpoint has several routes (/cart/, /cart/add-item, etc) which is why they have separate documentation for each.
