### ISSUE TITLE
'sale badge' translation is incorrect on the editor side in JP

### ISSUE THREAD

**Issue by japanayu** [woocommerce/woocommerce-gutenberg-products-block#4474]
## Issue
The translation of 'sale badge' is incorrect on the editor side in Japanese while the front side of the same is correct.
'即時売上' is wrong and 'SALE' is correct one.

## Screenshots
![sale-translation](https://user-images.githubusercontent.com/78955986/126048224-e11a3c51-51c6-4e4e-aaf3-7d47ec9c08bc.png)

## Environment
* WooCommerce version: 5.5.1

**Comment by mikejolley** [comment]
Hi there,

This is being tracked in https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4019

Thanks
