### ISSUE TITLE
Removing unneeded fields and make them unrequired

### ISSUE THREAD

**Issue by AliBorsan** [woocommerce/woocommerce-gutenberg-products-block#4475]
Hello
Simply: in a country which (Postcode + State + country) not useable and because the shipping only is in the same country:
We need to remove those fields from shipping and billing and make them not required.. which keeping them make the checkout page uncomfortable and long for the customers.
Is there any filter or method that we can do that, because they are unnecessary for us and the costumers have to fill out whatever in them?
We love the WC Blocks checkout page and want to use it, so if there any flexibility and ability to remove some unneeded fields that would be so nice and helpful.
Thank you.

**Comment by mikejolley** [comment]
Hi,

Yes, this is possible. Address fields are determined from the country locale. You can see how they are defined here:

https://github.com/woocommerce/woocommerce/blob/124aeb746710a258f4d66dec4d333dd6cc9818dc/includes/class-wc-countries.php#L795

If you [log an issue](https://github.com/woocommerce/woocommerce/issues) or submit a Pull Request to WooCommerce core with the details of the locale you're targeting and fields that are not-required, this can be changed. 

Thanks

**Comment by AliBorsan** [comment]
Thank you very much, i will check that and give a feedback, and yeah, almost it goes about some address fields especially when they are required. 
Removing the unrequired and make some others unrequired also and removing them from the form, can make filling the payment data and shipping address faster and more easy for the customer to jump to the final step without concerning about those fields or filling them with ransom data.

**Comment by AliBorsan** [comment]
And also there something for the translations:
Those fields translation: (State, Provence, and zip code sometimes) are enforced by Woocommerce translation, which are translated based on the exact meaning usage of the english words, which make no sense in many countries, especially with Arabic language. where the user find fields that request data that does not exist in his country, which is confusing.
Is there any method for custom translation of those fields that cant be verritten by any new version or updated translation of Woocommerce or Wordpress, without costing the site owner 49,99 $ plugin that slow down his site and keep spying on his activities and keeping annoying him  with admin notices and spamming his mail inbox?
Thank you in advance/

**Comment by mikejolley** [comment]
> without costing the site owner 49,99 $ plugin that slow down his site and keep spying on his activities and keeping annoying him with admin notices and spamming his mail inbox?

I am not sure what you mean by this or how it is relevant to this thread. If the translations are not fit for purpose, you can contribute to those here: https://translate.wordpress.org/projects/wp-plugins/woocommerce/

**Comment by AliBorsan** [comment]
Thank you and sorry for the confusion with the comment, which i transferred complements from many customers , that they had to buy customization or white lable plugins only to correct these things.
Contributing to the translation will not solve that, because any translation will apply to the whole language>> and using plugins like "Loco translate" with system folder for the translation could not help.
I mean, its a local system applies in each country, as example: The word "State" is not being used in many countries, because the system in each country has another type of structure which is lot of countries have different administrativ divisions.
I thought that it is simple to implement some solution, but it seems to be complicated, so .. sorry for that, and please just ignore this request.
Thank you very much for your kind interaction.
