### ISSUE TITLE
not able to take other payment gateways than paypal and COD. please add option to take other payment gateway plugin configured

### ISSUE THREAD

**Issue by sufiyaann** [woocommerce/woocommerce-gutenberg-products-block#4476]

**Comment by nerrad** [comment]
Hi there @sufiyaann  👋 

Thanks for taking the time to make us aware that you are using a payment method that isn't working with the Checkout and Cart blocks. These blocks are still in early access (via the feature plugin) and it's _expected_ that some existing Woo Extensions that integrate with the current checkout flow in WooCommerce core will not work with the blocks. 

Currently it's up to payment method extension developers to add support for the new checkout flow offered via the cart and checkout blocks. We have some [documentation on that here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/extensibility/payment-method-integration.md) and have also publicized this via [this post](https://developer.woocommerce.com/2021/03/15/integrating-your-payment-method-with-cart-and-checkout-blocks/) on the WooCommerce developer blog.

Your best course of action right now if you are using a payment method that isn't working with the blocks is to notify the developer of the extension and ask if they can add support.

Until then you can keep on top of the [status of the Cart & Checkout Blocks in this documentation](https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/).
