### ISSUE TITLE
Possibility to edit checkout fields error messages

### ISSUE THREAD

**Issue by rufus87** [woocommerce/woocommerce-gutenberg-products-block#4478]
## Describe the bug
There is no possibility to edit checkout form fields error messages. The code is written in the way to force usage of browser default messages and there is no way to pass custom message or make it translatable.

## To reproduce

1. Go to checkout
2. Blur any field
3. Shown error message can't be changed

## Expected behavior
There should be possibility to pass/change checkout fields error messages just like it was in standard checkout form.

### WordPress (please complete the following information):
* Core version: 5.8-RC2
* Gutenberg version (if installed): 11.0.0
* WooCommerce version: 5.5.1
* WooCommerce Blocks version: 5.5.0
* Site language: English
* Any other plugins installed: -

**Comment by mikejolley** [comment]
Strings are wrapped in `__()` so it might be possible to use https://developer.wordpress.org/reference/hooks/gettext/

Can you explain a little more about the error messages you wish to customise and _why_? Why do the defaults not apply to your use case?

**Comment by Aljullu** [comment]
Hi @rufus87, we haven’t heard back from you in a while, so I’m going to close this issue. If you can provide more feedback, feel free to reopen it and we will take another look. Thanks!
