### ISSUE TITLE
Layout Shift on Cart/Checkout with Popup Maker active

### ISSUE THREAD

**Issue by Pairfum-London** [woocommerce/woocommerce-gutenberg-products-block#4482]
## Describe the bug
We find that the page layout shifts when a pop-up is being triggered via Pop-up maker:
https://en-gb.wordpress.org/plugins/popup-maker/

## To reproduce
You can see this behaviour on our staging site:
https://staging.pairfum.com/cart/
https://staging.pairfum.com/checkout/

The popup will appear after about 15 seconds.

## Expected behavior
The page layout should not shift, i.e. it should stay stable.

## Screenshots
Please refer to the staging site.

### WordPress Environment ###
`
### WordPress Environment ###

WordPress address (URL): https://staging.pairfum.com
Site address (URL): https://staging.pairfum.com
WC Version: 5.5.1
REST API Version: ✔ 5.5.1
WC Blocks Version: ✔ 5.5.1
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.4.1
Log Directory Writable: ✔
WP Version: 5.7.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.19
PHP Post Max Size: 500 MB
PHP Time Limit: 300
PHP Max Input Vars: 20000
cURL Version: 7.77.0
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.38-MariaDB-log-cll-lve
Max Upload Size: 500 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.5.1
WC Database Prefix: pobi_
Total Database Size: 438.75MB
Database Data Size: 376.49MB
Database Index Size: 62.26MB
pobi_woocommerce_sessions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
pobi_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pobi_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pobi_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
pobi_woocommerce_order_items: Data: 1.52MB + Index: 0.28MB + Engine InnoDB
pobi_woocommerce_order_itemmeta: Data: 6.52MB + Index: 7.03MB + Engine InnoDB
pobi_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
pobi_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
pobi_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pobi_woocommerce_shipping_zone_locations: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
pobi_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pobi_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pobi_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pobi_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pobi_actionscheduler_actions: Data: 0.19MB + Index: 0.23MB + Engine InnoDB
pobi_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pobi_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pobi_actionscheduler_logs: Data: 0.14MB + Index: 0.14MB + Engine InnoDB
pobi_ahrefs_seo_content: Data: 1.08MB + Index: 0.11MB + Engine MyISAM
pobi_ahrefs_seo_snapshots: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
pobi_b2s_posts: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
pobi_b2s_posts_drafts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pobi_b2s_posts_favorites: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pobi_b2s_posts_network_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pobi_b2s_posts_sched_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pobi_b2s_post_sched_settings: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pobi_b2s_user: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
pobi_b2s_user_contact: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pobi_b2s_user_network_settings: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pobi_bwf_contact: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
pobi_bwf_contact_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
pobi_bwf_wc_customers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
pobi_cartflows_ca_cart_abandonment: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
pobi_cartflows_ca_email_history: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
pobi_cartflows_ca_email_templates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
pobi_cartflows_ca_email_templates_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
pobi_cartflows_visits: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
pobi_cartflows_visits_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
pobi_cli_cookie_scan: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
pobi_cli_cookie_scan_categories: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
pobi_cli_cookie_scan_cookies: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
pobi_cli_cookie_scan_url: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
pobi_cli_scripts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
pobi_cocart_carts: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
pobi_commentmeta: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
pobi_comments: Data: 3.52MB + Index: 3.30MB + Engine InnoDB
pobi_ff_scheduled_actions: Data: 0.10MB + Index: 0.00MB + Engine MyISAM
pobi_fluentform_draft_submissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
pobi_fluentform_entry_details: Data: 0.05MB + Index: 0.01MB + Engine MyISAM
pobi_fluentform_forms: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
pobi_fluentform_form_analytics: Data: 2.67MB + Index: 0.32MB + Engine MyISAM
pobi_fluentform_form_meta: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
pobi_fluentform_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
pobi_fluentform_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
pobi_fluentform_submissions: Data: 0.07MB + Index: 0.00MB + Engine MyISAM
pobi_fluentform_submission_meta: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
pobi_fluentform_subscriptions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
pobi_fluentform_transactions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
pobi_hplugin_root: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pobi_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pobi_litespeed_avatar: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pobi_litespeed_cssjs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pobi_litespeed_img_optm: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pobi_nextend2_image_storage: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
pobi_nextend2_section_storage: Data: 0.31MB + Index: 0.01MB + Engine MyISAM
pobi_nextend2_smartslider3_generators: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
pobi_nextend2_smartslider3_sliders: Data: 0.05MB + Index: 0.00MB + Engine MyISAM
pobi_nextend2_smartslider3_sliders_xref: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
pobi_nextend2_smartslider3_slides: Data: 0.15MB + Index: 0.01MB + Engine MyISAM
pobi_nxs_log: Data: 2.02MB + Index: 0.00MB + Engine InnoDB
pobi_nxs_query: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pobi_options: Data: 13.50MB + Index: 1.64MB + Engine InnoDB
pobi_postmeta: Data: 286.59MB + Index: 28.11MB + Engine InnoDB
pobi_posts: Data: 20.52MB + Index: 3.77MB + Engine InnoDB
pobi_rcb_asset_seo_redirect: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
pobi_rcb_consent: Data: 8.78MB + Index: 0.21MB + Engine MyISAM
pobi_rcb_presets: Data: 0.04MB + Index: 0.02MB + Engine MyISAM
pobi_rcb_revision: Data: 1.25MB + Index: 0.00MB + Engine MyISAM
pobi_rcb_revision_independent: Data: 0.17MB + Index: 0.00MB + Engine MyISAM
pobi_rcb_stats: Data: 0.05MB + Index: 0.04MB + Engine MyISAM
pobi_rcb_tcf_features: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
pobi_rcb_tcf_purposes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
pobi_rcb_tcf_special_features: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
pobi_rcb_tcf_special_purposes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
pobi_rcb_tcf_stacks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
pobi_rcb_tcf_vendors: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
pobi_realmedialibrary: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
pobi_realmedialibrary_debug: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pobi_realmedialibrary_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pobi_realmedialibrary_posts: Data: 0.30MB + Index: 0.36MB + Engine InnoDB
pobi_realmedialibrary_resetnames: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
pobi_realmedialibrary_tmp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pobi_termmeta: Data: 0.13MB + Index: 0.19MB + Engine InnoDB
pobi_terms: Data: 0.13MB + Index: 0.16MB + Engine InnoDB
pobi_term_relationships: Data: 1.52MB + Index: 1.52MB + Engine InnoDB
pobi_term_taxonomy: Data: 0.16MB + Index: 0.16MB + Engine InnoDB
pobi_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pobi_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pobi_usermeta: Data: 3.52MB + Index: 4.03MB + Engine InnoDB
pobi_users: Data: 0.17MB + Index: 0.17MB + Engine InnoDB
pobi_wacv_abandoned_cart_record: Data: 0.36MB + Index: 0.00MB + Engine InnoDB
pobi_wacv_cart_log: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
pobi_wacv_email_history: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
pobi_wacv_guest_info_record: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
pobi_wcj_track_users: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pobi_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pobi_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pobi_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pobi_wc_customer_lookup: Data: 0.28MB + Index: 0.22MB + Engine InnoDB
pobi_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pobi_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pobi_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
pobi_wc_order_product_lookup: Data: 1.52MB + Index: 0.72MB + Engine InnoDB
pobi_wc_order_stats: Data: 0.36MB + Index: 0.36MB + Engine InnoDB
pobi_wc_order_tax_lookup: Data: 0.23MB + Index: 0.25MB + Engine InnoDB
pobi_wc_product_meta_lookup: Data: 0.11MB + Index: 0.19MB + Engine InnoDB
pobi_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pobi_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pobi_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pobi_wfacp_stats: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
pobi_wfco_report_views: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
pobi_woocommerce_gpf_google_taxonomy: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
pobi_woocommerce_termmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
pobi_wow_coder: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
pobi_wpae_blocked_ip: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
pobi_wpae_spammer_ip: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
pobi_wpae_spam_data: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
pobi_wpmelon_advbedit_temp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
pobi_wp_phpmyadmin_extension__errors_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
pobi_yoast_indexable: Data: 7.52MB + Index: 4.17MB + Engine InnoDB
pobi_yoast_indexable_hierarchy: Data: 0.14MB + Index: 0.20MB + Engine InnoDB
pobi_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
pobi_yoast_primary_term: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
pobi_yoast_seo_links: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
pobi_yoast_seo_meta: Data: 1.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 6683
braintree_donation: 1
braintree_log: 3
cartflows_flow: 4
cartflows_step: 12
cfw_order_bumps: 1
cookielawinfo: 27
customize_changeset: 16
custom_css: 1
export_template: 4
feedback: 15
fl-builder-template: 21
foogallery: 124
global_product_addon: 2
gp_elements: 8
hollerbox: 2
imgt_log: 1
mailpoet_page: 1
megamenu: 3
ml-slide: 3
ml-slider: 1
nav_menu_item: 189
news: 1
nxs_filter: 6
oembed_cache: 63
options: 4
page: 125
popup: 3
popup_theme: 9
post: 412
postman_sent_mail: 1
product: 89
product_variation: 606
pys_event: 9
rcb-blocker: 6
rcb-cookie: 19
revision: 587
rp4wp_link: 441
scheduled_export: 4
sfbap1_social_feed: 2
shop_coupon: 18
shop_order: 3004
shop_order_refund: 66
soliloquy: 1
wacv_email_template: 7
wfacp_checkout: 1
wpuf_contact_form: 1
wpuf_input: 3
wp_email_images: 1
wsinsta_social_feed: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (57) ###

FooGallery: by FooPlugins – 2.0.39
Ahrefs SEO: by Ahrefs – 0.8.4
Beaver Builder Pattern Backgrounds: by SiteSpot Dev – 1.4.3
Beaver Builder Plugin (Pro Version): by The Beaver Builder Team – 2.4.2.4
BBQ Firewall: by Jeff Starr – 20210211
Blog2Social: Social Media Auto Post & Scheduler: by Blog2Social
Adenion – 6.7.2

Booster Plus for WooCommerce: by Pluggabl LLC – 5.4.2
Classic Editor: by WordPress Contributors – 1.6
Fetchify: by Fetchify – 1.3.0
Disable Cart Fragments: by Optimocha – 2.0
Yoast Duplicate Post: by Enrico Battocchi and Team Yoast – 4.1.2
Enable Media Replace: by ShortPixel – 3.5.0
Envato Market: by Envato – 2.0.6
Fluent Forms: by Contact Form - WPManageNinja LLC – 4.1.51
Fluent Forms Pro Add On Pack: by WP Fluent Forms – 4.1.0
FooBox Image Lightbox: by FooPlugins – 2.7.16
Format Media Titles: by David Gwyer – 1.0.0
GP Premium: by Tom Usborne – 2.0.2
GPLVault Update Manager: by GPL Vault – 4.0.2
WP Armour - Honeypot Anti Spam: by Dnesscarkey – 1.8.4
Judge.me Product Reviews for WooCommerce: by Judge.me – 1.3.11
Limit log in attempts reloaded: by Limit log in attempts reloaded – 2.23.0
LiteSpeed Cache: by LiteSpeed Technologies – 3.6.4
Smart Slider 3 Pro: by Nextend – 3.5.0.9
PixelYourSite Microsoft UET (Bing): by PixelYourSite – 2.1.1
PixelYourSite Pinterest: by PixelYourSite – 3.1.3
PixelYourSite PRO: by PixelYourSite – 8.3.8
Popup Maker: by Popup Maker – 1.16.2
Product Catalog Feed Pro by PixelYourSite: by PixelYourSite – 5.1.2
Real Cookie Banner: by devowl.io – 2.5.0
Real Media Library: by devowl.io – 4.13.12
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.5
Lazy Load - Optimize Images: by WP Rocket – 2.3.4
Safe SVG: by Daryll Doyle – 1.9.9
SAHU TikTok Pixel for E-Commerce: by  – 1.0.0
Shortcode in Menus: by Gagan Deep Singh – 3.5.1
Simple Social Icons: by StudioPress – 3.0.2
NextScripts: Social Networks Auto-Poster: by NextScripts – 4.3.20
Title and Nofollow For Links: by WPKube – 1.11
Ultimate Addons for Beaver Builder - Lite: by Brainstorm Force – 1.5.2
WooCommerce Cart Abandonment Recovery: by CartFlows Inc – 1.2.13
WPC Fly Cart for WooCommerce: by WPClever – 3.0.7
WooCommerce Blocks: by Automattic – 5.5.1
Braintree For WooCommerce: by Payment Plugins
support@paymentplugins.com – 3.2.26

WPC Product Bundles for WooCommerce (Premium): by WPClever – 5.7.5
Stripe For WooCommerce: by Payment Plugins
support@paymentplugins.com – 3.3.5

WooCommerce Advanced Bulk Edit: by George Iron – 5.0.1
WooCommerce Free Gift Coupons: by Kathy Darling – 3.2.0
Booster for WooCommerce: by Pluggabl LLC – 5.4.2
WooCommerce Multi Currency Premium: by VillaTheme – 2.1.16
WooCommerce - Store Exporter Deluxe: by Visser Labs – 5.1
WooCommerce Table Rate Shipping: by Bolder Elements – 4.2.1
WooCommerce: by Automattic – 5.5.1
Yoast SEO: by Team Yoast – 16.7
WP Armour Extended - Honeypot Anti Spam: by Dinesh Karki – 1.15
WP Coder: by Wow-Company – 2.5
WPC AJAX Add to Cart for WooCommerce: by WPClever – 1.3.4

### Inactive Plugins (16) ###

AeroCheckout: Custom WooCommerce Checkout Pages: by WooFunnels – 2.8.0
Angell EYE Updater: by Angell EYE – 2.0.16
Beaver Builder Plugin (Lite Version): by The Beaver Builder Team – 2.4.2.4
CartFlows: by CartFlows Inc – 1.6.15
CartFlows Pro: by CartFlows Inc – 1.6.13
CheckoutWC: by Objectiv – 5.3.0
Fast Checkout for WooCommerce: by  – 1.1.0
Flying Pages by WP Speed Matters: by Gijo Varghese – 2.4.2
NextScripts: SNAP Pro Upgrade Helper: by NextScripts – 1.5.10
PayPal for WooCommerce: by Angell EYE – 2.5.11
Perfect Checkout: by Perfect Checkout – 1.1.0
ShortPixel Adaptive Images: by ShortPixel – 2.3.3
WooCommerce Abandoned Cart Recovery Premium: by VillaTheme – 1.0.6.2
WooCommerce Amazon Pay: by WooCommerce – 2.0.3
Wordpress Pinterest Automatic: by ValvePress – 4.14.3
WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.1.11

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: GBP (£)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
woosb (woosb)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: ❌ Page not set
Basket: #9 - /cart/
Checkout: #10 - /checkout/
My account: #11 - /my-account/
Terms and conditions: #3762 - /terms-conditions/

### Theme ###

Name: GeneratePress Child
Version: 0.1
Author URL: https://tomusborne.com
Child Theme: ✔
Parent Theme Name: GeneratePress
Parent Theme Version: 3.0.4
Parent Theme Author URL: https://tomusborne.com
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 526
Oldest: 2021-06-19 19:13:14 +0100
Newest: 2021-07-20 16:41:02 +0100

Pending: 3
Oldest: 2021-07-20 18:35:02 +0100
Newest: 2021-07-23 12:00:03 +0100

### Templates ###

Extended logging mode for Store Exporter Deluxe: ✔Inactive Turn on Logging mode
Debugging mode for Store Exporter Deluxe: ✔Inactive Turn on Debugging mode
Scheduled Export to FTP: ✔
Scheduled Export to SFTP: ❌ The required SFTP functions are not available; ssh2_connect()
ssh2_auth_password()
ssh2_sftp(). Contact your hosting provider.

### Status report information ###

Generated at: 2021-07-20 16:41:04 +01:00
`
### Desktop (please complete the following information):
* OS: Windows
* Browser: chrome
* Version:

**Comment by mikejolley** [comment]
Is this resolved on the staging site? I didn't see any shift on the cart page using Edge/Chrome. I'd suspect it would be something to do with the overlay the popup plugin adds to the page.

**Comment by Pairfum-London** [comment]
Dear @mikejolley 

Many thanks for your reply.

We resolved it by de-activating the overlay that the popup sets.

In other words, the issue is still there but manageable.

Many thanks for looking into this.

Kind regards,

Pairfum London

**Comment by nerrad** [comment]
Thanks for responding! I'm going to close this issue because there's nothing actionable on our side.
