### ISSUE TITLE
Combined Cart & Checkout Page

### ISSUE THREAD

**Issue by Pairfum-London** [woocommerce/woocommerce-gutenberg-products-block#4483]
## Feature Request
We find WooCommerce Blocks for the Cart and Checkout page a fantastic improvement on the current pages. In particular, we really like the Express Checkout section.

To simplify and speed-up the checkout experience further, we believe a combined cart and checkout page would be very beneficial.

## Describe the solution you'd like
Adding the 'Your basket' section from the 'cart' page to the 'order summary' section on the 'checkout' page.
- only display the product title of each item in the order, i.e. not too much detail.
- a click action that reveals the product details with a quantity change button and the ability to 'remove item'

We also request the same Shipping Cost calculator on the 'checkout' page, as can be seen on the cart page.

## Describe alternatives you've considered
We have looked at the following alternatives / competitors
- Shopify checkout experience
- these plugins: Cartflows, Launchflows, WooFunnels
- the services: Checkout-X, Perfect Checkout

**Comment by Pairfum-London** [comment]
Dear @mikejolley many thanks for your request to add a 'needs feedback' request. Would you mind expanding on what additional information you would like us to provide? Kind regards, Pairfum London

**Comment by mikejolley** [comment]
@Pairfum-London This needs feedback from the team too. cc @nerrad 

> We also request the same Shipping Cost calculator on the 'checkout' page, as can be seen on the cart page.

Since this requires the address, why does it need to be added a separate thing vs inline quotes after inputting shipping details?

**Comment by Pairfum-London** [comment]
Dear @mikejolley and @nerrad 

A good question from Mike and I agree that a result that populates automatically after inputting the shipping details is enough.

Kind regards,

Pairfum London

**Comment by nerrad** [comment]
Hi @Pairfum-London 👋🏻 ,

Thanks for taking the time to leave your feedback and suggested improvements for the cart and checkout block (especially around having an option to combine into one view). Much appreciated!

We make note of all feedback we receive and we also close issues with the feedback as active issues are used for bugs or feature/enhancements. It does not mean that we'll forget about your suggestions. Periodically, we go through all the issues containing feedback to evaluate which ideas we want to incorporate into future iterations of the blocks.  Keep in mind closed  issues can also still be commented on – which is useful if you have further insights or more information around the suggestions made here.

Thanks again!
