### ISSUE TITLE
Payfast Does not Load as payment method

### ISSUE THREAD

**Issue by salesneodo** [woocommerce/woocommerce-gutenberg-products-block#4489]
I have the payfast plugin installed on the exact same version and on the normal Woocommerce checkout page the Payfast options shows. But not on the Woocommerce blocks, can you please asssist as the demo show and says you can use payfast 

https://www.neodo-inc.com/checkout/

**Comment by frontdevde** [comment]
For support with a specific site could you please reach out to support in the related support forum?
https://wordpress.org/support/plugin/woo-gutenberg-products-block/
Thank you!
