### ISSUE TITLE
Automate bumping minimum required versions for WooCommerce Blocks

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#4511]
With the work done in #4484, this plugin now has a L0 requirement for WordPress and WooCommerce version support. Currently, we need to manually update various places in the codebase whenever we bump minimum version support.

- `readme.txt`
- `woocommerce-gutenberg-products-block.php`

One challenge with automating this that will need to be considered is that we don't need to do this for every release of WooCommerce blocks and updates are currently only (manually) triggered when at the time of releasing blocks, there is a later version of WordPress or WooCommerce available than what is defined in the files.

**Comment by mikejolley** [comment]
Whilst we're looking at this, some other things we could automate in the release process (after which we can update the instructions):

1. Add a pre-release check to confirm `hub API user` works, or render instructions in the command line. Run on pre:deploy.
2. Create blank testing instructions .md file for the release and update index automatically *or* grab testing instructions from PRs automatically and pre-fill
3. Add version + date to the generated changelog snippet in release PR to cut out some manual steps
4. Create template for release post in release PR to update/copy/paste. This replaces the communication section.

**Comment by mikejolley** [comment]
Closing due to pca54o-6Dz-p2
