### ISSUE TITLE
[Styles] Change proceed to cart text and text color

### ISSUE THREAD

**Issue by angelrss3** [woocommerce/woocommerce-gutenberg-products-block#4526]
It works and looks great.

Change proceed to cart text and text color (My website is not in English and the translating plugins for some reason don't translate specifically this button). 

Also would be nice to select the typography instead of going with the theme one. 

Some visual customization further than dark mode would be appreciated.

**Comment by mikejolley** [comment]
Thanks for the feedback, I've moved this request to the backlog for consideration.
