### ISSUE TITLE
Investigate if we can remove `wp-block-editor` from the All Products block dependencies

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#4543]
The All Products block has `wp-block-editor` as a dependency. This issue is about investigating if it can be removed and eventually removing it if possible.

I could track down the dependency being imported in these two files:

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/19d29d11fea059650da48cbca4f35275e88324d6/assets/js/atomic/blocks/product-elements/price/block.js#L12

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/19d29d11fea059650da48cbca4f35275e88324d6/assets/js/atomic/blocks/product-elements/title/block.js#L10

**Comment by Aljullu** [comment]
I think we would be able to remove those imports if we migrated Product Price and Product Title blocks to use global styles.

**Comment by Aljullu** [comment]
Reopening because `all-products-frontend.asset.php` still lists `wp-block-editor` as a dependency.

**Comment by gigitux** [comment]
This bug had been resolved in this PR: https://github.com/woocommerce/woocommerce-blocks/pull/9251. The solution was to https://github.com/woocommerce/woocommerce-blocks/issues/8071.
