### ISSUE TITLE
Add Tracking

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-gutenberg-products-block#455]
**Is your feature request related to a problem? Please describe.**

To keep informed on which blocks are used most frequently by shop owners, we should tie into the JS tracking that is being added in 3.6 ( [PR](https://github.com/woocommerce/woocommerce/pull/22746) ) and call `window.wcTracks.recordEvent()` when a block is added. 

**Describe the solution you'd like**

When a block is first added - or should it be when "Done" is clicked the first time ideally we could record a track event for `block_add` with a prop of `blockType` which sends the block slug.

**Additional context**

I'm not totally certain if there is an easy-ish way to do this on a block or if we need to have an attribute set that denotes a track has been recorded for a block once already. Any thoughts @ryelle?

**Comment by warrendholmes** [comment]
We'll we be able to track when a block is rendered too?

**Comment by psealock** [comment]
An event on "Done" would be a good opportunity to fire a `block_edit` event. An event for the first initial usage is harder without firing directly from Gutenberg's block selector.

@warrendholmes is a `block_edit` event sufficient to gather usage data? 

>Will we be able to track when a block is rendered too?

Which rendering? The `save` functionality as seen in the editor or publishing of the post? I don't know if its possible to know if a shorthand was created from a block or not on publishing of the post.

**Comment by timmyc** [comment]
@psealock I chatted with Warren about this earlier and I think he was interested in tracking front-end renders, so a `c2` category event. I think we both agreed to not pursue that one quite yet.

As for recording the "add"ing of a block - WPCOM hooks into the publish flow via PHP, which we could do also in Woo core instead of trying to figure out a way to add an event only once in the block js logic.

**Comment by ryelle** [comment]
The above isn't totally clear to me, @psealock are you working on this issue? Or are there some docs somewhere I can see to figure out how to use the wc tracks system?

**Comment by timmyc** [comment]
I think he might be - based off his status update yesterday:

https://a8c.slack.com/archives/CBKK5KM41/p1551739906016800 - and it appears this will get implemented in woo core so guessing we could probably close this issue out.

**Comment by psealock** [comment]
Yes, correct on all counts. I'm working on this one, its going into Woo Core, and we can close this out out and track progress elsewhere.
