### ISSUE TITLE
Checkout i2: Blocks missing icons

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#4573]
Just tracking which icons are currently missing in the i2 prototype. 

**Checkout Fields Block** 

This is a wrapper Block for the left column.

![Screenshot 2021-08-13 at 13.56.29.png](https://images.zenhubusercontent.com/546232087c6ccc6277a5e9a7/43db57e0-dcad-45a3-827e-abf65b6bc41b)

**Order summary**

The Block that holds totals.

![Screenshot 2021-08-13 at 13.56.53.png](https://images.zenhubusercontent.com/546232087c6ccc6277a5e9a7/ce43fa97-9358-40ce-9740-a3e3f3241497)

**Checkout totals block**

This is a wrapper Block for the right column.

![Screenshot 2021-08-13 at 13.57.48.png](https://images.zenhubusercontent.com/546232087c6ccc6277a5e9a7/87cc62e2-1117-45e6-8dcd-4d638caaac01)

**Checkout actions**

Holds the place order button.

![Screenshot 2021-08-13 at 13.59.44.png](https://images.zenhubusercontent.com/546232087c6ccc6277a5e9a7/f49f360f-2ecd-4838-861e-5b1416b39f2e)

—

cc @vivialice

If we had a generic icon for "column" we could apply that to the checkout totals and checkout fields wrapper blocks? We could use the one in the Gutenberg columns Block:

![Screenshot 2021-08-13 at 13.59.07.png](https://images.zenhubusercontent.com/546232087c6ccc6277a5e9a7/e493324d-1112-47c0-acd5-f5ce915eaa85)

**Comment by vivialice** [comment]
Hey @mikejolley, sorry for the delay in following up on this. I tried a few options a while back and got feedback from the team, including another column style. It doesn't make sense to use a slightly different column icon though, so let's go ahead with Gutenberg's.
