### ISSUE TITLE
Checkout i2: Consider mobile styling

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#4576]
The mobile view has lots of wasted space, and elements like form steps do not change much, for example, they still have the left border which makes the form fields narrow. This is the editor in mobile preview mode:

![Screenshot 2021-08-13 at 15.30.03.png](https://images.zenhubusercontent.com/546232087c6ccc6277a5e9a7/240e1d20-90b1-4c98-a7c3-d3f0c21d6822)

Is the mobile display something we want to think about @vivialice? What about the order of elements (express payment, order summary, fields), is that something we should think about?

At the very least, we should remove the large space below order summary, before the form fields. I'm not sure what is causing that.

**Comment by vivialice** [comment]
Hey @mikejolley! Yes I want to take a look at the layout on mobile because the elements feel really detatched. For now, I agree we should decrease that extra spacing between the stacked columns and remove that extra margin to the left of the form. I will look at this soon and share some suggestions.

**Comment by mikejolley** [comment]
I'm moving this to sprint 2 awaiting feedback. Thanks.

**Comment by nerrad** [comment]
I chatted with Vivien and she clarified that this:

> For now, I agree we should decrease that extra spacing between the stacked columns and remove that extra margin to the left of the form

...is her suggested approach for immediately resolving this issue. In the meantime it's on her list to think through and offer some further suggestions to iterate on in the future.
