### ISSUE TITLE
Uncaught TypeError: Cannot read property 'mark' of undefined

### ISSUE THREAD

**Issue by dumitrub** [woocommerce/woocommerce-gutenberg-products-block#4586]
## Describe the bug
When going to the Shopping Cart as a visitor (incognito mode), 2 JS errors are displayed in the console, while the shopping cart contents is left "unpopulated". See attached screenshots.

It is important to note that I have these incompatible plugins installed, but they worked perfectly fine for a few months. They stopped working after 5.8 update.
WooCommerce Cart Add-Ons
WooCommerce Checkout Add-Ons

## To reproduce
Add stuff to the shopping cart as a visitor and go to the /cart/ page.

## Expected behavior
Things to work.

## Screenshots
![warenkorb-bug](https://user-images.githubusercontent.com/24874953/129596094-c14f9112-3134-4ba8-ad00-51702d0474ca.png)
![warenkorb-bug-console](https://user-images.githubusercontent.com/24874953/129596099-26af58bb-ce1f-4c4b-9ef6-f78484c46e00.png)

### WordPress (please complete the following information):
* Core version: [e.g. 5.8]
* WooCommerce version: [5.5.2]
* WooCommerce Blocks version: [5.6.0]
* Site language: German
* Any other plugins installed:
* WooCommerce Cart Add-Ons: [1.5.2.1]
* WooCommerce Checkout Add-Ons: [2.2.3]

### Desktop (please complete the following information):
* OS: Windows
* Browser Chrome
* Version 92.0.4515.131

**Comment by senadir** [comment]
This issue seems to be related to caching, are you running any sort of optimization plugin? SiteGround optimize plugin or something like that?

**Comment by dumitrub** [comment]
> This issue seems to be related to caching, are you running any sort of optimization plugin? SiteGround optimize plugin or something like that?

Thanks for getting back to me.
Yes, I actually use SG Optimizer, SiteGround's official caching plugin for WP. 
But the JS files are not combined or minified, so it did not occur to me that caching could be an issue.
Anything specific that I should do about it?

Thank you for your help and input.

**Comment by senadir** [comment]
We know that it doesn't play very well with `@wordpress` scripts in the frontend, nothing we can do on our side really. You can try to disable it and see if the issue is fixed. Making sure to disable minification, or resetting the plugin.

You can see this previous issue about it
https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3606

**Comment by dumitrub** [comment]
Thank you for the link to that issue.
Looks like it's the same bug. Odd that it hasn't been fixed or addressed, considering that caching is quite important :)
I'll be closing this thread then.
Thank you again :)

**Comment by senadir** [comment]
You can see that a couple of people commenting around fixing in that thread (at the end) not sure if applicable to your case.
