### ISSUE TITLE
Sort Select style broken on editor

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#4596]
When you add `All Reviews` or any other sortable block in the editor, you will see that the select arrow is repeated in the component. This only happens in the editor. I tested with Storefront and TwentyTwenty.
![image](https://user-images.githubusercontent.com/6165348/129856224-5f34f66c-614f-4e5c-aaec-34b4edbcaf2e.png)

**Comment by Amanporwal510** [comment]
can i solve this issue??

**Comment by senadir** [comment]
Absolutely @Amanporwal510, go ahead.

**Comment by nielslange** [comment]
> can i solve this issue??

Hello @Amanporwal510 👋 I was wondering if you have started working on this issue.

**Comment by opr** [comment]
Also seeing this on the All products block when testing 5.8.0 
![image](https://user-images.githubusercontent.com/5656702/131530723-c64dd554-cee1-4f1b-8edb-ed6233e66576.png)

**Comment by opr** [comment]
This only happens when Gutenberg is active and appears to only affect disabled selects.

**Comment by dinhtungdu** [comment]
This is a bug of Gutenberg, I created [an issue](https://github.com/WordPress/gutenberg/issues/35133) and [a PR](https://github.com/WordPress/gutenberg/pull/35135) in https://github.com/WordPress/gutenberg to fix it.

**Comment by dinhtungdu** [comment]
Closing this one because the issue was fixed in Gutenberg. See https://github.com/WordPress/gutenberg/pull/35135.
