### ISSUE TITLE
Mini Cart block: open drawer when a product is added to the Cart via a page refresh

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#4599]
We need to detect when the page is loaded after a product was added to the Cart (ie: from the Product page or via the `/?add_to_cart=17` URL parameter) and then render the Mini Cart drawer already open when the page loads.

**Comment by vivialice** [comment]
After reviewing this, for now, I recommend leaving the current add-to-cart behaviour as is (green banner and page reload) until we can fix the page reload. The cart contents counter will still update as expected. 

It is not ideal UX so I will soon look at a recommend for action feedback across this user journey in all scenarios and see if we can prioritise it in core at some point.
