### ISSUE TITLE
Payment Methods not supported

### ISSUE THREAD

**Issue by Andrewkow** [woocommerce/woocommerce-gutenberg-products-block#4611]
## Describe the bug
I added a new payment method but it's not displayed on the checkout page. However, it works on the default [woocommerce_checkout]. The payment gateway is HitPay, a new payment gateway provider based in Singapore.

### WordPress (please complete the following information):
* Core version: 5.8
* WooCommerce version: 5.6
* WooCommerce Blocks version: 5.7.0
* Site language: Eng
* Any other plugins installed: Many

**Comment by ralucaStan** [comment]
Hi there @Andrewkow  👋
 
Thanks for taking the time to make us aware that HitPay isn't working with the Checkout and Cart blocks. These blocks are still in early access (via the feature plugin) and it's expected that some existing Woo Extensions that integrate with the current checkout flow in WooCommerce core will not work with the blocks.
 
Currently it's up to payment method extension developers to add support for the new checkout flow offered via the cart and checkout blocks. We have some [documentation on that here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/extensibility/payment-method-integration.md) and you can also point them to [this post](https://developer.woocommerce.com/2021/03/15/integrating-your-payment-method-with-cart-and-checkout-blocks/).
 
Your best course of action right now if you are using a payment method that isn't working with the blocks is to notify the developer of the extension and ask if they can add support.
 
Until then you can keep on top of the [status of the Cart & Checkout Blocks in this documentation](https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/).
