### ISSUE TITLE
Update the PR template

### ISSUE THREAD

**Issue by ralucaStan** [woocommerce/woocommerce-gutenberg-products-block#4613]
Every new PR's description is filled by default with [a template](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/.github/pull_request_template.md). We need to review and update it:

- review and decide which sections should be changed
- add checks from the release template as discussed here: pca54o-20i-p2#comment-2402
- add instructions, as comments, about adding the appropriate release related labels
- options: add instructions/section for code changes overview

**Comment by nielslange** [comment]
@ralucaStan: Earlier today, I had a chat with @opr in which we noticed that the [PR template](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/.github/pull_request_template.md) lists the docs for feature flags and experimental interfaces under the accessibility section. In addition, a general section if the PR requires a change of the docs is missing.

We were thinking about creating a new section for docs with the two items general docs change and feature flags and experimental interfaces. Do you think it's a good idea adding these changes to your issue description?

**Comment by Aljullu** [comment]
Heads-up that we would like to make one more change to the PR template: adding the environment affected by the changes (see https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4641). Thanks @ralucaStan for pointing me out to this issue.

**Comment by Aljullu** [comment]
@ralucaStan do you think this has been fixed in #6293?

**Comment by ralucaStan** [comment]
Yes, I'm closing the ticket
