### ISSUE TITLE
Checkout Block: Add the country code to the phone input

### ISSUE THREAD

**Issue by msroky** [woocommerce/woocommerce-gutenberg-products-block#4614]
It would be of great benefit to customers if the phone field contained the country code prefix. 

Here is one great solution that would be good to embed in the WC Block -> https://stackoverflow.com/questions/57765343/how-to-display-country-phone-code-in-wordpress

**Comment by nerrad** [comment]
Hi @msroky,

We're definitely open to receiving feedback on potential new features for the checkout flow - however in considering any new feature it's important to make sure we're solving the right problems for _most_ users (users being either merchants or shoppers) and not introducing more problems for others.

So with that in mind, you mentioned this:

> It would be of great benefit to customers if the phone field contained the country code prefix.

Who are the "customers" you are referring to in this statement, and what is the benefit? What problem(s) does having the country code prefix solve

**Comment by senadir** [comment]
We considered adding this when we initially built Checkout block but decided not to. There’s little research into the value added by having masking, country flag, and country selector in Checkout, while the impact they bring is very significant, see [library 1](https://bundlephobia.com/package/react-phone-number-input@3.1.27) and [library 2](https://bundlephobia.com/package/react-phone-input-2@2.14.0), adding between 18kb to 50kb of mified+gzipped size. This is a 20%-50% increase in bundle size for Checkout, which would result in an increased loading time and worse conversion rate for a shop.

Adding country code is probably less impactful than masks and images, but still something that requires development time and so we would really appreciate to see the value it brings (even theoretical) before diving into it.

**Comment by nerrad** [comment]
We're still interested in hearing more details around what problems would be solved by adding country code to the phone input (or the use-cases requiring it) but since there hasn't been any response in a while I'm going to go ahead and close this issue.

Comments can still be added and we can use any additional info to consider re-opening and adding to our backlog.

**Comment by msroky** [comment]
I totally forgot to answer this topic, sorry.

I had a problem here because most customers don't use their country code, and some of them don't even use zero.

This is a problem for me when I fill their order on another page, or use one of the plugins to automatically fill orders, I have to manually search for their area code on google.

Wordpress order customer
![Capture333](https://user-images.githubusercontent.com/12650820/142462329-c66b7111-fec9-48f1-9599-f94fce840040.PNG)

The order I am fulfilling on another page of my supplier
![Captur22](https://user-images.githubusercontent.com/12650820/142462598-9ebf4788-0a75-4cb0-94ac-9a0f8ade65f5.PNG)
