### ISSUE TITLE
Same fields for all countries on checkout page

### ISSUE THREAD

**Issue by msroky** [woocommerce/woocommerce-gutenberg-products-block#4615]
The woocommerce payment form changes depending on the selected country, so some countries have a country field and some don't, I want the form to look the same for all countries and show the same fields. So I'm wondering how I'm going to do it?

**Comment by ralucaStan** [comment]
Hi there @msroky,
thank you for reaching it. It is not clear to me if you are using the default WooCommerce checkout or the Checkout block, so I will address both cases.

By default, WooCommerce enables/disables fields based on the user’s location.

If you are using the default WC checkout, it is possible [to customize the fields](https://docs.woocommerce.com/document/tutorial-customising-checkout-fields-using-actions-and-filters/) but I strongly recommend against it, as WC ensures a correct checkout based on the customer's location.
If you have any issues with a certain country and its field configuration I encourage you to [open an issue](https://github.com/woocommerce/woocommerce/issues/new/choose) on the WooCommerce repository.

If you are using the Checkout Block, it uses WC's localization logic when it comes to checkout fields. Changing the displayed fields is not currently possible, but we are currently investigating it for future development.

**Comment by msroky** [comment]
Thank you, I would not want the fields to be displayed based on location, I want one form for all locations. 
I use the Checkout block and that’s why I asked this question here.
