### ISSUE TITLE
Cart page displays "OR" text

### ISSUE THREAD

**Issue by msroky** [woocommerce/woocommerce-gutenberg-products-block#4619]
I have noticed that when a user reaches the cart page to be loaded with “OR” as shown in the image below

![Capture2](https://user-images.githubusercontent.com/12650820/130477364-66754376-ede5-4261-95a8-46b9a17f79e5.PNG)

Please resolve this as soon as possible as this confuses users when buying and creates uncertainty for the customer.

**The user used:**
Microsoft Edge 92.0.902.78
Windows 8
Descktop PC 1920x1080

**Comment by ralucaStan** [comment]
Hi @msroky,
I'm sorry to hear you are having problems with the Cart block.

The "OR" you are seeing comes from the Express payment button that apparently you don't see. If an Express payment method is not available that "OR" won't be visible, please look at what I see:

| With EP | Without EP |
|---|---|
| <img width="268" alt="Screenshot 2021-08-24 at 10 38 39" src="https://user-images.githubusercontent.com/1628454/130586135-c8bacaf9-3269-496d-b43e-e9ad2b599300.png"> | <img width="259" alt="Screenshot 2021-08-24 at 10 38 52" src="https://user-images.githubusercontent.com/1628454/130586167-a7e11e77-e43f-4761-9a84-511762bd8816.png"> |

So we need to understand why that button does not appear:
- what browser are you using? Do you have an Express method set up?
- does the button appear on the Checkout block?
- do you see any errors in the console?
- did you try testing this with other extensions disabled?

**Comment by msroky** [comment]
I tried testing with a few of my computers, it seems like everything is fine.

But when I look at users through hotjar, I see that they are shown "OR" text, I don't know why.

**Comment by msroky** [comment]
And yes, I use Stripe and Paypal as a payment method.

**Comment by frontdevde** [comment]
Thanks for reporting this issue, @msroky! We have other confirmed instances of this issue occurring. I'm thus closing this issue in favor of the related issue https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4653. We'll track progress towards resolving this issue there.
