### ISSUE TITLE
Woo Product Categories List not visually differentiating between Level 3 and Level 4 categories 

### ISSUE THREAD

**Issue by inaikem** [woocommerce/woocommerce-gutenberg-products-block#4625]
## Describe the bug
Category hierarchy is clear between all levels except Level 3 and Level 4. 

Level 4 categories appear like Level 3 as shown:

![wc-blocks-dropbown-safari-14 1](https://user-images.githubusercontent.com/66711744/130552812-cd7dc6b9-e194-45ab-92fb-5f306202daa2.png)
&nbsp;
## To reproduce

1. Create 4 WooCommerce product categories, each one nested under the previous one created, like follows:
    - Level 1
      - Level 2
        - Level 3
          - Level 4
2. Add a product to the last category
3. To a page, add the block Product Categories List
4. Under the block settings > List settings > Display style, pick "Dropdown"
5. Again under the block settings > Content, switch On "Show hierarchy"
6. Save and view page
&nbsp;
## Expected behavior
To be able to see the hierarchy and distinguish between level 3 and level 4.
&nbsp;
## Screenshots
See above.
&nbsp;
### WordPress (please complete the following information):
* Core version: 5.8
* Gutenberg version: 11.3
* WooCommerce version: 5.5.1
* WooCommerce Blocks version: Unknown (Atomic site)
* Site language: EN
&nbsp;
### Desktop (please complete the following information):
* OS: macOS 10.15.7 (19H1217)
* Browser Safari 14.1, Firefox 90.0.2 + 91.0.1, Chrome 92.0.4515.159
&nbsp;
## Additional context
User report: 4227938-zen + https://github.com/Automattic/wp-calypso/issues/55601 (@mxhassani)

**Comment by filipanoscampos** [comment]
Hi there! @opr and @ralucaStan 
The User came back as they are still seeing this issue.
The ticket: 4403013-zd-woothemes

I can confirm this, as you can see here:
![Screenshot 2021-10-25 at 14 02 03](https://user-images.githubusercontent.com/2540430/138700370-fde78567-46a7-49e3-9c78-494cbf82ba00.png)

Does the user need to take any action?
Shouldn't the update have fixed this?

Thank you!

**Comment by ralucaStan** [comment]
Hi @filipanoscampos, 👋 
Thank you for letting us know.
The fix for this should be included in Woo Blocks version 6.1.0; I've tested and things work as expected for me. 
<img width="213" alt="Screenshot 2021-10-25 at 14 29 29" src="https://user-images.githubusercontent.com/1628454/138705471-f874c3f3-cff4-4dcb-9b0c-faef95ed7cc7.png">

Unfortunately, I don't have access to see the ticket and what version the user is using, but if they update to the latest version, the bug should be fixed. 
Hope this helps.

**Comment by opr** [comment]
Hi @filipanoscampos - I've just checked and can see the user is not using the feature plugin of WooCommerce Blocks, instead their site is using only WooCommerce core 5.8. The version of WooCommerce Blocks packaged there is 5.9.1 which does not contain this fix.

When WooCommerce 5.9 is released the fix will be included in that. If the user wants to get the most up to date WooCommerce Blocks experience they can install the [WooCommerce Blocks feature plugin](https://wordpress.org/plugins/woo-gutenberg-products-block/).

**Comment by filipanoscampos** [comment]
Thank you both!
I'm done for the day but will reply to the user as soon as I can tomorrow.

**Comment by dcoleonline** [comment]
@filipanoscampos I've replied for you. :)

**Comment by filipanoscampos** [comment]
Thank you so much @dcoleonline :)
