### ISSUE TITLE
Customization Paypal Icon 

### ISSUE THREAD

**Issue by Finnbaarr** [woocommerce/woocommerce-gutenberg-products-block#4632]
## What do you think is missing from the Cart & Checkout blocks?

Is there any way to add the Paypal icon to the other payment methods on the cart page ?

**Comment by ralucaStan** [comment]
Hi there @Finnbaarr,
thank you for reaching out. 
Are you referring to adding the icon to the list from this picture? 
<img width="246" alt="Screenshot 2021-08-26 at 14 18 14" src="https://user-images.githubusercontent.com/1628454/130962389-8180c3d3-a6f8-400c-b741-f4610ca42525.png">

If so, then there is, unfortunately, no way to display the Paypal icon there. Cart and Checkout blocks are still in development and not all payment gateways have already been updated to support them. 

Currently, it's up to payment method extension developers to add support for the new checkout flow offered via the cart and checkout blocks. We have some documentation on that here and will be publicizing this more in the coming months. Your best course of action right now if you are using a payment method that isn't working with the blocks is to notify the developer of the extension and ask if they can add support.

You can keep on top of the status of the Cart & Checkout Blocks in this documentation.

Thanks!

**Comment by ralucaStan** [comment]
According to this https://github.com/woocommerce/woocommerce-paypal-payments/issues/211#issuecomment-1551145433 a new pre-release for the next PayPal Payments 2.0.5 is available [on GitHub](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.0.5-rc1) with express payment methods support in the WooCommerce blocks.
