### ISSUE TITLE
Woocommerce Checkout and Cart Block Missing Features & Incompatibility

### ISSUE THREAD

**Issue by ghost** [woocommerce/woocommerce-gutenberg-products-block#4633]
## What do you like about the Cart & Checkout blocks?
I like the whole layout and implementation of the plugin. But still, this whole thing should be available by default in Woocommerce.

## What do you think is missing from the Cart & Checkout blocks?
1) I am using the [Digits](https://codecanyon.net/item/digits-wordpress-mobile-number-signup-and-login/19801105) plugin for OTP-based login. This feature and plugin are currently not supported by the checkout block. Traditional Login and signup methods are good, but no one wants to remember passwords. OTP-based login is a much easier option for everyone.

2) If a customer wants to log in to their existing account, then the process is not very effecient. When the customer clicks on "Already have an account? Login" they are being redirected to my account or login page. And this is weird as this whole redirect process can lead to a decrease in conversions. Log in process should be done on the same checkout page without reloading or redirecting just like the default checkout page.

3) I am using [this](https://codecanyon.net/item/woocommerce-custom-fields/11332742?s_rank=5) plugin for WooCommerce Custom Fields.
With this plugin enabled the text "Product Details" is not properly Displayed. You can see this in this [image](https://pasteboard.co/KhCIl3M.png)

4) Indian Payment Gateways are not supported. I am using Razorpay Payment Gateway on my website. And When I enabled the Woocommerce checkout block the Razorpay payment option was not available on the checkout page. So, Just add support for multiple payment gateaways.

Waiting for an update that fixes all these highlighted issues.

**Comment by ralucaStan** [comment]
Hi @vlohar08,
thank you for getting in touch and for using Woo Blocks.

Regarding `points 1 & 2`, this is a really good suggestion and we already have [a ticket](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/2751) for this enhancement. 

For `point 3` I would need a link to view what goes on the page. From the looks of it, the font looks too big for that space, so changing the font style might fix your issue. **Let me know if you can provide a link.**

Regarding `point 4`, thanks for taking the time to make us aware that Razorpay Payment Gateway isn't working with the Checkout and Cart blocks. These blocks are still in early access (via the feature plugin) and it's expected that some existing Woo Extensions that integrate with the current checkout flow in WooCommerce core will not work with the blocks.
 
Currently, it's up to payment method extension developers to add support for the new checkout flow offered via the cart and checkout blocks. We have some [documentation on that here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/extensibility/payment-method-integration.md) and you can also point them to [this post](https://developer.woocommerce.com/2021/03/15/integrating-your-payment-method-with-cart-and-checkout-blocks/).
 
Your best course of action right now if you are using a payment method that isn't working with the blocks is to notify the developer of the extension and ask if they can add support.
 
Until then you can keep on top of the [status of the Cart & Checkout Blocks in this documentation](https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/).

**Comment by ghost** [comment]
1 & 2) That's Great!

3) Please add this product to the cart and proceed to checkout.
Product Link - https://casesrocks.com/product/love-letter-mobile-phone-case/

It's trying to load the product description on checkout and that's causing the issue. I am using Elementor templates and shortcodes to display product descriptions. On clicking on Customize I am seeing this - https://pasteboard.co/KhPlkjn.png

4) I sent a request to the Razorpay Team.

**Comment by ralucaStan** [comment]
Thank you for the link @vlohar08,
it looks like Elementor is populating the Product metadata description area in the sidebar (see `.wc-block-components-product-metadata__description` element). I recommend that you reach out to them in order to get some help with your issue. 

As there is nothing actionable from my side I will go ahead and close this ticket.
