### ISSUE TITLE
Release process: generate testing instructions automatically

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#4634]
Similarly to the way the changelog is automatically generated when creating the release PR, we would like to have a tool that automatically gathers testing instructions from all PRs that are assigned to a specific milestone and creates a document with them under `/docs/testing/releases/`.

In parallel to this, we might want to update the [Pull Request template](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/.github/pull_request_template.md) to state that testing steps are now required. If a PR has no testing steps, we can consider adding a `skip-testing-steps` (similar to the current `skip-changelog`), or intentionally write `No testing needed` in the testing steps section of the PR.

**Comment by Aljullu** [comment]
Heads-up about this similar issue from WC core: 15-gh-woocommerce/platform-private.

**Comment by mikejolley** [comment]
Closing due to pca54o-6Dz-p2
