### ISSUE TITLE
Add options to display custom product attributes after product title in Gutenberg

### ISSUE THREAD

**Issue by CalumChilds** [woocommerce/woocommerce-gutenberg-products-block#4635]
**Is your feature request related to a problem? Please describe.**
Currently, I am unable to display custom product attributes in any of the WooCommerce product blocks after the product title in Gutenberg. This is the one area of the website that I am unable to display my custom product attributes on.

![2021-08-21 (2) - Copy](https://user-images.githubusercontent.com/25369857/130312782-b38fa964-4cad-474a-8f1a-121d2409a1ec.png)

**Describe the solution you'd like**

I would like to see a custom section in the settings of all blocks that allow products to be displayed that allows users to choose which product attributes they would like to be displayed and where they would like them displayed (before, after title?) Additional options to display an icon or the attribute name before the attribute's value would be ideal.

![2021-08-21 (3)](https://user-images.githubusercontent.com/25369857/130312884-858c0759-c959-483a-b1c9-77e448f1d64e.png)
(this was achieved by manually editing the page HTML in my browser)

**Describe alternatives you've considered**
I have considered looking at the code behind Gutenberg and, using a custom theme/plugin, adding a section that would allow me to add custom attributes after the product name, but this would be extremely time-consuming, especially for someone who doesn't know much about the React framework that powers Gutenberg.

**Additional context**
N/A

**Comment by juliaamosova** [comment]
Hi @Wingo5315,

Thank you for opening this enhancement request. It needs to be addressed on the side of WooCommerce Blocks which are being developed in another repository: https://github.com/woocommerce/woocommerce-gutenberg-products-block. 

I am going to move your bug report there so that the right team could take a look further.

**Comment by ralucaStan** [comment]
Hi @Wingo5315, 
Thanks for taking the time to leave your feature request. While we appreciate you sharing your idea with us, it doesn’t fit in with our current priorities for the project. This doesn’t mean what you are suggesting isn’t a good idea or doesn’t make sense – it’s just that we have limited time to work on various projects. At some point we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. In the meantime, don’t be alarmed if you don’t see any activity on this issue for a while.
