### ISSUE TITLE
Release process: automatically set next version after a release has been successful

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#4638]
This issue is about automating this step of the [release process](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/.github/release-initial-checklist.md):

> Update version on the `trunk` branch to be for the next version of the plugin and include the `dev` suffix (e.g. something like [`2.6-dev`](https://github.com/woocommerce/woocommerce-gutenberg-products-block/commit/e27f053e7be0bf7c1d376f5bdb9d9999190ce158)) for the next version.

That should happen after the release has been successfully updated to GitHub and wordpress.org.

**Comment by mikejolley** [comment]
Closing due to pca54o-6Dz-p2
