### ISSUE TITLE
Release process: automatically close milestone when starting the release and set date after a successful release

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#4639]
This issue is about automating these steps from the [release process](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/.github/release-initial-checklist.md):

> Close the milestone of the release you are going to ship. That will prevent newly approved PRs to be automatically assigned to that milestone.
> Create a milestone for the next version.

and

> Edit the GitHub milestone of the release you just shipped and add the current date as the due date (this is used to track ship date as well).

The first ones should happen when the release branch is created, while the latter should happen once the release has shipped.

**Comment by tarunvijwani** [comment]
Created a [PR](https://github.com/woocommerce/automations/pull/54) to close the current milestone and open the next milestone whenever a new release branch is created.

**Comment by tarunvijwani** [comment]
Moved the second part of the request to separate ticket: https://github.com/woocommerce/woocommerce-blocks/issues/6986

**Comment by ralucaStan** [comment]
@tarunvijwani is the first part of the ticket happening?

> Close the milestone of the release you are going to ship. That will prevent newly approved PRs to be automatically assigned to that milestone.
Create a milestone for the next version.

if so let's close this ticket and keep https://github.com/woocommerce/woocommerce-blocks/issues/6986 for the 2nd part
> Edit the GitHub milestone of the release you just shipped and add the current date as the due date (this is used to track ship date as well).

**Comment by mikejolley** [comment]
Closing due to pca54o-6Dz-p2
