### ISSUE TITLE
Release process: create blocks-starter-pack to make it easier to test in newly created sites

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#4642]
This idea was proposed by @opr (pca54o-1Fy-p2#comment-2034):

> Another part of the release I find time consuming and repetitive is setting up and configuring a JN store. I would love to explore the possibility of a “blocks starter pack” plugin or something that we can upload to JN sites. In my mind, this would: import the starter content, install and activate Storefront, set up shipping options, set up Stripe, and change the Cart and Checkout pages to use blocks.

**Comment by nielslange** [comment]
As I've already tinkered with this in the past, I've assigned this issue to me and will draft a PR.

**Comment by nielslange** [comment]
I'm done with the first draft, but noticed that it's rather hard to spin up a PR given the nature of my implementation. To spin up a WooCommerce Blocks testing environment, I decided to put WP-CLI and WC-CLI to the test. I created a custom WP-CLI command, which lives on https://github.com/nielslange/woo-test-environment.

## Steps to test my implementation

1. Head over to https://jurassic.ninja/ and spin up a testing environment.
2. Log into the testing environment and copy the SSH credentials.
3. Establish an SSH connection to the site via terminal.
4. Navigate to the WordPress folder, e.g. `~/apps/user58297096/public`.
5. Run `wp package install git@github.com:nielslange/woo-test-environment.git` to install the custom command.
6. Run `wp woo-test-environment setup` to spin up a minimal WooCommerce Blocks testing environment, or the command `wp woo-test-environment setup --version=7.3.0 --gutenberg=true --theme=storefront` to spin up a WooCommerce Blocks testing environment with WooCommerce Blocks 7.3.0, the latest version of Gutenberg and the latest version of Storefront.
7. Run `wp woo-test-environment teardown` to tear down the WooCommerce Blocks testing environment.

## Additional parameter

- The command `--version=7.3.0` allows installing any given version of WooCommerce Blocks. That way, we don't need to upload the release zip manually. 
- The command `--gutenberg=true` installs and activates the latest version of the [Gutenberg](https://wordpress.org/plugins/gutenberg/) plugin.
- The command `--theme=storefront` installs and activates the latest version of the [Storefront](https://wordpress.org/themes/storefront/) theme. This parameter allows installing any desired theme of the WordPress.org repo. For example, the parameter `--theme=astra` allows installing and activating the latest version of the [Astra](https://wordpress.org/themes/astra/) theme.

## Additional notes

### Pages

To keep the menu short, my custom command creates the following pages:

- Shop (All Products block)
- Classic Shop (Shop shortcode)
- Cart (Cart block)
- Classic Cart (Cart shortcode)
- Checkout (Checkout block)
- Classic Checkout (Checkout shortcode)
- My Account (My Account shortcode)
- Terms
- Privacy

### Posts

To test all blocks, I decided to add each block, except the filter blocks, to individual posts. I then added a widget to the sidebar that lists all posts. That way, all blocks, except the Cart & Checkout blocks, can be easily accessed.

## Screenshot

![wpcli local_shop](https://user-images.githubusercontent.com/3323310/160661110-86d5936c-2044-435f-aa70-3f27223f46fd.png)

**Comment by albarin** [comment]
Closing it since there's an existing project in https://github.com/nielslange/woo-test-environment and new issues are being created there.
