### ISSUE TITLE
PayPal Checkout Plugin not supported on the cart and checkout pages

### ISSUE THREAD

**Issue by piotrszczesniak** [woocommerce/woocommerce-gutenberg-products-block#4644]
## What do you like about the Cart & Checkout blocks?
I like the modern look. 

## What do you think is missing from the Cart & Checkout blocks?
I am using PayPal Checkout Plugin and I would want PayPal payments to be available both on cart and checkout page. As for now they don't show despite the plugin is installed.  Anyway and anytime to make it work?

**Comment by ralucaStan** [comment]
Hi there @piotrszczesniak 👋
 
Thanks for taking the time to make us aware that PayPal Checkout Plugin isn't working with the Checkout and Cart blocks. These blocks are still in early access (via the feature plugin) and it's expected that some existing Woo Extensions that integrate with the current checkout flow in WooCommerce core will not work with the blocks.
 
Currently it's up to payment method extension developers to add support for the new checkout flow offered via the cart and checkout blocks. We have some [documentation on that here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/extensibility/payment-method-integration.md) and you can also point them to [this post](https://developer.woocommerce.com/2021/03/15/integrating-your-payment-method-with-cart-and-checkout-blocks/).
 
Your best course of action right now if you are using a payment method that isn't working with the blocks is to notify the developer of the extension and ask if they can add support.
 
Until then you can keep on top of the [status of the Cart & Checkout Blocks in this documentation](https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/).

**Comment by ralucaStan** [comment]
According to this https://github.com/woocommerce/woocommerce-paypal-payments/issues/211#issuecomment-1551145433 a new pre-release for the next PayPal Payments 2.0.5 is available [on GitHub](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.0.5-rc1) with express payment methods support in the WooCommerce blocks.
