### ISSUE TITLE
Add e2e tests to verify disabled blocks can't be added to widget areas

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#4645]
We are currently disabling some blocks from being added to widget areas using a work-around (see https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/4225 and https://github.com/WordPress/gutenberg/issues/28517 for some context). This is very brittle and has regressed in the past: https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4640.

This issue is about adding automated testing to check that Cart, Checkout, All Products & filters blocks can't be added to widget areas. This would have alerted us about this issue in advance.

**Comment by nerrad** [comment]
Closing because related PR is merged.

**Comment by Aljullu** [comment]
Hey @nerrad, this issue is about adding e2e tests so the fix in #4646 doesn't regress, because that PR doesn't include any tests. Should we reopen this issue again?

**Comment by nerrad** [comment]
Oops yup. If I ever close something incorrectly feel free to reopen and leave a comment why it should have been left open :)

**Comment by nerrad** [comment]
I think I was going by the pipelines (the issue was in the Review/QA pipeline). So can you move this issue to the appropriate pipeline @Aljullu (not sure when you plan on tackling the work).

**Comment by Aljullu** [comment]
Ah, for some reason it got connected to PR #4646. I disconnected them now and moved it back to the backlog, was thinking to leave this task for the cooldown.
