### ISSUE TITLE
Warning: Missing argument 3 for wgpb_extra_shortcode_features() 

### ISSUE THREAD

**Issue by 3adegh** [woocommerce/woocommerce-gutenberg-products-block#465]
Full error is :

Warning: Missing argument 3 for wgpb_extra_shortcode_features() in /home/.../domains/.../public_html/wp-content/plugins/woo-gutenberg-products-block/woocommerce-gutenberg-products-block.php on line 476

after update woocomerce the error epear in top of the product block in page

**Comment by ryelle** [comment]
I haven't been able to replicate the issue, and this function has been removed from in the upcoming 2.0/WooCommerce 3.6 release - so I'm going to close this issue. Let us know if you're still having trouble once 3.6 is released.

**Comment by DamianMartz** [comment]
@3adegh Did you manage to fix this issue? The same thing is happening to me.
