### ISSUE TITLE
Woocommerce Blocks Checkout - Payment methods 

### ISSUE THREAD

**Issue by salesneodo** [woocommerce/woocommerce-gutenberg-products-block#4657]
## Describe the solution you'd like

i have done research on the payment methods and saw on the one page post that Payfast is on the list yet on the checkout page the Payfast payment method is not available. I have the PayFast payment plugin installed and worked for months now without any issues as well as the Cloudcart-Gateway

. Why cant the plugin just not pull all the payment methods listed in the WooCommerce Settings - >> Payments for the ones that are active

.![payment](https://user-images.githubusercontent.com/87749605/131491227-b4aa3280-b855-4295-8383-d58837f0873c.png)

## Additional context

![payment](https://user-images.githubusercontent.com/87749605/131491227-b4aa3280-b855-4295-8383-d58837f0873c.png)

**Comment by salesneodo** [comment]
https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/

shows Payfast is one but does not load

**Comment by nielslange** [comment]
Hello @salesneodo,

Thanks for reporting this problem. To further troubleshoot it, can you please post the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) of your site?

**Comment by salesneodo** [comment]
`
### WordPress Environment ###

WordPress address (URL): https://www.neodo-inc.com
Site address (URL): https://www.neodo-inc.com
WC Version: 5.6.0
REST API Version: ✔ 5.6.0
WC Blocks Version: ✔ 5.5.1
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.5.1
Log Directory Writable: ✔
WP Version: ❌ 5.7.2 - There is a newer version of WordPress available (5.8)
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.30
PHP Post Max Size: 128 MB
PHP Time Limit: 5000
PHP Max Input Vars: 3000
cURL Version: 7.78.0
OpenSSL/1.1.1l

SUHOSIN Installed: –
MySQL Version: 5.6.51
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.6.0
WC Database Prefix: wpal_
Total Database Size: 709.31MB
Database Data Size: 507.30MB
Database Index Size: 202.01MB
wpal_woocommerce_sessions: Data: 58.50MB + Index: 1.99MB + Engine MyISAM
wpal_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpal_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpal_woocommerce_order_items: Data: 0.08MB + Index: 0.06MB + Engine MyISAM
wpal_woocommerce_order_itemmeta: Data: 0.53MB + Index: 0.43MB + Engine MyISAM
wpal_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpal_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
fin_accounts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
fin_costs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
fin_taxpaid: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
fin_transfers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_actionscheduler_actions: Data: 83.28MB + Index: 19.30MB + Engine MyISAM
wpal_actionscheduler_claims: Data: 0.28MB + Index: 1.00MB + Engine MyISAM
wpal_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpal_actionscheduler_logs: Data: 104.54MB + Index: 40.32MB + Engine MyISAM
wpal_adsw_ali_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_adtribes_my_conversions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_aiowps_events: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_aiowps_failed_logins: Data: 14.24MB + Index: 4.61MB + Engine MyISAM
wpal_aiowps_global_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_aiowps_login_activity: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wpal_aiowps_login_lockdown: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_aiowps_permanent_block: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_bobsi_tradefeed_audit: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpal_bobsi_tradefeed_product: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wpal_bobsi_tradefeed_product_base: Data: 13.27MB + Index: 0.00MB + Engine InnoDB
wpal_cbaccounting_account_manager: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_cbaccounting_category: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_cbaccounting_expcat_rel: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_cbaccounting_expinc: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_cbaccounting_vc_manager: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_commentmeta: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wpal_comments: Data: 17.10MB + Index: 14.05MB + Engine MyISAM
wpal_erp_acct_bills: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_bill_account_details: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_bill_details: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_cash_at_banks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_chart_of_accounts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_currency_info: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_expenses: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_expense_checks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_expense_details: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_financial_years: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_invoices: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_invoice_account_details: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_invoice_details: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_invoice_details_tax: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_invoice_receipts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_invoice_receipts_details: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_journals: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_journal_details: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_ledgers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_ledger_categories: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_ledger_details: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_ledger_settings: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_opening_balances: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_payment_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_pay_bill: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_pay_bill_details: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_pay_purchase: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_pay_purchase_details: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_people_account_details: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_people_trn: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_people_trn_details: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_products: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_product_categories: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_product_details: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_product_types: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_purchase: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_purchase_account_details: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_purchase_details: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_purchase_details_tax: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_taxes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_tax_agencies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_tax_agency_details: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_tax_categories: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_tax_cat_agency: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_tax_pay: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_transfer_voucher: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_trn_status_types: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_acct_voucher_no: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_ac_banks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_ac_chart_classes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_ac_chart_types: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_ac_journals: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_ac_ledger: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_ac_payments: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_ac_tax: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_ac_tax_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_ac_transactions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_ac_transaction_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_audit_log: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpal_erp_company_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_crm_activities_task: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_crm_contact_group: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_crm_contact_subscriber: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_crm_customer_activities: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_crm_customer_companies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_crm_save_email_replies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_crm_save_search: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_holidays_indv: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_hr_announcement: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_hr_dependents: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_hr_depts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_hr_designations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_hr_education: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_hr_employees: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpal_erp_hr_employee_history: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_hr_employee_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_hr_employee_performance: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_hr_financial_years: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_hr_financial_years_new: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_hr_holiday: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_hr_leaves: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_hr_leaves_new: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_hr_leaves_old: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_hr_leaves_unpaid: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_hr_leaves_unpaid_new: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_hr_leave_approval_status: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_hr_leave_approval_status_new: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_hr_leave_encashment_requests: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_hr_leave_encashment_requests_new: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_hr_leave_entitlements: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_hr_leave_entitlements_new: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_hr_leave_entitlements_old: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_hr_leave_policies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_hr_leave_policies_new: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_hr_leave_policies_old: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_hr_leave_policies_segregation: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_hr_leave_policies_segregation_new: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_hr_leave_requests: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_hr_leave_requests_new: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_hr_leave_requests_old: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_hr_leave_request_details: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_hr_leave_request_details_new: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_hr_work_exp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_peoplemeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpal_erp_peoples: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wpal_erp_people_types: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_people_type_relations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_erp_user_leaves: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_fbv: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpal_fbv_attachment_folder: Data: 0.47MB + Index: 0.00MB + Engine InnoDB
wpal_ig_blocked_emails: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_ig_campaigns: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_ig_contacts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_ig_contacts_ips: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_ig_forms: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_ig_lists: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_ig_lists_contacts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_ig_mailing_queue: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_ig_sending_queue: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_import_detail_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpal_import_log_detail: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpal_import_postID: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_mclean_refs: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wpal_mclean_scan: Data: 0.44MB + Index: 0.14MB + Engine MyISAM
wpal_options: Data: 15.72MB + Index: 2.02MB + Engine MyISAM
wpal_pmxe_exports: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wpal_pmxe_google_cats: Data: 0.26MB + Index: 0.05MB + Engine MyISAM
wpal_pmxe_posts: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wpal_pmxe_templates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_pmxi_files: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_pmxi_hash: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_pmxi_history: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_pmxi_images: Data: 0.89MB + Index: 0.22MB + Engine MyISAM
wpal_pmxi_imports: Data: 0.10MB + Index: 0.00MB + Engine MyISAM
wpal_pmxi_posts: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wpal_pmxi_templates: Data: 0.12MB + Index: 0.00MB + Engine MyISAM
wpal_postmeta: Data: 90.20MB + Index: 47.98MB + Engine MyISAM
wpal_posts: Data: 23.55MB + Index: 12.48MB + Engine MyISAM
wpal_qa_cog_category_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpal_qa_cog_order_product_lookup: Data: 0.07MB + Index: 0.04MB + Engine MyISAM
wpal_qa_cog_order_stats: Data: 0.03MB + Index: 0.03MB + Engine MyISAM
wpal_shipment_batch_process: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_smackcsv_file_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpal_smackuci_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpal_termmeta: Data: 1.64MB + Index: 1.08MB + Engine MyISAM
wpal_terms: Data: 1.47MB + Index: 2.33MB + Engine MyISAM
wpal_term_relationships: Data: 1.90MB + Index: 3.72MB + Engine MyISAM
wpal_term_taxonomy: Data: 1.00MB + Index: 0.83MB + Engine MyISAM
wpal_ultimate_csv_importer_acf_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpal_ultimate_csv_importer_mappingtemplate: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpal_ultimate_csv_importer_media: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpal_ultimate_csv_importer_shortcode_manager: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpal_ultimate_post_entries: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpal_usermeta: Data: 9.88MB + Index: 0.17MB + Engine MyISAM
wpal_users: Data: 0.02MB + Index: 0.03MB + Engine MyISAM
wpal_user_registration_sessions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_wcpdf_invoice_number: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wpal_wc_admin_note_actions: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wpal_wc_category_lookup: Data: 0.03MB + Index: 0.05MB + Engine MyISAM
wpal_wc_customer_lookup: Data: 0.03MB + Index: 0.03MB + Engine MyISAM
wpal_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_wc_order_product_lookup: Data: 0.05MB + Index: 0.05MB + Engine MyISAM
wpal_wc_order_stats: Data: 0.03MB + Index: 0.03MB + Engine MyISAM
wpal_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_wc_product_meta_lookup: Data: 3.01MB + Index: 4.67MB + Engine MyISAM
wpal_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpal_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_woo_shipment_status_email: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_woo_shippment_provider: Data: 0.04MB + Index: 0.01MB + Engine MyISAM
wpal_wpci_id_associations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_wsal_metadata: Data: 16.09MB + Index: 13.85MB + Engine MyISAM
wpal_wsal_occurrences: Data: 0.62MB + Index: 0.85MB + Engine MyISAM
wpal_wt_iew_action_history: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_wt_iew_cron: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_wt_iew_ftp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_wt_iew_mapping_template: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpal_yith_wcwl: Data: 8.89MB + Index: 4.56MB + Engine MyISAM
wpal_yith_wcwl_lists: Data: 13.73MB + Index: 12.75MB + Engine MyISAM
wpal_yoast_indexable: Data: 16.97MB + Index: 5.41MB + Engine MyISAM
wpal_yoast_indexable_hierarchy: Data: 0.71MB + Index: 2.13MB + Engine MyISAM
wpal_yoast_migrations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpal_yoast_primary_term: Data: 0.08MB + Index: 0.12MB + Engine MyISAM
wpal_yoast_seo_links: Data: 0.13MB + Index: 0.07MB + Engine MyISAM
wpal_yoast_seo_meta: Data: 4.44MB + Index: 4.37MB + Engine MyISAM

### Post Type Counts ###

attachment: 12063
custom_css: 1
es_template: 2
ig_campaign: 1
ml-slide: 73
ml-slider: 9
nav_menu_item: 384
oembed_cache: 46
page: 28
post: 1
product: 12061
product_variation: 6
product-feed: 1
revision: 641
seedprod: 1
shop_coupon: 3
shop_order: 606
shop_order_refund: 45
user_registration: 2
wccaf: 1
wcccf: 3
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (34) ###

Advanced noCaptcha & invisible Captcha: by Shamim Hasan – 6.1.5
All In One WP Security: by Tips and Tricks HQ
Peter Petreski
Ruhul
Ivy – 4.4.9

Bridge Connector: by  – 1.0.0
bidorbuy Store Integrator: by bidorbuy – 2.12.0
Contact Form 7: by Takayuki Miyoshi – 5.4.2
One page checkout and layouts for Woocommerce: by BluePlugins – 2.11
Facebook for WooCommerce: by Facebook – 2.6.4
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.18.0
Kirki Customizer Framework: by David Vongries – 3.1.9
Product Category Tree: by AWESOME TOGI – 2.5
Product CSV Import Export (BASIC): by WebToffee – 2.0.8
QA Cost of Goods & Margins: by Quick Assortments AB – 2.5.0
User Registration: by WPEverest – 2.0.2
WC Fields Factory: by Saravana Kumar K – 3.0.3
Advanced Shipment Tracking for WooCommerce: by zorem – 3.2.9
Checkout Field Editor for WooCommerce: by ThemeHigh – 1.4.9
GIVT Voucher Powered by CloudCart: by cloudDev – 1.2.0
WooCommerce Cost of Shipping: by TheRiteSites – 1.4.0
Woocommerce delete product images: by Husain Ahmed – 1.0.2
WooCommerce Blocks: by Automattic – 5.5.1
Product Feed PRO for WooCommerce: by AdTribes.io – 10.5.6
Print Invoice & Delivery Notes for WooCommerce: by Tyche Softwares – 4.6.4
WooCommerce Custom Payment Gateway: by WPRuby – 1.3.4
WooCommerce PayFast Gateway: by WooCommerce – 1.4.19
WooCommerce Shortcodes: by WooThemes
Claudio Sanches – 1.0.0

WooCommerce Wholesale Prices: by Rymera Web Co – 1.15
WP All Import - WooCommerce Add-On: by Soflyy – 1.4.9
WooCommerce: by Automattic – 5.6.0
Yoast SEO: by Team Yoast – 17.0
WP All Import: by Soflyy – 3.6.1
WP Crontrol: by John Blackbourn & crontributors – 1.10.0
YITH WooCommerce Compare: by YITH – 2.5.4.1
YITH WooCommerce Quick View: by YITH – 1.6.4
YITH WooCommerce Wishlist: by YITH – 3.0.25

### Inactive Plugins (8) ###

Ban Hammer: by Mika Epstein – 2.8
CMB2: by CMB2 team – 2.9.0
Coming Soon Page, Maintenance Mode & Landing Pages by SeedProd: by SeedProd – 6.6.0
NS WooCommerce Watermark: by NsThemes – 2.11.1
Order / Coupon / Subscription Export Import Plugin for WooCommerce (BASIC): by WebToffee – 2.1.0
WooCommerce Custom Payment Gateway Pro: by WPRuby – 2.0.2
WP All Export: by Soflyy – 1.3.0
WP Ultimate Exporter: by Smackcoders – 1.6.2

### Dropin Plugins (1) ###

maintenance.php: maintenance.php

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: ZAR (R)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: #226 - /terms-conditions/

### Theme ###

Name: Kakina
Version: 1.3.3
Author URL: http://themes4wp.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: –

### Action Scheduler ###

Complete: 1,876
Oldest: 2021-08-18 09:30:01 +0000
Newest: 2021-09-06 11:50:07 +0000

Failed: 228,159
Oldest: 2020-10-09 10:17:01 +0000
Newest: 2021-09-06 11:49:05 +0000

Pending: 1
Oldest: 2021-09-07 07:57:18 +0000
Newest: 2021-09-07 07:57:18 +0000


### Status report information ###

Generated at: 2021-09-06 14:22:25 +02:00
`

**Comment by Aljullu** [comment]
Thanks for opening this issue @salesneodo! I was able to reproduce what you described. I saw there is an open issue in the WooCommerce PayFast Gateway repo (https://github.com/woocommerce/woocommerce-gateway-payfast/issues/46), where the fix needs to be implemented. For now, I will close this issue here, if you want to be aware of any updates, you can follow the issue in the PayFast Gateway repo.
