### ISSUE TITLE
Use register_block_type_from_metadata function

### ISSUE THREAD

**Issue by spacedmonkey** [woocommerce/woocommerce-gutenberg-products-block#4672]
## Is your feature request related to a problem? Please describe.
In WordPress 5.5, the [register_block_type_from_metadata](https://developer.wordpress.org/reference/functions/register_block_type_from_metadata/) was added. The allows for gutenberg blocks to be registered in both PHP and Javascript, using a block.json file. This has a number of benefits for developers that integrated with blocks.

**Comment by nielslange** [comment]
Hello @spacedmonkey 👋🏻

Thanks so much for taking the time to leave some feedback – much appreciated! We make note of all feedback we receive and we also close issues with the feedback as active issues are used for bugs or feature/enhancements. It does not mean that we don’t note or review the feedback. Closed issues can also still be commented on.

**Comment by spacedmonkey** [comment]
Is there any chance movement on this? Registering blocks on the server and using block.json are recommended way of building blocks. 

CC @Aljullu

**Comment by Aljullu** [comment]
Thanks for raising this, @spacedmonkey! We are definitely interested in embracing this way of registering blocks. The reason we hadn't switched to it yet is not lack of interest, but limited resources. We will migrate a few blocks as a first step and based on the required effort we might prioritize this for all other blocks.

**Comment by dinhtungdu** [comment]
@spacedmonkey @Aljullu Actually, we're already registering blocks using metadata if available, so I think this issue can be closed.

https://github.com/woocommerce/woocommerce-blocks/blob/a3261a86a6905e9d5a773299245ddd0da30278e0/src/BlockTypes/AbstractBlock.php#L210-L218

**Comment by Aljullu** [comment]
Ah, good catch, @dinhtungdu! Should we change that call from `register_block_type()` to `register_block_type_from_metadata()`? We will save one [`file_exists()` call](https://developer.wordpress.org/reference/functions/register_block_type/#source) (which [we already do](https://github.com/woocommerce/woocommerce-blocks/blob/a3261a86a6905e9d5a773299245ddd0da30278e0/src/Assets/Api.php#L72)) and code will be more explicit. Thoughts?

**Comment by dinhtungdu** [comment]
> Should we change that call from `register_block_type()` to `register_block_type_from_metadata()`? We will save one [`file_exists()` call](https://developer.wordpress.org/reference/functions/register_block_type/#source) (which [we already do](https://github.com/woocommerce/woocommerce-blocks/blob/a3261a86a6905e9d5a773299245ddd0da30278e0/src/Assets/Api.php#L72)) and code will be more explicit. Thoughts?

Make a lot of sense to me! PR is incomming.
