### ISSUE TITLE
Mini Cart block: allow modifying the empty state

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#4674]
Similarly to the way the Cart block empty state can be modified, we would like the Mini Cart Contents block empty state to be editable too. We should be able to reuse most of the logic which is currently used in the Cart block:

https://github.com/woocommerce/woocommerce-gutenberg-products-block/tree/f0fc6c5fff2dcc5ee2ddb6ac76eec13b86701afa/assets/js/blocks/cart-checkout/cart/empty-cart-edit

**Comment by frontdevde** [comment]
@vivialice Could you give us some design guidance here? The latest Mini Cart Design i3 (pbIy4N-1YF-p2) focuses on how the empty state will look on the Frontend of the site. What are your thoughts on how it should look in the editor?

**Comment by Aljullu** [comment]
I created #4857 that will be used to implement the view switcher in the editor so this issue (#4674) can be solely focused on allowing the empty state to be modified.
