### ISSUE TITLE
Products by Category: Error loading block: Invalid parameter(s): attributes triggered with certain 3rd party themes

### ISSUE THREAD

**Issue by joashrajin** [woocommerce/woocommerce-gutenberg-products-block#4690]
## Describe the bug

The Products by Category Block gives an Error: `Error loading block: Invalid parameter(s): attributes`. This seems to happen with certain 3rd party themes, and [here](https://wordpress.org/support/topic/products-by-category-error-loading-block-invalid-parameters-attributes/#post-14846040) is what the Developers of the ExS Theme have shared:

"We’re using a Gutenberg Hook:

`hooks.addFilter('blocks.registerBlockType',`

to extend any Gutenberg block so user could add an animation class for it.

But I found that products grid block attributes are hardcoded without any filter here:

`wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/BlockTypes/AbstractProductGrid.php`

in the protected function get_block_type_attributes.

It would be great if developers could add a custom attributes with some filter for default block attributes.

I have found that ‘Error loading block: Invalid parameter(s) attributes‘ is a pretty common error with server side rendering blocks and it would be a great to find a global solution for this issue."

## To reproduce

1. Install a Theme such as [ExS Pro](https://d.pr/n/ZC2RAa)
2. Add the Products by Category Block to a page, choose some categories. 
3. Go to Appearance > Customize > ExS Theme Options > Animation and enable the Enable CSS animation for elements option.
4. View the Page in Gutenberg again. You should see the errors

## Screenshots
![image](https://user-images.githubusercontent.com/16253818/132357144-5683a2d8-52bb-421b-94a6-961ddcbda19c.png)

### WordPress (please complete the following information):
* Core version: [5.8]
* WooCommerce version: [5.6.0]
* WooCommerce Blocks version: [5.5.1 (preinstalled)]
* Site language: English

### Desktop (please complete the following information):
* OS: [macOS]
* Browser [Chrome]

## Additional context
Code the author used to fix it: 

```
hooks.addFilter(
  'blocks.registerBlockType',
  'exs/animation/animation-attributes',
  function(settings, name) {
    if(
      'woocommerce/product-category'===name
      ||
      'woocommerce/products-by-attribute'===name
      ||
      'woocommerce/product-categories'===name
      ||
      'woocommerce/product-tag'===name
      ||
      'woocommerce/product-top-rated'===name
      ||
      'woocommerce/product-on-sale'===name
      ||
      'woocommerce/product-new'===name
      ||
      'woocommerce/product-best-sellers'===name
      ||
      'woocommerce/handpicked-products'===name
    )

    {
      return settings;
    }

    //check if object exists for old Gutenberg version compatibility
    if(typeof settings.attributes !== 'undefined'){
      settings.attributes = lodash.assign( {}, settings.attributes, {
        animation: {
          type: 'string',
          default: '',
        }
      });
    }
    return settings;
  }
);
```

Please feel free to close if this is a duplicate of https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/891

**Comment by exstheme** [comment]
Hello!

Many thanks for your attention to this problem.
I wrote a super tiny plugin that will add a simple select dropdown to ANY Gutenberg block to the Gutenberg editor.

It  duplicates functionality from the ExS Pro theme without need to use any theme.

[https://cdn.exsthemewp.com/exs-extend-blocks-test.zip](https://cdn.exsthemewp.com/exs-extend-blocks-test.zip)

I have tested the WooCommerce blocks of following types:

woocommerce/product-category
woocommerce/products-by-attribute
woocommerce/product-categories
woocommerce/product-tag
woocommerce/product-top-rated
woocommerce/product-on-sale
woocommerce/product-new
woocommerce/product-best-sellers
woocommerce/handpicked-products

with this plugin on the default Twenty Nineteen v2.1  and same issue (`Error loading block: Invalid parameter(s): attributes`)  appears.

This problem is well known:

[https://duckduckgo.com/?q=Error+loading+block%3A+Invalid+parameter(s)%3A+attributes](https://duckduckgo.com/?q=Error+loading+block%3A+Invalid+parameter(s)%3A+attributes)

It appears if server side rendered block has no registered attributes in the PHP within  [register_block_type](https://developer.wordpress.org/reference/functions/register_block_type/) function with $args parameter.

As there is no ability to know what attribute third party developers will add to the block - the only way is to add 'apply_filters' to the array of attributes before register a new block so developers could hook in and add their own attributes to extend a block.

Hope this helps.

Thank you and best regards!

**Comment by nielslange** [comment]
Hello @joashrajin 👋

Thanks for taking the time to leave the feature request. While we appreciate you sharing your idea with us, it doesn’t fit in with our current priorities for the project.

This doesn’t mean what you are suggesting isn’t a good idea or doesn’t make sense — it’s just that we have limited time to work on various projects.

At some point, we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. Meanwhile, don’t be alarmed if you don’t see any activity on this issue for a while.

**Comment by exstheme** [comment]
Hello, @nielslange !

I don't think that replacing code
```
protected function get_block_type_attributes() {
  return array(
    'className'         => $this->get_schema_string(),
    'columns'           => $this->get_schema_number( wc_get_theme_support( 'product_blocks::default_columns', 3 ) ),
    'rows'              => $this->get_schema_number( wc_get_theme_support( 'product_blocks::default_rows', 3 ) ),
    'categories'        => $this->get_schema_list_ids(),
    'catOperator'       => array(
      'type'    => 'string',
      'default' => 'any',
    ),
    'contentVisibility' => $this->get_schema_content_visibility(),
    'align'             => $this->get_schema_align(),
    'alignButtons'      => $this->get_schema_boolean( false ),
    'isPreview'         => $this->get_schema_boolean( false ),
  );
}
```
with 
```
return apply_filters( 'AbstractProductGrid', array(
  'className'         => $this->get_schema_string(),
  'columns'           => $this->get_schema_number( wc_get_theme_support( 'product_blocks::default_columns', 3 ) ),
  'rows'              => $this->get_schema_number( wc_get_theme_support( 'product_blocks::default_rows', 3 ) ),
  'categories'        => $this->get_schema_list_ids(),
  'catOperator'       => array(
    'type'    => 'string',
    'default' => 'any',
  ),
  'contentVisibility' => $this->get_schema_content_visibility(),
  'align'             => $this->get_schema_align(),
  'alignButtons'      => $this->get_schema_boolean( false ),
  'isPreview'         => $this->get_schema_boolean( false ),
) );
```
in the file
`wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/BlockTypes/AbstractProductGrid.php`

will require a lot of work, but thanks anyway.

**Comment by nielslange** [comment]
Hello @exstheme 👋

Replacing the code itself does not take a lot of time. What takes more time is testing to ensure that the code change does not introduce unwanted side effects. That said, I'm happy to take a closer look at your proposed solution the next days, to get a better idea what consequences this solution might bring.

**Comment by exstheme** [comment]
Hi, @nielslange 

Thanks for your time!

I guess that [apply_filters function](https://developer.wordpress.org/reference/functions/apply_filters/) should not create any problems. 

Potential problems may cause if 3rd party developers will break your default block attributes.

**Comment by nielslange** [comment]
Hello @exstheme 👋

I looked up your code again and discussed this change with a few other developers. For now, we decided against `apply_filters`. As you mentioned in your last comment, adding `apply_filters` could lead to developers breaking their sites as the filter allows manipulating internal functionality. 

That said, the initial problem can be solved by adding the following filter to your site:

```php
add_filter(
  'register_block_type_args',
  function ( $args, $block_type ) {
    if ( 'woocommerce/product-category' !== $block_type ) {
      return $args;
    }

    $args['attributes']['animation'] = array(
      'type'    => 'string',
      'default' => '',
    );
    return $args;
  },
  10,
  2
);
```

This code snippet simply adds an attribute called `animation` to the `woocommerce/product-category` block. If more blocks should be affected, the code snippet needs to be adjusted accordingly.

We also noticed that the conditional statements of your JS code snippet seem to target the wrong blocks. To target `woocommerce/product-category`, `woocommerce/products-by-attribute`, etc., the following code snippet

```js
if(
  'woocommerce/product-category' === name ||
  'woocommerce/products-by-attribute' === name ||
  'woocommerce/product-categories' === name ||
  'woocommerce/product-tag' === name ||
  'woocommerce/product-top-rated' === name ||
  'woocommerce/product-on-sale' === name ||
  'woocommerce/product-new' === name ||
  'woocommerce/product-best-sellers' === name ||
  'woocommerce/handpicked-products' === name
) {
  return settings;
}
```

should be 

```js
if(
  'woocommerce/product-category' !== name ||
  'woocommerce/products-by-attribute' !== name ||
  'woocommerce/product-categories' !== name ||
  'woocommerce/product-tag' !== name ||
  'woocommerce/product-top-rated' !== name ||
  'woocommerce/product-on-sale' !== name ||
  'woocommerce/product-new' !== name ||
  'woocommerce/product-best-sellers' !== name ||
  'woocommerce/handpicked-products' !== name
) {
  return settings;
}
```

Although we decided not to add a wanted filter, thanks for suggesting this option initially. Your feedback is always much appreciated.
