### ISSUE TITLE
Experimental tracking support data for impressions causing slowdown

### ISSUE THREAD

**Issue by dianfishekqi** [woocommerce/woocommerce-gutenberg-products-block#4695]
Product grid appends inject item [data](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/src/BlockTypes/AbstractProductGrid.php#L93) to body, this line is not cached at all, when you have multiple product grids (in my case 7 * 12 ) causes over extra un cachable queries.

**Comment by nielslange** [comment]
Hello @dianfishekqi 👋

Thanks for reporting this issue. Can you provide detailed steps on how to reproduce and monitor the problem that you reported?

**Comment by nerrad** [comment]
While we'd appreciate more details about the exact problems you are encountering here @dianfishekqi I've taken a brief look at the code path referred to and here's a synopsis. The code being referenced is here:

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/e00cd017bfd3d30167a9821db5725675a58478f1/src/BlockTypes/AbstractProductGrid.php#L93

While the `$products` being mapped to the function `Automattic\WooCommerce\Blocks\StoreApi\Schemas::get_item_response` ARE in fact cached:

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/e00cd017bfd3d30167a9821db5725675a58478f1/src/BlockTypes/AbstractProductGrid.php#L292-L308

It looks like that each call to `Automattic\WooCommerce\Blocks\StoreApi\Schemas::get_item_response` results in additional queries for data related to the products (eg `get_the_terms`). Although it appears that those could be cached as well, so at least the initial query to terms for a given product ID should be the only query made if that product appears in multiple instances of the block.

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/e00cd017bfd3d30167a9821db5725675a58478f1/src/StoreApi/Schemas/ProductSchema.php#L430-L466

@mikejolley, without having any further data around exactly what the issue author is referring to here, do you think it's worthwhile at least auditing the queries happening through this code stack and seeing if we can optimize more as a potential performance improvement (and add to the backlog)?

**Comment by dianfishekqi** [comment]
Hello  all,

```
SELECT post_id as variation_id, meta_key as attribute_key, meta_value as attribute_value FROM wp_postmeta WHERE post_id IN (25295,25298,25300,25303)AND meta_key IN ('attribute_pa_size') |
```
one of the queries not being cached debugged on **Query Monitor** source[ `Automattic\W\B\S\S\ProductSchema>get_variations()` ](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/e00cd017bfd3d30167a9821db5725675a58478f1/src/StoreApi/Schemas/ProductSchema.php#L450)

**Comment by dianfishekqi** [comment]
@nerrad It's amounting to 91/121 queries on our homepages.

<img width="1497" alt="Screen Shot 2021-10-25 at 10 31 59" src="https://user-images.githubusercontent.com/4225509/138662108-a142c65b-b310-4baf-81eb-ea16c6815b2e.png">
<img width="1486" alt="Screen Shot 2021-10-25 at 10 34 08" src="https://user-images.githubusercontent.com/4225509/138662306-6499b7ba-58ab-46a2-b144-3e7ce28c0502.png">

**Comment by dianfishekqi** [comment]
Commenting it out :
<img width="1486" alt="Screen Shot 2021-10-25 at 10 36 26" src="https://user-images.githubusercontent.com/4225509/138663064-1a446b70-c605-45ad-94fa-cf7fd9cc65ff.png">

Brings down the number of queries to zero improving page generation time by 70%.

<img width="1486" alt="Screen Shot 2021-10-25 at 10 37 46" src="https://user-images.githubusercontent.com/4225509/138663028-eb5010af-8e76-4753-a14f-137cb50996b1.png">

**Comment by nerrad** [comment]
Thanks! This is something on the list of things we'll look into.

**Comment by mikejolley** [comment]
<del>There is no evidence that the queries are uncached (which would be reported as duplicate queries in Query Monitor), there are just many similar queries per variable product.</del> We can look at priming them somehow, or revise what is exposed via the experimental action.

Managed to replicate the query issue with multiple duplicate blocks.
