### ISSUE TITLE
Cart i2

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#4703]
This is an epic to track the development of Cart i2, a refactor of Cart block to allow inner blocks, in the steps of [Checkout i2](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4260)

**Comment by webdados** [comment]
This a must-have to be able to mimic some of the old hooks/actions.

**Comment by mikejolley** [comment]
@senadir done?

**Comment by senadir** [comment]
Yep
