### ISSUE TITLE
Order can still be placed when no shipping options are available

### ISSUE THREAD

**Issue by TomDeFord** [woocommerce/woocommerce-gutenberg-products-block#4705]
## Describe the bug
Order can still be placed when no shipping options are available

## To reproduce
1. Create 2 shipping zones, one with a specific postal/zip code but no shipping method. The second add a country wide catch all with a standard local pickup shipping method.
2. At check out select postal/zip code for 1st shipping zone - no shipping option is displayed, clicking Place Order proceeds.

3. Additional observation: when the postal/zip code is entered in 2. above, the order summary displays ' Shipping $0 via' (i.e. no shipping method listed) followed by the postal/zip code address entered even though shipping there is not allowed.

## Expected behavior
Should stop order being created if no shipping method available

## Environment
* Core version: 5.8.0
* WooCommerce version: 5.6.0
* WooCommerce Blocks version: 5.8.0

**Comment by senadir** [comment]
Thank you for submitting this issue @TomDeFord I can confirm this bug. No need for such a convoluted testing instructions, you can set a shipping zone in country X and checkout with country Y to reproduce this.
