### ISSUE TITLE
Checkout has no checkbox to confirm Ts&Cs

### ISSUE THREAD

**Issue by TomDeFord** [woocommerce/woocommerce-gutenberg-products-block#4707]
## Describe the bug
Checkout has no checkbox to confirm Ts&Cs

## To reproduce
1. Add product to cart and checkout
2. Unlike core checkout no checkbox is available to confirm acceptance of Ts&Cs

## Expected behavior
1. Add Ts&Cs checkbox like current core checkout

## Environment
* Core version: 5.8.0
* WooCommerce version: 5.6.0
* WooCommerce Blocks version: 5.8.0

**Comment by nielslange** [comment]
Hello @TomDeFord 👋

Thanks for reporting this problem. We are aware of it and currently working on `Checkout i2`, which has a [checkbox for the terms & conditions](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4714). Therefore, I'm going to close this issue. Nevertheless, thanks for reporting it. Your contributions are always welcome!

**Comment by nickfmc** [comment]
Is there an ETA for the i2 checkout? need to decide if we are rebuilding a checkout page or waiting ?
