### ISSUE TITLE
Break down Cart i2 block into 4 different blocks.

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#4709]
We need to break Cart i2 block into those blocks:
- Two columns block.
- A block that contain all items.
- A block that contain total lines.
- A block with Proceed to Checkout block.
- A block with Express Payment blocks.

**Comment by mikejolley** [comment]
@senadir This makes sense. We could look at adding specific blocks later on for things like cross/sells upsells too. Optional.

**Comment by senadir** [comment]
This was handled individually by PRs.
