### ISSUE TITLE
Checkout i2: panels can be toggled in editor view

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#4710]
I'm not sure if this is intended or not, but wanted to report it because it seems to work differently between Checkout and Checkout i2: panels can be opened and closed in the editor.

## To reproduce
1. Create a post or page and add the Checkout i2 block.
2. Click on Order Summary or Coupon Code.
3. Notice the panels open/closed.

https://user-images.githubusercontent.com/3616980/132857657-94445b20-99f0-4d82-922d-960ab2728494.mp4

## Old Checkout behavior
When clicking on Panel titles, nothing happened in the old Checkout.

**Comment by Aljullu** [comment]
The same happens with the `Use same address for billing` checkbox. It wasn't interactive in the old Checkout but it is in Checkout i2.

**Comment by senadir** [comment]
> The same happens with the Use same address for billing checkbox. It wasn't interactive in the old Checkout but it is in Checkout i2.

Currently, we don't persist the checkbox value in frontend, but we need it to toggle on the billing address step if someone wants to add any inner blocks to it.
