### ISSUE TITLE
Checkout i2: empty totals section in Checkout sidebar when taxes are disabled

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#4712]
## To reproduce

1. Go to WooCommerce > Settings and uncheck _Enable tax rates and calculations_ (maybe other changes are required).
![imatge](https://user-images.githubusercontent.com/3616980/132858906-6171c2e6-99a2-4343-a2fa-9995e0a9e118.png)
2. Create a page with the Checkout i2 block.
3. Notice an empty section appears on the sidebar (there is a double border).
![imatge](https://user-images.githubusercontent.com/3616980/132859023-864253ba-1905-4fda-a597-fc2a7e35fb3b.png)

## Expected behavior
If taxes are disabled at the WooCommerce level, that section shouldn't be displayed in the Checkout block sidebar and, thus, it shouldn't display the double border.

**Comment by senadir** [comment]
I can confirm this.

**Comment by mikejolley** [comment]
I think I recall this being in trunk at one point, so we might just need to port the fix across from checkout i1.

**Comment by senadir** [comment]
I believe it was this?
https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/4415
