### ISSUE TITLE
Checkout i2: Terms and condition checkbox validation relies only on color

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#4714]
## To reproduce

1. Create a page and add the Checkout i2 block.
2. Select the Terms and Conditions inner block.
3. In the _Display options_, check _Require checkbox_.
4. Visit that page in the frontend and try to submit the form.
5. Notice there is no error message, only the checkbox and the text turned red.

<img src="https://user-images.githubusercontent.com/3616980/132862234-2498c876-ee69-4851-ad85-45efe7032bb3.png" width="547" alt="" />

## Expected behavior
For accessibility reasons, I think we shouldn't rely solely on the color of elements and instead add a message or an icon that shows where the error is.

**Comment by mikejolley** [comment]
It also gets focus on the text box. Let's perhaps add a more visible outline.
