### ISSUE TITLE
Checkout i2: coupon code error overlaps bottom border

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#4715]
## To reproduce

1. Create a page with the Checkout i2 block.
2. On the frontend, try to add a coupon that doesn't exist.
3. Notice the error that appears collides with the bottom border of the section.

https://user-images.githubusercontent.com/3616980/132862970-3565458d-137a-4851-9689-f21850dc746e.mp4

**Comment by senadir** [comment]
This seems to also happen in Checkout, But I can't found the code that caused it 🤔

**Comment by mikejolley** [comment]
We logged an issue for these validation styles right @senadir? I know it's like this to avoid layout shift but it's bad that we allow a small 1 line space for an unknown validation error. If it happens in Ci1, I reckon to shelve it until it's worked on properly.

Issue https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4583

**Comment by senadir** [comment]
Yeah this seems to be around for some time now. It also seems to be related to this one maybe https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3996? I will leave it for now.

**Comment by senadir** [comment]
Making the error line take a persistent size would regress this https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3968
