### ISSUE TITLE
Checkout I2: Lacking clear indication Shipping Zones link out to shipping management pages.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#4722]
## Describe the bug
I would classify this as a UI/UX bug even though I realize this _may_ be implemented according to design. Currently with the Checkout I2 block, when the Shipping Options inner block is selected, the Zones inspector controls have options that appear as items that can be edited inline, however when you click them it opens a new tab in the browser which is a bit jarring given there is no other signal that will happen.

![CleanShot 2021-09-10 at 14 50 55](https://user-images.githubusercontent.com/1429108/132903008-02805b7f-5248-4b5b-b63b-394d625c91b2.gif)

I think there should be some indication that clicking these links will open up a separate browser tab. For now we should probably use the external link icon instead of the right arrow icon? cc @vivialice for feedback.

**Comment by nerrad** [comment]
The same feedback here applies to the links to various payment methods in the relevant inspector controls panel when the payment methods block is selected. It's not clear they are links to the payment methods page.

**Comment by mikejolley** [comment]
👍🏻  I agree with the icon change. I understand the designs were done with the intention of having settings inline, something not technically possible at this time.
