### ISSUE TITLE
Not all source files are included in the WooCommerce Blocks source zip

### ISSUE THREAD

**Issue by opr** [woocommerce/woocommerce-gutenberg-products-block#4725]
## Describe the bug
If you try to download a zip of the repo (not a built zip as per releases) then not all files are included. Every file listed as `export-ignore` in `.gitattributes` is excluded.

## To reproduce

1. Go to our repo on GitHub, press the green "Code" button and then "Download ZIP"
2. Open the zip and see there are some missing files such as `package.json` (everything listed in `.gitattributes) which doesn't allow the plugin to be built.

## Expected behavior
All source files should be available.

## Additional context
We're using `.gitattributes` to exclude items from the built archive when running `npm run package-plugin:deploy` but this has unintended side effects. This does NOT happen when cloning the repo using git commands, it would only be noticed if you download the zip.

We had a similar issue in Storefront (https://github.com/woocommerce/storefront/issues/1760) - we resolved this by using composer.json to ignore files we didn't want in the build and removing them from `.gitattributes`

**Comment by senadir** [comment]
> we resolved this by using composer.json to ignore files we didn't want in the build and removing them from .gitattributes

Do we have the tools in this repo to use composer.json instead of `.gitattributes` if not, should this be stated in the issue?

**Comment by nielslange** [comment]
Related: #4928 & #4929
