### ISSUE TITLE
Add support for the iDEAL payment method, it's provived via Stripe

### ISSUE THREAD

**Issue by Holland1** [woocommerce/woocommerce-gutenberg-products-block#4726]
As iDeal is (close to) the only payment method that is used in the Netherlands, I can't implement Cart & Checkout Blocks on my website. 

Hopefully it's possible to consider this feature request, as I'm very keen to integrate Cart & Checkout Blocks. 

Thanks

**Comment by nerrad** [comment]
Hi there @Holland1  👋 

Thanks for taking the time to make us aware that the iDeal payment method isn't working with the Checkout and Cart blocks. These blocks are still in early access (via the feature plugin) and it's _expected_ that some existing Woo Extensions that integrate with the current checkout flow in WooCommerce core will not work with the blocks. 

Currently it's up to payment method extension developers to add support for the new checkout flow offered via the cart and checkout blocks. We have some [documentation on that here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/extensibility/payment-method-integration.md) and will be publicizing this more in the coming months. 

It's not clear what specific extension you are referring to, but your best course of action right now if you are using a payment method that isn't working with the blocks is to notify the developer of the extension and ask if they can add support.

Until then you can keep on top of the [status of the Cart & Checkout Blocks in this documentation](https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/).

Something that may work for you in the future as well is [WooCommerce Payments](https://woocommerce.com/products/woocommerce-payments/) will be offering [support for countries including the Netherlands](https://docs.woocommerce.com/document/payments/countries/) in the future. Currently iDeal is in preview with WooCommerce Payments.

We make note of all feedback we receive and we also close issues with the feedback as active issues are used for bugs or feature/enhancements. It does not mean that we don’t note or review the feedback. Closed issues can also still be commented on.
