### ISSUE TITLE
Can't add more than 11 Hand Picked products

### ISSUE THREAD

**Issue by WiredWonder** [woocommerce/woocommerce-gutenberg-products-block#4728]
## Describe the bug
Can't add more than 11 products from multiple categories/searches to the Hand Picked Products block.

## To reproduce

1. add items up to (or greater than) 10, 
2. save the widget, 
3. attempt to add more products to the widget through multiple searches. 

You will find it starts replacing items past 11, as every time you search for something else, it re-calculates the current "products selected" list it only retrieves 10 items.

## Expected behavior
I can hand pick as many items as I want.

### WordPress (please complete the following information):
* Core version: 5.8.1
* Gutenberg version (if installed): na
* WooCommerce version: 5.6.0
* WooCommerce Blocks version: na
* Site language: en_AU
* Any other plugins installed: many

### Desktop (please complete the following information):
* OS: Windows
* Browser: Firefox
* Version: 92

### Smartphone (please complete the following information):
na

## Additional context
Originally raised as #4505 however @mikejolley frustratingly closed that issue before it could be retested by the opener so I have had to raise basically a duplicate.

**Comment by mikejolley** [comment]
We can see your comments. You don't need to open duplicates. Closing in favour of https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4505

**Comment by WiredWonder** [comment]
@mikejolley you literally asked me to create a new ticket. There is no need to be this rude.

**Comment by mikejolley** [comment]
I think there has been a misunderstanding here, so sorry if I wasn't clear which version has the fix. [I commented on your other issue a mew moments ago](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4505). tl;dr the fix is in the Blocks Feature plugin _now_, and won't be in the core version until **WooCommerce 5.7.0**

**Comment by WiredWonder** [comment]
Thank you, confirming it has been fixed in Blocks 5.7.0.
