### ISSUE TITLE
Implement hooks that exist on the cart and checkout shortcodes

### ISSUE THREAD

**Issue by webdados** [woocommerce/woocommerce-gutenberg-products-block#4743]
I've tested the new cart block and just found out that some content I added via the `woocommerce_before_cart_contents` hook does not show up.

Shouldn't this kind of hooks (not just this one) be implemented on the blocks version of the cart/checkout/whatever... blocks to guarantee backward compatibility?
If this is not planned, are there specific/alternate hooks?

**Comment by senadir** [comment]
Hey there @webdados
No, those hooks aren't added because they're PHP ones, we don't have backward compatibility in that regard because the way Cart and Checkout function completely changed.

I can point you to all of our [extensibility interfaces](https://github.com/woocommerce/woocommerce-gutenberg-products-block/tree/trunk/docs/extensibility). We're adding new ones as we see fit.

You can also tell me what you're trying to do and I can point you to the best solution:
- Using SlotFills.
- Creating a new block.

Both solutions will require you to use some quantity of JS/React depending on how complex easy what you're trying to do.

**Comment by webdados** [comment]
In this case, it's a simple php code to show how much is missing on the order total to get free shipping.

I guess that if I want this to be updated when the cart is changed, for example when changing quantities, without the page being reloaded, I need to do this in JS/React, right? If the page was reloaded I could just insert a new block with a shortcode or something similar.

**Comment by webdados** [comment]
I was hoping there was some kind of backward compatibility and the hooks could be done in PHP and then loaded via ajax on the new blocks.

**Comment by senadir** [comment]
>I was hoping there was some kind of backward compatibility and the hooks could be done in PHP and then loaded via ajax on the new blocks.

I see your point here but this would prevent be hard to place given we changed the design and layout, and would severely limit the code from benefiting events and information existing in the new blocks, as well as introduce serious performance issue.

> In this case, it's a simple php code to show how much is missing on the order total to get free shipping.
I guess that if I want this to be updated when the cart is changed, for example when changing quantities, without the page being reloaded, I need to do this in JS/React, right? If the page was reloaded I could just insert a new block with a shortcode or something similar.

Keep track of [this issue](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4703) about Cart i2. Once this work is done, you would have the ability to:
- Create a new block that can be automatically inserted into Cart.
- Gets access to all of the cart information, up to date, without needing to update the page, you will get information like the cart totals, shipping methods, and other things, on each update (quantity, item removed...).

The functionality you're talking about "show how much is missing on the order total to get free shipping." is something we talked about internally and if we didn't end up implementing ourself, would probably provide a tutorial into how to implement.

**Comment by webdados** [comment]
> Keep track of this issue about Cart i2. Once this work is done, you would have the ability to:
> 
> Create a new block that can be automatically inserted into Cart.
> Gets access to all of the cart information, up to date, without needing to update the page, you will get information like the cart totals, shipping methods, and other things, on each update (quantity, item removed...).

Good.

> The functionality you're talking about "show how much is missing on the order total to get free shipping." is something we talked about internally and if we didn't end up implementing ourself, would probably provide a tutorial into how to implement.

Not sure this is something that falls under the scope of WooCommerce, but rather customs development or third-party plugins. I already have this implemented on my private "toolbox plugin" I use on every WooCommerce website, and I'm planning on making some of these features be compatible with the new cart and checkout.
