### ISSUE TITLE
Cart i2: Implement new contexts built for Checkout i2

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#4796]
Checkout i2 brought with it two new contexts `CheckoutBlockContext` and `CheckoutBlockControlsContext`. I'm not yet sure what's the value from them. This is an issue to see if we need them, document them, and implement them in Cart i2.

**Comment by mikejolley** [comment]
I've used one of these for the ViewSwitcher. They are not needed unless you want to pass editor components down to the children or share attributes with child blocks. I think we should implement as needed, as I did in #4811
