### ISSUE TITLE
Unable to create an account using the Checkout Block

### ISSUE THREAD

**Issue by joashrajin** [woocommerce/woocommerce-gutenberg-products-block#4800]
## Describe the bug
I'm not sure if this will be addressed in https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4697, however, the issue is that you can't create an account on checkout when using a Checkout Block. 

## To reproduce

1. Go to WooCommerce > Settings > Accounts & Privacy > Account Creation and enable `"Allow customers to create an account during checkout"`
2. Create a Checkout Page with a Checkout Block
3. Add a product to your card, then view your checkout page 
4. You should notice that there is no checkbox option to create an account unless you switch back to the regular checkout page made without WC Blocks. 

## Expected behavior
A checkbox is shown to allow you to create an account on checkout

## Screenshots
WC Blocks Checkout Page:
![image](https://user-images.githubusercontent.com/16253818/134155093-6955d956-2f7c-4f28-9061-48c569aa1bfe.png)

Regular Checkout Page: 
![image](https://user-images.githubusercontent.com/16253818/134156056-d2f75650-d5a6-47d1-baf8-9bf05f3cc157.png)

### WordPress (please complete the following information):
* Core version: [5.8.1]
* WooCommerce version: [5.6.0]
* WooCommerce Blocks version: [5.9.0]
* Site language: English

**Comment by senadir** [comment]
You can enable that option by:
- First, doing what did here `Go to WooCommerce > Settings > Accounts & Privacy > Account Creation and enable "Allow customers to create an account during checkout"`
- Going to Checkout Block, enabling creating account
![image](https://user-images.githubusercontent.com/6165348/134183068-6e3ee5ca-bd6e-4f1d-9739-f6f99e7257d7.png)

Accounts will now be created regardless. If you have this option set to true
![image](https://user-images.githubusercontent.com/6165348/134183196-f95f937d-3230-4479-9bd9-20baea912b04.png)

Then customers can choose if they want to create an account or not.

**Comment by joashrajin** [comment]
Hi @senadir 👋

Thanks for sharing this with me. For some reason, this option was missing earlier but I see it now! 😀
