### ISSUE TITLE
How can I do this?

### ISSUE THREAD

**Issue by msroky** [woocommerce/woocommerce-gutenberg-products-block#4836]
How to customize the look of a shopping cart?
![Capture33](https://user-images.githubusercontent.com/12650820/134605340-b79d7a60-46f0-4bfb-91e1-7db9310c5e85.PNG)
I would love to have this
![Captur55e](https://user-images.githubusercontent.com/12650820/134605386-be9bf339-460d-4704-959f-512f9e0cc6df.PNG)
Why customers have to choose delivery options on the cart and at checkout, is quite confusing for customers. 
Is there a possibility for me to custom this part?

**Comment by nielslange** [comment]
Hello @msroky 👋

Kindly note that this repository is for development purposes only. Support requests for the WooCommerce Blocks plugin need to be filled on https://wordpress.org/support/plugin/woo-gutenberg-products-block/.
