### ISSUE TITLE
StoreApi: Get session id (switch from react client to hosted WC checkout) 

### ISSUE THREAD

**Issue by florianbepunkt** [woocommerce/woocommerce-gutenberg-products-block#4845]
## Is your feature request related to a problem? Please describe.
The StoreAPI offers lots of possibilities for a headless WooCommerce, using WC as a backend with a React frontend (like Gatsby, Nextjs, etc). While customers should browse products and handling their cart with the React app I would like to redirect them to the actual WC checkout page for the final checkout/payment step. In order to do so I would need the customer's session id, so I can show them the correct cart/checkout.

## Describe the solution you'd like
I would like a way to retrieve the current session id via StoreApi, so I can pass it as a param when redirecting the customer from my React app to the actual WooCommerce checkout page. With the session id I could load the correct session for a given customer

```
// minimal example
add_action( 'woocommerce_load_cart_from_session', function () {
    $session_id = sanitize_text_field( $_GET['session_id'] );
    $handler = new \WC_Session_Handler();
    $session_data = $handler->get_session( $session_id );
}
```

## Describe alternatives you've considered
This might be a bit of an X/Y problem. In a longterm perspective it would be great to have a fully decoupled/headless WooCommerce with a fully headless checkout/payment flow. But currently I don't think all payment providers support this and honestly as a dev I don't feel comfortable enough to do this, so having WooCommerce host only the checkout/payment step is an attractive middle ground imho.

Any alternative ways to retrieve the correct cart (that was created with the StoreApi) inside the WC checkout (despite session id) would also help.

**Comment by mikejolley** [comment]
I'm going to go ahead and close this in favour of https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5683 since both are asking for pretty much the same thing. Thanks.
