### ISSUE TITLE
Error when validating paiment. country is mandatroy

### ISSUE THREAD

**Issue by CrowDz** [woocommerce/woocommerce-gutenberg-products-block#4851]
## Describe the bug

Even if the country field is set, the validation is not OK,

## To reproduce
Add product to cart
Validate cart
Add email, address, credit card ... etc

validate paiment 

## Expected behavior
See thank you page

## Screenshots
Un error is occured with the provided address: the coutry filed is mandatory 
![image](https://user-images.githubusercontent.com/13650328/134991653-cc3abe5c-c223-4344-854e-bd41a2efbd0e.png)

here is the request paylaod:

{"billing_address":{"first_name":"Noure","last_name":"dinne","company":"","address_1":"2 allée des marronniers","address_2":"","city":"Le plessis robinson","state":"","postcode":"92350","country":"FR","email":"jonhdo+1000@gmail.com","phone":"0612121212"},"shipping_address":{"first_name":"Noure","last_name":"dinne","company":"","address_1":"2 allée des marronniers","address_2":"","city":"Le plessis robinson","state":"","postcode":"92350","country":"FR","phone":""},"customer_note":"","should_create_account":false,"payment_method":"stripe","payment_data":[{"key":"paymentMethod","value":"stripe"},{"key":"paymentRequestType","value":"cc"},{"key":"stripe_source","value":"src_1JeS59FDv1kP6SvX9zLzORkS"},{"key":"wc-stripe-new-payment-method","value":false}],"extensions":{}}

as you can see, the country is set in the data.

### WordPress (please complete the following information):
* Core version: 5.8.1
* WooCommerce version: 5.7.1
* WooCommerce Blocks version: 5.9.1
* Site language: FR_fr

**Comment by tjcafferkey** [comment]
@CrowDz I'm unable to replicate this issue, even with the same details you've provided in the payload. Is there anything missing from the replication steps which you may be doing that results in this error?

Any further information to help reliably replicate this would be great.

**Comment by nerrad** [comment]
Hi there @CrowDz,

Thanks for your original report, however we were unable to reproduce and our request for additional information has gone unanswered. We close issues like this after some time has passed to keep our backlog manageable and with things we can eventually action on. 

Even though the issue is closed, you can still come back and add more comments if you more info and we can re-open if we're able to reproduce.
