### ISSUE TITLE
Increase space between error message and form element

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#4865]
## Describe the bug
The coupon error message is very close to the form element. This might decrease the readability. https://www.w3.org/WAI/WCAG21/Understanding/text-spacing.html states for the readability:

> Success Criterion 1.4.12 Text Spacing (Level AA): In content implemented using markup languages that support the following text style properties, no loss of content or functionality occurs by setting all of the following and by changing no other style property:
> 
> - Line height (line spacing) to at least 1.5 times the font size;
> - Spacing following paragraphs to at least 2 times the font size;
> - Letter spacing (tracking) to at least 0.12 times the font size;
> - Word spacing to at least 0.16 times the font size.
> 
> Exception: Human languages and scripts that do not make use of one or more of these text style properties in written text can conform using only the properties that exist for that combination of language and script.

## To reproduce

1. Create a test page and add the checkout block
2. Open the test page in the frontend
3. Provide an invalid code
4. See that the error message is very close to the form element

## Expected behavior

I'd expect to see more space between the form element and the error message.

## Screenshots

<table>
<tr>
<td>Current behavior:
<br><br>

<img width="351" alt="Screenshot 2021-09-29 at 13 47 21" src="https://user-images.githubusercontent.com/3323310/135232452-c0610ce4-6d9d-4eac-b0a4-b722fe0c00df.png">
</td>
<td>Expected behavior:
<br><br>

<img width="347" alt="Screenshot 2021-09-29 at 13 48 41" src="https://user-images.githubusercontent.com/3323310/135232465-02cb1a7e-fccb-44d8-9ddc-a4e0dfe64716.png">
</td>
</tr>
</table>

**Comment by tjcafferkey** [comment]
@nielslange currently the spacing is consistent with other validation messages in the checkout. I think to increase this for coupon codes would create an inconsistency. What do you think?

![Screenshot 2021-09-30 at 09 57 35](https://user-images.githubusercontent.com/8639742/135421410-20ef02e8-00a6-4d14-9dd3-629abba74557.png)

**Comment by nielslange** [comment]
> @nielslange currently the spacing is consistent with other validation messages in the checkout. I think to increase this for coupon codes would create an inconsistency. What do you think?

@tjcafferkey For readability-reasons, I'd adjust the spacing of all error messages.

@vivialice Can we get your input from on design perspective on this issue?

**Comment by vivialice** [comment]
I like the wider spacing - how does this look on stacked forms like in the checkout? Wondering if it could get cluttered in this scenario.

**Comment by nielslange** [comment]
> I like the wider spacing - how does this look on stacked forms like in the checkout? Wondering if it could get cluttered in this scenario.

@vivialice Below, you can find two screenshots how the stacked form looks like. One screenshot shows the current spacing, while the other one shows the adjusted spacing.

<table>
<tr>
<td valign="top">Without spaces:
<br><br>

![#4865-without-spacing](https://user-images.githubusercontent.com/3323310/135794543-ce120da9-0905-48b7-997b-ec941c1d2f5c.png)
</td>
<td valign="top">With spaces:
<br><br>

![#4865-with-spacing](https://user-images.githubusercontent.com/3323310/135794552-c97d80c1-fa80-4772-b06c-d057f18cb7f3.png)
</td>
</tr>
</table>

**Comment by vivialice** [comment]
Thanks for providing these screenshots @nielslange ! We'd need to update the customer-facing field errors across all instances so let me just flag this with the team to make sure we aren't disrupting others.

**Comment by vivialice** [comment]
@nielslange I think we are good to go ahead with these changes 👍
