### ISSUE TITLE
When using the product category, 1 item is missing in the frontend

### ISSUE THREAD

**Issue by jobthomas** [woocommerce/woocommerce-gutenberg-products-block#487]
**Describe the bug**

* Using the sample CSV file in WC core
* Trying to add the Hoodies
* It says 3 in the backend even there are 4, but 4 show up in the backend ![https://cld.wthms.co/mkCi5k](https://cld.wthms.co/mkCi5k+)
* The frontend only shows 3 ![https://cld.wthms.co/ugck8q](https://cld.wthms.co/ugck8q+)

https://jobthomas.mystagingwebsite.com/woocommerce-blocks-test-page/

For reference, in the products section of the dashboard, it says there are 4: 

![https://cld.wthms.co/p4MeSh](https://cld.wthms.co/p4MeSh+)

**To Reproduce**

See above - I can provide log-in creds on the test site. Tested both locally (Local by Flywheel) and on the Pressable test site. 

cc @timmyc 

**Expected behavior**

**Screenshots**

**WordPress (please complete the following information):**

* Core version: 5.1.1
* Gutenberg version (if installed): -
* WooCommerce version: 3.5.6
* WooCommerce Blocks version: 1.4.0
* Site language:
* Any other plugins installed:

**Desktop (please complete the following information):**

* OS: macOS
* Browser FF

**Comment by ryelle** [comment]
Thanks for testing this out! This issue was fixed with https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/406, which will be released with v 2.0 of the plugin/3.6 of WooCommerce– "Hoodie with Pocket" is hidden from display, so it should not appear in the backend preview.

**Comment by timmyc** [comment]
@ryelle beat me to it! Confirmed that was the issue by logging in to the test site. I updated the visibility on the missing hoody to Shop + Store and all was well. I'm going to close this out as it has already been fixed.
