### ISSUE TITLE
Correct WooCommerce branding color

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#4878]
## Describe the bug

Some block icons are still using the old WooCommerce color code `#96588a` instead of the new one `#7f54b3`. This is in violation of the [WooCommerce Brand and Logo Guidelines](https://woocommerce.com/brand-and-logo-guidelines/).

## To reproduce

1. Create a test page.
2. Open the block inserter.
3. Scroll to the section WooCommerce.
4. See the icons using the wrong color.

## Expected behavior

The icons must use the correct color as defined in the [WooCommerce Brand and Logo Guidelines](https://woocommerce.com/brand-and-logo-guidelines/).

## Screenshots

<img width="348" alt="Screenshot 2021-09-30 at 22 07 11" src="https://user-images.githubusercontent.com/3323310/135481623-e0a7e697-9c65-4ec7-8add-7bed3be1e6f8.png">

## Environment

* Core version: 5.8.1
* Gutenberg version (if installed): n/a
* WooCommerce version: 5.8.0-dev
* WooCommerce Blocks version: 6.1.0-dev

## Related issues

- https://github.com/woocommerce/woocommerce/issues/30829
- https://github.com/woocommerce/woocommerce/pull/30586

**Comment by corgoss** [comment]
Hi, I would like to try.

**Comment by nielslange** [comment]
> Hi, I would like to try.

@hafhaf10 Absolutely! Your contribution would be very much welcome. To getting started, you simply need to [set up a development version](https://github.com/woocommerce/woocommerce-gutenberg-products-block#installing-the-development-version) of this plugin. Please let me know if you have any further questions, and good luck with your first contribution! 🙌
