### ISSUE TITLE
Using fewer columns on the backend seems to select the full-width product image, while not on the frontend

### ISSUE THREAD

**Issue by jobthomas** [woocommerce/woocommerce-gutenberg-products-block#488]
**Describe the bug**
When adding any of the blocks that has multiple columns by default, it uses the thumbnails, but on the backend it looks like this will change with reducing the amount of columns. However, this is not the case on the frontend; it's still not wide at all. 

Backend:
![https://cld.wthms.co/EpnR7j](https://cld.wthms.co/EpnR7j+)

Frontend:
![https://cld.wthms.co/W7JCpR](https://cld.wthms.co/W7JCpR+)

https://jobthomas.mystagingwebsite.com/woocommerce-blocks-test-page/

I've tested it with a few different types of blocks that depend on columns and the result is always the same. Wide/full width doesn't really have an effect:

![https://cld.wthms.co/vAxNBD](https://cld.wthms.co/vAxNBD+)
Link to image here: https://cld.wthms.co/vAxNBD.

**To Reproduce**

1. Add any block with columns
2. Reduce the amount of columns to 1
3. On the backend it looks full-width
4. not on the frontend

**Expected behavior**
Frontend and backend give the same result (or at least similar).

**Comment by ryelle** [comment]
This is really down to how woocommerce/the theme handles 1-column shortcodes, I'm not sure if we should change this @LevinMedia @jameskoster – any thoughts?

**Comment by jobthomas** [comment]
The big difference with previous versions of WC is that shortcodes didn't really have a backend preview. Blocks changes this and ideally it would adopt the same or at least a similar preview. 

I'm fairly confident we'll get customers reaching out to us who are frustrated that they can use these blocks full width on the backend, but that it doesn't display frontend.

**Comment by ryelle** [comment]
Right, sorry I didn't mean it isn't a problem– just that I don't think we can change the output code, so we'll only have the 300px image on the front end. We could style the backend preview to max-width at 300px? 

Or we could attempt to override the shortcodes to show the larger image, but then we'll need to override theme styles, and I don't know what other issues that could cause.

**Comment by ryelle** [comment]
Decided to just try updating the preview, I think that's a better solution for something we can get into 2.0-blocks/3.6-core 👍  #489

**Comment by jobthomas** [comment]
> Right, sorry I didn't mean it isn't a problem

Oh, sorry, I also totally didn't want to imply you were thinking that. I just wanted to point out the difference between using Gutenberg and not. And thanks for the PR.
