### ISSUE TITLE
Checkout block and WC Pay result in 'payment_method_data[billing_details][name]' type errors

### ISSUE THREAD

**Issue by melek** [woocommerce/woocommerce-gutenberg-products-block#4880]
## Describe the bug
The Checkout block causes a validation issue when checking out with WC Pay in test mode. I did not test this in live mode.

## To reproduce

1. Install WooCommerce with Storefront, WooCommerce, WooCommerce Blocks, and WooCommerce Payments set to 'Test Mode'.
2. On the checkout page, add a checkout block with a phone field set as Optional.
3. As a guest user in a private window, add an item to cart and try to checkout with no phone number added.
4. See error:  
> You passed an empty string for 'payment_method_data[billing_details][name]'. We assume empty values are an attempt to unset a parameter; however 'payment_method_data[billing_details][name]' cannot be unset. You should remove 'payment_method_data[billing_details][name]' from your request or supply a non-empty value.
5. Try again on the same page. The error repeats.
6. Refresh the checkout page.  Checkout **with a phone number entered** such as 555-555-5555.
7. See error repeat, but with `[phone]` instead of `[name]` (and shows up twice for me)
6. Refresh the checkout page. Optionally remove the phone number, and check out.
7. Checkout succeeds. It appears checkout will continue to succeed for the same guest session, indicating to me there is something session-related happening.

I had this happen when logged in as well with `[phone]`, I think it was because I had no phone number in my profile - but I didn't test that. It was a little finicky, but I can reliably reproduce.

## Expected behavior
No error should occur.

## Screenshots
![Screenshot](https://d.pr/i/uYhZ8u+.png)  
*If you do not see the image, please [click here](https://d.pr/i/uYhZ8u).*

### WordPress (please complete the following information):
* Core version: 5.8.1
* WooCommerce version: 5.7.1
* WooCommerce Blocks version: 6.0.2
* WC Pay Version: 3.0.0
* Site language: US-EN
* Any other plugins installed: Tested with none on client dev site and with Akismet/Jetpack/WP Mail Logging on test site

### Desktop (please complete the following information):
* OS: Windows 10
* Browser Firefox Latest

## Additional context
* I believe this should be considered a high priority bug if it can be verified.
* 4323899-zen

**Comment by nerrad** [comment]
This looks like it is potentially an issue with WooCommerce Payments and not Checkout Blocks given the error appears to be coming from WooCommerce Payments. I'm going to move the issue for initial triage to that repository.
