### ISSUE TITLE
Mismatch behavior between preview and real cart data

### ISSUE THREAD

**Issue by dinhtungdu** [woocommerce/woocommerce-gutenberg-products-block#4884]
## Describe the bug
Working on #4852, I found that we return different preview data based on the `woocommerce_tax_display_cart` option:

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/8f3c29265fae50eeb43f933b261ba6cdd8fca344/assets/js/previews/cart.ts#L200-L202

While it may have little to no effect on the end-users, it's the wrong usage of  `woocommerce_tax_display_cart` IMO. That option should be used to change how the price is displayed, not the price value itself. 

## Expected behavior
The preview data should be the same regardless of `woocommerce_tax_display_cart`. Blocks should take that option into account while displaying the price.

**Comment by mikejolley** [comment]
This setting does change how product prices are returned from the API (not cart totals, just product prices). I'm going to add a note inline to explain this.
