### ISSUE TITLE
Woocommerce Blocks doesn't work with Woocommerce Synced Force Sells.

### ISSUE THREAD

**Issue by Juha83** [woocommerce/woocommerce-gutenberg-products-block#4889]
## Describe the bug
When using Woocommerce Blocks and Woocommerce Force Sells together. It allows users to remove the Synced Force Sell product from the cart.

## To reproduce
Steps to reproduce the behaviour:

1. Go to https://playground.juhakumpula.com/product/windsor/
2. Click on add to cart
3. go to the Cart page
4. The user can remove the handling fee from the cart.

## Expected behaviour
The user should not be able to remove the synced force sells product from the cart.
If using woocommerce default [woocommerce_cart] shortcode, it works like it should be.

### WordPress (please complete the following information):
* Core version: [e.g. 5.0.3]
* Gutenberg version (if installed): [e.g. 4.8.0]
* WooCommerce version: [e.g. 3.5.3]
* WooCommerce Blocks version: [e.g. 1.3.1]
* Site language:
* Any other plugins installed:

### Desktop (please complete the following information):
* OS: [e.g. macOS, Windows]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):
* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Comment by senadir** [comment]
Hi there @Juha83  👋 
Thanks for taking the time to make us aware that WooCommerce Forced Sells isn't working with the Checkout and Cart blocks. These blocks are still in early access (via the feature plugin) and it's expected that some existing Woo Extensions that integrate with the current checkout flow in WooCommerce core will not work with the blocks. 
We're currently working on adding extensibility for the blocks so extensions have a way to make sure they integrate with the new flows being developed. Once that is done we'll have docs prepared and will be reaching out to Woo Extension developers to help them with getting their extensions integrated.
Until then you can keep on top of the [status of the Cart & Checkout Blocks in this documentation](https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/).
