### ISSUE TITLE
Bad page checkout loading

### ISSUE THREAD

**Issue by msroky** [woocommerce/woocommerce-gutenberg-products-block#4914]
Here I made a video of how my checkout page loading

https://i.imgur.com/GYWSd54.mp4

It looks really bad and it instills mistrust among customers. I wish you could fix that and add some loading animation.

**Comment by ralucaStan** [comment]
Hello @msroky,
Sorry to hear that you are having this issue. 
The Checkout block has indeed a loading step, it is also visible in your video as well. The issue I see is that the footer jumps to the top, which should not be the case. I am thinking this might be particular to your website. Could you provide a link to check if that is the case?

**Comment by opr** [comment]
Hi there @msroky the video you attached seems to have stopped working, I've recorded a new one and created a new issue which covers both the Checkout _and_ the Cart blocks, as this happens on both.

I am closing this issue in favour of #5011, you may follow #5011 for updates. Thanks again for reporting this!
