### ISSUE TITLE
Flaky e2e tests failing with "TypeError: Cannot read property 'id' of undefined"

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#4916]
Every once in a while, e2e tests fail in the GitHub Action even though they pass locally.

The error is: `TypeError: Cannot read property 'id' of undefined`. (Heads-up that there is an open issue that mentions this same error message: https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/2441)

An example of a failed run can be found here: https://github.com/woocommerce/woocommerce-gutenberg-products-block/runs/3819264239

**Comment by dinhtungdu** [comment]
@Aljullu Note that the error in #2441 is different from the one causing failed E2E test. The E2E tests fail because the cart/checkout test page isn't always created.

**Comment by mikejolley** [comment]
I didn't notice this issue, but have been seeing the ID error. I added https://github.com/woocommerce/woocommerce-gutenberg-products-block/commit/5aabb28f4bacbac02c044d215ef99beee0a62fab the other day as a workaround and so far I haven't seen any fails from e2e for this.

**Comment by Aljullu** [comment]
I think we can close this issue and if the failing tests appear again either reopen or create a new one, but currently there isn't anything actionable.
