### ISSUE TITLE
Remove extra files/folders in built zip

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#4928]
As of WooCommerce Blocks 6.1.0, those files are in the final zip:

- [x] patches (only needed when building)
- [x] packages (is a source folder, not needed on final build)
- [ ] inbox-notifier (seems like an empty folder, cc @opr)
- [x] global.d.ts (dev file)
- [x] tsconfig.base.json (dev file)

We should skip them on our build zips.

**Comment by nielslange** [comment]
Related: #4725 & #4929

**Comment by nielslange** [comment]
@senadir I addressed this issue in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5234 and wanted to let you know that I could not find a `inbox-notifier/` folder, but I excluded the `reports/` folder in addition, as that folder only contains the e2e test report, which is not relevant for the deploy zip.
