### ISSUE TITLE
Convert Single Product PHP template into a basic PHP-rendered block template

### ISSUE THREAD

**Issue by frontdevde** [woocommerce/woocommerce-gutenberg-products-block#4934]
To better understand the complexity of this endeavor, we’ll start by going through the steps outlined for the _Single Product WooCommerce template_ only. This will allow us to get a clearer picture of the tasks involved in creating more complex block templates, uncover potential gaps and enable us to give a more confident estimate on the overall scope of this project.

**Comment by tjcafferkey** [comment]
Closing this issue as it was completed as part of this experimental PR https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/4939
