### ISSUE TITLE
Identify which WooCommerce templates to convert to block templates

### ISSUE THREAD

**Issue by frontdevde** [woocommerce/woocommerce-gutenberg-products-block#4935]
First, we will need to identify which top-level WooCommerce templates to convert. In the spirit of shipping early, we’re not looking to convert every template immediately but instead focus on shipping the ones that have the highest benefit to merchants first.

**Comment by tjcafferkey** [comment]
@Aljullu have you any thoughts on this issue? I think the obvious ones are perhaps:

* `single-product.php`
* `archive-product.php`
* `single-product-reviews.php`

I suppose once we have the approach/framework in place to be able to convert each template we can do this progressively/iteratively?

**Comment by Aljullu** [comment]
I wonder if `taxonomy-product-cat.php` and `taxonomy-product-tag.php` should be in that list as well.

> `single-product-reviews.php`

I'm not sure about this one, my understanding is that it's used to replace the comment template from WP core, right?

> I suppose once we have the approach/framework in place to be able to convert each template we can do this progressively/iteratively?

For the Feature Plugin, I think that's fine (we will probably need to [feature gate](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/blocks/feature-flags-and-experimental-interfaces.md) these changes). Then, once all templates have been converted and released in the Feature Plugin, I think we should enable all of them at once in WC core. Does that sound good?

**Comment by frontdevde** [comment]
It’d be good to reach a decision here as to what templates we **must** include in v1. 
Summarising that as per the discussion so far, the consensus includes 
`single-product`, `archive product`, `taxonomy-product-cat` and `taxonomy-product-tag`.
Can we agree on these? cc @Aljullu @nerrad 

Edit: just noting that we'll probably be able to easily add more once the key parts are in place. This is just about agreeing on a list of templates that are essential for the initial v1 (think MVP).

**Comment by nerrad** [comment]
Okay so I agree that this list should be prioritized as the templates that _must_ be done:

- single-product
- archive-product
- taxonomy-product-cat
- taxonomy-product-tag

It looks like `single-product-reviews.php` does replace the comment template on the single product page. So it's possible we _might_ have to pick that up as well to provide accurate 1:1 parity with current php based templates for the single product page. It seems to me it would work best as a template part maybe - but you can take a look at the work being done for the Comments block in Gutenberg to see if there's anything we can learn from that work here.

> For the Feature Plugin, I think that's fine (we will probably need to feature gate these changes). Then, once all templates have been converted and released in the Feature Plugin, I think we should enable all of them at once in WC core. Does that sound good?

Given Woo Blocks 6.3.0 is the next release we're going to be targeting with block templates support, I think we can forgo feature gating this - we can revisit if we're not able to hit that target.

**Comment by Aljullu** [comment]
@frontdevde should we close this issue now that you have created the issues for the identified templates?

- https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5032
- https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5033
- https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5034
- https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5035

Regarding single-product-reviews, we can review it in a later stage, but I don't think we need keep this issue open for it.

**Comment by frontdevde** [comment]
I thought of keeping it open because of `single-product-reviews`. But happy to close :)
