### ISSUE TITLE
Update workflows to support forks (which have read-only privilege only)

### ISSUE THREAD

**Issue by ralucaStan** [woocommerce/woocommerce-gutenberg-products-block#4942]
PRs opened from forked repos fail on the JS linting step, as seen in [this PR](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/4920/checks?check_run_id=3869029213).

This happens because jobs running on the forked repos can't upload artefacts.

## Additional context
See this internal Slack conversation for additional context p1634034758497900-slack-C8X6Q7XQU

**Comment by mikejolley** [comment]
Closing due to pca54o-6Dz-p2
