### ISSUE TITLE
"No payment method provided" error at checkout if cart total is 0

### ISSUE THREAD

**Issue by dubfonik** [woocommerce/woocommerce-gutenberg-products-block#4948]
## Describe the bug
Using the Checkout block, if cart total is 0 (either by produce price or use of a coupon), and no payment methods are defined, the checkout cannot be completed. Error **No payment method provided** appears.

I am able to proceed if using the standard `[woocommerce_checkout]`, but not with the new WooCommerce Block version

## To reproduce

1. Disable payment methods
2. Add a $0 product, or use a coupon code with 100% discount
3. Attempt to checkout

## Expected behavior
We should be able to checkout if the cart total is 0.

### WordPress (please complete the following information):
* Core version: [e.g. 5.8.1]
* WooCommerce version: [e.g. 5.8.0]
* WooCommerce Blocks version: [e.g. 6.1.0]
* Site language: english
* Any other plugins installed:

### Desktop (please complete the following information):
* OS: Windows 10
* Browser Brave
* Version 1.30.87 Chromium: 94.0.4606.71 (Official Build) (64-bit)

## Additional context
Checkout works as expected if using the original (non-Blocks) version of WooCommerce Checkout

**Comment by ralucaStan** [comment]
Hi @dubfonik, 👋 
thank you so much for taking the time to bring this to our attention.

We have added a high priority to this ticket and we will work on this as soon as possible.

For the developer picking this ticket, details about why this is happening can be found in this internal discussion p1634292524196700-slack-C8X6Q7XQU.

**Comment by aheckler** [comment]
4391620-zen

**Comment by darcie** [comment]
32091056-hc
