### ISSUE TITLE
Mini Cart and Navigation blocks conflict

### ISSUE THREAD

**Issue by grogou** [woocommerce/woocommerce-gutenberg-products-block#4952]
## Describe the bug
The Mini Cart and Navigation blocks are using `window.onload` event, first for lazy load scripts, second one for init some MicroModal. So if I use these blocks on same page, only work the second rendered block action. In my case I have 

After some research.

I replaced `window.onload` to `window.addEventListener('load',function(){})`
Using this method ensures that the handler is additive and does not replace existing handlers. 
And the 2 blocks works properly.

## Screenshots 
![image](https://user-images.githubusercontent.com/10712881/137478512-59df0bb0-244b-42b3-99bf-a30debd46400.png)
this and mini cart is not working. 

## Testing steps
1. Make sure you have Gutenberg and Woo Blocks plugins installed
2. Create a new page and add the Mini cart block first
3. Save the page and go to the site to see the Mini cart block working
4. Go back and add the Navigation block after the mini cart
5. Save the page and go to the front-end to see the page
6. Notice that the Mini Cart block stopped working.

## Expected behaviour
The Mini cart block should work.

**Comment by Aljullu** [comment]
Good catch with this issue, @grogou!

I added this to the Mini Cart project so we can take a look at it and fix it. Thanks for letting us know!

I wonder if we should also create an issue in Gutenberg regarding this. Rewriting what is in `window.onload` might break some other plugins besides WC Blocks. What do you think?

**Comment by grogou** [comment]
@Aljullu I think we need to change it in both places, so if you need I can create same issue on Gutenberg too, because `addEventListener` more scalable. But the only thing I can't understand, why this case works clean on TT1 Blocks theme, it is strange.

**Comment by Aljullu** [comment]
Yes, I think it might be worth raising this issue in Gutenberg as well and see what they think about it. If you can create it, that would be perfect, thanks! :ok_hand:

**Comment by grogou** [comment]
@Aljullu we have answer from Gutenberg. https://github.com/WordPress/gutenberg/issues/35768 . So they added this to Navigation block todo list.

**Comment by Aljullu** [comment]
Thanks for bringing that upstream @grogou!

**Comment by ralucaStan** [comment]
I have updated the issue description with `Testing steps` and `Expected behaviour` sections for better understanding.
