### ISSUE TITLE
Long term goal: Full site editing/FSE?

### ISSUE THREAD

**Issue by strarsis** [woocommerce/woocommerce-gutenberg-products-block#4953]
Is the long term goal also Full site editing/FSE of WooCommerce?
That it is possible to place the cart/product list (archive)/single product elements in Gutenberg editor?
Or should this be kept in the theme domain?

**Comment by opr** [comment]
Hi there @strarsis - thanks for your question.

You might like to check out the [WooCommerce Blocks Roadmap post](https://developer.woocommerce.com/2021/08/31/peek-into-the-woocommerce-blocks-roadmap/) which has a little more information about our FSE goals in WooCommerce Blocks.

I hope this quote from that post will answer your question:

> We are working diligently to bring the best of full site editing to the WooCommerce environment for the benefit of merchants and shoppers alike. Increased site performance, high quality blocks, and optimized patterns will empower merchants to maximize conversion while retaining their unique storefront.
