### ISSUE TITLE
Compatibility notice styles are missing in the Site Editor

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#4954]
## To reproduce

1. Activate the latest version of Gutenberg and a block theme (ie: [TT1 Blocks](https://wordpress.org/themes/tt1-blocks/)).
2. Go to Site Editor.
3. Add the Mini Cart block.
4. Notice the compatibility notice styles are not correctly loaded:

![imatge](https://user-images.githubusercontent.com/3616980/137689875-b6b71985-34bd-45d7-9156-016dc28166f7.png)

**Comment by dinhtungdu** [comment]
#5147 also fixes the extra space bug in the notice content:

![image](https://user-images.githubusercontent.com/5423135/141955779-33d4aa2e-5ea1-4899-aa86-9cf5ff001864.png)
