### ISSUE TITLE
The update to 6.1.0 triggers an error on the checkout page.

### ISSUE THREAD

**Issue by DarianDev** [woocommerce/woocommerce-gutenberg-products-block#4958]
## Describe the bug
The update to 6.1.0 kills the checkout page. 

"Something went wrong…

The checkout has encountered an unexpected error. Try reloading the page. If the error persists, please get in touch with us so we can assist.

Error: Cannot read property ‘call’ of undefined`"

## To reproduce

1. Update to 6.1.0
2. Click on 'Checkout'
3. See error

## Expected behavior
Fix the Error, and display the Checkout Page normally 

### WordPress (please complete the following information):
* Core version: 5.8.1
* Gutenberg version (if installed): [e.g. 4.8.0]
* WooCommerce version: 5.8
* WooCommerce Blocks version: 6.1.0
* Site language: german

### Any other plugins installed:
* Advanced Order Export For WooCommerce: version: 3.1.9, author: AlgolPlus
* Elementor: version: 3.4.5, author: Elementor.com
* Favicon by RealFaviconGenerator: version: 1.3.22, author: Philippe Bernard
* Kadence WooCommerce Email Designer: version: 1.4.8, author: Kadence WP
* Microsoft Advertising Universal Event Tracking (UET): version: 1.0.3, author: Microsoft Corporation
* Orbit Fox Companion: version: 2.10.8, author: Themeisle
* Rank Math SEO: version: 1.0.74, author: Rank Math, Automatische Aktualisierungen aktiviert
* Schema & Structured Data for WP & AMP: version: 1.9.85, author: Magazine3
* WooCommerce: version: 5.8.0, author: Automattic
* WooCommerce Blocks: version: 6.0.2, author: Automattic (latest version: 6.1.0)
* WooCommerce Payments: version: 3.1.0, author: Automattic
* WooCommerce PayPal Payments: version: 1.6.1, author: WooCommerce
* WooCommerce PDF Invoices & Packing Slips: version: 2.10.1, author: Ewout Fernhout
* WooCommerce Pixel Manager: version: 1.11.6, author: woopt
* WooCommerce Stripe Gateway: version: 5.6.2, author: WooCommerce
* WP Rollback: version: 1.7.1, author: Impress.org

### Desktop (please complete the following information):
* OS: Windows and Mac
* Browser: Chrome & Safari = every Browser

### Smartphone (please complete the following information):
* Device: all devices
* OS: all os versions
* Browser: all Browsers

## Additional context

https://wordpress.org/support/topic/6-1-0-killed-my-checkout-page/?#post-14976099

**Comment by senadir** [comment]
Hi there! we're aware of the error and working on identifying a fix.

Currently, you can downgrade to 5.9.1 or disable Elementor for the error to go.

**Comment by nerrad** [comment]
To be clear to those following this issue, none of the development team has been able to reproduce the bug some folks are experiencing as reported here. While the common thread seems to be having Elementor installed, our dev team has also tried to reproduce with the latest  free version of Elementor without success.

If anyone reproducing this can share additional details about your setup including:

- What theme you are running.
- How you've setup your checkout page.
    - Do you just have the Checkout block installed? 
    - Does the block appear as expected in the native WordPress page editor?
    - How is the block configured?
- Who is hosting your store? There is possibility that this may be a caching issue and if we discover another common thread is folks having their sites on the same host that will help narrow that down.
 
With answers to these questions, hopefully we'll be able to reproduce the issue and that will enable us to identify what potential fixes there may be and where they should be done.

**Comment by nerrad** [comment]
So I spent a bit of time debugging this myself today and while I still am unable to reproduce the reported error, I did discover that in some cases (depending on the theme in use), if you have an existing page with the checkout block and then go to edit it with Elementor, the block will produce a bunch of errors on the frontend related to unregistered payment methods (likely loading to issues with loading order in the Elementor context). If you then add something to the page using Elementor and save, this breaks the block on any future loads (because Elementor doesn't preserve the correct block structure on save).

For reference I used OceanWP theme for testing (since that's what one user had in their system report). Notable that the theme advertises itself as Elementor compatible.

So I wonder if there's some way a the content can get into a bad state with using Elementor to edit a page that is leading to this error? Until we get more information from users though, there's not much we can do.

I suspect at least part of the issue is that Elementor doesn't really integrate well with Gutenberg. It appears it's model doesn't account for WordPress blocks and when you edit a page in Elementor it essentially takes over the page editing experience.

**Comment by DarianDev** [comment]
> To be clear to those following this issue, none of the development team has been able to reproduce the bug some folks are experiencing as reported here. While the common thread seems to be having Elementor installed, our dev team has also tried to reproduce with the latest free version of Elementor without success.
> 
> If anyone reproducing this can share additional details about your setup including:
> 
> * What theme you are running.
> * How you've setup your checkout page.
>   
>   * Do you just have the Checkout block installed?
>   * Does the block appear as expected in the native WordPress page editor?
>   * How is the block configured?
> * Who is hosting your store? There is possibility that this may be a caching issue and if we discover another common thread is folks having their sites on the same host that will help narrow that down.
> 
> With answers to these questions, hopefully we'll be able to reproduce the issue and that will enable us to identify what potential fixes there may be and where they should be done.

Hello,

here are some more information:

Theme: Neve

Only have installed the Checkout Block

yes the block appear as expected in the native WordPress page editor

The block is configured as followed: 

Host is "one.com" no caching activ

Pictures:

![1](https://user-images.githubusercontent.com/17782319/138349671-04fd452c-b5cd-4e2b-9fd1-ec5f210206d3.PNG)
![2](https://user-images.githubusercontent.com/17782319/138349675-fe06207d-a991-4a55-ae9a-f6406e0142c5.PNG)
ated 



Hope that information helps, if you need more information you can come back to me i try to help.

**Comment by nerrad** [comment]
@DarianDev have you tried deleting the block in the editor (don't copy or cut it), re-adding it from the block inspector, and then saving?

Another thing you could try is creating a new page, add the block to it, and then set that page as the checkout page  in your WooCommerce settings.

**Comment by DarianDev** [comment]
@nerrad 

both suggestions doesnt help out. still got the same error

**Comment by nielslange** [comment]
@DarianDev Do you see the same error when running a [conflict test](https://docs.woocommerce.com/document/how-to-test-for-conflicts/)?

**Comment by DarianDev** [comment]
@nielslange yes

**Comment by nielslange** [comment]
Could you create a fresh test site, e.g. using a subdomain, on one.com, to see if the same problem also appears on a brand-new site? I'm asking as so far, we haven't been able to reproduce the problem that you are facing.

**Comment by nerrad** [comment]
Also, could you try putting the block on a different page (that isn't designated as the Woo Checkout page) and give us a link to that page? If there's an error when it's added to a separate page, we can take a look and see what additional info we might be able to get.

**Comment by nerrad** [comment]
I missed this before, but I see you are using WooCommerce Payments, I wonder if this may be related. Without seeing the error stack trace for the error happening its hard to know if this is the cause or not.

@senadir it'd be good to see if this is a common element across those having issues (usage of WooCommerce Payments) and maybe see if the problem can be reproduced with it active.

Another possibility is I see that this website is using cloudflare rocket loader. @DarianDev, do you have the ability to disable that just for your checkout pages? If so, could you try that and see if it fixes the issue?

**Comment by DarianDev** [comment]
Error was with cloudflare, clear cloudflare cache and reenable rocket loader
