### ISSUE TITLE
Cart i2: additional classes for inner blocks do not appear on the front-end

### ISSUE THREAD

**Issue by ralucaStan** [woocommerce/woocommerce-gutenberg-products-block#4962]
## Describe the bug
When adding a custom class in the editor for any Cart i2 inner block, the class is not added in the front-end

## To reproduce

1. Go to the editor and add the Cart i2 block
2. Click on the Order summary inner block
3. On the block's setting sidebar click Advanced and add a `my-order-summary` class under `Additional CSS class(es)`
4. Go to the frontend and see that the class does not appear in the frontend
5. Go back to the editor and notice that the class `my-order-summary` is still there

## Expected behavior
The class should appear in the front-end

**Comment by mikejolley** [comment]
This is related to https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4867 and the same issue as in https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4963
