### ISSUE TITLE
Update Cart in Checkout/Cart

### ISSUE THREAD

**Issue by tarimella** [woocommerce/woocommerce-gutenberg-products-block#4977]
When you are on the checkout/cart page, you cannot update the cart. You have to go to the cart page, empty items and then add them again. I don't want to lose anyone in that process.

Add a dropdown below the item quantity - 0-1-2-3 options and then an "update cart" button on both pages.

**Comment by opr** [comment]
Hi there @tarimella thanks for leaving your feedback about WooCommerce blocks.

It's not possible to change the quantities on the **Checkout** block, but it should be working fine on the Cart block.

Could you provide a little more information about what you're seeing and why you need to empty the items before adding them again?

Here's how quantity-changing on the Cart block should be working:
https://www.loom.com/share/90f352fd98b346b3a71e1c6493df11b1

**Comment by tarimella** [comment]
I only see “remove item”…there is no option to update the cart on my end. Could you check? 

Pantherssocceracademy.com/cart
______

Tania Ulloa-Malavé
Brand Consultant & Designer    
TARIMELLA DESIGNS

m. 216.235.1536
t.   614.602.2420
w3 tarimella.com   
s.  twitter. facebook. linkedin

**Comment by nerrad** [comment]
Hi there @tarimella 

Thanks for sharing a link to your site. In looking at the page source, the quantity selector is actually present there, but the current styling hides the inputs. I see that the cart block has the dark mode inputs configured (which is typically only toggled when the cart is used on a theme with dark backgrounds).

This is controlled via the settings for the cart block when you edit the page containing it. When you select the cart block, you'll see something like this in the block inspector controls:

![CleanShot 2021-10-20 at 13 26 34@2x](https://user-images.githubusercontent.com/1429108/138141906-810a84c9-6ecd-44de-8cb5-bff0ad45de8e.png)

If you ensure that is toggled off, it should fix the issue you see with the hidden quantity control.

**Comment by tarimella** [comment]
You’re absolutely right! Sorry about that…and thank you! 
______

Tania Ulloa-Malavé
Brand Consultant & Designer    
TARIMELLA DESIGNS

m. 216.235.1536
t.   614.602.2420
w3 tarimella.com   
s.  twitter. facebook. linkedin
