### ISSUE TITLE
Featured Product Block Search is Broken

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#4983]
## Describe the bug
On a store with a large number (+100) products, search appears to be broken when using the Featured Product Block. On a smaller catalog you can simulate this by editing the values in:

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/5f34c86072936ac908a93c49881775d21df69a6a/assets/js/editor-components/utils/index.js#L19

## To reproduce
Steps to reproduce the behaviour:

1. Have a large catalog, or edit the function above so it does requests to the API
2. Insert Featured Product Block
3. Enter a search term for a product not visible in the list
4. No results. Query has `search=&` in it.

## Expected behaviour
It should do the query and return the filtered results.

This was reported here: https://wordpress.org/support/topic/feature-product-not-wordking-correcly/ I reproduced it locally.

**Comment by dianfishekqi** [comment]
Maybe related https://github.com/10up/ElasticPress/issues/2371
