### ISSUE TITLE
Special chars show up encoded in the checkout block under the "Shipping" section

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gutenberg-products-block#4987]
## Describe the bug

Special chars show up encoded in the checkout block under the "Shipping" section.

## To reproduce

1. Under WooCommerce -> Settings -> Shipping, create a shipping zone for the US
2. Add a shipping method to the zone and edit it
3. In the "Method title" field, add a name containing some special chars. For example "Le shipping method - special" and save
4. Add a product to the cart and proceed to the block checkout
5. Add a shipping address in the US so the newly added shipping method shows up
6. Notice the "-" character is encoded. This happens for other special chars as well
![image](https://user-images.githubusercontent.com/41606954/138762325-fbf86575-810c-4411-96db-f6f3a20b661f.png)

## Expected behavior

I'd expect the shipping method name to be displayed on WooCommerce's settings page, without chars being encoded.

### WordPress (please complete the following information):
* Core version: 5.8.1
* Gutenberg version (if installed): 
* WooCommerce version: 5.8.0
* WooCommerce Blocks version: 6.1.0
* Site language: EN
* Any other plugins installed: WooCommerce Payments 3.1.0 / WooCommerce Payments Dev Tools

### Desktop (please complete the following information):
* OS: macOS
* Browser: chrome
* Version: 94.0.4606.81

**Comment by nielslange** [comment]
I briefly looked into this problem and these are my findings:

1. I created the shipping method `Flat Rate` and renamed it to `> Flat Rate <`.
2. I looked up the shipping method in the database and found the following entry:
```
a:3:{s:5:"title";s:19:"&gt; Flat rate &lt;";s:10:"tax_status";s:7:"taxable";s:4:"cost";s:1:"0";}
```
3. The cart block shows the correct value, and the corresponding part can be found on https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/34e367ff1c8b020cd93dba27849f480a3c842ec0/assets/js/base/components/radio-control/option-layout.tsx#L17-L24
4. The checkout block shows the wrong value, and the corresponding part can be found on https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/34e367ff1c8b020cd93dba27849f480a3c842ec0/assets/js/base/components/cart-checkout/totals/shipping/shipping-via.tsx#L12-L15

I haven't got a fix for this problem yet, but wanted to share my findings, in case someone else picks up this teas meanwhile.
