### ISSUE TITLE
Experimental Interface Review and Update

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#4996]
We have a number of experimental interfaces within the WooCommerce Blocks feature plugin that have been audited as a part of a process for evaluating their stability. As a part of this audit, interfaces are determined to be one of the following:

- **Graduate** to stable - we're confident that we can support the public contract of the interface and are ready to remove the experimental prefix.
- Leave as is - we're still not sure the interface should remain as is, so it'll stay experimental until the next audit.
- **Review** - Some further investigation is needed before we can determine one way or another.
- **Retire**/remove - there will be a period of deprecation but we will remove the interface (either in favor of something else that is available, or simply because it's not something worthwhile supporting).

Issues attached to this epic will have one of the bolded words from the list above in the title to help differentiate what next for the interface.

Once all the attached issues are complete, the following would be some great next steps:

* [ ] Publish a post on developer.woocommerce.com highlighting all the interface changes as a part of this work.
* [ ] Link to the post on the internal Woo Engineering P2 to ensure teams are aware.

**Comment by ralucaStan** [comment]
Closing this epic as the issues have been addressed. Communication will happen as a result of the internal meetings around accessibility. CC @opr
