### ISSUE TITLE
Review `__experimentalRegisterCheckoutFilters` and `__experimentalApplyCheckoutFilter` JS filters

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#5000]
These two JavaScript filters are exposed on the `@woocommerce/blocks-checkout` exposed global and allow registering and applying a filter to certain parts of the Cart and Checkout Block. 

While these have been in place for a while (nearly a year) there may still be [some concerns around performance](https://href.li/?https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/4570). So the purpose of this issue is to

- Review the actual performance impact of these filters.
- Evaluate if there is work that can be done to either improve the performance of the filters or mitigate the peripheral impact (such as a containing component re-rendering more than it needs to).
- It might be good to see if we can add some sort of executing time limit on callbacks executed by this filter and bail the execution if it's over ms?

Things to do if it's decided we can graduate:

* [ ] Introduce a new action with the experimental prefix removed.
* [ ] Deprecate the old action (so it will still fire, but have it throw a deprecated developer notice pointing to the new name.
* [ ] Update inline code documentation.
* [ ] Update any other documentation.
* [ ] Check this action off in the list

**Comment by ralucaStan** [comment]
I did not test the performance impact of rerunning the filter registered functions but I've reviewed @opr's [PR](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5143#pullrequestreview-890045327) that prevents the functions from rerunning. It does not go to the root of the problem, aka why are we calling the functions when the parameters don't change, but it does prevent unnecessary reruns.

I say it's a good workaround and fix to this issue.

**Comment by ralucaStan** [comment]
> I did not test the performance impact of rerunning the filter registered functions but I've reviewed @opr's [PR](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5143#pullrequestreview-890045327) that prevents the functions from rerunning. It does not go to the root of the problem, aka why are we calling the functions when the parameters don't change, but it does prevent unnecessary reruns.
> 
> I say it's a good workaround and fix to this issue.

Considering the work done here I am going to close this issue for now.
