### ISSUE TITLE
Cart/Checkout blocks' loading placeholders disappear for a few seconds before the block fully loads

### ISSUE THREAD

**Issue by opr** [woocommerce/woocommerce-gutenberg-products-block#5011]
## Describe the bug
The Cart and Checkout blocks' loading placeholders disappear before the blocks are fully loaded.

## To reproduce

1. Go to the Cart block with an item in your cart.
2. Notice the loading placeholder disappears well before the actual block loads in.
3. Refresh the page and notice it again.

## Expected behavior
There should be a seamless transition between the loading state and the actual block.

## Screenshots
https://www.loom.com/share/64554bccbbde46b1b239fe0870d93eb0

**Comment by msroky** [comment]
Loading cart and checkout pages is still very bad, empty space is displayed first (as if the page does not exist) and only after a few seconds everything is loaded, my customers for this reason leave these two pages. Please fix this as soon as possible.

I made a video of what it looks like: https://i.imgur.com/6e8iuQX.mp4

On a mobile phone it looks even worse, the elements move as if falling apart. 

I use the latest version of the wordpress theme http://preview.themeforest.net/item/salient-responsive-multipurpose-theme/full_screen_preview/4363266
