### ISSUE TITLE
New Block: Products by Tag(s)

### ISSUE THREAD

**Issue by vburghelea** [woocommerce/woocommerce-gutenberg-products-block#503]
**Is your feature request related to a problem? Please describe.**
We're unable to use product tags to filter products in landing pages.

**Describe the solution you'd like**
One of the ways we want to be able to display products in landing pages is based on tags. This is very similar to #243 - except using the tags taxonomy.

**Describe alternatives you've considered**
We're currently looking at implementing a tag-to-attribute workaround, but it would be great if we could just use tags.

**Additional context**
Can't think of anything - #243 is pretty much on point, except on a different taxonomy.

**Comment by ryelle** [comment]
Thanks for the suggestion! We'll look at adding this in a future version.

**Comment by warrendholmes** [comment]
@vburghelea I'm curious to the reason why you chose to use tags instead of attributes or categories?

**Comment by vburghelea** [comment]
The main reason for wanting to go with tags is that it makes it possible for content editors to specify certain products that should be displayed in a landing page manually, without affecting generic structures. Attributes are tougher to customize and we use product categories in a slightly different manner: we sell events and attach a GPS location to categories (we use them as cities), so architecturally speaking, a product can't belong to multiple categories - we have a few assumptions in our code surrounding that. This would enable us to maintain our product category metaphor, while at the same time making landing page creation more flexible for content editors.

**Comment by timmyc** [comment]
After chatting with @ryelle she noted the following as next steps for this block:

- Create a new control, `ProductTagControl`, following `ProductCategoryControl` or `ProductsControl`
- Update the `getShortcode` and `getQuery` functions to handle tag queries
- For the block itself, look at the Products by Category block
