### ISSUE TITLE
Compatibility issue with woocommerce-booking

### ISSUE THREAD

**Issue by ankitguptaindia** [woocommerce/woocommerce-gutenberg-products-block#5039]
## Describe the bug
When a site has WooCommerce Booking extension enabled and admin trying to activate woocommerce-gutenberg-products-block extension on site then the site triggers a Fatal error. If disable WooCommerce Booking then the plugin works as expected. 

`Fatal error: Uncaught TypeError: Automattic\WooCommerce\Blocks\Integrations\IntegrationRegistry::register(): Argument #1 ($integration) must be of type Automattic\WooCommerce\Blocks\Integrations\IntegrationInterface, Automattic\WooCommerce\Blocks\Payments\Integrations\Cheque given, called in /Users/ank/Local Sites/woolocal/app/public/wp-content/plugins/woo-gutenberg-products-block/src/Payments/Api.php on line 115 and defined in /Users/ank/Local Sites/woolocal/app/public/wp-content/plugins/woo-gutenberg-products-block/src/Integrations/IntegrationRegistry.php on line 62`

## To reproduce

1. Go to Dashboard > Plugins
2. Install and activate WooCommerce Gutenberg Products Block Extension
3. Enable debug true in wp-config file
4. Activate WooCOmmerce Booking extention.
5. Check error log or WP plugins page

## Expected behavior
Both extensions should work without any error. 

## Screenshots
![image](https://user-images.githubusercontent.com/6384299/139433933-787ad3ea-1a21-41d2-9654-2c4a4db1432b.png)

## Environment

* WordPress: 5.8.1
* Theme: Storefront - Version: 3.9.1
* WooCommerce - Version 5.8.0
* WooCommerce Blocks - 6.2.0
* PHP: 8.0.0 
* Web Server: nginx
* Browser: Chrome Version 94.0.4606.81
* OS: macOS Big Sur V 11.5.1
* Active Plugins -  WooCommerce and WooCommerce Blocks

## Additional context

https://user-images.githubusercontent.com/6384299/139435401-888ddf09-57b9-4b21-acb5-eadb2d53f8d9.mp4

**Comment by ankitguptaindia** [comment]
Found issue at the time of working on this https://github.com/woocommerce/woocommerce-gateway-payfast/issues/46

**Comment by nerrad** [comment]
Howdy @ankitguptaindia,

Unfortunately, I'm unable to reproduce this either locally, or on another test site:
![CleanShot 2021-11-01 at 14 25 22](https://user-images.githubusercontent.com/1429108/139721877-789f1864-3a47-4746-9648-3e192fb81912.gif)

There might be some other conflict happening in your environment maybe? You mentioned you are testing with the Payfast extension, is that active in your test environment and if you deactivate the extension do you still see the issue?

The error you are reporting is really puzzling as well because `Automattic\WooCommerce\Blocks\Payments\Integrations\Cheque` which is reported as triggering the error is in fact an instance of `Automattic\WooCommerce\Blocks\Integrations\IntegrationInterface`. So it's puzzling why that error would be triggered.

In case this is PHP version related, I updated my local dev to use PHP 8 and still no error or issues with activating bookings.

**Comment by ankitguptaindia** [comment]
Hello, @nerrad Thanks for checking this scenario.

This is a _STRANGE_ issue for me as well. I tried this on 3 new setup and this is working fine on all new setup. But when I use my regular testing setup, I am still getting same Fatal error. I am assuming this is happening due to any setting on my current setup. 
After playing here I found one more scenario, if I enabled `WooCommerce Stripe Gateway` plugin then this error is no more and new error is appearing when creating new post/page.


![Screenshot 2021-11-11 at 1 59 21 PM](https://user-images.githubusercontent.com/6384299/141264327-28b99e1b-3739-4cf9-b052-0e65a85cf046.png)


Let me show all these scenarios in the below video-
-----


https://user-images.githubusercontent.com/6384299/141266285-b861d0bf-d82d-42fb-a2a3-2f23c9dc1564.mp4


For my setup Configuration, I added detailed info here- 
-----

<Details>

`
### WordPress Environment ###

WordPress address (URL): https://hidden-sailfish.jurassic.ninja
Site address (URL): https://hidden-sailfish.jurassic.ninja
WC Version: 5.9.0
REST API Version: ✔ 5.9.0
WC Blocks Version: ✔ 6.2.0
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.8.0
Log Directory Writable: ✔
WP Version: 5.8.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.51 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.25
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.9.0
WC Database Prefix: wp_
Total Database Size: 4.50MB
Database Data Size: 2.99MB
Database Index Size: 1.51MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.03MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 2
page: 9
post: 3
product: 1
revision: 1
shop_order: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (4) ###

Companion Plugin: by Osk – 1.18
WooCommerce Blocks: by Automattic – 6.2.0
WooCommerce Bookings: by WooCommerce – 1.15.48
WooCommerce: by Automattic – 5.9.0

### Inactive Plugins (4) ###

Akismet Anti-Spam: by Automattic – 4.1.12
Hello Dolly: by Matt Mullenweg – 1.7.2
Jetpack: by Automattic – 10.3
WooCommerce Stripe Gateway: by WooCommerce – 5.7.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 13
Oldest: 2021-11-10 09:03:23 +0000
Newest: 2021-11-11 08:18:00 +0000

Pending: 2
Oldest: 2021-11-12 08:16:33 +0000
Newest: 2021-12-10 15:03:49 +0000


### Status report information ###

Generated at: 2021-11-11 08:48:46 +00:00
`
</Details>

**Comment by nerrad** [comment]
Since you're unable to reproduce on new sites and we're also unable to reproduce, this suggests that there may be something specific to your environment that may be broken. It may be that there is an incompletely installed plugin (perhaps WooCommerce Blocks).

**Comment by ankitguptaindia** [comment]
It makes sense. I am closing this now, will keep eye on this scenario. I will re-open again if I see this issue again. Thank you!
