### ISSUE TITLE
Cart Block: Cross Sells do not show

### ISSUE THREAD

**Issue by joashrajin** [woocommerce/woocommerce-gutenberg-products-block#5047]
## Describe the bug

When using the Cart Block, the Cart Page does not show any cross-sells. Reverting to the shortcode for the Cart Page solves the problem. 

## To reproduce

1. Enable WooCommerce Blocks on your site
2. Create a cart page and use the Cart Block on it
3. Go to a product page and add a Cross-Sell to it (via Product Data > Linked Products > Cross-Sells)
4. Add the product to your cart, then compare how your cart page with the Cart Block looks versus the one with the cart shortcode (`[woocommerce_cart]`)

## Expected behavior
The cross-sells should show

## Screenshots

Cart Block:
![image](https://user-images.githubusercontent.com/16253818/139796612-0137b725-20b9-40ad-8087-4dabd5aa661c.png)

Cart Shortcode: 
![image](https://user-images.githubusercontent.com/16253818/139796920-80e12428-10ef-4875-9406-25cb3ca5ba08.png)

### WordPress (please complete the following information):
* Core version: 5.8.1
* WooCommerce version: 5.8.0
* WooCommerce Blocks version: 6.2.0
* Site language: English
* Any other plugins installed: N/A

### Desktop (please complete the following information):
* OS: MacOS 12.0.1
* Browser: Chrome
* Version 95.0.4638.54

**Comment by nerrad** [comment]
Just noting that while I've given this issue high priority, it does not necessarily mean it will be worked on soon. This is clearly missing feature support in the Cart block but this will require some design work for how things will work with the block flow.

**Comment by mikejolley** [comment]
@senadir How do you feel about creating a dedicated cross sells block that can be inserted top level or as an inner block of cart?

**Comment by senadir** [comment]
Yep, that's the plan, pending setting up a project, getting designs and scope, then building it.

**Comment by mikejolley** [comment]
Ok. I've removed the bug label.

**Comment by ralucaStan** [comment]
Closing this in favour of #6554

**Comment by ralucaStan** [comment]
Related https://github.com/woocommerce/woocommerce-blocks/issues/7183

**Comment by ralucaStan** [comment]
@joashrajin  this functionality has been added with version 8.6.0. You'll need to manually insert the Cross-Sells block on the Cart page. Let us know what you think.

**Comment by joashrajin** [comment]
@ralucaStan Looks awesome! Thanks for adding it
