### ISSUE TITLE
Product(s)Control: Query for products takes a long time with a lot of products

### ISSUE THREAD

**Issue by ryelle** [woocommerce/woocommerce-gutenberg-products-block#505]
A store owner with about 5000 products reported that the Hand-picked Products block is taking at least 30 seconds to load ([forum post](https://wordpress.org/support/topic/handpicked-products-query-extremely-slow/)).

This is likely due to the pre-loading of all products into the `ProductsControl` component, which fetches products in batches of 100, but waits for all products to return before rendering them. The intention was to load all items into the `SearchListControl`, to make searching very fast (no waiting for a server response).

Let's benchmark how this works on 100, 500, 1000, 5000+ products – once 1000+ products are loaded, is JS searching really faster than querying the API again?

Could we use two methods for these `ProductControl`s, one for smaller stores and one for larger product databases (so we can keep the fast search for the smaller product catalogs)?

Overall, this might benefit from some local caching, so the products don't have to be fetched every time the `ProductControl` is loaded.

**Comment by salar90** [comment]
We also are facing the same issue. API itself has the ability to search with just an argument, There is no need to fetch all products in order to find a product via JS.
