### ISSUE TITLE
Getting 'Country is Required' even when entered to calculate shipping in basket

### ISSUE THREAD

**Issue by emcgal** [woocommerce/woocommerce-gutenberg-products-block#5070]
The latest WooCommerce Blocks is giving me the 'Country is Required' when calculating the shipping in the basket even when the full address is entered. 

Version 6.2.0

I have tested with other themes (Twenty Twenty One and Twenty Seventeen) and all other plugins off bar Woocommerce and problem remains.

I am guessing this is a bug unless as I have reproduced it loads of times my end.

**Comment by nerrad** [comment]
Hi @emcgal,

Thanks for taking the time to report this issue. Will you be able to give us a few more details around how the Checkout block is configured for the site you are reproducing this on? Anything related to address options would be great. Thanks!

**Comment by emcgal** [comment]
Sorry for the delay, I didn't get any email notification. This is the easiest to show. If I skip and go the checkout it was fine there. I'm totally bambozzled at this stage on what to do. Any help apprecated.
https://www.loom.com/share/c1c324be7029444bb43f0947a36d966f

**Comment by emcgal** [comment]
@alexflorisca thanks for jumping on this. Didn't get any notification, must see why.

Is this closed / fixed.

What I finally discovered was (after rebuilding the website thinking it wasn't a bug because no one else was able to reproduce it, including myself on this particular build so I assumed some code was corrupt), it was to do with the setting in general on woocommerce, I had the default location for the user set to no location. Switched to shop location and the issue resolved.

If you want me to test anything let me know and I'll check my notification settings. Presumed they were on.

Thanks a mil 🙏🏻

**Comment by alexflorisca** [comment]
@emcgal We were able to reproduce the bug, even if a default location was set, thanks for pointing it out. It was to do with an internal state of a hook not syncing properly with the the user data coming from the server. We've fixed this in #5129, just waiting for it to get merged and it should be in the next release.

**Comment by emcgal** [comment]
@alexflorisca Super! I honestly was think I was going mad because everyone in others groups firstly couldn't produce it and then I actually had someone tell me that is how it should work 😬 and then tell me I should just use Geolocation (which I have reservations to use since GDPR and if cookies are not accepted, causes problems). Plus Geolocation isn't suitable here because the buyer and send to could be very different/ I want the decision to be made final in the basket, not the checkout because of unexpected surprises. From a UX perspective, it is way better for the user to enter their location to send to in the basket while they are at expectation mode, not committed to pay and then go YIKES at the shipping. 

While I have ya 😆 I am struggling to change the text on back orders once they are in the basket (ok on single product page), could you guide me to anywhere I might get help with that? Thanks 🙏🏻

**Comment by alexflorisca** [comment]
You're not going mad @emcgal , it was a legit bug!

> I am struggling to change the text on back orders once they are in the basket

I'm not quite sure what you mean by this sorry. I'd also like to keep the discussion here relevant to the issue so I would kindly ask that you contact [WooCommerce support](https://woocommerce.com/contact-us/) and they'll be able to help you, they're a friendly bunch!
