### ISSUE TITLE
Explore the impact of enabling block templates for all block themes without explicit WooCommerce support

### ISSUE THREAD

**Issue by frontdevde** [woocommerce/woocommerce-gutenberg-products-block#5075]
The goal of this exploratory task is to understand the full impact of enabling Site Editing templates support for themes that don't explicitely support WooCommerce (Note: support is usually declared by adding `add_theme_support( 'woocommerce' );` to the theme's functions.php).

Currently, if a block theme hasn't set explicit support, we do not load the related WooCommerce block templates on the Frontend. Let's explore the full impact of removing the `current_theme_supports( 'woocommerce' )` check for block themes.

See pdnLyh-8D-p2 for more details.

**Comment by tjcafferkey** [comment]
This work is in review here (https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5071) do you think we should close this issue?

**Comment by frontdevde** [comment]
Yes, let's close this in favor of https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5071.
