### ISSUE TITLE
Product Search (editor): the block's input can be edited 

### ISSUE THREAD

**Issue by ralucaStan** [woocommerce/woocommerce-gutenberg-products-block#5078]
## Describe the bug
The input from the Product search block has a value(`Search products...`) instead of a placeholder in the editor. The user can edit this value.

## To reproduce

1. Go to a page and add the Product search block
2. Click on the input and see that you can remove the `Search products...` text

## Expected behavior
The user should not be able to edit the input, as we don't allow this in other blocks
The "Search products..." should be the input's placeholder instead of the input's value

## Screenshots
<img width="614" alt="Screenshot 2021-11-05 at 12 40 42" src="https://user-images.githubusercontent.com/1628454/140505227-8715e2ea-b6eb-4684-ad6d-79df790757ab.png">

**Comment by alexflorisca** [comment]
We've investigated this and found that the text is editable because it controls the value of the product search placeholder on the front end. If we stop the text from being editable, it prevents merchants from being able to customize the product search block
