### ISSUE TITLE
StoreAPI wc/store/cart returns address with empty state 

### ISSUE THREAD

**Issue by peterlama** [woocommerce/woocommerce-gutenberg-products-block#5131]
## Describe the bug
The country state validation introduced in pr #4844 is seemingly always incorrect, causing the state to be empty. At least in my case, the value of the state address field is the state code, but `wc()->countries->get_states` returns an array of state names with the state codes as keys. Changing it to use `isset` fixed it in my case.

![image](https://user-images.githubusercontent.com/5176612/141415115-962619ab-856f-4bd1-ba3f-be4f01aa0e71.png)

## To reproduce

1. Log in with a user that has a US billing address
2. Go to cart page
3. Enter the following in the console: `wp.data.select('wc/store/cart').getCartData().billingAddress`
4. And you can see the state is empty

![image](https://user-images.githubusercontent.com/5176612/141413060-7c505127-ebf5-4bb9-a79b-1762835fe5da.png)
![image](https://user-images.githubusercontent.com/5176612/141413369-418a5936-1288-47c8-b944-4a254872d293.png)

## Environment
* WooCommerce version: 5.9
* WooCommerce Blocks version: 6.2
* Site language: EN
* Store location: USA

**Comment by mikejolley** [comment]
I think this is being impacted by a different bug with missing billing data that @senadir @opr and @alexflorisca have been investigating. The code in question is this:

```php
$billing_country = $address->get_billing_country();
$billing_state   = $address->get_billing_state();
$valid_states    = array_filter( (array) wc()->countries->get_states( $billing_country ) );

if ( ! empty( $billing_state ) && count( $valid_states ) && ! in_array( $billing_state, $valid_states, true ) ) {
	$billing_state = '';
}
```

`wc()->countries->get_states( $billing_country )` returns just the subset of states for the given country. If the country is not set (and null) it returns all states as you're seeing. 

I can add a workaround to disable validation if there is no billing country, but the actual bug is elsewhere.

**Comment by peterlama** [comment]
@mikejolley In my case the country is not empty, but the address state value is the code and not the name. As can be see in this screen from xdebug.
![image](https://user-images.githubusercontent.com/5176612/141492902-04ad81f6-d416-4cdb-a193-3717aa4a3e82.png)
