### ISSUE TITLE
WooCommerce blocks - Order by Menu not working

### ISSUE THREAD

**Issue by Robertght** [woocommerce/woocommerce-gutenberg-products-block#5138]
This is a replica of this one: https://github.com/Automattic/wp-calypso/issues/57727

---

### Quick summary

When you add a sortable woocommerce block to a page and select order by menu order from the sidebar options, the order does not match the menu order

### Steps to reproduce

1. add any sortable woocommerce block 
2. select sort by menu order
3. see that some other order given

### What you expected to happen

the order should match the menu order in customizer

### What actually happened

settings in editor: 
![2021-11-07 at 11 42](https://user-images.githubusercontent.com/47717887/140640048-c85b41c3-ee05-48d7-b972-6bc5aa89427d.jpg)

order in menu:
![2021-11-07 at 11 44](https://user-images.githubusercontent.com/47717887/140640085-e42c99df-951c-4992-b96a-b7b1058d5768.jpg)

### Context

4434971-zd-woothemes

**Comment by Aljullu** [comment]
Hi there @Robertght, thanks for following up and directing the issue to the correct repo.

By _Menu Order_, it refers to the order products have when viewing them from `/wp-admin/edit.php?post_type=product`. If you go to that page, you will notice there is a _Sorting_ tab that can be used to change the order of products. Rearranging products there will change the order they appear in the Product grid blocks that have the _Menu Order_ option selected.

Based on that, I'm going to close this issue given that this is working as expected, but if you disagree or have a proposal on a better naming for that option, let us know! :slightly_smiling_face: 

cc @Nic-Sevic

**Comment by futurowebpl** [comment]
In my opinion, no sorting method works at all if "Manually select products" is selected in WC Gutenberg Block.

Then - Manually select products it does not react in any way to any reordering,

**Comment by Nic-Sevic** [comment]
Hi @Aljullu, thanks for the explanation! In that case I can reach back out to the user and let them know. 

For the future though, perhaps something like "Product Sort Order" would be more intuitive? Or as a feature request even the ability to manually assign a display order from the block itself?

**Comment by Aljullu** [comment]
> In my opinion, no sorting method works at all if "Manually select products" is selected in WC Gutenberg Block.

Where do you see the "Manually select products" option, @futurowebpl? If you mean the Hand-Picked Products block, it seems to apply 'Order By' options correctly for me.

**Comment by Aljullu** [comment]
Thanks for following-up @Nic-Sevic!

> Or as a feature request even the ability to manually assign a display order from the block itself?

This is covered in: https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4769. :slightly_smiling_face: 

The issue only refers to the Hand-Picked Products block, but it can be extended to cover all product grid blocks.
