### ISSUE TITLE
Checkout page switches language [bug]?

### ISSUE THREAD

**Issue by emsiladnav** [woocommerce/woocommerce-gutenberg-products-block#5141]
Once I preview the checkout page in my editor, it displays the page in my default language [dutch] (which I want), however if I preview the page by url, it switches to English? How can I default it to Dutch?

**Comment by emsiladnav** [comment]
Expected result:
<img width="1159" alt="Schermafbeelding 2021-11-15 om 14 20 02" src="https://user-images.githubusercontent.com/74651518/141788883-20bb9bcd-489e-4d1d-afb3-4b9b56e45668.png">

Actual result:
<img width="722" alt="Schermafbeelding 2021-11-15 om 14 20 32" src="https://user-images.githubusercontent.com/74651518/141788902-2defa7c3-3344-419e-9709-226fe58cb03a.png">

**Comment by DarianDev** [comment]
The issue is known, the fix should be released this week. im also waiting for the fix :)

**Comment by emsiladnav** [comment]
> The issue is known, the fix should be released this week. im also waiting for the fix :)
 
Thanks for letting me know! :) @DarianDev
