### ISSUE TITLE
Cart block: Visual bug for WooCommerce Points and Rewards 

### ISSUE THREAD

**Issue by ralucaStan** [woocommerce/woocommerce-gutenberg-products-block#5152]
## Describe the bug
The form for WooCommerce Points and Rewards  in the Cart block does not look as before.

## To reproduce
Steps to reproduce the behaviour:

1. Install WooCommerce Points and Rewards, go to WooCommerce > Points and Rewards and add points to your user.
2. Go to WooCommerce > Points and Rewards > Settings and enable "Allow partial redemption"
3. Go to Cart and see the input to redeem points is showing
4. Notice that it does not look ok

## Expected behaviour
See screenshots for difference. 

## Screenshots
**Before**
<img width="810" alt="Screenshot 2021-11-16 at 11 53 51" src="https://user-images.githubusercontent.com/1628454/141974541-78a22b3e-d723-4014-b9de-a672fa6864c0.png">
**Now**
<img width="783" alt="Screenshot 2021-11-16 at 12 07 05" src="https://user-images.githubusercontent.com/1628454/141974558-cf1a5755-07e8-4c24-a2c3-1ff82bae1a8f.png">

**Comment by alexflorisca** [comment]
I've been looking into this but may not get time to fix before next week so updating with progress.

- The bad commit that introduced the layout bug is [76d565b83fba4e6d3ce658275206eeb94cd15510](https://github.com/woocommerce/woocommerce-gutenberg-products-block/commit/76d565b83fba4e6d3ce658275206eeb94cd15510)
- No changes to the immediate points and rewards block computed css so likely not a css bug.

TO DO
- investigate changes in that commit and any DOM manipulation done via JS

**Comment by opr** [comment]
Closed when merging accidentally. Reopened as this is not solved yet.
