### ISSUE TITLE
Investigate webpack build process performance

### ISSUE THREAD

**Issue by HardeepAsrani** [woocommerce/woocommerce-gutenberg-products-block#517]
**Describe the bug**
After making my changes, when I run `npm run build` nothing happens for a long time. My Docker container stops responding. This only happens during the build, `start` works just fine.

I've tried to the npm and node js as defined in package.json

**To Reproduce**

1. npm install & composer install
2. Run npm run build

**Expected behavior**
To compile or show an error

**Comment by HardeepAsrani** [comment]
It took two cat lifetimes but it finally built. Is there any performance issue in the webpack build process?

**Comment by ryelle** [comment]
I've also noticed that `npm run build` can take longer than expected. It would be great to get some metrics profiling the webpack process, to see if we can pinpoint the slowdown.

**Comment by mikejolley** [comment]
This slowdown occured in 2.1 but in the more recent builds I've not had much of a slowdown. In the summary after build on 2.1 some of the files were > 2mb, but in the more recent versions the files are much smaller. I suspect https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/571 finally fixed this issue.
