### ISSUE TITLE
WooCommerce Theme Block Templates Appear in Template Select Dropdown for Posts and Pages

### ISSUE THREAD

**Issue by tjcafferkey** [woocommerce/woocommerce-gutenberg-products-block#5172]
## Describe the bug
During the Store Editing Templates project we came across an issue where when we added Core WooCommerce block templates (e.g. `single-product.html`, `archive-product.html`) and made them available for FSE themes these were also appearing in the Template dropdown on the Edit Post page.

For the default block templates (ie. the ones that come with WooCommerce now) we ensured we hid these from the Template dropdown https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5167. However if these templates come as part of a theme they still appear.

We need to investigate:
* If these templates **should** be appearing here if they're provided from the theme
* If the answer is no who's responsibility is it to hide these templates? Woos, or the theme developers?
* If its our responsibility we need to come out with a solution which will solve this.

## To reproduce

1. Follow the testing notes on the [Epic](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4926)
2. Add a `single-product.html` template into your FSE enabled theme
3. Edit a Post or Page and observe in the Template dropdown the WooCommerce Single Product template.

**Comment by gigitux** [comment]
After some investigation, I think it is not our responsibility to hide templates.

For FSE themes, [the theme developer can hide them via the `theme.json`](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/#customtemplates)

For classic themes, [the theme developer can hide them via a comment on PHP code](https://developer.wordpress.org/themes/template-files-section/page-template-files/#creating-page-templates-for-specific-post-types)


What do you think?

**Comment by tjcafferkey** [comment]
I am inclined to agree with you!

**Comment by Aljullu** [comment]
+1 from my side. :slightly_smiling_face:

**Comment by gigitux** [comment]
@tjcafferkey @Aljullu 
Thanks for the feedback, I will close this issue 👍
