### ISSUE TITLE
Use consistent add to cart logic

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#5182]
## Describe the bug

When viewing the `All Products` in the frontend and adding a product to the cart, the `Add to cart` button changes to `1 in cart ✓`. When viewing the `Top rated products` in the frontend and adding a product to the cart, the `Add to cart` button changes to `Add to cart ✓` and a second button `View cart ✓` appears next to it.

It's not consistent that the `Add to cart` button behaves differently on different blocks.

## To reproduce

1. Create a test page, add the `All Products` block to it and save the page.
2. Look up that page in the frontend.
3. Click on the `Add to cart` button for one of the products.
4. See that the `Add to cart` button changes to `1 in cart ✓`.
5. Create a test page, add the `Top rated products` block to it and save it.
6. Look up that page in the frontend.
7. Click on the `Add to cart` button for one of the products.
8. See that the `Add to cart` button changes to `Add to cart ✓`.
9. See that another button called `View cart ✓` appears next to the `Add to cart ✓` button.

## Expected behavior

The `Add to cart` button should behave consistent throughout all blocks.

## Screenshots

<table>
<tr>
<td>All Products:
<br><br>

![all-products](https://user-images.githubusercontent.com/3323310/142399719-6d39087e-46e6-4b15-875e-450a55bdfbde.png)
</td>
<td>Hand-picked Products:
<br><br>

![Hand-picked-Products](https://user-images.githubusercontent.com/3323310/142399785-5413cc28-dc49-424e-af7b-f1547b396d61.png)
</td>
<td>On-Sale-Products:
<br><br>

![On-Sale-Products](https://user-images.githubusercontent.com/3323310/142399803-4f0d60a8-22a8-4b3f-8df4-b02649db834b.png)
</td>
<td>Top-rated Products:
<br><br>

![Top-rated-products](https://user-images.githubusercontent.com/3323310/142399827-70cc5875-fab1-4bb1-9c8b-8937f02f05ee.png)
</td>
</tr>
</table>

## Affected parts

As far as I can tell, all blocks that list products, except the `All Products` block, are affected by this.

**Comment by opr** [comment]
I've done some investigation on this today, the reason that the buttons are different is the All Products block uses the `woocommerce/product-add-to-cart` block to render the buttons whereas the other blocks that use the `AbstractProductGrid` are rendered server-side and the add to cart button is some pre-set HTML that gets picked up by WooCommerce core functionality.

I think we could look into updating the way the blocks that use of the `AbstractProductGrid` are rendered and saved so they instead use the `ProductList` block. This will probably be a pretty big task though and we'd need to update the:
- Products by Attribute
- Products by Tag
- Products by Category
- On Sale Products
- Newest Products
- Hand Picked Products
- Best Selling Products
- Top Rated Products

**Comment by mikejolley** [comment]
Before we jump into updating the older grid blocks to the newer All Products Block structure, we may want to investigate if All Products block could be updated to filter what is displayed, to cover all the other grid blocks use-cases. One block to rule them all.
