### ISSUE TITLE
Order - address and customer data are not transmitted

### ISSUE THREAD

**Issue by DarianDev** [woocommerce/woocommerce-gutenberg-products-block#5190]
## Describe the bug
Since the update to 6.3.x the customer data are partly not transmitted anymore. The order appears, is paid, but I am missing all information, such as the address, e-mail and co.

This is catastrophic. It is not the case with every order, but with every 10th order.

## To reproduce
Use 6.3.x and receive orders.

## Expected behavior
All data must be correctly transmitted and displayed so that the order can be processed.

## Screenshots
![1](https://user-images.githubusercontent.com/17782319/142494877-e726f411-0b0b-43e4-bbe2-e5979e6fed5a.PNG)

### WordPress (please complete the following information):
* Core version: 5.8.2
* WooCommerce version: 5.9
* WooCommerce Blocks version: 6.3.2
* Site language: german

**Comment by Aljullu** [comment]
Hi @DarianDev, thanks for filling this issue.

I tried to reproduce it in my site but wasn't able to do so. In order to further investigate the issue, would you be able to go to WooCommerce > Status, click on _Get System Report_ and share it with us?

In the meantime, I would also suggest you to follow the [WooCommerce Self-Service guide](https://woocommerce.com/document/woocommerce-self-service-guide/), which in many cases can help resolve any issues in your site.

**Comment by DarianDev** [comment]
@Aljullu sure, here is the system report:

`
### WordPress Environment ###

WC Version: 5.9.0
REST API Version: ✔ 5.9.0
WC Blocks Version: ✔ 6.3.2
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 2.8.0
Log Directory Writable: ✔
WP Version: 5.8.2
WP Multisite: –
WP Memory Limit: ❌ 51 MB - Wir empfehlen das PHP Speicher-Limit (memory_limit) auf mindestens 64 MB zu setzen. Siehe: PHP Speicher-Limit erhöhen
WP Debug Mode: –
WP Cron: ✔
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.13
PHP Post Max Size: 256 MB
PHP Time Limit: 300
PHP Max Input Vars: 5000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.30-MariaDB-1:10.3.30+maria~focal
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.9.0
WC Database Prefix: www0_
Datenbank-Gesamtgröße: 244.91MB
Datenbank-Datengröße: 150.38MB
Datenbank-Indexgröße: 94.53MB
www0_woocommerce_sessions: Daten: 6.02MB + Index: 0.08MB + Engine InnoDB
www0_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
www0_woocommerce_order_items: Daten: 3.52MB + Index: 1.50MB + Engine InnoDB
www0_woocommerce_order_itemmeta: Daten: 19.55MB + Index: 16.02MB + Engine InnoDB
www0_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
www0_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_actionscheduler_actions: Daten: 5.02MB + Index: 6.02MB + Engine InnoDB
www0_actionscheduler_claims: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_actionscheduler_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_actionscheduler_logs: Daten: 4.02MB + Index: 3.70MB + Engine InnoDB
www0_aepc_custom_audiences: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_aepc_logs: Daten: 0.05MB + Index: 0.00MB + Engine InnoDB
www0_aioseo_notifications: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
www0_aioseo_posts: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_commentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_comments: Daten: 10.52MB + Index: 9.09MB + Engine InnoDB
www0_getpaid_invoices: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_getpaid_invoice_items: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_hurrytimer_evergreen: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_mailchimp_carts: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_mailchimp_jobs: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_mailpoet_custom_fields: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_mailpoet_dynamic_segment_filters: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_mailpoet_feature_flags: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_mailpoet_forms: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_mailpoet_log: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_mailpoet_mapping_to_external_entities: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_mailpoet_newsletters: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_mailpoet_newsletter_links: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
www0_mailpoet_newsletter_option: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_mailpoet_newsletter_option_fields: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_mailpoet_newsletter_posts: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_mailpoet_newsletter_segment: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_mailpoet_newsletter_templates: Daten: 2.52MB + Index: 0.00MB + Engine InnoDB
www0_mailpoet_scheduled_tasks: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_mailpoet_scheduled_task_subscribers: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_mailpoet_segments: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_mailpoet_sending_queues: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_mailpoet_settings: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_mailpoet_statistics_bounces: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_mailpoet_statistics_clicks: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
www0_mailpoet_statistics_forms: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_mailpoet_statistics_newsletters: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_mailpoet_statistics_opens: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
www0_mailpoet_statistics_unsubscribes: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
www0_mailpoet_statistics_woocommerce_purchases: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
www0_mailpoet_stats_notifications: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_mailpoet_subscribers: Daten: 0.02MB + Index: 0.13MB + Engine InnoDB
www0_mailpoet_subscriber_custom_field: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_mailpoet_subscriber_ips: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_mailpoet_subscriber_segment: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_mailpoet_user_agents: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_mailpoet_user_flags: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_ms_snippets: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_options: Daten: 6.08MB + Index: 0.25MB + Engine InnoDB
www0_pay_options: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_pay_option_subs: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_pay_transactions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_postmeta: Daten: 72.53MB + Index: 45.17MB + Engine InnoDB
www0_posts: Daten: 6.44MB + Index: 3.58MB + Engine InnoDB
www0_rank_math_404_logs: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_rank_math_analytics_gsc: Daten: 0.34MB + Index: 0.58MB + Engine InnoDB
www0_rank_math_analytics_objects: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_rank_math_internal_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_rank_math_internal_meta: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_rank_math_redirections: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_rank_math_redirections_cache: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_smush_dir_images: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_snippets: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_termmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_terms: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_term_relationships: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_term_taxonomy: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_tm_taskmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_tm_tasks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_usermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_users: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
www0_wcdpi_country: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_wcdpi_page_format: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_wcdpi_product_additional: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_wcdpi_product_basic: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_wcdpi_product_sales: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_wcdpi_shipment: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_wcdpi_shipment_attachment: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_wcdpi_shipment_item: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_wcdpi_t_app_service: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_wcdpi_t_app_service_feature: Daten: 0.06MB + Index: 0.00MB + Engine InnoDB
www0_wcdpi_t_app_service_provider: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_wcpdf_invoice_number: Daten: 0.33MB + Index: 0.00MB + Engine InnoDB
www0_wc_admin_notes: Daten: 0.05MB + Index: 0.00MB + Engine InnoDB
www0_wc_admin_note_actions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_wc_customer_lookup: Daten: 1.52MB + Index: 1.58MB + Engine InnoDB
www0_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_wc_order_coupon_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_wc_order_product_lookup: Daten: 2.52MB + Index: 1.31MB + Engine InnoDB
www0_wc_order_stats: Daten: 2.52MB + Index: 1.11MB + Engine InnoDB
www0_wc_order_tax_lookup: Daten: 1.52MB + Index: 0.58MB + Engine InnoDB
www0_wc_product_meta_lookup: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
www0_wc_reserved_stock: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_wpinv_subscriptions: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
www0_yoast_indexable: Daten: 2.52MB + Index: 1.13MB + Engine InnoDB
www0_yoast_indexable_hierarchy: Daten: 0.11MB + Index: 0.16MB + Engine InnoDB
www0_yoast_migrations: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_yoast_primary_term: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_yoast_seo_links: Daten: 0.11MB + Index: 0.06MB + Engine InnoDB
www0_yoast_seo_meta: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
www_commentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www_comments: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
www_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www_options: Daten: 0.31MB + Index: 0.03MB + Engine InnoDB
www_postmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www_posts: Daten: 0.08MB + Index: 0.06MB + Engine InnoDB
www_termmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www_terms: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www_term_relationships: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
www_term_taxonomy: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www_usermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
www_users: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB

### Post Type Counts ###

attachment: 197
cartflows_flow: 2
cartflows_step: 2
custom_css: 1
elementor_library: 1
hurrytimer_countdown: 1
mailpoet_page: 1
nav_menu_item: 4
oembed_cache: 12
page: 14
post: 1
product: 1
revision: 42
saswp_reviews: 
saswp-collections: 2
shop_coupon: 3
shop_order: 
shop_order_refund: 
ufaq: 7
wcct_countdown: 1
wpi_payment_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (16) ###

Elementor: von Elementor.com – 3.4.8
Favicon by RealFaviconGenerator: von Philippe Bernard – 1.3.22
Kadence WooCommerce Email Designer: von Kadence WP – 1.4.8
Microsoft Advertising Universal Event Tracking (UET): von Microsoft Corporation – 1.0.3
Schema & Structured Data for WP & AMP: von Magazine3 – 1.9.89
Rank Math SEO: von Rank Math – 1.0.76.1
Orbit Fox Companion: von Themeisle – 2.10.8
WooCommerce Blocks: von Automattic – 6.3.2
Advanced Order Export For WooCommerce: von AlgolPlus – 3.2.1
WooCommerce Stripe-Gateway: von WooCommerce – 5.8.0
WooCommerce Pixel Manager: von woopt – 1.11.7
WooCommerce-Zahlungen: von Automattic – 3.3.0
WooCommerce PayPal Payments: von WooCommerce – 1.6.1
WooCommerce PDF Invoices & Packing Slips: von Ewout Fernhout – 2.10.3
WooCommerce: von Automattic – 5.9.0
WP Rollback: von Impress.org – 1.7.1

### Inactive Plugins (0) ###


### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop-Basis: #36315 - /shop/
Warenkorb: #40 - /warenkorb/
Kasse: #41 - /kasse/
Mein Konto: ❌ Seiten-ID ist gesetzt
aber die Seite existiert nicht

Allgemeine Geschäftsbedingungen: #124 - /agb/

### Theme ###

Name: Neve
Version: 3.0.11
Author URL: https://themeisle.com
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie du ein Child-Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: neve/woocommerce/product-searchform.php

### WooCommerce PayPal Payments ###

Onboarded: Yes
Shop country code: DE
PayPal card processing available in country: No
Pay Later messaging available in country: Yes
Vault enabled: Yes

### WooCommerce Payments ###

Version: 3.3.0
Connected to WPCOM: Ja
Blog ID: 197921031
Account ID: acct_1JdyKr2EponPmJDi

### Action Scheduler ###

Complete: 14.370
Oldest: 2021-10-20 12:18:20 +0200
Newest: 2021-11-19 13:05:03 +0100

Pending: 5
Oldest: 2021-11-19 13:05:14 +0100
Newest: 2021-11-23 09:14:49 +0100


### Status report information ###

Generated at: 2021-11-19 13:05:15 +01:00
`

**Comment by gigitux** [comment]
Hi @DarianDev, thanks for sending us the `System Report`. I tried to reproduce it on my site but wasn’t able to replicate the problem.
I would suggest you follow the steps as described in [Plugin and theme conflicts](https://woocommerce.com/document/woocommerce-self-service-guide/#section-4)

**Comment by senadir** [comment]
I should note that it's very hard for us to fix this issue without proper reproduction steps.

> This is catastrophic. It is not the case with every order, but with every 10th order.

Any common patterns you notice between those failed orders? Specific items, regions, logged in/logged out? If you have some sort of tracking, what kind of browser maybe?

**Comment by DarianDev** [comment]
Its always paypal orders, but i also dont have more information :(

**Comment by DarianDev** [comment]
> I should note that it's very hard for us to fix this issue without proper reproduction steps.
> 
> > This is catastrophic. It is not the case with every order, but with every 10th order.
> 
> Any common patterns you notice between those failed orders? Specific items, regions, logged in/logged out? If you have some sort of tracking, what kind of browser maybe?

I have a one product store with only german customers always logged out, dont have user accounts. no tracking :/ 
phone and desktop orders

its with very payment method, paypal, bank transfer or woocommerce payments

**Comment by gigitux** [comment]
@DarianDev can you write some detailed retro steps? Unfortunately, I am unable to replicate the problem

**Comment by mikejolley** [comment]
I double-checked the StoreAPI implementation for new orders and confirmed:

- Orders cannot be created or placed without an address
- The route updates the customer object first, and then the order based on customer data
- Before payment, there is a final validation routine to ensure addresses are set. If not, the endpoint returns `woocommerce_rest_invalid_address`

So from the API perspective, I see nothing which would cause an error to be placed without data.

> its with very payment method, paypal, bank transfer or woocommerce payments

I think @DarianDev if you can dig in and verify this statement is true it might narrow down the culprit. If you really do have bank transfer orders with no address, that may indicate a conflict with a plugin causing address data to be deleted, or even something obscure like the Privacy class functionality which periodically wipes data.

If it's only Paypal, or only WC Payments, those can then be investigated in more depth.

**Comment by DarianDev** [comment]
it is really strange, in the order confirmation, which is sent by mail to the customer, the address is listed normally but when you call the order in the backend it says that no data was given. @mikejolley

**Comment by mikejolley** [comment]
Sounds like something is deleting or hiding the data after the order is placed? Do the order notes reveal any hints? If the order goes through I don't see how this is related to the checkout process in Blocks.

**Comment by DarianDev** [comment]
@mikejolley i myself have not yet managed to reproduce the error, it always occurs with real customer orders, unfortunately there are no clues.

**Comment by mikejolley** [comment]
@DarianDev Has this occured any more? 

> in the order confirmation, which is sent by mail to the customer, the address is listed normally but when you call the order in the backend it says that no data was given

This should also mean the confirmation to the store owner would have the address too. So as long as those emails are coming through, it would be inconvenient but not as catastrophic as first thought. 

Given we've not seen any further reports of this from other users, and don't have steps to reproduce to make this issue actionable, I will be closing it, but please if you notice any further patterns or can narrow it down to a specific plugin conflict reply here so we can reopen and reaccess.

Thanks
