### ISSUE TITLE
Mini Cart: create Mini Cart template part area

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#5194]
Initially discussed in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5025#issuecomment-973902812.

We would like to create a _Mini Cart_ block template part area, similar to _Header_ and _Footer_. This way, the user can create multiple template parts belonging to the Mini Cart area. In a follow-up issue, we would need to allow selecting a specific template part from the Mini Cart block itself.

![imatge](https://user-images.githubusercontent.com/3616980/142604028-d93c7e1d-52d8-4522-a9ec-a9140d10904d.png)

#5025 included some [initial code to accomplish that](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5025/commits/4c8f44a4bb9faa6894bb9a6d641f9971dd9f0b5d#diff-5413cd4815fd0404e0f8ae4b0870e40fc2d7f12ec3ba52df2d30b137f10bd105R105-R121), but it was left out from that PR. However, I guess it can be used as a reference?

For the icon, we will use the Mini Cart icon with the badge:

<details>
<summary>mini-cart-icon.svg</summary>

```HTML
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M8.22219 20.1114C8.65175 20.1114 8.99998 19.7631 8.99998 19.3336C8.99998 18.904 8.65175 18.5558 8.22219 18.5558C7.79263 18.5558 7.4444 18.904 7.4444 19.3336C7.4444 19.7631 7.79263 20.1114 8.22219 20.1114Z" stroke="#111111" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M16.7778 20.1114C17.2074 20.1114 17.5556 19.7631 17.5556 19.3336C17.5556 18.904 17.2074 18.5558 16.7778 18.5558C16.3482 18.5558 16 18.904 16 19.3336C16 19.7631 16.3482 20.1114 16.7778 20.1114Z" stroke="#111111" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M2 3.77779H5.11117L7.19565 14.1924C7.26677 14.5505 7.46158 14.8722 7.74597 15.1011C8.03036 15.33 8.38621 15.4517 8.75123 15.4447H16.3114C16.6764 15.4517 17.0322 15.33 17.3166 15.1011C17.601 14.8722 17.7958 14.5505 17.867 14.1924L19.1114 7.66674H5.88896" stroke="#111111" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
<circle cx="19" cy="7" r="4" fill="black"/>
</svg>
```

</details>

**Comment by vivialice** [comment]
@Aljullu Do you want me to write some copy for the description?
