### ISSUE TITLE
Mini Cart quantity badge doesn't honor thousands separator

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#5198]
Follow-up of https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5188#pullrequestreview-811051141.

## To reproduce
1. Add 1000 (or more= products to your cart. You can easily do that from any product page.
2. Add the Mini Cart block to a page or post and view it in the frontend.
3. Notice there is no thousands' separator:
![Mini Cart block showing no thousands separator in the quantity badge](https://user-images.githubusercontent.com/3616980/142609353-a0f55aa9-ae56-41bc-b0d7-ef2bf921030f.png)

**Comment by mikejolley** [comment]
@Aljullu Is this a bug? The thousand separator setting in Woo core is only for prices. 

Qty in core checkout:
![Screenshot 2021-11-19 at 11 32 13](https://user-images.githubusercontent.com/90977/142616042-8690f110-6622-4693-9a65-2674bf4809fa.png)

**Comment by Aljullu** [comment]
Ah... good point. Probably better to be consistent with core.
