### ISSUE TITLE
Single Product: all of the product is duplicated in the description tabbed area

### ISSUE THREAD

**Issue by Sandstromer** [woocommerce/woocommerce-gutenberg-products-block#5199]
## Describe the bug
With a FSE theme active, the full single product page is being duplicated in the description tabbed area.

## To reproduce

1. Activate a FSE theme, e.g. Blockbase, TT1-Blocks etc.
2. View a single product in the frontend
3. See that in the Description tabbed area, the full product content is displayed, complete with image gallery, entry summary, related products, upsells etc.

## Expected behavior
Only the long description should be displayed here, not the whole of the single product content.

## Screenshots
**Frontend view:**
![woocommerce-single-product-duplicated](https://user-images.githubusercontent.com/76742815/142637878-e74ee1ae-f008-4b2f-9079-5daae28a2449.jpg)

**Inspector view showing full product duplicated:**
![woocommerce-single-product-duplicated-inspector](https://user-images.githubusercontent.com/76742815/142637979-590ef291-4a98-488a-bbbd-86ff050d4d55.jpg)

### WordPress (please complete the following information):
* Core version: 5.8.2
* Gutenberg version: 11.9.1
* WooCommerce version: 5.9.0
* WooCommerce Blocks version: 6.3.2
* Site language: English
* Any other plugins installed: None

**Comment by Aljullu** [comment]
Thanks for reporting this issue @Sandstromer!

I'm pretty sure this is happening in WC 5.9, but is fixed in WC 6.0, which will be released in mid-December.

@frontdevde @tjcafferkey what are your thoughts on this issue? Do you have any temporary solution in mind that could prevent this? If not, should we feature-gate all the templates work we did to WC core >= 6.0?

**Comment by tjcafferkey** [comment]
This doesn't happen in WC 6.0 and above. And since the feature is now only available on WC 6.0 and above (https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5210) we can close this issue.
