### ISSUE TITLE
Display Categories (not products by category)

### ISSUE THREAD

**Issue by maikunari** [woocommerce/woocommerce-gutenberg-products-block#5224]
Building a woocommerce store and want to add a subset of categories to the homepage.  Not all of the products in each category, just the category with category featured image. 

It would be great if these could be selected just like in the Products by Category block.  

I know this can be done with the woocommerce [product_categories] shortcode, but it seems like a natural addition to have this in a block.

**Comment by gigitux** [comment]
Hi there @maikunari 👋🏻

Thanks so much for taking the time to leave some feedback – much appreciated! 

There is an open issue woocommerce/woocommerce#42678 for the creation of this new block.
