### ISSUE TITLE
Legacy template block: themes can't override the archive-product.html only

### ISSUE THREAD

**Issue by MaggieCabrera** [woocommerce/woocommerce-gutenberg-products-block#5230]
## Describe the bug
It seems like a theme can only override the archive product template by overriding the taxonomy category/tag templates.

## To reproduce

1. Install Blockbase
2. Create a template inside `block-templates/archive-product.html` with this content:

```
<!-- wp:template-part {"slug":"header","tagName":"header"} /-->

<!-- wp:group {"tagName":"main","layout":{"inherit":true}} -->
<main class="wp-block-group">

	<!-- wp:group {"align":"wide"} -->
	<div class="wp-block-group alignwide">
		<!-- wp:woocommerce/legacy-template {"template":"archive-product"} /-->
	</div>
	<!-- /wp:group -->

</main>
<!-- /wp:group -->

<!-- wp:template-part {"slug":"footer","tagName":"footer","layout":{"inherit":true},"className":"site-footer-container"} /-->
```

3. Go to the frontend and check an archive page, it's loading either taxonomy-product_cat.html or taxonomy-product_tag.html from the plugin instead of the theme template we just created (the one we created is wide aligned).

## Expected behavior
I expected `archive-product.html` being defined in the theme to override the more specific templates from the plugin

### WordPress (please complete the following information):
* Core version: 5.8.2
* Gutenberg version (if installed): trunk
* WooCommerce version: 6.1.0
* WooCommerce Blocks version: 6.5.0

**Comment by tjcafferkey** [comment]
@MaggieCabrera I'm unable to replicate this issue, I've added added the `archive-product.html` template to the Blockbase theme and added some additional text to the markup you provided, which does get rendered on the frontend by overriding the Woo plugin templates. Can you please confirm if you're still experiencing this issue, or if I have misunderstood the problem?

Just for context, it is [here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/src/BlockTemplatesController.php#L438-L444) where we check if the theme has a `archive-product.html` template before rendering our own.

**Comment by MaggieCabrera** [comment]
@tjcafferkey it's still happening to me. I'm using [this branch](https://github.com/Automattic/themes/pull/5079) of Blockbase that has the edited templates (basically I make them wide width). Using the following plugins:

<img width="1299" alt="Screenshot 2021-12-10 at 11 25 33" src="https://user-images.githubusercontent.com/3593343/145559135-0670384f-0a8a-4a31-bc8b-de8152eb2fb6.png">

After I updated to 6.5.0 and I get the same thing. I do see the code that you are referencing on the plugin, though, so I don't know if I'm doing something else wrong!

This is what I see, the product page gets the wide alignment correctly but not the archive page:

![Screen Capture on 2021-12-10 at 11-24-53](https://user-images.githubusercontent.com/3593343/145559413-85796f2d-64ea-4bc1-a2f2-bd9a5b9f3fcc.gif)

**Comment by MaggieCabrera** [comment]
Thank you @tjcafferkey! This fixes the issue I had on Blockbase
