### ISSUE TITLE
The Mini Cart template part block should be available inside Mini Cart view only.

### ISSUE THREAD

**Issue by dinhtungdu** [woocommerce/woocommerce-gutenberg-products-block#5232]
## To reproduce

1. Check out the latest `trunk` of `woocommerce` or install the [nightly build](https://github.com/woocommerce/woocommerce/releases/tag/nightly).
2. Check out the latest `trunk` of Gutenberg.
3. Go to Appearance > Editor (Beta).
4. Add new block, search for Mini Cart template.
5. See it can be added to the page template.

## Expected behavior
Mini cart template part should be available inside Mini Cart block view only.

## Screenshots
![image](https://user-images.githubusercontent.com/5423135/143223929-d4ba66b4-62dd-4a5b-8700-7de35e8c8fa2.png)

## Additional context
This issue comes from #5221.

The Mini Cart template part block is a variation of the Template Part block. From my initial research, I think this should be fixed in Gutenberg, but adding this issue for discussion ​to see if we can do anything on our end.

**Comment by dinhtungdu** [comment]
@Aljullu I think we should rename the Mini Cart template part block, right now it's confusing to have two Mini Cart blocks.

**Comment by Aljullu** [comment]
@dinhtungdu is there any use-case for having the Mini Cart template part available from the inserter? If not, could we hide it completely? I agree it's easy to get confused and in theory the template part will be accessible from the Mini Cart block parameters (according to #5195), so there would be no need to show it in the inserter, no?

**Comment by dinhtungdu** [comment]
> If not, could we hide it completely?

@Aljullu It makes sense to me! I don't see any other use-case either.
