### ISSUE TITLE
Revise storybook entry for `Button` component

### ISSUE THREAD

**Issue by sunyatasattva** [woocommerce/woocommerce-gutenberg-products-block#5250]
As part of the [Storybook resurrection](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5248) project, we intend to revise our currently implemented components to add full control and, where applicable, a few useful stories.

In particular, for the `Button` component:

- [ ] Implement controls for all props

### Possible stories

- [ ] Disallow add to cart
- [ ] Adding to cart state
- [ ] Added to cart state

**Comment by lpizzinidev** [comment]
Hi 🤚 Can I work on this issue?

**Comment by sunyatasattva** [comment]
Hi @lpizzinidev ! Thanks for offering your help. Feel free to work on this issue, then! And ping me if you need any extra clarification.

**Comment by lpizzinidev** [comment]
@sunyatasattva Thanks! I'll be working on this

**Comment by sunyatasattva** [comment]
We currently have an open PR that migrates StoryBook to 6.4.0. Please work off that branch whlle it is not merged and then you'll be able to rebase. https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5264

**Comment by sunyatasattva** [comment]
@lpizzinidev Do you still want to work on this issue?

**Comment by lpizzinidev** [comment]
@sunyatasattva 
I'm sorry I've been busy lately working on other projects and I didn't have the time to work on this.
Feel free to assign the issue to somebody else.
