### ISSUE TITLE
State has to be filled every time during checkout

### ISSUE THREAD

**Issue by leonardola** [woocommerce/woocommerce-gutenberg-products-block#5259]
## Describe the bug
When a logged in user enters the checkout the state field is empty and has to be manually filled every time

## To reproduce
- While logged in as a shopper with a address saved go to blocks checkout page.
- The state will not be filled 

## Expected behavior
State should be filled when customer has state saved

**Comment by gigitux** [comment]
Thanks for opening this issue @leonardola! Unfortunately, I'm unable to reproduce the issue. The form fills and there is the same behavior as in the classic checkout page.

If you can reproduce it, it would be great if you could set up a site where we could reproduce the issue as well (ie: Jurassic Ninja or an ephemeral site).

Thanks!

**Comment by leonardola** [comment]
I was using a previous version of the plugin. Updating to 6.4 fixed the bug. Closing this
