### ISSUE TITLE
Global Styles work and exploration

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#5267]
* We started implementing global styles to several blocks, but some of them proved to be more complex than expected. Those are:
  * Blocks which are rendered in PHP (ie: Product Categories List).
  * Blocks which are rendered in React (ie: Mini Cart).
  * Blocks where we need to style inner components (ie: Mini Cart quantity badge).
* This issue is about investigating what limitations the current Gutenberg API has, propose a way to fix them upstream and whether we should work-around them downstream.
* It should also include a list of all experimental features we need to use so we can get in contact with Gutenberg devs and know their plans ON graduating them.

**Comment by gigitux** [comment]
I'm closing this epic. #5665 is the new reference.
