### ISSUE TITLE
Legacy Template block: investigate using useForcedLayout() for locking

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#5270]
In a recent discussion (see p1637925029465400/1637923254.460600-slack-C8X6Q7XQU), @senadir suggested using `useForcedLayout()` to lock the Legacy Template block, that would allow adapting it to our specific needs, like making the block to reappear when deleted.

This issue is about researching if `useForcedLayout()` would be useful for the Legacy Template block and, if it is, make use of it to improve the user experience.

**Comment by tjcafferkey** [comment]
Based on my understanding I am not sure this would solve the problem. Using `useForcedLayout()` forces certain inner blocks to be present and will re-add them if removed, for example some fields (totals, tax etc) in the checkout. However, the user can get around this by deleting the parent block. This would be the problem I think with using it for our use case, the user could just delete the block templates parent block.

Just cc'ing @senadir incase I have misunderstood the hooks usage and how it could potentially be useful for our scenario.
