### ISSUE TITLE
PriceSlider IE workaround doesn't work on focus

### ISSUE THREAD

**Issue by sunyatasattva** [woocommerce/woocommerce-gutenberg-products-block#5276]
In the [`PriceSlider` component](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/assets/js/base/components/price-slider/index.js#L123) we have a function to workaround an IE issue based on the mouse position.

This piece of code runs also `onFocus`. However, the mouse coordinates (in this case `clientX` are not available on the focus event).

We should talk about a possible solution to this depending on what the original IE issue was. Paging @mikejolley as it seems you were the one who found this issue originally.

**Comment by mikejolley** [comment]
It works around lack of pointer-events (https://mikejolley.com/2019/08/02/building-a-cross-browser-compatible-multi-handle-range-slider/#supporting-internet-explorer-and-edge). 

Since this only impacts the ability to mouse over the handles, I don't expect focus to be affected. What was the problem you saw?

**Comment by sunyatasattva** [comment]
First of all, a huge thanks for the link to the blog post. It's amazing that you wrote a rundown of your experience developing this specific component, that was a fascinating read.

I didn't see any specific problem because I'm not sure how it's supposed to behave. However, if you see [here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/assets/js/base/components/price-slider/index.js#L261), `findClosestRange` is also called `onFocus`, and that function uses the `clientX` property to get the mouse position. However that property is not available in the event triggered by focus.

```js
const x = event.clientX - bounds.left;
``` 

Perhaps the `onFocus` was added to handle a11y/tabbing?

> Since this only impacts the ability to mouse over the handles, I don't expect focus to be affected. 

Maybe the solution is to just remove the handler on focus?
