### ISSUE TITLE
Mini Cart block: extensibility audit

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#5278]
Once all other issues related to the Mini Cart block have been finished, we will need to audit if extensions are working fine with it.

Some extensions that we might want to test:
* Subscriptions: are prices shown correctly (ie: `$5/month`)?
* Product Add-Ons: are product addons shown in the cart items.
* ...

This issue involves:

* Getting a list of extensions that integrate with the Cart block.
* Making sure that, when it makes sense, they integrate with the Mini Cart block as well. Basically, anything that extends the Cart line items and the totals, should extend them too in the Mini Cart block.
* Update documentation referring to the Cart extensibility points to explain (if) they also affect the Mini Cart block.

Given that we use the same React components as the Cart block, I expect most extensions to "just work" with the Mini Cart block. However, we need to test it to be sure.

**Comment by dinhtungdu** [comment]
## Testing result:

<table>
<tr>
	<td> Extension
	<td> Result
	<td> Screenshot
<tr>
	<td> <a href="https://woocommerce.com/products/product-add-ons/">Product Add-Ons</a>
	<td> ✅ This extension is working as expected with the Mini Cart Block.
	<td> <img width="1616" alt="Screen Shot 2022-01-20 at 15 04 38" src="https://user-images.githubusercontent.com/5423135/150298340-229ebfa7-ee92-4d1f-a8a7-05c4d3dfde47.png">

<tr>
	<td> <a href="https://woocommerce.com/products/name-your-price/">Name Your Price</a>
	<td> ✅ This extension is working as expected with the Mini Cart Block.
	<td> <img src="https://user-images.githubusercontent.com/5423135/150476966-1b8df589-9f04-4902-a700-888f9e3364e4.png" />

<tr>
	<td> <a href="https://woocommerce.com/products/gravity-forms-add-ons/">Gravity Forms Product Add-ons</a>
	<td> ✅ The extension is working as expected with the Mini Cart Block.
	<td> <img src="https://user-images.githubusercontent.com/3616980/150998030-b013ce2c-c015-4773-8fc6-345abb8ba2e0.png"/>

<tr>
	<td> <a href="https://woocommerce.com/products/woocommerce-subscriptions/">WooCommerce Subscriptions</a>
	<td> ✅ The Mini Cart is missing the subscription period and amount due description at the time of purchase. These information should be added because missing it make customers confused.
	<td> <img width="1692" alt="Screen Shot 2022-01-20 at 16 30 00" src="https://user-images.githubusercontent.com/5423135/150312033-9180f93f-61c5-4a85-96cd-6b9582d5078a.png">

<tr>
	<td> <a href="https://woocommerce.com/products/woocommerce-google-analytics/">WooCommerce Google Analytics</a>
	<td> ✅ There are GA events triggered when removing an item from cart and changing an item’s quantity. These events already work from the MiniCart.
	<td> N/A

<tr>
	<td> <a href="https://woocommerce.com/products/woocommerce-points-and-rewards">WooCommerce Points and Rewards</a>
	<td> ⚠️ This extension shows up to 2 notices on the cart **page** for the Cart Shortcode. For the Cart block, we integrated the point conversion form and the reward information into the Cart sidebar. The Mini Cart block only shares product list table with the Cart block, show nothing changes to the Mini Cart block if the site uses Points & Rewards.
	<td> <img width="760" alt="Screenshot 2022-01-21 at 11 35 05" src="https://user-images.githubusercontent.com/5423135/150516165-9339ef27-fd7d-4b66-9170-eab64ba91c05.png">

<tr>
	<td> <a href="https://woocommerce.com/products/composite-products/">Composite Products</a>
	<td> 🚨 This plugin isn't compatible with Cart and Checkout block. Thus it's not compatible with the Mini Cart Block. The Cart Shortcode show the relationship between the base product and its components, but the on Cart, Checkout and Mini Cart block, the components are displayed as independent products.
	<td> <img width="3008" alt="Screen Shot 2022-01-21 at 16 21 48" src="https://user-images.githubusercontent.com/5423135/150501571-9ac37eef-d807-420d-94c5-4c130e26e3ea.png">
</table>

**Comment by dinhtungdu** [comment]
@ralucaStan I updated the result above with my test against Composite Products extension. I think it should be added to [Known incompatible extensions](https://woocommerce.com/document/cart-checkout-blocks-support-status/#section-7).

**Comment by ralucaStan** [comment]
@dinhtungdu great update. 👏  Let's wait until the Mini Cart block is released before we update anything.

**Comment by Aljullu** [comment]
Thanks for testing these extensions and writing the report, @dinhtungdu!

> * WooCommerce Subscriptions: The Mini Cart is missing the subscription period and amount due  description at the time of purchase. These information should be added  because missing it make customers confused.

Oh, that was a surprise for me. I expected it would just work given that we use the same components as the Cart block. @dinhtungdu can you open an issue for this and add it to the Mini Cart epic?

> WooCommerce Points and Rewards: This extension shows up to 2 notices on the cart **page** for the Cart  Shortcode. For the Cart block, we integrated the point conversion form  and the reward information into the Cart sidebar. The Mini Cart block  only shares product list table with the Cart block, show nothing changes  to the Mini Cart block if the site uses Points & Rewards.

To me, this look like the expected behavior. @ralucaStan what do you think?

> Gravity Forms Product Add-ons

I tested it myself and everything seems to work great. :ok_hand: 

![imatge](https://user-images.githubusercontent.com/3616980/150998030-b013ce2c-c015-4773-8fc6-345abb8ba2e0.png)

**Comment by dinhtungdu** [comment]
@Aljullu I opened #5642 for WC Subscriptions.

I updated the table above with your result testing Gravity From. Thanks for that!

> To me, this look like the expected behavior.

I agree. I used the wrong icon for it. Updated accordingly.

At this point, can we close this issue and mark it as done?

**Comment by Aljullu** [comment]
> At this point, can we close this issue and mark it as done?

Yes, let's do that. If Raluca fins something we missed, we can reopen. :+1:

**Comment by ralucaStan** [comment]
> To me, this look like the expected behavior.

 I just read the description of the block `Contains the products table and other custom blocks of filled mini cart.` I guess it's a product decision if info about Point and rewards should be displayed.

@Aljullu as you are familiar with the intention of the Mini cart I trust your judgement here.
