### ISSUE TITLE
Mini Cart: don't allow users to create extra template parts in the Mini Cart template part area

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#5284]
Having more than one template part registered in the Mini Cart template part area might be confusing by users. Because of that, we won't allow the creation of extra template parts in the Mini Cart template part area.

In order to achieve this we need to:

* Revert the changes included in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5231.
* Find a way so the Mini Cart template part area is not available when creating a template part (this was introduced in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5221). I think there are two options to achieve this:
  * reverting #5221 so there isn't a Mini Cart template part area at all
  * finding some other solution so the Mini Cart template part area exists, but it's not shown in the modal when creating a new template part

**Comment by dinhtungdu** [comment]
This issue closes #5232
