### ISSUE TITLE
Twenty Twenty Two: discounted prices are underlined

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#5286]
## To reproduce
1. With the [Twenty Twenty Two theme](https://wordpress.org/themes/twentytwentytwo/), add the Products by Category block to a product or page.
2. In the frontend, check how discounted prices are shown.
3. Notice the discounted prices is underlined.

## Expected behavior
There shouldn't be underline under the discounted price.

## Screenshots
![imatge](https://user-images.githubusercontent.com/3616980/144219134-596a0b06-60d9-43c9-89fa-841f6b86e338.png)

**Comment by sunnyjain15699** [comment]
Hi @Aljullu . I would like to work on this issue. Can you guide me through it ?

**Comment by Aljullu** [comment]
Sure @sunnyjain15699! First, you will need to clone this repo and build it. You can follow [these instructions](https://github.com/woocommerce/woocommerce-gutenberg-products-block#installing-the-development-version). After that, you are ready to start making changes to the code.

In this case, you will need to add a CSS ruleset to [`assets/css/style.scss`](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/ef607e5d0348e5b5c6f439c89547837a4aac4a31/assets/css/style.scss). That's where we add custom CSS styles for specific WP themes.

You can see we had to apply [the same fix for TwentyTwenty](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/ef607e5d0348e5b5c6f439c89547837a4aac4a31/assets/css/style.scss#L244-L246), so you could use that code as a reference. You will need to update the selector so it applies to the Twenty Twenty Two theme.

Hope that helps! Let me know if you have any questions!

**Comment by sunnyjain15699** [comment]
Do I need to set up wordpress locally, using some local server software like MAMP and then install the plugin there in my local wordpress site ? Also how will I connect my locally setup code of Node and Composer with that setted up local website ?

**Comment by Aljullu** [comment]
Yes, I would recommend setting up a WordPress installation locally. How you do that, will depend on your preferences. One tool you could try is [LocalWP](https://localwp.com/), which is quite simple to use. But MAMP or anything similar should work as well.

Once you have your WordPress site set up, you will just need to clone this repo into the `/wp-content/plugins/` folder and then build it as explained in the [docs](https://github.com/woocommerce/woocommerce-gutenberg-products-block#installing-the-development-version). Once you have done that, you will be able to activate the plugin from the admin and see any changes you make.

Hope it helps and happy coding! :slightly_smiling_face:

**Comment by nielslange** [comment]
@sunnyjain15699 Are you still looking into this issue?

**Comment by Aljullu** [comment]
@tomasztunik this seems to have regressed in `trunk`. Can you test and maybe reopen this issue?

**Comment by tomasztunik** [comment]
Will test it 👍 

Confirmed underline on sale price came back.

class name changed from `.wc-block-components-product-price` to `..wc-block-grid__product-price` Opening PR to fix this.
