### ISSUE TITLE
Checkout performance benchmarking 

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#5289]
This is an epic task that is meant to:
- Research what kind of metrics we should be tracking (locally in CI, globally in merchants stores).
- Implement tracking locally/globally.

We're not yet to act on the results of this benchmarking yet, just collecting it.

Prior work for local GB tracking:
- https://codehealth.vercel.app/
- https://github.com/youknowriad/codehealth
- https://github.com/WordPress/gutenberg/pull/33694 

GB work only tracks direct users (in our case merchants), we're interested in seeing the experience of customers as well.

**Comment by ralucaStan** [comment]
Closing this epic, as we will most likely start a separate performance effort later this year.
