### ISSUE TITLE
Add descriptions to Woocommerce templates

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce-gutenberg-products-block#5295]
In WooCommerce 6, templates should also have descriptions, see the archive template.

Steps:
1. With WC 6, Gutenberg and a FSE theme installed, go to Appearance > Editor. 
2. Click the WP logo in top right to open left hand sidebar, click Templates
3. The Woocommerce templates should have a description similar to the standard Wordpress templates

<img width="816" alt="Screenshot 2021-12-02 at 14 42 29" src="https://user-images.githubusercontent.com/846565/144444204-6d3c38a4-a53e-48ec-9b92-c30321021357.png">

**Comment by Aljullu** [comment]
Heads-up that this was fixed in #6345.
