### ISSUE TITLE
Additional form in shipping

### ISSUE THREAD

**Issue by mz-mee** [woocommerce/woocommerce-gutenberg-products-block#5332]
Hi,
I use this plugin for choosing some pickup places (it´s very popular delivery company in Czech republic). But it´s not working with your plugin.

Your plugin just output shipping text, but not add form and button which is needed by this plugin. You can visit screen, with default woocommerce checkout page and your plugins checkout - https://ctrlv.cz/LFO6. There is some possibility to solve this? I think, it can be some issue for other delivery companies all over the world (not only for Packeta).

I wrote same letter to author of plugin - https://wpify.io/cs/.

Martina

**Comment by sunyatasattva** [comment]
Hi there Martina!

Thank you for reaching out to our team with your suggestion. Let me see if I understood you correctly: you are using a 3rd party plugin from WPify (could you point out the exact plugin, please?) and, with this plugin, on the shipping section there will be some extra actions added which are required for the plugin to work, but they don't show up in our blocks, is that correct?

Help me understand here, what is missing is this button, correct?

![czech-shipping](https://user-images.githubusercontent.com/1847066/145221384-ee032b6a-169f-4350-b10f-6c6d2a6ffb3c.png)

Did I get this right? Is there anything else that is missing?

Thanks a bunch for your information: the more precise you can be, the more likely I can see if we can provide any help from our side.

**Comment by mz-mee** [comment]
Hello,
that´s exactly it.
The plugin you can download here -
https://cs.wordpress.org/plugins/wpify-woo/ and the modul is called Packeta
(Zásilkovna).

I found plugin, that works with this shipping button, there is -
https://cs.wordpress.org/plugins/fluid-checkout/. You can visit our website
cart to see the html output (it´s only in czech, shop catalog is here -
https://tvprodeti.cz/kramek/).

I solve my problem by other plugin, but your UX is better and nicer, so I
hope, that I can use it in future. :)

Nice day,

Martina

st 8. 12. 2021 v 15:03 odesílatel M. L. Giannotta ***@***.***>
napsal:

**Comment by sunyatasattva** [comment]
Hello Martina,

Thanks for your reply. Unfortunately, this seems to be an issue with the plugin author, as it's their responsibility to provide compatibility with our blocks. We do provide opportunities for such plugins to extend our functionality like it is shown in the screenshot you provided.

You could point the plugin author specifically to [this documentation](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/extensibility/available-slot-fills.md#experimentalordershippingpackages) which should solve the specific problem of adding the extra button required, and, more generally, to our [extensibility docs](https://github.com/woocommerce/woocommerce-gutenberg-products-block/tree/trunk/docs/extensibility).

We are really glad you prefer our UX as we are working really hard on it, and hopefully you can help bring more plugin authors to our ecosystem.

For now, I will be closing this specific ticket, as the functionality is provided and it's up to them to use it. But feel free to contribute or open new tickets in the future. Your support is appreciated!

**Comment by mz-mee** [comment]
Ok, I understand. Thanks for your time! If developer of plugin contact me,
I resend him the links.

Martina

st 8. 12. 2021 v 18:03 odesílatel M. L. Giannotta ***@***.***>
napsal:
