### ISSUE TITLE
Featured Product block breaks when product is out of stock + hidden from catalog

### ISSUE THREAD

**Issue by Robertght** [woocommerce/woocommerce-gutenberg-products-block#5344]
This is a replica of https://github.com/Automattic/wp-calypso/issues/58595

----

### Quick summary

'Featured Product' block breaks in the editor when the product is out of stock _and_ the Inventory is set to hide out of stock items from the catalog. Selecting `edit` results in `This block has encountered an error and cannot be previewed.`

### Steps to reproduce

1. Open a WooCommerce Site
2. Add a Featured Product block to a page and save
3. Head to the products and set the product to **Out of Stock**
4. Under WooCommerce > Settings > Products > Inventory, check the box that says "Hide out of stock items from the catalog"
5. Return to the page with your Featured Product block, select it, and select "Edit" to choose a new product to feature

<img width="960" alt="Markup 2021-11-29 at 10 04 32" src="https://user-images.githubusercontent.com/27249804/143914067-7ce7d817-1d57-4575-8045-c732219e9d46.png">

<img width="1095" alt="Markup 2021-11-29 at 10 11 34" src="https://user-images.githubusercontent.com/27249804/143914084-30fc0cf8-319c-44e7-ab74-d4f28237a64a.png">

### What you expected to happen

The block can still be edited to choose a new product. 

- When "Hide out of stock items from the catalog" is _unchecked_, the block responds as expected. 

### What actually happened

Clicking edit results in a broken block

https://user-images.githubusercontent.com/27249804/143914004-d40f04aa-967b-4c61-9be7-57e00d209d06.mp4

### Context

Reported by a user here: 32966334-hc
Was able to recreate on my test site

### Operating System

macOS

### Browser

Mozilla Firefox

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Removing the block and re-inserting it is a quick workaround

I can confirm this happens with WooCommerce Blocks 6.5.0

**Comment by opr** [comment]
Given that the block still displays the product on the front-end (regardless of stock-hiding status) I propose that we allow the merchant to select any product for display in the block (regardless of stock status). We could also put the stock status next to the product name too. cc @vivialice what do you think of this UX?

**Comment by vivialice** [comment]
> I propose that we allow the merchant to select any product for display in the block (regardless of stock status)

Do you mean select from the Site Editor settings?

> We could also put the stock status next to the product name too

I think this could be another setting to opt-in to and not added in by default. We could use the toggle selector perhaps.

**Comment by Aljullu** [comment]
@opr are you still working on this one?

**Comment by opr** [comment]
> @opr are you still working on this one?

No sorry, I forgot to unassign myself @Aljullu

**Comment by albarin** [comment]
@Aljullu @opr I've been digging a bit on this bug and I've figured out what's going on. The same bug is actually also happening on other blocks that use the product search with variations (like `Single Product`).

There are two possible ways of fixing this:
- Allowing to select any product regardless of its status (as @opr suggested)
- Not allowing it (when clicking `Edit` it won't break but won't show the `outofstock` product in the list of available products for the block)

What do you think? 🤔

**Comment by tomasztunik** [comment]
I believe we should make it possible to select any product and handle it properly unless it's hidden - which is like deliberately saying "Do not show it anywhere" - user should have the confidence it won't pop up unexpected. 

I believe it should be possible to select out of stock items simply because user might be setting up draft or hidden page before everything is available/set up in the catalogue. And they should be able to build and plan publishing content for the future.

**Comment by Aljullu** [comment]
+1 from my side. Allowing to select any product regardless of its status sounds to me like the best option.
