### ISSUE TITLE
Use native forEach in SearchListControl utils

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#5356]
SearchListControl utils file is [importing `forEach` from lodash](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/ffc42ecb748b932ad67c47be0258699985e03233/assets/js/editor-components/search-list-control/utils.tsx#L4). However, the [`forEach` native equivalent ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach) is well-supported in all browsers we support and it means we will have one less dependency from lodash.

This issue is about:

* Removing the `forEach` import from lodash.
* Replace the `forEach` usage with it's native counterpart.
* Test that there are no regressions.

**Comment by sunnyjain15699** [comment]
Hi @Aljullu . I would like to work on this issue. Can you guide me through it ?

**Comment by Aljullu** [comment]
Sure @sunnyjain15699, let me know if you have any questions. The issue description already has a link to the file you will need to modify, but expanding it a bit more.

First, you will need to clone this repo and build it. You can follow [these instructions](https://github.com/woocommerce/woocommerce-gutenberg-products-block#installing-the-development-version). After that, you are ready to start making changes to the code.

You will need to remove `forEach` from this line import:

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/ffc42ecb748b932ad67c47be0258699985e03233/assets/js/editor-components/search-list-control/utils.tsx#L4

and then modify these three lines to use the native `forEach`:

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/ffc42ecb748b932ad67c47be0258699985e03233/assets/js/editor-components/search-list-control/utils.tsx#L80-L82

You can see how the native `forEach` function works in this [documentation page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach).

Hope that helps! Let me know if you have any other questions!

**Comment by nielslange** [comment]
@sunnyjain15699 Are you still looking into this issue?

**Comment by Aljullu** [comment]
Closed by #5965.
