### ISSUE TITLE
Mini Cart: make it so the link to the template part works on WP 5.8 + GB and WP 5.9

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#5357]
Issue surfaced by @dinhtungdu in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5348#pullrequestreview-828545463. The template editor URL is different in WP 5.8 + GB and WP 5.9, so we can't reliably link to it without doing a WP version check.

Ideally, instead of adding the logic to check the WP version in WC Blocks, we can contribute upstream in Gutenberg and create a `get_site_editor_url()` function that we, and other plugin devs, can use to link to the site editor. See: https://github.com/WordPress/gutenberg/issues/37277.

**Comment by gigitux** [comment]
In accordance with [this comment](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5372#issuecomment-992298108), I think that we can close this issue. What do you think? @Aljullu

**Comment by Aljullu** [comment]
Right!
