### ISSUE TITLE
Mini Cart: investigate if 'Edit template part' link should be available only to users with certain capabilities

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#5359]
The Site editor is not available to all users, only those with `current_user_can( 'edit_theme_options' )` can access it, if I'm not wrong. Because of that, the link to edit the template part should only be visible to users that can edit it.

This issue is about:

* Researching which permission level is needed to edit template parts.
* Update the Mini Cart block code so the link to edit the template part is only available to users with those permissions.

## To reproduce
1. Go to Users > Add new and create a user with role _Author_.
2. Log in with that user.
3. Add a Mini Cart block and click on the Edit template part link:
![imatge](https://user-images.githubusercontent.com/3616980/145562689-23c84603-d6f5-4cf8-b1b2-d6d3d48527a3.png)
4. Notice you are redirected to a page which you don't have permission to see:
![imatge](https://user-images.githubusercontent.com/3616980/145562748-af94f7a0-90e8-49d2-9d2e-47546f4620a1.png)

**Comment by dinhtungdu** [comment]
I think it's better to set the edit link from the backend. So in the editor, we just need to check for a single variable.

**Comment by Aljullu** [comment]
> I think it's better to set the edit link from the backend. So in the editor, we just need to check for a single variable.

Agree, I was thinking about this too, we would need to pass less variables from PHP to JS.
