### ISSUE TITLE
Updating shipping method at checkout doesn't update the draft order that's been created.

### ISSUE THREAD

**Issue by brettshumaker** [woocommerce/woocommerce-gutenberg-products-block#5366]
## Describe the bug
During checkout, changing the selected shipping method updates the data in the session, but does not update the draft order that has been created.

## To reproduce

1. Make sure at least 2 shipping methods are enabled for your store.
2. Add products to your cart.
2. Go to the block checkout page.
3. In a new window/tab, open the 'Edit' screen for the draft order created on `wp-admin/edit.php?post_status=wc-checkout-draft&post_type=shop_order`
4. Observe shipping method.
5. Go back to the checkout page and update the shipping method.
6. Go back to the draft order screen, refresh and see that the shipping method has not changed to match the checkout UI.

## Expected behavior
I would expect that updating the shipping method on the checkout UI would cause that shipping method to be updated anywhere that my cart/order/session data is stored.

## Screenshots
Here's a screen recording of me going through the above steps and then also updating the shipping address in checkout to demonstrate that doing so updates the draft order.

https://user-images.githubusercontent.com/1558827/145601832-64d3fffe-de36-4308-aff1-0dc6559a2d75.mp4

### WordPress (please complete the following information):
* Core version: 5.8.2
* WooCommerce version: 5.8.0
* WooCommerce Blocks version: 6.2.0

### Desktop (please complete the following information):
* OS: Mac
* Browser Brave
* Version 1.32.115

## Additional context
cc @senadir

**Comment by mikejolley** [comment]
@senadir we need to decide which cart endpoints update orders too, since this has come up twice now. Other endpoints that could affect orders, but currently only affect the cart include _line item_ endpoints (e.g. add to cart/remove from cart/coupons). These only persist cart data to the order when the checkout page is loaded, and when the order is placed. There is a helper which converts and syncs cart data to an order.

Shipping works the same. Upon entry, the shipping method from the cart is synced to the order, and upon placing the order, shipping (as well as all other order data including addresses) is persisted.

@brettshumaker Obviously watching the draft order in admin and seeing what changes lets you observe this, but that doesn't appear to be a real-world use case. Can you explain why this behaviour is needed?

**Comment by senadir** [comment]
> we need to decide which cart endpoints update orders too, since this has come up twice now. Other endpoints that could affect orders, but currently only affect the cart include line item endpoints (e.g. add to cart/remove from cart/coupons).

It would make that sense that all of them update the order or none of them updates it, I'm leaning toward all of them updating order but I feel like this isn't an outcome you're looking to get @mikejolley? Also, is there performance issues if they all updated an order?

**Comment by mikejolley** [comment]
@senadir I'm not in favour of that. We shouldn't treat orders as the storage mechanism for cart data, and yes, there is an overhead to syncing cart data to order data.

I would prefer that the data collected during checkout is only persisted when you place the order, like a traditional form submit, with the initial cart->order sync on entry. If certain things need to be updated during checkout flow, it should be done via a `checkout/` endpoint. I know we made the customer update endpoint update both, but this was to avoid a refactor of the use-customer-data hook. I think it would be good to use a PATCH request on `checkout/` for that instead.

**Comment by brettshumaker** [comment]
> Can you explain why this behaviour is needed?

@mikejolley This just came up during the development of the platform checkout. I don't know that it's specifically "needed" for what we're building, but it seemed like a bug since only _some_ cart data is synced with the draft order so I reported it.

@frosso - is this something we would need for the platform checkout? My initial thought is "no" but want to check with you as well.

**Comment by frosso** [comment]
> is this something we would need for the platform checkout? My initial thought is "no" but want to check with you as well.

I agree with you @brettshumaker - I don't think it's not needed, just a little inconsistency we noticed.

Thanks for the explanation on the functionality!

**Comment by senadir** [comment]
> We shouldn't treat orders as the storage mechanism for cart data, and yes, there is an overhead to syncing cart data to order data.

I agree.

> I would prefer that the data collected during checkout is only persisted when you place the order, like a traditional form submit, with the initial cart->order sync on entry.

I think this would be at odds with what we're doing right now, and would cycle us back to the same API we had a year ago with shipping being a separate endpoint.

> If certain things need to be updated during checkout flow, it should be done via a checkout/ endpoint.

We also update coupons and select shipping during checkout, which are done via cart and reflect cart.
We update shipping and billing addresses which are a shipping property but reflect cart, as they update totals.

> know we made the customer update endpoint update both, but this was to avoid a refactor of the use-customer-data hook. I think it would be good to use a PATCH request on checkout/ for that instead.

Are you suggesting, given time and effort, updating addresses should be done via checkout post? how about the addresses present via cart and selecting shipping in cart, should that still be supported?

**Comment by mikejolley** [comment]
> We also update coupons and select shipping during checkout, which are done via cart and reflect cart.

I forgot about those. So you're suggesting whenever cart updates, we update checkout/order too then?

In theory I guess we'd have to if certain things, like line items, ever had the ability to update/remove during checkout itself.

Let me ponder this some more. Perhaps we could solve this across all routes by always running a sync after a cart update, if a draft order is in session.

**Comment by senadir** [comment]
> I forgot about those. So you're suggesting whenever cart updates, we update checkout/order too then?

I'm actually okay with not updating the order until its placed, with the only exception is persisting the email.

> Let me ponder this some more. Perhaps we could solve this across all routes by always running a sync after a cart update, if a draft order is in session.

Take your time, however, if we still feel like updating order is going to cause a performance issues, we can just work with the premise that its only going to be updated three times:
- On checkout load.
- On entering email.
- On placing order.

Other updates are all handled by cart (coupons, shipping fields, shipping methods, future possibility of updating items).
