### ISSUE TITLE
Checkout Block ignores woocommerce_available_payment_gateways hook

### ISSUE THREAD

**Issue by chrismademe** [woocommerce/woocommerce-gutenberg-products-block#5388]
## Describe the bug
When using the WooCommerce Checkout block, the `woocommerce_available_payment_gateways` hook is not respected and so any payment gateways added/removed here are not reflected at checkout.

## To reproduce

1. Enable a payment gateway in WooCommerce settings, bank transfer for example.
2. Add this code to your theme's `functions.php`:

```php
<?php
add_filter( 'woocommerce_available_payment_gateways', function( $methods ) {

    // Remove BACS for normal customers
    if ( ! current_user_can( 'manage_woocommerce' ) ) {
        unset($methods['bacs']);
    }

    return $methods;
} );
```

3. Make sure you're logged out, add a product to your cart and head to the checkout
4. BACS will be available, dispite being removed in a filter

## Expected behavior
The available gateways should be the same as those that appear in the classic shortcode checkout, having been filtered.

### WordPress (please complete the following information):
* Core version: 5.8.2
* WooCommerce version: 5.9.0
* WooCommerce Blocks version: 6.5.0
* Site language: en_US

### Desktop (please complete the following information):
* OS: macOS
* Browser: Chrome
* Version: Latest

Thanks!
Chris

**Comment by mikejolley** [comment]
For anyone reviewing this issue, this is not a straightforward swap to `get_available_payment_gateways`. The example above is simplistic and doesn't factor in more advanced use cases where payment method availability could be based on cart items, customer, address, etc etc. Therefore the ideal solution would be to return available methods via the API, potentially on both the `cart` and `checkout` routes. This can then be used to render payment options on checkout.

**Comment by chrismademe** [comment]
Thanks for the response. I appreciate it's probably not as straight forward as it seems.
With that said, is there currently a way to filter available methods on the frontend?

**Comment by ralucaStan** [comment]
> is there currently a way to filter available methods on the frontend? 

@chrismademe take a look at [the filtering payment gateways section](https://developer.woocommerce.com/2021/11/09/available-extensibility-interfaces-for-the-cart-and-checkout-blocks#filtering-payment-methods) in the _Available Extensibility Interfaces for The Cart and Checkout Blocks_ post, you might find what you need.

**Comment by chrismademe** [comment]
@ralucaStan I will do, thank you! :)
