### ISSUE TITLE
Improve Currency type documentation

### ISSUE THREAD

**Issue by sunyatasattva** [woocommerce/woocommerce-gutenberg-products-block#5397]
> This issue is an umbrella issue for the automatically generated issues via the `@todo` comments by @github-actions. This replaces and closes #5391, #5392, #5393

As part of TypeScript migration and Storybook docs, we have made and documented a few TS interfaces. Currently, the currency interface accepts any `string` as currency code, which would not be exact. A stricter type would mean allowing only available currency codes.

The same, arguably, should be done for allowed currency symbols, though perhaps it would be less important.

Also, during the documentation, the [meaning of `minorUnit`](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/509bede1c950d3426ab3819fed81c5349642c106/assets/js/types/type-defs/currency.ts#L13) it wasn't understood and hence not documented. Documentation should be added there.

---
https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/509bede1c950d3426ab3819fed81c5349642c106/assets/js/types/type-defs/currency.ts#L5-L18
---

See #5293

**Comment by mikejolley** [comment]
@sunyatasattva The list of allowed currency codes is filterable and therefore can vary from store to store making typing difficult. See https://github.com/woocommerce/woocommerce/blob/77917a2de31d76f90b4380815a48b4efcef543a8/plugins/woocommerce/includes/wc-core-functions.php#L475

**Comment by sunyatasattva** [comment]
That's great that we already have a list, though. I understand we can't precisely type everything, but already having a union type of all those codes would be better than just `string`. Because, while we don't know if `CLP` is a valid code for a specific store in a specific moment (and that's a runtime issue), we know that `CLO` is probably a typo somewhere and things like this. I mean, we know the subset of all possible strings that can be assigned there, and that gives us a better protection than a generic `string` type.

What are your thoughts?
