### ISSUE TITLE
Enable read only items in the cart block

### ISSUE THREAD

**Issue by codewp** [woocommerce/woocommerce-gutenberg-products-block#5415]
## Is your feature request related to a problem? Please describe.
Add ability to lock a specific item in the Cart block so the user can't change its quantity or delete it using the "Remove item" link.

It is possible to do the above feature in the WooCommerce cart shortcode with hooks but it is not possible in the cart block. 

More details about the use-case in this comment https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5415#issuecomment-1002583218

## Additional context

Please check the below image for more information.

![5](https://user-images.githubusercontent.com/10684451/146680228-ba64ec4e-14a2-4544-9cdb-d8eb8cca51ea.png)

**Comment by ralucaStan** [comment]
Hello @codewp,
Thanks for taking the time to leave your feature request. We really appreciate you sharing your idea with us.

This enhancement is something that we are working on at the moment, in [this PR](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5406). Please follow our future releases to find out when this will be added. 

I am gonna close this issue for now; this does not mean you won't be able to comment further on it if you have additional feedback to your enhancement.

**Comment by codewp** [comment]
Hi @ralucaStan 

Thanks for your feedback.

In the pull request that you mentioned, I see there is only locking the quantity change field but it seems that there is not a filter to lock the "remove product" field too.

Please let me know does that pull request supports locking the "remove product" field too?

Thanks

**Comment by ralucaStan** [comment]
Hi @codewp ,
thank you for the fast reply. Indeed the PR does not remove the "Remove item" link, as the use case it tries to fix, unique products, does not require this change.

We would need to hear more about your use case in order to understand the particular need you have on your store. Based on it we will decide the next steps.

**Comment by ralucaStan** [comment]
From what I'm able to understand from the picture you attached the need would be to offer free gifts. What are the properties of the free gift? Could there be more than 1 item of the same free gift? Does it get shipping costs? Does it get added to the order after checkout or during cart? Does it need to be a cart item, or just displayed in the cart somewhere?

**Comment by codewp** [comment]
Hi @ralucaStan 

Thank you for your reply and for your explanation.

A plugin that implements BOGO deals, needs this requirement.

For example, a Buy One Get One deal will automatically add a product to the cart, and based on it the customer cannot remove that product or edit that free product quantities.

Remove or edit quantities of the free gift is controller by the BOGO deals plugin.

The gift product can be a regular product in the shop which is selected by the manager.

It is a regular cart item with extra information added to that product to make it different from other products. It has a cart item ID and a zero price with other information that is added to the cart.

We implement this feature in our [discount plugin for WooCommerce](https://www.asanaplugins.com/product/woocommerce-dynamic-pricing-and-discounts-plugin/).

BOGO deals can be applied to the same product or on another product. For example, customers can purchase a Polo and get another Polo as a gift, or get a Cap as a gift. The gift products are regular products of the shop with an edited price to be free and locking it in the cart.

Please let me know does this information makes sense?

Thanks

**Comment by ralucaStan** [comment]
@codewp I've reopened the issue and edited it for more clarity. 
Thank you for the helpful answer. One more question, what can you tell me about shipping for this free gifts?

**Comment by codewp** [comment]
@ralucaStan 

Thanks for your time and for editing the issue.

Actually, I don't decide about the shipping and the plugin has not had such a feature yet to edit the shipping cost of free products yet.

We have a [shipping discount for WooCommerce](https://www.asanaplugins.com/product/shipping-discount-woocommerce/) plugin that supports shipping discounts, maybe it can help us to discount the shipping cost of free products, but this feature is not been requested by our customers yet.

Please let me know if you have any questions.

Thanks.

**Comment by opr** [comment]
cc @alexflorisca looks like this is similar functionality to #5745

Pinging you here so you're aware of this.
