### ISSUE TITLE
Store Editing Templates: Currently using the incorrect slug for WooCommerce

### ISSUE THREAD

**Issue by tjcafferkey** [woocommerce/woocommerce-gutenberg-products-block#5423]
## Describe the bug

Amongst the code for the WooCommerce Store Editing Templates we are using the id/slug `woocommerce` or `WooCommerce` for our block templates. We've recently discovered the correct value should possibly be `woocommerce/woocommerce`and have noticed a number of issues because of this:

* On the frontend when the component tries to [fetch the WooCommerce plugin data by slug](https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-site/src/components/list/added-by.js#L61-L64), it fails to get anything.
* XHR requests are being sent to incorrect endpoints such as `/wp-json/wp/v2/plugins/WooCommerce` and getting a 404 response, when the should be going to `/wp-json/wp/v2/plugins/woocommerce/woocommerce`.
* In the database under the table `wp_terms` we're saving this incorrect slug as `woocommerce` (under `name` and `slug` columns) when it should be `woocommerce/woocommerce` (name) and `woocommerce-woocommerce` (slug).

As a result of this, if we were to simply make some code amendments and update our usages to use the correct value, this means that users who have already modified their WooCommerce templates would no longer see them listed in the Templates list view, and they would also not be found when fetching them to render on the frontend because we'd be looking for the new value (`woocommerce/woocommerce`) when searching the DB for templates saved against the old value (`woocommerce`)

Related https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5420
Related https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5412
Related https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5375
Related https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5327

**Comment by gigitux** [comment]
> We've recently discovered the correct value should possibly be woocommerce/woocommerce (this will need double checking)

I agree with double-checking this.

If we are sure that the structure is `plugin-slug//template-slug` and our plugin slug is `woocoommerce/woocommerce` we are ready to go.

My concern is that `woocoommerce/woocommerce//${slug}` could be not very clear if it is checked by someone that doesn't have context,  it can be a little bit tricky.
