### ISSUE TITLE
On WordPress 5.8 an error will be display if the user after save the template refresh the page 

### ISSUE THREAD

**Issue by gigitux** [woocommerce/woocommerce-gutenberg-products-block#5426]
## Describe the bug
On WordPress 5.8 the error `You attempted to edit an item that doesn't exist. Perhaps it was deleted?` when the user after saving the template, keeps staying in the template editor and refresh the page.

## To reproduce

1. Open the FSE editor
2. From the sidebar on the left click on `Templates`.
3. Click on one of these templates `Product Category Page`, `Product Archive Page`, `Product Archive Page` or `Single Product Page`. (check that it is not a modified template )
4. Edit the template and save it.
5. Refresh the page.

## Expected behavior
The user can refresh the editor and continue to edit the template.
## Screenshots
![image](https://user-images.githubusercontent.com/4463174/146918125-a0a20789-a580-43d3-a8d3-07492117a08e.png)

**Comment by frontdevde** [comment]
Retested today and can't reproduce the issue with WP 5.8.3 and the latest WooCommerce Blocks & Gutenberg. 
Closing as it can't be reproduced anymore. Assuming this was likely fixed in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5425
