### ISSUE TITLE
Form autofill doesn't work when using 1Password

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#5428]
## Describe the bug

In #4561, we ensured that autofill within the checkout blocks works as expected. While testing the WooCommerce Blocks 6.6.0 release, I discovered that the autofill functionality is working when using the native autofill functionality of Chrome, but not when using 1Password.

## To reproduce

1. Create a test page with the checkout block.
2. Go to the shop page and add a product to the cart.
3. Go to the checkout page and autofill the address using 1Password.
4. Remove one of the required fields, e.g. the city, and click on `place Order`.
5. Add the missing field using autofill of 1Password and click `Place Order` again.
6. See that the input field still shows an error despite being filled.

## Expected behavior

When using autofill the form using 1Password I expect that no form errors are visible.

## Screenshots

![autofill](https://user-images.githubusercontent.com/3323310/146921956-68a87d8e-30cd-4b22-9cce-6f7ac9a36507.png)

## Additional context

This is an extension to #4561.

**Comment by mikejolley** [comment]
cc @senadir

**Comment by opr** [comment]
This works ok on non-localhost sites - set up a JN site to test this and you'll see it's not reproducible there. The error that _seems_ to be happening locally is
```
Failed to fillFrame: Frame is missing uuid.
(anonymous) @ injected.js:4
(anonymous) @ injected.js:4
(anonymous) @ injected.js:4
n @ injected.js:4
```
from the 1Password JS files. 

I created a post on their forums to see if we can get more info about this.

**Comment by opr** [comment]
Further discussion happening on the 1Password forums https://1password.community/discussion/comment/625916/#Comment_625916

**Comment by ralucaStan** [comment]
Just tested and autofill works with 1password
