### ISSUE TITLE
Country is required error on Checkout block

### ISSUE THREAD

**Issue by opr** [woocommerce/woocommerce-gutenberg-products-block#5451]
## Describe the bug
When on the Checkout block, entering an email and moving to the next input causes an error: `Country is required` - this happens before the user even has chance to enter the country.

Introduced in #5394 

## To reproduce
**Do this in an incognito/private window**
1. Add something to your cart.
2. Go to the Checkout block.
3. Enter an email and blur the input.
4. See the error.

## Expected behavior
The error should not happen and the Checkout form should already have the default country pre-filled (at least it did before #5394 was merged)

**Comment by mikejolley** [comment]
This looks to also have been fixed by https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5473
