### ISSUE TITLE
FSEO: Keep an eye on the customizer settings

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#5454]
In #30044, the link Customize WooCommerce had been added to Apperance section and the back button of the WooCommerce settings within Apperance » Customize had been removed. This change had been applied assuming that when using a block theme, the Customizer would no longer be visible.

In WordPress/gutenberg#35877, a switch had been added to Gutenberg, to show the Customizer for block themes, when a plugin is adding settings to the Customizer.

This issue serves aims to keep an eye on the customizer settings once WordPress 5.9+ landed, to ensure that the customizer will remain visible when a plugin is utilizing it.

**Comment by Aljullu** [comment]
@nielslange now that WP 5.9 has been released, should we close this issue? I think your [fix in WC core](https://github.com/woocommerce/woocommerce/pull/31508) was all that was needed, is that right?

**Comment by nielslange** [comment]
> @nielslange now that WP 5.9 has been released, should we close this issue? I think your [fix in WC core](https://github.com/woocommerce/woocommerce/pull/31508) was all that was needed, is that right?

Yes. All good here, and this issue is no longer needed. Closing now. 🙌
