### ISSUE TITLE
Slot fill for cart items - Insert link into cart below arcticle name

### ISSUE THREAD

**Issue by deinstern24** [woocommerce/woocommerce-gutenberg-products-block#5514]
Hey there,
is there any way, like a hook or something, how I can add a simple link below each article name when using the new cart block?
I need this to enable a cart edit addon, so that a customer is able to click this link and then edit the article. The only other way would be to force the user to actually delete an item and then go over the customization again and add it to the cart again, which would be really... well, not so nice :-)
I really like the cart and checkout blocks otherwise, keep up the good work!
Kind regards
Ansgar

**Comment by opr** [comment]
Hi there, thanks for reaching out with your question and for providing feedback on the Cart and Checkout blocks!

To help me understand a bit more about what you're trying to do could you clarify what exactly you have in mind when you say "edit the article" what edits do you expect the user to make, where does clicking the link take them etc.

Are the customisations you're referring to things like attributes (Size, Colour etc.) or something else?

Thanks :)

**Comment by deinstern24** [comment]
Hi there,and thanks for your reply!Yes the customizations are like attributes. A customer has to choose some dropdowns and also enter some text. I got a plugin which inserts a link in the cart to edit this article, using standard woocommerce filter for the article name.So if a customer at the cart page realizes he made a mistake like a typo, he can go and edit the article instead of deleting and starting from scratch.The standard filters do not work with the new blocks, so I would need some other way to get that "edit link" into the cart.I hope that clarifies things a little?Am 06.01.2022 17:21 schrieb Thomas Roberts ***@***.***>:
Hi there, thanks for reaching out with your question and for providing feedback on the Cart and Checkout blocks!
To help me understand a bit more about what you're trying to do could you clarify what exactly you have in mind when you say "edit the article" what edits do you expect the user to make, where does clicking the link take them etc.
Are the customisations you're referring to things like attributes (Size, Colour etc.) or something else?
Thanks :)

**Comment by mikejolley** [comment]
There is no [slot fill at cart item level](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/extensibility/available-slot-fills.md). I'll update the issue title and mark this as a feature request.
