### ISSUE TITLE
Duplicated error messages in the checkout block

### ISSUE THREAD

**Issue by rafaelzaleski** [woocommerce/woocommerce-gutenberg-products-block#5530]
## Describe the bug
Duplicated error messages in the checkout block (view screenshot below). 

## To reproduce
With the "WooCommerce Gateway Stripe" plugin enabled in test mode:

1. Add products to the cart and go to a page with the checkout block
2. Enter the required fields 
3. Use any of the failure cards from [this list](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#checkout-failures-with-various-cards)
4. Submit the payment
5. See the duplicated error message as per the screnshot.

## Expected behavior
Only one error message should be shown.

## Screenshots

<img width="1128" alt="Screen Shot 2022-01-05 at 16 02 28" src="https://user-images.githubusercontent.com/4153905/148443131-2bce0c6a-acc7-4fb9-82bc-0e017631e843.png">

### WordPress (please complete the following information):
* Core version: 5.8.2
* WooCommerce version: 6.0.0
* WooCommerce Blocks version: 6.7.0
* Site language: en-US
* Any other plugins installed:
* WooCommerce Gateway Stripe v6.0.0

### Desktop (please complete the following information):
* OS: macOS
* Browser: Chrome
* Version 96.0.4664.110 (Official Build) (x86_64)

## Additional context
--

**Comment by opr** [comment]
Hey @rafaelzaleski this was fixed in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5476 can you get the latest trunk and verify it fixes this issue for you please?

**Comment by rafaelzaleski** [comment]
@opr, the issue is fixed in the trunk branch!
