### ISSUE TITLE
Store Editing Templates: Migrate incorrect plugin slug in the database.

### ISSUE THREAD

**Issue by tjcafferkey** [woocommerce/woocommerce-gutenberg-products-block#5533]
#### Description

Please read the original issue about the incorrect plugin slug here https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5423

We were able to fix this by updating the usages to use the correct plugin slug (https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5519) (`woocommerce/woocommerce`) and querying the DB for both the incorrect and correct slugs used. For sites that have already customised DB templates whilst using the old slug they will have this saved in their DB. We need to migrate these values to the new slug.

#### What we need to consider

**If the site has DB entries using the old slug _and_ the new slug:**
We will have to find the `term_id` for the old slug and update all entries using it to use the _new_ slugs `term_id`.

**If the site has DB entries just using the old slug:**
We can simply update the old slug row in `wp_terms` 

From:
name: `WooCommerce` 
slug: `woocommerce`

To:
name:`woocommerce/woocommerce` 
slug: `woocommerce-woocommerce`

**Comment by frontdevde** [comment]
Closing this issue as we decided against a DB migration (see slack-archives/C8X6Q7XQU/p1642065460228900).
