### ISSUE TITLE
FSE - URL inconsistency in WooCommerce Block templates

### ISSUE THREAD

**Issue by puntope** [woocommerce/woocommerce-gutenberg-products-block#5540]
## Describe the bug

If you enter into the FSE editor, modify a template, and reload the page. It shows that the template is maybe deleted. 
If you go back to templates, reload, and enter clicking on. the template, it works.

Seems like for the default template URL parses as `woocommerce/my-template` but after you modify it, it parses as `WooCommerce/my-template`

## To reproduce

1. Install Wp.5.9 and WC6.1 (probably with 6.0 also doesn't work) 
2. Activate TT2 theme
3. Go to Appearance -> Editor (beta) 
4. Go to templates, by clicking on the WP logo at the top left corner.
5. Select a WooCommerce template not edited before, for example Single Product
6. Edit the template and save
7. Reload the page
8. Template not found

## Expected behavior

In step 8. Template is found

## Screenshots

Video with my voice explaining the bug

https://user-images.githubusercontent.com/5908855/148780986-872e0159-f216-47a0-a704-f549ac71d663.mov

### WordPress (please complete the following information):

<details>
<summary>SSR</summary>
### wp-core ###

version: 5.9-RC1-52464
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /var/www/html
wordpress_size: loading...
uploads_path: /var/www/html/wp-content/uploads
uploads_size: loading...
themes_path: /var/www/html/wp-content/themes
themes_size: loading...
plugins_path: /var/www/html/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-active-theme ###

name: Twenty Twenty-Two (twentytwentytwo)
version: 1.0
author: the WordPress team
author_website: https://wordpress.org/
parent_theme: none
theme_features: core-block-patterns, post-thumbnails, responsive-embeds, editor-styles, html5, automatic-feed-links, block-templates, widgets-block-editor, wp-block-styles, editor-style
theme_path: /var/www/html/wp-content/themes/twentytwentytwo
auto_update: Disabled

### wp-themes-inactive (11) ###

Twenty Eleven: version: 3.9, author: the WordPress team, Auto-updates disabled
Twenty Fifteen: version: 3.0, author: the WordPress team, Auto-updates disabled
Twenty Fourteen: version: 3.2, author: the WordPress team, Auto-updates disabled
Twenty Nineteen: version: 2.1, author: the WordPress team, Auto-updates disabled
Twenty Seventeen: version: 2.8, author: the WordPress team, Auto-updates disabled
Twenty Sixteen: version: 2.5, author: the WordPress team, Auto-updates disabled
Twenty Ten: version: 3.5, author: the WordPress team, Auto-updates disabled
Twenty Thirteen: version: 3.4, author: the WordPress team, Auto-updates disabled
Twenty Twelve: version: 3.5, author: the WordPress team, Auto-updates disabled
Twenty Twenty: version: 1.8, author: the WordPress team, Auto-updates disabled
Twenty Twenty-One: version: 1.4, author: the WordPress team, Auto-updates disabled

### wp-plugins-active (8) ###

WooCommerce: version: 6.1.0-rc.2, author: Automattic, Auto-updates disabled
WordPress Beta Tester: version: 3.1.4, author: Peter Westwood, Andy Fragen, Auto-updates disabled
WP Mail SMTP: version: 3.2.1, author: WPForms, Auto-updates disabled

### wp-plugins-inactive (6) ###

Akismet Anti-Spam: version: 4.2.1, author: Automattic, Auto-updates disabled
AutomateWoo: version: 5.5.7, author: WooCommerce, Auto-updates disabled
Follow-Up Emails: version: 4.9.16, author: WooCommerce, Auto-updates disabled
Pinterest for WooCommerce: version: 1.0.1, author: WooCommerce, Auto-updates disabled
WooCommerce Admin: version: 3.0.1, author: WooCommerce (latest version: 3.0.3), Auto-updates disabled
WooCommerce Beta Tester: version: 2.0.5, author: WooCommerce, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1690
imagemagick_version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org
imagick_version: 3.5.1
file_uploads: File uploads is turned off
post_max_size: undefined
upload_max_filesize: undefined
max_effective_size: 0 B
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 122 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 786432
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 1
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DJVU, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, JBG, JBIG, JNG, JNX, JPE, JPEG, JPG, JPS, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WEBP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: 2.3.0
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: 9.50

### wp-server ###

server_architecture: Linux 5.10.76-linuxkit x86_64
httpd_software: nginx/1.21.4
php_version: 7.4.25 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 30
memory_limit: 128M
admin_memory_limit: 256M
max_input_time: 60
upload_max_filesize: undefined
php_post_max_size: undefined
curl_version: 7.68.0 OpenSSL/1.1.1f
suhosin: false
imagick_availability: true
pretty_permalinks: true

### wp-database ###

extension: mysqli
server_version: 10.3.32-MariaDB-1:10.3.32+maria~focal
client_version: mysqlnd 7.4.25
max_allowed_packet: 16777216
max_connections: 100

### wp-constants ###

WP_HOME: https://60e8-213-94-23-19.ngrok.io
WP_SITEURL: https://60e8-213-94-23-19.ngrok.io
WP_CONTENT_DIR: /var/www/html/wp-content
WP_PLUGIN_DIR: /var/www/html/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: true
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: true
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### wp_mail_smtp ###

version: 3.2.1
license_key_type: lite
debug: Email Source: WooCommerce
Mailer: Mailgun
Domain sandboxdd5376d89f7243ea93ad5548e8535a85.mailgun.org is not allowed to send: Sandbox subdomains are for test purposes only. Please add your own domain or add the address to authorized recipients in Account Settings.; Email Source: WP Core
Mailer: Mailgun
Domain sandboxdd5376d89f7243ea93ad5548e8535a85.mailgun.org is not allowed to send: Sandbox subdomains are for test purposes only. Please add your own domain or add the address to authorized recipients in Account Settings.
db_tables: wp_wpmailsmtp_tasks_meta, wp_wpmailsmtp_debug_events
lite_install_date: Dec 30, 2021 @ 9:35am

<details>

**Comment by Aljullu** [comment]
Thanks for opening this issue @puntope!

@tjcafferkey is that the same as what was fixed in #5519?

**Comment by tjcafferkey** [comment]
>@tjcafferkey is that the same as what was fixed in #5519?

Yep, I've tested this as well just now and it does indeed fix the bug observed in the issue. It's worth noting also that:

* In the latest version of WooCommerce Blocks this has been fixed
* There's a WooCommerce 6.1.1 point release scheduled which fixes this in Core
* This will also be fixed in the latest WooCommerce 6.2.

If you have _already_ customised a WooCommerce Blocks Template before receiving this fix, I believe you may still experience this bug until you clear the customizations, redo them, and resave that specific block template.

Based on this, I will close this issue but feel free to reopen if any of the above is inaccurate/incorrect and I'll look into this further.
