### ISSUE TITLE
Autofill checkout address not working

### ISSUE THREAD

**Issue by msroky** [woocommerce/woocommerce-gutenberg-products-block#5547]
Hello,
I've tried using a few plugins to automatically fill in the address field to improve the user experience on checkout page, but none of the plugins I've used appear to be compatible with your plugin.

When I turn off WC Gutenberg Block Checkout, and use the plain form of woocommerce, then it works without a problem.

This is one of the plugins I used https://wordpress.org/plugins/checkout-address-autofill-for-woocommerce/

I didn't notice any error in the console. I hope you find a solution to this and fix.

**Comment by opr** [comment]
Hi there @msroky I've just tried to reproduce this and it looks like it only works in the premium/pro version of the plugin you linked, is that what you're using?

If so, then I'd recommend reaching out to the developers of that plugin to see what isn't working, and if they find a bug with our extensibility points we can address it further.

Thanks!

**Comment by msroky** [comment]
I noticed this error in the console when I start typing the address and when the  google map starts
![54](https://user-images.githubusercontent.com/12650820/149790733-8b501139-1b22-4818-96cc-7e73c0051cdb.PNG)

This does not happen when I turn off your plugin and use the regular checkout form
