### ISSUE TITLE
Create dynamic My Account link block

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#5561]
This is just a very limited description for now to document the idea and potential block.

This would be a block that would be available within the WordPress navigation block that dynamically shows different text (potentially icons) depending on the status of the site visitor. If the site visitor is not logged in, the block would show something like "Log in". If the site visitor is logged in, the block would show something like "My Account".

**Note:** Currently the navigation block doesn't allow for custom blocks.

Internal reference: p9Jlb4-3B8-p2

**Comment by iamtakashi** [comment]
Do we have a different solution that's being worked on? Otherwise, I think it's still relevant as it is a common behaviour that we see in store sites.

**Comment by nerrad** [comment]
Oops this must have got closed unnoticed by the stale bot. It's still definitely on the roadmap.
