### ISSUE TITLE
Update folder names and folder structure

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#5588]
Currently, not all component folders reflect the name of the component they contain. This issue aims start a discussion to rename the component folders, so that it’s clear which folder contains which component.

| Component name               | Current folder name         | Ideal folder name            | Status |
| ---------------------------- | --------------------------- | ---------------------------- | ------ |
| Active Product Filters       | active-filters              | active-product-filters       | ❌     |
| All Products                 | products/all-products       | all-products                 | ❌     |
| All Reviews                  | reviews/all-reviews         | all-reviews                  | ❌     |
| Best Selling Products        | product-best-sellers        | best-selling-products        | ❌     |
| Checkout                     | cart-checkout/checkout      | checkout                     | ❌     |
| Cart                         | cart-checkout/cart          | cart                         | ❌     |
| Featured Category            | featured-category           | featured-category            | ✅     |
| Featured Product             | featured-product            | featured-product             | ✅     |
| Filter Products by Attribute | attribute-filter            | filter-products-by-attribute | ❌     |
| Filter Products by Price     | price-filter                | filter-products-by-price     | ❌     |
| Filter Products by Stock     | stock-filter                | filter-products-by-stock     | ❌     |
| Hand-picked Products         | handpicked-products         | handpicked-products          | ✅     |
| Mini Cart                    | cart-checkout/mini-cart     | mini-cart                    | ❌     |
| Newest Products              | product-new                 | newest-products              | ❌     |
| On Sale Products             | product-on-sale             | on-sale-products             | ❌     |
| Product Categories List      | product-categories          | product-categories-list      | ❌     |
| Product Search               | product-search              | product-search               | ✅     |
| Products by Attribute        | products-by-attribute       | products-by-attribute        | ✅     |
| Products by Category         | product-category            | product-by-category          | ❌     |
| Products by Tag              | product-tag                 | product-by-tag               | ❌     |
| Reviews by Category          | reviews/reviews-by-category | reviews-by-category          | ❌     |
| Reviews by Product           | reviews/reviews-by-product  | reviews-by-product           | ❌     |
| Single Product               | single-product              | single-product               | ✅     |
| Top Rated Products           | product-top-rated           | top-rated-products           | ❌     |

The table above shows that some components are bundled within a parent folder.

For example, the cart and checkout components are hosted in a parent folder:

- cart-checkout

  - cart
  - checkout
  - mini-cart
  - mini-cart-contents
  - payment-methods
  - shared

Another example are the review components, which are also bundled in a parent folder:

- reviews
  - all-reviews
  - reviews-by-category
  - reviews-by-product

  I do see why we bundle some components in a parent folder. However, we're doing this not consistent. If we bundle all review-related components, why don't we bundle the filter-related or the product-related components as well?

## Potential changes

I see two ways of making the component folders more consistent:

1. Using a flat folder structure
2. Using a deep folder structure

### Flat folder structure

When using a flat folder structure, all component folders are directly hosted within `assets/js/blocks`. This increases the finally of the components, but we might also have to move shared functionality to a different place, e.g. `assets/js/blocks/cart-checkout/shared` would be moved to `assets/js/shared/cart-checkout`. A flat folder structure could look like this:

```
.
└── assets/
    └── js/
        ├── active-product-filters
        ├── all-products
        ├── all-reviews
        ├── best-selling-products
        ├── cart
        ├── checkout
        ├── featured-category
        ├── featured-product
        ├── filter-products-by-attribute
        ├── filter-products-by-price
        ├── filter-products-by-stock
        ├── handpicked-products
        ├── mini-cart
        ├── newest-products
        ├── on-sale-products
        ├── product-categories-list
        ├── product-search
        ├── products-by-attribute
        ├── product-by-category
        ├── product-by-tag
        ├── reviews-by-category
        ├── reviews-by-product
        ├── single-product
        └── top-rated-products
```

### Deep folder structure

When using a deep folder structure, components are bundled based on their scope. The advantage of having a deep folder structure is that all related files are bundled, which increases the visibility of the functionality shared by the corresponding components. A deep folder structure could look like this:

```
.
└── assets/
    └── js/
        ├── cart-checkout/
        │   ├── cart
        │   ├── checkout
        │   └── mini-cart
        ├── filter/
        │   ├── active-product-filters
        │   ├── filter-products-by-attribute
        │   ├── filter-products-by-price
        │   └── filter-products-by-stock
        ├── featured/
        │   ├── featured-category
        │   └── featured-product
        ├── products/
        │   ├── all-products
        │   ├── best-selling-products
        │   ├── handpicked-products
        │   ├── newest-products
        │   ├── on-sale-products
        │   ├── product-categories-list
        │   ├── product-search
        │   ├── products-by-attribute
        │   ├── product-by-category
        │   ├── product-by-tag
        │   ├── single-product
        │   └── top-rated-products
        └── reviews/
            ├── all-reviews
            ├── reviews-by-category
            └── reviews-by-product
```

## Proposal

I propose both renaming the folder names to reflect the names of the component they host as well as updating the folder structure either a flat or a deep structure. Personally, I think that a deep folder structure makes more sense in this case. That said, I'm keen to hear your thoughts on this proposal.

**Comment by AbdirahimAhmedNor** [comment]
would mine if do that for you??
