### ISSUE TITLE
When only a single express payment method is present in checkout, it should expand to fill the entire container

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/woocommerce-gutenberg-products-block#5593]
As noted in the title, when only a single express checkout is present in the checkout, it should expand to fill the entire row:

Current behavior:

<img width="1760" alt="Screen Shot 2022-01-18 at 6 42 40 PM" src="https://user-images.githubusercontent.com/4500952/150053999-cd8855cf-ac14-4d04-a34a-450ef60e34cf.png">

Expected behavior:

<img width="1758" alt="Screen Shot 2022-01-18 at 6 45 48 PM" src="https://user-images.githubusercontent.com/4500952/150054187-c2f435d9-37d0-41e0-8f14-87d90f04c345.png">

**Comment by nielslange** [comment]
Hello @LevinMedia 👋

Thanks for reporting this. I just went ahead and created a fix for this problem in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5601. I cannot give you an estimate when or if we merge this change, though.
