### ISSUE TITLE
Store API: /products?include calls don't work for variations

### ISSUE THREAD

**Issue by ralucaStan** [woocommerce/woocommerce-gutenberg-products-block#5609]
## Describe the bug
When requesting a product from the API (/wp-json/wc/store/products?include=x), if the product is a variation the response from the API is an empty array.

## To reproduce

1. Go to your products, search for a variable product, open it and see the Variations tab
2. Copy the id of one variation
3. Go to a tool like Postman and make a request for your store with `/wp-json/wc/store/products?include=YOUR_ID`
4. Notice in the response is an empty array.

## Expected behavior
The response should have data about the product, similar to requesting to the data when requestion the individual product with `/wp-json/wc/store/products/YOUR_ID`

**Comment by ralucaStan** [comment]
Closing this as it is aligned with the WC REST API behaviour

**Comment by TatjanaDjurdjevic** [comment]
Does the same works for  wc/store/products?parent=x ?
When trying to fetch only variations of the one products, /products?parent=x return empty array.

Steps to reproduce the behavior:

Go to your products, search for a variable product, open it and see the Variations tab
Copy the id of one of that parent product (that has variations)
Go to a tool like Postman and make a request for your store with /wp-json/wc/store/products?parent=YOUR_ID
Notice in the response is an empty array.

**Comment by TatjanaDjurdjevic** [comment]
After half day of research, if you include type=variation in the query the result is not empty array... 
(eg. products?type=variation&parent=YOUR_ID)  
I think this behaviour should be noted somewhere in documentation.

Also if you put type=variation, the above mentioned call works (include for variations). 

Steps to reproduce: 
Go to your products, search for a variable product, open it and see the Variations tab
Copy the id of one variation
Go to a tool like Postman and make a request for your store with /wp-json/wc/store/products?type=variation&include=YOUR_ID
The response is now the product with selected id.

Please update the documentation.

**Comment by ralucaStan** [comment]
Thank you @TatjanaDjurdjevic for documenting your findings. We will soon update the documentation.
