### ISSUE TITLE
Payment options are not displayed at the checkout

### ISSUE THREAD

**Issue by jwalli** [woocommerce/woocommerce-gutenberg-products-block#5620]
Hello,

I have included Stripe and Paypal as payment options.

Now at the checkout only the possibility to pay via credit card is displayed.

The other payment options are listed in the right border, but they are not offered at the checkout.

They are available at the normal Woocommerce checkout.

What can I do so that the different payment methods can be selected by the customer?

Many greetings,

Jörg

![Screenshot 2022-01-24 140442](https://user-images.githubusercontent.com/16581401/150787956-0345a732-31bc-4938-abc9-a43943fc3cec.png)
![Screenshot 2022-01-24 140419](https://user-images.githubusercontent.com/16581401/150787969-92f5b397-054d-4043-a373-49c49b5be95b.png)

**Comment by tarhi-saad** [comment]
Hi there @jwalli 👋

Thanks for taking the time to make us aware that Stripe and Paypal aren’t working with the Checkout and Cart blocks. These blocks are still in early access (via the feature plugin) and it’s expected that some existing Woo Extensions that integrate with the current checkout flow in WooCommerce core will not work with the blocks.

Currently, it’s up to payment method extension developers to add support for the new checkout flow offered via the cart and checkout blocks. We have some [documentation on that here](https://href.li/?https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/extensibility/payment-method-integration.md) and you can also point them to this [post](https://href.li/?https://developer.woocommerce.com/2021/03/15/integrating-your-payment-method-with-cart-and-checkout-blocks/).

Your best course of action right now if you are using a payment method that isn’t working with the blocks is to notify the developer of the extension and ask if they can add support.

Until then you can keep on top of the [status of the Cart & Checkout Blocks in this documentation](https://href.li/?https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/).
