### ISSUE TITLE
Add filter to customize product grid block output

### ISSUE THREAD

**Issue by wesleylancel** [woocommerce/woocommerce-gutenberg-products-block#5632]
## Is your feature request related to a problem? Please describe.
I'd like to customize the output for all blocks that output a grid of product.

## Describe the solution you'd like
Add a filter here: https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/src/BlockTypes/AbstractProductGrid.php#L118 that is called with the entire list of products, in addition to the one being called per product here https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/src/BlockTypes/AbstractProductGrid.php#L118.

## Describe alternatives you've considered
Unsure of any alternatives.

**Comment by gigitux** [comment]
Hi wesleylancel,
thanks for opening this issue.
Let me check if I understand, are you suggesting creating a custom hook that allows you to manipulate [this array](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/src/BlockTypes/AbstractProductGrid.php#L78)? 
While we appreciate you sharing your idea with us, it doesn't fit in with our current priorities for the project. With Gutenberg, extensibility is done in other ways (inner blocks, variations, global styles, etc.): adding PHP filtering is powerful but has some drawbacks like being very brittle, making it easier to break in future updates or when two plugins conflict, etc. so we are trying to move away from that approach.

Our plan is to allow displaying product grids with the usage of Gutenberg's `Query Loop` block, so in the future, it will be easier to customize them.

**Comment by wesleylancel** [comment]
@gigitux I don't want to change that array, just the output of the entire block, including the HTML that is around the products (defined here: https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/src/BlockTypes/AbstractProductGrid.php#L119) and the way the products individually are rendered. Is there an alternative way of doing that without having to recreate the block (data-wise it'd be identical, only want to changed rendered HTML)?

**Comment by gigitux** [comment]
At this moment, unfortunately, is not possible. We are aware of this lack and we plan to add more customizability to Product Grid blocks. All the future customizations will be done with block variations, inner blocks, global styles instead to use PHP filtering.

What is your use case and what would you like change?

**Comment by wesleylancel** [comment]
@gigitux Use case for me is being able to completely change the outputted HTML based on the array with products data. Changing the wrapper around is the thing that isn't possible now. I already have a shortcode that renders products the way I want, for me it'd be easy to just be able to pass the array of products returned by the block after taking all its settings into account to my PHP code behind the shortcode.

**Comment by Aljullu** [comment]
Hi there @wesleylancel, thanks for sharing your use case. We are aware that some of our blocks still have limited customizability, we know that's something that could be improved, but at the same time we want to do it right and in a future-proof way.

As @gigitux said, some of the product grid blocks might be refactored underneath to use the Query Loop block from Gutenberg, that will allow new ways of extensibility (inner blocks, variations, global styles, creating patterns...). Once that happens you will be able to completely change the markup used to display each product, for example, creating a Query Loop inner block to display products in the way you want. In fact, you should already be able to do so, even though the Query Loop block from Gutenberg still has some filtering limitations.

In the meanwhile, our recommended approach for people who want a high level of customizability is to use the shortcodes.
