### ISSUE TITLE
Cart/Mini Cart buttons missing hover and focus styles

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#5647]
### Cart block
1. Install the theme [Twenty Twenty Two](https://wordpress.org/themes/twentytwentytwo/) (you might need to update to WP 5.9 or install Gutenberg to get it working).
2. Go to the Cart page with the Cart block.
3. Hover/focus the _Proceed to Checkout_ button and notice there is no hover/focus style.

https://user-images.githubusercontent.com/3616980/151334365-69312873-5079-451c-839c-92461de4701f.mp4

### Mini Cart block
1. Install the theme Twenty Twenty Two (you might need to update to WP 5.9 or install Gutenberg to get it working).
2. Go to Apperance > Editor and add the Mini Cart block to the header.
3. Go to the frontend and open the Mini Cart.
4. Notice the View my cart and Checkout blocks don't have hover/focus styles.

https://user-images.githubusercontent.com/3616980/151334446-97059859-d5ba-46e5-848a-dab0fe69b5b6.mp4

## Expected behavior
All buttons should have hover/focus styles.

**Comment by tarhi-saad** [comment]
Hi @Aljullu! Thank you for reporting this issue!

Indeed when following the steps provided above, we can see that the hover and focus styles are missing from the Cart & mini cart buttons. But, I think this isn't specific to the Twenty Twenty Two theme. I've tested the following themes:

- Twenty Twenty One
- Twenty Twenty
- Twenty Nineteen
- Blockbase (a non-core theme)

Each one of the above themes has the same styling issues. And the only one that has the correct style is the Storefront theme.

Could you share with me the themes you've tested where the focus & hover styles were showing correctly?

**Comment by Aljullu** [comment]
> Could you share with me the themes you've tested where the focus & hover styles were showing correctly?

You're probably right. I only tested Storefront and Twenty Twenty Two. Hover/focus styles were present in Storefront, but they weren't in Twenty Twenty Two. I didn't test any other themes, so the problem might be broader than what the issue describes, sorry for the confusion!
