### ISSUE TITLE
WooCommerce Store Editing Templates v3

### ISSUE THREAD

**Issue by tjcafferkey** [woocommerce/woocommerce-gutenberg-products-block#5650]
## Project summary

This is a continuation of the Store Editing Templates project. We will mainly be focusing in the following areas which will compliment the work we've achieved in V1 and V2.

* **Documentation** - Technical documentation to support developers who are looking to understand and contribute to WooCommerce Store Editing Templates.
* **Testing** - We are looking to support any future changes by having a suite of automated tests which will provide a level of safety to future development of the feature.
* **Refactoring** - A lot has changed since we started this project. There has been new versions of WooCommerce and WordPress, on top of this we have a better understanding of how this feature fits into existing WordPress FSE functionality. Let's see if we can refactor any of the code to make it more approachable, simple and robust.
* **Bugs** - As this feature gets adopted more and more by WooCommerce users we will leave room for any incoming issues that need our immediate attention.

The focus should ideally be on documentation and automated testing. This way fixing bugs and doing any refactors will be supported by this.

**Comment by sunyatasattva** [comment]
Thank you @tjcafferkey for creating nice and clear test specs!
