### ISSUE TITLE
Store Editing Templates: Add E2E tests for Single Product block template

### ISSUE THREAD

**Issue by tjcafferkey** [woocommerce/woocommerce-gutenberg-products-block#5656]
**Scenario to cover:**

* Should a user navigate to Site Editor > All Templates with an FSE theme active they should see the WooCommerce provided Single Product block template.
* Should a user load the Single Product  template, the editor will have the “WooCommerce Single Product Block” Legacy Template block present.
* Should a user load the product page it will render product details and allow the user to add the product to their basket.
* Should a user customise the Single Product template and save it. The user should see a "Clear customizations" option on the All Templates view (clearing customisations functionality should be covered by Gutenberg)
* Should a user load  the customised Single Product template the Site Editor should render these customisations
* Should a user have a customised Single Product template, these customisations would be present on the frontend.

**Comment by sunyatasattva** [comment]
> Should a user load the product page it will render product details and allow the user to add the product to their basket.

@tjcafferkey Should this be covered by these tests? What kind of things should we check here as “product details”? It should have a picture, a description, adding to basket… should it have reviews and related products? Perhaps we can make a more specific list for this one spec.

**Comment by tjcafferkey** [comment]
>Should this be covered by these tests?

I put this scenario in here because we actually encountered this problem during the Store Editing Templates project, you can see the issue raised for that here https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5328 and the subsequent fix here https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5346 for it.

Because [our templating code](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/src/BlockTypes/LegacyTemplate.php) is separate from the one that comes with WooCommerce Core it's hard to reliably depend on tests in Core covering us for this functionality.

All that said I am interested to hear your thoughts on that though.

>What kind of things should we check here as “product details”? It should have a picture, a description, adding to basket… should it have reviews and related products? Perhaps we can make a more specific list for this one spec.

Yes totally, I'm happy to be guided by your judgement on this please feel free to amend this aspect of the spec how you see fit 🙂
