### ISSUE TITLE
Store Editing Templates: Add E2E tests for Product Archive block template

### ISSUE THREAD

**Issue by tjcafferkey** [woocommerce/woocommerce-gutenberg-products-block#5657]
**Scenario to cover:**

* Should a user navigate to Site Editor > All Templates with an FSE theme active they should see the WooCommerce provided Product Archive block template.
* Should a user load the Product Archive template, the editor will have the “WooCommerce Product Grid Block” Legacy Template block present.
* Should a user load the Shop page on the frontend, it will render a list of products.
* Should a user customise the Product Archive template and save it. The user should see a "Clear customizations" option on the All Templates view (clearing customisations functionality should be covered by Gutenberg)
* Should a user load the customised Product Archive template the Site Editor should render these customisations
* Should a user have a customised Product Archive template, these customisations would be present on the frontend.

**Comment by sunyatasattva** [comment]
> Should a user customise the Product Archive template and save it. The user should see a "Clear customizations" option on the All Templates view

Is it really worth to check this step for all the templates? Is it something that can break per-template basis? It sounds to me we can cover this only once, but maybe I'm missing some scenarios in which one can work and one can break?

> Should a user load the customised Product Archive template the Site Editor should render these customisations

☝️  I can see how this does need to be tested every template, for example.

**Comment by tjcafferkey** [comment]
>Is it really worth to check this step for all the templates? Is it something that can break per-template basis? It sounds to me we can cover this only once, but maybe I'm missing some scenarios in which one can work and one can break?

I think given that this functionality is part of the critical journey for merchants and their users it's definitely worth testing, even though we may think "if it breaks for one template it will break for all", I'm not so sure we can and always will be able to rely on this as the codebase evolves. On top of this each rendering of the template is handled individually [here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/src/BlockTemplatesController.php#L411).

Personally I think covering each template is worth the trade off that comes with it, what do you think? Perhaps we can split the tests at some point in the future, so we have a streamlined set of tests for PRs and a full suite for releases?

Interested to hear your thoughts on that.

**Comment by sunyatasattva** [comment]
Thanks for the comment. I'll guess I'll have more thoughts as I implement those. I'll start by doing them, it's probably not a very big effort to reuse the tests. We can remove/refactor them once we have a more complete picture.
