### ISSUE TITLE
Store Editing Templates: Add E2E tests for Product Category block template

### ISSUE THREAD

**Issue by tjcafferkey** [woocommerce/woocommerce-gutenberg-products-block#5658]
**Scenario to cover:**

* Should a user navigate to Site Editor > All Templates with an FSE theme active they should see the WooCommerce provided Product Category block template.
* Should a user load the Product Category template, the editor will have the “WooCommerce Product Grid Block” Legacy Template block present.
* Should a user load a product category page on the frontend, it will render a list of products.
* Should a user customise the Product Category template and save it. The user should see a "Clear customizations" option on the All Templates view (clearing customisations functionality should be covered by Gutenberg)
* Should a user load the customised Product Category template the Site Editor should render these customisations
* Should a user have a customised Product Category template, these customisations would be present on the frontend.

**Comment by sunyatasattva** [comment]
This was closed by https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5820 there was a mistake in the PR description.
