### ISSUE TITLE
Product Title: Add support for spacing with Global Styles API

### ISSUE THREAD

**Issue by gigitux** [woocommerce/woocommerce-gutenberg-products-block#5667]
The `Product Title` block should have support for spacings with Global Styles API

**Comment by Aljullu** [comment]
Just tested it and it looks like Product Title already has margin styles.

![imatge](https://user-images.githubusercontent.com/3616980/154507875-5564d9ef-8b7b-4906-9de4-5cb9c0cebfbd.png)
