### ISSUE TITLE
Product Price: Improve Global Styles API integration 

### ISSUE THREAD

**Issue by gigitux** [woocommerce/woocommerce-gutenberg-products-block#5672]
The `Product Price` block, with the Global Styles API, should support:

- font-style
- font-size
- font-weight 
- specific text color for sale price -> it impossible to implement with the current Global Styles API
- specific text color for regular price ->  it impossible to implement with the current Global Styles API

**Comment by tomasztunik** [comment]
It is not possible now to introduce Global Styles for multi-state or multi-property/element complex blocks. If we introduce Global Styles in Product Price component we'll make it less customisable than it was before so from user's perspective this is going to be a regression.

- Any custom changes to sale, baseline and standard price would need to happen via CSS.

Great discussion regarding this including follow up links one can find there can be found here https://github.com/WordPress/gutenberg/issues/33255

Possible alternative to explore is to break down Product Price block into 3 separate blocks that would render each value as individual block. Issue with this is if we used this in Products listings, Product item views etc. 

We could introduce variants (maybe?!) of the Product Price block by style (small, medium, big) or by function (list, item, cart)? and for each context use matching variant. Issue with this approach is it introduces a lot of granularity and adds a lot of noise by adding blocks that make sense only in the context of their host feature block.

Questions I have are. 
1. Do we want to introduce Global Styles at the cost of existing features and customisability?
2. Do we want to introduce block granularity to get around Global Style limitations?
