### ISSUE TITLE
Featured Product/Category: some button styles don't get applied

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#5676]
Width settings and font size styles don't take effect in the Featured Product/Category inner button.

## To reproduce

1. Add a Featured Product or Featured Category block to a post or page.
2. Click on the inner button.
3. Try changing its Width settings and Typography size.
4. Notice nothing changes. This also affects the frontend.

## Expected behavior
The user should be able to change the width and font size of the button.

## Screenshots

https://user-images.githubusercontent.com/3616980/151771093-c2785b3d-7879-490a-81c9-b211e712e459.mp4

**Comment by Aljullu** [comment]
@gigitux do you think we should add this to the Global styles epic?

**Comment by gigitux** [comment]
@Aljullu Thanks for bringing up this! I added this issue to #5665 epic 👍
