### ISSUE TITLE
Copy the `block.json` files from `assets` to `build` dynamically in Webpack config

### ISSUE THREAD

**Issue by opr** [woocommerce/woocommerce-gutenberg-products-block#5693]
Currently, introduced in #5692 we copy `assets/js/blocks/checkout/block.json` to `build/checkout/block.json` manually in the webpack config.

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/bin/webpack-configs.js#L257-L265

We should make this dynamic so we don't have to hard code these values.

**Comment by alexflorisca** [comment]
This has been fixed by #5692
