### ISSUE TITLE
Ability to hook into adding custom fields to checkout

### ISSUE THREAD

**Issue by nickfmc** [woocommerce/woocommerce-gutenberg-products-block#5694]
We really need a way to add custom fields to the checkout block. I think this is one big thing holding it back

**Comment by alexflorisca** [comment]
Hi @nickfmc, thanks for raising the issue. You can currently add custom fields to the checkout by adding a new inner block to the address area, and render an input inside of it. We do something similar in [this test plugin](https://github.com/woocommerce/newsletter-test) to render a checkout box for subscribing to a newsletter. You can follow the same format to add custom fields elsewhere on the Checkout block.
