### ISSUE TITLE
Ensure consistent spacing for checkout input fields

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#5699]
## Describe the bug

In #5633, we adjusted the spacing of the `Create an account?` checkbox below the email address input field. While testing the release, I noticed that this fix caused a regression bug. When displaying the `Create an account?` checkbox, the email address input field gets pushed down. This problem is caused by:

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/360827baff0b00d6852882225ecfc8d5b071c75a/assets/js/base/components/text-input/style.scss#L113-L115

Once the `Create an account?` checkbox is visible, the email address input field is no longer the only child and instead of `margin-top: 0` this element is using `margin-top: 1.5em`. 

## To reproduce

1. Go to `WP Admin » WooCommerce » Settings » Account & Privacy`.
2. Activate the option ` Allow customers to create an account during checkout` in the section `Account creation`.
2. Create a test page and add the checkout block to it.
3. Click on the email address input field.
4. Activate the option `Allow shoppers to sign up for a user account during checkout` in the section `Account options` in the sidebar.
5. See that the email address input field gets pushed down as soon as the `Create an account?` checkbox becomes visible.

## Screen recording

![Screen Capture on 2022-02-02 at 14-07-43](https://user-images.githubusercontent.com/3323310/152109415-7dece974-5c66-4aac-8995-a1607a799e2d.gif)

## Expected behavior

When adding the `Create an account?` checkbox, the spacing of the email address input field should remain untouched.

**Comment by tarunvijwani** [comment]
I'd like to work on this.
