### ISSUE TITLE
phone field and bulding / apartment can no longer be deactivated

### ISSUE THREAD

**Issue by DarianDev** [woocommerce/woocommerce-gutenberg-products-block#5723]
i am using the latest version of the plugin with wordpress 5.9 and have disabled the phone field in the editor, but it is still shown as an optional item also building and apartment in the editor the fields are hidden, but on the page they are displayed live

**Comment by senadir** [comment]
@opr this might be related to the `block.json` shift, can you confirm if attributes persist or not?

**Comment by opr** [comment]
@senadir looks like the behaviour is inverted, if they are hidden in editor they show up on the front-end, if they are shown in the editor they are hidden on the front-end. I'll look into why this is happening now.
