### ISSUE TITLE
Mini Cart block and `shop` endpoint: data is not updated when adding the first product to the cart

### ISSUE THREAD

**Issue by gigitux** [woocommerce/woocommerce-gutenberg-products-block#5729]
## Describe the bug
If the user adds a product from ´/shop´ endpoint, the mini cart will not update. 
Similiar issue #5266 

## To reproduce

(with classic theme)
1. Active `Storefront` theme and add the Mini Cart Block as a widget.
2. Go on `/shop` page and add a product.
3. Check that the cart (`/cart/`), while the Mini Cart block is not updated.

(with block theme)
1. Active `TT1` theme and add the Mini Cart Block in the footer.
2. Go on `/shop` page and add a product.
3. Check that the cart (`/cart/`), while the Mini Cart block is not updated.

## Expected behavior
The Mini Cart should be updated.

## Screenshots

https://user-images.githubusercontent.com/4463174/152780949-a87ddade-4834-400c-b71f-6fd9d4384e8e.mp4

### WordPress (please complete the following information):
* Core version: 5.9

**Comment by dinhtungdu** [comment]
@gigitux I can't reproduce the issue with the Storefront theme. I'm using WP 5.9, WC 6.3.0-dev, WC Block lastest `trunk` with Gutenberg deactivated. I also can't reproduce with block themes as well, I used Twenty Twenty Two in my test. Can you share your configuration?

**Comment by gigitux** [comment]
@dinhtungdu I'm able to reproduce with: WC Blocks latest trunk with GB disabled, WordPress 5.9 and WooCommerce 6.2, and Storefront theme.

Are you adding the product from `/shop` page?

**Comment by dinhtungdu** [comment]
> Are you adding the product from `/shop` page?

@gigitux Yeah, I added product from the `/shop` page. I also changed WC to 6.2

https://user-images.githubusercontent.com/5423135/153167044-c56f7405-9445-442c-8c2c-b746eaa2554e.mov

**Comment by dinhtungdu** [comment]
I can reproduce the issue on a new installation.
