### ISSUE TITLE
Phone field is missing

### ISSUE THREAD

**Issue by s0len** [woocommerce/woocommerce-gutenberg-products-block#5738]
## Describe the bug
Missing Phone field in checkout. Also not able to remove Appartment field.

I've tried Storefront theme and disable all plugins except for woocommerce and woocommerce blocks. No change.

## To reproduce
Just go to checkout and try finding phone field. https://papmau.se/1644518948813/?page_id=55

## Expected behavior
Should see a phone field.

## Screenshots
![2022-02-07 (1)](https://user-images.githubusercontent.com/35483234/152859084-1a2073c3-1dcc-4a23-9591-330583bfee4a.png)

## Environment

<details>
  <summary>Details</summary>

```
### WordPress (please complete the following information):

### wp-core ###

version: 5.9
site_language: sv_SE
user_language: sv_SE
timezone: +01:00
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 79
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/papmause/public_html
wordpress_size: 429,43 MB (450290671 bytes)
uploads_path: /home/papmause/public_html/wp-content/uploads
uploads_size: 118,65 MB (124409085 bytes)
themes_path: /home/papmause/public_html/wp-content/themes
themes_size: 26,35 MB (27632077 bytes)
plugins_path: /home/papmause/public_html/wp-content/plugins
plugins_size: 144,95 MB (151991565 bytes)
database_size: 58,19 MB (61018889 bytes)
total_size: 777,57 MB (815342287 bytes)

### wp-active-theme ###

name: Flatsome Child (flatsome-child)
version: 3.0
author: UX Themes
author_website: (undefined)
parent_theme: Flatsome (flatsome)
theme_features: core-block-patterns, post-thumbnails, woocommerce, title-tag, automatic-feed-links, customize-selective-refresh-widgets, sensei, html5, menus, post-formats, wc-product-gallery-lightbox, widgets
theme_path: /home/papmause/public_html/wp-content/themes/flatsome-child
auto_update: Inaktiverat

### wp-parent-theme ###

name: Flatsome (flatsome)
version: 3.15.3
author: UX-Themes
author_website: http://www.uxthemes.com/
theme_path: /home/papmause/public_html/wp-content/themes/flatsome
auto_update: Inaktiverat

### wp-themes-inactive (3) ###

Digital Storefront: version: 0.2.5, author: TheMagnifico52, Automatiska uppdateringar inaktiverade
Storefront: version: 3.9.1, author: Automattic, Automatiska uppdateringar inaktiverade
Twenty Twenty-Two: version: 1.0, author: WordPress-teamet, Automatiska uppdateringar inaktiverade

### wp-mu-plugins (1) ###

WP STAGING Optimizer: version: 1.4.1, author: René Hermenau

### wp-plugins-active (17) ###

Advanced Dynamic Pricing for WooCommerce: version: 4.0.1, author: AlgolPlus, Automatiska uppdateringar aktiverade
Back In Stock Notifier for WooCommerce | WooCommerce Waitlist Pro: version: 2.6.1, author: codewoogeek, Automatiska uppdateringar aktiverade
Contact Form 7: version: 5.5.4, author: Takayuki Miyoshi, Automatiska uppdateringar aktiverade
Customer Reviews for WooCommerce: version: 4.36, author: CusRev, Automatiska uppdateringar aktiverade
Google Listings and Ads: version: 1.11.0, author: WooCommerce, Automatiska uppdateringar aktiverade
Jetpack: version: 10.6, author: Automattic, Automatiska uppdateringar aktiverade
Kadence WooCommerce Email Designer: version: 1.4.10, author: Kadence WP, Automatiska uppdateringar aktiverade
Loginizer: version: 1.7.0, author: Softaculous, Automatiska uppdateringar aktiverade
Product Enquiry for WooCommerce: version: 3.1.4, author: WisdmLabs, Automatiska uppdateringar inaktiverade
Product Feed PRO for WooCommerce: version: 11.2.5, author: AdTribes.io, Automatiska uppdateringar aktiverade
WooCommerce: version: 6.1.1, author: Automattic, Automatiska uppdateringar aktiverade
WooCommerce Blocks: version: 6.9.0, author: Automattic, Automatiska uppdateringar inaktiverade
WooCommerce Fortnox Hub: version: 5.3.0-beta.4, author: BjornTech, Automatiska uppdateringar inaktiverade
WooCommerce Google Analytics Integration: version: 1.5.8, author: WooCommerce, Automatiska uppdateringar aktiverade
WooCommerce Shipping & Tax: version: 1.25.22, author: WooCommerce, Automatiska uppdateringar aktiverade
WooCommerce Stripe Gateway: version: 6.1.0, author: WooCommerce, Automatiska uppdateringar inaktiverade
Woo Swish e-commerce: version: 3.4.2, author: BjornTech, Automatiska uppdateringar aktiverade

### wp-plugins-inactive (2) ###

Nets Easy for WooCommerce: version: 1.25.0, author: Krokedil (latest version: 1.25.1), Automatiska uppdateringar inaktiverade
WP STAGING: version: 2.9.3, author: WP-STAGING (latest version: 2.9.4), Automatiska uppdateringar inaktiverade

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1808
imagemagick_version: ImageMagick 7.1.0-2 Q16 x86_64 2021-06-25 https://imagemagick.org
imagick_version: 3.5.1
file_uploads: File uploads is turned off
post_max_size: 50M
upload_max_filesize: 50M
max_effective_size: 50 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 155 GB
	imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	imagick::RESOURCETYPE_FILE: 196608
	imagick::RESOURCETYPE_MAP: 155 GB
	imagick::RESOURCETYPE_MEMORY: 78 GB
	imagick::RESOURCETYPE_THREAD: 1
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, APNG, ART, ARW, ASHLAR, AVI, AVIF, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CR3, CRW, CUBE, CUR, CUT, DATA, DCM, DCR, DCRAW, DCX, DDS, DFONT, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FARBFELD, FAX, FF, FILE, FITS, FL32, FLV, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GV, HALD, HDR, HEIC, HEIF, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JBG, JBIG, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, K25, KDC, KERNEL, LABEL, M2V, M4V, MAC, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORA, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PHM, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, POCKETMOD, PPM, PS, PSB, PSD, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGB565, RGBA, RGBO, RGF, RLA, RLE, RMF, RSVG, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TILE, TIM, TM2, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WEBM, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YAML, YCbCr, YCbCrA, YUV
gd_version: 2.2.5
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: 9.27

### wp-server ###

server_architecture: Linux 4.18.0-305.19.1.lve.el8.x86_64 x86_64
httpd_software: LiteSpeed
php_version: 7.4.27 64bit
php_sapi: litespeed
max_input_variables: 3000
time_limit: 90
memory_limit: 512M
max_input_time: 90
upload_max_filesize: 50M
php_post_max_size: 50M
curl_version: 7.71.0 OpenSSL/1.1.1d
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 10.5.13-MariaDB-cll-lve
client_version: mysqlnd 7.4.27
max_allowed_packet: 268435456
max_connections: 800

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/papmause/public_html/wp-content
WP_PLUGIN_DIR: /home/papmause/public_html/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Odefinierat
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### jetpack ###

site_id: 189142647
ssl_cert: No
time_diff: -1
version_option: 10.6:1643743183
old_version: 10.5.1:1643056997
public: Public
master_user: woocommerce/woocommerce-blocks#12058 Solen
current_user: woocommerce/woocommerce-blocks#12058 Solen
tokens_set: Blog User
blog_token: 62ryw89gJkj50@fB@GWiYl(sFJQT(hjr
user_token: #T(pO2BjuFYGc0XBsZ0IdaOM!A)uFZT5
version: 10.6
jp_plugin_dir: /home/papmause/public_html/wp-content/plugins/jetpack/
plan: free
protect_header: {"trusted_header":"REMOTE_ADDR","segments":1,"reverse":false}
full_sync: {"started":"Tue, 09 Feb 2021 21:01:21 +0000","finished":"Tue, 09 Feb 2021 21:05:08 +0000","progress":{"options":{"finished":true},"functions":{"finished":true},"constants":{"finished":true},"users":{"total":"1","sent":1,"finished":true,"last_sent":"1"},"network_options":{"finished":true}},"config":{"options":true,"functions":true,"constants":true,"users":[1],"network_options":true}}
sync_size: undefined
sync_lag: 0 seconds
full_sync_size: undefined
full_sync_lag: 0 seconds
idc_urls: {"home":"https:\/\/papmau.se","siteurl":"https:\/\/papmau.se","WP_HOME":"","WP_SITEURL":""}
idc_error_option: false
idc_optin: true
cxn_tests: All Pass.
```

</details>
 
## Additional context
None

**Comment by nielslange** [comment]
Hello @s0len 👋

Thanks for your report and welcome to GitHub! You mentioned that you're not seeing the phone field and that the apartment field cannot be removed. These fields can be controlled via the block settings, as seen on the following screenshot:

![#5738](https://user-images.githubusercontent.com/3323310/152987928-eca49641-a55c-4337-973f-7da26d8e912e.png)

Is it possible, that you somehow missed these settings? I'm looking forward to hearing from you. 😀

**Comment by s0len** [comment]
> Hello @s0len 👋
> 
> Thanks for your report and welcome to GitHub! You mentioned that you're not seeing the phone field and that the apartment field cannot be removed. These fields can be controlled via the block settings, as seen on the following screenshot:
> 
> ![#5738](https://user-images.githubusercontent.com/3323310/152987928-eca49641-a55c-4337-973f-7da26d8e912e.png)
> 
> Is it possible, that you somehow missed these settings? I'm looking forward to hearing from you. 😀

Hi @nielslange 

No unfortunately no that's not the case. As I explained, it's also not possible to remove the apartment field. So no matter the setting inside the block (which you've highlighted above) nothing changes.

When I inspect the cart using chromes inbuilt inspector there is no html tags referring to the form field which should contain the phone field.

EDIT: Note that the fields inside the block editor works as intended. Meaning the show/hide depending on the setting.

**Comment by nielslange** [comment]
I wonder if you're facing a plugin or theme conflict. I suggest that you run a conflict test, as explained on https://woocommerce.com/document/how-to-test-for-conflicts/, to see if this problem is caused by your theme or another plugin.

On my end, the visibility of the address fields can be toggled as expected.

## All address fields visible

<table>
<tr>
<td>Editor:
<br><br>

![5738-visible-editor](https://user-images.githubusercontent.com/3323310/153362291-301b59d7-880a-498d-874a-4c0bbb80d66e.png)
</td>
<td>Frontend:
<br><br>

![5738-visible-frontend](https://user-images.githubusercontent.com/3323310/153362281-2e9752f7-82ac-48a0-bbbf-9e71d6acd198.png)
</td>
</tr>
</table>

## All address fields hidden

<table>
<tr>
<td>Editor:
<br><br>

![5738-hidden-editor](https://user-images.githubusercontent.com/3323310/153362311-7762d463-4293-4fbc-8e56-3556684715ae.png)
</td>
<td>Frontend:
<br><br>

![5738-hidden-frontend](https://user-images.githubusercontent.com/3323310/153362302-198a0d90-d43d-4284-8e8b-e870c5d533be.png)
</td>
</tr>
</table>

**Comment by s0len** [comment]
So this time i made a staging site and on that I disabled all my plugins except woocommerce and woocommerce blocks. I've enabled the theme storefront. Still same issue.

Here's the URL to the staging site where the new cart is enabled.
https://papmau.se/1644518948813/?page_id=55

![2022-02-10 (1)](https://user-images.githubusercontent.com/35483234/153479179-6b6021da-0c22-476b-a6e9-508e50e4717a.png)
![2022-02-10 (2)](https://user-images.githubusercontent.com/35483234/153479186-3226775e-a794-4c99-b938-0ee79596c51c.png)
![2022-02-10](https://user-images.githubusercontent.com/35483234/153479188-81360293-41ea-4512-a1ef-2f6f7bfb5218.png)

**Comment by s0len** [comment]
Turns out that when I enable apartment and disable phone it will then show phone and hide apartment. weird bug this one for sure.. Any clue on what you might need to squash this one?

![2022-02-10 (3)](https://user-images.githubusercontent.com/35483234/153480176-fccbc453-5eba-4515-8919-b5d2df0be0ba.png)
![2022-02-10 (4)](https://user-images.githubusercontent.com/35483234/153480182-0e1f264e-dcb3-4410-bf5e-669f62c66aab.png)

**Comment by fevered** [comment]
I received a report of this issue in 4768704-zen and I was able to reproduce the issue on my test site. For reference, I have only WooCommerce Blocks (Version 6.9.0) and WooCommerce Core (Version 6.2.0) active and I am using the latest version of the Storefront theme. 

I was specifically looking into the phone number field not displaying. The following screenshot is the settings for my checkout block - the Phone field is both activated, and required: 

<img width="1341" alt="Screen Shot 2022-02-10 at 3 04 45 PM" src="https://user-images.githubusercontent.com/1293104/153479598-a4b09550-7dc4-4390-b7c7-625b6db1e237.png">

This is what I see in the checkout - there's no phone field: 

<img width="833" alt="Screen Shot 2022-02-10 at 3 04 26 PM" src="https://user-images.githubusercontent.com/1293104/153479657-5534c884-8dc6-4b9a-a422-d101a91b1165.png">

I did also test with the apartment field and noticed that with both fields, when I had them set as enabled they did not display - but when I disable them, they do display. Screenshots showing my settings and what I see in checkout with both options disabled (this also happens on an individual basis IE if I only have the Phone field disabled, only the phone field will display): 

Settings:
<img width="1236" alt="Screen Shot 2022-02-10 at 3 14 51 PM" src="https://user-images.githubusercontent.com/1293104/153480425-63f0ce55-c301-4efd-a0ff-9c404c12a551.png">

What I see in the checkout:
<img width="838" alt="Screen Shot 2022-02-10 at 3 17 02 PM" src="https://user-images.githubusercontent.com/1293104/153480578-210c9498-684f-48e9-8d97-a0e3bcfb5c12.png">

**Comment by thisissandip** [comment]
I tested this on my end and I came across the same issue as described by @fevered above.

If you enable the "Phone" or "Apartment" fields on the block - then they are NOT displayed on the frontend.

Block (Display the Apartment and Phone fields):

<img width="1310" alt="Markup 2022-02-16 at 14 13 21" src="https://user-images.githubusercontent.com/69596988/154227677-e7e6465d-0595-48a6-adaf-e02da1b8d60a.png">

Checkout (The fields are hidden):

<img width="1201" alt="Markup 2022-02-16 at 14 13 54" src="https://user-images.githubusercontent.com/69596988/154228871-95841f46-bee4-4adc-8d32-86a61aa7c1cf.png">


---

And, If you disable the "Phone" or "Apartment" fields on the block - then they ARE displayed on the frontend.

Block (Hide the Apartment and Phone fields):

<img width="1248" alt="Markup 2022-02-16 at 14 17 57" src="https://user-images.githubusercontent.com/69596988/154228446-3fcc1307-39ad-468a-8966-529ab8942cde.png">

Checkout (The fields are displayed even after they are set to be hidden) :

<img width="1173" alt="Markup 2022-02-16 at 14 18 26" src="https://user-images.githubusercontent.com/69596988/154228480-a0a9cc4b-0a70-44be-bc65-53bf6e390406.png">

Seems like the logic of hiding those fields on the frontend is broken.

Reported here: 4784049-zen

**Comment by tarunvijwani** [comment]
Thank you all for reporting this issue!
Unfortunately, I couldn't reproduce this on my end. @thisissandip and @fevered Could you please confirm whether this still exists?

https://user-images.githubusercontent.com/11503784/164389199-7afcccec-525b-43fa-86ca-ecbdacc9199d.mov

**Comment by fevered** [comment]
Hey @tarunvijwani - I just tested this with the latest version and I'm also not able to reproduce it.

**Comment by tarunvijwani** [comment]
This is a duplicate issue. We resolved this bug [here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5723).

If anyone still facing this problem, they'll need to update the plugin version to the latest version.
