### ISSUE TITLE
"Add Block" button overlaps content on the Checkout block in the editor

### ISSUE THREAD

**Issue by alexflorisca** [woocommerce/woocommerce-gutenberg-products-block#5742]
## Describe the bug
The "Add Block" button overlaps the other inner blocks on the checkout block (see screenshot)

## Screenshots
| Place Order | Totals |
| ------------ | ------ |
| ![Screenshot 2022-02-08 at 11 16 59](https://user-images.githubusercontent.com/3966773/152976612-e3895c81-7a56-4aca-8762-bd8660a64f6a.png) | ![Screenshot 2022-02-08 at 11 16 51](https://user-images.githubusercontent.com/3966773/152976700-e117efd1-b6c8-4292-bacd-976954e519a6.png) |

## To reproduce
Steps to reproduce the behaviour:

1. Open up a page with the Checkout block in the editor
2. Confirm that the "Place Order" button and the "Add Block" button at the bottom of the block overlap
3. Confirm that in the right hand side bar, the total price overlaps with the "Add block" button

## Expected behaviour
The "Add block" button should sit neatly underneath the "Place order" button. 

### WordPress (please complete the following information):
* Core version: 5.9
* Gutenberg version (if installed): 12.5.3
* WooCommerce version: 6.3.0-dev
* WooCommerce Blocks version:  7.0.0-dev

**Comment by ralucaStan** [comment]
I think this bug can be because of [this change](https://github.com/WordPress/gutenberg/pull/36605) in Gutenberg. It might be that we are not supposed to use the transparent button, but the solid black one. The transparent button is intended for empty groups.

**Comment by alexflorisca** [comment]
Let's change the button to use the black button and see if that fixes it first. It sounds like that's something that we need to do anyway, and if we still have an issue after we can go from there.
