### ISSUE TITLE
Find a way to keep the address up to date in CheckoutShippingAddress and CheckoutBillingAddress

### ISSUE THREAD

**Issue by opr** [woocommerce/woocommerce-gutenberg-products-block#5747]
Check out the `try/decouple-customer-data-context` branch and do the following:

1. Uncheck `Use same address for billing`.
2. Change postcode on either address.
3.  While the block is submitting the new data to the server, change the postcode again (you have to be quick!).
4. Observe the postcode change to the old one, then back to the new one.

The reason this is happening is the `wc/data/store` is the new source of truth for the address data. The data flow works like so:

1. User updates address in form, the `wc/store/cart` is updated to reflect the new address information.
2. If necessary, `UPDATE_CUSTOMER_DATA` is dispatched which sends the new address info to the server.
2a. Making further updates to the address form at this point causes step 2 to happen again.
3. When this completes, the new cart is returned by the server. We then dispatch `RECEIVE_CART` onto the store (remember, this contains the address data we sent along with `UPDATE_CUSTOMER_DATA`).
4. The `wc/store/cart` store is restored to the same data sent in step 2.

We need to find a way to allow the server to be updated, but prevent the returned value overwriting the data in the store if it is fresher.

**Comment by alexflorisca** [comment]
Can we disable the the form fields to stope the user from typing while data is being sent to the server?

**Comment by senadir** [comment]
I think disabling fields while typing would result in an extremely frustrating experience.

**Comment by alexflorisca** [comment]
Ah yeah I forgot we send to server while the user is typing (debounced), I thought it was only on loosing focus of the input.

**Comment by senadir** [comment]
Canceling in-flight requests is probably the solution we want to go with here.
