### ISSUE TITLE
Add filter to query args in AbstractProductGrid class

### ISSUE THREAD

**Issue by Rahmon** [woocommerce/woocommerce-gutenberg-products-block#5798]
## Is your feature request related to a problem? Please describe.
I can't change the query args used by the Products by Category block. Since the query is not the main query, I couldn't detect that the query is fired by a WC block in the action `pre_get_posts`.

## Describe the solution you'd like
I'd like to filter the query args used in the function [render](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/src/BlockTypes/AbstractProductGrid.php#L77) on AbstractProductGrid class. 

## Describe alternatives you've considered
Maybe there is another better place to put this filter like the [__construct method](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/c065387bb26c9c43824e1ee48bfc166cd2c758cd/src/Utils/BlocksWpQuery.php#L24) of BlocksWpQuery class.

## Additional context
I'm working in a scenario when I have a custom post type to show product variations and I need to add this extra post type to the query used by Products by Category block.

**Comment by tomasztunik** [comment]
👋 @Rahmon - give us some time to look into it. And in the meantime have you considered using tags to pick up the desired products with Products by Tag block? Or is it a more complex setup?

And just to clarify, do you still need to do a regular product listing or do you want to provide it with more data and alter how it's displayed?

**Comment by Rahmon** [comment]
:wave: @tomasztunik - Even using Products by Tag wouldn't work because I need to add an extra post type to the query (that by default uses only ['product'](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/c4a2a29643f9f4f2821e336665899a5d985ed978/src/BlockTypes/AbstractProductGrid.php#L191)). 

Yes. I need to do a regular product listing with more data ("products" with a custom post type). Let me know if you want to clarify something else :relaxed:

**Comment by alessandrotesoro** [comment]
I just encountered the same issue, there's no way to catch the query via `pre_get_posts` to insert custom logic. 

In my scenario I've built a custom search form but due to the way the blocks are built, I can't apply my filtering logic and inject the results into the query.

**Comment by frontdevde** [comment]
Letting you know that we discussed this with the team. We understand your request and acknowledge that the blocks currently don't offer a high enough level of customizability. As it pertains to the suggested solution though (i.e. adding a filter), we want to explore adding semantic extensibility. For some context see [this Gutenberg discussion here](https://github.com/WordPress/gutenberg/discussions/37448#discussioncomment-1949873). We don't have a timeline but this could potentially be addressed when/if we refactor those blocks using the Query Loop block.

With the above in mind, I will go ahead and close this issue. 
Rest assured that your feedback is not lost and has been received.
