### ISSUE TITLE
Store Editing Templates: Product Category doesn't load Product Archive as a fallback edgecase.

### ISSUE THREAD

**Issue by tjcafferkey** [woocommerce/woocommerce-gutenberg-products-block#5799]
## Describe the bug
There is a specific scenario where the Product Category does not load the Product Archive template as a fallback when it is eligible to do so.

## To reproduce

1. Ensure you're running latest WooCommerce & WordPress 5.9 with TwentyTwentyTwo theme activated.
2. Make sure your block theme has a `archive-product.html` file, this will be used as the fallback template for Product Category/Tag templates.
3. In Settings > Reading set your Homepage to be the "Shop" page.
4. Start outside the site Editor in WP Admin (Appearance > Themes).
5. Now navigate to Appearance > Site Editor. Because your "Shop" is set as the homepage it should load the `archive-product` template here initially.
6. Now browse to "All Templates" to view the complete list of templates.
7. Scroll down to "Product Category" and notice how it correctly indicates it is from the theme.
8. Click into it to edit the template and notice how the template is empty.

**Some things to note:**
* If you refresh the page the template gets loaded correctly.
* If you navigate back out of the empty template, into different template and then back into the Product Category template it loads correctly.
* If you don't set "Shop" as your homepage this bug doesn't appear.
* The correct template data is present in the `core` redux store, even when displaying a blank template.
* If you have Gutenberg activated, when presented with the blank template if you switch between the Code Editor and Visual Editor (triggering a rerender) the template renders correctly.

**This _could_ be an issue within Gutenbergs Site Editor.**

## Expected behavior
* On step 8 the template should load correctly.

## Screenshots

https://user-images.githubusercontent.com/8639742/153196618-5fad6ae9-35dd-4e28-9939-97fd91d8debd.mp4

**Comment by Aljullu** [comment]
@tjcafferkey do you think this issue is the same as https://github.com/woocommerce/woocommerce/issues/42656? Otherwise, should we reopen?
