### ISSUE TITLE
Actions and Filters documentation pages have broken links

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#5808]
## To reproduce
1. Go to https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/extensibility/actions.md
2. Click on any links under a _Source_ heading, for example, the first one: [StoreApi/Utilities/CartController.php](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/src/StoreApi/Utilities/CartController.php).
3. Notice it links to a broken URL:
https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/src/StoreApi/Utilities/CartController.php
instead of:
https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/src/StoreApi/Utilities/CartController.php

The same issue happens in the filters documentation page: https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/extensibility/filters.md

## Expected behavior
The links should work.

## Code

The _Source_ section of those files is generated here:

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/5545c38c4bef7e0d9768c29802426d4956716f2c/bin/hook-docs/actions/index.js#L57
https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/5545c38c4bef7e0d9768c29802426d4956716f2c/bin/hook-docs/filters/index.js#L57

**Comment by AndrewJDawes** [comment]
Hey, @Aljullu - are we ready to merge now? Let me know if there is anything else I can help with!

**Comment by Aljullu** [comment]
Sorry, I missed your PR. Reviewing it right now.
