### ISSUE TITLE
Single Product block - Storefront theme: When it is added a product with this block,  the Storefront Mini Cart doesn't update

### ISSUE THREAD

**Issue by gigitux** [woocommerce/woocommerce-gutenberg-products-block#5812]
## Describe the bug

With the Storefront theme activated, when it is added a product with the `Single Product` block, the Storefront Mini Cart doesn't update.

## To reproduce

1. Active Storefront theme.
2. Create a post/page with the `Single Product` block. Save it.
3. Go on the created post/page.
4. Add a product and check that the Storefront Mini Cart doesn't update.

## Expected behavior
The Storefront Mini Cart should be updated.

## Screenshots

https://user-images.githubusercontent.com/4463174/153460431-673520d0-5ef8-425b-825e-24e5646707da.mov

### WordPress (please complete the following information):
* Core version: 5.9

**Comment by Aljullu** [comment]
@gigitux I think this issue refers to the old version of the Single Product block, no? Can it be closed? i just tested it and the Add to Cart button causes a page refresh.

**Comment by gigitux** [comment]
@Aljullu Theoretically, there is an issue with the page refresh https://github.com/woocommerce/woocommerce-blocks/issues/8771. We are planning to work on it. Do you think that we should wait and fix this issue when we integrate the Interactivity API?

cc @thealexandrelara

**Comment by Aljullu** [comment]
Oh, ok. That makes sense. We can either keep this issue open and test it again once #8771 is fixed or close it now and reopen it if it's reproducible again after #8771 is fixed. Whatever makes more sense to you. :upside_down_face:

**Comment by gigitux** [comment]
Let's keep this issue. I will add in the #8054 epic. I think that it makes sense to keep the priority low, so it isn't necessary to spend a lot of time on it. What do you think?

**Comment by Aljullu** [comment]
> What do you think?

Sounds good to me. :+1:

**Comment by gigitux** [comment]
This issue has been fixed with https://github.com/woocommerce/woocommerce-blocks/issues/8771
