### ISSUE TITLE
Cover Mini Cart block with tests

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#5814]
Recently, @nielslange has identified several critical flows for the Cart block that they would like to cover with automated testing. This issue is to evaluate if we would like to have the same tests for the Mini Cart block:

* https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5751
* https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5752
* https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5753
* https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5754
* https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5755
* https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5756
* https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5762
* https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5763

**Important:** take into account the issues above are for the Cart block. We should create separate ones for the Mini Cart block.

There are a couple more that come to my mind:

* Shopper → Mini Cart → Can open/close the drawer
* Shopper → Mini Cart → Can go to Cart page

We already have some tests for the Mini Cart block that can be found here:

* https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/assets/js/blocks/cart-checkout/mini-cart/test/block.js
* https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/tests/e2e/specs/backend/mini-cart.test.js

**Comment by nielslange** [comment]
> Recently, @nielslange has identified several critical flows for the Cart block [...]

To be fair, it was not only my effort, but a team effort. Here's how we identified the critical flows:

- I created a list with all cart and checkout flows.
- I asked team Rubik to provide feedback regarding this list.
- After I received all feedback, I created a Google Form with all flows we found.
- Then, everyone from the team voted on the flows.
- Each flow could be voted as Critical (3 points), High (2 points) and Low (1 point).
- After the voting, I calculated the points of each flow.
- As we voted with 8 people, each flow could have min. 8 points and max. 24 points.
- We then considered each flow, that scored 16+ points, as critical.

I suggest identifying the critical flows as a team effort, to involve everyone, and to utilize [the wisdom of the crowd](https://en.wikipedia.org/wiki/Wisdom_of_the_crowd).

**Comment by dinhtungdu** [comment]
From the list above and @Aljullu suggestion, I edited and combined them to a critical flows list for the Mini Cart block:

- https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5828
- https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5829
- https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5831
- https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5830
- https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5832
- https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5835
- https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5833
- https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5834
- https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5837
- https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5836
