### ISSUE TITLE
Authorie.net added to payment options for Checkout Block

### ISSUE THREAD

**Issue by bradhogan** [woocommerce/woocommerce-gutenberg-products-block#5819]
I'm requesting that the WooCommerce Authorize.net extension be added to the WooCommerce Blocks > Checkout block.  Cheers,

**Comment by tarunvijwani** [comment]
Hi there bradley2083 👋

Thanks for taking the time to make the suggestion to add Authorize.net in the Checkout and Cart blocks. 

These blocks are still in early access (via the feature plugin) and it’s expected that some existing Woo Extensions that integrate with the current checkout flow in WooCommerce core will not work with the blocks.

We’re currently working on adding extensibility for the blocks so extensions have a way to make sure they integrate with the new flows being developed. Once that is done we’ll have docs prepared and will be reaching out to Woo Extension developers to help them with getting their extensions integrated.

There is already [some documentation available here](https://href.li/?https://github.com/woocommerce/woocommerce-gutenberg-products-block/tree/trunk/docs/extensibility) that you could share with the developers of the Authorize.net extension now if you want to get this on their radar!

Until then you can keep on top of the [status of the Cart & Checkout Blocks in this documentation](https://href.li/?https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/).


We make note of all feedback we receive and we also close issues with the feedback as active issues are used for bugs or feature/enhancements. It does not mean that we don’t note or review the feedback. Closed issues can also still be commented on.
