### ISSUE TITLE
store api - How do I view order information that has been checkouted

### ISSUE THREAD

**Issue by hans007** [woocommerce/woocommerce-gutenberg-products-block#5822]
store api 
How do I view order information that has been checkouted, such as historical orders, current orders, downloadable items.

**Comment by tarunvijwani** [comment]
Hi there @hans007 👋

Thanks for asking the question about Store API.  The [Store API](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/src/StoreApi/README.md) is a REST API that does not require authentication. 

It cannot be used to look up other customers and their orders. It can only retrieve data belonging to the current user.

More information is available in our [Store API documentation](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/src/StoreApi/README.md).

If you wish to retrieve the order details of a customer, you'll need to utilize the [WordPress REST API](https://woocommerce.github.io/woocommerce-rest-api-docs/#introduction).
