### ISSUE TITLE
Outdated error notices persist in the cart even after making valid configurations

### ISSUE THREAD

**Issue by jimjasson** [woocommerce/woocommerce-gutenberg-products-block#5838]
## Describe the bug

When an invalid configuration is made in the cart, an error notice shows up informing the customers why they cannot proceed to the checkout. For example, if someone adds a product to the cart twice and the stock of this product drops to 1 before completing the purchase, then an error notice will show up. This notice should be removed if the customer decreases the product's quantity to 1 or if the product gets restocked in the meantime. 

However, this is not the case. The error persists in the cart page even after the contents of the cart become valid. Taking a look at the response's body, I noticed that the `errors` key is empty but the outdated error persists in the cart:

![Markup on 2022-02-14 at 14:04:10](https://user-images.githubusercontent.com/25955483/153862546-4cb3cbb0-eaf0-436b-aa51-7915d91a2159.png)

## To reproduce

1. Create 2 in stock products.
2. Add them both to the cart.
3. Set the stock status of the first product to `Out of stock`.
4. Increase the quantity of the second product in the cart. You should see an error notice show up. 
5. Set the stock status of the first product back to `In stock`.
6. Increase the quantity of the second product in the cart. The error that was triggered because of the previous configuration still persists. 

## Expected behavior
Error notices should be cleared if the cart contents change and they become valid.

### WordPress (please complete the following information):
Fresh WordPress install.

**Comment by manospsyx** [comment]
Here's a video from the Product Bundles integration demonstrating this behavior: https://share.getcloudapp.com/d5uNkbrY

I also noticed that when an illegal "item removal" request is blocked by throwing an Exception on the Store API side, the message in the Exception is not rendered by the Block as a notice. You can see this in the second part of the video. Not sure if the two issues are related -- I'd guess that exception messages are not picked up at all, which is not necessarily a bug but perhaps something that the Cart Block does by design?

**Comment by PanosSynetos** [comment]
Wanted to chime in here too, this affects https://github.com/woocommerce/woocommerce-conditional-shipping-and-payments/ too

https://user-images.githubusercontent.com/2484390/156315729-e02c1ac8-1364-4105-837f-c247adc19d7d.mp4

**Comment by ankitguptaindia** [comment]
Would be helpful if fix this as this issue also affects the UX of Min/Max Quantities plugin. Thanks!

More Details related to the problem of Min/Max is here in **Point 2** https://github.com/woocommerce/woocommerce-min-max-quantities/pull/152#issuecomment-1204105631
