### ISSUE TITLE
Filter Products by Attribute: border color global style is not applied

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#5846]
## Describe the bug
Setting a border color to the Filter Products by Attribute block in global styles doesn't have any effect in the block once rendered in the editor/frontend.

## To reproduce
1. Go to Editor > Styles > Blocks > Filter Products by Attribute > Border and set a border color.
![imatge](https://user-images.githubusercontent.com/3616980/154052420-6979c67d-ac59-4fb4-852a-634cd8f4883e.png)
2. Create a post or page and add the Filter Products by Attribute block and select Dropdown display style.
3. Notice the border color set in global styles is not applied.
![imatge](https://user-images.githubusercontent.com/3616980/154052476-ff91337d-755d-4147-bfe2-8de62c9c7836.png)

## Expected behavior
The border color set in the global styles should be honored in the block.

**Comment by gigitux** [comment]
Unfortunately, I'm not able to reproduce this error :(

I'm using WordPress 5.9 without GB with Twenty Twenty Two theme enabled.

https://user-images.githubusercontent.com/4463174/154317738-bbb4410a-b6fd-49bd-9b36-825f37e312d0.mp4

The border on the post editor and frontend looks weird from the video, but I guess that it is the compression. I will attach some images:

![image](https://user-images.githubusercontent.com/4463174/154318109-9837feb6-6bc4-467f-b58b-2894d7367a06.png)
*frontend*

![image](https://user-images.githubusercontent.com/4463174/154318180-f0936271-8df3-4b6e-81cf-534faa3dabab.png)
*editor*

**Comment by tomasztunik** [comment]
I'm looking at the screenshot and the colour on the error screenshot is actually green that was selected, tested it locally as well and works 🆗  - @Aljullu you have to pick higher contrast colours next time :)

**Comment by Aljullu** [comment]
Lol, you are right! Sorry for the confusion. :pray:
