### ISSUE TITLE
Twenty Twenty-Two: Proceed to Checkout button changes its size when Cart is loading

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#5847]
In the Cart block with Twenty Twenty-Two theme, the Proceed to Checkout button changes its size when Cart data is loading.

## To reproduce
1. Make sure you have more than one shipping method set up.
2. Add some products to your Cart and go to the Cart block.
3. Change the selected shipping method.
4. Notice the size of the button changes.

https://user-images.githubusercontent.com/3616980/154054686-e16e1b66-b7cb-48e4-8ec5-ed81b37f449f.mp4

## Expected behavior
The button should always have the same size.

I think the reason of the change is because the element changes from being an `a` to a `button` and viceversa.

**Comment by wavvves** [comment]
@Aljullu just tested this and I couldn't replicate it, does it still occur for you? If not, we can probably close this.

**Comment by danieldudzic** [comment]
I can confirm that this is now working as expected.
