### ISSUE TITLE
Rename Legacy Template block to Classic Template block

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#5861]
Suggested by @nerrad, we want to rename the Legacy Template block to Classic Template block.

<img src="https://user-images.githubusercontent.com/3616980/154237625-3f39a3eb-dd6c-4830-8021-8bb9f8149cc9.png" width="285" alt="" />

Some relevant files:

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/assets/js/blocks/legacy-template/index.tsx

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/src/BlockTypes/LegacyTemplate.php

**Comment by sunyatasattva** [comment]
@Aljullu @nerrad When we do these kinds of renaming, how deep do we want to go renaming things internally? Like, do we change ids? Do we change filenames and classes?

It seems to be it could be weird to have `LegacyTemplate.php` which defines `LegacyTemplate` class which is actually called “classic template“ in the end. It could lead to confusion for future devs looking for things.

On the other hand, this kind of deep renaming has of course deeper implication in changing all dependencies and references.

With #5935 (still in draft) I'm sort of going a middle ground approach: renaming user-facing strings and changing some other definitions appearing in test cases descriptions, for example, but I'm leaving slugs, and internal ids as they are.

What are your thoughts?

**Comment by Aljullu** [comment]
> When we do these kinds of renaming, how deep do we want to go renaming things internally? Like, do we change ids? Do we change filenames and classes?

Good question. I don't have a strong opinion on this. In my opinion, we should go as deep as possible without breaking backwards compatibility. So I guess we can't change ids or anything like that, but I completely agree with your statement here:

> It seems to be it could be weird to have LegacyTemplate.php which defines LegacyTemplate class which is actually called “classic template“ in the end. It could lead to confusion for future devs looking for things.

So my question is: can we rename the PHP class while keeping the original block id so template don't invalidate? If so, I would try to go that way?

**Comment by tjcafferkey** [comment]
I agree with @Aljullu's thoughts on this too. Let's try change what we can which won't negatively impact on our users experience including filenames and asset names etc. IDs and such should remain the same if changing them could cause issues.
