### ISSUE TITLE
Product Tag List is not visible when it is used on All Product block in edit mode

### ISSUE THREAD

**Issue by gigitux** [woocommerce/woocommerce-gutenberg-products-block#5862]
## Describe the bug
The `Product Tag List` when the block is used on `All Product block`, is not visible in the “edit view” (image 1). If save it and exit from the “edit view”, it is visible (image 2).

## To reproduce

1. Go to post/page editor.
2. Add `All Products` block.
3. Click on the pencil to edit the single product view.
4. Add the `Product Tag List` block. 
5. It is not visible

## Expected behavior
The `Product Tag List` block should be visible in "edit view".

## Screenshots
![image](https://user-images.githubusercontent.com/4463174/154243552-f4c60c7b-315d-4399-96be-e649c97a4e5a.png)
![image](https://user-images.githubusercontent.com/4463174/154243701-fed97142-1614-4f3e-8635-3ed603f56c27.png)

**Comment by samueljseay** [comment]
@gigitux is this still relevant? I could not see an available "product tag list" block.

**Comment by gigitux** [comment]
> @gigitux is this still relevant? I could not see an available "product tag list" block.

Thanks for the ping! Not really, `All Products` block will be deprecated in the next months. I don't see any advantages on work on this issue. I will close the issue!
