### ISSUE TITLE
Cart block not working on WordPress.com site

### ISSUE THREAD

**Issue by tarunvijwani** [woocommerce/woocommerce-gutenberg-products-block#5866]
## Describe the bug

If we create a new page and add a cart block on a WordPress.com site, the screen gets freeze, and the browser gets crashes after a few minutes.

## To reproduce

1. Go to My Site → Pages → Add New. 
2. Add Cart block to the page.  
3. Notice the screen gets freeze. 

## Expected behavior

Cart block should be added to the page 

### WordPress:

-   Core version: 5.9
-   Gutenberg version (if installed): 12.5.4 
-   WooCommerce version: 6.2
-   WooCommerce Blocks version: 6.9.0

**Comment by opr** [comment]
Looks like requests are being made to the `https://siteurl.com/wp-json/wp/v2/block-renderer/woocommerce/product-new?context=edit&attributes%5Bcolumns%5D=3&attributes%5Brows%5D=1&attributes%5BalignButtons%5D=false&attributes%5BcatOperator%5D=any&attributes%5BcontentVisibility%5D%5Btitle%5D=true&attributes%5BcontentVisibility%5D%5Bprice%5D=true&attributes%5BcontentVisibility%5D%5Brating%5D=true&attributes%5BcontentVisibility%5D%5Bbutton%5D=true&attributes%5BisPreview%5D=false&attributes%5BstockStatus%5D%5B0%5D=instock&attributes%5BstockStatus%5D%5B1%5D=outofstock&attributes%5BstockStatus%5D%5B2%5D=onbackorder&post_id=2&_locale=user`

URL repeatedly on WPCOM, but not on local sites. I thought it would perhaps be lack of products causing this, but my WPCOM site has products.

**Comment by masperber** [comment]
Customer came in with this issue in 32837823-hc

Was able to workaround by using Shortcode block

**Comment by devNigel** [comment]
Facing the same issue on my test AT site.

**Comment by rinazrina** [comment]
Another report: 5167612-zd-woothemes

I can reproduce this on my test AT site too.

**Comment by wiesenhauss** [comment]
Another report: 35302175-hc

The issue appears on my test site too.

**Comment by tarunvijwani** [comment]
On a WordPress.com site, I was able to add the Cart and Checkout blocks to a page. But the front end doesn't load the content of the blocks. In the editor, it loads just fine.

Site: https://testingatomicsite.wpcomstaging.com/

WooCommerce: 6.6.1 
WooCommerce blocks: 8.0.0

| Editor | Front-end |
|---|---|
| <img width="902" alt="image" src="https://user-images.githubusercontent.com/11503784/177801788-fbf3f2d5-3c5c-4270-a30d-7e79cb3d062f.png"> | <img width="1157" alt="image" src="https://user-images.githubusercontent.com/11503784/177800908-a6f41f7a-8d1a-4b81-8526-16181d225842.png"> |

**Comment by csabarakasz** [comment]
Another report. On my test site, I could not replicate this, but on the user's site, I could. I deactivated all user plugin and switched themes. Didn't help. 

Original chat: 
- [ ] 36961223-hc

Followup:
- [ ] 5567833-zd-woothemes

**Comment by edwinho89** [comment]
Another report below:

- [ ] 5609786-zd-woothemes

I'm able to reproduce the issue on user's site and mine.

Based on another ticket in 5167612-zd-woothemes , I tried switching between FSE and non-FSE themes, both having similar issue.

**Comment by PanosSynetos** [comment]
Same for me - I was setting up a demo site for @manospsyx and it hang and crashed (tried Chrome and Firefox)

No errors in console

**Comment by jartes** [comment]
Another report on 37342472-hc. 

I was able to replicate this on a WordPress.com site. Suggested shortcodes as a workaround.

**Comment by pauljacobson** [comment]
Hi @senadir  👋 I have another report of this issue in 5684636-zen

I was able to reproduce this on [my test site](https://theatomizertestsite.wpcomstaging.com/) on a draft page. Both the user and I received an error like this when trying to add the Cart Block using the block selector: 2e1e5-pb/

This is what I experienced:

https://user-images.githubusercontent.com/2912202/200165283-bbd573fa-defb-4d23-9257-80d90e5c61cc.mp4

Themes:

- The user is using the Morden theme. 
- I was using Storefront on my site.

Plugins:

For my test, I only had our preinstalled plugins enabled, along with WooCommerce.

**Comment by eduardozulian** [comment]
This is still happening on 5689158-zen 

The customer is using the shortcode workaround.

**Comment by PanosSynetos** [comment]
If memory serves me well, these issues will be fixed in the upcoming WooCommerce 7.1 release (that will include the new version of blocks) - But I'll leave it to the owners of the repository to check and let you know.

@pauljacobson can you try Woo 7.0 and https://wordpress.org/plugins/woo-gutenberg-products-block/ on your test site ?

This will install the latest Woo Blocks version, overriding the one bundled with WooCommerce 7.0 .

I wouldn't recommend suggesting this to clients, as WooCommerce 7.1 is released tomorrow, which contains the latest Blocks. But if they are in a hurry and need to fix their issues, it wouldn't hurt.

**Comment by pauljacobson** [comment]
> @pauljacobson can you try Woo 7.0 and https://wordpress.org/plugins/woo-gutenberg-products-block/ on your test site ?
> 
> This will install the latest Woo Blocks version, overriding the one bundled with WooCommerce 7.0 .

Hi there @PanosSynetos 👋 Thank you for the suggestion. I also received this suggestion from the team on Slack. I've already relayed this suggestion but I'll bear in mind the 7.1 release if I encounter this issue again.
