### ISSUE TITLE
is_cart() and is_checkout() issues with Cart/Checkout blocks

### ISSUE THREAD

**Issue by ninetyninew** [woocommerce/woocommerce-gutenberg-products-block#5868]
## Describe the bug

If a page uses the cart or checkout blocks and these pages are not defined as the cart/checkout pages in Woo's settings then the is_cart() and is_checkout() conditions do not return true.

This causes a few issues because while someone should set their block based pages to be the cart/checkout they might have not as they are testing a page with a cart/checkout block within it before changing the setting from the existing shortcode based pages.

Plugins/themes may need the is_cart() or is_checkout() to return true when on a page with the cart/checkout blocks to ensure their functionality works correctly.

We are seeing a lot of users testing block based cart/checkout pages and users noticing their cart/checkout isn't working correctly compared to the existing cart/checkout pages due to this.

## To reproduce

Steps to reproduce the behaviour:

1. Create a cart and checkout page using blocks
2. Put a var_dump on each page for is_cart() and is_checkout()
3. If the pages are not set to the cart/checkout page in WooCommerce settings it returns false
4. If the pages are set to the cart/checkout page in WooCommerce settings it returns true

## Expected behaviour

Potentially that if a page has a cart/checkout block the is_cart and is_checkout conditions return true?
Possibly also add a notice in Gutenberg if a page contains a cart/checkout block and the page isn't set to to the cart/checkout page in Woo settings notify the user of this?

### WordPress (please complete the following information):

-   Core version: 5.9.0
-   Gutenberg version (if installed): None
-   WooCommerce version: 6.1.0
-   WooCommerce Blocks version: 6.9.0
-   Site language: English

### Desktop (please complete the following information):

-   OS: macOs
-   Browser: Chrome

**Comment by tarunvijwani** [comment]
Hi there @ninetyninew 👋🏻

Thanks so much for taking the time to leave some feedback – much appreciated!

In this case, you can use `has_block( "woocommerce/checkout" )` or `has_block( "woocommerce/cart" )`  functions to check if the page has these blocks.
