### ISSUE TITLE
Breaking styles of font size selector items

### ISSUE THREAD

**Issue by webmandesign** [woocommerce/woocommerce-gutenberg-products-block#5880]
## Describe the bug

First, hopefully I am at the correct place to report this issue as I think it is related to `woocommerce-gutenberg-products-block` and not to main `woocommerce` repo code.

After updating to WordPress 5.9 I've noticed the font size selector displays incorrectly. There should be spaces between font size label, the actual value and selected checkbox.

This is happening due to WooCommerce plugin overriding default WordPress styles of `.components-custom-selector-control__item { display: grid; }` with `.components-custom-selector-control__item { display: flex; }`.

Please fix this in next update.

## To reproduce

1. With WordPress 5.9 using Twenty TwentyOne theme and WooCommerce plugin create a page and add a paragraph with some text.
2. In paragraph block options click the selector to change font size and see there is no space separating the font size label and the value.

## Expected behavior

There should be space between font size label and value.

## Screenshots

![wc-issue--editor--font-size-selector](https://user-images.githubusercontent.com/2456735/154494574-8b002dc2-7d81-4845-a41e-de9b423b4702.png)

### WordPress (please complete the following information):

-   Core version: 5.9
-   WooCommerce version: 6.2.0
-   WooCommerce Blocks version: none as I think this is already included with WC?

### Desktop (please complete the following information):

-   OS: Windows
-   Browser Chrome
-   Version 98

**Comment by danieldudzic** [comment]
This is an odd bug. But it doesn't seem to be related to Products Blocks. I'm able to replicate it with just WooCommerce and the Gutenberg plugins active.

I have tried this with earlier versions of WooCommerce, but even with WooCommerce 5.0.0 this seems to be broken.

Please report this in the [WooCommerce repo](https://github.com/woocommerce/).

**Comment by webmandesign** [comment]
@danieldudzic Thanks for the info. I've reported this at https://github.com/woocommerce/woocommerce/issues/31928

**Comment by peterfabian** [comment]
Sorry for the ping pong here, but I think that style rule is coming from vendors CSS in the Blocks plugin:
woocommerce/woocommerce-gutenberg-products-block/node_modules/@wordpress/components/src/custom-select-control/style.scss (or one of the other CSS files in the node_modules):

![Screenshot 2022-03-18 at 15 49 11](https://user-images.githubusercontent.com/2207451/159025490-a2fa5c6b-c591-4f3f-a80f-f7cc2b610b46.png)


As you can see in the screenshot, the CSS rule is defined in wc-blocks-vendors-style.css, which is built [here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/bin/webpack-configs.js#L642-L646).
