### ISSUE TITLE
Mini Cart block: additional classes don't add on the frontend side

### ISSUE THREAD

**Issue by gigitux** [woocommerce/woocommerce-gutenberg-products-block#5881]
## Describe the bug

The addition classes don't render on the frontend side.

## To reproduce

1. Open the FSE editor.
2. Add the Mini Cart block.
3. Get focused on it.
4. On the right sidebar, on the block -> advanced section, add custom classes.
5. Save.
6. On the frontend page, inspect the Mini Cart Block.
7. The custom classes aren't added.

## Expected behavior

The custom classes should be added on the frontend side

## Screenshots
![image](https://user-images.githubusercontent.com/4463174/154496384-74f4d913-0922-4353-aa5d-78cd13f2b240.png)

**Comment by dashkevych** [comment]
Will this fix be included in WooCommerce plugin itself (without active WooCommerce Blocks plugin)?

It looks like the issue is present in WooCommerce (6.7.0)

**Comment by gigitux** [comment]
> Will this fix be included in WooCommerce plugin itself (without active WooCommerce Blocks plugin)?
> 
> It looks like the issue is present in WooCommerce (6.7.0)

Thanks for this comment. Unfortunately, there was a regression. I fixed it in #6716. For now, I will reopen this issue.
