### ISSUE TITLE
Mini Cart Contents template: the blocks added by the user are not visible on frontend side 

### ISSUE THREAD

**Issue by gigitux** [woocommerce/woocommerce-gutenberg-products-block#5883]
## Describe the bug

Mini Cart Contents template: the blocks added by the user are not visible on the frontend side 

## To reproduce

1. Open the FSE editor.
2. Open the Mini Cart template.
3. Add a block in the template (add the blocks to the `Mini Cart Items` or `Empty Mini Cart Contents` .
4. Save it.
5. Go on the frontend side.
6. The added block is not visible.

## Expected behavior

The added block should be visible.

**Comment by dinhtungdu** [comment]
@gigitux Do you mean adding blocks under the `Mini Cart Contents` or adding inner blocks to the `Mini Cart Items`?

If you're adding a top-level block under the Mini Cart Contents, then the block won't be visible on the front-end, and it's expected behavior. Related to this, we have woocommerce/woocommerce#42659 to disable adding blocks to the Mini Cart template part.

**Comment by gigitux** [comment]
> @gigitux Do you mean adding blocks under the `Mini Cart Contents` or adding inner blocks to the `Mini Cart Items`?
> 
> If you're adding a top-level block under the Mini Cart Contents, then the block won't be visible on the front-end, and it's expected behavior. Related to this, we have woocommerce/woocommerce#42659 to disable adding blocks to the Mini Cart template part.

I refer to `Mini Cart Items` and `Empty Mini Cart Contents` (I will update the issue)

**Comment by dinhtungdu** [comment]
Look like there are some changes that broke the inner contents. The inner content works before. https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5584 is an example of Empty Cart inner blocks. Checking out the merge commit of https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5635, both Mini Cart Items and Empty Mini Cart inner blocks are working on the front end.

**Comment by gigitux** [comment]
Yesterday @tjcafferkey and I found the problem. There was a regression after merge https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5746

On the frontend side we load always the template from the file.

**Comment by tjcafferkey** [comment]
Fixed in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5916
