### ISSUE TITLE
Cart/checkout blocks and woocommerce_check_cart_items Notices / woocommerce_proceed_to_checkout hooks

### ISSUE THREAD

**Issue by ninetyninew** [woocommerce/woocommerce-gutenberg-products-block#5889]
## Describe the bug

We have tested WooCommerce cart/checkout block based pages vs the shortcode based pages and have noticed some differences related to the woocommerce_check_cart_items action.

We can see that core WooCommerce uses woocommerce_check_cart_items to ensure that the cart is valid for checkout:
https://github.com/woocommerce/woocommerce/blob/3611d4643791bad87a0d3e6e73e031bb80447417/plugins/woocommerce/includes/class-wc-cart.php#L110

We can see here that if there is an issue it adds a notice and returns false to stop further progress through the checkout:
https://github.com/woocommerce/woocommerce/blob/3611d4643791bad87a0d3e6e73e031bb80447417/plugins/woocommerce/includes/class-wc-cart.php#L698

We are using similar functions in some of our custom development/plugins, on the shortcode based pages we see a notice appear on the cart/checkout and we also use `remove_action( 'woocommerce_proceed_to_checkout', 'woocommerce_button_proceed_to_checkout', 20 );` to remove the proceed to checkout button when there is an error.

The functionality hooked into woocommerce_check_cart_items and the removal of woocommerce_proceed_to_checkout doesn't seem to be being taken into account on the cart/checkout blocks.

## To reproduce

1. Add some custom code hooked from woocommerce_check_cart_items to display a notice and return false
2. Check the differences in the cart/checkout and the notices that appear on block based pages vs shortcode based pages

## Expected behavior

woocommerce_check_cart_items and woocommerce_proceed_to_checkout hooks work the same for cart/checkout block based pages as shortcode based cart/checkout pages.

I also believe is_cart() and is_checkout() conditions should return true if a page contains a cart/checkout block but isn't necessarily set to the cart/checkout in WooCommerce settings - this is because a number of plugins/themes use these conditions to effect functionality if it is the cart/checkout page.

### WordPress (please complete the following information):

-   Core version: 5.9.0
-   Gutenberg version (if installed): N/A
-   WooCommerce version: 6.1.0
-   WooCommerce Blocks version: 6.9.0

### Desktop (please complete the following information):

-   OS: macOs
-   Browser Chrome

**Comment by opr** [comment]
Hi @ninetyninew thanks for taking the time to write this report.

Firstly, you're correct `is_cart` and `is_checkout` won't return true based on a block's presence alone, instead you may use `has_block( 'woocommerce/cart' )` and `has_block( 'woocommerce/checkout' )` to see if either block is on the page.

Secondly, could you elaborate, perhaps with screenshots too, on the differences you see between shortcode and blocks when you say this?
> Check the differences in the cart/checkout and the notices that appear on block based pages vs shortcode based pages

That would be helpful.

Also, could you clarify why you're removing the checkout button, is this just for aesthetic purposes, or do your use-cases allow shoppers to checkout despite the cart being invalid? The Checkout Block still runs `woocommerce_cart_check_items` and if an error notice is added there, the checkout stops and shows the notice. This method of error handling may soon be deprecated, though, so please don't rely on it or expect it to remain in place in the long term. This PR (https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5904) aims to introduce more error handling. I would advise following this issue, and keeping an eye on the WooCommerce Blocks documentation for any updates that come.

**Comment by ninetyninew** [comment]
@opr 

So I have a function hooked off `woocommerce_check_cart_items`

This function checks cart items for some custom data and if the product shouldn't allow cart to continue we use:

```
wc_add_notice( sprintf( __( 'Example notice for product: %s .', 'my-custom-text-domain' ), get_the_title( $product_id ) ), 'error' ); // This would include some details of the issue and how to fix the error in cart (e.g. remove this item)

remove_action( 'woocommerce_proceed_to_checkout', 'woocommerce_button_proceed_to_checkout', 20 );

return false;
```

Without the removal of `woocommerce_proceed_to_checkout` the checkout button remains, and if you click it you see an error from checkout (not styled very nicely) `"There are some issues with the items in your cart. Please go back to the cart page and resolve these issues before checking out."` - which is the standard checkout error notice, we just remove the button to stop someone getting there as there isn't really any point when the error needs fixing within the cart.

The code above on shortcode based cart (shows the notice):

![Screenshot 2022-02-23 at 5 48 30 pm](https://user-images.githubusercontent.com/56840277/155377243-484a116a-4cd4-4289-96c1-dff9c585745b.png)

The code above on block based cart (shows no notice so user doesn't see the issue in the notice to fix the issue and they just get the general checkout error because `woocommerce_proceed_to_checkout` isn't taken into account):

![Screenshot 2022-02-23 at 5 48 47 pm](https://user-images.githubusercontent.com/56840277/155377273-6fa2bc59-a8d4-4f57-b6f0-3e7d8bab8a4e.png)

**Comment by manospsyx** [comment]
@opr this is in line with our [review on Validation and Error Handling here](https://wp.me/pdqkbG-E9-p2). @xristos3490 recently opened a PR to address some limitations on the Store API side, but we'll need to slowly dive into the Next Steps outlined in that post and look at the JS side as well in order to provide a solid experience to developers who want to add their own validation/error logic in different parts of the checkout flow. cc @senadir

**Comment by ninetyninew** [comment]
So with that review will we need to amend our code to make the cart block function the same as the shortcode version? Is this more an issue with `wc_add_notice` and WooCommerce Blocks?

**Comment by manospsyx** [comment]
Hey @ninetyninew -- we're currently working on a number of changes related with:

- adding errors in Store API cart route responses;
- handling errors in the checkout block.

Currently, the Store API:

- Does not convert notices added via `woocommerce_check_cart_items` to errors; however, if you attempt to place an order, you will see that your notices are displayed there.
- Does not provide a standardized way to control access to the checkout block when cart errors exist. 

A few aspects of error handling in the cart/checkout blocks are still work-in-progress -- however, if you need a way to control access to the checkout block, you could hook into the `woocommerce_blocks_checkout_update_order_meta` action and throw an exception from there like this:

```
throw new Automattic\WooCommerce\Blocks\StoreApi\Routes\RouteException( 'my_custom_error', $notice );
```

Could you perhaps try this and let me know if it helps?

**Comment by ninetyninew** [comment]
I don't think we need to right now as we aren't seeing many users using WooCommerce Cart/Checkout blocks, most of the ones that do and have had issues with this seem happy to revert back to using the traditional cart/checkout - some of them have just installed the WooCommerce Blocks plugin and aren't aware cart/checkout blocks aren't part of core WooCommerce yet.

Ideally we are just looking for a means that works for both the traditional and blocks, we don't really want to be writing/maintaining 2 different pieces of code for the traditional cart/checkout vs block based, we've already had a similar thing with product blocks.

As cart/checkout blocks aren't available yet in WooCommerce core I think we'll just wait until there is something more concrete in terms of this notice issue, hopefully not requiring us to maintain 2 sets of code for the traditional and blocks.

**Comment by ralucaStan** [comment]
Since there's nothing actionable with this issue at the moment I'm going to close it, but I do appreciate you taking the time to leave the issue.

**Comment by ninetyninew** [comment]
@manospsyx I've had to come back to this as a priority now WooCommerce Cart/Checkout blocks are default for new installs, has there been any updates on this: https://github.com/woocommerce/woocommerce-blocks/issues/5889#issuecomment-1050077979 2 years later?

Upon testing I am seeing the notices appear fine in cart/checkout blocks but we are desperately trying to find an equivalent of `remove_action( 'woocommerce_proceed_to_checkout', 'woocommerce_button_proceed_to_checkout', 20 );` for blocks (the idea of hooking into `woocommerce_blocks_checkout_update_order_meta` and adding exceptions there isn't something we've found works and means writing a lot of additional/duplicated code, when we already have all the conditions as part of the `woocommerce_check_cart_items` function).

I've also reached out on: https://woocommercecommunity.slack.com/archives/C03MCL9RTAR/p1704804003139369 for help if you want to check my current issue, but it's roughly the same as reported here.

EDIT: I've just realised the cart/checkout blocks don't allow disable/removal of the button and while it's possible to go from cart to checkout with errors it's not possible to make continue checkout further, you can read more about this in my Slack above, so no need for a reply.
