### ISSUE TITLE
New Block: Reviews by Category

### ISSUE THREAD

**Issue by ryelle** [woocommerce/woocommerce-gutenberg-products-block#589]
Very similar to #588, this block lets the writer display reviews on multiple products in a selected category.

The initial state now lets you choose 1 or more categories:

![Reviews by Category - Edit](https://user-images.githubusercontent.com/541093/58134841-09513900-7bf6-11e9-9a1b-2ed166205716.png)

And once selected, each review now has a label with the product name:

![Reviews by Category - Preview](https://user-images.githubusercontent.com/541093/58134842-09513900-7bf6-11e9-9db5-3080ba789761.png)

The inspector options are almost exactly the same as Ratings by Product, the custom panels we have are:

- Product Category (still closed by default) using `ProductCategoryControl`
- Content (now has another toggle for showing product name)
- List Settings (no change)

**Comment by mikejolley** [comment]
@jwold Is there an icon/svg ready for this block please?

**Comment by jwold** [comment]
Here you go! Thanks :)

[SVG.zip](https://github.com/woocommerce/woocommerce-gutenberg-products-block/files/3444326/SVG.zip)
