### ISSUE TITLE
Update Legacy Template block titles

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#5890]
<img src="https://user-images.githubusercontent.com/3616980/154658234-51d0a2ec-065b-4fb1-a054-c540c8b9fa3d.png" alt="Legacy Template block title screenshot" width="682" />

We want to change the titles of the Legacy Template blocks like this:

Old Title | New Title
-- | --
WooCommerce Product Grid Block | WooCommerce Product Catalog Template
WooCommerce Product Tag Block | WooCommerce Products by Tag Template
WooCommerce Product Taxonomy Block | WooCommerce Products by Category Template
WooCommerce Single Product Block | WooCommerce Single Product Template

Suggested by @nerrad (pdnLyh-tW-p2#comment-323).

**Comment by sunyatasattva** [comment]
This was closed by #5935
