### ISSUE TITLE
Question on E2E utilities

### ISSUE THREAD

**Issue by dinhtungdu** [woocommerce/woocommerce-gutenberg-products-block#5893]
Currently, in the `./test` folder, we have two places for utility functions:

- `test/e2e/utils.js` which is, by its location, used for E2E testing.
- `test/utils`: this folder contains JS utilities for **both** JS unit tests and E2E testing.

What is the purpose of this organization?

This is making me confused. I think we should move utilities related to E2E into `test/e2e/utils.js`, or we can create `test/e2e/utils/` folder and move E2E utility files from `test/utils/`.

cc @Aljullu @nielslange

**Comment by Aljullu** [comment]
> This is making me confused. I think we should move utilities related to E2E into `test/e2e/utils.js`, or we can create `test/e2e/utils/` folder and move E2E utility files from `test/utils/`.

Agree, if a utility is only used by e2e tests, let's move it inside the `e2e` directory.

cc'ing @sunyatasattva who is currently working on e2e tests for the template editing project, so maybe has something to add as well.

**Comment by sunyatasattva** [comment]
I didn't even notice there were E2E tests utils not in the E2E utils file. Definitely we should move them all there.

Also, after [some feedback](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5722#discussion_r809790855) by @tomasztunik, I have created another file called `page-utils` to put more generic utilities for E2E tests but not related to our specific user flow.

Perhaps it would be interesting to call the other utils file something like `flow-utils` borrowing from Tomek's suggestion. I didn't do it because I thought it required a discussion + it needed an extra refactoring.

Since this issue is about refactoring, perhaps it's a good place to bring it up.

**Comment by tomasztunik** [comment]
I've noticed that with the utils in root as well and noticed most of them were actually e2e related. As we have here all kind of tests we should definitely keep only shared code at a given depth. 

Regarding user flow utils I think having domain name in the file like it was in Gutenberg is maybe enough? Do you think there'd be enough domain utils and flows that would call for separate files per domain? Ie. `site-editor.utils.ts` `site-editor.flows.ts`?

**Comment by sunyatasattva** [comment]
I personally don't think so at this point. And many utils are definitely shareable between site-editor and post-editor for example. We've got so many files add many more unless it's called for (like generically separating page-utils and flow utils was a good idea for me).

These are my 2c after working with these tests for a while, both in Gutenberg and in Blocks 😁

**Comment by nielslange** [comment]
My thoughts are similar to @sunyatasattva's thoughts. I'd rather move all functionality to `test/utils` so that these functions can be used both by unit, integration and e2e tests.

**Comment by ralucaStan** [comment]
Please note that there is another internal discussion about grouping the utility functions around `shopper` and `merchant` functionality. pca54o-38z-p2#comment-3679

We are exploring having `shopper.block.placeOrder()` utilities which are blocks specific in order not to overwrite the `shopper.placeOrder()` from WC

**Comment by alexflorisca** [comment]
Closing this as I think this is solved now. I'm also planning to create a bit of a E2E test tidy up PR, since there's a lot of work been done by different people on it. I'll take this discussion into account
