### ISSUE TITLE
Find places where `useCustomerDataContext` is used and replace it with `useCustomerData`

### ISSUE THREAD

**Issue by opr** [woocommerce/woocommerce-gutenberg-products-block#5897]
Ideally we should ensure all our data comes from one place, there are a few other instances of `useCustomerDataContext` being used but in woocommerce/woocommerce-blocks#5817 we added a hook for this data that does not rely on context.

We should replace uses of the context hook, and see if we can remove the `CustomerDataContext` altogether.

**Comment by ralucaStan** [comment]
@nielslange did your investigation in woocommerce/woocommerce#42634 have any results? 
@opr this seems to be the last open ticket from the epic https://github.com/woocommerce/woocommerce-blocks/issues/5711. What are your thoughts on it? Is this still worth pursuing?

**Comment by nielslange** [comment]
> @nielslange did your investigation in https://github.com/woocommerce/woocommerce/issues/42634 have any results?

@ralucaStan I opened woocommerce/woocommerce#42634, to track this issue, but haven't investigated it yet. I noticed that the reported issue was first stalled and then auto-closed. That said, unfortunately, I don't have any results to share in this case.

**Comment by opr** [comment]
`useCustomerDataContext` is no longer used.
