### ISSUE TITLE
Individual products - remove rows slider

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce-gutenberg-products-block#59]
When displaying individual products we know the total number of products the user wants to display. So we only need to present a columns selector - rows should be automatically calculated.

**Comment by spencerfinnell** [comment]
Is there a need for Rows when picking products? I picked 4 products and they displayed in the grid. I switched to Rows and only 1 was visible because Rows was set to 1 for some reason. If I picked 4 products specifically I think those should always show.

**Comment by jameskoster** [comment]
Yeah good point. Funny cause that's what I had in the original designs. 

Not sure why I opened this issue in the first place :D

**Comment by jameskoster** [comment]
Ah, I just checked. We're still displaying the rows slider for the individual products scope. We just need to remove that. I'll update the issue.

**Comment by claudiulodro** [comment]
See #89
