### ISSUE TITLE
New Block: Featured Category

### ISSUE THREAD

**Issue by ryelle** [woocommerce/woocommerce-gutenberg-products-block#591]
Like the Featured Product block, we can also feature a single category. First, you need to select a single category:

![featured-category-edit](https://user-images.githubusercontent.com/541093/58135105-1de20100-7bf7-11e9-8fdb-5bebd5855b0d.png)

This will then use the same format as Featured Product to show the title, description, and a button-link to the category archive (button text and link URL can be edited). The background image defaults to the category thumbnail, but can be changed.

![featured-category-preview](https://user-images.githubusercontent.com/541093/58135106-1de20100-7bf7-11e9-8abd-487c228048bb.png)

**Comment by mikejolley** [comment]
@jwold Do you have an SVG of the icon needed for this block? (the folder with star on it)

**Comment by jwold** [comment]
[icon.svg.zip](https://github.com/woocommerce/woocommerce-gutenberg-products-block/files/3356067/icon.svg.zip)

Here you go @mikejolley. I went with a different style of folder so that can avoid having three different folder styles in our blocks. Thanks!
