### ISSUE TITLE
Mini Cart Block: if the user updates the number of items from WC Core cart page, the Mini Cart block doesn't update

### ISSUE THREAD

**Issue by gigitux** [woocommerce/woocommerce-gutenberg-products-block#5931]
## Describe the bug

On the WC core cart page, if the user updates the number of items, the Mini Cart block doesn't update

## To reproduce

1. Open the FSE editor.
2. Add the `Mini Cart` block on the footer or header area.
3. Save.
6. On the frontend page, add a product to the cart
7. Go on the WC core cart page (by default is `/cart/`)
8. Update the item number.
9. Check that the Mini Cart block counter doesn't update.

## Expected behavior

The Mini Cart should be updated.

## Screenshots

![image](https://user-images.githubusercontent.com/4463174/155376322-dfecadf6-9c66-4ef0-bccf-b61cf3f4b1ac.png)

**Comment by Aljullu** [comment]
That might be caused by the fact that we don't load scripts when in Cart/Checkout pages:

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/886f38da3eb24711c94a4cd52ff19c9b742dec3b/src/BlockTypes/MiniCart.php#L82-L84
