### ISSUE TITLE
Consulta

### ISSUE THREAD

**Issue by calicotienda** [woocommerce/woocommerce-gutenberg-products-block#5956]
Hola, me gustaría poder usar los bloques que tienen para crear pagia de carrito y de check out pero son incompatibles con mi metodo de pago (transbank) existe alguna manera de compatibilizarlo??
MUchas gracias.

**Comment by ralucaStan** [comment]
Hi there @calicotienda  👋

Thanks for taking the time to make us aware that Transbank isn’t working with the Checkout and Cart blocks. These blocks are still in early access (via the feature plugin) and it’s expected that some existing Woo Extensions that integrate with the current checkout flow in WooCommerce core will not work with the blocks.

Currently it’s up to payment method extension developers to add support for the new checkout flow offered via the Cart and Checkout blocks. We have some [documentation on that here](https://href.li/?https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/extensibility/payment-method-integration.md) and you can also point them to [this post](https://href.li/?https://developer.woocommerce.com/2021/03/15/integrating-your-payment-method-with-cart-and-checkout-blocks/).

Your best course of action right now if you are using a payment method that isn’t working with the blocks is to notify the developer of the extension and ask if they can add support.

Until then you can keep on top of the [status of the Cart & Checkout Blocks in this documentation](https://href.li/?https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/).
