### ISSUE TITLE
404 error on product-sale-badge.js

### ISSUE THREAD

**Issue by daniyalahmadk** [woocommerce/woocommerce-gutenberg-products-block#5957]
## Describe the bug

When we try to edit any post/page (post.php/post-new.php) or try to access customizer it throws a 404 error for product-sale-badge.js.

It seems like the plugin is trying to load this js file from the following path:

`/wp-content/plugins/woo-gutenberg-products-block/build/product-sale-badge.js?ver=7.0.0
`

## To reproduce

1. Go to Posts > Add New
2. Check the console and we will find the website is trying to load product-sale-badge.js.

## Expected behavior

Not to throw this warning in the console.

### WordPress (please complete the following information):

-   Core version: 5.9.1
-   WooCommerce version: 6.1
-   WooCommerce Blocks version: 7.0
-   Site language: En
-   Any other plugins installed: N/A

### Desktop (please complete the following information):

-   OS: macOS
-   Browser chrome
-   Version: 22

**Comment by sunyatasattva** [comment]
Hello @daniyalahmadk 

Thanks for reporting this issue. Your reproduction instructions mention that this happens on any post for you, but I can't seem to reproduce that.

However, there is a known issues with failed resource loading here: https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5945 it seems like it would be the same issue, correct?

If that's the case, we are already aware of it and working on the issue as we speak!

**Comment by tomasztunik** [comment]
This is now fixed via #5989, should be live soon.
