### ISSUE TITLE
The Empty Cart block does not show translated texts

### ISSUE THREAD

**Issue by ralucaStan** [woocommerce/woocommerce-gutenberg-products-block#5968]
## Describe the bug

The Empty Cart block does not show translated texts

This bug was found while testing  https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5910

## To reproduce

1. Go to Settings > General > Language (`/wp-admin/options-general.php`) and select a language which has WC core translation at 100% but WC Blocks' at 0%. (I tested with `Català`).
2. Go to the updates screen (`/wp-admin/update-core.php`), scroll down and update the language translations.
3. Visit the Empty Cart block and notice the texts are not translated
4. Visit the Cart or Checkout block in the frontend and verify the texts are translated.

## Screenshots

<img width="1040" alt="Screenshot 2022-03-01 at 09 52 21" src="https://user-images.githubusercontent.com/1628454/156185392-a7fe9fce-c482-427f-999b-1897ae40f21a.png">

**Comment by masteradhoc** [comment]
@ralucaStan isnt this fixed already?

**Comment by ralucaStan** [comment]
Hey @masteradhoc,
thank you for reaching out. We didn't get a chance to look into this yet. But we did find a similar issue that was fixed following the steps from [this comment](https://github.com/woocommerce/woocommerce-blocks/issues/6281#issuecomment-1103589176). Would you mind trying that and let us know if that solves your issue?

**Comment by senadir** [comment]
Empty Cart uses core blocks (heading, paragraph...) and the value of those fields is hard-coded into the page, they will reflect the language you had when you inserted the block.
This is the same if you have multilanguage content pages, treat the empty cart as a static page.
<img width="999" alt="image" src="https://user-images.githubusercontent.com/6165348/169031909-77445302-091a-4176-9ddc-9fd0aa6bfb67.png">

For most translation engines (WPML, Polylang, TranslatePress) they provide the option to duplicate a page between langauges.

**Comment by senadir** [comment]
Raluca, I'm going to close this because there's nothing to fix here.
