### ISSUE TITLE
Interrupt the order payment flow when `errors` exist

### ISSUE THREAD

**Issue by manospsyx** [woocommerce/woocommerce-gutenberg-products-block#5972]
## Is your feature request related to a problem? Please describe.

Ideally, the Checkout Block should not allow users to attempt payment when errors are present in the cart state — both for performance, and for user experience reasons.

This ties into https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5971

## Describe the solution you'd like

- Prevent payment attempts if `errors` exist in the last cart response. Design feedback might be necessary to identify the optimal UI response when Place Order is clicked while notices exist on the page (e.g. tooltip, alert?).

**Comment by ralucaStan** [comment]
@elizaan36 pointed out that in WooPay the pattern is to disable the button until the required conditions are met.

**Comment by opr** [comment]
@mikejolley to solve this we would need to ensure snackbar notices relating to the cart are `explicitDismiss: true`.

If they are not, when they disappear there is no indication as to _why_ the button is disabled.

https://www.loom.com/share/0d5fa251251d4110b403b2520b84b192

Going back to your comment in pca54o-4vF-p2#comment-4546 you said you don't want to introduce anything new to the API, however that was before we moved to snackbars. What are your thoughts on that now? We could pass `[ 'explicitDismiss' => true ]` in the `WP_Error`'s additional data, which could in turn inform the UI.

**Comment by mikejolley** [comment]
@opr It is my understanding that we only should disable the place order button if _validation errors are present_, i.e. from field validation. Basing this on the error notice system is not intuitive—errors can be thrown by anything, but it doesn't necessarily relate to the state of the checkout form, and we don't want to block users. Submitting the order again and seeing the errors again does not seem like a problem.

If other use-cases need to disable the button, it should be done via a filter hook, but I'd be careful about locking users out of checkout unintentionally. Remember we want to introduce the event-based hooks too so you can block access to checkout before checkout form is presented.

**Comment by ralucaStan** [comment]
In on our discussions with @elizaan36 it was decided that we won't be disabling the Place order button when error notices are present on the form. 

If there are validation errors, then the form button won't be disabled, but when clicking it the first input with error should be focused. This is the current behaviour at the moment so I am closing this ticket
