### ISSUE TITLE
Only load blocks package when site is using a block enabled theme.

### ISSUE THREAD

**Issue by addedlovely** [woocommerce/woocommerce-gutenberg-products-block#5995]
## Describe the bug
Would it be possible to only load the blocks package when a theme is actually supporting / using blocks. In a similar vein to the WordPress core update below:
https://core.trac.wordpress.org/ticket/54844

Below is a screenshot from a trace on New Relic, when loading a product page.

Whilst is the impact is somewhat negligible, would feels like our site is somewhat suffering a death by a thousand cuts when it comes to performance.

## Screenshots
<img width="1616" alt="Blocks" src="https://user-images.githubusercontent.com/565669/156778974-497b7f5a-c07f-40ce-81f4-0e73e3fee4bb.png">

### WordPress (please complete the following information):

-   Core version: 5.9.1
-   WooCommerce version: 6.2.1 
-   Site language: English

**Comment by sunyatasattva** [comment]
Hello @addedlovely! Thanks for the report.

This is an excellent point and I'll put this on our backlog. We'll need to decide how to address this, but the fact that you provided a Core link helps a lot in the decision-making process.
