### ISSUE TITLE
Individual product blocks pre-populated

### ISSUE THREAD

**Issue by warrendholmes** [woocommerce/woocommerce-gutenberg-products-block#60]
If I create a new product block using the "Individual Products" block the same products are auto-selected if I choose to create another product block with "Individual Products".

I'm not sure if this is intentional or not. If it is, wouldn't the better option for the user be to Duplicate the block or convert it to a re-usable block?

**Comment by tiagonoronha** [comment]
I've tested this multiple times with different configurations, and I couldn't replicate the behaviour you're describing.

Talking with @claudiulodro we believe that this was a bug in Gutenberg and has since been fixed!
