### ISSUE TITLE
Use Shortcode to display Handpicked Products Block

### ISSUE THREAD

**Issue by AffenJunge7** [woocommerce/woocommerce-gutenberg-products-block#601]
Hey there,
I was wondering if you could use a shortcode to display the Gutenberg-Block for handpicked products.
I am working on a company project that uses shortcode to show their products provided by their own api. In the future there will be a product import that allowes me to work with the products within WooCommerce.
Would it be possible to create a functionality that replaces the old shortcode (e.g. [products=”123456,654321,142536″]) and outputs the Gutenberg block with these products by taking the arguments as a parameter and pass them to the block?

I asked this question before at the wordpress plugin support page and they asked me use the github repository.
https://wordpress.org/support/topic/use-shortcode-to-display-handpicked-producs-block/

Thanks and kind regards,
Peter

**Comment by ryelle** [comment]
Hi @AffenJunge7, we want to be able to do that, but Gutenberg doesn't support that kind of transform yet. As soon as we can, we will be adding this feature, you can watch our progress at this issue: https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/8

Thanks!
