### ISSUE TITLE
[Filter Products by Price]: Avoid using !important in styles

### ISSUE THREAD

**Issue by dashkevych** [woocommerce/woocommerce-gutenberg-products-block#6016]
## Describe the bug

Could you please avoid using `!important` in styles for WooCommerce blocks? 

Themes are responsible for appearance of a WordPress site. However, using `!important` in styles, makes it hard to override default styles of blocks provided by the plugin. As a result, it causes style issues and breaks overall design of a WordPress theme.

## Screenshots

<img width="1681" alt="input-css" src="https://user-images.githubusercontent.com/3655965/157331931-1ad83fef-fa4b-4582-8a35-28a8d77e3693.png">

### WordPress (please complete the following information):

-   Core version: 6.0-alpha-52823
-   WooCommerce version:  6.3.0
-   WooCommerce Blocks version: 7.1.0

**Comment by frontdevde** [comment]
Thank you for the feedback! The team aims to avoid using `!important` where possible. We might revisit this specific instance to see if there's a solution that covers all cases without the use of `!important`.
