### ISSUE TITLE
Mini Cart: Edit template part can be more intuitive

### ISSUE THREAD

**Issue by dinhtungdu** [woocommerce/woocommerce-gutenberg-products-block#6027]
## Is your feature request related to a problem? Please describe.
Currently, the template editor panel is quite vague. We should make it more explicit and clear for all users.

## Describe the solution you'd like
Adding help text or description explain the usage of the template part edit link: To edit the drawer or flyout content of the Mini Cart.

## Additional context
Thank @nerrad for raising this in the Monthly Walkthrough!

**Comment by nerrad** [comment]
Closing in favor of #6041 which has suggested text for this area. Thanks for getting the issue written up so quickly though Tung!
