### ISSUE TITLE
Mini Cart Template Part description 

### ISSUE THREAD

**Issue by vivialice** [woocommerce/woocommerce-gutenberg-products-block#6041]
## Is your feature request related to a problem? Please describe.

As brought up in this [P2 post and comment](https://wp.me/pdnLyh-AV#comment-390), the template part link currently isn't very understandable. 

<img width="576" alt="Screenshot 2022-03-10 at 17 24 24" src="https://user-images.githubusercontent.com/9888201/157720388-c9d7982e-eb86-4a8a-8a97-184479d62d09.png">

## Describe the solution you'd like

I have mocked up a change here: 

![Template link](https://user-images.githubusercontent.com/9888201/157725285-784a1ad0-c3fe-4983-a123-3167484a169d.png)

**Comment by nerrad** [comment]
If we keep the word "template" in the description, we should probably be more precise and refer to "template part" since that's what it is.

**Comment by vivialice** [comment]
Fair point. We can change the CTA to "Edit mini cart template part": 

![Template link](https://user-images.githubusercontent.com/9888201/157850174-44589995-93c0-4265-94b7-1cf4a90182b2.png)
