### ISSUE TITLE
Phone label not translated in Checkout block in the frontend

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#6044]
Phone field doesn't show translations in the frontend of the Checkout block.

## To reproduce

1. Set your store language to any different from English (I tried `Spanish` and `Catalan`).
2. Visit the Checkout block in the frontend.
3. Notice `Phone` or `Phone (optional)` labels are not localized.
4. If you edit the block, you will notice they are correctly localized in the editor.

## Expected behavior

`Phone` should be localized to the correct locale.

## Screenshots

![imatge](https://user-images.githubusercontent.com/3616980/157851556-177059e3-af55-46ac-9ad5-378ae3c0db4b.png)

**Comment by tarhi-saad** [comment]
Hi @Aljullu! Thank you for opening this issue. 

I followed the steps mentioned above to reproduce the bug, and it seems to be fixed:

<img width="701" alt="image" src="https://user-images.githubusercontent.com/14235870/158827444-769aa46e-7002-42f8-9618-0e12bddb0f2d.png">

I tested with `Spanish` and `Catalan`. I think this [comment](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/6036#issuecomment-1065134631) explains the fix:

> This is not the path to the build file, so the md5 hash of the file path does not match meaning this translation is never loaded. It should fix itself once the paths and translations are updated. Maybe :)
