### ISSUE TITLE
PayPal Payments instead of PayPal Standard

### ISSUE THREAD

**Issue by DarianDev** [woocommerce/woocommerce-gutenberg-products-block#6051]
## Is your feature request related to a problem? Please describe.

woocommerce blocks supports only paypal standard for checkout, unfortunately the paypal standard plugin in woocommerce is no longer developed, woocommerce therefore recommends to use paypal payments plugin. because paypal standards is a security risk. unfortunately woocommerce blocks does not support the paypal payments gateway, please update and fix this problem as soon as possible.

## Describe the solution you'd like
Add PayPal Payments support.

**Comment by tarhi-saad** [comment]
Hi there @DarianDev 👋

Thanks for informing us that Paypal Payments isn’t working with the Checkout and Cart blocks. These blocks are still in early access (via the feature plugin), and it’s expected that some existing Woo Extensions that integrate with the current checkout flow in WooCommerce core will not work with the blocks.

Currently, it’s up to payment method extension developers to add support for the new checkout flow offered via the cart and checkout blocks. We have some [documentation on that here](https://href.li/?https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/extensibility/payment-method-integration.md), and you can also point them to this [post](https://href.li/?https://developer.woocommerce.com/2021/03/15/integrating-your-payment-method-with-cart-and-checkout-blocks/).

Your best course of action right now if you are using a payment method that isn’t working with the blocks is to notify the developer of the extension and ask if they can add support.

Until then, you can keep on top of the [status of the Cart & Checkout Blocks in this documentation](https://href.li/?https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/).
