### ISSUE TITLE
Featured Category Block height can't be adjusted

### ISSUE THREAD

**Issue by shrutimoorthy** [woocommerce/woocommerce-gutenberg-products-block#6061]
## Describe the bug

Featured Category Block height can't be adjusted to something smaller than the default height. It is currently locked to a min-height of 500px with inline CSS. 

## To reproduce

1. Go to a new Page.
2. Add a Featured Category Block. 
3. Try to adjust the height of the block to something smaller than 500px. 

## Expected behavior

Featured Category Block height should be adjustable to something smaller than the default height. 

### WordPress:

-   Core version: 5.9.2
-   Gutenberg version (if installed): 12.7.2
-   WooCommerce version: 6.3.1
-   WooCommerce Blocks version: 6.9.0
-   Site language: English
-   Any other plugins installed: Not applicable

### Desktop:

-   OS: Not applicable
-   Browser: Not applicable
-   Version: Not applicable

## Additional context:

Can't be adjusted using CSS either due to inline CSS in the block's code.

**Comment by alexflorisca** [comment]
Thanks for this @shrutimoorthy. At the minimum, this should be overwritable with css. I've added it to our backlog.
