### ISSUE TITLE
Error activating the plugin with WooCommerce Payments active

### ISSUE THREAD

**Issue by cesarcosta99** [woocommerce/woocommerce-gutenberg-products-block#6063]
## Describe the bug

On a new WP installation, if we have WooCommerce Payments and try to install and activate the latest version of WooCommerce Blocks (7.2.0), some errors are thrown. I suspect it may be happening if we update Blocks from previous versions as well.

## To reproduce

1. Create a Jurassic Ninja site with WooCommerce and WooCommerce Payments.
2. Go through the initial WooCommerce setup.
3. Install WooCommerce Blocks from the Plugins page.
4. Try to activate it and you should see the errors.

## Expected behavior

We don't see errors when activating Blocks or having both WooCommerce Payments and WooCommerce Blocks active.

## Screenshots

<img width="1762" alt="image" src="https://user-images.githubusercontent.com/10233985/158907112-e6d95a1e-7722-4a6c-b76b-8cadb5b254e3.png">

### WordPress (please complete the following information):

-   Core version: 5.9.2
-   WooCommerce version: 6.3.1
-   WooCommerce Blocks version: 7.2.0
-   Site language: English
-   WooCommerce Payments: 3.8.2

**Comment by senadir** [comment]
Hey! this is not an error, but a deprecation warning. We recently made Store API public and stable, and alongside, renamed some classes to better reflect the new position.
