### ISSUE TITLE
Coupons applied in cart, cannot be removed

### ISSUE THREAD

**Issue by PanosSynetos** [woocommerce/woocommerce-gutenberg-products-block#6066]
## Describe the bug

When applying a coupon in the cart block, the coupon is applied but cannot be removed.

## To reproduce

1. Create a coupon and add a product to the cart
2. Visit a page that contains the cart block
3. Apply the coupon
4. See that the coupon is applied 
5. The `pill` to remove the coupon does not exist
6. Reload the page, the `pill` will be shown

## Expected behavior

The `pill` to remove the coupon should be visible, the moment the coupon is applied. The checkout block works as expected

## Screenshots

https://user-images.githubusercontent.com/2484390/159268676-2aff53b0-a9c0-4a9f-877a-54d8f559f3e5.mp4

### WordPress (please complete the following information):

-   Core version: 5.9.2
-   WooCommerce version: 6.3.1
-   WooCommerce Blocks version: 7.3.0-dev (built from trunk)

### Desktop (please complete the following information):

-   OS: macOS 12.2.1
-   Browser: Chrome v99

**Comment by nielslange** [comment]
@PanosSynetos It seems that @opr fixed this issue in #6102. Can you verify that the problem, you reported, has been fixed?

**Comment by PanosSynetos** [comment]
@nielslange yes, it's fixed - I set up a test site with 7.3.0 and I can see the applied coupon.
