### ISSUE TITLE
Check that Jest supports TS

### ISSUE THREAD

**Issue by gigitux** [woocommerce/woocommerce-gutenberg-products-block#6067]
To be consistent with our TypeScript migration, we should start to write tests in Typescript. 
We need to check that the current Jest configuration supports Typescript. If not, we have to update it.

**Comment by tomasztunik** [comment]
I'm in the process of updating us to latest WordPress/scripts - will check while at that 👍

**Comment by tomasztunik** [comment]
It's already supported and was in use already for handful of tests ie:
`assets/js/blocks-registry/payment-methods/test/payment-method-config.tsx` and couple more, also some of the test utils are already using typescript. 

This is done via Babel transpilation so no compilation time typechecking unless we went with ts-jest but don't think this is critical before going 100% ts.

**Comment by gigitux** [comment]
Did you check e2e tests?

**Comment by tomasztunik** [comment]
it's using the same jest setup so should work but will double check, if they work will close this.
