### ISSUE TITLE
Track performance of cart and checkout blocks

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#6073]
Currently, we’re not tracking the performance of the cart and checkout blocks. This makes not impossible to tell if a change affects the performance in any way. During pca54o-2VH-p2, @ralucaStan, @tarunvijwani, @opr and I looked into options to track the performance. 

### Cart
- General loading times
	- serverResponse (Average time to server response)
	- firstPaint (Average time to first paint)
	- domContentLoaded (Average time to DOM content load)
	- loaded (Average time to load)
	- firstContentfulPaint (Average time to first contentful paint)
	- firstBlock (Average time to first block)
- Coupon loading time
- Shipping calculator & options time
- Quantity update time / product removal time

### Checkout
- General loading time
	- serverResponse (Average time to server response)
	- firstPaint (Average time to first paint)
	- domContentLoaded (Average time to DOM content load)
	- loaded (Average time to load)
	- firstContentfulPaint (Average time to first contentful paint)
	- firstBlock (Average time to first block)
- Coupon loading time
- Address form performance (free text and select)
- Use same address for billing performance
- Add a note to your order performance
- Shipping option loading time
- Payment option loading time
- Placing order time

## Additional information
This issue is inspired by the performance tracking of Gutenberg. The main files, regarding performance tracking, can be found on https://github.com/WordPress/gutenberg/blob/trunk/packages/e2e-tests/config/performance-reporter.js and https://github.com/WordPress/gutenberg/blob/trunk/bin/log-perormance-results.js.

**Comment by sunyatasattva** [comment]
Hey @nielslange! Regarding my mention at the meetup to add a way to wrap everything in performance tracking, it would require a paradigm shift first (which is the same that Gutenberg is gonna go through). I'll elaborate in my P2 post and attach the presentation, but basically, currently it's not just plug and play: it's a refactor that then would give us the freedom to do many plug and play things.

I'm not sure how these tests are structured, but at this point I would suggest a few possible solutions:

1. Create a performance wrapper for your business-logic utility functions. That will also have the side-effect that code will need to be re-organized to separate the concerns better if it is not already.
2. Create a currying over the `it` function.

The second one has the advantage that once you do it, you can basically search and replace any `it` with your new function and it will work out easily. It's not very scalable though. The first solution has the pro of re-organizing the code and actually make it future proof for when we move to the next stage. So it will be making the work of anybody who'll be doing the refactor much easier.

**Comment by nielslange** [comment]
Thanks for sharing your thoughts on wrapping the e2e tests with performance tracking. I'm excited to see your investigation in the future. I understand that you need more time on this area, so @opr and I will go ahead and proceed with implementing the simple performance tracking for now. 😀

**Comment by alexflorisca** [comment]
@opr (mainly), @nielslange and I did some work on this [here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/6119)

**Comment by nielslange** [comment]
Closing this due to pca54o-6Dz-p2
