### ISSUE TITLE
Infinite loop when adding `billing.currency` to `useEffect` dependencies array and using `onPaymentProcessing`

### ISSUE THREAD

**Issue by cristiancalara** [woocommerce/woocommerce-gutenberg-products-block#6077]
## Describe the bug

I'm trying to add a new Payment Method Integration for the Checkout Block. I'm following the guide here https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/extensibility/payment-method-integration.md and using https://github.com/woocommerce/woocommerce-gateway-stripe/commit/326fbea as a reference. 

Adding `billing.currency` dependency to the `useEffect` inside the `usePaymentProcessing` hook causes an infinite re-rendering loop - https://github.com/woocommerce/woocommerce-gateway-stripe/commit/326fbea#diff-1d7fade42ff239149638906d4fc9f40add219fddfca4c560778cb7556e51a139R155 (basically below this line)

The infinite loop is caused by the `onPaymentProcessing` call https://github.com/woocommerce/woocommerce-gateway-stripe/commit/326fbea#diff-1d7fade42ff239149638906d4fc9f40add219fddfca4c560778cb7556e51a139R149. The callback does not matter (tried empty function, still caused an infinite loop).

I need the information in the `billing.currency` in that hook to send to the integration provider. Any help would be appreciated :)

## To reproduce

Add `billing.currency` dependency to the `useEffect` inside the `usePaymentProcessing` hook causes an infinite re-rendering loop - https://github.com/woocommerce/woocommerce-gateway-stripe/commit/326fbea#diff-1d7fade42ff239149638906d4fc9f40add219fddfca4c560778cb7556e51a139R155 (basically below this line)

## Expected behavior

To not have an infinite loop. Or maybe any other way in which I could get the `billing.currency` information. Or maybe document which things can be safely added as dependencies and which cannot be added when using the `onPaymentProcessing` callback inside a useEffect hook

### WordPress (please complete the following information):

-   Core version: 5.9.2
-   Gutenberg version (if installed): not installed
-   WooCommerce version: 6.3.1
-   WooCommerce Blocks version: 7.2.0
-   Site language: en
-   Any other plugins installed: https://share.getcloudapp.com/L1uR7vne

### Desktop (please complete the following information):

-   OS: macOS
-   Browser: chrome (but tested safari and firefox as well and it still happens)

**Comment by tarunvijwani** [comment]
Hello @cristiancalara! Thanks for the report, I'm adding this to our backlog.

**Comment by opr** [comment]
Hey @cristiancalara - I am sorry I didn't see this issue sooner - Can you try getting the currency from the `wc/store/cart` data store?

It would be possible doing it like this

```js
import { select } from '@wordpress/data';

const billingCurrency = select( 'wc/store/cart' ).getCartTotals()?.currency_code;
```

or if inside a React component, you could do it like this:

```js
import { useSelect } from '@wordpress/data';

const billingCurrency = useSelect( ( select ) => {
  const store = select( 'wc/store/cart' );
  return store.getCartTotals()?.currency_code;
} );
```

Let me know how it goes!

**Comment by ralucaStan** [comment]
@cristiancalara I will be closing this issue as there was no follow-up. Feel free to reopen or get in touch if you have other problems. Thank you for your contribution.
