### ISSUE TITLE
Feature request: option to select and insert “woocommerce single product (legacy template)” as a block into any template

### ISSUE THREAD

**Issue by edequalsawesome** [woocommerce/woocommerce-gutenberg-products-block#6110]
## Is your feature request related to a problem? Please describe.

The single product template gets created once WooCommerce is installed and there is a legacy template added into the template. If a user was to accidentally delete their single product template or if they wanted to create a new template that contains a single product block using FSE, there is no option to insert the WooCommerce single product legacy template.

After deleting that block from a template, selecting the "clear customizations" option also does not bring back the WooCommerce legacy block.

<img width="877" alt="woo-legacy-block" src="https://user-images.githubusercontent.com/4000628/159794160-a7d4ca2f-5c86-4582-9b18-9fece6000e19.png">

## Describe the solution you'd like

It would be great to have it available on the list of block so that users can reinsert it as required. User would be able to navigate to add block and select "single product (legacy template) to insert it.

## Additional context

Original request: https://github.com/Automattic/wp-calypso/issues/62062

**Comment by tomasztunik** [comment]
The clear customisations should definitely be bringing it back. 

I have just tried on the latest trunk version and on one shipped with WooCommerce 6.3.1 and it does restore when we select clear customisations from templates list.

@edequalsawesome  - Can you confirm it doesn't work for you and if so provide more details about your setup?

We'll look into using https://developer.wordpress.org/block-editor/reference-guides/block-api/block-templates/#individual-block-locking to prevent removal of the block.

**Comment by Aljullu** [comment]
Heads-up that this was fixed in #6539.
