### ISSUE TITLE
Newest Products Block - Product rating is hidden not works on front end

### ISSUE THREAD

**Issue by zoda61** [woocommerce/woocommerce-gutenberg-products-block#612]
**Describe the bug**
In the 'Newest Products Block' - 'Product rating' (is hidden) not works on front end but looks right in the block editor visually.

**To Reproduce**
Tested on newly installed WP 5.2.1,  Woocommerce 3.6.4 and Woocommerce Blocks 2.1.0 and standard theme Twenty Sixteen 2.0 after we have discovered the bug in live development with other themes. 
 
**WordPress (please complete the following information):**

* Core version: 5.2.1
* Gutenberg version (if installed): 5.8.0
* WooCommerce version: 3.6.4
* WooCommerce Blocks version: 2.1.0
* Site language: swedish
* Any other plugins installed: no

Tested with different web browsers on both windows 7, 10 and android, same result.

**Comment by ryelle** [comment]
Thanks for reporting this @zoda61 – we've changed how the content controls work for the next version, so this should be fixed once WooCommerce Blocks 2.2 is released (this week).
