### ISSUE TITLE
Provide a system for filter blocks to know whether they need to render or not

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#6140]
In a Classic theme, if you add a filter widget to the sidebar then it will render on the Shop page where products are visible but it won't load on other pages (e.g. homepage). However, with filter blocks, they are always displayed even if they can't interact with anything.

We need to make filter blocks aware of the context they are rendered on, so are only visible if there is something filterable (All Products block or a PHP grid template). That would allow us to replace filter widgets with filter blocks in Classic themes.

In order to accomplish this, we might want to use [this util](https://github.com/woocommerce/woocommerce/blob/2215c9ab3ee7759effde7a93ea01a95654b56b60/plugins/woocommerce/includes/blocks/class-wc-blocks-utils.php#L69) from WC core to detect if there is an All Products block or a Product Catalog template in the page.

**Comment by tjcafferkey** [comment]
@Aljullu we could use a similar technique [here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/src/BlockTypes/AllProducts.php#L22-L31) (and in the [ClassicTemplate.php](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/src/BlockTypes/ClassicTemplate.php) file) as we have already used [here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/src/BlockTypes/ClassicTemplate.php#L65-L69) to pass a `has_block_filterable_products` value to the frontend for the filter components to read.

The only problem is we also we will need this value to be passed on Core PHP templates for themes such as Storefront that still render the PHP files directly.

Do you think this is an idea worth pursuing? If so, have you any suggestions on how/where we would pass the `has_block_filterable_products` value on the core PHP templates as mentioned above?

**Comment by Aljullu** [comment]
> Do you think this is an idea worth pursuing?

I do think so, this would allow us to retire the filter widgets, so we can concentrate all efforts into the blocks and pave the way for migration from classic themes to block themes.

> If so, have you any suggestions on how/where we would pass the `has_block_filterable_products` value on the core PHP templates as mentioned above?

I wonder if the filter widgets could use the technique you suggested, but doing [the same checks as widget filters](https://github.com/woocommerce/woocommerce/blob/19e57a437738ebae732a2a69d698373564f88da3/plugins/woocommerce/includes/widgets/class-wc-widget-rating-filter.php#L90-L96). Is that something that could work?
