### ISSUE TITLE
Deprecate old filter widgets in favor of filter blocks

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#6144]
Once we have filter blocks that can interact with the PHP templates, we will be able to deprecate the old filter widgets, that means:

* allowing to insert filter blocks into the widgets screen
* allowing transforms from widgets to the blocks
* hiding the widgets from the inserter

This task should only be done once all other ones in the epic have completed.

**Comment by tjcafferkey** [comment]
@Aljullu have you any ideas on how we can deprecate the filter widgets for sites that are already using them? There are two approaches I can think of:

1. We keep them in place, but remove them from the inserter so once removed they cannot be re-added. Also no new sites will be able to add them.
2. We find a way to replace them automatically in sites. I don't think this is ideal seeing as we don't want to be amending sites on behalf of our users.

Also, with option 1 would we want to add some deprecation messaging to the widgets we're looking to deprecate to encourage users to replace them with the filter blocks? cc @vivialice

**Comment by Aljullu** [comment]
I think what WordPress is doing is option 1. Old widgets can't be added anymore, but they aren't automatically migrating widgets to blocks. Instead, there is a system that requires user interaction to transform widgets to blocks (see https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/4292).

So to answer your questions:

- I would go with option 1. Making sure we add transforms like in #4292.
- I wouldn't add a deprecation message.
