### ISSUE TITLE
TypeError: wp.i18n is undefined in new Mini Cart Block

### ISSUE THREAD

**Issue by maeseoki** [woocommerce/woocommerce-gutenberg-products-block#6153]
## Describe the bug
With the new MiniCart Block, its inline JavScript for translation purposes is loaded before wp object and i18n object, so a few TypeError are thrown and no translation is applied.

wp.i18n.setLocaleData( localeData, domain )

## To reproduce

1. Go to **Settings -> General** and change the language of the site to any language other than English (FYI I'm using Spanish)
2. Now go to **Appearance -> Widgets** and add **Mini Cart** widget to any Widget Area
3. Go to any page containing that Widget Area and see error in browser console

## Expected behavior

Widget string to be translated

### WordPress:

-   Core version: 5.9.2
-   WooCommerce version: 6.3.1
-   WooCommerce Blocks version: 7.3.0
-   Site language: Spanish
-   Any other plugins installed: None

### Desktop:

-   OS: Windows
-   Browser Firefox, Chrome

**Comment by gigitux** [comment]
Hello @maeseoki 

Thanks for reporting this issue. I'm able to reproduce the issue. We will work for fixing the issue
