### ISSUE TITLE
Product Attributes API not export slug but taxonomy

### ISSUE THREAD

**Issue by whywilson** [woocommerce/woocommerce-gutenberg-products-block#6168]
When accessing the Product Attributes API, it always returns the `taxonomy` instead of `slug`.
But the example shows it should be the `slug`.
Is that a bug or a new definition?

**Comment by gigitux** [comment]
Hi @whywilson, thanks a lot for reporting this!

We will investigate and we'll let you know!

**Comment by senadir** [comment]
Thank you for brining this to our attention, Wilson!

The API originally returned `slug`, in an update a couple of years ago, we changed that so it returns `taxonomy` and we kept `slug` for actual terms, but failed to update the docs. https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/6272/ fixes that.
