### ISSUE TITLE
In-Cart Product Quantity Limited to 99

### ISSUE THREAD

**Issue by billrobbins** [woocommerce/woocommerce-gutenberg-products-block#6175]
## Describe the bug

While it's possible to adjust the quantities of items in the cart block, it isn't possible to set them higher than 99.  

## To reproduce

1. Add an item to the cart.
2. In the cart block, try to increase the quantity to a number larger than 99.
3. Notice that 99 is the largest number that will be accepted.

## Expected behavior

I expected to be able to use much larger numbers in the cart for the product quantity.  

The input has a max of 99 set:

```
<input class="wc-block-components-quantity-selector__input" type="number" step="1" min="1" max="99" aria-label="Quantity of Coffee in your cart." value="1">
```

### WordPress (please complete the following information):

-   Core version: 5.9.2
-   WooCommerce version: 6.3.1
-   WooCommerce Blocks version: 7.3.0
-   Site language: US English
-   Any other plugins installed:

### Desktop (please complete the following information):

-   OS: macOS
-   Browser: Chrome
-   Version:  99.0.4844.84

## Additional context

First reported in the forums: https://wordpress.org/support/topic/woocommerce-blocks-cart-quantity-selector-set-to-max99/

**Comment by HuGoSm1th** [comment]
Hi,

Any progress with this?

**Comment by tarunvijwani** [comment]
Hello @billrobbins! Thanks for the report. I'm adding this to our backlog.

**Comment by HuGoSm1th** [comment]
Hi,

I have found the source of this nonsense here:
woo-gutenberg-products-block/src/StoreApi/Utilities/QuantityLimits.php line 143

`protected function get_product_quantity_limit( \WC_Product $product ) {
		$limits = [ 99 ];

		if ( $product->is_sold_individually() ) {
			$limits[] = 1;
		} elseif ( ! $product->backorders_allowed() ) {
			$limits[] = $this->get_remaining_stock( $product );
		}`

**Comment by tarunvijwani** [comment]
Thank you for the suggestion, @HuGoSm1th! 🙂

**Comment by senadir** [comment]
Thank you for shimming in @HuGoSm1th but I would appreciate a better language when shimming in with your opinion, as per our [code of conduct policy](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/.github/CODE_OF_CONDUCT.md) and remember that you're dealing with actual humans in an open source free project.

**Comment by HuGoSm1th** [comment]
> Thank you for shimming in @HuGoSm1th but I would appreciate a better language when shimming in with your opinion, as per our [code of conduct policy](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/.github/CODE_OF_CONDUCT.md) and remember that you're dealing with actual humans in an open source free project.

O well. You just broke point number 3 of your own rules. 
My intent was only to solve issue and help community.
