### ISSUE TITLE
Not all Cart & Checkout inner blocks render when migrating to inner blocks for Order Summary

### ISSUE THREAD

**Issue by ralucaStan** [woocommerce/woocommerce-gutenberg-products-block#6185]
## Describe the bug

When migrating to the Cart & Checkout blocks that have Order summary with inner blocks not all content is loaded for the Order summary.

See internal conversation p1649074270986619/1649068099.800419-slack-C8X6Q7XQU
## To reproduce

Steps to reproduce the behaviour:

1. Go to version v7.2.0
2. Build and add C & C blocks to pages
3. Check to see the content
4. Go to `git checkout trunk`
5. Build and see that some inner blocks are missing as follows:
**Cart**
- Order summary heading, Coupons & Taxes(?) inner blocks
**Checkout**
- Cart summary, Coupons & Taxes(?) inner blocks

## Expected behavior

All inner blocks should be rendered in the Order summary.

**Comment by senadir** [comment]
This would only apply to non forced blocks, other blocks which have `lock.remove: true` would show up fine.
