### ISSUE TITLE
Checkout Block does not appear for the Customer Payment Page

### ISSUE THREAD

**Issue by namiokuzono** [woocommerce/woocommerce-gutenberg-products-block#6187]
## Describe the bug

When WC Block for Checkout is set up, the Payment order page (customer payment page) still defaults to regular Checkout format. 

This could be an enhancement request; this may be by design. 

## To reproduce

- 1 Set up Cart/Checkout with WC Blocks
- 2 Manually create an order ; set your user account as customer ; add product ; click customer payment link 
- 3 The page does not look like it is properly formatted

## Expected behavior

It would be great to set up the WC Blocks even for the customer payment page

## Screenshots

Regular WC Block Checkout page: 

![https://d.pr/i/ZrfSEq](https://d.pr/i/ZrfSEq+)
Image link: https://d.pr/i/ZrfSEq

Customer payment page:

![https://d.pr/i/YXdCoU](https://d.pr/i/YXdCoU+)
Image link: https://d.pr/i/YXdCoU

### WordPress Environment ###

WC Version: 6.3.1
REST API Version: ✔ 6.3.1
WC Blocks Version: ✔ 7.3.0
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.2.1
Log Directory Writable: ✔
WP Version: 5.9.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.38 (Debian)
PHP Version: 7.3.31-1~deb10u1
PHP Post Max Size: 100 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.64.0
OpenSSL/1.1.1d

**Comment by namiokuzono** [comment]
Originally reported in 4921929-zen

**Comment by tarunvijwani** [comment]
Hello @namiokuzono!  We don't explicitly support that page at the moment. 

We may work on this later alongside some other pages. We make note of all feedback we receive and we also close issues with the feedback as active issues are used for bugs or feature/enhancements. It does not mean that we don’t note or review the feedback. Closed issues can also still be commented on. 🙂
