### ISSUE TITLE
`onPaymentProcessing` is called even though there are validation errors (missing email or name)

### ISSUE THREAD

**Issue by cristiancalara** [woocommerce/woocommerce-gutenberg-products-block#6193]
## Describe the bug
The `onPaymentProcessing` is called even though there are validation errors i.e. missing email & name, etc.

Reading the documentation at https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/extensibility/checkout-flow-and-events.md#onpaymentprocessing - it says that `This event emitter is fired when the payment method context status is PROCESSING and that status is set when the checkout status is PROCESSING, checkout hasError is false, checkout is not calculating, and the current payment status is not FINISHED.`. I would expect checkout hasError to be true when the email is missing?

## To reproduce
Add a callback to `eventRegistration.onPaymentProcessing` will be called when there are validation errors. 

```
const onSubmit = async () => {
	console.log('onSubmit');
};
const unsubscribeProcessing = onPaymentProcessing( onSubmit );
return () => {
	unsubscribeProcessing();
};
```
## Expected behavior

The callback not being called when there are validation errors.

## Screenshots

https://share.getcloudapp.com/eDu5gyvY - a few fields are errored out, but the onPaymentProcessing callback is still being called.

### WordPress (please complete the following information):

-   Core version: 5.9.2
-   Gutenberg version (if installed): not installed
-   WooCommerce version: 6.3.1
-   WooCommerce Blocks version: 7.3.0 (but tested 7.2.0)
-   Site language: en
-   Any other plugins installed: https://share.getcloudapp.com/L1uR7vne

### Desktop (please complete the following information):

-   OS: [e.g. macOS, Windows]
-   Browser [e.g. chrome, safari]
-   Version [e.g. 22]

### Smartphone (please complete the following information):

-   OS: macOS
-   Browser: chrome (but tested safari and firefox as well and it still happens)

## Additional context

I need the above as the payment method I'm implementing opens a modal and then returns a token for the transaction. I would like to avoid opening the modal if there are validation errors. If the above is not actually a bug - was wondering if the only way I should go about this is actually checking the billingData to see if the info is there?

**Comment by opr** [comment]
Hi, thanks for reporting this! I've made a note of this issue and added it to our backlog.

We're working on decoupling these contexts from our Cart and Checkout blocks, so this is something that may be fixed as a result of that work, as we continue to make progress with that, we'll check back on this bug.

Thanks again for reporting!

**Comment by cristiancalara** [comment]
Hey @opr - got back to this and tried a few things. Not sure if you maybe have any suggestions for any workaround? Or the only way to go here is to manually check the billing and shipping data arrays and just early return in the hook?

Any help would be appreciated, thanks! :)
