### ISSUE TITLE
Add an active state for the scope switcher

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce-gutenberg-products-block#62]
Scope switcher: https://cloudup.com/cGBCQLlRaFN

Let's make it clear which scope is currently active when switching, and disable it as a selection.

**Comment by tiagonoronha** [comment]
@jameskoster design? 

Or changing the color is enough?

**Comment by jameskoster** [comment]
This oughta do it;

![active](https://cldup.com/U8aLseXwVN-2000x2000.png)
