### ISSUE TITLE
Tidy up test utils functions

### ISSUE THREAD

**Issue by alexflorisca** [woocommerce/woocommerce-gutenberg-products-block#6205]
There are currently test utils living in a bunch of different places, and these could do with being organised a bit better. There are:

- `tests/e2e/utils.js`
- `tests/e2e/page-utils.js`
- `tests/utils/<loads!>`

All of these are e2e utils, so should live in `test/e2e/utils` folder and grouped a bit more logically. It would be useful to have a `tests/e2e/utils/index.js` that imports and exports utility functions from other more specific files.

**Comment by nielslange** [comment]
See also https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5893

**Comment by mikejolley** [comment]
Closing due to pca54o-6Dz-p2
