### ISSUE TITLE
Add more options to the Mini Cart block

### ISSUE THREAD

**Issue by bradhogan** [woocommerce/woocommerce-gutenberg-products-block#6207]
## Is your feature request related to a problem? Please describe.
Design is important and I'd love to be able to adjust a few styles with the Mini Cart.

## Describe the solution you'd like
The initial options I'd like to see when using the Mini Cart block would be:
- Change icon
- Hide cart amount
- Font should use theme font family (not Arial)

Thank you!

**Comment by frontdevde** [comment]
Hi @bradley2083, thanks for your suggestions!

> Change icon

We have talked about allowing icon changes on further iterations, it's on our list :) 
(Internal reference: slack-archives/C02FL3X7KR6/p1649425713389499)

> Hide cart amount

That's a good suggestion. I'll mark this issue as a `good first issue`.

**Comment by danielwrobert** [comment]
Closing the loop on this one:

- The icon has been updated in #6784.
- The ability to hide/show the price has been added in #6796.
- The font inheritance from the theme appears to already be the case. The `font-family` rule in the block is set to inherit and I can see the font changing when switching between themes. See the screenshots below for an example.

**Twenty Twenty-Two:**
![CleanShot 2022-08-05 at 15 19 00](https://user-images.githubusercontent.com/481776/183147093-554be33d-f0b5-4409-8803-110331675574.png)

**Dara:**
![CleanShot 2022-08-05 at 15 22 53](https://user-images.githubusercontent.com/481776/183147113-c3a34884-14d6-4fa4-ba64-237841d56a92.png)

With that, I'm going to go ahead and close this Issue out. Feel free to reopen if anything has been missed. Thanks!
