### ISSUE TITLE
Button block colors on product, cart and checkout not working

### ISSUE THREAD

**Issue by bradhogan** [woocommerce/woocommerce-gutenberg-products-block#6212]
## Describe the bug

Button colors if defined in the global styles > block seems to work when using the "All Products" block, but not when using the Cart or Checkout blocks. 

## To reproduce

1. Create a shop page and add the All Products block
2. Create a cart page and add the Cart block
3. Create a checkout page and add the Checkout block
4. Possibly add the Mini Cart to the header or something too (haven't checked if this color is working)
5. Go to Edit Site, click Styles, click Blocks, click Button block
6. Change button block background color to something else (#ff0000 for example so it's obvious)
7. Add product to cart and check cart and checkout pages (and mini cart)

## Expected behavior

Button colors should be consistent with the button block - whether that's the default colors defined in the theme or custom colors changed in the global styles.  

Also noteworthy is that the text-transform on the cart block button (proceed to checkout) and checkout block button (place order) do not use the theme's defined text-transform value.  

## Screenshots
<img width="464" alt="Screen Shot 2022-04-07 at 6 54 59 PM" src="https://user-images.githubusercontent.com/1781226/162342378-c549cd75-2341-4afc-92ca-2100eab14e39.png">
<img width="657" alt="Screen Shot 2022-04-07 at 6 55 07 PM" src="https://user-images.githubusercontent.com/1781226/162342393-fee37fc9-8703-4393-a3e6-4bd8ef9e7ef4.png">
<img width="768" alt="Screen Shot 2022-04-07 at 6 55 15 PM" src="https://user-images.githubusercontent.com/1781226/162342400-fd1bdbe9-ea56-4ea7-95d7-863c430d868f.png">

### WordPress (please complete the following information):

-   Core version: 5.9.3
-   Gutenberg version (if installed): 12.9.0
-   WooCommerce version: 6.3.1
-   WooCommerce Blocks version: 7.3.0
-   Site language: english
-   Any other plugins installed: no

### Desktop (please complete the following information):

-   OS: macOS
-   Browser chrome

Thank you!

**Comment by opr** [comment]
Hi @bradley2083, thanks for the report - I've replicated this issue and moved it into our backlog.
