### ISSUE TITLE
(Store Api) Attributes always empty in Get products

### ISSUE THREAD

**Issue by bw-flagship** [woocommerce/woocommerce-gutenberg-products-block#6220]
## Describe the bug

I use the store api for developing a headless shop.
I created an attribute (color) and assigned it to a product.
When getting the product via store-api, the attributes-array is always empty.
Filtering on the attribute via query parameters works (see screenshot), which proves that it's filled correctly.

## To reproduce

Create an attribute and map it to a product. Use wp-json/wc/store/products
Applies to wp-json/wc/store/products/123 as well.

## Expected behavior

The attribute should appear in the response body field "attributes".

## Screenshots

![2022-04-08_15-57-37](https://user-images.githubusercontent.com/89379862/162450920-89e5c6f8-4815-45c8-9baf-d90b5d50b8a1.png)

![2022-04-08_16-01-57](https://user-images.githubusercontent.com/89379862/162451719-c3a4809c-5dfd-462a-8e59-bd2390982233.png)

### WordPress (please complete the following information):

-   Core version: 5.9.3
-   WooCommerce version: 6.3.1
-   Site language: German
-   Any other plugins installed: WooCommerce PayPal Payments, WooCommerce Shipping and Tax, WooCommerce Payments

### Desktop (please complete the following information):

-   OS: macOS, but does not matter
-   No browser, Postman
-   Version [e.g. 22]

**Comment by danieldudzic** [comment]
Hi @bw-flagship,

Thank you for reporting this.

I was able to replicate the issue, and in my testing, it seems that enabling the "**Used for variations**" option causes "**Attributes**" to show up in the API.

![bug](https://user-images.githubusercontent.com/905781/162771252-553242d7-7245-4bb6-ae50-76f2f1a8fb58.jpg)

![Mozilla_Firefox](https://user-images.githubusercontent.com/905781/162771509-23711b5d-77ae-4b2b-b775-553c0053616c.jpg)

**Comment by opr** [comment]
Thank you for the report - another user mentioned this so we will close as a duplicate, and in favour of #6180. You may follow that issue for further updates. Thanks again.
