### ISSUE TITLE
Reviews Block Shows All Reviews and Not Just from Selected Category

### ISSUE THREAD

**Issue by billrobbins** [woocommerce/woocommerce-gutenberg-products-block#6222]
## Describe the bug

The reviews block allows the merchant to select which product categories' reviews should be displayed.  The preview in the block is correct but the front-end of the site shows all reviews regardless of the settings.  

## To reproduce

1. Create reviews for multiple products in different categories.
2. Add a reviews block to a page and select a category.
3. Notice that the preview of the block shows the correct reviews.
4. Publish the page.
5. Notice that all reviews are shown on the front end of the site.

## Expected behavior

I expected the front end of the site to only show reviews from the selected categories.

## Screenshots

Backend
![backend-reviews](https://user-images.githubusercontent.com/1138631/162497397-0f6a8d80-42ab-49e2-8e3e-e9f700eea991.png)

Front end
![frontend-reviews](https://user-images.githubusercontent.com/1138631/162497420-0f5676cb-be49-4c3b-b78a-fed069a6036c.png)

### WordPress (please complete the following information):

-   Core version: 5.9.3
-   WooCommerce version: 6.3.1
-   WooCommerce Blocks version: 7.3.0
-   Site language: US English
-   Any other plugins installed: WC + WooCommerce Payments

## Additional context

Mentioned in the forum: https://wordpress.org/support/topic/block-reviews-by-category-not-displaying-correctly/

**Comment by danieldudzic** [comment]
Tested and replicated

**Comment by albarin** [comment]
Same issue https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/6347
Fixed by https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/6358
