### ISSUE TITLE
Razorpay payment method is unavailable

### ISSUE THREAD

**Issue by arijitacf** [woocommerce/woocommerce-gutenberg-products-block#6223]
## What do you think is missing from the Cart & Checkout blocks?
The Razorpay payment method is missing and probably not supported by you Woocommerce blocks plugin. Please add this.

**Comment by nielslange** [comment]
Hi there @arijitacf  👋

Thanks for taking the time to make us aware that Razorpay isn't working with the Checkout and Cart blocks. These blocks are still in early access (via the feature plugin) and it's _expected_ that some existing payment methods will not work with the blocks.

Currently, it's up to payment method extension developers to add support for the new checkout flow offered via the cart and checkout blocks. We have some [documentation on that here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/extensibility/payment-method-integration.md) and will be publicizing this more in the coming months.

Your best course of action now if you are using a payment method that isn't working with the blocks is to notify the developer of the extension and ask if they can add support.

Until then, you can keep on top of the [status of the Cart & Checkout Blocks in this documentation](https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/).
