### ISSUE TITLE
Allow running e2e tests individually

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#6228]
In #6119, we added performance testing to this repo. To prevent that the performance tests run together with the e2e tests, we added the flags ` --testPathIgnorePatterns performance` to both the `test:e2e`, `test:e2e-dev` and `test:e2e-dev-watch` commands. Before we added these flags, we could run the entire test suite via `npm run test:e2e` and an individual test via `npm run test:e2e -- checkout-payments`. Since we added the flags, running an individual e2e test is no longer possible. 

This issue aims to ensure that we can run individual e2e tests again.

**Comment by dinhtungdu** [comment]
@nielslange I noticed the same issue with the recent update when I work on #6214 (I thought we updated `jest`). I solved that issue by using `-i` flag. For example, I can run Mini Cart translation tests only.

```
npm run test:e2e -- -t 'Translations' -i 'tests/e2e/specs/shopper/mini-cart.test.js'
```

Or just remove `-t` part if we need to run all tests in a file:

```
npm run test:e2e -- -i 'tests/e2e/specs/shopper/mini-cart.test.js'
```

We can also use `--runTestsByPath`
```
npm run test:e2e -- --runTestsByPath 'tests/e2e/specs/shopper/mini-cart.test.js'
```

**Comment by dinhtungdu** [comment]
Checking [the docs](https://jestjs.io/docs/27.4/cli), `-i` is an alias of `--runInBand`, which I think is an incorrect usage (but working !?) in our case.

`--runTestsByPath` is more explicit and easier to understand.

**Comment by nielslange** [comment]
While adding additional parameters might work, I found that approach rather error-prone. If I can choose between running 
```
npm run test:e2e -- -t 'Translations' -i 'tests/e2e/specs/shopper/mini-cart.test.js'
```
and running
```
npm run test:e2e -- mini-cart.test.js
```
and receiving the same result, I'll definitely run the later command. I believe that lowering the complexity of our codebase, frees up mental capacity.

Before #6119, running an individual command without additional parameters worked fine. I'd say, the only thing we missed when implementing #6119, was to create a separate config file for the performance tests. As mentioned in the PR description on #6230, that's what Gutenberg is doing as well. 

And example for improving commands can also been seen in your PR #5653, in which you added the command
```
"test:e2e-dev-watch": "npm run wp-env:config && cross-env NODE_CONFIG_DIR=tests/e2e/config wp-scripts test-e2e --config tests/e2e/config/jest.config.js --watch"
```
in addition to the existing command
```
"test:e2e-dev": "npm run wp-env:config && cross-env NODE_CONFIG_DIR=tests/e2e/config wp-scripts test-e2e --config tests/e2e/config/jest.config.js"
```

In this case, it would have been possible as well to simply add ` --watch` to the existing command. Yet, introducing an additional command, lowered the complexity of that command.
