### ISSUE TITLE
Check for House Number in Adress Field 

### ISSUE THREAD

**Issue by DarianDev** [woocommerce/woocommerce-gutenberg-products-block#6277]
## Is your feature request related to a problem? Please describe.
There is a problem that customers forget to enter their house number. It is very tedious to write to the individual customers and ask for the house number so that the mail can be delivered correctly. In the normal woocommerce checkout there is the possibility to check the address field for the presence of a number. i wish this function for woocommerce blocks. 

## Describe the solution you'd like
Set the order to be sent only if a house number is specified.

In my opinion, this is a must-have feature 

Best regards

**Comment by nielslange** [comment]
@DarianDev Thanks for reaching out regarding this issue. May I ask how you managed to check the address field for a house number when using the classic checkout page? By default, I do not see such functionality. The only thing I found for adding such a check, is by adding another field for the house number and making this field required, as described in https://www.businessbloomer.com/woocommerce-add-house-number-field-checkout/.

**Comment by DarianDev** [comment]
> @DarianDev Thanks for reaching out regarding this issue. May I ask how you managed to check the address field for a house number when using the classic checkout page? By default, I do not see such functionality. The only thing I found for adding such a check, is by adding another field for the house number and making this field required, as described in https://www.businessbloomer.com/woocommerce-add-house-number-field-checkout/.

with this code:

```php
add_action('woocommerce_checkout_process', 'address_field_validation', 10, 0);
function address_field_validation() {

    // The field value to check
    $post_value = $_POST['billing_address_1'];

    // If there is no number in this field value, stops the checkout process
    // and displays an error message.
    if ( $post_value && ! preg_match( '/[0-9]+/', $post_value ) ) {

        // The error message
        throw new Exception( sprintf( __( 'Het adresveld moet minimaal een huisnummer bevatten', 'woocommerce' ) ) );
    }
}
```

**Comment by nielslange** [comment]
Thanks for posting this code. I'll look into possible options and will get back to you once I have further information on this issue.

**Comment by nielslange** [comment]
@DarianDev Together with @opr, I looked into this case, and we've created the following code snippet, which checks if the shipping address contains a house number:

```php
add_action( 'woocommerce_store_api_checkout_update_order_from_request', function( WC_Order $order, $request ) {
	$shipping_address = $order->get_address('shipping')['address_1'];
	$matches = preg_match( '/\d+/', $shipping_address );
	if( ! $matches ) {
		throw new Exception( 'Your shipping address must contain a house number!' );
	}
}, 10, 2);
```

I rewrote this function so that it looks more like the function you posted in https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/6277#issuecomment-1102520253:

```php
add_action( 'woocommerce_store_api_checkout_update_order_from_request', 'woo_blocks_address_field_validation', 10, 2);
function woo_blocks_address_field_validation( WC_Order $order, $request ) {

    // The field value to check
    $post_value = $order->get_address('shipping')['address_1'];


    // If there is no number in this field value, stops the checkout process
    // and displays an error message.
    if ( $post_value && ! preg_match( '/[0-9]+/', $post_value ) ) {
    
        // The error message
        throw new Exception( 'Your shipping address must contain a house number!' );
    }
}
```

If you want to validate the billing address instead of the shipping address, simply change `$order->get_address('shipping')['address_1'];` to `$order->get_address('billing')['address_1'];`.

If you wish to validate both the shipping and the billing address, you can use the following code snippet:

```php
add_action( 'woocommerce_store_api_checkout_update_order_from_request', 'woo_blocks_address_field_validation', 10, 2);
function woo_blocks_address_field_validation( WC_Order $order, $request ) {
    $shipping_address = $order->get_address('shipping')['address_1'];
    $billing_address  = $order->get_address('billing')['address_1'];

    if ( $shipping_address && ! preg_match( '/[0-9]+/', $shipping_address ) ) {
        throw new Exception( 'Your shipping address must contain a house number!' );
    }

    if ( $billing_address && ! preg_match( '/[0-9]+/', $billing_address ) ) {
        throw new Exception( 'Your billing address must contain a house number!' );
    }
}
```

I'll close this issue for now, but if you have more questions, feel free to open it again.

**Comment by Zorast** [comment]
My Woocommerce 7.2.2 does implement this feature by itself
