### ISSUE TITLE
"Your store is looking great! Don't forget to continue personalizing it" note should link to Site Editor in block themes

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#6279]
We would like to make it easier for WooCommerce users to know how to customize their store. One option is to add a link in the onboarding so they discover the site editor.

## To reproduce

1. In a fresh install of WooCommerce with a block theme (ie: Twenty Twenty Two), go to WooCommerce > Home.
2. Finish the last step of the onboarding _Personalize my store_.
3. A note will appear with the text "Your store is looking great! Don't forget to continue personalizing it".
![imatge](https://user-images.githubusercontent.com/3616980/163974368-30287c0c-3790-4863-93a9-354984d04b77.png)
4. Notice there is no link to "continue personalizing it". :disappointed: 

## Expected behavior

If the store is using a block theme, "continue personalizing it" should link to the Site Editor.

## Links

Even though I opened this issue in WC Blocks repo because it's related to Store Editing, the change needs to be done in WC core repo.

* Line of the message: https://github.com/woocommerce/woocommerce/blob/85324ea2cf2cd1f1091fdd2c92c951b9074fc39c/plugins/woocommerce/src/Internal/Admin/Notes/CustomizingProductCatalog.php#L70
* Function to know if theme is a block theme: https://github.com/woocommerce/woocommerce/blob/85324ea2cf2cd1f1091fdd2c92c951b9074fc39c/plugins/woocommerce/includes/wc-conditional-functions.php#L506

**Comment by OpenSourceLasagna** [comment]
I would like to fix this. Would be nice if you could assigne me to it.

**Comment by Aljullu** [comment]
> I would like to fix this. Would be nice if you could assigne me to it.

Hi there @Paul0908, thanks for showing your interest on this! You can start working on this even if you are not assigned. When you have a PR ready, you can ping me and I can assign this issue to you.

Let me know if I can help in some way!
