### ISSUE TITLE
Checkout Page / Subscribe to newsletter / Mailchimp 

### ISSUE THREAD

**Issue by dlyrtns** [woocommerce/woocommerce-gutenberg-products-block#6284]
## What do you like about the Cart & Checkout blocks?
great work guys!
## What do you think is missing from the Cart & Checkout blocks?
it really would be great to have a checkbox (under the email address) to give people an opportunity to subscribe to newsletters and integrate this checkbox with Mailchimp

**Comment by nielslange** [comment]
Hello @dlyrtns 👋

Given that there are various newsletter services, such as MailChimp, MailerLite, HubSpot, etc., we don't plan to integrate a newsletter service directly into the Checkout block. Instead, the Checkout block should allow external developers to extend the Checkout block with their functionality.

As for MailChimp, when using the classic Checkout page, you could use the [Mailchimp for WooCommerce](https://wordpress.org/plugins/mailchimp-for-woocommerce/) plugin. We are aware, that this extension is currently not working with the Checkout and Cart blocks. These blocks are still in early access (via the feature plugin) and it’s expected that some existing Woo Extensions that integrate with the current checkout flow in WooCommerce core will not work with the blocks.

We’re currently working on adding extensibility for the blocks, so extensions have a way to make sure they integrate with the new flows being developed. Once that is done, we’ll have docs prepared and will be reaching out to Woo Extension developers to help them with getting their extensions integrated.

There is already [some documentation available here](https://href.li/?https://github.com/woocommerce/woocommerce-gutenberg-products-block/tree/trunk/docs/extensibility) that you could share with the developers of that extension now if you want to get this on their radar!

Until then, you can keep on top of the [status of the Cart & Checkout Blocks in this documentation](https://href.li/?https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/).

**Comment by thisissandip** [comment]
Hey @dlyrtns,

The MailChimp for WooCommerce is now compatible with the Cart and Checkout Blocks.

The minimum requirements are:

> WooCommerce Blocks 8.0.0+
Mailchimp for WooCommerce 2.7+

You can read and find other compatible extensions with Cart & Checkout blocks here: https://woocommerce.com/document/cart-checkout-blocks-support-status/#section-5

Should you have any questions, feel free to reach out to us and we will be happy to assist you! 🙂
