### ISSUE TITLE
Add paging features to Product Attributes API

### ISSUE THREAD

**Issue by whywilson** [woocommerce/woocommerce-gutenberg-products-block#6285]
## Is your feature request related to a problem? Please describe.
No. It's the feature to unify the API.

## Describe the solution you'd like
We'd like to get all the product attributes in paging style.

## Describe alternatives you've considered
For example, we can also get the count of all attributes by **X-WP-Total** in the response header.

## Additional context
None. Currently, I can only the the attribute array and get the count by the array account.

**Comment by sunyatasattva** [comment]
Hello @whywilson! Thank you for suggesting this. Let me get it straight: currently, when querying `/wp-json/wc/store/v1/products/attributes` you get an array of objects including all your product attributes, but you would only like to know the total amount of them and not get the entire array and check its length?

If that's the case, why do you think adding pagination would be the best solution to this issue? Or am I getting something wrong and you would like to have pagination for some other use-case?

**Comment by whywilson** [comment]
> Hello @whywilson! Thank you for suggesting this. Let me get it straight: currently, when querying `/wp-json/wc/store/v1/products/attributes` you get an array of objects including all your product attributes, but you would only like to know the total amount of them and not get the entire array and check its length?
> 
> If that's the case, why do you think adding pagination would be the best solution to this issue? Or am I getting something wrong and you would like to have pagination for some other use-case?

Hi @sunyatasattva ,
Thank you for the reply.
Getting the total amounts of attributes is one of the use-case that I need.
If the attributes API also get the paging features, the standard of access Store API will be in one way to access.
I've not tested, but what if the attributes is over 100. The sites are growing, the attributes is becoming more and more complex.
Thank you in advance.
