### ISSUE TITLE
E2E flaky tests

### ISSUE THREAD

**Issue by dinhtungdu** [woocommerce/woocommerce-gutenberg-products-block#6286]
In https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/6280, I only updated the comment explaining the reason for the additional update commands. After 3 attempts, the tests are still failing. More interesting, failed test cases are different each time.

I collected failed tests reports here so we can fix them when time/resource allows.

- First attempt: https://github.com/woocommerce/woocommerce-gutenberg-products-block/actions/runs/2188917395/attempts/1 
  - [e2e-test-report.zip](https://github.com/woocommerce/woocommerce-gutenberg-products-block/files/8518345/e2e-test-report.zip)
- Second attempt: https://github.com/woocommerce/woocommerce-gutenberg-products-block/actions/runs/2188917395
  - [e2e-test-report (1).zip](https://github.com/woocommerce/woocommerce-gutenberg-products-block/files/8518344/e2e-test-report.1.zip)
- Third attempt: https://github.com/woocommerce/woocommerce-gutenberg-products-block/actions/runs/2188917395
  - [e2e-test-report (2).zip](https://github.com/woocommerce/woocommerce-gutenberg-products-block/files/8518343/e2e-test-report.2.zip)

**Comment by ralucaStan** [comment]
<img width="745" alt="Screenshot 2022-04-20 at 17 06 49" src="https://user-images.githubusercontent.com/1628454/164263559-2266cabb-d586-4fe7-8121-d21d2a4d4916.png">
This is another flaky test that appeared for people

**Comment by alexflorisca** [comment]
I've made some changes to addresses all of these in #6289. However I timeboxed the work to 1 hour so it may not fix everything and there is definitely more room for improvement. More specifically
- Make sure we `await page.waitForSelector()` after a page navigation or dom interactions (clicks, etc)
- Handle the time between a user click and a UI update without timeouts. I've used `page.waitForNetworkIdle` where the click generates a network request but there may be other cases.

**Comment by dinhtungdu** [comment]
<img width="573" alt="image" src="https://user-images.githubusercontent.com/5423135/164647771-88aaaf62-92fa-4bba-a097-0bd7b10f38df.png">

Another flaky test in my PR.

Full report: [e2e-with-gutenberg-test-report.zip](https://github.com/woocommerce/woocommerce-gutenberg-products-block/files/8538578/e2e-with-gutenberg-test-report.zip)

**Comment by ralucaStan** [comment]
<img width="818" alt="Screenshot 2022-04-22 at 16 32 56" src="https://user-images.githubusercontent.com/1628454/164736046-f25f9819-c440-406c-9ec6-1e3ddf6e9a94.png">

**Comment by alexflorisca** [comment]
The failure in the above two comments is the same test. @ralucaStan comment is after my commit to add line 90 > `await paeg.waitForSelector('.wp-list-table.users');` in an attempt to fix the test @dinhtungdu reported.

Keep recoding all test failures you see on this issue, and I will work on it some more during the porter week next week

**Comment by dinhtungdu** [comment]
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/5423135/165255619-63a4c772-1f83-4059-b09c-1f28034ca534.png">

Some new (and old) failed test cases found in #6317 ([log](https://github.com/woocommerce/woocommerce-gutenberg-products-block/runs/6171744268?check_suite_focus=true)) - [e2e-with-gutenberg-test-report.zip](https://github.com/woocommerce/woocommerce-gutenberg-products-block/files/8561232/e2e-with-gutenberg-test-report.1.zip)

**Comment by ralucaStan** [comment]
<img width="856" alt="Screenshot 2022-04-26 at 17 36 54" src="https://user-images.githubusercontent.com/1628454/165339274-28628b09-3009-403f-be01-859cdfd0dc02.png">

**Comment by dinhtungdu** [comment]
<img width="897" alt="image" src="https://user-images.githubusercontent.com/5423135/166848616-e39893ea-56a7-454b-aa1a-3a7785dee081.png">

PR: https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/6351
Log: https://github.com/woocommerce/woocommerce-gutenberg-products-block/runs/6299074244?check_suite_focus=true
Report: [e2e-test-report.zip](https://github.com/woocommerce/woocommerce-gutenberg-products-block/files/8628208/e2e-test-report.zip)

**Comment by dinhtungdu** [comment]
<img width="900" alt="image" src="https://user-images.githubusercontent.com/5423135/166848905-bec0ada7-2d25-4080-bc5c-d6eb49a3e59f.png">

Same errors for both WP latest and WP with Gutenberg plugin.
PR: https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/6366
Log: https://github.com/woocommerce/woocommerce-gutenberg-products-block/runs/6299081292?check_suite_focus=true
Reports: [e2e-with-gutenberg-test-report.zip](https://github.com/woocommerce/woocommerce-gutenberg-products-block/files/8628219/e2e-with-gutenberg-test-report.zip) - [e2e-test-report.zip](https://github.com/woocommerce/woocommerce-gutenberg-products-block/files/8628221/e2e-test-report.zip)

**Comment by alexflorisca** [comment]
Noooooo, just when you thought it was over!! @senadir is planning on looking at E2E tests over cooldown next week so maybe you could take a look at this as part of it?

**Comment by senadir** [comment]
I'm opening this again.

**Comment by ralucaStan** [comment]
Can this ticket be closed now @senadir ?

**Comment by dinhtungdu** [comment]
PR: https://github.com/woocommerce/woocommerce-blocks/pull/6452
Log: https://github.com/woocommerce/woocommerce-blocks/actions/runs/2532393688/attempts/1
Report: [e2e-with-gutenberg-test-report.zip](https://github.com/woocommerce/woocommerce-blocks/files/8946939/e2e-with-gutenberg-test-report.zip)

This is weird, 22 tests failed. Many of them are normally passed. The PR only changes the title and description of the custom templates which aren't listed in the theme.json file, which isn't covered in our current E2E tests.

**Comment by wavvves** [comment]
There might be a clue in [this commit](https://github.com/woocommerce/woocommerce-blocks/pull/5953/commits/6c4a70de69482c3160adb749728270364f3e4c86).
I picked up a really old PR, with passing tests, updated `package-lock.json` and tests passed. After that, I brought trunk into it, and tests began to fail, so looking into that merge commit might give us clues about this.
Unfortunately, it did bring a lot of changes, we might need a shovel 🙄.

![image](https://user-images.githubusercontent.com/17236129/176697910-b3263e4f-3906-49a8-a6ea-b4265da448aa.png)

**Comment by ralucaStan** [comment]
Closing this ticket as it's no longer relevant
