### ISSUE TITLE
Mini Cart inner blocks can be removed if unlocking them with the new WP 6.0 UI

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#6309]
## Describe the bug

WP 6.0 introduces a UI to lock/unlock blocks. That makes it possible to remove Mini Cart inner blocks if the user previously unlocks them.

## To reproduce

1. Install WordPress beta tester plugin and update to WP 6.0 beta 2.
2. Go to Appearance > Site Editor > Template Parts > Mini Cart.
3. Select the Mini Cart Products Table block and unlock it. Press <kbd>Del</kbd> or delete the block using the UI.
4. (For some reason, I needed to repeat step 3)
5. Notice the Mini Cart Products Table block could be removed.

https://user-images.githubusercontent.com/3616980/165116246-8917cac2-94e6-4399-8b50-5b9574c10aa8.mp4

## Expected behavior

It shouldn't be possible to remove the Mini Cart Products Tabl block.

## More info

Gutenberg seems to have introduced a `supports.__experimentalLock` flag that might be useful to prevent this (https://github.com/WordPress/gutenberg/pull/39568).

**Comment by dinhtungdu** [comment]
Note that `__experimentalLock` has been removed from Gutenberg. I can't find any occurrence with https://github.com/WordPress/gutenberg/commit/d5b06563e8acb3f4597731fe3faa4b860fb62a26.

Update: it was replaced by `lock` in https://github.com/WordPress/gutenberg/pull/40145.
