### ISSUE TITLE
Cart inner blocks can be removed if unlocking them with the new WP 6.0 UI

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#6311]
## Describe the bug

WP 6.0 introduces a UI to lock/unlock blocks. That makes it possible to remove Cart inner blocks if the user previously unlocks them.

## To reproduce

1. Install WordPress beta tester plugin and update to WP 6.0 beta 2.
2. Add the Cart block to a post or page.
3. Unlock the Cart Line Items, Cart Items block and Filled Cart blocks.
4. Select the Cart Items block.
5. Press <kbd>Del</kbd> or delete the block using the UI.
6. Notice the Cart Items block could be removed.

https://user-images.githubusercontent.com/3616980/165117738-ac2218da-50aa-4194-9789-0db82e104b2c.mp4

## Expected behavior

It shouldn't be possible to remove the Cart Items block.

## More info

Gutenberg seems to have introduced a `supports.__experimentalLock` flag that might be useful to prevent this (https://github.com/WordPress/gutenberg/pull/39568).

I couldn't reproduce it with the Checkout block, but might be worth testing.

**Comment by wavvves** [comment]
While testing this, a couple of other details came up:

- Removing the Cart Items block indeed does it on the edit view, but the Cart blocks page doesn't seem affected after updating
- Removing the Filled Cart block seems to re-add everything again


https://user-images.githubusercontent.com/17236129/166230768-32a10e4d-aacd-4f00-8f0a-0c6c0f6a3588.mov

**Comment by wavvves** [comment]
@ralucaStan can you have a quick look at this to sort out the priority?

**Comment by ralucaStan** [comment]
Thank you for bringing this to my attention, I've labeled this with priority high.

**Comment by senadir** [comment]
As @Aljullu said above, we should `__experimentalLock: false` to all of our non-removable core blocks, so every time there's a `lock.remove: true` we add `__experimentalLock: false` to its support object.

**Comment by ralucaStan** [comment]
I'm wondering if this issue also applies to the Checkout block as well, I think it should so let's confirm that and handle the fix there as well.

**Comment by dinhtungdu** [comment]
FYI, `__experimentalLock` was changed to `lock` in https://github.com/WordPress/gutenberg/pull/40145.

**Comment by senadir** [comment]
> I'm wondering if this issue also applies to the Checkout block as well, I think it should so let's confirm that and handle the fix there as well.

It should, it was probably not noticed due to our `useForcedLayout` hook.

**Comment by alexflorisca** [comment]
I replicated this briefly but then I couldn't replicate it again. For me, when I try to remove the block, it disappears briefly but re-appears (see video below)

https://user-images.githubusercontent.com/3966773/168641658-b9b9e9ee-0573-4c7e-af0e-d027151a6f02.mov

Either way, this makes sense and is good future proofing, so I've created a [PR](https://github.com/woocommerce/woocommerce-blocks/pull/6419) to add `supports: { lock: false }` to all the Cart and Checkout locked inner blocks.

**Comment by doza62** [comment]
I was testing the new Cart block. I'm noticing the padlock feature also prevents inner-blocks from moving around. I think this could be useful, given it won't break anything, which is; to allow users (even through an "experimental features toggle") to rearrange inner-blocks freely.

I'm stumbled upon this issue through a current project. I need to display the cart totals right under the products (cart line items) and show "Cart cross sells" at the second column instead. I've tried reverting manually #6419 to test this idea with no success. I thought I may ask here before committing to revert this change in a fork or just moving stuff with javascript/css or something like that.

Thanks in advance.

**Comment by ralucaStan** [comment]
Hey @R0dri, 
thank you for reaching out. The ability to move inner blocks is something that is on our list. 
Thank you for explaining your use case. I can't give you a time when we'll work on this but your feedback is important.
