### ISSUE TITLE
(WC 6.5 Beta) PHP 8 Fatal Error on Customize

### ISSUE THREAD

**Issue by tammullen** [woocommerce/woocommerce-gutenberg-products-block#6314]
Reporting on behalf of @gglobalstep

## Describe the bug

On sites running on PHP 8 a Fatal Error occurs when loading the Customizer

## To reproduce

1. Go to wp-admin on a site using PHP 8 with only WooCommerce Active
2. Click on Appearance > Customize
3. See fatal error

## Screenshots

https://user-images.githubusercontent.com/24649833/165139708-45323536-5cb5-4da3-9d77-89098f702322.mp4
```
 Fatal error: Uncaught Error: call_user_func_array(): Argument #1 ($callback) must be a valid callback, function "woocommerce_blocks_get_i18n_data_json" not found or invalid function name
in /srv/htdocs/__wp__/wp-includes/class-wp-hook.php on line 307

Call stack:

WP_Hook::apply_filters()
wp-includes/plugin.php:189
apply_filters()
wp-includes/l10n.php:1155
load_script_translations()
wp-includes/l10n.php:1122
load_script_textdomain()
wp-includes/class.wp-scripts.php:599
WP_Scripts::print_translations()
wp-includes/class.wp-scripts.php:314
WP_Scripts::do_item()
wp-includes/class.wp-dependencies.php:136
WP_Dependencies::do_items()
wp-includes/class.wp-scripts.php:660
WP_Scripts::do_head_items()
wp-includes/script-loader.php:1954
print_head_scripts()
wp-includes/class-wp-hook.php:307
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:331
WP_Hook::do_action()
wp-includes/plugin.php:474
do_action()
wp-includes/class-wp-customize-widgets.php:685
WP_Customize_Widgets::print_scripts()
wp-includes/class-wp-hook.php:307
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:331
WP_Hook::do_action()
wp-includes/plugin.php:474
do_action()
wp-admin/customize.php:174
```

### WordPress (please complete the following information):

-   Core version: 5.9
-   WooCommerce version: 6.5.0 Beta 1
-   WooCommerce Blocks version: 7.4.1 (Bundled with WC)
-   Site language: English Default
-   Any other plugins installed: No

**Comment by rodelgc** [comment]
I'm able to reproduce this fatal error on JN and Atomic ephemeral sites using PHP 8. I can confirm that it's not happening on PHP 7.4.
