### ISSUE TITLE
Mini Cart block is not available from the Edit template screen

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#6342]
When editing a template from the Edit template feature in the post/page editor, the Mini Cart block is not available.

## To reproduce

1. From wp-admin, go to Pages and edit one of your pages.
2. In the _Page_ sidebar, edit the template:

<img src="https://user-images.githubusercontent.com/3616980/165728750-2d1863e7-b268-4074-9d4d-fdd7b97d4e88.png" width="288" alt=""/>

3. Notice the Mini Cart block is not available in the inserter (and if it was already in your header, an error is shown):
 
![imatge](https://user-images.githubusercontent.com/3616980/165729300-d9f5f394-4585-4ffd-9494-c9962cd7a0e1.png)

## Expected behavior

It should be possible to insert the Mini Cart block from the template editor.

**Comment by Aljullu** [comment]
I wonder if we should revert the changes introduced in #5653. Thoughts @dinhtungdu @gigitux?

We might also take the chance to experimental with the new API introduced in WP 6.0 to filter allowed blocks based on the context: https://github.com/WordPress/gutenberg/issues/28517#issuecomment-1070239810.

**Comment by gigitux** [comment]
Nice shortcut for editing template! 

> I wonder if we should revert the changes introduced in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5653. Thoughts @dinhtungdu @gigitux?
We might also take the chance to experimental with the new API introduced in WP 6.0 to filter allowed blocks based on the context: https://github.com/WordPress/gutenberg/issues/28517#issuecomment-1070239810.


I agree with you! 👍

**Comment by dinhtungdu** [comment]
> I wonder if we should revert the changes introduced in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5653.

Look like it's the way to go. `$pagenow` is not efficient when the Template Editor is loaded inside Block Editor.

**Comment by dinhtungdu** [comment]
> We might also take the chance to experimental with the new API introduced in WP 6.0 to filter allowed blocks based on the context: https://github.com/WordPress/gutenberg/issues/28517#issuecomment-1070239810.

@Aljullu I tested using `allowed_block_types_all`, the filter is called when the post/page edit screen loads initially. But when editing the template from the Setting sidebar, the filter isn't called. I tested with both Core versions 5.9.3 and 6.0 beta.

**Comment by Aljullu** [comment]
Oh, too bad. Thanks for testing, @dinhtungdu! I wonder if we should comment in that issue or open a new one so GB devs are aware of this limitation?

**Comment by dinhtungdu** [comment]
> I wonder if we should comment in that issue or open a new one so GB devs are aware of this limitation?

Sure thing! I will open an issue there for better visibility.

**Comment by dinhtungdu** [comment]
> Sure thing! I will open an issue there for better visibility.

Opened https://github.com/WordPress/gutenberg/issues/40780.
