### ISSUE TITLE
Product Categories: Show children of current category.

### ISSUE THREAD

**Issue by tjcafferkey** [woocommerce/woocommerce-gutenberg-products-block#6346]
## Is your feature request related to a problem? Please describe.
The classic widget which this block has replaced had the option to display only the children of the current category. The Product Categories block does not have this functionality. Since this is supposed to be a replacement it makes sense to strive for parity between the two.

## Describe the solution you'd like
Add an option to the Product Categories block so that when it is used as a widget, merchants can select an option to show only children of the current category the user is on.

| Classic Widget | Current Block |
| --- | ----------- |
| ![image (2)](https://user-images.githubusercontent.com/8639742/165924930-652dc3e2-f2e1-41b4-95ec-49cd8c102339.png) | ![Screenshot 2022-04-29 at 11 06 06](https://user-images.githubusercontent.com/8639742/165924994-35182c97-000e-4ef9-93d8-0597bc0be1f0.png) |

**Comment by kirtangajjar** [comment]
I'd like to work on this one. Can someone please assign it to me?
