### ISSUE TITLE
mini cart doesn't work (probably other woocommerce blocks)

### ISSUE THREAD

**Issue by derridHeidegger** [woocommerce/woocommerce-gutenberg-products-block#6372]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

once i use the mini cart block, i get an error in the dev tools. obviously nothing work. even though i add a product the mini cart is empty. actually even the message that the cart is empty is not shown.
this is an image of the error i get.
[https://drive.google.com/file/d/1Sh9c7G52BqOqLK0YY5URRtHijMVPIS-H/view?usp=sharing](url)

this is the full discussion i already had in the support, which asked me to write here:
[https://wordpress.org/support/topic/mini-cart-and-sidebar-on-wordpress-5-9-3/](url)

in there there are also videos showing exactly what is happening.

### Expected behavior

the mini cart should display the contents of the chosen products.

### Actual behavior

nothing is displayed, and even if i check with the dev tools, the cart is empty after i add products. so nothing work with the mini cart block.

### Steps to reproduce

1. add the woocommerce blocks
2. add the minin cart block to the header, in the site editor
3. check the mini cart, and the dev tools

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://localhost/may222
Site address (URL): http://localhost/may222
WC Version: 6.4.1
REST API Version: ✔ 6.4.1
WC Blocks Version: ✔ 7.5.0
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.3.2
Log Directory Writable: ✔
WP Version: 5.9.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: he_IL
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.48 (Win64) OpenSSL/1.1.1l PHP/8.0.10
PHP Version: 8.0.10
PHP Post Max Size: 40 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.76.1
OpenSSL/1.1.1l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.21-MariaDB
Max Upload Size: 40 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ מחלקת SoapClient אינה פעילה בשרת - שיטות תשלום המשתמשות ב-SOAP עשויות לא לעבוד כמצופה.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.4.1
WC Database Prefix: wp_
הגודל הכולל של בסיס הנתונים: 3.89MB
גודל הנתונים של בסיס הנתונים: 2.41MB
גודל האינדקס של בסיס הנתונים: 1.48MB
wp_woocommerce_sessions: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
wp_woocommerce_api_keys: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_woocommerce_attribute_taxonomies: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
wp_woocommerce_downloadable_product_permissions: נתונים: 0.02MB + אינדקס: 0.06MB + מנוע InnoDB
wp_woocommerce_order_items: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
wp_woocommerce_order_itemmeta: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_woocommerce_tax_rates: נתונים: 0.02MB + אינדקס: 0.06MB + מנוע InnoDB
wp_woocommerce_tax_rate_locations: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_woocommerce_shipping_zones: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
wp_woocommerce_shipping_zone_locations: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_woocommerce_shipping_zone_methods: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
wp_woocommerce_payment_tokens: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
wp_woocommerce_payment_tokenmeta: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_woocommerce_log: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
wp_actionscheduler_actions: נתונים: 0.02MB + אינדקס: 0.11MB + מנוע InnoDB
wp_actionscheduler_claims: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
wp_actionscheduler_groups: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
wp_actionscheduler_logs: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_commentmeta: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_comments: נתונים: 0.02MB + אינדקס: 0.09MB + מנוע InnoDB
wp_links: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
wp_options: נתונים: 1.39MB + אינדקס: 0.06MB + מנוע InnoDB
wp_postmeta: נתונים: 0.09MB + אינדקס: 0.06MB + מנוע InnoDB
wp_posts: נתונים: 0.06MB + אינדקס: 0.06MB + מנוע InnoDB
wp_termmeta: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_terms: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_term_relationships: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
wp_term_taxonomy: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_usermeta: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_users: נתונים: 0.02MB + אינדקס: 0.05MB + מנוע InnoDB
wp_wc_admin_notes: נתונים: 0.05MB + אינדקס: 0.00MB + מנוע InnoDB
wp_wc_admin_note_actions: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
wp_wc_category_lookup: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
wp_wc_customer_lookup: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_wc_download_log: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_wc_order_coupon_lookup: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_wc_order_product_lookup: נתונים: 0.02MB + אינדקס: 0.06MB + מנוע InnoDB
wp_wc_order_stats: נתונים: 0.02MB + אינדקס: 0.05MB + מנוע InnoDB
wp_wc_order_tax_lookup: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
wp_wc_product_attributes_lookup: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
wp_wc_product_meta_lookup: נתונים: 0.02MB + אינדקס: 0.09MB + מנוע InnoDB
wp_wc_rate_limits: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
wp_wc_reserved_stock: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
wp_wc_tax_rate_classes: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
wp_wc_webhooks: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB

### Post Type Counts ###

attachment: 24
page: 7
post: 2
product: 18
product_variation: 7
wp_global_styles: 1
wp_template_part: 1

### Security ###

Secure connection (HTTPS): ❌
					החנות לא משתמשת בHTTPS. מידע נוסף על HTTPS ותעודות SSL.
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce Blocks: מאת חברת אוטומטיק – 7.5.0
ווקומרס: מאת חברת אוטומטיק – 6.4.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: ILS (₪)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

בסיס חנות: woocommerce/woocommerce#6 - /shop/
סל קניות: woocommerce/woocommerce#7 - /cart/
תשלום: woocommerce/woocommerce#8 - /checkout/
החשבון שלי: woocommerce/woocommerce#9 - /my-account/
תנאי שימוש: ❌ דף לא מוגדר

### Theme ###

Name: Twenty Twenty-Two
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: ❌ – אם משנים את ווקומרס בערכת נושא אב שלא נבנתה באופן אישי
מומלץ להשתמש בערכת עיצוב בת. אפשר לראות: כיצד ליצור ערכת עיצוב בת

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

הושלם: 36
Oldest: 2022-05-03 12:27:36 +0300
Newest: 2022-05-03 12:30:39 +0300

נכשל: 1
Oldest: 2022-05-03 12:27:37 +0300
Newest: 2022-05-03 12:27:37 +0300

ממתין לאישור: 2
Oldest: 2022-05-04 08:50:17 +0300
Newest: 2022-05-04 12:30:39 +0300

### Status report information ###

Generated at: 2022-05-04 08:50:31 +03:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by albarin** [comment]
Hello @derridHeidegger, thanks for reporting this.
We have been trying but were unable to reproduce the issue you are having.
Could you please try to reproduce it using another environment? We suggest you try https://localwp.com/
Please let us know how it goes.
Thank you!

**Comment by derridHeidegger** [comment]
Hi @albarin 
sorry for the late response. i have tested with Local....it workes with Nginx, php version: 7.4.1 and DB = MySQL 8.0.16

but if i tried apache with Mysql 8.0.16 and with Maria 10.4.10 i cannot even install woocommerce at all. i get an error:

"ההתקנה נכשלה: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> 500 Internal Server Error Internal Server Error The server encountered an internal error or misconfiguration and was unable to complete your request. Please contact the server administrator at webmaster@localhost to inform them of the time this error occurred, and the actions you performed just before this error. More information about this error may be available in the server error log."

i checked the php error log and i get this line:

[09-May-2022 06:24:03 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library 'php_imagick.dll' (tried: C:/Users/ronsh/AppData/Local/Programs/Local/resources/extraResources/lightning-services/php-7.4.1+18/bin/win64/ext\php_imagick.dll (The specified module could not be found.), C:/Users/ronsh/AppData/Local/Programs/Local/resources/extraResources/lightning-services/php-7.4.1+18/bin/win64/ext\php_php_imagick.dll.dll (The specified module could not be found.)) in Unknown on line 0

so on apache i cannot even test the blocks since i cannot install woocommerce.

**Comment by tomasztunik** [comment]
@derridHeidegger I've tried to do a quick search on the error you found and it seems [there might be a Local app bug on Windows](https://community.localwp.com/t/php-7-4-1-and-windows-10-lead-to-wp-cli-warning-php-startup-unable-to-load-dynamic-library-php-imagick-dll/26371/3) with PHP 7.4.1. Can you try running it with PHP version 7.3.5?

**Comment by derridHeidegger** [comment]
tried it with 7.3.5 and i get : 404 Site Not Found

**Comment by derridHeidegger** [comment]
also tried version 8 and i get the initial error: cannot install woocommerce

**Comment by tomasztunik** [comment]
Hmm, it seems there is some kind of issue somewhere between your local Windows/Apache/PHP and WP/Woo, but I'm afraid this is outside of WooCommerce Blocks' scope. 

For the purpose of trying to reproduce your original issue with MiniCart can we try getting it running with nginx as the server? You mentioned WordPress/WooCommerce worked this way right?

**Comment by derridHeidegger** [comment]
i have done a lot of wp sites and woocommerce and never encounter these issues? am i the only one that encounter issues like that?
is woocommerce and woocommerce blocks work on apache? i have even uninstalled xammp from my machine and i get the same results. people need to work locally. i can work for now with nginx but that is not the answer.

**Comment by tomasztunik** [comment]
We haven't heard any other reports with issues like this and we've had a couple of us try to reproduce this with no success. 

Did a quick attempt at googling your errors with xammp included and there are mentions of possibly corrupt/misconfigured .htaccess file (which is not used by nginx) causing errors like this - you'll have to do some searching, especially if nginx works it clearly points toward something being corrupt around xammp/apache local setup. Sometimes there are configuration files that last through reinstallation. 

I feel your frustration @derridHeidegger but this is outside of our area of support here and you'll have to be mindful. As soon as we narrow it down to an issue with WooCommerce Blocks that we can reproduce we'll be on the case with you :)

**Comment by derridHeidegger** [comment]
on ngix it does work....although, the mini cart is not translated according to the site. so the cart page is automatically translated, but not the mini cart.

**Comment by tomasztunik** [comment]
Great to hear it works with nginx! If we hear any more reports with windows/apache/xammp and have a solution we'll try to update it here, if you found one yourself please let us know for others if they stumble with similar issue.

Regarding translations it might be there are some new strings that have not been translated to Hebrew just yet or that have the translations in the approval pipeline. You can check the status of translations at https://translate.wordpress.org/locale/he/default/wp/. Help with translations is always appreciated! Else if the translations are there and you've downloaded latest translations from the `dashboard / updates` screen and it's still missing let's create a separate issue focused on that.

I'll close the issue for now but please feel welcome to continue commenting/providing more details. If we see more reports or find an issue on our end we'll either re-open this or reference this issue and we appreciate your feedback!
