### ISSUE TITLE
BlockTemplateUtils: Unit testing

### ISSUE THREAD

**Issue by tjcafferkey** [woocommerce/woocommerce-gutenberg-products-block#6380]
The `[BlockTemplateUtils](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/src/Utils/BlockTemplateUtils.php)` class holds some important logic when it comes to loading WooCommerce block templates into Gutenbergs Site Editor. However there is a significant lack of unit testing around this logic which we could benefit from as this code has become more complex over time.

Some methods worth testing immediately:

* `inject_theme_attribute_in_content()`
* `template_is_eligible_for_product_archive_fallback()`
* `set_has_theme_file_if_fallback_is_available()`
* `remove_theme_templates_with_custom_alternative()`
* `create_new_block_template_object()`

Some that may require more thought but are just as important.

* `build_template_result_from_file()`
* `build_template_result_from_post()`

**Comment by Aljullu** [comment]
@tjcafferkey I see this issue was closed by the stale bot. Do you think it was solved since then or should we reopen (and maybe add the `cooldown` label)?

**Comment by tjcafferkey** [comment]
Yep, I think so @Aljullu !
