### ISSUE TITLE
Billing/Shipping address mismatch when paying with an express payment method then making a new order with a regular payment method

### ISSUE THREAD

**Issue by opr** [woocommerce/woocommerce-gutenberg-products-block#6389]
## Describe the bug
If you use an express payment method, and place an order with a different billing and shipping address, then go and place a new order **without** using an express payment method, if the `Use same address for billing` box is ticked, and not modified between orders, then the billing address used during the the first order is used, rather than the one in the shipping address form.

## To reproduce

1. Ensure you have an express payment method available (You may need to disable password managers and be on HTTPS to get this to work)
2. Place an order using the express payment method and ensure the billing and shipping address are different.
3. Place a new order but use a regular payment method, do not alter the shipping or billing address, simply place the order without changing the form.
4. See the billing address is different to the shipping address, even though `Use same address for billing` was checked.

## Expected behavior
Billing address should be the same as shipping address in this case.

**Comment by senadir** [comment]
This behavior isn't limited really to express payment methods, you can reproduce it using:

- Add item, go to Checkout, uncheck "use shipping as billing", fill out different addresses, place order.
- Add another item, go to checkout, leave "use shipping as billing", place order, check the thank you page, you will see your old billing address.
