### ISSUE TITLE
Run e2e tests on a remote url

### ISSUE THREAD

**Issue by alexflorisca** [woocommerce/woocommerce-gutenberg-products-block#6395]
## Is your feature request related to a problem? Please describe.
It would be cool to do something like `npm run test:e2e-remote https://alright-dwarf.jurassic.ninja/`. This would automate a lot of the smoke testing we do manually for blocks releases, WC and WP updates.

It needs more thinking about how to best to this but it doesn't seem to difficult based on a short discussion in this Slack thread : p1652195830635169-slack-C8X6Q7XQU .  I plan to do this in a future cooldown

**Comment by mikejolley** [comment]
Closing due to pca54o-6Dz-p2
