### ISSUE TITLE
Center the Product Block Inserter in view on screen

### ISSUE THREAD

**Issue by msdesign21** [woocommerce/woocommerce-gutenberg-products-block#64]
When I go to add a product block there are times that I have to scroll up to see all the options on my screen. 

I would expect that once I select to add a product block, the inserter options would be fully visible without me having to scroll up/down. 

Here are two examples: 

http://cld.wthms.co/GmZBH4 

http://cld.wthms.co/UOZ1hI 

"Center" might not be the right word. Maybe it's more "anchor at the top to make all options visible".

**Comment by ryelle** [comment]
It looks like the scroll is moved so that the top of a newly inserted block is more "in view", I'm going to close this as it seems gutenberg fixed it 🙂
