### ISSUE TITLE
Mini Cart drawer "View my cart" hover state not readable

### ISSUE THREAD

**Issue by tomasztunik** [woocommerce/woocommerce-gutenberg-products-block#6400]
## To reproduce

1. Having default Twenty Twenty-Two theme isntalled
2. Have a mini cart block inserted in your theme
3. Add products to the cart
4. Open the mini cart drawer
5. Hover over the "View my Cart" button
6. See the issue

## Expected behavior

If the background gets filled with dark colour the text colour should have correct contrast

## Screenshots

| idle | hovered |
| --- | --- |
| ![Screenshot 2022-05-11 at 11 16 00](https://user-images.githubusercontent.com/112270/167815755-d45b6100-779f-4978-a8f2-0b7ab7dd2c01.jpg) |  ![Screenshot 2022-05-11 at 11 16 05](https://user-images.githubusercontent.com/112270/167815790-c0d939de-c789-414f-97e5-c057f14fbaa7.jpg) |

### WordPress (please complete the following information):

-   Core version: 5.9.3
-   WooCommerce version: 6.4.1
-   WooCommerce Blocks version: 7.6.0
-   Site language: EN

**Comment by Aljullu** [comment]
I think this was fixed in #6731. Is that correct, @dinhtungdu?

**Comment by dinhtungdu** [comment]
@Aljullu Yes, I fixed hover and focus style for the cart button.
