### ISSUE TITLE
Items not removed from the cart when checking out with PayPal Standard

### ISSUE THREAD

**Issue by alexflorisca** [woocommerce/woocommerce-gutenberg-products-block#6401]
## Describe the bug

Cart items don't reset after placing an order with Paypal standard. Once the order goes through, the confirmation page is shown but the items are not removed from the cart

## To reproduce

1. Install & enable [Paypal Standard](https://wordpress.org/plugins/enable-standard-paypal-for-woocommerce/)
2. Add any product to your basket
3. Go to Blocks Checkout page
4. Checkout with PayPal standard (you can create an account with my a8c email address if you don't have one already. You can also use card number 4242 4242 4242 4242 and any valid expiry and CVC number)
5. Click "Return to Merchant"
6. You should see the order summary page and cart icon showing the number of cart items for your order.
7. Go to Cart page.
8. The same items you just placed an order for should be there

## Expected behaviour

I would expect the cart to be empty after placing the order

## Screenshots

![Screenshot 2022-05-11 at 12 11 37](https://user-images.githubusercontent.com/3966773/167837163-5852896a-778b-426a-a5c3-418f7a8e9c2f.png)

### WordPress (please complete the following information):

-   Core version: [e.g. 5.9]
-   WooCommerce version: [e.g. 6.4]
-   WooCommerce Blocks version: [e.g. 7.6.0]

**Comment by tomasztunik** [comment]
This sounds like an issue with the payment service or extension responding with success before the order was fully updated or not changing the order (cart) status to pending and clearing the cart once it started being processed.

Do you think this is on our side @alexflorisca?

**Comment by alexflorisca** [comment]
Yep, I haven't investigated yet, but most probably!

**Comment by opr** [comment]
I could not reproduce this, I tested it a few times with different accounts and different carts.

**Comment by alexflorisca** [comment]
I can still replicate on a local version of WP, see video below (and apologies for the long wait times between page load, my machine being slow). Maybe let's pair on it if you want?

https://user-images.githubusercontent.com/3966773/184654558-5dd7d6a2-a680-4370-9ab1-a541797035a7.mov

**Comment by mikejolley** [comment]
Just noting we also have a similar issue logged here https://github.com/woocommerce/woocommerce-blocks/issues/7233

**Comment by opr** [comment]
Just tested, seems that #8236 solves this.
