### ISSUE TITLE
Plugin is causing a problem with UTC time

### ISSUE THREAD

**Issue by kristinskj** [woocommerce/woocommerce-gutenberg-products-block#641]
A client asked me why she couldn't publish posts/pages immedeately anymore. She only had the option to plan, not publish.

She is in UTC+2 zone, and WP acts as she is in UTC zone with the plugin activated. If she changes time to two hours previous current time, she can publish. If she doesn't, posts/pages are published two hours later.  We found out that de-activating WooCommerce Blocks solved the problem. Not sure what the bug is, but this is what happens.

![2019-06-20_18-00-38](https://user-images.githubusercontent.com/10383853/59869234-2020b200-9393-11e9-9ff5-e38fe7380571.jpg)
![2019-06-20_18-01-49](https://user-images.githubusercontent.com/10383853/59869235-2020b200-9393-11e9-8dcd-29b33d8bf9f0.jpg)

* Core version: 5.2.2
* WooCommerce version: 3.6.4
* WooCommerce Blocks version:  2.1.0
* Site language: Norwegian

* OS: iOS 10.14.1
* Browser: Chrome, Safari
* Version [e.g. 22]

**Comment by mikejolley** [comment]
Confirmed this occurs with release 2.1 of blocks, but is fixed in 2.2. Please update and this will be resolved.

Thanks
