### ISSUE TITLE
Endless loop when using `handpicked-products`

### ISSUE THREAD

**Issue by PanosSynetos** [woocommerce/woocommerce-gutenberg-products-block#6416]
## Describe the bug

When the current product is in the list of `handpicked-products`, it results in an endless loop, causing out of memory issues.

There is no indication of what caused the error; all users see is a white screen of death.

The screenshot below, is from my local environment, where "luckily", after 256 nested loops, it crashed.

Thanks @andrew-ajrwebdesign, for reporting this, and sorry for the trouble!

## To reproduce

Steps to reproduce the behavior: (replicated on my local environment)

1. Enable Gutenberg for products
```php
function ps_activate_gutenberg( $can_edit, $post_type ) {
	if ( 'product' === $post_type ) {
		$can_edit = true;
	}
	return $can_edit;
}
add_filter( 'use_block_editor_for_post_type', 'ps_activate_gutenberg', 10, 2 );
```
2. Assuming you have products created, edit a product with ID `17` and add the following code. Note that `17` is in the array of `"products":[17,38,31,34]`

```
<!-- wp:columns {"align":"wide"} -->
<div class="wp-block-columns alignwide"><!-- wp:column -->
<div class="wp-block-column">
<!-- wp:woocommerce/handpicked-products {"columns":4,"editMode":false,"contentVisibility":{"image":true,"title":true,"price":true,"rating":true,"button":true},"products":[17,38,31,34]} /--></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
```
3. Press update, and you'll be greeted with an error `Updating failed` - If you reload the wp-admin edit product page, you'll get a fatal error (or white screen of death)
4. Visit the product page, you'll get a fatal error (or white screen of death)
5. On some hosts, it causes out of memory issues.

```
Fatal error: Uncaught Error: Maximum function nesting level of '256' reached. aborting 
in /Users/panos/Locasites/app/public/testsite/wp-includes/class-wp-object-cache.php on line 493
```

Another easier way, is to add the block normally, and select the product you're currently editing

![image](https://user-images.githubusercontent.com/2484390/168570680-be848576-e0ae-47d8-8020-96bb11c0730f.png)

In order to "fix" the errors, users would have to disable Gutenberg for product blocks, edit the product (switch to code), remove the conflicting ID, save and then enable block support once again.

OR

Do the exact same change on a database level. 

## Expected behavior

It shouldn't crash. If the current product ID, is in the list of products, then it should be ignored and move on with the rest.

On top of that, the current product, shouldn't be available in the `search for products to display`

## Screenshots

![Edit product “Test 10” ‹ WordPress 2022-05-16 12-20-42 png 2022-05-16 12-51-32](https://user-images.githubusercontent.com/2484390/168567288-00e2f434-1b5c-4e01-a648-6c9894a660a4.jpg)

## Solution

It can be tackled on PHP level, and when looping the products, if `global $post_id` is the same as the current ID of the loop, then `continue`.

In the future, when the block is refactored, we can use the `Query Loop` and limit the products displayed in the `Search for products to display` field

### WordPress (please complete the following information):

-   Core version: 5.9.3
-   WooCommerce version: 6.5.1
-   WooCommerce Blocks version: 7.6.0

**Comment by danieldudzic** [comment]
Hi @PanosSynetos,

I gave it a try, and tried to fix it via PHP - but I keep getting the infinite loop, even when I remove the current post id from the posts ids array 🤷

**Comment by PanosSynetos** [comment]
Hey @danieldudzic - long time :)

Could you please open a draft PR so I can have a look when I get a chance?

**Comment by PanosSynetos** [comment]
@danieldudzic I have a PR ready, feel free to check it out.

**Comment by PanosSynetos** [comment]
Closing this one, as it has been taken care of into https://github.com/woocommerce/woocommerce-blocks/pull/6471
