### ISSUE TITLE
Cart packages names and content not rendered

### ISSUE THREAD

**Issue by NTShop** [woocommerce/woocommerce-gutenberg-products-block#6437]
When the cart contents are split into multiple packages via the "woocommerce_cart_shipping_packages" PHP filter the shipping rates at checkout for each package do appear as expected however there is no defining visual aid between them at checkout. So for example if there are 2 shipping methods available on the site then both methods appear twice as they should but there's no indication as to why they appear twice. When using the regular checkout shortcode the packages are separated, the contents of each package is clearly displayed with its corresponding package name, and the shipping methods associated with each package are shown in relation to the package. See the screenshots below: 

**Checkout with shortcode (note that the package name has been filtered via the "woocommerce_shipping_package_name" hook)**

![checkout1](https://user-images.githubusercontent.com/6944811/169669727-eec2fe20-505d-4cf3-a737-9fdb2d7ccd23.png)

**Checkout with block, shipping options section:** 

![checkout2](https://user-images.githubusercontent.com/6944811/169669731-e783c2e1-3d12-4b9d-8cdd-c2eb0c8ce339.png)

Edit:
## Steps to reproduce:

1. Install this free plugin from the WP plugin repository: "Multiple Packages for WooCommerce"
2. Navigate to WooCommerce -> Settings -> Multiple Packages
3. Adjust the settings to work based on "Per Product"
4. Add two different products to the cart and typically need shipping.
5. Go the checkout page and look at the shipping options.

**Comment by senadir** [comment]
I fail to reproduce that with WooCommerce subscription (but they use slotFills), can you share your implementation?
<img width="859" alt="image" src="https://user-images.githubusercontent.com/6165348/169861801-5346c905-8c3d-422b-ae44-57371d23b1bf.png">

**Comment by NTShop** [comment]
Hi, sure, do this: 

Install this free plugin from the WP plugin repository: "Multiple Packages for WooCommerce"

Navigate to WooCommerce -> Settings -> Multiple Packages

Adjust the settings to work based on "Per Product" 

Add two different products to the cart and typically need shipping. 

Go the checkout page and look at the shipping options.

**Comment by opr** [comment]
Hi @NTShop - I've just tried to replicate this using your recommended plugin, and I got the expected result.

Here is the filter code I am using to change the shipping package name

```php
add_filter(
	'woocommerce_shipping_package_name',
	function( $name ) {
		return $name . ' (  filtered)';
	}
);
```

And here is how it displays on the front-end:

<img width="687" alt="image" src="https://user-images.githubusercontent.com/5656702/170480075-3a2c4095-07ce-4dc7-a27d-679ff0eb9114.png">

I notice the spacing is a little off so I have created #6467 to track this.

You mention in your original comment:

> Checkout with shortcode (note that the package name has been filtered via the "woocommerce_shipping_package_name" hook)

Could you please show me what code you're using to filter the shipping names?

**Comment by NTShop** [comment]
Currently I'm not using any custom code to filter the package names because I cannot see any package names at checkout. Attached is a screenshot of the plugins active on the test site, there is no custom code or modifications anywhere in this site. 

![plugins](https://user-images.githubusercontent.com/6944811/171233988-5ee7c13d-47ad-4eb7-8e3a-003f53df77ec.png)

Here is the result at checkout with 2 simple products in the cart, as you can see there are still no package names appearing: 

![shipping](https://user-images.githubusercontent.com/6944811/171234309-0dfe7482-fd1b-427a-b60c-ebdcb4326757.png)

**Comment by NTShop** [comment]
I tested with the newly released WooCommerce Blocks 7.9, the problem still exists in my tests using the 3 plugins in the screenshot shown in my previous response and no custom code on the site.

**Comment by tarunvijwani** [comment]
@NTShop I'm able to reproduce the issue. Thank you for reporting it! I'm adding this to our backlog.

**Comment by NTShop** [comment]
Thanks! Just an FYI: The problem persists in WooCommerce Blocks 8.0.
