### ISSUE TITLE
Pass cart_item_data to CartAddItem route

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce-gutenberg-products-block#6445]
## Is your feature request related to a problem? Please describe.
It doesn't appear possible in the [`CartAddItem`](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/StoreApi/Routes/V1/CartAddItem.php#L93-L99) route to pass any additional `cart_item_data`.  Is it possible to send custom configurations?

## Describe the solution you'd like
Some kind of support for custom product types

## Additional context
This probably falls under extensibility/support for custom product types... or products with custom forms, etc.

**Comment by senadir** [comment]
Hey Helga, thank you for raising this. It's indeed something that we didn't tackle yet because we didn't see a need for it. Do you have a specific use case for which you're adding products using Store API?

**Comment by helgatheviking** [comment]
Hi @senadir. I do _not_ yet, but I am the author of Name Your Price and Mix and Match Products. Down the road, in order to have them work with the current blocks (or my own blocks?) I would need to pass custom data to the Store API in order for them to pass validation and be added to the cart. With Name Your Price, there's a need to pass data from a price input. From Mix and Match... there are multiple quantity inputs to pass along representing the quantities of the configuration of products you want to purchase as part of your container/box product.

**Comment by opr** [comment]
cc @ralucaStan could you help triage this further please, does this sound like an extensibility point we could look into adding in future? Should we move it to the backlog?

**Comment by ralucaStan** [comment]
Thank you @opr for bringing this to my attention. I've moved it to the Next column, we should focus on this during our next cycle.

**Comment by micarner** [comment]
Is there somewhere I can see the status of the development on this issue? I too see this as being a very useful feature. Product variations only go so far as their options are from a predefined set. If I want to pass a text field or a complex set of dynamic options, I don't see a way to do this using the Store API.

**Comment by ralucaStan** [comment]
Hi @micarner,
thank you for reaching out. This issue is included in our cycle so it should get some progress soon.
