### ISSUE TITLE
Custom event when cart total changes

### ISSUE THREAD

**Issue by andfinally** [woocommerce/woocommerce-gutenberg-products-block#6450]
## Is your feature request related to a problem? Please describe.

It would be very useful if the cart block triggered a custom event when the cart total changes. 

In WooCommerce.com, we need to watch for changes in the cart so we can recalculate a discount using the Dynamic Pricing extension. Our component has to watch the block markup like this:

```js
// check if cart change, if yes then refresh the data
useEffect( () => {
	if ( ! document.body.classList.contains( 'page-cart' ) ) {
		return;
	}

	const cartBlock = document.querySelector( '.wp-block-woocommerce-cart' );
	if ( ! cartBlock ) {
		return;
	}

	function getTotalsFromCartHTML() {
		return cartBlock
			.querySelector( '.wc-block-components-totals-item__value' )?.innerHTML || '';
	}

	let previousTotalsValue = getTotalsFromCartHTML();

	const checkIfTotalCartAmountChanged = function() {
		const newTotals = getTotalsFromCartHTML();
		const isFirstRender = ! previousTotalsValue;
		if ( ! isFirstRender && newTotals !== previousTotalsValue ) {
			setFetchCounter( counter => counter + 1 );
		}
		previousTotalsValue = newTotals;
	};

	const observer = new MutationObserver( checkIfTotalCartAmountChanged );
	observer.observe( cartBlock, { childList: true, subtree: true, attributes: true } );
}, [] );
```

13352-gh-Automattic/woocommerce.com

This is quite brittle: in this situation, it would be super useful if we could simply listen for an event instead.

## Describe the solution you'd like

When the cart total changes, trigger a custom event that passes the cart total. (In an ideal world it'd pass other info like the order items, quantities and subotals, but this is all we need for our current purposes.)

## Describe alternatives you've considered

We are using a MutationObserver instead.

**Comment by opr** [comment]
Hey @andfinally we are in the process of moving to `@wordpress/data` to manage the cart state, so when this lands you would be able to subscribe to the `wc/store/cart` store and process any changes to item quantities there.

I've moved this into the epic issue for the data stores project so we can track this issue as the project progresses.

**Comment by BrianHenryIE** [comment]
For anyone who finds this, I managed to get something similar working with:

```typescript
import { subscribe, select } from '@wordpress/data';
import { CART_STORE_KEY } from '@woocommerce/block-data';
import { extensionCartUpdate } from '@woocommerce/blocks-checkout';

subscribe( () => {
    const { isBeforeProcessing } = select( 'wc/store/checkout' );

    if ( isBeforeProcessing ) {

        const store = select( CART_STORE_KEY );
        const cartData = store.getCartData();

        // Some conditional logic here.

        // Maybe debounce.

        extensionCartUpdate({
            namespace: 'my-plugin-namespace',
            data: {
                "cartData": cartData
            },
        });
    }
} );
```

Make changes to the cart in PHP following [Updating the cart with the Store API](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/rest-api/extend-rest-api-update-cart.md#registering-a-callback-to-run-when-the-cartextensions-endpoint-is-hit) and the cart will update when the request returns.

Thanks @opr for the pointer on Slack yesterday.
