### ISSUE TITLE
Woocommerce block responsize size problems

### ISSUE THREAD

**Issue by eliquame** [woocommerce/woocommerce-gutenberg-products-block#6451]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

If i use (i tried 2 WC blocks) product blocks more than 4 columns (5 or 6) the card box sizes and other sizes (text, button, ect) will be very very small. Example like zoom out effect. :-)
The text sizes are not use the theme inherit body or Heading size, not use default 1rem size. With 5 columns will be 9.28px the product title, and if you want you it with 6 columns, it will be (product title) 8px size.

Its make every scenario, small monitor, FullHD screen or 4K screen too.

### Expected behavior

Use the deafult theme sizes, what can we overdrive example whit custom css or in customize option page.

### Actual behavior

![image](https://user-images.githubusercontent.com/44946426/170046404-7680e4d0-2b3c-4f3d-9323-ff25bb998b42.png)

### Steps to reproduce

1. in gutenberg editor choose wc block
2. I tried it with hand picked product blocks and Sales product block
3. Choose 1row and more than 4 columns products layout (5 or 6 columns)
4. Save
5. See the public page.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://gulya.simplecreative.hu
Site address (URL): https://gulya.simplecreative.hu
WC Version: 6.5.1
REST API Version: ✔ 6.5.1
WC Blocks Version: ✔ 7.4.3
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 5.9.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.29
PHP Post Max Size: 96 MB
PHP Time Limit: 14400
PHP Max Input Vars: 12000
cURL Version: 7.61.1
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.6.7-MariaDB
Max Upload Size: 96 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.5.1
WC Database Prefix: wp_
Total Database Size: 7.56MB
Database Data Size: 5.63MB
Database Index Size: 1.93MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 4.03MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.13MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.41MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_composite_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bis_activity: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_bis_notifications: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_bis_notificationsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

addify_quote: 1
addify_rfq_fields: 1
attachment: 25
custom_css: 1
customize_changeset: 34
nav_menu_item: 7
oly_hooks: 4
page: 9
post: 3
product: 7
revision: 18
shop_order: 1
wp_block: 1
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (15) ###

Code Snippets: by Code Snippets Pro – 3.1.0
GreenShift - Animation and Page Builder Blocks: by Wpsoul – 2.4.4
Olympus Blocks: by UranusWP – 1.0.0
Olympus Pro: by UranusWP – 1.0.2
WooCommerce Back In Stock Notifications: by WooCommerce – 1.3.1
WooCommerce Checkout Add-Ons: by SkyVerge – 2.5.6
WooCommerce Composite Products: by WooCommerce – 8.4.1
WooCommerce Conditional Shipping and Payments: by WooCommerce – 1.13.0
WooCommerce Deposits: by WooCommerce – 1.5.5
WooCommerce Measurement Price Calculator: by SkyVerge – 3.20.1
WooCommerce Product Add-ons: by WooCommerce – 4.2.0
WooCommerce Product Bundles: by WooCommerce – 6.15.2
Request a Quote for WooCommerce: by Addify – 2.3.0
WooCommerce: by Automattic – 6.5.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: HUF (Ft)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: woocommerce/woocommerce#6 - /shop/
Cart: woocommerce/woocommerce#7 - /cart/
Checkout: woocommerce/woocommerce#8 - /checkout/
My account: woocommerce/woocommerce#9 - /my-account/
Terms and conditions: woocommerce/woocommerce#2 - /sample-page/

### Theme ###

Name: OlympusWP
Version: 1.1.5
Author URL: https://uranuswp.com/about-us/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Back In Stock ###

Database Version: 1.3.1
Loopback Test: ✔

### Composite Products ###

Database Version: 8.4.1
Loopback Test: ✔
Template Overrides: –

### Product Bundles ###

Database Version: 6.15.2
Loopback Test: ✔
Template Overrides: –

### Action Scheduler ###

Complete: 42
Oldest: 2022-05-18 14:28:33 +0000
Newest: 2022-05-24 11:31:44 +0000

### Status report information ###

Generated at: 2022-05-24 15:29:50 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by gigitux** [comment]
Hi, 
thanks for opening the issue.

Did you try to set the block with `full-width` option? (check the attached gif). If you are not happy about the result, you can always [use custom class CSS to customize the font](https://wordpress.com/it/support/aggiungi-altre-classi-css-ai-blocchi/).

I'm closing this issue. Closed issues can also still be commented on.

![Screen Capture on 2022-05-26 at 12-11-36](https://user-images.githubusercontent.com/4463174/170467725-7ae62470-28c7-4000-8f94-93a26ac452e5.gif)
