### ISSUE TITLE
Featured Product and Featured Category blocks default colors don't have enough contrast

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#6489]
## To reproduce

1. Add a Featured Product or Featured Category block into a post or page.
2. Notice text doesn't have enough contrast with the background.

![imatge](https://user-images.githubusercontent.com/3616980/171025759-80071c62-e924-4a8a-93cd-211e1952b90d.png)

## Expected behavior

By default, we should make sure text and background have enough contrast.

**Comment by Aljullu** [comment]
@sunyatasattva will you be able to take a look at this one? I think there wasn't this issue before. Maybe we should change the overlay default color?

**Comment by sunyatasattva** [comment]
Sure, I'll look into it. Previously I think the default was white, so contrast worked well enough. Strange we didn't notice.

**Comment by sunyatasattva** [comment]
Result of testing, as clarification for this issue: this seems to happen only when themes override blocks CSS. In this case, Storefront shows this problem, while most other themes I tested with do not.
