### ISSUE TITLE
Register Filter Blocks using `block.json`

### ISSUE THREAD

**Issue by dinhtungdu** [woocommerce/woocommerce-gutenberg-products-block#6491]
For each block:
- Add `block.json` file for each filter block.
- Register JS block using metadata from `block.json`.

Blocks to be updated:

- [ ] Active Filters
- [ ] Filter Products by Prices
- [ ] Filter Products by Attribute
- [ ] Filter Products by Stock

Part of https://github.com/woocommerce/woocommerce-blocks/issues/4672

**Comment by spacedmonkey** [comment]
Related: https://github.com/woocommerce/woocommerce-blocks/issues/4672

**Comment by dinhtungdu** [comment]
@spacedmonkey Thanks for the notice, I updated the PR description above to clearly state this is a part of 4672.
