### ISSUE TITLE
Can't select hidden products in handpicked products block

### ISSUE THREAD

**Issue by osirismqz** [woocommerce/woocommerce-gutenberg-products-block#6507]
Product visibility is a great feature to hide products from our shops catalogue automatically. But you should be allowed to show this products manually inside the handpicked products block.

A common example: showing a product on a landing page but not on the main shop page.

Same bug was present years ago and it got fixed:

- https://github.com/woocommerce/woocommerce-blocks/issues/790
- https://github.com/woocommerce/woocommerce-blocks/pull/803

Im using WordPress 6.0 and WooCommerce Blocks 7.7.0

**Comment by frontdevde** [comment]
Hi @osirismqz!

That should indeed be possible. I just tried to reproduce the issue. That said, using a new clean test site with WordPress 6.0, WooCommerce 6.5.1, and WooCommerce Blocks 7.7.0 I can't reproduce the issue. When I make a product hidden, I can still select it in the Handpicked Products block:

<img width="296" alt="Screenshot 2022-06-02 at 16 24 42" src="https://user-images.githubusercontent.com/1562646/171652190-fcc9c039-f01c-4eb7-bfa1-268403d17dc7.png">
<img width="692" alt="Screenshot 2022-06-02 at 16 22 00" src="https://user-images.githubusercontent.com/1562646/171652228-8468030d-42df-4721-8b02-713d230014cb.png">
<img width="357" alt="Screenshot 2022-06-02 at 16 21 49" src="https://user-images.githubusercontent.com/1562646/171652253-9896b590-3a7f-4703-aaf3-bcf2adc82925.png">

Could you maybe try a different product that is currently visible in the Handpicked Products block and only change the `Catalog visibility:` to `Hidden`. Is that product then also not visible in the Handpicked Products block for you?

**Comment by osirismqz** [comment]
You are right. I tried on a different install and it worked right. My bad.

It must be some plugin but I cannot find the culprit.

Sorry and thanks for your help!
