### ISSUE TITLE
Feedback on ./src/StoreApi/docs/checkout.md

### ISSUE THREAD

**Issue by infomidhun** [woocommerce/woocommerce-gutenberg-products-block#6518]
<img width="1271" alt="Screenshot 2022-06-06 at 4 07 46 PM" src="https://user-images.githubusercontent.com/68937211/172145560-2dd81a77-db02-4234-ba3f-14e80a1ddde7.png">

Can you ensure the shipping_address type is integer, assume it is an array.
https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/StoreApi/docs/checkout.md#process-order-and-payment

**Comment by alexflorisca** [comment]
Thanks a lot for reporting this @infomidhun! I've created a [PR](https://github.com/woocommerce/woocommerce-blocks/pull/6541) to fix this, should be merged soon :)
