### ISSUE TITLE
Ensure WooCommerce is styled as expected out of the box with block themes

### ISSUE THREAD

**Issue by frontdevde** [woocommerce/woocommerce-gutenberg-products-block#6526]
This is the parent issue (Epic) to track tasks related to the "Ensure WooCommerce is styled as expected out of the box with block themes" effort.

**Comment by colorful-tones** [comment]
@frontdevde I've begun investigating integrating WooCommerce with our newly launched [Extendable](https://wordpress.org/themes/extendable/) block theme. Here is my progress so far in Draft PR: https://github.com/extendify/extendable/pull/60.

Perhaps this might help someone? I'm hoping to keep the conversation and feedback flowing. Thanks!

cc: @richtabor

**Comment by frontdevde** [comment]
Thank you for sharing, @colorful-tones! 👏 I'll take a look at your Draft PR tomorrow 👍

> Perhaps this might help someone? I'm hoping to keep the conversation and feedback flowing. 

Highly appreciated! We're definitely interested in anything you might find that could help us ensure WooCommerce works well out of the box with block themes. So any obstacles you might encounter towards that end would be great to know about!

**Comment by Aljullu** [comment]
I think we can close this epic and continue the discussion about Elements API in #6567.
