### ISSUE TITLE
Audit the WooCommerce Twenty Twenty-Two style sheet and identify rules to extract as common styles for all block themes

### ISSUE THREAD

**Issue by frontdevde** [woocommerce/woocommerce-gutenberg-products-block#6528]

**Comment by colorful-tones** [comment]
@frontdevde do you happen to know where the source for this is coming from please? Specifically the `twenty-twenty-two.css`

```
'src'     => str_replace( array( 'http:', 'https:' ), '', WC()->plugin_url() ) . '/assets/css/twenty-twenty-two.css'
```

https://github.com/woocommerce/woocommerce/blob/6aa4b5cdae4dbc0942f923c0492d5958eb344718/plugins/woocommerce/includes/theme-support/class-wc-twenty-twenty-two.php#L57

**Comment by frontdevde** [comment]
Hey, Damon 👋 The Twenty Twenty-Two specific stylesheet can be found [here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/legacy/css/twenty-twenty-two.scss). I'm not sure that's what you're asking though? Feel free to elaborate further and I'll try to answer!

**Comment by colorful-tones** [comment]
> Hey, Damon 👋 The Twenty Twenty-Two specific stylesheet can be found here. I'm not sure that's what you're asking though?

@frontdevde that is perfect. Thanks!

**Comment by colorful-tones** [comment]
Strange that it lives in `woocommerce/plugins/woocommerce/legacy/`, because TwentyTwentyTwo is not legacy to me. 🤔

**Comment by frontdevde** [comment]
Closing as the issue tracks the WC 2022 audit. The Audit was completed and changes are to be addressed in https://github.com/woocommerce/woocommerce/pull/33518.
