### ISSUE TITLE
Editor side translations are loaded on the frontend side

### ISSUE THREAD

**Issue by gigitux** [woocommerce/woocommerce-gutenberg-products-block#6530]
## Describe the bug

On the frontend side, the code loads the block translations that belong to the editor side.

## To reproduce

1. Change the language to the Netherlands then update all translations.
2. Create a page with the All Products block.
3. Check the page source of the new page and you can notice that the editor side translations are loaded.

## Expected behavior

The editor side translations should be loaded only on the editor side.

## Screenshots

![image](https://user-images.githubusercontent.com/4463174/172330721-88f5a548-824c-4244-a8a6-924fa874b021.png)

**Comment by Aljullu** [comment]
@gigitux I think these translations come from `wp-block-editor`, right? In that case, do you think this is a duplicate of https://github.com/woocommerce/woocommerce-blocks/issues/4543?

**Comment by gigitux** [comment]
> @gigitux I think these translations come from `wp-block-editor`, right? In that case, do you think this is a duplicate of #4543?

Mmm, yes, more or less :D 
The main problem is that this issue is not related only to the `All Products` block. I tried with `Checkout` block and we load the editor-side translation on the frontend side.

Maybe we should merge the issues and be sure that we check the problem for all blocks.

**Comment by Aljullu** [comment]
Can you check if that happens on `npm run build` instead of `npm start` (it doesn't for me :thinking: )? We do some more aggressive tree shaking on build, so some dependencies which are loaded in dev mode aren't in production.

**Comment by gigitux** [comment]
> Can you check if that happens on npm run build instead of npm start (it doesn't for me 🤔 )? We do some more aggressive tree shaking on build, so some dependencies which are loaded in dev mode aren't in production.

I installed the plugin from wp.org and I'm still able to reproduce the problem

**Comment by Aljullu** [comment]
> I installed the plugin from wp.org and I'm still able to reproduce the problem

With the Checkout block? I tested again with this test site and I can't reproduce it:

https://ephemeral-aljullu-20220607.atomicsites.blog/checkout/ (← you will need to add a product to the cart for the Checkout page to appear)

I checked the source code of the page and can't find the `wp-block-editor-js-translations` string. Am I doing something wrong? :confused: 

Versions:
* WooCommerce 6.5.1
* WooCommerce Blocks 7.8.0
* WordPress 6.0

**Comment by gigitux** [comment]
I guess that you are not able to reproduce it because you have to switch to another language (for example switch to Italian).

On my test website, I'm able to reproduce the issue with the Checkout block.

I added a Checkout Block without adding shipping options and this is the Italian translation on the editor side:

![image](https://user-images.githubusercontent.com/4463174/173360721-43d46d7c-5ad9-477a-a056-955a66f841a2.png)

This is the Checkout Block on the frontend side:
![image](https://user-images.githubusercontent.com/4463174/173359737-2b5fe79b-6009-4af1-8c1c-a611ac8c98b8.png)

You can notice that the translations that I highlight on the first image don't appear, but unfortunately, it is loaded on our page:

![image](https://user-images.githubusercontent.com/4463174/173361140-27f1e166-474e-44bc-996d-6b090073d139.png)


In this case, the translations are added with a script tag with id `wc-checkout-block-frontend-js-before`.

**Comment by Aljullu** [comment]
> I guess that you are not able to reproduce it because you have to switch to another language (for example switch to Italian).

Ouch, sorry, I forgot to change the language. :man_facepalming: 

> In this case, the translations are added with a script tag with id `wc-checkout-block-frontend-js-before`.

Right, I'm able to see. I wonder if we should have two different issues, one for the All Products block (which I think is #4543) and one for the Checkout block (maybe this one?). I think they are two different issues and this way we can assign each one to the correct team. Thoughts? :thinking:

**Comment by gigitux** [comment]
> > I guess that you are not able to reproduce it because you have to switch to another language (for example switch to Italian).
> 
> Ouch, sorry, I forgot to change the language. 🤦‍♂️
> 
> > In this case, the translations are added with a script tag with id `wc-checkout-block-frontend-js-before`.
> 
> Right, I'm able to see. I wonder if we should have two different issues, one for the All Products block (which I think is #4543) and one for the Checkout block (maybe this one?). I think they are two different issues and this way we can assign each one to the correct team. Thoughts? 🤔

I'm not sure because my knowledge of translations is pretty limited. I'm wondering:
- Can we improve how we handle translations? Potentially not handling translations for each block, but create a code that works that we can easily re-use (maybe improve [this](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/ce0f86bc4c95d220d7e95e13f2c8673c29ec4c93/src/BlockTypes/AbstractBlock.php/#L161-L172))
- Are there other blocks that we should check?

**Comment by Aljullu** [comment]
> - Can we improve how we handle translations? Potentially not handling translations for each block, but create a code that works that we can easily re-use (maybe improve [this](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/ce0f86bc4c95d220d7e95e13f2c8673c29ec4c93/src/BlockTypes/AbstractBlock.php/#L161-L172))

I have you some ideas on how to improve it, go for it! Maybe as a cooldown task?

> - Are there other blocks that we should check? 

I'm not sure, I guess we could check all blocks, but those issues seem to be specific to Checkout and All Products, no?

**Comment by gigitux** [comment]
> I have you some ideas on how to improve it, go for it! Maybe as a cooldown task?

To be honest, for now, I don't have any ideas :( 

> I'm not sure, I guess we could check all blocks, but those issues seem to be specific to Checkout and All Products, no?

True, but in the case of the `All products` block, in [the dedicated class](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/2301500d5cfdaa6bd55f81049cba6da2a84f62c2/src/BlockTypes/AllProducts.php) there isn't any particular code for the translations.

This is the reason why I think that we should debug [this code on the `AbstractBlock` class](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/2301500d5cfdaa6bd55f81049cba6da2a84f62c2/src/BlockTypes/AbstractBlock.php/#L161-L172).

**Comment by tarhi-saad** [comment]
Upon some investigation, I realized that this bug had been resolved in this PR: #9251. The solution was to [remove the dependency on `block-editor` from frontend blocks](https://github.com/woocommerce/woocommerce-blocks/issues/8071).

@gigitux, @Aljullu, could you please double-check? If it works for you, feel free to close this issue! 🙌

**Comment by gigitux** [comment]
@tarhi-saad You're right! I'm not able to reproduce anymore! We can close this issue and #4543! I will proceed with it! @Aljullu feel free to open both issues if you find some issues!
