### ISSUE TITLE
MiniCart - Notice undefined index "label_including_tax"

### ISSUE THREAD

**Issue by WebKinect** [woocommerce/woocommerce-gutenberg-products-block#6536]
## Describe the bug

Using the MiniCart Block anywhere in any template, with "woocommerce_cart_display_prices_including_tax" = 'incl' and wc_prices_include_tax = 'yes' in WooCommerce Filters, the following error occurs:

Notice: Undefined index: tax_label in $path_to_wordpress/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/BlockTypes/MiniCart.php on line 122

I already checked the method MiniCart::get_tax_label on line 437, where it builds the array to expect the index and found "label_including_tax" as index. But there is no reference inside WooCommere-Blocks or WooCommerce itself, that uses this array index.
So i suppose that "label_including_tax" just needs to be replaced by "tax_label" on line 450.

## To reproduce

1. Add Filter on "woocommerce_cart_display_prices_including_tax" to return 'incl'
2. Add Filter on "woocommerce_prices_include_tax" to return 'yes'
3. Add Block MiniCart on any page / template
4. Save page / template
5. Go to frontend of saved page / template to see the error

## Expected behavior

It should render without notices.

### WordPress (please complete the following information):

-   Core version: 6.0
-   Gutenberg version (if installed): 13.2.1
-   WooCommerce version: 6.5.1
-   WooCommerce Blocks version: 7.4.3
-   Site language: de_DE

### Desktop (please complete the following information):

-   OS: macOS
-   Browser : chrome
-   Version 102.0.5005.61

**Comment by Aljullu** [comment]
Thanks for opening this issue and investigating the source of the bug, @0verscore! I was able to reproduce and will try to get a fix soon.
