### ISSUE TITLE
Store API: Add Cross-Sells products endpoint

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#6555]
Currently, the Cross-Sells products are only available in the shortcode-based Cart, but not in the Cart block. To make the Cross-Sells products available in the frontend of the Cart block, we need to add a new endpoint to the Store API. 

## Backwards-compatibility

For backwards-compatibility, that endpoint need to use [`get_cross_sells()`](https://github.com/woocommerce/woocommerce/blob/ace978691401af09bea34dd0ee716a49822ef4e3/plugins/woocommerce/includes/class-wc-cart.php#L812-L830) from the WooCommerce core. 

## Store API endpoint

~The Store API will have `cart/cross-sells` as an independent endpoint and `cross-sells` as a top-level item in cart response.~ The Cross-Sells products will be part of the `cart` endpoint. See https://github.com/woocommerce/woocommerce-blocks/issues/6555#issuecomment-1155029250.

## Additional notes

The Cross-Sells products are defined on a product-level via `WP Admin » Products`:

<img width="1358" alt="Screenshot 2022-06-13 at 12 27 43" src="https://user-images.githubusercontent.com/3323310/173334466-02a92777-670a-4861-8d08-9b9b3f77a179.png">

**Comment by wavvves** [comment]
@nielslange after a call with @opr, what do you think of this being added to the cart object at `/wp-json/wc/store/cart`?

Pros:

- It would save an extra request on the cart page.
- In this particular case, they are deeply coupled with the cart's current state, adding and removing products might interfere with the x-sell data (adding/removing a product)
- Would be retro-compatible (since we will be adding something)
- Less endpoint pollution

Cons:

- If we want the same block on the product details page we'd still need an endpoint for this if we don't want to add it to the Product object

**Comment by nielslange** [comment]
> @nielslange after a call with @opr, what do you think of this being added to the cart object at `/wp-json/wc/store/cart`?

@wavvves The Cross-Sells products endpoint should definitely be part of the cart object at `/wp-json/wc/store/cart`. I also written that in the description above, but forgot to mention that explicitly in our call. Sorry for that.

> Cons:
> 
> If we want the same block on the product details page we'd still need an endpoint for this if we don't want to add it to the Product object

The Cross-Sells products will _only_ appear on the Cart, nowhere else. Therefore, the _Cons_, you've correctly identified, are no longer _Cons_. 😀

**Comment by opr** [comment]
> The Store API will have `cart/cross-sells` as an independent endpoint

How come this is necessary? If it's not going to be shown anywhere besides the Cart Block, then we should just get the cross sells from the Cart endpoint, I can't see a use-case for the `cart/cross-sells` endpoint but maybe I'm missing something?

**Comment by nielslange** [comment]
> How come this is necessary? If it's not going to be shown anywhere besides the Cart Block, then we should just get the cross sells from the Cart endpoint, I can't see a use-case for the `cart/cross-sells` endpoint but maybe I'm missing something?

You mean instead of having the `cart/cross-sells` endpoint, similar to the [`cart/items`](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/StoreApi/docs/cart-items.md#list-cart-items)  endpoint, you'd only make the cross-sells products available via the [`cart`](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/StoreApi/docs/cart.md) endpoint, correct?

Creating the `cart/cross-sells` endpoint was one of the technical requirements @senadir defined in pdFofs-43-p2. I assumed that having this endpoint to get the cross-sells products directly is more performant than calling the `cart` endpoint and extracting the cross-sells products then. Don't you see any performance benefits from having a separate endpoint?

**Comment by opr** [comment]
> I assumed that having this endpoint to get the cross-sells products directly is more performant than calling the cart endpoint and extracting the cross-sells products then.

If we're already on the Cart Block, we'll have to get data from `/cart` anyway, and operations on the cart that will affect cross-sells (remove items, change quantity) will return the entire cart, so the cross-sells will be included in that.

I guess the benefit of `cart/cross-sells` is it makes our API better and more granular, it allows consumers of the Store API to get the data they want without taking the entire cart. I don't think we will be accessing it in our client though?

**Comment by senadir** [comment]
Having separate endpoints is something we historically did and think should keep doing, the goal here is not for Cart block but for external consumers who might want to consume just that section.

**Comment by nielslange** [comment]
@senadir I wonder if fetching Cross-Sells products outside the Cart actually makes sense, as the Cross-Sells products belong to products in the Cart. Outside the Cart block, the Cross-Sells products would appear without context, unless they would be loaded on the corresponding product page.

**Comment by opr** [comment]
@nielslange it's to allow other consumers to get only the cross sells if they want. I agree with Nadir.

We don't need it for our client, since we will only show it in the Cart Block, but somebody else might want it for their application, so I think this is OK.

**Comment by senadir** [comment]
>  I wonder if fetching Cross-Sells products outside the Cart actually makes sense, as the Cross-Sells products belong to products in the Cart. Outside the Cart block, the Cross-Sells products would appear without context, unless they would be loaded on the corresponding product page.

For Cart block, it doesn't make sense yeah, so that's why it's loaded from within Cart response, for other consumers, we don't know and shouldn't make such assumption.

**Comment by senadir** [comment]
After a little research, **let's drop the extra endpoint for `cart/cross-sells` for now.**

It seems that Store API supports `_fields` query param, in which someone can still fetch cross sells alone using that option, so hitting `GET /wp-json/wc/store/v1/cart?_fields=cross_sells` would only return cross sells.

This might allow us to depricate other endpoints in the future.

**Comment by ralucaStan** [comment]
I took a look at WC Rest API and they have the `cross_sell_ids` defined at [product level](https://woocommerce.github.io/woocommerce-rest-api-docs/#products). @senadir is this something that we would also need to introduce at product level in Store API, considering the Cross Sell was not really handled in the Store API (from what I was able to find)?

**Comment by senadir** [comment]
We might revisit this later for the products endpoint, but for cart it should top level value, not product based.

**Comment by wavvves** [comment]
I agree with @senadir with it being top level because of relations, Cross-sells in relation to cart contents vs Cross-sells associated with a single product.

Product level will need more logic (and that logic already [exists](https://github.com/woocommerce/woocommerce/blob/ace978691401af09bea34dd0ee716a49822ef4e3/plugins/woocommerce/includes/class-wc-cart.php#L812-L830)) attached to be used with the cart, as it can have duplicates and invalid items already present on the cart. Actually, that's the reason why products have `cross_sell_ids`.

This makes me think, isn't Cross-sells always associated with cart? If we look into [`get_cross_sells()`](https://github.com/woocommerce/woocommerce/blob/ace978691401af09bea34dd0ee716a49822ef4e3/plugins/woocommerce/includes/class-wc-cart.php#L812-L830) we see its based off cart contents, and even at Product level, ie Product details page, do we want to show Cross-sell items that are already in the cart? Seems like redundant information.

So `get_cross_sells()` is the way to go here, and also the way to go if we ever want to have them on the Product details page.

**Comment by senadir** [comment]
> This makes me think, isn't Cross-sells always associated with cart? If we look into [get_cross_sells()](https://github.com/woocommerce/woocommerce/blob/ace978691401af09bea34dd0ee716a49822ef4e3/plugins/woocommerce/includes/class-wc-cart.php#L812-L830) we see its based off cart contents, and even at Product level, ie Product details page, do we want to show Cross-sell items that are already in the cart? Seems like redundant information

This will be relevant for Store API and Product endpoint if someone is building their own product view and want to include cross-sells right there, currently there's upsell for that but cross sell might work as well, however, it's way beyond the scope of this project.

**Comment by ralucaStan** [comment]
> it's way beyond the scope

Totally, I should have mentioned that it's not my expectation to be handled in pdFofs-5q-p2 if there is indeed a need. 
I just wanted to bring this to the attention of the team the way it's handled in WC Store API and hightlight that it is something that might be handled in the future.

**Comment by senadir** [comment]
Having separate endpoints is something we historically did and think should keep doing, the goal here is not for Cart block but for external consumers who might want to consume just that section.

**Comment by opr** [comment]
> but for external consumers who might want to consume just that section.

Noting that this is a great use-case for GraphQL 👀
