### ISSUE TITLE
Elements API: complete an audit of all blocks that make use of core elements and update them to inherit Elements API styles

### ISSUE THREAD

**Issue by frontdevde** [woocommerce/woocommerce-gutenberg-products-block#6567]
For context and details see p2-pdnLyh-1kY.

**Comment by colorful-tones** [comment]
@frontdevde I'm not sure if this is related or worthy of a separate issue. Gutenberg is currently working towards including `button` and `a` styling in `theme.json`. In support of this there was this [bit of CSS recently introduced](https://github.com/WordPress/gutenberg/blob/3d9aa0bc00162554f0ad3f1a0f4524f24744c476/lib/compat/wordpress-6.1/class-wp-theme-json-6-1.php#L90) to target `a:not(.wp-element-buttons)` with styling. However, it seems that most WooCommerce Blocks blocks do not have this `.wp-element-button` class. Therefore, their output is unaffected by this update.

![Screen Shot 2022-07-25 at 4 37 38 PM](https://user-images.githubusercontent.com/405912/180869960-7559956f-9a47-4efa-9017-a750d625ca87.png)

![Screen Shot 2022-07-25 at 4 35 07 PM](https://user-images.githubusercontent.com/405912/180869999-ab8c2872-54d8-4f48-afb8-20ace4ea52a8.png)

**Comment by Aljullu** [comment]
I'm going to close this issue. Regarding buttons, it has been mostly fixed in #7516. As the Elements API evolves, we will consider more opportunities to use it in our blocks, but I don't think we have anything actionable here right now.
