### ISSUE TITLE
slotfills for the cart items

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce-gutenberg-products-block#6579]
## Is your feature request related to a problem? Please describe.
I am working on adding support for my Free Gift Coupons plugin. In the shortcode checkout I am able to display a button and that button will then open a variable product's add to cart form via ajax. The form can be submitted and a variation selected. This is handy for folks using my plugin gift a free variable product, but allow the customer to chose the variation, ex: Free T-shirt, customer picks size.

![image](https://user-images.githubusercontent.com/507025/173826088-ae4b05fb-2973-44b4-9131-b7bdd3873995.png)

## Describe the solution you'd like
I'm not really sure yet. I am able to hack my way into showing a button, by filtering the Store API's `short_description` response... and this is about where I would want to display this button.

![image](https://user-images.githubusercontent.com/507025/173825811-ab6db683-92cf-475c-a237-e37c156929c3.png)

But doing it this way seems clunky since it's adding markup to the API response. I think it should be a React module so I can write the whole display variable form + update cart parts in React. In which case, do we need some slotFills in this area? And in the cart items in general? 

## Describe alternatives you've considered
Still need to explore if it's possible to maybe write in vanilla JS. Can I still listen for click events on the button rendered this way? Still very early in my thought processes.

**Comment by senadir** [comment]
Hey @helgatheviking ! Thank you for opening this issue :D

We won't be exploring slot fills in the items area yet, at least, this is not our plan, the plan is to turn that area in a block collection and for people to add blocks there, in that case, your code can be a block.

This might not work or make sense, in which, we will end up using slot fills, but we will add the ability to build custom content in that area.

For now, we have no possible workaround except building a separate block below the items area, bu that might not make sense for you flow.

**Comment by helgatheviking** [comment]
Thanks. A separate block below the items does not make sense for me since the new content is specific to the cart item row. I did want to log here that there's a need for extensibilty at this point.

**Comment by helgatheviking** [comment]
@tarhi-saad is there any linked code that closes this?

**Comment by tarhi-saad** [comment]
Hello @helgatheviking!

> We won't be exploring slot fills in the items area yet, at least, this is not our plan, the plan is to turn that area in a block collection and for people to add blocks there, in that case, your code can be a block.

Based on @senadir's response, slot fills aren't the solution we are pursuing now. We are focusing on inner blocks instead. So, I don't think there is value in keeping this issue open. 🙌 But, please let me know if you have any other suggestions to keep this issue open!

**Comment by helgatheviking** [comment]
@tarhi-saad thanks for letting me know! Any obvious issues I should keep an eye on? Is there docu somewhere on this?

**Comment by tarhi-saad** [comment]
Hi @helgatheviking! Thank you for being so interested and willing to help us improve the Woo Blocks project.

To improve the customization & extensibility of the C&C Blocks, we explored two main solutions:

- Slot fills (Insert a slot fill before and after each step)
- Inner Blocks (We brock down Cart/Checkout into a collection of inner blocks and satisfy all conditions)

Although the first solution (i.e., slot fills) was easy to reason about, it wasn't scalable, had too many implementation details, made refactoring really hard, had some missing functionality, etc. So, we found that the `inner blocks` solution was the best, most future-proof, and it bridged the gap between C&C and Gutenberg.

- You can find here [our first public announcement of the inner blocks feature](https://developer.woocommerce.com/2022/04/19/woocommerce-blocks-7-4-0-to-7-4-2-release-notes/).
- [Merged inner blocks related PRs](https://github.com/woocommerce/woocommerce-blocks/pulls?q=is%3Apr+inner+blocks+in%3Atitle+is%3Aclosed)
- [Open issues related to inner blocks](https://github.com/woocommerce/woocommerce-blocks/issues?q=is%3Aissue+is%3Aopen+inner+blocks++in%3Atitle)
