### ISSUE TITLE
Gutenberg + Woo > Blockify the Product Categories shortcode (and others) !

### ISSUE THREAD

**Issue by Marc-pi** [woocommerce/woocommerce-gutenberg-products-block#6583]
## The issue : end user vs agency feedback
Actually, the only way to display categories cards is to use the shortcode 
[product_categories] – Will display all your product categories.

End user do not understand why some features are not WYSIWYG like with already blockified features. It reduce Gutenberg adoption.

We need to explain them WP and Woo are in a "in between" status about Gutenberg adoption. 
Which brings friction.... Customer are more willing to use third part builders, and not Gutenberg. 

The usage of Woo with Gutenberg is harder (for those who already use actively the Gutenberg builder), we need to quickly build Block themes https://woocommerce.com/document/woocommerce-shortcodes/

## Proposed solution
Blockify residual Woo shortcodes so WooCommerce becomes the best great Gutenberg showcase !
Block options: 
* hide count
* display cat name on image or under 
* duotone, 
* cat level, 
* Nr of rows / columns
* etc.

Hope you are on the way to quickly finalize the blockification of Woo :-)

## Describe alternatives you've considered
There is indeed the "category list block", but the display is by list, not with cards.
Displaying a card list of categories is need for the homepage or landing pages.
Maybe we can extend available blocks...

## Additional context
https://woocommerce.com/document/woocommerce-shortcodes/#section-13

**Comment by albarin** [comment]
Hello @Marc-pi!
We have on our roadmap to add that Category Grid Block but currently, we do not have any estimated time for when it'll be available.
Meanwhile, you have the shortcode available as you mentioned, or you could also add a columns block and then a Featured Category block to each of the columns.

Thanks a lot for your feedback!
