### ISSUE TITLE
Products by Category: Adding CSS Class in Block Settings Results in Error

### ISSUE THREAD

**Issue by ivan-ottinger** [woocommerce/woocommerce-gutenberg-products-block#659]
When we add a custom class to the **Products by Category** block, the following error is displayed:

`Error loading block: Invalid parameter(s): attributes`

The issue doesn't seem to affect front-end in any way.

When we remove the custom class, the block will turn back to normal.

**To Reproduce**

1. Create a new page
2. Add **Products by Category** block
3. Enter random string to **Additional CSS Class** field in block settings.

**Expected behavior**
Block is normally rendered in editor.

**Screenshots**

Before adding the class:
![Screen Shot on 2019-06-28 at 13:46:57](https://user-images.githubusercontent.com/25105483/60340259-58d01500-99ab-11e9-9e6e-786c33b6210a.png)

After adding the class:
![Screen Shot on 2019-06-28 at 13:47:25](https://user-images.githubusercontent.com/25105483/60340260-58d01500-99ab-11e9-9041-cc899a96d043.png)

**WordPress**

Tested on WPCOM Atomic site.

* Core version: 5.2.2
* WooCommerce version: 3.6.4
* WooCommerce Blocks version: 2.2.0
* Site language: English
* Any other plugins installed: Not sure if this is relevant as I was able to reproduce this issue on several site with different set of plugins - but if necessary, I can add the list of plugins installed.

**Desktop**

* Browser: Google Chrome 
* Version 74.0.3729.169 (Official Build) (64-bit)

**Additional context**

Reported in #2140437-zen

**Comment by Aljullu** [comment]
Thanks for filling the issue @ivan-ottinger.

I could reproduce this too when working on #588. It affects all SSR blocks.
