### ISSUE TITLE
Custom Mini Cart block contents get covered by the admin bar

### ISSUE THREAD

**Issue by danieldudzic** [woocommerce/woocommerce-gutenberg-products-block#6594]
## Describe the bug

Custom Mini Cart block drawer contents are being covered by the admin bar 

## To reproduce

1. Use a block theme
2. Add the Mini Cart block 
3. Edit the Mini Cart block template
4. Add a custom block (for example a Paragraph) above the default Mini Cart contents

## Expected behavior

The custom content to display correctly under the admin bar

## Screenshots

**Expected**

![mini_cart_–_Reliable_Parrot](https://user-images.githubusercontent.com/905781/174317042-d6ae4d5b-fcbf-4d72-b66a-1430a95535df.jpg)

**What's happening**

![mini_cart_–_Reliable_Parrot](https://user-images.githubusercontent.com/905781/174316803-e1d06b31-fcb0-4b01-a24e-95853ae8afa2.jpg)

## Environment
Jurassic Ninja

### WordPress (please complete the following information):

-   Core version: 6.0
-   WooCommerce version: 6.6.0
-   WooCommerce Blocks version: 7.6.1

**Comment by Aljullu** [comment]
I'm wondering if instead of trying to fix this issue, we should focus on woocommerce/woocommerce#42659. To me, the issue here is that we shouldn't allow merchants to add blocks before or after the `Mini Cart Contents` block.

cc @albarin what do you think? Should we close this issue in favor of woocommerce/woocommerce#42659?

**Comment by albarin** [comment]
> cc @albarin what do you think? Should we close this issue in favor of woocommerce/woocommerce#42659?

Yes, makes total sense to me👌 I wasn't aware of https://github.com/woocommerce/woocommerce/issues/42659
