### ISSUE TITLE
Mini Cart block icon

### ISSUE THREAD

**Issue by vivialice** [woocommerce/woocommerce-gutenberg-products-block#6617]
Currently, the mini cart block is using the same icon as the Cart block. I have a modified version for the Mini Cart icon that I think would work better. 

References: 
<img width="545" alt="Screenshot 2022-06-22 at 13 32 28" src="https://user-images.githubusercontent.com/9888201/175044772-07edffc5-b597-4702-8eb4-5eed5ef59b97.png">

<img width="203" alt="Screenshot 2022-06-22 at 13 25 02" src="https://user-images.githubusercontent.com/9888201/175044794-833cf92c-bab7-4146-b404-8813a5f9ee55.png">
<br>
Suggested replacement: 

<img width="560" alt="Screenshot 2022-06-22 at 16 45 37" src="https://user-images.githubusercontent.com/9888201/175058714-67fb91c6-4c45-4e28-9ae3-ba4af289165a.png">

SVGs downloadable [here](https://cloudup.com/c6kbrsO3x04) and [here](https://cloudup.com/cVV0bNF1hg2). 

Let me know if you have any thoughts or comments!

**Comment by Marc-pi** [comment]
Would be fine to improve that so we let choose what icone between a small set (ex : Bag vs Cart)

**Comment by dashkevych** [comment]
It would be great to have also an option to replace default icon to better match overall design of the theme.

**Comment by ifrountas** [comment]
Is there currently a way to change the default block icon?
