### ISSUE TITLE
WooCommerce messages don't appear in block themes with Mini Cart block

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#6621]
WooCommerce messages that appear in some occasions to provide feedback to customers, don't show up in block themes.

## To reproduce

1. With a classic theme (ie: Storefront), go to a product page.
2. Add the product to your cart.
3. Notice a message is shown on top of the page: "Product has been added to your cart".

![imatge](https://user-images.githubusercontent.com/3616980/175261893-cc81e70a-d0ca-427b-9c18-8b8b3144895e.png)

4. Now switch to a block theme (ie: Twenty Twenty-Two), add the Mini Cart block to the header and go again to a product page.
5. Add the product to your cart.
6. Notice no message is shown on top of the page.

The same happens with any other messages:

![imatge](https://user-images.githubusercontent.com/3616980/175262435-755c254e-f967-44e5-841e-3ff1e26dbe5b.png)

## Expected behavior

The behavior with block themes should be the same as with classic themes.

**Comment by colorful-tones** [comment]
@Aljullu - I just pulled down the latest build and ran against a block theme I'm working on and the message displayed fine for me. 🤔 

- WP 6.0
- WooCommerce Blocks 8.0.0-dev
- WooCommerce 6.6.1

With my custom block theme active, steps I took: visit single product and click 'Add to Cart'. The page refreshes and I see verifying message: "Shirt – Green” has been added to your cart."

![Screen Shot 2022-06-24 at 6 17 29 PM](https://user-images.githubusercontent.com/405912/175701976-c4762c74-0822-4b66-ab8f-2e11f16a66d2.png)

**Comment by gigitux** [comment]
@colorful-tones I'm able to replicate the error if the Mini Cart Block is added to the page. Try to add it in the header or in the footer.

**Comment by Aljullu** [comment]
Good catch, I updated the testing steps specifying the Mini Cart block needs to be added to the header. :+1:
