### ISSUE TITLE
Markup is visible in checkout error notices when the error is caused by a PHP syntax error.

### ISSUE THREAD

**Issue by opr** [woocommerce/woocommerce-gutenberg-products-block#6628]
When a server-side error occurs during checkout, the error shown contains unrendered HTML/Markup.

To reproduce:
1. Add items to the cart and go to the Checkout block.
2. Open https://github.com/woocommerce/woocommerce-blocks/blob/029b379138906872dec3ed920fcb23d24404a3f2/src/StoreApi/Schemas/V1/CheckoutSchema.php#L26-L25 in your editor, introduce a syntax error.
3. Try to check out.
4. See the error with unrendered HTML.
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/5656702/175665298-d4080883-f392-456d-8aee-294d5e01383b.png">

**Comment by wavvves** [comment]
@opr I stopped mid-fixing this, to think about the issue origin. So, if CheckoutSchema.php has a syntax error, that will prevent the loading of the checkout page. The said error would have to be introduced between the time the user requests the checkout page, and tries to actually checkout.

So I went looking for another way to reproduce this, added an undefined function call to `get_checkout_response()` and got this:

![image](https://user-images.githubusercontent.com/17236129/181272279-d32e5294-ba53-41e2-9517-862230e6c4a6.png)

On the shortcode version, the checkout page displays properly, and we can follow through with a valid order (although there is an output about the fatal error on the order confirmation page):

![image](https://user-images.githubusercontent.com/17236129/181272699-ab9b644d-4191-4616-959a-e3051bb19e41.png)

Should this be added to the scope of the task (the difference between shortcode and block version)?

The confusing "order received + error" should be reported as a separate issue, as it is relative to the shortcode version. 

It is probably possible to find a way to reproduce exactly the problem described, I need to find a file only loaded on the checkout endpoint.

Also, we don't seem to be handling non-2xx responses on our frontend (which would solve the original issue you proposed, as we need to give out a generic error, thus not worrying about the HTML in the output), and that would probably be in scope for this issue.

**Comment by opr** [comment]
Hi @wavvves - The original bug report is less about the cause, more about the result. Ultimately we don't want markup in these error messages, **no matter how they appear**. The only reason the report suggests making a syntax error is because it's a quick and easy way to introduce an error that will cause the server to respond with something containing markup. Those instructions were not meant to describe the cause of the bug.

> The said error would have to be introduced between the time the user requests the checkout page, and tries to actually checkout.

As there is a nonzero chance of this happening, we should cater for it.

**Comment by wavvves** [comment]
What about the other things I mentioned, like the discrepancy between shortcode and block version and non-2xx handling, would that be a blocker for adding this to core? @ralucaStan 

Another thing @opr, stripping markup would have a problem with links, producing a confusing msg to the user (like the example). How do you think we should handle that?

**Comment by opr** [comment]
> What about the other things I mentioned, like the discrepancy between shortcode and block version and non-2xx handling, would that be a blocker for adding this to core? @ralucaStan

Sorry, replied too eagerly:

> On the shortcode version, the checkout page displays properly, and we can follow through with a valid order (although there is an output about the fatal error on the order confirmation page):.
Should this be added to the scope of the task (the difference between shortcode and block version)?

Definitely worth investigating _why_ it happens on the shortcode version, and figuring out why it is possible to place the order. Compare that to Store API and see if we have the same flow and same failure modes. 

If the error happens between the order being placed, and the response being sent then yes we should look into this and figure out how to handle it, otherwise we should just show the error and prevent checkout I think, I'll let Raluca confirm though.

> Another thing @opr, stripping markup would have a problem with links, producing a confusing msg to the user (like the example). How do you think we should handle that?

Let's look into how we can render this HTML correctly on the front end. I don't think we should strip any of the tags. We will most likely need to use `RawHTML` from `@wordpress/element` to do this.

> as we need to give out a generic error, thus not worrying about the HTML in the output)

Why is this true? Shoudn't we display whatever error the server wants us to on a non-200 response?

**Comment by wavvves** [comment]
> Why is this true? Shouldn't we display whatever error the server wants us to on a non-200 response?

Sorry, I didn't explain very well, I was referring to 5xx errors without valid error output (unexpected throws, errors occurring outside the application layer, etc)

> Let's look into how we can render this HTML correctly...

Glad this has come up, as I understood the purpose of the task wrongly 😅. On it 👍🏼

**Comment by opr** [comment]
> Sorry, I didn't explain very well, I was referring to 5xx errors without valid error output (unexpected throws, errors occurring outside the application layer, etc)

Ah yes, we have some generic text we could use for this: `Something went wrong. Please contact us to get assistance.` I think that will be fine for any "unspecified" error.

**Comment by wavvves** [comment]
@opr I made some changes on the PR 🙂
