### ISSUE TITLE
Update shipping as billing should be handled at store level or useShippingAsBilling should be exposed.

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#6641]
As of right now, you can set shipping and billing addresses from the data store using `setShippingAddress`, however, you don't have access to the `useShippingAsBilling` value that lives on the checkout state data store, so you can't really know if you should be setting billing as well.

I suggest we either expose `useShippingAsBilling` (probably done on the work you're doing @alexflorisca?) or have it managed at the data store level, with option 1 being more preferable.

**Comment by alexflorisca** [comment]
Yes, `useShippingAsBilling` will be available on the new checkout data store after we release the data store migration project
