### ISSUE TITLE
Payment methods not set in editor

### ISSUE THREAD

**Issue by alexflorisca** [woocommerce/woocommerce-gutenberg-products-block#6655]
**This is a leftover todo for the [Feature: Data Store Migration - Payments](https://github.com/woocommerce/woocommerce-blocks/pull/6619/files#) PR, it's not an issue on trunk**

When loading the Checkout block in the editor, on the `feature/data-store-refactor-payments` branch, the payment methods do not display, because the `availablePaymentMethods` state variable is not yet set at the time the editor is loaded.

**Comment by tarhi-saad** [comment]
The bug is fixed in this commit: https://github.com/woocommerce/woocommerce-blocks/pull/6619/commits/d944a03302b10da4d7011f97c3e7058e19f50c56
