### ISSUE TITLE
Woo Template Descriptions 

### ISSUE THREAD

**Issue by vivialice** [woocommerce/woocommerce-gutenberg-products-block#6659]
Hi folks! I was reviewing the Woo templates and I think we could include some descriptions for them. Currently, just the search results template has a description. 

To kick this off, I have written some suggestions - which are open for feedback. 

Current list: 

<img width="833" alt="wootemplates" src="https://user-images.githubusercontent.com/9888201/177520319-28a64e93-7cfa-4b4a-a826-6d73b8d6786e.png">

Suggestions:

**Product Search Results** 
~Template used to display search results for products.~
Displays search results for your store. 

**Products by Tag**
Displays products filtered by a tag. 

**Product Catalog**
Displays your products. 

**Single Product**
Displays a single product. 

**Products by Category**
Displays products filtered by a category. 

✌️

**Comment by gigitux** [comment]
Hi! Thanks for opening the issue!

Are you sure that you are using the last version of the plugin? With #6345 @danieldudzic adds the description.

![image](https://user-images.githubusercontent.com/4463174/177554760-6643b0a6-6247-4318-9fc0-11b14b14de4e.png)

In every case, we need to update descriptions 👍

**Comment by vivialice** [comment]
In that case I am definitely not using the last version 😓
