### ISSUE TITLE
Going from draft version to "Ready for review" PR does not trigger actions

### ISSUE THREAD

**Issue by opr** [woocommerce/woocommerce-gutenberg-products-block#6671]
When you open a PR but save it as a draft, it does not trigger the actions we usually run on PRs when opening it as "ready for review".

To replicate:
1. Push some code on a branch
2. Create a PR but open it in draft mode
3. Convert the PR to "ready to review"
4. Observe the actions that run, note the unit tests/E2E tests etc. do not run until a new commit is pushed.

**Comment by audreyspency** [comment]
is this still relevant till this date

**Comment by mikejolley** [comment]
Closing due to pca54o-6Dz-p2
