### ISSUE TITLE
Unable to select saved token radio button, after selecting another payment method

### ISSUE THREAD

**Issue by achyuthajoy** [woocommerce/woocommerce-gutenberg-products-block#6678]
## Describe the bug

With a saved WooCommerce Payments token, after loading the blocks checkout page the saved token is selected by default. However, if we choose to use a new payment method and tries to select the saved token again, it fails to pick the saved one with the console error `Uncaught TypeError: l is not a function`.

I haven't tried with any other payment gateways.

## To reproduce

Screencast - https://d.pr/v/Y4g2tP

1. Install, activate & setup WooCommerce Payments
2. Add any product to cart and complete checkout using any test card. Make sure to check the option `Save payment information to my account for future purchases.`
3. Add another product to cart and go to checkout. By default, the saved token will be selected. Try using another payment method and then click on the saved token. Notice that the saved token is not selected and console throws the error mentioned above.

## Expected behavior

The user should be able to choose the saved token if they try to use any other payment options and decide against it.

## Screenshots

<img width="1792" alt="Screenshot 2022-07-12 at 6 49 33 PM" src="https://user-images.githubusercontent.com/1161872/178500928-f15977d6-403b-4c56-aa72-4faaafa967cc.png">

### WordPress (please complete the following information):

-   Core version: 6.0
-   WooCommerce version: 6.6.1
-   WooCommerce Blocks version: 8.0.0
-   Site language: English
-   Any other plugins installed: WooCommerce Payments 4.4.0

### Desktop (please complete the following information):

-   OS: macOs
-   Browser Firefox
-   Version 103.0b4

**Comment by tarhi-saad** [comment]
I was able to reproduce the bug following the instructions above! I'll remove the `high priority` label since this bug can be easily detected by the shopper and a simple page refresh can fix the issue.

**Comment by rafaelzaleski** [comment]
If you have more than one payment method saved, you won't be able to switch the payment method used to pay for the order.

**Comment by c-shultz** [comment]
>I was able to reproduce the bug following the instructions above! I'll remove the high priority label since this bug can be easily detected by the shopper and a simple page refresh can fix the issue.

@ralucaStan I'm not as familiar as I should be on your bug prioritization, but this one has been showing up in WooCommerce Payments testing recently, so it would be good to see this get a good amount of priority so it can get fixed relatively soon.

**Comment by ralucaStan** [comment]
Hey @c-shultz,
this is indeed a regression report that slipped us. 
The good news is that we fixed this yesterday and the fix is now part of WooCommerce Blocks 8.2.1.
