### ISSUE TITLE
PayPal & Custom Field

### ISSUE THREAD

**Issue by vincent-sensei** [woocommerce/woocommerce-gutenberg-products-block#6679]
## Is your feature request related to a problem? Please describe.

**Checkout Block for woocommerce:**

1. the PayPal payment method does not appear in the block (woocommerce / automatic plugin)

2. in the block it is not possible to add custom fields (for example in Italy the tax code is mandatory for individuals and the VAT number for companies that buy)

3. in the block you start by entering the shipping data.4. 

## Describe the solution you'd like

1. adding paypal
2. adding custom fields
3. data entry starting from billing and not from shipping so as not to have problems with lack of billing data (tax code and VAT number)

**Comment by tarhi-saad** [comment]
Hi @vincent-sensei! I didn't understand the issue you're describing. It would be great to write us in English instead and to follow the issue template by answering the questions above!

**Comment by vincent-sensei** [comment]
hi @tarhi-saad  , sorry for the wrong post and my english. I hope it gets better now.

Is your feature request related to a problem? Please describe.

**Checkout Block for woocommerce:**
1. the PayPal payment method does not appear in the block (woocommerce / automatic plugin)

2. in the block it is not possible to add custom fields (for example in Italy the tax code is mandatory for individuals and the VAT number for companies that buy)

3. in the block you start by entering the shipping data.4. 

Describe the solution you'd like

1. adding paypal
2. adding custom fields
3. data entry starting from billing and not from shipping so as not to have problems with lack of billing data (tax code and VAT number)
A clear and concise description of any alternative solutions or features you've considered.

**Comment by tarhi-saad** [comment]
Hi there @vincent-sensei 👋

> the PayPal payment method does not appear in the block (woocommerce / automatic plugin)

Thanks for taking the time to make us aware that the PayPal payment method isn’t working with the Checkout and Cart blocks. These Blocks are a beta feature to optimize for faster checkout and it’s expected that some existing Woo Extensions that integrate with the current checkout flow in WooCommerce core will not work with the blocks.

Currently, it’s up to extension developers to add support for the new checkout flow offered via the Cart and Checkout Blocks. We have some [documentation for Third-party developers](https://href.li/?https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs#third-party-developers) and some [Developer Resources](https://href.li/?https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs#developer-resources) available to help with their integration efforts.

Your best course of action now if you are using a payment method that isn’t working with the blocks is to notify the developer of the extension and ask if they can add support.

Until then, you can keep on top of the [status of the Cart & Checkout Blocks in this documentation](https://href.li/?https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/).

> in the block it is not possible to add custom fields (for example in Italy the tax code is mandatory for individuals and the VAT number for companies that buy)

We are aware of this limitation and we are currently working on adding extensibility for the blocks. There is a [work in progress to add support for checking out with a EU vat number field using the checkout block](234-gh-woocommerce/woocommerce-eu-vat-number#issuecomment-1172918727) from the [EU VAT Number extension](https://woocommerce.com/products/eu-vat-number/).

> data entry starting from billing and not from shipping so as not to have problems with lack of billing data (tax code and VAT number)

Thank you for the suggestion and the interest you are showing in the Cart & Checkout blocks. For now, we don't have this particular issue. There isn't a billing-specific field that can't be found in the shipping section. And for the case of the VAT number (It's still a [work in progress](234-gh-woocommerce/woocommerce-eu-vat-number)), we decided to have it as it's own step outside of the billing section. Ex:

<img src="https://user-images.githubusercontent.com/14235870/185433776-0c52b059-597b-4662-ba59-ee0c948bf2ac.png" width="500">

I'll close this issue, but feel free to reopen it or open a new one if you have an example of a specific billing field that can be missed during checkout or if you have any other bug reports or suggestions.
