### ISSUE TITLE
Add the Release Schedules page in GitHub and implement the automation to fill the fields automatically in the table after the release.

### ISSUE THREAD

**Issue by gigitux** [woocommerce/woocommerce-gutenberg-products-block#6681]
To continue the automation process for the release, we should move the release schedules page to GitHub in this way:
- the release roadmap is public
- We can add an automation process that, after the release, fills the field in the release schedules page automatically. In this way, we can remove [these two steps](https://github.com/woocommerce/woocommerce-blocks/blob/ce9d8b38b832525c155871fbf12f1ebdcae58906/.github/release-initial-checklist.md/#L89-L90) for our release process handling.

**Comment by mikejolley** [comment]
Closing due to pca54o-6Dz-p2
