### ISSUE TITLE
Add GithHub Jobs that runs E2E tests on the old version of WordPress

### ISSUE THREAD

**Issue by gigitux** [woocommerce/woocommerce-gutenberg-products-block#6686]
To prevent errors on WooCommerce Core (e.g. #6590) when it is installed on the old versions of WordPress, we should run the E2E tests on the old versions of WordPress supported by WooCommerce.

PR #6685 is an attempt to fix this issue, but we should investigate why some tests fail on older versions of WordPress.

**Comment by ralucaStan** [comment]
Keep in mind this comment from @nielslange from an internal talk per0F9-9l-p2#comment-80

**Comment by mikejolley** [comment]
Closing due to pca54o-6Dz-p2
