### ISSUE TITLE
Cart Block: Order summary inner blocks controls appear on the left side of the screen

### ISSUE THREAD

**Issue by ralucaStan** [woocommerce/woocommerce-gutenberg-products-block#6698]
## Describe the bug

Cart Block: Order summary inner blocks controls appear on the left side of the screen

## To reproduce

Steps to reproduce the behaviour:

1. Go to the Cart Block
2. Click on the fee inner block
3. Notice that the controls appear on the left side

## Expected behaviour

The controls should appear aligned with the left margin of the Order summary block. Like in the Checkout block.

## Screenshots
<img width="827" alt="Screenshot 2022-07-18 at 17 45 35" src="https://user-images.githubusercontent.com/1628454/179542267-fd935aff-59c7-4b0f-a490-5d6e76cdd380.png">

**Comment by tarhi-saad** [comment]
Hi @tarunvijwani! I've done some debugging and found a potential solution, but there are still some questions to be answered:

### Current behavior
 
The current behavior isn't a bug but an option: the toolbars of all child Blocks (applied deeply, recursive) can have their toolbars "captured" and shown on the Block which is consuming `InnerBlocks`.

And the [option responsible for this change of behavior](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/inner-blocks/README.md) is `__experimentalCaptureToolbars`.

### Potential fixe

I added the option `__experimentalCaptureToolbars` and set it to `false` as a prop of the `InnerBlocks` component in the `assets/js/blocks/cart/edit.js` file:

```js
<CartProvider>
	<InnerBlocks
		allowedBlocks={ ALLOWED_BLOCKS }
		template={ defaultTemplate }
		templateLock={ false }
		__experimentalCaptureToolbars={ false } // This is the line in question!
	/>
</CartProvider>
```

![image](https://user-images.githubusercontent.com/14235870/185998474-5c20c27a-7881-45b3-b0b8-5022026550a6.png)


### Remaining questions

The default value of `__experimentalCaptureToolbars` is supposed to be `false`, so I was wondering how come this option has a value of `true`:

<img width="765" alt="image" src="https://user-images.githubusercontent.com/14235870/185996385-3c257147-d421-48ce-bd4b-2d2e410245f5.png">

I console logged this value from [this file](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-tools/selected-block-popover.js#L177).

After applying the above fixe, the `templateLock` value changes as well for some reason:

<img width="732" alt="image" src="https://user-images.githubusercontent.com/14235870/185997587-efda9a8d-003b-4630-9273-72344a595127.png">

**Comment by tarunvijwani** [comment]
This is very useful. Thank you so much @tarhi-saad. 🙂
