### ISSUE TITLE
Remove the Cart and Checkout Blocks from behind the feature flag

### ISSUE THREAD

**Issue by ralucaStan** [woocommerce/woocommerce-gutenberg-products-block#6699]
This issue is for tracking and preparing the Cart and Checkout Blocks to be enabled in [WooCommerce](https://wordpress.org/plugins/woocommerce) plugin.

## Pre-release steps

TBD

## Release steps

- [ ] Branch: starting from `trunk`, create a new branch for block release. (Note: Don't use the `release/` prefix for the branch name because it will trigger the release workflow.)
- [ ] Changing the register block function from `registerFeaturePluginBlockType()` to `registerBlockType()`.
- [ ] Moving the block out of the `is_feature_plugin_build()` check in `src/BlockTypesController.php`.

## Verification steps

- [ ] Update `woocommerce_blocks_phase` to 1 in `.blocks.ini`.
- [ ] Provide basic smoke testing steps for both Cart and Checkout blocks in the PR for this ticket
- [ ] Test the plugin with both block and classic themes to see if a new block is included and functions properly.
- [ ] If the block contains translation, test if the translation works with both block and classic themes.

**Comment by Marc-pi** [comment]
well, would be a nice big step for pushing ahead the Woo FSE adoption ;-)
But don't forget that  [WooCommerce PayPal Payments]( https://woocommerce.com/document/cart-checkout-blocks-support-status/) is not compatible with Woo Cart/Checkout Blocks.

see https://github.com/woocommerce/woocommerce-paypal-payments/issues/211

> Support for Cart and Checkout Blocks is planned but it will take longer than originally anticipated. When the new Blocks are no longer a feature plugin and become a core part of WooCommerce, then PayPal Payments will certainly be ready for it. But there is currently no timeframe for support of the Blocks feature plugin. It will eventually happen but that's all we can say for the moment.

what's the team plan ?
as reminder, [Paypal Standard](https://developer.woocommerce.com/2021/07/12/developer-advisory-paypal-standard-will-be-hidden-on-new-installs/) is hidden for new installs but compatible. At minimum, please warn users, and as asked for in https://github.com/woocommerce/woocommerce-paypal-payments/issues/211, please add a warning in the new gateway settings (backoffice). But would be nice that the new Paypal plugin will be ready when the feature flag is turned off !

**Comment by ralucaStan** [comment]
Hi @Marc-pi,

thank you so much for your active feedback and involvement.
We can't speak for [WooCommerce PayPal Payments](https://woocommerce.com/document/cart-checkout-blocks-support-status/)'s team integration plans but on the Cart & Checkout Blocks' side we are doing our best to warn users about possible incompatibilities:
- we are tracking the incompatibility in the repo for better visibility [WooCommerce PayPal Payments doesn't work with the Cart & Checkout Blocks #6816](https://github.com/woocommerce/woocommerce-blocks/issues/6816)
- we will show an alert that warns about possible incompatibilities (in https://github.com/woocommerce/woocommerce-blocks/issues/6851)
- we will keep an active list of incompatible extensions [Incompatible Extensions](https://woocommerce.com/document/cart-checkout-blocks-support-status/#section-7)
