### ISSUE TITLE
Mention that we prefer importing from `@wordpress/element` instead of `react`

### ISSUE THREAD

**Issue by sunyatasattva** [woocommerce/woocommerce-gutenberg-products-block#6732]
In our repo we want to try to avoid importing directly from `react` as a policy. Instead, developers should use `@wordpress/element`. I was informed of this by @Aljullu on [this PR](https://github.com/woocommerce/woocommerce-blocks/pull/6551), but I hadn't noticed myself, as our repo is a bit inconsistent (92 instances of importing from `react` vs 154 of importing from `@wordpress/element`).

However, the philosophy behind this is very solid: we want an abstraction layer so we don't have to rely on a specific underlying implementation. As such, me and @Aljullu agree that this preference should be indicated somewhere in the repo docs, and—I should add—we should perhaps migrate all the current `react` imports to `@wordpress/element`.

**Comment by gigitux** [comment]
Thanks for opening this issue, @sunyatasattva! 
I think that it makes sense to add a dedicated [eslint rule as in Gutenberg](https://github.com/WordPress/gutenberg/blob/95816949e28a6ec1c6fc0bdc3c31432c98a22e44/.eslintrc.js/#L190-L202).

**Comment by sunyatasattva** [comment]
Yiss please
