### ISSUE TITLE
Payment gateway not working

### ISSUE THREAD

**Issue by Gilbennun2** [woocommerce/woocommerce-gutenberg-products-block#6762]
## Describe the bug

Hello guys,
Im not sure but you do not support all payment gateways? I would like to know if there is any solution for implementing a gateway that is not currently supported(maybe?), this plugin is the only solution that exists for a convenient and clean ordering process. I use payplus payment gateway (Very popular payment gateway in Israel).

## To reproduce

See error: There are no payment methods available. This may be an error on our side. Please contact us if you need any help placing your order.

## Environment

-   Core version: 6.01
-   Gutenberg version (if installed): [e.g. 12.0.0]
-   WooCommerce version: 6.7
-   WooCommerce Blocks version: 8.1
-   Site language: English
-   Any other plugins installed: Elementor
### Desktop (please complete the following information):

-   OS: macOS
-   Browser: chrome

### Smartphone (please complete the following information):

-   Device: iPhone 13 Pro
-   OS: ios15

**Comment by nielslange** [comment]
Hello @Gilbennun2 👋
 
Thanks for taking the time to make us aware that [PayPlus Payment Gateway](https://wordpress.org/plugins/payplus-payment-gateway/) isn't working with the Checkout and Cart blocks. These blocks are still in early access (via the feature plugin) and it's expected that some existing Woo Extensions that integrate with the current checkout flow in WooCommerce core will not work with the blocks.
 
Currently, it's up to payment method extension developers to add support for the new checkout flow offered via the cart and checkout blocks. We have some [documentation on that here](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/checkout-payment-methods/payment-method-integration.md), and you can also point them to [this post](https://developer.woocommerce.com/2021/03/15/integrating-your-payment-method-with-cart-and-checkout-blocks/).
 
Your best course of action right now if you are using a payment method that isn't working with the blocks is to notify the developer of the extension and ask if they can add support.
 
Until then you can keep on top of the [status of the Cart & Checkout Blocks in this documentation](https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/).
