### ISSUE TITLE
Category filtering

### ISSUE THREAD

**Issue by TatjanaDjurdjevic** [woocommerce/woocommerce-gutenberg-products-block#6775]
## Is your feature request related to a problem? Please describe.
When using the API it would be really useful to be able to fetch only parent categories, and also to fetch only children of one parent category (eg. list only children of category cosmetic). 
Are there any plans to expand the API so categories can be filtered by parent_id?

## Describe the solution you'd like
Any API endpoint, that can query categories by parent_id.

**Comment by albarin** [comment]
Hello @TatjanaDjurdjevic, thanks for reaching out!
You can fetch categories by parent id using the [`List all product categories`](https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-product-categories) endpoint with the `parent` parameter.

For example:`/wp-json/wc/v3/products/categories?parent=16`, would give you all the children categories of the category with `id=16`.
For retrieving only parent categories you could do `/wp-json/wc/v3/products/categories?parent=0`.

I hope this helps, please contact us again in case we can help you further. Thanks!!

**Comment by TatjanaDjurdjevic** [comment]
Hello @albarin, thanks for the quick replay :) 

Actually we are developing a client application, not a server integration, so we cannot use woo commerce rest-api (don't want to expose admin api like that).

So there are no plans in the future to add more queries for categories in store rest api?
