### ISSUE TITLE
Taxes in Products

### ISSUE THREAD

**Issue by TatjanaDjurdjevic** [woocommerce/woocommerce-gutenberg-products-block#6778]
## Is your feature request related to a problem? Please describe.
When fetching the products via API `wp-json/wc/store/v1/products` there are no information about tax class of the product, or tax applied to the prices of the product. You can fetch taxes from API only after adding item to the cart. 
Are there any plans to expand API to add that information?

**Comment by albarin** [comment]
Hello @TatjanaDjurdjevic, thanks for reaching out!
You can find that `tax_class` and `tax_status` information on the v3 of the API using the [`List all products`](https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products) and the [`Retrieve a product`](https://woocommerce.github.io/woocommerce-rest-api-docs/#retrieve-a-product) endpoints.
Let us know if that helps, thanks!
