### ISSUE TITLE
Reviews Allowed

### ISSUE THREAD

**Issue by TatjanaDjurdjevic** [woocommerce/woocommerce-gutenberg-products-block#6779]
## Is your feature request related to a problem? Please describe.
When fetching products via API, eg. `wp-json/wc/store/v1/products `products that don't have reviews allowed, return
```
"average_rating": "0",
"review_count": 0,
```
Are there any plans to add is_reviews_allowed field?

**Comment by albarin** [comment]
Hello @TatjanaDjurdjevic, thanks for reaching out!
In this case, we recommend you to use this endpoint from the WooCommerce Rest API `/wp-json/wc/v3/products` to retrieve products, you will see you get back a `reviews_allowed` property for each product.
Hope it helps! Thanks!
