### ISSUE TITLE
8.0.0 & 8.1.0 Prevent Selection of Saved Cards

### ISSUE THREAD

**Issue by Stella3** [woocommerce/woocommerce-gutenberg-products-block#6783]
Since 8.0.0 and including 8.1.0, it is not possible to select a saved card other than the pre-selected 1st saved card on the list. The radio buttons simply don't react. 

We have heard this complaint with users on iPhone, Android, and Windows.

Rolling back to 7.9.0 fixes the issue. 

Behavior is the same with both WooCommerce Stripe Gateway 6.4.3 & Payment Plugins for Stripe WooCommerce 3.3.24

![image](https://user-images.githubusercontent.com/19824054/181583640-98ec8dac-f98d-4e7f-98a0-fa12af4da371.png)

`
### WordPress Environment ###

WC Version: 6.7.0
REST API Version: ✔ 6.7.0
WC Blocks Version: ✔ 7.9.0
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.1
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Flywheel/5.1.0
PHP Version: 7.4.30
PHP Post Max Size: 300 MB
PHP Time Limit: 178
PHP Max Input Vars: 10000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 5.7.37-google
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.7.0
WC Database Prefix: wp_fo40na56ca_
Total Database Size: 167.12MB
Database Data Size: 120.63MB
Database Index Size: 46.49MB
wp_fo40na56ca_woocommerce_sessions: Data: 0.17MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fo40na56ca_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_fo40na56ca_woocommerce_order_items: Data: 1.52MB + Index: 0.25MB + Engine InnoDB
wp_fo40na56ca_woocommerce_order_itemmeta: Data: 5.52MB + Index: 7.03MB + Engine InnoDB
wp_fo40na56ca_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_fo40na56ca_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fo40na56ca_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fo40na56ca_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_woocommerce_payment_tokens: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_woocommerce_payment_tokenmeta: Data: 0.19MB + Index: 0.20MB + Engine InnoDB
wp_fo40na56ca_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_actionscheduler_actions: Data: 1.02MB + Index: 0.94MB + Engine InnoDB
wp_fo40na56ca_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_actionscheduler_logs: Data: 0.52MB + Index: 0.47MB + Engine InnoDB
wp_fo40na56ca_aryo_activity_log: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_atum_order_itemmeta: Data: 0.17MB + Index: 0.16MB + Engine InnoDB
wp_fo40na56ca_atum_order_items: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_atum_product_data: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_fo40na56ca_commentmeta: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
wp_fo40na56ca_comments: Data: 4.52MB + Index: 3.53MB + Engine InnoDB
wp_fo40na56ca_elfsight_instagram_feed_cache: Data: 16.52MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_elfsight_instagram_feed_ig_user: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_elfsight_instagram_feed_user: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_elfsight_instagram_feed_widgets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_mailster_actions: Data: 0.28MB + Index: 0.69MB + Engine InnoDB
wp_fo40na56ca_mailster_action_bounces: Data: 0.11MB + Index: 0.05MB + Engine InnoDB
wp_fo40na56ca_mailster_action_clicks: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_fo40na56ca_mailster_action_errors: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_fo40na56ca_mailster_action_opens: Data: 0.23MB + Index: 0.48MB + Engine InnoDB
wp_fo40na56ca_mailster_action_sent: Data: 0.50MB + Index: 0.94MB + Engine InnoDB
wp_fo40na56ca_mailster_action_unsubs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_fo40na56ca_mailster_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_mailster_forms_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fo40na56ca_mailster_forms_tags: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fo40na56ca_mailster_form_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_mailster_links: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_mailster_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fo40na56ca_mailster_lists_subscribers: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_fo40na56ca_mailster_queue: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_fo40na56ca_mailster_subscribers: Data: 0.13MB + Index: 0.14MB + Engine InnoDB
wp_fo40na56ca_mailster_subscriber_fields: Data: 0.09MB + Index: 0.20MB + Engine InnoDB
wp_fo40na56ca_mailster_subscriber_meta: Data: 1.52MB + Index: 2.56MB + Engine InnoDB
wp_fo40na56ca_mailster_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_mailster_tags_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fo40na56ca_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_options: Data: 11.28MB + Index: 0.39MB + Engine InnoDB
wp_fo40na56ca_postmeta: Data: 31.55MB + Index: 17.06MB + Engine InnoDB
wp_fo40na56ca_posts: Data: 9.52MB + Index: 0.80MB + Engine InnoDB
wp_fo40na56ca_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fo40na56ca_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fo40na56ca_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fo40na56ca_term_relationships: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fo40na56ca_usermeta: Data: 5.52MB + Index: 7.03MB + Engine InnoDB
wp_fo40na56ca_users: Data: 0.13MB + Index: 0.14MB + Engine InnoDB
wp_fo40na56ca_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_wcpdf_packing_slip_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_wc_customer_lookup: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_fo40na56ca_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fo40na56ca_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fo40na56ca_wc_order_product_lookup: Data: 1.52MB + Index: 0.67MB + Engine InnoDB
wp_fo40na56ca_wc_order_stats: Data: 0.31MB + Index: 0.30MB + Engine InnoDB
wp_fo40na56ca_wc_order_tax_lookup: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_fo40na56ca_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_wc_product_meta_lookup: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_fo40na56ca_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_wc_reserved_stock: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_fo40na56ca_wfconfig: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_wffilemods: Data: 12.55MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_wfhits: Data: 1.02MB + Index: 0.28MB + Engine InnoDB
wp_fo40na56ca_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_fo40na56ca_wfknownfilelist: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_wflogins: Data: 0.48MB + Index: 0.16MB + Engine InnoDB
wp_fo40na56ca_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_fo40na56ca_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_fo40na56ca_wfstatus: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
wp_fo40na56ca_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 244
atum_purchase_order: 6
atum_supplier: 4
b2bking_conversation: 29
b2bking_custom_field: 15
b2bking_custom_role: 5
b2bking_group: 7
b2bking_rule: 5
cs_footer: 1
cs_header: 13
cs_template: 7
custom_css: 1
custom-css-js: 1
nav_menu_item: 8
newsletter: 39
oembed_cache: 1
page: 24
post: 2
postman_sent_mail: 250
product: 55
product_variation: 114
revision: 261
shop_coupon: 36
shop_order: 2913
shop_order_refund: 99
woo_mb_template: 17
wp_global_styles: 1
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (27) ###

Activity Log: by Activity Log Team – 2.8.3
ATUM Inventory Management for WooCommerce: by Stock Management Labs™ – 1.9.20.2
B2BKing Pro: by WebWizards – 4.1.82
B2BKing Core: by WebWizards – 4.0.0
Code Snippets: by Code Snippets Pro – 3.2.0
Contact Form 7: by Takayuki Miyoshi – 5.6.1
Elfsight Instagram Feed CC: by Elfsight – 4.0.3
GA Google Analytics: by Jeff Starr – 20220517
Jetpack: by Automattic – 11.1.2
Mailster SendGrid Integration: by EverPress – 2.1
Mailster - Email Newsletter Plugin for WordPress: by EverPress – 3.1.6
Post SMTP: by Post SMTP – 2.1.3
Superfly Menu: by Looks Awesome – 5.0.14
User Switching: by John Blackbourn & contributors – 1.6.0
WooCommerce Blocks: by Automattic – 7.9.0
Payment Plugins for Stripe WooCommerce: by Payment Plugins
support@paymentplugins.com – 3.3.24

WooCommerce PDF Invoices & Packing Slips: by WP Overnight – 3.0.0
WooCommerce PDF Invoices & Packing Slips Professional: by WP Overnight – 2.12.1
WooCommerce Shipping & Tax: by WooCommerce – 1.26.2
WooCommerce - ShipStation Integration: by WooCommerce – 4.1.48
WooCommerce: by Automattic – 6.7.0
WooCommerce Email Customizer with Drag and Drop Email Builder: by Flycart Technologies LLP – 1.5.16
Wordfence Security: by Wordfence – 7.6.0
WP File Manager: by mndpsingh287 – 7.1.6
SEOPress: by SEOPress – 5.8.0.5
WPS Hide Login: by WPServeur
NicolasKulka
wpformation – 1.9.6

XforWooCommerce: by XforWooCommerce – 1.7.0

### Inactive Plugins (3) ###

Query Monitor: by John Blackbourn – 3.9.0
WooCommerce Blocks: by Automattic – 8.1.0
WooCommerce Stripe Gateway: by WooCommerce – 6.4.3

### Dropin Plugins (1) ###

db-error.php: db-error.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #109 - /shop/
Cart: #110 - /cart/
Checkout: #111 - /checkout/
My account: #112 - /my-account/
Terms and conditions: #132 - /terms-conditions/

### Theme ###

Name: Pro
Version: 5.1.5
Author URL: https://theme.co
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
settings

Daily Cron: ✔ Next scheduled: 2022-07-29 00:07:34 -04:00
Options: ✔
Notes: 94
Onboarding: completed

### Action Scheduler ###

Complete: 2,537
Oldest: 2022-06-27 13:37:32 -0400
Newest: 2022-07-28 12:29:34 -0400

Pending: 4
Oldest: 2022-07-28 20:14:47 -0400
Newest: 2022-07-29 10:54:16 -0400

### Status report information ###

Generated at: 2022-07-28 12:37:27 -04:00
`

**Comment by tobinfekkes** [comment]
Can confirm this as well, but with Authorize.net. Our customer service was first notified yesterday.
<img width="261" alt="image" src="https://user-images.githubusercontent.com/6226162/181803528-3f7d3a72-cf58-460a-89f3-b3c43079659d.png">

**Comment by wavvves** [comment]
Hi @Stella3 @tobinfekkes, thank you for reporting this.
We have confirmed this bug and are currently working on releasing a fix for it 👍🏼

**Comment by wavvves** [comment]
Hello @Stella3 @tobinfekkes,
we managed to fix this issue and it was released in [Woocommerce Blocks 8.2.1](https://wordpress.org/plugins/woo-gutenberg-products-block/). 

> #### Bug Fixes
> 
> - Fixed an issue where shoppers could not switch between different saved payment methods. ([6825](https://github.com/woocommerce/woocommerce-blocks/pull/6825))
