### ISSUE TITLE
Windows development issue - `SassError: This file is already being loaded.`

### ISSUE THREAD

**Issue by opr** [woocommerce/woocommerce-gutenberg-products-block#6797]
## Describe the bug
When running `npm run build` on Windows 10 or 11, it shows ` SassError: This file is already being loaded.` and the project cannot build. I suspect this is caused by Windows directory separators not being tested correctly.

This was also reported here (https://github.com/woocommerce/woocommerce-blocks/issues/6029#issuecomment-1067905345) but the user who found the issue didn't make the follow up ticket.

There is another issue where building sass files from the `node_modules` directory doesn't work and that is also caused by the  directory separators.

## To reproduce

1. Load Windows 10 or 11.
2. Clone the repo, ensure you're using node v16 and run `npm install`
3. Next run `npm run build`
4. See error.

## Expected behavior

Project should build regardless of platform.

**Comment by Tropicalista** [comment]
I have same problem.

I'm on windows, node v16.
