### ISSUE TITLE
payment integration

### ISSUE THREAD

**Issue by jasper1994** [woocommerce/woocommerce-gutenberg-products-block#6814]
payment gateway : https://wordpress.org/plugins/myfatoorah-woocommerce/

 **Please help me to integrate  "MyFatoorah – WooCommerce"**  

**its not visible in woocommerce block checkout page even though its enabled in payment methods**

![image](https://user-images.githubusercontent.com/24310964/182344239-5a434a4b-7981-4d85-bcc2-47eec5597a47.png)

**Comment by wavvves** [comment]
Hi @jasper1994, thank you for reporting this. That plugin isn't compatible with our checkout block, I suggest opening a [ticket for MyFatoorah](https://wordpress.org/support/plugin/myfatoorah-woocommerce/) so the plugin developers know there is a need for adding support to it.
