### ISSUE TITLE
Raw HTML in shipping packages items in Checkout block

### ISSUE THREAD

**Issue by yamenvip** [woocommerce/woocommerce-gutenberg-products-block#6835]
Hi,
Recently i install the plugin "woo-gutenberg-products-block.8.2.0", but there a problem with "wc-block-components-shipping-rates-control_ package-item" shows this text on browser "<span aria-hidden="true">Schokolade&lt;span&gt; - &lt;/span&gt;1kg</span>" , (<span> - </span>), I want to remove this "<span> - </span>"
Where can i find the check out template so i can edit it?

How do i remove this too ?
"wc-block-components-product-metadata"

**Comment by wavvves** [comment]
Hi, thank you for reporting this. Can you please post screenshots? What about plugins or filters that might be causing this?

Also, is this  `<span> - </span>` showing anywhere else the item title shows? (Cart/Checkout item list, product details page, shop products, etc).

Does this happen for other items? Do you have any more items with weight appended to the title?

**Comment by yamenvip** [comment]
Hi,

Thanks for your reply, it only shows in checkout and cart pages, when I deactivate the plugin it goes back to normal.
It may shows somewhere too, but for me I do use the plugin only for Cart/Checkout pages.
(https://user-images.githubusercontent.com/61413183/182659403-1ee3d4b9-f0e6-49b8-b9a3-0dee64bc4880.png)
(https://user-images.githubusercontent.com/61413183/182659443-1497dca1-19f2-451c-b6a1-14d144975ca9.png)

**Comment by wavvves** [comment]
Can you share a list of activated plugins?

**Comment by yamenvip** [comment]
Amino Core
CMB2
Elementor
Kirki Customizer Framework
Limit Login Attempts Reloaded
MC4WP: Mailchimp for WordPress
Mollie Payments for WooCommerce
Simple Google reCAPTCHA
SVG Support
TranslatePress - Multilingual
weLaunch Framework
WooCommerce
WooCommerce blocks for the Gutenberg editor.
WooCommerce PDF Invoices
WPForms Lite
YITH WooCommerce Wishlist

**Comment by wavvves** [comment]
I'm sorry, I'm having some trouble replicating this issue. What are you using to sell by weight? Is it adding weight to the item title? Do you have a live test URL where I can see the bug occurring?
Thanks

**Comment by yamenvip** [comment]
Sure you may see this via: https://pistachio-de.com/store/ 
Just add any product to cart you may find the weight title, 'Attributes' this what I did use for the weight ,

**Comment by wavvves** [comment]
Ok so I tried to replicate this, and the unrendered <span> did not show:

![image](https://user-images.githubusercontent.com/17236129/183095746-57721443-9e7d-4852-a0ba-03ae6d07065d.png)

Can you please test deleting and recreating the product weight variations? If this didn't help, does changing to another theme like Storefront fix it?
I'm having trouble attaching this bug to the WooCommerce Blocks plugin.

**Comment by yamenvip** [comment]
Hi, deleting and recreating the product weight variations did not help !, even when I change to Storefront the checkout and cart did not shows anything , only loading !

**Comment by yamenvip** [comment]
> Ok so I tried to replicate this, and the unrendered did not show:
> 
> ![image](https://user-images.githubusercontent.com/17236129/183095746-57721443-9e7d-4852-a0ba-03ae6d07065d.png)
> 
> Can you please test deleting and recreating the product weight variations? If this didn't help, does changing to another theme like Storefront fix it? I'm having trouble attaching this bug to the WooCommerce Blocks plugin.

Could explain me where do i need to change to get this solved ?

**Comment by tarhi-saad** [comment]
Hi @yamenvip! Thank you for reaching out and sharing the issue you encountered! 🙌 I couldn't replicate this issue either (see image below). So, as mentioned by @wavvves, this bug may not be related to the `WooCommerce Blocks` plugin. But, could you try the following actions on your website and see if the HTML `span` element is still showing:

- I see that the Cart didn't even appear when you changed the theme to `Storefront`. Could you change it to the `Twenty Twenty-Two` theme instead and check if you are still getting the same issue?
- Another thing you can try if the above action didn't get us any results is disabling all your plugins and keeping only the `Woocommerce` & `WooCommerce Blocks` plugins.

<img width="324" alt="image" src="https://user-images.githubusercontent.com/14235870/185502780-87cafa1d-9089-446b-945b-15ba977cf2ef.png">

**Comment by nielslange** [comment]
Hi @yamenvip, we haven’t heard back from you in a while, so I’m going to close this issue. If you can provide additional feedback, feel free to reopen it, and we will take another look. Thanks!

**Comment by yamenvip** [comment]
I want to confirm that the issue is resolved! 
Thank you for all your hard work on this. 👌

**Comment by nielslange** [comment]
Hello @yamenvip, I'm glad to everything works as expected now.
