### ISSUE TITLE
Improve the `no results` page

### ISSUE THREAD

**Issue by albarin** [woocommerce/woocommerce-gutenberg-products-block#6847]
The goal is to replace the banner with a line of text following the [new design](https://www.figma.com/file/6ZhHLQ7ucHUYgWHr3nusNB/%F0%9F%94%8E-Filter-Blocks-%26-Patterns?node-id=217%3A6078).
<img width="4009" alt="no-results-page" src="https://user-images.githubusercontent.com/186112/182823952-c8b9d515-f482-4901-b331-2c8a7cb10638.png">

**Comment by danielwrobert** [comment]
Based on some clarifications from @vivialice, I am [moving this issue over to the Storefront repo](https://github.com/woocommerce/storefront/issues/2026).

We essentially need to adjust the styling for this notification from within the theme - it is not directly related to the WooCommerce Blocks.
