### ISSUE TITLE
Open T&C and Privacy Policy in new Tab

### ISSUE THREAD

**Issue by masteradhoc** [woocommerce/woocommerce-gutenberg-products-block#6850]
## Describe the bug
We should open the pages T&C and Privacy Policy on the checkout in a new tab.
Currently these links are set without target blank, see
![image](https://user-images.githubusercontent.com/6242098/182834937-3388ab8c-8a65-4c62-8e44-e585df791251.png)

Although i found some intention here: https://github.com/woocommerce/woocommerce-blocks/blob/f9ecff2307d5b43afdc8ae3f97011e460a0529fe/assets/js/base/components/cart-checkout/policies/index.tsx#L25

## To reproduce

1. Set T&C and Data Protetion Page in Woo /wp-admin/admin.php?page=wc-settings&tab=advanced
2. set Data Protetion Page in Wordpress /wp-admin/options-privacy.php
3. Go to Checkout
4. Click on the link

## Expected behavior
Should open both links in a new tab

**Comment by senadir** [comment]
Hey, this is currently possible since those links are regular Gutenberg links, you can just click on them and edit them:
<img width="757" alt="image" src="https://user-images.githubusercontent.com/6165348/184625718-322db5e0-7010-43f5-97ac-1526cf6f33ee.png">

**Comment by masteradhoc** [comment]
@senadir yes true :) But on the old Checkout they used to be open in a new tab by default. This now doesnt seem the case anymore. From a UX Point of view i think open in a new tab should still be the default and i'd like to reopen the issue and get it back to the previous state.

What do you think?

**Comment by senadir** [comment]
You raise a good point @masteradhoc, I opened a [PR](https://github.com/woocommerce/woocommerce-blocks/pull/6908) to fix that.
