### ISSUE TITLE
Products by Category block doesn't show error messages when there are no products in a clean install

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#686]
![Peek 2019-07-04 15-11](https://user-images.githubusercontent.com/3616980/60669372-77805100-9e6e-11e9-979d-8121c07f63c1.gif)

**To Reproduce**
1. Reset your store with the plugin WP Reset in a clean install.
2. Create a new post and add the _Products by Category_ block.
3. Select 'Uncategorized' or any other category you have.
4. Notice the block becomes blank and no error appears.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/717
