### ISSUE TITLE
Update default Cart/Checkout notice to turn the current page into the default cart/checkout one

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#6864]
Currently, when you open a page that has Cart or Checkout block, and that page isn't the default Cart/Checkout page, you will get a notice telling you to update by taking you to the settings page:

> If you would like to use this block as your default checkout you must update your <a>page settings in WooCommerce</a>

We want to change that so you can make it the default without needing to leave the editor.

To reduce confusing, we will also switch the current page URL to `/cart` or `/checkout` respectively, or reuse the previous page URL.
![image](https://user-images.githubusercontent.com/6165348/183126104-96477a6b-6cf1-456b-9f25-a95d7cebd8bb.png)
![image](https://user-images.githubusercontent.com/6165348/183126123-d9f6c5c7-38d4-4604-9bbf-cba671689310.png)

**Comment by ralucaStan** [comment]
Based on internal discussions p1660321707024299/1660311130.074619-slack-C8X6Q7XQU, for people with WC >= 6.8, we want to change that so you can make it the default without needing to leave the editor. For people with WC < 6.8 we want to keep the current behaviour and show [the current notification with a link](https://user-images.githubusercontent.com/6165348/184404663-11cac5f1-1729-4782-a39f-ee5f101a78a7.png) that makes the user leave the editor.

**Comment by senadir** [comment]
Yes, that's the current behavior in https://github.com/woocommerce/woocommerce-blocks/pull/6867
