### ISSUE TITLE
Mini Cart > alternative icons

### ISSUE THREAD

**Issue by Marc-pi** [woocommerce/woocommerce-gutenberg-products-block#6868]
## Is your feature request related to a problem? Please describe.
follow up of https://github.com/woocommerce/woocommerce-blocks/issues/6617
![image](https://user-images.githubusercontent.com/919332/183424158-4648cb44-ac16-478c-9f7d-e07ffbaa1bb2.png)

Some improvements were recently made by @danielwrobert , to make the mini cart icon different from the one of the Cart Block.
Actually, only 1 icon is proposed in the mini cart block : it does not suite all contexts
examples : you make a jellery or fashion shop > you want a bag icon instead of a "supermarket like icon"

something like that
![image](https://user-images.githubusercontent.com/919332/183424775-087fe3bd-5c3a-4243-b743-e2a6be687c83.png)

## Describe the solution you'd like
* add a bag icon (i don't think we need too much icons, but a more female icon, complementary from the male cart icon)
* permit to personalize the icon : link to replacement svg file, as proposed by @dashkevych ????

## Describe alternatives you've considered
N/A

## Additional context
N/A

**Comment by sunyatasattva** [comment]
Hello @Marc-pi ! Thank you for your suggestion and submission. I see why this might be useful. I'm adding this to our backlog, and hopefully we can get to it :)

**Comment by SchneiderSam** [comment]
Or just add the Function to add our own SVG file.

**Comment by ifrountas** [comment]
It would be much better if you can give us the ability to insert a filter with our own svg icon.

**Comment by grel0** [comment]
it's been like this for months now!.

**Comment by digi4care** [comment]
i tried it with this code but i reverts back to it orginal svg, bummer

```
function custom_render_block_core_minicart (string $block_content, array $block)
{

	$svg = '<svg .... </svg>';

	if (
		$block['blockName'] === 'woocommerce/mini-cart' && 
		!is_admin() &&
		!wp_is_json_request()
	) {
		return preg_replace('/(<svg .*?\/svg\>)/s', $svg, $block_content);
	}

	return $block_content;
}

add_filter('render_block', 'custom_render_block_core_minicart', null, 2);
```
