### ISSUE TITLE
Allow Checkout Error message to be filterable for others extensions

### ISSUE THREAD

**Issue by ankitguptaindia** [woocommerce/woocommerce-gutenberg-products-block#6871]
When any issue occurs during the checkout, block based checkout gives an error message. This message is not filterable and gives a generic message.

For the extension [woocommerce-min-max-quantities](https://github.com/woocommerce/woocommerce-min-max-quantities/) , when any errors occur in the cart and checkout get failed, this plugin gives a detailed message to resolve the problem. If using shortcode based checkout page then this message has detailed info but when using block based checkout then this message is not customizable.  

| Shortcode based Checkout   |      Block based Checkout      |
|----------|:-------------:|
 |  
![Screenshot 2022-08-03 at 6 47 46 PM](https://user-images.githubusercontent.com/6384299/182617456-460232f3-380c-4f5b-88c6-562febf5bc95.png) | ![Screenshot 2022-08-03 at 6 48 05 PM](https://user-images.githubusercontent.com/6384299/182617515-d454d85e-38a9-498e-b15a-3d525e0193f2.png) |

## Describe the solution you'd like
Would be great if provide a filter to manage this text. 

## Related Discussion
- Point 1 of https://github.com/woocommerce/woocommerce-min-max-quantities/pull/152#issuecomment-1204960581 & https://github.com/woocommerce/woocommerce-min-max-quantities/pull/152#issuecomment-1204105631

**Comment by senadir** [comment]
Depending on the type of error that happens (server side, vs client side), you can actually throw an error and that error will be shown, at least in the flow you screenshotted above. Can you give me an example of when this might happen?

**Comment by nielslange** [comment]
Hi @ankitguptaindia, we haven’t heard back from you in a while, so I’m going to close this issue. If you can provide additional feedback, feel free to reopen it, and we will take another look. Thanks!
