### ISSUE TITLE
Prevent the GH stale workflow from closing issues

### ISSUE THREAD

**Issue by ralucaStan** [woocommerce/woocommerce-gutenberg-products-block#6872]
We are using the [stale Github action](https://github.com/actions/stale) to [mark issues](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/.github/workflows/close-stale-issues.yml) as stale after 60 days and close them after 10 days. 

Because of this some tickets might get lost, tickets that document actual problems or improvements.

We need to:
- prevent the workflow from closing the stale tickets after 10 days
- prevent the worflow from adding stale to issues coming from the github-actions user
- prevent the worflow from adding stale to issues with the `labels: type:technical debt`, `category:refactor`, `type:documentation`, `plugin incompatibility`

**Comment by ralucaStan** [comment]
Internal discussion p1660047103998199-slack-C02UBB1EPEF

**Comment by ralucaStan** [comment]
[stale Github action](https://github.com/actions/stale) can also comment on a stale PR, so we might solve https://github.com/woocommerce/woocommerce-blocks/issues/6956 without using another action.

So, as part of this ticket we could also:

- add a stale label to PRs (we can use the default 7 days)
- comment on a PR when the label is added, but don't close the PR

**Comment by opr** [comment]
> prevent the worflow from adding stale to issues coming from the github-actions user

This is not possible, we could add a second workflow which checks all of `github-actions` issues and removes stale from them instead, what do you think?

**Comment by ralucaStan** [comment]
I don't have strong feelings around this. Let's skip this point for now
