### ISSUE TITLE
Checkout Block cutting off its content

### ISSUE THREAD

**Issue by asumaran** [woocommerce/woocommerce-gutenberg-products-block#6885]
## To reproduce

- Create a new page
- Insert the checkout block

Notice the limits of the checkout block will cut off its content. 

## Expected behavior

No content should be outside of the checkout block limits.

## Screenshots

<img src="https://user-images.githubusercontent.com/1025173/184261697-61093ef8-a331-4533-a6c2-75c3d63a5369.png" width="500" />

### WordPress:

-   Core version: 6.0.1
-   WooCommerce version: 6.7.0
-   WooCommerce Blocks version: 8.2.1
-   Site language: english

### Desktop (please complete the following information):

-   OS: macOS
-   Browser: MacOS
-   Version: Version 104.0.5112.79 (Official Build) (x86_64)

**Comment by tarhi-saad** [comment]
Thank you @asumaran for reporting this bug! 🙌 I was able to reproduce it. The elements outside the block limits are either translated elements (e.g., the `Express checkout` block title), or `::before` content in CSS.
