### ISSUE TITLE
Switching to List View Should Keep Original Number of Products Visible

### ISSUE THREAD

**Issue by spencerfinnell** [woocommerce/woocommerce-gutenberg-products-block#69]
If you have a Grid View set to show 1 row with 4 columns and you switch to List View the number of rows is set to 1 which hides products. I think when switching the rows should be set to `$rows * columns`.

4 Columns x 2 Rows = 8 Rows
3 Columns x 3 Rows = 9 Rows

etc...

It's confusing switching to List View and having products disappear. Originally noted in #59

**Comment by claudiulodro** [comment]
Closing this because we're removing list view. See https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/70
