### ISSUE TITLE
Package Feature Toggle in Cart & Checkout Shipping options area

### ISSUE THREAD

**Issue by theritesite** [woocommerce/woocommerce-gutenberg-products-block#6902]
## Is your feature request related to a problem? Please describe.
A newer feature of the Cart & Checkout blocks displays individual packages for the order in the html tag "wc-block-components-shipping-rates-control__package-item"
This is a cool upgrade, but is unwanted in a store that I use WC Blocks on. There should be a way to toggle off the packages being listed in the cart & checkout. For WC Stores that do not offer multiple package options, this is bloat on the cart screen that we would like to have the opportunity to remove to reduce friction and confusion.

## Describe the solution you'd like
A toggle switch on the Shipping Options block in the cart or checkout to disable listing the packages.

## Describe alternatives you've considered
- Tagging into a feature in the primary WooCommerce Settings pages.
- A Filter to change the boolean value to display through a code snippet.

## Additional context
On WooCommerce 6.8.0
WC Blocks 8.2.1
WP 6.0.1

**Comment by danieldudzic** [comment]
Hi @theritesite,

Thank you for reporting this issue.

I have consulted on it, with @opr and it seems that there's already a fix: https://github.com/woocommerce/woocommerce-blocks/pull/6899

cc: @tarunvijwani do you think, we can include it in the current release?

**Comment by tarhi-saad** [comment]
The fix: #6899 is included in the latest version of Woo Blocks (i.e., [v8.3.1](https://github.com/woocommerce/woocommerce-blocks/releases/tag/v8.3.1))
