### ISSUE TITLE
Razorpay Payment Gateway not showing

### ISSUE THREAD

**Issue by darshan-hirpara** [woocommerce/woocommerce-gutenberg-products-block#6913]
![Screenshot_252](https://user-images.githubusercontent.com/100473716/185169637-5aea3355-eac4-4f15-afc6-6c23f80e9645.png)

## What do you think is missing from the Cart & Checkout blocks?

Razorpay payment gateway is integrated with woocomemrce but not showing into woocommerce checkout block. please help, i am having hard times fixing checkout pages.

email: hirparadarshan@yahoo.com

**Comment by danieldudzic** [comment]
Hi!

Thanks for taking the time to make us aware that Razorpay isn't working with the Checkout and Cart blocks. These blocks are still in early access (via the feature plugin) and it's expected that some existing payment methods will not work with the blocks.

Currently, it's up to payment method extension developers to add support for the new checkout flow offered via the cart and checkout blocks. We have some [documentation on that here](https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs/third-party-developers/extensibility/checkout-payment-methods) and will be publicizing this more in the coming months.

Your best course of action now if you are using a payment method that isn't working with the blocks is to notify the developer of the extension and ask if they can add support.

Until then, you can keep on top of the [status of the Cart & Checkout Blocks in this documentation](https://woocommerce.com/document/cart-checkout-blocks-support-status/).
