### ISSUE TITLE
Improve public-facing text and labels

### ISSUE THREAD

**Issue by sunyatasattva** [woocommerce/woocommerce-gutenberg-products-block#6916]
We noticed that oftentimes our labels and text tend to be overly technical or unclear. As the blocks experience becomes more and more common place, we should prioritize improving our text as essential to UX. Thanks to @ifinoi's amazing work, we have identified the problematic labels and came up with a replacement for each of them. 

<table>
  <tr>
   <td>Original text
   </td>
   <td>Replacement
   </td>
   <td>References
   </td>
  </tr>
  <tr>
   <td>Note: by choosing “Cover” you will lose the ability to freely move the focal point precisely.
   </td>
   <td>This may affect your ability to freely move the focal point of the image.
   </td>
   <td>assets/js/blocks/featured-category/block.js:225,assets/js/blocks/featured-product/block.js:326 build/featured-category.js:1,build/featured-category.js:6 build/featured-product.js:1
   </td>
  </tr>
  <tr>
   <td>Choose “Cover” if you want the image to scale automatically to always fit its container.
   </td>
   <td>Select "Cover' to have the image automatically fit its container.
   </td>
   <td>assets/js/blocks/featured-category/block.js:219,assets/js/blocks/featured-product/block.js:320 build/featured-category.js:1,build/featured-category.js:6 build/featured-product.js:1
   </td>
  </tr>
  <tr>
   <td>Mini Cart Empty Cart Message
   </td>
   <td>Empty Mini Cart Message
   </td>
   <td>src/BlockTypes/MiniCart.php:515
   </td>
  </tr>
  <tr>
   <td>Edit the appearance of your empty and filled mini cart contents.
   </td>
   <td>Edit the appearance of the Mini Cart.
   </td>
   <td>build/mini-cart.js:1
   </td>
  </tr>
  <tr>
   <td>Block that Shows the shopping button for the Mini Cart block.
   </td>
   <td>Block that displays the shopping button when the Mini Cart is empty.
   </td>
   <td>assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/mini-cart-shopping-button-block/block.json
   </td>
  </tr>
  <tr>
   <td>Removal will cause unintended effects on your store.
   </td>
   <td>Removing this will cause unintended effects on your store.
   </td>
   <td>build/legacy-template.js:1
   </td>
  </tr>
  <tr>
   <td>Attention: Do not remove this block!
   </td>
   <td>Do not remove this block!
   </td>
   <td>build/legacy-template.js:1
   </td>
  </tr>
  <tr>
   <td>Contains blocks that are displayed when the mini cart has products.
   </td>
   <td>Contains blocks that display the content of the Mini Cart.
   </td>
   <td>assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/filled-mini-cart-contents-block/block.json
   </td>
  </tr>
  <tr>
   <td>Filled Mini Cart Contents
   </td>
   <td>Filled Mini Cart view
   </td>
   <td>assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/filled-mini-cart-contents-block/block.json
   </td>
  </tr>
  <tr>
   <td>Contains blocks that are displayed when the mini cart is empty.
   </td>
   <td>Blocks that are displayed when the Mini Cart is empty.
   </td>
   <td>assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/empty-mini-cart-contents-block/block.json
   </td>
  </tr>
  <tr>
   <td>Empty Mini Cart Contents
   </td>
   <td>Empty Mini Cart view.
   </td>
   <td>assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/empty-mini-cart-contents-block/block.json
   </td>
  </tr>
  <tr>
   <td>Something went wrong.
   </td>
   <td>Something went wrong. Please contact us for assistance.
   </td>
   <td>assets/js/base/context/providers/cart-checkout/checkout-processor.js:259,build/cart-frontend.js:4 build/cart.js:36 build/checkout-frontend.js:4,build/checkout.js:26
   </td>
  </tr>
  <tr>
   <td>This is an editor placeholder for the %s. On your store this will be replaced by the template and display with your product image(s), title, price, etc. You can move this placeholder around and add further blocks around it to extend the template.
   </td>
   <td>This is a placeholder for the %s. In your store it will display the actual product image, title, price, etc. You can move this placeholder around and add more blocks around it to customize the template.
   </td>
   <td>build/legacy-template.js:3
   </td>
  </tr>
  <tr>
   <td>Edit inner product layout
   </td>
   <td>Edit the layout of each product
   </td>
   <td>assets/js/blocks/products/all-products/edit.js:151 build/all-products.js:36
   </td>
  </tr>
  <tr>
   <td>The selected attribute does not have any term assigned to products.
   </td>
   <td>There are no products with the selected attributes.
   </td>
   <td>assets/js/blocks/attribute-filter/block.js:525,build/attribute-filter-frontend.js:29 build/attribute-filter.js:33
   </td>
  </tr>
  <tr>
   <td>Ensure customers agree to your terms and conditions and privacy policy.
   </td>
   <td>Ensure that customers agree to your Terms & Conditions and Privacy Policy.
   </td>
   <td>assets/js/blocks/checkout/inner-blocks/checkout-terms-block/block.json
   </td>
  </tr>
  <tr>
   <td>You don't seem to have a Terms and Conditions and/or a Privacy Policy pages setup.
   </td>
   <td>You don't have any Terms and Conditions and/or  Privacy Policy pages set up.
   </td>
   <td>build/checkout.js:34
   </td>
  </tr>
  <tr>
   <td>Your store doesn't have any Payment Methods that support the Express Checkout Block. If they are added, they will be shown here.
   </td>
   <td>Your store does not have any payment methods that support the Express Checkout block. Once you have configured a compatible payment method, it will be displayed here.
   </td>
   <td>build/cart.js:40 build/checkout.js:42
   </td>
  </tr>
  <tr>
   <td>Allow customers to filter the grid by products stock status. Works in combination with the All Products block.
   </td>
   <td>Enable customers to filter the product grid by stock status. 
   </td>
   <td>assets/js/blocks/stock-filter/index.js:26 build/stock-filter.js:13
   </td>
  </tr>
  <tr>
   <td>You currently have the following shipping integrations active.
   </td>
   <td>The following shipping integrations are active on your store.
   </td>
   <td>build/checkout.js:42
   </td>
  </tr>
  <tr>
   <td>The WooCommerce Blocks feature plugin requires a more recent version of WooCommerce and has been paused. Please update WooCommerce to the latest version to continue enjoying WooCommerce Blocks.
   </td>
   <td>The WooCommerce Blocks plugin requires a more recent version of WooCommerce and has been deactivated. Please update to the latest version of WooCommerce.
   </td>
   <td>src/Domain/Bootstrap.php:129
   </td>
  </tr>
  <tr>
   <td>Customer "new account" emails are sent to the customer when a customer signs up via checkout or account blocks.
   </td>
   <td>“New Account” emails are sent when a customer signs up via the checkout flow.
   </td>
   <td>src/Domain/Services/Email/CustomerNewAccount.php:58
   </td>
  </tr>
  <tr>
   <td>Show a list of tags belonging to a product.
   </td>
   <td>Display the list of tags that are assigned to a product.
   </td>
   <td>assets/js/atomic/blocks/product-elements/tag-list/constants.js:14,build/all-products.js:28
   </td>
  </tr>
  <tr>
   <td>Show a list of categories belonging to a product.
   </td>
   <td>Display the list of categories that are assigned to a product.
   </td>
   <td>build/all-products.js:28
   </td>
  </tr>
  <tr>
   <td>Allow customers to filter the products by choosing a lower or upper price limit. Works in combination with the All Products block.
   </td>
   <td>Enable customers to filter the product grid by choosing a price range.
   </td>
   <td>assets/js/blocks/price-filter/index.js:29 build/price-filter.js:3
   </td>
  </tr>
  <tr>
   <td>Show the currently active product filters. Works in combination with the All Products and filters blocks.
   </td>
   <td>Display the currently active product filters..
   </td>
   <td>assets/js/blocks/active-filters/index.js:29 build/active-filters.js:15
   </td>
  </tr>
  <tr>
   <td>Allow customers to filter the grid by product attribute, such as color. Works in combination with the All Products block.
   </td>
   <td>
Enable customers to filter the product grid by selecting one or more attributes, such as color.

   </td>
   <td>assets/js/blocks/attribute-filter/index.js:29 build/attribute-filter.js:37
   </td>
  </tr>
  <tr>
   <td>Products will update as options are selected.
   </td>
   <td>

Products will update as soon as attributes are selected.
   </td>
   <td>assets/js/blocks/attribute-filter/edit.js:200,assets/js/blocks/stock-filter/edit.js:93 build/attribute-filter.js:37,build/stock-filter.js:13
   </td>
  </tr>
  <tr>
   <td>Showing Filter Products by Attribute block preview.
   </td>
   <td>

Now displaying a preview of the Filter Products by Attribute block.
   </td>
   <td>assets/js/blocks/attribute-filter/edit.js:269 build/attribute-filter.js:37
   </td>
  </tr>
  <tr>
   <td>We are currently working on improving our cart and checkout blocks to provide merchants with the tools and customization options they need.
   </td>
   <td>
   </td>
   <td>assets/js/editor-components/feedback-prompt/index.js:56 build/cart.js:7,build/checkout.js:7
   </td>
  </tr>
  <tr>
   <td>Enter the address that matches your card or payment method.
   </td>
   <td>Enter the billing address that matches your payment method.
   </td>
   <td>build/checkout-blocks/billing-address-frontend.js:1 build/checkout.js:34
   </td>
  </tr>
  <tr>
   <td>This site is experiencing difficulties with this payment method. Please contact the owner of the site for assistance.
   </td>
   <td>We are experiencing difficulties with this payment method. Please contact us for assistance.
   </td>
   <td>assets/js/blocks/cart-checkout-shared/payment-methods/payment-method-error-boundary.js:26,build/cart-blocks/cart-express-payment-frontend.js:5 build/cart.js:5,build/checkout-blocks/express-payment-frontend.js:5,build/checkout-blocks/payment-frontend.js:5 build/checkout.js:5
   </td>
  </tr>
  <tr>
   <td>Your store does not have any payment methods configured that support the checkout block. Once you have configured a compatible payment method it will be shown here.
   </td>
   <td>Your store does not have any payment methods that support the Checkout block. Once you have configured a compatible payment method it will be displayed here.
   </td>
   <td>assets/js/blocks/cart-checkout-shared/payment-methods/no-payment-methods/index.js:40,build/checkout-blocks/payment-frontend.js:5 build/checkout.js:36
   </td>
  </tr>
  <tr>
   <td>The last inner block will be aligned vertically.
   </td>
   <td>Align the last block to the bottom.
   </td>
   <td>assets/js/editor-components/grid-layout-control/index.js:65,build/all-products.js:5 build/product-best-sellers.js:5,build/product-category.js:5 build/product-new.js:5,build/product-on-sale.js:5 build/product-tag.js:9,build/product-top-rated.js:5 build/products-by-attribute.js:15
   </td>
  </tr>
  <tr>
   <td>Align Last Block
   </td>
   <td>Align the last block to the bottom
   </td>
   <td>assets/js/editor-components/grid-layout-control/index.js:59,build/all-products.js:5 build/product-best-sellers.js:5,build/product-category.js:5 build/product-new.js:5,build/product-on-sale.js:5 build/product-tag.js:9,build/product-top-rated.js:5 build/products-by-attribute.js:15
   </td>
  </tr>
  <tr>
   <td>Edit the blocks inside the preview below to change the content displayed for each product within the product grid.
   </td>
   <td>Edit the blocks inside the example below to change the content displayed for all products within the product grid.
   </td>
   <td>assets/js/blocks/products/all-products/edit.js:210 build/all-products.js:36
   </td>
  </tr>
  <tr>
   <td>Products with prices are needed for filtering by price. You haven't created any products yet.
   </td>
   <td>To filter your products by price you first need to assign prices to your products.
   </td>
   <td>assets/js/blocks/price-filter/edit.js:132 build/price-filter.js:3
   </td>
  </tr>
  <tr>
   <td>Products will update when the slider is moved.
   </td>
   <td>Products will update when the slider is moved.
   </td>
   <td>assets/js/blocks/price-filter/edit.js:86 build/price-filter.js:3
   </td>
  </tr>
  <tr>
   <td>Products will only update when the button is pressed.
   </td>
   <td>Products will only update when the button is clicked.
   </td>
   <td>assets/js/blocks/attribute-filter/edit.js:196,assets/js/blocks/price-filter/edit.js:82,assets/js/blocks/stock-filter/edit.js:89 build/attribute-filter.js:37,build/price-filter.js:3 build/stock-filter.js:13
   </td>
  </tr>
  <tr>
   <td>Attributes are needed for filtering your products. You haven't created any attributes yet.
   </td>
   <td>To filter your products by attribute you first need to assign attributes to your products.
   </td>
   <td>assets/js/blocks/attribute-filter/edit.js:240 build/attribute-filter.js:37
   </td>
  </tr>
  <tr>
   <td>Show a list of filters based on a chosen attribute.
   </td>
   <td>Display a list of filters based on the selected attributes.
   </td>
   <td>assets/js/blocks/attribute-filter/edit.js:234,assets/js/blocks/attribute-filter/edit.js:368 build/attribute-filter.js:37
   </td>
  </tr>
  <tr>
   <td>Overlay a "sale" badge if the product is on-sale.
   </td>
   <td>Display a “sale” badge if the product is on-sale.
   </td>
   <td>assets/js/atomic/blocks/product-elements/image/edit.js:62,build/all-products.js:28
   </td>
  </tr>
  <tr>
   <td>An unknown error occurred which prevented the block from being updated.
   </td>
   <td>An error has prevented the block from being updated.
   </td>
   <td>build/all-products.js:5 build/all-reviews.js:9 build/featured-category.js:6,build/featured-product.js:6 build/handpicked-products.js:5,build/product-best-sellers.js:5 build/product-category.js:5,build/product-new.js:5 build/product-on-sale.js:5,build/product-top-rated.js:5 build/products-by-attribute.js:5,build/reviews-by-category.js:13 build/reviews-by-product.js:13,build/single-product.js:5
   </td>
  </tr>
  <tr>
   <td>Showing Reviews by Category block preview.
   </td>
   <td>Now displaying a preview of the reviews for the products in the selected categories.
   </td>
   <td>assets/js/blocks/reviews/reviews-by-category/edit.js:96,build/reviews-by-category.js:13
   </td>
  </tr>
  <tr>
   <td>This block lists reviews for products from selected categories. The selected categories do not have any reviews yet, but they will show up here when they do.
   </td>
   <td>This block displays reviews for products from the selected categories. Products from selected categories will be displayed when there are reviews for them.
   </td>
   <td>assets/js/blocks/reviews/reviews-by-category/no-reviews-placeholder.js:22,build/reviews-by-category.js:13
   </td>
  </tr>
  <tr>
   <td>Show reviews of your products to build trust.
   </td>
   <td>Display reviews for your products.
   </td>
   <td>assets/js/blocks/reviews/reviews-by-product/index.js:32,build/reviews-by-product.js:19
   </td>
  </tr>
  <tr>
   <td>Your store doesn't have any product tags.
   </td>
   <td>You have not set up any product tags on your store.
   </td>
   <td>assets/js/editor-components/product-tag-control/index.js:110,build/product-tag.js:7
   </td>
  </tr>
  <tr>
   <td>This block displays products from selected tags. In order to preview this you'll first need to create a product and assign it some tags.
   </td>
   <td>This block displays products from selected tags. To use it you first need to create products and assign tags to them.
   </td>
   <td>assets/js/blocks/product-tag/block.js:313 build/product-tag.js:9
   </td>
  </tr>
  <tr>
   <td>This block shows product categories for your store. To use it, you'll first need to create a product and assign it to a category.
   </td>
   <td>This block displays the product categories for your store. To use it you first need to create a product and assign it to a category.
   </td>
   <td>assets/js/blocks/product-categories/block.js:29,build/product-categories.js:1
   </td>
  </tr>
  <tr>
   <td>Visually highlight a product or variation and encourage prompt action
   </td>
   <td>Highlight a product or variation.
   </td>
   <td>assets/js/blocks/featured-product/block.js:177 build/featured-category.js:1,build/featured-product.js:1
   </td>
  </tr>
  <tr>
   <td>Showing Hand-picked Products block preview.
   </td>
   <td>Now displaying a preview of the Hand-picked Products block.
   </td>
   <td>assets/js/blocks/handpicked-products/block.js:121,build/handpicked-products.js:7
   </td>
  </tr>
  <tr>
   <td>Product image is hidden.
   </td>
   <td>Remove
   </td>
   <td>assets/js/editor-components/grid-content-control/index.js:27,build/handpicked-products.js:7 build/product-best-sellers.js:5,build/product-category.js:5 build/product-new.js:5,build/product-on-sale.js:5 build/product-tag.js:9,build/product-top-rated.js:5 build/products-by-attribute.js:15
   </td>
  </tr>
  <tr>
   <td>Product image is visible.
   </td>
   <td>Remove
   </td>
   <td>assets/js/editor-components/grid-content-control/index.js:23,build/handpicked-products.js:7 build/product-best-sellers.js:5,build/product-category.js:5 build/product-new.js:5,build/product-on-sale.js:5 build/product-tag.js:9,build/product-top-rated.js:5 build/products-by-attribute.js:15
   </td>
  </tr>
  <tr>
   <td>Something went wrong…
   </td>
   <td>Something went wrong. Please contact us for assistance.
   </td>
   <td>assets/js/blocks/cart/block.js:77 build/cart-frontend.js:6,build/checkout-frontend.js:6
   </td>
  </tr>
  <tr>
   <td>Something went wrong. Please contact us to get assistance.
   </td>
   <td>Something went wrong. Please contact us for assistance.
   </td>
   <td>assets/js/base/context/providers/add-to-cart-form/form-state/index.js:249,assets/js/base/context/providers/add-to-cart-form/form/submit/index.js:104,assets/js/base/utils/errors.js:54 build/all-products.js:5,build/all-products.js:18 build/all-reviews.js:9 build/cart-frontend.js:1,build/cart-frontend.js:3 build/cart.js:1 build/checkout-frontend.js:1,build/checkout-frontend.js:3 build/checkout.js:1,build/featured-category.js:6 build/featured-product.js:6,build/handpicked-products.js:5,build/mini-cart-contents-block/footer--mini-cart-contents-block/products-table-frontend.js:1,build/mini-cart-contents.js:17 build/product-add-to-cart-frontend.js:1,build/product-add-to-cart.js:1 build/product-best-sellers.js:5,build/product-category.js:5 build/product-new.js:5,build/product-on-sale.js:5 build/product-top-rated.js:5,build/products-by-attribute.js:5 build/reviews-by-category.js:13,build/reviews-by-product.js:13 build/reviews-frontend.js:7,build/single-product-frontend.js:3 build/single-product.js:5,build/wc-blocks-data.js:3
   </td>
  </tr>
  <tr>
   <td>Filter button
   </td>
   <td>Remove
   </td>
   <td>assets/js/blocks/attribute-filter/edit.js:190,assets/js/blocks/price-filter/edit.js:76,assets/js/blocks/stock-filter/edit.js:83 build/attribute-filter.js:37,build/price-filter.js:3 build/stock-filter.js:13
   </td>
  </tr>
  <tr>
   <td>Or
   </td>
   <td>Any
   </td>
   <td>assets/js/blocks/attribute-filter/edit.js:159,assets/js/blocks/cart-checkout-shared/payment-methods/express-payment/cart-express-payment.js:69,build/attribute-filter.js:37,build/cart-blocks/cart-express-payment-frontend.js:5 build/cart.js:40
   </td>
  </tr>
  <tr>
   <td>And
   </td>
   <td>All
   </td>
   <td>assets/js/blocks/attribute-filter/edit.js:152 build/attribute-filter.js:37
   </td>
  </tr>
  <tr>
   <td>Query Type
   </td>
   <td>Filter condition
   </td>
   <td>assets/js/blocks/attribute-filter/edit.js:128 build/attribute-filter.js:37
   </td>
  </tr>
  <tr>
   <td>Product count
   </td>
   <td>Display product count
   </td>
   <td>assets/js/blocks/attribute-filter/edit.js:83,assets/js/blocks/stock-filter/edit.js:38 build/attribute-filter.js:37,build/stock-filter.js:13
   </td>
  </tr>
  <tr>
   <td>Label is hidden.
   </td>
   <td>Remove
   </td>
   <td>assets/js/blocks/product-search/edit.js:69 build/product-search.js:1
   </td>
  </tr>
  <tr>
   <td>Label is visible.
   </td>
   <td>Remove
   </td>
   <td>assets/js/blocks/product-search/edit.js:65 build/product-search.js:1
   </td>
  </tr>
  <tr>
   <td>Empty categories are hidden.
   </td>
   <td>Remove
   </td>
   <td>assets/js/blocks/product-categories/block.js:173,build/product-categories.js:1
   </td>
  </tr>
  <tr>
   <td>Empty categories are visible.
   </td>
   <td>Remove
   </td>
   <td>assets/js/blocks/product-categories/block.js:169,build/product-categories.js:1
   </td>
  </tr>
  <tr>
   <td>Hierarchy is hidden.
   </td>
   <td>Remove
   </td>
   <td>assets/js/blocks/product-categories/block.js:150,build/product-categories.js:1
   </td>
  </tr>
  <tr>
   <td>Hierarchy is visible.
   </td>
   <td>Remove
   </td>
   <td>assets/js/blocks/product-categories/block.js:146,build/product-categories.js:1
   </td>
  </tr>
  <tr>
   <td>Product count is hidden.
   </td>
   <td>Remove
   </td>
   <td>assets/js/blocks/attribute-filter/edit.js:93,assets/js/blocks/product-categories/block.js:106,assets/js/blocks/stock-filter/edit.js:48 build/attribute-filter.js:37,build/product-categories.js:1 build/stock-filter.js:13
   </td>
  </tr>
  <tr>
   <td>Product count is visible.
   </td>
   <td>Remove
   </td>
   <td>assets/js/blocks/attribute-filter/edit.js:89,assets/js/blocks/product-categories/block.js:102,assets/js/blocks/stock-filter/edit.js:44 build/attribute-filter.js:37,build/product-categories.js:1 build/stock-filter.js:13
   </td>
  </tr>
  <tr>
   <td>Add to Cart button is hidden.
   </td>
   <td>Remove
   </td>
   <td>assets/js/editor-components/grid-content-control/index.js:94,build/handpicked-products.js:7 build/product-best-sellers.js:5,build/product-category.js:5 build/product-new.js:5,build/product-on-sale.js:5 build/product-tag.js:9,build/product-top-rated.js:5 build/products-by-attribute.js:15
   </td>
  </tr>
  <tr>
   <td>Add to Cart button is visible.
   </td>
   <td>Remove
   </td>
   <td>assets/js/editor-components/grid-content-control/index.js:90,build/handpicked-products.js:7 build/product-best-sellers.js:5,build/product-category.js:5 build/product-new.js:5,build/product-on-sale.js:5 build/product-tag.js:9,build/product-top-rated.js:5 build/products-by-attribute.js:15
   </td>
  </tr>
  <tr>
   <td>Product rating is hidden.
   </td>
   <td>Remove
   </td>
   <td>assets/js/editor-components/grid-content-control/index.js:75,build/handpicked-products.js:7 build/product-best-sellers.js:5,build/product-category.js:5 build/product-new.js:5,build/product-on-sale.js:5 build/product-tag.js:9,build/product-top-rated.js:5 build/products-by-attribute.js:15
   </td>
  </tr>
  <tr>
   <td>Product rating is visible.
   </td>
   <td>Remove
   </td>
   <td>assets/js/editor-components/grid-content-control/index.js:71,build/handpicked-products.js:7 build/product-best-sellers.js:5,build/product-category.js:5 build/product-new.js:5,build/product-on-sale.js:5 build/product-tag.js:9,build/product-top-rated.js:5 build/products-by-attribute.js:15
   </td>
  </tr>
  <tr>
   <td>Product price is hidden.
   </td>
   <td>Remove
   </td>
   <td>assets/js/editor-components/grid-content-control/index.js:59,build/handpicked-products.js:7 build/product-best-sellers.js:5,build/product-category.js:5 build/product-new.js:5,build/product-on-sale.js:5 build/product-tag.js:9,build/product-top-rated.js:5 build/products-by-attribute.js:15
   </td>
  </tr>
  <tr>
   <td>Product price is visible.
   </td>
   <td>Remove
   </td>
   <td>assets/js/editor-components/grid-content-control/index.js:55,build/handpicked-products.js:7 build/product-best-sellers.js:5,build/product-category.js:5 build/product-new.js:5,build/product-on-sale.js:5 build/product-tag.js:9,build/product-top-rated.js:5 build/products-by-attribute.js:15
   </td>
  </tr>
  <tr>
   <td>Product title is hidden.
   </td>
   <td>Remove
   </td>
   <td>assets/js/editor-components/grid-content-control/index.js:43,build/handpicked-products.js:7 build/product-best-sellers.js:5,build/product-category.js:5 build/product-new.js:5,build/product-on-sale.js:5 build/product-tag.js:9,build/product-top-rated.js:5 build/products-by-attribute.js:15
   </td>
  </tr>
  <tr>
   <td>Product title is visible.
   </td>
   <td>Remove
   </td>
   <td>assets/js/editor-components/grid-content-control/index.js:39,build/handpicked-products.js:7 build/product-best-sellers.js:5,build/product-category.js:5 build/product-new.js:5,build/product-on-sale.js:5 build/product-tag.js:9,build/product-top-rated.js:5 build/products-by-attribute.js:15
   </td>
  </tr>
</table>

**Comment by senadir** [comment]
Hey! Cart block recently switched from using `OR` to `ANY`, any reason for that? it's now more ambiguous than it was
 @ifinoi 
![image](https://user-images.githubusercontent.com/6165348/195061835-314541b5-ec5f-4d62-82b5-344e50938560.png)

**Comment by sunyatasattva** [comment]
Hey @senadir, this was an oversight by us. We have changed an “OR” statement that was referring to a query type filter within our blocks (see line 751 of [this Google Sheet](https://docs.google.com/spreadsheets/d/1aMC5ZgKdKAxFKYtlnBa2wniQZqIvSAa1z-YBQ_5mOpE/edit#gid=1090116064), though a better comment is in [this Google Doc](https://docs.google.com/document/d/15ocBO6OGl6X-nLL_CjbPl2sFd-E2oxL95echwfca2wE/edit)), and this string was caught in the change.

We did review our changes quite closely, but this was a slip-up. Apologies!
