### ISSUE TITLE
Disable WooCommerce Block (Classic Editor only used)

### ISSUE THREAD

**Issue by cbratschi** [woocommerce/woocommerce-gutenberg-products-block#6921]
## Is your feature request related to a problem? Please describe.
Our WordPress sites are not using Gutenberg and we already deactivated the styles added by WooCommerce Blocks. During performance measurement we detected additional code gets loaded all the time which is not necessary:

"Automattic\\WooCommerce\\Blocks\\BlockTypesController::register_blocks"

We would like to disable all features of WooCommerce Blocks to get the best possible performance. Is there a way to disable the whole plugin? We could not find any useful hooks in the source code to do this.

## Describe the solution you'd like
We need a flag or hook to disable WooCommerce Blocks. No additional overhead should be added to WordPress if blocks are not used.

## Describe alternatives you've considered
We already unregistered set styles. But there is more, like the REST API handlers and this can change anytime again.

## Additional context
-

**Comment by danieldudzic** [comment]
Hi @cbratschi,

I have consulted on this with @senadir.

The only straightforward way of achieving this would be to use `remove_action('plugin_loaded', array( \Automattic\WooCommerce\Package, 'on_init');` which will also remove the WooCommerce Admin so you'd need to have another action on `plugin_loaded` to `call \Automattic\WooCommerce\Admin\Composer\Package::init();`.

Out of curiosity, would you mind elaborating on where did you notice the performance impact?

**Comment by danielwrobert** [comment]
@cbratschi I’m going to close this because there doesn't seem to be anything actionable for us at this point, given the above response by @danieldudzic. If/when you have additional details, you can still add them to this Issue and we can re-open it, if necessary.

Thanks!

**Comment by cbratschi** [comment]
@danieldudzic we use our own monitoring tools to check time spent in hooks. In case of Automattic\WooCommerce\Blocks\BlockTypesController::register_blocks the overhead is about 25 ms. We measured this in REST API calls where this is about 10% of the overall response time.

We always prefer clean solutions to not get into trouble with plugin updates. The provided workaround could be troublesome in future.
