### ISSUE TITLE
Mini Cart Icon size control 

### ISSUE THREAD

**Issue by vivialice** [woocommerce/woocommerce-gutenberg-products-block#6922]
## Describe the solution you'd like
Now that we have the text size control working well, it enhances the need to add controls for the mini cart icon size. 

<img width="595" alt="Screenshot 2022-08-18 at 15 44 44" src="https://user-images.githubusercontent.com/9888201/185424022-71d6a28c-2a94-451b-92fe-1bf3f7ae3d18.png">

I haven't mocked up a design for how we could handle this, but I think we could use controls that exist. 

Ideas? 

- I found this option as part of Jetpacks Avatar block:
<img width="281" alt="Screenshot 2022-08-18 at 15 53 50" src="https://user-images.githubusercontent.com/9888201/185426517-6868d44d-3598-4a07-af3b-7ee3e6949efe.png">

We could use the panel section title `Icon dimensions` and `Size` for the slider header. 

- Or we could use presets similar to Image block: 

<img width="311" alt="Screenshot 2022-08-18 at 15 58 00" src="https://user-images.githubusercontent.com/9888201/185427457-5d06f50c-994e-4415-8927-b0366c780228.png">

**Comment by danielwrobert** [comment]
Per a conversation with @vivialice, I am going to go ahead and close this Issue out for now.

The icon and badge currently scale with the price text size. This is also the behavior for the Customer Account block so we decided it would be best to keep them consistent.

Also [closed and noted](https://github.com/woocommerce/woocommerce-blocks/pull/7166#issuecomment-1375807842) on #7166.
