### ISSUE TITLE
Store API CartShippingRate hook suggestion

### ISSUE THREAD

**Issue by oberonlai** [woocommerce/woocommerce-gutenberg-products-block#6940]
Hi

Is it possible to add apply_filter with shipping rate response in Store API? I want to add my custom fields of shipping methods. The source code is in src/StoreApi/Schemas/V1/CartShippingRateScehma.php line 304 with function `get_rate_response()`. 

Or is there another way to extend the existing schema without ExtendSchema? I suppose to use ExtendSchema to extend shipping response, but it's a little bit redundant. I hope I can use the extend the existing shipping_rate to implement. Thanks for your help.

**Comment by senadir** [comment]
You can experiment with rate meta, while we won't add such filter the API, you can use `woocommerce_shipping_method_add_rate` if you don't own the code to that rate, or simply add them to `meta_data` when calling `WC_Shipping_Method::add_rate()`.

The reason we don't add filters to API responses is that it risks creating unpredictable responses that will have cascading effects on the UI, if not from you, then from other plugins and other people.

**Comment by oberonlai** [comment]
Hi Senadir,

Thanks for your reply. I got your point why you can't add this filters. I'll try your suggestion to add shipping meta in Store API.
