### ISSUE TITLE
Add validation mechanism to Mini Cart block

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#6941]
## Describe the bug

Currently, it's not possible to display errors in the Mini Cart block. That's an issue for some extensions, that have specific validation rules in the cart context.

## To reproduce

1. Add the Mini Cart block to the header of your store.
2. Install [Product Bundles](https://woocommerce.com/products/product-bundles/).
3. Create a Product bundle product with _Min Bundle Size_ and _Max Bundle Size_ values (ie: 2 and 4).

![imatge](https://user-images.githubusercontent.com/3616980/185574792-02a8c3df-ce7e-47ee-b57e-52e723e7c455.png)

4. Go to the frontend of the site, and add the Product bundle product you just created to your cart.
5. Open the Mini Cart and change the quantities of the inner products to something bigger than the _Max Bundle Size_.

<img src="https://user-images.githubusercontent.com/3616980/185575486-d44fbccf-7527-42c0-875e-1f706c58435d.png" alt="" width="473" />

6. Notice you are allowed to do it and no error is shown.
7. Go to the Cart page.
8. Notice there is an error on top of the block:
<img src="https://user-images.githubusercontent.com/3616980/185575363-9d08bbfa-8930-4f35-9d58-9253956745e3.png" alt="" width="733" />

## Expected behavior

The same error that is shown in the Cart block should be shown in the Mini Cart block.

## Additional context

That's because the Cart block has a validation mechanism while the Mini Cart block doesn't. We should add the same validation mechanism so extensions can register errors.

**Comment by solstudioim** [comment]
Reported in 5481840-zd-woothemes

**Comment by gigitux** [comment]
Unfortunately, I wasn't able to replicate the error with your repro steps, but I was able to reproduce it in another way and fix the issue. Please, check #7234.
