### ISSUE TITLE
Different behavior of the Product Button block when it is used in the Product Query Block and it is used in the All Products Block

### ISSUE THREAD

**Issue by gigitux** [woocommerce/woocommerce-gutenberg-products-block#6949]
The Product Button block when it is used in the All Products block shows how many times the product has been added to the cart:

![Screen Capture on 2022-08-19 at 14-28-30](https://user-images.githubusercontent.com/4463174/185659417-70b98fb8-48f1-459f-82c7-2f091596b651.gif)

The behavior is different when it is used in the Product Query block:

![Screen Capture on 2022-08-19 at 14-28-54](https://user-images.githubusercontent.com/4463174/185659391-0b385ead-0830-43b2-8fdb-8f4b8b3f676f.gif)

Our goal is to have the same behavior (the first one) in the next iterations.

**Comment by sunyatasattva** [comment]
We discussed about this, and the conclusion was that it is probably not worth to fix this by itself, but instead wait for Frontity and the full hydration system.

**Comment by gigitux** [comment]
Fixed by #10006
