### ISSUE TITLE
Add support for customizing Cart/Checkout colors and fonts

### ISSUE THREAD

**Issue by EVCV** [woocommerce/woocommerce-gutenberg-products-block#6955]
## What do you like about the Cart & Checkout blocks?

It is a clean and simple design

## What do you think is missing from the Cart & Checkout blocks?

ability to customise all the colours, text and layout of all the cart and checkout.

**Comment by nielslange** [comment]
Hello @EVCV 👋

> ability to customise all the colours, text and layout of all the cart and checkout.

Thanks so much for taking the time to leave some feedback – much appreciated! We make note of all feedback we receive, and we also close issues with the feedback, as active issues are used for bugs or feature/enhancements. It does not mean that we don’t note or review the feedback. Closed issues can also still be commented on.
