### ISSUE TITLE
Fix Gutenbergs FormTokenField component upstream

### ISSUE THREAD

**Issue by tjcafferkey** [woocommerce/woocommerce-gutenberg-products-block#6961]
## Describe the bug

We currently use the `<FormTokenField />` component for our dropdown in the Filter by Attribute block. There is an issue whereby when we click "Reset" on the filters we have selected, the dropdown automatically opens. We created a workaround for this to fix it on our end but we need to do an upstream fix for this.

More information can be found on this here https://github.com/woocommerce/woocommerce-blocks/pull/6920#issuecomment-1222402482

## To reproduce

If [this PR](https://github.com/woocommerce/woocommerce-blocks/pull/6920) is not merged, please checkout the branch instead.

1. Add Filter by Attribute to a page and ensure its using the dropdown style & has the apply filter button active.
2. On the frontend, open the dropdown and select an attribute but don't click the "Apply" filter button
3. Instead click "Reset"
4. See the dropdown automatically open now.

## Expected behavior

On step 4 the dropdown should not open

**Comment by Aljullu** [comment]
@tjcafferkey should we close this issue? We will stop using `@wordpress/components` in the frontend (https://github.com/woocommerce/woocommerce-blocks/issues/8452), so that includes `FormTokenField`.

**Comment by tjcafferkey** [comment]
Yeah, I think it's safe to close this issue in this case.
