### ISSUE TITLE
Clean the top-level of the `/build` folder

### ISSUE THREAD

**Issue by tarhi-saad** [woocommerce/woocommerce-gutenberg-products-block#6972]
After the changes introduced in the #6737 PR, the `/build` folder is currently [polluted with so many top-level folders](https://github.com/woocommerce/woocommerce-blocks/pull/6737#discussion_r933517699). To fix this, we can choose to generate the `Inner Blocks` `blocks.json` files inside a parent folder (e.g., `/checkout-blocks` and `/cart-blocks`).

This is the code block to update:

https://github.com/woocommerce/woocommerce-blocks/blob/b220e4937665119c139a01f43f0149111c95444b/bin/webpack-configs.js#L264-L277

<img width="400" alt="image" src="https://user-images.githubusercontent.com/14235870/186400699-609ce639-a505-4bee-8687-8514439fe608.png">

**Comment by senadir** [comment]
This fix wouldn't affect JS translation loading (only concerns PHP translation loading) so it's fine to fix without backward compatibility.
