### ISSUE TITLE
Display view switcher for Cart Block when selecting inner blocks   

### ISSUE THREAD

**Issue by tarunvijwani** [woocommerce/woocommerce-gutenberg-products-block#6985]
## Describe the bug

`__experimentalExposeControlsToChildren`  was added by the [PR](https://github.com/woocommerce/woocommerce-blocks/pull/4817) to display the view switcher when selecting the inner blocks of the Cart block. It was dependent on [PR opened in Gutenberg repo](https://github.com/WordPress/gutenberg/pull/35078), which was never merged. 

Currently, the view switcher is only visible when we select the parent Cart block, which is nearly impossible to select without using the list view option. It can be done now using a filter. 

## To reproduce

1. Go to Cart block. 
2. Click on any inner block
3. Notice there is no option to select view switcher

## Expected behavior

View switcher should be displayed when selecting inner blocks

**Comment by ralucaStan** [comment]
Related to https://github.com/woocommerce/woocommerce-blocks/issues/6698

**Comment by tarunvijwani** [comment]
Marking this issue on hold for further discussion: pca54o-4DS-p2
