### ISSUE TITLE
Add validation error for shipping calculator in Cart block 

### ISSUE THREAD

**Issue by tarunvijwani** [woocommerce/woocommerce-gutenberg-products-block#6989]
## Describe the bug

The shipping calculator does not display a validation error if we enter an incorrect zip code.

## To reproduce

1. Add a product to the cart and go to the Cart block
2. Add a new address with an invalid zip code in the Shipping calculator, different from what you already used
3. Click on the Update button and wait for the update.
4. Notice there is no validation error. 

## Expected behavior

There should be a client-side validation 

## Additional context

Refer to the slack conversion: p1659013772168479-slack-C8X6Q7XQU

**Comment by tarunvijwani** [comment]
We'd need to add the client-side validations to display the error. More details: p1659013772168479-slack-C8X6Q7XQU

**Comment by tarunvijwani** [comment]
Marking this issue on hold for further discussion: pca54o-4O7-p2

**Comment by tarunvijwani** [comment]
We're adding client-side validation in #7722, which might resolve this issue.

**Comment by wavvves** [comment]
Might be useful to look at [this issue](https://github.com/woocommerce/woocommerce-blocks/issues/7486) too, although not on the same scope

**Comment by nielslange** [comment]
Closing this issue as the problem no longer appears.
