### ISSUE TITLE
Filter products by attribute block not working for terms with non-ASCII characters

### ISSUE THREAD

**Issue by Konamiman** [woocommerce/woocommerce-gutenberg-products-block#6993]
## Describe the bug

When a product attribute defines terms with non-ASCII characters the "Filter products by attribute block" doesn't work, no products are displayed whatsoever when selecting one of the terms in the block.

## To reproduce

See https://github.com/woocommerce/woocommerce/pull/34432#issuecomment-1225464870, basically create a product attribute that has terms with non-ASCII characters, create products having these terms, add the block to filter by that attribute, and verify that selecting any of the non-ASCII terms in the block yields no results.

## Expected behavior

The filter works as expected.

## Screenshots

First screenshot uses the old "Filter product by attribute" WooCommerce widget, second screenshot uses the block.

![image](https://user-images.githubusercontent.com/937723/186698245-ce72b4c6-b6fb-4e85-867c-aec89b995571.png)

![image](https://user-images.githubusercontent.com/937723/186698290-aee217d3-1b06-4974-b2ce-cb87293ecc4d.png)

### WordPress

-   Core version: 6.0
-   WooCommerce version: 6.9
-   WooCommerce Blocks version: 8.3.1

## Additional context

The problem is caused by an additional urlencoding in the generated url. See this example:

Old widget: `shop/?filter_大きさ=大&query_type_大きさ=or`
Block: `shop/?filter_大きさ=%25e5%25a4%25a7&query_type_大きさ=or`

The WooCommerce code that handles the query string wipes out the name of the term as part of the input sanitization process.

**Comment by gigitux** [comment]
Hi @Konamiman, thanks for opening an issue! 
I did an investigation, and I discovered that the Store API returns the slug already encoded. Unfortunately, the encoding is done by the `WP_Term_Query` class https://github.com/woocommerce/woocommerce-blocks/blob/300c9e117df6f7f5a3a75b4277290472401f867f/src/StoreApi/Routes/V1/AbstractTermsRoute.php/#L125-L126. Specifically [here](https://core.trac.wordpress.org/browser/tags/6.0.2/src/wp-includes/class-wp-term-query.php#L557). 
I think that we should fix the `WP_Term_Query`. What do you think?

**Comment by Konamiman** [comment]
@gigitux Ouch. Yes, looks like it's `WP_Term_Query` the one that needs fixing here.

**Comment by gigitux** [comment]
@Konamiman Can I transfer this issue to the WooCommerce Core repo?

**Comment by danieldudzic** [comment]
Hi @Konamiman!

I will close this issue for now.

Please re-open this issue in the WooCommerce Core repo.

Perhaps this can be resolved as a part of: https://github.com/woocommerce/woocommerce/pull/34432 ?

**Comment by Konamiman** [comment]
Hi @gigitux, sorry I missed your pings.

After taking a second look at this (since we got pinged about https://github.com/woocommerce/woocommerce/pull/34432 which somehow got approved but not merged) I still think that this should be fixed in Blocks.

If I understand correctly how it works, blocks queries the Store API and then renders the widget with the appropriate url for each option, all via JS code. Then it's fine for if the Store API returns the attribute names urlencoded: the Blocks JS code should take care of decoding it before generating the urls.

This would also make the urls generated by the block consistent with the urls generated by the old Woo widget. Also `WP_Term_Query` is provided by WordPress, not WooCommerce, so we can't really fix it (not easily at least) .

Other folks at Proton agree with me on this so I'm reopening the issue, please let me know what do you think about it.
