### ISSUE TITLE
Refactor payment status [after data store work is merged]

### ISSUE THREAD

**Issue by alexflorisca** [woocommerce/woocommerce-gutenberg-products-block#6998]
Thile working on [Feature: Data Store Migration](https://github.com/woocommerce/woocommerce-blocks/pull/6612#top), I realised thy payment status was implemented in quite a confusing way. On trunk, pre data store work, we had a `payment-method` state using a reducer, and a `payment-method-data-context` context that used some of that state, added to it, and exposed, well, more state, but as context. We tried to simplify this by combining both of those pieces of state into one and storing that in the data store. For the most part, this was successful, apart from the status. 

What we have now (post data store work), is a bit counterintuitive. We have a `currentStatus` state variable, with multiple boolean sub properties for each possible status. Something like this:

```js
{
    currentStatus: {
		isPristine: true,
		isStarted: false,
		isProcessing: false,
		isFinished: false,
		hasError: false,
		hasFailed: false,
		isSuccessful: false,
		isDoingExpressPayment: false,
	},
     ...
```

What would be more useful is to work out what the minimum state we need to store, and convert some of these properties to selectors, like we do in the checkout data store.

We also want to make sure that when setting the currentStatus to `pristine`, we are resetting all the necessary values to the default state.

**Comment by ralucaStan** [comment]
@senadir had some concerns around breaking backward compatibility with the proposed changes.
