### ISSUE TITLE
Terms and Conditions notice text isn't visible on dark mode

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#7008]
## Describe the bug

We're showing a notice if the terms and conditions is missing a link or a page isn't setup. That notice is showing white on white in dark themes and should be fixed.

![image](https://user-images.githubusercontent.com/6165348/187433018-24356f02-d564-406c-86a9-d0eaa6f9aa57.png)

### How to reproduce
- Load up a theme with a possible dark background, like 2022 FSE.
- Load Checkout block.
- Edit Terms and conditions text to remove links.
- See notice.

### Expected outcome
Text should not be white.

### Possible fixes
One fix is to force black text for the notice text, this is a blunt quick solution.

Preferred solution is to switch to using `Warning` instead of `Notice`. Warning seems to be the used method in several places to solve this issue and looks better.
<img width="704" alt="image" src="https://user-images.githubusercontent.com/6165348/187433436-3dc9e13e-50c3-49e3-9443-ba929ac692ef.png">

**Comment by ralucaStan** [comment]
Closing as these will be moved to the sidebar section
