### ISSUE TITLE
Out of stock

### ISSUE THREAD

**Issue by myfp31** [woocommerce/woocommerce-gutenberg-products-block#701]
**Describe the bug**
Hello,

When selecting products in the per category block, all products of the category are shown even out of stock product.
These "out of stock" product appears even if "Hide out of stock items from the catalog" is checked in woocommerce => setting => product => inventory.

**To Reproduce**

1. create two products. One out of stock.
2. create a new page.
3. create a block (all except on sale one)
4. See the two products.

**WordPress (please complete the following information):**

* Core version: 5.2.2
* PHP 7.1.30
* WooCommerce version: 3.6.5 
* WooCommerce Blocks version:2.2.1
* Site language: EN_US + FR
* theme : Oneline Lite 1.3.7
* Any other plugins installed:  30 others.

**Additional context**
seems to appear after the last update (Woocommerce or block).

Thanks in advance

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/722
