### ISSUE TITLE
Payment method block shows non integrated payment methods.

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#7011]
## Describe the bug

Slightly related to #7010 , we render payments method in the sidebar. However, the current logic shows **all** enabled payment methods, even one not integrated with Checkout block, I think this will create further confusion and we should only show integrated ones, or highlight ones that are not integrated from the others.

<img width="294" alt="image" src="https://user-images.githubusercontent.com/6165348/187439128-c349869e-bd4d-4133-8c90-e367407156dd.png">

## To reproduce

1. Enable PayPal payments.
2. Go to Checkout editor.
3. Select Payments step, you will see PayPal but it is not actually integrated.

## Expected behavior

Integrated payment methods should be highlighted separately from non-integrated ones.
Or, non-integrated ones shouldn't be shown there.

**Comment by ralucaStan** [comment]
Closing in favour of https://github.com/woocommerce/woocommerce-blocks/issues/7856
