### ISSUE TITLE
Support Editing Proceed to Checkout button text in Cart editor page.

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#7012]
We currently render a `Proceed To Checkout` page in Cart, the text of that button isn't editable via filters or Gutenberg, a great first step would be to support editing that text.

<img width="267" alt="image" src="https://user-images.githubusercontent.com/6165348/187440054-c38f099d-ad64-4dce-8344-aba9006a9467.png">

### Expected outcome
- You should be able to select the button and edit the text with no styling options.
A greater option would be to reuse the Button block or the button component or mimic that.

This should set the road to have full global styles support for that button, but that's a future goal.

A reminder to not fall into https://github.com/woocommerce/woocommerce-blocks/issues/7007 again is that we should mimic Button block and use `RichText` instead of `PlainText`.

**Comment by wavvves** [comment]
@senadir will a similar solution to [this](https://github.com/woocommerce/woocommerce-blocks/pull/7154) suffice?

**Comment by senadir** [comment]
No, that one is done with a filter, we're looking here to make it editable by the merchant on the editor, visually.
