### ISSUE TITLE
Explore ways to have a shared template part between Mini Cart and Cart blocks

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#7016]
With https://github.com/woocommerce/woocommerce-blocks/issues/7013 and https://github.com/woocommerce/woocommerce-blocks/issues/7012, we will provide users with the ability to edit the proceed to checkout button, this might include text for now, but in the future might be styles and colors as well.

To have a consistent user experience between those two blocks, the proceed to checkout block should be a shared part that persist both the label and styles.

This issue is here to explore if that's possible, and if it, propose a working PR toward it.

**Comment by senadir** [comment]
@tjcafferkey shared that this is possible (via this example)
https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/BlockTypes/MiniCart.php#L399-L413

**Comment by Aljullu** [comment]
Thinking out loud, but instead of a template part, maybe WC could create a [reusable block](https://wordpress.org/support/article/reusable-blocks/) that is used in Cart and Mini Cart blocks?

**Comment by albarin** [comment]
Adding the `won't fix` label for now, for more context check the conversation [here](https://github.com/woocommerce/woocommerce-blocks/pull/8738#issuecomment-1479054926).
