### ISSUE TITLE
Woo commerce email system isnt working

### ISSUE THREAD

**Issue by Nizamudeen-zayed** [woocommerce/woocommerce-gutenberg-products-block#7023]
Error found in debug log : 

[31-Aug-2022 07:15:07 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function PHPMailer\PHPMailer\mail() in /home/petzseec/public_html/wp-includes/PHPMailer/PHPMailer.php:874
Stack trace:
#0 /home/petzseec/public_html/wp-includes/PHPMailer/PHPMailer.php(1930): PHPMailer\PHPMailer\PHPMailer->mailPassthru('mnizamudeen6@gm...', '[Petzsee]: New ...', '<!DOCTYPE html>...', 'Date: Wed, 31 A...', NULL)
woocommerce/woocommerce-blocks#12058 /home/petzseec/public_html/wp-includes/PHPMailer/PHPMailer.php(1658): PHPMailer\PHPMailer\PHPMailer->mailSend('Date: Wed, 31 A...', '<!DOCTYPE html>...')
woocommerce/woocommerce-blocks#2 /home/petzseec/public_html/wp-includes/PHPMailer/PHPMailer.php(1494): PHPMailer\PHPMailer\PHPMailer->postSend()
woocommerce/woocommerce-blocks#3 /home/petzseec/public_html/wp-includes/pluggable.php(548): PHPMailer\PHPMailer\PHPMailer->send()
woocommerce/woocommerce-blocks#4 /home/petzseec/public_html/wp-content/plugins/woocommerce/includes/emails/class-wc-email.php(683): wp_mail(Array, '[Petzsee]: New ...', '<!DOCTYPE html>...', Array, Array)
woocommerce/woocommerce-blocks#5 /home/petzseec/public_html/wp-content/plugins/woocommerce/includes/emails/class-wc-email-new-order.php(110): WC_Email->send('mnizamudeen6@gm...', '[Petzsee]: New ...', '<!DOCTYPE html>...', 'Content-Type: t...', Array)
woocommerce/woocommerce-blocks#6 /home/petzseec/public_html/wp-includes/class-wp-hook.php(307): WC_Email_New_Order->trigger(41350, Object(Automattic\WooCommerce\Admin\Overrides\Order))
woocommerce/woocommerce-blocks#7 /home/petzseec/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
woocommerce/woocommerce-blocks#8 /home/petzseec/public_html/wp-includes/plugin.php(524): WP_Hook->do_action(Array)
woocommerce/woocommerce-blocks#9 /home/petzseec/public_html/wp-content/plugins/woocommerce/includes/class-wc-emails.php(170): do_action_ref_array('woocommerce_ord...', Array)
woocommerce/woocommerce-blocks#10 /home/petzseec/public_html/wp-includes/class-wp-hook.php(307): WC_Emails::send_transactional_email(Array, Object(Automattic\WooCommerce\Admin\Overrides\Order))
woocommerce/woocommerce-blocks#11 /home/petzseec/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
woocommerce/woocommerce-blocks#12 /home/petzseec/public_html/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
woocommerce/woocommerce-blocks#13 /home/petzseec/public_html/wp-content/plugins/woocommerce/includes/class-wc-order.php(373): do_action('woocommerce_ord...', 41350, Object(Automattic\WooCommerce\Admin\Overrides\Order))
woocommerce/woocommerce-blocks#14 /home/petzseec/public_html/wp-content/plugins/woocommerce/includes/class-wc-order.php(222): WC_Order->status_transition()
woocommerce/woocommerce-blocks#15 /home/petzseec/public_html/wp-content/plugins/woocommerce/includes/class-wc-order.php(334): WC_Order->save()
woocommerce/woocommerce-blocks#16 /home/petzseec/public_html/wp-content/plugins/woocommerce/includes/gateways/cod/class-wc-gateway-cod.php(327): WC_Order->update_status('processing', 'Payment to be m...')
woocommerce/woocommerce-blocks#17 /home/petzseec/public_html/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(982): WC_Gateway_COD->process_payment(41350)
woocommerce/woocommerce-blocks#18 /home/petzseec/public_html/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1206): WC_Checkout->process_order_payment(41350, 'cod')
woocommerce/woocommerce-blocks#19 /home/petzseec/public_html/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(461): WC_Checkout->process_checkout()
woocommerce/woocommerce-blocks#20 /home/petzseec/public_html/wp-includes/class-wp-hook.php(307): WC_AJAX::checkout('')
woocommerce/woocommerce-blocks#21 /home/petzseec/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
woocommerce/woocommerce-blocks#22 /home/petzseec/public_html/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
woocommerce/woocommerce-blocks#23 /home/petzseec/public_html/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(90): do_action('wc_ajax_checkou...')
woocommerce/woocommerce-blocks#24 /home/petzseec/public_html/wp-includes/class-wp-hook.php(307): WC_AJAX::do_wc_ajax('')
woocommerce/woocommerce-blocks#25 /home/petzseec/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(false, Array)
woocommerce/woocommerce-blocks#26 /home/petzseec/public_html/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
woocommerce/woocommerce-blocks#27 /home/petzseec/public_html/wp-includes/template-loader.php(13): do_action('template_redire...')
woocommerce/woocommerce-blocks#28 /home/petzseec/public_html/wp-blog-header.php(19): require_once('/home/petzseec/...')
woocommerce/woocommerce-blocks#29 /home/petzseec/public_html/index.php(17): require('/home/petzseec/...')
woocommerce/woocommerce-blocks#30 {main}
  thrown in /home/petzseec/public_html/wp-includes/PHPMailer/PHPMailer.php on line 874

Not receiving mail when a customer register,purchases .

**Comment by Nizamudeen-zayed** [comment]
try https://petzsee.com/product/avianbreeder-fruitblend-diet-cockatiels-40lb-18-14kg/ doing check out you will not recieve email for confirmation

**Comment by wavvves** [comment]
Hello @Nizamudeen-zayed, thanks for reaching out with this.
Unfortunately, this issue is not related to this repository. You may want to try and contact WordPress support as it seems unrelated to WooCommerce.
[This](https://wordpress.org/support/topic/fatal-error-uncaught-error-call-to-undefined-function-phpmailer/) may also be a good starting point to look for a possible answer.

**Comment by nielslange** [comment]
I'm closing this issue for now, as it's not related to WooCommerce Blocks. That said, if you experience any other problems, that are related to WooCommerce Blocks, feel free to create a new issue via https://github.com/woocommerce/woocommerce-blocks/issues/new/choose.
