### ISSUE TITLE
New Block: Recently Viewed Products

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-gutenberg-products-block#704]
**User Story**
As a merchant
I want a block that shows a list of products that a user has previously browsed
So I can allow users to get back to them easily if need be

**Acceptance Criteria**
- The merchant can see in the editor a block example with 4 products as default. They should be the most recently viewed products of his entire inventory, first to last.
- If the merchant has less than 4 products, the default view should be adjusted to the number of products on their inventory: 3 products (3 columns), 2 products (2 columns), 1 product (1 column)
- The merchant can control the number of rows for the block (layout setting)
- The merchant can control the number of columns for the block (layout setting)
- The number of columns is set by default to 4 (content setting)
- The merchant can show/hide the product title (content setting)
- The merchant can show/hide the product rating (content setting)
- The merchant can show/hide the product price (content setting)
- The number of products is set by default to 4 (content setting)
- The merchant can change the number of products that are shown (content setting)
- The merchant can add CSS additional class (advanced setting)
- Layout and Content settings are expanded by default
- Advanced setting is collapsed by default

**Additional links**
P2: `p6riRB-4yg-p2`
[Prototype](https://www.figma.com/file/TDJTN1qpgVMB7MbOGVHNF0jI/Recently-Viewed-Products?node-id=0%3A1)

**Comment by jwold** [comment]
This looks really great @pmcpinto ! Having you write out the AC helps you understand if you're interpreting the design correctly, and helps me know if I need to be more clear on specific design elements. Thanks!

There are just two AC that I wanted to followup on:

> **They can be displayed randomly or alphabetically**

I'd suggest removing this part. The block should instead show the most recently reviewed product first to last. Quick sketch example:

![IMG_0217](https://user-images.githubusercontent.com/3411173/60906582-4b791d00-a22c-11e9-9049-7768649ecde6.JPG)

----

> **If the merchant has less than 4 products, the number of columns set as default should also be updated: 3 products (3 columns), 2 products (2 columns)**

Just wanted to validate that you're expecting it would function similar to the "Products by Category" block? Quick video: https://v.usetapes.com/WhugE9306g

----

**Comment by pmcpinto** [comment]
> Having you write out the AC helps you understand if you're interpreting the design correctly, and helps me know if I need to be more clear on specific design elements. Thanks!

I think it's a good way to validate everything and see if we're not missing any detail that can be a blocker in terms of UX or Dev :)

> I'd suggest removing this part. The block should instead show the most recently reviewed product first to last.

Just to confirm: so your idea is that the merchant is able to see as an example the most recently viewed products of his entire inventory, right?

> Just wanted to validate that you're expecting it would function similar to the "Products by Category" block? Quick video: https://v.usetapes.com/WhugE9306g

Basically what I would like to avoid is predefining the number of columns as 4, to correctly display 4 producs in the block, but if the user only has 2/3 products in the inventory it will look weird to display them in 4 columns. Pls see this eg: https://cld.wthms.co/t1uk43 Makes sense?

**Comment by jwold** [comment]
> Just to confirm: so your idea is that the merchant is able to see as an example the most recently viewed products of his entire inventory, right?

Yes. I think we're on the same page with this one.

> Basically what I would like to avoid is predefining the number of columns as 4, to correctly display 4 producs in the block, but if the user only has 2/3 products in the inventory it will look weird to display them in 4 columns. Pls see this eg: https://cld.wthms.co/t1uk43 Makes sense?

Oh, I get it. You're saying:

If a store only has 2 products, and they go to insert this block, instead of default to 4 column view, default to 2 column view. 

Then, if they want to get that weird situation where they have 2 products on 4 columns they could (https://cld.wthms.co/t1uk43), but that'd be only if they did it intentionally but changing columns around after the fact. 

So you're trying to just make a better looking default view that adjusts the block based on if they have less than 4 products. I like that. Smart thinking.

**Comment by pmcpinto** [comment]
> So you're trying to just make a better looking default view that adjusts the block based on if they have less than 4 products.

Yes, that's right. I'm assuming that not all merchants want to spend time adjusting the block layout or that they notice that it's going to look weird on the frontend.
