### ISSUE TITLE
Revisit payment status logic 

### ISSUE THREAD

**Issue by alexflorisca** [woocommerce/woocommerce-gutenberg-products-block#7040]
## Describe the bug
The payment status logic is confusing and there are scenarios where if stripe throws an error, the payment is considered successful.

Try checking out with the following stripe test cards, while checking the value of the payment status

4242 4242 4242 4242 - Checkout succeeds
4000 0025 0000 3155 - SCA prompt appears, if you choose to fail, then checkout fails, if you choose to succeed then the checkout succeeds
4000 0082 6000 3178 - Choose to succeed, but the payment should still fail because of insufficient funds
4000 0000 0000 9979- Checkout fails with generic card error. (This card is marked stolen).

**Comment by senadir** [comment]
Is this limited to Stripe only? This feels like an issue from the actual integration, do we have the actual statuses available in our system?

**Comment by alexflorisca** [comment]
I noted this issue down in a hurry while I was testing so I haven't dug into it properly yet, it's more of a note to self. I was planning on working on this next cycle as part of [this issue](https://github.com/woocommerce/woocommerce-blocks/issues/6625)

**Comment by alexflorisca** [comment]
Had a look into this and the reason for this issue is related to https://github.com/woocommerce/woocommerce-blocks/issues/6998. Because the `currentStatus` object is composed of multiple flags, we can have some pretty non-sensical values for it. Like these:

![Screenshot 2022-11-09 at 16 07 25](https://user-images.githubusercontent.com/3966773/200881803-2dc4b22d-bc22-404c-b28e-63c0298362d4.png)
This is from an actual use case, where a stripe test card is used and we are waiting for the user to authenticate via a modal. According to this, the current status is pristine, processing and finished at the same time.

We then fail the payment, the `isFinished` flag disappears completely, isPristine is still true and `hasFailed` is false. This is madness, pure madness. 
![Screenshot 2022-11-09 at 16 08 11](https://user-images.githubusercontent.com/3966773/200882046-d532c32c-d006-430e-b6e1-d171c523fd7b.png)

I will close this issue and address all of these in #6998
