### ISSUE TITLE
Custom Payment Method not displaying

### ISSUE THREAD

**Issue by pixlmint** [woocommerce/woocommerce-gutenberg-products-block#7041]
## Describe the bug

A plugin I'm supporting has it's own payment method, which works fine in the regular checkout form, but isn't displayed on the new checkout block. When I add the `woocommerce_available_payment_gateways` filter and output the first argument I get a list of gateways, where mine is in it as expected. 

## To reproduce

1. Add Custom Payment Gateway (view additional context)
2. [Register it](https://woocommerce.com/document/payment-gateway-api/#section-2)
3. Acitvate it in Admin
4. Add Product to Cart
5. Go to checkout

## Expected behavior

Custom Payment Method shows in Frontend as selectable

### WordPress (please complete the following information):

-   Core version: 6.0.2
-   WooCommerce version: 6.8.2
-   WooCommerce Blocks version: 8.4.0
-   Site language: German

### Desktop (please complete the following information):

-   OS: Ubuntu 20.04
-   Browser: Firefox
-   Version: 103.0

## Additional context

My custom payment method:
```php
<?php

if (!defined('WPINC')) {
    die();
}

class WC_Gateway_RiskCUBE extends WC_Payment_Gateway
{
    public $domain;

    public function __construct()
    {
        $this->domain = 'custom_payment';
        $this->id = 'riskcube_invoice';
        $this->icon = apply_filters('woocommerce_custom_gateway_icon', '');
        $this->has_fields = false;
        $this->method_title = __('Invoice', $this->domain);
        $this->method_description = __('Allows payments with invoice (managed by RiskCube).', $this->domain);

        $this->init_form_fields();
        $this->init_settings();

        $this->title = $this->get_option('title');
        $this->description = $this->get_option('description');
        $this->instructions = $this->get_option('instructions', $this->description);
        $this->order_status = $this->get_option('order_status', 'completed');

        add_action('woocommerce_update_options_payment_gateways_' . $this->id, [$this, 'process_admin_options']);
        add_action('woocommerce_thankyou_' . $this->id, [$this, 'thankyou_page']);

        add_action('woocommerce_email_before_order_table', [$this, 'email_instructions'], 10, 3);
    }

    public function init_form_fields()
    {

        $this->form_fields = [
            'enabled' => [
                'title' => __('Enable/Disable', $this->domain),
                'type' => 'checkbox',
                'label' => __('Enable Invoice Payment', $this->domain),
                'default' => 'yes'
            ],
            'title' => [
                'title' => __('Title', $this->domain),
                'type' => 'text',
                'description' => __('This controls the title which the user sees during checkout.', $this->domain),
                'default' => __('Invoice Payment (RiskCube)', $this->domain),
                'desc_tip' => true,
            ],
            'order_status' => [
                'title' => __('Order Status', $this->domain),
                'type' => 'select',
                'class' => 'wc-enhanced-select',
                'description' => __('Choose order status after checkout.', $this->domain),
                'default' => 'wc-completed',
                'desc_tip' => true,
                'options' => wc_get_order_statuses()
            ],
            'description' => [
                'title' => __('Description', $this->domain),
                'type' => 'textarea',
                'description' => __('Payment method description that the customer will see at checkout.', $this->domain),
                'default' => __('Payment Information', $this->domain),
                'desc_tip' => true,
            ],
            'instructions' => [
                'title' => __('Instructions', $this->domain),
                'type' => 'textarea',
                'description' => __('Instructions that will be added to the thank you page and emails.', $this->domain),
                'default' => '',
                'desc_tip' => true,
            ],
        ];
    }

    /**
     * Output for the order received page.
     */
    public function thankyou_page()
    {
        if ($this->instructions) {
            echo wpautop(wptexturize($this->instructions));
        }
    }

    /**
     * Add content to the WC emails.
     *
     * @access public
     * @param WC_Order $order
     * @param bool $sent_to_admin
     * @param bool $plain_text
     */
    public function email_instructions($order, $sent_to_admin, $plain_text = false)
    {
        if ($this->instructions && !$sent_to_admin && 'custom' === $order->payment_method && $order->has_status('on-hold')) {
            echo wpautop(wptexturize($this->instructions)) . PHP_EOL;
        }
    }

    /**
     * Process the payment and return the result.
     *
     * @param int $order_id
     * @return array
     */
    public function process_payment($order_id)
    {
        $order = wc_get_order($order_id);

        $status = 'wc-' === substr($this->order_status, 0, 3) ? substr($this->order_status, 3) : $this->order_status;

        // Set order status
        $order->update_status($status, __('Checkout with custom payment. ', $this->domain));

        // Reduce stock levels
        $order->reduce_order_stock();

        // Remove cart
        WC()->cart->empty_cart();

        // Return thankyou redirect
        return [
            'result'   => 'success',
            'redirect' => $this->get_return_url($order)
        ];
    }
}
```

**Comment by nielslange** [comment]
Hello @ChristianGroeber,

Thanks for reaching out to us. 

> A plugin I'm supporting has it's own payment method, which works fine in the regular checkout form, but isn't displayed on the new checkout block. When I add the woocommerce_available_payment_gateways filter and output the first argument I get a list of gateways, where mine is in it as expected.

The page https://woocommerce.com/document/payment-gateway-api/#section-2 describes how to register a custom payment gateway when using the old checkout page, which is built in PHP. As the new Checkout block is built in React/JS, a custom payment gateway needs to be registered as described on https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/checkout-payment-methods/payment-method-integration.md.

I hope this helps to integrate your custom payment method.

**Comment by pixlmint** [comment]
@nielslange
> ...As the new Checkout block is built in React/JS, a custom payment gateway needs to be registered as described on [/third-party-developers/extensibility/checkout-payment-methods/payment-method-integration.md](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/checkout-payment-methods/payment-method-integration.md).

Just for clarification, does my plugin need to register the payment method on the frontend by itself? Or is that handled by WC-Blocks? Because compiling Typescript for something that every payment method plugin needs to do sounds like a lot more trouble than it should be.

**Comment by nielslange** [comment]
Hello @ChristianGroeber,

> Just for clarification, does my plugin need to register the payment method on the frontend by itself? Or is that handled by WC-Blocks?

Yes, your custom payment method need to be registered both on the client- and the server-side. There's no need to use TypeScript, though. Your implementation can be done using JavaScript. There's no build process involved. We do understand how convoluted this is for simple payment methods and are looking at ways to make it easier in the future.

Please let me know if you have any further questions to implement your custom payment method.

**Comment by pixlmint** [comment]
@nielslange 
> Yes, your custom payment method need to be registered both on the client- and the server-side. There's no need to use TypeScript, though. Your implementation can be done using JavaScript.

I've implemented this JavaScript:
```javascript
wc.wcBlocksRegistry.registerPaymentMethod({
  name: 'Test Payment Method',
  label: 'test-payment-method',
  ariaLabel: 'Test Payment Method',
  content: null,
  edit: null,
  canMakePayment: function() {return true;},
})
```
but that gives me an error that `edit` and `content` need to be React Elements. How do I do that in plain JavaScript?

Thank you so much for your help by the way

**Comment by nielslange** [comment]
Hello @ChristianGroeber,

You can use the following code snippet, which ensures that both `edit` and `content` are React Elements:

```js
const Content = () => 'Payment description';

wc.wcBlocksRegistry.registerPaymentMethod({
  name: 'Test Payment Method',
  label: 'test-payment-method',
  ariaLabel: 'Test Payment Method',
  content: wp.element.createElement(Content, null),
  edit: wp.element.createElement(Content, null),
  canMakePayment: function () {
    return true;
  }
});
```

> Thank you so much for your help by the way

Thank you for making your custom payment method compatible to the WooCommerce Blocks! 🙌

**Comment by pixlmint** [comment]
@nielslange 
> You can use the following code snippet, which ensures that both `edit` and `content` are React Elements:

Thanks for that snippet, it seems  to work in that, when I execute `wc.wcBlocksRegistry.getPaymentMethods()` my payment method is shown in the list, but I cannot yet see it as selectable in the Payment Options List. Do I additionally need to enable it somewhere?

**Comment by pixlmint** [comment]
Okay I found the problem, and when I made a change to the customer form it works now, thank you so much for your help @nielslange, you were incredibly helpful!

**Comment by nielslange** [comment]
I'm glad to hear that you found the problem, @ChristianGroeber! 😀

**Comment by pixlmint** [comment]
@nielslange 
Quick question, there doesn't happen to be an easy way to add a spinner to the list of payment methods? Just like the one that's displayed on the shipping options.

**Comment by senadir** [comment]
Hey @ChristianGroeber! why would you need a spinner? loading management and such handled by WooCommerce Checkout.

**Comment by pixlmint** [comment]
@senadir Our plugin does credit checks, so we need to send the customer data to the server, verify it with an API, and then depending on that display the payment option to the end user. 

```javascript
    wc.wcBlocksRegistry.registerPaymentMethod({
        name: 'custom_payment',
        label: 'Invoice',
        ariaLabel: 'Invoice',
        content: wp.element.createElement(Content, null),
        edit: wp.element.createElement(Content, null),
        canMakePayment: function (data) {
            if (wc.rc.paymentMethodPermissionRunning) {
                return false;
            }
            wc.rc.paymentMethodPermissionRunning = true;
            return $.ajax({
                url: '/?rest_route=/rc/v1/verify-customer-data',
                method: 'POST',
                success: function (data) {
                    wc.rc.paymentMethodPermissionRunning = false;
                    return data.allowInvoice;
                }
            });
        }
    });
```

Here's the code that does that.
