### ISSUE TITLE
Featured Items: Inline style color defaults override Global Styles

### ISSUE THREAD

**Issue by danielwrobert** [woocommerce/woocommerce-gutenberg-products-block#7042]
## Summary

The text color defaults for the Featured Product and Featured Category blocks are set as inline styles. The problem is that the inline styles also override any changes to the block's Global Styles in the Site Editor.

## To reproduce

1. Ensure you have a block theme active (i.e., Twenty Twenty-Two).
2. Go to **Appearance > Editor (Beta)**.
3. Click on the **Global Styles** panel and select the **Blocks** section.
4. Scroll down to the Featured Product or Featured Category block and edit the text and the background Global Styles.
5. Notice that the background changes but the text remains white.

## Expected behavior

The text setting should also be adjustable when edited via Global Styles.

## Screenshots

| Global Styles Panel | Global Styles Block Setting |
| ------ | ----- |
|  ![CleanShot 2022-08-31 at 16 48 11](https://user-images.githubusercontent.com/481776/187010061-8c68fcb6-14f5-4509-99ce-2ad3bff43369.png)  |  ![CleanShot 2022-09-01 at 14 31 05](https://user-images.githubusercontent.com/481776/188728546-ccb4b0d9-60c4-49d8-a280-0462083a9a6e.png)  |

## Additional context

The purpose for the inline default, as implemented in #6492, was to ensure the white text over the overlay, as some theme styles (i.e., Storefront) were potentially interfering.

Now that we have Block Themes and Global Styles becoming more prevalent, we should ensure that our blocks are editable via the controls offered. We can add an editor-specific style for added specificity but we do not want so much specificity that the Global Styles are overridden, as they are currently. IMO, the theme styles should be responsible to ensure they are not unintentionally overriding global settings.

cc @Aljullu and @sunyatasattva for your input, as you were both involved in #6489 and #6492.

**Comment by sunyatasattva** [comment]
Nice catch @danielwrobert. It is indeed tricky, as we should decide on a specific hierarchy on how styles are applied. And that's more a difficult architecture question than anything. Your proposal to have themes take their own responsibilities seems logical. After all, we do the same with other plugins: we can't account for all the things plugins could break and we assume they should take responsibility for that.

However, this is definitely a conversation that requires some edge case thinking, or we risk ending up ping-ponging through some different solutions, I feel. Maybe a P2?
