### ISSUE TITLE
Mini Cart block icon is purple in Site Editor global styles list, while all other WC blocks icons are black

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#7059]
## To reproduce

1. With a block theme, go to Appearance > global styles > Blocks.
2. Notice the Mini Cart block icon is shown in purple, while all other WC blocks icons are displayed with the default black.

<img src="https://user-images.githubusercontent.com/3616980/188457648-ebc19508-d238-4849-b930-a3806abdc7f7.png" width="288" alt="" />

## Expected behavior

In the Site Editor global styles, the Mini Cart block icon should be black as the icons of the other blocks. However, it should continue being purple in the Inserter:

<img src="https://user-images.githubusercontent.com/3616980/188457868-19bd7688-2dee-4139-b4c8-818c10aef0cd.png" width="343" alt="" />

**Comment by chandu-jadhav** [comment]
hey can I  work on this issue?

**Comment by Aljullu** [comment]
Sure thing, @chandu-jadhav! You can read how to get started with WC Blocks development here:

https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/contributors/contributing/getting-started.md

In order to fix this specific issue, you can find the block icons in this folder:

https://github.com/woocommerce/woocommerce-blocks/tree/trunk/assets/js/icons/library

Hope that helps! Let us know if you have any other questions.

**Comment by Aljullu** [comment]
Closing this as a duplicate of #7037.
