### ISSUE TITLE
New Block: Cart Preview

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-gutenberg-products-block#706]
**User Story**
As a merchant
I want a block with the cart preview
So I can have some flexibility around the cart preview placement on my store

**Acceptance Criteria**
- If the merchant has 0 products, could we display 3 fake products from storefront?
- If the merchant has 1-2 products, just show those 1-2 products.
- If the merchant has 3 products, show those 3.
- If the merchant has 4+ products, show 3 of them randomly (not alphabetically)
- The merchant can see the cart in the preview with the same products
- If the merchant has some items in the cart, he should be able to see the cart updated with those products in the frontend
- Merchant can show/hide the checkout button (content settings)
- Merchant can show/hide the thumbnail (content settings)
- Merchant can show/hide the cart if it's empty (content settings)
- The merchant can add CSS additional class (advanced setting)
- Content settings are expanded by default
- Advanced setting is collapsed by default

**Additional links**
P2: p6riRB-4xY-p2
[Prototype](https://www.figma.com/file/bVBF9mC3wkzOP5kyrxtUHY/Cart-Preview?node-id=6%3A0)

**Comment by jwold** [comment]
@pmcpinto, want to followup on one of the AC:

> The merchant can see in the editor the cart with 3 products as default. They can be displayed randomly or alphabetically

Been thinking through this, and even though that was based on the P2, we might want to update this AC a bit:

* If the merchant has 0 products, could we display 3 fake products from storefront? 
* If the merchant has 1-2 products, just show those 1-2 products.
* If the merchant has 3 products, show those 3. 
* If the merchant has 4+ products, show 3 of them randomly (not alphabetically)

**Comment by pmcpinto** [comment]
@jwold thanks for the feedback. I think those suggestions make sense. I'm going to update the AC.
