### ISSUE TITLE
New Block: Cart Link

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-gutenberg-products-block#708]
**User Story**
As a merchant
I want a block with a short/simplified version of the cart preview
So I can have some flexibility around the cart preview placement on my store

**Acceptance Criteria**
- The block should only show the subtotal of what the user is purchasing, how many items are in the cart, and an icon of the cart.
- If the user hovers or clicks in the cart link it will display the same view as the cart preview, and can be interacted with at that point.
- Merchant can view the cart link in the editor but he can't interact with it 
- On a mouse input device - If the user hovers over the cart link it will display the same view as the cart preview, and can be interacted with at that point.
- On a mouse input device - If the user clicks on the cart link it will take them to the cart.
- On a touch input device - If the user taps on the cart link it will take him to the cart.
- Merchant can show/hide the cart preview checkout button (content settings)
- Merchant can show/hide the cart preview thumbnail (content settings)
- Merchant can show/hide the cart if it's empty (content settings)
- The merchant can add CSS additional class (advanced setting)
- Content settings are expanded by default
- Advanced setting is collapsed by default

**Additional links**
P2: `p6riRB-4xY`
[Prototype](https://www.figma.com/file/ahiyJNvkOVNPzDec1JFodK/Cart-Link?node-id=0%3A1)

**Comment by jwold** [comment]
> **If the user hovers or clicks in the cart link it will display the same view as the cart preview, and can be interacted with at that point.**

and

> **In the preview the merchant can click/hover the cart link and see the cart preview**

I would change this to:

> On a mouse input device - If the user hovers over the cart link it will display the same view as the cart preview, and can be interacted with at that point. 
> On a mouse input device - If the user clicks on the cart link it will take them to the cart. 
> On a touch input device (tested on an iPad) - If the user taps once on the cart link it will display the same view as the cart preview, and can be interacted with at that point. 
> On a touch input device - If the user taps a second time on the cart link (after opening the cart preview) they should be taken to the cart. 

It's a bit more complex, but that copies the existing functionality: https://veganfoodpyramidcom.wpcomstaging.com/

**Comment by pmcpinto** [comment]
@jwold thanks. All of those changes make sense too. The only one that I'm not 100% sure about is regarding the behavior on a touch input device. Do you think it's worthy to display the cart preview modal instead of directly taking the user to the cart page?

Correctly displaying a modal on mobile it's usually tricky and I just tested some ecommerce platforms on my phone and they opt to redirect the user to the cart page. Lmk what do you think about it

**Comment by jwold** [comment]
@pmcpinto 

> Correctly displaying a modal on mobile it's usually tricky and I just tested some ecommerce platforms on my phone and they opt to redirect the user to the cart page. Lmk what do you think about it

Oh good point. I agree with you. 

When I tested, I was testing on an iPad Pro with iOS 13, which has a desktop like browsing experience. That's not the same as mobile. 

Let's redirect mobile users to the cart instead of opening the preview.

**Comment by pmcpinto** [comment]
@jwold Perfect, I'm going to update the AC. Thanks
