### ISSUE TITLE
Don't pull entire state from `wc/store/checkout` and instead make more focused selectors

### ISSUE THREAD

**Issue by opr** [woocommerce/woocommerce-gutenberg-products-block#7080]
In https://github.com/woocommerce/woocommerce-blocks/blob/adcf87e09954665950d24b21bfa0107b6cc80e7d/assets/js/base/context/providers/cart-checkout/checkout-processor.js#L57 we get the entire state of the data store. 

This is not ideal, and we should remove this selector
https://github.com/woocommerce/woocommerce-blocks/blob/361b48b6220f57fab8a62b9a9272757530d6f14a/assets/js/data/checkout/selectors.ts#L47

Wherever `getCheckoutState` is used, refactor it and take a more explicit approach to what we're pulling out of the data store.

**Comment by tarunvijwani** [comment]
This is already resolved in #7713
