### ISSUE TITLE
Set Columns to 1 When in List View

### ISSUE THREAD

**Issue by spencerfinnell** [woocommerce/woocommerce-gutenberg-products-block#71]
The column count should be set to 1 to override the shortcode's default column output when in List View

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/assets/js/products-block.jsx#L599

When using List View you currently get markup like

```html
<div class="woocommerce columns-3 list-layout">
  <ul class="products columns-3"></ul>
</div>
```

Which is very hard to style because existing theme support for `columns-x` will likely override anything set by `list-layout`.

Setting it to 1 will help, or removing the column markup completely would be even better.

**Comment by claudiulodro** [comment]
Closing this because we're removing the list view. See https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/70
