### ISSUE TITLE
Feedback on ./src/StoreApi/docs/checkout.md

### ISSUE THREAD

**Issue by mariusbolik** [woocommerce/woocommerce-gutenberg-products-block#7106]
Hello, thank you for your work. I really appreciate it!

Could you be so kind and add more information to the attributes for the POST request?
How has the `billing_address`, `payment_method` and `payment_data` object to look like?

Can you also provide an example for apple pay and google pay? We want to use apple pay and google pay in our mobile app and send the response tokes to the `/checkout` endpoint, so the payment can be processed.

Kind regards,
Marius

**Comment by opr** [comment]
Hey @mariusbolik thanks for taking the time to provide feedback on our documentation.

Relating to Apple/GPay I would love to know more about your use-case. The [WooCommerce Stripe Payment Gateway](https://wordpress.org/plugins/woocommerce-gateway-stripe/) plugin offers GPay and Apple Pay functionality - is this something you could leverage in your app?

If not, then you may need to integrate this yourself by using the [payment method integration api](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/checkout-payment-methods/payment-method-integration.md#props-fed-to-payment-method-nodes) we offer.

[I've created an issue](https://github.com/woocommerce/woocommerce-blocks/issues/7157) to document the `billing_address`, `payment_method` and `payment_data` objects in the POST request to the checkout endpoint in `src/StoreApi/docs/Checkout.md`.

For now, you can see this example POST request, I hope it's useful.

```
{
  "billing_address": {
    "first_name": "Jonny",
    "last_name": "Awesome",
    "company": "",
    "address_1": "1 Rodeo Drive",
    "address_2": "",
    "city": "Beverly Hills",
    "state": "CA",
    "postcode": "90210",
    "country": "US",
    "email": "some.email@gmail.com",
    "phone": ""
  },
  "customer_note": "",
  "create_account": false,
  "payment_method": "cod",
  "payment_data": [
    {
      "key": "wc-cod-new-payment-method",
      "value": false
    }
  ],
  "extensions": {},
  "shipping_address": {
    "first_name": "Jonny",
    "last_name": "Awesome",
    "company": "",
    "address_1": "1 Rodeo Drive",
    "address_2": "",
    "city": "Beverly Hills",
    "state": "CA",
    "postcode": "90210",
    "country": "US",
    "phone": ""
  }
}
```

The `payment_data` will be specific to your payment method, so I can't advise further on that.

I'll close this issue and use #7157 to track progress on improving the docs. Feel free to subscribe to that for updates.

Thank you!

**Comment by mariusbolik** [comment]
Hello @opr, thank you very much!

We currently develop an app that allows users to purchase products directly inside the app. We allow Apple Pay, Google Pay and Credit Card as payment methods. Could you please provide me with an example of the `payment_data` object for Apple Pay and Credit Card?

We receive the following Information from Apple Pay:
```
{
  paymentData: "eyJ2ZXJzaW9uIjoiRUNfdjEiLCJkYXRhIjoibDZlQ3pkVGpYcVAM3RmNGhBUnVQTU91RThDdG8rYzpRTHNZbW1UOENgreG8xbmxqQ0REajRTeFZ4U0cxZ1pCRWVX…",
  paymentMethod: {
  network: "Visa",
   billingAddress: {},
   displayName: "Visa 4016"
},
  transactionIdentifier: "1F550CDE07135EE9E59C91A66C518FFAA670753B4EC58BC02447711E68ED9CE8"
}
``` 
I think Google Pay returns the credit card information directly.

Regards,
Marius

**Comment by opr** [comment]
Hi there @mariusbolik, thanks for the extra info!

As mentioned previously, the `payment_data` object will be specific to your implementation, so not something I could send you. The `payment_data` object would be used to send data from the front-end to the back-end. 

I am not familiar with Apple Pay and its API, but as an example, you may want to know the `transactionIdentifier` on the back-end, or save it when saving the order. If that's the case, then that is something that should be present in `payment_data`. Besides the payment method ID, we don't expect or require anything in the `payment_data` object.

More information can be found in the [Payment Method Integration document](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/checkout-payment-methods/payment-method-integration.md#server-side-integration)

I hope this is useful but please feel free to keep the conversation going if you need more help or if anything is unclear.

**Comment by mariusbolik** [comment]
Hi @opr, thank you!
One last question for my understanding: Can I use the WooCommerce Store Rest API to execute a Stripe Payment on the WordPress Backend by sending the credit card information to the API without customizing anything? My favorite solution would be that I send all information like address and payment information to the API so that WooCommerce can process the payment via Stripe. Just as if someone had bought through the website.

**Comment by opr** [comment]
Hi @mariusbolik, as far as I understand it, you need to do a little more than sending the plain card details through. This is not something I'm very familiar with, but I believe (and please check with the Stripe documentation) that you need to get a token from the Stripe API (this is the user's card details but tokenised for security) before submitting, then when you submit to the back end, your `payment_data` should contain this token rather than the card details. Then, with that token you'll process the payment on the server.

An example of `payment_data` when I used one of the Stripe test cards:

```js
[
    {
        "key": "stripe_source",
        "value": "src_1LuuBZHDvQQ4mw4hrIT5UTNA"
    },
    {
        "key": "billing_email",
        "value": "jonny.awesome@gmail.com"
    },
    {
        "key": "billing_first_name",
        "value": "Jonny"
    },
    {
        "key": "billing_last_name",
        "value": "Awesome"
    },
    {
        "key": "paymentMethod",
        "value": "stripe"
    },
    {
        "key": "paymentRequestType",
        "value": "cc"
    },
    {
        "key": "wc-stripe-new-payment-method",
        "value": true
    }
]
```

The [`WooCommerce Stripe Payment Gateway`](https://github.com/woocommerce/woocommerce-gateway-stripe) plugin is open-source so you could look there to see how they do things, that might be helpful?

Again, please do check with Stripe about their processes to be extra sure you're on the right path!

**Comment by revnelson** [comment]
Where can I find more info on what payment_data I should be sending with Stripe payments? I have a stripe payment intent and using WP-GraphQL I was able to simply pass this to get the order to be created and marked as paid within WooCommerce. However, I have tried sending `[{ key: "_stripe_intent_id", value: "example_intent_id" }]` along with a checkout POST call, but the order comes back failed.
