### ISSUE TITLE
Clear items at checkout > translated error message not displayed 

### ISSUE THREAD

**Issue by Marc-pi** [woocommerce/woocommerce-gutenberg-products-block#7107]
## Describe the bug

follow up / declared previously https://github.com/woocommerce/woocommerce-blocks/issues/6662 (see point 4)

The translated value is not displayed in French FR, only English EN version is visible

> Checkout is not available whilst your cart is empty—please take a look through our store and come back when you're ready to place an order.

The string translation is correctly done (see https://translate.wordpress.org/projects/wp-plugins/woo-gutenberg-products-block/stable/fr/default/?filters%5Bstatus%5D=untranslated&page=20)

## To reproduce

1. Set your profile to French so you WP runs in FR
2. Add products to your cart
3. Go to checkout
4. Empty products with the mini cart prune
5. See error

## Expected behavior

Display the right translated string

## Screenshots

![image](https://user-images.githubusercontent.com/919332/189416191-56055cd1-ad0a-477f-be83-a380c3aa6a0e.png)

## Environment
the bug was already declared previously, so it is not version specific see point 4 of https://github.com/woocommerce/woocommerce-blocks/issues/6662
* WP 6.0.2
* WC 6.8.2
* WC Blocks 8.4.0
* I do make use of new FSE blocks for my order and checkout pages

## Additional context

N/A

**Comment by nielslange** [comment]
Hello @Marc-pi,

Thanks for reaching out. I quickly checked this string on WordPress.org and found out that is hasn't been approved yet:
https://translate.wordpress.org/projects/wp-plugins/woo-gutenberg-products-block/stable/fr/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=9927658&filters%5Btranslation_id%5D=95929836

Once the string had been approved by a translation editor, the translation will appear on your site. As translations are handled by volunteers, it's hard to say when someone will approve the translation. 

While the translation hasn't been approved yet, you could install the [Loco translate](https://wordpress.org/plugins/loco-translate/) plugin on your site, to manually translate the string on your end.
