### ISSUE TITLE
Close icon centring 

### ISSUE THREAD

**Issue by vivialice** [woocommerce/woocommerce-gutenberg-products-block#7115]
This likely affects other blocks that have this option applied, but for me the 'x' icon is not centred within the button. 

<img width="43" alt="Screenshot 2022-09-12 at 12 23 41" src="https://user-images.githubusercontent.com/9888201/189687244-c8bb53a3-8ec2-4a6e-ab47-52176799123c.png">

I'm using theme TT2 and Firefox.

**Comment by Aljullu** [comment]
Heads-up that this might have been fixed in #7088.

**Comment by imanish003** [comment]
Hi @vivialice, I just verified on Chrome & Firefox. Looks like this is fixed now as mentioned by @Aljullu in the last comment.

**Comment by albarin** [comment]
I'm closing the issue since I double checked it looks fixed.
