### ISSUE TITLE
Links for all filter blocks (reset and clear all) 

### ISSUE THREAD

**Issue by vivialice** [woocommerce/woocommerce-gutenberg-products-block#7118]
Can we ensure all links are displayed as underlined for consistency between the blocks and other areas of the site.

<img width="317" alt="Screenshot 2022-09-09 at 14 05 44" src="https://user-images.githubusercontent.com/9888201/189690171-16cf6143-a560-40f3-885a-0520cb51497f.png">

<img width="655" alt="Screenshot 2022-09-09 at 14 07 04" src="https://user-images.githubusercontent.com/9888201/189690186-4b653b0a-010b-479f-82f7-36100efccd2c.png">

**Comment by thealexandrelara** [comment]
Hello @vivialice 👋 ,
I've started working on this issue, but I'd like to check some things with you before I can proceed to a solution. I understand that the idea is to have consistency between the links inside the blocks and site. During my initial investigation, I found 3 different behaviors/stylizations for links

---

## Font weight & font size
By default, the font weight and font size seem to be different between the Active Filters and Filters by Attribute block (by Size, by Price, etc) which leaves us with 2 possible scenarios

### 1. Active Filters block - Clear All link
The attributes for the Clear All link are the following:

> * Font weight: `bold`
> * Font size: `12px`

<img width="286" alt="CleanShot 2022-10-05 at 18 42 03@2x" src="https://user-images.githubusercontent.com/20469356/194169555-ac83dfb8-c2a1-4f3d-a321-efe05732b729.png">

### 2. Filter by Attribute block - Reset link
The attributes for the Reset link are the following:

> * Font weight: `normal`
> * Font size: `14px`

<img width="303" alt="CleanShot 2022-10-05 at 18 45 04@2x" src="https://user-images.githubusercontent.com/20469356/194169831-15ebbf0a-a1c9-404b-b04d-02dfcb693fe3.png">

---

## Hover style
For the hover attribute, there are 3 possible scenarios:

### 1. Active Filters block - Clear All link
There is no style change when we hover over the Clear All link.

> Default style:
> * Font weight: `bold`
> * Font size: `12px`
> * Color: `#6d6d6d`
> 
> Hover style:
> * Font weight: `bold`
> * Font size: `12px`
> * Color: `#6d6d6d`

![CleanShot 2022-10-05 at 18 56 04](https://user-images.githubusercontent.com/20469356/194171403-ee24d06e-3287-406a-a4b7-c7daa0ba6fc0.gif)

### 2. Filter by Attribute block - Reset link
As for the Filter by Attribute block, when we hover over the Reset button, the underline appears and the text color changes (from `#6d6d6d` to `#333333`)

> Default style:
> * Font weight: `normal`
> * Font size: `14px`
> * Color: `#6d6d6d`
> * Text decoration: `none`
> 
> Hover style:
> * Font weight: `normal`
> * Font size: `14px`
> * Color: `#333333`
> * Text decoration: `underline`

![CleanShot 2022-10-05 at 19 04 19](https://user-images.githubusercontent.com/20469356/194172483-0ad4e58e-0f8e-41e1-be5d-b59d1597073f.gif)

### 3. Other links in the site 
For other links on the site like the Product Title, the behavior is almost the opposite of the Filter by Attribute block. By default, it's underlined and when hovered the underline disappears. The text color does not change.

> Default style:
> * Font weight: `normal`
> * Font size: `14px`
> * Color: `#6d6d6d`
> * Text decoration: `underline`
> 
> Hover style:
> * Font weight: `normal`
> * Font size: `14px`
> * Color: `#6d6d6d`
> * Text decoration: `none`

![CleanShot 2022-10-05 at 19 12 38](https://user-images.githubusercontent.com/20469356/194173540-21c0f4b6-1040-4d51-acd0-fc6a14f48838.gif)

--- 

Do you know if there is any pattern already defined that we can follow and use for components with links?

cc: @albarin @tjcafferkey

**Comment by vivialice** [comment]
Hey @thealexandrelara 👋 Thanks for conducting this review. I'll answer your queries below: 

**1. `Clear all` vs `Reset` link** 
We should go with the 12px size option. To confirm: what size is the text in the `Apply` button? Because that looks like 12px to me, but I could be wrong. All of these (clear, reset, apply) should be the same size. 

**2. Other links in the site**
Thank you for considering other links on the site. You're correct, we should have a consistent experience across stores. Currently, the `reset` link is doing the opposite as intended.

 > Do you know if there is any pattern already defined that we can follow and use for components with links?

There isn't one specifically defined for WooCommerce but in this case we should continue to follow best-practices: 
- underline all links by default 
- hide underline on hover

**Comment by thealexandrelara** [comment]
1. Clear all vs Reset link
@vivialice I just checked and the text size for the Apply button is 14px
<img width="319" alt="image" src="https://user-images.githubusercontent.com/20469356/194571960-9a1b0b5c-29fd-42ed-8b54-58713f15eff3.png">

Another thing that I'd like to discuss with you is about the **Clear all** because it is using a font weight `bold`, is that intentional or it should be `normal' like the other links?
![image](https://user-images.githubusercontent.com/20469356/194574518-76f23b51-d448-4cdd-8565-ce33fe12db40.png)

Thank you for your guidance, so I'll set all links to be underlined and with 12px by default, when the user hovers over the link I'll hide the underline while maintaining the same color.

**Comment by vivialice** [comment]
It shouldn't be bold 👍
