### ISSUE TITLE
None in stock options displaying oddly 

### ISSUE THREAD

**Issue by vivialice** [woocommerce/woocommerce-gutenberg-products-block#7121]
When no products are available to show, the product count displays strangely. Also, when there are no options, the filter behaviour is to hide the non-relevant options, so I am confused why these show up in the first place. 

<img width="441" alt="Screenshot 2022-09-12 at 15 50 30" src="https://user-images.githubusercontent.com/9888201/189704419-469992b0-4803-4793-b062-d918df40f48f.png">

**Comment by Aljullu** [comment]
Thanks for opening this issue! The styling was fixed in #7073.
