### ISSUE TITLE
Text sizing for Filter Blocks 

### ISSUE THREAD

**Issue by vivialice** [woocommerce/woocommerce-gutenberg-products-block#7126]
Let's clean up the text sizing across all the blocks as they aren't looking consistent or following heirarchy. 

Some notes with screenshots:
<img width="1525" alt="Screenshot 2022-09-12 at 16 44 31" src="https://user-images.githubusercontent.com/9888201/189697848-d926aae0-17b5-4589-b1c0-7a53f4eb61e6.png">

Summary: 
- Currently we have what looks like 5 or 6 text sizes, at most we should have maybe two. Not including the header/label text size. 
- To me, the ideal target size is the size used in the filter by price input. Can we update: all list, chips, dropdown, reset/clear links, button text to this

Reference: 
This mockup with the empty state is the visual balance we want. Majority of the type slightly smaller in proportion to other text on the site (body, header text).

**Comment by Aljullu** [comment]
When fixing this, let's make sure we use the [`font-size()` mixin](https://github.com/woocommerce/woocommerce-blocks/blob/d4e3247ec07bda51c51d8c1e0ca4216e7ff4d4a0/assets/css/abstracts/_mixins.scss#L1-L13).
