### ISSUE TITLE
New Block: Filter Products by Attribute

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-gutenberg-products-block#713]
**User Story**
As a merchant
I want a block that allows filtering my products by specific attributes
So I can allow users to narrow down products based on that criteria

**Acceptance Criteria**
- [x] The list should be truncated if it contains more than 10 attributes (https://baymard.com/blog/truncation-design)
- [x] The merchant can choose the query type AND/OR. 
- [x] If the merchant hasn’t setup attributes yet for their store it should see a message explaining that he first needs to add new attributes. That message should redirect the user to the Attributes page
- [x] If the merchant already has some attributes, he should see a search input to search for attributes
- [x] If the merchant wants to filter by multiple attribute types it requires creating additional blocks and choosing the next attribute
- [x] The merchant can show/hide the product count (content setting)
- [x] The merchant can edit and change the filter options in a new setting in the sidebar (filter products by attribute setting)
- [x] he merchant can also edit and change the filter options by clicking in the pencil icon in the block toolbar
- [x] Content, Block and Filter Products by Attribute settings are expanded by default
- ~~The list of the existing attributes will show the number of products associated to each attribute~~ Products are not mapped to attributes, they are mapped to terms. This cannot be done due to technical limitations.
- ~~The merchant can only see this block in the block library while editing the Product Archive Page~~ These filters will work with all-products block.
- ~~The block needs to be displayed in the Product Archive Page by default, to help with initial discovery~~ These filters will work with all-products block.

**Additional context**
P2: `p6riRB-4CG-p2`
[Prototype](https://www.figma.com/file/jvWme5r7Yvyi8F2jEABS6B/Active-Product-Filters?node-id=0%3A1)
[Mobile prototype](https://www.figma.com/file/WVqrrfEtgRGQ8jSVeFDvwn8t/Collapse%2FExpand-Exploration?node-id=0%3A1) with collapse/expand filter

**Comment by mikejolley** [comment]
Due to https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/850 I am editing the acceptance criteria above.

**Comment by mikejolley** [comment]
Moved dropdown feature to https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/1135
