### ISSUE TITLE
Slider of Price filter block should use currentColor instead of a hard-coded color

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#7130]
## Describe the bug

When the Price filter block is added on a dark background, the slider can't be seen.

## To reproduce

1. Add the Filter by Price and All Products blocks inside a Columns block into a post or page.
2. Change the background color of the Filter by Price column to a dark color. Change the text color to a light color.
3. Notice the price slider is no longer visible.

## Expected behavior

That's because we have some hard-coded styles in the slider. Ideally, we should default to [`currentColor`](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#currentcolor_keyword).

## Screenshots

<img src="https://user-images.githubusercontent.com/3616980/189833976-84cdbdef-1f11-47b6-8389-6df2da381a1e.png" alt="" width="351" />

**Comment by EmptySet-Exe** [comment]
Could I contribute to this issue?

**Comment by Aljullu** [comment]
Sure, go for it, @EmptySet-Exe! You will probably need to look into this CSS file: [`woocommerce-blocks/assets/js/base/components/price-slider/style.scss`](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/base/components/price-slider/style.scss).

You can read how to build the project and contribute to it in the [_Getting Started_ guide](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/contributors/contributing/getting-started.md). Let us know if you have any questions and thanks for your effort!

**Comment by EmptySet-Exe** [comment]
Thank you! Will I have to reach out for any questions here or...?

**Comment by Aljullu** [comment]
Yes, you can posts your questions here and we will do our best to answer all your questions. :slightly_smiling_face:

**Comment by EmptySet-Exe** [comment]
Hey I was wondering if you can help me with a hosting issue that I have?

**Comment by gigitux** [comment]
Hey @EmptySet-Exe, feel free to drop any question that you have here :)

**Comment by EmptySet-Exe** [comment]
Hi, I'm having trouble viewing my changes in the style.scss show up in my WordPress instance.

**Comment by gigitux** [comment]
My suggestion is to set up a local website to work on this issue. You could use [LocalWP](https://localwp.com/).

**Comment by EmptySet-Exe** [comment]
Hey I've noticed that the WooCommerce Blocks don't appear in the WP Editor unless if I have the WooCommerce Plugin installed. That's to say that the WooCommerce Blocks don't show up in the Block Inserter if I only have the WooCommerce Block Plugin installed alone. Is that how it's supposed to be, because I can't ensure that my changes are directly appearing on the webpage otherwise.

**Comment by gigitux** [comment]
> Hey I've noticed that the WooCommerce Blocks don't appear in the WP Editor unless if I have the WooCommerce Plugin installed. That's to say that the WooCommerce Blocks don't show up in the Block Inserter if I only have the WooCommerce Block Plugin installed alone. Is that how it's supposed to be, because I can't ensure that my changes are directly appearing on the webpage otherwise.

Follow[ these steps](https://github.com/woocommerce/woocommerce-blocks#installing-the-plugin-version) for configuring your local env.

**Comment by EmptySet-Exe** [comment]
![image](https://user-images.githubusercontent.com/46509186/193543941-fb39e5c5-5a75-4452-95fa-45ebfa1b19cb.png)
This happens after I type `npm start` in the cmd

**Comment by EmptySet-Exe** [comment]
Excuse me, I wanted to know if there are any guidelines for crafting a pull request?

**Comment by gigitux** [comment]
> Excuse me, I wanted to know if there are any guidelines for crafting a pull request?

In [this folder](https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs/contributors), there are all the guidelines for the contributors. When you open the PR, you will see a template, just fill the sections and open the PR :)

**Comment by EmptySet-Exe** [comment]
Which branch should I make the PR from for this?

**Comment by gigitux** [comment]
Hi! It seems that you created the PR https://github.com/woocommerce/woocommerce-blocks/pull/7278. Thanks for working on this! I will take a look in the next few days!

**Comment by EmptySet-Exe** [comment]
Hey, just curious, can you give me an idea as to why my contribution had failed some of those tests?

**Comment by gigitux** [comment]
Hi @EmptySet-Exe! We have some problems with our current E2E tests, so don't worry about that. 
Instead, could you fix the CSS linting issue? (https://github.com/woocommerce/woocommerce-blocks/pull/7278#issuecomment-1267115947)

**Comment by EmptySet-Exe** [comment]
Okay, I'll take a look at it. Thanks!

**Comment by EmptySet-Exe** [comment]
Thank you for allowing me to contribute!
