### ISSUE TITLE
[WooCommerce default styles for block themes] The "Add to cart", "Pay for order", and "Place order" buttons do not follow the primary CTA color

### ISSUE THREAD

**Issue by rodelgc** [woocommerce/woocommerce-gutenberg-products-block#7134]
## Describe the bug

As part of [Add WooCommerce default styles for block themes #33518](https://github.com/woocommerce/woocommerce/pull/33518), and as mentioned in pdnLyh-1uW-p2 (in the "Product variations enhancements" and "Cart & Checkout" sections), the CTA's should have a consistent primary color.

I encountered this issue when testing WooCommerce 6.9 RC1. Internal discussion here: pb22l9-1u6-p2#comment-1544, in the _"Some CTA’s do not follow the default style for block themes"_ section.

## To reproduce

1. Install WooCommerce 6.9 (currently in RC1)
2. Complete the setup wizard.
    - Use the sample products CSV when importing products.
    - Select COD as payment method
4. Install a block theme other than TT2. I used Blockbase, Archeo, Clove, Tove, and Wabi.
5. Go to the `/shop` page and remember how the "Add to cart" button looks like. That's the correct primary color for the "Add to cart" button.
6. Click on one of the simple products.
7. Notice that the color of the "Add to cart" button is different from the one in the `/shop` page.
8. Add the product to the cart and proceed to the checkout page.
9. In the checkout page, notice that the color of the "Place order" button is wrong. Its styling should be the same as the "Add to cart" button in the `/shop` page.
10. Login to WP Admin Dashboard.
11. Create an order with status "Pending payment" and that has any of the simple products from the store.
12. Click on the "Customer payment" link.
13. Notice that the styling of the "Pay for order" link is also wrong. It should be the same as the "Add to cart" button in the `/shop` page.

## Expected behavior

The "Add to cart", "Pay for order", and "Place order" buttons should follow the primary CTA color as mentioned in pdnLyh-1uW-p2 (in the "Product variations enhancements" and "Cart & Checkout" sections).

## Screenshots

**This is how the CTA's should be styled, just like the "Add to cart" button in the `/shop` page**
<img width="254" alt="Screen Shot 2022-09-13 at 4 25 55 PM" src="https://user-images.githubusercontent.com/4509348/189851173-d96d006d-6464-4a1b-9581-ca5c5c14e8be.png">

**Notice how the "Add to cart" in the product pages are inconsistent with the one from the `/shop` page**
<img width="366" alt="Screen Shot 2022-09-13 at 4 25 38 PM" src="https://user-images.githubusercontent.com/4509348/189851467-ccb4120e-85ad-4929-9f4d-a594fbae25a5.png">

**The "Pay for order" and "Place order" buttons also do not follow the primary color for CTA's**

![image](https://user-images.githubusercontent.com/4509348/189851647-9b0a9e2a-5ba7-49cd-b4c5-7f1215f8896d.png)

![image](https://user-images.githubusercontent.com/4509348/189851813-8c41e380-faed-420e-b5bd-6d59810a5e3c.png)

### WordPress (please complete the following information):

-   Core version: 6.0.2
-   WooCommerce version: 6.9 RC1

**Comment by ralucaStan** [comment]
This will be fixed as we bring Global Styles support to the Cart and Checkout blocks

**Comment by tarunvijwani** [comment]
Fixed in https://github.com/woocommerce/woocommerce-blocks/pull/8844
