### ISSUE TITLE
[WooCommerce default styles for block themes] Dropdown styling is so different from other input fields in some themes

### ISSUE THREAD

**Issue by rodelgc** [woocommerce/woocommerce-gutenberg-products-block#7135]
## Describe the bug

Logging this issue as part of [Add WooCommerce default styles for block themes #33518](https://github.com/woocommerce/woocommerce/pull/33518), and as mentioned in pdnLyh-1uW-p2 (the part where it says _"Ensure dropdowns are visually consistent with other form fields."_).

In some themes, the dropdown styling looks different from the rest of the input fields. For example, in Clove and Tove.

## To reproduce

1. Install WooCommerce 6.9.
1. Install a block theme other than TT2. I used Clove and Tove.
2. Complete the WooCommerce setup wizard. Make sure to add at least 1 simple product.
3. As a shopper, add a product to the cart.
4. Proceed to the checkout page.
5. In the Billing Address, notice how the "Country / Region" dropdown looks different from the rest of the input fields.

## Expected behavior

The dropdowns should look consistent with the other input fields.

## Screenshots

**Clove**
<img src="https://user-images.githubusercontent.com/4509348/189855593-1ac1f43b-4597-4af2-9966-1443e3d6ba4f.png" width="400">

**Tove**
<img src="https://user-images.githubusercontent.com/4509348/189855654-3f9d480e-0644-44c2-b932-40e9a30dd55e.png" width="400">

### WordPress (please complete the following information):

-   Core version: 6.0.2
-   WooCommerce version: 6.9 RC1

**Comment by nielslange** [comment]
Hello @rodelgc 👋

I briefly looked into this issue, and it appears that the issue affects the checkout shortcode, and not the Checkout blocks. Can you confirm that?

## Clove theme

<table>
<tr>
<td>Checkout shortcode:
<br><br>
<img width="1280" alt="Screenshot 2023-10-25 at 20 05 45" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/2bed85fe-5feb-4fc6-b563-df3c0da15fe1">
</td>
<td>Checkout block:
<br><br>
<img width="1280" alt="Screenshot 2023-10-25 at 20 05 03" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/0ad6b57b-c9ac-4876-a761-74204973ebe4">
</td>
</tr>
</table>

## Tove blocks

<table>
<tr>
<td>Checkout shortcode:
<br><br>
<img width="1279" alt="Screenshot 2023-10-25 at 20 06 30" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/99d45347-2a9c-4e4a-b186-7c0058bc4383">
</td>
<td>Checkout block:
<br><br>
<img width="1280" alt="Screenshot 2023-10-25 at 20 06 45" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/cf9d7b5e-c01e-4aa6-a8be-cc3117843800">
</td>
</tr>
</table>

**Comment by mikejolley** [comment]
I concur. This issue affects the custom dropdown used for classic checkout. 

Since this is a styling issue and seemingly non-critical bug, I don't think we need to work on this. I will mark this closed, but cc'ing @ralucaStan to double check. It's my understanding we're only working on block based checkout going forward, with the exception of critical bugs in the shortcode flow.

**Comment by ralucaStan** [comment]
Thank you both for confirming this. It's low priority and we won't be working on it. Good call to close the issue.
