### ISSUE TITLE
Expand Local Pickup settings.

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#7138]
Local pickup should support 3 new fields in it.

### Location title
This is the name of the pickup location, this field is still debatable as it works the same as Title.

### Location address
This is the pickup location address, it would be nice to have autocomplete for address but this is not a priority and if we don't have prior art in WooCommerce then let's skip it.

### Pick up details
This is a free text optional field for the rate description.

Implementation should be done directly in WooCommerce Core.

![image](https://user-images.githubusercontent.com/6165348/189933001-3f521548-4b33-4378-8f1d-ad28cec837e5.png)

![image](https://user-images.githubusercontent.com/6165348/189933050-563d74c4-449d-4340-8ffa-35cea7288936.png)

**Comment by mikejolley** [comment]
@senadir There is no prior art for autocomplete and most solutions would require API keys. Suggest we skip.

Why do we need a separate field for the location name? Seems like this is what we'd use `Title` for. I can add it for now and add it in brackets if possible. But it will only be visible in blocks.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/compare/add/local-pickup-location-settings?expand=1

**Comment by mikejolley** [comment]
Done in https://github.com/woocommerce/woocommerce-blocks/pull/7433
