### ISSUE TITLE
Introduce Shipping method block

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#7140]
In Checkout Block, we need to introduce a new block "Shipping Method" that's visible only if you have local pickups added in your website.

The block should be customizable in a sense that you can show or hide the icon or price of shipping

<img width="638" alt="image" src="https://user-images.githubusercontent.com/6165348/189941385-b2973e37-f05c-48ef-b0a5-439589a436a4.png">

![image](https://user-images.githubusercontent.com/6165348/190431274-c5beee4c-ffb8-4860-89fe-1cb77411665c.png)

In frontend, the block should integrate in the Checkout data flow and would decide what block to show, pickup locations or shipping rates.
It also should only be visible if we have local pickup available.

**Comment by mikejolley** [comment]
Done in https://github.com/woocommerce/woocommerce-blocks/pull/7433
