### ISSUE TITLE
Improve the documentation for `src/StoreApi/docs/checkout.md`

### ISSUE THREAD

**Issue by opr** [woocommerce/woocommerce-gutenberg-products-block#7157]
In #7016 it was mentioned that the documentation was lacking for how the POST request to the checkout endpoint should look.

We should add an example request payload.

We should also link to, or provide some information on the `payment_method` and `payment_data` keys.

**Comment by revnelson** [comment]
This would be great. Currently I cannot for the life of me figure out what `payment_data` I need to pass for a stripe payment where I have already processed the payment on the frontend so that the order is created and marked as paid within WooCommerce.
