### ISSUE TITLE
Introduce new Pickup locations block.

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#7161]
As of right now, Shipping options block would only render shipping rates, we want to introduce a new pickup locations block that renders pickup locations, the benefit here is that it would have its own inner block area to render pickup location specific data.
The main different is that you can click to expand a rate.

In the editor, Local pickup will be a sibling of shipping options, both will be rendered inside a block that has view switching capabilities, this is to be tackled in another PR.

![image](https://user-images.githubusercontent.com/6165348/190425953-4c59354d-80bc-4ddb-ad80-f09a0ece77b6.png)

**Comment by mikejolley** [comment]
@senadir it's probably best to keep this on hold until the toggle block is made (https://github.com/woocommerce/woocommerce-blocks/issues/7161).

It looks to me as though that toggle may impact other blocks (shipping address for example), so showing and hiding child blocks may not require them to be siblings within a shallow block. We could put them on the same level. Unless there was another reason for the shallow block I'm not seeing?
