### ISSUE TITLE
Ratings: Star icons are not displaying in the site editor

### ISSUE THREAD

**Issue by danieldudzic** [woocommerce/woocommerce-gutenberg-products-block#7167]
## Describe the bug

Rating stars are displaying correctly in posts and pages, but fail to load correctly in the site editor.

## To reproduce

1. Ensure your products have a few ratings
2. Add the **All Products** block to a page
3. Add the **All Products** block via Appearance > Editor to a template

## Expected behavior

I'd expect the stars to display correctly both in the site editor and in posts and pages.

## Screenshots
**Correct:**
![New_shop_–_ratings](https://user-images.githubusercontent.com/905781/190656175-1796cecb-437d-4e56-9440-88af65e26d54.jpg)

**Broken:**
![Editor__beta__‹_ratings_—_WordPress](https://user-images.githubusercontent.com/905781/190656750-c8068806-dbac-4a03-b0d5-b16c4ff71710.jpg)

**Comment by nerrad** [comment]
I don't know if this was noticed or documented either, but there appears to be an issue with the checkbox icon as well in the Add to Cart button element:

<img width="170" alt="CleanShot 2022-10-07 at 17 53 46@2x" src="https://user-images.githubusercontent.com/1429108/194668086-4bd18f8a-d03b-4288-9359-90c3f19f2356.png">

**Comment by danieldudzic** [comment]
I have now created an issue for this in the WooCommerce core repo: https://github.com/woocommerce/woocommerce/issues/35495

**Comment by danieldudzic** [comment]
This has been now fixed in WooCommerce Core via: https://github.com/woocommerce/woocommerce/pull/35532
