### ISSUE TITLE
Linked products

### ISSUE THREAD

**Issue by janaslav** [woocommerce/woocommerce-gutenberg-products-block#7183]
## What do you like about the Cart & Checkout blocks?
I like the clean layout of the cart.

## What do you think is missing from the Cart & Checkout blocks?
In the old cart, there were related product offered to clients, which are missing now. Is it possible to add them?

**Comment by senadir** [comment]
Hey, I think you mean Cross Sells? Cross sells will land next week in WooCommerce Blocks plugin :D

**Comment by ralucaStan** [comment]
@janaslav this functionality has been added with version 8.6.0. You'll need to manually insert the Cross-Sells block on the Cart page.

**Comment by janaslav** [comment]
Hello,

I've seen it, thank you!

It would be nice to have the option to modify its looks. :-)

Best regards,

Jana Lišková

**Comment by ralucaStan** [comment]
Hey Jana, thank you for your input. What options do you have in mind? Could you please share what you are trying to achieve?

**Comment by janaslav** [comment]
To be able to choose how they are presented. When some of the products have
a longer name, it doesn't look so pretty when they are next to each other.
Also, I'd like to add the block with these products under both sections,
not under one of them. I think it would look better (when using a PC).

Is it clear? Do you understand?

Thank you.

**Comment by ralucaStan** [comment]
Yes, two suggestions that you have are:
- better handling of the case when products have longer names
- ability to make the Cross Sell wider

**Comment by janaslav** [comment]
Yes, exactly.
