### ISSUE TITLE
WooCommerce Blocks 2.2.1 breaking my site

### ISSUE THREAD

**Issue by Swirlyking** [woocommerce/woocommerce-gutenberg-products-block#719]
**Describe the bug**
I'm using the theme "Alluring eCommerce" and everything is 100% updated at this moment except I'm using WooCommerce Blocks 2.1. When I update to 2.2.1 then my site seems to break. See attached

**To Reproduce**

**Expected behavior**

**Screenshots**
WooCommerce Blocks 2.1
<img width="826" alt="Screen Shot 2019-07-10 at 1 12 40 PM" src="https://user-images.githubusercontent.com/52760844/61001528-a71ed580-a314-11e9-8f6b-0ca652724ace.png">
WooCommerce Blocks 2.2.1
<img width="854" alt="Screen Shot 2019-07-10 at 1 13 17 PM" src="https://user-images.githubusercontent.com/52760844/61001526-a71ed580-a314-11e9-888d-4137800d70c1.png">

**WordPress (please complete the following information):**

* Core version: 5.2.2
* Gutenberg version: 6.1.0
* WooCommerce version: 3.6.5
* WooCommerce Blocks version: 2.1
* Site language: English
* Any other plugins installed:
Akismet: 4.1.2
Duplicator 1.3.16
Google Analytics for WordPress by MonsterInsights: 7.7.1
Kirki Customizer Framework: 3.0.44
WP Rollback: 1.6
WPForms Lite: 1.5.3.1
YITH WooCommerce Zoom Magnifier: 1.3.10

**Comment by mikejolley** [comment]
@Swirlyking I downloaded that theme from .org and tested it:

![Screenshot 2019-07-11 at 11 50 34](https://user-images.githubusercontent.com/90977/61045151-2cb48b00-a3d2-11e9-930f-258e205219cf.png)

The theme looks pretty different though so perhaps some customisation work?

2.2 changed the markup for product blocks to **not** use WooCommerce core templates. It outputs it's own markup. So any custom styles would need to be updated to reflect this.

**Comment by Swirlyking** [comment]
Ahhh. Okay, I turned off WooCommerce blocks and it's fine now.
