### ISSUE TITLE
Filter patterns preview showing Filter by Attribute in Edit view.

### ISSUE THREAD

**Issue by tjcafferkey** [woocommerce/woocommerce-gutenberg-products-block#7190]
## Describe the bug

When you search the Block Inserter > Patterns library for WooCommerce patterns, when you come to the WooCommerce Product Filters pattern you are able to see in the preview that the Filter by Attribute block is rendered in Edit mode. Because of this the preview does not look appealing.

## To reproduce

1. Go to Appearance > Editor > All Templates > Product Catalogue
2. Open the Block Inserter, then select Patterns tab
3. On the dropdown click WooCommerce to view WC available patterns.
4. See the pattern rendering the Filter by Attribute block in Edit mode.

## Expected behavior

The Filter by Attribute block should render an example preview.

## Screenshots

<img width="350" alt="Screenshot 2022-09-21 at 12 35 40" src="https://user-images.githubusercontent.com/8639742/191494013-6fceac9c-c1bb-4f0c-bb2d-cbd0cdf368db.png">

**Comment by tjcafferkey** [comment]
I am wondering if we are able to detect within the block itself if it is being rendered in a "Preview" pane and if so, render it with some dummy data in this context.

**Comment by Aljullu** [comment]
> I am wondering if we are able to detect within the block itself if it is being rendered in a "Preview" pane and if so, render it with some dummy data in this context.

`block.json` has an [`example` attribute](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-registration/#example-optional) which might be helpful. We are using it in some blocks, ie: [All Products](https://github.com/woocommerce/woocommerce-blocks/blob/f11f11c9ad91c611340c1ad64b7266aca391a72b/assets/js/blocks/products/all-products/block.json#L15-L19).

**Comment by tjcafferkey** [comment]
@Aljullu This looks useful thank you! Only problem is that we would need to know the `attribute_id` we are using as an example actually exists somehow.
