### ISSUE TITLE
Filter by Attribute border styles are not applied to the block

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#7192]
It looks like with the recent style updates, the border styles for the Filter by Attribute block no longer work. This affects both display modes: _List_ and _Dropdown_.

## To reproduce

1. Add the Filter by Attribute block to a post or page.
2. In the sidebar, change the border styling.
3. Notice nothing changes in the block.

![imatge](https://user-images.githubusercontent.com/3616980/191551087-3753cb48-dafc-4d99-b4b1-251b2a42f4c1.png)

## Expected behavior

Any of these two:
* ~the block should update and show border styling accordingly~
* or the option to set it shouldn't be available in the UI

## Additional context

@gigitux @albarin do you have any opinions on this?

I'm leaning towards completely removing the border styling from that block. Some reasons for that:

* in the past, it was only possible to change the border of the dropdown input, but it didn't work when display style was set to _List_, so that was confusing
* the border styling options were only available in the feature plugin, but we never graduated them to WC core because they rely on experimental APIs
* the Elements API might be a better fit for this use case (changing the border of the input field/checkboxes) than block global styles

**Comment by gigitux** [comment]
It makes sense to me. Should we add the label good first issue? I don't think that it is hard to remove, and it could be a good issue to show what is the Global Styles and how it works

**Comment by Aljullu** [comment]
> It makes sense to me. Should we add the label good first issue? I don't think that it is hard to remove, and it could be a good issue to show what is the Global Styles and how it works

Good idea. Done!

**Comment by roykho** [comment]
Hi @Aljullu - So I am just taking a look at this and I am only seeing the `Border` settings in the `Styles` section of the `Inspector controls` but in your screenshot, it seems to be in the `Settings` section of the `Inspector controls`.

I am not sure if some in GB changed to cause the `Border` controls to move to the `Settings` section since this issue was reported. But it still has the same purpose so I am assuming we want to "also" remove it from there?

**Comment by Aljullu** [comment]
In previous versions of Gutenberg, the tabs _Settings_ and _Styles_ didn't exist. Instead, everything was displayed together. I guess my screenshot is from that time.

> But it still has the same purpose so I am assuming we want to "also" remove it from there?

Yes, I would say so. Thanks for looking into this!
