### ISSUE TITLE
Mini cart shop button appearing differently in the editor vs the front end 

### ISSUE THREAD

**Issue by vivialice** [woocommerce/woocommerce-gutenberg-products-block#7197]
In the editor, the button appears in black and in orange (dictated by the theme) in the front end. I guess eventully we should add color controls for this block, but it should reflect their live store. 

In editor: 
<img width="707" alt="Screenshot 2022-09-21 at 18 40 46" src="https://user-images.githubusercontent.com/9888201/191574314-b875e36f-fe89-4e43-b978-ec2d420b4625.png">

In browser: 
<img width="564" alt="Screenshot 2022-09-21 at 18 40 58" src="https://user-images.githubusercontent.com/9888201/191574327-610c5c51-f0fd-40f9-aa36-56159baa1c29.png">

**Comment by albarin** [comment]
While working on this issue, I've also realised that other buttons also look a bit different in the editor and in the front-end (text color and height), even if they follow the theme styling.

| Editor | Front-end |
| ------ | ----- |
| <img width="486" alt="Screenshot 2023-02-28 at 10 41 52" src="https://user-images.githubusercontent.com/186112/221814583-b6cf968b-5b5b-4d70-821b-7667f83aa5f9.png"> | <img width="485" alt="Screenshot 2023-02-28 at 10 41 46" src="https://user-images.githubusercontent.com/186112/221814479-f42ec118-b41e-4372-9ec8-c52a1d927716.png"> |

**Comment by albarin** [comment]
While working on this issue, I've also realised that other buttons also look a bit different in the editor and in the front-end (text color and height), even if they follow the theme styling.

| Editor | Front-end |
| ------ | ----- |
| <img width="486" alt="Screenshot 2023-02-28 at 10 41 52" src="https://user-images.githubusercontent.com/186112/221814583-b6cf968b-5b5b-4d70-821b-7667f83aa5f9.png"> | <img width="485" alt="Screenshot 2023-02-28 at 10 41 46" src="https://user-images.githubusercontent.com/186112/221814479-f42ec118-b41e-4372-9ec8-c52a1d927716.png"> |

Should I also unify how they look? Should I go for the editor style or for the front-end one? @vivialice

**Comment by vivialice** [comment]
Thanks for tagging me @albarin ! We should definitely make sure the design is in the editor is reflected on the front-end 😄 The editor style looks correct to me, so I'd go with that one. 👍

**Comment by albarin** [comment]
I'm opening a different issue to fix that problem with buttons, because I think we have a bigger issue, it's not only mini-cart buttons. Here's the bug: https://github.com/woocommerce/woocommerce-blocks/issues/8587
