### ISSUE TITLE
Filter buttons rendering differently

### ISSUE THREAD

**Issue by vivialice** [woocommerce/woocommerce-gutenberg-products-block#7203]
I think I posted about this before, but I have another example on a dark background where the buttons look very different in the editor vs the front end: 

Editor: 
<img width="326" alt="Screenshot 2022-09-22 at 12 12 55" src="https://user-images.githubusercontent.com/9888201/191732501-7b6e1221-bf44-4245-86b9-02e84d6c2445.png">

Front-end: 
<img width="377" alt="Screenshot 2022-09-22 at 12 12 26" src="https://user-images.githubusercontent.com/9888201/191732523-5d4cb9ce-392a-4a91-8fd1-7bb844597bd3.png">

**Comment by danielwrobert** [comment]
This seems to be a duplicate issue from woocommerce/woocommerce#42591.

Closing this out but I will x-post to here on that Issue for another example to reference.
