### ISSUE TITLE
Test how Cart and Checkout blocks react when the user lands on a page where both Google Pay and Apple (since iOS 16)

### ISSUE THREAD

**Issue by ralucaStan** [woocommerce/woocommerce-gutenberg-products-block#7210]
Since iOS 16 was released on Sep 12, Apple Pay is now possible in mobile browsers other than Safari. This is relevant to our Express Payment methods, as now users that have both Apple Pay and Google Pay can see both buttons in the Chrome browser. 

We need to test and see how the Cart and Checkout blocks react when the user lands on a page where both Google Pay and Apple Pay qualify to be shown?

**Comment by ralucaStan** [comment]
context paJDYF-5zt-p2

**Comment by tarunvijwani** [comment]
It seems the express checkout option is not available on the mobile browser for the Cart and Checkout block. 

Screen recording:


https://user-images.githubusercontent.com/11503784/193275462-49b0c524-eff2-4ec0-8cd6-ee5baef5cedc.mov

Desktop site:

![image](https://user-images.githubusercontent.com/11503784/193275479-8e10cd34-6a76-4808-9a54-ddf4587d37dd.png)

**Comment by ralucaStan** [comment]
Hi Tarun, thank you for looking into this. D
Did you also try other themes outside of Storefront?

**Comment by ralucaStan** [comment]
For me it appeared in Safari with Twenty Twenty-Two.
I did not see it in Chrome, even if I have a payment method set up

![IMG_1A6699C40F6F-1](https://user-images.githubusercontent.com/1628454/194034840-f1db28eb-3a79-4d37-be0d-f79538367425.jpeg)

**Comment by tarunvijwani** [comment]
@ralucaStan It is not visible to me in Safari.

I tried Storefront and Twenty-Twenty-Two themes as well:


https://user-images.githubusercontent.com/11503784/195541481-e5ace879-8580-419d-b2c3-f0f4def299b0.mov



![image](https://user-images.githubusercontent.com/11503784/195541509-9620000c-d2c9-4cd0-81f0-e7a902bf4047.png)

**Comment by ralucaStan** [comment]
- Google pay appears on Android devices
- Since iOS 16 Apple pay appears on other browsers then Safari

As I can't have Google pay show up on Iphone > Safari I am going to close this and wait for issues regarding the display of both methods at the same time
