### ISSUE TITLE
Cart/Checkout resource hinting is added to admin pages

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#7215]
In 7.3.0 we added resource hinting to Cart/Checkout assets, we excluded that one from Cart/Checkout pages but we didn't exclude it from the admin page, this means if you're in admin and have a valid cart, you will get resource hinting.

This is not a bug per see, but I don't think you need such optimization inside admin pages.

**Comment by ralucaStan** [comment]
Follow up of https://github.com/woocommerce/woocommerce-blocks/pull/7211
