### ISSUE TITLE
Cart/Checkout resource hinting should be limited to only if you're running those blocks.

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#7216]
In 7.3.0, we added resource hinting to Cart/Checkout assets, however, the condition to add this hinting is if you have a valid cart, but it's kind of useless (and counter productive) if you're not running Cart block or Checkout block, so we should skip it if someone isn't running those blocks as default.

**Comment by ralucaStan** [comment]
This could be fixed together with #7215

**Comment by ralucaStan** [comment]
Follow up of https://github.com/woocommerce/woocommerce-blocks/pull/7211
