### ISSUE TITLE
When an forced inner block reappears after deleting it, it is confusing why it is happening

### ISSUE THREAD

**Issue by opr** [woocommerce/woocommerce-gutenberg-products-block#7227]
In #7170 @CSPoirier mentions that when deleting the order summary section in the Checkout block, it is confusing as to why it reappears.

We could look into either:
- Disabling the ability to remove altogether (would probably need some Gutenberg buy-in, which I'm not confident we'll get),
- Add a notice when it _does_ reappear, explaining why, or
- Add a permanent notice in the inspector controls explaining that it cannot be removed (the same for all locked blocks).

This applies to all forced inner blocks in all of our blocks, not just the Checkout block.

**Comment by senadir** [comment]
This is weird, the whole point of forcing blocks is so you can't delete them, the reappears thing is something we added while we reach parity with Gutenberg, but as of now, forcing is a native Gutenberg feature.

**Comment by opr** [comment]
Totally, but this issue is specifically about the UX of it reappearing without any explanation. Some users find this confusing, so it's something we should track so we can remove our "reappearing" functionality when the Gutenberg feature makes it into core (if it's not already), or find some way to improve the UX around this.

**Comment by senadir** [comment]
I think we should fix why you can remove a block to begin with, "reappearing" is just there to protect against edge cases (like removing it from html code).
