### ISSUE TITLE
Add a classname field to woocommerce_get_item_data filter

### ISSUE THREAD

**Issue by alexflorisca** [woocommerce/woocommerce-gutenberg-products-block#7235]
## Is your feature request related to a problem? Please describe.
Based on the discussion in #6512 and #6914, especially [this comment](https://github.com/woocommerce/woocommerce-blocks/pull/6914#issuecomment-1259273551) in particular, we want to enable the use of a custom class name within the product-details [here](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/base/components/cart-checkout/product-details/index.tsx#L35). At the moment, this is derived from the `key` or `name` properties, which can be translated, and so the name of the class would change when the language changes.

## Describe the solution you'd like
To avoid this, we would like users of the `woocommerce_get_item_data` filter to specify an explicit classname that they want to be applied for each product variant detail. This classname should be applied instead of deriving the class name from the `key` or `name` props.

## Describe alternatives you've considered
Removing the class, but this breaks other people's code who rely on it

## Additional context

This screenshot shows where the product details are displayed in the UI on the cart page, and the corresponding DOM
<img width="1326" alt="Screenshot 2022-09-27 at 10 48 05" src="https://user-images.githubusercontent.com/3966773/192509187-afda272a-f061-46cb-a9d3-fd46a041eed3.png">

**Comment by alexflorisca** [comment]
Whoever works on this, please ping @jimjasson when this is implemented and merged to trunk as it will affect some of Somewhere Warm's plugins.

**Comment by helgatheviking** [comment]
@alexflorisca If you will add the #hacktoberfest tag to this repo, I might take a crack at this...

**Comment by alexflorisca** [comment]
That's a great idea @helgatheviking, I've added the label to this issue and topic to the repo. Will be great to see what you come up with!

**Comment by helgatheviking** [comment]
Thanks! https://github.com/woocommerce/woocommerce-blocks/pull/7328 is a start.

**Comment by jimjasson** [comment]
Hey -- checking in on this one. Do you have any update on when it will be patched? Thanks!

**Comment by ralucaStan** [comment]
We will soon look into @helgatheviking's PR and let you know. It was not assigned to somebody and it was omitted.

**Comment by helgatheviking** [comment]
Thanks @ralucaStan I need it for my #Hacktoberfest creds :)

**Comment by alexflorisca** [comment]
Yeah this is on my radar but I've not got round to it yet. I'll review your PR this week @helgatheviking
