### ISSUE TITLE
Return local pickups as a top level API item

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#7236]
Superseding https://github.com/woocommerce/woocommerce-blocks/pull/7177, we want to offer local pickups as a top level item in Cart instead of part of `shipping_rates`, this ensures they continue to work even if shipping is disabled.

**Comment by mikejolley** [comment]
We're not doing this now afaik. We'll filter rates on the client side. Part of https://github.com/woocommerce/woocommerce-blocks/issues/7161
