### ISSUE TITLE
Out-of-stock notice is visible even if the Cart block updates the quantity of the product correctly

### ISSUE THREAD

**Issue by gigitux** [woocommerce/woocommerce-gutenberg-products-block#7239]
## Describe the bug
@imanish003 found this strange issue when during the test of #7234.

When a product is added multiple times (for example 10), and the merchant updates the stock quantity to a lower value (for example 9), if the user refreshes the page that contains the Cart block, this latter:
- updates the quantity with the max quantity available 🆗 
- shows an out-of-stock notice ⚠️ 

## To reproduce

1. Add item with quantity = 10.
![image](https://user-images.githubusercontent.com/4463174/192743216-f1b8f4ea-3f81-4d1a-91db-82d8d8ce38d7.png)
2. Update the stock quantity to 9.
3. Now refresh the page & open the Cart again. The Cart still shows the notice even though product quantity is updated automatically to 9 as shown in the screenshot below:
![image](https://user-images.githubusercontent.com/4463174/192743366-8773f22b-020d-457b-ba61-61ed21114034.png)
This gets fixed the page is refreshed again.

## Expected behavior

The notice should not be rendered because the cart updates the quantity of the product.

**Comment by opr** [comment]
Thanks @gigitux - this is a duplicate/very similar to #5838 so I will close it.
