### ISSUE TITLE
Forward $attributes to the products grid filter.

### ISSUE THREAD

**Issue by andreilupu** [woocommerce/woocommerce-gutenberg-products-block#724]
Hey,

Since the plugin now skips the product cards templates for rendering, all the themes that have their own HTML markup and style are forced to use the `woocommerce_blocks_product_grid_item_html` filter. In this case, we lack the ability to use the block controls there, because we cannot access the block attributes.

How do you feel if the `woocommerce_blocks_product_grid_item_html` would have the 4th parameter with block attributes?

Or maybe the `$data` parameter could store an `attributes` entry?

Overall, blocks attributes are not sensitive and I think that they should be shared with the output process (or maybe I miss something clear on why is this way now).

I can also help with a PR if we get to a decision.

**Comment by mikejolley** [comment]
@andreilupu since we don't know what other args may be useful to pass to this filter, I'd suggest passing `$this` as the 4th parameter, and then adding a public method (`get_block_attributes`?) to get at that array, or make `attributes` public. 

@Aljullu thoughts?

**Comment by andreilupu** [comment]
`$this` would also be great, as long as we can render our templates in accordance with the block settings.

**Comment by mikejolley** [comment]
I've consolodated all related issues to extending blocks into https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/891 until a decision is made. Please see that issue and add feedback there if relevant. 

Thanks

**Comment by miguelfspinto** [comment]
Are you planning to go forward with this decision? Adding a 4th parameter in the filter will not affect nothing and would solve a lot of challenges.
