### ISSUE TITLE
Unable to hook into address inputs with Javascript (e.g. with Google Places Autocomplete)

### ISSUE THREAD

**Issue by chrismademe** [woocommerce/woocommerce-gutenberg-products-block#7241]
## Describe the bug

I'm upgrading a site to use Block checkout because it solves a few issues we had with the old checkout, however the site in question used to use a Google Places Autocomplete plugin - this obviously doesn't work with the block checkout so I'm trying to implement it.

The problem is however, whilst I can attach the Autocomplete prompt to the first address field, when I then update the other fields with the data, it populates, then resets if you focus on it. It also doesn't move the label out of the way.

## To reproduce

Without writing the code to implement Google Places it's a little hard, but here is a video of what happens. Currently I'm doing this in Vanilla JS. Ideally I'd be able to hook in to the React components for the inputs but I don't think this is possible right now?

https://streamable.com/8evuo0

## Expected behavior

When choosing an address from the Google Autocomplete prompt, the fields should fill in, move their labels out of the way and not reset when a user focuses on them.

### WordPress (please complete the following information):

-   WordPress version: 6.0.2
-   WooCommerce version: 6.9.4
-   WooCommerce Blocks version: 8.6.0
-   Site language: English
-   Any other plugins installed: ACF Pro, WooCommerce Stripe Gateway, WooCommerce Subscriptions, WP Migrate

### Desktop (please complete the following information):

-   OS: macOS
-   Browser: Chrome
-   Version: Latest, I think 110.

Any help is much appreciated! Even pointing in the direction on how the blessed way to do this might be! Thank you.

**Comment by tarunvijwani** [comment]
Hi @chrismademe, thank you for reaching out. 
Yes, you're right. You'd need to switch to React as the input state is controlled by it. You'd need to hook into the cart data store and update the fields from there.

I hope this helps!

**Comment by chrismademe** [comment]
I figured that might be the case, is there documentation for the data store anywhere? I had a quick dive through the repo but my React knowledge is a little lacking!

Thanks for your reply :)

**Comment by chrismademe** [comment]
Just done a bit of digging and found this: https://github.com/woocommerce/woocommerce-blocks/tree/trunk/assets/js/data
Going to see what I can do with this and report back in case anyone else has the same issues!

**Comment by chrismademe** [comment]
Thought I'd update this, after trawling through the code of the WooCommerce Blocks plugin, I finally got this working! Documentation of the data stores would be amazing because this was really confusing to figure out.

Example code below in case anyone needs to do something similar!

### Plugin JS
(requires wp-scripts and custom webpack.config included below)

```js
import { React } from 'react';
import { select, useSelect, useDispatch } from '@wordpress/data';
import { CART_STORE_KEY as storeKey } from '@woocommerce/block-data';
import { registerPlugin } from '@wordpress/plugins';
const { ExperimentalOrderShippingPackages } = wc.blocksCheckout;

const DoSomethingWithShippingAddress = () => {
	const { setShippingAddress, setBillingAddress } = useDispatch(storeKey);
	const shippingAddressInput = document.querySelector('#shipping-address_1');

	if (shippingAddressInput) {
            // Whatever you need to do here, I was listening to the change event on Google Place Autocomplete and then calling setShippingAddress.
            setShippingAddress({ address_1: 'Example', postcode: 'EX01AMP' });
	}

        // Empty component because I don't know how else run React based code any other way.
	return <div></div>;
};

const render = () => {
	return (
		<ExperimentalOrderShippingPackages>
			<DoSomethingWithShippingAddress />
		</ExperimentalOrderShippingPackages>
	);
};

registerPlugin('woocommerce-address-autocomplete', {
	render,
	scope: 'woocommerce-checkout',
});
```

### Webpack Config
Required to map the imports to WooCommerce global objects

```js
const defaultConfig = require('@wordpress/scripts/config/webpack.config');

module.exports = {
	...defaultConfig,
	externals: {
		'@woocommerce/block-data': 'wc.wcBlocksData',
		'@woocommerce/block-checkout': 'wc.wcBlocksCheckout',
		'@woocommerce/base-context': 'wc.wcBlocksSharedContext',
	},
};
```

**Comment by opr** [comment]
Thanks @chrismademe, I'm glad to hear you solved your issue! Thanks for posting how you solved it too, that's really helpful. I agree that the docs should be improved, and I've already started working on adding better documentation for this data store.

I will close this issue in favour of #7451 as that one is more focused. Thanks again!
