### ISSUE TITLE
Work out which data store actions we want to expose for third parties

### ISSUE THREAD

**Issue by alexflorisca** [woocommerce/woocommerce-gutenberg-products-block#7250]
This means adding extra extensibility points through the use of data stores, so it needs to be thought out, and added on a case by case basis. For each action we want to make public, we need to:

- document it under the third party developers docs
- remove the `__internal` prefix from the name of the function

Blocked by #7248

**Comment by ralucaStan** [comment]
We do not need to document the __internal actions as these should not be used by third parties. They are subject to change without warning so please do not rely on them.
