### ISSUE TITLE
"Inherit query from template" toggle for "All Products" Block

### ISSUE THREAD

**Issue by richwpgit** [woocommerce/woocommerce-gutenberg-products-block#7254]
I think a "Inherit query from template" toggle for "All Products" Block, similar to the one for the WordPress "Query Loop" block, would allow for easier theming. This way the all products block could be used on the "Products by Category", "Product Search Results" as well as the "Products by Tags" Templates.

**Comment by gigitux** [comment]
Hi @richwpgit, thanks for opening this issue!
We are working actively to create a new block based on the Query Loop block whose goal is to replace all of our current product-displaying blocks. This new block should be flexible enough to reproduce all of the use-cases currently covered by existing blocks (e.g. showing all products, showing only new products, or products on sale, etc.), while also being filterable via dedicated filter blocks and compatible with FSE templates (i.e. it should replace the placeholders we currently use in archive templates).

If you want to follow the progress, I suggest you subscribe to this issue woocommerce/woocommerce#42616
