### ISSUE TITLE
JS error when a deprecated shortcode block was saved as a reusable block

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#727]
**To Reproduce**
1. Create a post in WooCommerce 3.6 without WooCommerce Blocks installed.
2. Add a _Products by Category_ block and add it to Reusable Blocks.
![image](https://user-images.githubusercontent.com/3616980/62117320-02ad0500-b2bc-11e9-8fc5-010df5d27831.png)
3. Enable WooCommerce Blocks 2.2 or 2.3.
4. Reload the post and notice an error appears in your browser devtools (you might need to open the block selector typing `/` or clicking on the `+` sign.).
![image](https://user-images.githubusercontent.com/3616980/61060538-fa6b5380-a3fa-11e9-8825-d4206878b21b.png)

The block works as expected, though.

**Comment by mikejolley** [comment]
This doesn’t happen for me, but I notice it is showing a shortcode. Do you have a legacy version of that block on your page? They don’t have shortcodes in them any more so this may be the issue.

**Comment by Aljullu** [comment]
> This doesn’t happen for me, but I notice it is showing a shortcode. Do you have a legacy version of that block on your page? They don’t have shortcodes in them any more so this may be the issue.

You're right, the previous steps to reproduce were wrong. I updated the issue after some investigation.

**Comment by Aljullu** [comment]
Closing this issue since it looks like this is the expected behavior for now: https://github.com/WordPress/gutenberg/issues/9070.
