### ISSUE TITLE
Featured Category: JS warning when adding the block

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#728]
**To Reproduce**
1. Create a new post or page and open your browser devtools (F12).
2. Add a _Featured Category_ block and select a category.
3. Notice a warning appears in your browser console:
![image](https://user-images.githubusercontent.com/3616980/61060833-7796c880-a3fb-11e9-8e73-c5030b4f7c0f.png)

The block works as expected, though.

**Comment by nerrad** [comment]
This is triggered by the `<ResizableBox/>` component from `@wordpress/components`:

<details>
<summary>Console Error</summary>
Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in StrictMode (created by Editor)
    in Editor
    in Unknown (created by WithSelect(Editor))
    in WithSelect(Editor)

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: Resizable
</details>

[`ResizableBox`](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/resizable-box) in turn is using the [`re-resizable` package](https://github.com/bokuweb/re-resizable) and ultimately that's what is [throwing the warning](https://github.com/bokuweb/re-resizable/blob/7ea154470567735149d5e3827cc9fb856f8e8f68/src/index.tsx#L463-L465).  I searched through the repo there and there are no issues related.

So this is something that has to be fixed upstream:

- Here's the GB issue I created: https://github.com/WordPress/gutenberg/issues/16950 which also links to an issue I created in the `re-resizable` repository.

**Comment by Aljullu** [comment]
Thanks for investigating where the error comes from @nerrad. I will close this issue, then.
