### ISSUE TITLE
Lots of prefetched scripts are loading in the head tag

### ISSUE THREAD

**Issue by hogash** [woocommerce/woocommerce-gutenberg-products-block#7295]
## Describe the bug
Hey guys,

Lots of prefetched scripts are loading in the head tag, regardless if Cart/Checkout blocks are loaded eg: https://d.pr/i/hWSg9H .

Shouldn't these two checks `$is_block_cart` and `$is_block_checkout` look for positive instead of negative?
- https://github.com/woocommerce/woocommerce-blocks/blob/9f9682fee7478b8fdb9e9e64c1438189bdab2811/src/AssetsController.php#L105
- https://github.com/woocommerce/woocommerce-blocks/blob/9f9682fee7478b8fdb9e9e64c1438189bdab2811/src/AssetsController.php#L109

### WordPress (please complete the following information):

-   WordPress version: 6.0.2
-   WooCommerce version: 6.9.4

### Desktop (please complete the following information):
- MacOS
- Chrome

**Comment by tarhi-saad** [comment]
Thank you, @hogash, for your contribution! 🙌 This is a feature we introduced in this PR #5553:

> This PR implements resource hinting for cart and checkout scripts when we can predict the customer will be visiting those pages during the current session. It essentially pre-caches block assets in the background when the page is idle so that when the customer lands on the cart and checkout pages, the block scripts can be loaded from cache.

> Shouldn't these two checks $is_block_cart and $is_block_checkout look for positive instead of negative?

Prefetching a resource is helpful when we know we’ll need that resource on a subsequent page, and we want to cache it ahead of time.

Some helpful resources:

- [3perf - prefetch](https://3perf.com/blog/link-rels/#prefetch)
- [Preload, Prefetch, And Priorities in Chrome](https://medium.com/reloading/preload-prefetch-and-priorities-in-chrome-776165961bbf)

I'll close this issue but feel free to comment on it if you have more questions, or you can open a new issue if you have a different request or bug report.

**Comment by hogash** [comment]
Thanks @tarhi-saad ! 

But i was not disputing the necessity of prefetching, that's fine. Its the fact that it's always loading because those 2 variables are comparing for negative instead of positive.

For example if cart block exists, load hints. If not, don't. Right now it's they're loading when the cart and checkout blocks are **not** loaded which makes no sense.

Hope it's more clear now.

**Comment by ralucaStan** [comment]
Hi @hogash, thank you for highlighting this. There is already a ticket for limiting resource hinting only when the user is running the blocks https://github.com/woocommerce/woocommerce-blocks/issues/7216 and it should be handled soon.

**Comment by ralucaStan** [comment]
@hogash this was fixed and will be released in WooCommerce Blocks 8.8 (coming next week)

**Comment by hogash** [comment]
> @hogash this was fixed and will be released in WooCommerce Blocks 8.8 (coming next week)

Awesome, thanks for the heads-up @ralucaStan !
