### ISSUE TITLE
Choose a block menu showing over the modal

### ISSUE THREAD

**Issue by imanish003** [woocommerce/woocommerce-gutenberg-products-block#7297]
## Describe the bug

As you can see in the screenshot below, choose block menu appears over the Patterns modal
![image](https://user-images.githubusercontent.com/16707866/193991731-8fd4b1cd-5863-479c-8432-3487a645d407.png)

## To reproduce
1. Edit any post & type `/woo`, and the following menu will appear:
![image](https://user-images.githubusercontent.com/16707866/193992885-0cef88b7-e728-43bb-bf69-8587c8d0eace.png)

2. Click on the plus button available in the top left corner
![image](https://user-images.githubusercontent.com/16707866/193992043-d049f60e-cc64-490f-b6b4-a9bd8801fee4.png)
3. Go to the patterns tab and click on Explore button while `choose a block` menu is still open.
![image](https://user-images.githubusercontent.com/16707866/193992167-8ee75ba0-cc3e-4a60-94c3-4ee876771997.png)
and you will see the issue
![image](https://user-images.githubusercontent.com/16707866/193992346-80cc168a-6cba-4aed-8445-73de0704449e.png)

## Expected behavior

The `choose a block` menu should be behind the modal, in this case, the patterns modal.

**Comment by sunyatasattva** [comment]
Well spotted @imanish003 ! However, this seems to be an issue with Core/Gutenberg and hence out of scope of this repo. It'd be great if you could do a bit of research if this is already known and, if not, report it over at https://github.com/WordPress/gutenberg/

I'm closing it for now. Feel free to let me know if you think we should reopen it.
