### ISSUE TITLE
Rearranging Elements of the Check-Out — Eg. Button Solution

### ISSUE THREAD

**Issue by ghost** [woocommerce/woocommerce-gutenberg-products-block#7300]
## What do you think is missing from the Cart & Checkout blocks?

It would be great to have more flexibility in the order of the checkout steps. 
For example, moving the checkboxes and the order button to the left column in order to fulfill the legal regulations with the "Button Solution" for the German market.

![checkout-page_woo-suggestion](https://user-images.githubusercontent.com/66997584/194031150-1e61ad5e-3bb6-487a-940c-7f486f57a8f5.png)

**Comment by alexflorisca** [comment]
Hi @FBUD. thanks a lot for bringing this up. We have to strike a balance between neat, tested UX that works with conversions, and flexibility here. I actually think you might be onto something, especially if we make the order summary column sticky. I've brought this up with my team, we'll discuss it and get back to you shortly.

**Comment by opr** [comment]
Hi @FBUD - I will close this issue and instead use woocommerce/woocommerce-blocks#7429 as the main one. woocommerce/woocommerce-blocks#7429 is a broader request and if we solve that, your issue will be solved too. Please follow that issue for further updates on this. Thank you!

Edit: We have created a new issue which we will use to track all related issues on this topic. Please subscribe to woocommerce/woocommerce#42554 to receive updates there. Thank you again for reporting this.
