### ISSUE TITLE
Documentations for @woocommerce packages - specifically base-context/hooks

### ISSUE THREAD

**Issue by chrismademe** [woocommerce/woocommerce-gutenberg-products-block#7305]
Hey,

I've added some custom fields to the Block Checkout, but I have no way of validating them. I believe I've found what I need in the `@woocommerce/base-context/hooks` package, which is `useCheckoutSubmit` but it seems like there's no way to import that? I've been through the Webpack config in the WooCommerce Blocks plugin and there  doesn't seem to be any mention of it.

Importing it in my plugin just throws errors.

It'd be awesome if these packages were documented for plugin developers to use because at the moment I can't do anything based on the state of the checkout/cart with my custom fields.

Thanks!
Chris

**Comment by alexflorisca** [comment]
Hi @chrismademe thanks for reaching out. Importing that hook won't work as it's an internal one, we do not expose it to third parties. 

We've actually just released an update that might make this easier for you. We have extracted a lot of the data for the Checkout into [wordpressp/data](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-data/) stores (kind of like redux). The `wc/store/validation` store might be particularly useful to you here. You can find the docs [here](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/data-store/validation.md)

**Comment by ralucaStan** [comment]
Closing this as there is no actionable item. @chrismademe do reach out if you need extra guidance.
