### ISSUE TITLE
Document woocommerce_blocks_loaded 

### ISSUE THREAD

**Issue by ralucaStan** [woocommerce/woocommerce-gutenberg-products-block#7315]
After internal discussions p1664968789479409-slack-C8X6Q7XQU around https://github.com/woocommerce/woocommerce-blocks/issues/7294 it was surfaced that we don't document `woocommerce_blocks_loaded` action. Plugins need to use it instead of `plugins_loaded` if they want to make sure that WC Blocks are loaded and we need to be explicit about this. Useful information in the internal discussion p1665046412343949/1664968789.479409-slack-C8X6Q7XQU

**Comment by tarunvijwani** [comment]
This issue is resolved with the [PR: #7600](https://github.com/woocommerce/woocommerce-blocks/pull/7600).
