### ISSUE TITLE
Product Categories list: Select categories to be listed

### ISSUE THREAD

**Issue by strarsis** [woocommerce/woocommerce-gutenberg-products-block#7339]
## Is your feature request related to a problem? Please describe.
Sometimes only a subset of product categories should be listed.
The Product Categories list block lists all product categories (with optionally empty ones).

## Describe the solution you'd like
A category selection for either explicitly including or excluding categories to be listed.

## Describe alternatives you've considered
List each category manually using the highlighted category block, 
however, the highlighted category block doesn't show empty product categories.

**Comment by albarin** [comment]
Hi @strarsis!
Unfortunately, this is not our immediate focus but we are definitely going to add your request to our backlog to look at in the future.
Thanks a lot for reporting it. 🙌
