### ISSUE TITLE
Customizer: the mini cart icon is bold

### ISSUE THREAD

**Issue by gigitux** [woocommerce/woocommerce-gutenberg-products-block#7359]
## Describe the bug

On Customizer, the Mini Cart icon is bold.

## To reproduce

1. Enable the Storefront theme.
2. Click on "Appearance > Customize".
3. Click on "Widgets > Below Header".
4. Search for the Mini Cart widget.
5. See that the Mini Cart icon seems "bold".

## Expected behavior

The right Mini Cart icon should be rendered.

## Screenshots

![image](https://user-images.githubusercontent.com/4463174/195026074-7b3767fc-1b02-4ee8-a002-6e360463ffc5.png)

**Comment by albarin** [comment]
After more investigation, I think there's some kind of issue with how [this icon](hqyJB5F38BOXTrOyxehUZH-fi-928%3A975&t=sn3IQg5WoxYKK82U-4) is rendered in Firefox, it uses mask and that's causing trouble (none of our other icons use masks). Would be great it some designer could help with this.
