### ISSUE TITLE
Update GitHub Actions that use Node 12

### ISSUE THREAD

**Issue by gigitux** [woocommerce/woocommerce-gutenberg-products-block#7360]
In according with [this GitHub post](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/), we have to migrate all the actions that use Node 12 to Node 16.

![image](https://user-images.githubusercontent.com/4463174/195038896-10d52f70-096c-405f-90ec-de9ac3fe8165.png)

**Comment by ralucaStan** [comment]
@nielslange was this issue closed by https://github.com/woocommerce/woocommerce-blocks/pull/7573 ?

**Comment by nielslange** [comment]
> @nielslange was this issue closed by #7573 ?

Nope, @ralucaStan. In #7573, I addressed other warnings. I did not change the Node version.

**Comment by mikejolley** [comment]
Closing due to pca54o-6Dz-p2
