### ISSUE TITLE
Add missing category filter

### ISSUE THREAD

**Issue by Tropicalista** [woocommerce/woocommerce-gutenberg-products-block#7378]
## Is your feature request related to a problem? Please describe.
At the moment there's no way to add a filter by category. This seems a useful addition.

## Describe the solution you'd like
A filter similar to attribute filter.

## Describe alternatives you've considered
Add another plugin.

**Comment by albarin** [comment]
Hi @Tropicalista!
Thanks for your request!
We have actually discussed the possibility of adding a `Filter by category` block, though it's not a short-term priority for us right now. We are always open for contributions to the repo, if that's something you'd like to do.
Thanks again!

**Comment by Tropicalista** [comment]
I'm trying to create this as separate plugin. Once I have a working block I will try to share it.

In any case do you know how I can import `@woocommerce/editor-components/search-list-control`?

Thanks
