### ISSUE TITLE
TT3: Mini cart styling changes on hover.

### ISSUE THREAD

**Issue by tjcafferkey** [woocommerce/woocommerce-gutenberg-products-block#7379]
## Describe the bug

When using the new TT3 theme, I added one of the WooCommerce headers to my site which included the Mini Cart. On the frontend when I hover over this, the font-size for the price shrinks, this happens on every page loaded. On top of this sometimes it requires two clicks for it to open.

## To reproduce

1. Enable TT3 theme
2. Go to Appearance > Site Editor and replace the header with `WooCommerce Essential Header | Light`
3. Save and visit the frontend.
4. Hover over the Mini Cart to observe the change in font-size.

## Expected behavior

The font-size should remain the same.

## Screenshots

![tt3-header](https://user-images.githubusercontent.com/8639742/195362057-3afb1b27-b00c-47aa-9ea1-c7646e97b904.gif)

**Comment by gigitux** [comment]
Not strictly related to this, but it seems that the `WooCommerce Essential Header | Light` pattern doesn't inherit the global styles. Is it a bug? @Aljullu 
![Screen Capture on 2022-10-28 at 11-19-57](https://user-images.githubusercontent.com/4463174/198552558-05d72e86-f068-4511-a09d-3c3a2276a738.gif)

**Comment by Aljullu** [comment]
> Not strictly related to this, but it seems that the WooCommerce Essential Header | Light pattern doesn't inherit the global styles. Is it a bug? @Aljullu

Good catch. I do think so. We should either:

1) Not define a font color and inherit it from the parent elements.
2) Define a font color and background color, so we can ensure there is enough contrast between the text and the background.

@gigitux will you create an issue for this? I don't think it blocks the TT3 release, though.

**Comment by gigitux** [comment]
> @gigitux will you create an issue for this? I don't think it blocks the TT3 release, though.

Issue created #7523
