### ISSUE TITLE
TT3: Global styles for WooCommerce Blocks not working

### ISSUE THREAD

**Issue by tjcafferkey** [woocommerce/woocommerce-gutenberg-products-block#7391]
## Describe the bug

It appears as though global styles for WooCommerce Blocks are not working with the TT3 theme. When I customize the global styles for the Product Categories List block, they aren't reflected properly on the frontend.

## To reproduce

1. Install and activate TT3
2. Add the Add Product Categories List block to a regular page.
3. To go Appearance > Site Editor > Product Catalog > Add Product Categories List block to this template
4. Using Global Styles change the styling of this specific block
5. View the differences between the Editor vs Template Frontend vs Page Frontend usage of this block.

## Expected behavior

The block would adhere to the global styles set.

## Screenshots

**Site Editor**
![Screenshot 2022-10-13 at 11 51 13](https://user-images.githubusercontent.com/8639742/195582204-68f8f469-fc4d-487d-aab4-f8a3cf063b00.png)

**Template frontend**
![Screenshot 2022-10-13 at 11 51 22](https://user-images.githubusercontent.com/8639742/195582232-b52a16b7-93da-4773-84ad-016ba5865f9b.png)

**Page frontend**
![Screenshot 2022-10-13 at 11 51 29](https://user-images.githubusercontent.com/8639742/195582252-428e6952-45b9-44e6-9f0f-fa085392994b.png)

**Comment by gigitux** [comment]
I'm closing this issue since it doesn't depend on us. There is an issue with WP 6.1 and Global Styles, and there is already a PR https://github.com/WordPress/wordpress-develop/pull/3529
