### ISSUE TITLE
When displaying "all products" or switching to "all products" forget column/row settings

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce-gutenberg-products-block#74]
It's confusing to select all products but only see 3 products displayed (for example).

"Where are all of my products"?

Obviously displaying _all_ products on a large store will be problematic, so perhaps we inherit the `per_page` setting and use that when "All products" is selected.

**Comment by spencerfinnell** [comment]
What about using what is set in the Customizer? Then adding "All Products" output would match the `/shop` page.

**Comment by jameskoster** [comment]
Yup, that'll do the trick.

**Comment by claudiulodro** [comment]
See #87. It's using the theme default number of rows setting from the customizer now.
