### ISSUE TITLE
Mini Cart buttons cut off in specific vertical phone viewports

### ISSUE THREAD

**Issue by seanconklin** [woocommerce/woocommerce-gutenberg-products-block#7400]
Vertical mobile screen partially cuts off the "Go to checkout" button with my iPhone 11 Pro Max and totally cuts off the button in the attached video from a customer using Chrome with vertical screen.

I'm able to reproduce the problem using Chrome Dev Tools but with intermittent results as I click around, refresh, etc.

It appears a contributing factor is the browser's floating navigation bar, which DNE in the Chrome Dev Tools yet the problem sometimes reproduces there as well per the attached SS's.

SS: iPhone Pro Max vertical (reliably reproduces)
![iPhone 11 vertical](https://user-images.githubusercontent.com/19829621/195697045-a4e7b45c-d4b4-4e4c-bd6f-eb8ed7c76f07.PNG)

SS: Chrome Dev Tools iPhone XR (intermittently reproduces)
![Chrome Dev Tools iPhone XR](https://user-images.githubusercontent.com/19829621/195697074-ce200405-76e5-4b3e-96c9-1cfc9c5c6792.png)

SS: Chrome Dev Tools iPad Air (intermittently reproduces)
![Chrome Dev Tools iPad Air](https://user-images.githubusercontent.com/19829621/195697148-2c110a15-0d1f-4c9e-88a5-9098310b1827.png)

Video MP4 (from a customer in Chrome mobile specs unknown)
https://user-images.githubusercontent.com/19829621/195697172-c02af392-3f1d-433e-88a0-cd8230ba5f8d.mp4

**Comment by seanconklin** [comment]
Alternate video format MOV
https://user-images.githubusercontent.com/19829621/195697504-de3647e0-8035-479b-9ba5-f2232af3849a.mov

**Comment by Tropicalista** [comment]
I suppose this is depending on the use of table instead of flex or grid. 

I have similar issue generating by left in stock badge.

In my case I solved modifying `white-space` property property of css.

**Comment by Brianmitchtay** [comment]
Seeing this same issue reported by a user in 5760222-zen. I am able to replicate the same on my testing site.
![Screenshot_20221202-130508](https://user-images.githubusercontent.com/45057772/205398692-acd87767-45ba-43ad-9ea3-e3a1a1c48b55.jpg)
![mini cart](https://user-images.githubusercontent.com/45057772/205398722-1bd49180-dc73-490b-b1f6-436d4b9e10a8.jpg)

**Comment by danielwrobert** [comment]
I've been able to reproduce this on several themes as well (screenshots below). The issue resurfaced today and I've moved it to a high priority item to investigate.

See: p1675100975816569-slack-C02FL3X7KR6 for additional context.

| | |
| ------ | ----- |
|   ![08F40EA6-FB9A-49A7-B8AF-0C972500F3EC](https://user-images.githubusercontent.com/481776/215603226-325da242-d22b-49fa-9509-42659b3ea7bc.PNG)    |    ![591FD170-0F9F-41AF-85C8-8F403077C73C](https://user-images.githubusercontent.com/481776/215603231-1d230c9b-c567-4031-a858-828021f95488.PNG)   |
|    ![569A73FD-FB86-43B5-AE22-3B00C416A037](https://user-images.githubusercontent.com/481776/215603230-89b85552-af5f-4a41-a54f-9a46c7f14ff7.PNG)    |       |
