### ISSUE TITLE
Coupon Code Block Features

### ISSUE THREAD

**Issue by PDowney** [woocommerce/woocommerce-gutenberg-products-block#7402]
## Is your feature request related to a problem? Please describe.
The coupon code block found within the filled cart block defaults to hidden. There is no option to make it expanded by default. There are also technical issues regarding the official WooCommerce Free Gift Coupons plugin purchased from woocommerce.com

## Describe the solution you'd like
I'd like to have a selectable option within the cart that allows me to have the coupon code box always show as expanded.

In addition, some consideration should be given to stores that depend on having a customer enter a coupon code to receive a free product without first having anything in the shopping cart. When visiting the cart page with an empty cart, there is no easy option to show the coupon code inner block in the empty cart block. I personally run a business that gives customers a coupon code that they enter in an empty cart and it gives them a free copy of a Sensei course, so this is not an unimaginable situation.

**Comment by alexflorisca** [comment]
Thanks for letting us know about your use case @PDowney. It seems sensible to me to have an option to show the coupon box by default so we will look into that. Showing the coupon box for an empty cart might be a bigger change that needs to be thought out a bit, but I will add this to our backlog and we will explore the options.

**Comment by ralucaStan** [comment]
Thank you @PDowney for reaching out. After a review with the design team, we won't be pursuing this change at the moment. If there are other requests for this scenario we will reconsider our decision. 

Feel free to provide your valuable feedback on other aspects of the blocks.
