### ISSUE TITLE
Bundled products prices not showing up on the block checkout

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gutenberg-products-block#7410]
## Describe the bug

Compatibility issue with [Product Bundles](https://woocommerce.com/products/product-bundles/) (Might be an issue with Product Bundles and not WC Blocks).

The price of the products within a bundle don't show up on the checkout summary, even when "Price Visibility" is enabled on "Cart/checkout" und "Advanced settings".

## To reproduce

1. Create a product. Under "Product type", select "Product bundle".
2. Under "Bundled products", add two products.
3. Under the product's "Basic settings", check off "Priced individually".
4. On the frontend, add this bundle to your cart.
5. Go to both the shortcode and block checkouts.
6. Notice that the bundled product has an individual price on the regular checkout, but it doesn't on the block one.

## Expected behavior

I'd expect the block checkout to have the same behavior as the regular checkout. In this case, I'd expect to see the individual price of the product on the checkout summary.

## Screenshots

Regular and block checkout comparison.
![loV9vQ.png](https://user-images.githubusercontent.com/41606954/195951772-25062526-dace-4ac6-89b3-aa759ead3360.png)

### WordPress (please complete the following information):

-   WordPress version: 6.0.2
-   Gutenberg version (if installed): [e.g. 12.0.0]
-   WooCommerce version: [e.g. 6.1] 7.0.0
-   WooCommerce Blocks version: 8.7.2
-   Site language: EN
-   Any other plugins installed: Product Bundles

### Desktop (please complete the following information):

N/A

### Smartphone (please complete the following information):

N/A

## Additional context

N/A

**Comment by nielslange** [comment]
Hello @a-danae 👋

Thanks for reaching out. I was able to reproduce this problem informed I informed the team that maintains the Product Bundle extension about this. They will take care of this. As there are no further actions for the WooCommerce Blocks team, I'll close this issue. But please don't hesitate to create a new issue if there's anything else that isn't working as expected or that's unclear.
