### ISSUE TITLE
Investigate why WordPress.com bug only happen for Cart and not Checkout block

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#7424]
In https://github.com/woocommerce/woocommerce-blocks/issues/5866 and https://github.com/woocommerce/woocommerce-blocks/pull/7367, we worked around the WordPress.com issue. We know for sure that WordPress.com code is monkeypatching some wp.data functions, mainly replaceBlocks and replaceInnerBlocks, and causing them to have an unstanble reference, which throws `useForcedLayout` into an infinite loop.

What we don't know, is why this only happens in Cart block and not Checkout block, and why it went away and returned. From my understanding, something in our code is shortcutting `useForcedLayout` early in Checkout, and did so for Cart, but surfaced again.

It would be good to understand this so if we can't fix it in WordPress.com, we have better mitigation.

It should be noted that, like https://github.com/woocommerce/woocommerce-blocks/pull/6718, this is just a temporary fix for a single place, it is very likely that the monkeypatching code will touch several places in our code base, and we will need to fix everyone of them, a better solution would be to fix it from the root.

**Comment by ralucaStan** [comment]
Related to #5866

**Comment by ralucaStan** [comment]
Adding external issue for reference https://github.com/Automattic/wp-calypso/issues/66092

**Comment by ralucaStan** [comment]
We have some next steps based on pca54o-4GY-p2#comment-4658.

We'll try in https://github.com/woocommerce/woocommerce-blocks/issues/7637 the proposed solution. If that fixes the issue this investigation won't be necessary.

**Comment by ralucaStan** [comment]
Closing this as the initial issue was fixed in https://github.com/woocommerce/woocommerce-blocks/pull/7879. If we need to investigate at some point in the future we can reopen.
