### ISSUE TITLE
Translation issue in French: "Save %s" is not translated by the right word

### ISSUE THREAD

**Issue by GDMarket** [woocommerce/woocommerce-gutenberg-products-block#7426]
**Prerequisites (mark completed items with an [x]):**
- [X ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [X ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

I made the following suggestion on the translation page and it seems it has been rejected the first time: the “Save %s” string that is displayed on discounted products has been translated to “Enregistrer %s” in french wich makes non-sense.

There has been a misunderstanding as we are not talking about saving a file, an image… but explaining to the customer that he is making a saving which, in french, could be translated to “Économisez %s”, like “Économisez 20€”.

**Comment by roykho** [comment]
Hi @GDMarket - Thanks for reporting. Can you please link to the exact line of code this is happening to?

**Comment by GDMarket** [comment]
Hello @roykho 

According to "[Translating WordPress](https://translate.wordpress.org/)" (you can find my report here: https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/fr/default/?filters%5Bstatus%5D=waiting):

[packages/woocommerce-blocks/build/cart-blocks/cart-line-items--mini-cart-contents-block/products-table-frontend.js:13](https://plugins.trac.wordpress.org/browser/woocommerce/tags/7.0.0/packages/woocommerce-blocks/build/cart-blocks/cart-line-items--mini-cart-contents-block/products-table-frontend.js#L13)
    [packages/woocommerce-blocks/build/cart.js:19](https://plugins.trac.wordpress.org/browser/woocommerce/tags/7.0.0/packages/woocommerce-blocks/build/cart.js#L19)
    [packages/woocommerce-blocks/build/mini-cart-contents.js:11](https://plugins.trac.wordpress.org/browser/woocommerce/tags/7.0.0/packages/woocommerce-blocks/build/mini-cart-contents.js#L11)

I've posted this here because I've been told to do so on wordpress woocommerce support page.

Thank you.

**Comment by nielslange** [comment]
Hello @GDMarket 👋

Thanks for reaching out. Please note that translations are reviewed by volunteers. It's possible that your initial translation had been rejected as the reviewer wasn't aware of the context. I can see that the translation _"Économisez %s"_ [is currently waiting to be reviewed](https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/fr/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=578221&filters%5Btranslation_id%5D=98845026). Given the overall status of the French translations, I assume that someone from the community will review this waiting string fairly soon.

In case the string got rejected again or if you find other strings that are wrong translated, you can report this directly within the corresponding translation via the following steps:

1. Open the corresponding translation.
2. Open the contextual links:
<img width="1231" alt="Screenshot 2022-10-19 at 10 04 54" src="https://user-images.githubusercontent.com/3323310/196587722-177925e0-cb7e-4a21-8a7a-5c7f41b44147.png">
3. Select the option `Discussion`:
<img width="1211" alt="Screenshot 2022-10-19 at 10 06 40" src="https://user-images.githubusercontent.com/3323310/196587964-72989536-ebf0-4d80-bca9-7fa0263b732c.png">
4. Select the topic `Question about translating to French (France)` and report the problem:
<img width="1215" alt="Screenshot 2022-10-19 at 10 09 46" src="https://user-images.githubusercontent.com/3323310/196588427-4ad04b04-cf6b-4c27-988d-b535383b6041.png">

I'm closing this issue for now, but you are welcome to reach out again if you have further questions.

cc: @roykho
