### ISSUE TITLE
Help rearrange checkout block fields

### ISSUE THREAD

**Issue by Goldenpiece** [woocommerce/woocommerce-gutenberg-products-block#7429]
Hi, I’d like to make a few changes to the checkout block:

  1). Move the Payment options section above billing address section.
  2). Merge (email input field) and (phone input field) into a single row to save space.
  3). Move proceed to paypal button to the right side, under order summary total. 

Notice the difference between Picture A and Picture B (Before/After) to see the expected changes

Please Assist,
Thanks

**Comment by opr** [comment]
Hi @Goldenpiece thank you for creating this issue. We have another similar issue about moving the "place order" button (Proceed to PayPal) in woocommerce/woocommerce-blocks#7429 but I think your issue illustrates the need for the ability to customise the block even further.

Right now there is no way to achieve what you want with the Checkout block as the structure is very rigidly defined, however we are beginning to explore ways to implement this functionality. I will move this issue into our backlog so we can update it when we know more about the problem. Thank you for your patience.

**Comment by opr** [comment]
Hi again @Goldenpiece. We have created a new issue which we will use to track all related issues on this topic. Please subscribe to woocommerce/woocommerce#42554 to receive updates there. Thank you again for reporting this.
