### ISSUE TITLE
Featured Category block improvement

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-gutenberg-products-block#743]
Currently, the way we display the category selection control gives the sensation that it's possible to select more than 1 category (or subcategory), and this may cause some confusion. Probably it would be better do opt for a pattern similar to what we have now in the Featured Product block.

![Featured-Category-selection](https://user-images.githubusercontent.com/3380168/61362967-0e8bd680-a87b-11e9-947a-96733d95debe.png)

**Comment by Aljullu** [comment]
Closed by #756.
