### ISSUE TITLE
Feedback on ./src/StoreApi/docs/checkout.md

### ISSUE THREAD

**Issue by paulchrisycj** [woocommerce/woocommerce-gutenberg-products-block#7430]
{
    "code": "rest_missing_callback_param",
    "message": "Missing parameter(s): billing_address",
    "data": {
        "status": 400,
        "params": [
            "billing_address"
        ]
    }
}

I keep getting this error whenever I am trying to fill in the details for checkout using Postman. Even though my request already specified raw data with the following fields. Any help?

**Comment by opr** [comment]
Hi @paulchrisycj - please could you show us your request in postman?

Here's an example of one that works (I just tested it) so perhaps you could compare it to yours and see if it looks the same:

```js
{
    "billing_address": {
        "first_name": "Jonny",
        "last_name": "Awesome",
        "company": "",
        "address_1": "100 Test Street",
        "address_2": "",
        "city": "Los Angeles",
        "state": "CA",
        "postcode": "90210",
        "country": "US",
        "email": "jonny.awesome.123@gmail.com",
        "phone": ""
    },
    "customer_note": "",
    "create_account": false,
    "payment_method": "cod",
    "payment_data": [
    ],
    "extensions": {},
    "shipping_address": {
        "first_name": "Jonny",
        "last_name": "Awesome",
        "company": "",
        "address_1": "100 Test Street",
        "address_2": "",
        "city": "Los Angeles",
        "state": "CA",
        "postcode": "90210",
        "country": "US",
        "phone": ""
    }
}
```

If you use mine does it work or do you get the same error? (Bear in mind you'll need to activate the cash on delivery payment method to test this since that's the payment method selected in the request!)

**Comment by paulchrisycj** [comment]
Hi @opr, thanks for the example, I managed to get it working. Sorry for the late reply, I was focusing on different parts of the project and didn't notice someone replied. Thanks!
