### ISSUE TITLE
Razorpay not working with woocommerce blocks.

### ISSUE THREAD

**Issue by sarawagirahul** [woocommerce/woocommerce-gutenberg-products-block#7436]
## What do you think is missing from the Cart & Checkout blocks?

It's amazing, but I'm trying to add Razorpay as a payment gateway, and it's not working with it; the plugin is active under settings>payments> but still doesn't show up. 

Looking forward for the solutions.

**Comment by opr** [comment]
Hi @sarawagirahul - we have an open issue about Razorpay already in#6944. I'll close this issue and mention it in woocommerce/woocommerce#42603 - please follow that issue for updates!

Thank you.
