### ISSUE TITLE
Composite products StoreApi

### ISSUE THREAD

**Issue by frnodb** [woocommerce/woocommerce-gutenberg-products-block#7444]
Has any plan to integrate composite products with new cart api?

**Comment by nielslange** [comment]
Hello @frnodb 👋

> Has any plan to integrate composite products with new cart api?

I'm not sure what exactly you are aiming for. While [WooCommerce Composite Products](https://woocommerce.com/products/composite-products/) are already compatible with [WooCommerce Blocks](https://woocommerce.com/products/woocommerce-gutenberg-products-block/), what do you mean by integrating that extension with the Cart API?

**Comment by frnodb** [comment]
I think actually it’s not possible to add to cart a composite product vía rest Api ,isn’t it?

**Comment by nielslange** [comment]
> I think actually it’s not possible to add to cart a composite product vía rest Api ,isn’t it?

I reached out to the team that maintains the [WooCommerce Composite Products](https://woocommerce.com/products/composite-products/), and they informed me that currently it's only possible to add composite products to an order using the REST API, but not the cart using the Store API. I've added this feature to their list, but cannot tell you when or if they address this feature request.

As there's no action item for the WooCommerce Blocks development team, I'm going to close this issue now. But please don't hesitate to create another issue if you have more questions or suggestions.
