### ISSUE TITLE
Add documentation for the `wc/store/cart` data store

### ISSUE THREAD

**Issue by opr** [woocommerce/woocommerce-gutenberg-products-block#7451]
This data store has been in place for a while, but had not been documented. A user reported that it would be really helpful to have this documented in #7241 and I agree.

Please go through the selectors and public facing actions of this store and document them.

I already started working on this on my branch `add/wc-store-cart-docs` so feel free to continue from there.

**Comment by ralucaStan** [comment]
closed by https://github.com/woocommerce/woocommerce-blocks/pull/7708
