### ISSUE TITLE
Need a basic example on how to use woocommerce shared hocs

### ISSUE THREAD

**Issue by Tropicalista** [woocommerce/woocommerce-gutenberg-products-block#7454]
Due the lack of documentation, I cannot understand how to use exported woocommerce module in a custom block.

I'm trying to create a variation table, using react.

I've registered a block:

```
function archimedia_block_init()
{
    register_block_type_from_metadata(
        __DIR__,
    );
}
add_action('init', 'archimedia_block_init');
```

I'm trying to use woocommerce hocs:

```
import { withProduct } from '@woocommerce/shared-hocs';
const Edit = ( { attributes } ) => {
	return (
		<div>
			<p>My test</p>
		</div>
	);
}
export default Edit;
```
I got this error: 
`Module not found: Error: Can't resolve '@woocommerce/shared-hocs'`

I see that the module are exported and are loaded on the page. How can I use it to build my custom block?

**Comment by nielslange** [comment]
Hello @Tropicalista 👋

Thanks for reaching out. To better assist you, can you explain what exactly you're trying to accomplish?

In the example you shared above, I see that you're calling `import { withProduct } from '@woocommerce/shared-hocs';`. Looking at https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/shared/hocs/with-filtered-attributes.js and https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/shared/hocs/with-product-data-context.js, I see that `@woocommerce/shared-hocs` only holds the functions `withFilteredAttributes()` and `withProductDataContext()`, but it does not contain a function called `withProduct()`.

As for the error, have you installed the `@wordpress/dependency-extraction-webpack-plugin` dependency yet? You can find further information about this dependency via the following resources:

- https://developer.wordpress.org/block-editor/reference-guides/packages/packages-dependency-extraction-webpack-plugin/
- https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/checkout-block/integration-interface.md#get_script_data
- https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/contributors/contributing/javascript-build-system.md#external-scripts

**Comment by Tropicalista** [comment]
I was able to solve my problem using this config:

```
const defaultConfig = require( '@wordpress/scripts/config/webpack.config' );
const WooCommerceDependencyExtractionWebpackPlugin = require( '@wordpress/dependency-extraction-webpack-plugin' );

const wcDepMap = {
	'@woocommerce/blocks-registry': [ 'wc', 'wcBlocksRegistry' ],
	'@woocommerce/settings': [ 'wc', 'wcSettings' ],
	'@woocommerce/block-data': [ 'wc', 'wcBlocksData' ],
	'@woocommerce/data': [ 'wc', 'data' ],
	'@woocommerce/shared-context': [ 'wc', 'wcBlocksSharedContext' ],
	'@woocommerce/shared-hocs': [ 'wc', 'wcBlocksSharedHocs' ],
	'@woocommerce/price-format': [ 'wc', 'priceFormat' ],
	'@woocommerce/blocks-checkout': [ 'wc', 'blocksCheckout' ],
};

const wcHandleMap = {
	'@woocommerce/blocks-registry': 'wc-blocks-registry',
	'@woocommerce/settings': 'wc-settings',
	'@woocommerce/block-settings': 'wc-settings',
	'@woocommerce/block-data': 'wc-blocks-data-store',
	'@woocommerce/data': 'wc-store-data',
	'@woocommerce/shared-context': 'wc-blocks-shared-context',
	'@woocommerce/shared-hocs': 'wc-blocks-shared-hocs',
	'@woocommerce/price-format': 'wc-price-format',
	'@woocommerce/blocks-checkout': 'wc-blocks-checkout',
};

const requestToExternal = ( request ) => {
	if ( wcDepMap[ request ] ) {
		return wcDepMap[ request ];
	}
};

const requestToHandle = ( request ) => {
	if ( wcHandleMap[ request ] ) {
		return wcHandleMap[ request ];
	}
};

module.exports = {
	...defaultConfig,
	entry: {
		...defaultConfig.entry,
		frontend: './src/frontend.js',
	},
	plugins: [
		...defaultConfig.plugins.filter(
			( plugin ) =>
				plugin.constructor.name !== 'DependencyExtractionWebpackPlugin'
		),
		new WooCommerceDependencyExtractionWebpackPlugin( {
			requestToExternal,
			requestToHandle,
		} ),
	],
};
```
This can be added to documentation for people who want try to build custom blocks.

Thanks

**Comment by nielslange** [comment]
> I was able to solve my problem using this config:

I'm glad to hear that you've been able to solve this case, @Tropicalista.

> This can be added to documentation for people who want try to build custom blocks.

That's a great idea. I just created https://github.com/woocommerce/woocommerce-blocks/issues/7500 to track this.
