### ISSUE TITLE
TT3 theme: Testing the Cart Block

### ISSUE THREAD

**Issue by ralucaStan** [woocommerce/woocommerce-gutenberg-products-block#7463]
We need to test the Cart Block and see if there are any issues with the new TT3 theme included in WP 6.1.

View the repository for TT3 and follow the instructions to get started: https://github.com/WordPress/twentytwentythree

**Comment by nielslange** [comment]
Closing this issue after successfully tested the Cart block using [WordPress 6.1-RC2](https://wordpress.org/news/2022/10/wordpress-6-1-release-candidate-2-now-available/) and the [Twenty Twenty-Three theme](https://github.com/WordPress/twentytwentythree):

- https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/testing/cart-checkout/README.md
- https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/testing/cart-checkout/general-flow.md
- https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/testing/cart-checkout/editor.md
- https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/testing/cart-checkout/shipping.md
- https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/testing/cart-checkout/payment.md
- https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/testing/cart-checkout/items.md
- https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/testing/cart-checkout/taxes.md
- https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/testing/cart-checkout/coupons.md
- https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/testing/cart-checkout/compatibility.md
