### ISSUE TITLE
TT3 theme: some buttons are not legible with some style variations

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#7466]
## Describe the bug

WC Blocks buttons are not legible with specific Twenty Twenty Three style variations. Originally reported by @peterfabian.

## To reproduce

1. Download and activate [TT3](https://github.com/WordPress/twentytwentythree).
2. Add the Products by Category block and select clothing.
3. Visit the page in the frontend.
4. Test all TT3 style variations (Appearance > Site Editor > Styles > Browse Styles).
5. Notice with some of them buttons text is not visible.

We should test all other blocks to verify which ones are affected.

## Expected behavior

Buttons should be legible.

## Screenshots

![imatge](https://user-images.githubusercontent.com/3616980/197570624-31c442f2-1924-4691-8510-fe862a4b607a.png)

## Proposed solution

I think that if we add the Elements API class (`wp-element-button`) to all buttons, they will display correctly. That class can be retrieved (in WP 6.1) with `WP_Theme_JSON_Gutenberg::get_element_class_name( 'button' )`.

**Comment by Aljullu** [comment]
Related issue: https://github.com/woocommerce/woocommerce-blocks/issues/7388.

They might even be the same issue or be two different issues that could be fixed with the same fix, but I logged it separately just in case.

**Comment by gigitux** [comment]
#7388 fixes this issue.
