### ISSUE TITLE
Store API not return attribute for variations

### ISSUE THREAD

**Issue by Tropicalista** [woocommerce/woocommerce-gutenberg-products-block#7477]
## Describe the bug

The store api is not returning attributes for variation query:

`/wp-json/wc/store/v1/products?type=variation&parent=13`

## To reproduce

1. Go to `/wp-json/wc/store/v1/products?type=variation&parent=13`
2. Check response attributes properties

## Expected behavior

The aapi should return variation attributes as it happens on variations property of product query.

**Comment by nielslange** [comment]
Hello @Tropicalista 👋

Thanks for reaching out. As the attributes are part of the parent product, you can retrieve both the attributes themselves and the corresponding variation products by fetching the Store API endpoint for the parent product. In my test store, I have the variable product _Hoddie_ with the product ID 30. 

This product has the following attributes:
- Logo: Yes | No
- Color: red | green | blue

In addition, this product has the following variations:
- ID: 30 | Logo: Yes | Color: blue
- ID: 23 | Logo: No | Color: red
- ID: 24 | Logo: No | Color: green
- ID: 25 | Logo: No | Color: blue

Below, you can find screenshots of the attribute and variations both on the product page and in the Store API response.

<table>
<tr>
<td valign="top">Attributes on product page:
<br><br>

<img width="1436" alt="Screenshot 2022-10-27 at 09 56 32" src="https://user-images.githubusercontent.com/3323310/198180201-d13a6fa9-5364-4dbd-bb0a-09d4efa4b827.png">

</td>
<td valign="top">Attributes in Store API call:
<br><br>

<img width="1439" alt="Screenshot 2022-10-27 at 10 01 36" src="https://user-images.githubusercontent.com/3323310/198180877-a195f533-746e-4ead-a003-0f948362b2e6.png">

</td>
</tr>
</table>

<table>
<tr>
<td valign="top">Variations on product page:
<br><br>

<img width="1441" alt="Screenshot 2022-10-27 at 09 56 49" src="https://user-images.githubusercontent.com/3323310/198180233-512a6d4d-5b19-4699-bfe2-75e8b291867b.png">

</td>
<td valign="top">Variations in Store API call:
<br><br>

<img width="1438" alt="Screenshot 2022-10-27 at 10 01 53" src="https://user-images.githubusercontent.com/3323310/198180924-ef37157f-8f54-471f-9743-06c3eb02855b.png">

</td>
</tr>
</table>

I hope this answers your question. As there are no action items for us, I'm going to close this issue. But please don't hesitate to create another issue if you have additional questions or suggestions.

**Comment by Tropicalista** [comment]
Hi, thanks for your example. 

I'm aware of this. I was wondering if there's a method to retrieve more details about variations.

For my use case I need a way to build a product variations grid. SoI need a way to collect all variations details, but it seems not possible with current endpoint.

For example there's not an endpoint to retrieve all variations with:

- image
- attributes
- price

I will try to extend schema and I report back. Probably share an example of a custom block can also help other developers with this too: https://github.com/woocommerce/woocommerce-blocks/issues/7500
