### ISSUE TITLE
After added to cart problem.

### ISSUE THREAD

**Issue by ProdesignerAgency** [woocommerce/woocommerce-gutenberg-products-block#7483]
## Describe the bug

So meny scripts after added to cart.

## To reproduce

1. I don`t use WooCommerce blocks.
2. when i add product to cart, and i refresh page i have those scripts:

![Zrzut-ekranu-2022-10-26-o-10 00 34](https://user-images.githubusercontent.com/6230472/197970470-3ce83e32-39a7-4451-939f-96ddf28d0a82.jpg)

3. When i remove product from cart i don`t have those scripts.

## Expected behavior

No scripts :)

### WordPress (please complete the following information):

-   WordPress version: [e.g. 6.0.3]
-   WooCommerce version: [e.g. 7]
-   Site language: PL
-   Any other plugins installed: Clean Installation

**Comment by nielslange** [comment]
Hello @ProdesignerAgency 👋

Thanks for reaching out. Both WordPress and WooCommerce are moving from PHP to JavaScript. JavaScript requires various library files. The scripts that you are seeing, are these library files. It is worth noting that all scripts that start with `wp-include` are coming directly from WordPress. Removing these scripts would lead to the fact that both WordPress and WooCommerce would no longer function.

Given that these scripts are required, there are no action points for us. Therefore, I'm going to close this issue for now. But please don't hesitate to contact us again if you have more questions or suggestions.
