### ISSUE TITLE
JS console error displayed when attempting to apply an invalid coupon.

### ISSUE THREAD

**Issue by wavvves** [woocommerce/woocommerce-gutenberg-products-block#7485]
## Describe the bug

When attempting to apply an invalid/non-existent coupon, an error is displayed on JS console.

## To reproduce

1. Go to the Cart Block page
2. Apply a non-existent coupon
3. Open JS console on dev-tools and see the following error

`express-payment-frontend.js?ver=7f2f9e5d1fbf79754cfc:3 Uncaught (in promise) ReferenceError: receiveApplyingCoupon is not defined at express-payment-frontend.js?ver=7f2f9e5d1fbf79754cfc:3:157`

## Expected behavior

No errors should be displayed on the console after attempting to apply an invalid coupon code.

## Screenshots

<img width="877" alt="image" src="https://user-images.githubusercontent.com/17236129/198016421-7821622f-01c7-4b12-aaad-4f993b47ca5b.png">

**Comment by nefeline** [comment]
I'm going ahead and closing this issue since it was already solved (see: https://github.com/woocommerce/woocommerce-blocks/pull/7969#issuecomment-1357874533 ).
