### ISSUE TITLE
Missing payment options

### ISSUE THREAD

**Issue by trevormiddleton** [woocommerce/woocommerce-gutenberg-products-block#7487]
## What do you think is missing from the Cart & Checkout blocks?
The main payment options! We run an online store that relies on WooCommerce. Since we replaced the old checkout page with the WooCommerce checkout block, we've had reports from mobile users of only the Express Pay (Google Pay/Apple Pay) being available. I've seen this myself in Firefox on my iPhone 12 Pro Max running iOS 16.1. In Firefox for macOS Catalina, that section of the checkout block generated an error message that it couldn't be retrieved. Please can you fix this as a matter of urgency?

Kind regards
Trevor Middleton

**Comment by nielslange** [comment]
Hello @trevormiddleton 👋

Thanks for reaching out. Currently, the Checkout and Cart blocks are in an early stage and not all payment gateways are supported. Can you tell us which payment option isn't working as expected on your end?

**Comment by trevormiddleton** [comment]
Hi there

Thanks for getting back to me.

The section of the checkout block containing the WooCommerce Payments, PayPal, and Stripe Payments options doesn’t always appear. I tried it myself on my iPhone earlier, as we’d been contacted by a customer who said that only the Express Payment options was showing, and found that I had to refresh the page in order for the other payment options to appear.

As we need payments to be 100% reliable, would you advise switching back to the old, shortcode, shopping cart and checkout pages?

Kind regards
Trevor Middleton

**Comment by nielslange** [comment]
> The section of the checkout block containing the WooCommerce Payments, PayPal, and Stripe Payments options doesn’t always appear. I tried it myself on my iPhone earlier, as we’d been contacted by a customer who said that only the Express Payment options was showing, and found that I had to refresh the page in order for the other payment options to appear.

Thanks for your reply. While [PayPal Payments](https://woocommerce.com/products/woocommerce-paypal-payments/) is incompatible with WooCommerce Blocks yet, [WooCommerce Payments](https://woocommerce.com/payments/) and [Stripe Payments](https://woocommerce.com/products/stripe/) are compatible. 

You mentioned that the payments only appear when refreshing the page. I assume that you don't see PayPal, but only WooCommerce Pay and Stripe, correct? Given that they sometimes appear, I suggest executing a theme/plugin conflict test as described on https://woocommerce.com/document/how-to-test-for-conflicts/. This should help to clarify if the current theme or any of the other active plugins lead to this problem.

> As we need payments to be 100% reliable, would you advise switching back to the old, shortcode, shopping cart and checkout pages?

If offering PayPal Payments is crucial for your business, I'd suggest switching back to the shortcode-based checkout. In case PayPal Payments are not crucial for your business, I'd proceed with the Cart and Checkout blocks and keeping an eye on https://github.com/woocommerce/woocommerce-blocks/issues/6816, to see when PayPal Payments will become compatible with WooCommerce Blocks.

**Comment by trevormiddleton** [comment]
Sent from my iPhoneOn 27 Oct 2022, at 04:48, Niels Lange ***@***.***> wrote:﻿

The section of the checkout block containing the WooCommerce Payments, PayPal, and Stripe Payments options doesn’t always appear. I tried it myself on my iPhone earlier, as we’d been contacted by a customer who said that only the Express Payment options was showing, and found that I had to refresh the page in order for the other payment options to appear.

Thanks for your reply. While PayPal Payments is incompatible with WooCommerce Blocks yet, WooCommerce Payments and Stripe Payments are compatible.
You mentioned that the payments only appear when refreshing the page. I assume that you don't see PayPal, but only WooCommerce Pay and Stripe, correct? Given that they sometimes appear, I suggest executing a theme/plugin conflict test as described on https://woocommerce.com/document/how-to-test-for-conflicts/. This should help to clarify if the current theme or any of the other active plugins lead to this problem.The Quick Pay section, featuring Apple Pay (iOS) or Google Pay (Android) is visible, but the entire section featuring PayPal, WooCommerce Pay, and Stripe doesn’t appear until you refresh the page. In desktop browsers there is an error-related graphic. Here’s an example of the type of message we’ve been getting recently:‘Hi, I'm trying to order some curry kits via your website, but it's only giving me payment option via Google pay. Do you not accept any other payment options?’

As we need payments to be 100% reliable, would you advise switching back to the old, shortcode, shopping cart and checkout pages?

If offering PayPal Payments is crucial for your business, I'd suggest switching back to the shortcode-based checkout. In case PayPal Payments are not crucial for your business, I'd proceed with the Cart and Checkout blocks and keeping an eye on #6816, to see when PayPal Payments will become compatible with WooCommerce Blocks.I’ve already switched back to the shortcode-based shopping cart and checkout. Many of our customers prefer to use PayPal, so that option is essential for us.

**Comment by nielslange** [comment]
> Many of our customers prefer to use PayPal, so that option is essential for us. 

In this case, I suggest using the shortcode-based checkout together with [PayPal Payments](https://woocommerce.com/products/woocommerce-paypal-payments/) while keeping an eye on [#6816](https://github.com/woocommerce/woocommerce-blocks/issues/6816).

Given that there are no action items for us at this time, I'm closing this issue. But please don't hesitate to create another issue if you have further questions or suggestions.
