### ISSUE TITLE
Add a block info section to the sidebar

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce-gutenberg-products-block#75]
![desc](https://cldup.com/WGaorCb1WR-2000x2000.png)

In addition to a description we should highlight what the current block is displaying with a link to change it;

![current](https://cldup.com/HUYu4s99nK-3000x3000.png)

**Comment by spencerfinnell** [comment]
BlockDescription is removed in 2.4

https://github.com/WordPress/gutenberg/pull/5398

**Comment by jameskoster** [comment]
Interesting. Missed that! 

In the case of the products block I think there's still some value in revealing the scope of the current block. We'll have to think about the design though.

**Comment by jameskoster** [comment]
Just circled back to this, looks like block descriptions are still present, just the method changed; https://github.com/WordPress/gutenberg/blob/master/docs/deprecated.md#240

So we can add something like this;

![description](https://cldup.com/-JHQe-ZO4i-3000x3000.png)

![description2](https://cldup.com/mld26nKupF-3000x3000.png)

**Comment by claudiulodro** [comment]
See #90
