### ISSUE TITLE
Document how to use @woocommerce/shared-hocs

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#7500]
In woocommerce/woocommerce-blocks#7454, @Tropicalista asked how to use `@woocommerce/shared-hocs` as this was not clear in our docs. This issue aims to improve our docs by explaining how to use `@woocommerce/shared-hocs` and showing an example, e.g. https://github.com/woocommerce/woocommerce-blocks/issues/7454#issuecomment-1289519939.

**Comment by tomalec** [comment]
See https://github.com/woocommerce/woocommerce/issues/42584

**Comment by mikejolley** [comment]
Closed in favour of https://github.com/woocommerce/woocommerce/issues/42584
