### ISSUE TITLE
[Product Query - Atomic Blocks] Review how we avoid enqueueing JS assets when blocks are rendered on the server side

### ISSUE THREAD

**Issue by gigitux** [woocommerce/woocommerce-gutenberg-products-block#7511]
## Describe the bug

Thanks to #7504, we discovered that the approach we are using to avoid enqueueing JS assets when blocks are rendered on the server side breaks custom translations.

The approach consists of avoiding enqueueing JS assets during the `initialize()` ([ProductButton class](https://github.com/woocommerce/woocommerce-blocks/blob/771716951a9814dd7fd412246b45d0a059024afe/src/BlockTypes/ProductButton.php/#L55-L61), [AbstractBlock class](
https://github.com/woocommerce/woocommerce-blocks/blob/771716951a9814dd7fd412246b45d0a059024afe/src/BlockTypes/AbstractBlock.php/#L115-L116))

Instead, we enqueue the assets in the render method: when the content:
- isn't empty, it is necessary to enqueue JS assets because the block will be rendered on the client side. It means that the client will download the JS.
- is empty, it is unnecessary to enqueue JS assets because the markup is generated server-side.

### Testing

1. Revert the changes done in #7504.
2. Add an instance of the **All Products** Block to the page.
3. Use a plugin like Loco Translate to translate the text of `%d in cart` within the WooCommerce core plugin language files.
4. Visit the All Products Block page and add a product to the cart.
5. Verify the string isn't being translated.

## Expected behavior

We should try to understand why this approach breaks custom translations, and we should find an alternative approach.

**Comment by sunyatasattva** [comment]
This issue might not be reproduceable anymore, @dinhtungdu is going to double check.

**Comment by dinhtungdu** [comment]
Update, reverting changes in https://github.com/woocommerce/woocommerce-blocks/pull/7504 still breaks the translation.  I'm investigating how we can selectively enqueue translation only when needed.

**Comment by dinhtungdu** [comment]
In 7504, [only changes were made](https://github.com/woocommerce/woocommerce-blocks/pull/7504/files#diff-1ac318a88a9ab3f401069703369347d0434e49bde5569256881807db16b0b1d4R43-R49) to `AllProduct.php` fixes the translation issue for all inner blocks of `All Products` block. 

[This change](https://github.com/woocommerce/woocommerce-blocks/pull/7504/files#diff-0b312ca1f7285ba82ef3260ca7dc152e5f4f105ca616a505d4848712ab1e4d26R59-R60) doesn't have any effect in the All Products context. It also makes the if condition in the `render()` method redundant:

https://github.com/woocommerce/woocommerce-blocks/blob/e875692b5dadd336e70db5931d2f9be80a82dc8a/src/BlockTypes/ProductButton.php#L79-L83
