### ISSUE TITLE
Fix Header and Footer patterns not being available in pattern chooser for replacing existing header/footer layout

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#7518]
We now have [header and footer patterns bundled with WooCommerce Blocks](https://github.com/woocommerce/woocommerce-blocks/tree/trunk/patterns), however, they are not registered with the corresponding template parts which means that they are not available in the header/footer layout pattern chooser when using the UI for replacing the content of the template part. See GIF below for what I mean:

![CleanShot 2022-10-28 at 06 48 41](https://user-images.githubusercontent.com/1429108/198570470-801bee1d-7dae-4f7f-a06c-b152ea2e75a1.gif)

## Fix:

The cause is that the patterns are not registering contextually with the block type (in this case the header or footer template parts). For a header pattern, all you need to add is this to the pattern comment block:

```
* Block Types: core/template-part/header
```

With the above, the pattern will appear in the pattern chooser for the header template part:

<img width="1392" alt="CleanShot 2022-10-28 at 07 00 52@2x" src="https://user-images.githubusercontent.com/1429108/198572099-cb44f8c1-30dd-4c51-b9de-7617767f4977.png">

You can use `core/template-part/footer` for footer patterns.

I've given this a high priority because this is an important discoverability improvement (at least the first iteration of that).

**Comment by devnechi** [comment]
Hello Hi,
I would like to work on this issue. I  am new in the world of contribution not to git and I believe I can help with this.
