### ISSUE TITLE
Mini Cart Button doesn't inherit style from theme

### ISSUE THREAD

**Issue by gigitux** [woocommerce/woocommerce-gutenberg-products-block#7522]
## Is your feature request related to a problem? Please describe.
The Mini Cart Button doesn't inherit style from the theme. There is a similar issue for Cart & Checkout blocks (#7081). It is important to keep consistent with Cart & Checkout blocks. We should start to work on this issue when the Rubik team will start to work on #7081.

![image](https://user-images.githubusercontent.com/4463174/198632805-2dde3825-cf29-489d-84d1-f35c89bef681.png)

**Comment by Aljullu** [comment]
I think this was solved in https://github.com/woocommerce/woocommerce-blocks/pull/8478. @gigitux should we close this issue?

**Comment by gigitux** [comment]
Yep! I will close this issue! 💪
