### ISSUE TITLE
`WooCommerce Essential Header | Light` pattern doesn't inherit the styles from the theme

### ISSUE THREAD

**Issue by gigitux** [woocommerce/woocommerce-gutenberg-products-block#7523]
## Describe the bug

`WooCommerce Essential Header | Light` pattern doesn't inherit the global styles.

1. Enable TT3 theme.
2. Go to Appearance > Site Editor
3. Use the `Aubergine` style variation
4. Replace the header with `WooCommerce Essential Header | Light`
5. Check that the text is black and doesn't look well with the style variation.

## Expected behavior

The pattern should inherit the styles from the theme.

## Screenshots

![Screen Capture on 2022-10-28 at 11-19-57](https://user-images.githubusercontent.com/4463174/198552558-05d72e86-f068-4511-a09d-3c3a2276a738.gif)

We should either:

1) Not define a font color and inherit it from the parent elements.
2) Define a font color and background color, so we can ensure there is enough contrast between the text and the background.

**Comment by Aljullu** [comment]
Oh, it looks like there was already an issue in WC core repo: https://github.com/woocommerce/woocommerce/issues/35248 and there is an open PR fixing it: https://github.com/woocommerce/woocommerce-blocks/pull/7524.

**Comment by gigitux** [comment]
Oh, great! I'm closing this issue as a duplicate of #7524.
