### ISSUE TITLE
Woocommerce blocks change text field and add new field

### ISSUE THREAD

**Issue by yamenvip** [woocommerce/woocommerce-gutenberg-products-block#7529]
Hi guys,

What is the best way to change text fields and add new fields in checkout page ?
I want to make sure new fields link to my invoice. in case of update "Plugin" the custom works stay.

Thanks you!

**Comment by wavvves** [comment]
Hi @yamenvip, thanks for reaching out. To add new custom fields to checkout, try out [Checkout Field Editor](https://woocommerce.com/products/woocommerce-checkout-field-editor/). If that one does not fill your needs, there are a few more unsupported alternatives in the plugin directory you might wanna try.

**Comment by yamenvip** [comment]
Thank you too, I think "Checkout Field Editor" not support it yet with woocommerce blocks plugin, Can we have a good solution? where do I need to start ?

**Comment by senadir** [comment]
We're working on adding better support for managing custom fields in Checkout block, you can follow this thread https://github.com/woocommerce/woocommerce-blocks/discussions/5493

For now, there is no easy way to add fields unless you do it pragmatically.
