### ISSUE TITLE
Use external dependencies in wp-admin

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#753]
From https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/750#pullrequestreview-264016895:

> Looking at the `vendors.js` compiled code, I still see things like `lodash` dependency. Only 1 request for `lodash.js` is made, but the dependency is also shipped in vendors.
> 
> `externals: [ lodash: 'lodash' ],` in the webpack config should remove it from vendors and build the blocks js to look for lodash on the window.

**Comment by Aljullu** [comment]
@psealock I'm closing this issue since after taking a closer look, I think `lodash` and other shared dependencies are not included in `vendors.js`.

Feel free to reopen this issue if there is something we missed.

**Comment by psealock** [comment]
Yup, cool thanks confirmed using webpack bundle analyzer.

```
npx webpack --profile --json > wc-admin-stats.json
npx webpack-bundle-analyzer wc-admin-stats.json
```
