### ISSUE TITLE
Update the workflow to include the automation for updating the due date

### ISSUE THREAD

**Issue by tarunvijwani** [woocommerce/woocommerce-gutenberg-products-block#7563]
This ticket is a subticket for [#6986](https://github.com/woocommerce/woocommerce-blocks/issues/6986).

In #7560 we are implementing an automation that updates due of the milestone after the release. 

Once #7560 is completed we need to update the [wordpress-deploy.yml](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/.github/workflows/wordpress-deploy.yml) workflow to include the new automation.

## Expected behaviour

Once this request is resolved, the due date of milestone of the shipped version will be updated automatically after the release in WC Blocks.

**Comment by tarunvijwani** [comment]
On hold. Waiting for https://github.com/woocommerce/automations/pull/56 to be merged.

**Comment by mikejolley** [comment]
Closing due to pca54o-6Dz-p2
