### ISSUE TITLE
Add tooltip to the edit icon in the Block toolbar

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce-gutenberg-products-block#76]
In a recent test, getting back to the block settings via the pencil icon was not obvious. The user repeatedly checked the [ellipsis menu](https://cloudup.com/c-JQ9u4hEXo), though. Should we add a text link there as well? 

I'm conflicted on this. Once you've _learned_ the pencil icon it makes sense and you're unlikely to forget. And I'm not a big fan of having lots of different paths to the same destination. But this would make the first time experience better for some folks.

cc @kellychoffman @josemarques

**Comment by josemarques** [comment]
The pencil icon is being used in standard gutenblocks to edit:

![screen shot 2018-03-20 at 20 13 51](https://user-images.githubusercontent.com/57050/37680347-88e8eba2-2c7b-11e8-95bb-0d9444ecc845.png)

I think we should keep in insync with the default experience. But it's worth mentioning to a wider audience as a Gutenberg issue.

**Comment by kellychoffman** [comment]
Wondering if we could have the tooltip show by default the first time you visit? That way its still consistent with the rest of Gberg.

**Comment by jameskoster** [comment]
We don't even have a tooltip currently, so adding that would be a good start I think.

Revealing it after the first time the user clicks the "done" button as guidance back in to the scope settings sounds like a good idea to me.

**Comment by jameskoster** [comment]
On review, I think just adding the tooltip will be adequate. Once we've added https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/75 that will hopefully be enough guidance back in to the settings.

**Comment by ryelle** [comment]
A tooltip is added to the edit button automatically now, so this can be closed.
