### ISSUE TITLE
JavaScript errors when using a plugin that minifies JS files

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#762]
Reported several times in the support forums:

- https://wordpress.org/support/topic/javascript-errors-42/
- https://wordpress.org/support/topic/error-js-and-fast-velocity-minify/
- https://wordpress.org/support/topic/update-website-sliders-javascript-referenceerror-_-is-not-defined/

**To Reproduce**

1. Install WooCommerce Blocks.
2. Install Autoptimize.
3. Create a post with a _Product Categories List_ block.
4. View the post in the frontend and notice there are JS errors in the console.

**Comment by mikejolley** [comment]
https://github.com/futtta/autoptimize/issues/263#issuecomment-514554041

This is out of our hands afaik. Adding an exclusion rule for `lodash` is a workaround.
