### ISSUE TITLE
Product Query: [FSE] “Inherit query from template” option should only be available inside FSE templates

### ISSUE THREAD

**Issue by sunyatasattva** [woocommerce/woocommerce-gutenberg-products-block#7620]
https://github.com/woocommerce/woocommerce-blocks/pull/7382 introduces the option to inherit the global query. This option only makes sense within the context of FSE templates. The block should detect whether we are within FSE templates and only then allow the toggle to be displayed in the inspector controls.

**Comment by imanish003** [comment]
Hi @gigitux, based on the task description, it seems that this issue is also linked to the custom "Inherit query from template" feature. Can you please confirm whether this is the case? If it is, I believe we can close this issue.

**Comment by gigitux** [comment]
Yes, let's close this PR!

**Comment by imanish003** [comment]
Sounds good! Thanks, Luigi 🙌🏻

Just for reference for anyone reading the comment in future, we've decided not to implement a custom "inherit query from template." As a result, I'm closing this issue. However, we can always reopen it in the future if we decide to proceed with implementing the custom "inherit query from template". You can find related issues under Epic #6793. 🔍👀

**Comment by imanish003** [comment]
Sounds good! Thanks, Luigi 🙌🏻

Just for reference for anyone reading the comment in future, we've decided not to implement a custom "inherit query from template." As a result, I'm closing this issue. However, we can always reopen it in the future if we decide to proceed with implementing the custom "inherit query from template". You can find related issues under Epic woocommerce/woocommerce#42616. 🔍👀
