### ISSUE TITLE
Product Query [3]: Implement first set of patterns specific to the Product Query block

### ISSUE THREAD

**Issue by sunyatasattva** [woocommerce/woocommerce-gutenberg-products-block#7624]
A first set of patterns provided by design should be implemented as only available within the Product Query block. See https://github.com/WordPress/gutenberg/pull/44197 on how this is possible.

CC @vivialice to provide the patterns.

**Comment by danieldudzic** [comment]
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/7778
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/7779
- [x] https://github.com/woocommerce/woocommerce-blocks/issues/7780
