### ISSUE TITLE
Product Query: [FSE] Sort order displayed incorrectly on the front-end

### ISSUE THREAD

**Issue by sunyatasattva** [woocommerce/woocommerce-gutenberg-products-block#7626]
> ⚠️ Warning
> In order to reproduce this bug, https://github.com/woocommerce/woocommerce-blocks/pull/7382 is required

## Describe the bug

The sort order seems to be incorrect on the SSR block on the front-end. This can be easily seen as when a classic template block is set to “Sort by latest”, the order in which products are displayed on the front-end differs. Meanwhile, the sort order seems to coincide in the editor.

## To reproduce

1. Go to the “Product Catalog” template.
2. Add a “Product Query” block, with “Order by”: “Newest to oldest”.
3. Compare the results in the preview with the results in the front-end and the classic template.

## Screenshots

![Screenshot 2022-11-08 at 23 52 05](https://user-images.githubusercontent.com/1847066/200693232-770f3578-ba86-452c-a8b4-972ff4d4f554.png)

![Screenshot 2022-11-08 at 23 51 57](https://user-images.githubusercontent.com/1847066/200693205-b1fbd2d5-8764-4842-8c68-f9b0f0ae77de.png)

**Comment by imanish003** [comment]
Hi @gigitux, I attempted to reproduce this issue, but it isn't happening for me. 🤷🏻‍♂️ Additionally, it appears that this is within the 'Only required with custom "Inherit from template" logic' section of the Products block Epic woocommerce/woocommerce#42616. Perhaps we can close this issue for now?

<img width="786" alt="image" src="https://user-images.githubusercontent.com/16707866/233068826-5941d757-af79-4ac6-817e-50e6ba4a7aaf.png">

**Comment by kmanijak** [comment]
I could reproduce, but with the custom "Inherit from template" logic.

I added the notification at the top of the PR description, the same as in https://github.com/woocommerce/woocommerce-blocks/issues/7608. 

> Perhaps we can close this issue for now?

I think we could approach this issue the same as https://github.com/woocommerce/woocommerce-blocks/issues/7608, so I'd close it for now, and if we decide to follow the custom logic, then we can reopen.

**Comment by imanish003** [comment]
That makes sense to me. I'll close it for now. Thank you, Karol, for adding the notification at the top of the PR description. 🙌🏻
