### ISSUE TITLE
Product Query: [FSE] Block should show the correct editor preview as much as possible

### ISSUE THREAD

**Issue by sunyatasattva** [woocommerce/woocommerce-gutenberg-products-block#7630]
When the Product Query is added to a FSE template, and the switch to “Inherit the query from template” is turned on, the editor preview should resemble as closely as possible. For example, if the merchant is editing the template for a single category, products from that single category should be taken.

There are, obviously, limitations: when inside a generic “Products by Category” template, the block can't know which category to display, in this case we display the first category available for the time being.

Maybe in the future we'll display placeholders directly in this case? cc @vivialice @nerrad

**Comment by imanish003** [comment]
For now, we've decided not to implement a custom "inherit query from template." As a result, I'm closing this issue. However, we can always reopen it in the future if we decide to proceed with implementing the custom "inherit query from template". You can find related issues under Epic woocommerce/woocommerce#42616. 🔍👀
<img width="781" alt="image" src="https://user-images.githubusercontent.com/16707866/233030866-8a102f98-179f-4e1f-84cb-15129b4f3e1b.png">
