### ISSUE TITLE
Product Query: [Atomic Block] Convert Tag List Block

### ISSUE THREAD

**Issue by danielwrobert** [woocommerce/woocommerce-gutenberg-products-block#7634]
Refactor the Tag List block to support the new Product Query block.

Requirements:

- Must be client-side rendered in the editor.
- Must be server-side rendered (with hydration support) on the frontend.
- The block should be kept independent from the Query Loop block for use with future blocks - see the Single Product block as an example.

**Comment by Aljullu** [comment]
I'm going to close this issue based on this: https://github.com/woocommerce/woocommerce-blocks/pull/7802#issuecomment-1365969889.
