### ISSUE TITLE
Experiment with proposed fix to `useForcedLayout`

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#7637]
In pca54o-4GY-p2#comment-4658 Jarda proposed a refactor to `useForcedLayout` that would eliminate the need for complex state management and would just batch things using pure JS.

This is a simplified version of that code, keep note that `useForcedLayout` should still take into account existing templates and block placement.

```js
function useForcedLayout( clientId ) {
  const registry = useRegistry();
  useEffect( () => {
    const unsub = registry.subscribe( () => {
      const innerBlocks = registry.select( 'core/block-editor' ).getBlocks( clientId );
      const missingBlocks = getMissingBlocks( innerBlocks );
      for ( const block of missingBlocks ) {
        registry.dispatch( 'core/block-editor' ).appendBlock( block );
      }
    } );
    return () => unsub();
  }, [ clientId, registry ] );
}
```

**Comment by alexflorisca** [comment]
This was addressed in https://github.com/woocommerce/woocommerce-blocks/pull/7879
