### ISSUE TITLE
Move `StoreSnackbarNoticesContainer` to `@woocommerce/blocks-checkout` package and add tests

### ISSUE THREAD

**Issue by opr** [woocommerce/woocommerce-gutenberg-products-block#7638]
#7558 moved the `StoreNoticesContainer` to the `@woocommerce/blocks-checkout` package. We should also move `StoreSnackbarNoticesContainer` and add tests for it.

Be sure to update files where this component is imported.

**Comment by ralucaStan** [comment]
@opr  should we close this ticket because the snackbars can be triggered from anywhere?

**Comment by opr** [comment]
Yes, good point.
