### ISSUE TITLE
Product Query [3]: [FSE] Product Query block should respect catalog visibility options

### ISSUE THREAD

**Issue by sunyatasattva** [woocommerce/woocommerce-gutenberg-products-block#7645]
Products can be marked with different visibility options within the admin dashboard:

<img width="288" alt="CleanShot 2022-11-09 at 10 34 13@2x" src="https://user-images.githubusercontent.com/1847066/200911689-d588b31a-0e76-4878-b378-17ef30cacad0.png">

<img width="234" alt="CleanShot 2022-11-09 at 11 28 27@2x" src="https://user-images.githubusercontent.com/1847066/200911554-770fe89c-ff8b-4562-bab6-7bc8a025545f.png">

Currently, the Product Query block doesn't respect this setting, and just shows every product.

![image](https://user-images.githubusercontent.com/1847066/200911662-b40b04d5-9d4d-41d6-a8b9-5d5775b0111d.png)

By default, the Product Query block should respect the visibility options in both FSE templates and other editor context. That means that if a product is set to be “Hidden”, it should not show up even in Product Query blocks used in Posts and Pages. Eventually (issue link TBD) we'll add an option to override this within the inspector, but we'll settle for this default for now.

**Comment by sunyatasattva** [comment]
This will have to be done only if/when we implement the custom “Inherit query from template” logic.

**Comment by imanish003** [comment]
I checked & found out that when a user has either the Hidden or Search results only options selected, the product won't appear in the Products block. Since we're respecting the catalog visibility option, I am going to close this issue. 
![image](https://user-images.githubusercontent.com/16707866/232751012-73749a83-a278-416e-98b0-16cf8358060a.png)
