### ISSUE TITLE
Third party blocks should be insertable in Cart/Checkout without defining it in the parent field.

### ISSUE THREAD

**Issue by Marin-Matosevic** [woocommerce/woocommerce-gutenberg-products-block#7661]
Not sure if it exits (I couldn't find it), but it would be really helpful to have an allowed-blocks filter for Cart and Checkout blocks.

I have a custom cart-related block that can be included anywhere on the site, but if I want to enable it in the Cart block, I must define the parent property in block.json to include a list of areas where my block will be available.
If a block has defined parent property, then it can't be a standalone block in the sidebar, footer, or anywhere else for that matter.

Am I missing out on something?

My workaround was to have two identical blocks with different names, one with parent property for woo Cart and Checkout, the other without parent property...

It would be much easier to simply hook into the filter and add a custom block to allowed blocks defined in "woocommerce/packages/woocommerce-blocks/assets/js/blocks/cart-checkout-shared/editor-utils.ts"

**Comment by senadir** [comment]
Thank you for the report, it makes sense that a block should be able to work inside and outside, we will look into making `coreBlockTypes` filterable or adding a new array as well alongside core one.
