### ISSUE TITLE
The ERROR and FAIL payment status values are not accurate

### ISSUE THREAD

**Issue by alexflorisca** [woocommerce/woocommerce-gutenberg-products-block#7667]
## Describe the bug
While working on #7666, I discovered the payment status actually changes to `ERROR` and `FAIL` based on the response from the observers that run on the `onPaymentProcessing` event, rather than when a payment has actually errored or failed. 

A bit of background...

During the checkout flow, we emit an event called `PAYMENT_PROCESSING`, which a third party payment plugin can listen to and perform some actions. This is executed after the checkout has been validated and there are not errors. A payment plugin can use this event to, for example, create a payment intent. Stripe does this. It creates a reference object to indicate a payment intent, and returns a `SUCCESS` or `ERROR` based on the outcome of this. This isn't the actual payment though. This is made later, through a fetch call to the store api (payment is done server side). We set the payment status based on this response from the event handler. Which doesn't reflect the status of the actual payment, and is misleading. For example, the payment intent can be successful (which it is even for bad cards), so we set the payment status to `SUCCESS`. We then call the store api and make the actual payment, this comes back declined with an error. The user will see the error, but the payment status is still `SUCCESS`. Once the checkout is idle, the payment status gets set to `PRISTINE`. There is no logic to set the payment status for `FAILED`, which it should be in this case.

## To reproduce

1. Comment out [this line ](https://github.com/woocommerce/woocommerce-blocks/blob/0295a9995c0d2eb93502e423a402ce95d63dac2d/assets/js/base/context/providers/cart-checkout/checkout-processor.js#L193)
2. Checkout with a bad card (for example: `4000000000000002`) with redux dev tools open
3. Looks at the value of the `status` property in the payment store

## Expected behavior

I would expect the payment status to be set to `FAILED` when a payment fails.

**Comment by ralucaStan** [comment]
pdFofs-EM-p2
