### ISSUE TITLE
Blocks can't be extended with block filters

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#769]
I created an example extension on top of WooCommerce Blocks with the goal to add some attributes using block filters (https://developer.wordpress.org/block-editor/developers/filters/block-filters/), but it doesn't seem to work.

### Steps to reproduce

1. Clone and build this repo in your plugins folder:
```
git clone git@github.com:Aljullu/woocommerce-blocks-extension.git
git checkout showcase/attributes-bug
npm install && npm start
```
2. Enable the plugin `WooCommerce Blocks Extension`.
3. Create a post and add a paragraph and a WooCommerce Block (for example, _Featured Product_).
4. Notice they have a new _Advanced_ setting: _Remove lorem-ipsum class_.
5. First issue: Notice it's disabled by default in the _Featured Product_ block even though its default value is `true`.
6. Enable the toggle for both blocks and reload the page.
7. Second issue: Notice the new value was not persisted for _Featured Product_ block, while it was for the paragraph block.
8. Disable the toggle for both blocks and preview the post.
9. Thrid issue: Notice only the paragraph gets a `lorem-ipsum` class, while that doesn't work for the _Featured Product_ block.

**Comment by nerrad** [comment]
This issue has been open for a while, since a lot has changed since it's original creation I'm going to close this, if this is something that surfaces again for some needed use-case we can create a new one.
