### ISSUE TITLE
Re-add best seller/top rated scopes

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce-gutenberg-products-block#77]
We removed these scopes as options for two reasons;

* Few people use them
* There was a conflict with ordering - essentially there would have been two different ways to display top rated / best sellers. Either by displaying all products ordered by rating, or selecting the "top rated" filter.

However, I thought about a potential solution which I'd like to see us try. 

* Add top rated / best sellers back in the "filter" scope - https://cloudup.com/cINeAyzrkdA
* If either is selected then display "all products" ordered accordingly - https://cloudup.com/cDNjR30nOze

This way we provide a shortcut to display those scopes without simultaneously providing two separate paths.

**Comment by claudiulodro** [comment]
Before I (re)implement this, I have a UI concern. 

Selecting "Best sellers" will mark "All products" as the selected scope. My concern is this will confuse the user as they will keep trying to select "Best sellers" and think it's a bug or something that "All products" is always the selected scope. Thoughts?

<img width="395" alt="screen shot 2018-04-03 at 10 10 44 am" src="https://user-images.githubusercontent.com/7317227/38264257-4bb75d20-3727-11e8-9939-836db26b7267.png">

**Comment by jameskoster** [comment]
@claudiulodro Ooof, good point.

OK, here's an idea; perhaps the "Best Sellers" and "Best Rated" scopes are different to "All Products" ordered by rating / sales in that they will _only display products that have sold or have been rated_.

That way we can re-introduce the best sellers and best rated as independent scopes. I think that makes sense conceptually as well because these two scopes are supposed to be filtered - you wouldn't expect to see products without ratings when you're filtering by "Best Rated".

I know that's pretty much what we had to begin with. Sorry for flip-flopping 🙃
