### ISSUE TITLE
Wc-blocks.js

### ISSUE THREAD

**Issue by marijang** [woocommerce/woocommerce-gutenberg-products-block#7716]
Hey i have problem with wc-blocks.js

Here is link

https://github.com/infinum/eightshift-frontend-libs/issues/684

Can you help with that.

TypeError: Cannot read properties of undefined (reading 'startsWith') at e.getAttributesWithDefaults (http://dev.cop.com/wp-content/plugins/woocommerce/packages/woocommerce-blocks/build/wc-blocks.js?ver=edc8c61c9712604dbdb967565c8043d6:1:5091) at e.render (http://dev.cop.com/wp-content/plugins/woocommerce/packages/woocommerce-blocks/build/wc-blocks.js?ver=edc8c61c9712604dbdb967565c8043d6:1:5388) at finishClassComponent (http://dev.cop.com/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:17515:33) at updateClassComponent (http://dev.cop.com/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:17465:26) at beginWork (http://dev.cop.com/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:19103:18) at HTMLUnknownElement.callCallback (http://dev.cop.com/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:3942:16) at Object.invokeGuardedCallbackDev (http://dev.cop.com/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:3991:18) at invokeGuardedCallback (http://dev.cop.com/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:4053:33) at beginWork$1 (http://dev.cop.com/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:23994:9) at performUnitOfWork (http://dev.cop.com/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:22806:14)

**Comment by tarunvijwani** [comment]
Hi @marijang! Thank you for reporting it. To help you further, I have some follow-up questions. I'd appreciate it if you can address them:

1. Which WordPress and WooCommerce version you're using? Have you tried updating the versions?
2. Can you please share the theme file link?
3. Can you share the WooCommerce system report? You can find it under WooCommerce -> Status -> System Status
4. Have you tried installing WooCommerce-Blocks plugin and check if the error still exist?

Looking forward to hearing back from you.

**Comment by marijang** [comment]
1. Wordpress 6.1.1
2. Theme link https://eightshift.com/docs/theme/  --but i can send you mine or we can arrange team viewer
3. i can share you
4. I tried but no effect

I found the problem in code wc-blocks.js ... and i change to:

`        const h = Object(f.createHigherOrderComponent)(t => {
            class e extends c.Component {
                constructor() {

                    super(...arguments), d()(this, "mounted", !1)

                }
                componentDidMount() {
                    const {
                        block: t,
                        setAttributes: e
                    } = this.props;


                    //console.log(this.props,'props');
                    let name;
                    if (t.name) {
                        name = t.name;
                    } else {
                        name = this.props.name;
                    }

                    name.startsWith("woocommerce/") && e(this.getAttributesWithDefaults());


                }
                componentDidUpdate() {
                    if (this.props.block.name) {
                        this.props.block.name.startsWith("woocommerce/") && !this.mounted && (this.mounted = !0)
                    } else {
                        this.props.name.startsWith("woocommerce/") && !this.mounted && (this.mounted = !0)
                    }
                }
                getAttributesWithDefaults() {
                    if (this.props.block.name) {
                        const t = Object(r.getBlockType)(this.props.block.name);
                        let e = this.props.attributes;
                        return !this.mounted && this.props.block.name.startsWith("woocommerce/") && void 0 !== t.attributes && void 0 !== t.defaults && (e = Object.assign({}, this.props.attributes || {}), Object.keys(t.attributes).map(o => (void 0 === e[o] && void 0 !== t.defaults[o] && (e[o] = t.defaults[o]), o))), e
                    } else {
                        const t = Object(r.getBlockType)(this.props.name);

                        let e = this.props.attributes;
                        return !this.mounted && this.props.name.startsWith("woocommerce/") && void 0 !== t.attributes && void 0 !== t.defaults && (e = Object.assign({}, this.props.attributes || {}), Object.keys(t.attributes).map(o => (void 0 === e[o] && void 0 !== t.defaults[o] && (e[o] = t.defaults[o]), o))), e

                    }
                    return false;
                }`

It seems that i do not get value for this.props.block.name but i have this.props.name value for block name

**Comment by tarunvijwani** [comment]
I’ve tried reproducing this bug using the following steps:

1. Activated multiple themes like Storefront, twenty nineteen, twenty twenty one etc. 
2. Tried switching theme only with WooCommerce plugin. 
3. Installed WooCommerce Blocks plugin and tried switching themes.


I’m unable to successfully reproduce the bug. This doesn’t mean there isn’t something happening, but it appears to be specific to your environment or theme. I'd suggest reaching out the theme developers for the solution. Until we can reproduce this, there isn’t anything we can do to fix. For that reason, I’m going to close this issue, but please do leave a comment if you have additional information that you think will help us reproduce the issue. We will re-open if we’re able to replicate.

Thanks again for your report!
