### ISSUE TITLE
a step by step guide? video?

### ISSUE THREAD

**Issue by lalindeluis** [woocommerce/woocommerce-gutenberg-products-block#7718]
Hi guys, I am bit confused. Right after I install and activate the plug-in  what I am supposed to do? how do see this working example?

**Comment by tarunvijwani** [comment]
Hi @lalindeluis!

You can follow our [WooCommerce Blocks documentation](https://woocommerce.com/document/woocommerce-blocks/) guide to know more about the blocks.  

I also found a [YouTube video](https://www.youtube.com/watch?v=3nqDQVw_tv4&ab_channel=SundayUkafia) that might be helpful. 

Let me know if you have any questions!

**Comment by ralucaStan** [comment]
I'll close as there was no response from the author.
