### ISSUE TITLE
Rate-Limiting blocking edits to admin page blocks 

### ISSUE THREAD

**Issue by tobinfekkes** [woocommerce/woocommerce-gutenberg-products-block#7738]
## Describe the bug

Due to daily abuse of our StoreApi checkout endpoint, we were thrilled to see the new rate-limiting feature released in the Woo Blocks feature plugin. We'd already tried many other various ways of preventing hundreds of failed orders via credit card fraud attempts. The StoreApi endpoint makes abuse trivial, so rate-limiting is a welcome, and necessary, feature.

However, because the same blocks and endpoints are used in the admin editor, we're now also getting blocked from saving our updates to pages. Screenshot below. If you (or a team on the same corporate static IP address) make too many changes in a small window, editing pages/posts with blocks becomes unusable.

## To reproduce

1. Go to any admin page and create a product-related block or blocks.
2. Make many changes to the block(s) and keep saving them.
3. Shortly, you will get a notice that you've been rate-limited.

## Expected behavior

Any logged-in administrator should be excluded from the rate limit. Since both IP and UserID are known, it should be pretty straightforward to exclude any UserIDs with the role of `Administrator`.

## Screenshots

<img width="896" alt="image" src="https://user-images.githubusercontent.com/6226162/203656606-e2ba6c42-b16d-4e7e-9007-7d2d59dc1cdb.png">

### WordPress (please complete the following information):

-   WordPress version: 6.1.1
-   Gutenberg version: 14.5.0
-   WooCommerce version: 7.1
-   WooCommerce Blocks version: 8.9.1
-   Site language: English

### Desktop (please complete the following information):

-   OS: Mac and Windows
-   Browser Brave
-   Version v1.45.131, Chromium 107

**Comment by mikejolley** [comment]
Rate limits are tied to your user ID before IP Address. Are many users sharing the same account?

**Comment by tobinfekkes** [comment]
@mikejolley They are not. This instance was one individual administrator user account.

Simply loading an page in `wp-admin` that has many blocks on it gets the same response:

<img width="660" alt="image" src="https://user-images.githubusercontent.com/6226162/203867017-833a0c62-a44d-4b0a-b963-a599e4fd95ad.png">

And that is on my own private residential IP address and I'm the only one logged in.

It appears that just making the requests to load all the product blocks is triggering the rate limits.

<img width="600" alt="image" src="https://user-images.githubusercontent.com/6226162/203867351-c8c88398-b76b-4712-a008-7c2d1708b772.png">

I do have the threshold set pretty low (5 requests per 60 seconds) because the fraud attempts were getting so bad. But regardless of that, it seems a logged-in administrator should be exempt from those rates by default.

**Comment by wavvves** [comment]
@tobinfekkes This makes sense, and editing should not be Rate Limited.

While we don't address this, you might wanna try and put the Rate Limiting options filter inside [is_admin()](https://developer.wordpress.org/reference/functions/is_admin/) (and also check for administrator capability using [current_user_can()](https://developer.wordpress.org/reference/functions/current_user_can/)) so that it would only be enabled if those conditions don't apply.

In the meantime, we can look into integrating this from our side since, as I said, makes sense to exclude that from Rate Limiting.

**Comment by tobinfekkes** [comment]
@wavvves Thank you for the response! Yes, great suggestions, that is a great fix for me. I can add those conditions to our setup.

My primary thought is about when the rate-limiting feature is included in core. Then, there will be a huge increase in users this will affect as more people move to the checkout block from the checkout shortcode. Disabling admins from the rate-limiting seems like a good default to have, rather than a default to block everyone. 

The fraud abuse on ours and other checkout endpoints are not (and will never come) from admins, and not even users with roles. It's bots. It's one API request to the add-to-cart endpoint, then one request to the checkout endpoint. The checkout block is great, but it's trivial to abuse.

**Comment by tarhi-saad** [comment]
Thank you, @tobinfekkes, for reporting this bug! I was able to reproduce it! It's indeed not a good developer experience. I'll add the high-priority label to this issue and move it to our backlog to fix it as soon as possible! 🙌

**Comment by ralucaStan** [comment]
Internal discussion p1669818006878869-slack-C8X6Q7XQU
