### ISSUE TITLE
WooCommerce Blocks load MUCH slower than classic WooCommerce Widgets

### ISSUE THREAD

**Issue by apenchev** [woocommerce/woocommerce-gutenberg-products-block#7759]
## Describe the bug

The WooCommerce blocks have been a terrible experience for our store, as they avoid page caching and use the slow WordPress REST API – each REST API call takes around 1.8s; hacking WP REST Cache to work with WooCommerce was not enough to make the fetch response time reasonable. The classic WooCommerce widgets, on the other side, are way faster – they don’t rely on the REST API and work with page caching. Would love it if the blocks had an option to avoid using the REST API! That would combine the best of both worlds.

## To reproduce

1. Install WooCommerce: https://wordpress.org/plugins/woocommerce/
2. Create a Page with the following blocks: Product Categories List, Filter by Price, All Products
3. Save & Publish the Page
4. Install the Classic Widgets plugin: https://wordpress.org/plugins/classic-widgets/
5. From /wp-admin/widgets.php, add the following Widgets: Product Categories, Filter by Price
6. Create & Publish a new empty Page (that will be used as the WooCommerce's Store Page)
7. From /wp-admin/admin.php?page=wc-settings&tab=products, change the Products Page to be the page from step 6.
8. Now, compare the loading times and perceived performance of the pages from step 6. and step 2.

## Expected behavior

WooCommerce blocks should render the same way the WooCommerce Widgets do.

## Screenshots

I've added videos from our website (which uses cheap shared hosting) showcasing the big difference in loading times.

### WordPress (please complete the following information):

-   WordPress version: 6.1.1
-   Gutenberg version (if installed): not installed
-   WooCommerce version: 7.1.0
-   WooCommerce Blocks version: not installed
-   Site language: Bulgarian

### Desktop (please complete the following information):

-   OS: Windows 10
-   Browser: Edge
-   Version: 107

https://user-images.githubusercontent.com/3998720/204038162-40c91f1c-c70b-4195-94a6-59513c8d2be1.mp4

https://user-images.githubusercontent.com/3998720/204038163-1f028fb1-6303-4a5e-a3a2-22556995a564.mp4

![fetch](https://user-images.githubusercontent.com/3998720/204038165-8224b293-2158-4e7d-ab4a-ff7ac022f18d.PNG)

**Comment by sunyatasattva** [comment]
Hello @apenchev ! Thank you for the report and I'm glad you, for the most part, like the block experience.

We are working on the performance and exactly what you are mentioning by creating blocks that are server-side rendered and do not make API requests on the first page load.

We are going to have a [new “Products” block](https://github.com/woocommerce/woocommerce/issues/42616) using this approach coming out as a feature plugin-only beta in the next few weeks, and we are looking forward to any feedback of merchants such as yourself.

Please do try this new block yourself and provide your feedback at [this link](https://airtable.com/shrFX5FAqmCY6hVYI).

We are really listening and your feedback is very valuable.

For the time being, I'm closing this issue as it is something we are already working on and we have more specific issues.

**Comment by Aljullu** [comment]
Heads-up that we created this issue to track converting filter blocks to server-side rendering: woocommerce/woocommerce-blocks#7844. Not something we plan to work immediately, but noting it's in our roadmap.
