### ISSUE TITLE
Add to Cart: button product element is missing alignment settings

### ISSUE THREAD

**Issue by danieldudzic** [woocommerce/woocommerce-gutenberg-products-block#7780]
The Add to Cart button product element doesn't currently support the alignment block settings:

![Edit_Page_“All_Products”_‹_ratings_—_WordPress](https://user-images.githubusercontent.com/905781/204528611-07943745-4094-4163-aa36-0ebe7a99e216.jpg)

This is necessary for building Product Query patterns like the following:
![🔎_Product_Query_Block_–_Figma](https://user-images.githubusercontent.com/905781/204535125-25ffd6bc-8de5-4915-b2ac-1a4d2a2841f5.jpg)

**Comment by ribaricplusplus** [comment]
I was planning to work on this. How do you even manage to select the "Add to cart button" block? I can't select it in the editor if I try rendering something like the "All products" block.
