### ISSUE TITLE
Show a notice if a user has enabled local pickup and has legacy local pickup options as well.

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#7788]
We want to show a dismissible notice if a merchant has both legacy local pickup options and enabled the new local pickup
![image](https://user-images.githubusercontent.com/6165348/204820226-46c01e56-5f16-4978-94d9-e2f71fcf4d03.png)

Condition to show the notice:
- Notice wasn't already dismissed.
- User has active (enabled) legacy local pickup options in the shipping zones table.
- User enabled the new local pickup.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce-blocks/pull/7842
