### ISSUE TITLE
Town/City & Subdistrict using plain text?

### ISSUE THREAD

**Issue by InstrukturRGI** [woocommerce/woocommerce-gutenberg-products-block#7801]
## What do you think is missing from the Cart & Checkout blocks?

I noticed that the input for "Town / City" and "Subdistrict (optional)" is presented as plain text instead of the usual select-dropdown. Won't this bring a lot of problem? I use a plugin called "Woongkir" from the official repo, and I could not get my shipping cost estimation unless I typed the exact name of my city.

official name of my city is "Kabupaten Surabaya" which basically means 'District Surabaya', but we locals will most likely just type in 'Surabaya' and get confused why the store can't ship to my place.

**Comment by senadir** [comment]
This is a current limitation we have, we might look into making it a select right now once we figure out the data fetching and storage mechanism, but as of right now, WooCommerce core doesn't support predefined list for City field, you would need to build a custom JS field for that.

**Comment by InstrukturRGI** [comment]
Thank you for the answer. I guess I will stop using this plugin for now.
Good luck developing the plugin!
