### ISSUE TITLE
payment method PayPal is missing

### ISSUE THREAD

**Issue by ghost** [woocommerce/woocommerce-gutenberg-products-block#7820]
## What do you like about the Cart & Checkout blocks?
I like the design and the possibility to customize mine.
## What do you think is missing from the Cart & Checkout blocks?
It is missing the function in the checkout that the payment method PayPal can be selected.

**Comment by tarhi-saad** [comment]
Hello @R7JANV1 👋 

Thanks for taking the time to make us aware that [PayPlus Payment Gateway](https://wordpress.org/plugins/payplus-payment-gateway/) isn't working with the Checkout and Cart blocks. As a merchant, the best course of action right now if you are using a plugin that isn't working with the Cart and Checkout Blocks is to notify the developer of the extension and ask if they can add support.

Currently, it's up to extension developers to add support for the new checkout flow offered via the Cart and Checkout Blocks. We have some [documentation for Third-party developers](https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs#third-party-developers) and some [Developer Resources](https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs#developer-resources) available to help with their integration efforts.

You can keep on top of the [status of the Cart & Checkout Blocks in this documentation](https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/).
