### ISSUE TITLE
Make place order button editable

### ISSUE THREAD

**Issue by ghost** [woocommerce/woocommerce-gutenberg-products-block#7822]
## What do you like about the Cart & Checkout blocks?
I like the ease of use very much.
## What do you think is missing from the Cart & Checkout blocks?
The possibility to change the text in the "place order" button.
Because in Germany there is a clear rule for the button that allows the purchase contract to come into effect. The button should be able to be changed to Buy now.

**Comment by nielslange** [comment]
Hello @R7JANV1 👋

Thanks for taking the time to report this issue. We recently worked on the following related issues:

- https://github.com/woocommerce/woocommerce-blocks/pull/7817
- https://github.com/woocommerce/woocommerce-blocks/pull/7733

Making the place order button editable, fits perfect to the other improvements. I'll look into this the next days.

**Comment by nielslange** [comment]
Hi @R7JANV1, 

I'll close this issue in benefit of #7015, which covers the same request but contains a bit more context.

**Comment by ghost** [comment]
Hi @nielslange,
I have seen that the PR has been merged, when will the function be available for my stable wordpress instance?
best regards.

**Comment by nielslange** [comment]
> Hi @nielslange, I have seen that the PR has been merged, when will the function be available for my stable wordpress instance? best regards.

@R7JANV1 This change had been shipped with [WooCommerce Blocks 9.2.0](https://developer.woocommerce.com/2022/12/20/woocommerce-blocks-9-2-0-release-notes/) on December 20, 2022, and we expect to ship this change with WooCommerce 7.4 on February 14, 2023. I suggest keeping an eye on https://developer.woocommerce.com/category/release-post/, to see when WooCommerce 7.4 had been shipped.

**Comment by ghost** [comment]
> > Hi @nielslange, I have seen that the PR has been merged, when will the function be available for my stable wordpress instance? best regards.
> 
> @R7JANV1 This change had been shipped with [WooCommerce Blocks 9.2.0](https://developer.woocommerce.com/2022/12/20/woocommerce-blocks-9-2-0-release-notes/) on December 20, 2022, and we expect to ship this change with WooCommerce 7.4 on February 14, 2023. I suggest keeping an eye on https://developer.woocommerce.com/category/release-post/, to see when WooCommerce 7.4 had been shipped.

Thank you!

**Comment by ghost** [comment]
Unfortunately, I cannot find the function to edit the button, despite the update to Wordpress 6.2. and the latest version of WooCommerce Blocks

**Comment by nielslange** [comment]
@R7JANV1 You should be able to click directly into the button to edit it:

![Screen Capture on 2023-03-31 at 14-48-28](https://user-images.githubusercontent.com/3323310/229058226-a608f0fc-9541-410b-b607-b109b7d1b277.gif)

I hope this helps!

**Comment by ghost** [comment]
Sorry, I thought there would be a mask in the sidebar with options to choose what the button should be called.  So everything works as it should!  Thank you for this feature!

**Comment by nielslange** [comment]
No worries, @R7JANV1. And I'm glad to hear that you're able to adjust the button texts now. 🙌
