### ISSUE TITLE
Filter blocks: should display the "Reset" button in the editor

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#7826]
## Describe the bug

In the frontend, when the shopper has applied some filters using the filter blocks, a "Reset" button appears. However, that button is not visible in the editor, so it's confusing to set its styles without seeing it.

## To reproduce

1. Add a Products by Attribute block to a post or page and the All Products block.
2. In the frontend, filter by one of the attributes.
3. Notice the Clear All button appearing, which wasn't visible in the editor.

## Expected behavior

The Clear All button should be visible in the editor as well. We could pretend some of the options are selected to keep it consistent with the frontend, where the "Reset" button only appears if there are options selected.

## Screenshots

Editor | Frontend
--- | ---
![imatge](https://user-images.githubusercontent.com/3616980/205306829-6b70b459-a072-4d18-ad49-812b349c5d40.png) | ![imatge](https://user-images.githubusercontent.com/3616980/205306875-751567cb-1c48-4a7f-a23e-e2cb11f51541.png)

**Comment by Aljullu** [comment]
@roykho I see this was fixed for the Filter by Attribute block in #8285, but ideally it should be fixed in all Filter blocks: Filter by Price, Filter by Stock, Filter by Rating... Do you think we should reopen this issue?

**Comment by roykho** [comment]
@Aljullu - sorry it wasn't completely clear we needed to do it for all filter blocks. I will re-open.

**Comment by nielslange** [comment]
@Aljullu and @roykho Please note that this PR had already been shipped with yesterday's release. I wonder if it isn't better to keep this PR closed and create separate PRs for the other filter blocks.

**Comment by Aljullu** [comment]
@nielslange I'm a bit confused, did you mean "issue" instead of "PR"? I agree that we shouldn't reopen PRs that have already been merged (and released), but I think it's ok to reopen an issue if it reappears or we consider it hasn't been fixed completely. :thinking:

**Comment by nielslange** [comment]
> @nielslange I'm a bit confused, did you mean "issue" instead of "PR"? I agree that we shouldn't reopen PRs that have already been merged (and released), but I think it's ok to reopen an issue if it reappears or we consider it hasn't been fixed completely. 🤔

My bad, @Aljullu. I've mistaken this issue with [this merged PR](https://github.com/woocommerce/woocommerce-blocks/pull/8285). All good and sorry for the confusion.
