### ISSUE TITLE
Filter Products by Price: List view

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#784]
Implement a list view of price ranges as an alternative to the price slider.

Part of #710, possibly optional.

**Relevant Acceptance Criteria**

- [ ] The merchant can choose between displaying the filters as slider or list (block setting)
- [ ] The block presents the slider as the default option
- [ ] How to edit the price ranges that are displayed in a list (TBD)

**Other considerations**

- [ ] Decide how bands are decided or edited by the user in the block
- [ ] Implement queries. This could be simple (use same query as slider) or more optimised (group products and store those groupings for faster queries).
- [ ] Implement product counts per band shown
- [ ] Clarify with @jwold, the designs show bands followed by a text field for manual entry. These conflict. I'd suggest using bands exclusively if using list view rather than manual entry.

**Comment by jwold** [comment]
@mikejolley just to clarify, you're suggesting we remove this (screenshot below), is that correct?

<img width="500" alt="Screen Shot 2019-07-31 at 11 56 48" src="https://user-images.githubusercontent.com/3411173/62239746-5128d500-b38a-11e9-99d1-f5dcbbb9d0f2.png">

I added it to allow for flexibility on the frontend, but if that adds too much to the complexity from a development perspective I'm happy to remove it. 

It actually simplifies things a bit, which could be a good thing.

**Comment by jwold** [comment]
> How to edit the price ranges that are displayed in a list (TBD)

I also got to thinking about how we could edit the price ranges, and have a suggestion. 

![IMG_0236](https://user-images.githubusercontent.com/3411173/62241012-20966a80-b38d-11e9-9127-a26cda81d096.JPG)

And here's a video walking through the sketch: https://v.usetapes.com/S1T3nAk5vv

Note: We'd likely need inline validation to point out to the store owner when a new value they're about to add conflicts with a previous value.

cc @pmcpinto

**Comment by pmcpinto** [comment]
> I also got to thinking about how we could edit the price ranges, and have a suggestion.

I like this suggestion, but if in terms of development it may a while to finish it we should consider backlog it and move forward just with the price slider. We can always release later or consider it something for a premium feature/block.

I quickly checked some of our competitors and it's interesting to see that the offer limited options for price filtering on core:
- https://support.bigcommerce.com/s/article/Product-Filtering-Settings
- https://community.shopify.com/c/Shopify-Discussion/Filter-by-price/td-p/444442

**Comment by jwold** [comment]
> but if in terms of development it may a while to finish it we should consider backlog it and move forward just with the price slider. We can always release later or consider it something for a premium feature/block.

Good point! I'm totally fine with backlogging his and defer to @mikejolley on whether this is feasible right now or should be developed later.

**Comment by pmcpinto** [comment]
> Good point! I'm totally fine with backlogging his and defer to @mikejolley on whether this is feasible right now or should be developed later.

👍@mikejolley let us know what do you think.
