### ISSUE TITLE
Filter Products by Price: Query handling/core integration

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#785]
Implement queries to get min/max price and filter the catalog.

Part of #710

**Relevant Acceptance Criteria**

- [ ] The merchant can see the price range of all the products in his store: min: 0$ and max: most expensive product in the store
- [ ] If the filter button is hidden, in the front end the product list is updated when the user stops dragging the slider handle
- [ ] The merchant can only see this block in the block library while editing the Product Archive Page (if existing blocks can instead use this filter, this won't be required)

**Other considerations**

- [ ] Clarify with @jwold and look into how min/max price is calculated. Core currently basis it on the visible products. e.g. in a category the upper and lower prices will differ from the main store page. 
- [ ] Optimise queries for getting largest/smallest price from catalog and/or other blocks.
- @nerrad is investigating how data should be shared between this block and core and/or other blocks

**Comment by jwold** [comment]
@mikejolley great question!

> Clarify with @jwold and look into how min/max price is calculated. 

It seems like we need to decide whether we'll calculate the min/max price based on:

- **Scenario 1** - The cheapest and most expensive products in the store
- **Scenario 2** - The cheapest and most expensive products in the current category (not sure if we can do that)
- **Scenario 3** - The cheapest and most expensive products being displayed based on selected options in the filter blocks. 

So for example, if my store has:

- $10 book (3 star rating)
- $20 shirt (4 star rating)
- $50 sweatshirt (1 star rating)

In **Scenario 1**, all products are shown, so the min/max is $10/$50. 

In **Scenario 2**, if I'm on the clothing category, min/max is $20/$50.

In **Scenario 3**, if I've gone to my Filter Products by Rating block, and chose 3 star & Up, then only the book and shirt appear, and min/max is $10/20. 

Is that the clarity you were looking for? Happy to sketch this out if that's helpful! :)

cc @pmcpinto

**Comment by pmcpinto** [comment]
@mikejolley @jwold should we worry about the min price calculation, considering that the price slider is going to the 0$ as the min price by default?

**Comment by mikejolley** [comment]
@pmcpinto @jwold Scenario 3 is what core does now. That should be the goal here IMO.

**Comment by jwold** [comment]
> @mikejolley @jwold should we worry about the min price calculation, considering that the price slider is going to the 0$ as the min price by default?

In Baymard I believe there was some guidance about the benefit to increasing the minimum to your lowest price product. 

> @pmcpinto @jwold Scenario 3 is what core does now. That should be the goal here IMO.

@mikejolley  I agree with that. If it's helpful I could design it out a bit to make sure my understanding is the same as yours. Would you like me to attempt that?

**Comment by mikejolley** [comment]
@jwold Sure thing.

To clarify (if thats possible because it's hard to explain), the price slider in core shows a range with an adjusted minimum/maximum based on products being shown and/or filtered, excluding the current price filter.

So If I am viewing a category called t-shirts and filtering by the blue attribute, the min price and max price will be taken from the cheapest and most expensive blue t-shirt.

**Comment by jwold** [comment]
@mikejolley ok I've mocked it up and recorded a short video, more just to see if we're on the same page with how we imagine this working.

First, the 45 second video: https://v.usetapes.com/cfNJZk0rTW

Second, the actual sketch:

![IMG_0240](https://user-images.githubusercontent.com/3411173/62394931-9a605c80-b523-11e9-9977-7f9ea04a95e5.JPG)
