### ISSUE TITLE
woocommerce_cleanup_draft_orders scheduled action > Checkout drafts are not fired

### ISSUE THREAD

**Issue by Marc-pi** [woocommerce/woocommerce-gutenberg-products-block#7850]
## Describe the bug

Checkout draft are not deleted, despite there is a dedicated scheduled action

## To reproduce

1. Add product to cart (with woo blocks plugin activated)
2. Go to checkout
3. Fill some field
4. Do not enter credit card credentials
5. Quit the page

## Expected behavior

the woocommerce_cleanup_draft_orders scheduled action, fired once a day, should delete the order once a day
according to https://developer.woocommerce.com/2020/11/23/introducing-a-new-order-status-checkout-draft/

## Screenshots

what is strange, but should not be a real issue, is the rank_math group , seems to be a visual bug.

![image](https://user-images.githubusercontent.com/919332/205863697-11a1df1f-0a63-407f-ab61-5a93e563fcfe.png)

the order is correctly saved as draft, but was not deleted yesterday
The scheduled action was not declared as failed

![image](https://user-images.githubusercontent.com/919332/205865204-47bef8c7-a7f7-44e9-88d9-79a3ae4983ea.png)

## Environment

- WP 6.1.1
- Woocommerce 7.1.0
- Woocommercre blocks 9.0.0
- PHP 7.4.33

**Comment by alexflorisca** [comment]
Thanks for reporting this @Marc-pi. This looks like a bug in WooCommerce core, not with the checkout block, so I can move it to the WooCommerce repo. But before I do. can you confirm if this happens with the shortcode version of the Checkout?

**Comment by Marc-pi** [comment]
hello
no, it is not !
* I do use the woo FSE blocks, as stated above i do use the WooCommerce Blocks plugin
* it is not the shortcode version.
* here is a screenshot
* i do not use the shortcode version, but this last do not make use of this scheduled action, as long as i know. 
![image](https://user-images.githubusercontent.com/919332/205910980-ffe2ed13-9332-4f07-9795-919f35e2cf41.png)

**Comment by alexflorisca** [comment]
Hi @Marc-pi, my colleagues and I tested this and it seems like the cron job runs successfully and the orders are deleted. We used a fresh install of WooCommerce and WooCommerce Blocks. So my hunch is that there is conflict with another plugin - maybe the Rank Math plugin if you're seeing their name next to the cron job? I would suggest you first disable all other plugins and try it. Also if you haven't got the latest WooCommerce and WooCommerce blocks I would suggest upgrading to the latest versions.

If that doesn't solve it, we'd need to know a few more details about your setup. If you could head to WooCommerce > Status and click on Get System Report and copy the answer here, we can see what else you have installed and what versions of things your running which might help us debug this further.

**Comment by ralucaStan** [comment]
Closing this issue for the moment. @Marc-pi feel free to reopen if you are able to replicate this bug when no other extensions are activated.
