### ISSUE TITLE
Filter Blocks > Reset link not visible in Site Editor mode

### ISSUE THREAD

**Issue by Marc-pi** [woocommerce/woocommerce-gutenberg-products-block#7874]
## Describe the bug

Reset button is not visible in Site Editor, despite it is in Front
There is no option to hide it from block controls/options

## To reproduce

Add a block (ex: Filter by Attribute) and compare site editor vs front

## Expected behavior

- Align site Editor with Front
- Add an option to hide Reset button (in each Woo Block)

## Screenshots

Front
![image](https://user-images.githubusercontent.com/919332/206190284-a917ca44-e811-4077-989c-8bf70f7e2abe.png)

Site Editor
![image](https://user-images.githubusercontent.com/919332/206190819-10600168-5ac2-4b12-b526-06196b79e4e3.png)

## Environment

WP6.1.1
Woo Blocks 9.1
Gutenberg plugin 14.6.1
WC 7.1
TT2 Theme

**Comment by roykho** [comment]
Thanks for reporting. This should be fixed via https://github.com/woocommerce/woocommerce-blocks/pull/8285
