### ISSUE TITLE
Feedback on ./src/StoreApi/docs/cart.md

### ISSUE THREAD

**Issue by isaac-matchbook** [woocommerce/woocommerce-gutenberg-products-block#7878]
Under "Select Shipping Rate", it looks like the "package_id" -> "required" is set to "string" rather than a boolean "yes" or "no" value, and the description is set to "yes". I'm guessing the intention was to set the "type" to integer | string which moved everything over a column.

![Screen Shot 2022-12-07 at 1 41 23 PM](https://user-images.githubusercontent.com/78096774/206268137-fdc32ad9-7de0-4cac-ad31-b168202cd89e.png)

**Comment by mikejolley** [comment]
Thanks, I'll correct this.
