### ISSUE TITLE
Hide the arrow in dropdown if there's no more options to choose from

### ISSUE THREAD

**Issue by kmanijak** [woocommerce/woocommerce-gutenberg-products-block#7889]
## Describe the bug

When there's no more options to choose from the filter dropdown, the arrow is still visible there. We should hide the input, otherwise it feels like you can still add more options, but clicking on the control doesn't do anything.

## To reproduce

1. Add the Filter by Rating to the page (make sure you have at least one product with rating)
2. In Editor set it to "Dropdown" and "Multiple"
3. Go to frontend
4. Choose all of the available option

## Expected behavior

There's no indicator there's still something to choose from

## Actual behavior

The arrow is still there, but clicking on the control doesn't do anything.

## Screenshots

https://user-images.githubusercontent.com/3616980/206177760-73419348-0f61-4fd6-a52a-5700a5cc140a.webm

## Additional context

1. The issue may be already fixed in the newer versions of Gutenberg, but at the moment woocoomerce-blocks uses outdated version (current wordpress-components version: 14.2.0). Please check if the version has been bumped and if the bug still occurs at the moment of picking up this issue.

2. Issue can be reproduced with the Dropdown set to "single". It occurs differently: no arrow, but when clicked, there's an input available, without any option to choose.

**Comment by Lonecloud7** [comment]
can you provide a link to the page where this component is declared?

**Comment by kmanijak** [comment]
Hi @Lonecloud7 👋

Dropdown version of Filter by Rating is in progress and is available on the branch: `add/filter-by-rating-dropdown` if you want to check it out (keep in mind it's WIP and it may not be a final version).

However, the bug can be reproduced in dropdown version of Filter by Attribute block as well, in case you want to check the bug itself.
