### ISSUE TITLE
Add coupon code link instead of dropdown

### ISSUE THREAD

**Issue by ralucaStan** [woocommerce/woocommerce-gutenberg-products-block#7890]
We need to change the look and feel of the coupon code in both the Cart and Checkout blocks

We will remove the collapsed section and replace it with a link.

Design to be added to the ticket by @elizaan36

**Comment by elizaan36** [comment]
@tarunvijwani Here are details for the design update for the coupon code in Cart and Checkout blocks. As @ralucaStan mentioned, this update will remove the collapsed section and replace it with a link. The link is a better visual cue for the shopper and also creates more alignment with the WooPay checkout.

## Cart

Add coupon link opens into the form
<img width="250" alt="Screen Shot 2022-12-12 at 9 48 42 PM" src="https://user-images.githubusercontent.com/5121465/207225012-b819d82a-f2e3-4447-ac02-da294fb02286.png"> <img width="250" alt="Screen Shot 2022-12-12 at 9 49 02 PM" src="https://user-images.githubusercontent.com/5121465/207225049-1c0558d6-9300-4c98-924c-005c6925b073.png">

Coupon added / error
<img width="250" alt="Screen Shot 2022-12-12 at 9 49 31 PM" src="https://user-images.githubusercontent.com/5121465/207225084-b1bbb84b-7918-4113-89c6-84ba71553641.png"> <img width="250" alt="Screen Shot 2022-12-12 at 9 50 00 PM" src="https://user-images.githubusercontent.com/5121465/207225101-9a029b48-5909-4386-a0f1-45eb83618383.png">

## Checkout

Add coupon link
<img width="350" alt="Screen Shot 2022-12-12 at 9 58 06 PM" src="https://user-images.githubusercontent.com/5121465/207225210-68dfc930-f432-4edf-a30d-7dff7492f607.png">
Add coupon form
<img width="350" alt="Screen Shot 2022-12-12 at 9 59 05 PM" src="https://user-images.githubusercontent.com/5121465/207225254-9ddb67bb-3f2d-44c4-bd80-8b6979d949dd.png">
Coupon added
<img width="350" alt="Screen Shot 2022-12-12 at 9 59 25 PM" src="https://user-images.githubusercontent.com/5121465/207225271-3ba21625-79d0-4852-9df2-d2d8769d61e9.png">
Form field error
<img width="350" alt="Screen Shot 2022-12-12 at 9 59 42 PM" src="https://user-images.githubusercontent.com/5121465/207225503-d89a8556-7217-44c7-a140-604835323787.png">

I shared the Figma in Slack, let me know if you have any questions!

**Comment by tarunvijwani** [comment]
Before merging the PR for this issue, E2E cases must be updated for the coupons. Else, we will introduce new E2E errors.
