### ISSUE TITLE
WooCommerce setting `Hide shipping costs until an address is entered` hides Local Pickup

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#7895]
If `Hide shipping costs until an address is entered` is enabled, you can no longer see local pickup selector unless you provide a full address, defeating the purpose of Local Pickup.

**Comment by mikejolley** [comment]
Core uses this in the cart class `show_shipping` method. This is mostly used for visual elements aside from here in `get_shipping_from_cart`:

https://github.com/woocommerce/woocommerce/blob/9db2c452905ebf796a8e8b4d63db64b57e169dbe/plugins/woocommerce/includes/class-wc-cart-totals.php#L332

Shipping won't be returned from the API whilst `show_shipping` is false. 

We could short circuit and ignore the setting as a possible option.

**Comment by mikejolley** [comment]
Ideas for resolving this:

1. Short Circuit the option, so it's always `false` in the context of the cart block + store API. This does, however, leave an option that doesn't make sense.
2. ^ this but hide the setting in core if the Checkout Block is being used.
3. ^ this but hide the entire advanced shipping section in core. Many of the settings on that page conflict with the new Checkout Blocks and could potentially be moved to the block's settings and/or phased out.

To unblock the work, option 2 is probably the minimum. Hide the setting and force the value so it doesn't break core calculations.

If we did phase out the screen itself (option3) we could drastically simplify the settings UI, but some core work is needed:

![Screenshot 2022-12-09 at 13 39 01](https://user-images.githubusercontent.com/90977/206714754-dc0bfb1b-651d-411e-93de-9a3d16d0f3bb.png)

**Calculations** section 

- Shipping calculator is already a block-level setting
- "Hide shipping costs until an address is entered" is the option we want to force/phase out. Usage stats would be nice?

**Shipping destination** section

- Would work as a block-level setting, aside from "Force shipping to the customer billing address" which would need to be synced to the options table. Could still be an option presented at block level to simplify the UI.

**Debug mode** section

- Should be a PHP flag!

**Comment by pmcpinto** [comment]
The Tracks data suggests that the “Hide shipping costs until an address is entered” setting has low usage. Thomas has created a data request, but it's uncertain when we'll get more data. Therefore, I recommend moving forward with the following as a short-term solution: short-circuit the solution, keep the setting but disable it when a store has the checkout block with local pickup enabled + a message informing the user about this.
We can revisit this approach in Q3/Q4 and explore [option 3](https://github.com/woocommerce/woocommerce-blocks/issues/7895#issuecomment-1344328114).
