### ISSUE TITLE
Error notice triggered when using Elementor editor

### ISSUE THREAD

**Issue by paymentplugins** [woocommerce/woocommerce-gutenberg-products-block#7907]
## Describe the bug

When using the Elementor post editor, the `woocommerce-blocks/src/Payments/Api.php` error_log message "Payment gateway with handle \'%1$s\' has been deactivated in Cart and Checkout blocks because its dependency \'%2$s\' is not registered." is triggered.

## To reproduce

1. Install WooCommerce 7.1+ and Elementor 3.9.0
2. Navigate to the WordPress Admin > Posts > Add New
3. On the post page, click the "Edit With Elementor" button. This will trigger the error_log entry.

## Expected behavior

Editing a post using Elementor should not result in the script handles related to payments from being dequeued. 

### WordPress (please complete the following information):

-   WordPress version: 6.1.1
-   Gutenberg version (if installed): [e.g. 12.0.0]
-   WooCommerce version: 7.1.1
-   WooCommerce Blocks version: 8.7.6
-   Site language: English
-   Any other plugins installed: Elementor 3.9.0

## Additional context

This error seems to occur because Elementor is not firing the `init` action when the Elementor post editor is opened. In `woocommerce-blocks/src/AssetsController.php` the `register_assets` method is associated with the `init` action. That is where all blocks scripts are registered. 

In `woocommerce-blocks/src/Payments/Api.php`, there is the following line of code: `add_action( 'wp_print_scripts', array( $this, 'verify_payment_methods_dependencies' ), 1 );`. When the wp_print_scripts function action is triggered, WooCommerce Blocks validates that all dependencies for a given payment method script handle are registered. 

However, if the `init` action is never fired, then none of the WooCommerce Blocks dependencies like `wc-price-format` etc are registered which results in that error message.

There should be some conditional check that ensures the verify_payment_methods_dependencies only executes if the init action has been run.

Example:

```
public function verify_payment_methods_dependencies() {
    if(!did_action('init')){
        return;
    }
}
```

**Comment by preadored** [comment]
Same on our site. Should I add a separate report with our site details?

**Comment by csmcneill** [comment]
35170274-hc

**Comment by gviger** [comment]
Same on our site. Shows on default new empty Woo Shop page even with Stripe plugin disabled. All plugins, Wordpress etc at most recent versions. Just showed up today after WooCommerce 7.2.2 auto update yesterday.

**Comment by mikejolley** [comment]
The suggested solution to check if `init` ran looks good to me. I will move this to the backlog so someone can work on it.

**Comment by rossviviano** [comment]
40442355-hc
