### ISSUE TITLE
Feedback on ./packages/checkout/slot/README.md

### ISSUE THREAD

**Issue by oscargare** [woocommerce/woocommerce-gutenberg-products-block#7917]
Hi! It would be great to have an example of extending the checkout block using the available Slot Fills **without React.** Like the samples of the WordPress docs:
https://developer.wordpress.org/block-editor/reference-guides/packages/packages-plugins/

ES5 could be enough for adding "small features."

In my case, I need to add a simple message to ExperimentalOrderMeta. 

Thanks!

**Comment by senadir** [comment]
This is still react, the difference between ES5 and ES6 examples (badly named in my opinion) is that one of them uses a compiler (`@wordpress/scripts`) while the other (ES5) is code you can inject directly into the page.

You can also use [this page](https://babeljs.io/repl/#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=PQKhAIAECsGcA9wGMBOBTAhgFzQUQDZoC2aAdluCMAFBID2psFA3sutnoSeeAL7gBecAHcADgDo0XMlgDc1WgybgAwgxw8hACgCUggHzhm1AJDosAVxSlwAHgAmASwBu-gBZT8dW8CevqvEA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=true&targets=&version=7.20.6&externalPlugins=&assumptions=%7B%7D) to transform code from ES6 to ES5 in the main time.

**Comment by oscargare** [comment]
Great. thank you

**Comment by ralucaStan** [comment]
👋 Closing this ticket as there is no actionable item on our side.
