### ISSUE TITLE
Display "Add review" link if there's no product rating

### ISSUE THREAD

**Issue by kmanijak** [woocommerce/woocommerce-gutenberg-products-block#7923]
### Description
If product has no ratings, "Add rating" link appears instead of stars. For now the link text is NOT modifiable and redirects to #reviews section. Change applies to:

- All Products
- Products
- Legacy PHP template

### Gain
It would help with preserving the layout and eventually be a consistent way to link shoppers directly to the rating results for the product.

---

Note: The scope of this issue has changed based on the discussion in https://github.com/woocommerce/woocommerce-blocks/pull/7929

**Comment by Aljullu** [comment]
Hmmm, that's probably a regression. Should we include it in 9.1.1? cc @nerrad

**Comment by nerrad** [comment]
Was your comment meant for another issue Albert?

**Comment by Aljullu** [comment]
Ups, yes. :sweat_smile: Posted it in https://github.com/woocommerce/woocommerce-blocks/issues/7931.
