### ISSUE TITLE
Weird options ordering in Filter by Stock Status dropdown version

### ISSUE THREAD

**Issue by kmanijak** [woocommerce/woocommerce-gutenberg-products-block#7928]
The chosen options change the order after applying the filter in the Filter by Stock Status (dropdown version). Check the video below:

https://user-images.githubusercontent.com/4463174/207090261-d20c13ec-7854-48ce-b628-eb67a8adb4d0.mp4

Steps to reproduce:
1. Make sure you have at least one product with the stock status: "In stock", "Out of Stock" and/or "On backorder"
2. In the Editor add:
  - *Filter by Stock* block - set it to Dropdown and Multiple
  - *Products* block
3. In the frontend apply stock status filters: "In stock", "Out of Stock" and/or "On backorder"
4. Refresh the page if it hasn't refreshed itself

**Actual:** Order of the filters stays the same
**Expected:** Order of the filters changes as on the video

_Originally posted by @gigitux in https://github.com/woocommerce/woocommerce-blocks/issues/7831#issuecomment-1346765503_

**Comment by kirtangajjar** [comment]
Hello, I'd like to work on this issue
