### ISSUE TITLE
All Products: inner blocks don't honor global styles

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#7930]
## To reproduce

1. Add the All Products block to a post or page.
2. Edit the block with the pencil icon in the toolbar and change the global styles of one of the inner blocks.
![imatge](https://user-images.githubusercontent.com/3616980/207319148-cf688e21-b568-482a-98d3-7eda0eb27460.png)
3. Click on _Done_.
4. Notice the changes are not applied in the editor.
![imatge](https://user-images.githubusercontent.com/3616980/207319398-cdf63489-e534-4584-8d4c-4a1acad3c897.png)
5. Publish the post and visit it in the frontend.
6. Notice the changes are not applied in the frontend either.

## Expected behavior

The inner blocks should honor the defined styles.

**Comment by danieldudzic** [comment]
I have a feeling, this is a similar issue to: https://github.com/woocommerce/woocommerce-blocks/pull/7790#pullrequestreview-1200821814 - in which, the text alignment prop would be set to `undefined` in a different context than the editor (where it was working fine).

I had a short chat with @sunyatasattva about it but ultimately wasn't able to determine the culprit.

**Comment by Aljullu** [comment]
Closing based on the discussion on https://github.com/woocommerce/woocommerce-blocks/pull/8781#issuecomment-1478976855.
