### ISSUE TITLE
Rating and price are inlined in Products PHP template

### ISSUE THREAD

**Issue by kmanijak** [woocommerce/woocommerce-gutenberg-products-block#7931]
Prerequisites:
Make sure to have at least one product with any rating.

Steps to reproduce:
1. In the Editor add Legacy PHP Template to the page
2. Display it on the frontend

**Actual:** Rating and a price are inlined (see screenshot)

**Expected:** Rating and a price one after another

https://user-images.githubusercontent.com/20098064/207308668-6eddb1c2-8396-4695-8edb-b681857c3faa.png

_Originally posted by @nerrad in https://github.com/woocommerce/woocommerce-blocks/issues/7929#issuecomment-1348395829_

**Comment by Aljullu** [comment]
Hmmm, that's probably a regression. Should we include it in 9.1.1? cc @nerrad

**Comment by nerrad** [comment]
Yes, if possible.
