### ISSUE TITLE
ExperimentalOrderShippingPackages slot is missing in the editor preview

### ISSUE THREAD

**Issue by MonteLogic** [woocommerce/woocommerce-gutenberg-products-block#7939]
How would I use the Slot Fill on the edit page to make it show up exactly where it would be on the checkout page? 

For instance, my app on the checkout page looks like this: 
![image](https://user-images.githubusercontent.com/30337368/207475268-cc3ec97d-8442-4910-a1a0-fa073ee2bf46.png)

While on my edit page I cannot access the area that's in the same are to put information/data in it. It looks as follows: 
![image](https://user-images.githubusercontent.com/30337368/207475460-fc091285-49c4-4806-a81f-b4a7f9d84349.png)

What steps do I need to take to duplicate the app view on edit and checkout page for better user workflow? 

I have already setup the IntegrationInterface to work well as well as properly link to the edit file which it is compiled to. 

If this is not possible what solutions could make it close to the area? 

Thanks in advance.

**Comment by mikejolley** [comment]
Are you using slot fills for the frontend view? If so, can you share how you've done it. AFAIK slot fills work under both contexts.

**Comment by MonteLogic** [comment]
Yes, I am using SlotFills for the frontend view. The project I am working on is a fork of [woocommerce/newsletter-test](https://github.com/woocommerce/newsletter-test)
 
Gist with edit.js, block.js  and IntegrationInterface. 
https://gist.github.com/795257bccc733ff6d35a6ec74668f187

**Comment by mikejolley** [comment]
Ah `ExperimentalOrderShippingPackages`. @senadir this one is not shown in the editor. is there a reason for this?

https://github.com/woocommerce/woocommerce-blocks/blob/e875692b5dadd336e70db5931d2f9be80a82dc8a/assets/js/base/components/cart-checkout/shipping-rates-control/index.tsx#L180-L199

**Comment by senadir** [comment]
We possibly missed this one, I can't think of a reason to skip it there.

**Comment by opr** [comment]
It looks like no fills are being rendered in the editor, the slot is there but nothing fills it.

Trying to remove the `isEditor` check here results in an empty space below "Shipping options"

I'll continue investigating this but if anyone has any ideas why the fill won't render please let me know!
