### ISSUE TITLE
Storefront: missing icons due to WooCommerce font not being loaded

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#795]
**To Reproduce**

1. In a store using Storefront add a `Product by Category` block.
2. Add one of the products to your cart.
3. Notice the missing icon:
![image](https://user-images.githubusercontent.com/3616980/62361343-202bda00-b51b-11e9-9cc9-b6ad4edc8585.png)

The `WooCommerce` font is usually loaded [here](https://github.com/woocommerce/woocommerce/blob/master/assets/css/_fonts.scss#L17), but some themes like Storefront don't add that CSS file, making the icon not to appear.

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/storefront/pull/1189
