### ISSUE TITLE
When navigating back to a page with the Mini Cart block using the browser buttons the quantities do not update

### ISSUE THREAD

**Issue by opr** [woocommerce/woocommerce-gutenberg-products-block#7974]
## Describe the bug

Using the browser navigation buttons to go back to a page with the Mini Cart block after previously modifying the cart causes the quantities to revert to the original number until you actually refresh the page.

## To reproduce

1. Add the Mini Cart block to a page, and the All Products block.
2. Add items to your cart and observe the "total" number update as you add products.
3. Open the Mini Cart and then proceed to checkout.
4. From the checkout page, press the browser back button.
5. Observe the Mini Cart block and see that the quantities are not the same as they were when you proceeded to checkout.

## Expected behavior

Quantities would be correct when navigating back using the browser buttons.

## Screenshots

https://www.loom.com/share/bb01ec49eb16430fa9dc150cf330787f

## Additional context

Reported as a comment on #3827 by @thexpand :)

**Comment by opr** [comment]
@ralucaStan marking this as tier 1 backlog because I believe it may require us to do work in the data store as well as for Kirigami to make changes too.

**Comment by mikejolley** [comment]
Could potentially use the solution in https://github.com/woocommerce/woocommerce-blocks/pull/8236
