### ISSUE TITLE
Local Pickup: WooCommerce Subscriptions should render local pickup rates in a local pickup slot

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#7998]
Right now, WooCommerce Subscriptions render its rates in the shipping options block, it mixes both pickup locations and regular rates there.

If you switch to local pickup panel, WooCommerce Subscriptions doesn't render there.

WooCommerce Subscriptions is a bit different because it doesn't add packages, it add a whole new cart so we can't merge those packages.

What we should do:

- Introduce a new slot fill inside the local pickup one.
- Have WooCommerce Subscriptions render local pickup rates there.
- Remove local pickup rates from the original package.

**Comment by mikejolley** [comment]
Waiting on https://github.com/woocommerce/woocommerce-blocks/pull/8256

We'll add a slot fill and decide whether or not to help with the integration, or just document for future addition.

**Comment by ralucaStan** [comment]
https://github.com/woocommerce/woocommerce-blocks/pull/8256 has been merged

**Comment by opr** [comment]
I did some work in https://github.com/Automattic/woocommerce-subscriptions-core/issues/399#issuecomment-1454253456 which shows the `ExperimentalOrderLocalPickupPackages` in use.
