### ISSUE TITLE
Add a `from` transform to each block to support legacy shortcodes

### ISSUE THREAD

**Issue by claudiulodro** [woocommerce/woocommerce-gutenberg-products-block#8]
If a page has the products shortcode already on it (from posts created using the classic editor) convert the shortcode into a pre-populated Products block. More investigating will need to be done to see if this is possible, but I believe Gutenberg 2.1 has some shortcode handling features so it should be possible.

Possible use case for transformations API: https://github.com/WordPress/gutenberg/issues/4578

**Comment by LevinMedia** [comment]
Relates to #86

**Comment by ryelle** [comment]
Looks like we can use `transform`s to convert supported shortcode options into our blocks: https://wordpress.org/gutenberg/handbook/designers-developers/developers/block-api/block-registration/#transforms-optional

Shortcodes are very customizable though, so we'll still have to fall back to the core shortcode block for options the blocks don't support

**Comment by ryelle** [comment]
Currently we can only map a given shortcode to one block, there's no way to check the attributes of a shortcode before running the transform. This issue is on hold until there's core support for `isMatch` on shortcode transforms (or whatever the solution is): https://github.com/WordPress/gutenberg/issues/10674

**Comment by nerrad** [comment]
This issue has been open for a while. While the idea is sound, there doesn’t seem to be need for the transforms at the moment. We can revisit and reopen specific issues for blocks that we want to add transforms to as the need/desire surfaces.
