### ISSUE TITLE
'Edit with HTML' showing blank on Hand Picked Products and Product Categories

### ISSUE THREAD

**Issue by nixiack** [woocommerce/woocommerce-gutenberg-products-block#800]
**Describe the bug**
Using WC 3.7 RC2, when I do a test block and try to Edit as HTML it jus shows blank on all blocks.

**To Reproduce**

1. Go to 'any new page or post on test site with WC 3.7 RC 2'
2. Click on the + and add Hand Picked Product:

![Screenshot](https://cld.wthms.co/88yPxz+)
Screenshot: https://cld.wthms.co/88yPxz
3. Create a Hand-picked Product block, then click the 3 dots and select `Edit as HTML`
4. Nothing shows/it is blank as this GIF example:

http://g.recordit.co/iOqVz3zi2W.gif

**Expected behavior**
When clicking on `Edit as HTML` it should show the HTML area like so:

![Screenshot](https://cld.wthms.co/2yLnVR+)
Screenshot: https://cld.wthms.co/2yLnVR 

**WordPress (please complete the following information):**

* Core version: 3.7 RC2 (also tested in 3.6.5 and I *was* able to replicate!)
* Gutenberg version (if installed): -----
* WooCommerce version: [5.2.2]
* WooCommerce Blocks version: 3.7 RC 2 (no plugin, core Blocks)
* Site language:
* Any other plugins installed:

**Desktop (please complete the following information):**

* OS: [e.g. iOS]
* Browser [Chrome, Firefox]
* Version
Chrome: Version 75.0.3770.142 (Official Build) (64-bit)
Firefox(Quantum): 68.0.1 

**Smartphone (please complete the following information):**

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Additional context**
Pinged developers in Slack, @juliaamosova was able to replicate as well.

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/801 - shortcodes are no longer used on these blocks.

Thanks
