### ISSUE TITLE
Feedback on ./src/StoreApi/docs/cart.md

### ISSUE THREAD

**Issue by isaac-matchbook** [woocommerce/woocommerce-gutenberg-products-block#8000]
It looks like there is no way to update the customer's Billing Company or Shipping Company. 

This would be a helpful feature. Thanks!!

**Comment by senadir** [comment]
The company field is available in the cart schema so you can update it just fine, what did you try?

**Comment by nielslange** [comment]
Hello @isaac-matchbook 👋

I’m going to close this because there still isn’t anything actionable for us on this issue. If/when you have additional details, you can still add them to this issue and if we’re able to reproduce, we can re-open as necessary.
