### ISSUE TITLE
TAX rate not updating after changing the country on Checkout page. 

### ISSUE THREAD

**Issue by regedy1** [woocommerce/woocommerce-gutenberg-products-block#8015]
## Describe the bug

The TAX rate is not updating on checkout page after changing the country.

## To reproduce

1. add product
2. go to checkout
3. change the country in billing address / shipping address
4. the tax rate is not updating in the total price table

## Expected behavior
The standard woocommerce checkout works with updating the tax rate according to the country.

### WordPress (please complete the following information):

-   WordPress version: 6.1.1
-   WooCommerce version: 7.2.2
-   WooCommerce Blocks version: 9.2.0
-   Site language: English
-   Any other plugins installed: [EU/UK VAT Compliance for WooCommerce, WP Rocket
### Desktop (please complete the following information):

-   OS: MAC
-   Browser: BRAVE
-   Version: Version 1.46.144

**Comment by senadir** [comment]
Taxes update when you persist an address to the server, and addresses are persisted when they're complete (no errors or empty required fields) after that each change will trigger a new update as well.

Are you sure you filled all of the fields?

**Comment by regedy1** [comment]
With the old checkout, even just selecting a country leads to an update of the tax rate.

With the checkout block, I filled out every field and it doesn't refresh. 

<img width="1203" alt="Screenshot 2022-12-22 at 18 38 36" src="https://user-images.githubusercontent.com/36901285/209127587-a3bf7da0-faac-40c5-9242-7cc9e8a9fc22.png">
<img width="1180" alt="Screenshot 2022-12-22 at 18 38 48" src="https://user-images.githubusercontent.com/36901285/209127595-48df7530-d227-4261-a15b-c6954d0dbd99.png">
<img width="1219" alt="Screenshot 2022-12-22 at 18 41 39" src="https://user-images.githubusercontent.com/36901285/209127640-ffd6b42c-08a2-45ff-8a16-dd7f90d87ad6.png">

**Comment by senadir** [comment]
To confirm a similar bug we have, do you happen to have the terms and condition block added and set to Checkbox?

**Comment by regedy1** [comment]
I couldn't see a difference whether the terms and conditions with checkbox were on or off. Still no VAT update. 
I even removed the T&C block, but it still didn't work. 

Also deactivated all plugins and only had Woocommerce + Woocommerce Blocks left. 🤔

<img width="601" alt="Screenshot 2022-12-22 at 20 33 00" src="https://user-images.githubusercontent.com/36901285/209146753-5f0466d6-86ad-4faa-a035-7b8bf24ceedc.png">
<img width="609" alt="Screenshot 2022-12-22 at 20 40 10" src="https://user-images.githubusercontent.com/36901285/209146737-eb9214e4-64c0-41bb-b00e-05b574c4ecf0.png">

**Comment by regedy1** [comment]
<img width="624" alt="Screenshot 2022-12-22 at 20 45 11" src="https://user-images.githubusercontent.com/36901285/209147462-1156de16-d0be-45f1-9008-a98b2150a051.png">
