### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function Automattic\WooCommerce\Blocks\BlockTypes\wp_is_block_theme()

### ISSUE THREAD

**Issue by loicrey** [woocommerce/woocommerce-gutenberg-products-block#8032]
## Describe the bug

After updating my plugins and WooCommerce, I wasn't able to edit or add any posts or pages because of a Fatal Error when I do these actions.

## To reproduce

1. I update Woocommerce plugin to 7.2.2 in extensions dashboard
2. Click on Edit/Add Posts or Pages in Dashboard
3. See error

### WordPress (please complete the following information):

-   WordPress version: 5.8.6
-   Gutenberg version (if installed): #
-   WooCommerce version: 7.2.2
-   WooCommerce Blocks version: #
-   Site language: French
-   Any other plugins installed:

## Additional context

Error code : 
```
Fatal error: Uncaught Error: Call to undefined function Automattic\WooCommerce\Blocks\BlockTypes\wp_is_block_theme() in /server/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/BlockTypes/ProductImage.php:168 Stack trace: 
#0 /server/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/BlockTypes/AbstractBlock.php(100): Automattic\WooCommerce\Blocks\BlockTypes\ProductImage->enqueue_data() 
#1 /server/wp-includes/class-wp-hook.php(303): Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock->enqueue_editor_assets('') 
#2 /server/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array) 
#3 /server/wp-includes/plugin.php(470): WP_Hook->do_action(Array) 
#4 /server/wp-admin/edit-form-blocks.php(252): do_action('enqueue_block_e...') 
#5 /server/wp-admin/post.php(187): require('/server/...') 
#6 {main} in /server/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/BlockTypes/ProductImage.php on line 168
```

It seems to fix itself with Wordpress Version 6.1.1

**Comment by Aljullu** [comment]
Thanks for opening this issue, @liocrey! This was fixed in https://github.com/woocommerce/woocommerce-blocks/pull/7496.

> It seems to fix itself with Wordpress Version 6.1.1

Correct, updating WordPress will fix this issue.

We will evaluate if we do a patch release, in the meanwhile, as you say, the best way to work-around this issue is updating WordPress.
