### ISSUE TITLE
Where are the Hooks?

### ISSUE THREAD

**Issue by UVLabs** [woocommerce/woocommerce-gutenberg-products-block#8035]
Tried using the Checkout Block and then activating "Simpy Show Hooks" but it doesn't seem like there are any hooks like before such as:

`woocommerce_before_checkout_shipping_form`
`woocommerce_after_checkout_shipping_form`
`woocommerce_before_checkout_billing_form`

There doesn't even seem to be the `woocommerce_checkout_before_customer_details` hook.

Are these hooks expected to come at some point? How do developers hook into different parts of the checkout block?

**Comment by wavvves** [comment]
Hi @UVLabs , the Checkout Block doesn't currently support editing the form via the mentioned hooks. Work is underway to offer an alternate way of editing it.
