### ISSUE TITLE
Blockifying Product Archive Templates

### ISSUE THREAD

**Issue by dinhtungdu** [woocommerce/woocommerce-gutenberg-products-block#8059]
This is the umbrella issue for all issues under the Blockifying Product Archive Templates project. The goal of this project is to create a complete block experience for Product Archive templates. We achieve that goal by leveraging the Products block and creating equivalent blocks to parts of the archive page like result count and product ordering. We also want to account for the extensibility within this project by researching the mechanism for extensions to extend the templates and implementing a compatibility layer to keep as many extensions as possible working with blockified templates while giving time for extension developers to update and blockify their extensions.

## Tasks

- [x] #8060
- [x] #8061
- [x] #8063
- [x] #8062
- [x] #8064
- [x] #8065
- [x] #8066
- [x] #8067
- [x] #8216 
- [ ] #8415

**Comment by gigitux** [comment]
Since that #9551 has been merged, we can consider this issue fixed. We will work on https://github.com/woocommerce/woocommerce-blocks/issues/8415 during the next iterations.
