### ISSUE TITLE
Create Notices Block

### ISSUE THREAD

**Issue by dinhtungdu** [woocommerce/woocommerce-gutenberg-products-block#8062]
We want to create a block so merchants can display the store notices to customers. By having a block, the merchant can also determine where the notices appear.

| Property | Value |
|---------|---------|
| Block title | Store Notices |
| Block description | Display shopper-facing notifications generated by WooCommerce or extensions. |
| Block slug | `notices` |
| Block file location | `assets/js/blocks/notices/` |
| Block class location | `src/BlockTypes/Notices.php` |
| Scope | Site Editor |
| Equivalent template file | None |
| Equivalent template function | [`woocommerce_output_all_notices()`](https://github.com/woocommerce/woocommerce/blob/25f051cad273bf709b127d162ab43f437d774c42/plugins/woocommerce/includes/wc-template-functions.php#L3805-L3809) |
| Style | None |
| Visibility | Woocommerce Core |

### Screenshot

<img width="1099" alt="image" src="https://user-images.githubusercontent.com/5423135/210508641-18efcb29-8e79-4936-be27-d7bbbaad83a7.png">

**Comment by dinhtungdu** [comment]
@albarin FYI, I update the description of this block to:

> Display shopper-facing notifications generated by WooCommerce or extensions.

**Comment by albarin** [comment]
Got it, thanks! 🙌
