### ISSUE TITLE
Can't add the Products block in WP 5.9

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#8069]
## To reproduce

1. With WordPress 5.9 and WooCommerce core 7.3 beta 2, create a post or page.
2. Try to add the _Products (Beta)_ block.
3. Notice the block can't be added and there is an error in the console.

## Expected behavior

Either we:

1. Hide the Products block on WordPress 5.9.
2. Find a way to add the Products block without the need of `core/query-no-results`, which seems to be the problematic inner block.

I lean towards approach 1 because it's simpler and I think it's safe to assume most stores using a block theme keep WordPress up to date. But if we can find a way to implement approach 2, I think it's also ok.

## Screenshots

![imatge](https://user-images.githubusercontent.com/3616980/210212841-92acdf65-5f42-46d7-9d46-007d183e7965.png)

**Comment by Aljullu** [comment]
@sunyatasattva do you think we should prioritize this? It would be good to get it fixed in WP 7.3 so we don't expose the Products block in stores which can't insert it.

**Comment by sunyatasattva** [comment]
Thanks for finding this out @Aljullu ! Do you know what happens if you add the normal Query Loop block on WP 5.9? And yea, I think it would be good to prioritize this.

**Comment by Aljullu** [comment]
> Do you know what happens if you add the normal Query Loop block on WP 5.9?

It does work. What I think is missing in WP 5.9 is `core/query-no-results`, but the Query Loop block is there. (I didn't do too much research, though)
