### ISSUE TITLE
item Keys mismatch in cart items & Shipping_rates Object causing 409 error

### ISSUE THREAD

**Issue by bitsnio** [woocommerce/woocommerce-gutenberg-products-block#8074]
## Describe the bug

items in cart become invalid when the key of items available in `cart.Shipping_rates[0].items` object and `cart.Items ` differ. this Difference make the item keys invalid since API verifies based on item keys available in shipping_rates Object.

<img width="680" alt="image" src="https://user-images.githubusercontent.com/58328990/210229026-29ec4461-3d52-4369-b16f-c703af96c241.png">

## To reproduce

this Behaviour is very tricky. When i add an item in cart then the key of newly added item matches both in shipping_rates Object and Items object as in snap-1. But after some time the item key under main Items object changes. Since all updates are being done based on main Items key in case of mismatch in both keys 409 error is thrown since shipping_rates's item key is only valid key as per snap-2

snap-1
<img width="614" alt="image" src="https://user-images.githubusercontent.com/58328990/210229684-88992689-3007-4bdc-812c-6875032ec871.png">
snap-2
<img width="933" alt="image" src="https://user-images.githubusercontent.com/58328990/210229881-5578a470-caa6-4061-8972-1a901ff319f4.png">

## Expected behavior

if somehow due to change in item , Key is invalidated then both keys remain same.

### WordPress (please complete the following information):

-   WordPress version: [e.g. 5.9]
-   Gutenberg version (if installed): 9
-   WooCommerce version: 7.2.2
-   WooCommerce Blocks version: [e.g. 9.2.0]
-   Site language:PHP
-   Any other plugins installed:

### Desktop (please complete the following information):

-   OS: macOS
-   Browser: chrome

**Comment by tarhi-saad** [comment]
Hello there, @bitsnio! 👋 Thank you for informing us about this bug! 🙌 I attempted to replicate it but was unsuccessful! If I modify my item, it will be removed automatically following an API request, which is the desired action. Could you please provide us with step-by-step directions for reproducing this bug?

**Comment by bitsnio** [comment]
Hi @tarhi-saad , I have tried a lot to replicate this bug. But when you leave items in cart for sometime like in my case it was 2 days then the key of items changed. you cannot update/delete these items any more. only way to update the items to use the item key available in shipping_rates object. Keep your items in cart for sometime then check. Just to mention I'm using JWT token for authentication and this issue is occurring even token is still valid.

**Comment by tarhi-saad** [comment]
Hello there, @bitsnio! 👋 Thank you for the explanation! 🙌 It would be fantastic if we could reproduce the bug on our end, so I'll create a new website, add some products to the Cart, and check the item keys in two days! Could you help us with the following questions to create a testing environment similar to yours?

- Are you using the plugin version of the `WooCommerce Blocks` or the WooCommerce core version?
- Did you run the tests using an authenticated account (e.g., admin)?
- Did you try running a test using a fresh website installation?
- Type of products you tested it with (e.g., simple, variable, virtual, etc.)?

I'll also ask internally to see if we can find what's causing this change of key in this particular case.

**Comment by tarhi-saad** [comment]
We have another question, if you don't mind, @bitsnio:

> Just to mention I'm using JWT token for authentication and this issue is occurring even token is still valid.

What JWT you are using? Is it our JWT token or a third-party extension for JWT auth?

**Comment by bitsnio** [comment]
> Hello there, @bitsnio! 👋 Thank you for the explanation! 🙌 It would be fantastic if we could reproduce the bug on our end, so I'll create a new website, add some products to the Cart, and check the item keys in two days! Could you help us with the following questions to create a testing environment similar to yours?
> 
> * Are you using the plugin version of the `WooCommerce Blocks` or the WooCommerce core version?

first I was using Core and same issue was present there but later I shifted to `WooCommerce Blocks` so currently using Woocommerce blocks Plugin

> * Did you run the tests using an authenticated account (e.g., admin)?

I have run all test on customer account not through any admin account.

> * Did you try running a test using a fresh website installation?

Not Yet since I have very complex scenarios built in current website.

> * Type of products you tested it with (e.g., simple, variable, virtual, etc.)?

I have tested both simple and variable products and issue is produced with both types. not testing done for virtual

> I'll also ask internally to see if we can find what's causing this change of key in this particular case.

actually that is important since the issue is related to item_key. Since the key related to items in shipping_rates remains unchanged but items key changes unexpectedly.

**Comment by bitsnio** [comment]
> We have another question, if you don't mind, @bitsnio:
> 
> > Just to mention I'm using JWT token for authentication and this issue is occurring even token is still valid.
> 
> What JWT you are using? Is it our JWT token or a third-party extension for JWT auth?
it is third-party plugin. below is the one we are using.
https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/

**Comment by senadir** [comment]
Hey @bitsnio, are you reliably reproducing this?

I pushed a quick fix that should fix this

https://github.com/woocommerce/woocommerce-blocks/pull/8199
