### ISSUE TITLE
Product Elements: Feature parity between Add to Cart button and core Buttons

### ISSUE THREAD

**Issue by sunyatasattva** [woocommerce/woocommerce-gutenberg-products-block#8085]
Currently, the “Add to Cart” button is missing some of the functionalities from the core Buttons, e.g.

1. Fill vs Outline style
2. Missing padding control

Identify all missing features and achieve feature parity.

**Comment by imanish003** [comment]
Hi @sunyatasattva,
I have a few questions. I compared `Add to cart button` with `Core button` & identified following differences:

### Inspector controls
| Add to cart button | Core button |
|-|-|
| ![image](https://user-images.githubusercontent.com/16707866/211290942-a985077e-02a3-4901-aa86-9e6840a8035d.png) | ![image](https://user-images.githubusercontent.com/16707866/211290991-e9a34057-3ff5-42c6-8a4a-87b736a33e1e.png) |

**Following are the extra functionality in Core Button:**
- Styles: Fill & Outline
- Width Settings
- Typography
    - Font Family
    - Appearance
    - Line height
    - Letter spacing
    - Decoration
    - Letter case

**Question: Do we want to add all these to `Add to cart button`?**

There is Margin that is extra in `Add to cart button`.

**Question: Do you know why Margin isn't there in Core Button?** 

### Block Toolbar 

| Add to cart button | Core button |
|-|-|
| ![image](https://user-images.githubusercontent.com/16707866/211291945-6ff6dcd0-f86d-4234-a586-5a2a19e92d8d.png) | ![image](https://user-images.githubusercontent.com/16707866/211291994-c75c3312-76ce-4957-875c-dcd42d931237.png) |

**Question: There are lots of extra functionality in Core button toolbar, Do we want to add all those to `Add to cart button` toolbar?**

**Comment by sunyatasattva** [comment]
Great research @imanish003! My answer would probably be yes, according to what I've understood of our next steps so far (see pdnLyh-30z-p2).

However, I'd summon @vivialice and @nerrad for confirmation that we want to achieve absolute parity by duplicating all the functionality or we want to do something different. Again, it'd be cool if the core button was just extendable. One idea to make this happen, could be to make the “Button” block accept inner blocks and then create our own Add to Cart button which would only be handling functionality, while the styling would be handled by the core button. That was just off the top of my head, because I'd love not to have to duplicate features from GB as we'll also make sure we do it regularly.

> Question: Do you know why Margin isn't there in Core Button?

I do not know, alas. Interesting question to ask the GB team!

**Comment by nerrad** [comment]
One other thing to consider here is that the `Button` block is actually an inner block in the `Buttons` block (which has an impact on styling as well). I wonder if we'd be able to do a variation of the `Button` block for Add to Cart button and have it available as an inner block of the `Buttons` block (maybe this is what you were suggesting Lucio)?

<img width="366" alt="CleanShot 2023-01-09 at 13 26 25@2x" src="https://user-images.githubusercontent.com/1429108/211380942-997cdf65-b135-4835-a1ab-aa5df3ec9ff3.png">

**Comment by sunyatasattva** [comment]
Yea, I think it'd be nice to explore a whole bunch of different avenues before we resort to just duplicating all the available functionality, what do you think? Would that be worth the time investment? Personally, I think so.

Also, to have a more direct reply to Manish's question, let's say we get to the worst case scenario and we need our own block, am I right in assuming in that case we'd want **all** the functionality and styling options of the core Button?

**Comment by nerrad** [comment]
> Personally, I think so.

Agreed, I think we should exhaust the avenues for re-using the core block first before falling back to enhancing the existing block. Even if that includes identifying what would be needed in Gutenberg in order to extend/create a variant of the core block.

> let's say we get to the worst case scenario and we need our own block, am I right in assuming in that case we'd want all the functionality and styling options of the core Button?

Likely, but let's nail down the specifics once we know for sure if in the interim we need to enhance the existing block.

**Comment by imanish003** [comment]
Thank you, @sunyatasattva @nerrad, for diving in & answering my questions. 

> I think we should exhaust the avenues for re-using the core block first before falling back to enhancing the existing block. Even if that includes identifying what would be needed in Gutenberg in order to extend/create a variant of the core block.

Agreed! Let me figure out the ways to reuse the core block. I will get back to you with my findings.

**Comment by sunyatasattva** [comment]
Great! Please @imanish003 could you adjust the estimate of this issue to match your expectation for this research?

**Comment by imanish003** [comment]
@sunyatasattva Sure, I have updated the estimate , taking into account potential challenges and contingencies.

**Comment by imanish003** [comment]
Update: We decided not to use core/button or core/buttons variation for Add to Cart button. More info in P2 comment: per0F9-qd-p2#comment-443.

I am starting to work on this again.

**Comment by imanish003** [comment]
I have finished all the tasks that were not blocked and have created new issues for the ones that are blocked. This approach will help us better organize our work and ensure all issues are accounted for. I will go ahead and close this issue.
