### ISSUE TITLE
Product Elements: Add design tools to “On Sale Badge” block

### ISSUE THREAD

**Issue by sunyatasattva** [woocommerce/woocommerce-gutenberg-products-block#8087]
Details TBD.

cc @vivialice

**Comment by vivialice** [comment]
Hey @sunyatasattva 👋 

I did a review of the **On-Sale badge** and you can also find the summary in [Figma](https://www.figma.com/file/MC2DxQ0e2yLBY13gQs3nnM/Product-Element-Blocks-i2?node-id=811%3A6306&t=WXVx9AhHZrisbH1L-1) .We have different settings available depending on where the block is found, either: 

- On the **Product image block**
- As its own block
- In Global styles list

<img width="953" alt="Screenshot 2023-01-18 at 11 16 31" src="https://user-images.githubusercontent.com/9888201/213157800-16e4af70-a294-4b0f-a6d9-677c554e3182.png">

### **Inspector settings**

We already have most of what we need in the separate block variation of **On-Sale products**.  I have a few suggestions for improvement: 

- Bring in other Typography styles available, (right now we are just using Font Size): Font Family, Appearance, Line height, Letter spacing, Letter case, Decoration
- Add Margin option to Dimensions drawer

Also, I feel like what settings are available in the main panel, should be available in the Global Styles options. 

### **Placement**

<img width="552" alt="Screenshot 2023-01-18 at 10 49 50" src="https://user-images.githubusercontent.com/9888201/213152523-2c35b19d-0c1e-4ed3-aa19-52baeb52fb0a.png">

I am not sure where we ended up on this discussion, but there was talk of exploring referencing the **Cover block** toolbar placement controls for the product image. For the first iteration, I think it's fine if we continue with the _left / center / right_ options currently available, but perhaps it's something we can explore with this work.
