### ISSUE TITLE
Filter by Rating: sometimes Notice shows there's no ratings while there are ratings

### ISSUE THREAD

**Issue by kmanijak** [woocommerce/woocommerce-gutenberg-products-block#8097]
## To reproduce

0. Make sure you have some products _with_ ratings
1. Create a new post
2. Add some filter, e.g. FIlter by Stock
3. Add Filter by Rating

## Expected behavior

- Preview of rating filter shows up
- There's no Notice saying there's no products with ratings yet

## Screenshots
- Red rectangle - Notice saying there's no products with ratings
- Green rectangle - preview of Filter by Ratings showing there are products with rating
<img width="744" alt="Screen Shot 2023-01-04 at 11 24 09 AM" src="https://user-images.githubusercontent.com/20098064/210534882-263d96d5-88a4-4569-bd2d-d06018a0e0be.png">

## Environment

-   WordPress version: 6.1.1
-   Gutenberg version (if installed): 14.4.0
-   WooCommerce version: 7.2.0
-   WooCommerce Blocks version: 9.2.0

## Additional context

The issue occurs only when Filter by Rating is added as a consecutive filter. The initial state says there's no ratings at the moment which are being fetched at the moment.

The flag to show notice [is set here](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/blocks/rating-filter/block.tsx#L244) and as the initial state satisfies the condition, flag is set to `true`, however there's no logic that would change that later on.

**Comment by danieldudzic** [comment]
I'm following the steps but can't reproduce the issue.

**Comment by kmanijak** [comment]
Hmm.. I can't seem to reproduce it on `trunk` either 🤔 It's possible that issue has been fixed in the meantime. I found it while testing https://github.com/woocommerce/woocommerce-blocks/pull/8079 - but I can't reproduce it there as well.

Thanks @danieldudzic for confirmation, I'm closing the issue then
