### ISSUE TITLE
Send a message to the #team-rubik slack channel when nightly builds fail

### ISSUE THREAD

**Issue by alexflorisca** [woocommerce/woocommerce-gutenberg-products-block#8106]
We've had a few instances of nightly builds failing. It would be great if we could be alerted of these so we can notify other teams using it upstream. Slack conversation p1672919163102919-slack-C8X6Q7XQU

~~I've briefly looking into into it, and it should be possible with the [Slack Notify GH action](https://github.com/marketplace/actions/slack-notify). We can run it as an extra step after on the nightly-deploy workflow, and only run it if the action fails by using `if: failure()` inside the slack notify step. [This article](https://stackoverflow.com/questions/58858429/how-to-run-a-github-actions-step-even-if-the-previous-step-fails-while-still-f) might be handy~~

This is possible with the Github slack app, see comment below

**Comment by Aljullu** [comment]
@alexflorisca what are your thoughts on using the repo channel for this? This way folks from other teams working on WC Blocks are notified as well and can eventually help. :slightly_smiling_face:

**Comment by alexflorisca** [comment]
Yeah sure thing, will use #woo-blocks-repo :)

**Comment by alexflorisca** [comment]
This is done now. No code needed. I used the github slack app to subscribe in the #woo-blocks-repo channel

```/github subscribe woocommerce/woocommerce-blocks workflows:{name:"Nightly builds"}```
