### ISSUE TITLE
Add item on cart variation issue

### ISSUE THREAD

**Issue by WordpressArtist** [woocommerce/woocommerce-gutenberg-products-block#8115]
I am trying to add a product on cart.
Normal products works fine but for product having variants throwing issue..

Example on DOCS:
curl --header "Nonce: 12345" --request POST https://example-store.com/wp-json/wc/store/v1/cart/add-item?id=100&quantity=1
NO detailed example how to add variants on documentation

variation | array | Yes | Chosen attributes (for variations) containing an array of objects with keys attribute and value.

How to pass array on url  ?

http://host.test/wp-json/wc/store/v1/cart/add-item?id=19487&quantity=1&variation="[{\"attribute\":\"Type\",\"value\":\"Product With Cover\"}]"
OR
http://host.test/wp-json/wc/store/v1/cart/add-item?id=19487&quantity=1&variation="['attribute':'Type','value':'Product With Cover'}]" NOt working 

returning 

 "code": "rest_invalid_param",
    "message": "Invalid parameter(s): variation",
    "data": {
        "status": 400,
        "params": {
            "variation": "variation[0] is not of type object."
        },
        "details": {
            "variation": {
                "code": "rest_invalid_type",
                "message": "variation[0] is not of type object.",
                "data": {
                    "param": "variation[0]"
                }
            }
        }
    }

Please help.

**Comment by senadir** [comment]
Hey @WordpressArtist, you can variable products in 2 ways:

- You can pass the variation product ID directly (not parent variable product) without needing to pass a variation array.
- You can pass the variable product ID, and a variation data array that consists of the term slug and value.


This is usually done in the request body, not the URL, but it's doable, however, it will turn into a complicated URL, assuming you're trying to add variable product with ID 7, quantity 1, and variation color (which has a taxonomy of pa_color) and value of blue, it would be something like this:

```
wc/store/v1/cart/add-item?id=7&quantity=1&variation[0][attribute]=pa_color&variation[0][value]=blue
```

This would only work if `Color` is a global attribute, its taxonomy would be `pa_` + the slug you defined.

I also added an issue to track documenting this.
