### ISSUE TITLE
Store API doesn't append third party query params to cart item permalink

### ISSUE THREAD

**Issue by bozzmedia** [woocommerce/woocommerce-gutenberg-products-block#8119]
## Describe the bug

When using the new cart and checkout blocks there does not seem to be a way to click the product and edit variations or options as you can in Woo Classic. 

## To reproduce

1. Use WC Bocks
2. Use a plugin that relies on appending information to a URL to allow editing of variations/additional info (In my case: Gravity Forms Product Addon)
3. When using Woo Classic, it works fine, ex:

https://redacted.com/product/product-name/?attribute_frame-color=Light+Red&wc_gforms_cart_item_key=6aceac4da5b55f3b726d18025cc96cef

5. When using Woo Blocks checkout, the edit URL seems to be different and does not carry that information.
https://redacted.com/product/product-name/

Full info on slack including an addon dev who has run into issues:
https://woocommercecommunity.slack.com/archives/C1KAZ91E3/p1671566495106139

The dev of Gravity Forms addon also confirms this is an issue with current implementation of the checkout block. They state: "This appears to be a problem with WooCommerce itself.  Even using a standard Variable product with nothing else it doesn't allow you to click on the title in the Cart from the cart block and edit it.  I'm guessing there is a filter on the cart item link they are not calling when rendering the cart for the block that they do when rendering the "Real" cart.   Since they are missing the filter in WC core there's not anything I can do from my end to "hack" around it. "

## Expected behavior

WC Blocks should support the same method as classic for allowing this interoperability of editing product options and addon options.

### WordPress (please complete the following information):

-   WordPress version: 6.1.1
-   Gutenberg version (if installed): not installed
-   WooCommerce version: latest production
-   WooCommerce Blocks version: latest production
-   Any other plugins installed: Gravity Forms Product Addons

**Comment by senadir** [comment]
Hey @bozzmedia ! Thank you for reaching out, I responded to the slack thread but responding here as well.

Store API (and by extension Cart/Checkout block) support adding attributes to the URL of item, this is done via `WC_Product_Variation::get_permalink`, what you're looking for is third party link params, added via `woocommerce_cart_item_permalink`, which is a hook present on the Cart/Mini Cart HTML templates, adding it here will impact Store API and so we would rather look into it before doing this.

There's no direct way to do this right now (nothing I'm aware of at least), I will let you know once we tackled this.
