### ISSUE TITLE
Feedback on ./docs/third-party-developers/extensibility/hooks/actions.md

### ISSUE THREAD

**Issue by nvgandhi123** [woocommerce/woocommerce-gutenberg-products-block#8120]
Hello !

I can't find a hook for the checkout process validation similar to "woocommerce_after_checkout_validation"

Thanks

**Comment by senadir** [comment]
Hey! are you trying to run some code before the order is submitted?

**Comment by nvgandhi123** [comment]
Hello Seghir,

I am the author of the plugin reCaptcha For WooCommerce (
https://woocommerce.com/document/recaptcha-for-woocommerce/) , I have
received one request from a client that my plugin should be compatible with
the checkout block. So I have checked few pieces of documentation about the
block but it is I think still under development so I can't find hooks. I
require hook like "woocommerce_after_checkout_validation" to validate
Recaptcha requests, but I can t find any hook for blocks API created yet ?


Thanks
I13 Web Solution

**Comment by senadir** [comment]
Hey @nvgandhi123! 

Are you looking to validate things completely via JS or via PHP.

Both methods require some knowledge of JS or React
I suggest you reject the request on the client before it goes to the server, you can do that by hooking into `wc/store/checkout` and `wc/store/validation` data stores, something that resembles this

```js
const { dispatch, select, subscribe } = wp.data;

subscribe( () => {
	const { isBeforeProcessing } = select( 'wc/store/checkout' );
	const { setValidationErrors, clearValidationError } = dispatch(
		'wc/store/validation'
	);
	let passedCaptcha = false;
	if ( isBeforeProcessing ) {
		passedCaptcha = customCaptchaFunction();
	}

	if ( ! passedCaptcha ) {
		setValidationErrors( {
			'custom-captcha-plugin': {
				message: 'you failed capatch',
				hidden: false,
			},
		} );
	} else {
		clearValidationError( 'custom-captcha-plugin' );
	}
} );
```

If you need to do this via PHP, you will need to hook into `woocommerce_store_api_checkout_order_processed`.

**Comment by nvgandhi123** [comment]
Hello Seghir,

Thanks for your reply.

I need a server-side check as the captcha token need to pass google and
google validates it and sends back to me.

I have tried -- woocommerce_store_api_checkout_order_processed

but the problem is "woocommerce_store_api_checkout_order_processed" is not
prevent creating orders. "woocommerce_store_api_checkout_order_processed"
always creates order in draft that cause a problem as imaging when there is
an attack on the server makes thousands of order in the draft that not good
idea.

So there should be hook that allows checks before order create. :)

Thanks
I13 Web Solution

**Comment by senadir** [comment]
Draft orders are created the moment you visit Checkout page, they can also be created using Store API, without any browser interaction, so I'm not sure how effective Captcha will be there.

We have a rate limit mechanism that you can hook into if you want:
https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/StoreApi/docs/rate-limiting.md

**Comment by nvgandhi123** [comment]
OK THanks

Please can you provide any documentation or example to add a simple
additional hidden field or something text field in yo checkout block? As
there is hardly any example that found so it is very hard to get started
with this.


THanks
I13 Web Solution

**Comment by ralucaStan** [comment]
@nvgandhi123 there is an example you could use in [@woocommerce/extend-cart-checkout-block](https://www.npmjs.com/package/@woocommerce/extend-cart-checkout-block). This is a template to be used with @wordpress/create-block to create a WooCommerce Blocks extension starting point. It also showcases how to use some extensibility points, e.g. registering an inner block in the Checkout Block, applying filters to certain texts such as the place order button, using Slot/Fill and how to change the behaviour of the Store API.

There is also this page that might come in handy https://github.com/woocommerce/woocommerce-blocks/tree/trunk/packages/checkout/blocks-registry#registering-a-block

**Comment by nvgandhi123** [comment]
@ralucaStan many Thanks for your example. I have tried it and get some success.

But have one problem that I can not get, I have modified example to move field to checkout field block using below
"parent": ["woocommerce/checkout-fields-block"],

It is successfully moved but when I reorder it from admin, Admin is shown field ok, But frontend always shows to end even I have moved. Please see the below screenshot, Any insight will useful for me.

![image](https://user-images.githubusercontent.com/23288565/219850354-0ce6dc05-b636-4271-ba57-7066ccbcc24e.png)


But it is not reflected to the fronted after compiling and regenerating the component. Please see below

![image](https://user-images.githubusercontent.com/23288565/219850259-0ddcbddc-6260-4e25-bd26-d9eb4711e5be.png)

Any suggestions and insight will help.

Thanks

**Comment by nvgandhi123** [comment]
@senadir 

Any help would be appreciated if you provide an example of any call back after checkout button clicked and validation is fired and complete. I see there are callbacks there in the checkout block but did not get how to use it.

Thanks

**Comment by opr** [comment]
@nvgandhi123 I believed running the callback on this event is only available via the payment method interface right now. We should look into exposing these events to inner blocks that aren't payment methods, @senadir @ralucaStan

**Comment by nvgandhi123** [comment]
@opr Thanks for letting me know. Please update me once those hooks are available. or Any alternative as I want to know click event on checkout. @senadir @ralucaStan
