### ISSUE TITLE
Styles for products are different from every block

### ISSUE THREAD

**Issue by hike734** [woocommerce/woocommerce-gutenberg-products-block#8121]
## What do you like about the Cart & Checkout blocks?
I like how clean they look compared to the old standard shortcodes for sure. It's nice to be able to customize the interface somewhat as well.

## What do you think is missing from the Cart & Checkout blocks?
Two issues that I have right now are as follows: 

1. The styles vary across all of the blocks that I can tell. I have the Woocommerce Colors plugin that gives me control over the "Add to Cart" button styles and that affects the Products block, but not the store itself (any more) and I'm not sure what's up with the "Cart Cross-Sells Products" block. That uses headings for the product title and another style for the buttons. Can there be a way to use the same CSS style for all of the woocommerce buttons in a site regardless of the block?
2. I use Mailster for my newsletter and the checkbox that works with the shortcode doesn't work with the block. Not sure if that's functionality that you can recognize or that they need to update compatibility with the Checkout Block

**Comment by senadir** [comment]
For Mailster, they need to integrate the plugin with Checkout block for it to work.

For styling, we're planning to work on unifying all button styles across blocks, I filled an issue to make the cross sell block more consistent, thank you for your feedback :D
