### ISSUE TITLE
Icon + text scaling on Mini Cart and My Account block 

### ISSUE THREAD

**Issue by vivialice** [woocommerce/woocommerce-gutenberg-products-block#8128]
Hey folks! On the back of a chat I had with @danielwrobert, I wanted to highlight a visual inconsistency I noticed with text + icon scaling controls. 

View example, `Customer Account` and `Mini Cart` blocks both set to Typography scale `Small`: 
<img width="313" alt="Screenshot 2023-01-09 at 15 32 41" src="https://user-images.githubusercontent.com/9888201/211345786-a89450a3-affa-40e0-98e0-6f82f1b8da5a.png">
<img width="283" alt="Screenshot 2023-01-09 at 15 39 01" src="https://user-images.githubusercontent.com/9888201/211347191-59c4688f-a150-4c27-bf59-67f4c9fa66d4.png">

We came to the decision that for now, **we will maintain scaling the icon alongside the text using the typography settings**. However, I have noticed when the two blocks are side-by-side, the two don't look like they are using the same scale setting. 

Could we check what the settings are here and match the two? Eventually, this will also apply to the search icon scaling. 
- The mini cart icon looks slightly too big compared to the customer account icon  
- In the screenshot above, it looks like we should scale the customer account icon to visually be balanced with the mini cart icon.

Since we are keeping the settings simple, the defaults should work together well visually without having to edit the two differently. I'm including some real-world examples of where we should be aiming towards:

**01**
<img width="235" alt="Screenshot 2023-01-09 at 16 08 26" src="https://user-images.githubusercontent.com/9888201/211353795-a8b4ec44-d56d-4cec-b09b-be5927a5fbed.png">

**02**
<img width="142" alt="Screenshot 2023-01-09 at 16 08 40" src="https://user-images.githubusercontent.com/9888201/211353837-6c573ea0-125b-4719-a8f9-55356d44a968.png">

**03**
<img width="227" alt="Screenshot 2023-01-09 at 16 08 55" src="https://user-images.githubusercontent.com/9888201/211353891-122d3e1a-ec75-417e-b66a-0c6c5985e278.png">

**04**
<img width="281" alt="Screenshot 2023-01-09 at 16 09 06" src="https://user-images.githubusercontent.com/9888201/211353928-900a755c-9d0b-4dcc-9317-79a41a89fb95.png">

**Comment by Aljullu** [comment]
When working on this, we should keep an eye on how any changes we introduce impact existing stores which are already making use of these blocks.
