### ISSUE TITLE
Filter by Price: slider position is out of sync with the thumb

### ISSUE THREAD

**Issue by kmanijak** [woocommerce/woocommerce-gutenberg-products-block#8129]
## Describe the bug
There's a UI glitch in Filter by Price. When moving the thumb, the slider doesn't exactly follow the thumb position. It matches the position every couple of steps (see the screenshots) and is out of sync in between

## To reproduce
Prerequisites:
- Use a wide screen (min. 1500px wide). Issue occurs on a smaller screens as well, but the position difference is smaller than the  thumb radius, hence the glitch is "covered" by the thumb.

1. Create a new page
2. Add a Filter by Price block
3. Save and see go to frontend
4. Move the thumbs slowly

## Expected behavior

Slider is following the thumbs

## Screenshots/videos

- 1500px wide page
<img width="1451" alt="Screen Shot 2023-01-09 at 17 37 39 PM" src="https://user-images.githubusercontent.com/20098064/211359978-eb5c6b1f-632a-4823-a73c-fdbf66765321.png">

- 2300px wide page (on the video, you can see that every couple of steps slider and thumb go in sync and then the position difference increases until the next step when they sync again)
https://user-images.githubusercontent.com/20098064/211360425-5f9126ce-365c-47f1-8184-862bb55308b8.mov

### WordPress

-   WordPress version: 6.1.1
-   Gutenberg version (if installed): 
-   WooCommerce version: 7.2.0
-   WooCommerce Blocks version: 9.2.0

### Desktop (please complete the following information):

-   OS: macOS
-   Browser: Chrom

**Comment by Sidsector9** [comment]
Hello, I would like to work on this issue
