### ISSUE TITLE
All Products: "Impossible" to save customizations due to an erroneous re-render

### ISSUE THREAD

**Issue by danieldudzic** [woocommerce/woocommerce-gutenberg-products-block#8139]
## Describe the bug
In the **edit** mode: When you have a block selected that’s not **All Products** (for example inner block like the **Product Title**) and you try to (re)select **All Products** it triggers a re-render of the block, before any of the `Reset`, `Cancel` or `Done` can be executed.

The only way buttons can be "reached" is if you enter the **edit** mode and not select an inner block (and stay within the **All Products** block selection) and then select the `Done` button.

## Issues caused by this bug
woocommerce/woocommerce-blocks#3049 woocommerce/woocommerce#42526 woocommerce/woocommerce-blocks#7930

**Not reported**: We are currently hiding product element settings (for example: `alignment` for **Product Price** and **Rating** product elements) when used inside of the All Products block because of this bug (https://github.com/woocommerce/woocommerce-blocks/pull/7790#pullrequestreview-1200821814).

## Steps to reproduce the behavior:

1. Go to a new page and add the **All Products** block.
2. Click on the `pencil` icon to enter the `edit` mode.
3. Try to move inner blocks (product title, price etc.) around and select the `Done` button.
4. Notice your changes were not saved.

## Expected behavior

By preventing a re-render on the parent (**All Products**) (re)selection the the `Cancel`, `Reset`, `Done` buttons should be able to operate correctly.

## Video

https://user-images.githubusercontent.com/905781/211434127-19700bc0-2488-4787-891e-999c7623e497.mp4

### WordPress (please complete the following information):

-   WordPress version: 5.9, 6.0, 6.1.1
-   WooCommerce version: 7.2.2
-   WooCommerce Blocks version:  9.3.0

**Comment by dinhtungdu** [comment]
I tested several older versions of WooCommerce and WooCommerce block and this issue was introduced in WooCommerce Block 8.8.0. WC Blocks 8.7.5 bundled with WooCommerce 7.1.0 doesn't have this issue.

**Comment by dinhtungdu** [comment]
ad422287c095411d25fcebac4548b30d2f470a99 introduced the bug. I can't reproduce the issue with its previous commit (c75cf0fe998789fff38c0e58b99e8bc5adef5a04).
