### ISSUE TITLE
Featured Product block is invalidated when editing its HTML

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#814]
**To Reproduce**

1. Create a post and add a _Featured Product_ block.
2. Click on _Edit as HTML_.
3. Focus the HTML textarea.
4. Focus somewhere else (clicking outside the HTML textarea).
5. Notice the block is invalidated.

**Screenshots**
![Peek 2019-08-07 15-37](https://user-images.githubusercontent.com/3616980/62627282-6a50f900-b929-11e9-9068-6b78f5686067.gif)

This issue affects the _Featured Category_ block too.

**Comment by nerrad** [comment]
This should be fixed by #801 right?

**Comment by Aljullu** [comment]
@nerrad absolutely! It looks like #801 was merged to `master` and I was testing `release/2.3`. I added a comment in that PR about getting the changes to 2.3.

I also opened #816 since #801 was not including _Featured Category_ block.
