### ISSUE TITLE
ProductPrice story is broken

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#8145]
## To reproduce

1. Run `npm run storybook` and open the Storybook page.
2. Go to any of the _ProductPrice_ stories.
3. Notice an error appears:

![imatge](https://user-images.githubusercontent.com/3616980/211558887-cef05140-389f-446a-9cef-5855bdcf648e.png)

## Expected behavior

The component should be displayed correctly without an error.

**Comment by roykho** [comment]
Some work has already been done for this seen [here](https://github.com/woocommerce/woocommerce-blocks/pull/8049)

**Comment by Aljullu** [comment]
Right, actually this issue is a duplicate of #8048. Sorry for the confusion!
