### ISSUE TITLE
Selecting a block from the List view no longer switches views in Cart and Mini Cart

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#8148]
For blocks that have 2 views (Mini Cart, Cart), opening the list view and selecting a hidden view's block used to switch to that block. This doesn't seem to work anymore, I tested in 9.1.5 it worked fine. It's likely (but not confirmed) that this PR caused it https://github.com/woocommerce/woocommerce-blocks/pull/8006

This logic handled selecting the parent block
https://github.com/woocommerce/woocommerce-blocks/blob/7e9fcd52265d17fb63bc86dd3aae3a223846bbb4/assets/js/blocks/cart-checkout-shared/use-view-switcher.tsx#L56-L74
### Steps to reproduce

- Insert Cart block.
- Open List view (Control Option O or the list view icon in the top left).
- Select the empty cart.
- The view should switch.
This probably applies to selecting the block in different ways that I'm not aware of (all via the data store).

**Comment by ralucaStan** [comment]
Thank you @senadir for catching this regression.
I confirm #8006 is the culprit. CC @mikejolley 

Moving this to the next column
