### ISSUE TITLE
Safari: Proceed to Checkout jumps slightly when disabled

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#8159]
In safari, proceed to checkout button in Cart seems to recover its border when being disabled, causing it to jump. This is likely to happen in Checkout as well but isn't noticeable.

![image](https://user-images.githubusercontent.com/6165348/211819961-26378d8f-42ab-41ab-92ba-83a8f8d96571.png)

**Comment by ralucaStan** [comment]
Closing as I was not able to replicate
