### ISSUE TITLE
Update the minimum PHP version required to PHP 7.3+

### ISSUE THREAD

**Issue by ralucaStan** [woocommerce/woocommerce-gutenberg-products-block#8161]
The minimum PHP version required for WooCommerce [was bumped from 7.0 to 7.2 in WooCommerce 6.5 in May 2022](https://developer.woocommerce.com/2022/01/05/new-requirement-for-woocommerce-6-5-php-7-2/). Exactly one year later WooCommerce will take the next step: starting with version 7.7, scheduled for release in May 2023, WooCommerce will require PHP 7.3 or newer to work. More details in [this article](https://developer.woocommerce.com/2023/01/10/new-requirement-for-woocommerce-7-7-php-7-3/)

We need to update the minimum PHP version required for Blocks, currently at 7.0.

**Comment by opr** [comment]
This is fixed by the 10.0.0 release (https://github.com/woocommerce/woocommerce-blocks/pull/8990)
