### ISSUE TITLE
[Filter by attribute:widget] Calculate product count based on context

### ISSUE THREAD

**Issue by OC2PS** [woocommerce/woocommerce-gutenberg-products-block#8174]
## Describe the bug

As per [this](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/widgets/class-wc-widget-layered-nav.php#L337) - product count for attribute terms should be based on the page you're viewing. However, we see that all the count is based on the whole store.

## To reproduce

1. In Admin, add Filter by Attribute widget to your store
2. In frontend, notice that the count displayed is for shop-level instead of displaying the actual count based on the archive page you're viewing

## Expected behavior

* Product count for attribute terms should be based on the page you're viewing
* For example, if Blue is a color attribute term, and there are 3 Blue products in category A and 1 Blue product in category B, then on category A page, I expect to see product count for Blue as 3, and on category B page, I expect to see product count for Blue as 1 

## Actual behavior

Continuing the above example, the counts is based on shop-level availability and not the page you're currently viewing:
On either category's page, the count is shown as 4.

![Widget frontend](https://user-images.githubusercontent.com/17475174/211960769-a8e94580-93f3-419e-88b1-b413f051381e.png)

### WordPress (please complete the following information):

N/A

**Comment by kmanijak** [comment]
Hi @OC2PS , thanks a lot for taking a time to create this issue! 👍

We're aware of this problem and it's already in our backlog: https://github.com/woocommerce/woocommerce/issues/42542. Given that, I'll mark this issue as a duplicate and close it to keep the backlog organized. Please be aware, that closed issues can also still be commented on.

For future reference please use https://github.com/woocommerce/woocommerce/issues/42542 to track the status of this issue, thanks!
