### ISSUE TITLE
Style Book: old versions of the Filter by Attribute, Stock and Price are displayed

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#8175]
## To reproduce

0. With WordPress 6.2 (or a previous version with GB installed) and a block theme like [Twenty Twenty-Three](https://wordpress.org/themes/twentytwentythree/) enabled.
1. Go to Appearance > Editor and edit a template.
2. In the toolbar, select Styles (black and white circle) and then, Open Style Book (eye icon).
3. Go to the WooCommerce tab.
4. Notice the Filter by Attribute block displays an old version of the block with the option to Upgrade.

![Filter by Attribute block in the Style Book](https://user-images.githubusercontent.com/3616980/212303027-dcde3a93-67c4-4059-b99e-a6d296bece9d.png)

## Expected behavior

The most recent version of Filter by Attribute should be displayed, so there the banner to 'upgrade' the block is not displayed.

**Comment by nefeline** [comment]
By investigating https://github.com/woocommerce/woocommerce-blocks/issues/8178 it was possible to verify that the filter by attribute block is not the only one with this problem: in reality, we have the Attribute, Price and Stock Filters all with the same errors:

<img width="1216" alt="Screenshot 2023-01-23 at 02 15 50" src="https://user-images.githubusercontent.com/15730971/213952131-61f46f4c-9fd9-4929-8414-f46a6c500de3.png">

Based on the changes introduced on [#6978](https://github.com/woocommerce/woocommerce-blocks/pull/6978), these filter blocks were converted into parent blocks containing a core/heading block and the actual filter block, but the wrapper is not found when loaded in the context of the Style Book. The [isInsideFilterWrapper](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/blocks/filter-wrapper/upgrade.tsx#L26-L38) const is always false while on Style Book, but not in the editor.

Style Book uses the existing BlockPreview component to display a preview of every registered block in an iframe per block.

It is still unclear what would cause such behavior, we will continue the investigation within the next few days and share updates as soon as we have them.
