### ISSUE TITLE
Style Book: Product Search block displays an upgrade notice

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#8180]
## To reproduce

0. With WordPress 6.2 (or a previous version with GB installed) and a block theme like [Twenty Twenty-Three](https://wordpress.org/themes/twentytwentythree/) enabled.
1. Go to Appearance > Editor and edit a template.
2. In the toolbar, select Styles (black and white circle) and then, Open Style Book (eye icon).
3. Go to the WooCommerce tab.
4. Notice the Product Search block displays an _Upgrade block_ notice.

![Product Search block in Style Book](https://user-images.githubusercontent.com/3616980/212305277-f575ebc2-c8e0-4d9d-a523-0d3cc3fda598.png)

## Expected behavior

We should either:
1. Hide the Product Search block from the Style Book given that now it's just a variation of the Gutenberg Search block.
2. Fix the display so the _Upgrade block_ notice is not shown and the new version of the block is displayed.

**Comment by gigitux** [comment]
We should hide the `Product Search` block because we no longer support it. Unfortunately, at this stage, Style Book shows all the blocks even if they have inserter option set to false. I created an issue on Gutenberg https://github.com/WordPress/gutenberg/issues/47440

**Comment by Aljullu** [comment]
@gigitux did you mean https://github.com/WordPress/gutenberg/issues/47440 instead? :slightly_smiling_face:

**Comment by gigitux** [comment]
@Aljullu Yes!
