### ISSUE TITLE
Create the Single Product Details block

### ISSUE THREAD

**Issue by nefeline** [woocommerce/woocommerce-gutenberg-products-block#8186]
Create a block version of the product details (visible on the single product template), so merchants can add the product description, information, and reviews to their stores.

| Property | Value |
|---------|---------|
| Block title | Product Details |
| Block description | TBD |
| Block slug | `product-details` |
| Block file location | `assets/js/blocks/product-details/` |
| Block class location | `src/BlockTypes/ProductDetails.php` |
| Style | <ul> <li> Typography <li> Color <li> Spacing </ul> |
| Visibility | Woocommerce Core |

# Tabs

## Details:

| Property | Value |
|---------|---------|
| Equivalent template file | [`woocommerce/templates/single-product/tabs/tabs.php`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/single-product/tabs/tabs.php) |
| Equivalent template function | [`woocommerce_default_product_tabs()`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/wc-template-functions.php#L1852) |

## Screenshot:

<img width="650" alt="Screenshot 2023-01-15 at 20 19 39" src="https://user-images.githubusercontent.com/15730971/212562386-709252a7-af2f-4193-bdd2-ba34c68adc3f.png">

# Description

## Details:

| Property | Value |
|---------|---------|
| Equivalent template file | [`woocommerce/templates/single-product/tabs/description.php`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/single-product/tabs/description.php) |
| Equivalent template function | [`the_content()`](https://github.com/WordPress/WordPress/blob/master/wp-includes/post-template.php#L245) |

## Screenshot:

<img width="650" alt="Screenshot 2023-01-15 at 19 34 39" src="https://user-images.githubusercontent.com/15730971/212560502-29d98c62-a6e5-4db6-a6fc-cb43a9fd0140.png">

# Additional information

## Details:

| Property | Value |
|---------|---------|
| Equivalent template file | [`woocommerce/templates/single-product/tabs/additional-information.php`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/single-product/tabs/additional-information.php) |
| Equivalent template function | [`wc_display_product_attributes()`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/wc-template-functions.php#L3462) |

## Screenshot:

<img width="650" alt="Screenshot 2023-01-15 at 19 45 11" src="https://user-images.githubusercontent.com/15730971/212560745-9e42555f-bda0-48ee-ab52-f91b18915d89.png">

# Reviews

## Details:

| Property | Value |
|---------|---------|
| Equivalent template file | [`woocommerce/templates/single-product-reviews.php`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/single-product-reviews.php) |
| Equivalent template function (for listing existing reviews) | [`wp_list_comments()`](https://github.com/WordPress/WordPress/blob/master/wp-includes/comment-template.php#L2066) and [`woocommerce_comments()`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/wc-template-functions.php#L1936) |
| Equivalent template function (for submitting a new review) | [`comment_form()`](https://github.com/WordPress/WordPress/blob/master/wp-includes/comment-template.php#L2325) |

## Screenshot:

<img width="650" alt="Screenshot 2023-01-15 at 19 45 29" src="https://user-images.githubusercontent.com/15730971/212560746-cf944144-b564-4cbe-8a24-3f821330b67a.png">

**Comment by nefeline** [comment]
Hey @vivialice ! Would you please update the Block Title & Description listed on the description of this issue with the expected copy? A few additional questions:

- Did we decide on the appropriate placeholder for the editor view for this block?
- Did we decide on whether we’ll re-utilize the existing classic template layout (including a tabbed container) or refresh with a new design that displays reviews separately outside of a tabbed container?

Thanks!

**Comment by tomxygen** [comment]
In my stores I use a PHP snippet to place reviews below product description instead of using the tab switcher.
I wish I could do the same with Blocks.
