### ISSUE TITLE
store/cart/add-item variation doesn't work with ad-hoc (local) attributes

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#8187]
When adding a variable product via Store API, you have the choice of using:

- Directly using the variation id.
- Using the parent variable product ID + variation data array.

That array can be in the shape of [{ attribute: "string", value: "string"}...] in which attribute is the slug, and value is the name, you can get those information from the product's variation section in store/products/

However, this doesn't work if a variation is an ad-hoc one (inline variations that you create on the product page instead of global one).

This is because the term has no id or taxonomy to be matched against, and `sanitize_variation_data` seems to throw that one away. Bypassing `sanitize_variation_data` and formatting the data manually to go straight to `find_matching_product_variation` still didn't seem to work, so I'm tempted to assume that `find_matching_product_variation` is the one that doesn't support ad-hoc attributes.

I'm not sure if this is expected behavior or a bug, cc @mikejolley

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/blob/466d93e3efede61f36d9ece439524a7c8790b7f1/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php#L1093-L1100

It doesn't make it obvious if meta attributes are supported. The attribute must be marked for variation use however, which also lines up with our `sanitize_variation_data` function. 

`sanitize_variation_data` doesn't seem to care if its a taxonomy or not; it has handling for both types. Maybe you have a different issue here? Special characters?

**Comment by senadir** [comment]
I wrote a long response to a reproduce steps, but I wasn't able to reproduce it at the end 😅 It worked fine, you need to provide the exact name you have in the product page (case-sensitive).
