### ISSUE TITLE
Create the Add to Cart block

### ISSUE THREAD

**Issue by nefeline** [woocommerce/woocommerce-gutenberg-products-block#8188]
Create a block version of the add-to-cart form available on single product templates.

| Property | Value |
|---------|---------|
| Block title | Add-to-cart button |
| Block description | Display a button so the customer can add a product to their cart. Options will also be displayed depending on product type. e.g. quantity, variation. |
| Block slug | `add-to-cart` |
| Block file location | `assets/js/blocks/product-add-to-cart/` |
| Block class location | `src/BlockTypes/AddToCart.php` |
| Equivalent template function | [`woocommerce_template_single_add_to_cart()`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/wc-template-functions.php#L1686) |
| Style | <ul> <li> Typography <li> Color <li> Spacing </ul> |
| Visibility | Woocommerce Core |

The add-to-cart button template can vary depending on the product type:

# Simple Product

## Details:

| Property | Value |
|---------|---------|
| Equivalent template file | [`woocommerce/templates/single-product/add-to-cart/simple.php`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/single-product/add-to-cart/simple.php) |
| Equivalent template function | [`woocommerce_simple_add_to_cart()`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/wc-template-functions.php#L1696) |

## Screenshot:

<img width="285" alt="Screenshot 2023-01-15 at 22 16 35" src="https://user-images.githubusercontent.com/15730971/212567786-27f408dd-cf36-4a7c-aeca-bf72f48a8065.png">

# Grouped Product

## Details:

| Property | Value |
|---------|---------|
| Equivalent template file | [`woocommerce/templates/single-product/add-to-cart/grouped.php`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/single-product/add-to-cart/grouped.php) |
| Equivalent template function | [`woocommerce_grouped_add_to_cart()`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/wc-template-functions.php#L1705) |

## Screenshot:

<img width="380" alt="Screenshot 2023-01-15 at 22 20 53" src="https://user-images.githubusercontent.com/15730971/212567937-0b5eb9d2-6190-4996-97cd-d64f812332cc.png">

# Variable Product

## Details:

| Property | Value |
|---------|---------|
| Equivalent template file | [`woocommerce/templates/single-product/add-to-cart/variable.php`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/single-product/add-to-cart/variable.php) |
| Equivalent template function | [`woocommerce_variable_add_to_cart()`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/wc-template-functions.php#L1727) |

## Screenshots:

<img width="290" alt="Screenshot 2023-01-15 at 22 28 22" src="https://user-images.githubusercontent.com/15730971/212568236-b2f1b291-a7b5-4c0b-9a4a-65043aef1dfc.png">

<img width="549" alt="Screenshot 2023-01-15 at 22 27 06" src="https://user-images.githubusercontent.com/15730971/212568182-998fd48e-6568-4861-b34e-b1203d5f7f8d.png">

# External Product

## Details:

| Property | Value |
|---------|---------|
| Equivalent template file | [`woocommerce/templates/single-product/add-to-cart/external.php`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/single-product/add-to-cart/external.php) |
| Equivalent template function | [`woocommerce_external_add_to_cart()`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/wc-template-functions.php#L1752) |

## Screenshot:

<img width="179" alt="Screenshot 2023-01-15 at 22 24 55" src="https://user-images.githubusercontent.com/15730971/212568094-b2c0f75d-0899-41cb-b087-ffcf1ced5d0d.png">

**Comment by nefeline** [comment]
Hey @vivialice ! Would you please update the Block Title & Description listed on the description of this issue with the expected copy? Do we have an appropriate placeholder content for the editor view of this block already?

Thanks!

**Comment by vivialice** [comment]
Hey @nefeline 😄 Here is a copy suggestion for this block: 

**Block title:**
Add-to-cart button

**Description**
Display a button so the customer can add a product to their cart. Options will also be displayed depending on product type. e.g. quantity, variation.

I don't have a design yet for the placeholder for this block. I can add it to my priorities, when would you need it?

**Comment by nefeline** [comment]
Thank you so much @vivialice 🙌 !

> I don't have a design yet for the placeholder for this block. I can add it to my priorities, when would you need it?

I plan to start working on this next week (as soon as I finish my Porter rotation), but development can progress without it, so probably in 1-2 weeks should be a-ok!

**Comment by vivialice** [comment]
Okay, thanks @nefeline !

**Comment by vivialice** [comment]
👋 Hi @nefeline Thank you for your patience! I have selected a version for you to move ahead with - which is close to your original solution actually. The copy is slightly amended in the notice. 

<img width="493" alt="Screenshot 2023-01-31 at 17 31 47" src="https://user-images.githubusercontent.com/9888201/215838111-e41f4514-f91a-4145-85c9-1f48de0ca446.png">
