### ISSUE TITLE
Research how extensions extend Single Product template

### ISSUE THREAD

**Issue by gigitux** [woocommerce/woocommerce-gutenberg-products-block#8204]
We need to research how extensions extend the Single Product template.

As @dinhtungdu did for the Archive Templates, we have to limit our investigation to the extensions and themes on www.woocommerce.com

Also, [this page](https://storecustomizer.com/woocommerce-product-page-hooks-visual-guide/) could be a great starting point to see all the hooks available on the Single Product page.

**Comment by gigitux** [comment]
Hook usage by extensions in WooCommerce.com:

|Hook                                      |Count|
|------------------------------------------|-----|
|woocommerce_before_add_to_cart_button     |109  |
|woocommerce_after_add_to_cart_button      |45   |
|woocommerce_before_single_product         |41   |
|woocommerce_single_variation              |40   |
|woocommerce_after_single_product_summary  |36   |
|woocommerce_before_add_to_cart_form       |34   |
|woocommerce_before_single_product_summary |26   |
|woocommerce_simple_add_to_cart            |21   |
|woocommerce_after_add_to_cart_form        |17   |
|woocommerce_product_thumbnails            |14   |
|woocommerce_product_meta_end              |12   |
|woocommerce_variable_add_to_cart          |11   |
|woocommerce_after_single_product          |11   |
|woocommerce_after_main_content            |10   |
|woocommerce_before_main_content           |8    |
|woocommerce_product_meta_start            |5    |
|woocommerce_grouped_add_to_cart           |4    |
|woocommerce_external_add_to_cart          |2    |
|woocommerce_product_additional_information|2    |
|woocommerce_before_quantity_input_field   |1    |
|woocommerce_after_quantity_input_field    |1    |
|woocommerce_review_after_comment_text     |1    |
|woocommerce_sidebar                       |0    |
|woocommerce_share                         |0    |
|woocommerce_product_after_tabs            |0    |
|woocommerce_review_before                 |0    |
|woocommerce_review_before_comment_meta    |0    |
|woocommerce_review_meta                   |0    |
|woocommerce_review_before_comment_text    |0    |
|woocommerce_review_comment_text           |0    |

**Comment by gigitux** [comment]
Also, the entire list of the hook used in the Single Product Page is visible [here](https://www.businessbloomer.com/woocommerce-visual-hook-guide-single-product-page/#tab-additional_information)

**Comment by gigitux** [comment]
Also, the entire list of the hook used in the Single Product Page is visible [here](https://www.businessbloomer.com/woocommerce-visual-hook-guide-single-product-page/#tab-additional_information)

**Comment by gigitux** [comment]
As @dinhtungdu noticed, we can avoid adding compatibility with the hook `woocommerce_sidebar`. For the rest, we have to work on a compatibility layer. I think that the observations done on #8064 are the same here.

What do you think? @nerrad @Aljullu

**Comment by Aljullu** [comment]
Yes, it makes sense to me. My only thought is that given that for some blocks we will be using the PHP template for now (Add to Cart form, Product Gallery, etc.), I expect that some of those hooks will already be supported and will not need to be in the compatibility layer.

**Comment by gigitux** [comment]
> My only thought is that given that for some blocks we will be using the PHP template for now (Add to Cart form, Product Gallery, etc.),

Yeah, I completely agree! I just added them for completeness. Also, the list will be helpful if/when we decide not to use the PHP template anymore 💪.

**Comment by gigitux** [comment]
I'm going to close this issue! The research is done! 💪
