### ISSUE TITLE
Provide a way to easily switch to the blockified Single Product Template

### ISSUE THREAD

**Issue by gigitux** [woocommerce/woocommerce-gutenberg-products-block#8208]
We have to provide an easy way for the merchant to switch to the blockified Single Product Template. As it is suggested in https://github.com/woocommerce/woocommerce-blocks/issues/8066, we can use the button on the current `Classic Product` block:

![image](https://user-images.githubusercontent.com/4463174/212722423-0d3cfc83-6235-4345-9516-4a06d13618c8.png)

**Comment by kmanijak** [comment]
Part of the job has been done within https://github.com/woocommerce/woocommerce-blocks/pull/8248. While working on the blockifying Product Archive template, there's already established mechanism for the conversion of the classic template to blocked version.

In scope of this task is to work on the function in [`assets/js/blocks/classic-template/single-product.ts` file](https://github.com/woocommerce/woocommerce-blocks/pull/8248/files#diff-84c57bebfa435f9bce1472532eb63de9bacbd17ba965b44cf3dca77fad25e189), while preserving the interface. You can base the work on [`assets/js/blocks/classic-template/archive-product.ts` file](https://github.com/woocommerce/woocommerce-blocks/pull/8248/files#diff-ce4f6ffb07a9721751958ad15a696d9630b3dc29513015225fd4218d3e6f978e).

(_Keep in mind those are links to the PR in review, so it's still a subject to change, but the overall strategy should be preserved_)
