### ISSUE TITLE
Local pickup placeholders are not visible in the editor

### ISSUE THREAD

**Issue by tarunvijwani** [woocommerce/woocommerce-gutenberg-products-block#8212]
## Describe the bug

Local pickup placeholders are not visible in the editor when there is no shipping method in WC settings 

## To reproduce

1. Enable local pickup. 
2. Remove all the shipping methods from WC settings
3. Open the Checkout block page editor
4. Notice placeholders and inner blocks for the local pickup are not visible

## Expected behavior

Notice placeholders and inner blocks for the local pickup should be visible. 

## Screenshots

| Expected | Actual |
|---|---|
|![image](https://user-images.githubusercontent.com/11503784/212721449-4a83896f-55ac-4124-ab75-ac2300a86e90.png)|![image](https://user-images.githubusercontent.com/11503784/212721568-8b76ba5b-a0ae-4224-90aa-1ec4000b9f32.png)|

Slack: p1673880223140939-slack-C02UBB1EPEF

**Comment by senadir** [comment]
This was fixed by #8207
