### ISSUE TITLE
Cart and Checkout field-request to edit

### ISSUE THREAD

**Issue by Cliffgrainger** [woocommerce/woocommerce-gutenberg-products-block#8214]
## What do you like about the Cart & Checkout blocks?
The new layout is and ability to change the Checkout for an alternative is really useful. 

## What do you think is missing from the Cart & Checkout blocks?
I would love the ability to edit or add additional fields. For instance my client wants to ask the customer to indicate whether special conditions re delivery exist. They deliver large items to agricultural, farms and equine stables and need to know if they have the facility to unload otherwise we send a craned lorry as opposed to a standard one. A checkbox indicating same or to edit the 'Note field " would be ideal

**Comment by nielslange** [comment]
Hello @Cliffgrainger 👋

Thanks for your feature request. We appreciate you sharing your idea with us. We’re glad to inform you that this feature is one of our goals for this year. Although we can’t give you a specific timeline for its implementation, we consider it an important feature and will be working on it. Please bear with us and keep an eye out for updates on this issue.

As a temporary solution, you could add a paragraph above the Order Note block, to request additional information from the sellers regarding the shipping. Such a message could look like this:

<img width="2880" alt="Screenshot 2023-01-23 at 21 43 15" src="https://user-images.githubusercontent.com/3323310/214068010-06e9b259-e89a-4506-9034-0dbfd42331f5.png">

I'm closing this issue for now, but as mentioned before, please keep an eye out for updates on this issue.
