### ISSUE TITLE
Stripe + WC Block: After having a card decline, working card cannot be processed

### ISSUE THREAD

**Issue by namiokuzono** [woocommerce/woocommerce-gutenberg-products-block#8215]
## Describe the bug

When a working card is tried at the WC Blocks Checkout page right after the non-working card, the Checkout page returns 400 API response. https://cln.sh/BMbT2KqW 

## To reproduce

1. Try placing an order with the test card number: ` 4000 0000 0000 0002 ` 
2. This returns with a generic "The card was declined" error message (as expected)
3. Do not load the Checkout page and proceeds to the next step
4. Try placing an order with the test card number: ` 4000 0000 0000 3220 ` (3DS required)
5. Error occurs: "Sorry, we are unable to process your payment at this time. Please retry later." (or "Your card has been declined.")

Tested with shortcode based WooCommerce Checkout page, and this issue is not reproduced. 

## Expected behavior

At the step 5 in above, you should be able to place an order with no problem. 

## Screenshots

https://cln.sh/phkMvcHv

### WordPress (please complete the following information):

- WP Version: 6.1.1
- WC Version: 7.3.0
- WC Blocks Version: ✔ 9.3.0
- Language: en_US

### Desktop (please complete the following information):

-   OS: 13.2 (a) Beta (22D7750270d)
-   Browser Chromium

**Comment by namiokuzono** [comment]
Originally reported by a user via 5871599-zen

**Comment by tarunvijwani** [comment]
@namiokuzono Thank you for reporting this. Unfortunately, I couldn't replicate the issue on my end. Here is the screen recording:


https://user-images.githubusercontent.com/11503784/213526266-fe3f5df2-ca43-42ae-b665-112447ac19e4.mov


I'd really appreciate it if you could help me with the link to the test site where you could reproduce this issue. 

Looking forward to hearing back from you.

**Comment by namiokuzono** [comment]
Hi @tarunvijwani ! Thank you for looking into this! 

I have freshly installed a new site again (since the last one was deleted) and retried the workflow, and still able to reproduce the issue. 

Could you put this product in the cart:
https://verbal-porpoise.jurassic.ninja/product/test/
Then try going over the workflow once again and see what happens? 

Here is the video recording:  https://cln.sh/drd3Npt6

<details>
<summary>Click to expand SSR</summary>
`
### WordPress Environment ###

WordPress address (URL): https://verbal-porpoise.jurassic.ninja
Site address (URL): https://verbal-porpoise.jurassic.ninja
WC Version: 7.3.0
REST API Version: ✔ 7.3.0
WC Blocks Version: ✔ 9.4.1
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.55 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.33
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.3.0
WC Database Prefix: wp_
Total Database Size: 5.35MB
Database Data Size: 3.75MB
Database Index Size: 1.60MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.45MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.16MB + Index: 0.13MB + Engine InnoDB
wp_posts: Data: 0.20MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 46
nav_menu_item: 102
page: 22
post: 39
product: 1
revision: 2
shop_order: 3
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (5) ###

Companion Plugin: by Osk – 1.29
WooCommerce Blocks: by Automattic – 9.4.1
WooCommerce Stripe Gateway: by WooCommerce – 7.0.2
WooCommerce: by Automattic – 7.3.0
WordPress Importer: by wordpressdotorg – 0.8

### Inactive Plugins (3) ###

Akismet Anti-Spam: by Automattic – 5.0.1
Hello Dolly: by Matt Mullenweg – 1.7.2
Jetpack: by Automattic – 11.7.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #1364 - /shop/
Cart: #1365 - /cart/
Checkout: #1366 - /checkout/
My account: #1367 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Three
Version: 1.0
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2023-01-25 08:03:27 +00:00
Options: ✔
Notes: 37
Onboarding: skipped

### Action Scheduler ###

Complete: 16
Oldest: 2023-01-24 08:13:31 +0000
Newest: 2023-01-24 08:24:48 +0000

Pending: 1
Oldest: 2023-01-25 08:03:39 +0000
Newest: 2023-01-25 08:03:39 +0000


### Status report information ###

Generated at: 2023-01-24 08:25:27 +00:00
`
</details>

**Comment by mikejolley** [comment]
I was able to replicate this, however, payment went through successfully with the card number `378282246310005` which has 3D Secure disabled. This leads me to believe the issue is due to the 3D secure implementation in the Stripe Gateway—perhaps missing for the Checkout Block implementation?

The error you're seeing is the generic error Stripe Gateway returns if the requests and retries are unsuccessful. This does not appear to be a bug with block checkout itself.

I will transfer this issue to the Stripe repository for feedback. Thanks.

**Comment by mikejolley** [comment]
Issue moved to [woocommerce/woocommerce-gateway-stripe #2537](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2537) via [**Zenhub**](https://www.zenhub.com/)
