### ISSUE TITLE
README: "Writing Your First Block Type" tutorial redirects to Gutenberg project when clicked

### ISSUE THREAD

**Issue by thealexandrelara** [woocommerce/woocommerce-gutenberg-products-block#8224]
The ["Writing Your First Block Type" tutorial](https://wordpress.org/gutenberg/handbook/designers-developers/developers/tutorials/block-tutorial/) link inside the [Getting started with block development](https://github.com/woocommerce/woocommerce-blocks#getting-started-with-block-development) section of the project 's README is being redirected to the Gutenberg project instead of the tutorial.

Is there a new link that it should refer to? Maybe [Create a basic block](https://developer.wordpress.org/block-editor/how-to-guides/block-tutorial/writing-your-first-block-type/) from the Block Editor Handbook?

**Comment by nielslange** [comment]
Good catch, @thealexandrelara! Besides [Create a basic block](https://developer.wordpress.org/block-editor/how-to-guides/block-tutorial/writing-your-first-block-type/) from the Block Editor Handbook, I wonder if we should also refer to [@wordpress/create-block](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-create-block/) also from the Block Editor Handbook. Personally, I find the second resource a bit more helpful, but the first one is equally important to understand what the tool from the second link is doing.

**Comment by tarunvijwani** [comment]
Thank you for reporting it @thealexandrelara. We have updated the link in our docs. 👍
