### ISSUE TITLE
Fix inconsistent border focus styles

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#8227]
## Describe the bug

During a call with @ralucaStan, we noticed that the border focus styles of the various input elements on the Checkout block are inconsistent. This issue aims to implement consistent border focus styles. 

## To reproduce

1. Add a product to the cart and go to the Checkout page.
2. Use the tab to focus various input elements.
3. See that the border focus of `input[type="text"]`, `input[type="checkbox"]`, `input[type="radio"]` and `textarea` are different.

## Expected behavior

- All border focus styles should be consistent. 
- `textarea` should use the same border focus style as `input[type="text"]` → black outline and no outline offset
- `input[type="radio"]` should use the same border focus style as `input[type="text"]` → black outline and outline offset

### `input[type="text"]`

<table>
<tr>
<td>Regular:
<br><br>

<img width="794" alt="Screenshot 2023-01-18 at 10 20 36" src="https://user-images.githubusercontent.com/3323310/213075611-9bd69510-7662-4ef2-ba65-7f977f76ecbe.png">
</td>
<td>Current border focus:
<br><br>

<img width="803" alt="Screenshot 2023-01-18 at 10 21 01" src="https://user-images.githubusercontent.com/3323310/213075729-85c58536-8ee8-473a-939e-7559c19a630a.png">
</td>
</tr>
</table>

### `textarea`

<table>
<tr>
<td>Regular:
<br><br>

<img width="777" alt="Screenshot 2023-01-18 at 10 26 43" src="https://user-images.githubusercontent.com/3323310/213076400-fcee233f-e4ed-4451-a930-31018421dfa0.png">
</td>
<td>Current border focus:
<br><br>

<img width="783" alt="Screenshot 2023-01-18 at 10 26 59" src="https://user-images.githubusercontent.com/3323310/213076438-73aa57a4-6ed6-4fa9-bd9d-5c39f31d7c13.png">
</td>
<td>Expected border focus:
<br><br>

<img width="783" alt="Screenshot 2023-01-18 at 10 36 01" src="https://user-images.githubusercontent.com/3323310/213077574-768f2ca3-76c1-4c91-b972-aab367ec4db0.png">
</td>
</tr>
</table>

### `input[type="checkbox"]`

<table>
<tr>
<td>Regular:
<br><br>

<img width="236" alt="Screenshot 2023-01-18 at 10 28 33" src="https://user-images.githubusercontent.com/3323310/213076667-7e9346cb-8e02-4882-953e-bb71a84d4251.png">
</td>
<td>Current border focus:
<br><br>

<img width="240" alt="Screenshot 2023-01-18 at 10 29 03" src="https://user-images.githubusercontent.com/3323310/213076728-908c4c6f-e60a-4f4a-8ed7-5a592770190e.png">
</td>
</tr>
</table>

### `input[type="radio"]`

<table>
<tr>
<td>Regular:
<br><br>

<img width="247" alt="Screenshot 2023-01-18 at 10 30 16" src="https://user-images.githubusercontent.com/3323310/213076863-0ff0f067-d999-4302-9dec-3cdc0a84febe.png">
</td>
<td>Current border focus:
<br><br>

<img width="239" alt="Screenshot 2023-01-18 at 10 30 33" src="https://user-images.githubusercontent.com/3323310/213076900-e4578ca3-e5fc-4946-9440-aeb56369941a.png">
</td>
<td>Expected border focus:
<br><br>

<img width="239" alt="Screenshot 2023-01-18 at 10 33 43" src="https://user-images.githubusercontent.com/3323310/213077291-c4d9df48-a0c7-481e-b8b2-2099fe781046.png">
</td>
</tr>

</table>

cc: @elizaan36

**Comment by elizaan36** [comment]
Good catch! This makes sense to me.

**Comment by nielslange** [comment]
> Good catch! This makes sense to me.

@elizaan36 In #9861, @webaxones raised concerns regarding the accessibility of focused input fields. What are your thoughts on adding an `outline-offset: 4px;` to having a clear distinction between the normal and the focus state:

<img width="361" alt="Screenshot 2023-06-19 at 12 01 18" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/8b11a642-f123-4d35-a937-2e5550d3372b">

> **Note**
> In the example above, I removed our custom styles and only added the `outline-offset: 4px;` definition.

**Comment by elizaan36** [comment]
hey @nielslange I can understand the accessibility concern. It's not something we have used for form fields anywhere in the shopper experience so I'd hold off on adding the offset to the form fields focus state for now. I'm afraid it would add a lot of noise as the user completes each step of the form.

**Comment by webaxones** [comment]
The very concept of web accessibility is to make a site usable by everyone, regardless of the user's disability, and the visibility of input fields on focus should indeed use more "visual noise" for visually impaired individuals. Reducing this noise on a significant part of the form is not only a serious accessibility mistake, but also a major UX error by creating inconsistency with the input fields present on other pages of the site.

**Comment by nielslange** [comment]
> It's not something we have used for form fields anywhere in the shopper experience so I'd hold off on adding the offset to the form fields focus state for now.

That's correct for WooCommerce Blocks, @elizaan36. That said, https://woocommerce.com/checkout/ and https://woocommerce.com/products/ are showing these focus states.

<table>
<tr>
<td>Before:
<br><br>

<img width="1512" alt="Screenshot 2023-06-29 at 10 28 26" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/4ac6294f-4a94-45cd-bc26-57cab69cc627">
</td>
<td>After:
<br><br>

<img width="1512" alt="Screenshot 2023-06-29 at 10 28 42" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/19e39d89-a55b-45b2-8f83-ea5ecbd2d71f">
</td>
</tr>
</table>

**Comment by ralucaStan** [comment]
Let's focus on this ticket on aligning the focus styles. Once all styles are similar we can discuss and change all of them as we see fit.

We appreciate the suggestion @webaxones so I suggest discussing it in a separate ticket, so we can stick with the scope of the ticket.

**Comment by webaxones** [comment]
So, by reopening the first issue @ralucaStan ? 
https://github.com/woocommerce/woocommerce-blocks/issues/9861

**Comment by ralucaStan** [comment]
Oh, I wasn't aware there is another issue. I'd keep that open to collect feedback. Niels was right that it's related, but we'd still need buy-in from the team on the proposal. Thank you for your flexibility.

**Comment by webaxones** [comment]
Ok I'll let you handle that :)
Remember: accessibility is important for equality between people.
And if you think in terms of sales as a priority: the elderly who are likely to have vision problems have the greatest purchasing power.
