### ISSUE TITLE
Optional Field Salutation on Checkout

### ISSUE THREAD

**Issue by masteradhoc** [woocommerce/woocommerce-gutenberg-products-block#8229]
## Is your feature request related to a problem? Please describe.
From time to time we always get request from clients to add a salutation field in the woocommerce checkout.
This mostly always happens when the orders should automatically get sent to ERP or custom data to CRM Systems.
Often there these fields are kind of required and needed to have a good dataset.

## Describe the solution you'd like
It would be great if you could add a salutation field that is optional. by default it shouldnt be added.
in that way we could have a standardized way to get this data and pass it further

## Describe alternatives you've considered
Currently we're custom coding this. Not a big issue but the interfaces always have to custom code this field also and as there is no standardized field value etc. this leads to higher costs than actually needed for this.

**Comment by tarunvijwani** [comment]
@masteradhoc Thanks for suggesting this enhancement. I see that this enhancement to add a custom field was requested earlier in https://github.com/woocommerce/woocommerce-blocks/discussions/5483. Currently, it's indeed not possible to add/remove fields to/from the cart and checkout block. However, it is on our internal list of desired enhancements.

**Comment by masteradhoc** [comment]
@tarunvijwani thanks for the fast response here! Definately add the possibility to add/remove fields is crucial and should be high priority. though here i think more about a standardfield that should be added (optional). quite a lot systems need / request this information.
