### ISSUE TITLE
Local pickup icon is not aligned correctly in Antonia theme

### ISSUE THREAD

**Issue by tarunvijwani** [woocommerce/woocommerce-gutenberg-products-block#8230]
On a [WordPress.com](http://wordpress.com/) site with antonia theme: https://wordpress.com/theme/antonia/
we have a minor CSS issue in the Editor for local pickup.

<img width="1208" alt="image" src="https://user-images.githubusercontent.com/11503784/213161186-c9076e52-8542-4105-ac68-b7438f60dd07.png">

## To reproduce

1. Enable local pickup. 
2. Activate the `antonia` theme. 
3. Go to the Checkout block page editor
4. Notice the local pickup icon is not aligned correctly 

## Expected behavior

The local pickup icon should be aligned correctly for all the themes. 

https://user-images.githubusercontent.com/11503784/213162009-0ce42f81-3e67-4c0f-80aa-f8d79234e282.mov

**Comment by mikejolley** [comment]
![Screenshot 2023-03-14 at 11 14 28](https://user-images.githubusercontent.com/90977/224984486-fad7bc47-c29a-437d-b615-c2eec1001897.png)

Seems ok now.
