### ISSUE TITLE
Just need line items and total

### ISSUE THREAD

**Issue by Tanzi-Bee** [woocommerce/woocommerce-gutenberg-products-block#8242]
Need line items prices, total and go to checkout.
## What do you like about the Cart & Checkout blocks?
It's an option for when you need it
## What do you think is missing from the Cart & Checkout blocks?
more options to add or remove.

**Comment by tarunvijwani** [comment]
@Byham2012 Thanks for suggesting this enhancement. I see that this enhancement had been requested before in https://github.com/woocommerce/woocommerce-blocks/discussions/5483. Currently, it's indeed not possible to add/remove fields to/from the cart and checkout block. However, is on our internal list of desired enhancements.
