### ISSUE TITLE
Cart route being loaded in editor

### ISSUE THREAD

**Issue by kimmenbert** [woocommerce/woocommerce-gutenberg-products-block#8244]
## Describe the bug

Even without any WooCommerce blocks in content, the speed of the editor seems to be affected by WooCommerce blocks.
On a project I'm working on, I hooked into `woocommerce_check_cart_items`. I never expected that using that filter would be triggered back-end.

This makes me wonder. How much non-needed logic is processed in the editor. Worst case, will editor performance now be affected by the number of products in your cart session?

## To reproduce

1. Log in to admin, go to the edit screen of any page / post

2. Add this piece of code to your functions.php / a custom plugin

```
function thing_happens_in_editor() {
  die( 'Why' );
}
add_action( 'woocommerce_check_cart_items', 'thing_happens_in_editor', 1 );
```

3. Reload page, see "Why" message

## Expected behavior

I would not expect this logic to affect the editor, at least not when the editor does not even contain any WC block

### WordPress (please complete the following information):

-   WordPress version: 6.1.1
-   WooCommerce version: 7.3.0

**Comment by senadir** [comment]
Thank you for letting us know @kimmenbert! Cart session should not be reached during render in the editor, we use a fully mocked up cart to avoid that, there may be a regression that caused this. I will reword the issue title to reflect that.

**Comment by mikejolley** [comment]
Triggered by the "All Products" block for some reason. Investigating.
