### ISSUE TITLE
Store API: add multiple items to the cart

### ISSUE THREAD

**Issue by pierre-dekode** [woocommerce/woocommerce-gutenberg-products-block#8250]
I'd like to know if it is possible to add **multiple** items to the cart in one single request using the [POST `/cart/add-item` route](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/StoreApi/docs/cart.md#add-item).

I'm building a headless WooCommerce shop and we'd like to transform a wishlist of products into a purchasable cart. Being able to send an array of items to the `/cart/add-item` route would be extremely useful!

Thanks for your help.

**Comment by nielslange** [comment]
Hello @pierre-dekode 👋

> I'd like to know if it is possible to add multiple items to the cart in one single request using the [POST /cart/add-item route](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/StoreApi/docs/cart.md#add-item).

Thanks for reaching out. While it's not possible adding multiple items to the cart using the [POST /cart/add-item route](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/StoreApi/docs/cart.md#add-item), you can add multiple items to the cart using the `POST /wc/store/v1/batch` route. Your payload would look like this:

```json
{
  "requests": [
    {
      "path": "/wc/store/v1/cart/add-item",
      "method": "POST",
      "data": {
        "id": 26,
        "quantity": 1
      },
      "cache": "no-store",
      "body": {
        "id": 26,
        "quantity": 1
      },
      "headers": {
        "Nonce": "1db1d13784"
      }
    },
    {
      "path": "/wc/store/v1/cart/add-item",
      "method": "POST",
      "data": {
        "id": 27,
        "quantity": 1
      },
      "cache": "no-store",
      "body": {
        "id": 27,
        "quantity": 1
      },
      "headers": {
        "Nonce": "1db1d13784"
      }
    }
  ]
}
```

I'm closing this issue now, but please let us know if you have any further questions or suggestions regarding WooCommerce Blocks.

**Comment by pierre-dekode** [comment]
Awesome, thanks a lot @nielslange
