### ISSUE TITLE
Missing the woocommerce_after_shop_loop_item action hook

### ISSUE THREAD

**Issue by wouterch** [woocommerce/woocommerce-gutenberg-products-block#8261]
I currenly use the woocommerce_after_shop_loop_item in custom code I have written to display a 'New!' text on category pages for all products that were added in the last 7 days. This suits me perfectly. However, with blocks, this doesn't work.

Is there any workaround to this? 

I don't understand how woocommerce_blocks_product_grid_item_html could work instead. Any clear documentation on this? Or wouldn't this be able to help my use case?

I use something like:

```php
function show_new_product_label_on_category_page() {
	global $product; // get global product variable
	$newness_days = 7; // set variable for when something is still new (within these days)
	$created      = strtotime( $product->get_date_created() ); // when was the product created?
	if ( ( time() - ( 60 * 60 * 24 * $newness_days ) ) < $created ) {
		echo '' . esc_html__( 'New!', 'woocommerce' ) . '';
	}
}
```

**Comment by Aljullu** [comment]
Thanks for opening this issue @wouterch!

We are working on a new Products block (https://github.com/woocommerce/woocommerce/issues/42616) which is already available in WC core under the _Products (beta)_ name.

We recently add a compatibility layer so it will support several hooks, including `woocommerce_after_shop_loop_item`. You can read more about it in this PR: https://github.com/woocommerce/woocommerce-blocks/pull/8172. Support for these hooks will be included in WC Blocks 9.5 (to be released next week) and WC core 7.5 (to be released on March 14th). I would suggest to test your extension with this new block once we release the new compatibility layer.

The plan is that all other product grid blocks will transition to this new Products block, so I will mark this issue as fixed. However, you can still add new comments if you have any questions or would like to add something.
