### ISSUE TITLE
Store Notices and Catalog Sorting blocks don't work well in dark themes

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#8265]
## To reproduce

1. Install a theme with a dark background (ie: theme TT3 with Auberginie style or theme Zaino).
2. Go to Appearance > Editor and edit the Product Catalog template.
3. Add the Store Notices and Catalog Sorting blocks.
4. Notice they are illegible.

Editor | Frontend
--- | ---
![imatge](https://user-images.githubusercontent.com/3616980/214032684-cb579344-7855-46e3-83f7-15899b21d47a.png) | ![imatge](https://user-images.githubusercontent.com/3616980/214032629-da11c6fc-4003-4419-9cf8-f697252291ff.png)

## Expected behavior

We should make sure the texts are legible in dark themes.

**Comment by Aljullu** [comment]
FYI @dinhtungdu @albarin @kmanijak I added this to the Blockifying Product Archive Templates epic.

**Comment by nielslange** [comment]
@Aljullu In pdFofs-EZ-p2, @elizaan36 shared some thoughts on that. I think it's helpful to add a comment on that post about the issue you reported here.

**Comment by Aljullu** [comment]
Thanks for the heads-up, @nielslange! The existing Store Notices block is just a wrapper around the WC core PHP functions which render the notices, so I don't think it's directly impacted by that project. But I left a comment to get a confirmation.

**Comment by albarin** [comment]
@Aljullu At least for the **Store Notices**, I think this is a problem with the `Notice` component from `@wordpress/components` and not with the new block. On the editor side, we are using the `Notice` which is the one with the issue, while on the front end, we are using the PHP function, as you mentioned, and it's rendering fine with those themes.
For example, if you insert the `Filter by Attribute` block and click on `Done` without selecting any attribute, you'll see the same behavior with the `Notice` component.

**Comment by Aljullu** [comment]
Good catch! Would it work if we forced notices displayed inside our blocks to have black color text, @albarin?
