### ISSUE TITLE
Custom field for newsletter subscription in Woocommerce checkout block

### ISSUE THREAD

**Issue by wouterch** [woocommerce/woocommerce-gutenberg-products-block#8275]
I am currently using custom code (or a plugin) to add a newsletter subscription box to the checkout. With add_action('woocommerce_thankyou') I run custom code to send the email address to an external API.

With the new Woocommerce Checkout block I can't figure out how to add a custom checkout field, such as a "Subscribe to newsletter" checkout box, that I can then validate on the _thank you page_ in order to run my custom code. 

This is the code I use now:

    // check for user newsletter consent
    $field_name = 'billing_consent_newsletter';
    $consent = get_post_meta( $order_id, $field_name, true );
    if($consent != 1){
        return;
    }

How would I make something like this work with the Woocommerce Checkout blog? I don't mind some custom coding, but I do not have any idea of how to start. Or are you already working on a user friendly way to add custom checkout fields? Or any plugins that do this already?

Thanks a lot!

**Comment by nielslange** [comment]
Hello @wouterch 👋

Thanks for reaching out! I suggest looking at https://www.npmjs.com/package/@woocommerce/extend-cart-checkout-block, which is a great starting point for creating WooCommerce Blocks extensions, such as a newsletter subscription box. In fact, this dependency, uses a newsletter subscription box as an example. It is worth noting that this dependency is a starting point. It's not a complete solution, and how to handle newsletter subscriptions depends on your specific use case.

I'll be closing this issue, but please feel free to reply if you have any further questions or concerns about this topic. If you have new questions or suggestions, please create a new issue.
