### ISSUE TITLE
Wrong Schema Identifier for Shipping address

### ISSUE THREAD

**Issue by C4MS** [woocommerce/woocommerce-gutenberg-products-block#8286]
Updating both addresses using endpoint below works just fine, response data does show correct address

```
POST /cart/update-customer
```

Retrieving checkout data, shows billing for both addresses

```
GET /checkout
```

replacing  `BillingAddressSchema::IDENTIFIER` with `ShippingAddressSchema::IDENTIFIER` works as expected

<img width="325" alt="image" src="https://user-images.githubusercontent.com/806497/214453009-287d40a0-e0ae-4444-a115-2efe5ffa5896.png">

https://github.com/woocommerce/woocommerce-blocks/blob/029b379138906872dec3ed920fcb23d24404a3f2/src/StoreApi/Schemas/V1/CheckoutSchema.php#L50

**Comment by nielslange** [comment]
Hello @C4MS 👋

Thanks for bringing this to our attention. @wavvves created a fix yesterday and I just successfully reviewed it. I expect that we'll ship this fix with the next release, which will take place next week.
