### ISSUE TITLE
Cleanup babel dependencies

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#829]
Coming from: https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/819#discussion_r312428655.

We think we have several dependencies in `package.json` that could be removed because they are included in other packages. This issue is about `babel-*` dependencies which might be already included in `@wordpress/babel-preset-default`.

**Comment by nerrad** [comment]
A first pass has already been done on this and it surfaces from time to time but I think this is obsolete for now.
