### ISSUE TITLE
Product Elements: [Variations] Element variations are still gated behind the plugin flag

### ISSUE THREAD

**Issue by sunyatasattva** [woocommerce/woocommerce-gutenberg-products-block#8296]
We removed the featured plugin flag from the “Products (Beta)” block in [this PR](https://github.com/woocommerce/woocommerce-blocks/pull/8001). Alas, we forgot to remove the flag on the elements, and they are not accessible without the plugin.

**Comment by gigitux** [comment]
https://github.com/woocommerce/woocommerce-blocks/pull/8297 fixes this issue!
