### ISSUE TITLE
Individual products scope: Make it more obvious that multiple products can be selected 

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce-gutenberg-products-block#83]
Currently the search results overlay the selected products which doesn't help. We could also display a hint that more products can be added, either on first time use or permanently.

**Comment by jameskoster** [comment]
@claudiulodro @tiagonoronha here's an updated design for this scope based on feedback;

https://sketch.cloud/s/OeGkk/all/individual-products-alternative/scope-selected/play

Notes:

* Search icon added to input
* Results now stay visible, even when added, but have a different design treatment (highlight + checkmark)
* Clicking an added product in the results will remove it (see prototype)
* As products are added they form a grid below - this grid should honor the column setting for this block to give a rough semblance of a preview
* Clicking outside the results will close them
* Products can only be removed from the grid when the results are closed (see prototype)

**Comment by claudiulodro** [comment]
See #89
