### ISSUE TITLE
STORE API Connot get product cutom fields 

### ISSUE THREAD

**Issue by aidevelopercode** [woocommerce/woocommerce-gutenberg-products-block#8300]
When i use STORE API to get products  http://localhost/wp-json/wc/store/v1/products, the meta custom filed not showed in json response body

**Comment by gigitux** [comment]
Hi, thanks for opening this issue.

It is necessary to extend the Rest API to achieve that. You can find more details [here](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/rest-api/extend-rest-api-add-data.md/#L1-L2).

**Comment by mikejolley** [comment]
Store API does not return all meta data from products - some could be considered private.

You have 2 options:

1. Extend the schema to include your custom meta fields https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/rest-api/extend-rest-api-new-endpoint.md

2. Use product attributes instead. Those are returned by default.

Thanks
