### ISSUE TITLE
Cart Block "No shipping options were found" message

### ISSUE THREAD

**Issue by madjedo** [woocommerce/woocommerce-gutenberg-products-block#8320]
If customers enters the cart page before entering their address at checkout the cart block displays the confusing message of

_"No shipping options were found"_

Kinda confusing and could lead to a high droprate. Especially if you are running a international shop. Should instead say:

_"Enter your address at checkout to view shipping options"_

Alternatively:

_"Proceed to checkout to view shipping options"._

And if the merchant has enabled 'shipping calculator' it could instead display message of:

_"Enter address details in above shipping calculator to view shipping options"._

**Comment by madjedo** [comment]
Or better yet, allow merchants to easily remove this field entirely from the cart page.

**Comment by mikejolley** [comment]
Thanks for the report @madjedo 

I've confirmed that the work being done in https://github.com/woocommerce/woocommerce-blocks/pull/8141 will fix this issue by including some text to add an address via the calculator, or otherwise do so via checkout. As such I'm closing this issue.

Thanks
