### ISSUE TITLE
Cart Block, all shipping options gets displayed after selecting any other shipping option

### ISSUE THREAD

**Issue by madjedo** [woocommerce/woocommerce-gutenberg-products-block#8321]
I have a filter that unsets shipping options that are not free the from same forwarder if a customer cart qualifies for free shipping, by for example exceeding a certain cart value amount.

The code is:

    // Only unset FLAT RATE if FREE SHIPPING is available
    if ( isset( $rates['free_shipping:1'] ) || isset( $rates['free_shipping:8'] )  ) { // FREE SHIPPING ID is 1 or 8
    unset( $rates['flat_rate:3'] ); // FLAT RATE shipping method with ID 3
    unset( $rates['flat_rate:7'] ); // FLAT RATE shipping method with ID 7
    }

But if a customer visits the cart page and selects any other option then the free shipping option, the unset flat_rate option gets displayed:

![free_shipping_only](https://user-images.githubusercontent.com/25926337/215332186-a32b80a8-b93f-42c1-9ae9-49c3f2f0e50a.png)

![not_free_shippin](https://user-images.githubusercontent.com/25926337/215332197-54adbe8f-5ecc-4ea1-ae62-39a8d2dca7b2.png)

**Comment by mikejolley** [comment]
@madjedo I see the code which does the removal, but where have you placed this? Does it fire on a particular hook?

The rates will update once an API request has been fired off; the list of shipping methods is not static. It just looks like your code only runs on page load, not on subsequent requests.

**Comment by alexflorisca** [comment]
Closing this as no reply in 2 weeks. If this is still an issue, we can re-open as needed.
