### ISSUE TITLE
Detecting Store API request in order to skip woocommerce_add_to_cart_validation

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce-gutenberg-products-block#8335]
`woocommerce_add_to_cart_validation` is noted as _deprecated_ but it's still running in the [Store API `validate_add_to_cart`](https://github.com/woocommerce/woocommerce-blocks/blob/2d7360624e8516637c966ba9a5815a49cf352b3d/src/StoreApi/Utilities/CartController.php#L263). Many of us are filtering this as part of legacy add to cart validation.

What's the recommended way to tell our existing applications... hey this is a REST request.. so we can tell our callbacks _not_ to run in the Store API context?? Then we can introduce callbacks on `woocommerce_store_api_validate_add_to_cart` and not validate twice.

**Comment by mikejolley** [comment]
@helgatheviking would the method `wc()->is_rest_api_request()` work here?

**Comment by helgatheviking** [comment]
@mikejolley yes! I think that would do it, thank you. When was that added? there's no `@since` tag, but it looks like maybe 3.6?

**Comment by mikejolley** [comment]
Possibly—It's 4 years old so probably safe to use now :D 

Ill mark this issue closed, thanks.

**Comment by helgatheviking** [comment]
Works for me. Thanks Mike.
