### ISSUE TITLE
Help starting to build a checkout block

### ISSUE THREAD

**Issue by webdados** [woocommerce/woocommerce-gutenberg-products-block#8337]
Hi,

I'm entirely new to React and need to add block support to my payment gateway.

As a starting point, I'm using the BACS index.js file and I'm stuck at an error while running "npm run build": 
`> test@1.0.0 build
> wp-scripts build

assets by status 2.85 KiB [cached] 2 assets
Entrypoint index = index.js index.asset.php
orphan modules 4 KiB [orphan] 8 modules
./src/index.js + 8 modules 5.29 KiB [not cacheable] [built] [code generated]

ERROR in ./src/index.js 6:0-69
Module not found: Error: Can't resolve '@woocommerce/blocks-registry' in '/.../wordpress-testing/app/public/wp-content/plugins/my-plugin/woocommerce-blocks/test/src'
  Parsed request is a module
  using description file: /.../wordpress-testing/app/public/wp-content/plugins/my-plugin/woocommerce-blocks/test/package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /.../wordpress-testing/app/public/wp-content/plugins/my-plugin/woocommerce-blocks/test/src/node_modules doesn't exist or is not a directory
      looking for modules in /.../wordpress-testing/app/public/wp-content/plugins/my-plugin/woocommerce-blocks/test/node_modules
        single file module
          using description file: /.../wordpress-testing/app/public/wp-content/plugins/my-plugin/woocommerce-blocks/test/package.json (relative path: ./node_modules/@woocommerce/blocks-registry)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /.../wordpress-testing/app/public/wp-content/plugins/my-plugin/woocommerce-blocks/test/node_modules/@woocommerce/blocks-registry doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /.../wordpress-testing/app/public/wp-content/plugins/my-plugin/woocommerce-blocks/test/node_modules/@woocommerce/blocks-registry.jsx doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /.../wordpress-testing/app/public/wp-content/plugins/my-plugin/woocommerce-blocks/test/node_modules/@woocommerce/blocks-registry.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /.../wordpress-testing/app/public/wp-content/plugins/my-plugin/woocommerce-blocks/test/node_modules/@woocommerce/blocks-registry.tsx doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /.../wordpress-testing/app/public/wp-content/plugins/my-plugin/woocommerce-blocks/test/node_modules/@woocommerce/blocks-registry.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /.../wordpress-testing/app/public/wp-content/plugins/my-plugin/woocommerce-blocks/test/node_modules/@woocommerce/blocks-registry.json doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              /.../wordpress-testing/app/public/wp-content/plugins/my-plugin/woocommerce-blocks/test/node_modules/@woocommerce/blocks-registry.wasm doesn't exist
        /.../wordpress-testing/app/public/wp-content/plugins/my-plugin/woocommerce-blocks/test/node_modules/@woocommerce/blocks-registry doesn't exist
      /.../wordpress-testing/app/public/wp-content/plugins/my-plugin/woocommerce-blocks/node_modules doesn't exist or is not a directory
      /.../wordpress-testing/app/public/wp-content/plugins/my-plugin/node_modules doesn't exist or is not a directory
      (...)

webpack 5.75.0 compiled with 1 error in 890 ms
`

This is probably some silly thing I'm missing, but as I mentioned before, this is entirely new to me.

What I've done so far:
- Update npm to latest version
- npm init to create package.json 
- npm install --save-dev --save-exact @wordpress/scripts
- npm i @woocommerce/shared-settings
And I'm now stuck.

**Comment by mikejolley** [comment]
I have a list of resources which might help you get started, or at least provide a working development environment which you can apply to your own: https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs#developer-resources

For the specific problem you're having, that missing dependency is not imported via package.json but mapped in webpack. You'll need to use the dependency injection webpack plugin. 

Take a look at this: https://www.npmjs.com/package/@woocommerce/extend-cart-checkout-block

This creates a starter plugin with wp-scripts and build processing in place, as well as a basic loader for WordPress. It handles dependency mapping so you can access scripts like `@woocommerce/blocks-checkout` and others from the checkout package that are used for payment gateway registration: https://github.com/woocommerce/woocommerce-blocks/tree/trunk/packages/checkout

Another plugin to reference would be https://github.com/woocommerce/woocommerce-gateway-dummy

I think one of the above starter plugins should be enough to get your webpack config working. Good luck!
