### ISSUE TITLE
Enable blockified template support when required templates are implemented

### ISSUE THREAD

**Issue by dinhtungdu** [woocommerce/woocommerce-gutenberg-products-block#8342]
The blockified template support is implemented in #6538 but is disabled currently:

https://github.com/woocommerce/woocommerce-blocks/blob/001685f6f89cb43e9341e76ca1124c60db62c110/src/BlockTemplatesController.php#L390-L391

https://github.com/woocommerce/woocommerce-blocks/blob/001685f6f89cb43e9341e76ca1124c60db62c110/src/BlockTemplatesController.php#L482-L484

After #8209 and #8067 are merged, we need to enable the blockified template support. 

We also need to evaluate and decide to keep or change the feature gating to feature plugin.

**Comment by gigitux** [comment]
Fixed with #9551
