### ISSUE TITLE
Feedback on ./src/StoreApi/docs/product-categories.md

### ISSUE THREAD

**Issue by NikitaShvetsovCode** [woocommerce/woocommerce-gutenberg-products-block#8344]
Greetings! Can you please tell me how to get products from a category by ID?

**Comment by mikejolley** [comment]
Hi,

See this endpoint: https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/StoreApi/docs/products.md

There is a `category` parameter which you can pass in an ID to filter the products returned.

Thanks
