### ISSUE TITLE
Move "terms" page notice to the inspector

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#8362]
## Describe the bug

This is not a bug, but seems like something we should modify. In the terms and conditions block, if you don't have a terms page setup you'll see a notice like this inline:

![Screenshot 2023-02-01 at 16 09 14](https://user-images.githubusercontent.com/90977/216098051-13eac586-cec1-47e7-a910-d85f7c63a557.png)

This is not reflective of the appearance on the frontend. I'd suggest moving the notice to the inspector instead.

Thoughts @woocommerce/rubik?

**Comment by nielslange** [comment]
On one hand, all other info and warning messages are located in the inspector. On the other hand, I wonder if the visibility decreases when moving the "terms" page notice to the inspector. I'd probably draft a PR to see how the result would look.

**Comment by alexflorisca** [comment]
Yeah it's a tricky one, we had a similar chat before about the UI for resetting a button's text. I think this make sense in this case as you want to draw visibility to the fact that you will be displaying the terms text, but without any terms pages. The other option could be to move the whole thing to the inspector - so the terms text would be an option on the checkout block.

**Comment by senadir** [comment]
I'm not sure how to feel about this, it's true that it's not reflective about frontend state, but this is an error state or a validation issue, and I think those are exception to that rule.

**Comment by mikejolley** [comment]
Are they errors, though? Those pages are not mandatory. You could present text there without actual terms pages defined. For example if you had a custom page or site to send them, or wanted to show terms inline.

**Comment by ralucaStan** [comment]
I tend to agree with Mike. We moved notices to the sidebar so this section would need to follow that model as well. Even if that would bring less visibility to the prompt. 

I'd say this is a low priority for now
