### ISSUE TITLE
Place order button is full width in the editor

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#8363]
## Describe the bug

When editing the checkout block, the place order button appears full width:

![Screenshot 2023-02-01 at 16 11 50](https://user-images.githubusercontent.com/90977/216098838-2414acbb-517c-4647-9663-12fb33d8d733.png)

However on the frontend it is aligned beside the back link:

![Screenshot 2023-02-01 at 16 12 37](https://user-images.githubusercontent.com/90977/216098929-8a613d13-94ac-42db-a03d-6841616a52a9.png)

These should match.

**Comment by ralucaStan** [comment]
This might depend on the theme. What theme is this @mikejolley?

<img width="701" alt="Screenshot 2023-02-14 at 09 50 35" src="https://user-images.githubusercontent.com/1628454/218685694-701aeccf-9add-4319-a3f9-514d770ec60d.png">

**Comment by mikejolley** [comment]
@ralucaStan 2023

**Comment by iamdharmesh** [comment]
Hi there,

I would like to work on this issue as part of Contributor Day.

Thanks
