### ISSUE TITLE
Product Categories List causing one pixel white line at the end of the page in some themes

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#837]
Reported in the support forum:
https://wordpress.org/support/topic/one-pixel-horizontal-line-at-bottom-of-site-pages/

When using the Eikra theme, a white line appears at the bottom of the page caused by the _Product Categories List_ block button.

The specific line causing the issue:
https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/assets/js/blocks/product-categories/style.scss#L41

I assume it comes from:
https://github.com/WordPress/gutenberg/blob/master/packages/components/src/button/style.scss#L255

We could check if this line is really necessary in the _Product Categories List_ considering it doesn't have text inside the button.

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/849
