### ISSUE TITLE
Filter by Rating: Reset button does not work

### ISSUE THREAD

**Issue by tjcafferkey** [woocommerce/woocommerce-gutenberg-products-block#8373]
## Describe the bug

When you add Filter by Rating to your page and enable the Apply button for the block. When you filter products on the frontend and then attempt to reset these by clicking "Reset" it breaks and shows a console error for an undefined function.

## To reproduce

1. Ensure products have ratings
2. Add Filter by Rating to your page and enable the Apply button in the block settings
3. On the frontend, apply some filters for this block and then attempt to reset them by clicking the "Reset" button
4. See error in console.

## Expected behavior

Filters are successfully reset.

**Comment by danieldudzic** [comment]
Thanks for fixing this! 🙏
