### ISSUE TITLE
Two "The provided postcode / ZIP is not valid" error message are displayed. 

### ISSUE THREAD

**Issue by fetenlakhal** [woocommerce/woocommerce-gutenberg-products-block#8387]
## Describe the bug

5927922-zd / 40342701-hc

If you add a wrong zip code, two "The provided postcode / ZIP is not valid" error messages are displayed. If you correct the zip code, the first one disappears; The second is stuck. This is happening with the new version 9.5.0.

## To reproduce

1. Add the latest version of [WooCommerce Blocks](https://woocommerce.com/products/woocommerce-gutenberg-products-block/) on your website 
2. Add the [check-out block](https://woocommerce.com/document/cart-checkout-blocks-support-status/) on your check-out page. 
1. Add a product to the cart and go to checkout
2. Change country to Poland for example with the zip code 40-837. 
3. Change country to United Kingdom.
4. You will see two "The provided postcode / ZIP is not valid" error messages.
5. Change the zip code to E14 9AJ
6. The first "The provided postcode / ZIP is not valid" error message is stuck. 

## Expected behavior

Only one "The provided postcode / ZIP is not valid" error message is displayed and disappears after correcting the zip code. 

## Screenshots

Please check this Gif: d.pr/i/IkNwW4

### WordPress (please complete the following information):

-   WordPress version: 6.1.1
-   WooCommerce version: 7.1.0
-   WooCommerce Blocks version: 9.5.0
-   Site language: English

## Additional context

The user also reported that the order summary was not updated after that, but I can't reproduce that.

**Comment by gameDNA-Helix** [comment]
+1

**Comment by senadir** [comment]
Thank you for reporting this @taftina, I managed to reproduce it and will push a fix.
