### ISSUE TITLE
Critical Error on commit 8bd0d4d3e1d4bd0ef6b80022b54f520dd1b9e3a1

### ISSUE THREAD

**Issue by MonteLogic** [woocommerce/woocommerce-gutenberg-products-block#8388]
## Describe the bug

I am on Linux Mint and I couldn't get the dev version to work after the 8bd0d4d3e1d4bd0ef6b80022b54f520dd1b9e3a1 commit. I am using 16.18.1 version of node. When I install and run it per instructions I am getting fatal error when I am on the admin side but not the client side. Before the commit there is no such fatal error.

The exact error message:
"
[06-Feb-2023 00:52:34 UTC] PHP Fatal error:  Uncaught Exception: Cannot construct an instance of Automattic\WooCommerce\Blocks\Assets\AssetDataRegistry because it has not been registered. in /home/monte/Local Sites/matlackrebuild/app/    public/wp-content/plugins/woocommerce-blocks/src/Registry/Container.php:89

"
 
Trying building the project with x86 Linux mint and the error may pop up again, haven't tried it yet on another machine but I do know for sure that that commit creates a fatal error.

**Comment by alexflorisca** [comment]
Hi @MonteLogic, curious if it's just that commit or you are still getting this on trunk?

**Comment by MonteLogic** [comment]
I'm getting it on every commit from the trunk to that commit which I listed. @alexflorisca  But I'm not getting the error whenever I delete the development version and use the WordPress.org listed plugin.

**Comment by alexflorisca** [comment]
Interesting, maybe some of our build scripts are not compatible with your setup. How are you running the development version?

**Comment by opr** [comment]
Hey @MonteLogic could you share more information about your setup? Which PHP version are you using? Which composer version are you using?

**Comment by wavvves** [comment]
Also @MonteLogic can you install nvm and run `nvm use`? That will install and enable the node version contained in `.nvmrc` (at the time of this writing 16.13.2) which is the recommended node version to use.

**Comment by MonteLogic** [comment]
> 

Thanks for the input, will try again with official version

**Comment by mikejolley** [comment]
Since this hasn't had a response for 3 weeks I'm going to close it and assume the issue was resolved. If not, please comment back with details so it can be investigated further. 

Thanks
