### ISSUE TITLE
Local Pickup/Shipping selector should have same height regardless of content

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#8393]
There are some cases in which Local Pickup selector have a different height from the shipping one, however, both should have the same height regardless of content.

<img width="536" alt="image" src="https://user-images.githubusercontent.com/6165348/217268525-29cd8b4b-a12b-48b2-bad5-55cdc986b67c.png">

### Reproduce Steps

1. Enable Local Pickup.
2. In the editor settings of Local Pickup, disable price.
3. In WooCommerce -> Settings -> Shipping -> Shipping Options set ` Hide shipping costs until an address is entered` to true.
4. In Checkout, you should see an unbalanced view.

**Comment by ralucaStan** [comment]
closed by https://github.com/woocommerce/woocommerce-blocks/pull/8394
