### ISSUE TITLE
Customer Account Block: Center Align doesn't work

### ISSUE THREAD

**Issue by thisissandip** [woocommerce/woocommerce-gutenberg-products-block#8412]
## Describe the bug

Center Align doesn't work with the customer align block

## To reproduce

1. On a page or a post, add the "Customer Account" block
2. Set it to Center Align
3. See it is not center aligned

## Expected behavior

It should be center aligned.

## Screenshots

![jfCL9q.gif](https://user-images.githubusercontent.com/69596988/218457226-0379d8b3-2b76-4c21-9c56-beca85222914.gif)

### Expected Fix

I think it's missing the below CSS:

```
justify-content: center;
```

![tnxN6W.png](https://user-images.githubusercontent.com/69596988/218457169-b5698d84-f2c5-435e-a666-3b5239cef5d4.png)

**Comment by Aljullu** [comment]
Confirming the issue, I'm able to reproduce. Thanks, @thisissandip!
