### ISSUE TITLE
Experiment with saved addresses in the Checkout Blocks

### ISSUE THREAD

**Issue by ralucaStan** [woocommerce/woocommerce-gutenberg-products-block#8426]
## Is your feature request related to a problem? Please describe.
The checkout form is too long at the moment. Each time a returning customer visits the page, the whole form is visible and the fields are prepopulated

## Describe the solution you'd like
I'd like us to experiment with saved billing/shipping addresses. There are some experiments in design at the moment, but I think it's important to see what impact a change like this has on:
- the data store
- the way we update the checkout state
- the mobile experience
- localization and the order of fields
- error notices and inline validation related to the fields

## Additional context
For inspiration, we can use the proposal from this P2 pdFofs-kT-p2:
- first time users see a button to add an address
- the form appears in the page (not in a modal) and they submit a new address
- the for disappears and an address summary is displayed, along with a link to change it
- changing the address should display the form again

- returning buyers see the saved address with the change button

**Comment by senadir** [comment]
I assume you mean having support for several addresses per customer? if not, ignore the rest.

This seems like something that should be tackled at WooCommerce core level.

Without disturbing the experience and creating breaking changes, we should look at it from this this length:

- Preferred address.
- Other address.

Preferred address is what get persisted to the customer's profile and is what get returned when you call things like customer->get_shipping_x and get_billing_x

Other addresses can be persisted to meta data.

**Comment by mikejolley** [comment]
@senadir multiple addresses is nice, but we can still have UI improvements with a single address in condensed form.
