### ISSUE TITLE
Icon for the `Product Details` block

### ISSUE THREAD

**Issue by gigitux** [woocommerce/woocommerce-gutenberg-products-block#8427]
With #8225, we introduced the `Product Details` block with a temporary icon.

![image](https://user-images.githubusercontent.com/4463174/218798937-8753a3b6-457b-4762-9465-870df75e5727.png)

@vivialice, could you give us more details about which icon we should use?

**Comment by shaunandrews** [comment]
<img width="735" alt="CleanShot 2023-04-21 at 14 51 09@2x" src="https://user-images.githubusercontent.com/191598/233713097-60879ddb-b33f-4db5-bf95-b002789527c2.png">

[product-details-icon.svg.zip](https://github.com/woocommerce/woocommerce-blocks/files/11298511/product-details-icon.svg.zip)

Here's a new icon. Can we update the description, too, please? "Display a product’s description, attributes, and reviews."

Thanks!
