### ISSUE TITLE
Display Cart and Checkout blocks in the Style Book

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#8433]
In https://github.com/woocommerce/woocommerce-blocks/pull/8369, the Cart block was hidden from the Style Book, but we would like to re-enable it. We would also like to display the Checkout block. (See discussion in pdnLyh-35n-p2#comment-2093).

## To reproduce

0. You will need WP >=6.2 or to have the latest version of Gutenberg installed.
1. Go to Appearance → Editor and edit a template.
2. Navigate to Style Book (Select the Styles icon and then the Eye icon).
3. Click on the Woo tab.
4. Notice the Cart and Checkout blocks don't appear in the previews.

## Expected behavior

Cart and Checkout blocks previews should appear in the Style Book.

**Comment by ralucaStan** [comment]
internal discussion p1675180993522159-slack-C02UBB1EPEF

**Comment by ralucaStan** [comment]
We need to work again on this, as the initial approach had some issues p1677701598203669-slack-C8X6Q7XQU
