### ISSUE TITLE
"Order received" page does not display the payment method information when an order is completed via the Checkout Block

### ISSUE THREAD

**Issue by ankitguptaindia** [woocommerce/woocommerce-gutenberg-products-block#8448]
## **🐞 Description-**

1. **When an order is completed through the Checkout Block, the "Order received" page fails to display the payment method information. This issue does not occur when orders are completed via the shortcode-based checkout page.**

| **With Block-Based checkout**                                                                                  | **With Shortcode-Based checkout**                                                                              |
|----------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------|
| ![image](https://user-images.githubusercontent.com/6384299/219310418-f31f7c0b-0354-4d67-aba3-b478a77fe649.png) | ![image](https://user-images.githubusercontent.com/6384299/219309640-ef1f8e0d-e512-461a-845c-b917f7bdbc57.png) |

2.  🐞  **Payment Method details also missing on Order Listing Page in WP dashboard.** 

![image](https://user-images.githubusercontent.com/6384299/219313032-3cd4f6e4-1312-45ec-a6c1-df6b95e4eeab.png)

## To reproduce

1. Install the WooCommerce Block plugin on a WordPress site.
4. Create a product and add it to the site's shopping cart.
5. Proceed to checkout using the "Checkout" Block, which can be added to a page using the "WooCommerce" block category.
6. Complete the checkout process and confirm the order.
7. On the "Order received" page, observe that the payment method information is missing.

To confirm that the issue does not occur when using the shortcode-based checkout page, follow these additional steps:

1. Create a product and add it to the site's shopping cart.
2. Add the shortcode [woocommerce_checkout] to a page and publish it.
3. Proceed to checkout using the newly created shortcode-based checkout page.
4. Complete the checkout process and confirm the order.
5. On the "Order received" page, observe that the payment method information is properly displayed.

## Expected behavior

Payment Method information should appear for the customer on Order/Thank you Page.

## Environment

<Details>
```
`
### WordPress Environment ###

WordPress address (URL): https://woolocal.local
Site address (URL): https://woolocal.local
WC Version: 7.4.0
REST API Version: ✔ 7.4.0
WC Blocks Version: ✔ 9.6.0
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.0.0
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.54.0
LibreSSL/2.6.5


### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (5) ###


WooCommerce Blocks: by Automattic – 9.6.0
WooCommerce Bookings Stable: by WooCommerce – 1.15.75
WooCommerce Stripe Gateway: by WooCommerce – 7.0.2
WooCommerce Product Vendors: by WooCommerce – 2.1.70
WooCommerce: by Automattic – 7.4.0



### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.2.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔




### Status report information ###

Generated at: 2023-02-16 14:05:07 +05:30
`

```

</Details>

**Comment by opr** [comment]
Thanks for the report, I replicated this. I will add it to our backlog!

**Comment by iamdharmesh** [comment]
Hi there, 

I would like to work on this issue as part of Contributor Day.

Thanks

**Comment by nielslange** [comment]
> I would like to work on this issue as part of Contributor Day.

Hello @iamdharmesh 👋 Thanks for your interest in working on this issue. I just assigned it to you. Please also feel free to join us in the [#woo-contributor-day_checkout](https://woocommercecommunity.slack.com/archives/C052GRY8N2J) channel on  https://woocommercecommunity.slack.com/.

**Comment by ankitguptaindia** [comment]
I am going to do QA of this PR as part of Contributor Day.
