### ISSUE TITLE
I Need hook

### ISSUE THREAD

**Issue by vvv3** [woocommerce/woocommerce-gutenberg-products-block#845]
\Automattic\WooCommerce\Blocks\BlockTypes\AbstractProductGrid::get_add_to_cart - No hook for $attributes.

No hook for $attributes as in function woocommerce_template_loop_add_to_cart and i no way to add own attribute.

**Comment by mikejolley** [comment]
I've consolodated all related issues to extending blocks into https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/891 until a decision is made. Please see that issue and add feedback there if relevant. 

Thanks
