### ISSUE TITLE
Interactivity API: make current filter blocks (client-side rendered) work with client-side navigation

### ISSUE THREAD

**Issue by DAreRodz** [woocommerce/woocommerce-gutenberg-products-block#8456]
We must ensure that current filter blocks can use `navigate` from the Block Interactivity API to update the Products block content.

The filters we need to modify are these:

- [Active filters](https://github.com/woocommerce/woocommerce-blocks/tree/trunk/assets/js/blocks/active-filters)
- [Attribute filter](https://github.com/woocommerce/woocommerce-blocks/tree/trunk/assets/js/blocks/attribute-filter)
- [Price filter](https://github.com/woocommerce/woocommerce-blocks/tree/trunk/assets/js/blocks/price-filter)
- [Rating filter](https://github.com/woocommerce/woocommerce-blocks/tree/trunk/assets/js/blocks/rating-filter)
- [Stock filter](https://github.com/woocommerce/woocommerce-blocks/tree/trunk/assets/js/blocks/stock-filter)

They all call a function named `changeUrl()` in `utils/filters.ts`.

https://github.com/woocommerce/woocommerce-blocks/blob/41a40fb710454f32a64958b875b9de7457ddd3ea/assets/js/utils/filters.ts#L30-L41

By modifying that function in a way that it calls the `navigate()` function from the Interactivity API when client-side navigations are enabled, we would be making all blocks update the Products block content without having to reload the whole page.

The challenge here will be to make these block import `navigate` from a different bundle (the Interactivity API's [`runtime` bundle](https://github.com/woocommerce/woocommerce-blocks/blob/cc98bc16c4109e0b1f83e875370ec4fc6bbd9039/bin/webpack-configs.js#L784-L854)).

**Comment by DAreRodz** [comment]
> The challenge here will be to make these block import `navigate` from a different bundle (the Interactivity API's `runtime` bundle).

@luisherranz, do you know how to consume a bundle as a module from a different bundle (if that's possible in Webpack)? 🤔

**Comment by luisherranz** [comment]
So `@woocommerce/interactivity` is not treated as an external dependency?

**Comment by luisherranz** [comment]
I mean, are you trying to import it using something similar to this?

```js
import { navigate } from "@woocommerce/interactivity";
```

**Comment by DAreRodz** [comment]
> So `@woocommerce/interactivity` is not treated as an external dependency?

> I mean, are you trying to import it using something similar to this?
> 
> ```js
> import { navigate } from "@woocommerce/interactivity";
> ```

That's exactly what I'd like to do. 😅 

However, by doing so, each block contains its own copy of the Interactivity API runtime―even using React instead of Preact, because the bundling process is different for these blocks.

**Comment by DAreRodz** [comment]
BTW, I did a quick test assigning `navigate` to a global variable in `window`, and everything seems to work fine. ✨ 

EDIT: not 100% right, there are cases where the filters disappear. It happens occasionally with multiple filters at the same time

**Comment by luisherranz** [comment]
> However, by doing so, each block contains its own copy of the Interactivity API runtime―even using React instead of Preact, because the bundling process is different for these blocks.

So it seems like something is not working as expected, right?

We should ping someone from Woo to take a look at why an import to `@woocommerce/interactivity` is adding it to the bundle instead of enqueuing it as a dependency.

**Comment by luisherranz** [comment]
> there are cases where the filters disappear. It happens occasionally with multiple filters at the same time

Do you think that problem is related to the bundling or it's something different?

**Comment by DAreRodz** [comment]
> Do you think that problem is related to the bundling or it's something different?

It should be something different. I'm assigning the global `navigate` from our bundle, enqueuing it, and calling `window.wpx.navigate` from the `changeUrl` function mentioned above.

> We should ping someone from Woo to take a look at why an import to `@woocommerce/interactivity` is adding it to the bundle instead of enqueuing it as a dependency.

Maybe @gigitux or @Aljullu could help us here. 😊

**Comment by luisherranz** [comment]
> there are cases where the filters disappear. It happens occasionally with multiple filters at the same time

Well... we probably would have to add `wp-ignore` to those nodes to make Preact ignore their client-side rendered modifications of the DOM. 

But don't spend time on this because we won't use full-page client-side navigation in Woo and that problem should disappear once we refactor the router to work only on the inner HTML of the Products block.

> Maybe @gigitux or @Aljullu could help us here.

Luigi, Albert: if you don't know what may be the problem, please ping someone else from Woo. Thanks 🙂

**Comment by luisherranz** [comment]
If the problem is very complex to solve, we can use the global variable solution. But we should name it something like `window.__experimentalWooStore` (or whatever naming Woo uses for their experimental APIs) to avoid problems with extenders.

**Comment by gigitux** [comment]
I'm not sure I understand the issue, but it seems there is an issue with the webpack configuration. 
I'm not very expert on this, maybe @senadir or @thealexandrelara have some ideas about fixing the issue!

**Comment by Aljullu** [comment]
I'm not an expert either, but one idea would be to try using [`wcDepMap` and `wcHandleMap`](https://github.com/woocommerce/woocommerce-blocks/blob/8c739347b9a56d5676bfc8e8824462ca01b9edea/bin/webpack-helpers.js#L11-L32). That's what we use for externals which are shared across blocks, if I'm not wrong.

I see [`@woocommerce/interactivity` is currently listed as an alias](https://github.com/woocommerce/woocommerce-blocks/blob/8c739347b9a56d5676bfc8e8824462ca01b9edea/bin/webpack-helpers.js#L62-L65), but that's not exactly the same, an alias doesn't mean it will be unique across blocks. Instead, an external _will_ guarantee it's only loaded once for all blocks. If you go this way, you will also need to add it as a [core entry](https://github.com/woocommerce/woocommerce-blocks/blob/8c739347b9a56d5676bfc8e8824462ca01b9edea/bin/webpack-entries.js#L125) for it to be built.

**Comment by DAreRodz** [comment]
> [...] one idea would be to try using [wcDepMap and wcHandleMap](https://github.com/woocommerce/woocommerce-blocks/blob/8c739347b9a56d5676bfc8e8824462ca01b9edea/bin/webpack-helpers.js#L11-L32).

> Instead, an external will guarantee it's only loaded once for all blocks. If you go this way, you will also need to add it as a [core entry](https://github.com/woocommerce/woocommerce-blocks/blob/8c739347b9a56d5676bfc8e8824462ca01b9edea/bin/webpack-entries.js#L125) for it to be built.

Thanks @Aljullu, I'll explore that approach. 🙏

**Comment by senadir** [comment]
Exactly what Albert said, in order to have a singleton you need to either assign the instance to some global variable (in window) or move the script to its own output build file that gets enqueued.

If it's not a large file I think doing window global is better? while also making sure you're not overriding it or trying to initiate several different instances.

**Comment by DAreRodz** [comment]
Thank you, @senadir. I did a quick test following @Aljullu's approach and it seems to be working fine.

I'm going to open a PR and start with the development. 🙂

**Comment by roykho** [comment]
Hi @DAreRodz 

Just realized this task was created awhile ago. We're currently working on this as well in our Epic https://github.com/woocommerce/woocommerce/issues/42255

So checking with you if you're still working on this?

**Comment by DAreRodz** [comment]
> So checking with you if you're still working on this?

Hey @roykho, thanks for the ping. I'm not working on this anymore (in fact, it's been a lot since I set this issue "on hold" in the Tracking Issue). I'll close this, as you're already working on your implementation for the Filter blocks.
