### ISSUE TITLE
New Block: All reviews

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#847]
Separated from https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/589

A simple block to list all reviews, rather than those from a category or single product.

**Comment by Aljullu** [comment]
@jwold do we have a specific icon for the _All Reviews_ block?

**Comment by jwold** [comment]
So far I am liking: https://d.pr/i/fxAQeS, I may make a custom icon for it, but for now I'd suggest we use that. Are we able to pull in a gridicon?

**Comment by Aljullu** [comment]
Thank you @jwold!

> Are we able to pull in a gridicon?

Yes, we are using them in some other blocks too.
