### ISSUE TITLE
AvaTax causes a fatal error when renewing subscriptions

### ISSUE THREAD

**Issue by opr** [woocommerce/woocommerce-gutenberg-products-block#8473]
## Describe the bug

Reported in p1676641499676679-slack-C01DT6U03HC

There is a fatal error when using AvaTax and WooCommerce 7.4.0 - this was introduced in 5c01299d6f7df8adc8b4becc9a5db71d965912a3
 
## To reproduce

1. Install [AvaTax](https://woocommerce.com/products/woocommerce-avatax/) (credentials in secret 7715) and set it up so taxes are applied to your orders. I used a store in the USA and used USA addresses.
2. Install WooCommerce Subscriptions
3. Create a Subscription product and add it to your cart. Then check out.
4. Open the **subscription** in the WP dashboard and from the subscription actions box choose "Process renewal"
5. <img width="319" alt="image" src="https://user-images.githubusercontent.com/5656702/219742801-c2d87718-ddad-4622-a2b2-b9f7eb3befdf.png">
6. See the error.

## Expected behavior

Subscription renewals should work even if AvaTax is enabled.

## Additional context

See https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/Shipping/ShippingController.php#L292 for the line this error happens on.

Also cc @woocommerce/helix in case you want to take a look - the stack trace can be found in the slack message: p1676641499676679-slack-C01DT6U03HC

**Comment by neilmccreadie** [comment]
5975104-zen

**Comment by rossviviano** [comment]
32138782-hc

**Comment by maxlaf** [comment]
37663405-hc
For searchability, this is the main error that's thrown:
```
Uncaught Error: Call to a member function get() on null in /wordpress/plugins/woocommerce/7.4.0/packages/woocommerce-blocks/src/Shipping/ShippingController.php:260
```

**Comment by nicdwilson** [comment]
5967453-zen

**Comment by rossviviano** [comment]
36019744- hc

**Comment by opr** [comment]
We have a callback for the `woocommerce_customer_taxable_address` filter in https://github.com/woocommerce/woocommerce-blocks/blob/c2e4cc03b886fd07668f0882d9bea8d291f78af0/src/Shipping/ShippingController.php#L287 which uses the session to check which shipping method is chosen.

In the context of a subscription renewal, the session is not set up, and if it were, the chosen shipping method would not be there anyway.

We need a way to check what context we're filtering the address in if possible, if it is during a renewal, we should try to derive the shipping method from the order, and if it is from an ordinary checkout, we can continue as normal.

**Comment by thracefulton** [comment]
Another instance in 40423785-hc

**Comment by sverleis** [comment]
As seen in `41300601-hc`
