### ISSUE TITLE
Product image attribute is object but not array on StoreAPI

### ISSUE THREAD

**Issue by whywilson** [woocommerce/woocommerce-gutenberg-products-block#8474]
## Describe the bug

When accessing the product information with StoreAPI, the attributes of the image should be an array. But some products are objects with numbers as the index.

## To reproduce

1. Visit the URL https://woocommerce.com/wp-json/wc/store/products/18734000927154.
2. The "images" is not an array.

**Comment by nielslange** [comment]
Hello @whywilson 👋

Thanks for reaching out. May I ask why it's a problem that the image attributes are stored as an object instead of as an array?

**Comment by whywilson** [comment]
> 

While using the StoreAPI in App, the JSON format should be standard and the same. Other products are array. But this one is object may result in the crashed in App.

**Comment by nielslange** [comment]
> While using the StoreAPI in App, the JSON format should be standard and the same. Other products are array. But this one is object may result in the crashed in App.

Currently, both the product attributes and the image attributes are using the same standard. All individual products respectively individual images are stored as objects within one array. I'm uncertain if I understand your problem correctly, as I cannot see a difference in the way these two elements are returned from the Store API. You mentioned that the app may crash. Can you tell me which app you're referring to? 

@mikejolley and @wavvves I'm keen in hearing your thoughts on this issue.

**Comment by whywilson** [comment]
> > While using the StoreAPI in App, the JSON format should be standard and the same. Other products are array. But this one is object may result in the crashed in App.
> 
> Currently, both the product attributes and the image attributes are using the same standard. All individual products respectively individual images are stored as objects within one array. I'm uncertain if I understand your problem correctly, as I cannot see a difference in the way these two elements are returned from the Store API. You mentioned that the app may crash. Can you tell me which app you're referring to?
> 
> @mikejolley and @wavvves I'm keen in hearing your thoughts on this issue.

Please check the image below for the difference.
![g2doE.jpeg](https://i.328888.xyz/2023/02/21/g2doE.jpeg)

Left link: https://woocommerce.com/wp-json/wc/store/products/18734001545617
Right Link: https://woocommerce.com/wp-json/wc/store/products/18734000927154

**Comment by wavvves** [comment]
Hi @whywilson, thanks for reporting this. 

Although I cannot reproduce it locally, indeed, our `Product` schema states the `images` data on the response should always be of `array` type.

I opened a [PR](https://github.com/woocommerce/woocommerce-blocks/pull/8499) to address this.

**Comment by whywilson** [comment]
> Hi @whywilson, thanks for reporting this.
> 
> Although I cannot reproduce it locally, indeed, our `Product` schema states the `images` data on the response should always be of `array` type.
> 
> I opened a [PR](https://github.com/woocommerce/woocommerce-blocks/pull/8499) to address this.

I cannot reproduce it in most of our stores. But it did happen on WooCommerce's official store.
Check out the link https://woocommerce.com/wp-json/wc/store/products?per_page=100 and search `"images":{"`. You'll find 2 products that their images are object.

**Comment by nielslange** [comment]
Thanks for providing additional context, @whywilson. I also had a chat with @senadir and @wavvves, and they mentioned that the image response should have the following structure:

```
"images": [
  { ... },
  { ... },
  { ... },
],
```

instead of 

```
"images": {
  1: { ... },
  2: { ... },
  3: { ... },
},
```

In #8499, @wavvves addressed this problem. Thanks again for reporting this and sorry that I didn't understand the problem initially.
