### ISSUE TITLE
Blockifying Single Product Template: Related Products block

### ISSUE THREAD

**Issue by gigitux** [woocommerce/woocommerce-gutenberg-products-block#8481]
![image](https://user-images.githubusercontent.com/4463174/220123560-58cc2ad8-433c-4048-8ee3-05ac39dffdfa.png)

The classic Single Product Template has a section called `Related Products`. We have to replicate it for the Single Product Template. We could:
- use the Products block.
- create a dedicated block that wraps the PHP code.

Do you think that should be possible using the `Products` block? I believe we could use the Products block, but I don't think we can recreate a `Related Products` behavior with the current settings available. We could create a new variation of the Products Block and pass a custom query via PHP code.

What do you think? @sunyatasattva @imanish003

**Comment by sunyatasattva** [comment]
Already replied on Slack, but I'll add the reply here too for public and future visibility:

> I agree that would be awesome to use the Products block in these cases, but how should the query be built? Should such options be available to the merchants via the inspector panel, or should perhaps “Related” and “Cross-sell” be pre-determined variation with “hidden” attributes that have no corresponding controls?
> […]
> I didn’t mean that the block itself is hidden or that merchants can’t add it. Only that these settings are not available on the inspector controls of a regular “Products” block, but can still be passed to the block by creating a variation that’s insertable.
