### ISSUE TITLE
Cart Block - Strike product price for addon prices

### ISSUE THREAD

**Issue by jamsheerkrd** [woocommerce/woocommerce-gutenberg-products-block#8488]
https://github.com/woocommerce/woocommerce-blocks/blob/cc98bc16c4109e0b1f83e875370ec4fc6bbd9039/assets/js/base/components/product-price/index.tsx#L283

It is supposed to strike only if there is a discount, so the checking must be `price < regularPrice`
Otherwise if any addon prices added up with the product price also will show a strike price

**Comment by nielslange** [comment]
Hello @jamsheerkrd 👋

Thanks for reaching out. Can you tell me how to reproduce this case?

**Comment by mikejolley** [comment]
@jamsheerkrd Are you able to provide some steps so we can reproduce this issue? Does it require an extension such as product addons? This issue will be closed unless we're able to reproduce the problem on our side. Thanks.

**Comment by opr** [comment]
Hi @jamsheerkrd thank you for taking the time to report this. I installed WooCommerce Product Add-ons and tried to reproduce but was unable to. As my colleagues have mentioned we will close this issue until we are able to reproduce.

It would be really helpful if you could provide some instructions to help us do this. Please feel free to reopen the issue when you are able to do this! Thank you.
