### ISSUE TITLE
Incorrect usage of `woocommerce_order_get_tax_location` filter. 

### ISSUE THREAD

**Issue by iamdharmesh** [woocommerce/woocommerce-gutenberg-products-block#8493]
## Describe the bug
I am working on the issue https://github.com/woocommerce/woocommerce-deposits/issues/498, it is about tax not being applied on scheduled orders when we pay using block-based checkout, taxes for scheduled orders working fine when we place orders using traditional shortcode-based checkout.  During debugging on the issue, I found that we are using the `woocommerce_order_get_tax_location ` filter [here](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/StoreApi/Utilities/OrderController.php#L63-L68) and using `wc()->customer->get_taxable_address()` as a callback to return a tax location. 

`WC_Abstract_Order::get_tax_location()` returns an Associative array of tax location while,
```
Array
(
    [country] => US
    [state] => TX
    [postcode] => 78731
    [city] => Austin
)
```

`wc()->customer->get_taxable_address()` returns a indexed array of tax location.
```
Array
(
    [0] => US
    [1] => TX
    [2] => 78731
    [3] => Austin
)
```

As we are extending `woocommerce_order_get_tax_location` with the response of `wc()->customer->get_taxable_address()`,  `WC_Abstract_Order::get_tax_location()` starts returning an indexed array instead of an associative array of tax location and `WC_Order_Item:: calculate_taxes()` skips calculate taxes as it has checks for array keys [here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-order-item.php#L216). which results in no tax applied to scheduled payments of deposit order.

As `WC_Abstract_Order::get_tax_location()` returns an associative array, it expects all functions extending `woocommerce_order_get_tax_location` should return associative array (considering the condition based on array key in other functions).

I didn't find any issue in woocommerce-blocks by this filter usage, but it creates issues with deposits extension. As this tax location is used at multiple places, there may be chances that the current usage of the filter is correct and I missed something important here and reported the issue. Please feel free to close this issue if that is the case.

Thanks

## To reproduce
Didn't find any failing use case while using only this repo, but we can reproduce the issue with the deposits extension. 
Reproduce steps are given here https://github.com/woocommerce/woocommerce-deposits/issues/498 in the description.

## Expected behavior
Extending the filter `woocommerce_order_get_tax_location` should return the same data structure (associative array instead of an indexed array).

### WordPress (please complete the following information):

-   WordPress version: 6.1.1
-   Gutenberg version (if installed): -
-   WooCommerce version: 7.4
-   WooCommerce Blocks version: 9.6.1
-   Site language: English
-   Any other plugins installed: WooCommece-Deposits

### Desktop (please complete the following information):

-   OS: macOS 13 Ventura
-   Browser: Version 110.0.5481.100 (Official Build) (arm64)
-   Version: [e.g. 22]

### Smartphone (please complete the following information):

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Comment by wavvves** [comment]
Hi @iamdharmesh this may be impacting other things I'm currently investigating, and planning to open another issue. If so a single PR may fix both. Please allow me some time to sort that out 👍🏼
