### ISSUE TITLE
Filter Products by ... : Collapse/expand product filter blocks

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#850]
Product filter blocks should have an accompanying heading, and (as per the designs) have a toggle control so the filter can be shown/hidden by the user. To do this we will build a container block.

- Filter blocks will be "atomic".
- We'll build a container block which includes heading, content toggle, and innerblocks (the filter will be added as an inner block).
- To make this easier to use, we'll release a curated filter block which includes (on first setup, automatically) all filter container blocks with filters pre-setup so the user can add/remove/move filters within it.

**Relevant Acceptance Criteria**

- [ ] The user can collapse/expand the filter in the frontend
- [ ] On mobile devices the filter should be collapsed by default

**Comment by pmcpinto** [comment]
Ok that makes sense. I just changed the issue title, considering that this collapse/expand filter feature it's supposed to be available on each "Filter Product by" block :)
