### ISSUE TITLE
[GlobalStep] [WP 6.2 Beta] "Product Price" block margin fails to update after clicking "Done" button on a test page with "All Products" block.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-gutenberg-products-block#8511]
### Bug Description:
"Product Price" block margin fails to update after clicking "Done" button on a test page with "All Products" block.

### Environment:
Woocommerce Version: WooCommerce 7.5.0-beta.1
WordPress version: 6.2-beta3

PC:
Windows 10, 
Chrome(Version 110.0.5481.104)
Firefox(Version 110.0)

### Steps To Reproduce:
1. Create any test site using Jurassic Ninja.
2. Install and activate all the required plugins.
3. Install and activate Woocommerce.
4. Add an All Products block on a new test page.
5. Click on the pencil icon to edit the layout and change the Product Price block margin.
6. Verify the margin is applied in the editor of pencil icon.
7. Now click "Done" button.
8. Observe that "Product Price" block margin fails to update on a test page with "All Products" block.

### Instruction link:
https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/testing/releases/950.md#product-price-transition-from-using-css-margin-to-global-styles-8269

### Actual Result:
"Product Price" block margin fails to update after clicking "Done" button on a test page with "All Products" block.

### Expected Result:
"Product Price" block margin should be updated after clicking "Done" button on a test page with "All Products" block.

### Screenshot:

![#8511](https://user-images.githubusercontent.com/41110392/220661318-6ac1bf49-16e4-4d58-b8ec-2fef23178ff3.gif)

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>

`
### WordPress Environment ###

WC Version: 7.5.0
REST API Version: ✔ 7.5.0
WC Blocks Version: ✔ 9.6.1
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2-beta3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.55 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.33
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.5.0
WC Database Prefix: wp_
Total Database Size: 5.05MB
Database Data Size: 3.55MB
Database Index Size: 1.50MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.47MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
page: 8
post: 3
product: 18
product_variation: 7
revision: 8
wp_global_styles: 1
wp_template: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Query Monitor: by John Blackbourn – 3.11.1
Companion Plugin: by Osk – 1.29
WooCommerce Beta Tester: by WooCommerce – 2.1.0
WooCommerce: by Automattic – 7.5.0-beta.1
WordPress Beta Tester: by Peter Westwood
Andy Fragen – 3.2.7

### Inactive Plugins (3) ###

Akismet Anti-Spam: by Automattic – 5.0.2
Hello Dolly: by Matt Mullenweg – 1.7.2
Jetpack: by Automattic – 11.8.4

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class (Drop-in)

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Three
Version: 1.0
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-02-23 13:06:17 +00:00
Options: ✔
Notes: 34
Onboarding: skipped

### Action Scheduler ###

Complete: 56
Oldest: 2023-02-22 13:07:24 +0000
Newest: 2023-02-22 13:13:24 +0000

Failed: 2
Oldest: 2023-02-22 13:11:19 +0000
Newest: 2023-02-22 13:11:30 +0000

Pending: 1
Oldest: 2023-02-23 13:07:24 +0000
Newest: 2023-02-23 13:07:24 +0000

### Status report information ###

Generated at: 2023-02-22 14:51:18 +00:00
`

</details>

**Comment by Aljullu** [comment]
I think the issue comes from the discrepancy between these two checks:
https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/atomic/blocks/product-elements/price/supports.ts#L29
https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/base/hooks/use-spacing-props.ts#L17-L21
In one, we check if `__experimentalGetSpacingClassesAndStyles` exists and in the other one whether it's the feature plugin or not. We should unify them towards one.

**Comment by albarin** [comment]
> I think the issue comes from the discrepancy between these two checks: https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/atomic/blocks/product-elements/price/supports.ts#L29 https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/base/hooks/use-spacing-props.ts#L17-L21 In one, we check if `__experimentalGetSpacingClassesAndStyles` exists and in the other one whether it's the feature plugin or not. We should unify them towards one.

Should the margin work in WC Core or only when the blocks plugin is installed? Depending on the solution could be different 🤔

**Comment by Aljullu** [comment]
I think we should keep as it was in WC 7.4: I tested and it seems like it wasn't possible to set the margin of the Product Price block inside the All Products block.

IMO we shouldn't be introducing new features to the All Products block considering it will be superseded by the Products block.
