### ISSUE TITLE
Product blocks are dependant on default WC styles

### ISSUE THREAD

**Issue by traed** [woocommerce/woocommerce-gutenberg-products-block#852]
There seems to be some dependencies on the default styles within the block CSS. I have disabled the default styles but, for example, the Newest Products block tries to add an icon to the add-to-cart-button when clicked. That icon is from the WooCommerce font and is thus broken when the default styles aren't there.

My wish would be for the blocks' CSS to only be structural. Currently, aside from the broken icon, it adds color, font-styling, etc.

1. Disable default WC styles and add your own.
2. Add the Newest Products block to a page.
3. Click on the Add to cart button
4. A broken icon is added (i.e. a black square) to the button text

**WordPress**
* Core version: 5.2.2
* WooCommerce version: 3.7.0
* Site language: Swedish

**Comment by nerrad** [comment]
I took a look at the blocks to see if there are dependencies on WooCommerce core styles and I'm not seeing any currently. It's possible this existed at one point and since the first report has been fixed (there has been a number of improvements to styles) so I'm going to close this.
