### ISSUE TITLE
Display special characters when they are part of a city name

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#8533]
## Problem

In #8531, @Moosinams mentioned that some Dutch cities can start with a single quote, for example `'s-Hertogenbosch`. While it's possible to place an order with `'s-Hertogenbosch` as city name, when placing a second order, the city name `&#8216;s-Hertogenbosch` appears in the Checkout block.

## Steps to reproduce

1. Add a product to the cart.
2. Go to the checkout. 
3. Place the order with the following address:
```
Address         : Stationsplein 151
Country/Region  : Nederland
Postal code     : 5211 BP
City            : 's-Hertogenbosch
```
4. Place another order.
5. Verify that the prefilled city name appears as `&#8216;s-Hertogenbosch`.

## Additional cities that start with an apostrophe:

- ’s-Gravenhage (The Hague) - Netherlands
- ’s-Hertogenrade - Netherlands
- ’s-Heerenberg - Netherlands
- ’s-Heer Abtskerke - Netherlands
- ’s-Heer Arendskerke - Netherlands
- ’s-Heerenhoek - Netherlands
- ’s-Heer Hendrikskinderen - Netherlands

**Comment by wavvves** [comment]
@nielslange In my opinion, we shouldn't prevent data from being escaped. Instead, decode the HTML entities or make sure the browser can parse them properly for displaying. It's highly likely this problem affects other fields 🤔

**Comment by Moosinams** [comment]
Dear Niels,

Sorry to aks you in this way.
I have a problem with the checkout-page.
 It gives error; invalid parameter owner[name]. Owner name must be at least
3 characters long.

Hope you could help me using my email.

I find it to difficult to pass it on github.

Greetings
Moos
[image: Schermafbeelding 2023-04-11 om 10.58.14.jpg]

Op vr 24 feb 2023 om 13:03 schreef Niels Lange ***@***.***>:

**Comment by nielslange** [comment]
> @nielslange In my opinion, we shouldn't prevent data from being escaped. Instead, decode the HTML entities or make sure the browser can parse them properly for displaying. It's highly likely this problem affects other fields 🤔

Good point, @wavvves. My primary intension was to ensure that city names with special characters are displayed correctly. I changed the title of this issue accordingly.

**Comment by nielslange** [comment]
> Dear Niels, Sorry to aks you in this way. I have a problem with the checkout-page. It gives error; invalid parameter owner[name]. Owner name must be at least 3 characters long. Hope you could help me using my email. I find it to difficult to pass it on github. Greetings Moos

Hello @Moosinams 👋

To avoid confusion, please create a separate issue for your question.

**Comment by dnusca** [comment]
I'd like to pick this one up!

**Comment by dnusca** [comment]
@nielslange I'm wondering at what level in the component hierarchy the HTML entities should be decoded?

We've got:

- AddressForm
-- ValidatedTextInput
--- TextInput

I was going to decode the entities inside TextInput, but might there be a use case for displaying encoded html entities in a TextInput?

**Comment by nielslange** [comment]
> [...] I'm wondering at what level in the component hierarchy the HTML entities should be decoded?

Thanks for reaching out, @dnusca. Given the component hierarchy, decoding the HTML entities inside the `TextInput` component would be appropriate. This follows the general principle from both [WordPress.org](https://developer.wordpress.org/apis/security/#h-guiding-principles) and [WordPress VIP](https://docs.wpvip.com/technical-references/security/validating-sanitizing-and-escaping/#h-guiding-principles) guidelines to escape data as late as possible.

**Comment by dnusca** [comment]
Thanks. I've submitted a PR with the changes in the `TextInput`

**Comment by Moosinams** [comment]
Tnx for your help.

Moos

Op wo 19 apr. 2023 om 18:53 schreef Paulo Arromba ***@***.***>
