### ISSUE TITLE
Allow more than 6 rows in product grid blocks

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#854]
**User Story:**
As a merchant I want to display all products of a category which has 37 products. Currently, the blocks included in WooCommerce allow a maximum of 6 columns and 6 rows, so only 36 products can be displayed in the same block.

Allowing more than 6 rows would fix the issue.

**Links:**
Suggestion made on WP.org forum. Thread [here](https://wordpress.org/support/topic/only-the-outdated-version-of-a-plugin-works/#post-11826679).

**Comment by mikejolley** [comment]
Instead of damaging performance by trying to render too many products in one request, why not support pagination?

**Comment by denisegiusti** [comment]
Hi.

I have the same problem, need more rows to add all the products.

Is it going to be added?

Thank you so much

**Comment by nerrad** [comment]
An original design motivation behind the product grid blocks (h/t @LevinMedia  for the history lesson) was to provide a way for merchants to expose a short list of products (given the block type) on marketing type/aggregation type pages as an entrypoint to their full catalog. They were never intended to be an alternate way of creating product archive type views (replacing a shop page for example).

With that said, since we also intend on migrating the older blocks to a different rendering method (product element and inner blocks), this is something that we'll revisit as a part of that migration (when it happens). So based on the above, I'm closing this issue.

**Comment by companyofwords** [comment]
This is really poor for customer service and experience - considering Woocommerce have charged for paid extensions which only work using Gutenburg blocks. This inflexibility means we have to choose a free alternative and abandon our paid for extension....can we get a refund?

**Comment by gustavo-roganti** [comment]
WooCommerce reads the max_row variable using this code:

`wc_get_theme_support( 'product_blocks::max_rows', 6 )`

Which means you can customize the value in your theme using

`add_theme_support('woocommerce',['product_blocks' => ['max_rows' => 10]]);`

**Comment by openmindculture** [comment]
Tried this code in a WooCommerce site using WooCommerce blocks, but no success.

**Comment by gustavo-roganti** [comment]
I have been able to force the number of max_rows and default_rows to be higher than 6:

    add_theme_support('woocommerce',['product_blocks' => ['max_rows' => 100, 'default_rows' => 100]]);

In newer WooCommerce versions the default_rows is buggy, and it is re-set to 6 somehow.

The block works if you set it to show any number of rows, eg. 99, so long as it is NOT the "default_rows" number.

I eventually coded a fix for the "default_rows" issue:


	//the default number of rows is ignored by the block on frontend. Grrrrr. Set it again in a filter.
	add_filter( 'register_block_type_args', function( $args, $block_name ) {
        // apply to any block that extends AbstractProductGrid
        $AbstractProductGrid_blocks = [
            'woocommerce/handpicked-products',
            'woocommerce/product-best-sellers',
            'woocommerce/product-category',
            'woocommerce/product-new',
            'woocommerce/product-on-sale',
            'woocommerce/products-by-attribute',
            'woocommerce/product-tag',
            'woocommerce/product-top-rated',
        ];
        if ( in_array( $block_name, $AbstractProductGrid_blocks) ) {
            if (isset($args['attributes']) && isset($args['attributes']['rows']) && isset($args['attributes']['rows']['default'])) {
	            $args['attributes']['rows']['default'] = 100;
            }
        }
		return $args;
	}, 10, 2 );

Hope it helps

**Comment by openmindculture** [comment]
The above code works for some types of product grid, like the shortcode `[products]`.
But the [classic / legacy template block: archive-product](https://fullsiteediting.com/lessons/woocommerce-and-full-site-editing/#h-using-the-woocommerce-classic-template-block) (`<!-- wp:woocommerce/legacy-template {"template":"archive-product"} /-->`), now used as it seems to be the most compatible with third-party plugins, and one of the few to support WooCommerce's basic product category (`tax-product_cat`, using the `wp:woocommerce/product-categories` WooCommerce product categories list block), sadly does not honor the workaround in `functions.php` and it does not support any official `rows` or number of products limit parameter either.

Does anyone know a solution to display _all_ products on the product archive page without any pagination, using the classic legacy products block?

**Comment by Paul-Morris** [comment]
If gustavo-roganti's  solution isn't working for you, try deleting the block and re-adding  it back to your page. 

No matter how much cache clearing and banging my head on the keyboard, I could not get this to work until I discovered I simply had to re-add the block. Thanks Gustavo!

**Comment by Paul-Morris** [comment]
Thanks this works great, BUT I found it only works with **Products by Category** block  if I set rows to **3** in the wordpress interface. Also it only displays more than 6 rows in the front end, not in the wordpress editor. Took me forever to realize that!

Hopefully that helps anyone else who spent a few hours trying to fix it!


> I have been able to force the number of max_rows and default_rows to be higher than 6:
> 
> ```
> add_theme_support('woocommerce',['product_blocks' => ['max_rows' => 100, 'default_rows' => 100]]);
> ```
> 
> In newer WooCommerce versions the default_rows is buggy, and it is re-set to 6 somehow.
> 
> The block works if you set it to show any number of rows, eg. 99, so long as it is NOT the "default_rows" number.
> 
> I eventually coded a fix for the "default_rows" issue:
> 
> ```
> //the default number of rows is ignored by the block on frontend. Grrrrr. Set it again in a filter.
> add_filter( 'register_block_type_args', function( $args, $block_name ) {
>     // apply to any block that extends AbstractProductGrid
>     $AbstractProductGrid_blocks = [
>         'woocommerce/handpicked-products',
>         'woocommerce/product-best-sellers',
>         'woocommerce/product-category',
>         'woocommerce/product-new',
>         'woocommerce/product-on-sale',
>         'woocommerce/products-by-attribute',
>         'woocommerce/product-tag',
>         'woocommerce/product-top-rated',
>     ];
>     if ( in_array( $block_name, $AbstractProductGrid_blocks) ) {
>         if (isset($args['attributes']) && isset($args['attributes']['rows']) && isset($args['attributes']['rows']['default'])) {
>             $args['attributes']['rows']['default'] = 100;
>         }
>     }
> 	return $args;
> }, 10, 2 );
> ```
> 
> Hope it helps
