### ISSUE TITLE
The "Add Coupon" link event not translated in Cart & Checkout blocks.

### ISSUE THREAD

**Issue by Babylon1999** [woocommerce/woocommerce-gutenberg-products-block#8541]
## Describe the bug

The "add coupon" event is not translated to French although I can find the string translated in the [stable release](https://translate.wordpress.org/projects/wp-plugins/woo-gutenberg-products-block/stable/fr/default/). 

## To reproduce

Steps to reproduce the behaviour:

1. Switch the site language to French
2. Add Cart/Checkout Block
3. The coupon addition link is not translated

## Expected behaviour

To be translated as the rest of the block elements

## Screenshots

<img width="1064" alt="image" src="https://user-images.githubusercontent.com/67080558/221246801-fbe6e310-4558-4c67-8a95-4cae07ba172d.png">

### WordPress (please complete the following information):

WordPress address (URL): https://test.wpcomstaging.com
Site address (URL): https://test.wpcomstaging.com
WC Version: 7.4.0
REST API Version: ✔ 7.4.0
WC Blocks Version: ✔ 9.6.2
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: fr_FR
External object cache: ✔

### Desktop (please complete the following information):

-   OS: MacOS
-   Browser: Firefox

## Additional context

Related tickets: zd-5986847

**Comment by Babylon1999** [comment]
https://wordpress.org/support/topic/translate-add-a-coupon/

**Comment by ralucaStan** [comment]
Closing as the issue was fixed
