### ISSUE TITLE
Express checkout buttons doesn't collapse properly 

### ISSUE THREAD

**Issue by malithsen** [woocommerce/woocommerce-gutenberg-products-block#8545]
## Describe the bug

On Tsubaki theme, when more than one express payment method is active, express buttons are collapsed but appear with no margin between the buttons. 

## To reproduce

1. Install and activate Tsubaki theme (default theme on WPCOM e-commerce sites)
2. Install WCPay and enable more than one express payment method from Payments -> Settings -> Express checkouts
3. As a customer, add a product to the cart and go to checkout
4. Notice the broken checkout buttons

## Expected behavior

Have enough margin between the buttons

## Screenshots
![SCR-20230224-kpb](https://user-images.githubusercontent.com/6216000/221291757-bd188719-c2ad-4f0d-adf9-fdb749b12389.png)

**Comment by csmcneill** [comment]
We discussed this in a meeting today about WooPay.

If merchants experience this issue before WooCommerce 7.5.0 is released, here's a quick and dirty CSS snippet that resolves the issue on my test site running T22 and WCPay 5.5.1:

```
.wc-block-components-express-payment .wc-block-components-express-payment__event-buttons {
	flex-wrap: inherit;
}
```

cc @pierorocca @c-shultz
