### ISSUE TITLE
Block variations usage is not correctly tracked

### ISSUE THREAD

**Issue by sunyatasattva** [woocommerce/woocommerce-gutenberg-products-block#8546]
Currently, the tracking code does not account for block variations, so block usage is reported as the original block name (e.g. `core/query` instead of `woocommerce/product-query`). This is pretty bad as we need to accurately track data for our blocks to get meaningful metrics.

In order to correctly track variation data, we could hook into [this filter](https://opengrok.a8c.com/source/xref/wpcom/wp-content/mu-plugins/tracks/hooks/posts-and-pages.php?r=58f2ccf6&mo=4206&fi=110#105) and use the `namespace` property and `__woocommerceNamespace` assigned to block variations to identify our blocks. A similar approach is used in Jetpack [here](https://opengrok.a8c.com/source/xref/wpcom/wp-content/mu-plugins/tracks/hooks/posts-and-pages.php?r=58f2ccf6#426-439).

**Comment by imanish003** [comment]
As discussed in the slack thread(p1678199954444849-slack-C03Q87XT1QF), we will be implementing tracking of block variations in Jetpack & WPCom, where general tracking of blocks exists. 

Therefore, I am closing this issue.
