### ISSUE TITLE
Is the single product block available at all?

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce-gutenberg-products-block#8547]
![image](https://user-images.githubusercontent.com/507025/221365572-ed91db54-15a1-4282-8a96-a790abbeaf32.png)

Feels like a bit of a facepalm question in waiting, but I don't see the Single Product block at all.... does it not exist? Do you need to do something to enable it? This is a fresh clone of the repo after `npm run build`.

**Comment by nerrad** [comment]
We chatted in the WooCommerce community slack about this, so I think you're okay on that Kathy? Short answer is no, not yet 😄.
