### ISSUE TITLE
wcSettings loads a lot of dubplicate/unnecessary data

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#8555]
wcSettings loads a lot of unnecessary data like loading all countries and their states, sometimes twice (for shipping and billing), this can be optimized and we can load a subset of those informations or only load them when we know we need them.

I did something like that before https://github.com/woocommerce/woocommerce-blocks/pull/6901

**Comment by mikejolley** [comment]
I'm working on a combined country property to reduce duplication.
