### ISSUE TITLE
The Customer Account block should show up when searching for "My Account"

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#8570]
The Customer Account block is displayed as a "My Account" link:

<img src="https://user-images.githubusercontent.com/3616980/221817816-66dcb6b2-37b1-4e12-9a15-9566a3a32325.png" alt="" width="235" />

However, if you look for "My Account" in the block inserter, the Customer Account block doesn't show up:
<img src="https://user-images.githubusercontent.com/3616980/221818134-b451c344-ca5c-47ba-bb03-ad4ca2d6642d.png" alt="" width="372" />

As a user, I would like that if I search for "My Account", the Customer Account block is displayed.

We could use the [`keywords` property](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-metadata/#keywords) for this.

**Comment by masteradhoc** [comment]
@Aljullu made a small PR for this.
