### ISSUE TITLE
Cart Block > column display not working anymore

### ISSUE THREAD

**Issue by Marc-pi** [woocommerce/woocommerce-gutenberg-products-block#8581]
## Describe the bug

Willing to test the new Local Pickup feature (especially how it is displayed in cart page), i stumble opon a strange change, that seems to be a nice regression ;-)
* Adding a new instance of the Cart Block generates the cart in a single column on front (even if the columns blocks are used by the cart block).
 * There is no way to display it in 2 columns on front like it was before
* Confirmed on several websites.

## To reproduce

On 2 websites that did run already WooCommerce 
1. Create a new page
2. Add the Cart Block within
3. Compare the new layout with the current Cart page (i did have a cart page already)

NB i am not able to see the new display with steps for Local Pickup. When submiting the Local Pickup setting Page, i get a blank page. I'll open a new issue after this one if fixed / confirmed.
![image](https://user-images.githubusercontent.com/919332/221967211-db7539d9-7d01-4fa8-a05a-6a58dba3c9a7.png)

I did read the Local Pickup test protocol
https://github.com/woocommerce/woocommerce-blocks/blob/b49573b91d37cff511c3fb3288e0458dbf0c582f/docs/internal-developers/testing/cart-checkout/local-pickup.md

## Expected behavior

Add back 2 columns on desktop ?!?
I did not read there was a change on this ?
I did not find any warning in https://github.com/woocommerce/woocommerce-blocks/pull/7433, nor after a search on other issues/PR.
Or did i miss something : local pickup feature changed the way the cart is displayed (desktop and mobile == same display ?)

## Screenshots

* Old Behavior

![image](https://user-images.githubusercontent.com/919332/221964650-f69becef-b5e9-4430-9578-51962b02fbac.png)

* Actual display

![image](https://user-images.githubusercontent.com/919332/221965748-4d891350-cdc3-4cf7-9ec8-017ee2c3897d.png)

## WP Environment

WP 6.1.1
Woo 7.4.0
Woo Blocks 9.6.3
Theme TT2
No other plugins installed

**Comment by Marc-pi** [comment]
same findings on Woo 7.4.1

**Comment by Marc-pi** [comment]
confirmed on Woo Blocks 9.7.0 as well

**Comment by ralucaStan** [comment]
@Marc-pi thank you so much for trying out Local pickup.
I tried testing again with the latest version 9.8.0 and I was not able to replicate it.
- I activated the blocks local pickup 
- I created a new page and added the Cart block
- I checked both the editor and the front-end and things worked as expected.

Would you mind trying again and sharing the results. Thank you so much for your help.

**Comment by ralucaStan** [comment]
Hey @Marc-pi 
I am going to close this issue as there was no reply from your side and we couldn't replicate.

With https://github.com/woocommerce/woocommerce-blocks/issues/8894 we enforced a wide alignment for the C & C Blocks.

Also, there is the option to change the Align for blocks from none to wide 
<img width="333" alt="Screenshot 2023-04-10 at 14 53 35" src="https://user-images.githubusercontent.com/1628454/230897103-7b420abe-3da1-4a57-9737-91e8be4b6f48.png">
