### ISSUE TITLE
Page scrolls to top when selecting new payment method radio button

### ISSUE THREAD

**Issue by malithsen** [woocommerce/woocommerce-gutenberg-products-block#8584]
## Describe the bug

Page scrolls to top when selecting the radio button to use a new payment method.
This only seems to happen when "Use same address for billing" checkbox is unchecked

## To reproduce

1. Go to Blocks checkout
2. Uncheck "Use same address for billing"
3. Under Payment Options, select "Credit card / debit card" radio button
4. Notice that the page scrolls up when selecting the radio button

## Expected behavior

Scroll position should not change when selecting radio buttons

## Screenshots

https://user-images.githubusercontent.com/6216000/222030984-5930ee2d-b261-4d71-9ed1-9ac22edd6d76.mov

**Comment by ralucaStan** [comment]
Thank you @malithsen for reporting this. I was not able to replicate it.

@mikejolley mind trying replicating it as well?

**Comment by mikejolley** [comment]
I'm not able to replicate this on trunk; using Stripe, opening address (logged in user), address is populated, toggle.

Any other clues @malithsen? Are there are validation errors present in the address form? What version are you running this on?

**Comment by malithsen** [comment]
hm I no longer have access to the test site I used for this. Just retested with the latest Blocks and I can't replicate it anymore either.

Thanks for taking a look @ralucaStan @mikejolley and apologies for the false alarm. Closing this.
