### ISSUE TITLE
Filter's heading displays for a moment and disappears if there's no product

### ISSUE THREAD

**Issue by kmanijak** [woocommerce/woocommerce-gutenberg-products-block#8586]
### Description
In case there are no filtering options in a particular filter, the filter is not displayed. It may occur if the other filter's condition narrows down the product set so much, that there's no filtering option left in the first one. In this case, filter options won't be displayed, however, the heading will for a moment.

### Steps to reproduce
1. Create new Page
2. Add Filters pattern
3. Don't add any products grid (that mimics the situation there's no filtering options, because of lack of products)
4. Save the page and go to the frontend

**Expected**: Filters don't appear
**Actual**: Filters don't appear, but the headings appear for a moment and then disappear

### Video

https://user-images.githubusercontent.com/20098064/222080473-0627ec75-3a83-4a78-bde7-5f095b66a513.mov

### Suggested fix
Currently, the heading is displayed by default and once the API call for a filter options resolves, the decision on whether to hide the heading is made. I think it should be reversed: hide the heading by default and if there ARE options to display, show the heading and options.

**Comment by nerrad** [comment]
One concern I have, that we should watch for here is to minimize any contributions to cumulative layout shifts.

**Comment by kmanijak** [comment]
Closing as not relevant anymore
