### ISSUE TITLE
Mini Cart: Button styling is inconsisten between the editor and the front-end

### ISSUE THREAD

**Issue by albarin** [woocommerce/woocommerce-gutenberg-products-block#8587]
## Describe the bug

Some button styles show in a different background color, size or text color in the editor and in the front-end.

## To reproduce

1. Enable TT3 theme with the Aubergine style.
2. Go to the Site Editor and add the mini-cart block to the header and save.
3. Go to the Site Editor and edit the mini-cart template part and save.
4. Check the cart buttons in the editor vs the cart buttons in the front-end are different.

| Editor | Front-end |
| ------ | ----- |
| <img width="486" alt="Screenshot 2023-02-28 at 10 41 52" src="https://user-images.githubusercontent.com/186112/221814583-b6cf968b-5b5b-4d70-821b-7667f83aa5f9.png"> | <img width="485" alt="Screenshot 2023-02-28 at 10 41 46" src="https://user-images.githubusercontent.com/186112/221814479-f42ec118-b41e-4372-9ec8-c52a1d927716.png"> |

1. Enable TT3 theme with the Whisper style.
2. Create a new page and add a Single Product and a Checkout block and save.
3. Check the cart buttons in the editor vs the cart buttons in the front-end are different.

| Editor | Front-end |
| ------ | ----- |
| <img width="499" alt="Screenshot 2023-03-01 at 10 01 41" src="https://user-images.githubusercontent.com/186112/222092514-201d45e3-88be-47c5-ad9a-58af77f8ef97.png">|<img width="512" alt="Screenshot 2023-03-01 at 10 01 51" src="https://user-images.githubusercontent.com/186112/222092537-fae29747-d360-406c-b0df-35f02a5b78b3.png">|
| <img width="236" alt="Screenshot 2023-03-01 at 10 01 58" src="https://user-images.githubusercontent.com/186112/222092684-8b46beba-1ee6-4692-a298-64bdc7e36955.png"> | <img width="261" alt="Screenshot 2023-03-01 at 10 01 54" src="https://user-images.githubusercontent.com/186112/222092822-ec84a81c-5c87-444e-94ab-0c1bc4ea5e39.png"> |

## Expected behavior

The button styling should be consistent in both cases.

**Comment by ralucaStan** [comment]
@tarunvijwani would you mind linking this ticket to the corresponding one from your project that would also close it?

**Comment by ralucaStan** [comment]
Or better yet close this in favor of your project tickets.

**Comment by tarunvijwani** [comment]
Thank you, @ralucaStan!  Closing the issues in favor of #8808 #8810 #8713 #8712

**Comment by tarunvijwani** [comment]
Re-opening the ticket as it also involves mini-cart and single product issues. 

Cart and Checkout problems will be handled in https://github.com/woocommerce/woocommerce-blocks/issues/8808 https://github.com/woocommerce/woocommerce-blocks/issues/8810 https://github.com/woocommerce/woocommerce-blocks/issues/8713 https://github.com/woocommerce/woocommerce-blocks/issues/8712

Moving this to other team pipeline in the Rubik board.

**Comment by ralucaStan** [comment]
Oh, thank you @tarunvijwani. I did not realize it was about the Mini cart. I updated the title.
