### ISSUE TITLE
WooCommerce/Templates elements broken

### ISSUE THREAD

**Issue by nathyraissa** [woocommerce/woocommerce-gutenberg-products-block#859]
I use the theme children in my template but after of update, some styles disappear....
Exemple: when i use WooCommerce/Blocks in wordpress.

Exist one documentation of the new woocommerce 3.7 for themes children?

Thank

**Comment by mikejolley** [comment]
I've consolodated all related issues to extending blocks into https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/891 until a decision is made. Please see that issue and add feedback there if relevant. 

Thanks
