### ISSUE TITLE
Add ability to remove and change quantity of products in the checkout page (summary section)

### ISSUE THREAD

**Issue by Levi-70** [woocommerce/woocommerce-gutenberg-products-block#8596]
this is a enhancement not a bug

**Comment by Levi-70** [comment]
![image](https://user-images.githubusercontent.com/41117997/222201582-bc6da1f3-42bf-42ed-9b27-bc5b2389be33.png)
this idea but in the checkout

**Comment by ralucaStan** [comment]
Hey @Levi-70, thank you for your suggestion.

I will close the ticket for now; We took note of it and we might consider it in the future.  
Happy to hear any future feedback you might have on the checkout blocks.
