### ISSUE TITLE
Shortcode detection

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce-gutenberg-products-block#86]
I think it would be awesome if we could detect when folks attempt to use the existing products shortcode and offer to insert the products block instead.

We could use the same UI as the `/blockname` command in Gutenberg;

![slash](https://cldup.com/N2DrMviYMy-3000x3000.png)

So listen for `[products` and if that's entered pop up the suggestion.

**Comment by LevinMedia** [comment]
Relates to #8
