### ISSUE TITLE
Customer Account Block: Adjust Icon size

### ISSUE THREAD

**Issue by iamtakashi** [woocommerce/woocommerce-gutenberg-products-block#8607]
## Describe the bug

I like how easy to add an icon for the block, but the only thing is that the default size and the space around the icon are quite different from the Mini Cart block. I can adjust it with the font size and the block spacing, but it's fiddly. Having the two icons side by side is a reasonable use case, and it'd be nice if they were uniform so that it gives you good default.

For example, the default size gives you this. 

![Screenshot 2023-03-02 at 12 03 36](https://user-images.githubusercontent.com/908665/222435762-dcd368e7-c8f7-4b7a-91f6-5fad305b73e7.jpg)

## To reproduce

1. Go to Site Editor
2. Add the mini cart block and the customer account block
3. Choose the icon only option for both
4. See the size difference.

## Expected behavior

It'd be nice if the icon sizes and the dimensions of the blocks are uniform for both blocks (when the icon only option is selected)

### WordPress (please complete the following information):

-   WordPress version: 6.1.1
-   Gutenberg version (if installed): Trunk
-   WooCommerce version: 7.4.1
-   Site language: English
-   Any other plugins installed: Jetpack

### Desktop (please complete the following information):

-   OS: macOS
-   Browser: Chrome
-   Version: 110.0.5481.177

## Additional context
pNEWy-gbp-p2#comment-55742

**Comment by roykho** [comment]
Closing this as resolved via [PR](https://github.com/woocommerce/woocommerce-blocks/pull/8821)
