### ISSUE TITLE
woocommerce-blocks 9.7.1 crashed site with a Fatal error

### ISSUE THREAD

**Issue by aikar-sonera** [woocommerce/woocommerce-gutenberg-products-block#8619]
Hi

woocommerce-blocks where automaticaly updated to 9.7.1 in my website and it crashed the site:

Fatal error: Uncaught Error: Class 'WP_HTML_Tag_Processor' not found in /var/www/clients/client1/web217/web/wp-content/plugins/woo-gutenberg-products-block/src/Interactivity/woo-directives.php:112 Stack trace: #0 /var/www/clients/client1/web217/web/wp-includes/class-wp-hook.php(310): woo_process_directives_in_block() woocommerce/woocommerce-blocks#12058 /var/www/clients/client1/web217/web/wp-includes/plugin.php(205): WP_Hook->apply_filters() woocommerce/woocommerce-blocks#2 /var/www/clients/client1/web217/web/wp-includes/class-wp-block.php(291): apply_filters() woocommerce/woocommerce-blocks#3 /var/www/clients/client1/web217/web/wp-includes/blocks.php(1051): WP_Block->render() woocommerce/woocommerce-blocks#4 /var/www/clients/client1/web217/web/wp-includes/blocks.php(1089): render_block() woocommerce/woocommerce-blocks#5 /var/www/clients/client1/web217/web/wp-includes/class-wp-hook.php(308): do_blocks() woocommerce/woocommerce-blocks#6 /var/www/clients/client1/web217/web/wp-includes/plugin.php(205): WP_Hook->apply_filters() woocommerce/woocommerce-blocks#7 /var/www/clients/client1/web217/web/wp-includes/post-template.php(255): apply_filters() woocommerce/woocommerce-blocks#8 /var/www/clients/client1/web217/web/wp-content/themes/Avada/page.php(24): the_content() in /var/www/clients/client1/web217/web/wp-content/plugins/woo-gutenberg-products-block/src/Interactivity/woo-directives.php on line 112

I had to deactivate gutenberg blocks for the moment, could you please check these lines in your code? Kind regards

**Comment by AdamiPL** [comment]
same problem on my all WooCommerce sites

**Comment by Marc-pi** [comment]
yep, confirmed also
i've rolled back to 9.7.0

**Comment by ahegyes** [comment]
Same problem. Rolling back to 9.7.0 fixes it.

**Comment by nielslange** [comment]
Thanks for reporting this! We're already looking into this and working on a fix.

**Comment by Marc-pi** [comment]
thx @nielslange ;-)

**Comment by zdenys** [comment]
41196668-hc

**Comment by Marc-pi** [comment]
upgrade to 9.7.2 went smoothly

**Comment by Marc-pi** [comment]
@nielslange 
what was finaly the culprit about this upgrade bug ?

**Comment by aikar-sonera** [comment]
No problem after upgrade to 9.7.2. Thanks for the fast response.

**Comment by nielslange** [comment]
> @nielslange what was finaly the culprit about this upgrade bug ?

@Marc-pi When creating the 9.7.1 patch release, some PRs that had been merged into `trunk` slipped into the `release/9.7.1` branch. This caused the fatal error under certain conditions.

**Comment by Marc-pi** [comment]
@nielslange silly, i was looking at trunk

> The issue could be reproduced in WordPress sites which didn’t have Gutenberg enabled.

i guess we can close this issue now
keep it up

**Comment by nielslange** [comment]
Closing this issue as it had been resolved with the WooCommerce Blocks 9.7.2 patch release.
