### ISSUE TITLE
StoreAPI docs: Add an example of a POST request when adding a simple and a variable product to the Cart

### ISSUE THREAD

**Issue by jonathan-dejong** [woocommerce/woocommerce-gutenberg-products-block#8626]
### Issue

In regards to this section: https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/StoreApi/docs/cart.md#add-item

I spent many hours now debugging and trying to understand why the endpoint kept rejecting my POST body when it looked like this:

```
{
    "id": "891768",
    "quantity": "1",
    "variation": [
        {
            "attribute": "attribute_pa_produkt-size",
            "value": "30"
        },
        {
            "attribute": "attribute_pa_produkt-length",
            "value": "60-cm"
        }
    ]
}
``` 

I ended up stepping through all the code that the storeAPI runs the request through and eventually found that it doesn't want the attribute keys with the `attribute_` part in it. 
In the sanitation here: https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/StoreApi/Utilities/CartController.php#L1300

It gets the full attribute name, but then it checks the provided attribute name against the partial one only to return the full name in the end in the `$return`. 

In a perfect world I would've liked the sanitation to support either. 
The reason for this is because if I want to fetch the variations attributes in the most efficient manner in the frontend with on a single product, I will use the `data-product_variations` data set on the variation form. 
I fall back to fetching them another way, but if that data already exists it's a lot more efficient. 

### Solution

But at the very least we should specify in this documentation what format the data is requested to be in. 
Preferably perhaps with an example request of both a simple and a variable product?

**Comment by jonathan-dejong** [comment]
To clarify this is how it would expect that body to look like right now:

```
{
    "id": "891768",
    "quantity": "1",
    "variation": [
        {
            "attribute": "pa_produkt-size",
            "value": "30"
        },
        {
            "attribute": "pa_produkt-length",
            "value": "60-cm"
        }
    ]
}


```

**Comment by tarhi-saad** [comment]
Hello @jonathan-dejong! 👋 Thank you for pointing this out! 🙌 I agree! An example of a POST request would be helpful in this case! I'll update the issue title & description and add this ticket to our backlog!

**Comment by tva77** [comment]
should be nice to add the headers to be sent, too.
