### ISSUE TITLE
[PHP 8.1 Compatibility] Deprecated code

### ISSUE THREAD

**Issue by ralucaStan** [woocommerce/woocommerce-gutenberg-products-block#8628]
StoreApi uses some obsolete code for PHP 8.1:

### Expected behavior

Running "Query Monitor" extension and, we shouldn't see deprecated functions when using PHP 8.1.

### Actual behavior

```

Deprecated	Creation of dynamic property Automattic\WooCommerce\StoreApi\Schemas\V1\CheckoutSchema::$image_attachment_schema is deprecated	2	

    wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/StoreApi/Schemas/V1/CheckoutSchema.php:51

	Extension : woocommerce
	
```

### Steps to reproduce

Setup a WordPress with WooCommerce extension, powered by PHP 8.1 on the server.
Install Query Monitor extension.
Check PHP errors and warnings, to see them.

related to https://github.com/woocommerce/woocommerce/issues/33808

**Comment by SK-Crow** [comment]
Just found this issue.  Having the same problem on 8.2:  https://github.com/woocommerce/woocommerce/issues/37231
