### ISSUE TITLE
Product Meta block: Icon and description

### ISSUE THREAD

**Issue by gigitux** [woocommerce/woocommerce-gutenberg-products-block#8630]
With #8484, we introduced the Product Meta block.

![image](https://user-images.githubusercontent.com/4463174/222753328-0e55346a-aa3d-4073-aef0-08d0bdd7e26e.png)

We should revisit the icon and the description of this block.

**Comment by shaunandrews** [comment]
<img width="989" alt="CleanShot 2023-04-21 at 15 09 04@2x" src="https://user-images.githubusercontent.com/191598/233715983-4b5ffd78-6785-4789-8da2-7bc07234d8bc.png">

![Box with Dots](https://user-images.githubusercontent.com/191598/233715992-06d5bb2c-e166-4c48-a9fa-5bb47df44479.svg)

Here's a new icon. Could we also please update the description to "Display a product’s SKU, categories, tags, and more."
