### ISSUE TITLE
Filter Products by ... : Add filters to default shop page

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#864]
This was part of https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/786/https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/710 to aid discovery but is not technically possible yet. 

Quoting @jwold:

I'm not sure if this is technically possible until we have block areas enabled. I am imagining I could open the Product Archive Page, start editing it in Gutenberg, and see something like this:

![62248323-ab329600-b39c-11e9-82e0-0efed6d04df9](https://user-images.githubusercontent.com/90977/63027421-d9d46480-bea4-11e9-9492-faf140661785.jpg)

So the filter block would be in a group block, and in the left column. The "all products" block (this doesn't actually exist) or a shortcode would be in the right. That "all products" block/shortcode would not be user editable, and maybe not even visible on the backend, in its place you'd just see this preview message.

Then, when someone comes to edit this page they're presented with the filter blocks already in place, which helps make it easier to know how to add and remove the filter blocks.

---

So for this to be feasible we'll need to wait for:

- A way in order to control sidebar and content in Gutenberg (widget areas)
- All other filter blocks to be ready

**Comment by jwold** [comment]
As a possible expansion on this idea I played around with what an editable All Products block could look like:

<img width="868" alt="Screen Shot 2019-08-14 at 12 49 19 PM" src="https://user-images.githubusercontent.com/3411173/63051354-f4511280-be91-11e9-86f2-cf26c3e4538b.png">

[Figma link](https://www.figma.com/file/WRaazltkXXrHSDizltrZRf/All-Products?node-id=0%3A1)

**Comment by nerrad** [comment]
@mikejolley what do you think about closing this issue now that we have the All Products and Filter blocks?  I think this issue still pertains a bit towards replacing the current shop page with the All Products block but sounds like something that can be opened up separately when we want to do that?

**Comment by mikejolley** [comment]
@nerrad Let's close. I think we've abandoned the idea of using these for the main shop page with the inclusion of `wp.data` and all products. The 2 approaches are not compatible.
