### ISSUE TITLE
Default Payment Method isn't selected in Mobile

### ISSUE THREAD

**Issue by Trinituz** [woocommerce/woocommerce-gutenberg-products-block#8640]
As the title said, default payment method isn't selected at least in iOS (tested in both Chrome and Safari) 

This kind of forced one to display 2nd unwanted method in order to show radio button, as having only one payment method does not show radio button and can deters customer.
![242136](https://user-images.githubusercontent.com/127100756/223092867-575fd81a-1fb7-4dff-86fa-faf7e9cb3120.jpg)

**Comment by nielslange** [comment]
Hello @Trinituz,

Thanks for reaching out, and apologies for my delayed response. I just looked up https://shop.advanced-intelligence.com/, but I can only see the payment option _Debit/Credit Card_ both on desktop and mobile. Have you removed the 2nd payment option meanwhile?

**Comment by ralucaStan** [comment]
Hey @Trinituz, thank you for reaching out. 
I was not able to replicate this, in iOS (tested in both Chrome and Safari) with multiple themes.

It might have something to do with your theme. I see you don't use the block anymore but I recommend trying it with another theme to see if you can replicate.

I am going to close for now as there is nothing on our side we can do. Feel free to report the bug to the theme creators if you find out that it is theme specific.
