### ISSUE TITLE
Cart block sticky footer in mobile should have the same background as the main content

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#8651]
## To reproduce

1. Set your theme to a dark style (ie TT3 with Pilgrimage styling).
2. Go to the Cart block page on mobile.
3. Notice the sticky footer has white background.

## Expected behavior

The sticky footer should honor the background of the main content.

For reference, the Mini Cart bock does something similar for the drawer background, see https://github.com/woocommerce/woocommerce-blocks/pull/7510. Ideally we should be able to reuse the same logic.

## Screenshots

<img src="https://user-images.githubusercontent.com/3616980/223365583-e184b386-5256-4e82-a2aa-c93cce953796.png" alt="" width="353" />

**Comment by iamdharmesh** [comment]
Hi there,

I would like to work on this issue as part of Contributor Day.

Thanks
