### ISSUE TITLE
Local Pickup: shipping method tab appears above shipping address after entering shipping address

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#8660]
In #7895, @senadir mentioned that when `Hide shipping costs until an address is entered` is enabled via `WP Admin » WooCommerce » Settings » Shipping » Shipping options`, the local pickup selector only appears when an address has been provided. 

In https://wordpress.slack.com, @masteradhoc just pinged me and informed me about the same issue. In comparison to @senadir, @masteradhoc did not highlight the fact that the shipping method section appears after providing an address, but the the fact that the shipping method section appears above the shipping address section. 

<table>
<tr>
<td valign="top">Checkout form before providing billing address:
<br><br>
<img width="1023" alt="Screenshot 2023-03-08 at 09 52 33" src="https://user-images.githubusercontent.com/3323310/223610718-c4fdb96d-1a67-464f-a7be-423fcfecaf6c.png">

</td>
<td valign="top">Checkout form after providing billing address:
<br><br>

<img width="1023" alt="Screenshot 2023-03-08 at 09 53 12" src="https://user-images.githubusercontent.com/3323310/223610712-9fb36cbc-324c-46fa-b4fe-59de6791cdf6.png">
</td>
</tr>
</table>

The following screenshot visualised this problem:

![geraete-schuppen li_kasse_](https://user-images.githubusercontent.com/3323310/223612145-03d2c1d6-561e-4c0b-9daf-d223e49bb79c.jpg)

- Seller provides email address.
- Seller **scrolls down** and provides shipping address. _(Shipping methods section appears above billing address section.)_
- Seller **scrolls up** and selects shipping method.
- Seller **scrolls down** and verifies shipping option.
- Seller **scrolls down** and selects payment method.
- Seller **scrolls down** and places the order.

cc: @elizaan36

**Comment by masteradhoc** [comment]
Thanks @nielslange !

**Comment by dennisjonda** [comment]
How can I activate this view? Somehow I only see "Versandoptionen". @nielslange

**Comment by nielslange** [comment]
> How can I activate this view? Somehow I only see "Versandoptionen". @nielslange

Thanks for asking, @dennisjonda! You can activate the local pickup using these steps:

1. Head over to `/wp-admin/admin.php?page=wc-settings&tab=shipping&section=pickup_location`.
2. On that page, enable local pickup.
3. On the same page, provide at least one pickup location.

This is how my test settings look like:

<img width="1434" alt="Screenshot 2023-03-08 at 20 45 18" src="https://user-images.githubusercontent.com/3323310/223728876-1b705aae-fb0f-4885-9150-0f07167bcfc8.png">

Worth mentioning that the classic WooCommerce pages contain the local pickup shipping method as well, which can be found within the shipping zones:

<img width="1434" alt="Screenshot 2023-03-08 at 20 48 09" src="https://user-images.githubusercontent.com/3323310/223729532-a20224b6-a047-4fad-a09d-f1c4b04c619b.png">

The local pickup option of WooCommerce Blocks is independent of that. Adjusting the local pickup settings within the shipping zones, will not affect the local pickup that is visible in the Checkout block of the WooCommerce Blocks.

I hope this helps to enable local pickups on your end. If you have any further questions, please reach out! 😀

**Comment by dennisjonda** [comment]
@nielslange, that's great! Thank you very much for your detailed answer. It helped me a lot and I'm currently putting it to use. :)

**Comment by nielslange** [comment]
I'm happy to hear that, @dennisjonda! 😀
