### ISSUE TITLE
Global Styles - Add to Cart Button - fix styles application

### ISSUE THREAD

**Issue by kmanijak** [woocommerce/woocommerce-gutenberg-products-block#8667]
## Steps to reproduce
1. Go to Editor
2. Add Products block
3. Add _Add to Cart Button_ block as an inner block if not already included
4. Open Global Styles and change following styles:

#### Typography - Text
**Expected:** This section should not influence the button, there's separate Typography - Button section
**Actual:** Font, Size (Frontend only), Line Height changes Button styles in Editor and Frontend

#### Typography - Button
**Expected:** Only this section _should_ influence the button
**Actual:** Only Line height does and appearance applies the italic, without font weight

#### Colors - Button
**Expected:** Text and Background colors apply in Editor and Frontend
**Actual:** Text and Background work in frontend, but not in Editor

⚠️ Remember
- **Check all of the above in Editor and Frontend!**
- **Styles composition may be fragile and the issue may evolve. Please check if block reacts to all the other Global Styles**
- **For items we are inheriting from Gutenberg that seem inconsistent and/or have room for improvement, we should raise an upstream Issue or PR and avoid making localized changes that bring inconsistency with Gutenberg.**
- Reflect the newest state of styles support in the [Spreadsheet](https://docs.google.com/spreadsheets/d/1KsKoq3J86s4PRZoHufj_qshGl_tTWjfolJXsrqE2AsU/edit#gid=1253950386) after finishing this task

**Comment by dinhtungdu** [comment]
The global style for Product Button isn't working. I tested with both Products and Product Collection blocks and got the same result.

<img width="2511" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/5423135/7d35f372-0448-47cc-bdbb-b319add5468f">

**Comment by Gustavo-Hilario** [comment]
- [ ] I could replicate this issue here: p9cu9o-3SB-p2. The user was using the _"Creation 2"_ theme and _"All Products"_ block. I tested it in one of my sites, and it also didn't work for the _"Products (beta)"_ block. The color changes in the _"Add to Cart"_ block settings and Global Styles aren't being applicable on the editor or published page.

**Comment by imanish003** [comment]
Hi @kmanijak,
I've attempted to replicate the issue on the latest version and it seems it's no longer occurring. Could you please recheck and confirm if you're still encountering it?

**Comment by kmanijak** [comment]
> I've attempted to replicate the issue on the latest version and it seems it's no longer occurring. Could you please recheck and confirm if you're still encountering it?

I confirm it's no longer reproducible. I think the whole issue can be closed as styles were improved overall and the issue no longer applies 👍 Hence I'm closing it. It can be reopened though if you think it's still valid.
