### ISSUE TITLE
Feedback on ./src/StoreApi/docs/cart-items.md

### ISSUE THREAD

**Issue by magrhy** [woocommerce/woocommerce-gutenberg-products-block#8670]
@ @

**Comment by kmanijak** [comment]
Hi, thanks for reaching out!

Seems there might've been some problem when submitting the feedback. For now I'm going to close this issue, as active issues are used for bugs or feature/enhancements.

But keep in mind that closed issues can also still be commented on. So feel free to drop your feedback about `./src/StoreApi/docs/cart-items.md` and it will be noted for sure!
