### ISSUE TITLE
Saved Payment Methods showing when canMakePayment is false

### ISSUE THREAD

**Issue by leonardola** [woocommerce/woocommerce-gutenberg-products-block#8678]
## Describe the bug

This is related to Saved Payment Methods in the Blocks Checkout.

When calling the method `registerPaymentMethod` we can pass a function to the `canMakePayment` attribute. That function is called every time there is a change in the address fields. But the `showSavedCards` attribute does not accept a function and it does not take into account if `canMakePayment` is true after changes in the address field.

## To reproduce

- The easiest way is to install Gocardless payment method. You'll need to checkout to this branch if the support is not released yet [here](https://github.com/woocommerce/woocommerce-gateway-gocardless/pull/202)
- Buy a product and opt to save the payment method
- Later add another product to the cart and go to the checkout blocks
- When using a valid address (UK address for example) the saved card will show up as expected
- When you change to an invalid address the saved card will still show up even though the payment method itself is hidden now

## Expected behavior
What we need is that either the saved methods are hidden when `canMakePayment` returns false or that the `showSavedCards` also accepts a function that will be called when there is an address change so we can return false to hide the saved methods when necessary.

**Comment by mikejolley** [comment]
Related to https://github.com/woocommerce/woocommerce-blocks/pull/8461/files but an issue in the client rather than on the server side. This will need working on, so I've added it to our issue backlog. Thanks for the report.

**Comment by ralucaStan** [comment]
@opr I remember you had a WIP PR for this? Was there any good progress on that one?

**Comment by opr** [comment]
> @opr I remember you had a WIP PR for this? Was there any good progress on that one?

Yes, functionality-wise my solution works, I did not get chance to publish a PR for this yet. The work is available on `fix/saved-payment-methods` branch ([diff here](https://github.com/woocommerce/woocommerce-blocks/compare/fix/saved-payment-methods?expand=1)) and needs tests adding.

I will work on this.
