### ISSUE TITLE
Unable to access user nonce through remote client app using WooCommerce store/admin API

### ISSUE THREAD

**Issue by dshubham08** [woocommerce/woocommerce-gutenberg-products-block#8683]
I am developing a remote app to access the WooCommerce API, and I need to access the user nonce to perform certain actions like adding products to the cart or processing orders. However, I am unable to access the user nonce using the WooCommerce APIs

I understand that accessing the user nonce through the WooCommerce API is not the intended way, but it is necessary for my use case. I have reviewed the WooCommerce API documentation, searched online for resources, and tried various methods to access the user nonce, but have been unsuccessful.

Additional information:
I am using the latest version of WooCommerce.
I have confirmed that I am unable to access the user nonce through the WooCommerce API d
Any assistance or guidance on how to access the user nonce using the WooCommerce API through my remote app would be greatly appreciated.

**Comment by senadir** [comment]
The nonce exists on all store/cart or store/checkout responses header, you can perfom a GET on /cart to have it.

Alternatively, you can initiate it yourself on the server using `wp_create_nonce('wc_store_api')`

**Comment by mikejolley** [comment]
Closing this as it has been answered. Thanks.
