### ISSUE TITLE
Ensure Cart block supports the theme-level global styles for `Typography » Buttons`

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#8712]
Currently, the Cart block partially supports the default theme-level global styles for `Typography » Buttons`. This issue aims to ensure that the Cart block fully supports the default theme-level global styles.

## Steps to reproduce

1. Go to `WP Admin » Apperance » Editor`.
2. Open the `Styles` sidebar.
3. Open the `Typography » Buttons` settings.
4. Adjust the settings `FONT`, `SIZE CUSTOM`, `APPERANCE` and `LINE HEIGHT`.
5. See that some settings are not supported.

## Screenshots

<table>
<tr>
<td>Cart:
<br><br>

<img width="2877" alt="Typography-Buttons-Cart" src="https://user-images.githubusercontent.com/3323310/224690364-fac657a0-b6d7-4090-b73c-d0e4bcbd55be.png">
</td>
</tr>
</table>

**Comment by tarunvijwani** [comment]
We'll also need to ensure that https://github.com/woocommerce/woocommerce-blocks/issues/8587 is handled along with this issue.

**Comment by mikejolley** [comment]
Noting that button styles work (as does checkout) with the exception of line height which is not consistent between cart and checkout.

**Comment by tarunvijwani** [comment]
The typography of the buttons present on Cart block will be fixed with the changes in  https://github.com/woocommerce/woocommerce-blocks/pull/8892

**Comment by nielslange** [comment]
Closing this issue due to #8892.
