### ISSUE TITLE
Ensure Cart block supports the theme-level global styles for `Colors » Buttons`

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#8713]
Currently, the Cart block partially supports the default theme-level global styles for `Colors » Buttons`. This issue aims to ensure that the Cart blocks fully support the default theme-level global styles.

## Steps to reproduce

1. Go to `WP Admin » Apperance » Editor`.
2. Open the `Styles` sidebar.
3. Open the `Colors » Buttons` settings.
4. Adjust the settings `TEXT COLOR` and `BACKGROUND COLOR`.
5. See that some settings are not supported.

## Screenshots

<table>
<tr>
<td>Cart:
<br><br>

<img width="2877" alt="Colors-Buttons-Cart" src="https://user-images.githubusercontent.com/3323310/224696850-4f103fed-0890-4e26-9179-41d986b1535f.png">
</td>
</tr>
</table>

**Comment by tarunvijwani** [comment]
We'll also need to ensure that https://github.com/woocommerce/woocommerce-blocks/issues/8587 is handled along with this issue.

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/woocommerce-blocks/pull/8844
