### ISSUE TITLE
When the `Mini cart` modal has a border, the close button should not be on top of it

### ISSUE THREAD

**Issue by albarin** [woocommerce/woocommerce-gutenberg-products-block#8716]
## Describe the bug

When the `Mini cart` sidebar has a border, the close "x" button is on top of it and it does not look good, especially on dark themes.

## To reproduce

1. Enable TT2 theme with Swiss style.
2. Create a page with the `Mini cart` block and save it.
3. Go to the frontend, and click on the `Mini cart` button to open the sidebar.
4. See that the "x" button is on top of the border.

## Expected behavior

The "x" button should be inside the sidebar content, not on the border.

## Screenshots

![image](https://user-images.githubusercontent.com/186112/224728994-1e8a3502-52fb-4703-b829-c7a981d3962f.png)

**Comment by kmanijak** [comment]
May be addressed in scope of https://github.com/woocommerce/woocommerce-blocks/issues/8606
