### ISSUE TITLE
Can't add spaces to Cart and Mini Cart buttons

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#8734]
## To reproduce

1. Add the Cart block to a post or page.
2. In the editor, press the _Proceed to Checkout_ button to edit the text.

![imatge](https://user-images.githubusercontent.com/3616980/225037160-8c8f2226-3074-44af-b993-2e11200b9f83.png)

3. Notice you can successfully type characters.
4. Now, try adding a <kbd>Space</kbd>.
5. Notice spaces aren't added.

## Expected behavior

It should be possible to add spaces to the button.

**Comment by albarin** [comment]
I've been checking this and I can only reproduce it in Firefox.

**Comment by Aljullu** [comment]
I opened a PR with a work-around: https://github.com/woocommerce/woocommerce-blocks/pull/8777. However, this seems to be a Firefox bug, so [I reported it directly to them](https://bugzilla.mozilla.org/show_bug.cgi?id=1822860). If it gets fixed upstream, we would hopefully be able to remove the work-around. :crossed_fingers:
