### ISSUE TITLE
Mini Cart: Close button is not being displayed

### ISSUE THREAD

**Issue by thealexandrelara** [woocommerce/woocommerce-gutenberg-products-block#8735]
## Describe the bug

When the Mini Cart drawer is open, the close button that used to display on the top right, is not being displayed. I know that we can click outside the drawer to close it, but this behavior is happening even in the mobile view, which would block the user from closing the Mini Cart content.

## To reproduce

1. Log in to your WordPress dashboard;
2. Go to Appearance > Themes, and select a block theme (for example: Twenty-twenty three);
3. Go to Appearance < Site Editor (Beta);
4. Click on Template Parts > Header;
5. Click the Edit button;
6. Click on the "+" icon to add a new block and search for "Mini Cart" block in the search bar.
7. Click on the "Mini Cart" block to add it to your page or post.
8. Go to your website and add some products to the cart;
9. Click on the Mini Cart icon and check that the close button is not appearing;

## Expected behavior

The close button should appear when the drawer is open
<img width="770" alt="image" src="https://user-images.githubusercontent.com/20469356/225030777-9e55d5f1-7afc-41f1-af97-ab8b5b8134ca.png">

## Screenshots

As you can see in the below image, the close button is not being displayed:
<img width="768" alt="image" src="https://user-images.githubusercontent.com/20469356/225030965-a8413574-6301-44cc-b01b-78d2a3457446.png">

### WordPress (please complete the following information):

-   WordPress version: 6.1.1
-   Gutenberg version (if installed): 15.0.1
-   WooCommerce version: 7.6.0-dev
-   WooCommerce Blocks version: 9.9.0-dev
-   Site language:
-   Any other plugins installed:

### Desktop (please complete the following information):

-   OS: MacOS Ventura
-   Browser Chrome
-   Version 111.0.5563.64

## Additional context

It looks like that when I disable the background property in the `h2.wc-block-mini-cart__title` css rule, the issue is gone (I think it's being caused because the close button is behind the Mini Cart title.
<img width="584" alt="image" src="https://user-images.githubusercontent.com/20469356/225036468-86d71c8d-7be5-4a10-b9d7-94a3628e9762.png">

**Comment by Aljullu** [comment]
Good catch, @thealexandrelara! For context, that's a regression introduced in #8676 and WC Blocks 9.8.0 is not affected.
