### ISSUE TITLE
[PHP 8.2 Compatibility] Deprecation warnings

### ISSUE THREAD

**Issue by ralucaStan** [woocommerce/woocommerce-gutenberg-products-block#8739]
## Describe the bug

Deprecation warnings have been reported for StoreApi in https://github.com/woocommerce/woocommerce/issues/35763 with 
PHP 8.2.0 RC6.

```
Deprecated: Creation of dynamic property Automattic\WooCommerce\StoreApi\Schemas\V1\CheckoutSchema::$image_attachment_schema is deprecated in \wp-content\plugins\woocommerce\packages\woocommerce-blocks\src\StoreApi\Schemas\V1\CheckoutSchema.php on line 51
```

### Steps to reproduce

Setup a WordPress with WooCommerce extension, powered by PHP 8.1 on the server.
Install Query Monitor extension.
Check PHP errors and warnings, to see them.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce-blocks/pull/8802
