### ISSUE TITLE
Product Image Gallery: placeholder goes outside the block selection

### ISSUE THREAD

**Issue by gigitux** [woocommerce/woocommerce-gutenberg-products-block#8742]
## Describe the bug

On WP 6.2 with the Tsubaki theme enabled, the placeholder of the Product Image Gallery goes outside the block selection:

## To reproduce

1. Enable the Tsubaki theme
2. Edit the Single Product Template
3. Via code editor, replace the template with [this](https://gist.github.com/gigitux/e9323d6d280313f528996e34d62ae626)
4. Focus on the Product Image Gallery Block.
5. See that the placeholder goes outside the block selection (as in the image below).

## Expected behavior

The placeholder should not go outside the block selection.

## Screenshots

![image](https://user-images.githubusercontent.com/4463174/225101004-a7b72da5-14aa-4721-90bc-534c2dc8645a.png)

**Comment by kmanijak** [comment]
When editing the page via code editor, there's a glitch: on the narrow screen, the Product Gallery overlaps with the content on the right:

https://user-images.githubusercontent.com/20098064/225862631-b581a8a4-a0a6-43d4-91f5-6d002845ba74.png

It seems Product Gallery doesn't downscale when squeezed by the Column

https://user-images.githubusercontent.com/20098064/225862945-08b5340a-d07f-4506-9eb2-6e048d636d71.png

Found in the scope of https://github.com/woocommerce/woocommerce-blocks/pull/8767
