### ISSUE TITLE
Ensure Cart and Checkout blocks support the default theme-level global styles for `Layout`

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#8752]
In pdFofs-Ns-p2, I found out that the Cart and Checkout blocks only partially support the default theme-level global styles for `Typography » Headings`. This issue aims to ensure that both blocks fully support the default theme-level global styles.

## Steps to reproduce

1. Go to `WP Admin » Apperance » Editor`.
2. Open the `Styles` sidebar.
3. Open the `Layout` settings.
4. Adjust the settings `CONTENT`, `WIDE`, `PADDING TOP`, `PADDING RIGHT`, `PADDING LEFT`, `PADDING BOTTOM` and `BLOCK SPACE`.
5. See that the `PADDING TOP` setting is not reflected in the editor. (This might have to be clarified with the GB team.)

## Screenshots

<table>
<tr>
<td>Cart:
<br><br>

<img width="2869" alt="Layout-Cart" src="https://user-images.githubusercontent.com/3323310/225237683-1319e86b-0320-415b-aa0e-fa33f1e58d68.png">
</td>
<td>Checkout:
<br><br>

<img width="2879" alt="Layout-Checkout" src="https://user-images.githubusercontent.com/3323310/225237676-49018c3e-d7eb-4e57-a494-8bd32c251096.png">
</td>
</tr>
</table>

**Comment by tarunvijwani** [comment]
Closing the issue as it is related to Gutenberg. The layout style controls the entire page padding, margins, and width that Gutenberg handles. There are no block-specific layout settings.
