### ISSUE TITLE
Single product page breaks with blocks 9.8.0

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce-gutenberg-products-block#8753]
## Describe the bug

We're seeing reports of single product pages not loading properly when WooCommerce Blocks version 9.8.0 is active.

## To reproduce

1. Blocks 9.8.0 is active
2. block enabled theme is active
3. Single product page doesn't load. No obvious console or PHP errors. 

## Expected behavior

To be able to activate WooCommerce Blocks without impacting single product pages

## Screenshots

blocks plugin active:
![Z9Hfh4.png](https://user-images.githubusercontent.com/2127470/225238290-6936f78e-a5ef-4235-ba7b-ac03170376b7.png)

blocks plugin inactive:
![nY07Ts.png](https://user-images.githubusercontent.com/2127470/225238534-3c9f1bc1-28eb-4237-9e4c-a1b830f2fa8f.png)

### WordPress (please complete the following information):

-   WordPress version: 6.1.1
-   WooCommerce version: 7.5.0
-   WooCommerce Blocks version: 9.8.0
-   Site language: EN
-   Any other plugins installed:

**Comment by sverleis** [comment]
Also able to replicate when using the WordPress.com based theme, **Tsubaki**

**Works as expected on [Version 9.7.2](https://downloads.wordpress.org/plugin/woo-gutenberg-products-block.9.7.2.zip)**, but broken on both 9.7.1 and 9.8.0.

`Internal ref: 6042774`

**Comment by Aljullu** [comment]
@WillBrubaker and @sverleis thanks for your reports! Heads-up that this has been fixed in WC Blocks 9.8.1.
