### ISSUE TITLE
ProductQuery->update_rest_query() overwrite tax_query of wp rest request

### ISSUE THREAD

**Issue by Bernier154** [woocommerce/woocommerce-gutenberg-products-block#8765]
## Describe the bug

I've been having problems with the rest api of a website using woocommerce. In this website i've made a custom infinite scroll of the product, by category to easily navigate it. 

Problem is, now, Wordpress return over 600 products per categories (categories where there are 20 products max)

I've been digging and found that Automattic\WooCommerce\Blocks\BlockTypes\ProductQuery->update_rest_query() was the culprit. 

this is hooked on rest_product_query, and modify the query, but overrides the "tax_query" parameters. So all my categories fetch return all the products, 

## To reproduce

1. On the front end do a js fetch with the product_cat= parameters
2. receive the result of the query with product not even in this category.

## Expected behavior

The function should not overwrite the tax query, or the hook should only be added for your blocks and not the general rest api.

### WordPress (please complete the following information):

-   WordPress version: 6.1.1
-   Gutenberg version (if installed):
-   WooCommerce version: 7.5.0
-   WooCommerce Blocks version: 9.6.5
-   Site language: fr_CA

### Desktop (please complete the following information):

-   OS:  Windows
-   Browser   firefox
-   Version 111

**Comment by kmanijak** [comment]
Hi @Bernier154, thank you for raising this issue!

> Steps to reproduce the behavior:
>
> 1. On the front end do a js fetch with the product_cat= parameters
> 2. receive the result of the query with product not even in this category.

Could you explain in more detail the steps to reproduce the issue?

I tried to reproduce it using Store API to get products by category and I couldn't spot the problem.

Here's the [docs ](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/StoreApi/docs/products.md)of the method I used and a query:

`<<STORE DOMAIN>>/wp-json/wc/store/v1/products?category=<<CATEGORY ID>>`

**Comment by Bernier154** [comment]
Hi @kmanijak, 

I have reproduced the steps on a fresh wordpress: 
Wordpress 6.1.1
Twenty Twenty-Three  1.0
WooCommerce 7.5.0

My bug was not with the storeApi, but the WP_REST Api

I created six products, 1 product category, and 1 product added to the test category. 


in the functions.php I enqueued my test script for the front-end: 
```js
add_action('wp_enqueue_scripts',function(){
    wp_enqueue_script('test',get_template_directory_uri().'/test.js',['wp-api-fetch']);
});
```
The script is a bunch of test queries to the WP_REST api: (I added dome for the category praram, but i'm pretty sure it is not supported by the endpoint)
```js
const fetchProducts = () => {
    const paths = [
        "/wp/v2/product?per_page=100",
        "/wp/v2/product?per_page=100&product_cat=15",
        "/wp/v2/product?per_page=100&product_cat=16",
        "/wp/v2/product?per_page=100&category=15",
        "/wp/v2/product?per_page=100&category=16"
    ];

    Promise.all(paths.map(async path=>{ 
        return new Promise((resolve,reject)=>{
            wp.apiFetch({path:path})
            .then(products=>{
                resolve({
                    query:path,
                    products:products.map(product=>{
                        return {name:product.title.rendered,category:product.product_cat.join(',')};
                    })
                });
            });
        });
    })).then(output=>{
        console.log(output);
    });
}
fetchProducts();
```
The output is 
```JSON
[
  {
    "query": "/wp/v2/product?per_page=100",
    "products": [
      {
        "name": "Product 6",
        "category": "15"
      },
      {
        "name": "Product 5",
        "category": "15"
      },
      {
        "name": "Product 4",
        "category": "15"
      },
      {
        "name": "Product 3",
        "category": "15"
      },
      {
        "name": "Product 2",
        "category": "15"
      },
      {
        "name": "Product 1",
        "category": "16"
      }
    ]
  },
  {
    "query": "/wp/v2/product?per_page=100&product_cat=15",
    "products": [
      {
        "name": "Product 6",
        "category": "15"
      },
      {
        "name": "Product 5",
        "category": "15"
      },
      {
        "name": "Product 4",
        "category": "15"
      },
      {
        "name": "Product 3",
        "category": "15"
      },
      {
        "name": "Product 2",
        "category": "15"
      },
      {
        "name": "Product 1",
        "category": "16"
      }
    ]
  },
  {
    "query": "/wp/v2/product?per_page=100&product_cat=16",
    "products": [
      {
        "name": "Product 6",
        "category": "15"
      },
      {
        "name": "Product 5",
        "category": "15"
      },
      {
        "name": "Product 4",
        "category": "15"
      },
      {
        "name": "Product 3",
        "category": "15"
      },
      {
        "name": "Product 2",
        "category": "15"
      },
      {
        "name": "Product 1",
        "category": "16"
      }
    ]
  },
  {
    "query": "/wp/v2/product?per_page=100&category=15",
    "products": [
      {
        "name": "Product 6",
        "category": "15"
      },
      {
        "name": "Product 5",
        "category": "15"
      },
      {
        "name": "Product 4",
        "category": "15"
      },
      {
        "name": "Product 3",
        "category": "15"
      },
      {
        "name": "Product 2",
        "category": "15"
      },
      {
        "name": "Product 1",
        "category": "16"
      }
    ]
  },
  {
    "query": "/wp/v2/product?per_page=100&category=16",
    "products": [
      {
        "name": "Product 6",
        "category": "15"
      },
      {
        "name": "Product 5",
        "category": "15"
      },
      {
        "name": "Product 4",
        "category": "15"
      },
      {
        "name": "Product 3",
        "category": "15"
      },
      {
        "name": "Product 2",
        "category": "15"
      },
      {
        "name": "Product 1",
        "category": "16"
      }
    ]
  }
]
```

But if i add this super ugly fix to the PHP, sitll in functions.php of the theme, (It search for the cluprit hooked method and unhook it)
```php
add_filter( "rest_product_query",function($query,$request){
    global $wp_filter;
    foreach($wp_filter['rest_product_query'] as $depth=>$hooks){
        foreach($hooks as $signature=>$data){
            if(is_array($data['function'])){
                if(get_class($data['function'][0]) == 'Automattic\WooCommerce\Blocks\BlockTypes\ProductQuery'){
                    remove_filter('rest_product_query',$signature);
                }
            }
        }
    }
    return $query;
},1,2);
```
I rerun the aforementioned script and i get the data that i predicted
```json
[
  {
    "query": "/wp/v2/product?per_page=100",
    "products": [
      {
        "name": "Product 6",
        "category": "15"
      },
      {
        "name": "Product 5",
        "category": "15"
      },
      {
        "name": "Product 4",
        "category": "15"
      },
      {
        "name": "Product 3",
        "category": "15"
      },
      {
        "name": "Product 2",
        "category": "15"
      },
      {
        "name": "Product 1",
        "category": "16"
      }
    ]
  },
  {
    "query": "/wp/v2/product?per_page=100&product_cat=15",
    "products": [
      {
        "name": "Product 6",
        "category": "15"
      },
      {
        "name": "Product 5",
        "category": "15"
      },
      {
        "name": "Product 4",
        "category": "15"
      },
      {
        "name": "Product 3",
        "category": "15"
      },
      {
        "name": "Product 2",
        "category": "15"
      }
    ]
  },
  {
    "query": "/wp/v2/product?per_page=100&product_cat=16",
    "products": [
      {
        "name": "Product 1",
        "category": "16"
      }
    ]
  },
  {
    "query": "/wp/v2/product?per_page=100&category=15",
    "products": [
      {
        "name": "Product 6",
        "category": "15"
      },
      {
        "name": "Product 5",
        "category": "15"
      },
      {
        "name": "Product 4",
        "category": "15"
      },
      {
        "name": "Product 3",
        "category": "15"
      },
      {
        "name": "Product 2",
        "category": "15"
      },
      {
        "name": "Product 1",
        "category": "16"
      }
    ]
  },
  {
    "query": "/wp/v2/product?per_page=100&category=16",
    "products": [
      {
        "name": "Product 6",
        "category": "15"
      },
      {
        "name": "Product 5",
        "category": "15"
      },
      {
        "name": "Product 4",
        "category": "15"
      },
      {
        "name": "Product 3",
        "category": "15"
      },
      {
        "name": "Product 2",
        "category": "15"
      },
      {
        "name": "Product 1",
        "category": "16"
      }
    ]
  }
]
```

## Where I think the problem lies

At `Automattic\WooCommerce\Blocks\BlockTypes\ProductQuery line 74` the method `ProductQuery ->update_rest_query()` is hooked the the `rest_product_query` filter.

This filter modifies the query at all time, even if the comment say `Update the query for the product query block in Editor.`.

If we dig deeper we see that this method returns a array merge of the args, and the modified args. In my example, the  `product_cat` param adds a tax_query to the query but the tax query is overwritten by the `$visibility_query` array.

The `$visibility_query` array is built by `ProductQuery->get_product_visibility_query($stock_query)`. 
this method return a tax query without taking the previous tax query into account. (and php `array_merge` will overwrite the previous occurence of a key if it is repeated)
```php
[...]
return array(
			'tax_query' => array(
				array(
					'taxonomy' => 'product_visibility',
					'field'    => 'term_taxonomy_id',
					'terms'    => $product_visibility_not_in,
					'operator' => 'NOT IN',
				),
			),
		);
[...]
```


I hope this can help, sorry it is so long. at the moment, I had to integrate the "ugly" fix on a client website because the update broke a front end module.

The solution would be either only apply the hook if it is for the rendering of the woocommerce block, or just a better solution than the array merge like the `wp_parse_arges()` function.

**Comment by Aljullu** [comment]
@Bernier154, just FYI, @imanish003 is working on a fix for this issue. In case you want to take a look at the PR or test the fix. You can find it in https://github.com/woocommerce/woocommerce-blocks/pull/9049. :slightly_smiling_face:
