### ISSUE TITLE
Fatal error with filter_shipping_packages() in some cases

### ISSUE THREAD

**Issue by kaushikasomaiya** [woocommerce/woocommerce-gutenberg-products-block#8772]
We do not have steps to replicate this issue but the error was reported in a couple of interactions:

- 5990743-zen
- https://wordpress.org/support/topic/fatal-error-on-editing-a-post-uncaught-typeerror-with-php-8-0-24/
- 5979786-zen
- https://wordpress.org/support/topic/fatal-error-when-adding-or-editing-post-cpt-custom-blocks/page/2/

> 2023-02-25T14:35:00+00:00 CRITICAL Uncaught TypeError: array_filter(): Argument [#1](https://woothemes.zendesk.com/agent/tickets/1) ($array) must be of type array, null given in  public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Shipping/ShippingController.php:310

> Fatal error: Uncaught Error: array_filter(): Argument woocommerce/woocommerce-blocks#12058 ($array) must be of type array, null given
in /wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Shipping/ShippingController.php on line 310

This occurs when trying to edit a page/post or CPT.

I suspect it might have something to do with plugins that use Local Pick up instance. 

I am reporting it here so that developers can investigate it further.

**Comment by kmanijak** [comment]
We assume the issue should be fixed in WooCommerce Blocks 9.7.0 (with https://github.com/woocommerce/woocommerce-blocks/pull/8413).

Users were asked to try to reproduce with WooCommerce Blocks 9.7.0 in [this thread](https://wordpress.org/support/topic/fatal-error-when-adding-or-editing-post-cpt-custom-blocks/page/2/) for confirmation.

cc: @tarunvijwani - please take over the further conversation if needed 🙏

**Comment by kaushikasomaiya** [comment]
Since there are no known steps to replicate this issue - I went ahead and supplied a null value to array_filter() in filter_shipping_packages(), applied the fix woocommerce/woocommerce-blocks#8413 to my local site, tried adding a new page and the error no longer appeared.

@kmanijak @tarunvijwani  Any ideas when Blocks 9.7.0 would be shipped into WooCommerce core?

**Comment by nielslange** [comment]
> Any ideas when Blocks 9.7.0 would be shipped into WooCommerce core?

@kaushikasomaiya WooCommerce Blocks 9.7.0 should be shipped with WooCommerce 7.6 which is scheduled for April 11, 2023.
