### ISSUE TITLE
Empty Product Block Div on Frontend

### ISSUE THREAD

**Issue by BFTrick** [woocommerce/woocommerce-gutenberg-products-block#88]
Hey Woo team,

Thought I'd give this feature a run through. Everything on the edit product page was great! Seriously. It's an awesome experience that I can't wait to show off to users. 👍 

Unfortunately I couldn't get the products block to render on the front end. It's just an empty div.

Screencast: https://d.pr/i/bxetqv

## Plugins & Themes

* WooCommerce 3.3.4
* WooCommerce Gutenberg Products Block 1.0.0
* Gutenberg 2.5.0
* Storefront 2.2.8

**Comment by robin-scott** [comment]
Getting same here testing with Gutenberg in Storefront when adding category. Shortcode looks good. Front-end - an empty div:

![image](https://user-images.githubusercontent.com/17259256/38387990-c1f49d22-3911-11e8-8e8c-2b46b5432f3f.png)

Note when adding individual products - this is working.

Its just categories (so far) I think @BFTrick

**Comment by robin-scott** [comment]
So if you "manually" select your products - not selecting the product cat - this renders (for me) on front end just fine.

In HTML view:

![image](https://user-images.githubusercontent.com/17259256/38388127-30f74f6c-3912-11e8-8474-7f1a8d2411d0.png)

The above works just fine.

![image](https://user-images.githubusercontent.com/17259256/38388152-42de2b6a-3912-11e8-97a4-acffda319e6f.png)

The above (display a product category) - this doesn't work... get same result as @BFTrick

**Comment by robin-scott** [comment]
Fiddling around the shortcode doesn't work in a "normal" block, so its outside of this plugin's control - I think?!

**Comment by robin-scott** [comment]
doh I found it... the category shortcode doesn't take ID - it takes the slug...

`[products limit="4" columns="4" category="slug-name" orderby="date"]` - works :)

**Comment by robin-scott** [comment]
ah yeah I haven't used these shortcodes for a long old time @claudiulodro so wouldn't have ever noticed it... if it hadn't been for the fact I had Gutenberg on a 3.3.4 install when @BFTrick mentioned this!

**Comment by claudiulodro** [comment]
See #92.
