### ISSUE TITLE
Ensure Checkout block supports the theme-level global styles for `Colors » Headings`

### ISSUE THREAD

**Issue by tarunvijwani** [woocommerce/woocommerce-gutenberg-products-block#8806]
Currently, the Checkout blocks partially support the theme-level global styles for `Typography » Headings`. This issue aims to ensure that the Checkout block fully supports the theme-level global styles.

## Steps to reproduce

1. Go to `WP Admin » Apperance » Editor`.
2. Open the `Styles` sidebar.
3. Open the `Colors » Headings` settings.
4. Adjust the color settings.
5. See that some headlines do not reflect the color.

## Screenshots

<table>
<tr>
<td>Checkout:
<br><br>

<img width="2879" alt="Colors-Headings-Checkout" src="https://user-images.githubusercontent.com/3323310/225236595-eb2b8656-3069-4886-8eb1-a57e75fea4a9.png">
</td>
</tr>
</table>

**Comment by nielslange** [comment]
Closing this issue as the the theme-level global styles for `Colors » Headings` are fully supported already:

<img width="2877" alt="Screenshot 2023-03-24 at 14 47 11" src="https://user-images.githubusercontent.com/3323310/227457204-09f84188-c672-4d8e-8f50-9b68caa7a22d.png">
