### ISSUE TITLE
Ensure Checkout block supports the theme-level global styles for `Colors » Buttons`

### ISSUE THREAD

**Issue by tarunvijwani** [woocommerce/woocommerce-gutenberg-products-block#8808]
Currently, the Checkout block partially supports the default theme-level global styles for `Colors » Buttons`. This issue aims to ensure that the Checkout blocks fully support the default theme-level global styles.

## Steps to reproduce

1. Go to `WP Admin » Apperance » Editor`.
2. Open the `Styles` sidebar.
3. Open the `Colors » Buttons` settings.
4. Adjust the settings `TEXT COLOR` and `BACKGROUND COLOR`.
5. See that some settings are not supported.

## Screenshots

<table>
<tr>
<td>Checkout:
<br><br>
<img width="2871" alt="Colors-Buttons-Checkout" src="https://user-images.githubusercontent.com/3323310/224696889-e2615ade-7c5f-48a2-a89b-85aa9fc1ec6e.png">
</td>
</tr>
</table>

**Comment by ralucaStan** [comment]
@tarunvijwani please keep this ticket in mind as well https://github.com/woocommerce/woocommerce-blocks/issues/8571

**Comment by tarunvijwani** [comment]
We'll also need to ensure that https://github.com/woocommerce/woocommerce-blocks/issues/8587 is handled along with this issue.

**Comment by nielslange** [comment]
Fixed by #8844
