### ISSUE TITLE
Ensure Checkout block supports the theme-level global styles for `Typography » Buttons`

### ISSUE THREAD

**Issue by tarunvijwani** [woocommerce/woocommerce-gutenberg-products-block#8810]
Currently, the Checkout block partially supports the default theme-level global styles for `Typography » Buttons`. This issue aims to ensure that the Checkout block fully supports the default theme-level global styles.

## Steps to reproduce

1. Go to `WP Admin » Apperance » Editor`.
2. Open the `Styles` sidebar.
3. Open the `Typography » Buttons` settings.
4. Adjust the settings `FONT`, `SIZE CUSTOM`, `APPERANCE` and `LINE HEIGHT`.
5. See that some settings are not supported.

## Screenshots

<table>
<tr>

<td>Checkout:
<br><br>

<img width="2878" alt="Typography-Buttons-Checkout" src="https://user-images.githubusercontent.com/3323310/224690373-bdcb58d5-80f3-4b26-bc26-116b22c9a10e.png">
</td>
</tr>
</table>

**Comment by tarunvijwani** [comment]
We'll also need to ensure that https://github.com/woocommerce/woocommerce-blocks/issues/8587 is handled along with this issue.

**Comment by nielslange** [comment]
Closing this issue due to #8892.
