### ISSUE TITLE
Ensure Checkout block supports the theme-level global styles for `Typography » Headings`

### ISSUE THREAD

**Issue by tarunvijwani** [woocommerce/woocommerce-gutenberg-products-block#8811]
Currently, the Checkout block partially supports the default theme-level global styles for `Typography » Headings`. This issue aims to ensure that the Checkout block fully supports the default theme-level global styles.

## Steps to reproduce

1. Go to `WP Admin » Apperance » Editor`.
2. Open the `Styles` sidebar.
3. Open the `Typography » Headings` settings.
4. Adjust the settings `FONT`, `APPERANCE`, `LINE HEIGHT`, `LETTER SPACING` and `LETTER CASE`.
5. See that some settings are not supported.

## Screenshots

<table>
<tr>
<td>Cart:
<br><br>
<img width="2879" alt="Typography-Headings-Cart" src="https://user-images.githubusercontent.com/3323310/224685498-a1422560-9cc4-4e75-9c82-b4e41b318fe4.png">

</td>
</tr>
</table>

**Comment by nielslange** [comment]
Closing this issue as it had been fixed with #8918.
