### ISSUE TITLE
Products list items uses "custom" markup instead of wc_get_template_part()

### ISSUE THREAD

**Issue by jespervnielsen** [woocommerce/woocommerce-gutenberg-products-block#882]
**Describe the bug**
When using the products lists blocks, the markup of the items is "hardcoded".
https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/src/BlockTypes/AbstractProductGrid.php#L339-L350

It made sense, before the blocks was converted to dynamic blocks. But afterwards, the blocks is dynamic, and should be build on same princibles like the rest of woocommerce template system.

Some big issues, is that the hooks to add (multiple) data and elements on the items is complicated now.
Each plugin/theme must override the filter of the markup, witch makes its hard to have different plugins add each own data to the list items, since it require som stupid reggex, or total override of the markup.

The global products isn't setup, so using functions like get_the_ID() and stuff like that wont work. 
(i know the id, is avaible on the $product in the filter),

inspiration could be found in WooCommerce Shorcodes https://github.com/woocommerce/woocommerce/blob/master/includes/shortcodes/class-wc-shortcode-products.php#L633-L660

**To Reproduce**

Create product blocks list.
Compare with shortcodes.

**Expected behavior**
Using wc_get_template_part, and run all hooks.

**Comment by mikejolley** [comment]
I've consolodated all related issues to extending blocks into https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/891 until a decision is made. Please see that issue and add feedback there if relevant. 

Thanks
