### ISSUE TITLE
[GlobalStep] Mini Cart block fails to translate "Tabla de productos del mini carrito" inner block on "Appearance > Editor" page.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-gutenberg-products-block#8823]
### Bug Description:
Mini Cart block fails to translate "Tabla de productos del mini carrito" inner block on "Appearance > Editor" page.

### Environment:
Woocommerce Version:  WooCommerce 7.6.0-beta.1 
WordPress version:  WordPress 6.2-RC3

PC:
Windows 10, 
Chrome(Version 111.0.5563.111)
Firefox(Version 110.0.1)

### Steps To Reproduce:
1. Create any test site using Jurassic Ninja.
2. Install and activate all the required plugins.
3. Install and activate Woocommerce.
4. Set your store language to a language with WC Blocks translations, ie: Spanish (Español).
5. With a block theme (ie: TT3), go to Appearance > Editor > Template Parts and edit the Mini Cart block template part.
6. Open the sidebar list view and check the inner blocks.
7. Observe that, Mini Cart block fails to translate "Tabla de productos del mini carrito" inner block

### Instruction Link:
https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/testing/releases/980.md#fix-mini-cart-missing-translations-8591

### Actual Result:
Mini Cart block fails to translate "Tabla de productos del mini carrito" inner block on "Appearance > Editor" page.

### Expected Result:
Mini Cart block should be translated to "Tabla de productos del mini carrito" inner block on "Appearance > Editor" page.

### Screenshot:

![#8823](https://user-images.githubusercontent.com/41110392/226969235-ed596e4b-76fd-4ac9-bf45-389bb42e6605.png)

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>

`
### WordPress Environment ###

WC Version: 7.6.0
REST API Version: ✔ 7.6.0
WC Blocks Version: ✔ 9.8.1
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2-RC3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.0.28
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.86.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.6.12-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.6.0
WC Database Prefix: wp_
Tamaño total de la base de datos: 10.36MB
Tamaño de los datos de la base de datos: 5.57MB
Tamaño del índice de la base de datos: 4.79MB
wp_woocommerce_sessions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_woocommerce_order_items: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_order_itemmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_actionscheduler_actions: Datos: 2.52MB + Índice: 2.55MB + Motor InnoDB
wp_actionscheduler_claims: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_actionscheduler_groups: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_actionscheduler_logs: Datos: 1.52MB + Índice: 0.73MB + Motor InnoDB
wp_commentmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_comments: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
wp_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_options: Datos: 0.11MB + Índice: 0.03MB + Motor InnoDB
wp_postmeta: Datos: 0.13MB + Índice: 0.09MB + Motor InnoDB
wp_posts: Datos: 0.38MB + Índice: 0.06MB + Motor InnoDB
wp_termmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_terms: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_term_relationships: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_term_taxonomy: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_usermeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_users: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_wc_admin_notes: Datos: 0.05MB + Índice: 0.00MB + Motor InnoDB
wp_wc_admin_note_actions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_category_lookup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wc_customer_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_download_log: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_order_bundle_lookup: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
wp_wc_order_coupon_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_order_product_lookup: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_wc_order_stats: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_wc_order_tax_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_product_attributes_lookup: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_product_download_directories: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_product_meta_lookup: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
wp_wc_rate_limits: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_reserved_stock: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wc_tax_rate_classes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_bundled_itemmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_bundled_items: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB

### Post Type Counts ###

attachment: 25
page: 22
post: 8
product: 21
product_variation: 7
revision: 35
shop_coupon: 1
shop_order: 4
wp_global_styles: 2
wp_template: 1
wp_template_part: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

Query Monitor: por John Blackbourn – 3.12.0
WooCommerce Beta Tester: por WooCommerce – 2.1.0
WooCommerce: por Automattic – 7.6.0-beta.1

### Inactive Plugins (6) ###

Akismet Anti-Spam: por Automattic – 5.1
Gutenberg: por Gutenberg Team – 15.3.1
Jetpack: por Automattic – 12.0-a.5
Page Optimize: por Automattic – 0.5.2
WooCommerce Product Bundles: por WooCommerce – 6.17.3
WordPress Beta Tester: por Peter Westwood
Andy Fragen – 3.3.4

### Dropin Plugins (3) ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class (Drop-in)
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Base de la tienda: #6 - /shop/
Carrito: #7 - /cart/
Finalizar compra: #8 - /checkout/
Mi cuenta: #9 - /my-account/
Términos y condiciones: ❌ Página sin definir

### Theme ###

Name: Twenty Twenty-Three
Version: 1.1
Author URL: https://wordpress.org
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: block-editor-feature-enabled
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-03-23 08:48:07 +00:00
Options: ✔
Notes: 37
Onboarding: skipped

### Action Scheduler ###

Completo: 4.817
Oldest: 2023-03-22 08:49:17 +0000
Newest: 2023-03-22 16:13:16 +0000

Fallida: 3
Oldest: 2023-03-22 09:12:33 +0000
Newest: 2023-03-22 13:03:37 +0000

Pendiente: 2
Oldest: 2023-03-22 16:13:49 +0000
Newest: 2023-03-23 08:49:17 +0000

### Status report information ###

Generated at: 2023-03-22 16:13:49 +00:00
`

</details>

**Comment by danieldudzic** [comment]
This seems to be working correctly now:

<img width="1203" alt="fixed" src="https://github.com/woocommerce/woocommerce-blocks/assets/905781/b699f1be-9a3b-454c-a301-4a964b04b155">

I will close for now, but please re-open if the issue persists.
