### ISSUE TITLE
Ensure Checkout block supports the theme-level global styles for `Layout » Block spacing`

### ISSUE THREAD

**Issue by tarunvijwani** [woocommerce/woocommerce-gutenberg-products-block#8826]
Currently, the Checkout block partially supports the default theme-level global styles for `Layout » Block spacing`. This issue aims to ensure that the Checkout block fully supports the default theme-level global styles.

## Steps to reproduce

1. Go to `WP Admin » Apperance » Editor`.
2. Open the `Styles` sidebar.
3. Open the `Layout » Block spacing` settings.
4. Adjust the Block spacing.
5. See that settings are not supported.

## Screenshots
| Settings | Editor | Frontend |
|---|---|---|
|<img width="100%" alt="image" src="https://user-images.githubusercontent.com/11503784/227126080-ba5ce058-17cc-44b1-857d-a214d582954a.png">|<img width="100%" alt="image" src="https://user-images.githubusercontent.com/11503784/227126314-66c43940-69e6-4a68-98f7-2743a057a90a.png">|<img width="100%" alt="image" src="https://user-images.githubusercontent.com/11503784/227126663-8c6721e9-c02b-4804-a62f-e72357437a7e.png">|

**Comment by tarunvijwani** [comment]
@nielslange Saad has shared some of his [findings related to the same topic](https://github.com/woocommerce/woocommerce-blocks/issues/8828#issuecomment-1489594023) that might apply to this ticket as well.

**Comment by nielslange** [comment]
Internal discussion: p1680693584700449-slack-C02UBB1EPEF

**Comment by nielslange** [comment]
Closing this issue based on p1680703800302049/1680693584.700449-slack-C02UBB1EPEF
