### ISSUE TITLE
Ensure Checkout block supports the theme-level global styles for `Blocks » Product image » layout`

### ISSUE THREAD

**Issue by tarunvijwani** [woocommerce/woocommerce-gutenberg-products-block#8827]
Currently, the Checkout block partially supports the default theme-level global styles for `Blocks » Product image » layout`. This issue aims to ensure that the Checkout block fully supports the default theme-level global styles.

## Steps to reproduce

1. Go to `WP Admin » Apperance » Editor`.
2. Open the `Styles` sidebar.
3. Open the `Blocks » Product image » layout` settings.
4. Adjust the settings.
5. Notice it is breaking the CSS on the frontend and editor. 

## Screenshots
| Settings | Editor | Frontend |
|---|---|---|
|![image](https://user-images.githubusercontent.com/11503784/227129592-404760c0-466f-41ec-861e-42e8da4a3319.png)|![image](https://user-images.githubusercontent.com/11503784/227129640-cf7c40af-5f94-4590-8388-207a1633ccda.png)|![image](https://user-images.githubusercontent.com/11503784/227129679-98dd5036-5264-4c30-b13f-2c8283456709.png)|

**Comment by nielslange** [comment]
Closing this issue as it had been fixed with #8898.
