### ISSUE TITLE
Ensure Cart block supports the theme-level global styles for `Layout » Block spacing`

### ISSUE THREAD

**Issue by tarunvijwani** [woocommerce/woocommerce-gutenberg-products-block#8828]
Currently, the Cart block partially supports the default theme-level global styles for `Layout » Block spacing`. This issue aims to ensure that the Cart block fully supports the default theme-level global styles.

## Steps to reproduce

1. Go to `WP Admin » Apperance » Editor`.
2. Open the `Styles` sidebar.
3. Open the `Layout » Block spacing` settings.
4. Adjust the Block spacing.
5. See that settings are not supported.

## Screenshots
| Settings | Editor | Frontend |
|---|---|---|
|<img width="100%" alt="image" src="https://user-images.githubusercontent.com/11503784/227130885-e2dcf14d-7714-4e50-840b-53fab1aa1471.png">|<img width="100%" alt="image" src="https://user-images.githubusercontent.com/11503784/227130598-462eda3f-b759-4707-bb3d-422f7f75c5bc.png">|<img width="100%" alt="image" src="https://user-images.githubusercontent.com/11503784/227130728-9feadf9b-5581-4540-8567-b0cb08bef811.png">|

**Comment by nielslange** [comment]
Closing this issue based on https://github.com/woocommerce/woocommerce-blocks/issues/8752#issuecomment-1478612392.

**Comment by tarhi-saad** [comment]
I didn't get the time to implement some ideas I discussed with @tarunvijwani in our last call! But here are some findings for anyone interested in taking over this ticket.

- There are no examples of `Block spacing` support implementation from other teams. So, feel free to try different ideas and test against a couple of block themes.
- We want to have the spacing applied between the Inner Blocks
- From what I gathered, two styles get updated when changing the `Block spacing`: `gap` and `margin-block-start`
- `gap` is applied to the elements with the class: `.is-layout-flex`
- `margin-block-start` is applied to the elements with the selector: `.is-layout-flow > * + *`

Here are some suggestions we can apply:

- You can start by inheriting the `gap` and `margin-block-start` values
- If it doesn't work, maybe you can add the mentioned classes to some parent element and then inherit the `gap` and `margin-block-start` values

**Comment by nielslange** [comment]
Internal discussion: p1680693584700449-slack-C02UBB1EPEF

**Comment by nielslange** [comment]
Closing this issue based on p1680703800302049/1680693584.700449-slack-C02UBB1EPEF
