### ISSUE TITLE
Cross-Sells Products block: Replace Add to Cart block with Product Button block

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#8858]
In woocommerce/woocommerce#44503, @kmanijak suggested removing the Add to Cart block as that block is experimental, hasn't been touched for 3 years and as there's a newer block. Currently, the Cross-Sells Block is still using the Add to Cart block. This issue aims to replace the Add to Cart block with the Product Button block within the Cross-Sells Products block.

**Comment by ralucaStan** [comment]
- Is the Add to Cart used in other places?
- What are the immediate advantages of using the Add to Cart Form block?

**Comment by nielslange** [comment]
> * Is the Add to Cart used in other places?

The `<AddToCartButton/>` component is used in the following files:

1. `assets/js/blocks/cart/cart-cross-sells-product-list/cart-cross-sells-product.tsx`
2. `assets/js/atomic/blocks/product-elements/add-to-cart/product-types/variable/index.tsx`
3. `assets/js/atomic/blocks/product-elements/add-to-cart/product-types/simple.tsx`

The first file loads the component from `assets/js/atomic/blocks/product-elements/add-to-cart/block.tsx`, the second and third file load the component from `assets/js/atomic/blocks/product-elements/add-to-cart/shared/add-to-cart-button.tsx`.

> * What are the immediate advantages of using the Add to Cart Form block?

Switching `<AddToCartButton />` to `<ProductButton />` allows us to remove the Add To Cart Button block as well as it ensures that the buttons of Cross-Sells products support Global Styles. Below you can find a screenshot that shows how the Cross-Sells block would be impacted by a switch from `<AddToCartButton />` to `<ProductButton />`.

<table>
<tr>
<td>

`<AddToCartButton />`

<br><br>

<img width="1165" alt="Screenshot 2023-03-30 at 14 33 17" src="https://user-images.githubusercontent.com/3323310/228762899-15d86cf2-bec5-4584-b717-26056454591e.png">

</td>
<td>

`<ProductButton />`

<br><br>

<img width="1091" alt="Screenshot 2023-03-30 at 14 32 46" src="https://user-images.githubusercontent.com/3323310/228762790-155a4803-4321-4b6a-8033-2a1b8d05f6f2.png">

</td>
</tr>
</table>

**Comment by tarunvijwani** [comment]
Closed by https://github.com/woocommerce/woocommerce-blocks/pull/8914 PR
