### ISSUE TITLE
Add ajax support for Add to cart form

### ISSUE THREAD

**Issue by tomxygen** [woocommerce/woocommerce-gutenberg-products-block#8862]
## Is your feature request related to a problem? Please describe.
Currently, when using the Add to cart form in the single product template, if the user clicks on Add to cart, the page is reloaded.

## Describe the solution you'd like
Ajax add to cart should be implemented in the Add to cart form, because it is a requirement for all the modern ecommerce stores.
Moreover, without reloading the page, it's possible smoothly add to cart and then auto-open the mini cart with the product already in the cart.

**Comment by roykho** [comment]
Hi @tomxygen - Thanks for your request. This enhancement has actually been requested before. I will close this issue and leave you a link where this is already being tracked [here](https://github.com/woocommerce/woocommerce/issues/36006)

**Comment by tomxygen** [comment]
Hi @roykho thank you for your reply.
However, that the enhancement request you mentioned, is related to WooCommerce in general, which includes Classic Themes as well.
What I'm referring with my enhancement request is specific to WooCommerce blocks and the Add to cart form

**Comment by roykho** [comment]
Hi @tomxygen - Yes I understand. At this point they're one in the same. Meaning we have discussions on both ends and if we do it to one we will likely do it to the other. At least from Woo core to Blocks is concern. I hope that is more clear.
