### ISSUE TITLE
Blockified Product Archive: Provide a way for the user to easily roll back to the Classic Template

### ISSUE THREAD

**Issue by kmanijak** [woocommerce/woocommerce-gutenberg-products-block#8875]
### Description
Currently, the user can rollback to the Classic Template by adding the block WooCommerce Product Grid Block (or similar on different templates).

For newcomers, this approach could be complex and not straightforward. One proposal is to add the roll-back button to the template inspector controls. We should investigate if we can extend it.

### Notes
Keep in mind there's a parallel issue about exactly the same goal for Blockified Single Product Template: https://github.com/woocommerce/woocommerce-blocks/issues/8853. Before working on this issue, check on https://github.com/woocommerce/woocommerce-blocks/issues/8853 to make sure the work is not duplicated. In case there's already a solution/proposal/research done in https://github.com/woocommerce/woocommerce-blocks/issues/8853, please follow it.

**Comment by gigitux** [comment]
This issue was fixed by #9386.
