### ISSUE TITLE
Unify Payment Gateway incompatibility with the Cart & Checkout Blocks

### ISSUE THREAD

**Issue by devcisplshoubhik** [woocommerce/woocommerce-gutenberg-products-block#8886]
Unify Payment Gateway plugin incompatibility with the Cart & Checkout Blocks. We tried to find out a solution to make it compatible. Can anyone provide us with proper documentation to follow up and resolve the incompatibility issue?

**Comment by opr** [comment]
Hi @devcisplshoubhik - are you referring to https://unyfi.co.uk/services/merchant-services/payment-gateway/ ?

If so, then thank you for taking the time to make us aware that it isn’t working with the Checkout and Cart blocks. These Blocks are a beta feature to optimize for faster checkout and it’s expected that some existing Woo Extensions that integrate with the current checkout flow in WooCommerce core will not work with the blocks.

Currently it’s up to extension developers to add support for the new checkout flow offered via the Cart and Checkout Blocks. We have some [documentation for Third-party developers](https://href.li/?https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs#third-party-developers) and some [Developer Resources](https://href.li/?https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs#developer-resources) available to help with their integration efforts.

Your best course of action now if you are using a payment method that isn’t working with the blocks is to notify the developer of the extension and ask if they can add support.

Until then, you can keep on top of the [status of the Cart & Checkout Blocks in this documentation](https://href.li/?https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/).
