### ISSUE TITLE
9.9.0 release > unsorted changelog

### ISSUE THREAD

**Issue by Marc-pi** [woocommerce/woocommerce-gutenberg-products-block#8917]
It starts with 9.8.4, 9.9.0 changes are below, user has to scroll to see what's new

Just have a look at screenshot to understand better
It's within the WP Plugin Updater

![image](https://user-images.githubusercontent.com/919332/229097641-b7c95e52-50db-4976-bcda-82cd477abb2b.png)

![image](https://user-images.githubusercontent.com/919332/229097847-bf86c21e-4909-482a-aca6-1c422c61c3eb.png)

**Comment by opr** [comment]
Hi @Marc-pi thank you for bringing this to our attention - the release process is still ongoing so we will address this later today.

By the way we expect the release to be finalised today with an accompanying announcement post on https://developer.woocommerce.com/

I'll leave this issue open until we've addressed it.

**Comment by opr** [comment]
Hey @Marc-pi - [The changelog](https://wordpress.org/plugins/woo-gutenberg-products-block/#developers) has been updated! Thanks again for letting us know about that.
