### ISSUE TITLE
When using multiple packages and "Hide shipping costs until an address is entered" the rates are still shown in the sidebar

### ISSUE THREAD

**Issue by opr** [woocommerce/woocommerce-gutenberg-products-block#8919]
If the Checkout block has the "Hide shipping costs until an address is entered" option enabled, the rates do not show in the Shipping Options block, however the packages still have their rates shown in the sidebar

<img width="914" alt="image" src="https://user-images.githubusercontent.com/5656702/229108170-108ec282-91b6-405c-bcef-4aaec45ecbc6.png">

We should hide it, and ensure the totals are calculated excluding the shipping price while the address is incomplete.

For whoever works on this, we should include a shoutout about the "Hide shipping costs until an address is entered" functionality in the 10.0.0 announcement post.

**Comment by dennisjonda** [comment]
Also already in the shopping cart, before entering a shipping address, although I have switched it off. Or do I have to do something else?
![grafik](https://user-images.githubusercontent.com/74372535/229326800-8afa81a7-e68e-477d-89e4-78e64ecfa784.png)

**Comment by K13NN13** [comment]
also having a similar issue. The shipping options are selected already and I don't have the option to change the shipping address in the cart page.
