### ISSUE TITLE
WooCommerce Blocks

### ISSUE THREAD

**Issue by Gerry-Berry** [woocommerce/woocommerce-gutenberg-products-block#893]
Hi there,

I'm having issue with the WooCommerce blocks.
When I want to add a new product block it tells me that either I have no products or that there is no WooCommerce installed.

When I check a page where product blocks have already been inserted, it tells me the site is having technical difficulties.

Any suggestions how I can fix this or is it a bug after the last update?

Thanks,

Gerry

![Screenshot 2019-08-20 at 14 52 41](https://user-images.githubusercontent.com/54315108/63344968-5611f080-c35a-11e9-994a-4bd836dd7b88.png)
![Screenshot 2019-08-20 at 14 52 23](https://user-images.githubusercontent.com/54315108/63344969-5611f080-c35a-11e9-8104-5bae239edeb3.png)
![Screenshot 2019-08-20 at 14 51 15](https://user-images.githubusercontent.com/54315108/63344970-5611f080-c35a-11e9-9900-4ecf56483c56.png)

**Comment by mikejolley** [comment]
ADVGB is not a block from this plugin. The featured product block is however. Can you post your status report so we can take a look what else is running?

**Comment by Gerry-Berry** [comment]
Here it is: 

`
### WordPress Environment ###

WordPress address (URL): https://www.oceannation.store
Site address (URL): https://www.oceannation.store
WC Version: 3.7.0
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: ✔
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: bg_BG
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.8
PHP Post Max Size: 512 MB
PHP Time Limit: 300
PHP Max Input Vars: 256
cURL Version: 7.65.0
OpenSSL/1.0.2k-fips

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.25-MariaDB-log
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.7.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 33.78MB
Database Data Size: 24.84MB
Database Index Size: 8.94MB
wp_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_4_adsw_activities: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_4_adsw_ali_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_4_adsw_search_analytics: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_4_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_4_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_4_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_4_ig_blocked_emails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_4_ig_campaigns: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_4_ig_contacts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_4_ig_contacts_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_4_ig_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_4_ig_lists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_4_ig_lists_contacts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_4_ig_mailing_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_4_ig_sending_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_4_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_4_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_4_options: Data: 2.05MB + Index: 0.05MB + Engine InnoDB
wp_4_postmeta: Data: 1.52MB + Index: 0.23MB + Engine InnoDB
wp_4_posts: Data: 2.44MB + Index: 0.06MB + Engine InnoDB
wp_4_pum_subscribers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_4_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_4_redirection_404: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_4_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_4_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_4_redirection_logs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_4_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_4_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_4_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_4_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_4_trp_gettext_bg_bg: Data: 0.34MB + Index: 0.27MB + Engine InnoDB
wp_4_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_4_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_4_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_4_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_4_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_4_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_4_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_4_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_4_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_4_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_4_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_4_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_4_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_4_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_4_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_4_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_4_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_4_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_4_yoast_seo_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_4_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_5_trp_gettext_bg_bg: Data: 0.16MB + Index: 0.09MB + Engine InnoDB
wp_5_yoast_seo_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_5_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ac_abandoned_cart_history_lite: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_ac_email_templates_lite: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ac_sent_history_lite: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_adsw_activities: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_adsw_ali_meta: Data: 0.14MB + Index: 0.03MB + Engine InnoDB
wp_adsw_search_analytics: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_berocket_termmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_blogmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_blogs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_blog_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_hustle_modules: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_hustle_modules_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ig_blocked_emails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ig_campaigns: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ig_contacts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ig_contacts_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ig_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ig_lists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ig_lists_contacts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ig_mailing_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ig_sending_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nextend2_image_storage: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_nextend2_section_storage: Data: 0.30MB + Index: 0.03MB + Engine InnoDB
wp_nextend2_smartslider3_generators: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nextend2_smartslider3_sliders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nextend2_smartslider3_sliders_xref: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nextend2_smartslider3_slides: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 3.06MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 2.52MB + Index: 2.00MB + Engine InnoDB
wp_posts: Data: 1.52MB + Index: 0.30MB + Engine InnoDB
wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_redirection_404: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_registration_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_site: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sitemeta: Data: 1.02MB + Index: 0.03MB + Engine InnoDB
wp_skrill_transaction_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_trp_dictionary_bg_bg_en_gb: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_trp_dictionary_bg_bg_en_us: Data: 2.52MB + Index: 0.30MB + Engine InnoDB
wp_trp_dictionary_en_us_bg_bg: Data: 0.13MB + Index: 0.14MB + Engine InnoDB
wp_trp_gettext_bg_bg: Data: 1.52MB + Index: 0.38MB + Engine InnoDB
wp_trp_gettext_en_gb: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_trp_gettext_en_us: Data: 2.52MB + Index: 2.19MB + Engine InnoDB
wp_UPCP_Catalogues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_UPCP_Catalogue_Items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_UPCP_Categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_UPCP_Custom_Fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_UPCP_Fields_Meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_UPCP_Items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_UPCP_Item_Images: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_UPCP_SubCategories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_UPCP_Tagged_Items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_UPCP_Tags: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_UPCP_Tag_Groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_UPCP_Videos: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_usermeta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.05MB + Index: 0.00MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (29) ###

Child Theme Configurator: by Lilaea Media – 2.5.0
Contact Form 7: by Takayuki Miyoshi – 5.1.4
Cookie Notice: by dFactory – 1.2.46
Currency Switcher for WooCommerce: by WP Wham – 2.11.0
PayPal for WooCommerce: by Angell EYE – 1.5.7 – Not tested with the active version of WooCommerce
Smart Slider 3: by Nextend – 3.3.21
WooCommerce Blocks: by Automattic – 2.3.0
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.12
WooCommerce: by Automattic – 3.7.0
Smush: by WPMU DEV – 3.2.4
Contact Form 7: by Takayuki Miyoshi – 5.1.4
Child Theme Configurator: by Lilaea Media – 2.5.0
Smush: by WPMU DEV – 3.2.4
Ultimate Addons for Gutenberg: by Brainstorm Force – 1.13.6
Gutenberg: by Gutenberg Team – 6.3.0
Advanced Gutenberg: by JoomUnited – 2.0.7
Advanced Gutenberg Blocks: by maximebj – 1.9.1
Social Media Follow Buttons Bar: by Space X-Chimp – 4.54.1
FB Messenger Live Chat: by Zotabox – 1.4.10
TranslatePress - Multilingual: by Cozmoslabs
Razvan Mocanu
Madalin Ungureanu
Cristophor Hurduban – 1.5.5 – Not tested with the active version of WooCommerce

All In One SEO Pack: by Michael Torbert – 3.2.4
Stackable - Gutenberg Blocks: by Gambit Technologies
Inc – 1.17.1

Kadence Blocks - Gutenberg Page Builder Toolkit: by Kadence WP – 1.6.7
Enhanced Text Widget: by Boston Dell-Vandenberg – 1.4.6
Easy Facebook Likebox: by Danish Ali Malik – 4.4.1
Akismet Anti-Spam: by Automattic – 4.1.2
WooCommerce: by Automattic – 3.7.0
WooCommerce Blocks: by Automattic – 2.3.0
Redirection: by John Godley – 4.3.3

### Inactive Plugins (1) ###

AliDropship Woo Plugin: by Vitaly Kukin & Yaroslav Nevskiy & Pavel Shishkin & Denis Zharov – 1.5.4 – Not tested with the active version of WooCommerce

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: BGN (лв.)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #4 - /catalogue/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page visibility should be public

### Theme ###

Name: Gutenshop Child Ocean Nation
Version: 2.5.1553458535
Author URL: https://superbthemes.com/
Child Theme: ✔
Parent Theme Name: Gutenshop
Parent Theme Version: 3.1
Parent Theme Author URL: https://superbthemes.com/
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: gutenshop/woocommerce/checkout/form-coupon.php
gutenshop/woocommerce/checkout/terms.php
gutenshop/woocommerce/content-product.php
gutenshop/woocommerce/content-single-product.php
gutenshop/woocommerce/myaccount/form-login.php


### Action Scheduler ###

Complete: 7
Oldest: 2019-07-27 05:29:06 +0000
Newest: 2019-08-19 14:54:15 +0000

Pending: 1
Oldest: 2019-08-24 07:17:05 +0000
Newest: 2019-08-24 07:17:05 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

**Comment by Gerry-Berry** [comment]
Hi there,
any suggestions on the issue?

My reusable blocks are also not working.

Thanks

**Comment by mikejolley** [comment]
I've not had a chance to look into this yet but the first thing that stands out is multisite. 

I wonder if the API on your site is not working correct, since you say all blocks are having issues, not just the Woo blocks.

**Comment by Gerry-Berry** [comment]
Hey there,

Yes, I noticed blocks can't pull any data from the site - products, posts
pages, etc.
Recently I installed Redirection plug in as I want to delete the subdomain
(data has been transferred to main domain). I deactivated it, but the issue
persists.
I also read it might be an SSL issue and tomorrow I will disable my
certificate and see what happens.
Any suggestions will be much appreciated :)

Thanks,

Gerry

**Comment by mikejolley** [comment]
Did you have any luck with this?

If not you may need to try removing plugins one-by-one to find a conflict, or can try Saving permalink settings to ensure any stored rules are flushed if API endpoints are broken (settings > permalinks > save).

**Comment by Gerry-Berry** [comment]
Hey there and sorry for the late reply!
I haven't done it yet, hopefully I'll get to it tomorrow.

Have you had similar issues reported by other users? The blocks worked fine on multisite so far.

I'll keep you posted.
Have a nice day!

**Comment by Gerry-Berry** [comment]
Hi again!
I started deactivating my plugins one by one and it turned out the issue was caused by Currency Switcher For WooCommerce.
All blocks seem to work fine now that it's deactivated, but I'll still need a currency switcher.
Any suggestions?

Thanks,
Gerry

**Comment by mikejolley** [comment]
@Gerry-Berry Probably best to report this to the author of that extension if it's affecting all blocks so they can see what is causing this. Thanks for posting an update here.
