### ISSUE TITLE
Product Price block inside the All Products block: shows product selector in the editor

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#8932]
This is a recent regression, as I couldn't reproduce in WC core 7.5 without WC Blocks installed.

## To reproduce

1. Create a post or page.
2. Insert the All Products block.
3. Edit the layout of the All Products block.
4. Notice the Product Price inner block shows a product selector.

## Expected behavior

The Product Price block inside the All Products block should display the product price, not the product selector.

## Screenshots

WC 7.5 | WC 7.5 with WC Blocks 9.9
--- | ---
![imatge](https://user-images.githubusercontent.com/3616980/229519467-e350327d-1568-4ace-8669-a8e6ef75e458.png) | ![imatge](https://user-images.githubusercontent.com/3616980/229519388-78ef5a8e-1baa-4912-a3d9-f9bce401ebc6.png)

**Comment by Aljullu** [comment]
@gigitux I think this was introduced in https://github.com/woocommerce/woocommerce-blocks/pull/8609. Considering that we no longer allow inserting the Product Price block without a parent. Do you think we could completely remove the [`ProductSelector`](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/atomic/blocks/product-elements/price/edit.tsx#L105)?

**Comment by gigitux** [comment]
> @gigitux I think this was introduced in #8609. Considering that we no longer allow inserting the Product Price block without a parent. Do you think we could completely remove the [`ProductSelector`](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/atomic/blocks/product-elements/price/edit.tsx#L105)?

Thanks for catching this! I agree with you! I will assign this issue to me 💪
