### ISSUE TITLE
[Mini Cart]: Change the `Add to cart` control to a toggle

### ISSUE THREAD

**Issue by albarin** [woocommerce/woocommerce-gutenberg-products-block#8946]
The `Mini Cart` block has the `Add to cart behaviour` option in its settings.

<img width="268" alt="Screenshot 2023-04-18 at 13 29 37" src="https://user-images.githubusercontent.com/186112/232763634-c65c198c-9bd2-47fb-94a5-efc62cafb88e.png">

Since it's a binary choice (`Do nothing` or `Open cart in a drawer`), it's better for it to be a toggle control (see https://github.com/woocommerce/woocommerce-blocks/issues/7517#issuecomment-1495021317 for more context)

It should look like 👇 
<img width="270" src='https://user-images.githubusercontent.com/191598/229633698-ded80ef8-3a68-45ef-9a7f-cfd668a3f19d.png' />

**Comment by Sidsector9** [comment]
Hello, I would like to work on this issue.

**Comment by ankitguptaindia** [comment]
Hi, I would like to do QA on this issue as part of Contribution Day.
