### ISSUE TITLE
Create `Header: Minimal` pattern

### ISSUE THREAD

**Issue by albarin** [woocommerce/woocommerce-gutenberg-products-block#8953]
![Row](https://user-images.githubusercontent.com/186112/232717046-f5a395f9-a554-4982-8dfd-f42163ecb512.png)

Check Figma designs F5AAbRJOGbTeEweXPFtHgf-fi-1540_33115 for the latest updates and mobile views.

**Comment by albarin** [comment]
- **Mini Cart**: the counter cannot be removed, I think there's an issue in the `Mini Cart` project to make the icon more customizable, should we just use the one we have for now with the counter for this pattern?

**Comment by roykho** [comment]
I believe also the "hamburger" menu has to be created as a new block?

**Comment by albarin** [comment]
> I believe also the "hamburger" menu has to be created as a new block?

@roykho I think we already have it, check the `WooCommerce Header Minimal`, there's an example there. 😄

**Comment by roykho** [comment]
@albarin - hmmm but it's not exactly the same right. I believe the `WooCommerce Header Minimal` is using the native Gutenberg Navigation block. It has a different icon than the design and also the opened menu, in our design we have a search bar in the popover where the native menu doesn't?

**Comment by albarin** [comment]
@roykho Oh, I completely missed the opened menu design in Figma, I just saw it 🤦 Yes, I'm not sure how much that can be customized, I'm seeing you can add blocks to it, maybe we can add the search block there.
Also, the icon can be changed to the 3 lines one:
<img width="274" alt="Screenshot 2023-04-14 at 15 37 44" src="https://user-images.githubusercontent.com/186112/232059430-4177ee83-a51f-4c60-a96a-357b13c9f8e4.png">

**Comment by albarin** [comment]
Updated design with the latest changes.
