### ISSUE TITLE
Store API - Add product slug field

### ISSUE THREAD

**Issue by achorein** [woocommerce/woocommerce-gutenberg-products-block#8985]
## Is your feature request related to a problem? Please describe.
I would like to use woocommerce store api to build a static headless shop without API authentification (using the "Store API" instead of the Woo Rest API).
For that i need the product slug to be available and usable in order to correctly build my urls (routes).

## Describe the solution you'd like
- `/wc/store/v1/products` should return `slug` attribute (in addition of `permalink`)
- we should be able to get a product from his slug and not only by the id (`/wc/store/v1/products/:id` and `/wc/store/v1/products/:slug`). Or to find a product using the search api : `/wc/store/v1/products?slug=product-slug`

**Comment by wavvves** [comment]
Hi @achorein, thanks for reaching out.

Can you provide us more details on the use case where searching by slug would be required?

I'm guessing you would like to have your URL structure, and on the product details page try get a product by provided slug and return a 404 if none match? Is that the case?

**Comment by achorein** [comment]
> I'm guessing you would like to have your URL structure, and on the product details page try get a product by provided slug and return a 404 if none match? Is that the case?

@wavvves exactly

The use case is simple :
1.  A main page using `/wc/store/v1/products` to list all products in the shop with thumbnails. Links built from frontend using only product slug attribute (not `permalink` which will differ between frontend and backend)
2. A product detail page, built with `/wc/store/v1/products/:slug` data (for SEO we use slug instead of id)

searching by slug is not necessary if we can directly get a product by its slug, it was another solution that could have satisfied the need.
