### ISSUE TITLE
Proceed to Checkout button overlaps within Cart block in post editor

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#8996]
## Describe the bug

When using a block theme, e.g. [Twenty Twenty-Three](https://wordpress.org/themes/twentytwentythree/), and when using a payment gateway that shows an Express Payment button in the Cart block, the Proceed to Checkout button overlaps the `OR` separator. In addition, there's no spacing between the Proceed to Checkout button and the payment method icons.

## To reproduce

1. Install and activate a block theme, e.g. [Twenty Twenty-Three](https://wordpress.org/themes/twentytwentythree/).
2. Install and activate the [WooCommerce Stripe Payment Gateway](https://wordpress.org/plugins/woocommerce-gateway-stripe/) plugin.
3. Activate Express checkouts.
<img width="1069" alt="Screen Shot 2023-04-11 at 13 02 13" src="https://user-images.githubusercontent.com/3323310/231070035-abf52a6b-f19f-4e41-9f30-e158fa953d93.png">

4. Create a test page and add the Cart block.
5. Verify that the Proceed to Checkout button overlaps the `OR` separator.
6. Verify there's no spacing between the Proceed to Checkout button and the payment method icons.
7. Switch to a classic theme, e.g. [Storefront](https://wordpress.org/themes/storefront/).
8. Verify that the issue does not appear when using a classic theme.

## Expected behavior

When using a block theme, the Proceed to Checkout button should not overlap and there should be sufficient spacing between the button and the payment method icons.

## Screenshots

<img width="1307" alt="Screen Shot 2023-04-11 at 13 04 41" src="https://user-images.githubusercontent.com/3323310/231070477-29957b0f-38cc-4298-93ef-7e4c3c828d85.png">

**Comment by ralucaStan** [comment]
I don't think this is actually a bug now, @tarhi-saad could you please check

**Comment by ralucaStan** [comment]
I was not able to replicate this. Closing
