### ISSUE TITLE
invalid parameter owner[name] on checkout page 

### ISSUE THREAD

**Issue by Moosinams** [woocommerce/woocommerce-gutenberg-products-block#8997]
## Describe the bug

filling in the customer details on the checkout page (as returning customer, autofill), result in this error:
Invalid parameter owner[name]. Owner name must be at least 3 characters long.

## To reproduce

Go to moosinams.nl/checkout
fill in details as returning customer using autofill

## Expected behavior

normally payment page will appear

## Screenshots

![Schermafbeelding 2023-04-11 om 10 58 14](https://user-images.githubusercontent.com/126246807/231117017-bf74f9a1-157d-4015-9224-dad4bbb8d9c1.jpg)

## Environment

Using the newest versions of the plugins, using as well iPhone 10 as Macbook Monterey

**Comment by wavvves** [comment]
Closing this as it is a duplicate for #9038
