### ISSUE TITLE
Investigate if we can get GB release candidates in Woo Blocks automated tests (at least on nightlies)

### ISSUE THREAD

**Issue by ralucaStan** [woocommerce/woocommerce-gutenberg-products-block#9012]
It'd be good to investigate whether we can automatically get the GB release candidates in Woo Blocks automated tests (at least on nightlies). That could help potential GB issues before a release (at least gives us a week's heads up). 

At the moment we don't run any E2E tests on nightlies. The tests we would introduce should not interfere with creating the nightly ZIP, as it is consumed by other extensions in their own tests.

p1681210630634569-slack-C04NWH6NDHA

**Comment by mikejolley** [comment]
Closing due to pca54o-6Dz-p2
