### ISSUE TITLE
Single Product Block missing meta information on frontend

### ISSUE THREAD

**Issue by roykho** [woocommerce/woocommerce-gutenberg-products-block#9030]
## Describe the bug

When the single product block is used, meta information such as SKU, categories and tags are missing on the frontend.

## To reproduce

1. Add a page.
2. Add the Single Product Block. Update save.
3. Open this page on the frontend.
4. See that the meta information is missing.

## Expected behavior

All the meta information should be shown.

## Screenshots

| Editor | Frontend |
| ------ | ----- |
| ![UIGJ88.png](https://user-images.githubusercontent.com/2132595/231788399-520c0cd4-42ec-4032-95f5-07cf55f67cb1.png)|![ty613B.png](https://user-images.githubusercontent.com/2132595/231788589-329c710c-5e76-47a7-a56d-3ac7f65574f5.png)|

### WordPress (please complete the following information):

-   WordPress version: 6.2
-   Gutenberg version (if installed): 15.5.1
-   WooCommerce version: 7.7.0-dev
-   WooCommerce Blocks version: 10.1.0-dev
-   Site language: English
-   Any other plugins installed:

### Desktop (please complete the following information):

-   OS: macOS
-   Browser: Chrome
-   Version: 112.0

**Comment by gigitux** [comment]
cc @thealexandrelara

**Comment by thealexandrelara** [comment]
Thank you for reporting this @roykho, I'll take a look into it 

@gigitux I saw that you're working on https://github.com/woocommerce/woocommerce-blocks/pull/8966 so just want to confirm with you that this is a different issue (just to avoid working on the same thing 😅 )

**Comment by gigitux** [comment]
> Thank you for reporting this @roykho, I'll take a look into it
> 
> @gigitux I saw that you're working on #8966 so just want to confirm with you that this is a different issue (just to avoid working on the same thing 😅 )

I just aligned that PR with trunk and I can confirm that the Product Meta block isn't rendered on the front end. My PR fixes only the Product SKU. I think that we introduced some regression with the last changes that we did.

**Comment by thealexandrelara** [comment]
> I just aligned that PR with trunk and I can confirm that the Product Meta block isn't rendered on the front end. My PR fixes only the Product SKU. I think that we introduced some regression with the last changes that we did.

Ohh okay, I'll take a look into it and find a fix for this so you won't be blocked by this issue 🦾
