### ISSUE TITLE
The way how WooCommerce blocks are disabled has unexpected side effects

### ISSUE THREAD

**Issue by CreativeDive** [woocommerce/woocommerce-gutenberg-products-block#9050]
This is my reference issue from https://github.com/WordPress/gutenberg/issues/12931

Is there a solution in the meanwhile? In the case you want allow all blocks in a specific context, except for a few other blocks that shouldn't be allowed, what can we do to solve that?

1. Get all registered blocks as array.
2. Exclude specific blocks from the array.
3. As result we can use all blocks but not our excluded blocks.

That's the only way I can think of to solve this. Therefore I use `WP_Block_Type_Registry::get_instance()->get_all_registered()` to get all the registered blocks. But here is an dramatic issue (like mentioned above). I can't get all registered blocks. It seems some block types are missing.

In my case the missing block types are only WooCommerce blocks, but not all only some specific WooCommerce blocks.

For this reason I get this warning in the console if the block have a list of allowed blocks included:

<img width="2027" alt="Bildschirmfoto 2023-04-14 um 10 54 31" src="https://user-images.githubusercontent.com/31563167/232006037-d00839e1-ee7f-4582-b22d-20f0170aa3bb.png">

It seems this is only a warning and not a breaking thing.

I have checked the differences between and the result are missing WooCommerce blocks which are not included in `WP_Block_Type_Registry::get_instance()->get_all_registered()`:

<img width="1607" alt="Bildschirmfoto 2023-04-14 um 11 01 44" src="https://user-images.githubusercontent.com/31563167/232006404-78fad3fe-8628-48bc-9b68-5978853e25df.png">

My question here, why there are not all registered blocks included by `WP_Block_Type_Registry::get_instance()->get_all_registered()`?

At the moment I have no solution and no idea to solve that.

**Comment by CreativeDive** [comment]
I can see this is the reason why the WooCommerce block types are missing:

https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/BlockTypesController.php#L258-L274

This makes it difficult to get all the blocks this way.

**Comment by CreativeDive** [comment]
Is there any other way to disable these blocks later than the init action?

**Comment by CreativeDive** [comment]
I think the most common way without having this side effect would be using `unregisterBlockType()` in javascript.

**Comment by Aljullu** [comment]
Hey there, @CreativeDive, thanks for opening this issue.

This looks like a tricky one because it might involve some limitations from Gutenberg. As you mention, there are some blocks which we don't register in the post/page editor because we don't want them to be available in that context. My understanding is that this is what's causing issues to you, is that correct? Also, it wasn't clear to me what you are trying to achieve. You want to filter out all WC Blocks in the post/page context for all users?

Having a better understanding of the use case would help us see whether there is anything we do on our end. Thanks in advance!

**Comment by CreativeDive** [comment]
@Aljullu thank you for response. It's about determining which blocks should be allowed as inner blocks.

Normally I can determine which blocks are allowed as inner blocks. But that doesn't make much sense if there are 50 blocks that should be allowed and 5 blocks that shouldn't be allowed. Apart from blocks that the user installs and wants to add himself.

This leads to a conflict. You want to prevent the use of certain blocks but allow all others without listing every allowed block.

I have described above which way I use to achieve exactly that using `WP_Block_Type_Registry::get_instance()->get_all_registered()`.

First I let all registered blocks be listed in order to allow all and from this list I remove blocks that should not be allowed. And this is exactly where there is a issue with certain WooCommerce blocks. Since they are not registered in the init action.

It should be possible to get the same result disallowing WooCommerce blocks using `unregisterBlockType()` instead.

**Comment by Aljullu** [comment]
Thanks for providing more details, @CreativeDive! It's true the result of `WP_Block_Type_Registry::get_instance()->get_all_registered()` is different in the Page/Post editor than in other pages. But as you mentioned, that's expected, as [we don't want to make some blocks available in that context](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/BlockTypesController.php#L258-L274).

What I'm failing to understand is how that impacts your implementation. My understanding is that you are creating a block that can contain inner blocks and you want to add an "allow list" to it. Is that correct? In that case, you can rely on what you get from `WP_Block_Type_Registry::get_instance()->get_all_registered()` and filter the results from the returned object. The blocks which aren't listed there are likely not registered, so you don't need to unregister them.

Please, let me know if I'm missing something.

**Comment by CreativeDive** [comment]
@Aljullu Please look above at the javascript console warning from react. 

```
Previous: The not allowed WooCommerce blocks are not in the list
Incoming: The not allowed WooCommerce blocks are suddenly in the list
```

But why? I'll take a closer look. Something seems to be wrong here. At the moment I don't know why the WooCommerce blocks can suddenly be in the list of allowed blocks.

**Comment by Aljullu** [comment]
A couple of questions that could help identify what's going on:

1. What code are you running that is producing that warning?
2. In which screens do you see the warning? Is that the post/page editor or the Site Editor?

Thanks in advance!

**Comment by CreativeDive** [comment]
I've checked my code now and couldn't find a place where I add WooCommerce blocks that aren't allowed in certain post types to my allowed blocks.

I think I understand why this error can appear.

1. I output all registered blocks as an array from `WP_Block_Type_Registry::get_instance()->get_all_registered()`

2. I remove blocks from this array that shouldn't be allowed for inner bocks.

3. It would be possible that all the registered blocks are cached and the WooCommerce blocks are not present here because they are not registered in some cases: https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/BlockTypesController.php#L247-L260

5. Later in another post type where the WooCommerce blocks are allowed but no longer match the cached registered blocks.

6. Now this error occurs.

It is just a guess. I could not find any issue on my side.

I still think that using `unregisterBlockType()` on the WooCommerce side might fix this issue.

**Comment by Aljullu** [comment]
Thanks for following up, @CreativeDive!

Unfortunately, I'm not sure if I will be able to be of much help without more details. As far as I know, we don't cache the WC blocks list at any point, instead, it's generated on each page view. If that list appears to be cached, there might be something else going on, like a plugin or custom code interfering with the block type list generation.

If you have some more details of the issue or think we can be of any help, please let us know. Answering the two questions in [my previous message](https://github.com/woocommerce/woocommerce-blocks/issues/9050#issuecomment-1516218809) might be a good first step to diagnose what's going on.

Thanks in advance!

**Comment by CreativeDive** [comment]
I'll continue to monitor it and if I have new insights, I'll reopen the issue.
