### ISSUE TITLE
Create `Product features: icon grid` pattern

### ISSUE THREAD

**Issue by albarin** [woocommerce/woocommerce-gutenberg-products-block#9054]
![Icon grid](https://user-images.githubusercontent.com/186112/232024184-6d3da468-a5de-4ad5-afbf-3d39582f02cc.png)

Check Figma designs F5AAbRJOGbTeEweXPFtHgf-fi-1327_26020 for the latest updates and mobile views.

**Comment by roykho** [comment]
It is decided we don't work on this pattern because it is not really e-Commerce specific pattern. p1682018154807799/1681997277.805129-slack-C052DGZDC2C
