### ISSUE TITLE
No google pay

### ISSUE THREAD

**Issue by flaureli** [woocommerce/woocommerce-gutenberg-products-block#9078]
## What do you like about the Cart & Checkout blocks?

Your demo looks awesome.

## What do you think is missing from the Cart & Checkout blocks?

I have to remove google pay, i don't offer it.  How do I do that?

**Comment by flaureli** [comment]
I don't offer pickup, I don't offer google pay, I need to add custom instructions... none of this is apparently available????????

**Comment by flaureli** [comment]
I don't even know what Link is.  I use stripe.

**Comment by tarunvijwani** [comment]
@flaureli Thank you for reaching out. Could you please explain the issue in detail? Are you having difficulty disabling the express checkout?

**Comment by mikejolley** [comment]
Hi there

When creating issues please describe the issue you're facing, what environment you're running, and any steps you've already taken to resolve. 

In this case I think you're just asking about Google Pay specifically? Google Pay is not included with the Blocks, but may be added by a payment gateway such as Stripe. You can usually decide what Stripe shows in the settings: WooCommerce > Settings > Payments > Stripe. You should find it there and remove if if you're not interested. 

> I don't offer pickup

This again is optional. Remove all local pickup methods from WooCommerce > Settings > Shipping, and WooCommerce > Settings > Shipping > Local Pickup.

If you're seeing these options in the editor, it may just be a placeholder. Save the page and view the page on the frontend of the store to see what your customers will see when checking out.

I'll mark this issue closed but feel free to create a new issue if you spot any bugs. Thanks.
