### ISSUE TITLE
Woocommerce blocks archive/shop page

### ISSUE THREAD

**Issue by bramokki** [woocommerce/woocommerce-gutenberg-products-block#9085]
Hey with the new theme editor its possible to make archive pages (block based themes). I want to make an woocommerce archive/shop page with gutenberg.
But there is no option to show the products based on the current slug/category. Will this option be available in the future? 
And maybe an option to integrate theme styles for the products blocks.

**Comment by Aljullu** [comment]
Hi, @bramokki and thanks for your question! We are working on 'blockifying' the Product catalog templates (which include the Shop page, Products by Category/Tag/Attribute and the Product Search Results template). Our plan is to provide an easier 'upgrade' button similar to the one which is currently available in the Single Product template, so merchants can click on it and automatically be upgraded to the new blockified experience.

Right now, however, that button is not available yet as we are finishing some polishes of the Products block, which will be the block powering the product grid in those pages. I would suggest you to follow the Products block issue to keep track of the latest developments: https://github.com/woocommerce/woocommerce/issues/42616.

In the meanwhile, if you want to try how it's going to look, you can edit the templates of your store manually (via Appearance > Editor > Templates) and replace the `WooCommerce Product Grid Block` block with all other required blocks: Store Breadcrumbs, Archive Title, Store Notices, Product Results Count, Catalog Sorting and the Products block. Alternatively, you can copy and paste the [blockified template](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/templates/templates/blockified/archive-product.html) we are planning to make available soon.

Hope that helped! I will proceed closing this issue as there is nothing actionable right now. But feel free to answer if there is anything else you would like to discuss.
