### ISSUE TITLE
CC Avenue - The following extension is incompatible with the block-based checkout.

### ISSUE THREAD

**Issue by kaustubh57** [woocommerce/woocommerce-gutenberg-products-block#9088]
## Describe the bug
Payment Gateway (CC Avenue) not able to integrate with WooCommerce Block plugin.
Error: The following extension is incompatible with the block-based checkout. 

## To reproduce
1. Go to 'Settings -> WooCommerce -> Payment'
2. Enable 'CC Avenue' payment (attached the plugin)
3. Go go checkout page and try to enable the CC Avenue payment
4. See error - Error: The following extension is incompatible with the block-based checkout. 

## Expected behavior
Plugin should work with payment gateway.

## Screenshots
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/1927067/232819237-bc529247-3ec5-4c96-ae50-f05c23a3bc75.png">

### WordPress (please complete the following information):

-   WordPress version: 6.2
-   Gutenberg version (if installed): 15.4.0
-   WooCommerce version: 7.6.0
-   WooCommerce Blocks version: 10.0.1
-   Site language: Englisn
-   Any other plugins installed: CC Avenue

### Desktop (please complete the following information):

-   OS: macOS
-   Browser: Chrome
-   Version: 112.0

[ccavenue_woocommerce.zip](https://github.com/woocommerce/woocommerce-blocks/files/11263271/ccavenue_woocommerce.zip)
[InstallationGuide.pdf](https://github.com/woocommerce/woocommerce-blocks/files/11263273/InstallationGuide.pdf)

**Comment by tarunvijwani** [comment]
@kaustubh57 Thank you for reporting the incompatibility. It's up to extension developers to add support for the new checkout flow offered via the Cart and Checkout Blocks. We have opened a new ticket to track the reports for it. Closing this in favor of https://github.com/woocommerce/woocommerce/issues/42399
