### ISSUE TITLE
Resizing the browser window with a Product Image Gallery does not auto adjust width of the Gallery, overlapping content.

### ISSUE THREAD

**Issue by dalebridge** [woocommerce/woocommerce-gutenberg-products-block#9091]
## Describe the bug

There is a bug when resizing the browser that is affecting the Product Image Gallery size. On load, the product image gallery has a set width applied to the main image div. As the browser expands, the image increases in width, to a full sized page layout. When the page starts to shrink with two columns, the image does not reduce down in width and so the image overlaps the content to the right until it swaps back to stacked single column.

## To reproduce

On a single product page, reduce the width of the page so the gallery image columns are stacked and as it reduces down, the overlapping occurs. If you refresh the page in mobile view, and increase the width of the page, the images do get larger, but not smaller on resize in the desktop layout.

## Expected behavior

Would expect it to adjust dynamically to the page width adjustments and not need to be refreshed to view the correct size layout.

## Screenshots

<img width="841" alt="Screenshot 2023-04-19 at 03 15 11" src="https://user-images.githubusercontent.com/99664378/232949060-b5d5ab38-14b5-443d-8528-47f07bd0a6a8.png">

https://user-images.githubusercontent.com/99664378/232949779-7f94d05f-844f-4fe4-8117-9c44b3b04351.mp4

<img width="336" alt="Screenshot 2023-04-19 at 03 23 59" src="https://user-images.githubusercontent.com/99664378/232950250-3af8d35c-2f4d-4d77-88b0-1a1528613746.png">

### WordPress (please complete the following information):

WooCommerce 7.6.0
WP 6.2
WooCommerce Blocks 10.0.1

### Desktop (please complete the following information):

Mac OS using Arc desktop browser.

**Comment by Aljullu** [comment]
Thanks for opening this issue, @dalebridge! I was able to reproduce as well in Twenty Twenty Three:

![imatge](https://user-images.githubusercontent.com/3616980/233338986-8b360047-5741-4e75-8f04-82c1e67c7095.png)

@gigitux is that something that can be included into the Single Product epic?

**Comment by gigitux** [comment]
Sure! It could be related to issue #9000, but keep a dedicated issue for now.
