### ISSUE TITLE
Cart block shows strikethrough price if cart item price has been modified via woocommerce_cart_updated action

### ISSUE THREAD

**Issue by ninetyninew** [woocommerce/woocommerce-gutenberg-products-block#9099]
## Describe the bug

If you are using a plugin or custom development which updates cart item prices on the `woocommerce_cart_updated` action the price in cart blocks shows a strikethrough of the price before the change. In comparison to normal cart the price is not strikethrough.

## To reproduce

1. Setup 2 pages, one as the normal cart, one as a block based cart
2. Add this code to theme `functions.php`:

```
function cart_test() {

	$cart = WC()->cart;

	if ( !empty( $cart ) ) {

		if ( isset( $cart->cart_contents ) ) {

			if ( !empty( $cart->cart_contents ) ) {

				foreach ( $cart->cart_contents as $cart_content_key => $cart_content_value ) {

					$cart_content_value['data']->set_price( 50000 );

				}

			}

		}

	}

}
add_action( 'woocommerce_cart_updated', 'cart_test' );
```

3. View cart on both pages to see difference in price display

## Expected behavior

Price displays without strikethrough on cart blocks if price modified via woocommerce_cart_updated action or similar hooks.

## Screenshots

Non-block cart:

<img width="770" alt="image" src="https://user-images.githubusercontent.com/56840277/233050790-7d428422-220a-44e2-81dd-df5989f5d9cb.png">

Cart block:

<img width="487" alt="image" src="https://user-images.githubusercontent.com/56840277/233050699-da2fec60-b732-434e-8b83-525c49538ee1.png">

### WordPress (please complete the following information):

-   WordPress version: 6.2.0
-   Gutenberg version (if installed): N/A
-   WooCommerce version: 7.6.0
-   WooCommerce Blocks version: N/A
-   Site language: English

### Desktop (please complete the following information):

-   OS: Mac Os
-   Browser Chrome
-   Version: 111

**Comment by mikejolley** [comment]
Hi @ninetyninew. I'm not sure I would consider this a bug. Unlike the shortcode cart, the block based cart shows sale prices. This can be seen if you add an item on sale to the cart like so:

![Screenshot 2023-04-24 at 11 46 49](https://user-images.githubusercontent.com/90977/233974616-d82e1da5-6340-42f3-8f1d-e4bb84213c8d.png)

vs 

![Screenshot 2023-04-24 at 11 46 25](https://user-images.githubusercontent.com/90977/233974638-d8eb6b1f-b3fa-4f6e-956d-b345c9f61da1.png)

What your code is doing is setting the active price to 50,000. You're not touching the "regular" and "sale" price which is still 10. Therefore the previous price is striked and the active price is show. 

You'd see the same behaviour on product pages if you modified product prices dynamically in this fashion using the `$product->set_price()` method.

You can rectify this by using the `$product->set_regular_price()` and `$product->set_sale_price()` methods in addition.

Just to clarify:

- Regular price is the original price of the product.
- Sale price is the sale price you'd pay if purchased if the product is on sale (this may not be used if there are specific dates in which the product is on sale).
- Price holds either the sale price, or regular price, depending on what is active. 

Hope this clarifies things.

**Comment by ninetyninew** [comment]
@mikejolley Thanks for the info, I was aware of the differences between `_price`, `_regular_price` and `_sale_price`, I just didn't notice the issue before until we tried a cart block and saw the strikethrough, so assumed the cart block was conditioning it as a sale price somehow, even though sale price is empty. The info provided should be enough for us to go on to look into a fix for this issue on cart blocks in our specific scenario. 🙌

**Comment by mikejolley** [comment]
Excellent, I'll close this out.
