### ISSUE TITLE
Grid blocks: Crop grid images with CSS to be consistent height

### ISSUE THREAD

**Issue by claudiulodro** [woocommerce/woocommerce-gutenberg-products-block#91]
When previewing grid blocks in the editor, the image used is the full image not a cropped thumbnail. This leads to alignment issues when different aspect ratios are used:

<img width="819" alt="Screen Shot 2019-05-09 at 11 34 38 AM" src="https://user-images.githubusercontent.com/541093/57466391-896abc80-724e-11e9-83c8-a3b789c4616a.png">

To reproduce:

- Create products with different image sizes for the featured image
- Add those products to your post in any grid block (Newest Products, Handpicked, etc)
- Misaligned content 🙁

**Comment by mikejolley** [comment]
This issue is not longer present - the UI changed for handpicked products :)

**Comment by mikejolley** [comment]
Confirmed this has been fixed by https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/596
