### ISSUE TITLE
Filter by Attribute does not display attirbutes for imported XML products

### ISSUE THREAD

**Issue by kmanijak** [woocommerce/woocommerce-gutenberg-products-block#9108]
### Description
Under certain synthetic circumstances Filter by Attribute shows "There are no products with selected attributes":
![image](https://user-images.githubusercontent.com/20098064/233074007-34ce4ae6-ec2e-410f-9e00-43584809a3c2.png)

Filter by Attribute (and some other filters) have been updated recently in [this PR](https://github.com/woocommerce/woocommerce-blocks/pull/8599), but that wasn't released yet and is scheduled for 10.1.0 (April 24). That means it happens only on `trunk` since that PR was merged. If you visit this issue later, then this version might've been released already so the issue could be reproduced there.

### Steps to reproduce
1. Setup new env
2. Use [`woo-test-environment`](https://github.com/nielslange/woo-test-environment) which imports the products [here](https://github.com/nielslange/woo-test-environment/blob/trunk/command.php#L199)
3. Edit Product Catalog
4. Add Filter by Attribute and Products block
5. In Filter by Attribute choose some attribute (e.g. Color)
6. **Expected**: There are couple of colors options shown in a preview
7. **Actual**: There's a notice saying "There are no products with selected attributes"

### More details
This happens if products are imported through WP Importer (e.g. via [`woo-test-environment`](https://github.com/nielslange/woo-test-environment)) and `{prefix}_wc_product_attributes_lookup` is not correctly propagated. All works fine if products/attributes are added manually or imported manually as CSV.
It may require update in WC Core do ensure the method that populates the table is triggered after the data import.

**Comment by kmanijak** [comment]
There's issue in WC Core re that: https://github.com/woocommerce/woocommerce/issues/25698

**Comment by gigitux** [comment]
cc @nielslange This issue affects our E2E test env (playwright). Any thoughts about how to fix it?

We run the command to generate the table too:

```
wp-env run tests-cli "wp wc tool run regenerate_product_lookup_tables --user=1"
```
[(source code)](https://github.com/woocommerce/woocommerce-blocks/blob/159185ac89e32ea8ae2d05b19552626371848297/tests/e2e-pw/bin/test-env-setup.sh/#L55-L56)

**Comment by kmanijak** [comment]
Adding a bit more context:

When I encountered this issue, I made an attempt of switching to CSV in a fork [here](https://github.com/kmanijak/woo-test-environment/commit/b5d0ea98f36543974fe7f9700b1432dbcdf62106), as the lookup table population works fine when data is imported through WooCommerce importer (using CSV).

But then I found out WP importer supports only WXR (XML) files as per [docs](https://developer.wordpress.org/cli/commands/import/):
> Path to one or more valid WXR files for importing. Directories are also accepted.

Also, the regeneration of lookup tables takes a while to complete (ref: p1681913867082209/1681818021.792209-slack-C02FL3X7KR6)

**Comment by gigitux** [comment]
> Adding a bit more context:
> 
> When I encountered this issue, I made an attempt of switching to CSV in a fork [here](https://github.com/kmanijak/woo-test-environment/commit/b5d0ea98f36543974fe7f9700b1432dbcdf62106), as the lookup table population works fine when data is imported through WooCommerce importer (using CSV).
> 
> But then I found out WP importer supports only WXR (XML) files as per [docs](https://developer.wordpress.org/cli/commands/import/):
> 
> > Path to one or more valid WXR files for importing. Directories are also accepted.
> 

Same [here](https://github.com/gigitux/woo-test-environment/commit/f0ac400dae9761b0db051fd36a9b2af557e84f94) 😅

> Also, the regeneration of lookup tables takes a while to complete (ref: p1681913867082209/1681818021.792209-slack-C02FL3X7KR6)

Gotcha!

**Comment by nielslange** [comment]
> cc @nielslange This issue affects our E2E test env (playwright). Any thoughts about how to fix it?
> 
> We run the command to generate the table too:
> 
> ```
> wp-env run tests-cli "wp wc tool run regenerate_product_lookup_tables --user=1"
> ```
> 
> [(source code)](https://github.com/woocommerce/woocommerce-blocks/blob/159185ac89e32ea8ae2d05b19552626371848297/tests/e2e-pw/bin/test-env-setup.sh/#L55-L56)

Thanks for reaching out, @gigitux. I'll look into this issue.

**Comment by nielslange** [comment]
@gigitux I looked into this issue, but I'm unable to reproduce it. At [woo-test-environment](https://github.com/nielslange/woo-test-environment), we're also [adding attributes](https://github.com/woocommerce/woocommerce-blocks/blob/159185ac89e32ea8ae2d05b19552626371848297/tests/e2e-pw/bin/test-env-setup.sh#L25-L41), before [regenerating the product lookup table](https://github.com/woocommerce/woocommerce-blocks/blob/159185ac89e32ea8ae2d05b19552626371848297/tests/e2e-pw/bin/test-env-setup.sh#L55).

@kmanijak Besides the testing steps that you listed above, can you give me additional steps on how to reproduce this issue?  For example, on my end, I do not see the Product Template:

![Screen Shot 2023-04-21 at 18 31 14](https://user-images.githubusercontent.com/3323310/233625417-b3d9ed78-cedb-4052-97d4-9a8009e16f41.png)

**Comment by kmanijak** [comment]
> @kmanijak Besides the testing steps that you listed above, can you give me additional steps on how to reproduce this issue? For example, on my end, I do not see the Product Template:

Apologies @nielslange, I meant Product Catalog not Product Template 🤦 I updated testing steps

**Comment by nielslange** [comment]
No problem, @kmanijak. I've just looked closer into this issue, but I'm still unable to see the problem. Here's what I did:

1. Create a fresh WordPress site.
2. Set up a test environment using https://github.com/nielslange/woo-test-environment
3. Ensure that the Twenty Twenty-Three theme is activated.
4. Open the `Product Catalog` template.
5. Remove the current block and add the `Filter by Attribute` and the `Products (beta)` blocks.
6. Look up the `Product Catalog` template via `/shop/classic-shop`.

Here's what I see on my end:

<table>
<tr>
<td valign="top" width="50%">Post editor:
<br><br>

<img width="1437" alt="Screen Shot 2023-04-21 at 19 01 22" src="https://user-images.githubusercontent.com/3323310/233630461-3ba50e81-34d8-428d-8fbd-7dd7c330b395.png">

</td>
<td valign="top" width="50%">Frontend:
<br><br>

<img width="720" alt="Screen Shot 2023-04-21 at 19 01 53" src="https://user-images.githubusercontent.com/3323310/233630568-81aba0ae-e0ae-4850-9cf5-690bc801255c.png">

</td>
</tr>
</table>

Could you try running the following command in your terminal:
```sh
wp woo-test-environment teardown && wp woo-test-environment setup --blocks
```
This tears down the current environment and sets it up again. Maybe the good old _"have you tried turning it off an on?"_ also helps in this case. 🤔

**Comment by kmanijak** [comment]
I see why is that and again this is actually a missing information in Steps to Reproduce, which I took for granted. 

The whole thing is because the Filter by Attribute (and some other filters) have been updated recently in [this PR](https://github.com/woocommerce/woocommerce-blocks/pull/8599), but that wasn't released yet and is scheduled for 10.1.0. That means it happens only on `trunk` since that PR was merged.

If I'm not mistaken, we can use any of the ZIP files from the PRs that were merged later 🤔 
E.g. [this PR](https://github.com/woocommerce/woocommerce-blocks/pull/9142) and here's a [ZIP file](https://wcblocks.wpcomstaging.com/wp-content/uploads/woocommerce-gutenberg-products-block-9142.zip)

_(TIL a lot about how to write better testing steps and describe issues better. Sorry for the trouble and I'm updating the issue description again 🙇 )._

**Comment by nefeline** [comment]
@gigitux regarding:

> This issue affects our E2E test env (playwright). Any thoughts about how to fix it?

While I don't have all the details regarding your issue on Playwright, I suspect it might be the same we had with our current infrastructure: the tests were also failing on Puppeteer, as the process for creating and populating the new product meta-lookup table is deferred (triggered via a scheduled action) out-of-the-box: we managed to fix this limitation by enabling direct updates:

<img width="868" alt="Screenshot 2023-04-27 at 10 33 55" src="https://user-images.githubusercontent.com/15730971/234808037-0d989c1f-b902-4cb2-9ae5-88490eb9a120.png">

See @albarin's PR:

https://github.com/woocommerce/woocommerce-blocks/pull/9029/files

**Comment by gigitux** [comment]
@nefeline Thanks for point the PR! I will check it and implement it in Playwright too! 🙇
