### ISSUE TITLE
Creating accounts with Cart-Token returns fatal

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#9116]
When you checkout using Cart-Token and `create_customer: true` the server would throw a fatal, an account would have been created with that email but the order won't be linked to it.

The error is:

```
Fatal error:  Uncaught Error: Call to undefined method Automattic\WooCommerce\StoreApi\SessionHandler::init_session_cookie() 
```

This is because Checkout calls `wc_set_customer_auth_cookie` which depends on `init_session_cookie` in the classic session handler.

**Comment by RickGeersing** [comment]
Having the same issue

**Comment by matthijs166** [comment]
We got the same issue!

**Comment by wavvves** [comment]
[Related](https://github.com/woocommerce/woocommerce-blocks/pull/5953#issuecomment-1551198659)

**Comment by grig-23** [comment]
6558007-zen
