### ISSUE TITLE
Notice Banners don't account for wc-forward anchors

### ISSUE THREAD

**Issue by ralucaStan** [woocommerce/woocommerce-gutenberg-products-block#9134]
## Describe the bug

3PD can add a `wc-forward` button/anchor inside the notice; the default styling expects that this button has the `wp-element-button` class.

We don't account for these links in the new design 
![Screenshot 2023-04-20 at 11 38 15 AM](https://user-images.githubusercontent.com/1628454/233332520-14c6b165-38bc-4530-a4fe-d7070a7bcce1.png)

In the WC old style the link would stay on the right
![Screenshot 2023-04-20 at 11 48 29 AM](https://user-images.githubusercontent.com/1628454/233332544-a9466242-7616-43d0-bc14-d7522368f618.png)

## To reproduce

1. Install Back in Stock Notifications
2. Visit an out-of-stock product
3. Click the “Notify me” button.

## Expected behavior

**Later edit:** pdFofs-11n-p2
**Snackbar**
<img width="520" alt="Screenshot 2023-06-20 at 10 31 25" src="https://github.com/woocommerce/woocommerce-blocks/assets/1628454/f011d729-2bda-44e4-b250-95829d838aac">
**Notice banner**
<img width="516" alt="Screenshot 2023-06-20 at 10 31 19" src="https://github.com/woocommerce/woocommerce-blocks/assets/1628454/9c12e523-0e52-4d92-b221-25a61c3c59e6">

-----

We need to define how the links should appear, considering that we also have the dismiss notification button, the text width, and the mobile experience. cc @elizaan36  

Internal discussion p1681980014544799-slack-C8X6Q7XQU

**Comment by elizaan36** [comment]
hey @ralucaStan Sorry, this may have been a miss on my part but the success notice isn't meant to appear as the top level notice. In the Figma and design posts, the success message only appears as a snackbar.

That being said, we still need to solve for the link/button in the notices. Here are mockups and I'll leave it to @mikejolley @shaunandrews and yourself for feedback and next steps on this.

**Link placement for notice**
<img width="482" alt="Screen Shot 2023-04-20 at 11 08 49 AM" src="https://user-images.githubusercontent.com/5121465/233711971-f10d6c27-32a0-4bee-9521-d022a81143a7.png">

**Link placement for snackbar**
<img width="474" alt="Screen Shot 2023-04-20 at 11 08 42 AM" src="https://user-images.githubusercontent.com/5121465/233711995-53a59023-e30f-4292-954a-56b9883043b7.png">

**Comment by ralucaStan** [comment]
@elizaan36  The design looks good to me, do we have a Figma for this with hover states and everything?

**Comment by elizaan36** [comment]
So far we have this [updated board in Figma](https://www.figma.com/file/hqyJB5F38BOXTrOyxehUZH/%5BWIP%5D-WooCommerce-Store-Editing-Library?node-id=2077%3A4323&t=Kb0uNnBzp9gVg7GJ-1), but we'll share more detailed usage guidelines soon.

**Comment by ralucaStan** [comment]
@pmcpinto should we work on this in the upcoming cycle?

**Comment by pmcpinto** [comment]
Yes. Thanks

**Comment by elizaan36** [comment]
I'll share the updated designs and usage guidelines on p2 in the coming days.

**Comment by ralucaStan** [comment]
related https://github.com/woocommerce/woocommerce-blocks/issues/9609

**Comment by ralucaStan** [comment]
@elizaan36 Just to confirm, is this the final design we are going with for the banner? From pdFofs-11n-p2 

Thank you so much!

<img width="429" alt="Screenshot 2023-06-16 at 15 37 47" src="https://github.com/woocommerce/woocommerce-blocks/assets/1628454/0cde8967-3c9d-40c6-acd9-ce0c08277a69">

**Comment by elizaan36** [comment]
Yup that's the latest! Should have updated this issue, thanks.

**Comment by ralucaStan** [comment]
closed via #9996
