### ISSUE TITLE
"Best selling products" block returns the "lastest products"

### ISSUE THREAD

**Issue by jobthomas** [woocommerce/woocommerce-gutenberg-products-block#915]
**Describe the bug**

When adding a "best selling products" block it returns the latest products.

**To Reproduce**

* Create a best selling and a new products block
* Both render the same products

Compared both on TwentyNineteen and SF and happening with both themes.

Tested with latest version of WC and WP. 

https://sales.local/shop/?orderby=date: 
![](https://cld.wthms.co/1PGdi0+)
Link to image here: https://cld.wthms.co/1PGdi0.

https://sales.local/shop/?orderby=popularity:
![](https://cld.wthms.co/VrTIIM+)
Link to image here: https://cld.wthms.co/VrTIIM.

When adding blocks: 
![](https://cld.wthms.co/jOX9p6+)
Link to image here: https://cld.wthms.co/jOX9p6.

Reported by @daveloodts

Experienced on https://www.despelvogel.com/product-categorie/alle-spellen/?orderby=popularity (and happening there as well)

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/917
