### ISSUE TITLE
Cart & Checkout templates

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-gutenberg-products-block#9153]
**Description:** we aim to move forward with implementing the Cart & Checkout templates, as we’ll be able to offer a distraction-free experience by default and more control over the cart and checkout.

**Acceptance criteria:**
- [x] We should keep the site header and footer for the Cart template.
- [x] We should start offering a distraction-free experience right from the first iteration of the Checkout template. This means removing the footer and offering a simplified header version (with just the logo and back button) or no header. [needs design input]
- [x] Brand-new users with a block-based theme should access the cart & checkout templates from the Templates section in the editor.
- [x] ~We don't automatically upgrade existing users with a block-based theme to the templates. They should access the cart & checkout blocks through the pages. We can use two complementary methods to nudge the users to transition to the templates:~
   - ~Include a message when they visit the cart or checkout page showcasing the benefits of having them as templates and with a mechanism to enable the template and disable the page. This should be done separately for the cart and checkout, as some users may not use both blocks. The user should be re-directed to the template after enabling it.  [needs design input]~
   - ~Trigger an Inbox notification informing the users about the new experience. The notification redirects the user to the cart or checkout page, where he can transition to the template, as mentioned above. [needs design input]~
   - Replaced with an upgrade routine (page contents -> block template)
- [x] Classic theme users with the cart & checkout blocks will keep using them for now.
- [x] When the user has the templates enabled and goes to WooCommerce - Settings - Advanced - Page Setup, the cart and checkout pages dropdowns are empty. We show a message informing him that the cart and checkout are templates, with a link to each template. The message should also notify the user that he can select a different route to the cart and checkout through the dropdowns. An alternative is to modify this settings section and allow users to edit the permalink structure as suggested here: pdToLP-la-p2#comment-232 [needs design input]
- [ ] The templates' discoverability will be addressed separately, as it will require collaboration with other teams.

**Event tracking:**
It will be defined as we refine the acceptance criteria

**Comment by nerrad** [comment]
> We don't automatically upgrade existing users with a block-based theme to the templates. They should access the cart & checkout blocks through the pages. 

I may be wrong, but on the surface, the logic/code involved with this could end up being pretty fragile (and cover a large surface area). I wonder if instead we _do_ upgrade these users/stores but notify them about the change? Under the hood, we should be able to retain the content of the existing cart/checkout page by copying over to the template (including leaving header/footer in place for these users).

**Comment by wavvves** [comment]
> > We don't automatically upgrade existing users with a block-based theme to the templates. They should access the cart & checkout blocks through the pages.
> 
> I may be wrong, but on the surface, the logic/code involved with this could end up being pretty fragile (and cover a large surface area). I wonder if, instead we _do_ upgrade these users/stores but notify them about the change? Under the hood, we should be able to retain the content of the existing cart/checkout page by copying over to the template (including leaving header/footer in place for these users).

I had a call with @gigitux a while back, where we briefly discussed this. Having the templates starting point *.html files is way too detached from the blocks, and it poses a lot of problems, e.g.:

*  New stuff/changes being added to the block (ex: cross-sells) that might be forgotten to update on the *.html file
* Heavily modified blocks will mean the user might be reluctant to use and update the templates

@mikejolley and I discussed this, which resulted in [this issue](https://github.com/woocommerce/woocommerce-blocks/issues/9334) being created:

> _Seeing if we can populate the default template with the contents of the existing page so existing content is preserved_
> _Redirect the edit page link to the template editor_
> _See if we can drop the existing page in favor of endpoints or something similar

So we would be upgrading users to templates, but the starting point would be where they left off exactly before enabling a new blocks theme.
They might not know editing templates lives elsewhere, but going the old known route would have them land in the right place, introducing them to the editor.
We also plan to take a jab on the permalink question. We want to pack this in a solution that would be intuitive for the user instead of spamming him with notices. 
Let's see how easy to discover, use and understand we can make this first. From there, we can tie loose ends.

**Comment by nerrad** [comment]
> Having the templates starting point *.html files is way too detached from the blocks, and it poses a lot of problems, e.g.:

I'd caution against diverging significantly from the WP core architecture around templates. The primary advantage of the starting point for templates being as they are is it enables the ability for themes to override what is provided by core as the starting point when a theme is activated. 

So any work you are doing on upgrading _existing stores_ as opposed to _new stores_ could be an additional override state.

Here's a rough diagram illustrating the upgrade heuristic I'm thinking of.

![image](https://user-images.githubusercontent.com/1429108/236802745-ee0ab9ef-c325-4a69-8c09-1853a2182388.png)


To the latter point around whether we notify the user or not, after the changes are done, I think we should do a survey of various checkout addons/extensions (including any pagebuilders that offer customization of the checkout) to see how they behave with migrated content. Results will either impact what we _don't_ migrate, and/or we notify the user.

**Comment by nerrad** [comment]
actually I need to modify the above a bit. Hang on am editing.

**Comment by nerrad** [comment]
One thing I just realized with the upgrade path is that early on, it's unlikely the block theme will have a `.html` template defined. However, after some time is passed the likelihood increases a bit.

**Comment by pmcpinto** [comment]
>  I think we should do a survey of various checkout addons/extensions (including any pagebuilders that offer customization of the checkout) to see how they behave with migrated content.

This is key. There's a significant % of stores using page builders, it's important to ensure we don't break their checkout flows.
