### ISSUE TITLE
Order confirmation template

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-gutenberg-products-block#9165]
**Description:** Besides providing details about tracking information or delivery times, the Order Confirmation page can increase customer satisfaction and revenue through cross-selling actions and more. A template will be the first step to allow merchants to easily visualize and customize an essential part of the shopping experience.

**Acceptance criteria:**
- [x] Implement the template with a placeholder block to render the current PHP template. The placeholder should be similar to what we have in templates, like the single product. [needs design input]
- [x] We should keep the site header and footer for the Order Confirmation template. [needs design input]
- [x] If the user has a classic theme, we render the current Order Received route.
- [x] We render the new template if the user (new or existing) has a block-based theme.
- [ ] We should evaluate whether it makes sense to inform existing users about the existence of the new template
- [x] The implementation should have full compatibility with existing extensions.
- [x] We should explore if the FSE template should be placed at the bottom of the hierarchy to avoid conflict with existing extensions.
- [x] The template should be removed from the list when a different template overrides it.
- [x] The permalink configuration in Settings - Advanced - Page Setup should be aligned with the Cart and Checkout (#9153) to ensure a cohesive experience. 
- [x] The "Pay for order" flow is out of scope.

**Event tracking:**
It will be defined as we refine the acceptance criteria.

**Comment by wavvves** [comment]
> The template should be removed from the list when a different template overrides it.

@pmcpinto I need some help understanding this entry, this comes directly under the previous point?
An example would be an extension that implements Order Received templates in a complex way (eg, having different templates depending on order contents like [Custom Thank You Pages](https://href.li/?https://woocommerce.com/document/woocommerce-custom-thank-you-pages/) does). 

We can possibly understand that if a merchant is using an extension that alters the order received page, then there's a low chance of being interested in editing and using our template. This would mean having our template further down in the loading order hierarchy and removing it from the template list to avoid confusion by giving the option to edit something that won't be used. Is this the case you are trying to illustrate?

Another thing, that case will probably have the same impact on a possible permalink option, that would be present but without actual usage.

**Comment by pmcpinto** [comment]
Hey Paulo, thanks for reaching out.

> We can possibly understand that if a merchant is using an extension that alters the order received page, then there's a low chance of being interested in editing and using our template. This would mean having our template further down in the loading order hierarchy and removing it from the template list to avoid confusion by giving the option to edit something that won't be used. Is this the case you are trying to illustrate?

Yes. This item in the AC was mainly based on the discussion that took place on the P2 about the order confirmation spike.

Feel free to edit the acceptance criteria to make it clearer. Thanks
