### ISSUE TITLE
The Playwright Tests Job is Failing

### ISSUE THREAD

**Issue by danielwrobert** [woocommerce/woocommerce-gutenberg-products-block#9170]
The Playwright Tests job seems to be consistently failing. Tried re-running the failed test multiple times with no luck.

See an example [here](https://github.com/woocommerce/woocommerce-blocks/actions/runs/4767986461). More examples can be viewed in [the list of jobs](https://github.com/woocommerce/woocommerce-blocks/actions/workflows/playwright.yml).

```
Playwright E2E tests
Process completed with exit code 1.
```

Requires investigation and fixing.

**Comment by nerrad** [comment]
@danielwrobert is this still relevant?

**Comment by danielwrobert** [comment]
@nerrad No, this seems to be resolved now. Closing out the issue, thanks!
