### ISSUE TITLE
Mini-Cart Block: Hide badge count when empty

### ISSUE THREAD

**Issue by shaunandrews** [woocommerce/woocommerce-gutenberg-products-block#9185]
<img width="52" alt="CleanShot 2023-04-24 at 12 05 26@2x" src="https://user-images.githubusercontent.com/191598/234053370-efaa96ff-1625-4805-8e7f-af6f018beb81.png">

When the cart is empty, the Mini-Cart block continues to show a badge with a count of '0'. It's pretty strange to see, and obscures the shape of the cart icon, making it hard to recognize.

Can we hide the badge when the cart is empty?

<img width="385" alt="CleanShot 2023-04-24 at 12 07 50@2x" src="https://user-images.githubusercontent.com/191598/234053941-33a51a3e-f491-4fb3-aa33-62e9294235ee.png">

**Comment by Aljullu** [comment]
@shaunandrews I will need your help with the icons. These are the ones I'm working with:

![icon-2](https://user-images.githubusercontent.com/3616980/234841233-31b16216-759b-4dcb-abbc-13645eb91e9f.svg)
![icon-1](https://user-images.githubusercontent.com/3616980/234841238-a9d41e5c-17a8-4382-9820-a4fa856ff23a.svg)

Even though they are very similar, one is slightly smaller, causing a visual jump when switching from one to the other:

[Enregistrament de pantalla des de 2023-04-27 12-52-08.webm](https://user-images.githubusercontent.com/3616980/234841492-ef8cccee-1ce2-4eaa-99da-fd737d3fa9ef.webm)

Do you think it would be possible to provide those two icons with the same sizing but one with the "badge space" removed?

**Comment by shaunandrews** [comment]
I think it would be better to use one icon, and then make the badge an HTML element with a background and border. This element would then be positioned above the icon to create the overlapping effect.

**Comment by Aljullu** [comment]
@shaunandrews one question regarding that. My understanding is that the plan is to switch to the new badge style:

<img width="1300" alt="cleanshot-2023-04-27-at-15 21 59402x" src="https://user-images.githubusercontent.com/3616980/236816508-c4db71ff-b010-4396-b1b0-9e28c7ab55f5.png">

Should we do the change in the Checkout block sidebar as well? Currently both badges share the same styling:

![imatge](https://user-images.githubusercontent.com/3616980/236816479-0f96895b-0a1b-49f8-a2f9-f16837289d57.png)

**Comment by shaunandrews** [comment]
Its probably fine to match, though I imagine we'll want to change the checkout block sidebar — that badge count isn't very obvious in that context, and really breaks the visual balance.

**Comment by Aljullu** [comment]
> Its probably fine to match, though I imagine we'll want to change the checkout block sidebar — that badge count isn't very obvious in that context, and really breaks the visual balance.

Ok, thanks! I will leave it as-is for now until the Checkout sidebar is worked on specifically. Regarding the Mini Cart badge, PR is ready: https://github.com/woocommerce/woocommerce-blocks/pull/9259. :slightly_smiling_face:
