### ISSUE TITLE
Can't change the `Mini Cart` width when the width is wider than the content

### ISSUE THREAD

**Issue by albarin** [woocommerce/woocommerce-gutenberg-products-block#9197]
## Describe the bug

In the `Editor`, when changing the width to a wider width than content, the change is not applied.

## To reproduce

1. Go to the `Editor`, open the `Header template`, and insert the `Mini Cart` block.
2. Go to the `Editor` > `Template parts` and open the `Mini Cart` template.
3. Open the `List View` and click on the `Mini Cart Contents` block.
4. On the settings sidebar change the `Dimensions` to a wider size (like `900`) and save.
5. Notice that the change is applied in the frontend but not in the `Editor`.

## Expected behavior

The width change should be applied also in the editor.

**Comment by Aljullu** [comment]
Good catch, @albarin! I think this can be fixed with https://github.com/woocommerce/woocommerce-blocks/pull/9201.
