### ISSUE TITLE
Inconsistent `Place Order` button placement

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#9205]
## Describe the bug

When a merchant hides the `Return to Cart` link within the Checkout block, the `Place Order` button is right-aligned within the post editor, but left-aligned in the frontend. This issue was reported by @kmanijak in p1682408862016089/1682354698.473329-slack-C02UBB1EPEF.

## To reproduce

1. Create a test page and add the Checkout block.
2. Open the `Document Overview`.
3. Go to `Checkout » Checkout Fields » Actions`.
<img width="1433" alt="Screen Shot 2023-04-26 at 09 01 52" src="https://user-images.githubusercontent.com/3323310/234446949-851db2ef-b3ce-46e0-8ab2-491f322d63a6.png">

4. Uncheck the checkbox `Show a "Return to Cart" link`.
<img width="1436" alt="Screen Shot 2023-04-26 at 08 51 21" src="https://user-images.githubusercontent.com/3323310/234445755-e80f9a99-fd6e-412f-9cb7-4d2909d4f144.png">

5. Save the test page.
6. Verify that the `Place Order` button is right-aligned.
7. Go to the frontend and add a product to the cart.
8. Go to the test page with the Checkout block.
9. See that the `Place Order` button is left aligned.

## Expected behavior

The `Place Order` button should be right-aligned or visible in full-width.

@elizaan36 What are your thoughts regarding right-aligned or full-width `Place Order` button? If the button should be full-width, I believe we should also reflect that in the post editor. Thinking out loud here, do you think it would make sense to allow merchants to define if the `Place Order` button should be visible right-aligned or full-width if the `Return to Cart` link is not visible?

## Screenshots

<table>
<tr>
<td valign="top">

`Place Order` button when the `Return to Cart` link is visible:

<img width="805" alt="Screen Shot 2023-04-26 at 09 04 13" src="https://user-images.githubusercontent.com/3323310/234447307-4dceb8a0-47f7-413c-a5fe-c6b7f10374a0.png">
</td>
<td valign="top">

`Place Order` button when the `Return to Cart` link is not visible:

<img width="816" alt="Screen Shot 2023-04-26 at 08 59 50" src="https://user-images.githubusercontent.com/3323310/234446663-6ab8278a-b6d5-40fb-8301-a469ec9b76d4.png">
</td>
</tr>
</table>

**Comment by elizaan36** [comment]
> @elizaan36 What are your thoughts regarding right-aligned or full-width Place Order button? If the button should be full-width, I believe we should also reflect that in the post editor. Thinking out loud here, do you think it would make sense to allow merchants to define if the Place Order button should be visible right-aligned or full-width if the Return to Cart link is not visible?

Great question. I'd default to full width when the "Return to cart" link is hidden. @shaunandrews What do you think?

**Comment by pmcpinto** [comment]
> Great question. I'd default to full width when the "Return to cart" link is hidden.

+1 on using full width
