### ISSUE TITLE
Audit: Returns and Warranty Requests

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#9216]
## Returns and Warranty Requests

- **Author:** WooCommerce
- **Website:** https://woocommerce.com/products/warranty-requests/
- **Repository:** (private) https://github.com/woocommerce/woocommerce-warranty

_This issue is to track compatibility testing between this extension and the Cart and Checkout blocks. [See the epic for the audit template](https://github.com/woocommerce/woocommerce-blocks/issues/9206) which should be completed and posted as a comment here once completed._

**Comment by opr** [comment]
# Extension Audit Template

## Functionality Review

This plugin enables warranty requests for products to be made by customers. It can add a warranty option to the product page which behaves just like a product option on variable products, or product addons.

From the my account page users can request warranty on completed orders if the setting is enabled.

Users can also fill in a form to request warranty.

This extension touches: *(mark all that apply)*

- [ ] Products (Beta)
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Add to cart button
- [x] Single Product Pages
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [x] Add to cart form
- [x] Cart Page
  - [x] Cart items
  - [ ] Product title
  - [ ] Product price
  - [x] Product meta
  - [ ] Product quantity
  - [ ] Cart totals
  - [ ] Notices
  - [ ] Custom functionality
- [x] Checkout Page
  - [ ] Checkout fields
  - [ ] Express checkout
  - [ ] Contact information
  - [ ] Shipping method
  - [ ] Pickup method
  - [ ] Shipping address
  - [ ] Billing address
  - [ ] Payment options
  - [ ] Checkout totals
  - [ ] Product title
  - [ ] Product price
  - [x] Product meta
  - [ ] Notices
  - [ ] Custom functionality
  - [ ] Order received page
- [x] My Account Page
- [ ] Store API
  - [ ] Edits existing endpoint
  - [ ] Adds custom endpoint
- [ ] Settings
  - [ ] WooCommerce settings
  - [ ] Custom settings page
  - [ ] Customizer 

## Compatibility with Blocks

Currently this works fine with Blocks, however when we get to blockifying the My Account area, we should be sure the request warranty button still shows up like so
<img width="723" alt="image" src="https://user-images.githubusercontent.com/5656702/234896414-a109bacb-1ff9-40b4-b446-0eae250e94fc.png">

I tested the warranty form with the Single Product block and Single product template, it appears in both.

| Single product template | Single product block |
| ------ | ----- |
| <img width="490" alt="image" src="https://user-images.githubusercontent.com/5656702/234896798-b6379f59-9050-4f47-a38f-2b3703a5bd6e.png"> | <img width="676" alt="image" src="https://user-images.githubusercontent.com/5656702/234896916-5869eb47-6400-4f98-a87c-cd4c55baad12.png"> | 


Issues identified:

None right now, but we need to ensure the button to request warranty appears in the My Account area when we convert it to use Blocks.

*Select those that apply:*

- [x] Extension is already fully compatible with Blocks
- [ ] Extension requires integration with Blocks
- [ ] Extension requires fixes in the blocks context
- [ ] Extension could be further enhanced to take advantage of Blocks

## Integration Required

This extension requires integration with: 

- [ ] Cart Block
- [ ] Checkout Block
- [ ] Payment Methods API
- [ ] Store API
- [x] Other

### Integration Points

| Location                                                                    | Type                                                                          | Description                                             | Effort |
| --------------------------------------------------------------------------- | ----------------------------------------------------------------------------- | ------------------------------------------------------- | :----: |
| My account | Client API | Ensure the button for warranty shows when changing the my account area to use blocks |  _3_   |
|                                                                             |                                                                               |
