### ISSUE TITLE
Audit: Jetpack

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#9223]
## Jetpack

- **Author:** Automattic
- **Website:** https://woocommerce.com/products/jetpack/
- **Repository:** (public) https://github.com/Automattic/jetpack

_This issue is to track compatibility testing between this extension and the Cart and Checkout blocks. [See the epic for the audit template](https://github.com/woocommerce/woocommerce-blocks/issues/9206) which should be completed and posted as a comment here once completed._

**Comment by opr** [comment]
# Extension Audit Template

## Functionality Review

This plugin enables several tools for security, performance, and growth.

It also offers individual plugins extra to Jetpack:

[Jetpack](https://wordpress.org/plugins/jetpack/) (security, performance, and growth tools)
[Jetpack Backup](https://wordpress.org/plugins/jetpack-backup/) (real-time backups and one-click restores)
[Jetpack Boost](https://wordpress.org/plugins/jetpack-boost/) (improve your site speed and SEO)
[Jetpack CRM](https://wordpress.org/plugins/zero-bs-crm/) (built for entrepreneurs and small businesses)
[Jetpack Protect](https://wordpress.org/plugins/jetpack-protect/) (stay one step ahead of security threats)
[Jetpack Search](https://wordpress.org/plugins/jetpack-search/) (help your visitors find what they need)
[Jetpack Social](https://wordpress.org/plugins/jetpack-social/) (write once, post everywhere)

This extension touches: *(mark all that apply)*

- [ ] Products (Beta)
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Add to cart button
- [ ] Single Product Pages
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Add to cart form
- [ ] Cart Page
  - [ ] Cart items
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Product quantity
  - [ ] Cart totals
  - [ ] Notices
  - [ ] Custom functionality
- [ ] Checkout Page
  - [ ] Checkout fields
  - [ ] Express checkout
  - [ ] Contact information
  - [ ] Shipping method
  - [ ] Pickup method
  - [ ] Shipping address
  - [ ] Billing address
  - [ ] Payment options
  - [ ] Checkout totals
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Product meta
  - [ ] Notices
  - [ ] Custom functionality
  - [ ] Order received page
- [ ] My Account Page
- [ ] Store API
  - [ ] Edits existing endpoint
  - [ ] Adds custom endpoint
- [ ] Settings
  - [ ] WooCommerce settings
  - [ ] Custom settings page
  - [ ] Customizer 

## Compatibility with Blocks

It does not appear that Jetpack affects any of the ecommerce functionality provided by WooCommerce.

Issues identified:
N/A

*Select those that apply:*

- [x] Extension is already fully compatible with Blocks
- [ ] Extension requires integration with Blocks
- [ ] Extension requires fixes in the blocks context
- [ ] Extension could be further enhanced to take advantage of Blocks

## Integration Required

N/A

This extension requires integration with: 

- [ ] Cart Block
- [ ] Checkout Block
- [ ] Payment Methods API
- [ ] Store API
- [ ] Other

### Integration Points

| Location                                                                    | Type                                                                          | Description                                             | Effort |
| --------------------------------------------------------------------------- | ----------------------------------------------------------------------------- | ------------------------------------------------------- | :----: |
| _Location of new integration point, or name of existing integration point._ | _Type e.g. client API, action or filter hook, component, or server side API._ | _Describe what the integration point will be used for._ |  _1_   |
|                                                                             |                                                                               |
