### ISSUE TITLE
Audit: Klarna Payments

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#9225]
## Klarna Payments

- **Author:** Krokedil
- **Website:** https://woocommerce.com/products/klarna-payments/
- **Repository:** (private) https://github.com/woocommerce/woocommerce-gateway-klarna

_This issue is to track compatibility testing between this extension and the Cart and Checkout blocks. [See the epic for the audit template](https://github.com/woocommerce/woocommerce-blocks/issues/9206) which should be completed and posted as a comment here once completed._

**Comment by nielslange** [comment]
Tried to audit this extension, but we don't have a company account and Klarna requires verifying the account creation with a local phone number. As I don't have a cell phone number of the supported locations, I could not create a testing account.

**Comment by opr** [comment]
# Extension Audit Template

## Functionality Review

This extension allows customers to pay for their order in installments via the Klarna buy-now-pay-later service.

This extension touches: *(mark all that apply)*

- [ ] Products (Beta)
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Add to cart button
- [ ] Single Product Pages
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Add to cart form
- [ ] Cart Page
  - [ ] Cart items
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Product quantity
  - [ ] Cart totals
  - [ ] Notices
  - [ ] Custom functionality
- [x] Checkout Page
  - [ ] Checkout fields
  - [ ] Express checkout
  - [ ] Contact information
  - [ ] Shipping method
  - [ ] Pickup method
  - [ ] Shipping address
  - [ ] Billing address
  - [x] Payment options
  - [ ] Checkout totals
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Product meta
  - [ ] Notices
  - [ ] Custom functionality
  - [ ] Order received page
- [ ] My Account Page
- [ ] Store API
  - [ ] Edits existing endpoint
  - [ ] Adds custom endpoint
- [ ] Settings
  - [ ] WooCommerce settings
  - [ ] Custom settings page
  - [ ] Customizer 

## Compatibility with Blocks

Recently the Klarna Payments extensions added support for the WooCommerce Blocks. We can successfully checkout using this payment gateway. But, it simply shows an entry with the Klarna logo and its name in the payment options section of the checkout block, and it does not have any further information about what this method is or how it works.

The shortcode version offers two options - pay in 30 days or three interest-free installments, whereas the Checkout block lists "Klarna".

The shortcode version shows a small panel when the method is selected; however, this does not appear on the block.

<img width="460" alt="image" src="https://user-images.githubusercontent.com/5656702/235420975-29b1bf5e-8e18-4dc0-8f9a-c26c59c1b7cd.png">

This panel contains a link, `Learn more about your payment options` which opens a modal explaining what Klarna is. This does not happen in the Checkout block.


Issues identified:

- [ ] Extension is already fully compatible with Blocks
- [ ] Extension requires integration with Blocks
- [x] Extension requires fixes in the blocks context
- [ ] Extension could be further enhanced to take advantage of Blocks

## Integration Required

The payment method needs to be correctly registered in the blocks' context.

This extension requires integration with: 

- [ ] Cart Block
- [x] Checkout Block
- [ ] Payment Methods API
- [ ] Store API
- [ ] Other

### Integration Points

| Location                                                                    | Type                                                                          | Description                                             | Effort |
| --------------------------------------------------------------------------- | ----------------------------------------------------------------------------- | ------------------------------------------------------- | :----: |
| Checkout block client | Registering the payment method with the block | Ensure the `content` property of the method contains the correct information, and the components required to load the modal also work correctly.  |  _unknown_   |
|                                                                             |                                                                               |

**Comment by tarhi-saad** [comment]
Hi @opr! The [Klarna Payments for WooCommerce](https://woocommerce.com/products/klarna-payments/) is compatible with the Cart & Checkout Blocks. 

<img width="649" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/14235870/d3bf5f30-bcb8-46fb-94fd-cb9f7d650ebc">

You can follow the instructions in this [Klarna docs](https://docs.klarna.com/platform-solutions/woocommerce/klarna-checkout/configuring-klarna-checkout-on-woocommerce/) to set it up with WooCommerce, and it should work as expected!

**Comment by opr** [comment]
Hey @tarhi-saad - thanks did you test this out too and get different results from what I got?

**Comment by tarhi-saad** [comment]
@opr, I tested the Klarna payments, and I was able to successfully complete my checkout (see recording below):

https://github.com/woocommerce/woocommerce-blocks/assets/14235870/25050a8c-bc2f-4b69-b6a8-c3ca4086ab3d

**Comment by opr** [comment]
@tarhi-saad ok thank you for the recording, would you be able to update my reply to this PR to indicate that it's successfully integrated? I would super appreciate it if you could!
