### ISSUE TITLE
Audit: PayPal Payments

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#9228]
## PayPal Payments

- **Author:** WooCommerce
- **Website:** https://woocommerce.com/products/woocommerce-paypal-payments/
- **Repository:** (public) https://github.com/woocommerce/woocommerce-paypal-payments

_This issue is to track compatibility testing between this extension and the Cart and Checkout blocks. [See the epic for the audit template](https://github.com/woocommerce/woocommerce-blocks/issues/9206) which should be completed and posted as a comment here once completed._

**Comment by nielslange** [comment]
WIP and status update: pdOdsj-7N-p2#comment-369

**Comment by ralucaStan** [comment]
I think this can be closed as we won't need to do an audit for the extension
