### ISSUE TITLE
Audit: Razorpay for WooCommerce

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#9230]
## Razorpay for WooCommerce

- **Author:** Razorpay
- **Website:** https://woocommerce.com/products/razorpay-for-woocommerce/
- **Repository:** n/a

_This issue is to track compatibility testing between this extension and the Cart and Checkout blocks. [See the epic for the audit template](https://github.com/woocommerce/woocommerce-blocks/issues/9206) which should be completed and posted as a comment here once completed._

**Comment by tarhi-saad** [comment]
We should create a Razorpay account to test this payment gateway. But, the onboarding is temporarily paused:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/14235870/236758577-61dd072f-be8a-499e-8629-32d5ac67dd5a.png">

### The Classic Checkout (The Shortcode version)

If we test this plugin being unauthenticated, we can see a new payment option in the **classic Checkout**:

<img width="462" alt="image" src="https://user-images.githubusercontent.com/14235870/236759271-3901e176-1513-4b7a-a6d8-7057a432e6fe.png">

But if we place an order with it, we get the `‘Authentication failed’` error:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/14235870/236759808-d3fa3d2b-0c2b-475a-b041-bd4fc7690b60.png">

### The Checkout Block

If we go to the Checkout Block, we will notice that the Razorpay payment gateway isn't available under the Payment options section:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/14235870/236760535-6fcf03c0-adb3-4f57-b0fa-4ca76917c5ec.png">

Although our Razorpay test was done while we were unauthenticated, we can assume this payment gateway isn't compatible with the Checkout Block based on the previous observations (i.e., the absence of the Razorpay payment option from the list of available payments).

A more conclusive test can be done later when the Razorpay payment gateway resumes onboarding!

@nielslange, should we close this issue or wait until we test the plugin while logged in?

**Comment by nielslange** [comment]
Thanks for reaching out, @tarhi-saad. I just replied to this question in p1683533651814859-slack-C8X6Q7XQU.

**Comment by tarhi-saad** [comment]
# Extension Audit Template

## Functionality Review

> The [Razorpay for WooCommerce](https://woocommerce.com/products/razorpay-for-woocommerce/) Accept Payments through your WooCommerce store with Razorpay. The easiest integration, online onboarding, and best in class performance.

This extension touches: *(mark all that apply)*

- [ ] Products (Beta)
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Add to cart button
- [ ] Single Product Pages
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Add to cart form
- [ ] Cart Page
  - [ ] Cart items
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Product quantity
  - [ ] Cart totals
  - [ ] Notices
  - [ ] Custom functionality
- [x] Checkout Page
  - [ ] Checkout fields
  - [ ] Express checkout
  - [ ] Contact information
  - [ ] Shipping method
  - [ ] Pickup method
  - [ ] Shipping address
  - [ ] Billing address
  - [x] Payment options
  - [ ] Checkout totals
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Product meta
  - [ ] Notices
  - [ ] Custom functionality
  - [ ] Order received page
- [ ] My Account Page
- [ ] Store API
  - [ ] Edits existing endpoint
  - [ ] Adds custom endpoint
- [ ] Settings
  - [ ] WooCommerce settings
  - [ ] Custom settings page
  - [ ] Customizer 

## Compatibility with Blocks

Currently, this extension is not compatible with WooCommerce blocks. It isn't displayed under the available payment gateways in the Checkout Block.

 This implies there wasn't any [integration done for the Checkout Block](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/checkout-payment-methods/payment-method-integration.md).

Issues identified:

- [ ] Extension is already fully compatible with Blocks
- [x] Extension requires integration with Blocks
- [ ] Extension requires fixes in the blocks context
- [ ] Extension could be further enhanced to take advantage of Blocks

## Integration Required

This extension requires integration with: 

- [ ] Cart Block
- [x] Checkout Block
- [x] Payment Methods API
- [x] Store API
- [ ] Other

### Integration Points

| Location                                                                    | Type                                                                          | Description                                             | Effort |
| --------------------------------------------------------------------------- | ----------------------------------------------------------------------------- | ------------------------------------------------------- | :----: |
| Store API/Payment method registration | Payment method registration | Ensure the payment method is [registered on the server side](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/checkout-payment-methods/payment-method-integration.md#server-side-integration) to process the payments  |  _unknown_   |
| Checkout block client | Registering the payment method with the block | Ensure the payment method is [registered on the client side](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/checkout-payment-methods/payment-method-integration.md#client-side-integration) using registration methods exposed on the `blocks-registry` API  |  _unknown_   |
|                                                                             |                                                                               |
