### ISSUE TITLE
Audit: Packlink PRO

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#9234]
## Packlink PRO

- **Author:** Packlink Shipping
- **Website:** https://woocommerce.com/products/packlink-pro/
- **Repository:** n/a

_This issue is to track compatibility testing between this extension and the Cart and Checkout blocks. [See the epic for the audit template](https://github.com/woocommerce/woocommerce-blocks/issues/9206) which should be completed and posted as a comment here once completed._

**Comment by tarhi-saad** [comment]
# Extension Audit Template

## Functionality Review

PackLink PRO links your store to a network of shipping services. The merchant can select explicit services, or defer to PackLink to select the cheapest one.

This extension touches: *(mark all that apply)*

- [ ] Products (Beta)
    - [ ] Product title
    - [ ] Product price
    - [ ] Product meta
    - [ ] Add to cart button
- [ ] Single Product Pages
    - [ ] Product title
    - [ ] Product price
    - [ ] Product meta
    - [ ] Add to cart form
- [x] Cart Page
    - [ ] Cart items
    - [ ] Product title
    - [ ] Product price
    - [ ] Product meta
    - [ ] Product quantity
    - [ ] Cart totals
    - [ ] Notices
    - [ ] Custom functionality
- [x] Checkout Page
    - [ ] Checkout fields
    - [ ] Express checkout
    - [ ] Contact information
    - [x] Shipping method
    - [x] Pickup method
    - [ ] Shipping address
    - [ ] Billing address
    - [ ] Payment options
    - [ ] Checkout totals
    - [ ] Product title
    - [ ] Product price
    - [ ] Product meta
    - [ ] Product meta
    - [ ] Notices
    - [ ] Custom functionality
    - [ ] Order received page
- [ ] My Account Page
- [ ] Store API
    - [ ] Edits existing endpoint
    - [ ] Adds custom endpoint
- [ ] Settings
    - [ ] WooCommerce settings
    - [ ] Custom settings page
    - [ ] Customizer

## Compatibility with Blocks


### Issues identified:

The Packlink Pro is compatible with the Cart & Checkout Blocks (e.g., we can place an order), but there are some improvements to be made:

#### Missing drop-off location button

When using a UK address in PackLink PRO, it is possible to choose a shipping method that uses a "drop-off" (aka Local pickup) method. But, the button to select the drop-off location is missing in the Checkout Block page. We can still place our order and select a drop-off location in the Packling Pro dashboard!

| Checkout: shortcode version | Checkout Block |
| --------------------------------------------------------------------------- | -------------------------- | 
| <img width="490" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/14235870/f9104b67-a764-4292-88f5-e073c3e99774"> | <img width="563" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/14235870/e770cf24-20a5-488c-94a5-428274da68b1"> |  

#### Missing shipping methods logos

The shipping methods can have logos associated with them, as seen in the example above. These logos do not show in the Cart or Checkout blocks.

<img width="358" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/5656702/e2985ad1-1f93-45a6-9806-98962ed0f3fe">

*Select those that apply:*

- [ ] Extension is already fully compatible with Blocks
- [ ] Extension requires integration with Blocks
- [x] Extension requires fixes in the blocks context
- [ ] Extension could be further enhanced to take advantage of Blocks

## Integration Required

This extension requires integration with:

- [x] Cart Block
- [x] Checkout Block
- [ ] Payment Methods API
- [ ] Store API
- [ ] Other

### Integration Points


| Location                                                                    | Type                                                                          | Description                                             | Effort |
| --------------------------------------------------------------------------- | ----------------------------------------------------------------------------- | ------------------------------------------------------- | :----: |
| Client-side | Maybe a filter for shipping options, or new way for us to display logos alongside shipping methods. | Showing logos or other custom content alongside a shipping metohd. |  _5_   |
|                                                                             |                                                                               |
