### ISSUE TITLE
Audit: Skydropx

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#9237]
## Skydropx

- **Author:** Skydropx
- **Website:** https://woocommerce.com/products/skydropx/
- **Repository:** n/a

_This issue is to track compatibility testing between this extension and the Cart and Checkout blocks. [See the epic for the audit template](https://github.com/woocommerce/woocommerce-blocks/issues/9206) which should be completed and posted as a comment here once completed._

**Comment by nielslange** [comment]
I tried to do an audit for this extension, but wasn't able to log into a newly registered account. I tried switching my VPN to Columbia and Mexico, but couldn't access the registration form.

**Comment by opr** [comment]
# Extension Audit Template

## Functionality Review
 
This extension integrates shipping methods from Mexico and Colombia making them available while in the Cart and Checkout flow.

This extension touches: *(mark all that apply)*

- [ ] Products (Beta)
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Add to cart button
- [ ] Single Product Pages
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Add to cart form
- [x] Cart Page
  - [ ] Cart items
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Product quantity
  - [ ] Cart totals
  - [ ] Notices
  - [ ] Custom functionality
- [x] Checkout Page
  - [ ] Checkout fields
  - [ ] Express checkout
  - [ ] Contact information
  - [x] Shipping method
  - [ ] Pickup method
  - [ ] Shipping address
  - [ ] Billing address
  - [ ] Payment options
  - [ ] Checkout totals
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Product meta
  - [ ] Notices
  - [ ] Custom functionality
  - [ ] Order received page
- [ ] My Account Page
- [ ] Store API
  - [ ] Edits existing endpoint
  - [ ] Adds custom endpoint
- [ ] Settings
  - [ ] WooCommerce settings
  - [ ] Custom settings page
  - [ ] Customizer 

## Compatibility with Blocks

This plugin works with WooCommerce blocks. The shipping methods show correctly and it is possible to place an order!

Issues identified:

Nothing blocking, but it seems rather slow. Perhaps it would be faster if we were closer to Central America while testing.

*Select those that apply:*

- [x] Extension is already fully compatible with Blocks
- [ ] Extension requires integration with Blocks
- [ ] Extension requires fixes in the blocks context
- [ ] Extension could be further enhanced to take advantage of Blocks

## Integration Required
None!

This extension requires integration with: 

- [ ] Cart Block
- [ ] Checkout Block
- [ ] Payment Methods API
- [ ] Store API
- [ ] Other

### Integration Points

None required.


| Location                                                                    | Type                                                                          | Description                                             | Effort |
| --------------------------------------------------------------------------- | ----------------------------------------------------------------------------- | ------------------------------------------------------- | :----: |
| _Location of new integration point, or name of existing integration point._ | _Type e.g. client API, action or filter hook, component, or server side API._ | _Describe what the integration point will be used for._ |  _1_   |
|                                                                             |                                                                               |
```
