### ISSUE TITLE
Products block: taxonomy filter names are not decoded properly

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#9242]
## To reproduce

1. Go to Products > Categories and create a category with name `Clothing & Accessories`.
2. Create a new post and add the Product Collection block.
3. In the sidebar, add a Taxonomies filter and select the Product category you just created.
4. Notice the name is not decoded properly.

![imatge](https://github.com/woocommerce/woocommerce-blocks/assets/3616980/fc20490f-7e0e-42c6-803e-6c8c207fb31a)

## Expected behavior

The name should be shown the same way it was introduced when created.

cc @kmanijak in case you think this should be included to the Products epic.

**Comment by kmanijak** [comment]
Fix provided in Gutenberg repo: https://github.com/WordPress/gutenberg/pull/50376
