### ISSUE TITLE
Add more "sort by" options to the Products block, starting with menu_order

### ISSUE THREAD

**Issue by asafm7** [woocommerce/woocommerce-gutenberg-products-block#9249]
### Discussed in https://github.com/woocommerce/woocommerce-blocks/discussions/9089

<div type='discussions-op-text'>

<sup>Originally posted by **asafm7** April 18, 2023</sup>
Add more "sort by" options to the Products block, starting with menu_order (which used to be the default sorting in WooCommerce, if I'm not wrong).</div>

**Comment by kmanijak** [comment]
Hi @asafm7, thanks for taking the time to create this issue!

Have you tried to use Catalog Sorting block along with the Products block? It does allow for changing a sorting of Products block in the same manner as it was in the Classic Template.

Please let me know if that answers your request 🙏

**Comment by asafm7** [comment]
Thanks @kmanijak .

I actually tried the Catalog Sorting block but it didn't show up on the front end, so I assumed it is designed for the Classic Template.

I've tried it on an FSE Home template (rather than a regular page). Maybe it is related?

**Comment by kmanijak** [comment]
> I actually tried the Catalog Sorting block but it didn't show up on the front end, so I assumed it is designed for the Classic Template.
> I've tried it on an FSE Home template (rather than a regular page). Maybe it is related?

I tried to use Catalog Sorting on a home page and I can confirm it doesn't render, which seems like a bug. I raised that here: https://github.com/woocommerce/woocommerce/issues/42387 so please use that issue to track the progress on the issue.

In the meantime, you can still try to use Catalog Sorting along with Products block on other pages, for example, editing Product Catalog template and see if these blocks give you the functionality you'd expect. For now, I'll go ahead and close this issue as we use open issues to track bugs and enhancements. But closed issues can also still be commented on and we're happy to hear your feedback! 🙌
