### ISSUE TITLE
Playwright migration: Add cache system for the CI

### ISSUE THREAD

**Issue by gigitux** [woocommerce/woocommerce-gutenberg-products-block#9261]
Currently, [we are not caching the deps](https://github.com/woocommerce/woocommerce-blocks/blob/0b1783472826c6804e041e800b9a892eeaa93fa3/.github/workflows/playwright.yml/#L21-L24). We should do it to improve the speed of the CI process. Also, we could try to use [Playwright Docker image](https://playwright.dev/docs/docker).

**Comment by dinhtungdu** [comment]
@gigitux FYI I'm caching the deps in #10508. If you haven't started working on this issue, I can take over.

**Comment by gigitux** [comment]
@dinhtungdu I didn't start to work on this! Feel free to assign to you!

**Comment by dinhtungdu** [comment]
@gigitux Cache was added in #10508. I tried using docker image but failed in https://github.com/woocommerce/woocommerce-blocks/pull/10612. Looking at the [workflow log](https://github.com/woocommerce/woocommerce-blocks/actions/runs/5876325321/job/15934259880), I think keep installing playwright is more optimal option. The approach I tried is possibly wrong, but I don't think it worth the effort to continue investigating this topic. I'm closing this issue, but feel free to reopen if needed.

<img width="1449" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/5423135/2c55e607-5e10-4554-88d8-b8d797f17f26">

**Comment by gigitux** [comment]
It makes sense! Thanks for your work! 👍
