### ISSUE TITLE
Remove billing fields from checkout

### ISSUE THREAD

**Issue by rajausman786** [woocommerce/woocommerce-gutenberg-products-block#9262]
### Discussed in https://github.com/woocommerce/woocommerce-blocks/discussions/9082

<div type='discussions-op-text'>

<sup>Originally posted by **rajausman786** April 18, 2023</sup>
How i can remove or unset billing fields from checkout page via coding, i am using WooCommerce Blocks and checkout is created with WooCommerce Blocks</div>

**Comment by mikejolley** [comment]
Hi @rajausman786 

This is not currently possible in the Block based checkout—the fields are standardised. We are aware of this request and it is on our roadmap, but there is no timeline for this.

I am going to close this issue in favour of https://github.com/woocommerce/woocommerce/issues/42496 which already exists.

Thanks
