### ISSUE TITLE
Product Grid items do not indicate 'Featured' status

### ISSUE THREAD

**Issue by musicalbigfoot** [woocommerce/woocommerce-gutenberg-products-block#927]
**Is your feature request related to a problem? Please describe.**
I am able to toggle visibility of the 'On Sale' badge for products in any of the blocks that use the AbstractProductGrid server side rendering functions. I would like to apply similar custom styles to a product if it has the 'Featured' status but currently have no way of doing this. Each product list item has a class added to it when a user visits the designated Shop archive, this data should remain available when creating with any of the product grid blocks in order to mimic the functionality of the core Shop archive template.

**Describe the solution you'd like**
Add a '--featured' class to the wc-block-grid__product list item if the product is indeed featured. This wouldn't require extra dom elements so I wouldn't think a visibility toggle would be necessary.

**Describe alternatives you've considered**
Creating my own versions of the blocks that are missing this information.

**Comment by nerrad** [comment]
We spent a bit of time chatting about this as a part of our backlog review and while we do agree this use-case is a valid need, when it's addressed we likely will approach it in a more abstract way so need is met in an implementation that allows for other custom "badge" type indicators. This is not something on our immediate roadmap to implement but I'm keeping the issue open for future consideration.
