### ISSUE TITLE
Product Rating block: Nothing happens when clicking on Add review link 

### ISSUE THREAD

**Issue by thealexandrelara** [woocommerce/woocommerce-gutenberg-products-block#9270]
## Describe the bug

Inside the Single Product block, we are using the Product Rating block to display the average rating for a single product. Currently, when no reviews exists for the product an Add Review link is displayed, which is an anchor link to the `#reviews` section. This happens because the Product Rating block was initially created with the Single Product template in mind, where the Reviews section used to exists so when a shopper clicked on it, they would be redirected to that section.

Now that we are using the Single Product block, a selected product can exist anywhere (inside a post, a page, a template, etc), so that is not guaranteed that there will be a Reviews section on the same page.

## To reproduce

1. Log in to your WordPress dashboard;
2. Go to Appearance > Themes, and select a block theme (for example: Twenty-twenty three);
3. Go to Appearance > Editor;
4. Click the Edit button;
5. Click on the "+" icon to add a new block and search for "Single Product" block in the search bar;
6. Click on the "Single Product" block to add it to your page or post;
7. Select a product that does not contain any review on the Product Selector and click on the Save button;
8. On the editor, check that the Review count is displayed;
9. Go to the frontend of your website;
10. On the frontend, check that the Add review link is displayed;
11. Click on it and check that nothing happens, except the `#reviews` is added to the URL

## Expected behavior

I can think in two possible behaviors:

1. Hide the Add Review link when the product has no reviews, or;
2. Just display the ratings with empty stars (with no anchor links to Reviews section), like: ☆☆☆☆☆

## Screenshots

https://user-images.githubusercontent.com/20469356/234971692-91acc7d0-67b4-4898-be8d-72bc8a2b0633.mov

### WordPress (please complete the following information):

-   WordPress version: 6.2
-   Gutenberg version (if installed): 15.6.0-rc.2
-   WooCommerce version: 7.8.0-dev
-   WooCommerce Blocks version: 10.2.0-dev
-   Site language: EN-US
-   Any other plugins installed:

### Desktop (please complete the following information):

-   OS: MacOS Ventura
-   Browser: Chrome
-   Version: 112.0.5615.137

**Comment by kmanijak** [comment]
Adding more context:

### Impact
With the new Single Product template, that issue affects also other places where "Product Rating" is used (e.g. Products block and All Products, which can be used in many places).

### Options
> 1. Hide the Add Review link when the product has no reviews, or;

That would be nice, but it's only feasible on Single Product page. I don't think that's easily achievable on Product Catalog since that would mean, the Product Rating block would have to fetch the Single Product template and go through its structure to look for a reviews block 🤔 

Is that possible that adding/removing Reviews block to/from Single Product template changes the setting which could be consumed by Product Rating block anywhere?

> 2. Just display the ratings with empty stars (with no anchor links to Reviews section), like: ☆☆☆☆☆

That was an original idea covered in this PR: https://github.com/woocommerce/woocommerce-blocks/pull/7929, but it was challenged as it seems like a low rating (not a lack of rating). Then it evolved toward "Add Review" link (details and options can be checked in the PR description).

**Comment by gigitux** [comment]
> With the new Single Product template, that issue affects also other places where "Product Rating" is used (e.g. Products block and All Products, which can be used in many places).

I'm not sure about this. Reading the code, we added the new string only for the Single Product Block (and in the future for the Single Product Template) - [source code](https://github.com/woocommerce/woocommerce-blocks/pull/9129/files/3c68ee0b34afe73679e06d93e6c7b96e9a20ce70#diff-9defe615963571610affb73341a43db364eeb7fc5616000176494510be3e8e70R166)

**Comment by kmanijak** [comment]
> I'm not sure about this. Reading the code, we added the new string only for the Single Product Block (and in the future for the Single Product Template) - [source code](https://github.com/woocommerce/woocommerce-blocks/pull/9129/files/3c68ee0b34afe73679e06d93e6c7b96e9a20ce70#diff-9defe615963571610affb73341a43db364eeb7fc5616000176494510be3e8e70R166)

I may misunderstand this, but what I meant is that "Add review" shows whenever there's no rating for the product. And it's a link that redirects to product page with `#reviews` section pointer. What I meant by "that issue affects also other places where "Product Rating" is used" is that the link would redirect to the product page without ratings enabled. Does it make sense?

**Comment by gigitux** [comment]
> > I'm not sure about this. Reading the code, we added the new string only for the Single Product Block (and in the future for the Single Product Template) - [source code](https://github.com/woocommerce/woocommerce-blocks/pull/9129/files/3c68ee0b34afe73679e06d93e6c7b96e9a20ce70#diff-9defe615963571610affb73341a43db364eeb7fc5616000176494510be3e8e70R166)
> 
> I may misunderstand this, but what I meant is that "Add review" shows whenever there's no rating for the product. And it's a link that redirects to product page with `#reviews` section pointer. What I meant by "that issue affects also other places where "Product Rating" is used" is that the link would redirect to the product page without ratings enabled. Does it make sense?

Ah, gotcha! By the way, in the classic shop, the `Add Review` link isn't shown. What is the best approach?

| Classic Template | Blockified Template |
|--------|--------|
|![image](https://user-images.githubusercontent.com/4463174/235176942-fac59189-0528-40f8-9dbe-204d99020d65.png)|![image](https://user-images.githubusercontent.com/4463174/235177037-d9e1961c-d3a2-44ed-817a-8a2939faa7af.png)| 


cc Any thoughts? @shaunandrews

**Comment by thealexandrelara** [comment]
Thank you all for the inputs and additional context!

> That would be nice, but it's only feasible on Single Product page. I don't think that's easily achievable on Product Catalog since that would mean, the Product Rating block would have to fetch the Single Product template and go through its structure to look for a reviews block 🤔

I haven't explored this so deep, but one thing that I noticed while working on #9129 is that we have access to the `$rating` (the average rating number) and the `$count` (amount of ratings for that product) - at least for the Single Product block. I'm wondering now if we can use the same logic for each product inside the Product Catalog/All Products block, because if that is possible, we can hide the link when the `$count` is 0, for example.

> That was an original idea covered in this PR: https://github.com/woocommerce/woocommerce-blocks/pull/7929, but it was challenged as it seems like a low rating (not a lack of rating). Then it evolved toward "Add Review" link (details and options can be checked in the PR description).

Thank you for sharing this, looking at the PR I read that you also discussed that in future iterations we could allow merchants to customize the text/link maybe that's something we can start thinking about it again. Another possibility would be to display "No reviews" or something like that instead of showing empty stars. 

> I may misunderstand this, but what I meant is that "Add review" shows whenever there's no rating for the product. And it's a link that redirects to product page with #reviews section pointer. What I meant by "that issue affects also other places where "Product Rating" is used" is that the link would redirect to the product page without ratings enabled. Does it make sense?

Yes, it makes sense the "Add Review" link only appears when there is no rating for the product

Having the "Add review" link by default was a smart move at first, but now that we are blockifying the Single Product template, I don't know how easy it would be to identify which product contains the Reviews block added to the page, and probably we have to think if this should be treated as the default behavior 🤔
