### ISSUE TITLE
Filter by Attribute heading should include attribute name by default

### ISSUE THREAD

**Issue by kmanijak** [woocommerce/woocommerce-gutenberg-products-block#9271]
### Description
Currently, the Filter by Attribute has a fixed heading "Filter by Attribute". It should tell what attribute this is filter is about e.g. Filter by Color or Filter by Size

Currently, the label can be changed manually, but that could be automized.

**Comment by zaghadon** [comment]
@kmanijak I'll look into this enhancement. Hopefully no one is on it now.

**Comment by kmanijak** [comment]
@zaghadon, I don't think anyone works on that now, so feel free to pick it up! Please let me know if you have any questions. 🙌

**Comment by zaghadon** [comment]
@kmanijak  Yeah great. So my question is, could you show screenshots of where this enhancement is needed. 

Presentation layers are usually theme-specific responsibility, mostly overridden by the current theme. I want to be certain this enhancement has to be applied on the blocks.

**Comment by roykho** [comment]
Hi @zaghadon - Here is a screenshot of the heading that should be changed based on what attribute is selected to filter:

![file.png](https://github.com/woocommerce/woocommerce-blocks/assets/2132595/3cedeab5-1097-46cb-8a42-0cec81606641)

**Comment by zaghadon** [comment]
I can confirm that the attribute-filter has an attributes file that exports the blockAttribute function, which returns a default heading text as "Filter by Attribute". 

I also checked and they're: 
3 Active Filters

- Filter by Price
- Filter by Rating
- Filter by Stock

I'm trying to understand, does this enhancement seek to make it such that if it's being filtered by Price, then the heading should return Filtered by Price? Instead of "Attribute"?

@roykho @kmanijak

**Comment by roykho** [comment]
> I'm trying to understand, does this enhancement seek to make it such that if it's being filtered by Price, then the heading should return Filtered by Price? Instead of "Attribute"?

No, we're only talking about the `Filter by Attribute` block here. When you add the block, it asks you to choose the attribute you want to filter by (size, color...etc). After choosing the attribute, the heading should change based on the chosen attribute.

**Comment by kmanijak** [comment]
Closing as irrelevant as it's going to be potentially addressed in new Frontend Filters.

cc: @dinhtungdu
