### ISSUE TITLE
Checkout block: Improve the Contact Information account settings in the post editor sidebar

### ISSUE THREAD

**Issue by ralucaStan** [woocommerce/woocommerce-gutenberg-products-block#9280]
## Is your feature request related to a problem? Please describe.
In the Checkout block post editor, the Contact Information section sidebar settings Account section needs to be improved.
<img width="211" alt="Screenshot 2023-04-28 at 12 24 48" src="https://user-images.githubusercontent.com/1628454/235125274-2a8427df-6c79-4273-8472-f9b72992c74a.png">

There are frequent authentification settings that apply to a checkout flow:
- If the merchant wants to enable/disable guest checkouts
- Allowing login
- Allowing new account creation 

Currently, when the merchant selects the contact information section, they only see a link to the WC Admin Accounts & Privacy where he needs to figure out what to select.
<img width="880" alt="Screenshot 2023-04-28 at 12 38 40" src="https://user-images.githubusercontent.com/1628454/235126274-1e4391ae-d0f4-4d65-a491-5c5873dd0098.png">

## Describe the solution you'd like
We need to allow the merchant to enable/disable common authentification settings directly from the post editor.
We could show in the Account sections toggles for these settings, instead of the link to the WC admin page.

**Comment by pmcpinto** [comment]
We shouldn't move forward with this to keep it consistent with other global settings. We should wait until design finishes the audit. Should we close this for now?
