### ISSUE TITLE
Refactor template related code

### ISSUE THREAD

**Issue by wavvves** [woocommerce/woocommerce-gutenberg-products-block#9289]
Part of Epic: Cart/Checkout/Order Received Templates https://github.com/woocommerce/woocommerce-blocks/issues/9288

Our current template-related code contains duplication, and since it has been used in several use case templates now, it can be refactored for simplification purposes.

We do not currently have unit testing for it, and this issue must be resolved before, as it can drastically improve the dev experience writing tests.

Acceptance criteria is not set. Instead, we should limit the amount of time spent to one day and implement the improvements possible within the timeframe.

~Note: It should be merged into trunk to avoid future conflicts.~

**Comment by mikejolley** [comment]
I'll take this one.

**Comment by mikejolley** [comment]
Making a note because there will be a followup needed; we use CHECKOUT_PAGE_ID etc across the codebase. When moving from pages to checkout endpoints, this all needs to be replaced.

**Comment by wavvves** [comment]
Resolved by #9411. This will find its way into the project branch via #9426, as it depends on it.
