### ISSUE TITLE
PHP Unit Tests for Cart/Checkout/ Order Received Templates

### ISSUE THREAD

**Issue by wavvves** [woocommerce/woocommerce-gutenberg-products-block#9290]
Part of Epic: Cart/Checkout/Order Received Templates https://github.com/woocommerce/woocommerce-blocks/issues/9288

PHP Unit Tests. Blocked by #9289 

Should be merged to epic's main branch.

Note: This issue is detached from the code it is testing as we already have POCs for the mentioned templates.

**Comment by mikejolley** [comment]
@wavvves there doesn't seem to be anything special on the PHP side that would justify test coverage. Did you have anything in mind for this task?

**Comment by wavvves** [comment]
@mikejolley you are probably right, I was checking for successful template registration, but it does not make much sense to do that individually. Maybe in the future if we register templates with a `foreach` maybe it would make sense to check the list against properly registered templates. I'll close this, and look into your E2E PR that will cover the changes properly 👍🏼
