### ISSUE TITLE
Don't automatically upgrade to Cart/Checkout templates

### ISSUE THREAD

**Issue by wavvves** [woocommerce/woocommerce-gutenberg-products-block#9293]
Part of Epic: Cart/Checkout/Order Received Templates https://github.com/woocommerce/woocommerce-blocks/issues/9288

Sub-task from https://github.com/woocommerce/woocommerce-blocks/issues/9153

> We don't automatically upgrade existing users with a block-based theme to the templates. They should access the cart & checkout blocks through the pages. We can use two complementary methods to nudge the users to transition to the templates:
Include a message when they visit the cart or checkout page showcasing the benefits of having them as templates and with a mechanism to enable the template and disable the page. This should be done separately for the cart and checkout, as some users may not use both blocks. The user should be re-directed to the template after enabling it. [needs design input]
Trigger an Inbox notification informing the users about the new experience. The notification redirects the user to the cart or checkout page, where he can transition to the template, as mentioned above. [needs design input]

**Comment by wavvves** [comment]
Hi @pmcpinto, regarding this subject, an experiment was made to streamline this process and reduce the need for communication relying on UX as the main educator. The work is present on #9334 

In a nutshell:
- If the user enables a block theme, current cart and checkout content will populate the template, making this backward compatible with the current state. It works also with shortcode versions.
- Editing that content will shift from the page editor to the template editor, but that change will be seamless as both edition processes are the same. 
- To avoid confusion and introduce the user to the new place where content edition lives, trying to edit those pages will take the user to the template editor version. This is how we try to educate the user through UX without notices with additional information to assimilate. In the case the user fails to comprehend he's not on the page editor but the template editor, that wouldn't pose a problem since it is a familiar edition process.

props to @mikejolley for this proposal

cc @shaunandrews

**Comment by pmcpinto** [comment]
Paulo, thanks for summarizing the solution, which seems to be pretty solid to me. IIUC the Cart and Checkout pages will still be available in the pages list until the user clicks on them and is redirected to the template editor, right?

**Comment by mikejolley** [comment]
@pmcpinto The pages still exist (we don't delete them), but when you click to edit them you'll be redirected to the editor. Despite the title of this issue, the upgrade is automatic in the sense that the template is used over the page content. But we're migrating page content so the end user does not need to be concerned with breakage.

This all applies only to block themes. This also means moving from a block theme back to a non-block theme will keep their pages intact and again prevent any breakage (although they would lose any changes made to the template itself which is understandable).

**Comment by mikejolley** [comment]
Ref: https://github.com/woocommerce/woocommerce-blocks/pull/9339
