### ISSUE TITLE
Checkout Blocks Local Pickup lacks the option to restrict to certain regions

### ISSUE THREAD

**Issue by pk385** [woocommerce/woocommerce-gutenberg-products-block#9296]
## Is your feature request related to a problem? Please describe.
Yes, we should have the ability to restrict local pickup to certain regions either by postal code or territory such as state, preferably both. This is currently only possible by using the default woocommerce shipping zones -> shipping methods version of local pickup and only enabling the shipping method in certain zones.

## Describe the solution you'd like
Add some options to the existing local pickup section under woocommerce settings -> shipping ->local pickup to enable or disable restricting local pickup to certain regions. This could be as simple as a checkbox and an territory dropdown. This way, the blocks implementation will be able to match the functionality of the default woocommerce shipping methods implementation of local pickup without re-implementing zones themselves.

## Describe alternatives you've considered
Maybe integrate further with the current shipping zones to honor any existing settings related to local pickup. It seems like there is already been some work done here since it's able to detect when the local pickup shipping method is active in a shipping zone:

> Enabling this will produce duplicate options at checkout. Remove the local pickup shipping method from your [shipping zones]

**Comment by opr** [comment]
Hi @pk385 - thanks for opening this issue. I can see why you may want to limit the option to collect locally, based on where the user is, however there are also arguments against this. It is something we considered during the design phase, the use case being that you might want to ship via a pickup location network, which are fairly common.

For now, this can be done easily via a custom shipping method, but we're not sure if we're ever going to add it to the core local pickup.

Doing this via custom plugin is possible using the following steps:

- Register a new shipping method that supports Local Pickup (`local-pickup` is the feature name).
- In the shipping method `calculate_shipping`, you filter by location.
- In the UI, you can register a custom block inside the shipping method step that's visible only if the `wc/store/checkout` data store's `prefersCollection` property is `true`. This should be an input that  would sync up to whatever you use to filter results e.g. state/zip code.
- When changing this value the data should be sent to the server using the `wc/store/cart` data store and the `updateCustomerData` action on it. That way your shipping methods `calculate_shipping` can use this value.

An important issue with filtering is how do you filter? You suggested zip code, but what if the shopper is okay driving to another zipcode, what if the pickup location in the next city is closer than the one in my city. You will need to calculate locations and decide to show that.

Overall this is something the shipping method should figure out, and if we're to add it to WooCommerce Blocks, I think it will complicate the UI.

On this basis we will close this issue but feel free to keep the discussion going if you need clarification or help with anything!

**Comment by pk385** [comment]
Yeah I completely get that and kind of knew what the response would be, but it complicates the checkout process if a customer on the other side of the country accidentally leaves the option selected or for some other reason chooses the option with no intention of actually coming to pick it up. Restricting local pickup to the same state is an imperfect but effective solution for weeding out a good portion of these orders, and If we had the data I think you would find that most customers who choose local pickup will be in or around the same state. That's really my main use case for it. A better solution would be to do distance based calculations and choosing a maximum distance that aligns closely to how far a customer would feasibly prefer driving over paying for shipping, which honestly probably isn't very far. Not worth the time, gas costs, effort, etc. I can't imagine there are many instances of customers driving more than 100 miles to pickup an order.  

I think this is going to be a roadblock for some people trying to adopt the blocks plugin in place of the default cart/checkout, not only because it's functionality lost but also because it's incompatible with the current zones local pickup settings. If a nice middle ground can be achieved where the default local pickup options can coexist with the new blocks, I think that would be ideal. I don't know the implementation details, but it seems like you could determine whether or not the customer matches a zone in which the default local pickup is enabled, and then selectively enable/disable local pickup in the checkout block. Again, haven't looked into this repo so I have no idea if that's possible, just an idea.
