### ISSUE TITLE
wcSettings conflict with wc-admin

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-gutenberg-products-block#932]
**Describe the bug**

The wc-admin dashboard is broken with Blocks plugin activated.

![Screen Shot 2019-08-30 at 11 13 49 AM](https://user-images.githubusercontent.com/1922453/63982736-d6351480-cb17-11e9-9ccb-5ec36857212d.png)

**To Reproduce**

1. Use master branch of wc-admin and this plugin and activate both.
2. Visit wc-admin dashboard and see the page fail to render. Check that`wcSettings` is undefined in the console.

**Expected behavior**

Dashboard should load.

**Comment by nerrad** [comment]
Fixed in merged pulls (see #956)
