### ISSUE TITLE
Make the Mini Cart block cache-friendly

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#9353]
Currently, if a store wants to use page caching, the Mini Cart block can show outdated totals or even totals from other sessions. We would like to fix that so stores can enable page caching without problems even when having the Mini Cart block in their page.

See also https://github.com/woocommerce/woocommerce-blocks/issues/7530.

## To reproduce

1. Install _WP-Optimize - Clean, Compress, Cache_ or a similar caching plugin.
2. Go to WP-Optimize > Settings > Cache and enable page caching.
3. In the frontend without being logged in (ie: in a private/incognito window) visit any page.
4. Add some products to your cart.
5. Visit the same page from step 3.
6. Notice the Mini Cart totals don't include the products you added in step 4.

## Expected behavior

Mini Cart should always show the correct totals, even if caching is enabled.

## Approach

In order to solve that, we would like to:

1. Store cart data in the client local storage. Ideally we would store the minimum data needed for the Mini Cart to show the correct values.
2. On PHP render, we would render the Mini Cart block as we do right now, assuming there are 0 products in the cart.
3. On page load:
3.1. We would check if the user has some cart data in their local storage. If it does, we will use it to fill Mini Cart block details.
3.2. In addition to the previous step, we will make a query to the Store API to gather the cart values and will update them in the Mini Cart button. We will save these values into the user local storage.

**Comment by bitmakers** [comment]
I was about to post a related issue but just found this - making the cart totals update on cached pages is essential in my opinion, especially since the mini cart block will likely be included in the header on every page.
