### ISSUE TITLE
Product Collection - Patterns: Pattern chooser

### ISSUE THREAD

**Issue by kmanijak** [woocommerce/woocommerce-gutenberg-products-block#9372]
### Description
Make sure the patterns created in scope of 
- https://github.com/woocommerce/woocommerce-blocks/issues/9368
- https://github.com/woocommerce/woocommerce-blocks/issues/9369
- https://github.com/woocommerce/woocommerce-blocks/issues/9370
- https://github.com/woocommerce/woocommerce-blocks/issues/9371
are available in the pattern chooser for the Product Collection block.
That behavior is already available in Products block under "Replace" button.

### Image
<img width="504" alt="image" src="https://user-images.githubusercontent.com/20098064/236237560-85ebf187-1d82-4164-9641-b8985ccc7541.png">
<img width="446" alt="image" src="https://user-images.githubusercontent.com/20098064/236237626-1cdcff97-26db-40a0-b50e-772c2e44dfc2.png">

**Comment by imanish003** [comment]
I'm closing this issue since we'll be addressing the same functionality in woocommerce/woocommerce#42224.

**Comment by kmanijak** [comment]
> I'm closing this issue since we'll be addressing the same functionality in https://github.com/woocommerce/woocommerce/issues/42224.

I don't mind closing it and can work in the scope of https://github.com/woocommerce/woocommerce/issues/42224. But I'd like to highlight there's a slight difference from my POV:
- https://github.com/woocommerce/woocommerce/issues/42224 - in here there's a flow of _newly_ added Product Collection
- https://github.com/woocommerce/woocommerce-blocks/issues/9372 - This issue is for already added Product Collection, so you can switch to different pattern.

Both are gonna use the same Pattern Chooser, but they represent a bit different flows. I'm going to include building the Pattern Chooser in https://github.com/woocommerce/woocommerce/issues/42224, but mentioning it for clarity so we're on the same page @imanish003 ! 🙌

**Comment by imanish003** [comment]
@kmanijak Got it. Thanks for the clarification 🙏🏻
