### ISSUE TITLE
Checkout still require postcode even if it's not required.

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#9376]
When postcode is optional, checkout still validates it and return an error if it's not present

<img width="693" alt="image" src="https://user-images.githubusercontent.com/6165348/236457494-c433453d-582f-42fc-bc99-a9705b430f3d.png">

**Comment by ralucaStan** [comment]
potentially introduced by https://github.com/woocommerce/woocommerce-blocks/pull/8503
