### ISSUE TITLE
Hook up checkout pay-for-order endpoint

### ISSUE THREAD

**Issue by hsingyuc** [woocommerce/woocommerce-gutenberg-products-block#9380]
This issue is associated with the issue: [an endpoint for processing pay-for-order orders](https://github.com/woocommerce/woocommerce-blocks/issues/9312)

## Describe the solution you'd like
1. Hook up the checkout pay-for-order endpoint, so clicking on the place order button will pay for the pay-for-order order
2. The `Place Order` button should be renamed to `Pay For Order`

## Screenshot
<img width="508" alt="Screen Shot 2023-05-05 at 4 35 23 PM" src="https://user-images.githubusercontent.com/56378160/236584910-a08444f3-07ee-45d3-82b3-29aee623ca17.png">

**Comment by nielslange** [comment]
Hello @hsingyuc,

Thanks for reaching out. In #7843, we added a filter to adjust the place order button label. Initially, we were using the `__experimentalRegisterCheckoutFilters` filter. In #8346, we've graduated that filter from experimental to stable. 

The following snippet shows how you should be able to change the button label from `Place Order` to `Pay For Order` in your corresponding use case:

```jsx
import { registerCheckoutFilters } from '@woocommerce/blocks-checkout';
import { __ } from '@wordpress/i18n';

const label = () => __( 'Pay For Order', 'YOUR-TEXTDOMAIN' );
registerCheckoutFilters( 'custom-place-order-button-label', {
	placeOrderButtonLabel: label,
} );
```

Applying this filter, will lead to the following result:

<img width="655" alt="Screenshot 2023-05-08 at 12 38 44" src="https://user-images.githubusercontent.com/3323310/236742600-bcc90d9c-a0bf-4668-b916-6ebf619fdf24.png">

I'll mark this issue as closed, but please don't hesitate to reopen it again in case that's not the solution you've been looking for.

**Comment by hsingyuc** [comment]
Hi, @nielslange!  This issue is part of the Pay-For-Order flow project ( pdpOw2-2u0-p2 ).  We are creating the flow inside of the WooCommerce Blocks.  I'm going to reopen this issue, but please let me know if you have any questions.

**Comment by nielslange** [comment]
Thanks for clarifying this, @hsingyuc. I'm going to move the issue to the backlog in this case.

**Comment by hsingyuc** [comment]
Closing this issue and moving forward with WooPay-only approach.
