### ISSUE TITLE
Cart and Checkout Item visibility

### ISSUE THREAD

**Issue by codewp** [woocommerce/woocommerce-gutenberg-products-block#9381]
It seems that some of the WooCommerce cart filters are missing in the cart and checkout blocks.

We used the below filters for items visibility and they don't work with the cart block.
```php
add_filter( 'woocommerce_cart_item_visible', array( $this, 'cart_item_visible' ), 10, 2 );
add_filter( 'woocommerce_widget_cart_item_visible', array( $this, 'cart_item_visible' ), 10, 2 );
add_filter( 'woocommerce_checkout_cart_item_visible', array( $this, 'cart_item_visible' ), 10, 2 );
add_filter( 'woocommerce_order_item_visible', array( $this, 'cart_item_visible' ), 10, 2 );
```

Thanks

**Comment by nielslange** [comment]
Thanks for reaching out, @codewp. To better understand this issue, can you explain what you're hoping to accomplish? Maybe there's an alternative way when using the Cart and Checkout blocks.

**Comment by codewp** [comment]
@nielslange 

Thank you for your reply.

I want to hide some items inside the cart, mini cart, checkout, and order details. 

Please let me know if you have further questions.

Thanks

**Comment by nielslange** [comment]
May I ask why you want to hide certain items? I wonder if customers won't find it confusing if they add an item to the cart, but cannot see it inside the cart, mini cart, checkout, and order details.

**Comment by codewp** [comment]
@nielslange 

Yes, I would like to allow hide product bundle items to the plugin users. It is asked by our customers for the product bundle plugin.

They would like to show only parent products and hide bundle items.

Please let me know if you have any questions.

**Comment by tarunvijwani** [comment]
Started an internal discussion: p1684244612336819-slack-C8X6Q7XQU

**Comment by tarunvijwani** [comment]
Hi @codewp you can extend the `CartItem` in store API to include something in the `extensions` array that signals whether it should be hidden.

To implement this on the front-end, you can utilize the `registerCheckoutFilters` function and register a filter for `cartItemClass`. If the extensions object for that specific cart item indicates that it should be hidden, you can apply a specific CSS class to hide it.

**Comment by tarunvijwani** [comment]
Here are some helpful documents and example code:
- https://github.com/woocommerce/woocommerce-blocks/blob/trunk/packages/checkout/filter-registry/README.md
- https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/checkout-block/available-filters.md 
- Example code: https://gist.github.com/opr/a20131566397017c4a35eb6f2f5143bf

**Comment by opr** [comment]
@codewp Hopefully the examples above are helpful to you! I will close this issue now because it looks like it can be solved using tools we already provide, however if you're stuck or need further help, please feel free to reopen it. Please also feel free to join the [WooCommerce Community Slack](https://woocommerce.com/community-slack/)!
