### ISSUE TITLE
Free and paid shipping options displayed incorrectly in checkout with coupon code

### ISSUE THREAD

**Issue by dennisjonda** [woocommerce/woocommerce-gutenberg-products-block#9395]
## Describe the bug

I discovered a bug that affects the checkout process. Specifically, when a coupon code is applied that breaks the free shipping threshold, the checkout page incorrectly displays both the free shipping and paid shipping option, rather than showing only the free shipping option.

In my particular case, I entered a coupon code that reduced the free shipping threshold. The checkout page displayed the free shipping option, but it was still possible to select and pay for the paid shipping option if desired.

This bug can be confusing for customers who may not realize that they are still able to select and pay for the paid shipping option, even when the free shipping option should be the only one displayed. This can lead to customers inadvertently paying for shipping when they expected it to be free, resulting in incorrect shipping charges being applied to orders.

## To reproduce

1. Set up a product that qualifies for free shipping above a certain threshold.
2. Add a coupon code that reduces the total price below the free shipping threshold.
3. Proceed to checkout and observe that both shipping options are displayed, despite the fact that paid shipping should be not showing.

## Expected behavior

The checkout page should only displays the free shipping option when a coupon code reduces the free shipping threshold.

## Screenshots
![grafik](https://user-images.githubusercontent.com/74372535/236885474-c0c52792-1f94-4b64-b9ff-eb2d52718b10.png)

### WordPress (please complete the following information):

-   WordPress version: 6.2
-   WooCommerce version: 7.6.1
-   WooCommerce Blocks version: 10.1.0
-   Site language: German, English
-   Any other plugins installed: Reproduced this Bug with only WooCommerce and Elementor

### Desktop (please complete the following information):

-   OS: Windows
-   Browser: chrome, firefox
-   Version 11

### Smartphone (please complete the following information):

-   Device: iPhone 14 Pro
-   OS: iOS
-   Browser chrome, firefox 
-   Version 16.4.1 (a)

**Comment by wavvves** [comment]
Hi @dennisjonda, thank you for reporting this. 
Just to clarify the fix that should be implemented here, if the total price is brought down below the free shipping threshold, shouldn't the paid option be the only one displayed?
Commonly, shipping rates are applied after taxes and discounts.

**Comment by tarhi-saad** [comment]
Hey there, @dennisjonda! As we have been waiting to hear back from you for over two weeks, I will proceed to close this issue. But if you'd like to continue the discussion, feel free to leave a comment, and we'll reopen it. 🙌
