### ISSUE TITLE
Add WooCommerce Blocks to checkout/order-pay page

### ISSUE THREAD

**Issue by dennisjonda** [woocommerce/woocommerce-gutenberg-products-block#9397]
## Is your feature request related to a problem? Please describe.
Yes, the problem is that the current checkout/order-pay page uses the old WooCommerce checkout design, which may not provide the best user experience and doesn't match the aesthetics of WooCommerce Blocks.

## Describe the solution you'd like
I would like to update the design of the checkout/order-pay page to be consistent with the WooCommerce Blocks' style. This will provide a more modern and visually appealing interface for customers to view their order details and make payments. The updated design should include all the necessary elements, such as order summary, payment method selection, and billing information.

## Describe alternatives you've considered
An alternative solution would be to create a custom checkout/order-pay page with a design that matches the WooCommerce Blocks' style. However, this could be more time-consuming and may not be as easy to maintain or update compared to updating the existing page.

Another option could be to use third-party plugins or extensions to achieve a similar design, but this might introduce compatibility issues and may require additional maintenance efforts.

## Additional context
Updating the design of the checkout/order-pay page to match the WooCommerce Blocks' style will improve the overall user experience, making it easier for customers to complete their payments. This will also ensure a consistent look and feel across the entire checkout process, reinforcing brand identity and enhancing customer trust.

![grafik](https://user-images.githubusercontent.com/74372535/236898973-4b0b2e26-09fe-440d-bce3-355aafa8a92e.png)

**Comment by nielslange** [comment]
Hello @dennisjonda, 

Thanks for reaching out. We are aware that he WooCommerce Blocks do not support the pay for orders functionality. The following two issues aim to add this functionality to WooCommerce Blocks:

- #9312
- #9380

Given that this issue is a duplicate, I'm going to close it for now. But please keep an eye on the other issues. And if you have any further questions or suggestions, please don't hesitate to create a new issue.
