### ISSUE TITLE
Please activate Razorpay plugin workin with block checkout page.

### ISSUE THREAD

**Issue by dheerajtomar** [woocommerce/woocommerce-gutenberg-products-block#9415]
it is very important and must required to enable indian payment plugin with block checkout .

**Comment by nielslange** [comment]
Hello @dheerajtomar,

Thanks for reaching out. We're aware that Razorpay does not offer support for the WooCommerce Blocks. In #6223, we're tracking all reports.

Currently, it's up to payment method extension developers to add support for the new checkout flow offered via the cart and checkout blocks. We have some [documentation on that here](https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs/third-party-developers/extensibility/checkout-payment-methods) and will be publicizing this more in the coming months.

Your best course of action now if you are using a payment method that isn't working with the blocks is to notify the developer of the extension and ask if they can add support. You can reach them directly via https://wordpress.org/support/plugin/woo-razorpay/.

Until then, you can keep on top of the [status of the Cart & Checkout Blocks in this documentation](https://woocommerce.com/document/cart-checkout-blocks-support-status/) as well as #6223.
