### ISSUE TITLE
Mini-Cart block editor sidebar: Cart Drawer image is not adjusted on RTL

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#9421]
The Cart Drawer image we should in the Mini-Cart block editor sidebar is not adapted to RTL languages.

## To reproduce

1. Change your site to a RTL language.
2. Edit a post or page and add the Mini-Cart block.
3. Notice the Cart Drawer image shows the Mini-Cart opened on the right, even though in RTL sites it opens on the left.

![imatge](https://github.com/woocommerce/woocommerce-blocks/assets/3616980/084900d0-21c1-4a82-a867-1d8c3d8a2371)

## Expected behavior

The Cart Drawer in the image should be opened on the left in stores using a RTL language.

**Comment by Aljullu** [comment]
Hey @roykho, I see this issue was closed, but it was making reference to the `Cart Drawer` asset, this one:

![imatge](https://github.com/woocommerce/woocommerce-blocks/assets/3616980/9e8580f7-27d7-4fa2-98ea-3f709690cd4b)

I see it's still not adapted to RTL languages. Should we reopen this issue?

**Comment by roykho** [comment]
@Aljullu - I see. So it wasn't clear to me from reading the description. I thought it was only the icon that needed to switch and that is what I fixed. I am thinking you meant the preview?

But nonetheless, the fixing of the icon was also needed as that's how it behaves in other places. I will open a PR to get that preview fixed today.

**Comment by Aljullu** [comment]
Sorry if the issue description wasn't clear enough! :pray: 

> But nonetheless, the fixing of the icon was also needed as that's how it behaves in other places.

Yup, I agree. :100:
