### ISSUE TITLE
Featured Product/Category blocks: text color transparency is not correctly applied in the editor

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#9424]
Changing the opacity of the text color in the Featured Product and Featured Category blocks doesn't have any effect in the block in the editor.

## To reproduce

1. Add the Featured Product or Featured Category block to a post or page.
2. Change the text color styles to a transparent color.
3. Notice the color becomes white, but still full opacity:

![imatge](https://github.com/woocommerce/woocommerce-blocks/assets/3616980/c33bcf9f-2371-478a-a37a-837fba2bbb73)

## Expected behavior

If the text color is transparent, the text should be invisible.

**Comment by roykho** [comment]
I think I am reproducing this correctly. It seems to work on my end?

https://github.com/woocommerce/woocommerce-blocks/assets/2132595/cbbf9e71-ece9-45e6-b1f6-2646624b7afe

**Comment by Aljullu** [comment]
> I think I am reproducing this correctly. It seems to work on my end?

Oooh, now it seems to work for me as well. Not sure if I did something wrong when testing or maybe it got fixed by something else. Closing anyway. Thanks for testing @roykho!
