### ISSUE TITLE
Product Rating Block > Enable individual customization of the stars and rating text

### ISSUE THREAD

**Issue by nefeline** [woocommerce/woocommerce-gutenberg-products-block#9438]
Based on @shaunandrews feedback on https://github.com/woocommerce/woocommerce-blocks/pull/9347#issuecomment-1538714088 : we need to ensure the text and the star ratings can have their colors changed separately (currently, their color customization is combined).

Before:
<img width="878" alt="Screenshot 2023-05-11 at 12 44 40" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/8df89738-615a-41bd-ac0c-e58de7468d97">

After:

<img width="277" alt="Screenshot 2023-05-11 at 12 46 16" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/c2ac069a-019a-4ce6-8afd-fccdd937fadf">

**Comment by nefeline** [comment]
I'm unassigning myself from this issue so @albarin can work on it as I'm switching focus to the Store Customization project that is now gaining momentum 🙌 !

**Comment by albarin** [comment]
`Product Rating Stars` and `Product Rating Counter` blocks were added in: https://github.com/woocommerce/woocommerce-blocks/pull/10148 and https://github.com/woocommerce/woocommerce-blocks/pull/10114
