### ISSUE TITLE
Mini-Cart Contents block is not scrollable in Site View, even though a scrollbar is visible

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#9439]
Issue initially reported by @annezazu in peapX7-2k4-p2#comment-2855.

## To reproduce

1. Go to Appearance > Editor > Template Parts > Mini Cart.
2. Notice there is a scroll bar inside the Mini Cart Contents block but it's not scrollable. That might be confusing for users.

![imatge](https://github.com/woocommerce/woocommerce-blocks/assets/3616980/cf2feacc-4f98-494c-8fec-e24dbdf5587a)

## Expected behavior

We should either:

1. Hide the scrollbar so it's clear that the Mini Cart Contents block is not scrollable.
2. Allow users to scroll it.

**Comment by roykho** [comment]
I am not able to reproduce this can you please confirm again:
![KyxU58.gif](https://github.com/woocommerce/woocommerce-blocks/assets/2132595/41bd3507-db15-459e-86c8-04d48449be6f)

* WP 6.2.2
* Gutenberg 15.9.0
* Woo Blocks trunk

**Comment by Aljullu** [comment]
> I am not able to reproduce this can you please confirm again:

Your screenshot is after you fully opened the template part. However, the issue refers to the Site View, in other words, when the left sidebar is still open. There is a video in peapX7-2k4-p2#comment-2855 which might help see the issue (starting from 1:00).

**Comment by roykho** [comment]
I see what you mean now. However I personally don't think that is an issue. None of the "preview" is interactive. With the scrollbar showing, it lets user know that they can add more blocks after the cart items and it also shows how it functions when there are more items to display.

**Comment by danieldudzic** [comment]
> I see what you mean now. However I personally don't think that is an issue. None of the "preview" is interactive. With the scrollbar showing, it lets user know that they can add more blocks after the cart items and it also shows how it functions when there are more items to display.

I agree with @roykho. I don't think having a (non-functional) scrollbar present is a deal breaker - it's just a more or less accurate "preview" of the Mini Cart when it has multiple items. Not sure it has to match 1 to 1 the frontend view.

**Comment by Aljullu** [comment]
Right, I don't have a strong opinion either. @annezazu what do you think?

**Comment by annezazu** [comment]
I'm not quite sure it's communicating that "they can add more blocks after the cart items and it also shows how it functions when there are more items to display" fwiw but this isn't a dealbreaker for me. Feel free to close if it's not something to pursue.

**Comment by Aljullu** [comment]
Based on the discussion, I'm going to close this issue. We can always reopen or create a new one if we get more reports of this.
