### ISSUE TITLE
/wc/store/v1/products/:id/variations endpoint

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce-gutenberg-products-block#9445]
## Is your feature request related to a problem? Please describe.
The REST API has a `/products/:id/variations` endpoint that reveals data for all the variations (or specific variations) of a variable product. Is this something being considered for the Store API? 

## Describe the solution you'd like
Parity with the REST API route

## Describe alternatives you've considered
Adding my own custom route. Likely I will go this route for now.

## Additional context
Looking into building out a Variable Mix and Match solution using a React frontend since ajax + lots of templates was extremely slow.

**Comment by nielslange** [comment]
Hello @helgatheviking,

Thanks for your suggestion about adding a /products/:id/variations endpoint to our Store API. We realize this could bring it more in line with the REST API, and potentially simplify its use.

In order to best evaluate your suggestion and understand your particular needs, we would appreciate some additional details:

1. Can you explain why the `/wc/store/v1/products/:id/variations` endpoint holds such significance in your specific use case? Are there particular functions or advantages that this endpoint offers which are not currently available?
2. Our existing Store API endpoint at `/wc/store/v1/products` already includes a variations array for every product. Could you elaborate on why this doesn't fulfil your needs? Are there particular data fields that you require and are not currently provided?

**Comment by helgatheviking** [comment]
Hi @nielslange I'll try to answer as best as I can. Keep in mind that the feature I am working on is still in early development so I'm rubber ducking my way through some things.

1. The REST API route allows me to add additional product meta to each variation's response. example:
```
"mnm_content_source": "categories",
"mnm_child_category_ids": [
    86,
    85
],
"mnm_min_container_size": 24,
"mnm_max_container_size": 24,
"mnm_priced_per_product": false,
"mnm_packing_mode": "together",
"mnm_shipped_per_product": false,
"mnm_weight_cumulative": false,
"mnm_discount": 0,
"mnm_child_items": [
    {
        "child_item_id": 0,
        "child_id": 539,
        "product_id": 539,
        "variation_id": 0,
        "min_qty": 0,
        "max_qty": 24,
        "step_qty": 1,
        "qty": "",
        "availability": {
            "availability": "86 in stock",
            "class": "in-stock"
        },
        "purchasable": true,
        "in_stock": true,
        "price_html": "<span class=\"woocommerce-Price-amount amount\"><bdi>0,00<span class=\"woocommerce-Price-currencySymbol\">&euro;</span></bdi></span>",
        "catalog_visibility": "visible",
        "images": [
            {
                "id": 575,
                "date_created": "2022-04-28T13:32:32",
                "date_created_gmt": "2022-04-28T13:32:32",
                "date_modified": "2022-04-28T13:32:32",
                "date_modified_gmt": "2022-04-28T13:32:32",
                "src": "https://sandbox.lndo.site/wp-content/uploads/2022/04/jumpstory-download20210616-162928-324x389.jpg",
                "name": "jumpstory-download20210616-162928.jpg",
                "alt": "",
                "position": 0
            }
        ],
        "name": "Saint Emilon Grand Cru",
        "permalink": "https://sandbox.lndo.site/product/saint-emilon-grand-cru/",
        "short_description": ""
    },
    {
        "child_item_id": 0,
        "child_id": 541,
        "product_id": 541,
        "variation_id": 0,
        "min_qty": 0,
        "max_qty": 24,
        "step_qty": 1,
        "qty": "",
        "availability": {
            "availability": "81 in stock",
            "class": "in-stock"
        },
        "purchasable": true,
        "in_stock": true,
        "price_html": "<span class=\"woocommerce-Price-amount amount\"><bdi>0,00<span class=\"woocommerce-Price-currencySymbol\">&euro;</span></bdi></span>",
        "catalog_visibility": "visible",
        "images": [
            {
                "id": 577,
                "date_created": "2022-04-28T13:32:42",
                "date_created_gmt": "2022-04-28T13:32:42",
                "date_modified": "2022-04-28T13:32:42",
                "date_modified_gmt": "2022-04-28T13:32:42",
                "src": "https://sandbox.lndo.site/wp-content/uploads/2022/04/jumpstory-download20210616-162856-scaled-1-324x389.jpg",
                "name": "jumpstory-download20210616-162856-scaled-1.jpg",
                "alt": "",
                "position": 0
            }
        ],
        "name": "Red Star Farms Red House Red",
        "permalink": "https://sandbox.lndo.site/product/red-star-farms-red-house-red/",
        "short_description": ""
    }
]
```

This data (esp the `mnm_child_items` result) is needed to render a grid of products whenever a variation is selected. 

![image](https://github.com/woocommerce/woocommerce-blocks/assets/507025/b0cd0616-1bf6-469d-9148-c57cee54de37)

I would like to use the Store API so that I don't have to force the plugin users to generate a key/secret. this is a plugin querying data on the _same site_ so the Store API seems appropriate for that? 

Currently there isn't a way to fetch all the product responses for all the variations (or multiple variations at once.. each variation needs to be fetched independently via `/wc/store/v1/products/:VariationID/

2. As far as I can see the `variations` array returned by the Store API is _very_ limited. It only returns the ID and attributes:
```
{ 
    "id" : 680, 
    "attributes": [
        {
            "name": "Size" 
            "value": "6 pack"
        }
    ]
}
```
This doesn't even include whether the variation is purchasable, no price data, no stock data, description, title, etc. It's also not extensible at all, so this isn't enough to render the associated product grid I have above. I could make an API call to fetch the single product result every time a variation is chosen... and this _does_ work. however, it can sometimes be slow and I found that preloading the rest route (like the cart/checkout does) eliminates the need to run additional `async/await/fetch` type calls from the frontend and the result is super fast rendering. 

```
$rest_route = '/wc/v3/products/' . $product->get_id() . '/variations';
		
Automattic\WooCommerce\Blocks\Package::container()->get( Automattic\WooCommerce\Blocks\Assets\AssetDataRegistry::class )->hydrate_api_request( $rest_route );
		
$rest_preload_api_requests = rest_preload_api_request( [], $rest_route );

Automattic\WooCommerce\Blocks\Package::container()->get( Automattic\WooCommerce\Blocks\Assets\AssetDataRegistry::class )->add( 'wcMNMVariableSettings', $rest_preload_api_requests[$rest_route]['body'] ?? [] );
```

**Comment by wavvves** [comment]
> This doesn't even include whether the variation is purchasable, no price data, no stock data, description, title, etc. It's also not extensible at all, so this isn't enough to render the associated product grid I have above. I could make an API call to fetch the single product result every time a variation is chosen

Hi @helgatheviking, have you tried batching the individual variation requests together? That would reduce the overhead for request/response times, because only one request would be made.

**Comment by helgatheviking** [comment]
@wavvves Thanks for that idea.  That does seem to work in the Store API (setting the product type to variation). I hadn't considered it as I think it did not work for me with the regular REST API.

**Comment by wavvves** [comment]
Going to be optimistic and close the issue for now, if you bump into any blockers, we'll reopen it again 🙂

**Comment by helgatheviking** [comment]
Was able to fetch the variations this way:

```
$request  = new \WP_REST_Request( 'GET', "/wc/store/v1/products" );

$request->set_query_params(
array(
	'type'      => 'variation',
	'per_page'	=> 0,
	'include'	=> $product->get_visible_children(),
	'order'     => 'asc',
	'orderby'	=> 'id',
)
);

$response = rest_do_request( $request );
```

Good enough for now.
