### ISSUE TITLE
Featured category block: Forced button

### ISSUE THREAD

**Issue by strarsis** [woocommerce/woocommerce-gutenberg-products-block#946]
**Is your feature request related to a problem? Please describe.**
Currently, the featured category block forces a button as its content.

**Describe the solution you'd like**
Allow empty featured category block content or at least something different than a button.

**Comment by strarsis** [comment]
Is there a way to make the button inside the Featured category block optional so 
it can be just the title of the category?

**Comment by nerrad** [comment]
This request will be possible as a part of future work migrating our existing blocks to use inner blocks so there's more control over what is shown. No ETA on when that work will be done but since it's accommodated by that planning I'm going to close this issue.

Thanks for the suggestion!
