### ISSUE TITLE
Can't update customer information on the pay for order page

### ISSUE THREAD

**Issue by hsingyuc** [woocommerce/woocommerce-gutenberg-products-block#9461]
## Is your feature request related to a problem? Please describe.
On the pay-for-order page, if a shopper updates their information, the checkout page will render an empty cart error.

## Describe the solution you'd like
Add a new `OrderUpdateCustomer` endpoint.  If it's a pay-for-order, in the redux store action `updateCustomerData`, we call the `OrderUpdateCustomer` endpoint instead of `/wc/store/v1/cart/update-customer` 

## Describe alternatives you've considered
When calling `updateCustomerData`, we can call the order's endpoint again instead of receiving cart items from the update customer endpoint.

## Recording

https://github.com/woocommerce/woocommerce-blocks/assets/56378160/20af238f-6b46-4ace-8617-9fc503bc0101

**Comment by tarunvijwani** [comment]
@hsingyuc I see you have assigned this issue to yourself. Do you need any help from our team to work on it?

**Comment by hsingyuc** [comment]
@tarunvijwani Hi Tarun!  Sorry, I saw your message just now.  Thank you for the offer!  I have two PRs for adding and hookup the endpoint.  It would be nice to have someone review them when they are ready for review.  Thanks again!

**Comment by hsingyuc** [comment]
I'm closing this issue based on our discussion here p1689368341767149-slack-C04NWH6NDHA
