### ISSUE TITLE
Set image size (option)

### ISSUE THREAD

**Issue by strarsis** [woocommerce/woocommerce-gutenberg-products-block#947]
Related to https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/247.

It would be great if the user or theme is able to set the image size to be used by the block.
This is also necessary for the categories block. Some blocks use a shortcode method which in turn doesn't specifically allow setting the image size.

**Comment by Aljullu** [comment]
Hi @strarsis, in recent versions we changed how the blocks' markup is generated, so they are no longer using shortcodes but instead use a custom markup. You can change the image size with CSS. Hope that helps!
