### ISSUE TITLE
Gift card field option above the credit card on checkout (is in the other column)

### ISSUE THREAD

**Issue by Threadcrapper** [woocommerce/woocommerce-gutenberg-products-block#9476]
## What do you like about the Cart & Checkout blocks?
Looks great 
## What do you think is missing from the Cart & Checkout blocks?
Option to move Gift Card block to above the Credit Card - otherwise people run their card, then want a credit because they meant to use the gift card, which is fees (and reputation) from the credit card company.

Does not work with PluginHive UPS Shipping and Print Label plugin - this prevents my customer from using it, yet.  

Also WooCommerce Gift Card Plugin has a conflict with Elementor Pro > WooCommerce Cart widget - will not apply balance.  I tried to report it, no one seemed interested.  I believe it is shortcode/block related, and a problem with the widget, not the Gift Card plugin.

**Comment by opr** [comment]
Hi there @Threadcrapper thanks for taking the time to provide feedback on the WooCommerce Cart and Checkout blocks! 🙌🏼 

Thanks for the compliment on the blocks, we're happy you think they look great.

Besides that, I see three pieces of other feedback.

> Option to move Gift Card block to above the Credit Card - otherwise people run their card, then want a credit because they meant to use the gift card, which is fees (and reputation) from the credit card company.

I believe this would be better handled by the team responsible for WooCommerce Gift Cards, cc @woocommerce/somewherewarm  so you are aware of this feedback

> Does not work with PluginHive UPS Shipping and Print Label plugin - this prevents my customer from using it, yet.

Thanks for letting us know about this incompatibility. 

These Blocks are designed to optimize for faster checkout and it’s expected that some existing Woo Extensions that integrate with the current checkout flow in WooCommerce core will not work with the blocks.

Currently it’s up to extension developers to add support for the new checkout flow offered via the Cart and Checkout Blocks. We have some [documentation for Third-party developers](https://href.li/?https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs#third-party-developers) and some [Developer Resources](https://href.li/?https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs#developer-resources) available to help with their integration efforts.

> Also WooCommerce Gift Card Plugin has a conflict with Elementor Pro > WooCommerce Cart widget - will not apply balance. I tried to report it, no one seemed interested. I believe it is shortcode/block related, and a problem with the widget, not the Gift Card plugin.

The Elementor Pro > WooCommerce Cart widget is not maintained by us, but by Elementor. I'll ping the @woocommerce/somewherewarm who maintain the Woocommerce Gift Cards plugin so they're aware, but I would also recommend reaching out to [Elementor support](https://elementor.com/support/) to help get that resolved!

I'll close this issue now as there's nothing immediately actionable on our end, but feel free to reach out again if you have further feedback or need help with something else.
