### ISSUE TITLE
MailPoet opt-in checkbox and text missing in block checkout

### ISSUE THREAD

**Issue by openmindculture** [woocommerce/woocommerce-gutenberg-products-block#9560]
## Describe the bug

MailPoet opt-in checkbox and text are missing in block checkout. They are present when using the classic checkout instead (shortcode `[woocommerce_checkout]`.

## To reproduce

Open WordPress Admin on a site that uses MailPoet and WooCommerce. Go to the checkout site. Remove the classic shortcode block as described in [Using the Block-Based Checkout](https://woocommerce.com/document/using-the-new-block-based-checkout/)

## Expected behaviour

There is an opt-in for MailPoet-based newsletters shown to the customers when checking out.

### WordPress (please complete the following information):

-   WordPress version: 6.2.2
-   Gutenberg version (if installed): WordPress 6.2.2 built-in 
-   WooCommerce version: 7.7.0
-   WooCommerce Blocks version: 10.2.0
-   Site language: German
-   Any other plugins installed:
  - MailPoet 4.16.0
  - Germanized Pro 3.6.11
 
### Desktop (please complete the following information):

-   OS: Ubuntu Linux 22.04.2, MacOS Ventura, Windows 11
-   Browsers, Verisons: Google Chrome 113.0, Apple Safari 16.3, Firefox 113.0.1

### Smartphone (please complete the following information):

-   Devices: all tested (iPhone, Android 13, ...)

**Comment by tomxygen** [comment]
I can't reproduce the issue.
First screenshot with mailpoet turned off and second with mailpoet turned on.
<img width="913" alt="Screenshot 2023-05-22 at 7 27 46 PM" src="https://github.com/woocommerce/woocommerce-blocks/assets/47855768/ae135592-e162-4f5e-a7fa-025176541732">
<img width="878" alt="Screenshot 2023-05-22 at 7 28 10 PM" src="https://github.com/woocommerce/woocommerce-blocks/assets/47855768/0bf9b60d-f190-4971-b892-dff182cce439">

**Comment by openmindculture** [comment]
Okay, I have to double check next time (after fixing a PayPal issue with block checkout, and when the development / stage setup works again). Sorry, I will close and hopefully not reopen unless I can reliably reproduce.
