### ISSUE TITLE
Extended settings hidden

### ISSUE THREAD

**Issue by ziembatron** [woocommerce/woocommerce-gutenberg-products-block#96]
Product gallery editor in Extended Settings is being hidden after Publish. I apologize in advance if this is the wrong forum for this comment.

![dev171 robintek com_wp-admin_post php_post 112 action edit](https://user-images.githubusercontent.com/39314695/40079069-9c68754e-5854-11e8-886b-838ca0687759.png)
![woo-commerce-dev-tools](https://user-images.githubusercontent.com/39314695/40079080-a41500a0-5854-11e8-95a0-e31b6460e268.jpg)

**Comment by claudiulodro** [comment]
Upgrade to WooCommerce 3.4. It will disable the Gutenberg editor for products since they are not optimized for Gutenberg yet.
