### ISSUE TITLE
Postcode field is missing on the Checkout block page for some countries

### ISSUE THREAD

**Issue by tarunvijwani** [woocommerce/woocommerce-gutenberg-products-block#9604]
## Describe the bug

This issue was reported on slack: p1684956900749749-slack-C7U3Y3VMY

When placing an order from Nigeria, the postcode field is missing on the Checkout block page, even though it's a required part of the address. Interestingly, the shortcode Checkout page displays the postcode field correctly for Nigeria. 

Further investigation is needed to understand the cause of the problem and determine if they impact other countries as well.

## To reproduce

1. Go to the 'Checkout Block' page.
2. In the shipping address, select Nigeria from the country list. 
3. Notice postcode field is not present. 

## Expected behavior

The checkout block should display the postcode field like the shortcode Checkout page for countries like Nigeria.

**Comment by senadir** [comment]
This seems to be the case from WC Core https://github.com/woocommerce/woocommerce/pull/21056, and I can't see the field on Checkout shortcode, are you sure of that?

<img width="581" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/6165348/7bbfa7fe-548a-448c-9e0e-4c3bc3d8ac58">

**Comment by opr** [comment]
@senadir thanks for posting - on my local site I saw the Postcode field for Nigeria however I made a fresh site and it does not appear, which is in line with our expectations.

I think this issue can be closed, especially after looking at https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-countries.php#L1308-L1316
