### ISSUE TITLE
The styling of CTA buttons in notices is not displaying correctly on legacy themes

### ISSUE THREAD

**Issue by xristos3490** [woocommerce/woocommerce-gutenberg-products-block#9609]
## Describe the bug

After [a recent update](https://github.com/woocommerce/woocommerce/pull/37631) to the WC core that prevents legacy themes from displaying blocks-based CSS classes, like wp-element-button, to reduce the risk/footprint for existing stores.

The new C&C-inspired notices are only [applied to stores that have the Cart and Checkout blocks installed](https://github.com/woocommerce/woocommerce-blocks/pull/8659/files#diff-482cf4016505450d0ba9c4d4665a6a095444fa2b85cc16155275726d5771f60dR52), without checking for an active block theme. This causes a problem with the CTA buttons, which do not appear visually appealing when a merchant has C&C blocks installed in a legacy theme.

I’m thinking of three possible solutions here:
- Re-evaluate core change
- Only apply the new notices _for block themes_ that use C&C blocks
- Adjust the CSS rule that controls the styling of the CTA buttons for the notices to not depend on the `wp-element-button` class.

## To reproduce

1. Go to a store using a legacy theme (e.g., Storefront) and ensure you use at least **WC 7.8-beta1**
2. Enable C&C blocks in the checkout process
3. Go to any single product page and add it to the cart.
4. Check the CTA button in the success notice and see that it's not working as expected.

## Expected behavior

The button should be appearing on the right side of the notice.

## Screenshots

<img width="1220" alt="Screenshot 2023-05-26 at 4 03 32 PM" src="https://github.com/woocommerce/woocommerce-blocks/assets/1105590/d8829960-3441-4181-a8ed-017884c7be75">

**Comment by ralucaStan** [comment]
@pmcpinto I've added this to the list of issues for Cycle 4
