### ISSUE TITLE
Implement a character limit when registering payment methods

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-gutenberg-products-block#9612]
## Describe the bug

In payments settings and block settings, payment methods descriptions show large walls of text. This displaces other payment methods and makes it difficult to read.

## To reproduce

1. Enable Amazon Pay payment method
2. Go to WooCommerce > Settings > Payments or the Checkout block editor.
3. See large wall of text

## Expected behavior

To prevent this from happening in the future, we can implement a character limit of 180 to limit the number of lines of text. This will make the settings copy readable and improve the overall scannability of the pages.

Could this limit be implemented when the payment method is [being registered](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/checkout-payment-methods/payment-method-integration.md#payment-methods---registerpaymentmethod-options-)?

## Screenshots

<img width="666" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/5121465/c60719c6-2ef3-4720-b1ea-02ab72e66834">

<img width="1971" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/5121465/ee3ab7dd-18c0-4750-8172-7ca04a4950f2">

cc @ralucaStan @pmcpinto

**Comment by opr** [comment]
We can add a call to [`wp_trim_words`](https://developer.wordpress.org/reference/functions/wp_trim_words/) here: https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/BlockTypes/Checkout.php#L327 however this only lets you limit by words, not characters. This could be worked-around by extensions using the [`wp_trim_words` filter](https://developer.wordpress.org/reference/hooks/wp_trim_words/).

Alternatively, we could do the check and truncation here: https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/blocks/checkout/inner-blocks/checkout-payment-block/edit.tsx#L85 and also show a JavaScript console warning if the text goes over the prescribed limit.

**Comment by elizaan36** [comment]
Great! the 2nd option seems best, no? Let me know if there's anything I can do to assist.
