### ISSUE TITLE
Optimise GitHub Action for checking Markdown links

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#9625]
While creating https://github.com/woocommerce/woocommerce-blocks/pull/9622, I noticed that the GitHub Action to check links within Markdown files only goes 3 levels deep. As some of our Markdown files are located deeper than three levels, we would not detect broken links in these files.

### Changes

This epic contains the following three issues:

1. Optimise `Check Markdown links` GitHub Action.
2. Fix newly detected broken links.

> **Note**
> The second issue relies on the first issue, meaning they need to be addressed in sequence.

**Comment by samueljseay** [comment]
@nielslange I think this is solved in https://github.com/woocommerce/woocommerce-blocks/issues/10161 ?

**Comment by nielslange** [comment]
@samueljseay Thanks for reaching out. Both this issue and #10161 have been resolved with #10537, which took a slight different approach than initially proposed. I'll close these two issues now.
