### ISSUE TITLE
Optimise `Check Markdown links` GitHub Action

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#9626]
In #9625, I mentioned the following:

> While creating https://github.com/woocommerce/woocommerce-blocks/pull/9622, I noticed that the GitHub Action to check links within Markdown files only goes 3 levels deep. As some of our Markdown files are located deeper than three levels, we would not detect broken links in these files. In addition, I noticed that the GitHub Action, to check for broken links in Markdown files, runs independent if the PR touches Markdown files or not.

This issue aims to apply the following changes to the `Check Markdown links` GitHub Action:

- Remove `max-depth: 3`to detect broken links in all Markdown files
- Remove `use-verbose-mode: ‘no’`, as `no` is the default value, see [configuration](https://github.com/gaurav-nelson/github-action-markdown-link-check/#configuration)
- Exclude Markdown files in `./docs/internal-developers/testing/releases/`

**Comment by hritikchaudhary** [comment]
I don't think we'll be able to exclude ./docs/internal-developers/testing/releases/ md files as excluding files feature is still seems to be in development https://github.com/gaurav-nelson/github-action-markdown-link-check/issues/38
We'll have to check if a workaround is available..

**Comment by roykho** [comment]
> Remove global permissions: {} entry

Note that we should not remove this. It is a security measure put in place as a reset to disallow any permissions for actions that use `secrets.GITHUB_TOKEN` default tokens.

**Comment by nielslange** [comment]
> Note that we should not remove this. It is a security measure put in place as a reset to disallow any permissions for actions that use `secrets.GITHUB_TOKEN` default tokens.

Thanks for mentioning this, @roykho. I have two questions, though:
1. You mentioned that it's for actions that use `secrets.GITHUB_TOKEN`. This particular action is not using `secrets.GITHUB_TOKEN`. Why is that part important in this file?
2. If it's a general security measure, shouldn't all our GitHub Actions have this part?

**Comment by roykho** [comment]
@nielslange So this workflow uses a 3rd party action (https://github.com/woocommerce/woocommerce-blocks/blob/trunk/.github/workflows/check-doc-links.yml#LL20C21-L20C68) and you don't always know what tokens they're implicitly using. So the general security practice is to lock the whole workflow down with no permissions and then ONLY enable the ones needed per job level.

> If it's a general security measure, shouldn't all our GitHub Actions have this part?

Yes all of our actions should have this security measure in place at workflow level. I did a whole security audit on the Woo monorepo awhile back and added this to all workflows. If interested, here is the [PR](https://github.com/woocommerce/woocommerce/pull/36200) for that and it explains in more detail why this was done.

**Comment by nielslange** [comment]
Thanks for providing additional information, @roykho.
