### ISSUE TITLE
Fix newly detected broken links

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#9627]
In #9625, I mentioned the following:

> While creating https://github.com/woocommerce/woocommerce-blocks/pull/9622, I noticed that the GitHub Action to check links within Markdown files only goes 3 levels deep. As some of our Markdown files are located deeper than three levels, we would not detect broken links in these files. In addition, I noticed that the GitHub Action, to check for broken links in Markdown files, runs independent if the PR touches Markdown files or not.

This issue aims to fix all newly detected broken links, once #9626 has been merged.

**Comment by hritikchaudhary** [comment]
List of dead links:

1. FILE: [./docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md) - [✖] #experimental-plugin-flag
2. FILE: [./docs/internal-developers/block-client-apis/checkout/checkout-api.md](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/block-client-apis/checkout/checkout-api.md) - [✖] ../../extensibility/checkout-flow-and-events.md
3. FILE: [./docs/internal-developers/block-client-apis/checkout/checkout-flow-and-events.md](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/block-client-apis/checkout/checkout-flow-and-events.md) -   [✖] #onCheckoutValidation
4.  FILE: [./docs/internal-developers/block-client-apis/checkout/checkout-flow-and-events.md](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/block-client-apis/checkout/checkout-flow-and-events.md) - [✖] https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/block-client-apis/checkout/checkout-api.md
5. FILE: [./docs/internal-developers/testing/cart-checkout/data-stores.md](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/testing/cart-checkout/data-stores.md) - [✖] https://github.com/woocommerce/woocommerce-bookings
6. FILE: [./docs/third-party-developers/extensibility/data-store/payment.md](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/data-store/payment.md) - [✖] #getcurrentstatus
7. FILE: [./docs/third-party-developers/extensibility/hooks/filters.md](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/hooks/filters.md) - [✖] #-woocommerce_add_to_cart_validation 
8. FILE: [./docs/third-party-developers/extensibility/hooks/filters.md](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/hooks/filters.md) - [✖] #-woocommerce_shared_settings
9. FILE: [./docs/third-party-developers/extensibility/hooks/filters.md](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/hooks/filters.md) - [✖] #woocommerce_shipping_-this--id-_is_available
10. FILE: [./docs/third-party-developers/extensibility/hooks/filters.md](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/hooks/filters.md) - [✖] #woocommerce_store_api_product_quantity_-value_type
11. FILE: [./docs/third-party-developers/extensibility/hooks/actions.md](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/hooks/actions.md) - [✖] #woocommerce_blocks_-this--registry_identifier-_registration 
12. FILE: [./docs/third-party-developers/extensibility/hooks/actions.md](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/hooks/actions.md) - [✖] #-woocommerce_check_cart_items
13. FILE: [./docs/third-party-developers/extensibility/hooks/actions.md](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/hooks/actions.md) - [✖] #woocommerce_-product--get_type-_add_to_cart
14. FILE: [./docs/third-party-developers/extensibility/hooks/actions.md](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/hooks/actions.md) - [✖] #-hook

**Comment by hritikchaudhary** [comment]
[1_markdown_link_check (1).txt](https://github.com/woocommerce/woocommerce-blocks/files/12243184/1_markdown_link_check.1.txt)
[log.log](https://github.com/woocommerce/woocommerce-blocks/files/12243189/log.log)

**Comment by hritikchaudhary** [comment]
Hi Niels, I have a question, I'll point the broken links to correct section... what should I do with the links where section itself is missing?
Also could you please assign it to me.
Thanks!

**Comment by nielslange** [comment]
Thanks for reaching out, @hritikchaudhary.

> what should I do with the links where section itself is missing?

If a certain section no longer exists, I'd remove the corresponding link.

> Also could you please assign it to me.

Done. This issue is yours. 😄

**Comment by hritikchaudhary** [comment]
> Done. This issue is yours. 😄

Thanks, it helps me keep track on my project board. 😄
