### ISSUE TITLE
Block error is displayed on clearing customizations for Woo Templates

### ISSUE THREAD

**Issue by nefeline** [woocommerce/woocommerce-gutenberg-products-block#9637]
## Describe the bug

When clearing out the customizations for a WooCommerce template, an error is consistently displayed when accessing it on the editor side:

`Your site doesn’t include support for the "woocommerce/legacy-template" block. You can leave this block intact or remove it entirely.`

This error occurs with and without having the Gutenberg plugin enabled (WordPress version 6.2, WooCommerce 7.8.0 and WooCommerce Blocks 10.4.0).

https://github.com/woocommerce/woocommerce-blocks/assets/15730971/13b80991-582a-481f-aeef-b13202fe9126

## To reproduce

1. Make sure you have a block theme enabled, such as Twenty-twenty three
2. Click on Edit Site
3. Click on Templates and customize any of the Woo's templates: e.g. the Single Product and save the changes
4. Now go back to the Site Editor and under Templates > Manage all templates, click on the ellipsis button and clear all customizations for the Single Product template: wait for the success message to be displayed.
5. Now, without refreshing the page, go back to edit the Single Product template: notice how the `Your site doesn’t include support for the "woocommerce/legacy-template" block. You can leave this block intact or remove it entirely.` is displayed.
6. Now refresh the editor page and verify that the block is rendered without any problems.

## Expected behavior

No block errors should be displayed when accessing any of the Woo templates right after clearing customizations.

### WordPress (please complete the following information):

-   WordPress version: [6.2.2]
-   WooCommerce version: [7.8.0]
-   WooCommerce Blocks version: [10.4.0]

**Comment by nefeline** [comment]
Porting over @gigitux 's comment [over here](https://github.com/woocommerce/woocommerce-blocks/pull/9579#issuecomment-1567065873) as it might be useful for solving this problem:

> It could be depended by [this code](https://github.com/woocommerce/woocommerce-blocks/blob/4b27966dfaad0889956a25d98f8d13bb606722ba/assets/js/blocks/classic-template/index.tsx/#L340-L382).
We register/de-register the block based on the template. There could be something wrong with that logic.

**Comment by nerrad** [comment]
I'm also guessing this is because the site editor is client-side only when navigating between routes so the block isn't registered on initial load maybe?
