### ISSUE TITLE
CSS box-sizing: border-box

### ISSUE THREAD

**Issue by diggeddy** [woocommerce/woocommerce-gutenberg-products-block#965]
Columns wrap to new row on themes that don't spam all elements with box-sizing: border-box; 

ie:

```
html {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}

*, :after, :before {
    -webkit-box-sizing: inherit;
    -moz-box-sizing: inherit;
    box-sizing: inherit;
}
```

There are many themes that don't use this CSS and in support of backward compatibility this CSS cannot be added to a Theme update without potentially 'changing/breaking' the layout of existing sites.

This could be resolved by adding this to the plugin style sheet:

```
.wc-block-grid__product {
    box-sizing: border-box;
}
```

**Comment by Aljullu** [comment]
Thanks for opening this issue @diggeddy. Your proposed solution looks good to me, do you want to create a PR yourself? I can review it myself.

Otherwise, I will create one at the end of this week so the fix is included into the next release.

**Comment by diggeddy** [comment]
@Aljullu thanks for resolving ( sorry missed the request ).

**Comment by Aljullu** [comment]
> @Aljullu thanks for resolving ( sorry missed the request ).

No worries! Thank you for opening the issue. :+1:
