### ISSUE TITLE
Mini Cart returns empty with Tsubaki theme 

### ISSUE THREAD

**Issue by namiokuzono** [woocommerce/woocommerce-gutenberg-products-block#9653]
## Describe the bug

Mini cart is returning empty/blank with our a8c-developed theme Tsubaki. 

## To reproduce

1. Go to https://github.com/Automattic/theme-tsubaki
2. Install the theme on JN or any staging site you have
3. Activate the Tsubaki theme
4. Create 1 test product 
5. Add the test product to Cart
6. Check Mini Cart

## Expected behavior

Mini Cart should not return empty. 

---
This is already being looked into as per - p1685470266460719/1685309678.597189-slack-C7U3Y3VMY

Posting this issue for support teams.

**Comment by ccwalburn** [comment]
Reported here: 6346726-zd-woothemes

**Comment by Aljullu** [comment]
We are working on a fix in https://github.com/woocommerce/woocommerce-blocks/pull/9651 (including #9649 and #9652). In the meanwhile, affected sites have two options:

* Install the latest version of WooCommercew Blocks (recommended).
* Downgrade to WooCommerce 7.7.0.

**Comment by namiokuzono** [comment]
Reported here: 6345596-zd-woothemes

**Comment by marissaexplores** [comment]
[6347068-zen](6347068-zd-woothemes) - Dorna theme
Recommending - install WooCommerce Blocks

**Comment by Aljullu** [comment]
Quick update: the fix has been merged into WC core (https://github.com/woocommerce/woocommerce/pull/38533) and will be released in [WC 7.7.2](https://github.com/woocommerce/woocommerce/actions/runs/5127098792).

**Comment by syhussaini** [comment]
Another report 6349366-zen
Theme - Gizmo by Theme Grill

**Comment by kavyagokul** [comment]
Another one in 6349601-zen . 
Theme - Tsubaki

Installed the Woocommerce blocks plugin as a workaround for now.

**Comment by poeticabdul** [comment]
Reported here 6350144-zd-woothemes

**Comment by thesacredpath** [comment]
Reported here as well: 6352036-zd-woothemes

**Comment by csmcneill** [comment]
Reported in 6352084-zen but with the Zaino theme.

**Comment by Aljullu** [comment]
[WooCommerce 7.7.2](https://developer.woocommerce.com/2023/06/01/woocommerce-7-7-2-fix-release/) has been released with a fix for this. I'll go ahead and close this issue, but please let us know if there are any other reports.
