### ISSUE TITLE
Sale price underlined in single product template

### ISSUE THREAD

**Issue by tomxygen** [woocommerce/woocommerce-gutenberg-products-block#9659]
## Describe the bug

Sale price is underlined in the single product template

## To reproduce

With 2023 theme enabled 
1. create a new product
2. Enable the blockified single product template
4. Add a price and a sale price
5. view the product page

## Expected behavior

The sale price shouldn't be underlined.

## Screenshots

<img width="286" alt="Screenshot 2023-05-31 at 12 03 05 PM" src="https://github.com/woocommerce/woocommerce-blocks/assets/47855768/0e184265-8b7f-4b5d-ae36-91b27c7812c0">

**Comment by gigitux** [comment]
@tomxygen Thanks for opening this issue! I added this issue in the main issue about the Single Product Template. I can confirm that this is different respect classic WC Core template:

| Classic Template | Blockified Template |
|--------|--------|
|![image](https://github.com/woocommerce/woocommerce-blocks/assets/4463174/c9e62330-67ef-4551-b85d-ad3e86de0d84)|![image](https://github.com/woocommerce/woocommerce-blocks/assets/4463174/3ed960f0-4662-48dd-a5bd-cdad2b4c207b)|


I noticed the different styles for the Products block as well:

| Classic Template | Blockified Template |
|--------|--------|
|![image](https://github.com/woocommerce/woocommerce-blocks/assets/4463174/bfe48925-b275-4dd0-b90e-cf081efcc7ef)|![image](https://github.com/woocommerce/woocommerce-blocks/assets/4463174/0a5bfee0-ae69-499d-9ea0-6c498ab25587)|

cc @imanish003 @kmanijak @thealexandrelara 

@shaunandrews, can you confirm that this is a design issue we must fix? Thanks!
