### ISSUE TITLE
Mini Cart can't initiate

### ISSUE THREAD

**Issue by dGdev77** [woocommerce/woocommerce-gutenberg-products-block#9660]
Hello!

I am setting up a Store based on the theme TwentyTwentyTwo Block Theme.
Everything worked fine, but suddenly the mini cart can't initiate anymore.

I get this error:

[Error] TypeError: undefined is not an object (evaluating 'window.wp.hooks')

	(anonyme Funktion) (deprecated.min.js:2:264)
	Globaler Code (deprecated.min.js:2:776)
[Error] TypeError: undefined is not an object (evaluating 'window.wp.deprecated')

	(anonyme Funktion) (dom.min.js:2:8005)
	Globaler Code (dom.min.js:2:13082)
[Error] TypeError: undefined is not an object (evaluating 'r.a.use')

	165 (wc-blocks-middleware.js:1:1402)
	n (wc-blocks-middleware.js:1:161)
	(anonyme Funktion) (wc-blocks-middleware.js:1:957)
	Globaler Code (wc-blocks-middleware.js:1:967)
[Error] TypeError: undefined is not an object (evaluating 'wp.i18n.setLocaleData')

	(anonyme Funktion) (broetchen:4)
	Globaler Code (broetchen:5)
	appendChild
	d (mini-cart-frontend.js:1:2449)
	(anonyme Funktion) (mini-cart-frontend.js:1:2577)
	Promise
	i (mini-cart-frontend.js:1:2546)
	(anonyme Funktion) (mini-cart-frontend.js:1:3323)
[Error] TypeError: undefined is not an object (evaluating 'P.__')

	158 (wc-blocks-data.js:1:20499)
	r (wc-blocks-data.js:1:155)
	(anonyme Funktion) (wc-blocks-data.js:1:951)
	Globaler Code (wc-blocks-data.js:1:961)
[Error] TypeError: undefined is not an object (evaluating 'o.__')

	(anonyme Funktion) (a11y.min.js:2:1506)
	d (a11y.min.js:2:1837)
	n (dom-ready.min.js:2:375)
	(anonyme Funktion) (a11y.min.js:2:2434)
	Globaler Code (a11y.min.js:2:2471)
[Error] TypeError: undefined is not an object (evaluating 'wp.i18n.setLocaleData')

	(anonyme Funktion) (broetchen:4)
	Globaler Code (broetchen:5)
	appendChild
	d (mini-cart-frontend.js:1:2449)
	(anonyme Funktion) (mini-cart-frontend.js:1:2577)
	Promise
	i (mini-cart-frontend.js:1:2546)
	(anonyme Funktion) (mini-cart-frontend.js:1:3323)
[Error] TypeError: undefined is not an object (evaluating 'r.__')

	(anonyme Funktion) (blocks-checkout.js:1:35068)
	n (blocks-checkout.js:1:157)
	(anonyme Funktion) (blocks-checkout.js:1:82404)
	n (blocks-checkout.js:1:157)
	(anonyme Funktion) (blocks-checkout.js:1:953)
	Globaler Code (blocks-checkout.js:1:963)
[Error] TypeError: undefined is not an object (evaluating 'n.CURRENCY')

	164 (price-format.js:1:1177)
	t (price-format.js:1:154)
	(anonyme Funktion) (price-format.js:1:950)
	Globaler Code (price-format.js:1:960)
[Error] TypeError: undefined is not an object (evaluating 'i.__')

	(anonyme Funktion) (blocks.min.js:3:104327)
	(anonyme Funktion) (blocks.min.js:10:50180)
	Globaler Code (blocks.min.js:10:50218)
[Error] TypeError: undefined is not an object (evaluating 'u.__')

	(anonyme Funktion) (components.min.js:32:190954)
	(anonyme Funktion) (components.min.js:39:27397)
	Globaler Code (components.min.js:39:27439)
[Error] Unhandled Promise Rejection: TypeError: o() is not a function. (In 'o()({path:"/wp/v2/users/me?context=edit"})', 'o()' is undefined)

	(anonyme Funktion) (preferences-persistence.min.js:2:1338)
[Error] TypeError: undefined is not an object (evaluating 's.addFilter')

	(anonyme Funktion) (block-editor.min.js:26:27907)
	(anonyme Funktion) (block-editor.min.js:41:157613)
	Globaler Code (block-editor.min.js:41:157656)
[Error] TypeError: undefined is not an object (evaluating 'wp.i18n.setLocaleData')

	(anonyme Funktion) (broetchen:4)
	Globaler Code (broetchen:5)
	appendChild
	d (mini-cart-frontend.js:1:2449)
	(anonyme Funktion) (mini-cart-frontend.js:1:2577)
	Promise
	i (mini-cart-frontend.js:1:2546)
	(anonyme Funktion) (mini-cart-frontend.js:1:3323)
[Error] TypeError: undefined is not an object (evaluating 'o.getSetting')

	(anonyme Funktion) (mini-cart-component-frontend.js:1:18656)
	o (mini-cart-component-frontend.js:1:371)
	(anonyme Funktion) (mini-cart-component-frontend.js:1:5296)
	o (mini-cart-component-frontend.js:1:371)
	(anonyme Funktion) (mini-cart-component-frontend.js:1:14581)
	o (mini-cart-component-frontend.js:1:371)
	(anonyme Funktion) (mini-cart-component-frontend.js:3:45730)
	o (mini-cart-component-frontend.js:1:371)
	(anonyme Funktion) (mini-cart-component-frontend.js:1:3069)
	Globaler Code (mini-cart-component-frontend.js:1:3079)

I am absolutely clueless how i caused the problem.
The last things I did before this started was to install WooCommerce Stripe Payment Gateway Plugin and setting up a Shipping Zone.

I tried to deactivate all Plugins, removes all actions and filters, cleared all Transients and Browser Cache. 
The Problem still persists with only the WooCommerce Plugin active. 

What else can I do to get things running again ?

Thank you for your help.

Best regards,
David

**Comment by dGdev77** [comment]
Turns out it is an issue of WooCommerce 7.7.1 
Downgraded to 7.7.0. Now the mini-cart works again.
But as it turns out only if the Stripe Payment Gateway Plugin is deactivated.

**Comment by Aljullu** [comment]
Hi there, @dGdev77, thanks for opening this issue. You are right, they are two different issues which were present in 7.7.0 and 7.7.1 and that will be fixed in 7.7.2, which will be released in the next hours. In the meanwhile, you can install the latest version of [WC Blocks](https://wordpress.org/plugins/woo-gutenberg-products-block/), which should fix the issue. Please let us know if it doesn't for you.

> Stripe Payment Gateway Plugin

Just to confirm, you are referring to this one, right?

https://wordpress.org/plugins/woocommerce-gateway-stripe/

**Comment by dGdev77** [comment]
Yes. The Stripe Gateway Plugin is the one that started the problem.
But in the meantime I have also installed the standard WooCommerce Payments. And with this plugin active I also have problems. In this setup the Mini Cart gets filled and shows content. But the items in the cart do not persist. When I add another item what is in the cart gets lost.

**Comment by Aljullu** [comment]
Thanks for providing more details, @dGdev77!

>  But in the meantime I have also installed the standard WooCommerce Payments. And with this plugin active I also have problems. In this setup the Mini Cart gets filled and shows content. But the items in the cart do not persist. When I add another item what is in the cart gets lost.

Is that affecting the Cart in general or only the Mini-Cart block? Ie: is the Cart block or Cart shortcode also affected? If so, it might be better to fill the issue in [WC core repo](https://github.com/woocommerce/woocommerce) or [WooCommerce Payments repo](https://github.com/Automattic/woocommerce-payments), with step-by-step reproduction instructions.

Btw, did you get the chance to test with WC Blocks to see if the error was resolved?

**Comment by kmanijak** [comment]
Considering there was no response for the last 2 weeks I'll go ahead and close this issue. Keep in mind the closed issue can be still commented on if necessary 🙌
