### ISSUE TITLE
Prevent mini-cart container from scrolling overflowed content on the x axis

### ISSUE THREAD

**Issue by xristos3490** [woocommerce/woocommerce-gutenberg-products-block#9669]
### Description

The mini-cart container has a scroll bar on the x axis which needs to be removed.

### Screenshot
![](https://cdn-std.droplr.net/files/acc_1208648/20SyIs)

### Steps to replicate

1. Use a block theme like TT3.
2. Add a product to the cart.
3. Open the mini-cart block and notice the scrollbar.

cc @Aljullu

**Comment by Aljullu** [comment]
Good catch, @xristos3490! ~I can reproduce in GNOME Web (which uses the same rendering engine as Safari), but not in Chrome or Safari.~ Actually, I think it's only reproducible if your OS/browser displays scrollbars.

**Comment by xristos3490** [comment]
> Actually, I think it's only reproducible if your OS/browser displays scrollbars.

That's true! I was using Safari when I saw this. Indeed, I can't replicate it in Chrome!
