### ISSUE TITLE
Loads backend scripts on frontend 

### ISSUE THREAD

**Issue by cannap** [woocommerce/woocommerce-gutenberg-products-block#97]
Hi when i enable this plugin it load lodash react react-dom tinimyce and such stuff on my frontend when i disable it removes

**Comment by claudiulodro** [comment]
Good catch. Thanks for the report. Fixed in https://github.com/woocommerce/woocommerce-gutenberg-products-block/commit/77b5f48eed1667e1af0535127e8673a4192d580a
