### ISSUE TITLE
Improving JS handling for blocks for better performance

### ISSUE THREAD

**Issue by asafm7** [woocommerce/woocommerce-gutenberg-products-block#9711]
Also reported here: https://github.com/woocommerce/woocommerce-blocks/discussions/8166#discussioncomment-6082410.

When adding WooCommerce Filter by Attributes block to a non-WooCommerce page, these 4 files are being enqueued:

![image](https://github.com/woocommerce/woocommerce-blocks/assets/14274769/926aa086-7fe8-4b0e-b2e5-35cddccb0046)

Dequeuing either one of these files breaks the Filter by Attributes block. Although "blocks-checkout", for example, isn't semantically related.

Maybe they are bound as dependencies.

Loading 0.5 MB of JS just to have a simple filter functionality (which isn't even an Ajax filter) feels redundant.

Maybe there is a better way to achieve it?

**Comment by tarhi-saad** [comment]
Hello, @asafm7! 👋 Thank you for reporting this issue! 🙌 From [this comment](https://github.com/woocommerce/woocommerce-blocks/discussions/8166#discussioncomment-6099553), I see that the problem has been resolved! I'll close this issue, but if the problem remains, please reopen it.
