### ISSUE TITLE
Add new event properties to product checkout and purchase Tracks events

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-gutenberg-products-block#9729]
**Description:** we want to add new event properties to the woocommerceanalytics_product_checkout and woocommerceanalytics_product_purchase Tracks events to develop a better understanding of the options that stores have available on cart and checkout, how shoppers interact with them, and how this impacts conversion.
The events are triggered through the woocommerce-analytics module. This will need to be implemented in the Jetpack repo. More info about prior art here: pb0Spc-ou-p2#comment-701

- [ ] Add the following event properties to the `woocommerceanalytics_product_checkout` event
`shipping_option`: the selected shipping option 
`products_count`: number of products included in the cart
`coupon_used`: if the coupon was used (boolean)
`order_value`: the order value/total
`template_used`: if the proceed from cart to checkout action has happened on a regular cart page or powered by the template
`additional_blocks`: if there are additional blocks on the cart page
`store_currency`: the currency used in the store

- [ ] Add the following event properties to the `woocommerceanalytics_product_purchase` event
`shipping_option`: the selected shipping option 
`products_count`: number of products included in the cart
`coupon_used`: if the coupon was used (boolean)
`order_value`: the order value/total
`template_used`: if the proceed from cart to checkout action has happened on a regular cart page or powered by the template
`additional_blocks`: if there are additional blocks on the cart page
`store_currency`: the currency used in the store

- [ ] Check if the `express_checkout` property is working as expected in both events

**Comment by opr** [comment]
@pmcpinto - looking at the `coupon_used` property, it is unclear whether this should be a boolean or if you want a list of all coupons applied on that cart?

Also, if we're tracking `order_value` do you want to track the store currency too?

**Comment by pmcpinto** [comment]
> @pmcpinto - looking at the coupon_used property, it is unclear whether this should be a boolean or if you want a list of all coupons applied on that cart?

It should be a boolean.

> Also, if we're tracking order_value do you want to track the store currency too?

Store currency can be a nice addition. I'll update the acceptance criteria. Thanks

**Comment by opr** [comment]
Similar to the discussion in https://github.com/woocommerce/woocommerce-blocks/issues/9250#issuecomment-1697827620 regarding

> `shipping_option`: the selected shipping option

We may not know this at the point the `woocommerceanalytics_product_checkout` is recorded.

Also, it's possible that there will be multiple packages each with its own shipping option, so I feel we should record this as an array at all times, with one entry per package (there will always be at least one package if there's a shippable product), and an empty array if only virtual products are in the cart.

**Comment by pmcpinto** [comment]
Let's go with an array. Thanks!

**Comment by pmcpinto** [comment]
hey @opr when will this be merged and shipped?

**Comment by opr** [comment]
Hey @pmcpinto it's currently being reviewed in Jetpack, https://github.com/Automattic/jetpack/pull/33544 - there's an issue with E2E tests but when we resolve that it should be shipped with the next Jetpack release, I think that'll be next month now.

**Comment by pmcpinto** [comment]
Thanks for the update!

**Comment by opr** [comment]
@pmcpinto https://github.com/Automattic/jetpack/pull/33544 has been merged
