### ISSUE TITLE
Local pick admin instrumentation

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-gutenberg-products-block#9731]
**Description:** The Rubik's Zenhub board doesn't include Core issues, so I'm opening this issue to ensure the team doesn't miss this one in the Core repo about adding instrumentation to the Admin page of the new local pickup experience powered by the Cart and Checkout blocks: https://github.com/woocommerce/woocommerce/issues/37699

**Comment by senadir** [comment]
This is done by 10841
