### ISSUE TITLE
MINI CART IN CART AND CHECKOUT PAGES

### ISSUE THREAD

**Issue by AltanOzkan** [woocommerce/woocommerce-gutenberg-products-block#9740]
<img width="281" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/25936195/9214d11f-4cac-41b4-96e8-4313e57273d5">

I don't want to hide or remove mini cart icon at card and checkout pages. I think there should be option for this. Thank you.

**Comment by webaxones** [comment]
Same here: I looked for an option to keep it.

**Comment by albarin** [comment]
Hi @AltanOzkan and @webaxones for reaching out. I'm linking to [this issue](https://github.com/woocommerce/woocommerce-blocks/issues/7760) for more context on the decision.
I think there's some discussion around this lately, mentioning @Aljullu and @pmcpinto, in case they have some input.
Thanks 🙏

**Comment by Aljullu** [comment]
Thanks for opening this issue, @AltanOzkan, and for the additional comment, @webaxones. I'm going to close it in favor of woocommerce/woocommerce#42352, which seems to be about the same, so we can keep the conversation in one single place.
