### ISSUE TITLE
Block Directory inclusion explorations (Design & Technical)

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#975]
This issue is intended to track explorations (both technical and design) for how WooCommerce blocks will be discovered/used within the pending new WordPress Block Directory coming to Gutenberg.

#### WP.org related

- [Project Overview - design](https://make.wordpress.org/design/2019/04/26/block-library-installing-blocks-from-within-gutenberg/)
- [Block Type Registration RFC](https://github.com/WordPress/gutenberg/blob/master/docs/rfc/block-registration.md)
- [Original Project Launch Post](https://make.wordpress.org/meta/2019/03/08/the-block-directory-and-a-new-type-of-plugin/)
- [Block Registration - Assets JSON structure](https://github.com/WordPress/gutenberg/pull/13693#issuecomment-491814028)
- [Block Directory Issues (also repo)](https://github.com/WordPress/block-directory/issues) and [Block Directory Project Board](https://github.com/WordPress/block-directory/projects/1)
- [Pull Implementing initial Block Directory discovery/install via Block Picker](https://github.com/WordPress/gutenberg/pull/17431)

cc @jwold for reference.

**Comment by jwold** [comment]
@nerrad my sense is there's value in waiting to see where the work is likely to land from the .org team. We could start playing with things earlier, and share that back to the team with our own insights, but it could mean additional work later. I'm happy to start on this now if we think it's a priority, but would recommend waiting. Thoughts?

cc @pmcpinto

**Comment by nerrad** [comment]
> I'm happy to start on this now if we think it's a priority, but would recommend waiting.

I agree it's still early for any definite plans.  I mostly just created this as a tracking issue for explorations/experiments.  There's a couple things I think we may want to influence the direction on for what is final in core:

- Grouping by product (i.e. All Woo blocks etc).
- Limiting blocks to only be downloaded as part of a group (or communicating dependencies somehow).

So I don't think we need to prioritize building specific interfaces yet, but should experiment here and there with what we'd _like_ to see so it can help influence (hopefully) the end result in core.

Ideally, I think it could be to our benefit to have something ready to launch when this does land in WP core.

**Comment by nerrad** [comment]
I just noticed Mike added it to the Design/Planning Sprint in Zenhub - might be too early for that?  I'll let Pedro weigh in here :)

**Comment by jwold** [comment]
Great thoughts! I'm ok with starting earlier if we all agree, but otherwise definitely agree to making sure we're ready when it lands in core.

**Comment by pmcpinto** [comment]
Do we already know when the block directory is going to be ready for prime time? I notice that 6.5 already includes an experiment around this (https://github.com/WordPress/gutenberg/pull/17431), but I'm not finding any estimation for when the "final" version is going to be ready.

I think we should wait at least until sprint 25 ends. My biggest concern is how long is going to take us on the technical side to adapt our plugin to this single block paradigm.

This could be a useful exploration for that cool-down period after a 4-6 week cycle we talked about. Btw, I have to draft the post about that to see if we all agree with that approach and we take it from there.

**Comment by nerrad** [comment]
> I think we should wait at least until sprint 25 ends. My biggest concern is how long is going to take us on the technical side to adapt our plugin to this single block paradigm.

Some of the bits and pieces needed to support the new block directory are _already_ implemented in Gutenberg core (namely `block.json` configs).  Since that will help with the refactoring I'm doing anyways for block loading, I can do that part without waiting for the main block directory to land.

For the rest, I agree we can wait until sprint 25 ends.  I mostly just wanted to document this issue so it's not forgotten.  I can shift away from doing further explorations (except I'll still implement block.json for block loading).

**Comment by nerrad** [comment]
From [this guidelines doc](https://github.com/WordPress/wporg-plugin-guidelines/pull/68) it looks like we won't be able to utilize the Block Directory for discovery of our blocks unless we're willing to split things up into individual "Block Plugins".

**Comment by jwold** [comment]
> From this guidelines doc it looks like we won't be able to utilize the Block Directory for discovery of our blocks unless we're willing to split things up into individual "Block Plugins".

Thank you for finding that! I wasn't aware of that guidelines restriction. Based on how are individual blocks work now I don't think it'd make sense to split them into individual plugins. So it sounds like we shouldn't go that route.

**Comment by nerrad** [comment]
Ya the guidelines were fairly recently posted.  It definitely changes the relevancy of this issue.  I'm going to close it for now - we can create a new issue if we decide down the road there are certain blocks we want to be discoverable via the block directory but for now I think it's a dead horse.
