### ISSUE TITLE
Delivery method switches from pickup to shipping when new rates are found based on the provided billing address

### ISSUE THREAD

**Issue by masteradhoc** [woocommerce/woocommerce-gutenberg-products-block#9790]
## Describe the bug
In my shop the Local Pickup is choosen by a person in the cart. When it redirects you to the checkout screen the local pickup option is still preselected and the client starts to fill out the details
1) Contact Information (E-Mail)
2) Shipping Methods - nothing to do
3) Store Location - nothing to do as only one available
4) set a deliveryadress (Name, Prename, Company, Adress) all fine so far
then choose a zipcode and city and it autoamtically changes to the flat rate shipping method
![image](https://github.com/woocommerce/woocommerce-blocks/assets/6242098/189a751e-4f68-4e9d-bb04-8bd7833de601)

## To reproduce

1. Go to /wp-admin/admin.php?page=wc-settings&tab=shipping&section=pickup_location
2. Click on Enable Local Pickup & set a title "Local Pickup"
3. Add a Pickup Location and set only Location Name and Pickup Details
4. go to the cart and choose local pickup
5. follow steps to enter on "Describe a bug"

## Versions
WooCommerce 7.7.2 & WooBlocks 10.4.0

## Expected behavior
stay at local pickup

## Screenshots
see above

**Comment by mikejolley** [comment]
Hi there.

I'm unable to replicate an issue based on your testing instructions. As you say, when you select pickup in cart it does remain selected on checkout. However, on the checkout, I do not get shipping related sections. I get (correctly):

- Pickup Locations
- Billing Address
- Payment

"delivery address" does not exist.

Can you provide more details or screenshots/screencast of what you're seeing?

**Comment by masteradhoc** [comment]
HI @mikejolley 
i now built up a fully new devsite with local to build it up from the beginning. Here are the steps to setup your store:

1) Setup store details at /wp-admin/admin.php?page=wc-settings&tab=general
![image](https://github.com/woocommerce/woocommerce-blocks/assets/6242098/73d8e830-05d9-433d-aa20-8acf40cf6599)
2) set general options like this
![image](https://github.com/woocommerce/woocommerce-blocks/assets/6242098/cd6d4bd6-a7f0-4f4c-ba1f-97e952ed56f8)
3) setup shipping zones with postalcodes, example below
Area 1: f.e. 9487, 9492, 9493, 9469
Area 2: f.e. 9494, 9491, 9488, 9466, 9465, 9473, 9468, 9467, 9472, 9470
![image](https://github.com/woocommerce/woocommerce-blocks/assets/6242098/3fcd6540-3127-4a9d-81bb-e52d91ae98df)
4) setup local pickup
![image](https://github.com/woocommerce/woocommerce-blocks/assets/6242098/ea8eb63d-f9b8-485e-bc67-cb710d83daa1)

Navigate Frontend like this:
https://app.screencast.com/9XZBogaK0rtZs

Hope that clears it up :)

**Comment by mikejolley** [comment]
@ralucaStan Might want to add this to the cycle. It may be more edge case, but could be high impact because it force changes shipping unexpectedly. 

I could replicate this with a single zone for a specific postcode (90210) with a flat rate. If the billing starts as some other postcode, and local pickup is selected in the cart, as soon as you change billing address during checkout to 90210, new rates are loaded and the shipping selection is forced.

**Comment by masteradhoc** [comment]
@mikejolley @ralucaStan any update on this one? It confuses quite a lot of my clients shopusers and leads to a lot lost possible conversions

**Comment by ralucaStan** [comment]
Hey @masteradhoc this issue is already on our list of next tickets to work on. I expect it to be picked up in the next couple of weeks. Thank you for your patience.

**Comment by masteradhoc** [comment]
@ralucaStan @tarunvijwani any ETA on this? Our client still has this issue and this leads to a lot frustrated and overpaying customers which in the checkout is very critical.

**Comment by tarunvijwani** [comment]
@masteradhoc It turned out to be more complex than we initially thought. We're still looking into it. I'll keep you updated once we have the PR ready for it. Thank you!

**Comment by masteradhoc** [comment]
@tarunvijwani how far are we here? Anything i can help with?

**Comment by tarunvijwani** [comment]
@masteradhoc We have a potential solution to the problem in #10457 PR. However, there is a one-edge case with multiple packages that still need to be fixed. Hopefully, we will have the solution by next week. Once PR is merged, I will update you. Thank you for your patience.

**Comment by masteradhoc** [comment]
Thanks for the update @tarunvijwani

**Comment by masteradhoc** [comment]
@tarunvijwani how is the status here? i saw that 11.0.0 was released without the PR.

**Comment by ralucaStan** [comment]
@masteradhoc the PR is still open and that's why it was not released in 11.0.0. 
I'll personally let you know when this is merged and what is the release plan for it.

**Comment by tarunvijwani** [comment]
@masteradhoc We've done more research and discovered that WooCommerce has a default behaviour that resets shipping methods every time an address change occurs. However, we have overridden this behaviour using a filter. I'll update the unit tests for the PR shortly and merge it as soon as possible. Thank you for your patience.

**Comment by masteradhoc** [comment]
@tarunvijwani thanks for the update, appreciate it!

**Comment by tarunvijwani** [comment]
@masteradhoc We have merged the fix to the trunk. It will be available in the next release. 🙂

**Comment by tarunvijwani** [comment]
@masteradhoc The fix has been released in the 11.2.0 version. 🎉
