### ISSUE TITLE
registerCheckoutFilters not applied on frontend in Cart Block

### ISSUE THREAD

**Issue by straightvisions-matthias-bathke** [woocommerce/woocommerce-gutenberg-products-block#9792]
## Describe the bug

The filter registerCheckoutFilters as described in [docs](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/checkout-block/available-filters.md) should be applied on editor screen and frontend screen. Tested on cart block, it is applied on editor screen only, not on frontend screen.

## To reproduce

Register the following script for testing:

```
const { registerCheckoutFilters } = window.wc.blocksCheckout;

registerCheckoutFilters( 'sv-baaboo-custom', {
	cartItemPrice: ( value, extensions, args ) => {
		if ( args?.context !== 'cart' ) {
			// Return early since this filter is not being applied in the Cart context.
			// We must return the original value we received here.
			return value;
		}
		//console.log(args.cartItem);
		return '<price/>'+'test';
	},
	showRemoveItemLink: ( value, extensions, { cartItem } ) => { return false; }
} );
```

Open Page with Cart Block, see changes: String "test" appended to cart item price and delete buttons removed.

Press Save to try to apply new output to frontend.

Check Cart page in frontend - filters are not applied.

## Expected behavior

Filters should apply in editor and frontend.

### WordPress

-   WordPress version: 6.2.2
-   WooCommerce version: 7.6.0
-   WooCommerce Blocks version: tested with and without WooCommerce Blocks v10.4.0
-   Site language: de_DE

**Comment by mikejolley** [comment]
I tested the code you provided and it did work on the frontend, but then I only tested by adding the code to blocks. This does at least confirm filters are executed.

![Screenshot 2023-06-13 at 13 21 13](https://github.com/woocommerce/woocommerce-blocks/assets/90977/02cd178e-25e1-4080-8fa5-de27e7fcca88)

Could it be where your script is placed? Is it enqueued on the frontend?

**Comment by straightvisions-matthias-bathke** [comment]
@mikejolley Script is successfully loaded in backend in Gutenberg Editor:

![image](https://github.com/woocommerce/woocommerce-blocks/assets/4689792/ebdbf759-d7b1-48d4-b8ba-a4f545ceb33b)

Script is not enqueued in frontend but in Gutenberg. I don't think Gutenberg Editor Scripts should be loaded in frontend? :)

I can confirm the wrong behavior with WooCommerce Blocks Plugin updated to v10.4.2

**Comment by mikejolley** [comment]
I'm not sure what you men @straightvisions-matthias-bathke — we're talking about `registerCheckoutFilters` which I confirmed ran in both places. If you have an updated list of steps to reproduce whatever issue you're facing, update your original post and I'll retest.

**Comment by straightvisions-matthias-bathke** [comment]
@mikejolley Thanks for taking your time here. I am glad the issue does not occur on your site. I'll try to isolate the cause of this issue, but until then - at least in my setup - the hook is not working as expected, as filter is performed in Gutenberg but not rendered in frontend.

**Comment by tarhi-saad** [comment]
Hello, @straightvisions-matthias-bathke! 👋 We greatly appreciate you bringing this bug to our attention! 🙌 As we cannot replicate the issue based on the existing testing steps mentioned in the ticket description, could you provide us with updated steps, as suggested by @mikejolley? This will assist us in better understanding and addressing the bug you encountered.

**Comment by mikejolley** [comment]
As its been 2 weeks I am going to close this but feel free to comment back if you find the issue or narrow it down to a specific thing with steps to replicate.

Thanks
