### ISSUE TITLE
"S" instead of empty star in Product Rating in WooCommerce

### ISSUE THREAD

**Issue by kmanijak** [woocommerce/woocommerce-gutenberg-products-block#9826]
### Prerequisites
- Found in WooCommerce v. 7.9.0-dev when testing WC Blocks 10.4.2 included in WC Core

### Steps to reproduce
1. Go to Single Product Template
2. Add Product Rating block if not already added

Expected: There's empty star sign before "No Reviews" text
Actual: There's "S" sign instead

<img width="373" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/20098064/bbbd9da1-76a0-4684-af44-8910c1aa0f6b">

**Comment by gigitux** [comment]
I'm able to replicate only with Gutenberg enabled. We already fix this issue once https://github.com/woocommerce/woocommerce/pull/35532. Maybe GB changed how the fonts are enqueued on the Site Editor. 

I would say to keep this in our repo, but I'm pretty sure we should do the PR on WC Core. cc @danieldudzic that worked on this issue.

**Comment by danieldudzic** [comment]
Seems like @Aljullu removed the fix 😅 

https://github.com/woocommerce/woocommerce/pull/36911

In theory, Albert's code shouldn't be breaking this.

**Comment by danieldudzic** [comment]
I have now opened a PR with a fix in the WooCommerce repo: https://github.com/woocommerce/woocommerce/pull/38769

**Comment by danieldudzic** [comment]
The fix has now been merged into WooCommerce core.
