### ISSUE TITLE
Introduce currency prefix and suffix options to replace current position value.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#983]
This is a followup to #956.  Essentially this will eliminate the need to do conditional outputs for currency strings because one can just do something like `symbolPrefix + value + symbolSuffix`. 

I think this should be a prepped value in the new `wc.wcSettings` export.  That way the original `wcSettings` global doesn't need changed.

**Comment by mikejolley** [comment]
I believe this was an item I suggested. 

Given the restraints in core, and the [more recent price package](https://github.com/woocommerce/woocommerce-gutenberg-products-block/tree/trunk/packages/prices) which derives the suffix/prefix from the Woo core options, I don't think we need to tackle this in settings anymore. One just needs to use the package.

Marking closed.
