### ISSUE TITLE
Product Chessboard pattern improvements

### ISSUE THREAD

**Issue by albarin** [woocommerce/woocommerce-gutenberg-products-block#9845]
- Review image compression and ensure optimal quality.
- Verify if the button colors align with the Global Styles / theme.

**Comment by roykho** [comment]
* Image quality has been handled by [PR](https://github.com/woocommerce/woocommerce-blocks/pull/9803)
* I've checked the button styling and since we're using a white background in the design, I've checked that themes' styles overrides this with their own styles.
