### ISSUE TITLE
Implement a more consistent and descriptive naming structure

### ISSUE THREAD

**Issue by albarin** [woocommerce/woocommerce-gutenberg-products-block#9853]
Discuss and change the names of the patterns. There's already another issue related to that https://github.com/woocommerce/woocommerce/issues/42375

**Comment by roykho** [comment]
With this [community PR](https://github.com/woocommerce/woocommerce-blocks/pull/9814) I think it's a good start towards consistency and I am ok to merge that in to satisfy this task.

**Comment by albarin** [comment]
> With this [community PR](https://github.com/woocommerce/woocommerce-blocks/pull/9814) I think it's a good start towards consistency and I am ok to merge that in to satisfy this task.

Agree, it's a good first step.

**Comment by albarin** [comment]
Fixed by https://github.com/woocommerce/woocommerce-blocks/pull/9814
