### ISSUE TITLE
Accessibility issue with the outline of input fields

### ISSUE THREAD

**Issue by webaxones** [woocommerce/woocommerce-gutenberg-products-block#9861]
Replacing the browser-styled outline on the input fields with a `box-shadow: 0 0 0 1px #50575e;` poses an accessibility problem (in addition to adding difficulty to override the styles):

If we define a border-color: currentColor for the fields, we no longer distinguish the outline, as in this example (focus state).

![image](https://github.com/woocommerce/woocommerce-blocks/assets/17084006/603757b4-9e61-4e7d-95b0-86e49d8c5f4f)

It would be more judicious to use a 1px outline with an outline-offset to distinguish it from the border.
As you know, the colors that browsers apply to outlines are not chosen randomly. They always stand out from the content. So maybe keep that color too instead of current one.

Regarding the difficulty of overriding: it forces to perform 2 types of override (for example the color of the outline), one override of the fields that natively use the outline (the vast majority) and an override of the components of the WC blocks that use a box-shadow, knowing that this box-shadow is not shared but repeated in various places.

:)

**Comment by nielslange** [comment]
Thanks for reaching out, @webaxones. Can you tell me how to reproduce this case and which elements/blocks are affected by that?

**Comment by webaxones** [comment]
Of course!
The example shown in the picture is the form to enter a coupon in the cart block.
My use case is different from this image but the issue is the same: a "focus" state that is too indistinct from the "normal" state.
I have styled my fields with a light gray border. Adding an outline via a 1px box-shadow generates a drop shadow in display, which is not ideal.
Here is the example of my use case: above normal state, below focus state.

![image](https://github.com/woocommerce/woocommerce-blocks/assets/17084006/9b8e41d1-c468-4eca-8fef-c944d3f2ad49)

**Comment by nielslange** [comment]
Thanks for providing additional information. I see that this issue is related to #8227. I'll close this issue for now. Please keep an eye on the other issue.
