### ISSUE TITLE
Re-enable PHP Unit Tests for PHP 8.1 and 8.2

### ISSUE THREAD

**Issue by kmanijak** [woocommerce/woocommerce-gutenberg-products-block#9862]
PHP Unit Tests jobs were failing on every PR. This is most likely due the official WordPress docker images being recently updated (e.g. [WordPress 8.2 image](https://hub.docker.com/layers/library/wordpress/php8.2/images/sha256-49be2e34db386890752ae32edbfb26ccd574267193ac007fe837d26a2a83a7e4?context=explore)) and are now based on debian:12-slim.

That change affected multiple repositories, Gutenberg included. The https://github.com/WordPress/gutenberg/pull/51513 was provided to the @wordpress/env package that unblocks the pipelines for Gutenberg's trunk, but the change is not released yet, hence we cannot update wp-env and have no control over docker-image to apply the changes manually.

To unblock PRs and making pipeline passing the PHP Unit Tests for PHP 8.1 and 8.2 were disabled: https://github.com/woocommerce/woocommerce-blocks/pull/9859. Tests for 7.4 and 8.0 are still running.

The scope of this issue is to:
- keep an eye on `wp-env` releases (check this issue, potentially the out-of-schedule patch release will happen: https://github.com/WordPress/gutenberg/pull/51513)
- once the PHP Unit Tests could run properly, readable them by reverting https://github.com/woocommerce/woocommerce-blocks/pull/9859

**Comment by noahtallen** [comment]
You should be able to re-enable this again! I updated `wp-env` to v8.1.1 on npm today, which includes the fix.
