### ISSUE TITLE
E2E testing for Cart/Checkout/ Order Received Templates

### ISSUE THREAD

**Issue by wavvves** [woocommerce/woocommerce-gutenberg-products-block#9863]
Part of Epic: Cart/Checkout/Order Received Templates https://github.com/woocommerce/woocommerce-blocks/issues/9288

E2E Tests. Blocked by #9289 

Should be merged to epic's main branch.

Note: This issue is detached from the code it tests, as we already have POCs for the mentioned templates.

**Comment by mikejolley** [comment]
Things that may need coverage:

- Migration from cart page to cart template
- Migration from checkout page to checkout template
- Permalink settings 
- Page accessible on frontend
- Template editor accessible for new templates and the template part
