### ISSUE TITLE
Empty Cart Inner Block: JS scripts of nested 3PD Blocks doesn't work

### ISSUE THREAD

**Issue by webaxones** [woocommerce/woocommerce-gutenberg-products-block#9864]
## Describe the bug

The **Empty Cart Inner Block** does not have any restrictions on the type of Blocks that can be nested inside it. This is different from the **Checkout Block** and the **Filled Cart Inner Block**, which have specific limitations on the allowed Blocks (i.e., we only allow Paragraph, Image, and Separator Blocks). This limitation was set in place to prevent the form from being broken and the experience from being compromised. 

But, we want the merchant to take advantage of the lack of limitation of the **Empty Cart Inner Block** to put there all kinds of content to boost sales. The issue is that when a 3PD extension's Block relies on JS scripts (e.g., a carousel), is nested within the **Empty Cart Inner Block** will not be displayed properly.

@webaxones reported the bug with some paid plugins (i.e., FacetWP, WP Grid Builder), but we can use any 3PD block that needs JS to work. I used [Carousel Slider Block for Gutenberg](https://wordpress.org/plugins/carousel-block/) in my testing.

> Note: I noticed that the required JS scripts were loaded, but the 3PD extension's Block wasn't working properly. I suspect that it's a loading order bug!

## To reproduce

1. Install an extension that offers a Block element requiring JS script(s) for proper display (e.g., [Carousel Slider Block for Gutenberg](https://wordpress.org/plugins/carousel-block/))
2. Create a new page, and add/configure the Block of the extension from the previous step
3. Check the page on the frontend. Make sure the Block is correctly displayed

<img width="650" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/14235870/931f9265-5963-419f-a67e-c0a73d1f7ccb">

4. Go to the editor page of the Cart Block
5. Switch the view to "Empty Cart" 
6. Add the 3PD Block of the extension from step 1 as a nested element
7. Save the changes, and check the Cart Block on the frontend. Empty your cart if necessary. Make sure 3PD extension's Block isn't correctly displayed

<img width="650" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/14235870/b48e7383-f79d-4083-9f96-810ceacc8f8e">

## Expected behavior

Blocks that require JS to function properly, should keep on working when they are nested within the Empty Cart Block

## Screenshots

| Current | Expected |
| -------- | --------- |
| <img width="650" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/14235870/b48e7383-f79d-4083-9f96-810ceacc8f8e"> | <img width="650" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/14235870/931f9265-5963-419f-a67e-c0a73d1f7ccb"> |

### WordPress (please complete the following information):

-   WordPress version: 6.2
-   WooCommerce version: 7.8
-   WooCommerce Blocks version: 10.6.0
-   Site language: English (US)

### Desktop (please complete the following information):

-   OS: macOS
-   Browser chrome
-   Version 114

## Additional context

You can test using the WP Grid Builder Grid Block paid extension, using the test website provided by @webaxones:

https://wcblockscart.instawp.xyz/cart/
WP Grid Builder Grid Block inside empty Cart : doesn't work

https://wcblockscart.instawp.xyz/normal-page/
WP Grid Builder Grid Block inside empty Page : work

Admin Access:
p1689003120166289/1688733473.489909-slack-C8X6Q7XQU

**Comment by nielslange** [comment]
Thanks for reaching out, @webaxones. 

> I think you should filter the allowed nested blocks that can be used within the Cart block (and probably Checkout as well). I tried to insert a product grid block created from an extension like FacetWP or WP Grid Builder, and the append action performed by the Cart block during page load caused the JavaScript of the third-party extension's grid to crash.
Maybe just allow Blocks without front JS script.

While we can control which inner blocks are allowed, we cannot avoid that a merchant adds a block below the Cart or Checkout block. Wouldn't this lead to the same problem that you are currently facing?

I just looked up the extension that you mentioned, and it appears that both [FacetWP](https://facetwp.com/) and [WP Grid Builder](https://wpgridbuilder.com/) are paid extensions. To better understand this issue, can you tell me what you are trying to accomplish? Without having much context of the extensions, to me, it looks like they are are used for building the main shop page with filter. I wonder if the cart page is the right spot for showing a product grid, as this might distract shoppers, which could impact the conversation.

**Comment by webaxones** [comment]
I do use WP Grid Builder to display product grids.
However, I also use it to display CTA product sliders.
In this case, I would like to display a product slider when the cart is empty, like in this image:

![image](https://github.com/woocommerce/woocommerce-blocks/assets/17084006/487c2949-3f04-4577-8189-ef3e914ba83c)


This is where the management of the WC Blocks Cart Block conflicts with the JavaScript of the third-party extension.
As long as all the blocks appear to be usable within the cart block, I expect their functionality not to be disrupted :)
Personally, I will manage on my own, but you will undoubtedly encounter the same situation with other people.

In the image above, I managed by placing the Grid block below the cart block and hooking its display conditionally. I still need to handle the case of removing products via AJAX.
But ideally, being able to add an inner block that utilizes JS on the frontend inside Cart block (empty part) would be perfect.

**Comment by wavvves** [comment]
Hi @webaxones, can you post the JS console output if any, to evaluate the conflict between blocks and the grid extension's block?

**Comment by webaxones** [comment]
Hi @wavvves 

There was no error in the console.
Give me 2 minutes and I'll set up a demo instaWP.

**Comment by webaxones** [comment]
Done. So :
https://ycle-smash-zufo.instawp.xyz/cart/
WP Grid Builder Grid Block inside empty Cart : doesn't work

https://ycle-smash-zufo.instawp.xyz/normal-page/
WP Grid Builder Grid Block inside empty Page : work

Admin Access:
https://ycle-smash-zufo.instawp.xyz/wp-login.php
Id: sahamoyiho3806
Password: NpqwdIyYeBoz19Cx2jMb

As it's a free instaWP account, the website is on for 6 days :)

**Comment by webaxones** [comment]
It's doesn't seem to be a big bug: just the plugin tag that is displayed instead of keeping its HTML comments.

**Comment by webaxones** [comment]
Actually, the JS of WP Grid Builder seems to not be loaded or malfunctioning when the block is used within the cart block.

**Comment by webaxones** [comment]
Hi @wavvves 
Just to remind you that the site expires in 2 days. If you don't have time to watch by then, feel free to ask me to recreate one later :)

**Comment by tarunvijwani** [comment]
Thank you for sharing the test site. I have initiated the internal discussion around it. 
Internal discussion: p1688733473489909-slack-C8X6Q7XQU

**Comment by webaxones** [comment]
Thanks @tarunvijwani 
Since it was a temporary website, I just cloned it to a new one which won't expire:

> Credentials were moved to this internal discussion: p1689003120166289/1688733473.489909-slack-C8X6Q7XQU

Eventually, copy the credentials to your internal discussion then remove them from here to avoid someone to do bad things :D

**Comment by tarhi-saad** [comment]
Hello, @webaxones! 👋 Thank you for reporting this bug! 🙌 I was able to reproduce it. I also updated the ticket description!

**Comment by opr** [comment]
hi @webaxones, thanks again for a detailed report! I opened https://github.com/woocommerce/woocommerce-blocks/pull/10619 which ensures an event is correctly dispatched during the Empty Cart block render. This event can be used by scripts to run their events when the empty cart block renders its inner blocks.

I don't think we can make any changes that will fix these plugins without requiring intervention from their authors, due to the fact that the place they're trying to render in doesn't exist on page load (the cart block is mounted _after_ page load).

In the case of the slider plugin you linked, in the `blocks/carousel/view.js` file in there, you can see it tries to instantiate `slick` immediately on page load, it should wait until the element present on the page before doing that, see the testing instructions in https://github.com/woocommerce/woocommerce-blocks/pull/10619 to try it out for yourself in conjunction with the changes in #10619.

Cheers.

**Comment by webaxones** [comment]
Hi @opr 
Actually, my original post had been edited by someone from WooCommerce because the plugin I'm using is a premium plugin: WP Grid Builder. And I think it's better coded than the one you may have used for your tests.
I suspect you don't have time to look now, but in case you have 2 minutes, here is a site that shows the problem with this plugin: [the "normal" page displays the grid normally](https://wcblocksscripts.instawp.xyz/normal-page/), the [empty cart on the other hand breaks the code generated by the plugin](https://wcblocksscripts.instawp.xyz/cart/).

**Comment by opr** [comment]
> the plugin I'm using is a premium plugin: WP Grid Builder. And I think it's better coded than the one you may have used for your tests.

Do you have time/energy to look into the code for this plugin to see how it determines when to execute its scripts? The issue here is there is no clear signal that the empty cart block is mounted and its inner blocks are rendered.

As an example, the plugin _we_ used to test outputs some static HTML which is then "hydrated" for want of a better word when the page loads. Of course at this point the static HTML remains, but the JS code to set up the slider was executed before the HTML was output. I suspect the plugin you mentioned is also running into this issue but without looking at the code I can't say for sure.

**Comment by webaxones** [comment]
Unfortunately I don't have the time right now. It doesn't matter, I'll try to find a solution later with a timer.
Thanks for the help :)
