### ISSUE TITLE
Handle translations on Cart/Checkout and Order Confirmation templates

### ISSUE THREAD

**Issue by wavvves** [woocommerce/woocommerce-gutenberg-products-block#9865]
Part of Epic: Cart/Checkout/Order Received Templates #9288

[Originating comment from code review](https://github.com/woocommerce/woocommerce-blocks/pull/9301#discussion_r1211512555)

Template boilerplate code contains strings that need localization eg "You may be interested in…" on Cart template

There is a solution outlined for this:
>Typically this is handled by putting this into a block pattern (which can be [either dynamically loaded via PHP file](https://github.com/woocommerce/woocommerce-blocks/tree/trunk/patterns) - which is automatically handled by our loader system), or dynamically registered via PHP to include localized strings. Then you just put the pattern syntax in the .html template file. You'll just want to make sure the pattern is configured to not show up in the inserter.
This is how the default block themes (eg Twenty Twenty Three) handle default content that needs localized.

**Comment by nielslange** [comment]
As for the outlined solution, on https://github.com/woocommerce/woocommerce-blocks/pull/6248/files an example implementation of @dinhtungdu can be found.

**Comment by wavvves** [comment]
Closing this as there is nothing to be addressed on Checkout and Order Confirmation templates after #9883
