### ISSUE TITLE
WooCommerce Blocks Feedback

### ISSUE THREAD

**Issue by karenhowell** [woocommerce/woocommerce-gutenberg-products-block#9872]
## What do you like about the Cart & Checkout blocks?

I like the modern checkout page.

## What do you think is missing from the Cart & Checkout blocks?

I would love to see a fix for the ConvertKit integration on the checkout page. Using WooCommerce Blocks, the integration doesn't work.  So we need a workaround to add custom fields for better flexibility.

**Comment by nielslange** [comment]
Thanks for reaching out, @karenhowell. Great to hear that you like the modern checkout page. 

As for your request, can you provide additional information about ConvertKit? What is the purpose of this extension and how does it integrate into the classic checkout?

**Comment by karenhowell** [comment]
Thanks @nielslange the plugin helps connect and subscribe customers to ConvertKit. I notice that with WooCommerce Blocks, the ability to ask people to sign up at the checkout page doesn't work. There is a screenshot of the original integration here: https://wordpress.org/plugins/convertkit-for-woocommerce/ that allows for a checkbox to be displayed asking if the person would like to join the newsletter. I would love it if that could be included with WooCommerce Blocks.

**Comment by nielslange** [comment]
Thanks for providing the additional context, @karenhowell. 

>  I would love it if that could be included with WooCommerce Blocks.

We're cautious about which features to add to the WooCommerce Blocks. It's fine to integrate a feature, if every user benefits from it.

In this case, it would be up to the developer of ConvertKit to make their plugin compatible to WooCommerce Blocks. I suggest that you reach out to them directly, to inform them that their plugin is currently not compatible. If you reach out to them, you can point them to the following resources:

- [Create a basic block](https://developer.wordpress.org/block-editor/how-to-guides/block-tutorial/writing-your-first-block-type/)
- [@wordpress/create-block](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-create-block/) → `npm` package for creating a basic block
- [@woocommerce/extend-cart-checkout-block](https://www.npmjs.com/package/@woocommerce/extend-cart-checkout-block) → `npm` package for creating an extension for WooCommerce Blocks

As there are no actions items for us in this case, I'll close this issue. But please don't hesitate to contact us again and create a new issue f you have additional questions or suggestions.
