### ISSUE TITLE
Product Gallery block: Add setting to control the appearance of the thumbnail images

### ISSUE THREAD

**Issue by thealexandrelara** [woocommerce/woocommerce-gutenberg-products-block#9897]
### Description
The Product Gallery block is expected to have a setting to control the appearance of the thumbnail images. 

### Outcomes
New setting:
- Thumbnails setting in the Inspector Controls

### Acceptance criteria
- The setting appears in the Inspector Controls inside a section called Thumbnails
- The setting contains 4 options that can be selected: 
  - No thumbnails will be displayed.
  - A strip of small images will appear to the left of the main gallery image.
  - A strip of small images will appear below the main gallery image.
  - A strip of small images will appear to the right of the main gallery image.
- When selecting an option, the change should immediately be reflect on the Editor
- When selecting an option and saving the post/page/template, the change should be reflected on the frontend

**Comment by danieldudzic** [comment]
This has been added via https://github.com/woocommerce/woocommerce-blocks/pull/10442
