### ISSUE TITLE
Product Gallery block: Add setting to allow zoom while hovering the Large Image block

### ISSUE THREAD

**Issue by thealexandrelara** [woocommerce/woocommerce-gutenberg-products-block#9904]
### Description
The Product Gallery block is expected to have a setting to allow zoom while hovering the Large Image block

### Outcomes
New setting:
- Zoom while hovering setting in the Inspector Controls

### Acceptance criteria
- The setting appears in the Inspector Controls inside a section called Media Settings
- The setting must be a toggle button
- When enabled and hovering the Large Image block it must zoom in by 30%
- When disabled and hovering the Large Image block it must not zoom in the image
- When selecting an option and saving the post/page/template, the change should be reflected on the frontend

**Comment by Marc-pi** [comment]
yep, that's a need :-)
