### ISSUE TITLE
Expected null or Object but is Array on StoreAPI Product Categories 

### ISSUE THREAD

**Issue by whywilson** [woocommerce/woocommerce-gutenberg-products-block#9908]
## Describe the bug
The return image of product categories should be null or object, but on some categories, it is an empty array.
The same issues happened on the image of `/wp-json/wc/store/products/categories` request.

## To reproduce

1. Access the [product category](https://www.boslla.com/wp-json/wc/store/products/categories/233) with wp-json.
2. Get the JSON content.

```
{
  "id": 233,
  "name": "Product Name",
  "slug": "product-name",
  "description": "Product description",
  "parent": 28,
  "count": 2,
  "image": [],   // not null or object, but array
  "review_count": 44,
  "permalink": ""
}
```

## Expected behavior

Expected the image to be null or object.

### WordPress

Core version: 6.2.2
WooCommerce version: 7.8.0

**Comment by Aljullu** [comment]
Thanks for opening this issue, @whywilson! Could you diagnose in which cases it happens? I wasn't able to reproduce, unfortunately.

For reference, the image property is generated here:

https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/StoreApi/Schemas/V1/ProductCategorySchema.php#L88

Looking forward to your reply!

**Comment by whywilson** [comment]
> Thanks for opening this issue, @whywilson! Could you diagnose in which cases it happens? I wasn't able to reproduce, unfortunately.
> 
> 
> 
> For reference, the image property is generated here:
> 
> 
> 
> https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/StoreApi/Schemas/V1/ProductCategorySchema.php#L88
> 
> 
> 
> Looking forward to your reply!

Hi there,
I cannot reproduce the issues, but it happened on some specific categories.
[All categories link](https://www.boslla.com/wp-json/wc/store/products/categories)
And search `"image":[]` to find more.

**Comment by Aljullu** [comment]
Thanks, @whywilson! I'm going to add this to our backlog so we can investigate it further.
