### ISSUE TITLE
Checkout Дуже багато полів , і немає змоги їх прибрати

### ISSUE THREAD

**Issue by Tinitun007** [woocommerce/woocommerce-gutenberg-products-block#9918]
## What do you think is missing from the Cart & Checkout blocks?

```[tasklist]
### Tasks
```

**Comment by Tinitun007** [comment]
В Адресе доставки  багато полів які немає змоги прибрати

**Comment by nielslange** [comment]
Thanks for reaching out, @Tinitun007. 

> В Адресе доставки багато полів які немає змоги прибрати

I translated your message to _"There are many fields in the Delivery address that cannot be removed"_. To better understand the issue you're facing, can you tell me which fields you'd expect to see respectively which fields to hide?

**Comment by tarunvijwani** [comment]
@Tinitun007 I’m going to close this because there still isn’t anything actionable for us on this issue. If/when you have additional details, you can still add them to this issue, and if we’re able to reproduce, we can re-open as necessary.

**Comment by Tinitun007** [comment]
Доброго дня .
треба зробити щоб їх можливо було вмикати і вимикати 
Адреса
Поштовий код
Місто
Країна регіон
Штат округ
бо як ставиш плагін кур'єрська доставка , то потрібно одне і теж вводити по два разию 
Дякую

**Comment by tarhi-saad** [comment]
Hello, @Tinitun007! 👋 Thank you for bringing this to our attention! 🙌 If I understand correctly, you're looking for the ability to toggle on/off individual fields in the shipping/billing address. However, this functionality is not currently available in the Block-based checkout. The fields are standardized, and customizing them individually is not supported.

We know about this request, which is on our roadmap for future enhancements. However, I must inform you that we have yet to set a specific timeline for its implementation.

To consolidate the related discussions and track progress more effectively, I will close this issue in favor of woocommerce/woocommerce#42496, which addresses this feature request.

Thank you for your understanding and for bringing this to our attention. If you have any further questions or concerns, please don't hesitate to let us know.

**Comment by Tinitun007** [comment]
> 



> Привіт,@Tinitun007!👋Дякуємо, що звернули на це нашу увагу!🙌Якщо я правильно розумію, ви шукаєте можливість увімкнути/вимкнути окремі поля в адресі доставки/платіжної адреси. Однак ця функція наразі недоступна в блоці. Поля стандартизовані, їх індивідуальне налаштування не підтримується.
> 
> Ми знаємо про цей запит, який є в нашій дорожній карті для майбутніх покращень. Проте я маю повідомити, що ми ще маємо визначити конкретні терміни його реалізації.
> 
> Щоб консолідувати пов’язані обговорення та ефективніше відстежувати прогрес, я закрию цю проблему на користь #8005 , яка відповідає цьому запиту щодо функції.
> 
> Дякуємо за розуміння та звернули на це увагу. Якщо у вас виникнуть додаткові запитання чи занепокоєння, будь ласка, не соромтеся повідомити нас.

Якщо воно не буде працювати належним чином ,то Я змушений буду видалити WordPress .
Я не програміст , перепробував всі плагіни нічого не працю , а тому воно для мене немає ніякої цінності

**Comment by Tinitun007** [comment]
> Привіт,@Tinitun007!👋Дякуємо, що звернули на цю нашу увагу!🙌Якщо я правильно розумію, ви шукаєте можливість увімкнути/вимкнути окремі поля в адресі доставки/платіжної адреси. Однак ця функція наразі недоступна в блоках. Поля стандартизовані, їх індивідуальні налаштування не підтримуються.
> 
> Ми знаємо про цей запит, який є в нашій дорожній карті для майбутніх покращень. Проте я маю повідомити, що ми ще маємо застосувати конкретні терміни його реалізації.
> 
> Щоб консолідувати пов'язані обговорення та ефективніше відслідковувати прогрес, я виявляю цю проблему на досягненні woocommerce/woocommerce#42496 , яка відповідає цьому запиту щодо функції.
> 
> Дякуємо за розуміння та звернули на цю увагу. Якщо у вас виникнуть додаткові запитання чи непокоєння, будь ласка, не соромтеся повідомити нам.

Треба налагодити код 
зроблю це 
хоча Я не програміст

**Comment by tarhi-saad** [comment]
Hi, @Tinitun007! 👋 Did you try using the shortcode version of the cart and checkout? We have a plugin called [Checkout Field Editor](https://woocommerce.com/products/woocommerce-checkout-field-editor/) that optimizes the checkout process by adding, removing, or editing fields to suit your needs. Here is a link to [its documentation](https://woocommerce.com/document/checkout-field-editor/)! 🙌 It works only for the shortcode version of the checkout.

**Comment by Tinitun007** [comment]
> 

Зараз спробую
