### ISSUE TITLE
Pictures dont display for "Newest Products" when cart is empty 

### ISSUE THREAD

**Issue by UhtredofBamburgh** [woocommerce/woocommerce-gutenberg-products-block#9923]

**Comment by UhtredofBamburgh** [comment]
<img width="1114" alt="Screen Shot 2023-06-20 at 10 58 42 AM" src="https://github.com/woocommerce/woocommerce-blocks/assets/129151419/9747077f-0eba-4e37-b67d-6287ffb14230">
<img width="1020" alt="Screen Shot 2023-06-20 at 10 58 56 AM" src="https://github.com/woocommerce/woocommerce-blocks/assets/129151419/37088c55-bde8-4609-8110-f27a7e430bc9">

**Comment by Aljullu** [comment]
@UhtredofBamburgh thanks for opening this issue!

Unfortunately, I'm not able to reproduce on my end. Can you check if you see any errors in the _Console_ or _Network_ tabs of your browser devtools? You can open them with <kbd>F12</kbd> and then reload the page.

Thanks in advance!
