### ISSUE TITLE
If the blockified product template is enabled the variation image doesn't reflect the selected variation

### ISSUE THREAD

**Issue by tomxygen** [woocommerce/woocommerce-gutenberg-products-block#9938]
## Describe the bug

If the blockified product template is enabled, and each product variation has its own product image, when switching variation the image doesn't reflect the selected variation.

## To reproduce

1. enable the blockified product template
2. create a variable product
3. set one product image for each variation
4. save the product
5. go to the product page and select one of the variation.

## Expected behavior

The product image should change depending on the selected variation.

**Comment by Aljullu** [comment]
Thanks for opening this issue, @tomxygen! I was able to reproduce.

Classic template | Blockified template
--- | ---
![imatge](https://github.com/woocommerce/woocommerce-blocks/assets/3616980/37314311-ccf7-4ef3-9a7f-14ea74e6f4dc) | ![imatge](https://github.com/woocommerce/woocommerce-blocks/assets/3616980/55d99688-1f78-4c98-928d-b8a94be097f3)

cc @gigitux @thealexandrelara for awareness.

**Comment by tomxygen** [comment]
@Aljullu @thealexandrelara any eta for the fix?
I'm building a store and have to decide whether to use blocks or not.

**Comment by thealexandrelara** [comment]
> @Aljullu @thealexandrelara any eta for the fix? I'm building a store and have to decide whether to use blocks or not.

Hey there @tomxygen, we've started investigating this issue and we are going to start working on a fix soon. However, we don't have an ETA at the moment, but we'll keep you updated with any progress. 

Thank you for reporting this issue and for your patience!

**Comment by thealexandrelara** [comment]
@tomxygen  Just an update regarding this issue: it has been fixed in #9986 and will be included inWooCommerce 7.9 release. Thank you once again for reporting this issue! 🤝
