### ISSUE TITLE
Product Gallery block: Add full-screen gallery

### ISSUE THREAD

**Issue by thealexandrelara** [woocommerce/woocommerce-gutenberg-products-block#9942]
## Description
The Product Gallery block contains a full-screen gallery that is opened when the shopper clicks on the Large Image block.

## Outcomes

- Full-screen gallery opens when the shopper clicks on the Large Image block

## Acceptance criteria
- When clicking the Large Image block, the full-screen gallery should appear
- The full-screen gallery should contain Previous and Next buttons
- The full-screen gallery should contain the product title at the top
- The full-screen gallery should contain a close button to the top right
- The full-screen gallery should contain the thumbnails for images and videos of the product
- The thumbnail images should be inside a section called Images
- The thumbnail videos should be inside a section called Videos

**Comment by Marc-pi** [comment]
don't forget an option to toggle off the feature :-) (open the full screen gallery on click)

**Comment by gigitux** [comment]
> don't forget an option to toggle off the feature :-) (open the full screen gallery on click)

Thanks for the feedback! Yes, there will be an option to toggle off the feature!
