### ISSUE TITLE
Product image gallery overflow (?) to the next one

### ISSUE THREAD

**Issue by tomxygen** [woocommerce/woocommerce-gutenberg-products-block#9944]
## Describe the bug

when the blockified single product template is turned on, depending on the column width, the second image may overflow into the first one.
<img width="863" alt="Screenshot 2023-06-21 at 7 19 56 PM" src="https://github.com/woocommerce/woocommerce-blocks/assets/47855768/b48fe0a7-5c7f-435d-8273-7d9b0ee10e0b">

I managed to fix the issue by setting the column width of the product image to 40%

<img width="1440" alt="Screenshot 2023-06-21 at 7 22 33 PM" src="https://github.com/woocommerce/woocommerce-blocks/assets/47855768/9824f801-2df9-4a81-be87-26fbe9b3a3f0">

<img width="773" alt="Screenshot 2023-06-21 at 7 21 02 PM" src="https://github.com/woocommerce/woocommerce-blocks/assets/47855768/30ced038-4aad-4d88-ac73-0dde07ab1236">

## To reproduce

1. enable the blockified product template
2. create a new product 
3. set a cover image and gallery images

## Expected behavior

Every photo should stay in its own slide.

This behavior may depend on the image size, but it's never mentioned how big the images should be.

**Comment by Aljullu** [comment]
Hi there, @tomxygen, thanks for opening this issue! I tried with several different image sizes and aspect ratios, but I wasn't able to reproduce. Could you share which image sizes did you use?

**Comment by tomxygen** [comment]
Hey @Aljullu, try with 500x500px.

**Comment by Aljullu** [comment]
I tried again with a 500x500px image, but I wasn't able to reproduce either. :confused: @thealexandrelara @gigitux can any of you two try to reproduce it?

**Comment by gigitux** [comment]
Hey @tomxygen, thanks for opening the issue.
I'm not able to replicate it. Could you send some images to reproduce the issue?

**Comment by thealexandrelara** [comment]
Hey @tomxygen, thank you for reporting this.

> I tried again with a 500x500px image, but I wasn't able to reproduce either. 😕 @thealexandrelara @gigitux can any of you two try to reproduce it?

I was able to reproduce it in Google Chrome by using an image 512 x 640 pixels.

#### Steps to reproduce

1. Log in to your WordPress dashboard.
2. Navigate to the "Products" tab in the left-hand sidebar and click on "All Products."
3. Locate and select the product you want to edit from the list of existing products.
4. Scroll down to the "Product Image" section. If the product already has a primary image, you can replace it by clicking on the "Set product image" link. If there is no existing image, you will see an "Add product image" button instead.
5. You'll be presented with options to upload an image. `Select an image with size 512 x 640 pixels`. Click on the "Set product image" button to confirm.
6. To add additional images to the product gallery, scroll down further to the "Product Gallery" section. Click on the "Add product gallery images" link.
7.  Follow Step 5 to upload or select the additional images for the product. You can use the same image used in step 5.
8. Click on the "Update" button to save your changes.
9. From your WordPress dashboard, go to Appearance > Themes. Make sure you have a block-based theme installed and activated. If not, you can install one from the Add New option. Block-based themes include "Twenty-twenty Two," "Twenty-twenty Three," etc.
10. On the left-hand side menu, click on Appearance > Editor. This will open the Site Editor.
11. On the left-hand side menu, click on Templates. This will open the list of available templates.
12. Find and select the 'Single Product' template from the list.
13. When the Classic Product Template renders, click on Transform into Blocks. This will transform the Classic template in a block template if you haven't done it before.
14. On the top-right side, click on the Save button.
15. Visit the product that you edited the image and check if the error occurs

**Comment by tomxygen** [comment]
hey @gigitux @Aljullu @thealexandrelara I've tested it again creating a brand new website and with more image sizes.
400x400 makes it very noticeable.
The linked PR #10013 fixes the issue.

**Comment by gigitux** [comment]
@tomxygen The patch will land on WC 7.9 🚀 Thanks for opening the issue!
