### ISSUE TITLE
Handpicked product block: enhance functionality align left/right 1-column 1-product

### ISSUE THREAD

**Issue by opicron** [woocommerce/woocommerce-gutenberg-products-block#995]
**Is your feature request related to a problem? Please describe.**
I am all for enjoying freedom in setting up gutenberg content. I believe the current iteration of the handpicked product block could be improved significantly with an small improvement. 

If the block could be aligned left/right when 1-column and 1-product is selected it could open up a lot of design/content opportunities. See this the following for the result with some tweaking on my install:

site:
https://www.tseportal.site/2019/09/25/de-sirui-ph-30-in-de-praktijk/

image:
https://i.imgur.com/j6Yl8ae.png

**Describe the solution you'd like**
Add an align left/right button on the block when 1-column and 1-product is selected.

**Describe alternatives you've considered**
I have tinkered with the idea of an single product block. But it would be much more efficient to have the alignment integrated in the handpicked product(s) block.

Looking forward to your thoughts.

ps: this is also posted on the wordpress plugin page: 
https://wordpress.org/support/topic/handpicked-product-block-enhance-functionality-align-left-right-1-column/

**Comment by nerrad** [comment]
Currently on our roadmap (but no ETA) we are planning on migrating the existing blocks (including Handpicked product block) to use product element and inner blocks which allow for finer control over how content is rendered (which will resolve this and other issues). With this in mind, to limit the surface area involved with that kind of migration we are not adding additional controls to the existing blocks. We've definitely heard the request for this feature and it has been considered for future iterations of the blocks but it won't be implemented as described in this issue so I'm closing it.

Thanks for leaving your request!
