### ISSUE TITLE
Hide Coupon if the Cart Total is $0.00

### ISSUE THREAD

**Issue by adrianlbs** [woocommerce/woocommerce-gutenberg-products-block#9956]
## Is your feature request related to a problem? Please describe.
Not sure if it's a bug or a feature, or just a use case, but we'd like to have the coupon field removed/hidden if the cart total is $0.00. 

## Describe the solution you'd like
We could have an option at the block level to hide it if the total is zero.  

## Describe alternatives you've considered
Custom solution.

## Additional context
At WooCommerce.com, we sell lots of "Free" products. Users often check out with a $0.00 total. We'd like to be able to tailor this "free purchase" experience by removing redundancies.

**Comment by nielslange** [comment]
Thanks for reaching out, @adrianlbs. I'd say, hiding the coupon field, when the cart totals are $0.00 makes sense. I'll move his issue to our backlog and label it accordingly.

**Comment by ralucaStan** [comment]
<img width="850" alt="Screenshot 2023-07-19 at 17 21 36" src="https://github.com/woocommerce/woocommerce-blocks/assets/1628454/1d29486f-0889-4862-9231-3a5d49738d90">
Looks like the checkout shortcode is also showing the coupon code.

**Comment by mikejolley** [comment]
Coupons could also be utilised to make shipping free, or add custom functionality such as free gifts FYI, so basing on subtotal might not work for everyone.

**Comment by ralucaStan** [comment]
Based on Mike's comment, thank you Mike, I'm going to close this ticket for now. We might revisit this in the future if we receive extra requests for this. 

Thank you again @adrianlbs for reaching out.
