### ISSUE TITLE
All Products Block saving data attributes in HTML

### ISSUE THREAD

**Issue by roykho** [woocommerce/woocommerce-gutenberg-products-block#9961]
The `All Products` block currently saves the attributes data into the HTML seen here https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/blocks/products/all-products/save.js#L27

Since these attributes data is already handled by Gutenberg we don't need to do that. This issue is to remove those as seen done in https://github.com/woocommerce/woocommerce-blocks/pull/9833

**Comment by hritikchaudhary** [comment]
Hi @roykho I'd like to work on it... I went through #9833 
To resolve this issue do we only have to remove the `{ ...data }` ?
I didn't understand why we added [deprecated.tsx](https://github.com/woocommerce/woocommerce-blocks/pull/9833/files#diff-1716ac9e92cebbc7c6bfcd14c12ec73600e75b4929eea467912faed0d42152f6)

**Comment by roykho** [comment]
Hi @hritikchaudhary - Sure! Thanks for offering to help with this. I've assigned you.

> I didn't understand why we added [deprecated.tsx](https://github.com/woocommerce/woocommerce-blocks/pull/9833/files#diff-1716ac9e92cebbc7c6bfcd14c12ec73600e75b4929eea467912faed0d42152f6)

Because if you don't deprecate, existing blocks will get block validation errors.

**Comment by hritikchaudhary** [comment]
@roykho one small help please... 
the deprecation part in #9833 is for filter count display toggle.. the scope of this issue is limited to removing `{ ...data } `
from html
Is my understanding correct?

**Comment by roykho** [comment]
> the deprecation part in https://github.com/woocommerce/woocommerce-blocks/pull/9833 is for filter count display toggle.. the scope of this issue is limited to removing { ...data } 
from html
Is my understanding correct?

Yes that is correct.

**Comment by hritikchaudhary** [comment]
Hi @roykho  I have raised #10032 to fix this..
Please let me know if any change is needed.
