### ISSUE TITLE
Mixed content errors in console

### ISSUE THREAD

**Issue by bradhogan** [woocommerce/woocommerce-gutenberg-products-block#9966]
## Describe the bug

Getting a list of mixed content errors with the Woo Blocks plugin trying to load certain resources with http when it should be forced to https.  [See console here](https://utahstories.com/).

<img width="1207" alt="Screen Shot 2023-06-22 at 10 11 54 AM" src="https://github.com/woocommerce/woocommerce-blocks/assets/1781226/e29fa312-d1a1-4e30-bfde-ce335ab44fba">

Thank you!

**Comment by nielslange** [comment]
Thanks for reaching out, @bradhogan. On https://utahstories.com/, I can no longer see the mixed content errors that you mentioned. That said, we released a new version of WooCommerce Blocks two days ago. Is it possible that your site has been updated since you created this issue?

**Comment by bradhogan** [comment]
@nielslange I reset the cache and that seems to have fixed it.  Not sure why it was only protocol references from this plugin but either way, working now.

**Comment by nielslange** [comment]
I'm glad to hear that resetting the cache solved the issue on your end.
