### ISSUE TITLE
Product Collection - mobile view columns configuration

### ISSUE THREAD

**Issue by kmanijak** [woocommerce/woocommerce-gutenberg-products-block#9971]
### Description

Currently, Product Collection has a "Columns" control that takes effect only on desktop. On mobile there's fixed 1-column view.

### Goal

Add an option to configure a number of columns in the mobile view for Product Collection. The final "shape" of the configuration is to be defined (ref: pdnLyh-3uF-p2#comment-2637). This issue may include spike around how to make block configuration between viewports easier.

**Comment by tomxygen** [comment]
Hi! 
I'm very interested in this issue but it hasn't gotten any attention yet.
Is there any update?

**Comment by imanish003** [comment]
Hi @tomxygen,

Apologies for the delay in getting back to you. I wanted to let you know that we've decided to address this particular issue as part of #10827. You're more than welcome to keep an eye on that issue by subscribing to it. We anticipate that the work on it will commence in the next 1-2 weeks.

Thank you for your understanding and patience. If you have any more questions or suggestions, please don't hesitate to share them with us. Your contributions are highly appreciated! 🙏🏻
