### ISSUE TITLE
Change Product Search block primary action

### ISSUE THREAD

**Issue by jwold** [woocommerce/woocommerce-gutenberg-products-block#998]
On the Product Search block we currently have a chevron icon which indicates a primary action for searching. That was chosen in order to move the block forward, since an actual button element was a technical blocker at the time. Raising this issue to revisit and change to a button. 

Based on feedback from @nerrad, another issue (https://github.com/WordPress/gutenberg/issues/7604) indicates transforming in block markup could be a challenge. 

Screenshot of current interface:
![Screen Shot 2019-09-27 at 1.15.58 PM.png](https://images.zenhubusercontent.com/56fb18016caf56c9d38eea1d/55ad6c07-0879-4fd6-aa8a-fd814c294555)

**Comment by haszari** [comment]
@nerrad - Can you clarify what the goal is here? Is the idea to change the component used for the search button, or something else?

I'm assuming the `transforming in block markup could be a challenge` refers to the fact that we'd need to add `deprecated` to the block config so there aren't validation errors in editor (or however it's handled now - haven't considered block validation issues for a while!).

**Comment by nerrad** [comment]
The goal is in the first paragraph:

> On the Product Search block we currently have a chevron icon which indicates a primary action for searching. That was chosen in order to move the block forward, since an actual button element was a technical blocker at the time. Raising this issue to revisit and change to a button.

If your question is more about “why?”, I don’t know the answer - I didn’t create the issue :) (and I can’t remember the conversation around this).

Maybe it would be more a11n friendly if the action was a button? 

I’m okay with closing this issue if there’s no apparent need to make the change.

> I'm assuming the transforming in block markup could be a challenge refers to the fact that we'd need to add deprecated to the block config so there aren't validation errors in editor (or however it's handled now - haven't considered block validation issues for a while!).

Correct!

**Comment by haszari** [comment]
Ok - maybe close? If there's a problem it'll come back up and we could reopen. Or could see if @LevinMedia (or @jwold !?) has more info. Happy either way, I was looking for low-hanging-fruit bugs, and this doesn't qualify for me :)

**Comment by nerrad** [comment]
Ya let’s close
