### ISSUE TITLE
Cart block: slow when switching between shipping rates

### ISSUE THREAD

**Issue by webaxones** [woocommerce/woocommerce-gutenberg-products-block#9983]
There might be something to improve on the shopping cart block's shipping rates:

I've noticed a slowdown on a project currently under development on a local computer. I reproduce this lag on an InstaWP installation with just WooCommerce, WooCommerce Blocks, and the 2023 theme, and you can see a video demo of it. 

https://github.com/woocommerce/woocommerce-blocks/assets/17084006/7f16daee-5678-47a5-9a3e-d3d7987be351

When changing shipping rates, the label takes 2 seconds to update. I understand that a REST call is necessary to update the shipping fee calculations, but something visual is missing to indicate that a process is underway, as was the case with a classic WooCommerce. (second video). (The REST request is still slower than the processing on a classic cart, but a visual element would perhaps make it acceptable).

https://github.com/woocommerce/woocommerce-blocks/assets/17084006/323a5202-0295-4d28-b79b-7d09a62c27ba

**Comment by wavvves** [comment]
Hi @webaxones, thank you for reporting this, indeed this would be an UX improvement.

@shaunandrews, what do you think about an optimistic approach, where we would update the UI instantly and then again once we get the REST response vs the visual cue that it is waiting for something?

**Comment by ralucaStan** [comment]
One approach we could start with is to disable the inputs while the call is made,  while also hiding the text under shipping title. 
When the call is successfully done we reenable the inputs and display the changed text.
If the call was not successful we will reset to the initial selection.

**Comment by nerrad** [comment]
> (The REST request is still slower than the processing on a classic cart, but a visual element would perhaps make it acceptable).

Besides the visual cue improvements, it looks like this is an area for potential performance improvement. It'd be good to investigate:

- Is the REST request consistently slower than the classic cart on different environments?
- If yes, is there anything we can do to improve that?

**Comment by mikejolley** [comment]
I'm working on this but just to say quickly, the perceived performance is bad because the request is debounced 1000ms. We can remove this debounce for instant gains.
